### DISCUSSION TITLE
[Bug]: strimzi-cluster-operator keeps restarting with issue:  WARN  BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for

### DISCUSSION THREAD

**Discussion by vietnguyenmipro** [strimzi/strimzi-kafka-operator#10038] [General]
### Bug Description

strimzi-cluster-operator keeps restarting with issue:  WARN  BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for xxxx ms, time limit is 2000 ms io.vertx.core.VertxException: Thread blocked

### Steps to reproduce

1. Install strimzi-kafka-operator as dependency in a application helm chart: 

```
dependencies:
  - name: strimzi-kafka-operator
    version: "0.40.0"
    repository: "oci://quay.io/strimzi-helm"
```

3. In helm templates folders: create new cluster with this definition:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: myapp
spec:
  kafka:
    version: 3.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
    storage:
      type: persistent-claim
      class: {{ .Values.kafka.cluster.kafka.storage.class }}
      size: {{ .Values.kafka.cluster.kafka.storage.size }}
      deleteClaim: true
  zookeeper:
    livenessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 120
      timeoutSeconds: 5
    replicas: {{ .Values.kafka.cluster.zookeeper.replicas }}
    storage:
      type: persistent-claim
      class: {{ .Values.kafka.cluster.zookeeper.storage.class }}
      size: {{ .Values.kafka.cluster.zookeeper.storage.size }}
      deleteClaim: true
  entityOperator:
    template:
      topicOperatorContainer:
        env:
        - name: STRIMZI_USE_ZOOKEEPER_TOPIC_STORE
          value: "true"
    topicOperator: {}
    userOperator: {}
```

4. Install the app with its dependency: helm install
5. Strimzi-cluster-operator keeps retartings with log attached (I was trying my best to format it but it was so ugly), please find the attachment.

```
2024-04-29` 19:19:36 WARN  BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 128580 ms, time limit is 2000 ms io.vertx.core.VertxException: Thread blocked
        at jdk.internal.misc.Unsafe.park(Native Method) ~[?:?]

2024-04-29 19:19:37 ERROR AbstractOperator:284 - Reconciliation #1(watch) Kafka(forme/myapp): createOrUpdate failed io.fabric8.kubernetes.client.KubernetesClientException: Operation: [patch]  for kind: [Deployment]  with name: [myapp-entity-operator]  in namespace: [forme]  failed.
```
`

### Expected behavior

The strimzi-cluster-operator works without above issue.

### Strimzi version

0.40.0

### Kubernetes version

1,29

### Installation method

helm
