### DISCUSSION TITLE
Connecting to bootstrap server fails

### DISCUSSION THREAD

**Discussion by mokhos** [strimzi/strimzi-kafka-operator#10274] [General]
Hi,
I have an application which is trying to connect to a kafka instance through ingress listener. But I cannot get it to work and I don't know where exactly the problem is.
My app is throwing these errors:

```
Connection to node -1 (x-kafka-external-bootstrap.x.x.fg3.ffm/10.93.8.33:443) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.

2024-06-27 14:29:01.605 [scheduling-1] ERROR d.a.o.k.p.r.ConsumersResourcesVerifier - Exception during Kafka Probe

java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes

	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
```

when I enable debug-level: 

`Give up sending metadata request since no node is available`

Kafka config looks like this:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.namespace }}
  namespace: {{ .Values.namespace }} 
spec:
  kafka:
    version: 3.6.1
    replicas: 3 
    listeners:
...
...
      {{- if .Values.kafka.ingress.enabled }}
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
            type: tls
        configuration:
          class: nginx
          brokerCertChainAndKey:
            certificate: tls.crt
            key: tls.key
            secretName: {{ .Values.namespace }}-tls
          bootstrap:
            host: {{ .Values.namespace }}-kafka-external-bootstrap.str.{{ .Values.oscCluster }}.fg3.ffm
            annotations:
              argocd.argoproj.io/sync-wave: "-15"
              kubernetes.io/ingress.class: nginx
              cert-manager.io/issuer: gardener-issuer
              cert-manager.io/common-name: {{ .Values.namespace }}-kafka-external-bootstrap
              dns.gardener.cloud/dnsnames: {{ .Values.namespace }}-kafka-external-bootstrap.str.{{ .Values.oscCluster }}.fg3.ffm
              dns.gardener.cloud/ttl: "600"
              dns.gardener.cloud/class: garden
          brokers:
          - broker: 0
            host: {{ .Values.namespace }}-kafka-broker-0.str.{{ .Values.oscCluster }}.fg3.ffm
            annotations:
              cert-manager.io/issuer: gardener-issuer
              kubernetes.io/ingress.class: nginx
          - broker: 1
            host: {{ .Values.namespace }}-kafka-broker-1.str.{{ .Values.oscCluster }}.fg3.ffm
            annotations:
              cert-manager.io/issuer: gardener-issuer
              kubernetes.io/ingress.class: nginx
          - broker: 2
            host: {{ .Values.namespace }}-kafka-broker-2.str.{{ .Values.oscCluster }}.fg3.ffm
            annotations:
              cert-manager.io/issuer: gardener-issuer
              kubernetes.io/ingress.class: nginx
      {{- end }}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 1
      default.replication.factor: 3
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
...
...
```

I can do `telnet` and `openssl s_client -connect` to the ingress host and it is successful. 

Can anyone please give me a hint or something? 
Thanks in advance
