### DISCUSSION TITLE
How to Achieve HA with Replicas on Different Storage Classes in Strimzi Kafka Cluster on K8s?

### DISCUSSION THREAD

**Discussion by willyaako** [strimzi/strimzi-kafka-operator#10369] [Q&A] [answered]
Hello,

I would like to deploy a Kafka cluster on my Kubernetes (K8s) cluster. This K8s cluster has 3 storage classes for geo-redundancy. I have created 3 KafkaNodePools and specified the storage class names for each. Each node pool has created 3 brokers.

To achieve high availability (HA) for the topics, I would like to ask if it is possible to specify replicas to be placed on brokers with different storage classes when creating a topic.

Here is my YAML configuration:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {NODE-DC1} ~ {NODE-DC3}
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
        class: {DC1}~{DC3}
        kraftMetadata: shared
```

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.0
    metadataVersion: 3.7-IV4
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false

    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
```
