### DISCUSSION TITLE
Repair broker , zookeeper by scaling replicas ?

### DISCUSSION THREAD

**Discussion by jackchuong** [strimzi/strimzi-kafka-operator#10437] [Q&A] [answered]
Hi all,
I have deployed kafka and zookeeper using strimzi-operator 0.36 in self managed k8s cluster.
k8s cluster storage provider is nfs-subdir-external-provisioner , a QNAP device as NFS server.
This is yaml
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka
  namespace: kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      num.partitions: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.4.0"
      log.cleanup.policy: compact,delete
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: nfs-idcnas002
        size: 10Gi
        deleteClaim: true
    resources:
      requests:
        memory: 1Gi
        cpu: "0.5"
      limits:
        memory: 4Gi
        cpu: "2"
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - master
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: nfs-idcnas002
      size: 10Gi
      deleteClaim: true
    resources:
      requests:
        memory: 1Gi
        cpu: "0.5"
      limits:
        memory: 4Gi
        cpu: "2"
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: NotIn
                  values:
                  - master
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
Sometimes there is a problem with the folder attached to the pvc of 1 of the 3 broker or zookeeper nodes, which causes the data in it to be corrupted and 1 pod in the 3 pod statefulsets to be corrupted as well.

Can I fix it by this way : scale down replicas to 2 ,  remove pod and pvc , then scale up replicas to 3 again so new pod and pvc will run ok ?
I read this article [https://strimzi.io/blog/2024/01/03/prevent-broker-scale-down-if-containing-paritition-replicas/](url) but it only for broker and I have to upgrade strimzi operator and crd to 0.38
How about zookeeper ?
