### DISCUSSION TITLE
[MM2] Consumer Group offsets not updating after upgrading to 3.5.1+

### DISCUSSION THREAD

**Discussion by thartyhp** [strimzi/strimzi-kafka-operator#10461] [Q&A]
We've been running MM2 for years now in an actice/passive mode and it's generally been pretty stable. We noticed when we moved form 3.4.0 to 3.5.1 we started getting lag alerts on the passive cluster. We moved back to 3.4.0 and MM2 started working again as before. We then tried 3.6.1 and the same issue. Didn't seem to matter if it was the low traffic dev clusters or high traffic prod clusters.
 
Here's the snippet of config I think is most applicable.
 
```
    mirrors:
    - sourceCluster: mm2-${SOURCE_CLUSTER}
      targetCluster: mm2-${CLUSTER_ENV}
      sourceConnector:
        tasksMax: 5
        config:
          producer.override.batch.size: 327680
          replication.factor: 3
          offset-syncs.topic.replication.factor: 3
          sync.topic.acls.enabled: true
          replication.policy.class: org.apache.kafka.connect.mirror.IdentityReplicationPolicy
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 3
      checkpointConnector:
        tasksMax: 5
        config:
          checkpoints.topic.replication.factor: 3
          sync.group.offsets.enabled: "true"
          replication.policy.class: org.apache.kafka.connect.mirror.IdentityReplicationPolicy
```

We tried messing with sync.group.offsets.enabled.interval.seconds: 30 and refresh.groups.interval.seconds: 90, but that didn't seem to move the needle. We had considered offset.max.lag, but we already had groups with more than 100+ lag on the passive side. Is there something else we could be missing here config wise? Something that was deprecated or needed to be changed when moving from 3.4.0? Is this something that's been fixed in 3.6.2 or 3.7.1?
