### DISCUSSION TITLE
0.41 Stuck Upgrade

### DISCUSSION THREAD

**Discussion by thartyhp** [strimzi/strimzi-kafka-operator#10561] [General]
This started with an update from 0.40 to 0.41 on OCP (Kubernetes v1.27)
 
We had defined CPU settings as a decimal. (i.e. 0.5) And while that worked in previous versions, it appears there's a change that enforced using one of the other notations. So we updated the configs to use a different notation and applied the config.
 
After the change it still wouldn't install, and the install plan had the same error about incompatible setting. This is where we made a mistake. We did a lot of searching and there wasn't a lot on this kind of issue, so we asked AI, which suggested removing the installplan, and that the OLM would create a new one.
 
That turned out to be very false, now the subscription is unhappy the installplan is missing.
 
```  
conditions:
  - lastTransitionTime: "2024-08-01T14:19:29Z"
    message: all available catalogsources are healthy
    reason: AllCatalogSourcesHealthy
    status: "False"
    type: CatalogSourcesUnhealthy
  - reason: UnpackingInProgress
    status: "True"
    type: BundleUnpacking
  - message: 'constraints not satisfiable: clusterserviceversion strimzi-cluster-operator.v0.40.0
      exists and is not referenced by a subscription, @existing/systems-kafka//strimzi-cluster-operator.v0.40.0
      and @existing/systems-kafka//strimzi-cluster-operator.v0.41.0 originate
      from package strimzi-kafka-operator, subscription strimzi-kafka-operator requires
      @existing/systems-kafka//strimzi-cluster-operator.v0.41.0, subscription
      strimzi-kafka-operator exists'
    reason: ConstraintsNotSatisfiable
    status: "True"
    type: ResolutionFailed
  - lastTransitionTime: "2024-09-06T16:52:33Z"
    reason: ReferencedInstallPlanNotFound
    status: "True"
    type: InstallPlanMissing
```
 
Is there a way to get this unstuck to create a new installplan?
 
Was there a better way of correcting the stuck installplan once we had corrected the config?
