### DISCUSSION TITLE
Listener configuration is not valid

### DISCUSSION THREAD

**Discussion by haroon9** [strimzi/strimzi-kafka-operator#10589] [Q&A] [answered]
While increasing the replica size from 1 to 3 I faced the following issue:
`ERROR ListenersValidator:47 - Reconciliation #16864(timer) Kafka(kafka/kafka): Listener configuration is not valid: [listener ingress is missing a broker host name for broker with ID 4 which is required for Ingress based listeners, listener ingress is missing a broker host name for broker with ID 5 which is required for Ingress based listeners]`

This happens when I set the broker IDs like this:
```
  brokers:
    - broker: 0
      host: broker.0.dev.gridcert.ai
      annotations:
        kubernetes.io/ingress.class: nginx
    - broker: 1
      host: broker.1.dev.gridcert.ai
      annotations:
        kubernetes.io/ingress.class: nginx
    - broker: 2
      host: broker.2.dev.gridcert.ai
      annotations:
        kubernetes.io/ingress.class: nginx
```

But when I changed the IDs to 4 and 5 works fine.
```
  brokers:
    - broker: 0
      host: broker.0.dev.gridcert.ai
      annotations:
        kubernetes.io/ingress.class: nginx
    - broker: 4
      host: broker.1.dev.gridcert.ai
      annotations:
        kubernetes.io/ingress.class: nginx
    - broker: 5
      host: broker.2.dev.gridcert.ai
      annotations:
        kubernetes.io/ingress.class: nginx
```

Is there any misconfiguration on my part? As in the cluster, I do not have other brokers running with IDs 1 and 2.
