### DISCUSSION TITLE
Strimzi Operator CRDs out of sync with ArgoCD after upgrade from 0.42.0 to 0.43.0

### DISCUSSION THREAD

**Discussion by jslusher** [strimzi/strimzi-kafka-operator#10587] [Q&A] [answered]
We recently tried upgrading our strimzi operator and everything seemed to go fine with the upgrade itself, but now ArgoCD sees the CRDs as being out of sync because of what looks like an empty field called `required:`. See the screenshot below. Here is our kustomize configuration of the helm chart:

```
helmCharts:
- name: strimzi-kafka-operator
  namespace: strimzi-operator
  releaseName: strimzi-kafka-operator
  version: 0.43.0
  repo: https://strimzi.io/charts
  includeCRDs: true
  valuesInline:
    watchAnyNamespace: true

resources:
- 010-ClusterRole-strimzi-admin.yaml
- 020-ClusterRole-strimzi-view.yaml
```

![Screenshot 2024-09-13 at 4 12 01 PM](https://github.com/user-attachments/assets/bc096213-4e5e-4e2a-832c-76e658234219)
