### DISCUSSION TITLE
Strimzi should allow internal listener to configure brokers[].host

### DISCUSSION THREAD

**Discussion by L1ghtman2k** [strimzi/strimzi-kafka-operator#10593] [General]
### Bug Description

I am trying to provision strimzi based operator with istio. I understand that strimzi [doesn't support istio](https://github.com/orgs/strimzi/discussions/10449#discussioncomment-10336245), however, in my case, I have to work around this problem because I can only use istio in our environment. 

I was able to set-up istio gateway + vs working with strimzi kafka, however, I had to specify listener `type: ingress`, to allow kafka to configure something on a backend, to make it work with istio. If I try internal listener, get the following error:
```
Listener configuration is not valid: [listener external cannot configure
        brokers[].host because it is not Route or Ingress based listener, listener
        external cannot configure bootstrap.host because it is not Route or Ingress
        based listener]
``` 

Another byproduct of specifying `type: ingress`, is strimzi creates ingress objects, even though nginx is not on the cluster.

I would like an option that avoids spinning up custom resources, while also allowing external listeners to be exposed by projects other than ingress-nginx.

### Strimzi version

0.40.0

### Kubernetes version

1.29

### Installation method

Helm Chart

### Infrastructure

Bare-metal

**Comment by scholzj** [comment]
The `brokers[].host` field is used to specify the host in the Kubernetes Ingress or OPenShift Route resources. It does not make any sense to _allow_ it with internal listeners because it would not be used anywhere and would be just ignored anyway.

**Reply by L1ghtman2k** [reply]
I am not aware of anything else that it modifies or prevents from modifying, but  istio does not work without that setting. 

What would be a better way to approach this?

**Reply by scholzj** [reply]
I do not know Istio, so I will probably not be able to help much. You would need to find out what it is that you need to configure and than we can look into it. But the `host` field is used in the Ingress resource and if you don't need the Ingress resource, I don't think you need the `host` field.

**Reply by L1ghtman2k** [reply]
I don't think this is just about istio. I am not aware of many other solutions out there, perhaps traefik, Kong, Ambassador, but the issues is that none of them are usable without having to specify "ingress", and even with "ingress" option, it doesn't work without having ingress nginx on the cluster because otherwise it throws:
```
Exceeded timeout of 300000ms while waiting for Ingress resource kafka-kafka-bootstrap in namespace kafka to be addressable
``` 

Also, I don't think `brokers[].host` is only useful for Kubernetes Ingress or OPenShift Route resources. Wouldn't bootstrap use those endpoints to advertise to the external users?

I think an alternative entry to `ingress`, that removes the verifications like `brokers[].host` needing to be excluded, and that doesn't require creating additional resources would work to allow all other unsupported ingresses to work?

**Reply by scholzj** [reply]
> I don't think this is just about istio. 

You brought Istio into this, not me. I'm sorry, but it is really confusing to understand what are you trying to do. You start with Istio, then you say that it is not about Istio. 

> I am not aware of many other solutions out there, perhaps traefik, Kong, Ambassador, but the issues is that none of them are usable without having to specify "ingress", and even with "ingress" option, it doesn't work without having ingress nginx on the cluster because otherwise it throws:
> 
> ```
> Exceeded timeout of 300000ms while waiting for Ingress resource kafka-kafka-bootstrap in namespace kafka to be addressable
> ```

This happens when the Ingress controller doesn't update the status of the Ingress resource. Unfortunately, the Ingress controllers have a bad compatibility. So Strimzi has no way to say whether this is because you misconfigured it or because your Ingress controller doesn't do it. Strimzi is developed and tested with the Kubernetes Ingress controller based on Nginx. It might work with other ones or it might not and the reasons might differ (from unsupported features, different annotations and options, up to different handling of the status). I think this is documented in our docs, there is not much we can do about the fact that the compatibility is had other than hpe that it will work better with the Gateway API.

> Also, I don't think `brokers[].host` is only useful for Kubernetes Ingress or OPenShift Route resources. Wouldn't bootstrap use those endpoints to advertise to the external users?
> 
> I think an alternative entry to `ingress`, that removes the verifications like `brokers[].host` needing to be excluded, and that doesn't require creating additional resources would work to allow all other unsupported ingresses to work?

The field you keep talking about is used to configure the host addresses in Ingress and Route resources. They are used by them for TLS-SNI based routing of the connections. So once again, removing the validation would not change anything because they are not used for the pother listener types.

**Reply by L1ghtman2k** [reply]
How does bootstrap endpoint know how to advertise broker hostnames to the external clients, if `brokers[].host` is not specified?

**Reply by scholzj** [reply]
I have no idea what you think `bootstrap endpoint` is. Bootstrapping happens by just routing the connection to one of the brokers.

**Reply by L1ghtman2k** [reply]
I use the following:

<details>

```
import ssl
import logging
from kafka import KafkaAdminClient
from kafka.admin import NewTopic
from kafka.errors import KafkaError, TopicAlreadyExistsError

# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

# Kafka configuration
bootstrap_servers = ['kafka-bootstrap.some.domain:443']
username = 'superuser'
password = '<some-password>'
ca_cert_path = 'ca.pem'  # Path to your existing CA certificate file

# Debug: Print configuration
logger.debug(f"Bootstrap servers: {bootstrap_servers}")
logger.debug(f"Username: {username}")
logger.debug(f"CA Certificate path: {ca_cert_path}")

# Create SSL context with proper security settings
ssl_context = ssl.create_default_context(cafile=ca_cert_path)
ssl_context.check_hostname = True
ssl_context.verify_mode = ssl.CERT_REQUIRED

# Debug: Print SSL context information
logger.debug(f"SSL Context - Check hostname: {ssl_context.check_hostname}")
logger.debug(f"SSL Context - Verify mode: {ssl_context.verify_mode}")


logger.info("Attempting to create Kafka admin client...")
# Create Kafka admin client with SCRAM-SHA-512
admin_client = KafkaAdminClient(
    bootstrap_servers=bootstrap_servers,
    security_protocol='SASL_SSL',
    sasl_mechanism='SCRAM-SHA-512',
    sasl_plain_username=username,
    sasl_plain_password=password,
    ssl_context=ssl_context,
)
logger.info("Kafka admin client created successfully.")

# Debug: Print admin client configuration
logger.debug(f"Admin client config: {admin_client.config}")

# Create a new topic
topic_name = "test_topicdfdd"
logger.info(f"Attempting to create topic: {topic_name}")
new_topic = NewTopic(name=topic_name, num_partitions=1, replication_factor=1)
admin_client.create_topics([new_topic])
logger.info(f"Topic '{topic_name}' created successfully.")

# List all topics
logger.info("Listing all topics...")
topics = admin_client.list_topics()
logger.info(f"Available topics: {topics}")



logger.info("Script execution completed.")
```

</details>

My client figures out that it needs to reach out to one of the brokers by their public hostname, even though, i have not specified any of that in my code. My assumption is that the kafka-bootstrap endpoint returns the public address to the client, so that client can connect to it

**Reply by scholzj** [reply]
No, it connects to any of the Kafka brokers and it gives it the list of brokers There is no special _bootstrap endpoint_ (or at least I never heard or saw this term being used). But if you want to configure the advertised addresses, you can configure them using the advertised host / port options in the listener configuration. You do not need to change the Ingress or Route host for it.

**Reply by L1ghtman2k** [reply]
I see, I will try that, thank you!

**Comment by L1ghtman2k** [comment]
Thanks Jakub, I was able to setup istio with `cluster-ip`, by configuring `advertisedHost` & `advertisedPort`:
```
      - authentication:
          type: scram-sha-512
        configuration:
          brokerCertChainAndKey:
            certificate: certificate
            key: privateKey
            secretName: infra
          brokers:
          - advertisedHost: kafka-broker0.mydomain.net
            advertisedPort: 443
            broker: 0
        name: external
        port: 9094
        tls: true
        type: cluster-ip     
```

I then setup the istio gw:
```
  kind: Gateway
  metadata:
    annotations:
    name: kafka-gateway
    namespace: kafka
  spec:
    selector:
      istio: minio-ingressgateway
    servers:
    - hosts:
      - kafka-broker0.mydomain.net
      - kafka-bootstrap.mydomain.net
      port:
        name: https
        number: 443
        protocol: HTTPS
      tls:
        mode: PASSTHROUGH
```

and a virtualservice:

```
  kind: VirtualService
  metadata:
    annotations:
    name: kafka-ingress
    namespace: kafka
  spec:
    gateways:
    - kafka-gateway
    hosts:
    - kafka-bootstrap.mydomain.net
    - kafka-broker0.mydomain.net
    tls:
    - match:
      - port: 443
        sniHosts:
        - kafka-bootstrap.mydomain.net
      route:
      - destination:
          host: kafka-kafka-external-bootstrap
          port:
            number: 9094
    - match:
      - port: 443
        sniHosts:
        - kafka-broker0.mydomain.net
      route:
      - destination:
          host: kafka-kafka-0
          port:
            number: 9094

```
