### DISCUSSION TITLE
Is it possible to resize disk on individual brokers?

### DISCUSSION THREAD

**Discussion by jslusher** [strimzi/strimzi-kafka-operator#10618] [Q&A] [answered]
I'm not having much luck finding current information on how strimzi supports volume resizing. Based on [this blog post from 2019](https://strimzi.io/blog/2019/02/28/resizing-persistent-volumes/), it appears that the operator supports EBS resizing if it's enabled on the storageclass.

I have the following configured for storage on my cluster:

```
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 1500Gi
        deleteClaim: true
```

I have 9 brokers currently. We have some large single-partitioned topics that are making a few of the brokers more full than others. 

Is it possible to add storage to particular brokers or do I have to update all of them?
