### DISCUSSION TITLE
Should brokers restart after increasing EBS volume size on their data disks?

### DISCUSSION THREAD

**Discussion by jslusher** [strimzi/strimzi-kafka-operator#10629] [Q&A] [answered]
I had the following set up for our 9-broker Kafka cluster's storage:

```
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 1500Gi
        deleteClaim: true
```

I changed `size` to `2000Gi` and I saw that the operator reconciled the podset. At this time 3 of the 9 brokers restarted. They restarted one at a time and everything seemed to go fine, but then that was it. The other 6 brokers did not restart. Execing into the pod and using `df -h` I can see that both the brokers that restarted and the ones that did not restart have the new volume size. 

Why did only 3 of the 9 brokers restart?
Is it necessary at all for the brokers to restart after increasing storage?
