### DISCUSSION TITLE
Option for Kafkatopic Resource to not delete the actual data if resource is delete

### DISCUSSION THREAD

**Discussion by chilicat** [strimzi/strimzi-kafka-operator#10645] [General]
Hi All,

I was wondering if it is possible to use KafkaTopic resources to create/configure topics but leave the data intact when deleted.

We require that because we see the deployment of Kubernetes resources as ephemeral, and it is not uncommon that our customers to delete and reinstall our Helm charts (which contain the KafkaTopic resources) with the expectation that the data still exists.

**Comment by chilicat** [comment]
I found this unidirectional topic operator page: https://strimzi.io/blog/2023/11/02/unidirectional-topic-operator/

Would I get the expected result by disabling the finializer?

```
 topicOperatorContainer:
        env:
          - name: STRIMZI_USE_FINALIZERS
            value: "false"
```

The documentation states: `In development and test environments, you can disable the use of finalizers`
Apart from the data is not deleted, would I expect other side effects by disabling the finalizer?
