### DISCUSSION TITLE
[Bug]: Changing KafkaTopic replicas and config simultaneously corrupts the topic

### DISCUSSION THREAD

**Discussion by vereshchagin-d** [strimzi/strimzi-kafka-operator#10694] [General]
### Bug Description

Hello!
We noticed a strange behavior when we tried to change the replicas and config parameters of a topic simultaneously. After updating the manifest, the KafkaTopic object state got stuck in pending with the message "Replicas change failed, Request failed (500), Cluster model not ready."
Thanks in advance.

### Steps to reproduce

1. Create topic
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: staging
  name: test
  namespace: staging
spec:
  partitions: 3
  replicas: 1
  topicName: test-topic
```
2. Update spec
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: staging
  name: test
  namespace: staging
spec:
  config:
    retention.ms: 600000
    segment.bytes: 3145728
    segment.ms: 600000
  partitions: 3
  replicas: 3
  topicName: test-topic
```
3. Got an error
<img width="700" alt="image" src="https://github.com/user-attachments/assets/712f446e-1017-4037-9e75-679d53eadd0d">

### Expected behavior

Number of replicas set to desired number.
Config applied.

### Strimzi version

0.42.0

### Kubernetes version

k8s 1.29.1

### Installation method

Helm chart

### Infrastructure

Cloud
