### DISCUSSION TITLE
How can I pass hostname to log4j configuration?

### DISCUSSION THREAD

**Discussion by rkuccf** [strimzi/strimzi-kafka-operator#10712] [Q&A]
Hi,
I'm working on log4j configuration that will send broker logs through SocketAppender to different pod. I want to set application appender's property to $HOSTNAME. I was trying to do this by setting additional java property using kafka.jvmOptions.javaSystemProperties and kafka.template.kafkaContainer.env:
```yaml
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
spec:
  kafka:
    jvmOptions:
      javaSystemProperties:
        - name: HOSTNAME
          value: $(HOSTNAME)
    logging:
      loggers:
        kafka.root.logger.level: INFO
        log4j.appender.CONSOLE: org.apache.log4j.ConsoleAppender
        log4j.appender.CONSOLE.layout: org.apache.log4j.PatternLayout
        log4j.appender.CONSOLE.layout.ConversionPattern: '%d{ISO8601} %p %c [%t] - %m%n'
        log4j.appender.SOCKET: org.apache.log4j.net.SocketAppender
        log4j.appender.SOCKET.Application: ${HOSTNAME}
        log4j.appender.SOCKET.Port: '8081'
        log4j.appender.SOCKET.RemoteHost: kafka-fluentbit-svc
        log4j.logger.kafka: INFO
        log4j.logger.kafka.controller: INFO
        log4j.logger.org.apache.kafka: INFO
        log4j.logger.state.change.logger: INFO
        log4j.rootLogger: ${kafka.root.logger.level}, CONSOLE, SOCKET
      type: inline
    template:
      kafkaContainer:
        env:
          - name: JAVA_TOOL_OPTIONS
            value: '-DHOSTNAME=$(HOSTNAME)'
    version: 3.7.0
  
```
Both of ways doesn't work and in the broker pod I can see:
```shell
[kafka@kafka-kafka-0 kafka]$ set | grep 'JAVA_TOOL_OPTIONS\|STRIMZI_JAVA_SYSTEM_PROPERTIES'
JAVA_TOOL_OPTIONS='-DHOSTNAME=$(HOSTNAME)'
STRIMZI_JAVA_SYSTEM_PROPERTIES='-DHOSTNAME=$(HOSTNAME)'
```
It seems that expanding environment variables doesn't work. 
Is there any other way to pass hostname to log4j configuration?

Thank you in advance!
