### DISCUSSION TITLE
how to change strimzi dns cache ttl for connect

### DISCUSSION THREAD

**Discussion by jorgebo10** [strimzi/strimzi-kafka-operator#10757] [General]
Hi,
Is it possible to configure networkaddress.cache.ttl  in Strimzi 0.34.0 for a KafkaConnector. I have found STRIMZI_DNS_CACHE_TTL but not sure how to check if it works.
Thanks

**Comment by scholzj** [comment]
I think `STRIMZI_DNS_CACHE_TTL` applies only to the Cluster and User Operators. Not to any operands.

**Reply by jorgebo10** [reply]
Thanks, for the reply. Maybe something like this ?

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-postgres-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.3.1
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  config:
    group.id: my-postgres-connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  template:
    connectContainer:
      env:
      - name: STRIMZI_DNS_CACHE_TTL
        value: "0"
 build:
    output:
      type: docker
      image: REGISTRY_CLUSTER_IP:5000/my-connect-postgres-cluster:latest
    plugins:
      - name: debezium-postgres-connector
        artifacts:
        - type: tgz
          url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.9.7.Final/debezium-connector-postgres-1.9.7.Final-plugin.tar.gz
          sha512sum: 088a92a7456101d7f01e356250439728e2018355d11797f20b8520d58ba6ce4400f917263223386b031c000d21010e1387970707bd7e8f92a681ac3c88ccc38b

  
```

**Reply by scholzj** [reply]
As I told you, `STRIMZI_DNS_CACHE_TTL` has no meaning anywhere else than in the Cluster and User operators. Search through the source code to see where it is used. For Connect, I think you have to configure the Java system property directly.

**Reply by jorgebo10** [reply]
Thanks, for the answer, i'm quiet new to Strimzi. I have searched through the code and as you mentioned it is only used in Cluster and User operators. It seems that STRIMZI_DNS_CACHE_TTL affects dns caching for neither kafka, kafkaconnect nor  mirrormaker, only operators. So i should maybe add to docker image

**Reply by scholzj** [reply]
I do not think you need to add it anywhere. You can just specify the Java system properties to configure it directly.

**Reply by jorgebo10** [reply]
cool, i went over the source code https://github.com/strimzi/strimzi-kafka-operator/blob/main/user-operator/src/main/java/io/strimzi/operator/user/Main.java and then i set the following config up:

 ```
jvmOptions:
    javaSystemProperties:
      - name: STRIMZI_DNS_CACHE_TTL
        value: "0"
      - name: javax.net.debug
        value: ssl
```
and noticed that env of my pod was updated:
```
{
                        "name": "STRIMZI_JAVA_SYSTEM_PROPERTIES",
                        "value": "-DSTRIMZI_DNS_CACHE_TTL=0 -Djavax.net.debug=ssl"
                    },
```
