### DISCUSSION TITLE
Strimzi Kafka consume from closest replica

### DISCUSSION THREAD

**Discussion by brunooliveiramac** [strimzi/strimzi-kafka-operator#10778] [Q&A]
Hi there, 
Im following this doc to configure rack awareness in my consumers and also set the proper configs in my strimzi kafka:

https://strimzi.io/docs/operators/latest/configuring.html#consuming_messages_from_the_closest_replicas

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka-operator
spec:
  entityOperator:
    template:
      pod:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: type
                  operator: In
                  values:
                  - kafka
              weight: 1
        tolerations:
        - effect: NoSchedule
          key: kafka-node-pool
          operator: Exists
    topicOperator:
      watchedNamespace: vikingcloud
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 2
      min.insync.replicas: 1
      num.network.threads: 4
      num.partitions: 1
      offsets.topic.replication.factor: 1
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - configuration:
        bootstrap:
          annotations:
            networking.gke.io/load-balancer-type: Internal
            service.kubernetes.io/topology-aware-hints: auto
          loadBalancerIP: 10.235.0.199
        brokers:
        - annotations:
            networking.gke.io/load-balancer-type: Internal
          broker: 0
        - annotations:
            networking.gke.io/load-balancer-type: Internal
          broker: 1
        - annotations:
            networking.gke.io/load-balancer-type: Internal
          broker: 2
        - annotations:
            networking.gke.io/load-balancer-type: Internal
          broker: 3
        - annotations:
            networking.gke.io/load-balancer-type: Internal
          broker: 4
        - annotations:
            networking.gke.io/load-balancer-type: Internal
          broker: 5
        - annotations:
            networking.gke.io/load-balancer-type: Internal
          broker: 6
        - annotations:
            networking.gke.io/load-balancer-type: Internal
          broker: 7
        - annotations:
            networking.gke.io/load-balancer-type: Internal
          broker: 8
      name: plain
      port: 9092
      tls: false
      type: loadbalancer
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    rack:
      topologyKey: topology.kubernetes.io/zone
    replicas: 9
    resources:
      limits:
        cpu: "8"
        memory: 33Gi
      requests:
        cpu: "6"
        memory: 8Gi
    storage:
      class: kafka-pd
      deleteClaim: false
      size: 22000Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                  - kafka
        tolerations:
        - effect: NoSchedule
          key: kafka-node-pool
          operator: Exists
        topologySpreadConstraints:
        - maxSkew: 1
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Honor
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
        - maxSkew: 1
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Honor
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
  kafkaExporter:
    groupRegex: .*
    template:
      pod:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - preference:
                matchExpressions:
                - key: type
                  operator: In
                  values:
                  - kafka
              weight: 1
        tolerations:
        - effect: NoSchedule
          key: kafka-node-pool
          operator: Exists
    topicRegex: .*
  zookeeper:
    replicas: 3
    resources:
      limits:
        cpu: "2"
        memory: 5Gi
      requests:
        cpu: "0.5"
        memory: 2Gi
    storage:
      class: kafka-pd
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                  - kafka
        tolerations:
        - effect: NoSchedule
          key: kafka-node-pool
          operator: Exists
        topologySpreadConstraints:
        - maxSkew: 1
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Honor
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
        - maxSkew: 1
          nodeAffinityPolicy: Honor
          nodeTaintsPolicy: Honor
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
```

For consumers  we set

```
  public ConsumerFactory<String, Event> eventIngestionConsumerFactory(@NotNull KafkaProperties properties) {
    Map<String, Object> consumerProps = properties.buildConsumerProperties();
    consumerProps.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
    consumerProps.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, KafkaAvroDeserializer.class);
    consumerProps.put(AbstractKafkaSchemaSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG, schemaRegistryUrl);
    consumerProps.put(KafkaAvroDeserializerConfig.SPECIFIC_AVRO_READER_CONFIG, true);
    consumerProps.put(KafkaAvroDeserializerConfig.AVRO_USE_LOGICAL_TYPE_CONVERTERS_CONFIG, true);
    **consumerProps.put(ConsumerConfig.CLIENT_RACK_CONFIG, kafkaReplicaZone);**
    return new DefaultKafkaConsumerFactory<>(consumerProps);
  }

```

But during consumer, I'm not seeing it fetching from closest. This pod is running in zone c, but consuming from zone b.
The topic has replication set to 3 and I have 3 zones, a, b, and f.

```
Added READ_UNCOMMITTED fetch request for partition event-ingestion-topic-53 at position FetchPosition{offset=2450619361, offsetEpoch=Optional[6], currentLeader=LeaderAndEpoch{leader=Optional[10.235.0.5:9092 (id: 5 rack: us-central1-b)], epoch=6}} to node 10.235.0.5:9092 (id: 5 rack: us-central1-b)
```

Does anyone face something similar? This is affecting our cloud costs due to the cross-zone traffic.
