### DISCUSSION TITLE
Static nodeport for external service

### DISCUSSION THREAD

**Discussion by benedictmulongo** [strimzi/strimzi-kafka-operator#10789] [Q&A] [answered]
Hi, 
I would like to know if it is possible to create a static nodeport for an external service 

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.8.0
    replicas: 1
    listeners:
    - name: plainext
      port: 9092
      type: nodeport
      tls: false
      configuration:
        brokers:
        - broker: 0
          nodePort: 31542
    - name: tls
      port: 9093
      type: internal
      tls: true
    - name: external
      port: 9094
      tls: false
      type: nodeport
      configuration:
        brokers:
        - broker: 1
          advertisedHost: localhost
          advertisedPort: 32769
          nodePort: 32769
      ...
```
Expectation: the `external` listerner on port `9094` should always map to `32769` after service restart.
Right now I get something random each time `30196` & `30163` as in the table below

| NAME                                         | TYPE       | CLUSTER-IP     | EXTERNAL-IP | PORT(S)                                | AGE |
|----------------------------------------------|------------|----------------|-------------|----------------------------------------|------|
| service/kafka-cluster-kafka-0                | NodePort   | 10.152.183.139 | <none>      | 9094:30196/TCP                         | 30m  |
| service/kafka-cluster-kafka-external-bootstrap | NodePort | 10.152.183.231 | <none>      | 9094:30163/TCP                         | 32m  |

**Comment by scholzj** [comment, marked as answer]
I think you are configuring it in the right way: https://strimzi.io/docs/operators/latest/full/configuring.html#property-listener-config-nodeport-reference

But if you have broker `0` in your cluster, you have to configure the port for the broker `0` and not for the broker `1`. So your configuration for port `32769` would be used only if you scale the number of brokers to actually have a broker with ID `1`.

**Comment by benedictmulongo** [comment]
From https://strimzi.io/docs/operators/latest/full/configuring.html#property-listener-config-nodeport-reference
13.7. Overriding assigned node ports

By default, the port numbers used for the bootstrap and broker services are automatically assigned by Kubernetes. You can override the assigned node ports for nodeport listeners by specifying the desired port numbers.

Strimzi does not perform any validation on the requested ports. You must ensure that they are free and available for use.
Example nodeport listener configuration with overrides for node ports

```yaml
# ...
listeners:
  #...
  - name: external
    port: 9094
    type: nodeport
    tls: true
    configuration:
      bootstrap:
        nodePort: 32100
      brokers:
      - broker: 0
        nodePort: 32000
# ...
```
