### DISCUSSION TITLE
Question about the KafkaNodePool resources ("storage overrides")

### DISCUSSION THREAD

**Discussion by BBQigniter** [strimzi/strimzi-kafka-operator#10813] [Q&A] [answered]
In the changelogs of Strimzi v0.43 following is mentioned:

> The storage overrides for configuring per-broker storage class are deprecated and will be removed in the future.
> If you are using the storage overrides, you should migrate to KafkaNodePool resources and use multiple node pools with a different storage class each.

Does this mean that something like this in a Kafka-cluster manifest, will not work anymore some day in future?

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-test
  namespace: kafka-test
spec:
  kafka:
    version: 3.7.0
    replicas: 3
...
    storage:
      type: persistent-claim
      # has no effect but we need it
      size: 5Gi
      class: local-kafka-storage
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
...
```

In our case we just prepare mount-points/data-directories and define persistent volumes for example on three different Kubernetes nodes, where the Kafka/Zookeeper node pods then will be scheduled. So `kafka-test-kafka-0` is always running on node-1, `kafka-test-kafka-1` is always running on node-2 and so on. This makes setups quite easy and we do not have/need a shared or clustered filesystem that can be used by all nodes.

**Comment by scholzj** [comment]
> Does this mean that something like this in a Kafka-cluster manifest, will not work anymore some day in future?

Yes and no 🫣. The YAML you shared will stop working. In order to use KRaft (ZooKeeper-less Kafka) you will need to move to KafkaNodePools and KafkaNodePool configure the storage in the `KafkaNodePool` resource.

However, the deprecated part that will not be supported anymore with KafkaNodePools is about the use of the storage class overrides:

```yaml
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
        class: my-storage-class
        overrides:
        - broker: 0
          class: my-storage-class-zone-1a
        - broker: 1
          class: my-storage-class-zone-1b
        - broker: 2
          class: my-storage-class-zone-1c
```

You do not seem to be using those. So you should be able to easily migrate to the KafkaNodePools as described in the docs.
