### DISCUSSION TITLE
Worker communication through REST interface

### DISCUSSION THREAD

**Discussion by lmenezes** [strimzi/strimzi-kafka-operator#10848] [General]
Hi there,

I'm running Strimzi 0.44.0 with Kafka 3.7.1 on Kubernetes v1.28 and I found that when using the REST interface to create/delete connectors requests will at times fail (when the non-leader worker tries to forward the request to the leader worker, as described [here](https://github.com/strimzi/strimzi-kafka-operator/issues/54)).

The error looks like this:

```json
{
    "error_code": 500,
    "message": "IO Error trying to forward REST request: java.net.UnknownHostException: kafka-connect-elasticsearch-sink-cluster-connect-d768bfb959wcgl: Name or service not known"
}
```

My understanding is that the advertised host is the pod's name, which won't work for cross pod communication (and doesn't match the behavior described in the issue above)

I have tried to find ways to override this but with no luck.

Is there a way to solve this issue? Perhaps not overriding the advertised host, but at least having it use the ip address rather than pod name?

**Comment by katheris** [comment]
Hi, can you share some more information about your setup, from your description I'm struggling to follow what is failing. For example what does your KafkaConnect CR look like, how are you accessing the REST API (e.g. from inside or outside the cluster, through a service, or through some ingress you created?).

I'm not sure what `kafka-connect-elasticsearch-sink-cluster-connect-d768bfb959wcgl` is referring to because the Kafka connect pod names should be e.g. "my-connect-cluster-connect-0", "my-connect-cluster-connect-1" for a Kafka Connect cluster called "my-connect-cluster"

**Reply by lmenezes** [reply]
Hi @katheris 

thanks for getting back so quickly :)

1. Kafka Connect CR (some details omitted for brevity):

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
spec:
  bootstrapServers: kafka-server:9092
  config:
    config.providers: directory
    config.providers.directory.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
    config.storage.replication.factor: -1
    config.storage.topic: kafka-connect-elasticsearch-sink.internal.connect-cluster-configs
    group.id: kafka-connect-elasticsearch-sink-group
    offset.storage.replication.factor: -1
    offset.storage.topic: kafka-connect-elasticsearch-sink.internal.connect-cluster-offsets
    status.storage.replication.factor: -1
    status.storage.topic: kafka-connect-elasticsearch-sink.internal.connect-cluster-status
  image: xxxxxxx.dkr.ecr.us-east-1.amazonaws.com/kafka-connect-elasticsearch-sink:commit-5085ca5
  replicas: 2
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: application
                operator: In
                values:
                - services-graviton
      metadata:
        annotations:
          sidecar.istio.io/inject: "true"
```

2. We are accessing the REST API both from within the cluster as well as from outside (with the same result: requests failing if not handled by the leader,  as it cannot resolve the host when trying to forward the request to the leader)
3. kafka-connect-elasticsearch-sink -> This is a custom imaged base off quay.io/strimzi/kafka:0.44.0-kafka-3.7.1. It basically includes our custom elasticsearch connector plugin and nothing else
4. Each pod runs also an istio sidecar

Now I'm curious to understand why the pod names are not matching what you describe.

For context, We started having this issue after upgrading strimzi from 0.38 to 0.44, I'm assuming because of the changes made to `docker-images/kafka-based/kafka/scripts/kafka_connect_run.sh` in this [commit](https://github.com/strimzi/strimzi-kafka-operator/commit/8249e8d42d109769919294f55ea3d689773bfd88#diff-c1533da49ac59cd9cd2e7e49043a59aed8afae4a76ad30dec1e65fa803686fd2R16-R18):

```diff
- # Prepare hostname depending on whether we use StrimziPodSets (Stable Pod Identities) or Deployments
- # For StrimziPodSets we use the Pod DNS name assigned through the headless service
- # For Deployments we use the Pod IP address
- if [ "$STRIMZI_STABLE_IDENTITIES_ENABLED" = "true" ]; then
-   ADVERTISED_HOSTNAME=$(hostname -f | cut -d "." -f1-4)
-   export ADVERTISED_HOSTNAME
- else
-   ADVERTISED_HOSTNAME=$(hostname -I | awk '{ print $1 }')
-   export ADVERTISED_HOSTNAME
- fi
+ # Prepare hostname - for StrimziPodSets we use the Pod DNS name assigned through the headless service
+ ADVERTISED_HOSTNAME=$(hostname -f | cut -d "." -f1-4)
+ export ADVERTISED_HOSTNAME
```
