### DISCUSSION TITLE
Can I set multiple topics for one ACL? Or do I have to define them separately?

### DISCUSSION THREAD

**Discussion by ghost** [strimzi/strimzi-kafka-operator#10994] [Q&A] [answered]
Like if I had:

```
      - resource:
          type: topic
          name: "topic.literal"
          patternType: literal
        operations:
          - Describe
          - DescribeConfigs
          - Read
          - Write
```

how do I have multiple topics specified? I have a lot of repartition and changelog topics and strimzi does not support -suffix patternType :(

```
Is something like this possible
```
      - resource:
          type: topic
          - name: "topic.literal1"
          - name: "topic.literal2"
          patternType: literal
        operations:
          - Describe
          - DescribeConfigs
          - Read
          - Write
```
