### DISCUSSION TITLE
Strimzi without self-managed CA certificates

### DISCUSSION THREAD

**Discussion by DavidMachacek** [strimzi/strimzi-kafka-operator#11005] [Q&A]
As of this moment Strimzi support providing custom CA, i.e.
```
spec:
  clusterCa:
    generateCertificateAuthority: false
  clientsCa:
    generateCertificateAuthority: false 
```

These certificates are expected to be CA:True
```
X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:TRUE
```

But our internal security policy prevents us from granting Strimzi or anyone else the private key from CA certification chain that includes our Root and intermediate CA. Why does it need it? We just want strimzi to be able to validate signed certificated, which we would prefer to provide by our own to each cluster member (zoo, brokers..) as well as to each client. Is this achieveable/configurable in Strimzi?

Our expectation is, that for example if Strimzi support providing custom clients certificates along with external-tls authentication, it should provide an option to run everything using CA managed by us, not by Strimzi itself.
