### DISCUSSION TITLE
Listener specific perPodService

### DISCUSSION THREAD

**Discussion by abiodunakandewp** [strimzi/strimzi-kafka-operator#11033] [Q&A]
Hi, 

Looking for some guidance on a problem we're encountering with having both loadbalancer and route listeners within our kafka cluster.

Our current setup is:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-node-pool
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 1
...
  template:
    perPodService:
      metadata:
        annotations:
          service.beta.kubernetes.io/aws-load-balancer-internal: "true"
          service.beta.kubernetes.io/load-balancer-source-ranges: 10.0.0.0/8
          service.beta.kubernetes.io/aws-load-balancer-subnets: ${SUBNET}
...
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
...
  kafka:
    listeners:
    - name: externaltls
      port: 9093
      type: loadbalancer
      tls: true
      authentication:
        type: tls
      configuration:
        bootstrap:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/load-balancer-source-ranges: 10.0.0.0/8
            service.beta.kubernetes.io/aws-load-balancer-subnets: ${SUBNET}
    - name: route
       port: 9094
       tls: true
       type: route
```

This configuration currently fails because of the route listener. The service related to the route listener fails to create with error `metadata.annotations[service.beta.kubernetes.io/load-balancer-source-ranges],
        message=Forbidden: may only be used when `type` is ''LoadBalancer'', reason=FieldValueForbidden,`.

We were wondering if we're missing some option to define a perPodService type within the listener itself.

For example:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
...
listeners:
- name: externaltls
  port: 9093
  type: loadBalancer
  perPodService:
    annotations:
     service.beta.kubernetes.io/aws-load-balancer-internal: "true"
     service.beta.kubernetes.io/load-balancer-source-ranges: 10.0.0.0/8
     service.beta.kubernetes.io/aws-load-balancer-subnets: ${SUBNET}
- name: route
  port: 9094
  tls: true
  type: route
  perPodService:
      annotations:
         <route-specific-annotation>: foo
```

We would like to avoid defining the annotations within `spec.kafka.listeners[*].configuration.brokers[*]` because when we scale the replicas within the node pool, we are then required to add another broker to the configuration.
