### DISCUSSION TITLE
[QUESTION] kafka super user with tls-external authentication denied authorisation in Kafka strimzi cluster

### DISCUSSION THREAD

**Discussion by OLAMIDE100** [strimzi/strimzi-kafka-operator#11049] [Q&A] [answered]
GENERAL SETUP 

1) Both CLUSTER CA and Client CA where created externally with the right secret annotation and label supplied to the cluster 

2) The User certificate and key where created external and signed with the client CA, all stored in pkcs12 trust store and key store

KAFKA YAML 

```

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  clusterCa:
    generateCertificateAuthority: false
  clientsCa:
    generateCertificateAuthority: false
  kafka:
    authorization:
      type: simple
      superUsers:
        - CN=super-user,OU=Dataops,O=*******,L=***********,C=EE
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external2
        port: 9094
        type: loadbalancer
        tls: true
        configuration:
          bootstrap:
            loadBalancerIP: **********
          brokers:
          - broker: 0
            loadBalancerIP: ************
        authentication:
          type: tls
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: cloud.google.com/gke-nodepool
                    operator: In
                    values:
                    - kafka-pool
        tolerations:
          - key: "app.kubernetes.io/instance"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
    
```
    
    
    USER YAML
  
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: super-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls-external


```

SECRET CREATEION 

```

kubectl create secret generic my-cluster-cluster-ca-cert  -n kafka \
  --from-file=ca.crt=/Users/adewale.adesoba/Documents/company_bitbucket/Private_key_infrastructure/kafka-cluster/certificate_authority/ca.crt \
  --from-file=ca.p12=/Users/adewale.adesoba/Documents/company_bitbucket/Private_key_infrastructure/kafka-cluster/certificate_authority/ca.p12 \
  --from-literal=ca.password=PWOC0LxFiRzN

kubectl create secret generic my-cluster-cluster-ca -n kafka \
  --from-file=ca.key=/Users/adewale.adesoba/Documents/company_bitbucket/Private_key_infrastructure/kafka-cluster/certificate_authority/ca.key


kubectl create secret generic my-cluster-clients-ca-cert -n kafka \
  --from-file=ca.crt=/Users/adewale.adesoba/Documents/company_bitbucket/Private_key_infrastructure/kafka-cluster/client_authority/ca.crt \
  --from-file=ca.p12=/Users/adewale.adesoba/Documents/company_bitbucket/Private_key_infrastructure/kafka-cluster/client_authority/ca.p12 \
  --from-literal=ca.password=OeutymenuBFj


kubectl create secret generic my-cluster-clients-ca -n kafka \
  --from-file=ca.key=/Users/adewale.adesoba/Documents/company_bitbucket/Private_key_infrastructure/kafka-cluster/client_authority/ca.key

kubectl label secret my-cluster-cluster-ca  strimzi.io/kind=Kafka strimzi.io/cluster=my-cluster -n kafka 
kubectl label secret my-cluster-cluster-ca-cert  strimzi.io/kind=Kafka strimzi.io/cluster=my-cluster -n kafka 
kubectl label secret my-cluster-clients-ca-  strimzi.io/kind=Kafka strimzi.io/cluster=my-cluster -n kafka 
kubectl label secret my-cluster-clients-ca-cert  strimzi.io/kind=Kafka strimzi.io/cluster=my-cluster -n kafka 

kubectl annotate secret my-cluster-cluster-ca strimzi.io/ca-key-generation=0 -n kafka
kubectl annotate secret my-cluster-clients-ca strimzi.io/ca-key-generation=0 -n kafka

kubectl annotate secret my-cluster-clients-ca-cert strimzi.io/ca-cert-generation=0 -n kafka
 kubectl annotate secret my-cluster-cluster-ca-cert strimzi.io/ca-cert-generation=0 -n kafka


```
ERROR AT THE BROKER POD

textPayload: "2025-01-16 13:13:20,802 INFO Principal = User:1.2.840.113549.1.9.1=#161761646577616c652e616465736f6261406e6162752e6565,CN=super-user,OU=Dataops,O=**********,L=**************,C=EE is Denied operation = DESCRIBE from host = 10.164.15.214 on resource = Topic:LITERAL:kemi for request = Metadata with resourceRefCount = 1 based on rule DefaultDeny (kafka.authorizer.logger) [data-plane-kafka-request-handler-1]"

**Comment by scholzj** [comment]
I think that for a start you would need to fix the formatting to make the YAMLs readable.

**Reply by OLAMIDE100** [reply]
done

**Reply by scholzj** [reply, marked as answer]
I think your certificate subject is not as you expected it ... based onthe authorization error, it looks like the username is `1.2.840.113549.1.9.1=#161761646577616c652e616465736f6261406e6162752e6565,CN=super-user,OU=Dataops,O=**********,L=**************,C=EE`

So that is what you need to use in the Kafka CR:
```yaml
    authorization:
      type: simple
      superUsers:
        - 1.2.840.113549.1.9.1=#161761646577616c652e616465736f6261406e6162752e6565,CN=super-user,OU=Dataops,O=**********,L=**************,C=EE
```

Also, you do not need the `KafkaUser` resource in this case, it is meaning less because even if you add anything to it, it will have no relation to the user fdrom your certificate (as it would need to have the subject only as `CN=super-user` to match the KafkaUser resource)
