### DISCUSSION TITLE
MirrorMaker 2.0 Consumer Group Offset Syncing Lag in Active-Passive DR Setup

### DISCUSSION THREAD

**Discussion by prth** [strimzi/strimzi-kafka-operator#11125] [General]
We are using Strimzi’s Kafka MirrorMaker 2.0 to replicate messages and consumer group offsets between two regions in an active-passive (DR) setup. While messages sync correctly, we observe significant lag in consumer group offset syncing.

**Issue Description**
	•	Message replication is working fine, with no noticeable lag.
	•	Consumer group offsets are not syncing in a timely manner.

**Here is configuration used for source and checkpoint connector**
```
     sourceConnector:
        tasksMax: 4
        config:
          replication.factor: -1
          offset-syncs.topic.replication.factor: -1
          refresh.topics.interval.seconds: 600
          replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy" 
          consumer.auto.offset.reset: earliest 
          offset.lag.max: 5
          sync.topic.acls.enabled: false
      checkpointConnector:
        tasksMax: 4
        config:
          checkpoints.topic.replication.factor: -1
          sync.group.offsets.enabled: true
          refresh.groups.interval.seconds: 10
          replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
          emit.checkpoints.interval.seconds: 5
          sync.group.offsets.interval.seconds: 5
      topicsPattern: "^(?!mirrormaker2-).*"
      groupsPattern: ".*"
```

We tried tuning/reducing consumer group sync intervals (`emit.checkpoints.interval.seconds`, `sync.group.offsets.interval.seconds`), but the issue persists.
We also reduced `offset.lag.max` on the source connector, but it did not improve offset syncing.

Are there any configurations we can tweak to improve consumer offset syncing performance?

**Comment by scholzj** [comment]
I guess a good start would be:
* Proper explanation what `significant lag` means
* Full custom resource
* Full logs

**Comment by prth** [comment]
Here is the what we were using

```
# https://artifacthub.io/packages/helm/strimzi-kafka-operator/strimzi-kafka-operator
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mm2-dr-setup-1
  namespace: kafka
spec:
  version: 3.8.0
  replicas: 2
  connectCluster: "targetRegion" # Must be the target custer
  clusters:
    - alias: "sourceRegion" # Source cluster
      bootstrapServers: {{source-server}}
      config:
        # -1 means it will use the default replication factor configured in the broker
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
    - alias: "targetRegion" # Target cluster
      bootstrapServers: {{target-server}}
      config:
        # -1 means it will use the default replication factor configured in the broker
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
  mirrors:
    - sourceCluster: "sourceRegion"
      targetCluster: "targetRegion"
      sourceConnector:
        tasksMax: 4
        config:
          replication.factor: -1
          offset-syncs.topic.replication.factor: -1
          refresh.topics.interval.seconds: 600
          replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy" 
          consumer.auto.offset.reset: earliest 
          offset.lag.max: 5
          sync.topic.acls.enabled: false
      checkpointConnector:
        tasksMax: 4
        config:
          checkpoints.topic.replication.factor: -1
          sync.group.offsets.enabled: true
          refresh.groups.interval.seconds: 10
          replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
          emit.checkpoints.interval.seconds: 5
          sync.group.offsets.interval.seconds: 5
      topicsPattern: ".*"
      groupsPattern: ".*"
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: mirror-maker-2-metrics
        key: metrics-config.yml
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 2
      memory: 4Gi
```


We are testing consumer group offset sync across regions using MirrorMaker 2 with the checkpoint connector. The goal is to evaluate how quickly consumer offsets are mirrored in a disaster recovery (DR) scenario.


**Test Scenario**:
1. Message Production: In the source region, we pushed a bulk of ~50K messages into a topic.
2. Slow Consumer: A Spring Boot Java application was set up as a slow consumer in the source region, processing one message at a time with a 1-second delay per message. It also committed offsets one at a time.
3. Monitoring Offset Sync:
     - Used AKHQ to manually refresh and track consumer group offsets on the target region.
     - Developed a Kafka Admin API-based utility that checked and logged consumer group offset changes every 2 seconds. And note that I was tracking this consumer group offset change on topic partition level
4. Target Region: No active consumers; it remained in standby mode.
	

**Observations** --
- Message Sync: Messages replicated instantly from source to target.
- Offset Sync Delay: The slow consumer progressed in source region at its stable rate. But in the target region, the consumer group offsets won't sync quickly, it would change every 30-45 minutes.
- Offset Sync Behavior: 
     - As the source consumer group’s offset reduced (e.g., around 1000 remaining), the sync frequency improved to once every 2-3 minutes.
     - When we stopped the consumer in the source region, we expected MirrorMaker to sync the final consumer group offset to the target. However, after stopping the source consumer, no further offset updates occurred, even after waiting for an hour.


**Concern:**
For disaster recovery, we need faster consumer group offset sync since a 45-minute delay is too long for failover scenarios. This becomes a major issue for DR drills, where we need to switch regions quickly.
Is there a way to improve the offset sync speed or force a faster sync when the source consumer stops? Any recommendations or known limitations regarding this behavior?
