### DISCUSSION TITLE
[Bug]: Cluster CA should not be generated, but the secrets were not found.

### DISCUSSION THREAD

**Discussion by Siradjedd** [strimzi/strimzi-kafka-operator#11131] [General]
### Bug Description

Hello ! 
I am deploying Strimzi Kafka (version 0.39.0) with Kafka 3.6.0 and I want to use an external Certificate Authority (CA) managed by Cert-Manager instead of Strimzi’s self-signed CA.
I disabled Strimzi’s built-in CA by setting:
```
clusterCa:
  generateCertificateAuthority: false
clientsCa:
  generateCertificateAuthority: false
```
I manually created TLS certificates using Cert-Manager and provided the secret (wildcard-mycompany-com-tls) to Kafka:
```
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
          type: tls
         configuration: 
          brokerCertChainAndKey:
              secretName: wildcard-labadeiz-com-tls
              certificate: tls.crt
              key: tls.key
      brokerCertChainAndKey:
              secretName: wildcard-labadeiz-com-tls
              certificate: tls.crt
              key: tls.key

```
When deploying Kafka, Strimzi fails with the following error:
`.strimzi.operator.common.model.InvalidResourceException: Cluster CA should not be generated, but the secrets were not found.
`
This indicates that Strimzi is expecting the Cluster CA and Clients CA secrets, but they are missing.

However, I am providing my own TLS certificates via Cert-Manager, so I do not want Strimzi to generate these secrets.

### Expected behavior

Strimzi running with cert-manager certificate and external-clients able to connect to it.

### Strimzi version

 0.39.0

### Kubernetes version

1.26.7

### Installation method

Helm chart

### Infrastructure

Baremetal
