### DISCUSSION TITLE
Issue with Standalone User Operator: "Cannot extract trust set from null secret" when TLS is disabled

### DISCUSSION THREAD

**Discussion by iMaxZxC** [strimzi/strimzi-kafka-operator#11206] [Q&A]
Hello,

I'm encountering an issue with the standalone User Operator (version 0.45.0) when attempting to manage users on a remote Kafka cluster (deployed on virtual machines, separate from my Kubernetes cluster). My setup does not use TLS, and I use SCRAM-SHA-512 for authentication with the credentials:

username: alice
password: alice-secret
I have set the following environment variables in my User Operator deployment:
```
Exception in thread "main" java.lang.NullPointerException: Cannot extract trust set from null secret.
    at java.base/java.util.Objects.requireNonNull(Objects.java:235)
    at io.strimzi.operator.common.auth.PemTrustSet.<init>(PemTrustSet.java:41)
    at io.strimzi.operator.user.Main.createAdminClient(Main.java:147)
    at io.strimzi.operator.user.Main.main(Main.java:82)
```
Configuration Details:
My User Operator deployment (in namespace kafka) is configured as follows:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-kraft-test-strimzi-user-operator
  namespace: kafka
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-kraft-test-strimzi-user-operator
  template:
    metadata:
      labels:
        app: kafka-kraft-test-strimzi-user-operator
    spec:
      serviceAccountName: kafka-kraft-test-strimzi-user-operator
      containers:
        - name: kafka-kraft-test-strimzi-user-operator
          image: quay.io/strimzi/operator:0.45.0
          command: ["/opt/strimzi/bin/user_operator_run.sh"]
          env:
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: "example-broker1:9093,example-broker2:9093,example-broker3:9093"
            - name: STRIMZI_LABELS
              value: "strimzi.io/cluster=kafka-kraft-test"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_CA_CERT_NAME
              value: "unused"
            - name: STRIMZI_CA_KEY_NAME
              value: "unused"
            - name: STRIMZI_CA_VALIDITY
              value: "365"
            - name: STRIMZI_CA_RENEWAL
              value: "30"
            - name: STRIMZI_WORK_QUEUE_SIZE
              value: "10000"
            - name: STRIMZI_CONTROLLER_THREAD_POOL_SIZE
              value: "10"
            - name: STRIMZI_USER_OPERATIONS_THREAD_POOL_SIZE
              value: "4"
            - name: STRIMZI_LOG_LEVEL
              value: "INFO"
            - name: STRIMZI_GC_LOG_ENABLED
              value: "true"
            - name: STRIMZI_SECRET_PREFIX
              value: "kafka-"
            - name: STRIMZI_ACLS_ADMIN_API_SUPPORTED
              value: "true"
            - name: STRIMZI_KAFKA_ADMIN_CLIENT_CONFIGURATION
              value: |
                default.api.timeout.ms=120000
                request.timeout.ms=60000
            - name: STRIMZI_TLS_ENABLED
              value: "false"
            - name: STRIMZI_SASL_ENABLED
              value: "true"
            # Using JAAS config only – not mixing with individual SASL variables:
            - name: STRIMZI_SASL_JAAS_CONFIG
              value: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"alice\" password=\"alice-secret\";"
            - name: STRIMZI_SECURITY_PROTOCOL
              value: "SASL_PLAINTEXT"
            - name: STRIMZI_TLS_AUTH_ENABLED
              value: "false"
```
Since I'm not using TLS, I've created a dummy secret named unused in the kafka namespace:
```
apiVersion: v1
kind: Secret
metadata:
  name: unused
  namespace: kafka
type: Opaque
data:
  ca.crt: ZHVtbXk= 
  ca.key: ZHVtbXk=
```
JAAS Configuration: Is my JAAS configuration correct for SCRAM‑SHA‑512? (I'm using the single variable STRIMZI_SASL_JAAS_CONFIG with the value:
org.apache.kafka.common.security.scram.ScramLoginModule required username="alice" password="alice-secret";
Is that the recommended approach?)

TLS Requirement: Given that TLS is disabled (STRIMZI_TLS_ENABLED is "false"), is it expected that the User Operator still requires valid CA secrets? Is using a dummy secret like the one above a valid workaround?

Any Additional Configuration: Are there any other changes or workarounds required to run the User Operator successfully in a non-TLS environment with SCRAM‑SHA‑512?
