### DISCUSSION TITLE
Issue with Changing ZooKeeper StorageClass in Strimzi Kafka Helm Chart

### DISCUSSION THREAD

**Discussion by apolienko** [strimzi/strimzi-kafka-operator#11267] [Q&A]
# Issue with Changing ZooKeeper StorageClass in Strimzi Kafka Helm Chart

## Environment
- Strimzi Kafka installed via Helm chart
- Current configuration: 3-node ZooKeeper cluster

## What I'm Trying to Achieve
I want to change the StorageClass used by ZooKeeper PVCs from `standard-rwo-retain` to the default StorageClass without losing data or disrupting the cluster.

## Steps Taken
1. I removed the `storageClass` line from `values.yaml`:
```yaml
zookeeper:
  storageDeleteClaim: true
  # storageClass: standard-rwo-retain  <- removed this line
  replicas: 3
  resources:
```

2. Applied the changes with Helm, and the output confirmed the removal:
```yaml
storage:
  type: persistent-claim
- class: "standard-rwo-retain"
  size: "20Gi"
  deleteClaim: true
```

## Current Problem
After applying these changes, I've verified that the `storageClass` specification is no longer present in the Kafka custom resource. However, the ZooKeeper pods are still using the old PVCs with the previous StorageClass. No new PVCs were created with the default StorageClass.

## Main Question
How can I properly perform maintenance on the ZooKeeper cluster to change the StorageClass? 

Specifically, I want to achieve a rolling update that would:
1. Replace all PVCs and PVs in the ZooKeeper pods
2. Use the new default StorageClass (or any other class)
3. Preserve all data across the cluster
4. Maintain cluster stability during the transition (no downtime)

What is the correct procedure to make this change safely in a production environment with a 3-node ZooKeeper cluster?
