### DISCUSSION TITLE
Client Can Connect to Kafka Without TLS Certificate Even When TLS is Enforced

### DISCUSSION THREAD

**Discussion by inderanz** [strimzi/strimzi-kafka-operator#11276] [Q&A]
A client running on a different GKE cluster is able to connect to a Strimzi-managed Kafka cluster without providing a client-side certificate, despite TLS authentication being enabled on the external listener.

 Expected vs. Actual Behavior

Expected: When a client without a valid certificate attempts to connect, the connection should fail with an SSL authentication error.
Actual: Clients are able to connect even without a certificate, despite TLS and client authentication being enabled.

The expectation is that connections without valid TLS client certificates should be rejected with an SSL handshake failure. However, the client is able to establish a connection and send/receive messages without authentication.

Kafka version: 3.6.2
Strimzi Operator version: 0.42.0
Deployment: Kraft mode with external listener using TLS
Cluster Type: GKE

Kafka Cluster Definition:

---
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster-prod-kafka-sit
  namespace: ns-cluster-prod-integration-sit
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.6.2
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: DEBUG
        org.apache.kafka.common.network: TRACE
        org.apache.kafka.common.security.auth: TRACE
        org.apache.kafka.common.security.ssl: TRACE
    metadataVersion: 3.6-IV0
    image: "team1-cnc-docker.registry.gcp.com/strimzi/kafka:0.42.0-kafka-3.6.2-amd64"
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: true
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
          type: tls
        configuration:
          brokerCertChainAndKey:
            secretName: kafka-chain-tls
            certificate: tls.crt
            key: tls.key
          bootstrap:
            loadBalancerIP: 100.65.56.224
            annotations:
              networking.gke.io/internal-load-balancer-allow-global-access: "true"
              networking.gke.io/load-balancer-type: Internal
          brokers:
          - broker: 0
            loadBalancerIP: 100.65.56.225
            advertisedHost: 100.65.56.225
            annotations:
              networking.gke.io/internal-load-balancer-allow-global-access: "true"
              networking.gke.io/load-balancer-type: Internal
          - broker: 1
            loadBalancerIP: 100.65.56.226
            advertisedHost: 100.65.56.226
            annotations:
              networking.gke.io/internal-load-balancer-allow-global-access: "true"
              networking.gke.io/load-balancer-type: Internal
          - broker: 2
            loadBalancerIP: 100.65.56.227
            advertisedHost: 100.65.56.227
            annotations:
              networking.gke.io/internal-load-balancer-allow-global-access: "true"
              networking.gke.io/load-balancer-type: Internal
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      socket.request.max.bytes: 400000000 # 400 MB
      ssl.cipher.suites: TLS_AES_256_GCM_SHA384, TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 
      ssl.enabled.protocols: TLSv1.3, TLSv1.2
      ssl.protocol: TLSv1.3 
  entityOperator:
    topicOperator:
      image: "team1-cnc-docker.registry.gcp.com/strimzi/operator:0.42.0-amd64"
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
    userOperator:
      image: "team1-cnc-docker.registry.gcp.com/strimzi/operator:0.42.0-amd64"
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1`
```
###

Reproduction Steps

Deploy Strimzi Kafka with TLS authentication enforced on the external listener (type: loadbalancer with authentication: tls).
Start a client pod in a different GKE cluster without any Kafka TLS certificates.
Run the Kafka producer without specifying any client-side certificate:

# Inside the client pod
bash kafka-console-producer.sh \
  --bootstrap-server kafka-bootstrap-sit.cluster1-np.gcpnp.com:9094 \
  --topic sit.v1.test.topic.01

]# 
[root@kafka-producer-755fbc5bd8-n7zx9 bin]# bash kafka-console-producer.sh --bootstrap-server kafka-bootstrap-sit.cluster1-np.gcpnp.com:9094 --topic sit.v1.test.topic.
01
>I am able to connect to bootstrap server, even when tls is enabled & for this pod am not using any client side cert & ideally it should fail with ssl error
>Not failing to connect
>exit

The producer is able to send messages without an SSL error, despite TLS authentication being enabled.

Verify the same behavior for a consumer:

bash kafka-console-consumer.sh \
  --bootstrap-server kafka-bootstrap-sit.cluster1-np.gcpnp.com:9094 \
  --topic sit.v1.test.topic.01 --from-beginning

>^C[root@kafka-producer-755fbc5bd8-n7zx9 bin]# 

# bash kafka-console-consumer.sh --bootstrap-server kafka-bootstrap-sit.cluster1-np.gcpnp.com:9094 --topic sit.v1.test.topic.01 --from-beginning
hi
{"paymentUid":21,"userId":"user1","amount":100.0,"status":null}
{"paymentUid":21,"userId":"user1","amount":100.0,"status":null}
{"paymentUid":21,"userId":"user1","amount":100.0,"status":null}
I am able to connect to bootstrap server, even when tls is enabled & for this pod am not using any client side cert & ideally it should fail with ssl error
Not failing to connect

The consumer is able to receive messages without authentication.

This is a critical security issue, as it allows unauthenticated access to the Kafka cluster even when TLS is explicitly configured. A fix or workaround is needed to prevent unauthorized clients from connecting.

Looking for
Confirmation if this is a known issue.
A fix or workaround to ensure proper TLS enforcement.
Any additional configurations required to enforce client authentication.
