### DISCUSSION TITLE
Annotations not being set on persistentVolumeClaims

### DISCUSSION THREAD

**Discussion by mchlt** [strimzi/strimzi-kafka-operator#11302] [Q&A] [answered]
Hi All,

I have a need for two annotations to be placed onto the PVCs that the Strimzi deployment / operator creates.
I have followed the recommendation seen in other discussion posts and also checked against the docs, but the Annotations never appear on the PVCs.

I am using Strimzi Operator and CLusters 0.45.0 with Kafka 3.9

This is the relevant snippet of my yaml:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mykafkaname
  namespace: mynamespace
  annotations:
    strimzi.io/node-pools: enabled   
    strimzi.io/kraft: enabled
spec:
  kafka:
    template:
      persistentVolumeClaim:
        metadata:
          annotations:
            argocd.argoproj.io/compare-options: IgnoreExtraneous
            argocd.argoproj.io/sync-options: Prune=false
...
```

When I manually patch those annotations onto the PVCs using kubectl, they appear and they work. 
However after a few minutes they are gone again, which I believe is done by the Strimzi Operator.  So that confirms the Operator doesn't know about the Annotations and thinks they should not be there.
Any idea what I may be missing?

Thanks,
Michiel
