### DISCUSSION TITLE
Brokers' fixed nodePorts are not applied.

### DISCUSSION THREAD

**Discussion by 21lva** [strimzi/strimzi-kafka-operator#11316] [Q&A]
Hello, I have been using strimzi. 

When it comes to replicas=3, the numbering of broker and nodePort setting works well.
But when I change the replicas to 15, it does not work what I expected.

Below is the setting. The indention might be wrong.

```yaml
# Source: strimzi/templates/kafka.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
annotations:
strimzi.io/kraft: enabled
strimzi.io/node-pools: enabled
name: cluster-1
spec:
	kafka:
		version: 3.9.0
		listeners:
		  - name: external
			port: 9094
			type: nodeport
			tls: true
			configuration:
				brokerCertChainAndKey:
					secretName: my-cert
					certificate: cert.pem
					key: private.key
				bootstrap:
					nodePort: 30010
				brokers:
				- broker: 0
					nodePort: 32200
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32200

				- broker: 1
					nodePort: 32201
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32201

				- broker: 2
					nodePort: 32202
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32202

				- broker: 3
					nodePort: 32203
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32203

				- broker: 4
					nodePort: 32204
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32204

				- broker: 5
					nodePort: 32205
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32205

				- broker: 6
					nodePort: 32206
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32206

				- broker: 7
					nodePort: 32207
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32207

				- broker: 8
					nodePort: 32208
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32208

				- broker: 9
					nodePort: 32209
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32209

				- broker: 10
					nodePort: 32210
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32210

				- broker: 11
					nodePort: 32211
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32211

				- broker: 12
					nodePort: 32212
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32212

				- broker: 13
					nodePort: 32213
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32213

				- broker: 14
					nodePort: 32214
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32214

				- broker: 15
					nodePort: 32215
					advertisedHost: cluster-1.myip.com
					advertisedPort: 32215

```

But the below picture is what I got.

![image](https://github.com/user-attachments/assets/025bea97-683b-4338-b86d-55183956c03a)

I checked whether the target ports, that should have been used, were being used. But they weren't.

Is there a way to fix the nodePorts? and can I name the brokers from 0 to 15?
