### DISCUSSION TITLE
Kafka Connect: Not authorized to access topics, using scram-sha-512 authentication and simple authorization

### DISCUSSION THREAD

**Discussion by stitch-marinus** [strimzi/strimzi-kafka-operator#11359] [Q&A]
Hi,

I've been trying to setup a simple Kraft deployment for testing but ran into an authorisation error on KafkaConnect:
```bash
2025-04-16 11:32:34,088 ERROR [Worker clientId=connect-local-connect-connect-0.local-connect-connect.kafka.svc:8083, groupId=local-connect-connect] Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [DistributedHerder-connect-local-connect-connect-0.local-connect-connect.kafka.svc:8083-1]
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [local-connect-offsets]
``` 

My configuration is as follows:
**Kafka:**

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  labels:
    name: local
    namespace: kafka
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalMs: 1000
      watchedNamespace: kafka
    userOperator:
      reconciliationIntervalMs: 1000
      watchedNamespace: kafka
  kafka:
    authorization:
      type: simple
    config: {}
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        tls: false
        type: nodeport
    replicas: 1
```

**User:** (this should have super user privileges) 
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: local
  name: kafka-connect
  namespace: kafka
spec:
  authentication:
    type: scram-sha-512
```

**KafkaConnect:**
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: 'true'
  name: local-connect
  namespace: kafka
spec:
  authentication:
    passwordSecret:
      password: password
      secretName: kafka-connect
    type: scram-sha-512
    username: kafka-connect
  bootstrapServers: local-kafka-bootstrap:9093
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    config.storage.replication.factor: 3
    config.storage.topic: local-connect-configs
    group.id: local-connect-connect
    offset.storage.replication.factor: 3
    offset.storage.topic: local-connect-offsets
    status.storage.replication.factor: 3
    status.storage.topic: local-connect-status
  image: kafka-connect:local
  replicas: 1
  tls:
    trustedCertificates:
      - pattern: '*.crt'
        secretName: local-cluster-ca-cert
```

Is there something I'm missing? I can't spot it.

**Comment by im-konge** [comment]
Hey, from the `Kafka` and `KafkaUser` CRs I don't see where the `kafka-connect` user is configured as super user. You would need to configure it in the Kafka CR, in `authorization` section.

**Reply by stitch-marinus** [reply]
I just mean that I didn't fill in the authorisation section. Originally when I set this up I created the kafka connect topics and gave the kafka-connect user explicit permissions, Read, Write, Describe and DescribeConfig permissions on all of them.

**Reply by im-konge** [reply]
Yes, but that will not grant the user super user permission. The way you have it configured now means that there is no super user configured in Kafka and that the KafkaUser you are creating doesn't have any authorization configuration. I'm pointing at this `(this should have super user privileges)` statement you have in the description.

**Reply by im-konge** [reply]
```
 authorization:
      type: simple
      superUsers:
        - kafka-connect
```

you should have something like this in Kafka spec. And create the KafkaUser `kafka-connect` with SCRAM-SHA.

**Reply by stitch-marinus** [reply]
I'll give it a go, but any idea why the specific authorisation would not work? I feel like I'm not seeing something obvious.

Doing that I got some new logs on the kafka cluster
```bash
2025-04-16 13:35:41,063 INFO Principal = User:kafka-connect is Denied operation = CREATE from host = 10.42.0.88 on resource = Topic:LITERAL:local-connect-offsets for request = CreateTopics with resourceRefCount = 1 based on rule DefaultDeny (kafka.authorizer.logger) [data-plane-kafka-request-handler-6]
2025-04-16 13:35:41,068 INFO Principal = User:kafka-connect is Denied operation = DESCRIBE_CONFIGS from host = 10.42.0.88 on resource = Topic:LITERAL:local-connect-offsets for request = DescribeConfigs with resourceRefCount = 1 based on rule DefaultDeny (kafka.authorizer.logger) [data-plane-kafka-request-handler-3]
```

I added acls for the kafka-user. 
```yaml
authentication: 
    type: scram-sha-512
    authorization:
      type: simple
      acls:
        - type: allow
          resource:
            type: topic
            name: "*" 
          operations:
            - READ
            - WRITE 
            - CREATE 
            - DESCRIBE 
            - DESCRIBE_CONFIGS
```
But the original error is still there in KafkaConnect.
