### DISCUSSION TITLE
[Bug]: Unknown field spec.kafka.template.pod.dnsPolicy

### DISCUSSION THREAD

**Discussion by TeoDimitrov** [strimzi/strimzi-kafka-operator#11407] [General]
### Bug Description

I am testing the new 0.46 Strimzi release and I need to set dnsPolicy to ClusterFirstWithHostNet. However, I am getting Unknown field spec.kafka.template.pod.dnsPolicy 

Does the new feature work in the 0.46 Strimzi release?

### Steps to reproduce

In order to reproduce the error I am applying the following configs:

[kafka-dnsPolicy.txt](https://github.com/user-attachments/files/20034247/kafka-dnsPolicy.txt)

### Strimzi version

0.46

### Kubernetes version

1.29.9

### Installation method

yaml

### Infrastructure

AKS

**Comment by ppatierno** [comment]
I am not able to reproduce it.
I just installed the latest 0.46.0 version and created a Kafka cluster by using a `Kafka` resource like this (together with a couple of node pools).

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 4.0.0
    metadataVersion: 4.0-IV3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    template:
      pod:
        dnsPolicy: ClusterFirstWithHostNet
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

The cluster starts and works fine. You can see the `dnsPolicy` there.
I am guessing you didn't override the CRDs with the new Strimzi installation and still using the previous one (from 0.45.0 or older) where that field is not present at all in the `Kafka` CRD.

**Comment by see-quick** [comment]
Yeah, I did the same. Not reproducible for me as well. Pods are running with the DNS policy set.
```yaml
apiVersion: v1
kind: Pod
...
spec:
  affinity: {}
  ...
  dnsPolicy: ClusterFirstWithHostNet <--- here set
  ...
  phase: Running
...
  ```
  
  And it's always good to start with sharing logs to understand the issue better. Because without logs, we can only guess...what might be the problem on your side :)
