### DISCUSSION TITLE
Cluster operator auto upgrading

### DISCUSSION THREAD

**Discussion by smsajid** [strimzi/strimzi-kafka-operator#11437] [Q&A] [answered]
I installed Strimzi operator using the default stable version: kubectl create -f https://operatorhub.io/install/stable/strimzi-kafka-operator.yaml
This was many versions ago ~0.39.0. I observed that the operator is auto upgrading to new versions as soon as they are released. This is causing issues as older versions of Kafka are not supported. 
Some errors due to this:

```
2025-05-13 13:57:18 WARN  AbstractOperator:566 - Reconciliation #2350(timer) KafkaConnect(smartsafety4s-prod/redis): Failed to reconcile
io.strimzi.operator.cluster.model.KafkaVersion$UnsupportedKafkaVersionException: Unsupported Kafka.spec.kafka.version: 3.8.1. Supported versions are: [3.9.0, 4.0.0]
```

How do I prevent the auto upgrade and also downgrade to older version of the operator?

**Comment by Frawless** [comment, marked as answer]
This is a common functionality of OLM. By default `installPlanApproval` is set to `Automatic`. You should change it to `Manual` in you `Subscription` to prevent auto-upgrades. Something like:

```
apiVersion: operators.coreos.com/v1alpha1 
kind: Subscription 
metadata: 
   name: my-strimzi-kafka-operator 
   namespace: operators 
spec: 
   channel: stable 
   name: strimzi-kafka-operator 
   source: operatorhubio-catalog 
   sourceNamespace: olm
   installPlanApproval: Manual
```

For more details see OLM documentation - https://olm.operatorframework.io/docs/tasks/install-operator-with-olm/
