### DISCUSSION TITLE
Broker reboots after reaching high memory utilisation

### DISCUSSION THREAD

**Discussion by vsfomin** [strimzi/strimzi-kafka-operator#11449] [General]
After I installed Kafka (Kraft Mode) in the k8s cluster and one of the microservices is configured to forward logs to the kafka topic, Kafka started consuming a lot of memory. After about two hours of operation, the 8Gb is reached, then all three brokers reboot. 
What could be the problem? When I try to switch logging to kafka, which is deployed on a VM, the memory consumption does not exceed 1.6 GB

![image](https://github.com/user-attachments/assets/7f72db5e-1c0b-4176-8eb1-97016e7cec57)
 
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  template:
      pod:
        tolerations:
        - key: "kafka"
          operator: "Exists"
          effect: "NoSchedule"
  resources:
      requests:
        memory: 4Gi
      limits:
        memory: 12Gi
  jvmOptions:
      "-Xmx": "8g"
      "-Xms": "2g"
  replicas: 3
  roles:
    - controller
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 40Gi
        kraftMetadata: shared
        deleteClaim: false
        class: csi-disk
        
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  template:
      pod:
        tolerations:
        - key: "kafka"
          operator: "Exists"
          effect: "NoSchedule"
  replicas: 3
  resources:
      requests:
        memory: 4Gi
      limits:
        memory: 12Gi
  jvmOptions:
      "-Xmx": "8g"
      "-Xms": "2g"
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 40Gi
        kraftMetadata: shared
        deleteClaim: false
        class: csi-disk
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
