### DISCUSSION TITLE
Upgrading Kafka from 3.8.0 to 3.9.0 fails during creation of custom cert keystore in broker

### DISCUSSION THREAD

**Discussion by avinash-platformatory** [strimzi/strimzi-kafka-operator#11446] [Q&A]
I'm upgrading Kafka from 3.8.0 to 3.9.0 and noticed that the broker fails to create the keystore for the custom listener with custom certs.From the pod description, the volume is mounted from the secret `tls-kafka-external` and the secret has the key `tls.key`. It is an unencrypted private key that worked with the previous version. The controller pods were upgraded fine but the broker pods fail with the following log statements - 
```
Creating keystore /tmp/kafka/custom-external-9094.keystore.p12
Could not find private key from -inkey file from /opt/kafka/certificates/custom-external-9094-certs/tls.key
```

The external listener is configured as follows - 
```yaml
     listeners:
     - name: external
        port: 9094
        type: ingress
        tls: true
        configuration:
          brokerCertChainAndKey:
            secretName: tls-kafka-external
            certificate: tls.crt
            key: tls.key
        authentication: # Omitted for brevity 
```
The cluster was working with version 3.8.0 but fails when upgraded to 3.9.0. **The cluster works if started with 3.9.0 with the exact same configuration/certs but not during upgrade.**

The cluster uses a custom image that adds tiered storage support. The base image version is set appropriately. The Dockerfile for reference - 
```Dockerfile
FROM quay.io/strimzi/kafka:latest-kafka-3.9.0

COPY build/distributions/tiered-storage-for-apache-kafka-*.tgz /opt/tiered-storage/

COPY storage/s3/build/distributions/s3-*.tgz /opt/tiered-storage/

USER root

RUN mkdir -p /opt/kafka/libs/tiered-storage-s3/core && \
    mkdir -p /opt/kafka/libs/tiered-storage-s3/s3 && \
    tar xf /opt/tiered-storage/tiered-storage-for-apache-kafka-*.tgz --strip-components=1 -C /opt/kafka/libs/tiered-storage-s3/core/ && \
    tar xf /opt/tiered-storage/s3-*.tgz --strip-components=1 -C /opt/kafka/libs/tiered-storage-s3/s3/ && \
    rm /opt/tiered-storage/tiered-storage-for-apache-kafka-*.tgz && \
    rm /opt/tiered-storage/s3-*.tgz

USER 1001

RUN mkdir /home/kafka/kafka-tiered-storage-cache
```

Strimzi version - 0.45.0
