### DISCUSSION TITLE
configure jdk.certpath.disabledAlgorithms

### DISCUSSION THREAD

**Discussion by jorgebo10** [strimzi/strimzi-kafka-operator#11459] [Q&A] [answered]
Hi, is there any way in strimzi to configure jdk.certpath.disabledAlgorithms=MD2, MD5 only ? I updated my cluster from 0.34.0 to 0.45.0 and having issues with SHA1withRSA, so i need to disable.

This is what i have in my pod after setting on version 0.45.0
```

jvmOptions:
    -Xms: 1g
    -Xmx: 4g
    javaSystemProperties:
    - name: jdk.certpath.disabledAlgorithms
      value: MD2,MD5
    - name: javax.net.debug
      value: ssl
```

grep jdk.certpath.disabledAlgorithms /usr/lib/jvm/java-17*/conf/security/java.security
```

#   jdk.certpath.disabledAlgorithms=MD2, DSA, RSA keySize < 2048
jdk.certpath.disabledAlgorithms=MD2, MD5, SHA1 jdkCA & usage TLSServer, \
# The syntax is the same as the "jdk.certpath.disabledAlgorithms" and
# See "jdk.certpath.disabledAlgorithms" for syntax descriptions.
# This is in addition to the jdk.certpath.disabledAlgorithms property above.
# See the specification of "jdk.certpath.disabledAlgorithms" for the
# See the specification of security property "jdk.certpath.disabledAlgorithms"
# jdk.certpath.disabledAlgorithms; those restrictions are still enforced even
```
