### DISCUSSION TITLE
In a ZooKeeper-based Kafka cluster, the KafkaNodePool role has to be always set only to the 'broker' role.

### DISCUSSION THREAD

**Discussion by ramilano** [strimzi/strimzi-kafka-operator#11464] [General]
Hello, I cannot migrate from zookeeper to kraft, I'using operator version 0.45 and this documentation
https://strimzi.io/blog/2024/03/22/strimzi-kraft-migration/

I added following annotations to kafka crd that I have deployed kafka

    strimzi.io/kraft: disabled
    strimzi.io/node-pools: enabled

then tried to deploy controller node pool, as documented in blog, but got this error:

The Kafka cluster common-kafka-cluster is invalid: [KafkaNodePool common-kafka-controller contains invalid roles configuration. In a ZooKeeper-based Kafka cluster, the KafkaNodePool role has to be always set only to the 'broker' role.]

**Comment by scholzj** [comment]
Please follow the docs, not a blog post that is over one year old. Also, you are missing the migration annotation (or you at least don't list it), so it is a regular ZooKeeper cluster, and controller nodes would not be supported at that point - that would be fully expected.

**Reply by scholzj** [reply]
(And if it does not work by following the docs, you should share the full custom resources, logs, and steps to reproduce.)

**Reply by ramilano** [reply]
thank you, yeah first I need to deploy kafkanodepool with broker role, 

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: common-kafka-broker
  namespace: common-infra
  labels:
    strimzi.io/cluster: common-kafka-cluster
spec:
  replicas: 3
  roles:
    - broker
```


then I need to deploy changes to create new kafkanodepool with controller and migration annotation

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: common-kafka-controller
  namespace: common-infra
  labels:
    strimzi.io/cluster: common-kafka-cluster
spec:
  replicas: 3
  roles:
    - controller
```

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: common-kafka-cluster
  namespace: common-infra
  annotations:
    strimzi.io/kraft: migration
    strimzi.io/node-pools: enabled
```
    
    
 then it start working
