### DISCUSSION TITLE
KafkaConnect rolling restart behavior

### DISCUSSION THREAD

**Discussion by swapsCAPS** [strimzi/strimzi-kafka-operator#11537] [Q&A]
Hi all!

I have question on the behavior of Strimzi Kafka Connect rebalances during rolling restarts.

While going through a/the [Kafka Connect book](https://www.oreilly.com/library/view/kafka-connect/9781098126520/) I found a section on rebalancing and how it's best to reduce the amount of rebalances in an attempt to reduce cluster strain and amount of stream pauses. It also goes into how you can tweak Connect so that during cluster restarts rebalances don't trigger as long as workers come back up _fast enough_ using `scheduled.rebalance.max.delay.ms`.

When triggering a rolling restart with Strimzi Connect in a 3 replica cluster (for example by changing a `spec.config`, or `spec.template.pod.annotations` value in a `KafkaConnect` resource) I see that tasks are immediately rebalanced to the other workers the moment one pod terminates. Am I observing this right? Is this expected behavior?
The potential issue that I see with this is that the moment worker 1 restarts, its tasks will get rebalanced to the other workers, which in turn will be restarted in the very near future. Causing what indeed looks like unnecessary rebalances; as work will need to be redistributed a couple of times during the roll.

If this is indeed the expected behavior (and it's not due to user error on my side) I would like to tweak the settings in such a way that a rebalance is not triggered if a worker comes up fast enough.
We are currently not setting `scheduled.rebalance.max.delay.ms` and assuming it will take [the default of 5min](https://kafka.apache.org/37/documentation.html#connectconfigs_scheduled.rebalance.max.delay.ms). Our pods come up `Ready` within 90secs, but we are still seeing the behavior described above. The rest of the settings related to rebalancing `session.timeout.ms` and `rebalance.timeout.ms` have sane defaults (according to the book and I tend to agree), so I'd rather not mess with those.

Cheers!

**TL;DR**
What is the expected rebalance behavior during a Strimzi Kafka Connect cluster restart?
Is it possible to prevent unnecessary rebalances when rolling a Strimzi Kafka Connect cluster?

**Comment by scholzj** [comment]
What version of Strimzi are you using? What is your configuration? Logs? Etc. In general, no, I do not think the tasks are expected to  be moved to other nodes during rolling updates.

**Reply by swapsCAPS** [reply]
Using Strimzi `0.45.0` with Kafka `0.45.0-kafka-3.8.1` based image.

### Config

```yaml
# connect-cluster.yaml
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: connect-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: "<snip>:0.45.0-kafka-3.8.1-v12"
  replicas: 2
  bootstrapServers: my-cluster-kafka-bootstrap.kafka:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        pattern: "*.crt"

  jmxOptions: {}
  config:
    config.providers: file,secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    group.id: connect-cluster
    offset.storage.topic: connect-offsets.01
    config.storage.topic: connect-configs.01
    status.storage.topic: connect-status.01

    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    connector.client.config.override.policy: All

    # https://kafka.apache.org/documentation.html#connect_plugindiscovery
    plugin.discovery: only_scan

  template:
    pod:
      metadata:
        annotations:
          # Bump this value to trigger a restart
          trigger-restart: "2025-06-16T14:43:07"
  logging:
    type: inline
    loggers:
      connect.root.logger.level: INFO
```

```yaml
# connectors.yaml
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: mysql-connector-10
  namespace: kafka
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSourceConnector
  tasksMax: 1
  autoRestart:
    enabled: true
  config:
    errors.log.enable: true
    errors.log.include.messages: true
    errors.tolerance: none

    # <snip>

---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: oracle-connector-01
  namespace: kafka
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSourceConnector
  tasksMax: 1
  autoRestart:
    enabled: true
  config:
    errors.log.enable: true
    errors.log.include.messages: true
    errors.tolerance: none
   # <snip>
```

### Log aggregation scripts:

Pods
```bash
k logs -f --tail 100000 -n kafka connect-cluster-connect-0 --prefix | grep -E "Kafka Connect worker initializing|Kafka Connect stopped|rebalance" > connect-cluster-connect-0.log
echo "DONE with first part"
sleep 10
k logs -f --tail 100000 -n kafka connect-cluster-connect-0 --prefix | grep -E "Kafka Connect worker initializing|Kafka Connect stopped|rebalance" >> connect-cluster-connect-0.log
```

Continuous port forwarding
```bash
while true; do;
    k -n kafka port-forward svc/connect-cluster-connect-api 8083:8083
    sleep 1
done
```

Connector status log
```bash
rm connector-status.log
while true; do
    now=`date -u "+%Y-%m-%dT%H:%M:%S"`
    echo $now >> connector-status.log
    curl -s 'localhost:8083/connectors?expand=status&expand=info' | jq '. | map_values(.status)' >> connector-status.log
    sleep 5
done
```

Trigger restart (Am I doing something erroneous here?)
```bash
gsed -i "s/trigger-restart.*/trigger-restart: \"$(date -u '+%Y-%m-%dT%H:%M:%S')\"/g" connect-cluster.yaml
k apply -f connect-cluster.yaml
```

I'm not sure how much use the logs will be. I have grepped fairly aggressively, please let me know if I should share more. 
In the `connector-status.log` it is quite apparent that right after I trigger a restart; worker 1 starts running both tasks.  
Restart triggered at `2025-06-16T14:43:07`. Worker running both tasks at `2025-06-16T14:43:21` [connector-status.log#134](https://github.com/user-attachments/files/20759459/connector-status.log#134)

What I also find suspicious is the `with rebalance delay: 0` message in the various `Joined group at generation` messages.

There might be a better way to debug this situation, simple unix tooling is what I resorted to for now, but would be interested in improvement points. I could theoretically spin up a Prometheus to generate some graphs.

[connect-cluster-connect-0.log](https://github.com/user-attachments/files/20759458/connect-cluster-connect-0.log)
[connect-cluster-connect-1.log](https://github.com/user-attachments/files/20759460/connect-cluster-connect-1.log)
[connector-status.log](https://github.com/user-attachments/files/20759459/connector-status.log)
