### DISCUSSION TITLE
[Bug]: ObservedGeneration in KafkaNodePool

### DISCUSSION THREAD

**Discussion by naveenthangaraj03** [strimzi/strimzi-kafka-operator#11601] [General]
### Bug Description

- If we try to change the CPU, Memory, Volume or Replica in kafkanodepool, then the field observedGeneration will change once the controller initiates the changes

### Expected behavior

- If we change the spec fields (CPU, Memory, Volume or Replica) in kafkanodepool then the observedGeneration field need to be changed after the controller finishes with the updates.

### Strimzi version

0.46.0

### Kubernetes version

Kubernetes 1.27

### Installation method

Yaml files

### Infrastructure

Bare-metal

### Configuration files and logs

- Before updating the cpu and memory

```
status:
  clusterId: SvuTau6TS6SAr4ADyX5DXA
  conditions: []
  labelSelector: strimzi.io/cluster=kafka-fi,strimzi.io/name=kafka-fi-kafka,strimzi.io/kind=Kafka,strimzi.io/pool-name=kafka-fi-dual-role
  nodeIds:
  - 0
  - 1
  - 2
  - 3
  - 4
  observedGeneration: 5
  replicas: 5
  roles:
  - controller
  - broker
```

- After updating the cpu and memory

```
status:
  clusterId: SvuTau6TS6SAr4ADyX5DXA
  conditions: []
  labelSelector: strimzi.io/cluster=kafka-fi,strimzi.io/name=kafka-fi-kafka,strimzi.io/kind=Kafka,strimzi.io/pool-name=kafka-fi-dual-role
  nodeIds:
  - 0
  - 1
  - 2
  - 3
  - 4
  observedGeneration: 6
  replicas: 5
  roles:
  - controller
  - broker
```

![image](https://github.com/user-attachments/assets/98b5785c-b7aa-4d3c-941d-b760a7f8b810)

- I had changed the cpu and memory for kafkanodepool but observedgeneration was updated once I initiated the update, it doesn't waited for the controller to finish the update, you can refer through the above image in that controller started to recreate the pod according to the update but only two pods are done but the observedgeneration is updated it doesn't waited for controller to finishes the update.
