### DISCUSSION TITLE
IdentityReplicationPolicy not working for MM2

### DISCUSSION THREAD

**Discussion by viopinto** [strimzi/strimzi-kafka-operator#4147] [Q&A]
I am trying to override automatic renaming by adding **IdentityReplicationPolicy** to the source connector configuration of the KafkaMirrorMaker2 resource such that the topics retain their original names.

The mirror maker configuration has the following source connector details:
```
      sourceConnector:
        config:
          replication.factor: 2
          offset-syncs.topic.replication.factor: 2
          sync.topic.acls.enabled: "true"
          refresh.groups.enabled: "true"
          refresh.topics.enabled: "true"
          replication.policy.class: "org.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
```

However, the mirrormaker is failing with the below error.
        **PUT /connectors/ns-mm-source-cluster->ns-mm-backup-cluster.MirrorSourceConnector/config returned 400 (Bad Request): Connector configuration is invalid and contains the following 1 error(s):
        Invalid value org.strimzi.kafka.connect.mirror.IdentityReplicationPolicy for configuration replication.policy.class: Class org.strimzi.kafka.connect.mirror.IdentityReplicationPolicy could not be found.
        You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`**

Need your inputs to have this resolved.
