### DISCUSSION TITLE
Create different port for each brokers AWS Loadbalancer

### DISCUSSION THREAD

**Discussion by bhushan558** [strimzi/strimzi-kafka-operator#4192] [General]
Hi, 
We are running 3 brokers in a cluster, I am trying to assign different port to each broker in AWS Loadbalancer. Below is the code, it creates 3 Loadbalancer, but opens up only 9094 port for each LB. I would like to have LB1 as port: 9094, LB2: 9095, LB3:9096. How can I achieve this. Thank you!

```
`apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
  namespace: kafka-strimzi
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    listeners:
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
      - name: external
        port: 9095
        type: loadbalancer
        tls: true
      - name: external
        port: 9096
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
    template:
      #...
      perPodService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0`
```
