### DISCUSSION TITLE
Cannot alter Kafka config after deployment

### DISCUSSION THREAD

**Discussion by tringuyen-yw** [strimzi/strimzi-kafka-operator#4255] [General]
Hi,

Using Strimzi 0.20.1, deploying a Kafka cluster with this config 

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: mykafka
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: true

    config:
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.6"
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
  zookeeper:
    replicas: 1
    livenessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    readinessProbe:
      initialDelaySeconds: 60
      timeoutSeconds: 5
    resources: {}
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
The deployment is successful. Notice service type `LoadBalancer` which allows external access on port 9094 as configured in the yaml above.

```
kubectl get services -n kafka

NAME                               TYPE           CLUSTER-IP     EXTERNAL-IP      PORT(S)
mykafka-kafka-0                    LoadBalancer   10.0.4.224     n1.n2.n3,a       9094:32209/TCP
mykafka-kafka-1                    LoadBalancer   10.0.77.34     n1.n2.n3,b       9094:30505/TCP
mykafka-kafka-2                    LoadBalancer   10.0.157.13    n1.n2.n3,c       9094:31811/TCP
mykafka-kafka-bootstrap            ClusterIP      10.0.30.74     <none>           9091/TCP,9092/TCP,9093/TCP
mykafka-kafka-brokers              ClusterIP      None           <none>           9091/TCP,9092/TCP,9093/TCP
mykafka-kafka-external-bootstrap   LoadBalancer   10.0.120.73    n1.n2.n3,d       9094:30905/TCP
mykafka-zookeeper-client           ClusterIP      10.0.4.178     <none>           2181/TCP
mykafka-zookeeper-nodes            ClusterIP      None           <none>           2181/TCP,2888/TCP,3888/TCP
```

Then I modify the yaml file to remove the external access, by commenting out the external listenter
```
...etc...
      #- name: external
      #  port: 9094
      #  type: loadbalancer
      #  tls: true
...etc...
```

Reconfigure the kafka cluster by `kubectl apply -f mykafkaconfig.yaml -n kafka`. When completed, `kubectl get services -n kafka` still shows the same output.

**QUESTION**: what is the recommended way to modify a Kafka cluster config? This could be the listeners as in this example. But this could be any property, such as `spec.kafka.config.log.retention.check.interval.ms`
