### DISCUSSION TITLE
strimzi kafka operator manages existing kafka

### DISCUSSION THREAD

**Discussion by lanzhiwang** [strimzi/strimzi-kafka-operator#4260] [General]
I directly deployed a kafka cluster using the kafka installation file, [kafka_2.12-2.5.0.tgz](https://www.apache.org/dyn/closer.cgi?path=/kafka/2.5.0/kafka_2.12-2.5.0.tgz). I specified the path on the physical machine `/kafka-zookeeper-data/kafka-0` as the log directory of kafka, and `/kafka-zookeeper-data/zookeeper-0` as the data directory of zookeeper, and then I created topics to produce and consume data.  In other words, I wrote some data in `/kafka-zookeeper-data/kafka-0` and `/kafka-zookeeper-data/zookeeper-0`.

In the second step, I created pv and pvc, and pv uses hostpath, `/kafka-zookeeper-data/kafka-0` and `/kafka-zookeeper-data/zookeeper-0`

```yaml
$ cat pv.yaml

apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-my-cluster-kafka-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /kafka-zookeeper-data/kafka-0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.34.46
  volumeMode: Filesystem
  storageClassName: local-path

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data-my-cluster-zookeeper-0
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /kafka-zookeeper-data/zookeeper-0
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - 192.168.34.46
  volumeMode: Filesystem
  storageClassName: local-path

$ cat pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-cluster-kafka-0
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pv-data-my-cluster-kafka-0

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-my-cluster-zookeeper-0
  namespace: kafka
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pv-data-my-cluster-zookeeper-0

```

Finally, I deployed the strimzi kafka operator and also created the kafka cluster.

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      log.message.format.version: "2.5"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    jmxOptions:
      "-Xms": 8192m
      "-Xmx": 8192m
    listeners:
      external:
        tls: false
        type: nodeport
      plain: {}
      tls: {}
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 500Mi
    storage:
      class: local-path
      deleteClaim: false
      size: 1Gi
      type: persistent-claim
    template:
      pod:
        securityContext:
          fsGroup: 0
          runAsUser: 0
    version: 2.5.0
  zookeeper:
    jmxOptions:
      "-Xms": 4096m
      "-Xmx": 4096m
    replicas: 1
    resources:
      limits:
        cpu: "1"
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 500Mi
    storage:
      class: local-path
      deleteClaim: false
      size: 1Gi
      type: persistent-claim
    template:
      pod:
        securityContext:
          fsGroup: 0
          runAsUser: 0

```

The kafka cluster can be successfully created, but I found that the operator cannot automatically discover the existing topic, and will not create a kafkatopic because of the topic in kafka itself. The data that has been written to the cluster cannot be consumed again.

I would like to ask if the operator does not support this scenario or the steps I have taken are wrong.

Can the operator manage an existing Kafka cluster ？
