### DISCUSSION TITLE
Why is the original pod restarted when increasing the number of Kafka replicas instead of directly adding new pods

### DISCUSSION THREAD

**Discussion by AllenZMC** [strimzi/strimzi-kafka-operator#4277] [Q&A] [answered]
Why is the original pod restarted when increasing the number of Kafka replicas instead of directly adding new pods ?
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.7.0
    replicas: 3
```
Will it affect the consumption of messages from topics?
