### DISCUSSION TITLE
Is it possible to mirror messages from multiple source cluster to single target cluster?

### DISCUSSION THREAD

**Discussion by JaeHyeokLee** [strimzi/strimzi-kafka-operator#4286] [Q&A] [answered]
Hi, I'm trying to copy data from multi source cluster. Can I use MirrorMaker2 yaml like below?
Or should I make multi MirrorMaker resources to mirror multi cluster's data?
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
spec:
  connectCluster: "targer-cluster"
  clusters:
  - alias: "source-cluster1"
    bootstrapServers: source-bootstrap-server-1
  - alias: "source-cluster2"
    bootstrapServers: source-bootstrap-server-2
  - alias: "source-cluster3"
    bootstrapServers: source-bootstrap-server-3   
  - alias: "target-cluster"
    bootstrapServers: target-bootstrap-server

 mirrors:
  - sourceCluster: "source-cluster1"
    targetCluster: "targer-cluster"
  - sourceCluster: "source-cluster2"
    targetCluster: "targer-cluster"   
  - sourceCluster: "source-cluster3"
    targetCluster: "targer-cluster" 
```
