### DISCUSSION TITLE
Expose Zookeeper JMX port for Datadog agent.

### DISCUSSION THREAD

**Discussion by raj-saxena** [strimzi/strimzi-kafka-operator#4287] [Q&A] [answered]
Hi,
We use Datadog for monitoring & the agent can auto-discover integrations based on annotations. [Details](https://docs.datadoghq.com/integrations/zk/?tab=containerized#setup)

So far, I have been successful in [enabling the Jmx port for kafka brokers](https://gist.github.com/raj-saxena/72d326ae7b73409a703908b500572ed2#file-strimzi-kafka-yaml-L74-L75) and [correctly marking](https://gist.github.com/raj-saxena/72d326ae7b73409a703908b500572ed2#file-strimzi-kafka-yaml-L13-L16) the pods so that Datadog can identify & pull metrics. ✅ 

I want to do the same for Zookeeper metrics and have added [similar marker annotations](https://gist.github.com/raj-saxena/72d326ae7b73409a703908b500572ed2#file-strimzi-kafka-yaml-L82-L86) to the Zookeeper pods. However, the Datadog check reports error possibly because the port is not open/reachable.
```sh
      Traceback (most recent call last):
        File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/zk/zk.py", line 248, in _send_command
          with closing(socket.create_connection((self.host, self.port))) as sock:
        File "/opt/datadog-agent/embedded/lib/python3.8/socket.py", line 808, in create_connection
          raise err
        File "/opt/datadog-agent/embedded/lib/python3.8/socket.py", line 796, in create_connection
          sock.connect(sa)
      TimeoutError: [Errno 110] Connection timed out
```

Unlike KafkaClusterSpec, there doesn't seem to be a [JmxOptions](https://strimzi.io/docs/operators/latest/using.html#property-kafka-jmx-reference) for Zookeeper. Please advise. 
Gist of our `Kafka.yaml` - https://gist.github.com/raj-saxena/72d326ae7b73409a703908b500572ed2

**Comment by scholzj** [comment]
The JMX access is currently supported only in Kafka brokers (and in 0.22.0 it will be added to Kafka Connect and Mirror Maker 2 as well). Historically, this has been always contributed by users - as maintainers we prefer to use the Prometheus endpoint for monitoring. So I think the JMX access to Zookeeper is waiting for someone to contribute it. If you would want to look into it, these are the PRs which added the KAfka and Kafka Connect JMS access:
* https://github.com/strimzi/strimzi-kafka-operator/pull/4096
* https://github.com/strimzi/strimzi-kafka-operator/pull/2268

**Comment by raj-saxena** [comment, marked as answer]
Update: Datadog supports Prometheus & OpenMetrics metrics collection - https://docs.datadoghq.com/agent/kubernetes/prometheus/

I added the following annotations to configure it:
```yaml
...
  kafkaExporter:
      # Annotations for Datadog JMX auto-discovery
    template:
      pod:
        metadata:
          annotations: 
            ad.datadoghq.com/my-cluster-kafka-exporter.check_names: '["openmetrics"]'
            ad.datadoghq.com/my-cluster-kafka-exporter.init_configs: '[{}]'
            ad.datadoghq.com/my-cluster-kafka-exporter.instances: |
              [
                {
                  "prometheus_url": "http://%%host%%:%%port%%/metrics",
                  "namespace": "my_kafka",
                  "metrics": ["go_gc_duration_seconds","go_goroutines","go_memstats_alloc_bytes","go_memstats_alloc_bytes_total","go_memstats_buck_hash_sys_bytes","go_memstats_frees_total","go_memstats_gc_sys_bytes","go_memstats_heap_alloc_bytes","go_memstats_heap_idle_bytes","go_memstats_heap_inuse_bytes","go_memstats_heap_objects","go_memstats_heap_released_bytes_total","go_memstats_heap_sys_bytes","go_memstats_last_gc_time_seconds","go_memstats_lookups_total","go_memstats_mallocs_total","go_memstats_mcache_inuse_bytes","go_memstats_mcache_sys_bytes","go_memstats_mspan_inuse_bytes","go_memstats_mspan_sys_bytes","go_memstats_next_gc_bytes","go_memstats_other_sys_bytes","go_memstats_stack_inuse_bytes","go_memstats_stack_sys_bytes","go_memstats_sys_bytes","kafka_brokers","kafka_consumergroup_current_offset","kafka_consumergroup_lag","kafka_exporter_build_info","kafka_topic_partition_current_offset","kafka_topic_partition_in_sync_replica","kafka_topic_partition_leader","kafka_topic_partition_leader_is_preferred","kafka_topic_partition_oldest_offset","kafka_topic_partition_replicas","kafka_topic_partition_under_replicated_partition","kafka_topic_partitions","process_cpu_seconds_total","process_max_fds","process_open_fds","process_resident_memory_bytes","process_start_time_seconds","process_virtual_memory_bytes"]
                }
              ]   
```
Soon, the metrics appeared in Datadog 🎉

**Reply by amitca71** [reply]
Hi, 
does anyone have experienced monitor without KafkaExporter. 
I use MSK and deployed strimzi KafkaConnect. I'm able to get the metrics, but was not able to see them in datadog (i followed the datadog tutorial, and it worked: https://docs.datadoghq.com/agent/kubernetes/prometheus/), but couldnt make it happen with the strimzi prometheous... i added the annotation part to the prometheus operator, but this didnt work. i tryed to add it to prometheus.yaml, but then i got : error: error validating "prometheus.yaml": error validating data: ValidationError(Prometheus.spec): unknown field "template" in com.coreos.monitoring.v1.Prometheus.spec; if you choose to ignore these errors, turn validation off with --validate=false
Thanks,
Amit

**Reply by iMajna** [reply]
I wouldn't really mark this reply as answer tho. @raj-saxena title is about exposing Zookeeper JMX port for datadog. You can easily export metrics for strimzi deployed Kafka + Zookeeper but port (9404) will be open only within pods therefore `openmetrics` integration wouldn't be able to collect metrics tho as it wouldn't be able to connect to the pods port. 

I'm not trying to un-approve your reply as it is correct for Kafka alone is you include `jmxOptions{}` within Kafka CR as that would expose port 9999 for either Kafka integration or OpenMetrics intergration. Yet again, not for Zookeeper.

Would be glad to be proven wrong as it would help me expose Zookeeper metrics to Datadog :)

**Reply by scholzj** [reply]
> You can easily export metrics for strimzi deployed Kafka + Zookeeper but port (9404) will be open only within pods therefore openmetrics integration wouldn't be able to collect metrics tho as it wouldn't be able to connect to the pods port.

The port 9404 is available from outside the ZooKeeper pods if you enable the Prometheus metrics. So you can connect to it and collect the metrics with anything what supports the format. So the answer should IMHO work.

In the mean time, I think that JMX support in ZooKeeper was now added as well, so you can use it as well.

**Reply by iMajna** [reply]
Thanks for replying btw! 

> The port 9404 is available from outside the ZooKeeper pods if you enable the Prometheus metrics

Hm, I thought this has been removed? I do have 

```
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-zk-metrics
```
and port `9404` can be seen but only within pod :O 
You do have to expose it via additional svc and then it is visible outside of pod - or there is another option (I believe using podMonitor is one?)?
