### DISCUSSION TITLE
0.21 - Allow configuring labels and annotations for Cluster CA certificate secrets

### DISCUSSION THREAD

**Discussion by jesussancheztellomm** [strimzi/strimzi-kafka-operator#4302] [Q&A] [answered]
Hello,
Could you please provide more info of how to add labels and annotations to the CA secrets?

I am unable to do it and can't find anything related to that in the docs.

When trying to add it via spec.kafka.clusterCaCert i get the following msg.

`2021-01-22 08:26:41 WARN  AbstractOperator:139 - Kafka resource kafka-lab-01 in namespace kafka-lab-01: Contains object at path spec.kafka with an unknown property: clusterCaCert`

Tried with:

```
kafka:
  clusterCaCert:
    metadata:
      annotations:
        anno2: val2
      labels:
        lab1: val1
```

Thanks in advance,
All the best

**Comment by scholzj** [comment, marked as answer]
You can use the `.spec.kafka.template` section for it: https://strimzi.io/docs/operators/latest/full/using.html#type-KafkaClusterTemplate-reference

I think your YAML is almost right, but it is missing the template part:

````yaml
kafka:
  template:
    clusterCaCert:
      metadata:
        annotations:
          anno2: val2
        labels:
          lab1: val1
```
