### DISCUSSION TITLE
Topic & broker config when using MirrorMaker2

### DISCUSSION THREAD

**Discussion by JaeHyeokLee** [strimzi/strimzi-kafka-operator#4304] [Q&A]
Hi, I'm using Mirrormaker2 and I am wondering if MirrorMaker mirrors topic settings or use target cluster's config.
Is topic's config(partitions, compression, retention setting etc.) same with `source cluster's topic configs` or `target cluster's broker config?`
Can I change topic config at MirrorMaker or target cluster's broker?

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
spec:
  connectCluster: "targer-cluster"
  clusters:
  - alias: "source-cluster1"
    bootstrapServers: source-bootstrap-server-1


 mirrors:
  - sourceCluster: "source-cluster1"
    targetCluster: "targer-cluster"
```
