### DISCUSSION TITLE
can it be done  one user binding  one topic?

### DISCUSSION THREAD

**Discussion by zhouxiaolong920** [strimzi/strimzi-kafka-operator#4321] [Q&A]
1. create a kafka cluster ===>ok
2. create one  kafka topic ===>ok
3. create one kafka user ===>ok

ask?:
can do ?  only one user<====binding====>only one topic
i have user   list,user1,   user2
i have topic  list,topic1 ,topic2
i want only user1 visit topic1,user2 visit topic2
i don't want one user consumer multiple topics

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.7.0
    replicas: 3
    listeners:
      external:
        type: nodeport
        tls: true
        authentication:
          type: scram-sha-512
    authentication:
      type: simple
    config:
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"
    resources:
      limits:
        cpu: "1"
        memory: 16Gi
      requests:
        cpu: "1"
        memory: 16Gi
    jvmOptions:
      -Xms: 8192m
      -Xmx: 8192m
    storage:
      type: jbod
      volumes:
      - id: 0
        class: mongo-storageclass
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    jvmOptions:
      -Xms: 2048m
      -Xmx: 2048m
    resources:
      limits:
        cpu: "2"
        memory: 4Gi
      requests:
        cpu: "2"
        memory: 4Gi
    storage:
      class: mongo-storageclass
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: zxl
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 10
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: my-user
  namespace: kafka
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: zxl
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: zxl
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read
        host: "*"
      # Example Producer Acls for topic zxl
      - resource:
          type: topic
          name: zxl
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: zxl
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: zxl
          patternType: literal
        operation: Describe
        host: "*"
```
