### DISCUSSION TITLE
Users with SASL + SSL

### DISCUSSION THREAD

**Discussion by fsouza-bux** [strimzi/strimzi-kafka-operator#4408] [Q&A] [answered]
Started to test a strimzi in order to migrate our current kafka deployments to it, and just noticed one thing regarding the listeners / users authentication.
We are mainly using SASL_SSL for the current listeners, so we use both SCRAM + TLS/SSL.
We got to push the listeners already in strimzi as SASL_SSL with the following below:

```
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
```

But it seems that with the current resource for the KafkaUser, either the auth is SCRAM or TLS, and by consequence the secret for the user ends up creating or the SCRAM auth or the whole set of certs and keys for the user.

Is there any way to use the resource to create a user + secret with both auth modes?

Thanks
