### DISCUSSION TITLE
How to configure jmx exporter to export kafka.mirror.connect JMX metrics?

### DISCUSSION THREAD

**Discussion by Sh1ftry** [strimzi/strimzi-kafka-operator#4443] [Q&A] [answered]
Hello,
I am using the [`kafka-mirror-maker-2-metrics.yaml`](https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/metrics/kafka-mirror-maker-2-metrics.yaml) example for exporting mirror maker 2 metrics using jmx exporter and it's working fine. However, it's missing metrics mentioned under [Public Interfaces in KIP-382: MirrorMaker 2.0](https://cwiki.apache.org/confluence/display/KAFKA/KIP-382%3A+MirrorMaker+2.0#KIP382:MirrorMaker2.0-PublicInterfaces):

>New metrics include:
> * replication-latency-ms(-avg/-min/-max): timespan between each record's timestamp and downstream ACK
> * record-bytes(-avg/-min/-max): size of each record being replicated
> * record-age-ms(-avg/-min/-max): age of each record when consumed
> * record-count: number of records replicated
> * checkpoint-latency-ms(-avg/-min/-max): timestamp between consumer group commit and downstream checkpoint ACK
>
> The mbean name for these metrics will be: kafka.mirror.connect:type=MirrorSourceConnect,target=([.\w]+),topic=([.\w]+),partition=([.\d]+) and kafka.mirror.connect:type=MirrorCheckpointConnector,target=([.\w]+),source=([.\w]+),group=([.\w]+)

I tried configuring it, but without any luck so far.
```yaml
    - pattern: kafka.mirror.connect<type=MirrorSourceConnect, target=(.+), topic=(.+), partition=(.+)><>([a-z-]+)
      name: kafka_mirror_source_connect_$4
      labels:
        target: "$1"
        topic: "$2"
        partition: "$3"
      help: "Kafka Mirror Source Connect JMX metrics"
      type: GAUGE
    - pattern: kafka.mirror.connect<type=MirrorCheckpointConnector, target=(.+), source=(.+), group=(.+)><>([a-z-]+)
      name: kafka_mirror_checkpoint_connector_$4
      labels:
        target: "$1"
        source: "$2"
        group: "$3"
      help: "Kafka Mirror Checkpoint Connector JMX metrics"
      type: GAUGE
```

Maybe you can spot some obvious mistake?
