### DISCUSSION TITLE
Disruption test caused error: /opt/kafka/kafka_run.sh: line 32: /tmp/password.file: Permission denied

### DISCUSSION THREAD

**Discussion by fsouza-bux** [strimzi/strimzi-kafka-operator#4460] [Q&A]
Hi guys,

In doing a small disruption test with our strimzi kafka cluster, and now we are getting an error related to permissions.
We have deleted one kafka broker pod, to check if it would recover, and it's not restarting anymore with the following error, related to permissions when starting the Pod, error is from the kafka-init initContainer:

```
+ JMX_ACCESS_FILE=/tmp/access.file
+ JMX_PASSWORD_FILE=/tmp/password.file
+ cat
+ cat
/opt/kafka/kafka_run.sh: line 32: /tmp/password.file: Permission denied
```
Looking at the other brokers the user running it is the user kafka, but with group root:
```
[kafka@kafka-kafka-1 kafka]$ id
uid=1001(kafka) gid=0(root) groups=0(root)
[kafka@kafka-kafka-1 kafka]$ ls -ltr /tmp/password.file
-r-------- 1 kafka root 34 Feb 17 21:09 /tmp/password.file
```

We are not using any custom images, and for storage we are creating the PVCs ahead of time, and we didn't include anything in the template related to the securityContext.
One additional info, the strimzi operator seems to not be pushing any updates we are doing to the cluster now, and it's throwing the following error message:

```
2021-02-23 12:26:00 WARN  AbstractOperator:379 - Reconciliation #80(timer) Kafka(kafka/kafka): Failed to acquire lock lock::kafka::Kafka::kafka within 10000ms.
```

Any ideas on how to get out of this deadlock situation? it seems that even when pushing new changes to the cluster it won't work as this reconcile is not being able to restart the pod.

Cheers,

Fernando

**Comment by fsouza-bux** [comment]
One additional update, i restarted the strimzi-operator, and it has passed through the first issue mentioned, but anyway it's erroring again, but now on a different point:
```
+ exec /usr/bin/tini -w -e 143 -- /opt/kafka/bin/kafka-server-start.sh /tmp/strimzi.properties
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /opt/kafka/kafka-request.log (Permission denied)
```
- Would that be related to the pre-created PVs / PVCs?
- is it mandatory to always push the security context to execute as root in certain cases?

I didn't change yet the securityContext but I'll be testing to see if the cluster recovers now and it's able to bring up the broker again.

Just to mention all version we are using now for these tests:
strimzi-kafka-operator: 0.21.1
k8s version (GKE): 1.18.12-gke.1206

**Reply by scholzj** [reply]
Can you share your Kafka CR and Strimzi version?

**Reply by fsouza-bux** [reply]
Hi Jakub, sure, strimzi version is 0.21.1 as stated above.

After one last change i think the problem now might be on one of the metrics we are putting in the jmx collector configmap:

```
+ exec /usr/bin/tini -w -e 143 -- /opt/kafka/bin/kafka-server-start.sh /tmp/strimzi.properties
[2021-02-23 13:15:58,310] INFO Starting KafkaAgent with brokerReadyFile=/var/opt/kafka/kafka-ready and sessionConnectedFile=/var/opt/kafka/zk-connected (io.strimzi.kafka.agent.KafkaAgent)
[2021-02-23 13:15:58,310] INFO Starting metrics registry (io.strimzi.kafka.agent.KafkaAgent)
[2021-02-23 13:15:58,589] INFO KafkaYammerMetrics found and will be used. (io.strimzi.kafka.agent.KafkaAgent)
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:513)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:525)
Caused by: java.lang.NullPointerException
	at java.base/java.util.TreeMap.putAll(TreeMap.java:312)
	at java.base/java.util.TreeMap.<init>(TreeMap.java:185)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.loadConfig(JmxCollector.java:219)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JmxCollector.<init>(JmxCollector.java:78)
	at io.prometheus.jmx.shaded.io.prometheus.jmx.JavaAgent.premain(JavaAgent.java:29)
	... 6 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at ./src/java.instrument/share/native/libinstrument/JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
```

Here's the kafka yaml (the #removed tags are for dns or ips we are including for the loadbalancer / listerners):

This deployment is including the changes in the security context, and after this the error above now is showing for the broker.

Deployment is being pushed through helm.

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  annotations:
    meta.helm.sh/release-name: kafka
    meta.helm.sh/release-namespace: kafka
  labels:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: kafka-0.1.0
  name: kafka
  namespace: kafka
spec:
  entityOperator:
    tlsSidecar:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
    topicOperator:
      logging:
        loggers:
          rootLogger.level: INFO
        type: inline
      reconciliationIntervalSeconds: 120
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
      watchedNamespace: kafka
    userOperator:
      logging:
        loggers:
          rootLogger.level: INFO
        type: inline
      reconciliationIntervalSeconds: 120
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
      watchedNamespace: kafka
  kafka:
    authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      background.threads: 10
      default.replication.factor: 3
      delete.topic.enable: "false"
      group.initial.rebalance.delay.ms: 3000
      log.cleaner.threads: 1
      log.retention.check.interval.ms: 300000
      log.retention.hours: -1
      log.segment.bytes: 1073741824
      min.insync.replicas: 2
      num.io.threads: 8
      num.network.threads: 3
      num.partitions: 1
      num.recovery.threads.per.data.dir: 1
      num.replica.fetchers: 2
      offsets.retention.minutes: 525600
      offsets.topic.replication.factor: 3
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 102400
      ssl.cipher.suites: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
      ssl.enabled.protocols: TLSv1.2
      ssl.protocol: TLSv1.2
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
      transactional.id.expiration.ms: 2147483647
      zookeeper.connection.timeout.ms: 6000
    jvmOptions:
      -XX:
        MaxDirectMemorySize: 512m
      -Xms: 3G
      -Xmx: 6G
    listeners:
    - authentication:
        type: scram-sha-512
      configuration:
        useServiceDnsDomain: true
      name: plain
      port: 9092
      tls: true
      type: internal
    - authentication:
        type: scram-sha-512
      name: tls
      port: 9093
      tls: true
      type: internal
    - authentication:
        type: scram-sha-512
      configuration:
        bootstrap:
          annotations:
            cloud.google.com/load-balancer-type: Internal
            external-dns.alpha.kubernetes.io/hostname: #removed
            external-dns.alpha.kubernetes.io/ttl: "300"
        brokerCertChainAndKey:
          certificate: ca.crt
          key: ca.key
          secretName: external-listener-ca
        brokers:
        - advertisedHost: #removed
          annotations:
            cloud.google.com/load-balancer-type: Internal
            external-dns.alpha.kubernetes.io/hostname: #removed
            external-dns.alpha.kubernetes.io/ttl: "300"
          broker: 0
        - advertisedHost: #removed
          annotations:
            cloud.google.com/load-balancer-type: Internal
            external-dns.alpha.kubernetes.io/hostname: #removed
            external-dns.alpha.kubernetes.io/ttl: "300"
          broker: 1
        - advertisedHost: #removed
          annotations:
            cloud.google.com/load-balancer-type: Internal
            external-dns.alpha.kubernetes.io/hostname: #removed
            external-dns.alpha.kubernetes.io/ttl: "300"
          broker: 2
        loadBalancerSourceRanges:
        - #removed
      name: external
      port: 9094
      tls: true
      type: loadbalancer
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    logging:
      name: kafka-broker-log4j-config
      type: external
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: jmx-broker-prometheus
          name: jmx-broker-config
    rack:
      topologyKey: topology.kubernetes.io/zone
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 3
    resources:
      limits:
        cpu: 2
        memory: 12Gi
      requests:
        cpu: 1500m
        memory: 8Gi
    storage:
      class: kafka-data
      deleteClaim: false
      size: 500Gi
      type: persistent-claim
    template:
      externalBootstrapService:
        metadata:
          annotations:
            cloud.google.com/load-balancer-type: Internal
      perPodService:
        metadata:
          annotations:
            cloud.google.com/load-balancer-type: Internal
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodetype
                  operator: In
                  values:
                  - kafka
        securityContext:
          fsGroup: 0
          runAsUser: 0
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: nodetype
          operator: Equal
          value: kafka
    version: 2.7.0
  zookeeper:
    config:
      initLimit: 20
      syncLimit: 10
      tickTime: 5000
    jvmOptions:
      -XX:
        MaxDirectMemorySize: 128m
      -Xms: 2G
      -Xmx: 4G
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    logging:
      name: kafka-zookeeper-log4j-config
      type: external
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: jmx-zookeeper-prometheus
          name: jmx-zookeeper-config
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 3
    resources:
      limits:
        cpu: 2
        memory: 5Gi
      requests:
        cpu: 500m
        memory: 3Gi
    storage:
      class: zookeeper-data
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodetype
                  operator: In
                  values:
                  - zookeeper
        securityContext:
          fsGroup: 0
          runAsUser: 0
        terminationGracePeriodSeconds: 10
        tolerations:
        - effect: NoSchedule
          key: nodetype
          operator: Equal
          value: zookeeper
```
