### DISCUSSION TITLE
How to add to topic list for KafkaUser

### DISCUSSION THREAD

**Discussion by barryzhounb** [strimzi/strimzi-kafka-operator#4533] [General]
In the following yaml file, it will create User dlake-topic. In this example, dlake-topic has permission for access topic dlake-topic. If dlake-user has a permission to access multiple topics, could I add a topic list? such as,  name: dlake-topic1, dlake-topic2, dlake-topic3

```
piVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: dlake-user
  namespace: abc
  labels:
    strimzi.io/cluster: dlake-cluster
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - host: '*'
        operation: All
        resource:
          name: dlake-topic
          patternType: literal
          type: topic
        type: allow
      - host: '*'
        operation: All
        resource:
          name: dlake-group
          patternType: literal
          type: group
        type: allow
      - host: '*'
        operation: All
        resource:
          name: dlake-cluster
          patternType: literal
          type: cluster
        type: allow
    type: simple
```
