### DISCUSSION TITLE
ssl connection issue to strimzi kafka

### DISCUSSION THREAD

**Discussion by Cshanmukh80** [strimzi/strimzi-kafka-operator#4560] [Q&A]
**I AM TRYING TO SET UP SSL CONNECTION TO STRIMZI KAFKA WITH SUPPORTING OF THE STRIMZI OPERATOR THROUGH HELM CHART**

The below is the yaml file of the kafka cluster

[strimzi-kafka-operator.zip](https://github.com/strimzi/strimzi-kafka-operator/files/6130073/strimzi-kafka-operator.zip)

[kafka.zip](https://github.com/strimzi/strimzi-kafka-operator/files/6130074/kafka.zip)

**my server.properties**

security.protocol=SSL
ssl.truststore.location=/tmp/kafka/kafka.truststore.jks
ssl.truststore.password=kafka123
ssl.keystore.location=/tmp/kafka/kafka.keystore.jks
ssl.keystore.password=kafka123
ssl.enabled.protocols=TLSv1.2
ssl.endpoint.identification.algorithm=
ssl.cipher.suites=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
ssl.protocol=TLSv1.2

**my service pod details**

![Screenshot from 2021-03-12 12-37-07](https://user-images.githubusercontent.com/80450247/110941324-2bcdbc80-835e-11eb-8329-8fd0c9e26930.png)

Even i have tried to edit the service port number of kafka with 9093 but it is not updating

i am getting below error

![Screenshot from 2021-03-12 12-34-22](https://user-images.githubusercontent.com/80450247/110941298-1f496400-835e-11eb-8d32-efb6dd229b2a.png)

can any one help me out

**Comment by scholzj** [comment]
You did not provided how your Kafka custom resource looks like. But from the template in the Helm Chart, you seem to be making up your own fields. You can use only the fields documented in the documentation. So for example this part should not be there:

```yaml
    containers: 
      volumeMounts:
      - name: server-prop
        mountPath: /tmp/strimzi/kafka/server.properties
        subPath: server.properties
      - name: kafka-trust
        mountPath: /tmp/strimzi/kafka/server.truststore.key
        subPath: kafka.truststore.key
      - name: kafka-key
        mountPath: /tmp/strimzi/kafk/server.keystore_1615469374.jks
        subPath: kafka.keystore.key
    volumes:
    - name: server-prop
      hostPath:
        path: /home/ist/Desktop/ELK/kafka/server.properties
    - name: kafka-trust
      hostPath: 
        path: /home/ist/Documents/certificates/server.truststore.jks
    - name: kafka-key
      hostPath: 
        path: /home/ist/Documents/certificates/server.keystore_1615469374.jks
```

Similarly, your configuration of health check probes does not follow the Strimzi API. The `entityOperator` section looks linke it is not even a valid YAML with the affinity, tolerations. The listeners configuration also does not seem valid. So I think first thing you should do is go through the documentation and make sure the Kafka CR it generates is a valid Kafka CR. You also need to share your actual YAML and not just the Helm Chart because it is not clear what exactly are you using in reality. You can for example do `kubectl get kafka -o yaml` to get it.

You should also run the client from a separate pod. It would be good to understand where / how did you got the stores with the certificates. But it is hard to say what the issue here is because your KAfka CR seems to be wrong on many places.
