### DISCUSSION TITLE
deprecated listeners

### DISCUSSION THREAD

**Discussion by barryzhounb** [strimzi/strimzi-kafka-operator#4670] [General]
I got the following warnings:

```
status:
  conditions:
    - lastTransitionTime: '2021-03-29T18:28:39+0000'
      status: 'True'
      type: Ready
    - lastTransitionTime: '2021-03-29T18:26:13.115674Z'
      message: >-
        In API version kafka.strimzi.io/v1beta1 the object kafkaListeners at
        path spec.kafka.listeners.kafkaListeners has been deprecated. This
        object has been replaced with GenericKafkaListener.
      reason: DeprecatedObjects
      status: 'True'
      type: Warning
    - lastTransitionTime: '2021-03-29T18:26:13.115674Z'
      message: >-
        Contains object at path spec.kafka.listeners.kafkaListeners.plain with
        unknown properties: type, port, tls
      reason: UnknownFields
      status: 'True'
      type: Warning
    - lastTransitionTime: '2021-03-29T18:26:13.115674Z'
      message: >-
        Contains object at path spec.kafka.listeners.kafkaListeners.tls with
        unknown properties: type, port, tls
      reason: UnknownFields
      status: 'True'
      type: Warning
```

It seem Operator is complaining listeners was deprecated, what is it for "listeners" if I need to fix this warning? 

```
kafka:
    authorization:
      type: simple
    config:
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      external:
        authentication:
          type: tls
        port: 9094
        tls: true
        type: route
      plain:
        port: 9092
        tls: false
        type: internal
      tls:
        authentication:
          type: tls
        port: 9093
        tls: true
        type: internal
```

**Comment by scholzj** [comment]
The configuration you have seems like a very weird mixture of the new format and the old format. 

Here are the docs for the conversion: https://strimzi.io/docs/operators/latest/full/deploying.html#con-upgrade-listeners-str ... that might be a good start. If you are on Strimzi 0.22, you can also use the conversion tool: https://strimzi.io/docs/operators/latest/full/deploying.html#proc-upgrade-cli-tool-files-str

Have a look at these and let me know if you have some more questions.

**Comment by barryzhounb** [comment]
Yes, I found these warnings after I update OpenShift version and AMQ version.  I have fixed the above warnings.

Now User definition had warnings in the status section as well, @scholzj , any ideas or suggestions for that?

```yaml
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
      - host: '*'
        operation: All
        resource:
          name: osprey-topic
          patternType: literal
          type: topic
        type: allow
      - host: '*'
        operation: All
        resource:
          name: osprey-group
          patternType: literal
          type: group
        type: allow
      - host: '*'
        operation: All
        resource:
          name: osprey-cluster
          patternType: literal
          type: cluster
        type: allow
    type: simple
status:
  conditions:
    - lastTransitionTime: '2021-03-29T20:29:43.694730Z'
      status: 'True'
      type: Ready
    - lastTransitionTime: '2021-03-29T20:29:43.378268Z'
      message: >-
        Contains object at path spec.authorization.acls.resource with unknown
        properties: name, patternType
      reason: UnknownFields
      status: 'True'
      type: Warning
  observedGeneration: 1
  secret: osprey-user
  username: osprey-user
```
