### DISCUSSION TITLE
Disable NetworkPolicy generation

### DISCUSSION THREAD

**Discussion by armisz** [strimzi/strimzi-kafka-operator#4799] [Q&A]
Hi,

Is there a way to disable the automatic NetworkPolicy generation for ZK and Kafka nodes?

By default, the generated NetworkPolicies grant general access to ZK and Kafka "technical" ports like 2181, 9091, 9404, 9999 to all other pods. I would like to limit this. Furthermore, I cannot specify networkPolicyPeers for the listener port 9093 upfront at the time when I deploy Kafka because in my setup client components contribute their own NetworkPolicies.

Thanks
Michael

**Comment by scholzj** [comment]
No, there is currently no way how to disable them.

> By default, the generated NetworkPolicies grant general access to ZK and Kafka "technical" ports like 2181, 9091, 9404, 9999 to all other pods. I would like to limit this. Furthermore, I cannot specify networkPolicyPeers for the listener port 9093 upfront at the time when I deploy Kafka because in my setup client components contribute their own NetworkPolicies.

I do not think this is completely true - ports 2181 in Zoo and 9091 are for sure not accessible from all other pods but limited to the Strimzi pods.

**Reply by armisz** [reply]
The generated NPs look like this on Strimzi 0.20.0:

Kafka
```
spec:
  ingress:
  - ports:
    - port: 9091
      protocol: TCP
  - ports:
    - port: 9093
      protocol: TCP
  - ports:
    - port: 9404
      protocol: TCP
  - ports:
    - port: 9999
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/name: my-cluster-kafka
  policyTypes:
  - Ingress
```

ZooKeeper
```
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          strimzi.io/name: my-cluster-zookeeper
    ports:
    - port: 2888
      protocol: TCP
    - port: 3888
      protocol: TCP
  - ports:
    - port: 2181
      protocol: TCP
  - ports:
    - port: 9404
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/name: my-cluster-zookeeper
  policyTypes:
  - Ingress
```

**Reply by armisz** [reply]
I have also a question related to the diagram in https://strimzi.io/docs/operators/latest/using.html#security-str
Which ports are accessed by the Cluster Operator?

**Reply by scholzj** [reply]
TBH, that is not how the network policy looks in my case ...

**Zookeeper:**

```yaml
ingress:
    - from:
      - podSelector:
          matchLabels:
            strimzi.io/name: my-cluster-zookeeper
      ports:
      - port: 2888
        protocol: TCP
      - port: 3888
        protocol: TCP
    - from:
      - podSelector:
          matchLabels:
            strimzi.io/name: my-cluster-kafka
      - podSelector:
          matchLabels:
            strimzi.io/name: my-cluster-zookeeper
      - podSelector:
          matchLabels:
            strimzi.io/name: my-cluster-entity-operator
      - podSelector:
          matchLabels:
            strimzi.io/kind: cluster-operator
      - podSelector:
          matchLabels:
            strimzi.io/name: my-cluster-cruise-control
      ports:
      - port: 2181
        protocol: TCP
    - ports:
      - port: 9404
        protocol: TCP
```

I.e. ...
* Ports 2888 and 3888 are used only internally by Zookeeper so only Zookeeper pods have access
* Port 2181 is used by other Strimzi components as well - operators, Kafka etc.
* Port 9404 (metrics) is open for everyone

**Kafka:**

```yaml
    ingress:
    - from:
      - podSelector:
          matchLabels:
            strimzi.io/kind: cluster-operator
      - podSelector:
          matchLabels:
            strimzi.io/name: my-cluster-kafka
      - podSelector:
          matchLabels:
            strimzi.io/name: my-cluster-entity-operator
      - podSelector:
          matchLabels:
            strimzi.io/name: my-cluster-kafka-exporter
      - podSelector:
          matchLabels:
            strimzi.io/name: my-cluster-cruise-control
      ports:
      - port: 9091
        protocol: TCP
    - ports:
      - port: 9092
        protocol: TCP
    - ports:
      - port: 9093
        protocol: TCP
    - ports:
      - port: 9094
        protocol: TCP
    - ports:
      - port: 9404
        protocol: TCP
```

I.e. ...
* Port 9091 is accessible only by Strimzi components, operators, Kafka Exporter, Cruise Control etc.
* Ports 9092, 9093, 9094 are user listeners without any configured peers and are accessible to everyone by default
* 9404 (metrics) is accessible to everyone

> Which ports are accessed by the Cluster Operator?

9091 on Kafka and 2181 on Zookeeper
