### DISCUSSION TITLE
Changing jmx prometheus exporter metrics config from legacy to new format does not update kafka statefulset

### DISCUSSION THREAD

**Discussion by gregwhorley** [strimzi/strimzi-kafka-operator#4804] [Q&A]
Using `strimzi-kafka-operator 0.21.1`, we had the jmx prometheus exporter configuration set since `0.20.0` in what is now referred to as the legacy format:

```yaml
spec:
  kafka:
    metrics:
      rules:
        lowercaseOutputName: true
        - pattern: ...
```

Which, from what I can tell, adds a volume mount to the `kafka` statefulset that points at a `kafka-kafka-config` configmap keyed on `metrics-config.yml` whose value is the json representation of the settings and rules underneath `metrics:`. At first, I was trying to update the existing ruleset and add new rules within the `kafka` helm template, which was applied via helm terraform provider without a problem. Getting a manifest of the strimzi helm release afterwards shows the new rule set as expected, but the `kafka-kafka-config` configmap was not updated.

After looking at issues in the `strimzi-kafka-operator` repo, I noticed that we were using an old format and thought I should try changing to the new one:

```yaml
spec:
  kafka:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yaml
```

With a separate helm template file that defines the configmap with the rules I wanted:

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-metrics
  labels:
    app: strimzi
data:
  kafka-metrics-config.yaml: |
    lowercaseOutputName: true
    rules:
    - pattern ...
```

Which also applied without a problem and the new Helm release revision manifest shows the new configmap and metrics config. Also, the configmap was created successfully with the key and value I expected. However, the `kafka` statefulset still was not updated and had the old volume mount pointing at the old configmap and key.

What am I missing?
