### DISCUSSION TITLE
cannot deploy custom images for KafkaConnect from private image repo using Strimzi operator

### DISCUSSION THREAD

**Discussion by igorpalant** [strimzi/strimzi-kafka-operator#4880] [Q&A]
I have built a custom kafka connect image that includes our required connectors. I am trying to deploy kafkaconnect resource using custom image that is located in our private repo. It seems that instructions imagePullPolicy and imagePullSecret do not get processed by strimzi and image cannot be downloaded from our private repo. I might be missing something. I could not find a good place to look, other than CRDs. Please help

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: oc-platform-kafka-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: ourrepo/mongodb-kafka-connector:1.0.1
  imagePullPolicy: Always
  imagePullSecret: our-secret
  replicas: 1
  bootstrapServers: platform-kafka-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: platform-kafka-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
```
