### DISCUSSION TITLE
Defining networkPolicyPeers in Kafka resource

### DISCUSSION THREAD

**Discussion by berndkuennen** [strimzi/strimzi-kafka-operator#4885] [Q&A] [answered]
Hi everybody,,

we've installed Strimzi 0.20.0 via helm chart and it's running fine so far. Now we'd like to manage topics etc. with lenses.io which is deployed to an own namespace. Lenses is able to connect to all services except the Zookeeper. As we found out, access to ZK is disabled for pods outside the Strimzi namespace.

Manipulating the network policy manually does work, just for a couple of seconds, of course, by adding a namespace selector:
```
    - namespaceSelector:
        matchLabels:
          name: my-lenses-namespace
```

We now tried to permanently enable access for pods from the lenses namespace by adding an entry to the ZK network policy via the kafka resource. Unfortunately, we did only find documentation about doing so for Kafka itself, so we tried the same pattern on Zookeeper - which fails:

```
  zookeeper:
    listeners:
    - name: plain
      networkPolicyPeers:
      - namespaceSelector:
          matchLabels:
            name: lenses
      port: 2181
      tls: false
      type: internal
```

This does not add an entry to the Zookeeper network policy.

How is an additional entry to be defined in the Kafka resource?
