### DISCUSSION TITLE
kafka pods will not deploy with type set to "loadbalancer"

### DISCUSSION THREAD

**Discussion by davehouser1** [strimzi/strimzi-kafka-operator#4915] [General]
**Problem:** 
When I deploy strimzi as a loadbalancer type, the zookeeper pods will deploy, but the kafka pods will never deploy. I see no way to check status to see why they never deploy. The External-IPs for for each "service/my-cluster-kafka-INTEGER", and the "service/my-cluster-kafka-external-boostrap" all show PENDING but never change.

**Trouble shooting:**
- I can create and delete strimzi as a nodePod type with no problems. This works.
- I read through the documentation [here](https://strimzi.io/blog/2019/05/13/accessing-kafka-part-4/). 

This section seems interesting:
_"After Strimzi creates the load balancer type Kubernetes services, the load balancers will be automatically created. Most clouds will automatically assign the load balancer some DNS name and IP addresses. These will be automatically propagated into the status section of the Kubernetes service. trimzi will read it from there and use it to configure the advertised address in the Kafka brokers."_
First of all, I am running this in a lab, not using cloud, so I control all DNS and configurations manually. I have done no such configurations (that I know of) Is this the issue? How would one configure these values manually?

The document goes on to read:
_"for example when for whatever reason the DNS resolution doesn’t work for your Kafka clients. In that case you can override the advertised hostnames in the Kafka custom resource."_
Questions: What is performing DNS resolution, and for what? The node IPs? what is the actual dig for resolution? where is it used? This maybe apparent in a cloud env, but does not make sense to me in my lab. Also its not clear what which DNS host resolver your referring to. Do you mean the internal kubernets dns driver? (I am using Calico in my case), or my actual external DNS servers for all hosts? Either way I tried to configure "advertisedHost" with FQDN of the nodes, thried their IPs, then tried unused ips and FQDN entries for those either. 

Strimzi never seems to build the kafka brokers with type set to "loadbalancer". Is there someway I can check on the status of the job? What am I missing?

Here is my configuration file I am using.

```
piVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls 
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls 
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          brokers:
          - broker: 0
            advertisedHost: kafka-broker-01.domain.internal
          - broker: 1
            advertisedHost: kafka-broker-02.domain.internal
          - broker: 2
            advertisedHost: kafka-broker-03.domain.internal
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        class: unity-iscsi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      class: unity-iscsi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
