### DISCUSSION TITLE
Strimzi prometheus server pod refuses to deploy

### DISCUSSION THREAD

**Discussion by davehouser1** [strimzi/strimzi-kafka-operator#4937] [General]
I am following the instructions found [here](https://strimzi.io/docs/operators/latest/full/deploying.html#proc-metrics-deploying-prometheus-str)
Also I found an online blog with exact commands used found [here](https://dzone.com/articles/grafana-and-prometheus-setup-with-strimzi-aka-kafk)

I am able to deploy everything up to `kubectl -n kafka apply -f prometheus.yaml`. After doing so, kubernetes shows 
```
clusterrole.rbac.authorization.k8s.io/prometheus-server created
serviceaccount/prometheus-server created
clusterrolebinding.rbac.authorization.k8s.io/prometheus-server created
prometheus.monitoring.coreos.com/prometheus created
```

However, nothing happens. no logs, no events, no pods, no services are created. I see nothing. I am using the same files the blog poster uses which are the same exact files that are in the Strimzi repo. I thought his maybe because of load balacning or some other rule I configured on my custom deployment, therefore I tried deploying my zk/kafka cluster with just a vanilla ephemeral deployment. Still nothing. 
Why does a prometheus-server pod never get deployed?

Here is the manifest I am using for promethus.yaml

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-server
  labels:
    app: strimzi
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-server
  labels:
    app: strimzi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-server
  labels:
    app: strimzi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-server
subjects:
  - kind: ServiceAccount
    name: prometheus-server
    namespace: kafka


---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: strimzi
spec:
  replicas: 1
  serviceAccountName: prometheus-server
  podMonitorSelector:
    matchLabels:
      app: strimzi
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  ruleSelector:
    matchLabels:
      role: alert-rules
      app: strimzi
  alerting:
    alertmanagers:
    - namespace: kafka
      name: alertmanager
      port: alertmanager
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
```
