### DISCUSSION TITLE
I am trying to figure out how to modify the quick start example to use a storageclass

### DISCUSSION THREAD

**Discussion by davesargrad** [strimzi/strimzi-kafka-operator#4959] [Q&A]
My storage class is seen below "rook-nfs-share1"

```
[dsargrad@chad rook]$ k get storageclass
NAME                      PROVISIONER                        RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-storage (default)   kubernetes.io/no-provisioner       Delete          WaitForFirstConsumer   false                  42d
rook-nfs-share1           nfs.rook.io/rook-nfs-provisioner   Delete          Immediate              false                  19h

```

Typically the way that I would define a PVC that uses this storage class I would to the following:

```
cat << EOF > nfs-pvc-dyn-example.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rook-nfs-pv-claim
spec:
  storageClassName: "rook-nfs-share1"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
 
EOF
```

Then I'd reference that as follows:

![image](https://user-images.githubusercontent.com/48793689/118120605-26bcd600-b3be-11eb-8417-1245a05fa0fd.png)

The strmzi example for establishing a single node kafka is as follows:

```
cat << EOF > kafka.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
 
EOF
```
This example references a storage type "jbod", in addition to a type persistent-claim. However it does not seem to allow me to specify a storage class or a named PVC.  When I use this the cluster never starts since it pends on the binding of a PVC.

How would I modify this to reference a PVC (or perhaps 2 PVC's - one for zookeeper) such as **rook-nfs-pv-claim** above, that uses my storage class **rook-nfs-share1**?
