### DISCUSSION TITLE
Enable mutual TLS authentication (Internal)

### DISCUSSION THREAD

**Discussion by shreyasarani23** [strimzi/strimzi-kafka-operator#4992] [General]
I want to enable mutual TLS authentication between my kafka broker and my kafka user. 
Below is the configuration of my kafka broker:
 listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    authorization:
      type: simple

Below is the configuration of my kafka user:
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Describe
        host: "*"

Now how do I tell my kafka broker to validate the client certificate and vice versa [i.e. client should validate broker certificate]. I know that when I deploy KafkaUser it creates a new Secret with the same name as the KafkaUser resource. How to use this secret?

Exactly where in the yaml file should I specify the details of my broker certificate and client certificate?
Please help

**Comment by scholzj** [comment]
Please use the Markdown code formatting to made the YAML snippets more readable. This way, it is hard to see the alignment, whitespaces etc. So I cannot tell if you have it right or wrong. Also, did you checked the docs? I think this is all covered there.

**Reply by shreyasarani23** [reply]
Sorry for the inconvenience.
Below is my kafka broker configuration:
```
listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
```
And this is my kafka user yaml file:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: new-topic
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: new-topic
          patternType: literal
        operation: Describe
        host: "*"

      - resource:
          type: topic
          name: new-topic
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: new-topic
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: new-topic
          patternType: literal
        operation: Describe
        host: "*"
```
In the documentation I couldn't find how they have used these certificates to validate the broker and client. I mean where we have to specify the details of these certificates, details in the sense [.crt,key etc]. It would be helpful for me If you can explain how to achieve this .
