### DISCUSSION TITLE
Topic and user Access using TOPIC and USER operator

### DISCUSSION THREAD

**Discussion by kmandal-volvo** [strimzi/strimzi-kafka-operator#5005] [Q&A]
I have ` Topic A ` and ` User B `  configured to access ` Topic A `, define ACL for necessary operation. This is deployed once the application user. I have ` Topic C `  and  ` User D ` configured to access ` Topic C ` ,  ACL define for necessary operation. This is deployed for another application user. This is working fine but my requirement is the first application ` User B `  once to provide access to ` Topic A ` to the user of another application ` User D ` . While configure getting working ` Kafkauser/D ` is part of a different application.

First application Deployment for user done this way.
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: B
  labels:
    strimzi.io/cluster: vcc-external-esp
spec:
  partitions: 10
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: B
  labels:
    strimzi.io/cluster: vcc-external-esp
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: A
          patternType: literal
        operation: Read
      - resource:
          type: group
          name: A
          patternType: literal
        operation: Read
```

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: D
  labels:
    strimzi.io/cluster: vcc-external-esp
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: A
          patternType: literal
        operation: Read
      - resource:
          type: group
          name: A
          patternType: literal
        operation: Read
```

Second application Deployment for user done this way.
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: C
  labels:
    strimzi.io/cluster: vcc-external-esp
spec:
  partitions: 10
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: D
  labels:
    strimzi.io/cluster: vcc-external-esp
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: C
          patternType: literal
        operation: Read
      - resource:
          type: group
          name: C
          patternType: literal
        operation: Read
```
