### DISCUSSION TITLE
Not getting alerts when one my kafka broker is down

### DISCUSSION THREAD

**Discussion by shreyasarani23** [strimzi/strimzi-kafka-operator#5016] [General]
Hi I have followed the steps in this link https://strimzi.io/docs/operators/latest/deploying.html#assembly-metrics-str . And below is the configuration of alert-manager-config file.
```
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-alertmanager
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 1m

    route:
      receiver: 'gmail-notifications'

    receivers:
    - name: 'gmail-notifications'
      email_configs:
      - to: abc@gmail.com
        from: abc@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: abc@gmail.com
        auth_identity: abc@gmail.com
        auth_password: app-password
        send_resolved: true
```
But I am not getting any alerting mails when one of my kafka broker/zookeeper pod/entity operator/user operator is down. Please tell me if there is anything wrong in my configuration or any additional things need to be specified?
