### DISCUSSION TITLE
connecting-apicurio-registry on Strimzi cluster

### DISCUSSION THREAD

**Discussion by kmandal-volvo** [strimzi/strimzi-kafka-operator#5047] [General]
I am trying to bring to Apicurio schema registry capability in our Strimzi Kafka cluster. As much I understand Apicurio schema registry CRD is available in the 0.20 version of Strimzi. I am not getting the pod after configuring the below template, please suggest or if any standard template is available provide me that as well.

```
apiVersion: apicur.io/v1alpha1
kind: ApicurioRegistry
metadata:
  name: service-registry
spec:
  configuration:
    persistence: "streams"
    streams:
      bootstrapServers: "vcc-test-kafka-bootstrap:9092"
```
