### DISCUSSION TITLE
scram-sha-512 authentication

### DISCUSSION THREAD

**Discussion by sleepdan** [strimzi/strimzi-kafka-operator#5061] [Q&A] [answered]
Hello everyone! I want to set up authentication using scram-sha-512. Here is my config:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: user1
  labels:
    strimzi.io/cluster: acl-test
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Write
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read
```
The documentation says that "When the user is created by the User Operator, it creates a new secret with the same name as the KafkaUser resource.", But in my case Secrets is not created:
```
#kubectl -n acl-test get kafkausers.kafka.strimzi.io 
NAME    CLUSTER    AUTHENTICATION   AUTHORIZATION   READY
user1   acl-test   scram-sha-512    simple          
# kubectl -n acl-test get secrets 
NAME                                     TYPE                                  DATA   AGE
default-token-ml5nz                      kubernetes.io/service-account-token   3      149m
my-cluster-clients-ca                    Opaque                                1      148m
my-cluster-clients-ca-cert               Opaque                                3      148m
my-cluster-cluster-ca                    Opaque                                1      148m
my-cluster-cluster-ca-cert               Opaque                                3      148m
my-cluster-cluster-operator-certs        Opaque                                4      148m
my-cluster-entity-operator-certs         Opaque                                4      146m
my-cluster-entity-operator-token-m99gm   kubernetes.io/service-account-token   3      146m
my-cluster-kafka-brokers                 Opaque                                4      147m
my-cluster-kafka-token-w2gr8             kubernetes.io/service-account-token   3      147m
my-cluster-zookeeper-nodes               Opaque                                4      148m
my-cluster-zookeeper-token-8rb4p         kubernetes.io/service-account-token   3      148m
strimzi-cluster-operator-token-gcbfz     kubernetes.io/service-account-token   3      149m
```
And it also seems strange to me that the Ready field of kafkauser is empty. 
So the question is, why isn't the secret being generated?

I've tried creating the secret manually, this way:
```
apiVersion: v1
kind: Secret
metadata:
  name: user1
  labels:
    strimzi.io/kind: KafkaUser
    strimzi.io/cluster: my-cluster
type: Opaque
data:
  password: cGFzc3dvcmQK
  sasl.jaas.config: b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkuc2NyYW0uU2NyYW1Mb2dpbk1vZHVsZSByZXF1aXJlZCB1c2VybmFtZT11c2VyMSBwYXNzd29yZD1wYXNzd29yZDsK
```
And trying to connect using kafka-console-producer with the following config file:
```
# cat client.cfg 
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=user1 password=password;

# ./bin/kafka-console-producer.sh --bootstrap-server 100.127.240.4:32452 --producer.config client.cfg --topic my-topic
```
but I get an authorization error
```
ERROR [Producer clientId=console-producer] Connection to node -1 (100.127.240.4/100.127.240.4:32452) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512 (org.apache.kafka.clients.NetworkClient)
```
Please tell me what could be the error? Maybe there is a step-by-step instruction with the same setup example?

**Comment by scholzj** [comment, marked as answer]
The `strimzi.io/cluster` label on your `KafkaUser` resource needs to match the name of your Kafka cluster which is `my-cluster` and not `acl-test`.

**Reply by sleepdan** [reply]
Oh, this is my fault! such an obvious mistake, sorry!!

**Reply by sleepdan** [reply]
another small question: how can you set your own password for the user?

**Reply by scholzj** [reply]
If you create the secret before the KafkaUser resource, it should take over the password from it.

**Reply by sleepdan** [reply]
I tried with password "hello":
```
# cat create_secret 
apiVersion: v1
kind: Secret
metadata:
  name: user1
  labels:
    strimzi.io/kind: KafkaUser
    strimzi.io/cluster: my-cluster
type: Opaque
data:
  password: aGVsbG8K
  sasl.jaas.config: b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkuc2NyYW0uU2NyYW1Mb2dpbk1vZHVsZSByZXF1aXJlZCB1c2VybmFtZT11c2VyMSBwYXNzd29yZD1oZWxsbzsK
```
in .data.password must be in base64? 

After create user with name user1 (same config as my first message), and try produce message in topic with config:
```
# cat client.cfg 
group.id=my-group
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=user1 password=hello;
```
but got error
`ERROR [Producer clientId=console-producer] Connection to node -1 (100.127.240.4/100.127.240.4:32452) failed authentication due to: Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512 (org.apache.kafka.clients.NetworkClient)`
