### DISCUSSION TITLE
How to get ordered delivery of messages at consumer side?

### DISCUSSION THREAD

**Discussion by shreyasarani23** [strimzi/strimzi-kafka-operator#5097] [General]
Hi @scholzj 
Following is my topic configuration
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  partitions: 3
  replicas: 2
  config:
    min.insync.replicas: 1
    retention.ms: -1
    segment.bytes: 1073741824
```
I have produced records into the topic by using following properties
```
enable.idempotence=true
max.in.flight.requests.per.connection=5
acks=all
retries=2147483647
```
```
[kafka@my-kafka-cluster-kafka-0 kafka]$ bin/kafka-console-producer.sh --topic test-topic --bootstrap-server my-kafka-cluster-kafka-bootstrap:9092 --producer-property acks=all --producer-property enable.idempotence=true --producer-property max.in.flight.requests.per.connection=5 --producer-property retries=2147483647
>1
>2
>3
>4
>5
>6
>7
[kafka@my-kafka-cluster-kafka-0 kafka]$ bin/kafka-console-consumer.sh --topic test-topic --from-beginning --bootstrap-server my-kafka-cluster-kafka-bootstrap:9092
3
6
1
2
4
5
7
```
Here the problem is that even though using enable.idempotence=true but at the consumer side I am not getting ordered delivery of messages. At the consumer side I want the output to be 1234567. Please help is there additional configuration required?
