### DISCUSSION TITLE
Kafka Connect custom image build questions

### DISCUSSION THREAD

**Discussion by davehouser1** [strimzi/strimzi-kafka-operator#5113] [General]
I am trying to deploy kafka connect with a custom plugin.
I read though this link [here ](https://strimzi.io/blog/2021/03/29/connector-build/), and section 4.2.3 [here](https://strimzi.io/docs/operators/latest/full/deploying.html#using-kafka-connect-with-plug-ins-str)

I also found documentation on the parameters for the build process [here](https://github.com/strimzi/strimzi-kafka-operator/blob/f2ce3ea17c28846ad61640df55f46231a4cea17f/documentation/api/io.strimzi.api.kafka.model.connect.build.Build.adoc)

Few things:
- It is not clear to me if a repo needs to be created a head of time on our private registry before trying to create the build. The name "output" implies that after Kafka Connect custom build is created it will be placed into the repo defined in "image". Must the repo specified in spec.build.output.image be created ahead of time? or will Kafka Connect build create the image and deposit it in the specified location?
- I am trying to use a private repo with this syntax `https://10.10.10.10:443/v2/my-connect-cluster:latest`, I think this is supported but the examples in the last document I shared do not include 'https://' will this syntax work?
- The last document states that pushSecret is required. Our private docker repo has no password. Is there some work around where I can make this manifest run without a password?

**Comment by scholzj** [comment]
> It is not clear to me if a repo needs to be created a head of time on our private registry before trying to create the build. The name "output" implies that after Kafka Connect custom build is created it will be placed into the repo defined in "image". Must the repo specified in spec.build.output.image be created ahead of time? or will Kafka Connect build create the image and deposit it in the specified location?

I do not think there is any standard for creating container repositories. So it all depends on your container registry. Some would auto-create the repository when you try to push to it. Some would not. So it depends. In general, creating it ahead should not cause any harm.

> I am trying to use a private repo with this syntax https://10.10.10.10:443/v2/my-connect-cluster:latest, I think this is supported but the examples in the last document I shared do not include 'https://' will this syntax work?

I do not think the `https://` should be included. I never used it when referencing Docker images. But not sure what happens if you use it, I do not think I ever tested it.

> The last document states that pushSecret is required. Our private docker repo has no password. Is there some work around where I can make this manifest run without a password?

That would be a bug if it says it is required. The push secret is needed only if your repository requires authentication. If it doesn't as you mentioned it should not be needed.

**Reply by davehouser1** [reply]
Ok I removed the "https://", and commented out the push secret. Here is what it looks like now 

```
piVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
spec:
  version: 2.7.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: tls 
    certificateAndKey:
      secretName: my-connect
      certificate: user.crt
      key: user.key
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
  build:
    output:
      type: docker
      image: 10.10.10.10:443/v2/my-connect-cluster:latest
      # pushSecret:
    plugins:
      - name: splunk-connect
        artifacts:
          - type: jar 
            url: https://github.com/splunk/kafka-connect-splunk/releases/download/v2.0.2/splunk-kafka-connect-v2.0.2.jar
            sha512sum: 72b9ca1162246d3b8173365d9089a651748da6e659dc24c1fdf28e4e8bf0cd4bf5a4ea95262716f27615a5724fcb6a44f574368e85f9e65ae0710886eff5e72e
```

And here is the error I see from the container's logs:

```
# kubectl -n kafka logs my-connect-cluster-connect-build
E0610 13:16:12.638994       1 aws_credentials.go:77] while getting AWS credentials NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

Any ideas how to avoid this when working with a private registry?

**Reply by scholzj** [reply]
So, did the build failed?

**Reply by davehouser1** [reply]
Yes, the build failed. Went into "Error"

**Reply by scholzj** [reply]
I never had this problem - neither with private nor with public registries. So not sure what is causing it. That looks like it finds some AWS credentials in your environments which it does not understand or something?

**Reply by scholzj** [reply]
The builder is based on Kaniko (https://github.com/GoogleContainerTools/kaniko). There seem to be some similar issues there. Maybe some of that would help.

**Reply by davehouser1** [reply]
Ok thanks @scholzj , I will do some research on the Kaniko page. Will report back if I get any updates.

**Reply by davehouser1** [reply]
I found two posts [here](https://github.com/GoogleContainerTools/kaniko/issues/1270) and [here ](https://github.com/GoogleContainerTools/kaniko/issues/1287).
There is references to the file /aws/aws_credentials.go in the kaniko source.
I checked the strimzi repo but did not seem to find it. Does this file exist or is the source found somewhere in the strimzi repo?

**Reply by scholzj** [reply]
Strimzi doesn't have it's own Kaniko source codes. We use Kaniko as it is.

**Reply by davehouser1** [reply]
Getting a little further with this. Had to adjust the ip to the fqdn. I get this error now:

```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "docker-registry.company.internal:443/v2/my-connect-cluster:latest": creating push check transport for docker-registry.company.internal:443 failed: Get "https://docker-registry.company.internal:443/v2/": x509: certificate signed by unknown authority
```

Is there a way I can load our root CA's public key to Strimzi so it trusts our docker-registry's cert (Signed by the internal CA)?

**Reply by scholzj** [reply]
No, not right now. You would need to use one of the `--skip-tls-verify...` options I guess.

**Reply by davehouser1** [reply]
I am sorry, I do not understand what you mean. Where do I put that parameter? I tried in my kubectl create command, which did not work. Does it go in the manifest somewhere for the kafka connect build? Or are you suggesting to stop trying to use kafka-connect build and just Kaniko external to all of this until I have a working image on my repo, and somehow make kafka-connect pull that image?

**Reply by scholzj** [reply]
Sorry ... that would be in the KafkaConnect custom resource in the `additionalKanikoOptions`: https://strimzi.io/docs/operators/latest/full/using.html#type-DockerOutput-reference

**Reply by davehouser1** [reply]
Thanks scholzj, again. Finally got it deployed. I used `additionalKanikoOptions: ["--skip-tls-verify"]` in my mainfest. Doing this allowed the images to be built and pushed to my private registry. 
Second hurdle was getting my nodes to trust the private registry to pull the image. 
Needed to follow these instructions [here ](https://www.ibm.com/docs/en/cloud-paks/cp-management/2.1.x?topic=monitoring-pods-displaying-imagepullbackoff-status)to fix that problem. This is unrelated to Strimzi and Kubernetes, more of a docker trust issue with certs. 

Will be digging in on how to use this pod soon. Thanks again for your help. I will update this thread once I have a full process.

**Reply by davehouser1** [reply]
I would like to check the status of the deployment. This [link ](https://strimzi.io/blog/2021/03/29/connector-build/) states: 
_"You can also double check the status of the KafkaConnect resource, which will now contain all available connectors:"_
It is not clear to me what command was ran to check if the plugins were installed correctly. Was the Kafka Connect REST API used? or is there some other command that I can use that provides the Kafka Connect plugin status?

**Reply by scholzj** [reply]
If you enabled the Connector Operator, you can do `kubectl get kafkaconnect -o yaml` and check the status section of the YAML. But it looks like you do not use the connector operator ... in which case I think we do not fill this field in. So you can do something like `curl localhost:8083/connector-plugins` from the Connect pod for example.

**Reply by davehouser1** [reply]
Actually `kubectl get kafkaconnect -o yaml` worked and gave the output I needed to check class names. 
When deploying my KafkaConnector for setting Splunk Connect parameters I see lots of java errors dealing with serialization:

```
2021-06-17 16:05:26,063 ERROR WorkerSinkTask{id=my-sink-connector-2} Error converting message value in topic 'zeek' partition 2 at offset 0 and timestamp 1623093595907: Converting byte[] to Kafka Connect data failed due to serialization error:  (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-my-sink-connector-2]
org.apache.kafka.connect.errors.DataException: Converting byte[] to Kafka Connect data failed due to serialization error:
```

The connector seems to deploy but kafka connect cannot seem to parse my data.
Here is what the data looks like

```
{"ts":1623945189.032393,"uid":"CunKml3CUMWzScKpo4","id.orig_h":"192.168.104.100","id.orig_p":50460,"id.resp_h":"192.168.105.100","id.resp_p":53,"proto":"udp","trans_id":29636,"query":"nilhost","qclass":1,"qclass_name":"C_INTERNET","qtype":1,"qtype_name":"A","AA":false,"TC":false,"RD":true,"RA":false,"Z":0,"rejected":false}
```

KafkaConnector file:

```
apiVersion: kafka.strimzi.io/v1beta2 
kind: KafkaConnector 
metadata: 
  name: my-sink-connector 
  labels: 
    strimzi.io/cluster: my-connect-cluster 
spec: 
  class: com.splunk.kafka.connect.SplunkSinkConnector 
  tasksMax: 3 
  config: 
    topics: zeek 
    splunk.indexes: splunk-kafka 
    splunk.hec.uri: http://inputs.10.111.11.11:8088/services/collector 
    splunk.hec.token: 9f1acd9a-34fb-4d31-af97-542e80d6b404 
    splunk.hec.raw: true 
    splunk.hec.ack.enabled: false 
    splunk.hec.track.data: true 
```

- Followed this guide on "Splunk Connect for Kafka tasks fail due to serialization error", problem persists. I am using the JSON parser. 
- Made sure topic exists, also there is data populated in the topic.
- Tried using the StringParser, which caused more errors. I think I need to use JSON. 

I understand if this is out of scope for Strimzi, just curious if anyone ran into this issue before?

**Reply by scholzj** [reply]
I'm afraid I do not know much about this and nothing about Splunk. I know how to configure the convertors but that is it. So I'm probably not going to be able to help.

I'm normally using the `StringConverter`:

```
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
```

But I think there is a ByteArrayConverter or something like that as well. Also, you should try to switch of the schema if your JSOn doesn't have it.
