### DISCUSSION TITLE
Unable to create topic with underscore "_"

### DISCUSSION THREAD

**Discussion by shreyasarani23** [strimzi/strimzi-kafka-operator#5142] [General]
Following is my topic configuration
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: app_launch
spec:
  partitions: 3
  replicas: 3
  config:
    min.insync.replicas: 2

```
when I try to create the topic I get the following error. Does strimzi doesn't allow to have underscore in topic name?
```
 kubectl apply -f t1.yaml -n kafka
The KafkaTopic "app_launch" is invalid: metadata.name: Invalid value: "app_launch": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
while I am able to create same topic on kafka CLI but with warning
```
[kafka@my-kafka-cluster-kafka-0 kafka]$ bin/kafka-topics.sh --create --topic app_launch --bootstrap-server my-kafka-cluster-kafka-bootstrap:9092
WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both.
Created topic app_launch.
```

**Comment by scholzj** [comment]
Please read the documentation: https://strimzi.io/docs/operators/latest/full/using.html#kafka_topic_naming_conventions

**Reply by shreyasarani23** [reply]
As per the documentation https://strimzi.io/docs/operators/latest/full/using.html#kafka_topic_naming_conventions I should be able to create topic by using ```spec.topicName```  Below is my topic configuration
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: topic-name-1
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  topicName: topicName-1
  partitions: 2
  replicas: 3
  config:
    min.insync.replicas: 2
```
Then I create the topic ``` kubectl apply -f t3.yaml -n kafka```
I get this ```kafkatopic.kafka.strimzi.io/topic-name-1 created``` . But in my yaml file I have specified ```
  topicName: topicName-1``` . So the topic name should be topicName-1 right?

Also when I do ```kubectl get KafkaTopic -n kafka```  it shows topic-name-1 is not in ready status. And I am unable to produce data to this topic.
```
~/kafka-deployment/teplay-times2$ kubectl get KafkaTopic -n kafka
NAME                                                                                               CLUSTER            PARTITIONS   REPLICATION FACTOR   READY
app-launch---4d30c079b7634594a874ab17cf99fb76eb8091ee                                              my-kafka-cluster   1            1                    True
consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a                                        my-kafka-cluster   50           1                    True
demo-topic-1                                                                                       my-kafka-cluster   3            2                    True
demo-topic-2                                                                                       my-kafka-cluster   3            2                    True
my-topic                                                                                           my-kafka-cluster   3            2                    True
strimzi-store-topic---effb8e3e057afce1ecf67c3f5d8e4e3ff177fc55                                     my-kafka-cluster   1            2                    True
strimzi-topic-operator-kstreams-topic-store-changelog---b75e702040b99be8a9263134de3507fc0cc4017b   my-kafka-cluster   1            1                    True
test-topic                                                                                         my-kafka-cluster   4            2                    True
topic-name-1                                                                                       my-kafka-cluster   2            3
```
Any idea why topic-name-1 is not in ready state and why it is not named as topicName-1 ?
below is the topic operator logs
```
2021-06-17 14:17:12,23516 INFO  [vert.x-eventloop-thread-1] TopicOperator:565 - 109332|periodic kube topic-name-1|13865618: Reconciling topic topicName-1, k8sTopic:nonnull, kafkaTopic:null, privateTopic:null
```

**Reply by scholzj** [reply]
I'm not sure why it is not ready. You would need to share the whole YAML from Kubernetes to get some details of it. As for the name, as the documentation says, the Kubernetes resource name will never be something like `topicName-1`. So the KafkaTopic resource will always have a valid name for Kubernetes. You should see the right name when you list the topic with some Kafka tools.

**Reply by shreyasarani23** [reply]
well I tried to list the topics using kafka cli but it doesn't list the topic ```topic-name-1```
```
[kafka@my-kafka-cluster-kafka-1 kafka]$ bin/kafka-topics.sh --list --bootstrap-server my-kafka-cluster-kafka-bootstrap:9092
__consumer_offsets
__strimzi-topic-operator-kstreams-topic-store-changelog
__strimzi_store_topic
app_launch
demo-topic-1
demo-topic-2
my-topic
test-topic
```
Here is my yaml file for kafka:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka-cluster
spec:
  kafka:
    template:
      podDisruptionBudget:
        maxUnavailable: 1
      pod:
        metadata:
          labels:
            app: kafkaPod
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: node
                    operator: In
                    values:
                    - <value>
    version: 2.8.0
    replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false  
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: 2.8
      auto.leader.rebalance.enable: "true"
      delete.topic.enable: "true"
      auto.create.topics.enable: "false"
    storage:
      type: persistent-claim
      size: 1Gi
      class: kafka-storage-class
      deleteClaim: false
  zookeeper:
    template:
      podDisruptionBudget:
        maxUnavailable: 1
      pod:
        metadata:
          labels:
            app: zookeeperPod
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: node
                    operator: In
                    values:
                    - <value>
    replicas: 2
    storage:
      type: persistent-claim
      size: 1Gi
      class: kafka-storage-class
      deleteClaim: false
  entityOperator:
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: node
                    operator: In
                    values:
                    - <value>
    topicOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging: 
        type: inline
        loggers:
          rootLogger.level: "INFO"
```
