### DISCUSSION TITLE
How to create multiple topics using yaml

### DISCUSSION THREAD

**Discussion by barryzhounb** [strimzi/strimzi-kafka-operator#5150] [General]
This following is a yaml that is used to create a topic. Now I want to create 3 topics, is it possible to refactor the following yaml to achieve it?

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: topic-1
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 6
  replicas: 3
```

**Comment by scholzj** [comment]
One resource is always one topic. But when you use YAML, you can easily have multiple resources in a single YAML file separated by `---` and when you do `kubectl apply -f` on it it will create all of them. E.g.:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: topic-1
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 6
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: topic-2
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 6
  replicas: 3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: topic-3
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 6
  replicas: 3
```
