### DISCUSSION TITLE
cluster-ca-cert has expired

### DISCUSSION THREAD

**Discussion by Aldjinn** [strimzi/strimzi-kafka-operator#5154] [Q&A]
Hi,
since yesterday, my kafka cluster is broken. The cluster has been created a year ago and the issue seems to be an expired certificate:

Output from a crash looping kafka pod:
```
+ ./kafka_tls_prepare_certificates.sh
Preparing truststore for replication listener
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/kafka/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore for replication listener is complete
Looking for the right CA
Found the right CA: /opt/kafka/cluster-ca-certs/ca.crt
Preparing keystore for replication and clienttls listener
Error certificate has expired getting chain.
````
```
NAME                                            READY   STATUS             RESTARTS   AGE
kafka-cluster-entity-operator-f6bb47fcb-g8dlf   1/3     CrashLoopBackOff   11         9m58s
kafka-cluster-kafka-0                           0/1     CrashLoopBackOff   208        17h
kafka-cluster-kafka-1                           0/1     CrashLoopBackOff   199        16h
kafka-cluster-kafka-2                           1/1     Running            1          11d
kafka-cluster-zookeeper-0                       1/1     Running            0          11d
kafka-cluster-zookeeper-1                       1/1     Running            0          11d
kafka-cluster-zookeeper-2                       1/1     Running            0          11d
```
My cluster is called "kafka-cluster" and the according secret containing the certificate is kafka-cluster-cluster-ca-cert. I've had a look into ca.crt and the result contains:
```
        Validity
            Not Before: Jun 17 07:30:37 2020 GMT
            Not After : Jun 17 07:30:37 2021 GMT
```

The cluster was created using the following settings:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.5'
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
I've tried to add the following clusterCa and clientsCa settings without any success:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.5'
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
  clusterCa:
    renewalDays: 30
    validityDays: 3650
    generateCertificateAuthority: true
    certificateExpirationPolicy: renew-certificate
  clientsCa:
    renewalDays: 30
    validityDays: 3650
    generateCertificateAuthority: true
    certificateExpirationPolicy: renew-certificate
```

Also adding annotations described in the documentation did not change anything:
```
kubectl -n kafka annotate secret kafka-cluster-cluster-ca-cert strimzi.io/force-renew=true
kubectl -n kafka annotate secret kafka-cluster-clients-ca-cert strimzi.io/force-renew=true
```

Manually (re-) creating certificates and replacing the secret did not help either:
```bash
# create
openssl req -x509 -new -subj '/O=io.strimzi/CN=cluster-ca v0' -key ca.key -sha256 -days 10950 -out ca.crt

# print
openssl x509 -in ca.crt -text

# convert to p12
# password: *******
openssl pkcs12 -export -in ca.crt -inkey ca.key -out ca.p12

# convert to base64
openssl base64 -in ca.p12 -out ca.p12.base64
```

I'm not sure if this could be related to my issue, but my kafka operator is pending for upgrade.
```
NAME                                 DISPLAY              VERSION   REPLACES                           PHASE
strimzi-cluster-operator.v0.23.0     Strimzi              0.23.0    strimzi-cluster-operator.v0.22.1   Pending
```

The update (is is called update) has failed because of
```
          - lastTransitionTime: '2021-06-07T00:09:28Z'
            lastUpdateTime: '2021-06-07T00:09:28Z'
            message: >-
              pods "strimzi-cluster-operator-v0.23.0-6d48cd845c-" is forbidden:
              error looking up service account
              operators/strimzi-cluster-operator: serviceaccount
              "strimzi-cluster-operator" not found
            reason: FailedCreate
            status: 'True'
            type: ReplicaFailure
````

I'm a little bit lost. This is my first issue with the combination of a k8s operator and expired certificates. In general, a problem related to one way or the other is challenging, but the combination is... more challenging, at least for me.

Kind regards,
Dennis
