### DISCUSSION TITLE
Issue with using FluxCD Gitops to manage Strimzi Kafka resource manifests

### DISCUSSION THREAD

**Discussion by misurin** [strimzi/strimzi-kafka-operator#5198] [Q&A] [answered]
Hi,

We are a mid-size data engineering team working in a Singapore E-commerce company. Kubernetes has been used widely across many of our services and we use FluxCD to manage the K8S deployments. 

We onboarded Kafka to our tech-stack a few months ago, We thought we could give Strimzi Operator a try and the actual installation process was very smooth, we're able to set up all features that we need. Until recently when we start migrating more use-cases to Kafka, more Kafka connectors need to set up, we realized that every time we make a change to the Kafka manifest Git repo, the whole cluster restarts even though the change is only a Kafka Connector config.

The restarting process starts with Rolling Restart of Zookeeper cluster, then Kafka Cluster, and then all Kafka Connect clusters.

I'm pretty sure that we made no changes to the main Kafka cluster manifest. When trying to compare the created Kafka cluster resource by FluxCD, we found that the only change is in the label `kustomize.toolkit.fluxcd.io/checksum`.

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  annotations:
  creationTimestamp: "2021-01-15T04:46:53Z"
  generation: 2
  labels:
    **kustomize.toolkit.fluxcd.io/checksum: f9380059f5f92fd6ccf96192922ddd8a2ce58c7c**
    kustomize.toolkit.fluxcd.io/name: data-eks-kafka
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  name: prod
  namespace: kafka
spec:

```

Is there any configuration in the operator to prevent this behavior? Or under which condition the operator decides to restart the whole cluster?

As a workaround, we have to block all Kafka connector creations using the KafkaConnector resources :(.
