### DISCUSSION TITLE
MirrorMaker2 connectors get ConnectionRestException

### DISCUSSION THREAD

**Discussion by AvihuHenya** [strimzi/strimzi-kafka-operator#5206] [Q&A]
Strimzi: 0.19.0
Kafka: 2.4.0
KafkaConnect: 2.4.0
KafkaMirrorMaker: 2.4.0

Hi all. I have encountered some problems when I have tried to deploy KafkaMirrorMaker2 instance to migrate data between 2 Kafka clusters. When applying the resource, I get error message regarding the 3 connectors related to the MirrorMaker (sourceConnector,  checkpointConnector, heartbeatConnector).

The error message is: 
GET
/connectors/source-cluster->target-cluster.MirrorCheckpointConnector/config returned 500 (Internal Server Error): Request timed out

and so for the 2 other connectors:
/connectors/source-cluster->target-cluster.MirrorSourceConnector/config
/connectors/source-cluster->target-cluster.MirrorHeartbeatConnector/config 

**KafkaMirrorMaker2 Yaml:**
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  namespace: strimzi
  name: my-mirror-maker-2
spec:
  version: 2.5.0
  replicas: 1
  connectCluster: "my-target-cluster"
  clusters:
  - alias: "my-source-cluster"
    bootstrapServers: my-cluster-kafka-bootstrap.strimzi.svc.cluster.local:9092
  - alias: "my-target-cluster"
    bootstrapServers: my-target-kafka-bootstrap.strimzi.svc.cluster.local:9092
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  mirrors:
  - sourceCluster: "my-source-cluster"
    targetCluster: "my-target-cluster"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: ".*"
    groupsPattern: ".*"
```
