### DISCUSSION TITLE
Kafka Connect Issue

### DISCUSSION THREAD

**Discussion by kmandal-volvo** [strimzi/strimzi-kafka-operator#5225] [Q&A]
Kafka connect working fine but now getting below issue 

org.apache.kafka.common.config.ConfigException: Topic 'connect-cluster-offsets' supplied via the 'offset.storage.topic' property is required to have 'cleanup.policy=compact' to guarantee consistency and durability of source connector offsets, but found the topic currently has 'cleanup.policy=delete'. Continuing would likely result in eventually losing source connector offsets and problems restarting this Connect cluster in the future. Change the 'offset.storage.topic' property in the Connect worker configurations to use a topic with 'cleanup.policy=compact'.

Logfile attached.
[vcc-esp-connect-private-sandbox-connect-d956557dc-drm6c.log](https://github.com/strimzi/strimzi-kafka-operator/files/6741739/vcc-esp-connect-private-sandbox-connect-d956557dc-drm6c.log)

Kafka connect configuration 
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: vcc-esp-connect-private-sandbox
  annotations:
    strimzi.io/use-connector-resources: "true"
#  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
#    strimzi.io/use-connector-resources: "true"
spec:
  image: vccai.azurecr.io/custom-kafka-connect-image:v9.0
  imagePullPolicy: Always
  #version: 2.6.0
  replicas: 2
  bootstrapServers: vcc-internal-esp-sandbox-kafka-bootstrap:9093
  imagePullSecrets:
    - name: azure-docker-registry
  tls:
    trustedCertificates:
      - secretName: vcc-internal-esp-sandbox-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: tls
    certificateAndKey:
      secretName: icoe-int-super-user
      certificate: user.crt
      key: user.key
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
  http:
    port: 8083
```
