### DISCUSSION TITLE
Unable to run kafka in localhost

### DISCUSSION THREAD

**Discussion by jaya-rama** [strimzi/strimzi-kafka-operator#5252] [Q&A]
Hi 
Below is my YAML file to deploy kafka, and all the pods are running fine when I deploy kafka cluster but when I use 127.0.0.1:32100 as bootstap server then I'm getting the following error 

WARN [AdminClient clientId=adminclient-1] Connection to node -1 (/127.0.0.1:32100) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)

But when I use the same configuration without advertisedHost then kafka is running perfectly fine but it's not running in localhost. Can someone help me in running kafka in localhost

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
    - name: external
      port: 9094
      type: nodeport
      tls: false
      configuration:
        bootstrap:
          nodePort: 32100
        brokers:
        - broker: 0
          advertisedHost: 127.0.0.1
          advertisedPort: 12340
          nodePort: 32000
        - broker: 1
          advertisedHost: 127.0.0.1
          advertisedPort: 12341
          nodePort: 32001
        - broker: 2
          advertisedHost: 127.0.0.1
          advertisedPort: 12342
          nodePort: 32002
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage: 
      type: persistent-claim 
      size: 128Mi
  zookeeper:
    replicas: 3
    storage: 
      type: persistent-claim 
      size: 128Mi 
  entityOperator:
    topicOperator: {}
    userOperator: {}

```
