### DISCUSSION TITLE
Cannot find kafka-user from secret USER-NAME

### DISCUSSION THREAD

**Discussion by akametall** [strimzi/strimzi-kafka-operator#5296] [Q&A]
Hi. I try to turn on kafka-strimzi tls authentication.
Doing it by https://strimzi.io/docs/operators/latest/full/deploying.html
But i cannot take from kubectl get secret -n namespace crt.
last what i do:
1. create KafkaUser.yaml

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: my-user
  labels:
     strimzi.io/cluster: my-cluster
spec:
   authentication:
       type: tls
   authorization:
      type: simple
      acls:
         - resource:
              type: topic
              name: my-topic
              patternType: literal
           operation: Read
      - resource:
           type: topic
           name: my-topic
           patternType: literal
        operation: Describe
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read
```

2. Secret.yaml

```
apiVersion: v1
kind: Secret
metadata:
  name: my-user
  labels:
    strimzi.io/kind: KafkaUser
    strimzi.io/cluster: my-cluster
type: Opaque
```

3. Put in kustomization.yaml this:

```
configMapGenerator:
  - name: kafka-my
    files:
      - config.yaml
      - config-my.yaml
      - KafkaUser.yaml
      - Secret.yaml
```
      
4. And in kafka.yaml

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  clusterCa:
    renewalDays: 1
    validityDays: 2
    generateCertificateAuthority: true
  clientsCa:
    renewalDays: 1
    validityDays: 2
    generateCertificateAuthority: true 
...
 - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
  - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: tls
authorization:
      type: simple
      superUsers:
        - my-user
```

And...i'm totaly stuck.
All i take from kubectl get secrets is:

```
NAME                                      TYPE                                  
default-token-66t4c                            kubernetes.io/service-account-token  
cluster-clients-ca                                 Opaque                                
cluster-clients-ca-cert                          Opaque                              
cluster-cluster-ca                                 Opaque                                
cluster-cluster-ca-cert                         Opaque                               
cluster-cluster-operator-certs             Opaque                                
cluster-entity-operator-certs               Opaque                             
cluster-entity-operator-token-8nkr4   kubernetes.io/service-account-token   
cluster-kafka-brokers                           Opaque                                
cluster-kafka-exporter-certs                  Opaque                               
cluster-kafka-exporter-token-snkgr      kubernetes.io/service-account-token   
cluster-kafka-token-llvq2                      kubernetes.io/service-account-token   
cluster-zookeeper-nodes                        Opaque                               
cluster-zookeeper-token-pxjfp              kubernetes.io/service-account-token   
```

so i cannot config user.config.file to access broker withous user.ca and etc.
