### DISCUSSION TITLE
Can I use Strimzi without minikube?

### DISCUSSION THREAD

**Discussion by networkingana** [strimzi/strimzi-kafka-operator#5316] [Q&A]
I have vanilla Kubernetes installation, and I want to use Kafka with Strimzi for production. Currently, I am organizing the whole environment with all of the applications of the system.

I encountered issues regarding the persistent volumes and storage. For now, I want to use local storage for the Kafka and zookeeper data. 

My cluster has one master node and two worker nodes

I created a storage class for kubernetes with the following YAML file:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
```

I also created persistent volume with the following YAML file:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-cluster-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /data
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - master-node
```
And finally, this is my Kafka YAML used from the strimzi-.0.24.0.zip example folder and modified with class

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: "local-storage"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: "local-storage"
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

My zookeepers fail to bind to my persistent volume can you please help me with this?

[kubect_describe_all.txt](https://github.com/strimzi/strimzi-kafka-operator/files/6835883/kubect_describe_all.txt)
[kubect_describe_pvc.txt](https://github.com/strimzi/strimzi-kafka-operator/files/6835884/kubect_describe_pvc.txt)

**Comment by scholzj** [comment]
Well, first of all, you need persistent volume per node. So it is not enough to create just one PV ... for 3 ZooKeepers and 3 Kafkas you will need 6 of them -> each for a different path. Not sure why at least the one them didn't bound, but this seems to be the complaint from Kubernetes:
```
Warning  ProvisioningFailed   15m (x12 over 18m)    persistentvolume-controller  no volume plugin matched name: kubernetes.io/no-provisioner
```

**Reply by networkingana** [reply]
I did that and tried again to deploy it but with no success, i used the report.sh script. Can you please check?
[report-18-07-2021_10-51-24.zip](https://github.com/strimzi/strimzi-kafka-operator/files/6836469/report-18-07-2021_10-51-24.zip)

**Reply by scholzj** [reply]
Well, it is a bit hard to say what the issue is. The ZooKeeper 0 seems to have problem connecting anywhere. So that would point to some networking issues I guess. ZooKeeper 1 has issues with TLS hostname verification - that is probably caused by some misconfiguration in your DNS which does not return the right values for reverse lookup. If you search through the issues, there are some discussions it and have ways how to disable the hostname verification if needed. The ZooKeeper 2 does not seem to be doing anything from the logs, hard to say why.

**Reply by networkingana** [reply]
[report-29-07-2021_19-54-30.zip](https://github.com/strimzi/strimzi-kafka-operator/files/6904238/report-29-07-2021_19-54-30.zip)
Now it seems errors with SSL stuff, I am really not sure what is happening :/

**Reply by scholzj** [reply]
You did not seemed to follow on the suggestion from the last post. You should either fix your DNS or disable the TLS hostname verification by adding:

```yaml
    jvmOptions:
      javaSystemProperties:
        - name: zookeeper.ssl.hostnameVerification
          value: "false"
        - name: zookeeper.ssl.quorum.hostnameVerification
          value: "false"
```

to `.spec.zookeeper`.
