### DISCUSSION TITLE
MirrorMaker2 does not replicate data between clusters

### DISCUSSION THREAD

**Discussion by AvihuHenya** [strimzi/strimzi-kafka-operator#5365] [Q&A]
**Source Cluster:**
Strimzi: 0.18.0
Kafka: 2.4.0
KafkaMirrorMaker: 2.4.0

**Target Cluster:**
Strimzi: 0.19.0
Kafka: 2.4.0
KafkaMirrorMaker: 2.4.0

Currently, I'm trying to test the MirrorMaker2 for DR purposes between two different OpenShift enviroments I have.
Beforehand, I tried to do the same, but between 2 clusters in the same namespaces, and it works well.

As of now, after I configured the MirrorMaker2 and the clusters, when I produce some messages in some topic in the source cluster, the topic doesn't replicate to the target cluster.

The Kafka configuration in both clusters are pretty default. 

**Kafka Yaml:**  
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: source-cluster
spec:
  kafka:
    version: 2.4.0
    replicas: 3
    listeners:
      external: 
          type: route
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}

```
**KafkaMirrorMaker2 Yaml:**

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  namespace: strimzi
  name: my-mirror-maker-2
spec:
  version: 2.4.0
  replicas: 1
  connectCluster: "my-target-cluster"
  clusters:
  - alias: "my-source-cluster"
    bootstrapServers: my-source-dr-kafka-cluster-kafka-bootstrap:443
    tls:
      trustedCertificates:
        - certificate: ca.crt
          secretName: my-source-dr-kafka-cluster-cluster-ca-cert
  - alias: "my-target-cluster"
    bootstrapServers: my-target-kafka-bootstrap.strimzi.svc.cluster.local:9092
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  mirrors:
  - sourceCluster: "my-source-cluster"
    targetCluster: "my-target-cluster"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
        replication.policy.seperator: ' '
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
       config:
         checkpoints.topic.replication.factor: 1
         refresh.groups.interval.seconds: 600
         emit.checkpoints.enabled: true
         sync.group.offsets.enabled: true
         sync.group.offsets.interval.seconds: 60
         emit.checkpoints.interval.seconds: 60
    topicsPattern: ".*"
    groupsPattern: ".*" 

````

As you can see, I'm connecting to the source cluster via route. In the target cluster (where I deployed the MirrorMaker2), I created a new secret with the same ca cluster certificate of the source cluster.
In addition, the MirrorMaker succeeded in connecting to the target cluster since the 3 topics- configs, offsets and status were created.
  
Any idea?

**Comment by scholzj** [comment]
Without any logs, it is hard to say what the problem is. In any case, things such as `sync.group.offsets.enabled: true` are IMHO not supported in Kafka 2.4.0 - although I would not expect that to affect the mirroring itself.

**Reply by AvihuHenya** [reply]
I've checked the logs of the MirrorMaker pod, all there is an INFO logs, and the same is the operator logs.
The condition of all objects (MirrorMaker2, Kafka clusters) is in type ready and status is true.

**Comment by AvihuHenya** [comment]
Within this subject, I have a few questions:
1) Is it mandatory to use both the source and target clusters two identical versions of Kafka? Is there any rules about that?
2) If I want to connect my Mirrormaker2 to a cluster with a scram-sha-512 authentication component, what componenet should I transfer to the second cluster? (The cluster where i deployed MirrorMaker2) the KafkaUser or only the secret created with the KafkaUser? 

For example:

```
authentication:
  type: scram-sha-512
  username: my-cluster-username
  passwordSecret:
    secretName: my-cluster-secret-name
    password: my-cluster-password-field
```

- Is the username fiels means the KafkaUser object? If yes, what should i give here in my MirrorMaker2 yaml file? (Again, in case i want to connect to a cluster with a scram-sha-512 authentication component). 
3) What is the exact configuration at the MirrorMaker2 yaml file that defines the time it takes the target cluster to check for new topics at the source cluster? 

Thank you.
