### DISCUSSION TITLE
Liveness and Readiness probes not available for Strimzi operator

### DISCUSSION THREAD

**Discussion by sidsj** [strimzi/strimzi-kafka-operator#5384] [Q&A]
**Is your feature request related to a problem? Please describe.**
When we deploy Strimzi operator readiness and liveness probes are not available on the operator pod

**Describe the solution you'd like**
We need readiness and liveness probes to be available on Strimzi Operator pod.
File uploaded for reference.

**Describe alternatives you've considered**

[strimzi-operator.txt](https://github.com/strimzi/strimzi-kafka-operator/files/6921940/strimzi-operator.txt)

**Comment by scholzj** [comment]
Your attached file has them in it:

```yaml
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
```

And so do the official installation files: https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml#L100-L111
