### DISCUSSION TITLE
KafkaConnect Connector Resource not able to connect to kafka cluster

### DISCUSSION THREAD

**Discussion by alpacino12** [strimzi/strimzi-kafka-operator#5442] [Q&A]
I have deployed a 3 node Strimzi kafka Cluster having strimzi  operator version 0.23 inside Azure Kubernetes Cluster .The Cluster and kafka/zookeeper pods are up and running . Strimzi kafka image used is strimzi/kafka:0.23.0-kafka-2.7.0
tushar@Azure:~$ kubectl get pods -n strimzi-kafka-aks-cluster
NAME                                                       READY   STATUS             RESTARTS   AGE
my-connect-cluster-connect-7b4cd65946-c9qjg                0/1     CrashLoopBackOff   25         112m
strimzi-kafka-aks-cluster-entity-operator-665645cc-wcgdn   3/3     Running            0          11d
strimzi-kafka-aks-cluster-kafka-0                          1/1     Running            0          11d
strimzi-kafka-aks-cluster-kafka-1                          1/1     Running            0          11d
strimzi-kafka-aks-cluster-kafka-2                          1/1     Running            0          11d
strimzi-kafka-aks-cluster-zookeeper-0                      1/1     Running            0          11d
strimzi-kafka-aks-cluster-zookeeper-1                      1/1     Running            0          11d
strimzi-kafka-aks-cluster-zookeeper-2                      1/1     Running            0          11d

 I'm trying to create a kafkaconnect cluster but the connect container  keeps on crashing . Here is the yaml deployment i'm using

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
#  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
#    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: strimzi-kafka-aks-cluster-kafka-extnl-bootstrap:9094
  #tls:
   # trustedCertificates:
    # - secretName: strimzi-kafka-aks-cluster-cluster-ca-cert
     #   certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
```

I have tried with both tls config map and without , with spec.image tag and without but each time it gives connection failed to kafka broker error

When i describe the failed pod it says 

Liveness probe failed: Get "http://10.244.5.25:8083/": dial tcp 10.244.5.25:8083: connect:connection refused

logs : 

2021-08-17 16:43:58,000 ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed) [main]
org.apache.kafka.connect.errors.ConnectException: Failed to connect to and describe Kafka cluster. Check worker's broker connection and securityproperties.
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:70)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:51)
        at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:97)
        at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:80)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1629218637936, tries=1, nextAllowedTryMs=1629218638070) timed out at 1629218637970 after 1 attempt(s)
        at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
        at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
        at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
        at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:64)
        ... 3 more
Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=listNodes, deadlineMs=1629218637936, tries=1, nextAllowedTryMs=1629218638070) timed out at 1629218637970 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes

Is there any issue with the deployement here ? Why is the connect instance not able to connect to the kafka cluster

**Comment by scholzj** [comment]
If you format the YAML as a code, it will be much more readable and easier to detect any whitespaces issues etc. Also, can you please share the Kafka custom resource with your Kafka cluster configuration? Without that it is hard to say if you configured it correctly or not.

**Comment by alpacino12** [comment]
Here's the yaml file i'm using to start the kafkaConnect pod

````
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
#  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
#    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.7.0
  replicas: 1
  bootstrapServers: kafka-gsmdp-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName:  kafka-gsmdp-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
```

I created the cluster via strimzi helm chart , updated values.yaml file like below

`# Default values for strimzi-kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# provide namespace for strimzi kafka cluster
namespace: strimzi-operator-aks-cluster

#Provide your kafka cluster name
cluster:
  kafkaname: kafka-gsmdp-cluster
#Provide number of kafka brokers need in kafka cluster
replicaCount: 3

# Mention internal and external ports for connecting to Kafka cluster
listeners:
  internalport: 9093
  extrnlport: 9094
# provide kafka resources
kafkaresources:
  storageclass: default
  volumecapacity: 10Gi
  reqmemory: 500m
  reqcpu: 500m
  limitmemory: 4Gi
  limitcpu: 500m

# Provide Zookeeper resources according requirements
zkresources:
  volumecapacity: 10Gi
  reqmemory: 500m
  reqcpu: 250m
  limitmemory: 2Gi
  limitcpu: 500m
# Provide versions according to  kafka version using in cluster
versions:
  logversion: 2.7
  interbrokerversion: 2.7

# Provide user details for authentication while connecting to cluster
strimziuser:
  kafkauser: my-user
  authtype: scram-sha-512

# Run the below command in your terminal and update the value accordingly in below section
# echo -n '{"auths":{"gateway-sesk1.nsc.internal.ericsson.com:30048":{"username":"etxxxxx","password":"Dv1xxxxxxxxxxaRU"}}}' |base64  | tr -d \\n
harborsecret: eyJhdXRocyI6eyJnYXRld2F5LXNlc2sxLm5zYy5pbnRlcm5hbC5lcmljc3Nvbi5jb206MzAwNDgiOnsidXNlcm5hbWUiOiJldGhvbmFnIiwicGFzc3dvcmQiOiJEdjFSZmNTMlhTTmd0UDRJdXJxOVdESkRhc2FtNWFSVSJ9fX0=
