### DISCUSSION TITLE
[helm] watchAnyNamespace flag seems to have no effect

### DISCUSSION THREAD

**Discussion by mjrepo2** [strimzi/strimzi-kafka-operator#5480] [Q&A] [answered]
I have installed strimzi 0.20.1 with the supplied helm chart values (https://github.com/strimzi/strimzi-kafka-operator/blob/0.20.1/helm-charts/helm3/strimzi-kafka-operator/values.yaml) and changed watchAnyNamespace: false, to true.
Strimzi is installed into a kafka namespace, and I want to create a "kafkauser" resource in different namespace and have the strimzi operator consume the resource and create the user in kafka.
So far, this is not working in any namespace other than the namespace strimzi is installed into, even though I have the watchAnyNamespace flag set to true.

I can create the user in the same namespace strimzi is running, and it creates a secret from it and the user operator logs show it has seen and created the resources.
In any other namespace there is no effect and no log entry, am I missing something?

Kafka user yaml:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  namespace: newnamespace
  name: kafka-user
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
```

strimzi helm values yaml:
```
# Default values for strimzi-kafka-operator.

# If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
# the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
watchNamespaces: []
watchAnyNamespace: true

image:
  repository: strimzi
  name: operator
  tag: 0.20.1
logVolume: co-config-volume
logConfigMap: strimzi-cluster-operator
logLevel: ${env:STRIMZI_LOG_LEVEL:-INFO}
fullReconciliationIntervalMs: 120000
operationTimeoutMs: 300000
kubernetesServiceDnsDomain: cluster.local

tolerations: []
affinity: {}
nodeSelector: {}

# Docker images that operator uses to provision various components of Strimzi.  To use your own registry prefix the
# repository name with your registry URL.
# Ex) repository: registry.xyzcorp.com/strimzi/zookeeper
zookeeper:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.20.1
kafka:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.20.1
kafkaConnect:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.20.1
kafkaConnects2i:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.20.1
topicOperator:
  image:
    repository: strimzi
    name: operator
    tag: 0.20.1
userOperator:
  image:
    repository: strimzi
    name: operator
    tag: 0.20.1
kafkaInit:
  image:
    repository: strimzi
    name: operator
    tag: 0.20.1
tlsSidecarEntityOperator:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.20.1
kafkaMirrorMaker:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.20.1
kafkaBridge:
  image:
    repository: strimzi
    name: kafka-bridge
    tag: 0.19.0
kafkaExporter:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.20.1
jmxTrans:
  image:
    repository: strimzi
    name: jmxtrans
    tag: 0.20.1
kafkaMirrorMaker2:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.20.1
cruiseControl:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.20.1
tlsSidecarCruiseControl:
  image:
    repository: strimzi
    name: kafka
    tagPrefix: 0.20.1
resources:
  limits:
    memory: 384Mi
    cpu: 1000m
  requests:
    memory: 384Mi
    cpu: 200m
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30

# Override the docker image repository used by all Strimzi images
imageRepositoryOverride: ""
# Override the docker image tag used by all Strimzi images
imageTagOverride: ""
createGlobalResources: true
```
