### DISCUSSION TITLE
How to apply mtls between pods with istio sidecar proxy to kafka pods

### DISCUSSION THREAD

**Discussion by DMSwimTech** [strimzi/strimzi-kafka-operator#5600] [Q&A]
Hey,

I saw that there was some discussion around the topic but I couldn't wrap my head around it. 

I have pods that are being effected by istio and I have Strimzi Kafka pods which are not being effected at  all by istio. 

My issue is that the pods can't connect because they are failing on the mtls handshake. 

Strimzi and Istio setup uses self sign certificate. My suspicion was that they are not trusting each one certifricate and I tried to use the following:

```
  listeners:
    - name: plain
      port: 9092
      type: internal
      tls: false
    - name: tls
      port: 9093
      type: internal
      tls: true
      authentication:
        type: tls
        tlsTrustedCertificates:
        - secretName: istio-ca-root-cert
          certificate: ca.crt
``` 

 and I add serviceEntry for istio. 
 
 Unfortunately for me that didn't work and help will be appreciate
