### DISCUSSION TITLE
using the standalone topic operator with an SSL enabled cluster

### DISCUSSION THREAD

**Discussion by itaydj** [strimzi/strimzi-kafka-operator#5644] [Q&A] [answered]
Hi,
I have a Kafka cluster thats running outside of our Kubernetes cluster and I want to use the standalone topic operator to manage topics on it.
my question is how can I pass the truststore and keystore files to it?
I read here : https://strimzi.io/docs/operators/latest/full/deploying.html#deploying-the-topic-operator-standalone-str
that I can use
STRIMZI_TRUSTSTORE_LOCATION and STRIMZI_KEYSTORE_LOCATION to pass the file but I guess the file should exist in the topic operator pod.
how can I copy the files to it?
Thanks in advance.

**Comment by scholzj** [comment, marked as answer]
You will for example need to create a secret with these files and edit the TO deployment to mount them as volumes.

**Reply by itaydj** [reply]
I understand, so theres no way to mount it from the topic-operator yml itself?
I need to apply the topic-operator and only after it is deployed edit it and mount the secrets?

**Reply by scholzj** [reply]
Not sure I follow ... you can edit the YAML as much as you want before you run `kubectl apply` on it.

**Reply by itaydj** [reply]
Sorry if im not clear,
my yaml looks as below:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-topic-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-topic-operator
  template:
    metadata:
      labels:
        name: strimzi-topic-operator
    spec:
      serviceAccountName: strimzi-topic-operator
      containers:
        - name: strimzi-topic-operator
          image: quay.io/strimzi/operator:0.25.0
          args:
          - /opt/strimzi/bin/topic_operator_run.sh
          env:
            - name: STRIMZI_RESOURCE_LABELS
              value: "strimzi.io/cluster=my-external-cluster"
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: server1:9093,server2:9093,server3:9093 
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: server1:2181,server2:2181,server3:2181/poc-kafka
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "18000"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS
              value: "6"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_TLS_ENABLED
              value: "false"
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 96Mi
              cpu: 100m
            requests:
              memory: 96Mi
              cpu: 100m
  strategy:
    type: Recreate
```

where am I setting the mount options?
I didnt find it in the documentations and this is the only example I have.

Thanks
