### DISCUSSION TITLE
KafkaUser resource with authorization to all topics.

### DISCUSSION THREAD

**Discussion by purbanow** [strimzi/strimzi-kafka-operator#5679] [Q&A]
Hi, 

is it possible to set authorization access for all topics? Something like this:
```
    - resource:
        type: topic
        name: *
      operation: Write
      host: "*"
```

Thanks a lot
