### DISCUSSION TITLE
External Listener

### DISCUSSION THREAD

**Discussion by yasin-amadmia-mck** [strimzi/strimzi-kafka-operator#5699] [Q&A]
So we running Kafka Strimzi operator within AKS. We want to connect to this kafka from our on-premise network too (all network etc is configured).
What we configured is an external Listener of type `loadbalancer` but with an annotation of Azure Internal IP. This works fine.
```
      - name: external
        port: 9095
        type: loadbalancer
        tls: false
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              external-dns.alpha.kubernetes.io/hostname: kafka.aks.cloud
          brokers:
          - broker: 0
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-0.aks.cloud
          - broker: 1
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-1.aks.cloud
          - broker: 2
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-2.aks.cloud
```
The above creates 4 services. An `external-0,1,2` - One per broker, and one `external-bootstrap`.

Question:
(1) What is the use of the `external-0,1,2` services ? 
(2) When connecting from on-premise for example, we should use the `external-bootstrap` service and NOT the `external-0,1,2` right ?
