### DISCUSSION TITLE
anti-affinity with hard scheduling (required doesn't seem to be working)

### DISCUSSION THREAD

**Discussion by elmehdisaniss** [strimzi/strimzi-kafka-operator#5750] [Q&A]
Hi Strimzi team,

I'm using the 0.25.0 of the strimzi operator with its 0.25.0 helm chart. I deployed the kafka/zookeeper clusters with 3 instances for each using [the anti-affinity configuration presented in 0.25.0 documentation](https://strimzi.io/docs/operators/in-development/using.html#configuring-pod-anti-affinity-to-schedule-each-kafka-broker-on-a-different-worker-node-str) in an eks cluster that has enough nodes (8 nodes) so the test wasn't relevant. So I used my 1 node minikube cluster so that minikube deploys only one instance and report the other ones as not able to be deployed due to the anti-affinity rule that is not satisfied (1node) but it was not the case. Minikube deployed all instances. I tried this test with the postgres operator and minikube couldn't schedule due to the non existence of other nodes to schedule pods on.

It is the same configuration for the values.yaml file : 

```
kafka_cluster:
  kafka:
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                      - nms-kafka
                topologyKey: topology.kubernetes.io/hostname
    replicas: 3
    resources:
      requests:
        cpu: 0m
        memory: 2000Mi
      limits:
        cpu: 0m
        memory: 2000Mi
    loglevel: INFO
  zookeeper:
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                      - nms-zookeeper
                topologyKey: topology.kubernetes.io/hostname
    replicas: 3
    resources:
      requests:
        cpu: 0m
        memory: 800Mi
      limits:
        cpu: 0m
        memory: 800Mi
    loglevel: INFO
```

And as we are using helm charts this is what is in the template file of the kafka resource : 
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: nms
spec:
  kafka:
    replicas: {{ .Values.kafka_cluster.kafka.replicas }}
    resources: {{ toYaml .Values.kafka_cluster.kafka.resources | nindent 6 }}
---
    {{- with .Values.kafka_cluster.kafka.template }}
    template:
      {{- toYaml . | nindent 6 }}
  zookeeper:
    replicas: {{ .Values.kafka_cluster.zookeeper.replicas }}
    resources: {{ toYaml .Values.kafka_cluster.zookeeper.resources | nindent 6 }}
---
        {{- with .Values.kafka_cluster.zookeeper.template }}
    template:
      {{- toYaml . | nindent 6 }}
  {{- end }}
```

Do you see this as an issue or do you have any explanation please ? 

Best regards,

**Comment by scholzj** [comment]
You probably configured it wrong? I'm afraid without you sharing the configuration you used etc., there is not much more one can say.

**Reply by scholzj** [reply]
If you can format the YAML as a code, it would be much more readable and it would allow to see the structure which is very important with YAML. I do not use Helm, so I do not know how that renders.

Also, do you actually use the `CLUSTER-NAME` in the label selector? You need to replace it with the name of your actual cluster.

**Reply by elmehdisaniss** [reply]
The rendered chart appears after the deployment completes and it showed that the anti-affinity configuration has been taken and the pods got deployed successfully and are running :
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: nms
spec:
  kafka:
    replicas: 2
    resources: 
      limits:
        cpu: 0m
        memory: 2000Mi
      requests:
        cpu: 0m
        memory: 2000Mi
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
          type: tls
    authorization:
      type: simple
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: INFO
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: strimzi.io/name
                  operator: In
                  values:
                  - nms-kafka
              topologyKey: topology.kubernetes.io/hostname
  zookeeper:
    replicas: 2
    resources: 
      limits:
        cpu: 0m
        memory: 800Mi
      requests:
        cpu: 0m
        memory: 800Mi
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: INFO
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: strimzi.io/name
                  operator: In
                  values:
                  - nms-zookeeper
              topologyKey: topology.kubernetes.io/hostname
```


Yes I used our actual cluster name, it is the one that I crossed out in the name key under the metadata.
