### DISCUSSION TITLE
test connector not working

### DISCUSSION THREAD

**Discussion by abulazm22** [strimzi/strimzi-kafka-operator#5769] [Q&A] [answered]
with the following yamls
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: default-connect-cluster
  namespace: kafka-demos
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.8.1
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  config:
    group.id: default-connect-cluster
    offset.storage.topic: default-connect-cluster-offsets
    config.storage.topic: default-connect-cluster-configs
    status.storage.topic: default-connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
```
and
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: default-source-connector
  namespace: kafka-demos
  labels:
    strimzi.io/cluster: default-connect-cluster
spec:
  class: org.apache.kafka.connect.file.FileStreamSourceConnector
  tasksMax: 1
  config:
    file: "/opt/kafka/LICENSE"
    topic: my-topic
```
the connect operator is started and healthy but the connector is not created and I get the error `GET /connectors/default-source-connector/config returned 500 (Internal Server Error): Request timed out` in the strimzi operator pod
