### DISCUSSION TITLE
How to set user ACL access only topic (deny all / read some topic)

### DISCUSSION THREAD

**Discussion by l0ginp** [strimzi/strimzi-kafka-operator#5785] [Q&A] [answered]
Hi team,
How to set user ACL access only topic (deny all / read some topic)

this is my config
```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: user01
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "test_topic"
          patternType: literal
        operation: Read
```
