### DISCUSSION TITLE
Discrepancy between source and destination configuration of kafka topics

### DISCUSSION THREAD

**Discussion by Lionheart1984** [strimzi/strimzi-kafka-operator#5809] [General]
Hi all 

i am using following configuration in mirrors section for mm2 (mirrormaker 2) as 
```
 sourceConnector:
        config:
          replication.factor: 2
          offset-syncs.topic.replication.factor: 2
          sync.topic.acls.enabled: "false"
          sync.topic.configs.enabled: "true"
          refresh.topics.interval.seconds: 300 ### 5 Minutes
          replication.policy.separator: ""
          replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 2
      checkpointConnector:
        tasksMax: 30
        config:
          checkpoints.topic.replication.factor: 2
          refresh.groups.interval.seconds: 300 ### 5 Minutes
          sync.group.offsets.enabled: "true"
          sync.group.offsets.interval.seconds: 60
          emit.checkpoints.enabled: "true"
          emit.checkpoints.interval.seconds: 60
```

When looking at the configuration at destination, i see retention.bytes = -1 
but at source, i see segment.bytes = retention.bytes 

How can i make the configuration for destination same as source ? 

Thank you
