### DISCUSSION TITLE
Kafka writing messages to topic sometime error "Not Leader For Partition"

### DISCUSSION THREAD

**Discussion by l0ginp** [strimzi/strimzi-kafka-operator#5822] [Q&A]
Hi, How to solve
Kafka writing messages to topic sometime error "Not Leader For Partition"

this error
<img width="1042" alt="MicrosoftTeams-image (8)" src="https://user-images.githubusercontent.com/43605404/139802704-ec2d13bd-c72b-4130-b16e-e4e35bed8bdf.png">

topic.yaml
```yml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: prod-queue-smart-alert
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 604800000
    segment.bytes: 10737418240
```
