### DISCUSSION TITLE
topics created but data not replicated

### DISCUSSION THREAD

**Discussion by smolina74** [strimzi/strimzi-kafka-operator#5841] [General]
Hi, 
I've noticed that commenting readinessProbe and livenessProbe sections data is not replicated, although topics are created (by the way, for my experiment I always delete that mm2-offset-syncs.<target alias>.internal topic on the source side).

this is my yaml:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: backup
spec:
  clusters:
  - alias: source
    bootstrapServers: lens-cluster-molina-kafka-bootstrap.molina:9092
  - alias: backup-target
    bootstrapServers: lens-cluster-santiago3-kafka-bootstrap:9092
  connectCluster: backup-target
  # livenessProbe:
  #   initialDelaySeconds: 25
  #   timeoutSeconds: 25
  logging:
    loggers:
      connect.root.logger.level: INFO
    type: inline
  mirrors:
  - checkpointConnector:
      config:
        replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
        replication.policy.separator: ''
    groupsPattern: .*
    sourceCluster: source
    sourceConnector:
      config:
        replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
        replication.policy.separator: ''
        sync.topic.acls.enabled: 'false'
    targetCluster: backup-target
    topicsPattern: .*
  # readinessProbe:
  #   initialDelaySeconds: 25
  #   timeoutSeconds: 25
  version: 2.7.0

```
Now, if I uncomment that mirroring works.

Should I have some special consideration for these settings?
