### DISCUSSION TITLE
How can I explicitly specify NodePort int for Kafka listener / kafka-external-bootstrap ?

### DISCUSSION THREAD

**Discussion by brsolomon-deloitte** [strimzi/strimzi-kafka-operator#5845] [Q&A] [answered]
I have e.g.

```
      - name: external
        port: 9094
        type: nodeport
        tls: false
```

to enable `my-cluster-kafka-external-bootstrap`.

This results in the following spec for a `kind: Service`:

```
  ports:
    - name: tcp-external
      nodePort: 32426
      port: 9094
      protocol: TCP
      targetPort: 9094
```

where `nodePort` is randomly chosen from the available range.

How can I explicitly specify the [`NodePort`](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport) port value under a `listeners` item rather than letting it get its randomly assigned value?

I have checked out `kubectl explain kafka.spec.kafka.listeners` and am not seeing anything there.

**Comment by brsolomon-deloitte** [comment, marked as answer]
Answering my own question: set `kafka.spec.listeners[x]. configuration.bootstrap.nodePort`

as described in https://strimzi.io/blog/2019/04/23/accessing-kafka-part-2/#pre-configured-node-port-numbers

```
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 31094
```
