### DISCUSSION TITLE
Failed to create single node cluster per getting started instructions

### DISCUSSION THREAD

**Discussion by davesargrad** [strimzi/strimzi-kafka-operator#5858] [Q&A]
I'm following [these ](https://strimzi.io/quickstarts/)instructions:

When I ran the command to wait, I found that it timed out (as the instructions said it might). However I also found that the following pod was in crash loop backoff.

![image](https://user-images.githubusercontent.com/48793689/140795873-83303f27-3ec1-4bf6-bd3b-dc97cc0fa736.png)

I've got a vanilla kubernetes cluster at version 1.21.
![image](https://user-images.githubusercontent.com/48793689/140796113-7751bf89-a0dd-4fb2-8460-79b7d7d49fb6.png)

**Comment by scholzj** [comment]
The error suggests that the pod is unable to use the storage. Your storage might require you to configure some specific fsGroup or uid in the security context. You can do that in the Kafka custom resource: https://strimzi.io/docs/operators/latest/full/using.html#type-PodTemplate-reference. But what are the right values depends on your environment.

**Comment by davesargrad** [comment]
Hi.

Thanks for the fast reply.

I’ve not done anything special in setting up my storage … except of course to create my machines using virtualbox

These are vanilla fedora VMs

I’ve already been successful at getting nginx up and running in my k8s cluster 

I didn’t do anything special with storage.

How might I isolate the specific issue? What experiments would tell me what the "environment issue" actually is?

**Reply by scholzj** [reply]
Well, Kubernetes does not offer persistent storage out of the box. So you had to install something to deal with the storage provisioning etc. So that is probably what you need to look at to see what it requires etc. 

Another way might to find out what the permissions are on the volume which was created => and one you know that, you might be able to set the UID / fsGroup to the right values.

Setting the UID to 0 (root) might also help you:
```yaml
securityContext:
      runAsUser: 0
```
But it is obviously less secure.

**Comment by davesargrad** [comment]
Thanks Jakub

Pretty sure I used local storage 

Since this is dev and ephemeral works for now 
Awesome response .. I’ll check this morning and follow up

**Comment by davesargrad** [comment]
Btw typically when I set up an app to run on K8s I do take an explicit action to configure storage 

I didn’t do that with strimziio only because I was following the getting started instructions and I must have missed the bit on storage setup guidance 

I’m actually good with running as user 0 for now 

I’ll try to add that and see what happens 

I’m looking for the truly fastest start for this small dev cluster

**Comment by davesargrad** [comment]
So this is the yaml I used. I see its reference to the persistent-claim. I assumed that the operator would create the PV and the associated PVC with default values.

To get started I'm pretty sure that all I want is an ephemeral local PV.. along with running as root. I only need a single broker kafka server.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.0"
      inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
