### DISCUSSION TITLE
Using a Secret in KafkaConnector.spec.config

### DISCUSSION THREAD

**Discussion by brsolomon-deloitte** [strimzi/strimzi-kafka-operator#5969] [Q&A] [answered]
I am using `KafkaConnector` to configure [ElasticsearchSinkConnector](https://docs.confluent.io/kafka-connect-elasticsearch/current/configuration_options.html).

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: elasticsearch-sink-connector
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.confluent.connect.elasticsearch.ElasticsearchSinkConnector
  tasksMax: 24
  config:
    name: elasticsearch-sink-connector
    ...
    connection.username: elastic
    connection.password: <Value of Secret cluster-es-elastic-user .data.elastic>
```

As shown above, **is there a way for a `KafkaConnector.spec.config` to refer to a Secret?**

Specifically the Secret value is retrievable as:

```bash
kubectl get secret -n my-namespace cluster-es-elastic-user -o go-template='{{.data.elastic | base64decode}}'
```

Struggling to wrap my head around this with the KafkaConnector CRD. If this was a Pod, there would be a couple of standard ways of [exposing the Secret value](https://v1-21.docs.kubernetes.io/docs/concepts/configuration/secret/#overview-of-secrets), but here I'm not sure.

**Comment by scholzj** [comment, marked as answer]
The way you can deal with this in Strimzi is actually similar to pods. You can mount your secret as an environment variable or volume in a specific section of the `KafkaConnect` custom resource and then you can use Kafka configuration providers to use the data from the secret: https://strimzi.io/docs/operators/latest/full/using.html#type-ExternalConfiguration-reference

You could either use the `FileConfigProvider` / `DirectoryConfigProvider` to load data from Secrets mounted as files or the `EnvVarConfigProvider` to do it from Env Vars.

Apart from that, you could also use the Kubernetes Config Provider as well: https://github.com/strimzi/kafka-kubernetes-config-provider

**Comment by brsolomon-deloitte** [comment]
Yep, that's exactly what I was looking for. Thank you!

Ended up with:

```
kind: KafkaConnect
...
  externalConfiguration:
    volumes:
      - name: connector-auth
        secret:
          secretName: {{ .Values.kafkaConnect.elasticsearch.authSecret.name }}
  config:
    config.providers: directory
    config.providers.directory.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
```

```
kind: KafkaConnector
...
spec:
  ...
  config:
    connection.password: "${directory:/opt/kafka/external-configuration/connector-auth:elastic}"

```
