### DISCUSSION TITLE
Mirrormaker replicating data 3 times

### DISCUSSION THREAD

**Discussion by smolina74** [strimzi/strimzi-kafka-operator#5974] [General]
hi,

1) I have two kafka clusters running in two different namespaces (source: santiago3 and target: santiago5)
In every experiment I'm recreating the target kafka cluster and also deleting the "mm2-offset-syncs.target.internal" topic in the source side

2) I run the following kafkamirrormaker2 in santiago5 (target side)

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: restore-e728055d-52de-4ca2-bcc4-a409a68aaa82
spec:
  clusters:
  - alias: source
    bootstrapServers: cluster-santiago3-kafka-bootstrap.santiago3:9092
  - alias: target
    bootstrapServers: cluster-santiago5-kafka-bootstrap:9092
  connectCluster: target
  livenessProbe:
    initialDelaySeconds: 25
    timeoutSeconds: 25
  logging:
    loggers:
      connect.root.logger.level: INFO
    type: inline
  mirrors:
  - checkpointConnector:
      config:
        replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
        replication.policy.separator: ''
    groupsPattern: .*
    sourceCluster: source
    sourceConnector:
      config:
        replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
        replication.policy.separator: ''
        sync.topic.acls.enabled: 'false'
    targetCluster: target
    topicsPattern: ^(?!.*backup.api).*
  readinessProbe:
    initialDelaySeconds: 25
    timeoutSeconds: 25
  version: 2.8.1
```

3) Then when I count the number of messages in the source side, for a particular topic, I get 39. But when I count the number of messages for the same topic in the target side, sometimes I'm getting 39, others 118 (same 39 messages replicated 3 times) and others 156 (same 39 messages replicated 4 times). 

Any idea?

thanks,
Santiago

**Comment by scholzj** [comment]
I'm afraid it is not entirely clear what the full setup is and what exactly are you doing. Can you provide more step-by-step guide to reproduce it? I think that without knowing the full setup and all the steps, it is hard to understand what exactly are you doing.

**Reply by smolina74** [reply]
Thanks for replying

My setup. I'm executing this in openshift
Client Version: 4.6.0-202104221811.p0-7eec1ed
Kubernetes Version: v1.20.0+87cc9a4

This is the kafka I'm installing in namespace santiago3:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster-santiago3
spec:
  kafka:
    version: 2.8.1
    replicas: 3

    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true

    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 50Gi
        deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml

    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - kafka
                topologyKey: "kubernetes.io/hostname"

  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml

    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - zookeeper
                topologyKey: "kubernetes.io/hostname"

  entityOperator:
    topicOperator: {}
    userOperator: {}
```
and this is the kafka I'm installing in santiago5:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster-santiago5
spec:
  kafka:
    version: 2.8.1
    replicas: 3

    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"

    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true

    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 50Gi
        deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml

    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - kafka
                topologyKey: "kubernetes.io/hostname"

  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml

    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: "app.kubernetes.io/name"
                      operator: In
                      values:
                        - zookeeper
                topologyKey: "kubernetes.io/hostname"

  entityOperator:
    topicOperator: {}
    userOperator: {}

```

And I'm using mirrormaker for replicating from the kafka in santiago3 namespace to the kafka in santiago5 namespace.

Do you need more info?

**Reply by scholzj** [reply]
Yeah, so ... what exactly are your steps? The MM2 recreating part is confusing. So I guess you have the 2 Kafka clusters. You send _100_ messages to some topic in the source cluster. And then you do what exactly?

**Reply by smolina74** [reply]
I have kafka cluster in santiago3 with a topic called mytopic containing 39 messages and using the kafkamirrormaker2 yaml I'm copying what I have in santiago3 to santiago5. But when doing it sometimes, when chcking mytopic I got the right number of messages on the target side (santiago5) but others I get 3 or 4 times the amount of those messages.

**Reply by scholzj** [reply]
But you said you are recreating it -> that sounds like something what can easily cause duplicates.

**Reply by scholzj** [reply]
I mean, it is important how you recreate it to make sure the data are not mirrored again and again with each recreation.

**Reply by smolina74** [reply]
before running each of my tests, first I'm deleting the target cluster (the one in santiago5), deleting the kafkatopics in santiago5 and then I create it again. In this way I can run the experiment in a totally clean target environment. I'm also checking topics there right after I recreate the cluster and of course there's nothing there.

**Reply by scholzj** [reply]
Do you also delete the PVCs? Because they would be recovered and they have the data.

**Reply by smolina74** [reply]
yes, I'm deleting PVCs also.  Basically I'm running the following script for cleaning that environment:

```
oc delete kafkamirrormaker2 -n santiago5 --all
oc delete kafka -n santiago5 --all
oc delete kafkatopics -n santiago5 --all
oc delete pvc data-0-cluster-santiago5-kafka-0 data-0-cluster-santiago5-kafka-1 data-0-cluster-santiago5-kafka-2 data-cluster-santiago5-zookeeper-0 data-cluster-santiago5-zookeeper-1 data-cluster-santiago5-zookeeper-2 -n santiago5
```

**Reply by smolina74** [reply]
I found what could be the problem. It turns out that source kafka cluster (santiago3) had be used before also as a target, receiving stuff from another kafka cluster. Then, when the replication to santiago5 happened also mirror maker related topics, like this one "mirrormaker2-cluster-offsets", were copied and that what was causing the multiple replication issue. In my new version I've excluded those mirror maker related topics from the replication and the replication is working fine. Question, do you know if there is a way for prefixing all of those mirrormaker/kafka connect related topics so they can be easily identified?

**Reply by scholzj** [reply]
I don't think you can prefix them somehow easily. But you can probably configure the names for some of these topics individually. For example by adding something like this:
```yaml
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
```

To the `config` section of the target cluster you might be able to configure the names used by the underlying Connect topic. There might be some other options in other places for some other topics as well (I do not have an exhaustive list I'm afraid).
