### DISCUSSION TITLE
Log4j2 CVE (CVE-2021-44228)

### DISCUSSION THREAD

**Discussion by scholzj** [strimzi/strimzi-kafka-operator#6023] [General]
**Info for everyone asking about the Log4j2 CVE (CVE-2021-44228) ...**

* Kafka and ZooKeeper are using Log4j1. Originally, it was suggested that Log4j1 might affected when you configured it to use the `JMSAppender` (which I doubt anyone did with Kafka, since that would be a bit weird) - but it seems this is not the case according to the latest information. So your Kafka brokers, ZooKeeper nodes, Kafka Connects etc. should be most probably fine.
* The affected components are the Operators, the Bridge and Cruise Control which all use Log4j2. **We did new releases which fixes the CVE - we recommend everyone to upgrade to it:**
    * The [Bridge 0.21.0 release](https://github.com/strimzi/strimzi-kafka-bridge/releases/tag/0.21.0)
    * The [Operators 0.26.1 patch release](https://github.com/strimzi/strimzi-kafka-operator/releases/tag/0.26.1) which includes the new version of the Strimzi Kafka Bridge and updates the Log4j2 dependency in our Operators and in Cruise Control.
* Strimzi Drain Cleaner uses Log4j2 only as a test dependency and should not be affected.

---

**If you for any reason cannot upgrade to Strimzi Operators 0.26.1 / Strimzi Kafka Bridge 0.21.0, you should be able to mitigate the CVE in existing versions by setting the Java system property `-Dlog4j2.formatMsgNoLookups=true` ...**

* For Cluster Operator, edit the Deployment and set the environment variable `JAVA_OPTS` to `-Dlog4j2.formatMsgNoLookups=true`
* For User and Topic operators and for the Kafka Bridge, you can use the `jvmOptions` to set the property:
  ```yaml
        jvmOptions:
          javaSystemProperties:
          - name: log4j2.formatMsgNoLookups
            value: "true"
  ```
  (You can do this in the following places: in the Kafka resource in .spec.cruiseControl, .spec.entityOperator.topicOperator and .spec.entityOperator.userOperator and in the KafkaBridge resource in .spec )
* For Cruise Control, you can pass the environment variable `KAFKA_OPTS` using the `.spec.cruiseControl.template` section of the `Kafka` custom resource:
  ```yaml
    # ...
    cruiseControl:
      template:
        cruiseControlContainer:
          env:
          - name: KAFKA_OPTS
            value: -Dlog4j2.formatMsgNoLookups=true
    # ...
  ```
* For Kafka Bridge, set the `JAVA_OPTS` environment variable using the `.spec.template` section:
  ```yaml
    template:
      bridgeContainer:
        env:
        - name: JAVA_OPTS
          value: -Dlog4j2.formatMsgNoLookups=true
  ```

When the pods are starting, you should see a line like this:
```
exec /usr/bin/tini -w -e 143 -- java ...
```
and there, somewhere after the `java` keyword, you should see the option being set. So you know that it was passed to the pods.

----

_(13.12.2021: Updates with a working way for Cruise Control)_
_(13.12.2021: Updates with a working way for Kafka Bridge)_
_(13.12.2021: Update for Drain Cleaner which has Log4j2 only as a test dependency)_
_(14.12.2021: 0.26.1 release)_
