### DISCUSSION TITLE
Mirror Maker 2 Negative Offsets

### DISCUSSION THREAD

**Discussion by urton** [strimzi/strimzi-kafka-operator#6082] [General]
We recently started a migration from a traditional self-managed Apache Kafka cluster to Strimzi. We enabled group offset sync and something I'm struggling to fully understand is why the mirrored group has a current-offset matching (or close to matching) the source offset, but then the log-end-offset essentially starts over resulting in a negative lag. Is this just aesthetic? The lag is slowly moving closer to 0 but some of our negative lags are very "large". Several hundred million. I verified all the data has moved over, but I'm struggling on this lag issue.

Any help clearing this up is much appreciated!

**Comment by scholzj** [comment]
I'm not sure I follow what do you mean with _negative lag_ here. Maybe you can provide more details or some examples?

**Reply by urton** [reply]
Thanks for the quick reply @scholzj. Example below.

**Comment by urton** [comment]
```
$ kafka-consumer-groups.sh --bootstrap-server my.strimzi.cluster:443 --command-config ${SSL_CLIENT_FILE} --describe --group my-group

Consumer group 'my-group' has no active members.

GROUP		TOPIC		PARTITION	CURRENT-OFFSET	LOG-END-OFFSET  LAG		CONSUMER-ID	HOST	CLIENT-ID
my-groug	my-topic	4		249358195	6481035		-242877160	-		-	-
my-group	my-topic	5		249479276	6628555		-242850721	-		-	-
my-group	my-topic	6		249307720	6382889		-242924831	-		-	-
my-group	my-topic	7		249333351	6447255		-242886096	-		-	-
my-group	my-topic	0		249328507	6304497		-243024010	-		-	-
my-group	my-topic	1		249340201	6286979		-243053222	-		-	-
my-group	my-topic	2		249339598	6384640		-242954958	-		-	-
my-group	my-topic	3		249336895	6344119		-242992776	-		-	-
my-group	my-topic	8		249368568	6390421		-242978147	-		-	-
my-group	my-topic	9		249319569	6379316		-242940253	-		-	-
my-group	my-topic	10		249339115	6388443		-242950672	-		-	-
my-group	my-topic	11		249478879	6341630		-243137249	-		-	-

$ kafka-consumer-groups.sh --bootstrap-server my.legacy.cluster:9092 --describe --group my-group

GROUP		TOPIC		PARTITION	CURRENT-OFFSET	LOG-END-OFFSET	LAG		CONSUMER-ID			HOST		CLIENT-ID
my-group	my-topic	9		252072134	252072134	0		consumer-1-xxxxx-8a985875be7a	/x.x.x.x	consumer-1
my-group	my-topic	10		252092284	252092284	0		consumer-1-xxxxx-8a985875be7a	/x.x.x.x	consumer-1
my-group	my-topic	11		252097489	252097489	0		consumer-1-xxxxx-8a985875be7a	/x.x.x.x	consumer-1
my-group	my-topic	0		252080774	252080774	0		consumer-1-xxxxx-c03960eb87e0	/x.x.x.x	consumer-1
my-group	my-topic	1		252092610	252092610	0		consumer-1-xxxxx-c03960eb87e0	/x.x.x.x	consumer-1
my-group	my-topic	2		252094190	252094190	0		consumer-1-xxxxx-c03960eb87e0	/x.x.x.x	consumer-1
my-group	my-topic	6		252060021	252060021	0		consumer-1-xxxxx-fb7b93c4241d	/x.x.x.x	consumer-1
my-group	my-topic	7		252088387	252088387	0		consumer-1-xxxxx-fb7b93c4241d	/x.x.x.x	consumer-1
my-group	my-topic	8		252124449	252124449	0		consumer-1-xxxxx-fb7b93c4241d	/x.x.x.x	consumer-1
my-group	my-topic	3		252090940	252090940	0		consumer-1-xxxxx-5232473666a7	/x.x.x.x	consumer-1
my-group	my-topic	4		252109115	252109115	0		consumer-1-xxxxx-5232473666a7	/x.x.x.x	consumer-1
my-group	my-topic	5		252095913	252095913	0		consumer-1-xxxxx-5232473666a7	/x.x.x.x	consumer-1
```

**Reply by scholzj** [reply]
That is weird. What is your MM2 configuration and what version do you use? The offsets of the individual messages will never be in sync. So it is expected that the log-end-offset differs. But MM2 when syncing the offsets adjusts the commits to the new offset numbers. So it looks like something didn't worked in that part of MM2.

**Reply by urton** [reply]
```
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  labels:
    app.my.domain/component: mm2
    app.my.domain/name: strimzi-mm2-prod
    app.my.domain/path: prod
    my.domain/project: my-project
    my.domain/environment: prod
    strimzi.io/cluster: my-project-prod
  name: my-project-prod
  namespace: my-project-strimzi-prod
spec:
  clusters:
  - alias: source-other
    bootstrapServers: x.x.x.x:9092,x.x.x.x:9092,x.x.x.x:9092
  - alias: source-legacy
    bootstrapServers:  x.x.x.x:9092,x.x.x.x:9092,x.x.x.x:9092
    config:
      max.poll.records: 20000
      receive.buffer.bytes: 33554432
      send.buffer.bytes: 33554432
      max.partition.fetch.bytes: 33554432
      message.max.bytes: 37755000
      compression.type: gzip
      max.request.size: 26214400
      buffer.memory: 524288000
      batch.size: 52428
  - alias: target-strimzi
    authentication:
      type: scram-sha-512
      username: kmm2user
      passwordSecret:
        secretName: kmm2user
        password: password
    bootstrapServers: my-project-prod-kafka-bootstrap.my-project-strimzi-prod.svc.cluster.local:9094
    config:
      max.poll.records: 20000
      receive.buffer.bytes: 33554432
      send.buffer.bytes: 33554432
      max.partition.fetch.bytes: 33554432
      message.max.bytes: 37755000
      compression.type: gzip
      max.request.size: 26214400
      buffer.memory: 524288000
      offset.flush.timeout.ms: 30000
      batch.size: 52428
      config.storage.replication.factor: 3
      offset.storage.replication.factor: 3
      status.storage.replication.factor: 3
    tls:
      trustedCertificates:
        - secretName: my-project-prod-cluster-ca-cert
          certificate: ca.crt
  connectCluster: target-strimzi
  jvmOptions:
    -Xmx: 8G
    -Xms: 6G
  mirrors:
  - sourceCluster: source-other
    targetCluster: target-strimzi
    sourceConnector:
      tasksMax: 3
      config:
        max.poll.records: 20000
        receive.buffer.bytes: 33554432
        send.buffer.bytes: 33554432
        max.partition.fetch.bytes: 33554432
        message.max.bytes: 37755000
        compression.type: gzip
        max.request.size: 26214400
        buffer.memory: 524288000
        batch.size: 52428
        offset-syncs.topic.replication.factor: 1
        replication.factor: 1
        replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
        replication.policy.separator: ""
        sync.topic.acls.enabled: "false"
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 3
    groupsPattern: .*
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
    topicsPattern: ^***$
  - sourceCluster: source-legacy
    targetCluster: target-strimzi
    sourceConnector:
      tasksMax: 30
      config:
        max.poll.records: 20000
        receive.buffer.bytes: 33554432
        send.buffer.bytes: 33554432
        max.partition.fetch.bytes: 33554432
        message.max.bytes: 37755000
        compression.type: gzip
        max.request.size: 26214400
        buffer.memory: 524288000
        batch.size: 52428
        offset-syncs.topic.replication.factor: 1
        replication.factor: 1
        replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
        replication.policy.separator: ""
        sync.topic.acls.enabled: "false"
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
        sync.group.offsets.enabled: true
    groupsPattern: .*
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
    topicsPattern: ^***$
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  livenessProbe:
    initialDelaySeconds: 90
  replicas: 6
  resources:
    limits:
      cpu: 4
      memory: 14Gi
    requests:
      cpu: 2
      memory: 10Gi
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: my.domain/node-type
                operator: In
                values:
                - infra
              - key: infra.my.domain/type
                operator: In
                values:
                - kafkamm2
                #- shared
              - key: my.domain/environment
                operator: DoesNotExist
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.my.domain/name
                operator: In
                values:
                - strimzi-mm2-prod
              - key: app.my.domain/component
                operator: In
                values:
                - mm2
            topologyKey: kubernetes.io/hostname
      metadata:
        labels:
          app.my.domain/component: mm2
          app.my.domain/name: strimzi-mm2-prod
          app.my.domain/path: prod
          pod-anti-affinity: strimzi-mm2-prod
          my.domain/project: my-project
          my.domain/environment: prod
          strimzi.io/cluster: my-project-prod
      tolerations:
      - effect: NoSchedule
        key: infra.my.domain/type
        operator: Equal
        value: kafkamm2
        #value: shared
  version: 2.8.1
```
