### DISCUSSION TITLE
tls-external type not available in 0.27 version of the operator?

### DISCUSSION THREAD

**Discussion by hari819** [strimzi/strimzi-kafka-operator#6117] [Q&A]
I wanted to provide my own user certificate for mTLS , so since the type "tls-external" is not available in 0.22.1 version which i was running before , i started a clean setup of 0.27.0 , 

[https://strimzi.io/docs/operators/in-development/full/using.html#tls_client_authentication_using_a_certificate_issued_outside_the_user_operator](url)

but i see that the kafka CRD is missing this type "tls-external" ,

>                                type:
>                                 type: string
>                                 enum:
>                                   - tls
>                                   - scram-sha-512
>                                   - oauth

has anyone tried this on latest version or does it work in 0.26 or 0.25 version ?

**Comment by hari819** [comment]
and i get this error while deploying the cluster , 

> invalid: spec.kafka.listeners.authentication.type: Unsupported value: "tls-external": supported values: "tls", "scram-sha-512", "oauth"


```
#https://strimzi.io/docs/operators/latest/full/using.html#overview-str
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 2.8.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls-external
        configuration:
          brokerCertChainAndKey:
            certificate: tls.crt
            key: tls.key
            secretName: tls-secret-kafka
```
