### DISCUSSION TITLE
Kafka data got compacted/deleted not respecting the configuration.

### DISCUSSION THREAD

**Discussion by alok87** [strimzi/strimzi-kafka-operator#6122] [Q&A]
We are using **Strimzi** to manage our Kafka cluster in Kubernetes.

Below is our Strimzi configuration for our Kafka cluster (removed the SSL and authorization confs below):
```.properties
[kafka@k8s-kafka-2 kafka]$ cat /tmp/strimzi.properties
##########
# User provided configuration
##########
log.message.format.version=2.6
log.retention.hours=-1
offsets.retention.minutes=525600
offsets.topic.replication.factor=3
```

We are using Infinite log retention to never delete data from our Kafka topics. 
We also have a default cleanup policy (which is delete and not compact)

Today, our topics oldest offset moved from 0 to high numbers. We lost a lot of earlier events due to this.

We are trying to figure out why it happened when we are using infnite retention.

Any help is appreciated.

**Comment by scholzj** [comment]
I don't think anyone can say what happened from 4 lines of some properties file. But one thing to keep in mind is that these are just the defaults -> they do not say anything about the actual configuration of the individual topics.

**Reply by alok87** [reply]
I have added all the details as more comments below. Please check once, appreciate your help @scholzj

**Reply by alok87** [reply]
@scholzj `cat /tmp/strimzi.properties` does not show log.retention.bytes=-1 
does it mean bytes are not taking effect? Can you suggest where can I check if it is taking effect?

**Reply by scholzj** [reply]
Not necessarily. `-1` is the default. Plus depending on when you configured it it might have been set dynamically in which case the file would update only in the next pod restart.

**Reply by alok87** [reply]
@scholzj 
- I checked the code for delete segments in kafka. It deletes based on time and bytes only. Here it [is](https://github.com/apache/kafka/blob/22d056c9b76c9bf8417d8701594d1fcee1c6a655/core/src/main/scala/kafka/log/UnifiedLog.scala#L1373-L1381).
- We also verified retentionMinutes and retentionHours also support -1 due to [this](https://github.com/apache/kafka/blob/2.6/core/src/main/scala/kafka/server/KafkaConfig.scala#L1606-L1619) code. We see there is a [test case](https://github.com/apache/kafka/commit/3139cc31f6cab26f3dfd429c36280d1567dbf61a#diff-f4b04bc51f23ea749861aecc07d402ce0dd160551bb7af8b772f6dd9b5f8e729R94-R96) also to ensure this and has been supported since 0.9.0.0.

We created the cluster with [this](https://github.com/strimzi/strimzi-kafka-operator/discussions/6122#discussioncomment-1887802) yaml. Our Kafka topics were created 8 months back and suddenly on 21st December, data dropped from 3.1TB to 500GB. 

The only 2 change we made in 8 months was 
- add the tolerations to make kafka pods schedule in different nodes. 
- increase the size recently from 3TB to 4TB when it got full.  We rolled out this change using Strimzi.

We have not made any change after that. I have also shared the Kafka topics yaml and the kafka topics configuration using kafka-config.sh script.  

I have added all broker configuration and topic configuration [here](https://github.com/strimzi/strimzi-kafka-operator/discussions/6122#discussioncomment-1895026). Please take a look once.

**Comment by alok87** [comment]
Those are only the configuration we have made on top of the default configuration when you create a Kafka cluster. Which scenarios or configurations can Kafka topics move its offset from 0 to higher number is what I was looking for.

Like log.retention.hours is one such configuration, what other configuration i should look for and which place? Help is what I am looking for, some guidance on debugging this.

Thanks for replying.

**Reply by scholzj** [reply]
Have you checked the blog post we published recently about it? https://strimzi.io/blog/2021/12/17/kafka-segment-retention/

**Reply by alok87** [reply]
Reading

**Reply by alok87** [reply]
@scholzj This was really helpful "These parameters can be also be set at broker level and overridden at the topic level."
Sharing the broker and topic configuration.
- Broker Configuration: I created three files broker0.conf broker1.conf and broker3.conf using kafka-config.sh
```
$ grep retention broker*conf
broker0.conf:  log.cleaner.delete.retention.ms=86400000 sensitive=false synonyms={DEFAULT_CONFIG:log.cleaner.delete.retention.ms=86400000}
broker0.conf:  log.retention.hours=-1 sensitive=false synonyms={STATIC_BROKER_CONFIG:log.retention.hours=-1, DEFAULT_CONFIG:log.retention.hours=168}
broker0.conf:  log.retention.minutes=null sensitive=false synonyms={}
broker0.conf:  offsets.retention.check.interval.ms=600000 sensitive=false synonyms={DEFAULT_CONFIG:offsets.retention.check.interval.ms=600000}
broker0.conf:  log.retention.check.interval.ms=300000 sensitive=false synonyms={DEFAULT_CONFIG:log.retention.check.interval.ms=300000}
broker0.conf:  log.retention.ms=null sensitive=false synonyms={}
broker0.conf:  log.retention.bytes=-1 sensitive=false synonyms={DEFAULT_CONFIG:log.retention.bytes=-1}
broker0.conf:  offsets.retention.minutes=525600 sensitive=false synonyms={STATIC_BROKER_CONFIG:offsets.retention.minutes=525600, DEFAULT_CONFIG:offsets.retention.minutes=10080}
broker1.conf:  log.cleaner.delete.retention.ms=86400000 sensitive=false synonyms={DEFAULT_CONFIG:log.cleaner.delete.retention.ms=86400000}
broker1.conf:  log.retention.hours=-1 sensitive=false synonyms={STATIC_BROKER_CONFIG:log.retention.hours=-1, DEFAULT_CONFIG:log.retention.hours=168}
broker1.conf:  log.retention.minutes=null sensitive=false synonyms={}
broker1.conf:  offsets.retention.check.interval.ms=600000 sensitive=false synonyms={DEFAULT_CONFIG:offsets.retention.check.interval.ms=600000}
broker1.conf:  log.retention.check.interval.ms=300000 sensitive=false synonyms={DEFAULT_CONFIG:log.retention.check.interval.ms=300000}
broker1.conf:  log.retention.ms=null sensitive=false synonyms={}
broker1.conf:  log.retention.bytes=-1 sensitive=false synonyms={DEFAULT_CONFIG:log.retention.bytes=-1}
broker1.conf:  offsets.retention.minutes=525600 sensitive=false synonyms={STATIC_BROKER_CONFIG:offsets.retention.minutes=525600, DEFAULT_CONFIG:offsets.retention.minutes=10080}
broker2.conf:  log.cleaner.delete.retention.ms=86400000 sensitive=false synonyms={DEFAULT_CONFIG:log.cleaner.delete.retention.ms=86400000}
broker2.conf:  log.retention.hours=-1 sensitive=false synonyms={STATIC_BROKER_CONFIG:log.retention.hours=-1, DEFAULT_CONFIG:log.retention.hours=168}
broker2.conf:  log.retention.minutes=null sensitive=false synonyms={}
broker2.conf:  offsets.retention.check.interval.ms=600000 sensitive=false synonyms={DEFAULT_CONFIG:offsets.retention.check.interval.ms=600000}
broker2.conf:  log.retention.check.interval.ms=300000 sensitive=false synonyms={DEFAULT_CONFIG:log.retention.check.interval.ms=300000}
broker2.conf:  log.retention.ms=null sensitive=false synonyms={}
broker2.conf:  log.retention.bytes=-1 sensitive=false synonyms={DEFAULT_CONFIG:log.retention.bytes=-1}
broker2.conf:  offsets.retention.minutes=525600 sensitive=false synonyms={STATIC_BROKER_CONFIG:offsets.retention.minutes=525600, DEFAULT_CONFIG:offsets.retention.minutes=10080}
```
- Topic Configuration: using kafka-config.sh
```
$ grep -i retention topic-titan-users.conf
  retention.ms=-1 sensitive=false synonyms={}
  retention.bytes=-1 sensitive=false synonyms={DEFAULT_CONFIG:log.retention.bytes=-1}
  delete.retention.ms=86400000 sensitive=false synonyms={DEFAULT_CONFIG:log.cleaner.delete.retention.ms=86400000}
```

**Reply by alok87** [reply]
@scholzj we also increased our storage.size from 2TB to 3TB recently. So our current max storage size is 3TB still and we see the deletion has triggered when the storage size hit 3TB. Kafka cleanup got triggered when it hit 3TB. 

But with default cleanup policy (DELETE), cleanup should not have triggered right?
<img width="1334" alt="Screenshot 2022-01-02 at 2 38 25 PM" src="https://user-images.githubusercontent.com/9006763/147871294-605958dc-6cb2-4820-b2dd-7f7d2302ddaa.png">
.

**Comment by alok87** [comment]
Adding details that might explain my problem:

- Topic Oldest Offset jumping from 0 to 16million
![Screenshot 2021-12-30 at 8 07 10 PM](https://user-images.githubusercontent.com/9006763/147761222-e7ab4f7f-8f70-4268-8d8d-7680078ed377.png)
Here is the screenshot of topic moving from 0 to 16Million offset number on 21st December. Topic name is `ts.titan.users`
- Sharing the topic configuration for the same topic:
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  creationTimestamp: "2021-02-27T12:07:44Z"
  generation: 2
  labels:
    strimzi.io/cluster: k8s
    manager: okhttp
    operation: Update
    time: "2021-12-21T15:25:33Z"
  name: ts.titan.users
  namespace: kafka
spec:
  config:
    max.message.bytes: "1572864"
  partitions: 1
  replicas: 1
  topicName: ts.titan.users
status:
  conditions:
  - lastTransitionTime: "2021-12-21T15:25:33.507828Z"
    status: "True"
    type: Ready
  observedGeneration: 2
```

This is happening for all topics not just one. Shared you the details of one. Let me know if adding more info here can help. Please suggest what more info I should share.

**Comment by alok87** [comment]
Added Kafka configuration as well:

`kubectl get kafka -n kafka -o yaml k8s`
```yaml
spec:
  entityOperator:
    template:
      pod:
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: secondary_ondemand
    topicOperator: {}
    userOperator: {}
  kafka:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app.kubernetes.io/name
              operator: In
              values:
              - kafka
          topologyKey: kubernetes.io/hostname
    config:
      log.message.format.version: "2.6"
      log.retention.hours: -1
      message.max.bytes: 1572864
      offsets.retention.minutes: 525600
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - authentication:
        type: tls
      name: external
      port: 9094
      tls: true
      type: loadbalancer
    - authentication:
        type: tls
      name: internal
      port: 9093
      tls: true
      type: internal
    logging:
      loggers:
        kafka.root.logger.level: DEBUG
      type: inline
    replicas: 3
    storage:
      class: gp2-expandable
      deleteClaim: false
      size: 3049Gi
      type: persistent-claim
      pod:
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: secondary_ondemand
  zookeeper:
    replicas: 3
    storage:
      class: gp2-expandable
      deleteClaim: false
      size: 50Gi
      type: persistent-claim
    template:
      pod:
        tolerations:
        - effect: NoSchedule
          key: dedicated
          operator: Equal
          value: secondary_ondemand
status:
```
