### DISCUSSION TITLE
kafka connect integration with datadog

### DISCUSSION THREAD

**Discussion by amitca71** [strimzi/strimzi-kafka-operator#6258] [Q&A]
Hi,
I use MSK and deployed strimzi KafkaConnect (my kafka cluster in on MSK). I'm able to get the metrics, but was not able to see them in datadog (i followed the datadog tutorial, and it worked: https://docs.datadoghq.com/agent/kubernetes/prometheus/), but couldnt make it happen with the strimzi prometheous... i added the annotation part to the prometheus operator, but this didnt work. i tryed to add it to prometheus.yaml, but then i got : error: error validating "prometheus.yaml": error validating data: ValidationError(Prometheus.spec): unknown field "template" in com.coreos.monitoring.v1.Prometheus.spec; if you choose to ignore these errors, turn validation off with --validate=false
Thanks,
Amit

**Comment by iMajna** [comment]
Well, I believe you need to approach it differently. 
I haven't tried it but I have done it for Kafka/Zookeeper/CruiseControl and many other and for each worked out. 

First of all you need to enable `metrics` exporting if it is not by default: 

In your KafkaConnect CR under `spec.kafka:`

```
    jmxOptions: {}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-zk-metrics
```

and then again under `spec.kafka` you would have something like this: 

```
    template:
      pod:
        metadata:
          annotations:
            ad.datadoghq.com/kafka-connect.check_names: '["jmx"]'
            ad.datadoghq.com/kafka.init_configs: '[{"is_jmx": true, "collect_default_metrics": true}]'
            ad.datadoghq.com/kafka.instances: '[{"host": "%%host%%","port":"<port>"}]'
```

Now, this will only extract metrics about resources such as cpu/memory and etc. 

If you want more metrics related to kafkaconnect producer and consumer (connectors) you have 2 options: 

1. Openmetrics (this is generating custom metrics/tags and it can be quite $$$)
2. Potentially Kafka plugin of Datadog?


## OpenMetrics

This is how I did it for Zookeeper:
```
    template:
      pod:
        metadata:
          annotations:
            ad.datadoghq.com/zookeeper.check_names: '["openmetrics"]'
            ad.datadoghq.com/zookeeper.init_configs: '[{}]'
            ad.datadoghq.com/zookeeper.instances: |
              [
                {
                  "prometheus_url": "http://%%host%%:9404/metrics",
                  "namespace": "zookeeper",
                  "metrics": [
                    "zookeeper_leader",
                    "process_open_fds",
                    "process_max_fds",
                    "zookeeper_tick",
                    "zookeeper_quorumsize",
                    "zookeeper_avgrequestlatency"
                  ]
                }
              ]
            ad.datadoghq.com/zookeeper.logs: '[{"source":"zookeeper","service":"zookeeper"}]'
```

## Kafka plugin from Datadog

```
    template:
      pod:
        metadata:
          annotations:
            ad.datadoghq.com/kafka.check_names: '["kafka"]'
            ad.datadoghq.com/kafka.init_configs: |
              [
                {
                  "is_jmx": true,
                  "collect_default_metrics": true,
                  "conf": [
                    {
                      "include": {
                        "domain": "kafka.log",
                        "bean_regex": "kafka\\.log:type=Log,name=Size,topic=(.*?),partition=(.*?)(?:,|$)",
                        "tags": { "topic": "$1", "partition": "$2" },
                        "attribute": {
                          "Value": {
                            "alias": "kafka.log.partition.size",
                            "metric_type": "gauge"
                          }
                        }
                      }
                    },
....
....
            ad.datadoghq.com/kafka.instances: '[{"host": "%%host%%","port":"9999"}]'
```

I would only change domains for kafkaconnect related ones, maybe it would work (haven't tried but in process in couple of days from now) 


Hope some of this helps you. Hit me up if you have some questions.
