### DISCUSSION TITLE
Unable to deploy Kafka when createGlobalResources is set to false

### DISCUSSION THREAD

**Discussion by mohitruhaan** [strimzi/strimzi-kafka-operator#6289] [Q&A]
Hello Experts,

While trying to deploy Strimzi version 0.27, we tried to set the flag: createGlobalResources to "false" in Values.yaml.
To our understanding, it means strimzi should work fine when used for managing Kafka within a namespace, this not needing global resources.
But we are not able to deploy Kafka within a namespace. We observe service account and authorization related errors as below:

```
2022-02-01 10:55:53 ERROR AbstractOperator:432 - Reconciliation #2(watch) Kafka(databus/databus-cluster): Reconciliation completion handler failed
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.96.0.1/apis/kafka.strimzi.io/v1beta2/namespaces/databus/kafkas/databus-cluster. Message: Forbidden!Configured _**service account doesn't have access. Service account may have been revoked.**_ kafkas.kafka.strimzi.io "databus-cluster" is forbidden: User "system:serviceaccount:databus:strimzi-cluster-operator" cannot get resource "kafkas" in API group "kafka.strimzi.io" in the namespace "databus": **_RBAC: [clusterrole.rbac.authorization.k8s.io "strimzi-cluster-operator-namespaced" not found, clusterrole.rbac.authorization.k8s.io "strimzi-entity-operator" not found]._**
```

Could you please suggest? Thanks!

**Comment by scholzj** [comment]
> To our understanding, it means strimzi should work fine when used for managing Kafka within a namespace, this not needing global resources.

That is not correct. IIRC, what this mode does is that it will not install the global resources such as the ClusterRoles or ClusterRoleBindings. But it expects you to do so outside of the Helm Installation (at least for the ClusterRoles and CRDs). See #1436 for more details.

You can in theory not install the ClusterRoleBindings and have some basic functionality. But there will be some limitations to what the operator can do (no rack awareness, storage resizing, node port listeners). You would also still need to install the ClusterRoles for it.

**Reply by mohitruhaan** [reply]
Thanks @scholzj ,
But why Strimzi needs cluster wide resources if run with the single namespace option?
Our use case is a shared Kafka service restricted by namespaces. Is there any workaround for dealing with Cluster Role Requirements?

**Reply by scholzj** [reply]
You might be able to work around it by creating a Role / RoleBindings for the operator (again, as I explained, with limited functionality). It is just not what the flag on the Helm Chart does. It skips the installation of the cluster-wide resources and expects you to install them in some other way. 

So what you can try is to download the installation YAMLs and just modify the ClusterRoles / CllusterRoleBindings to Role / RoleBindings. But keep in mind that CRDs are always cluster wide, so it will never be trully namespaced.

**Reply by mohitruhaan** [reply]
Thanks @scholzj ,

Even after changing the ClusterRoles / ClusterRoleBindings to Role / RoleBindings , we faced this error while deploying Kakfa:

```
io.vertx.core.impl.NoStackTraceThrowable: Failure executing: GET at: https://10.96.0.1/apis/rbac.authorization.k8s.io/v1/clusterrolebindings/strimzi-databus-databus-cluster-kafka-init. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. clusterrolebindings.rbac.authorization.k8s.io "strimzi-databus-databus-cluster-kafka-init" is forbidden: User "system:serviceaccount:databus:strimzi-cluster-operator" cannot get resource "clusterrolebindings" in API group "rbac.authorization.k8s.io" at the cluster scope.
```

Looking at the code, we see that ClusterroleBindings is still created as part of init container. On debugging further, we found that init container should be created if rackawareness is "true" looking at this commit:

https://github.com/sknot-rh/strimzi/commit/b0c04b4ff41d688d716ec5454082a95e873d551b

Do you think we should add a check that rackawarness should be checked before clusterrolebindings is created?


https://github.com/strimzi/strimzi-kafka-operator/blame/main/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/KafkaConnectAssemblyOperator.java#L113

**Reply by scholzj** [reply]
How does your Kafka / KafkaConnect custom resource look like?

**Reply by mohitruhaan** [reply]
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name:  {{ include "databus.fullname" . }}-cluster
spec:
  kafka:
    template:
      persistentVolumeClaim:
        metadata:
          annotations:
            <<removed>>
    version: 2.8.0
    replicas: {{.Values.replicas }}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      # - name: tls
      #   port: 9093
      #   type: internal
      #   tls: true
      #   configuration:
      #     brokerCertChainAndKey:
      #       secretName: databus-ca
      #       certificate: ca.crt
      #       key: ca.key
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          # brokerCertChainAndKey:
          #   secretName: databus-ca
          #   certificate: ca.crt
          #   key: ca.key
          bootstrap:
            nodePort: 32100
          {{- with .Values.brokerConfig }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
    {{- with .Values.kafkaResources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.kafkaConfig }}
    config:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: {{  .Values.kafkaStorage.size  }}
        deleteClaim: false
  zookeeper:
    template:
      persistentVolumeClaim:
        metadata:
          annotations:
              << removed >>
    replicas: {{.Values.zookeeper.replicas }}
     {{- with .Values.zookeeperResources }}
    resources:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
    storage:
      type: persistent-claim
      size: {{  .Values.zookeeperStorage.size  }}
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
```
