### DISCUSSION TITLE
How to create ingress with cert-manager?

### DISCUSSION THREAD

**Discussion by 1nd2rd3st** [strimzi/strimzi-kafka-operator#6300] [Q&A]
Hello,

we are currently running strimzi 0.23.0 and have the demand, that kafka has to be available for services outside of our kubernets cluster.
I thought about using the ingress option provided by strimzi. Our cluster is running the [nginx-ingress-controller](https://kubernetes.github.io/ingress-nginx/)

For the certificate management we use cert-manager. To create certificates with an ingress, the usual way described in the [cert-manager-docu](https://cert-manager.io/docs/usage/ingress/) is to provide the secretName for the certificates in the ingress controller under _tls.secretName_:
``` 
tls: # < placing a host in the TLS config will determine what ends up in the cert's subjectAltNames
  - hosts:
    - example.com
    secretName: myingress-cert # < cert-manager will store the created certificate in this secret.
```

But unfortunatly strimzi is not creating such secretName in the created ingress. This results in an error for the ingress _Skipped a TLS block: spec.tls[0].secretName: Required value_

Am I overlooking a solution to make cert-manager + strimzi running.

Any help is appreciated.
Regards.
