### DISCUSSION TITLE
KafkaUser with tls-external

### DISCUSSION THREAD

**Discussion by seemasanjaisinghani** [strimzi/strimzi-kafka-operator#6328] [General]
Here is our configuration : 
1. We have configured brokerCertChainAndKey: in kafkaCluster.yaml
The certificates we are using for brokerCertChaninAnd key are generated from GOogle CAS
----------------------->
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka_cluster_name }}
spec:
  clusterCa:
    generateCertificateAuthority: {{ .Values.kafka_generate_cert }}
  clientsCa:
    generateCertificateAuthority: {{ .Values.kafka_generate_client_cert }}
  kafka:
    version: 2.8.0
    replicas: {{ .Values.kafka_replicas }}
    logging:
      type: inline
      loggers:
        kafka.authorizer.logger: "DEBUG"
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
          type: tls
        configuration:
          brokerCertChainAndKey:
            secretName: kafka-gcp-cert-2
            certificate: tls.crt
            key: tls.key
          loadBalancerSourceRanges:
            - {{ .Values.kafka_listeners_external_load_balancer_source_ranges }}
<----------------------------------

2. We have created KafkaUser.yaml with authentication:tls-external

---------------------------------------->
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: acl-user1
  labels:
    strimzi.io/cluster: test-cluster
spec:
  authentication:
    type: tls-external 
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: kafka-cert-topic
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: kafka-cert-topic
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read
        host: "*"
<-------------------------------------------------

3. When our above generated KafkaUser with "CN:acl-user1" tried to communicate with broker/bootstrap, its shows handshake failed on kafka Cluster.
For user CN=acl-user1, we have our on prem certs generated with same CN name as user. 
When the user CN=acl-user1, tries to communicate with kafka, which truststore/CA does it verify the keystore of KafkaUser?

- Does it verify it against brokerCertChainandKey or CLinetCA?
- Is the truststore KafkaUser external certs are verified with, is configurable?

4. If we disable authentication on kafkaCluster then the SSL handshake works well, but with authentication:true , the handshake fails.

**Comment by scholzj** [comment]
Please format the examples as code to make them readable. And please make sure to share the actual values and not just some templates. Without that it is hard to understand what re you actually doing.

**Reply by seemasanjaisinghani** [reply]
`apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka_cluster_name }}
spec:
  clusterCa:
    generateCertificateAuthority: {{ .Values.kafka_generate_cert }}
  clientsCa:
    generateCertificateAuthority: {{ .Values.kafka_generate_client_cert }}
  kafka:
    version: 2.8.0
    replicas: {{ .Values.kafka_replicas }}
    logging:
      type: inline
      loggers:
        kafka.authorizer.logger: "DEBUG"
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
          type: tls
        configuration:
          brokerCertChainAndKey:
            secretName: kafka-gcp-cert-2
            certificate: tls.crt
            key: tls.key
          loadBalancerSourceRanges:
            - {{ .Values.kafka_listeners_external_load_balancer_source_ranges }}
          bootstrap:
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
          brokers:
          - broker: 0
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
          - broker: 1
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
          - broker: 2
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
    config:
      offsets.topic.replication.factor: {{ .Values.kafka_offsets_topic_replication_factor }}
      transaction.state.log.replication.factor: {{ .Values.kafka_transaction_state_log_replication_factor }}
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
      security.inter.broker.protocol: "PLAINTEXT"
      zookeeper.connection.timeout.ms: 18000
      ssl.endpoint.identification.algorithm: ""
      listener.name.internal.ssl.endpoint.identification.algorithm: ""
    template:
      pod:
        metadata:
          #annotations:
          #  sidecar.istio.io/inject: "true"
          #  traffic.sidecar.istio.io/includeInboundPorts: "*"
          #  traffic.sidecar.istio.io/excludeInboundPorts: "9091,2181,2888,3888"
          #  traffic.sidecar.istio.io/excludeOutboundPorts: "9091,2181,2888,3888"
          labels:
          {{- if .Values.istiolabel }}
            istio.io/rev:  {{ .Values.istiolabel }}
          {{- end }}
            
    storage:
      type: {{ .Values.kafka_storage_type }}
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka_storage_volume_size }}
        deleteClaim: true
  zookeeper:
    replicas: {{ .Values.zookeeper_replicas }}  
    config:
      quorumListenOnAllIPs: true
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper_storage_size }}
      deleteClaim: true
    template:
      pod:
        metadata:
          #annotations:
          #  sidecar.istio.io/inject: "true"
          #  traffic.sidecar.istio.io/includeInboundPorts: "*"
          #  traffic.sidecar.istio.io/excludeInboundPorts: "2888,3888,2181,9091"
          #  traffic.sidecar.istio.io/excludeOutboundPorts: "2888,3888,2181,9091"
          labels:
          {{- if .Values.istiolabel }}
            istio.io/rev:  {{ .Values.istiolabel }}
          {{- end }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        metadata:
          #annotations:
          #  sidecar.istio.io/inject: "true"
          #  traffic.sidecar.istio.io/includeInboundPorts: "*"
          #  traffic.sidecar.istio.io/excludeInboundPorts: "2888,3888,2181,9091"
          #  traffic.sidecar.istio.io/excludeOutboundPorts: "2888,3888,2181,9091"
          labels:
          {{- if .Values.istiolabel }}
            istio.io/rev:  {{ .Values.istiolabel }}
          {{- end }}`

**Reply by seemasanjaisinghani** [reply]
@scholzj  sorry for formatting but it doesn't pick up the code format, these are my real templates. Copied from our repo

**Reply by seemasanjaisinghani** [reply]
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ .Values.kafka_cluster_name }}
spec:
  clusterCa:
    generateCertificateAuthority: {{ .Values.kafka_generate_cert }}
  clientsCa:
    generateCertificateAuthority: {{ .Values.kafka_generate_client_cert }}
  kafka:
    version: 2.8.0
    replicas: {{ .Values.kafka_replicas }}
    logging:
      type: inline
      loggers:
        kafka.authorizer.logger: "DEBUG"
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
          type: tls
        configuration:
          brokerCertChainAndKey:
            secretName: kafka-gcp-cert-2
            certificate: tls.crt
            key: tls.key
          loadBalancerSourceRanges:
            - {{ .Values.kafka_listeners_external_load_balancer_source_ranges }}
          bootstrap:
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
          brokers:
          - broker: 0
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
          - broker: 1
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
          - broker: 2
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
    config:
      offsets.topic.replication.factor: {{ .Values.kafka_offsets_topic_replication_factor }}
      transaction.state.log.replication.factor: {{ .Values.kafka_transaction_state_log_replication_factor }}
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
      security.inter.broker.protocol: "PLAINTEXT"
      zookeeper.connection.timeout.ms: 18000
      ssl.endpoint.identification.algorithm: ""
      listener.name.internal.ssl.endpoint.identification.algorithm: ""
    template:
      pod:
        metadata:
          #annotations:
          #  sidecar.istio.io/inject: "true"
          #  traffic.sidecar.istio.io/includeInboundPorts: "*"
          #  traffic.sidecar.istio.io/excludeInboundPorts: "9091,2181,2888,3888"
          #  traffic.sidecar.istio.io/excludeOutboundPorts: "9091,2181,2888,3888"
          labels:
          {{- if .Values.istiolabel }}
            istio.io/rev:  {{ .Values.istiolabel }}
          {{- end }}
            
    storage:
      type: {{ .Values.kafka_storage_type }}
      volumes:
      - id: 0
        type: persistent-claim
        size: {{ .Values.kafka_storage_volume_size }}
        deleteClaim: true
  zookeeper:
    replicas: {{ .Values.zookeeper_replicas }}  
    config:
      quorumListenOnAllIPs: true
    storage:
      type: persistent-claim
      size: {{ .Values.zookeeper_storage_size }}
      deleteClaim: true
    template:
      pod:
        metadata:
          #annotations:
          #  sidecar.istio.io/inject: "true"
          #  traffic.sidecar.istio.io/includeInboundPorts: "*"
          #  traffic.sidecar.istio.io/excludeInboundPorts: "2888,3888,2181,9091"
          #  traffic.sidecar.istio.io/excludeOutboundPorts: "2888,3888,2181,9091"
          labels:
          {{- if .Values.istiolabel }}
            istio.io/rev:  {{ .Values.istiolabel }}
          {{- end }}
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        metadata:
          #annotations:
          #  sidecar.istio.io/inject: "true"
          #  traffic.sidecar.istio.io/includeInboundPorts: "*"
          #  traffic.sidecar.istio.io/excludeInboundPorts: "2888,3888,2181,9091"
          #  traffic.sidecar.istio.io/excludeOutboundPorts: "2888,3888,2181,9091"
          labels:
          {{- if .Values.istiolabel }}
            istio.io/rev:  {{ .Values.istiolabel }}
          {{- end }}
```

**Reply by seemasanjaisinghani** [reply]
KafkaUser -

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: acl-user1
  labels:
    strimzi.io/cluster: test-cluster
spec:
  authentication:
    type: tls-external 
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: kafka-cert-topic
          patternType: literal
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: kafka-cert-topic
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read
        host: "*"
      # Example Producer Acls for topic my-topic
      - resource:
          type: topic
          name: kafka-cert-topic
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: kafka-cert-topic
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: kafka-cert-topic
          patternType: literal
        operation: Describe
        host: "*"
```
