### DISCUSSION TITLE
Kafka cluster keeps restarting by Operator

### DISCUSSION THREAD

**Discussion by zkutasi** [strimzi/strimzi-kafka-operator#6333] [Q&A] [answered]
Hi,

I have seen there are similar questions here already, but I wanted to post my log to ask why my cluster is constantly kept restarting by the Kafka operator? For me the reason is not obvious.

[operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/8028457/operator.log)

My current Kafka config (I am testing Strimzi currently):
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi-kafka-cluster
spec:
  clientsCa:
    generateCertificateAuthority: false
  kafka:
    jvmOptions:
      javaSystemProperties:
        - name: javax.net.debug
          value: ssl
    version: 3.0.0
    replicas: 3
    listeners:
      - name: intp
        port: 9092
        type: internal
        tls: false
      - name: inttls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
        configuration:
          brokerCertChainAndKey:
            secretName: strimzi-kafka-internal-server-cert-secret
            certificate: srvcert.pem
            key: srvprivkey.pem
      - name: extp
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          bootstrap:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: bootstrap.strimzi.kafka.ezolkut.se
              external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
          - broker: 0
            advertisedHost: broker0.strimzi.kafka.ezolkut.se
            annotations:
              external-dns.alpha.kubernetes.io/hostname: broker0.strimzi.kafka.ezolkut.se
              external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 1
            advertisedHost: broker1.strimzi.kafka.ezolkut.se
            annotations:
              external-dns.alpha.kubernetes.io/hostname: broker1.strimzi.kafka.ezolkut.se
              external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 2
            advertisedHost: broker2.strimzi.kafka.ezolkut.se
            annotations:
              external-dns.alpha.kubernetes.io/hostname: broker2.strimzi.kafka.ezolkut.se
              external-dns.alpha.kubernetes.io/ttl: "60"
      - name: exttls
        port: 9095
        type: loadbalancer
        tls: true
        authentication:
          type: tls
        configuration:
          brokerCertChainAndKey:
            secretName: strimzi-kafka-external-sip-tls-server-cert-secret
            certificate: srvcert.pem
            key: srvprivkey.pem
          bootstrap:
            annotations:
              external-dns.alpha.kubernetes.io/hostname: bootstrap.strimzi.kafka.ezolkut.se
              external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
          - broker: 0
            advertisedHost: broker0.strimzi.kafka.ezolkut.se
            annotations:
              external-dns.alpha.kubernetes.io/hostname: broker0.strimzi.kafka.ezolkut.se
              external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 1
            advertisedHost: broker1.strimzi.kafka.ezolkut.se
            annotations:
              external-dns.alpha.kubernetes.io/hostname: broker1.strimzi.kafka.ezolkut.se
              external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 2
            advertisedHost: broker2.strimzi.kafka.ezolkut.se
            annotations:
              external-dns.alpha.kubernetes.io/hostname: broker2.strimzi.kafka.ezolkut.se
              external-dns.alpha.kubernetes.io/ttl: "60"
    config:
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator:
      secretPrefix: strimzi-kafka-cluster-user-
```
