### DISCUSSION TITLE
Will initContainers work with  kafka cluster

### DISCUSSION THREAD

**Discussion by subinmt** [strimzi/strimzi-kafka-operator#6335] [Q&A] [answered]
Hello Team,

We are looking to deploy a init container inside our  Kafka cluster yaml. Here I am pasting my yamls. Please suggest a solution, or please confirm the init containers will work with kafka. We are using strimzi kafka operator version 0.27.1.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi
  namespace: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        configuration:
          bootstrap:
            annotations:
              danm.k8s.io/interfaces: '[ {"clusterNetwork":"flannel-local", "ip": "dynamic"}, {"tenantNetwork":"tenant-vxlan", "ip": "dynamic"}]'
          brokers:
            - broker: 0
              annotations:
                danm.k8s.io/interfaces: '[ {"clusterNetwork":"flannel-local", "ip": "dynamic"}, {"tenantNetwork":"tenant-vxlan", "ip": "dynamic"}]'
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      inter.broker.protocol.version: "3.0"
      log.retention.hours: 1
    storage:
      type: ephemeral
    template:
      initContainer:
        - name: routes
          image: busybox:1.28
          command: [ 'sh', '-c', "/mnt/routes/run.sh" ]
          volumeMounts:
            - name: routes-script
              mountPath: /mnt/routes
                securityContext:
                  capabilities:
                  add: [ "NET_ADMIN" ]
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - kafka
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - kafka
                topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: routes-script
          configMap:
            name: routes-script
            defaultMode: 0777
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - kafka
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - kafka
                topologyKey: "kubernetes.io/hostname"
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

**Comment by scholzj** [comment, marked as answer]
You have to follow the API => you cannot add random new fields into the custom resource. These are all the things supports for the init container template: https://strimzi.io/docs/operators/latest/full/using.html#type-ContainerTemplate-reference (so no, you cannot add your own init containers)

**Reply by cstmgl** [reply]
sorry to come back to this, but I had the same question, and see that your answer is valid, but I looked at the API and just declared some random env values but I don't see them anywhere on the generated Deployment.yml 
So my question is, what are the initContainer templates used for?

for example this is what I put in mine:

```
spec:
  image: custom-image:1.2.3
  replicas: 2
  template:
    pod:
      metadata:
        labels:
          app: my-app
        annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/scheme: 'http'
          prometheus.io/port: '9404'
    initContainer:
      env: 
        - name: THIS_AS_NO_REASON
          value: NO_VALUE
```
I'm guessing this would attach to a init Container of the KafkaConnect generated deployment but I struggle to find out in which conditions the KafkaConnect deployment would automatically generate a initContainer on it's own.

To give you some context the reason why I wanted an init container is that I would like to ensure there is 2 things:
1 - network connectivity to kafka (maybe this is already provided by the cluster operator itself)
2- ensure my kafka connect internal topics are already created, so my application does not create them automatically
