### DISCUSSION TITLE
SSL handshake:- Failed to process post-handshake messages

### DISCUSSION THREAD

**Discussion by subinmt** [strimzi/strimzi-kafka-operator#6370] [Q&A] [answered]
Hi Team,

I am running Kafka cluster with ingress external listener. But when I am trying to test the producer/consumer I am getting the following error message.

nginx version: nginx/1.19.9
Strimzi Kafka Operator version: 0.27.1

```
$ bin/kafka-console-producer.sh --broker-list dev-kafka-bootstrap.mydomain.com:443 --producer-property security.protocol=SSL --producer-property ssl.truststore.password=password --producer-property ssl.truststore.location=/tmp/truststore.jks --topic kafka-topic

[2022-02-15 06:09:48,699] WARN [Producer clientId=console-producer] Bootstrap broker dev-kafka-bootstrap.mydomain.com:443 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2022-02-15 06:09:48,869] ERROR [Producer clientId=console-producer] Connection to node -1 (dev-kafka-bootstrap.mydomain.com/30.xx.xx.xx:443) failed authentication due to: Failed to process post-handshake messages (org.apache.kafka.clients.NetworkClient)
[2022-02-15 06:09:48,869] WARN [Producer clientId=console-producer] Bootstrap broker dev-kafka-bootstrap.mydomain.com:443 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2022-02-15 06:09:48,998] ERROR [Producer clientId=console-producer] Connection to node -1 (dev-kafka-bootstrap.mydomain.com/30.xx.xx.xx:443) failed authentication due to: Failed to process post-handshake messages (org.apache.kafka.clients.NetworkClient)
[2022-02-15 06:09:48,998] WARN [Producer clientId=console-producer] Bootstrap broker dev-kafka-bootstrap.mydomain.com:443 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient
```

**Ingress Controller logs:**

```
2022/02/15 01:41:24 http: TLS handshake error from 102.xx.xx.xx:53074: EOF
E0215 02:51:10.305192       7 server.go:75] "Failed to decode request body" err="couldn't get version/kind; json parse error: unexpected end of JSON input"
2022/02/15 02:51:10 http: TLS handshake error from 167.xx.xx.xx:53220: tls: client requested unsupported application protocols ([h2])
E0215 03:51:48.779847       7 server.go:75] "Failed to decode request body" err="couldn't get version/kind; json parse error: unexpected end of JSON input"
E0215 06:03:24.303060       7 server.go:75] "Failed to decode request body" err="couldn't get version/kind; json parse error: unexpected end of JSON input
```
Nginx ingress controller installed with SSL Passthrough:
```
    Args:
      /nginx-ingress-controller
      --publish-service=$(POD_NAMESPACE)/ingress-kafka-ingress-nginx-controller
      --election-id=ingress-controller-leader
      --controller-class=k8s.io/kafka
      --ingress-class=kafka
      --configmap=$(POD_NAMESPACE)/ingress-kafka-ingress-nginx-controller
      --validating-webhook=:8443
      --validating-webhook-certificate=/usr/local/certificates/cert
      --validating-webhook-key=/usr/local/certificates/key
      --enable-ssl-passthrough=true
```
Could you please help me to resolve the "failed authentication due to: Failed to process post-handshake messages" error?

**Comment by scholzj** [comment, marked as answer]
Assuming the errors from your Ingress log are related to the Kafka client connection, I guess it suggests that the TLS passthrough might not work? Because with TLS passthrough, I don't think the Ingress should be in any way involved in the TLS handshake.

**Reply by subinmt** [reply]
@scholzj But already I shared the ingress controller args and the passthrough is enabled there. Then what is the issue here and how can we solve this? I followed the below documentation for deploying the Kafka cluster with ingress external listener:
https://strimzi.io/blog/2019/05/23/accessing-kafka-part-5/

**Reply by scholzj** [reply]
I see it in the command, but I do not know if it is used in the actual pods etc. I'm just saying what I think based on the errors you shared.

**Reply by subinmt** [reply]
@scholzj  The ssl-passthrough is enabled and we can see that from the ingress controller args. The TLS handshake is managing the ingress controller I think. Here you can see some of the quotes from the ingress controller site about the ssl passthrough:
```
SSL Passthrough leverages [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) and reads the virtual domain from the TLS negotiation, which requires compatible clients. After a connection has been accepted by the TLS listener, it is handled by the controller itself and piped back and forth between the backend and the client.

If there is no hostname matching the requested host name, the request is handed over to NGINX on the configured passthrough proxy port (default: 442), which proxies the request to the default backend.
```
I followed your documentation and everything is working except the produced/consumer. May I know what I missed? Is there any way to solve this post ssl handshake issue? If you are not aware of this, is there any way to escalate this?

**Reply by scholzj** [reply]
Right - it needs to do the part of the handshake to find out the hostname and redirect it, you are right. TLS client authentication is also involved in the TLS handshakes. So you should double check if you have that configured correctly (not sure if you use it or not since you did not shared the broker configuration).

**Reply by subinmt** [reply]
@scholzj I am sure that the SSL passthrough was installed on the ingress controller correctly and I did that via helm values.yaml file. I am sharing the relevant part of the SSL passthrough in the values.yaml file:

```
  extraArgs: 
    enable-ssl-passthrough: "true"
```
Reff URL: https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml#L177

**Kafka Cluster:**
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi
  namespace: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          class: kafka
          bootstrap:
            host: dev-kafka-bootstrap.mydomain.com
            annotations:
              danm.k8s.io/interfaces: '[ {"clusterNetwork":"flannel-local", "ip": "dynamic"}, {"clusterNetwork":"mx-linknet", "ip": "30.xx.xx.xx"} ]'
          brokers:
          - broker: 0
            host: dev-kafka-brokers.mydomain.com
            annotations:
              danm.k8s.io/interfaces: '[ {"clusterNetwork":"flannel-local", "ip": "dynamic"}, {"clusterNetwork":"mx-linknet", "ip": "30.xx.xx.xx"} ]'
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      inter.broker.protocol.version: "3.0"
      log.retention.hours: 1
    storage:
      type: ephemeral
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - kafka
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - kafka
              topologyKey: "kubernetes.io/hostname"
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - kafka
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - zookeeper
              topologyKey: "kubernetes.io/hostname"
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

**Reply by scholzj** [reply]
Well, you certainly have TLS client authentication enabled in the broker. So do you use it in your client?

**Reply by subinmt** [reply]
@scholzj  I didn't get that exactly. I am trying to hit the following command from my kafka-0 broker pod(inside pod).

```
$ bin/kafka-console-producer.sh --broker-list dev-kafka-bootstrap.mydomain.com:443 --producer-property security.protocol=SSL --producer-property ssl.truststore.password=password --producer-property ssl.truststore.location=/tmp/truststore.jks --topic kafka-topic
```

Is there anything I missed, correct me, please.

**Reply by scholzj** [reply]
Well, since you configured TLS client authentication, you will need to create a user and configure keystore as well. Or you need to disable the TLS client authentication in the listener configuration.

**Reply by subinmt** [reply]
@scholzj  The truststore.jks file I created with the help of "ca.crt" and I copied the truststore file to /tmp directory of the kafka broker pod (inside kafka broker pod). You can see that jks file I am using the previously provided command. I created the truststore file with the help of your official doc:
https://strimzi.io/blog/2019/05/23/accessing-kafka-part-5/

```
kubectl -n kafka get secret strimzi-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 -d > ca.crt 
keytool -import -trustcacerts -alias root -file ca.crt -keystore truststore.jks -storepass password -noprompt
```

**Reply by scholzj** [reply]
I'm not saying the truststore is wrong. I'm saying you are missing keystore with the user certificate for the TLS client authentication.

**Reply by subinmt** [reply]
@scholzj  Can you provide the exact documentation, so that I can focus on that? Also I don't think the ingress external listener work without tls. I tried that the pod is not creating. Better please provide the keystore exact documentation and I a follow-up from there.

**Reply by scholzj** [reply]
I do not have anything at hand right now. How to configure the client is covered in the Kafka docs. Creating users using the User Operator is described in the Strimzi docs. As I said, you can also just disable the TLS client authentication in your Kafka custom resource if that is what you want to use.

**Reply by subinmt** [reply]
@scholzj Kafka user is that required for my commands testing? If I disabled the tls, the kafka pod is not creating here.
```
    listeners:
      - name: external
        port: 9094
        type: ingress
        tls: false
        #authentication:
          #type: tls
```
