### DISCUSSION TITLE
Kafkauser Secret Certificate validity and all

### DISCUSSION THREAD

**Discussion by stuartm21** [strimzi/strimzi-kafka-operator#6396] [Q&A]
Hi Team,

I have created a Kafkauser in my k8s cluster and now I am having some doubts. When the kafka user is created, the user credentials are created in a Secret. Inside that secret we can see the following datas as well:
```
Data
====
user.p12:       2722 bytes
user.password:  12 bytes
ca.crt:         1854 bytes
user.crt:       1468 bytes
user.key:       1708 bytes
```
Our application needs to use the user and its credentials for authentication and to produce or consume messages. So my questions are

1. How the kafkauser certificats are renewing here?
2. Will strimzi/your apps notify us once you renewed the certificates?

**Comment by scholzj** [comment]
Re 1) Strimzi will automatically renew the certificates before their expiration. The new certificate will be in the updated secret.
Re 2) No, currently there is no special notification.

**Reply by stuartm21** [reply]
@scholzj So the 1st case, how long the existing/new cert work, I meant the validity. 
2nd case, If there is no notification, our apps will go down! Is there any alternative solution for this? How can we solve this?

3. Can we use our own certs inside kafkauser?
4.  Reffer to Q1, is there any way to block the cert renewal for a2 year or 5year? like below?

```
clusterCa:
  validityDays: 3650
  renewalDays: 30 
clientsCa:
  validityDays: 3650
  renewalDays: 30
```

**Reply by scholzj** [reply]
IIRC, the validity you configure in the Clients CA will be applied to the certificates (if you change it, it is applied to new certificates, it does not regenerate existing ones immediately). You cannot provide your own user certificates, but you can provide your own Clients CA and generate the certificates your self.

**Reply by stuartm21** [reply]
@scholzj  I am sorry. I am a bit confused with your queries. Can you please explain and reply with question numbers.

How can I configure the validity in the client CA certs? That is actually created by Kafka/k8s. 

2. If there is no notification, there is a chance of our apps will go down! Is there any alternative solution for this? How can we solve this?
3. Can we use our own certs inside kafkauser-> How can provide the CA through the kafkauser yaml file. Could you please share the documentation?
4. Refer to Question 1, is there any way to block the cert renewal for a2 year or 5year?

**Reply by scholzj** [reply]
Re 2) That really depends on how you run your application. As with any certificates, they expire and you need to make sure they are updated when needed. We have the Kubernetes Config Provider which allows you to load the certicicates directly from the Kubernetes Secret in your Java clients. That might or might not work for your usecases and your applications.

Re 3) No, you cannot. You can provide your own Clients CA as part of the Kafka cluster.

Re 4) As I said above, the validity is configured in the clientsCa section. You can set it to as long as you want. But you cannot block the renewal when the certificates expire.

**Reply by stuartm21** [reply]
@scholzj Thanks . Can you please provide the steps or exact documentation of validity configuration(Ref 4)? How I can set it to as long as I want?

**Reply by scholzj** [reply]
That is the YAML you copied above 40 minutes ago. I do not have the link docs at hand right now. But I'm sure it is documented -> the docs are at https://strimzi.io

**Reply by stuartm21** [reply]
@scholzj Thanks, Sure I will go through below one, but that is actually editing on the kafka cluster level not kafka user level?

https://strimzi.io/docs/operators/latest/full/configuring.html#proc-renewing-ca-certs-manually-deployment-configuration-kafka
```
clusterCa:
  validityDays: 3650
  renewalDays: 30 
clientsCa:
  validityDays: 3650
  renewalDays: 30
```
5. How long before the renewal of the normal certs?

**Reply by scholzj** [reply]
> but that is actually editing on the kafka cluster level not kafka user level?

That is correct, this is a property of the whole Clients CA and not of individual user certificates.

> How long before the renewal of the normal certs?

The default is 365 validity / renewal 30 deys before expiration IIRC. It will be in the docs as well.

**Reply by stuartm21** [reply]
Thanks, @scholzj Thanks for all your help. :-)

**Reply by stuartm21** [reply]
@scholzj One quick doubt, If I added the following code block in my kafka cluster file:
```
clusterCa:
    renewalDays: 30
    validityDays: 365
    generateCertificateAuthority: true
  clientsCa:
    renewalDays: 30
    validityDays: 365
    generateCertificateAuthority: true
```

How about the kafka secret is updating? Will create a new secret for the kafka cluster and kafka user? Or only update the certs inside the existing Kafka k8s secret?

**Reply by scholzj** [reply]
Sorry, I'm not sure I follow.
a) You have the YAML missaligned -> not sure if only in the example aboce or in the actual custom resource
b) These are the default values, so did you changed something actually?
c) As mentioned earlier -> the new values will be used when a new certificate is actually needed and geenrated. It will not geenrate new certificates just because the values here changed.

**Reply by stuartm21** [reply]
@scholzj 
a) This is just an example yaml for reference.
b) Yes I changed the default values to 3year, this would be my original values:
```
clusterCa:
  renewalDays: 30
  validityDays: 1095
  generateCertificateAuthority: true
clientsCa:
  renewalDays: 30
  validityDays: 1095
  generateCertificateAuthority: true
```
c) So I hope the secret will not recreate or renamed.?

**Reply by stuartm21** [reply]
@scholzj  Can you please provide an update on the above queries?

**Reply by scholzj** [reply]
Sorry, I'm not sure what exactly are you asking there.

**Reply by stuartm21** [reply]
@scholzj  As per your previous update, you are saying that "the new values will be used when a new certificate is actually needed and generated. It will not generate new certificates just because the values here changed." That means secret will not recreate or renamed right? 
Also, how is this in the case of ca.crt inside the Kafka user secret?
```
Data
====
ca.crt:         1854 bytes
user.crt:       1468 bytes
user.key:       1704 bytes
user.p12:       2722 bytes
user.password:  12 bytes
```
Will the old ca.crt be replaced with a new one?  or the new and old ca.crt will stay here together?

**Reply by stuartm21** [reply]
@scholzj Can you please provide an update on the above queries?

**Reply by scholzj** [reply]
Yes, that means the secrets will not be recreated or renamed. The ca.crt should be the current ca.crt of the Clients CA.

**Reply by stuartm21** [reply]
@scholzj The kafka cluster cert is renewing as I expected but the kafka-user cert is not updating here. This is my kafka cluster(test cluster) spec:

```
spec:
  clusterCa:
    renewalDays: 1
    validityDays: 1
    generateCertificateAuthority: true
  clientsCa:
    renewalDays: 1
    validityDays: 1
    generateCertificateAuthority: true
```

**Cluster CA:**
```
Issuer: O=io.strimzi, CN=cluster-ca v0
        Validity
            Not Before: Feb 27 05:12:23 2022 GMT
            Not After : Feb 28 05:12:23 2022 GMT
        Subject: O=io.strimzi, CN=cluster-ca v0
```

**Kafka User Cert:**
```
Issuer: O=io.strimzi, CN=clients-ca v0
        Validity
            Not Before: Feb 24 04:02:40 2022 GMT
            Not After : Feb 25 04:02:40 2022 GMT
        Subject: O=io.strimzi, CN=clients-ca v0
```
