### DISCUSSION TITLE
Zookeeper is not able to start. no space left on device

### DISCUSSION THREAD

**Discussion by trezorg** [strimzi/strimzi-kafka-operator#6399] [Q&A]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
Zookeeper is not able to start. MountVolume.SetUp failed for volume. no space left on device

**To Reproduce**
2. Create Custom Resource
```
helm repo add strimzi https://strimzi.io/charts/
helm upgrade kafka kafka --create-namespace --namespace kafka --debug --install --wait --atomic --timeout 600s --set tag=minikube
```
3. Run command '
`
kubectl describe pods echo-zookeeper-0 -n kafka
`

```
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    45m                   default-scheduler  Successfully assigned kafka/echo-zookeeper-0 to minikube
  Warning  FailedMount  45m                   kubelet            MountVolume.SetUp failed for volume "zookeeper-nodes" : write /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~secret/zookeeper-nodes/..2022_02_19_08_50_38.3787359075/echo-zookeeper-0.crt: no space left on device
  Warning  FailedMount  45m                   kubelet            MountVolume.SetUp failed for volume "cluster-ca-certs" : write /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~secret/cluster-ca-certs/..2022_02_19_08_50_38.1028744460/ca.crt: no space left on device
  Warning  FailedMount  45m                   kubelet            MountVolume.SetUp failed for volume "kube-api-access-lnhpg" : write /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~projected/kube-api-access-lnhpg/..2022_02_19_08_50_38.1340754100/token: no space left on device
  Warning  FailedMount  45m                   kubelet            MountVolume.SetUp failed for volume "zookeeper-nodes" : write /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~secret/zookeeper-nodes/..2022_02_19_08_50_39.1324922041/echo-zookeeper-0.p12: no space left on device
  Warning  FailedMount  45m                   kubelet            MountVolume.SetUp failed for volume "cluster-ca-certs" : write /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~secret/cluster-ca-certs/..2022_02_19_08_50_39.3308813699/ca.password: no space left on device
  Warning  FailedMount  45m                   kubelet            MountVolume.SetUp failed for volume "kube-api-access-lnhpg" : write /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~projected/kube-api-access-lnhpg/..2022_02_19_08_50_39.545493937/ca.crt: no space left on device
  Warning  FailedMount  45m                   kubelet            MountVolume.SetUp failed for volume "zookeeper-nodes" : write /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~secret/zookeeper-nodes/..2022_02_19_08_50_40.1071632211/echo-zookeeper-0.password: no space left on device
  Warning  FailedMount  45m                   kubelet            MountVolume.SetUp failed for volume "cluster-ca-certs" : write /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~secret/cluster-ca-certs/..2022_02_19_08_50_40.1760936368/ca.p12: no space left on device
  Warning  FailedMount  45m                   kubelet            MountVolume.SetUp failed for volume "kube-api-access-lnhpg" : write /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~projected/kube-api-access-lnhpg/..2022_02_19_08_50_40.2469295928/namespace: no space left on device
  Warning  FailedMount  5m11s (x87 over 45m)  kubelet            (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[kube-api-access-lnhpg zookeeper-nodes cluster-ca-certs], unattached volumes=[kube-api-access-lnhpg strimzi-tmp data zookeeper-metrics-and-logging zookeeper-nodes cluster-ca-certs]: timed out waiting for the condition
  Warning  FailedMount  39s                   kubelet            Unable to attach or mount volumes: unmounted volumes=[zookeeper-nodes cluster-ca-certs kube-api-access-lnhpg], unattached volumes=[zookeeper-metrics-and-logging zookeeper-nodes cluster-ca-certs kube-api-access-lnhpg strimzi-tmp data]: timed out waiting for the condition
```

**Expected behavior**
Is is supposed all configmaps, secrets, PV would be mounted

**Environment (please complete the following information):**
 - Strimzi version: 0.28.0
 - Installation method: Helm chart, 0.28.0
 - Kubernetes cluster: Kubernetes 1.23.1
 - Infrastructure: Minikube v1.25.1

**YAML files and logs**

*kafka.yaml*

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: echo
spec:
  kafka:
    template:
      pod:
        tmpDirSizeLimit: 100Mi
    replicas: 3
    version: 3.1.0
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "DEBUG"
    resources:
      requests:
        memory: 512m
        cpu: "0.3"
      limits:
        memory: 512m
        cpu: "0.3"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
    authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      log.retention.bytes: 1073741824 # 1G
      log.segment.bytes: 104857600 # 100MB
      log.segment.ms: 86400000 # 1 day
      log.retension.ms: 2592000000 # month
      log.preallocate: true
      log.cleaner.min.cleanable.ratio: 0.2
      log.cleaner.max.compaction.lag.ms: 86400000 # 1 day
      unclean.leader.election.enable: "true"
      min.insync.replicas: 2
      inter.broker.protocol.version: 3.1
      ssl.cipher.suites: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      ssl.enabled.protocols: "TLSv1.2"
      ssl.protocol: "TLSv1.2"
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: jmx-prometheus-exporter
          key: kafka
  zookeeper:
    template:
      pod:
        tmpDirSizeLimit: 100Mi
    replicas: 1
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "DEBUG"
    resources:
      requests:
        memory: 256m
        cpu: "0.1"
      limits:
        memory: 512m
        cpu: "0.1"
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: jmx-prometheus-exporter
          key: zookeeper
  entityOperator:
    userOperator:
          resources:
            requests:
              cpu: "0.1"
              memory: 128Mi
            limits:
              cpu: "0.1"
              memory: 256Mi
```

*values.yaml*

```
strimzi-kafka-operator:
  tmpDirSizeLimit: 100Mi
  enabled: true
```

*Chart.yaml*

```apiVersion: v2
name: kafka
description: A Helm chart for Kubernetes strimzi kafka operator

type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:

  - name: strimzi-kafka-operator
    alias: strimzi-kafka-operator
    repository: "@strimzi"
    version: 0.28.0
    condition: strimzi-kafka-operator.enabled
    tags:
      - kafka
      - strimzi-kafka-operator

```

`
kubectl describe pods echo-zookeeper-0 -n kafka
`

```
Name:           echo-zookeeper-0
Namespace:      kafka
Priority:       0
Node:           minikube/192.168.49.2
Start Time:     Sat, 19 Feb 2022 12:54:58 +0300
Labels:         app.kubernetes.io/instance=echo
                app.kubernetes.io/managed-by=strimzi-cluster-operator
                app.kubernetes.io/name=zookeeper
                app.kubernetes.io/part-of=strimzi-echo
                controller-revision-hash=echo-zookeeper-5b4b9c686c
                statefulset.kubernetes.io/pod-name=echo-zookeeper-0
                strimzi.io/cluster=echo
                strimzi.io/kind=Kafka
                strimzi.io/name=echo-zookeeper
Annotations:    strimzi.io/cluster-ca-cert-generation: 0
                strimzi.io/generation: 0
                strimzi.io/logging-hash: 300e75146e7c338a6367c3fe2c3598ae3a2d6d05
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/echo-zookeeper
Containers:
  zookeeper:
    Container ID:  
    Image:         quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
    Image ID:      
    Ports:         2888/TCP, 3888/TCP, 2181/TCP, 9404/TCP
    Host Ports:    0/TCP, 0/TCP, 0/TCP, 0/TCP
    Command:
      /opt/kafka/zookeeper_run.sh
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  512m
    Requests:
      cpu:      100m
      memory:   256m
    Liveness:   exec [/opt/kafka/zookeeper_healthcheck.sh] delay=15s timeout=5s period=10s #success=1 #failure=3
    Readiness:  exec [/opt/kafka/zookeeper_healthcheck.sh] delay=15s timeout=5s period=10s #success=1 #failure=3
    Environment:
      ZOOKEEPER_METRICS_ENABLED:         true
      ZOOKEEPER_SNAPSHOT_CHECK_ENABLED:  true
      STRIMZI_KAFKA_GC_LOG_ENABLED:      false
      KAFKA_HEAP_OPTS:                   -Xms512m -Xmx512m
      ZOOKEEPER_CONFIGURATION:           tickTime=2000
                                         initLimit=5
                                         syncLimit=2
                                         autopurge.purgeInterval=1
                                         
    Mounts:
      /opt/kafka/cluster-ca-certs/ from cluster-ca-certs (rw)
      /opt/kafka/custom-config/ from zookeeper-metrics-and-logging (rw)
      /opt/kafka/zookeeper-node-certs/ from zookeeper-nodes (rw)
      /tmp from strimzi-tmp (rw)
      /var/lib/zookeeper from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fz98x (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-echo-zookeeper-0
    ReadOnly:   false
  strimzi-tmp:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  100Mi
  zookeeper-metrics-and-logging:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      echo-zookeeper-config
    Optional:  false
  zookeeper-nodes:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  echo-zookeeper-nodes
    Optional:    false
  cluster-ca-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  echo-cluster-ca-cert
    Optional:    false
  kube-api-access-fz98x:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                   From               Message
  ----     ------       ----                  ----               -------
  Normal   Scheduled    2m32s                 default-scheduler  Successfully assigned kafka/echo-zookeeper-0 to minikube
  Warning  FailedMount  2m31s                 kubelet            MountVolume.SetUp failed for volume "zookeeper-nodes" : write /var/lib/kubelet/pods/6e9e4026-dac7-484f-8fff-347dd753b83e/volumes/kubernetes.io~secret/zookeeper-nodes/..2022_02_19_09_54_59.2088955320/echo-zookeeper-0.crt: no space left on device
  Warning  FailedMount  2m31s                 kubelet            MountVolume.SetUp failed for volume "cluster-ca-certs" : write /var/lib/kubelet/pods/6e9e4026-dac7-484f-8fff-347dd753b83e/volumes/kubernetes.io~secret/cluster-ca-certs/..2022_02_19_09_54_59.3901447062/ca.crt: no space left on device
  Warning  FailedMount  2m31s                 kubelet            MountVolume.SetUp failed for volume "kube-api-access-fz98x" : write /var/lib/kubelet/pods/6e9e4026-dac7-484f-8fff-347dd753b83e/volumes/kubernetes.io~projected/kube-api-access-fz98x/..2022_02_19_09_54_59.3793692036/ca.crt: no space left on device
  Warning  FailedMount  2m31s                 kubelet            MountVolume.SetUp failed for volume "cluster-ca-certs" : write /var/lib/kubelet/pods/6e9e4026-dac7-484f-8fff-347dd753b83e/volumes/kubernetes.io~secret/cluster-ca-certs/..2022_02_19_09_54_59.2253585953/ca.crt: no space left on device
  Warning  FailedMount  2m31s                 kubelet            MountVolume.SetUp failed for volume "zookeeper-nodes" : write /var/lib/kubelet/pods/6e9e4026-dac7-484f-8fff-347dd753b83e/volumes/kubernetes.io~secret/zookeeper-nodes/..2022_02_19_09_54_59.2870250100/echo-zookeeper-0.password: no space left on device
  Warning  FailedMount  2m31s                 kubelet            MountVolume.SetUp failed for volume "kube-api-access-fz98x" : write /var/lib/kubelet/pods/6e9e4026-dac7-484f-8fff-347dd753b83e/volumes/kubernetes.io~projected/kube-api-access-fz98x/..2022_02_19_09_54_59.2182827290/ca.crt: no space left on device
  Warning  FailedMount  2m30s                 kubelet            MountVolume.SetUp failed for volume "cluster-ca-certs" : write /var/lib/kubelet/pods/6e9e4026-dac7-484f-8fff-347dd753b83e/volumes/kubernetes.io~secret/cluster-ca-certs/..2022_02_19_09_55_00.2205277064/ca.p12: no space left on device
  Warning  FailedMount  2m30s                 kubelet            MountVolume.SetUp failed for volume "zookeeper-nodes" : write /var/lib/kubelet/pods/6e9e4026-dac7-484f-8fff-347dd753b83e/volumes/kubernetes.io~secret/zookeeper-nodes/..2022_02_19_09_55_00.596437962/echo-zookeeper-0.key: no space left on device
  Warning  FailedMount  2m30s                 kubelet            MountVolume.SetUp failed for volume "kube-api-access-fz98x" : write /var/lib/kubelet/pods/6e9e4026-dac7-484f-8fff-347dd753b83e/volumes/kubernetes.io~projected/kube-api-access-fz98x/..2022_02_19_09_55_00.4089587653/ca.crt: no space left on device
  Warning  FailedMount  29s (x16 over 2m28s)  kubelet            (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[zookeeper-nodes cluster-ca-certs kube-api-access-fz98x], unattached volumes=[data zookeeper-metrics-and-logging zookeeper-nodes cluster-ca-certs kube-api-access-fz98x strimzi-tmp]: timed out waiting for the condition

```

*Mount pod volumes*

`
minikube ssh -- mount | grep 'var/lib/kubelet/pods
`

```tmpfs on /var/lib/kubelet/pods/a05c587f-6288-435c-b9c3-0389229015c5/volumes/kubernetes.io~projected/kube-api-access-fzv8b type tmpfs (rw,relatime,size=16063252k,inode64)
tmpfs on /var/lib/kubelet/pods/02f095ec-d634-4a1d-bc73-39db3d0800b0/volumes/kubernetes.io~projected/kube-api-access-xxvbh type tmpfs (rw,relatime,size=174080k,inode64)
tmpfs on /var/lib/kubelet/pods/8e7ec8e5-4976-46aa-8937-d1ef97cd4b11/volumes/kubernetes.io~projected/kube-api-access-2zdhw type tmpfs (rw,relatime,size=16063252k,inode64)
tmpfs on /var/lib/kubelet/pods/2a54840f-cc30-4df4-bab1-1b1ed019c796/volumes/kubernetes.io~empty-dir/strimzi-tmp type tmpfs (rw,relatime,size=102400k,inode64)
tmpfs on /var/lib/kubelet/pods/2a54840f-cc30-4df4-bab1-1b1ed019c796/volumes/kubernetes.io~projected/kube-api-access-cllhx type tmpfs (rw,relatime,size=393216k,inode64)
tmpfs on /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~empty-dir/strimzi-tmp type tmpfs (rw,relatime,size=4k,inode64)
```

`
kubectl get pods echo-zookeeper-0 -n kafka -o custom-columns=PodName:.metadata.name,PodUID:.metadata.uid
`

```
PodName            PodUID
echo-zookeeper-0   f5f35747-f45a-471e-a20a-c3d751205468

```
I see this mountpoint for pod echo-zookeeper-0 (f5f35747-f45a-471e-a20a-c3d751205468)

```
tmpfs on /var/lib/kubelet/pods/f5f35747-f45a-471e-a20a-c3d751205468/volumes/kubernetes.io~empty-dir/strimzi-tmp type tmpfs (rw,relatime,size=4k,inode64)
```

I suspect that the issue is **size=4k** in mount options (rw,relatime,size=4k,inode64)

**Additional context**

**Comment by scholzj** [comment]
This sounds like your worker node is out of disk space (or some partition on it)? It is failing to mount secrets and config maps which is done by Kubernetes.

**Reply by trezorg** [reply]
I have enough free disk space on my worker node.
I noticed some interesting thing.
When I used wrong description of resources I experienced that issue with mounting secrets and config maps
```
resources:
      requests:
        memory: 256m
        cpu: 100m
      limits:
        memory: 512m
        cpu: 100m
```
Notice memory: **256m** instead memory: **256Mi**
