### DISCUSSION TITLE
Watch all namespaces by TopicOperator and UserOperator

### DISCUSSION THREAD

**Discussion by stuartm21** [strimzi/strimzi-kafka-operator#6414] [Q&A]
@schmichri We have a kafka cluster and we are planning to create multiple kafka user and topics in multiple namespaces.
So how can we enable the `watchAnyNamespace` for TopicOperator and UserOperator in our kafka cluster? Does the following way it will work?
```
  entityOperator:
    topicOperator:
      watchAnyNamespace: true
    userOperator:
      watchAnyNamespace: true
```
