### DISCUSSION TITLE
Authentication failure while using Ingress based external listener

### DISCUSSION THREAD

**Discussion by opsocomusr** [strimzi/strimzi-kafka-operator#6419] [Q&A]
We are getting SSL Handshake failure while using ingress based external listener. Below is the error and openssl connect output.

Strimzi version: 0.26.0

Log

```
Connection to node -1 (<host>:443) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
```

```
openssl s_client -showcerts -connect <host>:443
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 354 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

The below command returns the proper certificates.

```
openssl s_client -showcerts -connect <host>:443 -servername <host>
```

We tried by setting `ssl.endpoint.identification.algorithm=""` as well as without this config and there was no change in the behaviour. Can you please help with this problem?

**Comment by scholzj** [comment]
I think you would need to share your configuration. The `openssl` stuff is expected - it uses TLS SNI which is what you configure usinf the `servername` option. So that is ok.

**Reply by opsocomusr** [reply]
This is our listener configuration.

```
spec:
  kafka:
    version: 2.8.0
    replicas: 7
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          class: strimzi-nginx
          brokerCertChainAndKey:
            secretName: kafka-bootstrap-certs-secret
            certificate: tls.crt
            key: tls.key
          bootstrap:
            host: kafka-bootstrap.domain.com
          brokers:
          - broker: 0
            host: kafka-broker-0.domain.com
          - broker: 1
            host: kafka-broker-1.domain.com
          - broker: 2
            host: kafka-broker-2.domain.com
          - broker: 3
            host: kafka-broker-3.domain.com
          - broker: 4
            host: kafka-broker-4.domain.com
          - broker: 5
            host: kafka-broker-5.domain.com
          - broker: 6
            host: kafka-broker-6.domain.com
    authorization:
      type: simple
```

**Reply by scholzj** [reply]
So, you have TLS client authentication enabled here. Did you configured it in your client?

**Reply by geniymaxdem** [reply]
I have the same problem
My kafka-cluster configuration
```
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 3Gi
    jvmOptions:
      "-Xmx": "2g"
      "-Xms": "2g"
      javaSystemProperties:
        - name: javax.net.debug
          value: ssl
    version: 3.0.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: internal
        port: 9094
        tls: true
        type: ingress
        configuration:
          class: nginx
          bootstrap:
            host: kafka.service.rowi.tech
          brokers:
          - broker: 0
            host: kafka-0.service.rowi.tech
          - broker: 1
            host: kafka-1.service.rowi.tech
          - broker: 2
            host: kafka-2.service.rowi.tech
        authentication:
          type: oauth
          enableOauthBearer: true
          disableTlsHostnameVerification: true
          validIssuerUri: https://keycloak.service.rowi.tech/auth/realms/kafka-authz
          jwksEndpointUri: https://keycloak.service.rowi.tech/auth/realms/kafka-authz/protocol/openid-connect/certs
          userNameClaim: preferred_username
          maxSecondsWithoutReauthentication: 3600
          tlsTrustedCertificates:
          - secretName: oauth-server-cert
            certificate: ca.crt
	    authorization:
		  type: keycloak
		  clientId: kafka
		  delegateToKafkaAcls: false
		  tokenEndpointUri: https://keycloak.service.rowi.tech/auth/realms/kafka-authz/protocol/openid-connect/token
		  disableTlsHostnameVerification: true
		  tlsTrustedCertificates:
		  - secretName: oauth-server-cert
			certificate: ca.crt
    config:
      # start manual config
      ssl.endpoint.identification.algorithm: ""
      ssl.enabled.protocols: "TLSv1.2"
      ssl.protocol: "TLSv1.2"
      log.retention.hours: 24
      log.segment.bytes: 104857600
      log.retention.bytes: 1073741824
      log.retention.check.interval.ms: 300000
      log.cleaner.enable: true
      log.cleanup.policy: "delete"
      fetch.max.bytes: 52428800
      max.partition.fetch.bytes: 1048576
      replica.fetch.max.bytes: 1000000000.
      max.message.bytes: 1000000000
      # end of manual config
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.0"
```
My client configured to use TLS 

```
cat > /tmp/alice.properties << EOF
security.protocol=SASL_SSL
ssl.truststore.location=/tmp/ca.p12
ssl.truststore.password=$STOREPASS
ssl.truststore.type=PKCS12
sasl.mechanism=OAUTHBEARER
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
  oauth.refresh.token="$REFRESH_TOKEN" \
  oauth.client.id="kafka-cli" \
  oauth.ssl.truststore.location="/tmp/ca.p12" \
  oauth.ssl.truststore.password="$STOREPASS" \
  oauth.ssl.truststore.type="PKCS12" \
  oauth.token.endpoint.uri="https://$SSO_HOST/auth/realms/kafka-authz/protocol/openid-connect/token" ;
sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
EOF
```
As you recomended, ca.p12 recived from kafka-cluster-cluster-ca-cert secrets
But, doesn't work, because when I try to connect from client, I recive the same error
```
[2022-02-24 11:52:23,546] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka.service.rowi.tech/10.46.17.109:443) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue. (org.apache.kafka.clients.NetworkClient)
```

**Comment by geniymaxdem** [comment]
And open_ssl doesn't show any problems in certificates configuration
```
openssl s_client -showcerts -connect kafka.service.rowi.tech:443 -servername kafka.service.rowi.tech

CONNECTED(00000003)
depth=2 C = RU, L = Moscow, O = OSMP, OU = Security department, CN = OSMP Root CA, emailAddress = osb@osmp.ru
verify return:1
depth=1 DC = com, DC = izumfin, CN = izumfin-CA01
verify return:1
depth=0 
verify return:1
---
Certificate chain
 0 s:
   i:/DC=com/DC=izumfin/CN=izumfin-CA01
-----BEGIN CERTIFICATE-----
some text
-----END CERTIFICATE-----
---
Server certificate
subject=
issuer=/DC=com/DC=izumfin/CN=izumfin-CA01
---
No client certificate CA names sent
Peer signing digest: SHA256
Server Temp Key: ECDH, P-256, 256 bits
---
SSL handshake has read 2128 bytes and written 447 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: C594F07B90FA03CE6F7EF56E68AC501A6F2A6415FA1BE58A1E5318FE82C79B60
    Session-ID-ctx: 
    Master-Key: 117C63377CED0943C002398B653A25C2F664C0F085C863CC463033FD99CCC8AB5FAD2A676BD872C6C0986BBFEBA73B60
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 600 (seconds)
    TLS session ticket:
    0000 - e3 29 f9 ce ca cd c6 43-ff 8f ce 84 03 88 f9 a4   .).....C........
    0010 - 99 bb 2b 7a c2 4d de 2f-f1 94 4d 6b 70 24 85 c4   ..+z.M./..Mkp$..
    0020 - 66 f8 4c 16 36 10 75 d6-49 fd 04 f7 1c 60 a9 a1   f.L.6.u.I....`..
    0030 - c1 29 9c 39 11 99 17 0a-4f c0 78 b5 96 3e 21 ba   .).9....O.x..>!.
    0040 - 06 a8 4e 0e db e1 31 88-60 79 cf 2c 98 eb f0 af   ..N...1.`y.,....
    0050 - 69 21 2f 7a 04 72 ad fb-77 6d 9f ed 3c 9a 63 9b   i!/z.r..wm..<.c.
    0060 - b9 77 5f 29 d8 1f c6 b6-79 f0 d9 4e 58 24 76 97   .w_)....y..NX$v.
    0070 - 5e 43 87 01 c9 df 94 2f-b0 b6 37 2c 66 e4 94 7f   ^C...../..7,f...
    0080 - a1 a8 5d f8 43 41 79 1e-80 0a 04 cb 12 e7 65 8c   ..].CAy.......e.
    0090 - e5 17 79 c8 d9 09 eb 66-f1 28 ea 3b 97 eb 95 71   ..y....f.(.;...q
    00a0 - 67 bb e2 f9 b7 39 1e ae-43 57 d8 11 67 d8 7d 93   g....9..CW..g.}.
    00b0 - ea fb b7 a3 20 e6 1e 3f-70 45 28 06 2f 79 da b6   .... ..?pE(./y..
    00c0 - be f3 a3 fb 88 2b 63 1f-1c a0 63 8d 82 71 b8 0e   .....+c...c..q..

    Start Time: 1645684912
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
closed
```

**Reply by scholzj** [reply]
I don't think you have the same problem: you do not have TLS Client authentication enabled. But the certificate returned to your TLS is does for sure not look like a broker certificate. Do you have TLS pasthrough enabled in your Ingress?

**Reply by opsocomusr** [reply]
Yes we have enabled TLS in the client side.

```
security.protocol=SSL
ssl.truststore.location=truststore.p12
ssl.truststore.password=<Password>
ssl.truststore.type=PKCS12
ssl.keystore.location=keystore.p12
ssl.keystore.password=<Password>
ssl.keystore.type=PKCS12
```

We also have these configurations with key.converter.schema.registry.ssl.* and value.converter.schema.registry.ssl.*. We are getting this problem while trying to start a connect cluster running outside of the kubernetes cluster.

**Reply by geniymaxdem** [reply]
My ingress for kafka-cluster have configuration like:
```
Name:             kafka-cluster-kafka-internal-bootstrap
Namespace:        kafka
Address:          10.46.17.109
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  SNI routes kafka.service.rowi.tech
Rules:
  Host                     Path  Backends
  ----                     ----  --------
  kafka.service.rowi.tech  
                           /   kafka-cluster-kafka-internal-bootstrap:9094 (10.233.108.18:9094,10.233.108.245:9094,10.233.108.48:9094)
Annotations:               ingress.kubernetes.io/ssl-passthrough: true
                           nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                           nginx.ingress.kubernetes.io/ssl-passthrough: true
Events:                    <none>
```
and like this
```
kubectl -n kafka get ing kafka-cluster-kafka-internal-bootstrap -o yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  creationTimestamp: "2022-02-24T06:46:22Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: kafka-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: strimzi-kafka-cluster
    strimzi.io/cluster: kafka-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-cluster-kafka
  name: kafka-cluster-kafka-internal-bootstrap
  namespace: kafka
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta2
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: kafka-cluster
    uid: b14a7f15-e428-41bb-8f8d-1578dadb75a9
  resourceVersion: "34749244"
  uid: 2a941515-587b-4249-aa85-ed0831518719
spec:
  ingressClassName: nginx
  rules:
  - host: kafka.service.rowi.tech
    http:
      paths:
      - backend:
          service:
            name: kafka-cluster-kafka-internal-bootstrap
            port:
              number: 9094
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - kafka.service.rowi.tech
status:
  loadBalancer:
    ingress:
    - ip: 10.46.17.109
```
And I don't understand, what do you mean
```
But the certificate returned to your TLS is does for sure not look like a broker certificate
```
Can you explain ?
Thanks

**Reply by scholzj** [reply]
@geniymaxdem If you connect to the broker, the `openssl c_client` should present you the broker TLS certificates. Your command shows some certificates which do not look like the broker certificates. So my guess is that wherever you connected, it is not the Kafka broker. The TLS passthrough - which needs to be enabled in the Kubernetes Nginx Ingress Controller deployment and not in the Ingress - is one of the common issues causing this. But i cannot really tell if this is your case or not.

@Pradeep2103 Then I guess you should see if the connection got to the broker and failed there or if it also didn't reached the broker. You didn't provided the output from the `openssl s_client` command and you use anyway custom listener certificate. So no idea if it works or not for you.

**Reply by opsocomusr** [reply]
We are getting this log on the broker side.

```
2022-02-24 07:59:07,840 INFO [SocketServer listenerType=ZK_BROKER, nodeId=4] Failed authentication with /10.131.1.34 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-4-ListenerName(EXTERNAL-9094)-SSL-11]
```

openssl s_client log

```
openssl s_client -showcerts -connect <host>:443
CONNECTED(00000003)
write:errno=0
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 354 bytes
Verification: OK
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
```

**Reply by scholzj** [reply]
Well, as you said in the first post, you need to use `-servername` I guess. In anycase, the error from the broker suggests that you have not correct TLS configuration in your client and the handshake is failing. Using the `javax.net.debug=ssl` Java system property in your client might help you to debug it.

**Reply by opsocomusr** [reply]
We tried enabling the property `javax.net.debug=ssl` on the client side.

The client is producing ClientHello handshake message but we are not getting ServerHello message back from the server. Immediately after producing the client hello message, the log says `Closing outbound of SSLEngine`.

```
javax.net.ssl|FINE|0C|kafka-admin-client-thread | adminclient-1|2022-02-24 10:38:29.839 PST|SSLEngineOutputRecord.java:505|WRITE: TLS12 handshake, length = 263
javax.net.ssl|FINE|0C|kafka-admin-client-thread | adminclient-1|2022-02-24 10:38:29.839 PST|SSLEngineOutputRecord.java:523|Raw write (
  0000: 16 03 03 01 07 01 00 01   03 03 03 20 5E 1A 40 FC  ........... ^.@.
  0010: 0D 58 18 63 F5 0B 3F 67   E9 EA 21 0C E9 8F B4 77  .X.c..?g..!....w
  0020: FB AE BF 9F 07 C1 44 93   47 33 EC 00 00 32 C0 2C  ......D.G3...2.,
  0030: C0 2B C0 30 C0 2F 00 9F   00 9E C0 24 C0 28 C0 23  .+.0./.....$.(.#
  0040: C0 27 00 6B 00 67 C0 0A   C0 14 C0 09 C0 13 00 39  .'.k.g.........9
  0050: 00 33 00 9D 00 9C 00 3D   00 3C 00 35 00 2F 00 FF  .3.....=.<.5./..
  0060: 01 00 00 A8 00 00 00 31   00 2F 00 00 2C 6B 61 66  .......1./..,kaf
  0070: 6B 61 2D 62 6F 6F 74 73   74 72 61 70 2E 73 74 61  ka-bootstrap.
  0090: 6F 70 74 75 6D 2E 63 6F   6D 00 0A 00 12 00 10 00  domain.com.......
  00A0: 17 00 18 00 19 01 00 01   01 01 02 01 03 01 04 00  ................
  00B0: 0B 00 02 01 00 00 0D 00   22 00 20 04 03 05 03 06  ........". .....
  00C0: 03 08 04 08 05 08 06 08   09 08 0A 08 0B 04 01 05  ................
  00D0: 01 06 01 03 03 03 01 02   03 02 01 00 32 00 22 00  ............2.".
  00E0: 20 04 03 05 03 06 03 08   04 08 05 08 06 08 09 08   ...............
  00F0: 0A 08 0B 04 01 05 01 06   01 03 03 03 01 02 03 02  ................
  0100: 01 00 17 00 00 00 2B 00   03 02 03 03              ......+.....
)
javax.net.ssl|ALL|0C|kafka-admin-client-thread | adminclient-1|2022-02-24 10:38:30.052 PST|SSLEngineImpl.java:659|Closing outbound of SSLEngine
javax.net.ssl|WARNING|0C|kafka-admin-client-thread | adminclient-1|2022-02-24 10:38:30.052 PST|SSLEngineOutputRecord.java:168|outbound has closed, ignore outbound application data
javax.net.ssl|FINE|0C|kafka-admin-client-thread | adminclient-1|2022-02-24 10:38:30.052 PST|SSLEngineOutputRecord.java:505|WRITE: TLS12 alert, length = 2
javax.net.ssl|FINE|0C|kafka-admin-client-thread | adminclient-1|2022-02-24 10:38:30.052 PST|SSLEngineOutputRecord.java:523|Raw write (
  0000: 15 03 03 00 02 01 5A                               ......Z
)
[2022-02-24 10:38:30,052] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka-bootstrap.domain.com/<ip>:443) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue. (org.apache.kafka.clients.NetworkClient)
```

**Reply by scholzj** [reply]
Then you probably didn't connect to the Kafka broker?

**Reply by opsocomusr** [reply]
We see these logs in the broker whenever we try to connect. Does this not mean it is reaching the broker?

```
2022-02-24 07:59:07,840 INFO [SocketServer listenerType=ZK_BROKER, nodeId=4] Failed authentication with /10.131.1.34 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-4-ListenerName(EXTERNAL-9094)-SSL-11]
```

**Reply by scholzj** [reply]
Do the times match? Or is that caused by something else? I don't know, you always share only half of the things, so it is hard to know what the issue might be.

**Reply by opsocomusr** [reply]
Yes, the times match. Sorry, I don't have any other logs from the broker other than this when we start the client.

Just one observation I see now is that if I start the client within our corporate network, with the similar configurations it is able to connect to the brokers without any issues (using external listener). But if we start the client outside of our network with same configurations, we are getting TLS authentication error.

There seems no issue with the listener configuration. But issue happens with different networks.

**Reply by geniymaxdem** [reply]
@scholzj My ingress conrtroller deployed with params 
```
 spec:
      containers:
      - args:
        - -nginx-plus=false
        - -nginx-reload-timeout=60000
        - -enable-app-protect=false
        - -nginx-configmaps=$(POD_NAMESPACE)/ingress-nginx-ingress
        - -default-server-tls-secret=kafka/kafka-secret-tls
        - -ingress-class=nginx
        - -health-status=false
        - -health-status-uri=/nginx-health
        - -nginx-debug=false
        - -v=1
        - -nginx-status=true
        - -nginx-status-port=8080
        - -nginx-status-allow-cidrs=127.0.0.1
        - -report-ingress-status
        - -enable-leader-election=true
        - -leader-election-lock-name=ingress-nginx-ingress-leader-election
        - -wildcard-tls-secret=kafka/kafka-secret-tls
        - -enable-prometheus-metrics=true
        - -prometheus-metrics-listen-port=9113
        - -prometheus-tls-secret=
        - -enable-custom-resources=true
        - -enable-tls-passthrough=true
        - -enable-snippets=false
        - -enable-preview-policies=false
        - -ready-status=true
        - -ready-status-port=8081
        - -enable-latency-metrics=false
```
As you can see, enable-tls-passthrough have a value - true
Can you show, for example, your ingress for external bootstrap ?
And one more question - what kind of trusted store we have to use in client for connect to kafka-broker ? It must be cluster-ca-cert or clients-ca-cert ?

**Reply by scholzj** [reply]
Mine is a bit different:
```
      args:
        - /nginx-ingress-controller
        - '--default-backend-service=$(POD_NAMESPACE)/default-http-backend'
        - '--configmap=$(POD_NAMESPACE)/nginx-configuration'
        - '--tcp-services-configmap=$(POD_NAMESPACE)/tcp-services'
        - '--udp-services-configmap=$(POD_NAMESPACE)/udp-services'
        - '--publish-service=$(POD_NAMESPACE)/ingress-nginx'
        - '--annotations-prefix=nginx.ingress.kubernetes.io'
        - '--enable-ssl-passthrough'
        - '--controller-class=k8s.io/ingress-nginx'
```

But it is the `enable-tls-passthrough` which should matter, yes.

With config like yours - without TLS authentication - the `cluster-ca-cert` is what you should use as your truststore in the clients. Plus you will need to add the OAuth authentication. But the openSSL was not returning the TLS certificate signed by the Cluster CA -> so without that the truststore is of little help.

**Reply by geniymaxdem** [reply]
@scholzj What kind of certs I have to use in brokerCertChainAndKey ?
And one more question
How will work this configuration (as below) ? I mean, what kind of authentication will be used ?
I'm sure - OAuth authentication
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 3Gi
    jvmOptions:
      "-Xmx": "2g"
      "-Xms": "2g"
      javaSystemProperties:
        - name: javax.net.debug
          value: ssl
    version: 3.1.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: internal
        port: 9094
        tls: true
        type: internal
        authentication:
          type: oauth
          enableOauthBearer: true
          disableTlsHostnameVerification: true
          validIssuerUri: https://keycloak.service.rowi.tech/auth/realms/kafka-authz
          jwksEndpointUri: https://keycloak.service.rowi.tech/auth/realms/kafka-authz/protocol/openid-connect/certs
          userNameClaim: preferred_username
          maxSecondsWithoutReauthentication: 3600
          tlsTrustedCertificates:
          - secretName: oauth-server-cert
            certificate: ca.crt
    authorization:
      type: keycloak
      clientId: kafka
      delegateToKafkaAcls: false
      tokenEndpointUri: https://keycloak.service.rowi.tech/auth/realms/kafka-authz/protocol/openid-connect/token
      disableTlsHostnameVerification: true
      tlsTrustedCertificates:
      - secretName: oauth-server-cert
        certificate: ca.crt
```

**Reply by scholzj** [reply]
Sorry, I'm not sure I follow the question. You configured OAuth authentication on the listener on port 9094, so OAuth authentication will be used there. Not authentication will be used on the other two listeners (whcih since you have authorization enabled is more or less a misconfiguration => you cannot have authorization without authentication really).

**Reply by geniymaxdem** [reply]
@scholzj What kind of certs I have to use in brokerCertChainAndKey ?

**Reply by geniymaxdem** [reply]
@scholzj I need your help
I don't understand what I'm doing wrong
Thats my curent configuration for kafka-cluster
```
apiVersion: kafka.strimzi.io/v1beta2kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    resources:
      requests:
        cpu: 200m
        memory: 1Gi
      limits:
        cpu: 500m
        memory: 3Gi
    jvmOptions:
      "-Xmx": "2g"
      "-Xms": "2g"
      javaSystemProperties:
        - name: javax.net.debug
          value: ssl
    version: 3.1.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9095
        tls: true
        type: ingress
        configuration:
          class: nginx
          bootstrap:
            host: kafka.service.rowi.tech
          brokers:
          - broker: 0
            host: kafka-0.service.rowi.tech
          - broker: 1
            host: kafka-1.service.rowi.tech
          - broker: 2
            host: kafka-2.service.rowi.tech
        authentication:
          type: oauth
          enableOauthBearer: true
          disableTlsHostnameVerification: true
          validIssuerUri: https://keycloak.service.rowi.tech/auth/realms/kafka-authz
          jwksEndpointUri: https://keycloak.service.rowi.tech/auth/realms/kafka-authz/protocol/openid-connect/certs
          userNameClaim: preferred_username
          maxSecondsWithoutReauthentication: 3600
          tlsTrustedCertificates:
          - secretName: oauth-server-cert
            certificate: ca.crt
    authorization:
      type: keycloak
      clientId: kafka
      delegateToKafkaAcls: false
      tokenEndpointUri: https://keycloak.service.rowi.tech/auth/realms/kafka-authz/protocol/openid-connect/token
      disableTlsHostnameVerification: true
      tlsTrustedCertificates:
      - secretName: oauth-server-cert
        certificate: ca.crt
```
And this config for client
```
security.protocol=SASL_SSL
ssl.truststore.location=/tmp/ca_cluster.p12
ssl.truststore.password=$STOREPASS
ssl.truststore.type=PKCS12
sasl.mechanism=OAUTHBEARER
sasl.jaas.config=org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
  oauth.refresh.token="$REFRESH_TOKEN" \
  oauth.client.id="kafka-cli" \
  oauth.ssl.truststore.location="/tmp/ca_cluster.p12" \
  oauth.ssl.truststore.password="$STOREPASS" \
  oauth.ssl.truststore.type="PKCS12" \
  oauth.token.endpoint.uri="https://$SSO_HOST/auth/realms/kafka-authz/protocol/openid-connect/token" ;
sasl.login.callback.handler.class=io.strimzi.kafka.oauth.client.JaasClientOauthLoginCallbackHandler
```
When I try to connect to kafka-broker, I revice error
```
[2022-02-28 09:21:23,754] WARN [AdminClient clientId=adminclient-1] Connection to node -1 (kafka.service.rowi.tech/10.46.25.18:443) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue. (org.apache.kafka.clients.NetworkClient)
```
My ingress-controlle setup with -enable-tls-passthrough=true param
Me be I setuped incorrect params for client ?
Help, please
