### DISCUSSION TITLE
Multiple ingress classes (f. ex internal / external nginx)

### DISCUSSION THREAD

**Discussion by mattia-crypto** [strimzi/strimzi-kafka-operator#6456] [Q&A]
**EDIT**
This is now focused on multiple ingress class names.

**OLD Version**

Out of curiosity, is there a working configuration example shown to work for the `Kafka` CRD which uses:

- ExternalDNS
- CertManager
- `listener[].configuration.class: ingress`

Below you will see my listener configurations. However, they give very strange results which I think verifies a few questions I have seen around this repository around `tls` in the `listener` configuration blocks... First and foremost, it confirms that only `nginx` ingress controller works.

**ALB Controller in AWS:**
_Note that I created the `kafka-tls-certs-external` using `cert-manager` CRDs._

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    # image: ""
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          class: alb
          brokerCertChainAndKey:
            secretName: kafka-tls-certs-external
            certificate: tls.crt
            key: tls.key
          bootstrap:
            host: bootstrap.example.dev
            annotations:
              external-dns.alpha.kubernetes.io/hostname: bootstrap.example.dev
              external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
            - broker: 0
              host: kafka-broker-0.example.dev
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-0.example.dev
                external-dns.alpha.kubernetes.io/ttl: "60"
            - broker: 1
              host: kafka-broker-1.example.dev
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-1.example.dev
                external-dns.alpha.kubernetes.io/ttl: "60"
            - broker: 2
              host: kafka-broker-2.example.dev
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-2.example.dev
                external-dns.alpha.kubernetes.io/ttl: "60"
```

You can see that in this case I simply use the `Ingress` capabilities of ALB. However, this does not create any `Ingress` resources in my release namespace. Neither does it create `Service` of type `LoadBalancer`, it simply creates a `Service` of type `ClusterIP` on a per N + 1 brokers (+1 for bootstrap) :

```
NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
kafka-cluster-kafka-0                    ClusterIP   192.168.3.184   <none>        9094/TCP                     64s
kafka-cluster-kafka-1                    ClusterIP   192.168.5.134   <none>        9094/TCP                     64s
kafka-cluster-kafka-2                    ClusterIP   192.168.6.196   <none>        9094/TCP                     64s
kafka-cluster-kafka-bootstrap            ClusterIP   192.168.13.80   <none>        9091/TCP,9092/TCP            64s
kafka-cluster-kafka-brokers              ClusterIP   None            <none>        9090/TCP,9091/TCP,9092/TCP   64s
kafka-cluster-kafka-external-bootstrap   ClusterIP   192.168.0.139   <none>        9094/TCP                     64s
kafka-cluster-zookeeper-client           ClusterIP   192.168.7.138   <none>        2181/TCP                     104s
kafka-cluster-zookeeper-nodes            ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   104s
```

My ALB logs indicate that nothing is happening on the ALB Controller side. Additionally, no brokers are being deployed, and after checking the `strimzi-operator` logs, I see this section, which is crucial:

```
Message: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post "https://ingress-nginx-internal-controller-admission.cluster-system.svc:443/networking/v1/ingresses?timeout=10s": no endpoints available for service "ingress-nginx-internal-controller-admission"
```

It proves that only the `nginx-ingress-controller` can be used. It makes sense that this does not trigger deployment of any brokers accordingly.

Naturally, I would try with the `nginx-ingress-controller`. The change is very simple, as I effectively only need to change the `listener[].configuration.class` parameter.

**NGINX Ingress Controller listener config:**
_Note that I created the `kafka-tls-certs-external` using `cert-manager` CRDs here as well. Regardless, I have deployed an `ingress-nginx controller` which is defined with an `ingressClass` of `nginx-external` and that works perfectly fine._

```
listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          class: nginx-external
          brokerCertChainAndKey:
            secretName: kafka-tls-certs-external
            certificate: tls.crt
            key: tls.key
          bootstrap:
            host: bootstrap.example.dev
            annotations:
              external-dns.alpha.kubernetes.io/hostname: bootstrap.example.dev
              external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
            - broker: 0
              host: kafka-broker-0.example.dev
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-0.example.dev
                external-dns.alpha.kubernetes.io/ttl: "60"
            - broker: 1
              host: kafka-broker-1.example.dev
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-1.example.dev
                external-dns.alpha.kubernetes.io/ttl: "60"
            - broker: 2
              host: kafka-broker-2.example.dev
              annotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-2.example.dev
                external-dns.alpha.kubernetes.io/ttl: "60"
```

This time I got this error in the operator logs:

```
2022-03-02 18:08:34 INFO  Main:151 - Cluster Operator verticle started in namespace kafka without label selector
2022-03-02 18:08:37 INFO  OperatorWatcher:38 - Reconciliation #1(watch) Kafka(kafka/kafka-cluster): Kafka kafka-cluster in namespace kafka was ADDED
2022-03-02 18:08:37 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkas' with unstable version 'v1beta2'
2022-03-02 18:08:37 INFO  AbstractOperator:226 - Reconciliation #1(watch) Kafka(kafka/kafka-cluster): Kafka kafka-cluster will be checked for creation or modification
2022-03-02 18:08:37 INFO  OperatorWatcher:38 - Reconciliation #2(watch) Kafka(kafka/kafka-cluster): Kafka kafka-cluster in namespace kafka was MODIFIED
2022-03-02 18:08:37 INFO  CrdOperator:113 - Reconciliation #1(watch) Kafka(kafka/kafka-cluster): Status of Kafka kafka-cluster in namespace kafka has been updated
2022-03-02 18:08:41 WARN  VersionUsageUtils:60 - The client is using resource type 'strimzipodsets' with unstable version 'v1beta2'
2022-03-02 18:08:42 WARN  VersionUsageUtils:60 - The client is using resource type 'poddisruptionbudgets' with unstable version 'v1beta1'
2022-03-02 18:09:37 INFO  AbstractOperator:373 - Reconciliation #1(watch) Kafka(kafka/kafka-cluster): Reconciliation is in progress
2022-03-02 18:09:41 ERROR AbstractOperator:247 - Reconciliation #1(watch) Kafka(kafka/kafka-cluster): createOrUpdate failed
io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:103) ~[io.fabric8.kubernetes-client-5.12.0.jar:?]
	at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:97) ~[io.fabric8.kubernetes-client-5.12.0.jar:?]
	at io.fabric8.kubernetes.client.dsl.base.CreateOnlyResourceOperation.create(CreateOnlyResourceOperation.java:63) ~[io.fabric8.kubernetes-client-5.12.0.jar:?]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.internalCreate(AbstractResourceOperator.java:275) ~[io.strimzi.operator-common-0.28.0.jar:0.28.0]
	at io.strimzi.operator.common.operator.resource.AbstractResourceOperator.lambda$reconcile$0(AbstractResourceOperator.java:113) ~[io.strimzi.operator-common-0.28.0.jar:0.28.0]
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.71.Final.jar:4.1.71.Final]
```

Also:
```
kafka-cluster-kafka-0                    ClusterIP   192.168.2.73     <none>        9094/TCP                     96s
kafka-cluster-kafka-1                    ClusterIP   192.168.11.178   <none>        9094/TCP                     96s
kafka-cluster-kafka-2                    ClusterIP   192.168.13.237   <none>        9094/TCP                     96s
kafka-cluster-kafka-bootstrap            ClusterIP   192.168.11.235   <none>        9091/TCP,9092/TCP            96s
kafka-cluster-kafka-brokers              ClusterIP   None             <none>        9090/TCP,9091/TCP,9092/TCP   96s
kafka-cluster-kafka-external-bootstrap   ClusterIP   192.168.6.197    <none>        9094/TCP                     96s
kafka-cluster-zookeeper-client           ClusterIP   192.168.3.117    <none>        2181/TCP                     2m25s
kafka-cluster-zookeeper-nodes            ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   2m25s
```

However, no ingress resources were made... I am really not sure what could be going wrong here.

**Comment by scholzj** [comment]
You can check this blog post - https://strimzi.io/blog/2021/05/07/deploying-kafka-with-lets-encrypt-certificates/ - which is very similar. The main difference is that Strimzi is designed, developed and tested with Kubernetes Nginx Controller. Not sure if your ALB controller will work. I assume ALB is Application Loadb Balancer? Does it support TLS passthrough on which Strimzi depends?

In any case, if it didn't created the Ingress resources, it probably failed before that. I don't think I ever saw an exception like this which is without any proper reason. Maybe if you change the log level to DEBUG, it would show at least what were the last things it was doing.

**Reply by mattia-crypto** [reply]
Indeed it is very strange which is why I wanted to bring it up in this discussion

**Reply by mattia-crypto** [reply]
And yes almost :-) it is the AWS Load Balancer Controller.

**Reply by mattia-crypto** [reply]
Will add some more logs in here

**Comment by mattia-crypto** [comment]
It does seem that Strimzi gets confused if there are multiple `ValidatingWebhookConfigurations` for the `ingress-nginx-controller`. Some people use multiple `ingress-nginx-controller`s for example, when you need an internal and external ingress class.

I managed to get the external configuration working by deleting the `internal` `ValidatingWebhookConfiguration`. I shouldn't really need to do this IMO if the internal ingress controller is not deployed, which it wasn't.

**Reply by scholzj** [reply]
Strimzi just creates the Ingress resources. It does not know if there are any webhooks validating it or not. That is up to Kubernetes. If this is due to the `ValidatingWebhookConfigurations`, what is it it doesn't like? I mean it validates the Ingress resource and rejects it which causes the mysterious exception without any reason I guess -> fine, that makes sense. But what in particular it doesn't like about the Ingress?

**Reply by mattia-crypto** [reply]
It appears that there is no logic for managing the case where there are multiple `ValidatingWebhookConfigurations`. That is the sole issue. Say you have:
- `ingress-controller-external-admission-webhook-configuration`
- `ingress-controller-internal-admission-webhook-configuration`

but you only have the `internal-nginx-controller` running in your cluster. In that case, the Operator will randomly choose one of the two `ValidatingWebhookConfiguration` it appears. Similarly, even if you had the `external-nginx-controller`, you would not have any guarantees as to which `ValidatingWebhookConfiguration` is used. 

In fact, this would also explain why having two different listeners configured with type `ingress`, one using `external` controller, and the other using `internal` controller, cause some issues for the `Kafka` resource's listener configuration. Concretely, this can cause scenarios were listeners that are meant to use the `ingress-class: external-nginx` might end up relying upon the `internal-nginx` ingress resource.

I think it would be good if the operator could at least:
- be aware of which `ingress-class` exists, which it already is
- based upon which `ingress-class` is specified in the `listener`, get the `ValidatingWebhookConfiguration` for that particular `ingress-class` for a particular listener, and
- finally create the appropriate `Ingress` with the correct `ValidatingWebhookConfiguration` associated with it.

Otherwise, it seems the brokers' listeners will not get the correct `ingress-class` associated to them.

**Reply by scholzj** [reply]
But this is not what the operator does. Strimzi does not interact in any way with the webhooks. It cannot manage the webhooks in any way.

The webhooks are registered in Kubernetes and during the registration they specify what kind of resources they should be called for. And when any application calls the Kubernetes API to create the resource - such as Ingress resource in this case - Kubernetes automatically pass it through the chain of registered validation webhooks. And if any of them rejects it, we will just get some error that the Ingress creation failed.

So yes, if you have two webhooks installed and one validates that field `x` has to be set to value `1` and the second validates that field `x` needs ot be set to value `2`, no Ingress will get created. But Strimzi cannot choose the webhooks -> that is what Kubernetes does on its own. The adminssion controllers are often used for implementing security controlls, so an application such as Strimzi cannot just choose which one will be applied.

So the logic you describe cannot be done in Strimzi. It is either and error that someone installed webhooks which validate the same resource and contradict each other as in my example above. Or it is an issue in the logic inside the webhook that it cannot properly distinguish which Ingress should be rejected and which not.

**Reply by mattia-crypto** [reply]
> So the logic you describe cannot be done in Strimzi. It is either and error that someone installed webhooks which validate the same resource and contradict each other as in my example above. 

In this case, the `Kafka` resource is a single resource given that is a CRD. This is effectively why I raised this discussion. Is there no way to use multiple ingress classes in Strimzi for the listener? Perhaps there is an example already.

Or perhaps you have an example of how you would configure the `nginx-ingress-controller` so that the `admissionWebhook` works for the different listeners in the same `Kafka` resource? 

More precisely put, how can I customise the `admissionWebhook` to target different listener configurations in the `Kafka` resource? In this case it seems the only option is to disable the `admissionWebhook`:

```
admissionWebhook:
    enabled: true
    namespaceSelector: {}
    objectSelector: {}
    labels: {}
    ...
```
Can I for example, add labels to a particular listener?
