### DISCUSSION TITLE
KafkaConnect and KafkaConnector configs as config map?

### DISCUSSION THREAD

**Discussion by cstmgl** [strimzi/strimzi-kafka-operator#6461] [Q&A] [answered]
Hi all, 
I'm reading the documentation for example for the KafkaConnector:

Reference the ConfigMap in the connector configuration.

```
Example connector configuration referencing the ConfigMap
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-connector
  labels:
    strimzi.io/cluster: my-connect
spec:
  # ...
  config:
    option: ${configmaps:my-project/my-connector-configuration:option1}
    # ...
# ...
Placeholders for the property values in the ConfigMap are referenced in the connector configuration. The placeholder structure is configmaps:PATH-AND-FILE-NAME:PROPERTY. KubernetesConfigMapConfigProvider reads and extracts the option1 property value from the external ConfigMap.
```

I have a question, because this would make my life so much easier, why can't I define the full config block as a config map?
Would this not make sense? Or maybe it's already possible and just lack of know-how on my part?
Considering my configs change quite a lot I really would like to define them as a config map but I don't see the point of having to define them all the options one by one so I was wondering how other people are doing it.

For example even the connect configs probably I would like to define in a config map
https://strimzi.io/docs/operators/0.24.0/using.html#property-kafka-connect-config-reference

Thanks for any feedback

**Comment by scholzj** [comment, marked as answer]
What would be the usecase to have them in ConfigMap? They are already created declaratively as a KafkaConnector resource. Loading some fields and values from Secret or ConfigMap is useful for some individual option which either should be treated as a Secret or which exist for example in some other configuration. But loading everything from config map makes no sense to me -> we have the custom resource for it.

**Reply by cstmgl** [reply]
Basically I wanted to be able to have a custom resource that is more a template than anything and just have the configuration change base on the config map.
But the name of the options and structure is much different between connector to connector and that's why I would rather do it in a config map

**Reply by scholzj** [reply]
But what makes the difference between this YAML:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-connector
  labels:
    strimzi.io/cluster: my-connect
spec:
  # ...
  config:
    option1: value1
    option2: value2
    option3: value3
    # ...
```

and this YAML:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-connector-config
data:
  option1: value1
  option2: value2
  option3: value3
  # ...
```

That is the part I don't understand. You still need to write the options into a YAML.
