### DISCUSSION TITLE
KafkaConnector error: 500 Internal Server Error

### DISCUSSION THREAD

**Discussion by urcaly00** [strimzi/strimzi-kafka-operator#6501] [General]
Hello, 
We recently started looking at strimzi and are running into errors with the KafkaConnector. 
Any suggestions to help  troubleshoot or resolve them  are welcome. Below is one example.

Thank you,
Lavaughn

strimzi 0.24
kafka 2.8.0
io.debezium.connector.mysql.MySqlConnector
Shared cluster and space does not appear to be an issue

ERROR
'GET /connectors/xyz-connector/config returned 500 (Internal Server Error): Request timed out'
    reason: ConnectRestException

**KafkaConnect**

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.8.0
  image: image1
  replicas: 1
  bootstrapServers: lab:9092
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    group.id: group1
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  externalConfiguration:
    env:
      - name: DKR_PROXY
        valueFrom:
          secretKeyRef:
            name: dkrproxy
            key: dkr_proxy
      - name: HTTP_PROXY
        valueFrom:
          secretKeyRef:
            name: httpproxy
            key: http_proxy
      - name: HTTPS_PROXY
        valueFrom:
          secretKeyRef:
            name: httpsproxy
            key: https_proxy
      - name: NO_PROXY
        valueFrom:
          secretKeyRef:
            name: noproxy
            key: no_proxy
  template:
    pod:
      imagePullSecrets:
        - name: lab-registry
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
      log4j.rootLogger: "INFO"
```

**KafkaConnectorYAML**
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: xyz-connector
  labels:
    strimzi.io/cluster: cluster1
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1  
  config:
    database.history.kafka.bootstrap.servers: lab:9092
    database.history.kafka.topic: sql-topic
    database.hostname: 1.1.1.1
    database.include.list: dbname
    database.user: xyzname
    database.password: xyz
    database.port: 3000
    database.server.id: 1333
    database.server.name: dbznm
    include.schema.changes: true
    table.include.list: table1
    topic.creation.enable: true
```

One interesting and unrelated note: With multiple connect clusters there was extensive log info available from the service connect api. With only one connect cluster no log files were generated until I bumped the logging level to DEBUG in the KafkaConnect

**Comment by scholzj** [comment]
As mentioned before - you should double check if there is no other Connect cluster using the same internal topics and group: https://strimzi.io/docs/operators/0.24.0/full/deploying.html#con-kafka-connect-multiple-instances-str.

I would also make sure to set resources for your Connect cluster. When I use Connect, I normally give it 0.5-1 CPU and 1-2 Gi of memory. But I'm not sure how much Debezium really needs. It might need more.

Maybe you can also try to use some simpler connectors to see what the problem relates to - e.g. https://github.com/strimzi/strimzi-kafka-operator/blob/0.24.0/examples/connect/source-connector.yaml or I use this for testing: https://github.com/scholzj/echo-sink

**Comment by urcaly00** [comment]
Hi Jakub, Thanks for your response. I have only one connect cluster now but the problem persists. I will try to increase the resources specifically for the connector. We have tried the Sink and Source Filestream connectors and they work fine. 
Thank you,
Lavaughn

**Reply by scholzj** [reply]
The connector does not have its resources. They are always on the Connect level. So you have to set them in the `KafkaConnect` custom resource. If the small connectors work and Debezium doesn't, it should be worth trying since Debezium is definitely _heavier_ connector (it also does a lot of stuff compared to them so it is expected). If it doesn't help, you should probably share the full log form Connect.

**Comment by urcaly00** [comment]
Thanks Jakub, I have some new errors. How can I use the validate function of the connect-api?

So far:
I added resources at the Connect level.
```yaml
  resources:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 1Gi
```

Current error:
Log Error
ERROR Failed testing connection for jdbc:mysql://servername:port?useInformationSchema=true&nullCatalogMeansCurrent=false&useSSL=false&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&connectTimeout=30000 with user 'username' (io.debezium.connector.mysql.MySqlConnector) [DistributedHerder-connect-1]

Connector error
 message: |-
      PUT /connectors/dbz-connector/config returned 400 (Bad Request): Connector configuration is invalid and contains the following 1 error(s):
      Unable to connect: Communications link failure

      The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
      You can also find the above list of errors at the endpoint `/{connectorType}/config/validate`
    reason: ConnectRestException
    status: "True"
    type: NotReady

From the kubernetes shell (Connect API) 
>slookup   sqlservername:port   is successful
>curl connect-api:8083/connectors
  returns an empty []  (can't find the dbz-connector
Also, username and password is correct.

FYI: If I try a JDBC connector, it does show up if I run curl connect-api:8083/connectors from the kubernetes shell
