### DISCUSSION TITLE
Zookeeper anti-affinity is missing

### DISCUSSION THREAD

**Discussion by tgruenert** [strimzi/strimzi-kafka-operator#6506] [Q&A] [answered]
**Describe the bug**
After a fresh install from example (3 instances) zookeeper run 3 times on the same node. 

**To Reproduce**
1. install operator `helm upgrade -i -f manual/blueprint/strimzi/operator-values.yaml strimzi strimzi/strimzi-kafka-operator`
2. Create Custom Resource from [examples](https://github.com/strimzi/strimzi-kafka-operator/tree/main/examples)/[kafka](https://github.com/strimzi/strimzi-kafka-operator/tree/main/examples/kafka)/kafka-persistent.yaml , do some enhancements for connection via ingress
4. Run command `kubectl apply -f kafka-persistent.yaml`
5. See error

![image](https://user-images.githubusercontent.com/6465773/157751404-ac7ee2a3-9a05-4791-bedb-73966a9687ae.png)

**Expected behavior**
zookeeper should install on every node one time

**Environment (please complete the following information):**
 - Strimzi version: 0.28.0 
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.20
 - Infrastructure: Rancher on bare metal

kafka.yaml
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    listeners:
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            host: kafka.example.org
          brokers:
          - broker: 0
            host: broker-0.kafka.example.org
          - broker: 1
            host: broker-1.kafka.example.org
          - broker: 2
            host: broker-2.kafka.example.org
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.1"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 8Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 8Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}


```
