### DISCUSSION TITLE
Strimzi Mirrormaker2 and Event Hub Odd Error, Can't Pinpoint

### DISCUSSION THREAD

**Discussion by walkinverse** [strimzi/strimzi-kafka-operator#6526] [Q&A] [answered]
I am trying to sync Kafka to Azure Event Hub, one way.  I followed every tutorial I could find to no avail.  Nothing seems to work as I keep getting obscure errors.  Below is the config used for deployment.  We even used the RootManageSharedAccessKey to make sure nothing blocks.  I have Kafka, KafkaConnect deployed without issue.  

MirrorMaker2 works between Kafka and Kafka, but no dice when I try to sync with EventHub.

To test if port 9093 was accessible, I successfully used telnet to access it.

I have tried the below config with the authentication block, and then with sasl under the config section.  Comments below.

## MM2 Config

```yaml
cat <<EOF | kubectl apply -n kafka-cloud -f -
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mirror-maker-eventhub
spec:
  version: 3.1.0
  replicas: 1
  connectCluster: "eventhub"
  clusters:
  - alias: "my-kafka-cluster"
    bootstrapServers: my-kafka-cluster-kafka-bootstrap:9092
  - alias: "eventhub"
    bootstrapServers: XXXXXXXXXXXXXXXXXXXX.servicebus.windows.net:9093
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
      producer.connections.max.idle.ms: 180000
      producer.metadata.max.age.ms: 180000
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://XXXXXXXXXXXXXXXXXXXX.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XXXXXXXXXXXXXXXXXXXX";
    tls:
      trustedCertificates: []
  mirrors:
  - sourceCluster: "my-kafka-cluster"
    targetCluster: "eventhub"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: ".*"
    groupsPattern: ".*"
EOF
```

First issue were these warnings.  I know it's only INFO, but the deployment keep crashing and will not stay running. I also know with Kafka these type of logs are vague at best. 

```shell
2022-03-15 21:21:06,151 INFO [AdminClient clientId=adminclient-1] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient) [kafka-admin-client-thread | adminclient-1]

2022-03-15 21:21:06,152 INFO [AdminClient clientId=adminclient-1] Cancelled in-flight METADATA request with correlation id 59 due to node -1 being disconnected (elapsed time since creation: 87ms, elapsed time since send: 87ms, request timeout: 16401ms) (org.apache.kafka.clients.NetworkClient) [kafka-admin-client-thread | adminclient-1]
```

Then I was able to catch this error in the logs. I can't tell where the problem lies and can't figure out how to resolve it.  

```shell
2022-03-15 21:22:55,572 INFO [AdminClient clientId=adminclient-1] Metadata update failed (org.apache.kafka.clients.admin.internals.AdminMetadataManager) [kafka-admin-client-thread | adminclient-1]
org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-03-15 21:22:55,574 INFO App info kafka.admin.client for adminclient-1 unregistered (org.apache.kafka.common.utils.AppInfoParser) [kafka-admin-client-thread | adminclient-1]
2022-03-15 21:22:55,575 INFO [AdminClient clientId=adminclient-1] Metadata update failed (org.apache.kafka.clients.admin.internals.AdminMetadataManager) [kafka-admin-client-thread | adminclient-1]
org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata
2022-03-15 21:22:55,575 INFO [AdminClient clientId=adminclient-1] Timed out 1 remaining operation(s) during close. (org.apache.kafka.clients.admin.KafkaAdminClient) [kafka-admin-client-thread | adminclient-1]
2022-03-15 21:22:55,582 INFO Metrics scheduler closed (org.apache.kafka.common.metrics.Metrics) [kafka-admin-client-thread | adminclient-1]
2022-03-15 21:22:55,582 INFO Closing reporter org.apache.kafka.common.metrics.JmxReporter (org.apache.kafka.common.metrics.Metrics) [kafka-admin-client-thread | adminclient-1]
2022-03-15 21:22:55,582 INFO Metrics reporters closed (org.apache.kafka.common.metrics.Metrics) [kafka-admin-client-thread | adminclient-1]
2022-03-15 21:22:55,583 ERROR Stopping due to error (org.apache.kafka.connect.cli.ConnectDistributed) [main]
org.apache.kafka.connect.errors.ConnectException: Failed to connect to and describe Kafka cluster. Check workers broker connection and security properties.
at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:70)
at org.apache.kafka.connect.util.ConnectUtils.lookupKafkaClusterId(ConnectUtils.java:51)
at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:97)
at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:80)
Caused by: java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment. Call: listNodes
```

When I run a describe I get this error

```shell
Status:
  Conditions:
    Last Transition Time:  2022-03-15T21:25:49.149589Z
    Message:               Exceeded timeout of 300000ms while waiting for Deployment resource mirror-maker-eventhub-mirrormaker2 in namespace kafka-cloud to be ready
    Reason:                TimeoutException
    Status:                True
    Type:                  NotReady
  Label Selector:          strimzi.io/cluster=mirror-maker-eventhub,strimzi.io/name=mirror-maker-eventhub-mirrormaker2,strimzi.io/kind=KafkaMirrorMaker2
  Observed Generation:     1
  Replicas:                1
  URL:                     http://mirror-maker-eventhub-mirrormaker2-api.kafka-cloud.svc:8083
Events:                    <none>
```

When I add the authentication block in mm2:

```yaml
    authentication: 
      type: plain 
      username: $ConnectionString
      passwordSecret: 
        secretName: eventhubssecret 
        password: eventhubspassword
```

I get this error, even though the secret exists and is validated.

```shell
Status:
  Conditions:
    Last Transition Time:  2022-03-15T23:30:31.200105Z
    Message:               PLAIN authentication selected, but username or password configuration is missing.
    Reason:                InvalidResourceException
    Status:                True
    Type:                  NotReady
  Observed Generation:     2
  Replicas:                0
Events:                    <none>
```

If anyone has any idea, it'd be greatly appreciated.  Spent the entire day to no avail.  I removed using secretes as it caused an error that the name and password were not supplied.  It's weird.

Thank you.

**Comment by scholzj** [comment]
How does this differ from https://stackoverflow.com/questions/71489737/strimzi-mirrormaker2-and-event-hub-odd-error-cant-pinpoint/71489915?

**Reply by walkinverse** [reply]
I asked there to see if I could get an answer.  And didn't.  I tried both ways.  The authentication block and ssal.   Mirrormaker2 works fine without issue from Kafka to Kafka.  It fails when trying to go from Kafka to Azure.  Is there some kind of setting in Azure that needs changed?  I am able to telnet the port 9093 from the outside on Azure.  But for whatever reason it cant authentication.  But again. If I spin up two Kafka clusters and use MirrorMaker2 to talk there are no issues.  What am I missing?  Kafaka and Azure are in different namepaces in Azure. The Kafka to Kafka test they were in the same.

**Reply by scholzj** [reply]
1) I did answered there
2) You didn't really wait for any answers.

Spamming many places with the same questions just leads to wasted effort from people who try to help you as well as for other people looking for the same answer.

**Reply by walkinverse** [reply]
I wasn't aware these two sites were connected. I apologize.  I will delete the one from there then and only keep this one.  I even had other colleagues look at the issue and what we have in the ymal matches exactly to the examples on strimzi.  Is there any setting in Azure we could be missing?    We spin up two instances of Kafka and used mirror maker 2 via strimzi to communicate without issue.  With Azure as cannot get it to work and are roadblocked.  Any advice you could offer would be greatly appreciated.  

I had another individual also look at the same links previously and we did follow them to the letter.  We are using PLAIN authentication.  Create the secret just as the examples and setup the mirrormaker2 file just as they example.  We put our connection but it will not connect.  We have all network available.  We can telnet to the Event Hub URL and Port without issue.  We are at a loss as to what the issue it.

On a side note when using

```
    authentication: 
      type: plain 
      username: $ConnectionString
      passwordSecret: 
        secretName: eventhubssecret 
        password: eventhubspassword
```

It produces an odd error stating the username was not provided.  Yet the secret exists.

```
cat <<EOF | kubectl apply -n kafka-cloud -f - 
apiVersion: v1
kind: Secret
metadata:
  name: eventhubssecret
type: Opaque
stringData:
  eventhubspassword: Endpoint=sb://<namespace>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxxxxx
EOF
```

I am at a loss as this point.  We are also using the most current operator of strimzi 0.28.  All the examples online show earlier version.  Could there be a bug?

**Reply by scholzj** [reply]
They are not connected but that does not matter.

As I told you before, the configuration you shared at the start is wrong. You need to follow the docs and the blog post to configure the PLAIN authentication. I do not know if Azure needs any special configuration. That is a question on Azure support I guess.

**Reply by walkinverse** [reply]
Unfortunately I wasn't clear.  We did try the PLAIN authentication as the document stated and then tried the other approach. Now we are back to your advice as stated in the document and still the same issue.  Any idea?

Followed to no avail => https://strimzi.io/blog/2020/06/09/mirror-maker-2-eventhub/

```
cat <<EOF | kubectl apply -n kafka-cloud -f -
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: test-mirror-maker-eventhub
spec:
  version: 3.1.0
  replicas: 1
  connectCluster: "eventhub"
  clusters:
  - alias: "kafka-cluster"
    bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  - alias: "eventhub"
    bootstrapServers: <namespace>.servicebus.windows.net:9093
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
      producer.connections.max.idle.ms: 180000
      producer.metadata.max.age.ms: 180000
    authentication: 
      type: plain 
      username: $ConnectionString
      passwordSecret: 
        secretName: eventhubssecret 
        password: eventhubspassword
    tls:
      trustedCertificates: []
  mirrors:
  - sourceCluster: "kafka-cluster"
    targetCluster: "eventhub"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: ".*"
    groupsPattern: ".*"
EOF
```

**Reply by scholzj** [reply]
1) Be careful that `$ConnectionString` is not replaced when creating the resource like this.
2) So what is actually your issue now?

**Reply by walkinverse** [reply]
It seems it can't read the secret.  With point 1 we have it as verbatim ```$ConnectionString```

But we keep getting this:

```
Status:
  Conditions:
    Last Transition Time:  2022-03-16T19:46:26.003481Z
    Message:               PLAIN authentication selected, but username or password configuration is missing.
    Reason:                InvalidResourceException
    Status:                True
    Type:                  NotReady
  Observed Generation:     6
  Replicas:                0
Events:                    <none>
```

**Reply by scholzj** [reply]
Well, you need to figure out why it cannot read the secret. Either you badly created it or you have some setup issue. But the guide in the blog post works.

**Reply by walkinverse** [reply]
I cut and pasted from the blog directly and made the changes to my eventhub passwords.  Could it be a strimzi operator issue with mirrormaker or a bug?  We followed the guide to the letter.  Any ideas?

This is the command used to create the secret.  I don't see anything wrong with it, do you? Am I missing something in the way I am creating it? Also we noticed in the blog its using v1alpha1. we are on version 0.28 and beta2 for the api verison.

```
cat <<EOF | kubectl apply -n kafka-cloud -f - 
apiVersion: v1
kind: Secret
metadata:
  name: eventhubssecret
type: Opaque
stringData:
  eventhubspassword: Endpoint=sb://<namespace>.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=xxxxxxxxxx
EOF 
```
