### DISCUSSION TITLE
auto.create.topics.enable: "false" ignored

### DISCUSSION THREAD

**Discussion by Cave-Johnson** [strimzi/strimzi-kafka-operator#6634] [Q&A]
I'm testing strimzi with a basic app that uses faust-streaming. Faust likes to auto create topics if they do not exist which I currently want to disable.
In my kafka deployment yaml I am setting `auto.create.topics.enable: "false"` under the config section however this is being ignored and faust is still auto creating the topics

Full kafka-deployment.yaml

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-test
spec:
  kafka:
    version: 3.1.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.1"
      auto.create.topics.enable: "false"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  entityOperator:
    template:
      topicOperatorContainer:
        env:
          - name: STRIMZI_USE_ZOOKEEPER_TOPIC_STORE
            value: "true"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

In addition, if i create a topic through a yaml file as outlined in the quick start guide, this applies and I can see it within rancher. However none of my faust producers and consumers can see or use this topic. What am i missing here?

The error i get is `
[2022-04-05 23:15:47,104] [1] [ERROR] Topic test-topic not found in cluster metadata`

**Comment by scholzj** [comment]
> In my kafka deployment yaml I am setting auto.create.topics.enable: "false" under the config section however this is being ignored and faust is still auto creating the topics

How do you know the topic was _auto-created_ and not intentionally created by your application?

> In addition, if i create a topic through a yaml file as outlined in the quick start guide, this applies and I can see it within rancher. However none of my faust producers and consumers can see or use this topic. What am i missing here?
>
> The error i get is [2022-04-05 23:15:47,104] [1] [ERROR] Topic test-topic not found in cluster metadata

It is not clear where do you get the error. You also didn't shared any logs or full custom resources (including the `.status` section), so it is hard to say whather they were seen, whether there is some error etc.

**Comment by Cave-Johnson** [comment]
> How do you know the topic was auto-created and not intentionally created by your application?

I believe this is the case because its a random ID added after the topic name such as `---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a`, I was under the impression that setting `auto.create.topics.enable: "false"` would stop the application from being able to create any topics, is this not the case? I would rather define all my topics through yaml so I have control over what topics exist.

> It is not clear where do you get the error. You also didn't shared any logs or full custom resources (including the .status section), so it is hard to say whather they were seen, whether there is some error etc.

Apologies, this error is from the application. Were do i find the output from `.status`?

Full custom resource is 

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: test-topic
  namespace: my-kafka-cluster
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 3
  replicas: 3
  config:
    retention.ms: 720000000
    segment.bytes: 1073741824
```
