### DISCUSSION TITLE
Using standalone topic/user operator with Redpanda (without zoopkeeper)

### DISCUSSION THREAD

**Discussion by ee07dazn** [strimzi/strimzi-kafka-operator#6659] [Q&A] [answered]
Hello 

I have an up/running Kafka cluster provided by [redpanda](https://redpanda.com/)  - obviously this does not include any zookeeper etc..
I have been able to setup kafka connect using StrimziOperator and talk to redpanda cluster. I am trying to see if I can use the Topic (&User) Operator to mange topics/users here. 
Following the [docs](https://strimzi.io/docs/operators/latest/deploying.html#deploying-the-topic-operator-standalone-str), I have updated the deployment yaml file and provided the relevant creds/env variables. 

I first tried by commenting out the `STRIMZI_ZOOKEEPER_CONNECT` variable but that threw an error suggesting this needs to be set. So it just set as blank..While the error is gone, unfortunately, the topic operator is crashing but i can't seem to see any errors in the message that can help me to debug the issue. 

I have attached the logs here..please let me know if there is anything else i can provide here to help me out or confirm one way or another whether - this will be incompatible with redpanda ?

Thanks

![Screenshot 2022-04-08 at 23 49 13](https://user-images.githubusercontent.com/46483973/162543704-c4554a56-d6fb-4956-aeab-bd8083acb8c1.png)

For reference, here is my version of deployment-strimzi-topic-operator.yaml

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-topic-operator
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-topic-operator
  template:
    metadata:
      labels:
        name: strimzi-topic-operator
    spec:
      serviceAccountName: strimzi-topic-operator
      containers:
        - name: strimzi-topic-operator
          image: quay.io/strimzi/operator:0.28.0
          args:
          - /opt/strimzi/bin/topic_operator_run.sh
          env:
            - name: STRIMZI_RESOURCE_LABELS
              value: "strimzi.io/cluster=redpanda-cluster"
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: "0.mycluster:30025,1.mycluster:30025,2..mycluster:30025"
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: ""
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "18000"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS
              value: "6"
            - name: STRIMZI_LOG_LEVEL
              value: DEBUG
            - name: STRIMZI_TLS_ENABLED
              value: "true"
            - name: STRIMZI_PUBLIC_CA
              value: "true"
            - name: STRIMZI_TLS_AUTH_ENABLED
              value: "false"
            - name: STRIMZI_SASL_ENABLED
              value: "true"
            - name: STRIMZI_SASL_USERNAME
              value: "my-service-account"
            - name: STRIMZI_SASL_PASSWORD
              value: "123"
            - name: STRIMZI_SASL_MECHANISM
              value: "scram-sha-256"
            - name: STRIMZI_SECURITY_PROTOCOL
              value: "SASL_SSL"
            - name: STRIMZI_TRUSTSTORE_LOCATION
              value: "/tmp/secret/clientTrustStore.p12"
            - name: STRIMZI_TRUSTSTORE_PASSWORD
              value: "mypass"
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: truststore-path
              mountPath: /tmp/secret
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 96Mi
              cpu: 100m
            requests:
              memory: 96Mi
              cpu: 100m
      volumes:
        - name: truststore-path
          secret:
            secretName: my-trust-store
  strategy:
    type: Recreate
```
