### DISCUSSION TITLE
old data in the PVC has been restored

### DISCUSSION THREAD

**Discussion by hari819** [strimzi/strimzi-kafka-operator#6675] [Q&A]
@scholzj 

we are running 3 brokers with 3 zookeeper , using the 0.27 version of the operator ,

this is the volume section of the Kafka broker in the cluster yaml ,

```
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          class: SSD
          size: 500Gi
          deleteClaim: false
        - id: 1
          type: persistent-claim
          class: SSD
          size: 500Gi
          deleteClaim: false
```

last week when the data was almost full , 400GB , i stopped the cluster operator first , scaled down ZK , Kafka .

Later I deleted all the PVCs for Kafka and Zookeeper to start the cluster as a fresh one ,  it was all good and data started accumulating when we started using the fresh kafka cluster, but today I noticed that all the old data which got deleted when i deleted the PVC got restored again , and the PVC is almost full again ,

is this expected with my setting of deleteClaim as "false" , please could you help me on this ?
