### DISCUSSION TITLE
Extend session.timeout and heartbeat.interval

### DISCUSSION THREAD

**Discussion by BryanDollery** [strimzi/strimzi-kafka-operator#6724] [Q&A]
Can anyone help explain to me exactly how to extend the heartbeat interval and session timeout using strimzi? I've checked though various docs that mention setting these values, but I can't find out where exactly to place them in my strimzi configuration. Right now I have a k8s.yaml, and I suspect the values should go in there, but I've tried that and it broke my cluster. 

I'm using the kafkajs client in nodejs and I'm finding problems with heartbeats not being sent and my consumers being ejected. I thought that increasing the timeouts might help. I'm not completely clear on the interplay of session.timeout and heartbeat.interval, so I thought I might set them both really high to see if it helps. I've tried this on the client and immediately ran into the problem of exceeding the maximum set on the cluster/broker.

My config is here (dev environment):

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: enterprise-bus
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 500Mi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.0"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 500Mi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
