### DISCUSSION TITLE
Configuring Read Only root filesystem in SecurityContext

### DISCUSSION THREAD

**Discussion by opsocomusr** [strimzi/strimzi-kafka-operator#6725] [Q&A]
Does Strimzi support running the pods with`readOnlyRootFilesystem`? We are getting the below error if we try to add this config in the CRD.

```
 template:
      pod:
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1001
```

```
error validating data: ValidationError(Kafka.spec.kafka.template.pod.securityContext): unknown field "readOnlyRootFilesystem" in io.strimzi.kafka.v1beta2.Kafka.spec.kafka.template.pod.securityContext; if you choose to ignore these errors, turn validation off with --validate=false
```

Will there be any change in pod's behaviour for the other 2 configs (`runAsNonRoot` and `runAsUser`) mentioned in the securityContext?
