### DISCUSSION TITLE
AKS ExternalName usage to expose to another namespace

### DISCUSSION THREAD

**Discussion by ghost** [strimzi/strimzi-kafka-operator#6777] [Q&A] [answered]
Hi guys,

In my AKS cluster I have a few microservices in one namespace and a Kafka cluster on a separate one.
I can communicate with Kafka bootstrap service with cluster-ip (nodePort) this ensures that ip address does not change?
I want a better approach, using a domain name and I try the follow:

```
kind: Service
apiVersion: v1
metadata:
  name: my-kafka-cluster-kafka-bootstrap
  namespace: kafka
spec:
  type: ExternalName
  externalName: kafka-bootstrap-external
```

but I can’t communicate with bootstrap when I use externalName "kafka-bootstrap-external", I notice that cluster-ip changed to none when I apply that yaml file.

How can I solve this problem?

Thanks :)
