### DISCUSSION TITLE
Kafka auth internal & external

### DISCUSSION THREAD

**Discussion by ghost** [strimzi/strimzi-kafka-operator#6788] [Q&A]
Hi,

I need to set up a cluster with the following requirements:

1. Enable an external App to write in one topic RegisterUser
2. Enable an internal App (in the same cluster as Kafka) to consume from the topic RegisterUser

I configured the Kafka cluster with the following listeners:
```
  listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls        
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
          type: tls
    authorization:
        type: simple
        superUsers:
           - ANONYMOUS
```
 and this is my user configuration:
 
```
 apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: RegisterUser
          patternType: literal
        operation: Read
        host: "*"
```

I can produce from the external network using a load balancer on port 9094, but when I try to consume on the internal port 9092 I'm getting an error:
Broker: Group authorization failed

When I checked the pod logs I got the following:
INFO Principal = User:ANONYMOUS is Denied Operation

So i add         
```
superUsers:
           - ANONYMOUS
```

Doing this internal clients bypassed by making ANONYMOUS a superuser.
I'm not able to connect to Kafka using the external listener without creds.
Is this approach safe? I still have the feeling that I'm missing something.
