### DISCUSSION TITLE
Warning while creating ingress listener: Translation failed: invalid ingress spec: service

### DISCUSSION THREAD

**Discussion by vaibhavk-cldcvr** [strimzi/strimzi-kafka-operator#6794] [Q&A]
Hello, this question is related to ingress type listener
my kafka config
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka1-cluster
spec:
  kafka:
    version: 3.0.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true 
        authentication:
          type: tls
      - name: externalnp
        port: 9095
        type: nodeport
        tls: true # true
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            nodePort: 31000
      - name: external
        port: 9096
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            host: kafka-bootstrap.masked.com
            annotations:
              cert-manager.io/ClusterIssuer: dev-letsencrypt
          brokers:
          - broker: 0
            host: broker-0.masked.com
            annotations:
              cert-manager.io/ClusterIssuer: dev-letsencrypt
          - broker: 1
            host: broker-1.masked.com
            annotations:
              cert-manager.io/ClusterIssuer: dev-letsencrypt
          - broker: 2
            host: broker-2.masked.com
            annotations:
              cert-manager.io/ClusterIssuer: dev-letsencrypt
          brokerCertChainAndKey:
            secretName: kafka-cert
            certificate: tls.crt
            key: tls.key
```
Ingress type listener creates bootstrap service of type ClusterIP
```
kafka1-cluster-kafka-external-0             ClusterIP      10.9.3.133    <none>           9096/TCP                              9h
kafka1-cluster-kafka-external-1             ClusterIP      10.9.11.116   <none>           9096/TCP                              9h
kafka1-cluster-kafka-external-2             ClusterIP      10.9.14.28    <none>           9096/TCP                              9h
kafka1-cluster-kafka-external-bootstrap     ClusterIP      10.9.7.83     <none>           9096/TCP                              9h
```

when I describe the ingress created by this, I get this warning
```
vaibhavkhalane@Vaibhav-Khalane ~ % k describe ing kafka1-cluster-kafka-external-bootstrap
Name:             kafka1-cluster-kafka-external-bootstrap
Namespace:        kafka
Address:          34.XX.XXX.XX
Default backend:  default-http-backend:80 (10.200.2.2:8080)
TLS:
  SNI routes kafka.masked.com
Rules:
  Host                            Path  Backends
  ----                            ----  --------
  kafka-bootstrap.masked.com
                                  /   kafka1-cluster-kafka-external-bootstrap:9096 (10.200.0.74:9096,10.200.2.67:9096,10.200.3.133:9096)
Annotations:                      cert-manager.io/ClusterIssuer: dev-letsencrypt
                                  ingress.kubernetes.io/ssl-passthrough: true
                                  nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                                  nginx.ingress.kubernetes.io/ssl-passthrough: true
Events:
  Type     Reason     Age                  From                     Message
  ----     ------     ----                 ----                     -------
  Warning  Translate  28m (x734 over 9h)   loadbalancer-controller  Translation failed: invalid ingress spec: service "kafka/kafka1-cluster-kafka-external-bootstrap" is type "ClusterIP", expected "NodePort" or "LoadBalancer"
  Normal   Sync       8m8s (x716 over 9h)  loadbalancer-controller  Scheduled for sync
```
Does this warning mean, traffic is prevented from going to service behind ingress? or why is it creating ClusterIP service instead of nodeport or loadbalancer?

**Comment by diedoman** [comment]
I was facing this same exact issue, and in my case this was caused by the type of ingress.

If you are trying to use nginx-ingress for this purpose, you must have ssl passthrough enabled (on nginx-ingress controller). If you do not have this, then your ingress will never reconcile (because 'regular' ingresses do not work on ClusterIP.). nginx-ingress with ssl-passthrough are an exception to this rule (as mentioned in the nginx documentation [here](https://kubernetes.github.io/ingress-nginx/user-guide/tls/#ssl-passthrough)

Another thing I am seeing in this log is that the the 'from' column under events references loadbalancer-controller, and not nginx. To make sure nginx-ingress is used, you might need to add the required annotation to your host. Here is an example of the cluster configuration that we got running with nginx-ingress with ssl-passthrough enabled.

```yaml

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0
    metadataVersion: 3.8-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: loadbalancer
        tls: true
        authentication:
          type: tls
      - name: public
        port: 9095
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          brokers:
          - broker: 0 
            host: broker-0.yourdomain.com
            annotations:
              kubernetes.io/ingress.class: "nginx"
          bootstrap:
            host: bootstrap.yourdomain.com
            annotations:
              kubernetes.io/ingress.class: "nginx"
```

**Reply by scholzj** [reply]
You should not need to add any annotations with Ingress class. Strimzi configures the ingress class when you specify it.

**Reply by diedoman** [reply]
@scholzj in my case I did see the annotations for ssl-passthrough appear, but I did not get the kubernetes.io/ingress.class: "nginx" annotation, causing the kubernetes cluster to try and add an ingress with its default type instead of using nginx-ingress. (nginx-ingress is not our default as we have more ingressclasses available).

In the example outputs of the original post in this thread I also see that the ingress.class annotation is not present, so seems that @vaibhavk-cldcvr was running into the same issue here and might have had their issue fixed by adding this annotation manually.

Perhaps I can try to reproduce this with a fresh setup. If I manage to reproduce it I will share it here, and if not will let you know as well ;)

**Reply by diedoman** [reply]
I created a new nodePool and KafkaCluster with the same settings, but without the ingress class annotation. Result is the same as mentioned  by @vaibhavk-cldcvr , so I think his problem was caused by the ingressclass not being set to nginx as well. 

My assumption is that this issue does not occur when your default ingress is set to nginx (and I think that almost everyone uses it as their default).

```/bash
Name:             test-cluster-kafka-public-bootstrap
Labels:           app.kubernetes.io/instance=test-cluster
                  app.kubernetes.io/managed-by=strimzi-cluster-operator
                  app.kubernetes.io/name=kafka
                  app.kubernetes.io/part-of=strimzi-test-cluster
                  argocd.argoproj.io/instance=strimzi
                  strimzi.io/cluster=test-cluster
                  strimzi.io/component-type=kafka
                  strimzi.io/kind=Kafka
                  strimzi.io/name=test-cluster-kafka
Namespace:        strimzi
Address:          
Ingress Class:    <none>
Default backend:  <default>
TLS:
  SNI routes bootstrap.testkafka.acceptance.evresys.nl
Rules:
  Host                                       Path  Backends
  ----                                       ----  --------
  bootstrap.testkafka.acceptance.evresys.nl  
                                             /   test-cluster-kafka-public-bootstrap:9095 (<none>)
Annotations:                                 ingress.kubernetes.io/ssl-passthrough: true
                                             nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                                             nginx.ingress.kubernetes.io/ssl-passthrough: true
Events:
  Type     Reason     Age                   From                     Message
  ----     ------     ----                  ----                     -------
  Normal   Sync       11s (x5 over 5m44s)   loadbalancer-controller  Scheduled for sync
  Warning  Translate  11s (x19 over 5m44s)  loadbalancer-controller  Translation failed: invalid ingress spec: service "strimzi/test-cluster-kafka-public-bootstrap" is type "ClusterIP", expected "NodePort" or "LoadBalancer"

```

and the configuration I used to set up this Kafka cluster:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: test-dual-role
  labels:
    strimzi.io/cluster: test-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        class: standard-rwo
        kraftMetadata: shared
        deleteClaim: true
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: test-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0
    metadataVersion: 3.8-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: loadbalancer
        tls: true
        authentication:
          type: tls
      - name: public
        port: 9095
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          # brokerCertChainAndKey:
          #   secretName: kafka-le-certificate
          #   certificate: tls.crt
          #   key: tls.key
          brokers:
          - broker: 0 
            host: broker-0.testkafka.acceptance.evresys.nl
            # annotations:
            #   kubernetes.io/ingress.class: "nginx"
          bootstrap:
            host: bootstrap.testkafka.acceptance.evresys.nl
            # annotations:
            #   kubernetes.io/ingress.class: "nginx"
    authorization:
      type: simple
      superUsers:
        - evresys
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
I use strimzi installed via 
helm (version 0.44.0), 
kubernetes engine version v1.30.3-gke.1639000

Would you like me to create a new issue for this @scholzj ? Really like the project and would love to help out in whatever way possible (e.g. updating documentation, unfortunately not very skilled in java)

**Reply by scholzj** [reply]
I think the annotation is not used anymore for some time. There is a field in the Ingress resource.

**Reply by diedoman** [reply]
You are correct, just stumbled across pull request [4715](https://github.com/strimzi/strimzi-kafka-operator/pull/4715) Which deprecates this annotation in favor of the class field. Sorry about that, will try to do my homework a bit better next time ;)

 For the sake of completeness I will post the updated solution here.

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: test-dual-role
  labels:
    strimzi.io/cluster: test-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        class: standard-rwo
        kraftMetadata: shared
        deleteClaim: true
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: test-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0
    metadataVersion: 3.8-IV0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: loadbalancer
        tls: true
        authentication:
          type: tls
      - name: public
        port: 9095
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          class: nginx # set your ingress class here
          brokers:
          - broker: 0 
            host: broker-0.testkafka.somedomain.com
          bootstrap:
            host: bootstrap.testkafka.somedomain.com
    authorization:
      type: simple
      superUsers:
        - evresys
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}

```
