### DISCUSSION TITLE
How to change time zone kafka cluster?

### DISCUSSION THREAD

**Discussion by northboys** [strimzi/strimzi-kafka-operator#6825] [Q&A]
How to change timezone on kafka cluster?

**Comment by scholzj** [comment]
I normally don't change, so not sure it still works. But at least in the past it worked to set the timezone in a `TZ` environment variable for the different containers: https://strimzi.io/docs/operators/latest/full/configuring.html#type-ContainerTemplate-reference ... I think you set it to a string such as `Europe/Prague`.

**Reply by northboys** [reply]
I've tried that but didn't work...

**Comment by harlemmuniz** [comment]
It worked for me in KafkaConnect resource container:

```yaml
spec:
  template:
    connectContainer:
      env:
        - name: TZ
          value: "America/Sao_Paulo"
```
