### DISCUSSION TITLE
InitContainer, run custom command ?

### DISCUSSION THREAD

**Discussion by Ycallaer** [strimzi/strimzi-kafka-operator#6853] [Q&A] [answered]
Hi all,
I am currently running Strimzi Connect with a custom image to run our different connectors.
However, I would like to add an InitContainer that accepts a custom command, and from the documentation this does not seem possible ?
So the use case: The init container should poll a custom endpoint (Confluent Schema Registry) and wait until the command returns a 200 return code. (so simple curl command).

I can see in https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/041-Crd-kafkaconnect.yaml that there is an "initContainer" option but it only accepts environment variables. But from the java code (https://github.com/strimzi/strimzi-kafka-operator/blob/9850f22e169fd19572ecefe7d5bde393e452fefd/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectCluster.java) I can't see how to pass a command ?

Anybody that can give me some pointers ? Many thanks

**Comment by scholzj** [comment, marked as answer]
Strimzi currently doesn't support custom init containers. The option in the CRD is to pass the environment variable to Strimzi's own init container used for _rack awareness_. TBH, I'm not sure I understand why do you need an init container to check if Schema Registry is running.

**Reply by Ycallaer** [reply]
So our connectors use SMTs that need schema registry. We have a job that restores schema registry and kafka connect should wait until a certain schema is present in SR. Otherwise KAfka Connect just fires , hits SR and if the restore job is not finished, it will fail.
This does not happen often, but we see this happen periodically, so a curl could be a remedy (I know it is not an ideal solution)

**Reply by scholzj** [reply]
TBH, this does not seem like the right solution to me. I think the real fix to this is to make it more resilient. Because what would you do if your Connect would be already running?

In any case, as I said - custom init containers are not supported by Strimzi today.

**Reply by Ycallaer** [reply]
ok thanks can be closed as answered

**Reply by rafis** [reply]
Many Helm Charts has extraManifests and extraInitContainers, it gives product extensibility and thus more appealing to use.

**Reply by dvaldivia** [reply]
@scholzj I think the use case for init containers is to do things like crafting a custom truststore, we have a use case where we need the KafkaConnect cluster to trust another service that is using [kubernetes signed certificates](https://kubernetes.io/docs/reference/access-authn-authz/certificate-signing-requests/) thus we need the kafka connect cluster to trust anything signed by the kubernetes root CA which every pod has available at `/var/run/secrets/kubernetes.io/serviceaccount/ca.crt`, an easy solution is would be to include an init container to do this:

```yaml
      initContainers:
        - name: init-truststore
          image: private.registry.com/openjdk:11-jre-slim
          command:
            - /bin/sh
            - -c
          args:
            - |
              mkdir -p /truststore/certs && \
              cp $JAVA_HOME/lib/security/cacerts /truststore/certs/truststore.jks && \
              keytool -importcert -noprompt -trustcacerts -file /var/run/secrets/kubernetes.io/serviceaccount/ca.crt -alias "kubernetes.ca" -keystore /truststore/certs/truststore.jks -storepass ${TRUSTSTORE_PASSWORD} && \
              echo "Truststore created successfully"
          env:
            - name: TRUSTSTORE_PASSWORD
              value: "YourTruststorePassword"
          volumeMounts:
            - name: truststore-volume
              mountPath: /truststore
```
