### DISCUSSION TITLE
Mirrormaker2 mirrorSourceConnector stuck using 1 task

### DISCUSSION THREAD

**Discussion by ntrvic** [strimzi/strimzi-kafka-operator#6857] [General]
I have a mm2 sourceConnector that is responsible for a lot of topic-partitions, however specifically for the sourceConnector, it only runs 1 task. I have the following configuration:

```
      sourceConnector:
        config:
          offset-syncs.topic.replication.factor: 3
          replication.factor: 3
          replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
          sync.topic.acls.enabled: "false"
        tasksMax: 100
...
    topicsPattern: .*
```     

The connect rest call for tasks looks like:

```
$ curl localhost:8083/connectors/events-dal-%3Edemo-cluster.MirrorSourceConnector/tasks
[{"id":{"connector":"events-dal->demo-cluster.MirrorSourceConnector","task":0},"config":{"target.cluster.status.storage.replication.factor":"-1","connector.class":"org.apache.kafka.connect.mirror.MirrorSourceConnector","offset-syncs.topic.replication.factor":"3","replication.factor":"3","sync.topic.acls.enabled":"false","topics":".*","replication.policy.class":"io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy","target.cluster.config.storage.replication.factor":"-1","source.cluster.alias":"events-dal","groups":".*","source.cluster.bootstrap.servers":"***********:9092","target.cluster.offset.storage.replication.factor":"-1","target.cluster.alias":"demo-cluster","task.class":"org.apache.kafka.connect.mirror.MirrorSourceTask","name":"events-dal->demo-cluster.MirrorSourceConnector","target.cluster.bootstrap.servers":"demo-cluster-kafka-bootstrap.kafka.svc:9096","task.assigned.partitions": < list of all partitions in our cluster >"
```

I do not see the same problem with the checkpoint connector. Could this be a bug, or am I missing something obvious?

Thank you!
