### DISCUSSION TITLE
KubernetesSecretConfigProvider Looking in Multiple Namespaces for Secret

### DISCUSSION THREAD

**Discussion by shubhamg7** [strimzi/strimzi-kafka-operator#6874] [Q&A] [answered]
Hello! We are setting up Kafka Connectors that provide database passwords via the `KubernetesSecretConfigProvider`. Originally we had one connector running perfectly fine using the `KubernetesSecretConfigProvider` to provide the secret from the same namespace as the connector. However when we have setup two connectors in different namespaces they are trying to read the secret value not only in its own namespace but also the other connectors namespace. Is this expected behavior?

I have been following [this blog post](https://strimzi.io/blog/2021/07/22/using-kubernetes-config-provider-to-load-data-from-secrets-and-config-maps/) for guidance.

Here's the exact config:

Connector A:
```
# ROLE
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role-A
  namespace: namespace-A
rules:
- apiGroups:
  - ""
  resourceNames:
  - my-secret
  resources:
  - secrets
  verbs:
  - get

# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-configuration-role-binding
  namespace: namespace-A
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: connector-configuration-role-A
subjects:
- kind: ServiceAccount
  name: my-connect-A-connect  # created by strimzi
  namespace: namespace-A

# Connector
database.password: ${secrets:namespace-A/my-secret:my-key}
```

Connector B:
```
# ROLE
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role-B
  namespace: namespace-B
rules:
- apiGroups:
  - ""
  resourceNames:
  - my-secret
  resources:
  - secrets
  verbs:
  - get

# Role Binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-configuration-role-binding
  namespace: namespace-B
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: connector-configuration-role-B
subjects:
- kind: ServiceAccount
  name: my-connect-B-connect  # created by strimzi
  namespace: namespace-B

# Connector
database.password: ${secrets:namespace-B/my-secret:my-key}
```

In both of the pods' logs I can also see the pod trying to retrieve the secret from the two distinct namespaces:
```
INFO Retrieving configuration from Secret my-secret in namespace namespace-A
INFO Retrieving configuration from Secret my-secret in namespace namespace-B
```

One of these retrievals succeeds but the other causes the pods for each connector to crash with an error like so:

```
org.apache.kafka.common.config.ConfigException: Invalid value io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.20.0.1/api/v1/namespaces/<namespace-name>/secrets/<secret-name>. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. secrets "<secret-name>" is forbidden: User "system:serviceaccount:<service-account-name>" cannot get resource "secrets" in API group "" in the namespace "<namespace-name>".
```

Ideally each pod should only look for the secret in its own namespace rather than trying to fetch the secret in another namespace. Please let me know if there is a fix for this and if theres anything I can expand on!
