### DISCUSSION TITLE
Creating a KafkaConnect image from a maven repository

### DISCUSSION THREAD

**Discussion by anamaymane** [strimzi/strimzi-kafka-operator#6925] [Q&A] [answered]
I'm trying too build a connect image using maven for retrieving an elasticsearch-connector. But apparently strimzi doesn't recognize the used configuration:

Here is my KafkaConnect yaml file:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-kafka-cluster-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 2
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  build:
    output:
      type: docker
      image: registry.gitlab.tech/test/kafka-connect-strimzi:1.6
      pushSecret: regcred
    plugins:
      - name: kafka-connect-elasticsearch2
        artifacts:
          - type: maven
            groupId: io.confluent
            artifactId: kafka-connect-elasticsearch
            version: 10.0.1

  config:
      group.id: connect-kafka-to-elk
      config.storage.topic: docker-connect-configs
      offset.storage.topic: docker-connect-offsets
      status.storage.topic: docker-connect-status
      key.ignore: "true"
      schema.ignore: "true"
      value.converter: "org.apache.kafka.connect.json.JsonConverter"
      value.converter.schemas.enable: false
      config.storage.replication.factor: "1"
      offset.storage.replication.factor: "1"
      status.storage.replication.factor: "1"
  resources:
    requests:
      cpu: "2"
      memory: 4Gi
    limits:
      cpu: "2"
      memory: 4Gi
  externalConfiguration:
    volumes:
      - name: elk-secret-store
        secret:
          secretName: elk-secret-store
  template:
    pod:
      imagePullSecrets:
        - name: regcred
```

Noting that I'm trying to use maven as a plugin source, because the connectors jars are missing some java dependencies

**Comment by scholzj** [comment]
What does it mean _doesn't recognize the used configuration_. I think you need to share more details, logs, statuses etc.

**Comment by anamaymane** [comment]
When I try to create a jar from a maven repo like this:

```
build:
    output:
      type: docker
      image: registry.gitlab.tech/test/kafka-connect-strimzi:1.6
      pushSecret: regcred
    plugins:
      - name: kafka-connect-elasticsearch
        artifacts:
          - type: maven
            groupId: io.confluent
            artifactId: kafka-connect-elasticsearch
            version: "10.0.1"
```

I have the following error when trying to update the cluster:

```
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(KafkaConnect.spec.build.plugins[0].artifacts[0]): unknown field "artifactId" in io.strimzi.kafka.v1beta2.KafkaConnect.spec.build.plugins.artifacts, ValidationError(KafkaConnect.spec.build.plugins[0].artifacts[0]): unknown field "groupId" in io.strimzi.kafka.v1beta2.KafkaConnect.spec.build.plugins.artifacts]
```

I'm using strimzi 0.29.0

**Reply by scholzj** [reply]
Sorry, but this is message from where?

**Reply by anamaymane** [reply]
This message is outputed by Helm when I  try to execute  the update to the cluster like this : 
```
helm upgrade install feature-name repo
```

Output:

```
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/cloud/.kube/mimir-k8s-config.yaml
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/cloud/.kube/mimir-k8s-config.yaml
Error: UPGRADE FAILED: error validating "": error validating data: [ValidationError(KafkaConnect.spec.build.plugins[0].artifacts[0]): unknown field "artifactId" in io.strimzi.kafka.v1beta2.KafkaConnect.spec.build.plugins.artifacts, ValidationError(KafkaConnect.spec.build.plugins[0].artifacts[0]): unknown field "groupId" in io.strimzi.kafka.v1beta2.KafkaConnect.spec.build.plugins.artifacts]
```

**Reply by scholzj** [reply]
I guess the fields are wrong? Did you checked the docs or the examples?

**Reply by anamaymane** [reply]
In fact in the doc, I haven't found an example using maven as a source of jar plugins. but I've seen that it was mentionned in the proposal doc that was made to incite the kafka connect build image feature. Here is the proposal doc I'm talking about: [https://github.com/strimzi/proposals/blob/main/015-kafka-connect-build.md](url)

**Reply by scholzj** [reply]
The examples are on the GitHub in the examples folder. The docs have both example of the Maven artifact as well as the reference guide for each field of the APi. Your fields are using a wrong name. So please fix it according to the docs.

**Reply by anamaymane** [reply]
Thank you, after digging in the doc I've found the correct syntax which is:
```
build:
    output:
      type: docker
      image: registry.gitlab.tech/test/kafka-connect-strimzi:1.8
      pushSecret: regcred
    plugins:
      - name: kafka-connect-elasticsearch
        artifacts:
          - type: maven
            repository: https://packages.confluent.io/maven/
            group: io.confluent
            artifact: kafka-connect-elasticsearch
            version: 10.0.1
```

However the Kafkaconnect image is not built due to parent pom errors, I don't know if you've an idea about it, here is the error message I get:

```
INFO[0076] Running: [/bin/sh -c 'curl' '-f' '-L' '--create-dirs' '--output' '/tmp/kafka-connect-elasticsearch/2cfc6ef7/pom.xml' 'https://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/10.0.1/kafka-connect-elasticsearch-10.0.1.pom'       && 'mvn' 'dependency:copy-dependencies' '-DoutputDirectory=/tmp/artifacts/kafka-connect-elasticsearch/2cfc6ef7' '-f' '/tmp/kafka-connect-elasticsearch/2cfc6ef7/pom.xml'       && 'curl' '-f' '-L' '--create-dirs' '--output' '/tmp/artifacts/kafka-connect-elasticsearch/2cfc6ef7/kafka-connect-elasticsearch-10.0.1.jar' 'https://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/10.0.1/kafka-connect-elasticsearch-10.0.1.jar'] 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 22662  100 22662    0     0  24848      0 --:--:-- --:--:-- --:--:-- 24848
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/io/confluent/common/6.0.0/common-6.0.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.confluent:kafka-connect-elasticsearch:10.0.1: Could not transfer artifact io.confluent:common:pom:6.0.0 from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 5, column 13
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.confluent:kafka-connect-elasticsearch:10.0.1 (/tmp/kafka-connect-elasticsearch/2cfc6ef7/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.confluent:kafka-connect-elasticsearch:10.0.1: Could not transfer artifact io.confluent:common:pom:6.0.0 from/to confluent (${confluent.maven.repo}): Cannot access ${confluent.maven.repo} with type default using the available connector factories: BasicRepositoryConnectorFactory and 'parent.relativePath' points at wrong local POM @ line 5, column 13: Cannot access ${confluent.maven.repo} using the registered transporter factories: WagonTransporterFactory: Unsupported transport protocol -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

**Reply by scholzj** [reply]
Well, the artifacts do not seem to be in Maven Central but in some private Maven repository. We really just feed the main artifact you specify into Maven and it downloads the dependencies. As the error suggests, it does not seem to be able to download it. Not sure why. If you share the generated Dockerfile maybe I see something obvious.

**Reply by anamaymane** [reply]
And how we can view the generated dockerfile ?

**Reply by scholzj** [reply]
There should be a config map which has it.

**Reply by anamaymane** [reply]
The problem is that the image is not built yet. the error occurs during the build

**Reply by anamaymane** [reply]
otherwise, is there a possiblity to pass env variables to the connect image builder pod. I think that specifying a maven option through environment variables will help me resolve the issue

**Reply by scholzj** [reply]
That doesn't matter. The Dockerfile is not the image ... that is the file with the instructions used to build the Docker image.

**Reply by anamaymane** [reply]
I finally find it, here is its content:

```
##############################
##############################
# This file is automatically generated by the Strimzi Cluster Operator
# Any changes to this file will be ignored and overwritten!
##############################
##############################

FROM quay.io/strimzi/maven-builder:0.29.0 AS downloadArtifacts
RUN 'curl' '-f' '-L' '--create-dirs' '--output' '/tmp/kafka-connect-elasticsearch/2cfc6ef7/pom.xml' 'https://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/10.0.1/kafka-connect-elasticsearch-10.0.1.pom' \
      && 'mvn' 'dependency:copy-dependencies' '-DoutputDirectory=/tmp/artifacts/kafka-connect-elasticsearch/2cfc6ef7' '-f' '/tmp/kafka-connect-elasticsearch/2cfc6ef7/pom.xml' \
      && 'curl' '-f' '-L' '--create-dirs' '--output' '/tmp/artifacts/kafka-connect-elasticsearch/2cfc6ef7/kafka-connect-elasticsearch-10.0.1.jar' 'https://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/10.0.1/kafka-connect-elasticsearch-10.0.1.jar'

FROM quay.io/strimzi/kafka:0.29.0-kafka-3.2.0

USER root:root

##########
# Connector plugin kafka-connect-elasticsearch
##########
COPY --from=downloadArtifacts '/tmp/artifacts/kafka-connect-elasticsearch/2cfc6ef7' '/opt/kafka/plugins/kafka-connect-elasticsearch/2cfc6ef7'
```

**Reply by scholzj** [reply]
Hmm, the pom.xml does not have the repository specified, so that is why it is not found. Not sure there is any easy workaround or fix.

**Comment by pcollinscode** [comment, marked as answer]
I ran across this same issue yesterday with the Confluent repository, here is what I did to solve it for the moment

1. I created a new Dockerfile which extended the Maven builder image to add a user's `settings.xml` file with additional repositories that Maven should use to look for dependencies.
```
FROM quay.io/strimzi/maven-builder

# I needed to use the root user, when I tried to use the 1001 user defined in the base it could not find the settings file. I didn't investigate further, see here https://github.com/strimzi/strimzi-kafka-operator/blob/main/docker-images/maven-builder/Dockerfile.
USER root

# see https://maven.apache.org/guides/mini/guide-multiple-repositories.html#repository-order for how Maven determines repos
COPY settings.xml /root/.m2/settings.xml
```
And then the `settings.xml` file that is copied into the users maven settings location
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
    <profiles>
        <profile>
            <id>confluent</id>
            <repositories>
                <repository>
                    <id>confluent</id>
                    <name>Confluent</name>
                    <url>https://packages.confluent.io/maven</url>
                </repository>
            </repositories>
        </profile>
    </profiles>
    <activeProfiles>
        <activeProfile>confluent</activeProfile>
    </activeProfiles>
</settings>
```
2. Update the Strimzi operator use the extended Maven builder (swap out whichever image registry you are using). **NOTE**: Your k8s cluster needs to be configured to pull images from your repository if its private first.
```
resource "helm_release" "strimzi_operators" {
  name       = "strimzi-operator"
  repository = "https://strimzi.io/charts/"
  chart      = "strimzi-kafka-operator"
  version    = "0.28.0"
  namespace  = local.ns_name
  
  set {
    name  = "mavenBuilder.image.registry"
    value = "<your registry here>"
  }
  set {
    name  = "mavenBuilder.image.repository"
    value = "<your repo here>"
  }
  set {
    name  = "mavenBuilder.image.name"
    value = "maven-builder"
  }
  set {
    name  = "mavenBuilder.image.tag"
    value = "latest"
  }
}
```
3. Added the maven artifact to the KafkaConnect plugins
```
    plugins:
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/{{ .Values.debezium.version }}.Final/debezium-connector-postgres-{{ .Values.debezium.version }}.Final-plugin.tar.gz
      - name: confluent-connect-avro-converter
        artifacts:
          - type: maven
            repository: https://packages.confluent.io/maven
            group: io.confluent
            artifact: kafka-connect-avro-converter
            version: 7.1.1
```
And that was it and it successfully built and deployed KafkaConnect with Confluent plugins from their registry even though their `pom.xml` don't specify the registry which is what causes the issue originally.

It could be nice if Strimzi somehow allowed us to specify the maven-builder user settings via the chart and then build that settings.xml file within the default maven-builder image when people might need to configure Maven for any reason.
