### DISCUSSION TITLE
KafkaTopic not working (topics not created)

### DISCUSSION THREAD

**Discussion by anamaymane** [strimzi/strimzi-kafka-operator#6928] [Q&A] [answered]
I'm trying to create a KafkaTopic resource using strimzi, however the topic is not create on kafka.

When listing the KafkaTopic resources, I can see that the KafkaTopic is created but the state is not ready:

```
$ kubectl get KafkaTopic
NAME              CLUSTER      PARTITIONS   REPLICATION FACTOR   READY
pipeline-events   my-cluster   2            2   
```

When describing the resource, I can't see a relevant event:

```
$ kubectl describe KafkaTopic pipeline-events 
Name:         pipeline-events
Namespace:    aymane-test-area
Labels:       app.kubernetes.io/managed-by=Helm
              strimzi.io/cluster=my-cluster
Annotations:  meta.helm.sh/release-name: test-app-v1
              meta.helm.sh/release-namespace: aymane-test-area
API Version:  kafka.strimzi.io/v1beta2
Kind:         KafkaTopic
Metadata:
  Creation Timestamp:  2022-06-13T09:27:34Z
  Generation:          1
  Managed Fields:
    API Version:  kafka.strimzi.io/v1beta2
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:meta.helm.sh/release-name:
          f:meta.helm.sh/release-namespace:
        f:labels:
          .:
          f:app.kubernetes.io/managed-by:
          f:strimzi.io/cluster:
      f:spec:
        .:
        f:partitions:
        f:replicas:
    Manager:         helm
    Operation:       Update
    Time:            2022-06-13T09:27:34Z
  Resource Version:  92124982
  Self Link:         /apis/kafka.strimzi.io/v1beta2/namespaces/aymane-test-area/kafkatopics/pipeline-events
  UID:               efe1efbd-aab1-46b0-b1ed-5e0c942bfeaf
Spec:
  Partitions:  2
  Replicas:    2
Events:        <none>
```

Also I've noticed that in the cluster operator logs, there is no sign of a topic creation or the creation of the topic operator.

here is my KafkaTopic yaml file:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: pipeline-events
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 2
  partitions: 2
```

Here is my kafka cluster yaml file:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: ingress
        tls: true
        configuration:
          class: nginx
          bootstrap:
            host: kafkabootstrap.test
          brokers:
            - broker: 0
              host: kafkabroker0.test
            - broker: 1
              host: kafkabroker1.test
          brokerCertChainAndKey:
            secretName: kafka-external-listner-secret
            certificate: tls.crt
            key: tls.key
    storage:
      type: ephemeral
    config:
      auto.create.topics.enable: "true"
      offsets.topic.replication.factor: 1
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
```
