### DISCUSSION TITLE
Monitoring Questions

### DISCUSSION THREAD

**Discussion by doronl** [strimzi/strimzi-kafka-operator#6950] [General]
Hi, using version 0.29, I didn't find any notes on documenmtation for this...

Anyway, I configued monitoring according to examples, (JMX on Kafka and ZK as well as Kafka exporter), after reconciliation I see only the Kafka exporter pod running... where are the JMX Exporters? did find any sidecar containers or related pods

I a deploying to a cluser with existing prometheus and Grafana, I added the new dashboards but I can only see the operators metrics...

**Comment by scholzj** [comment]
You should probably share your Kafka custom resource to make it clear what examples you used. From your description it is not clear if you are trying to use JMX access or Prometheus metrics.

**Reply by doronl** [reply]
Below is my Kafka CRD than PodMoniors
metrics yaml where taken from: https://github.com/strimzi/strimzi-kafka-operator/blob/0.29.0/examples/metrics/kafka-metrics.yaml as separte files.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: fg-kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    resources:
      requests:
        memory: 13Gi
        cpu: "3"
      limits:
        memory: 13Gi
        cpu: "3"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions:
      -Xms: 10240m
      -Xmx: 10240m
    storage:
      type: persistent-claim
      size: 900Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yaml
    template:
      pod:
        tolerations:
          - key: kafka-agents
            operator: Equal
            value: 'true'
            effect: NoSchedule
    rack:
      topologyKey: topology.kubernetes.io/zone
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
  zookeeper:
    replicas: 1
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    resources:
      requests:
        memory: 8Gi
        cpu: "2"
      limits:
        memory: 8Gi
        cpu: "2"
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    storage:
      type: persistent-claim
      size: 200Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: zookeeper-metrics
          key: zookeeper-metrics.yaml
    template:
      pod:
        tolerations:
          - key: eck-kibana-agents
            operator: Equal
            value: 'true'
            effect: NoSchedule
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
PodMonitors CRDs

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-operator-metrics
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      strimzi.io/kind: cluster-operator
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
    - path: /metrics
      port: http

---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: entity-operator-metrics
  labels:
    app: strimzi
    prometheus: kube-prometheus
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: entity-operator
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
    - path: /metrics
      port: healthcheck
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-resources-metrics
  labels:
    app: strimzi
    prometheus: kube-prometheus
    release: kube-prometheus-stack
spec:
  selector:
    matchExpressions:
      - key: "strimzi.io/kind"
        operator: In
        values: ["Kafka", "KafkaConnect"]
  namespaceSelector:
    matchNames:
      - kafka
  podMetricsEndpoints:
    - path: /metrics
      port: tcp-prometheus
      relabelings:
        - separator: ;
          regex: __meta_kubernetes_pod_label_(strimzi_io_.+)
          replacement: $1
          action: labelmap
        - sourceLabels: [__meta_kubernetes_namespace]
          separator: ;
          regex: (.*)
          targetLabel: namespace
          replacement: $1
          action: replace
        - sourceLabels: [__meta_kubernetes_pod_name]
          separator: ;
          regex: (.*)
          targetLabel: kubernetes_pod_name
          replacement: $1
          action: replace
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          separator: ;
          regex: (.*)
          targetLabel: node_name
          replacement: $1
          action: replace
        - sourceLabels: [__meta_kubernetes_pod_host_ip]
          separator: ;
          regex: (.*)
          targetLabel: node_ip
          replacement: $1
          action: replace

```

**Reply by scholzj** [reply]
Ok, so that is Prometheus monitoring. There is no separate pod. The JMX exporter rusn directly inside the Kafka / ZooKeeper pods as a Java agent. The metrics are exposed directly from the pods on port 9404 (if you exec into the pod, try something like `curl localhost:9404/metrics`). The PodMonitor resources wich are part of the Examples tell the Prometheus Operator to configure Prometheus to scrape the metrics directly from the pods.

**Reply by doronl** [reply]
I see, than I need to add to my Kafka CRD inoder for the PodMonitor to pick it up? 

```
metadata:
  labels:
    app: strimzi

```

BTW, my existing Prometheus is configurd with:

```
  podMonitorSelector:
    matchLabels:
      release: kube-prometheus-stack
```

**Reply by scholzj** [reply]
I'm not really expert on Prometheus and its configuration. I don't think you need `app: strimzi` label on the Kafka CR. The Kafka pods should be picked up with this selector from the PodMonitor:
```yaml
  selector:
    matchExpressions:
      - key: "strimzi.io/kind"
        operator: In
        values: ["Kafka", "KafkaConnect"]
```

You just need to make sure your Prometheus (Prometheus Operator) sees the PodMonitors and can connect to the brokers (things such as network isolation between namespaces etc. might cause issues for example)

**Reply by doronl** [reply]
I see your proint, selection is by the resource type... curl works for me inside the pods with localhost:9404/metrics however only the  operator metrics are arriving to Prometheus, not the kafka exporter nore the kafka JMX or ZK JMX are arriving there...

**Reply by scholzj** [reply]
As I said, I'm afraid I don't know much about Prometheus :-/. I know the usual advice is to check the targets in the Prometheus UI. That should tell you if Prometheus knows it should scrape them or not. But I'm afraid I don't know much what next.

> selection is by the resource type

This is actually a label which is on the pod. It mirrors the Kind of the resource which triggered the creation, but it has the form of the label on the pods here.

**Reply by scholzj** [reply]
One think I noticed is that your Cluster Operator Pod Monitor does not have these labels:
```
    prometheus: kube-prometheus
    release: kube-prometheus-stack
```

All other PodMonitors above have them. Could that be related somehow? Possibly, also the relabeling rules are different on the PodMonitor for the Kafka metrics. So another possible things which can cause some differences.

**Reply by doronl** [reply]
OK, thanks, I will continue digging into this, will update if there is anything interesting

**Comment by doronl** [comment]
I had some improvement but still not functioning as expected...

I used a ServiceMonitor instead of a PodMonitor, it needs to work with a service though... I tried creating a service that will give me all pods with:

```
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9404
      targetPort: 9404
  selector:
    strimzi.io/kind: Kafka
  type: ClusterIP
```
But it picked up the entity-operator as it has label strimzi.io/kind: Kafka as well and it is a failing target on prometheus...
At the same time I still have some problems  with metrics and dashboards, questions:

1. Is there a minimal requirement for prometheus and grafana versions for the metrics integration to work?
2. Is the label strimzi.io/kind: Kafka on the entity-operator correct? Can I remove it somehow?
3. Can I add a custom label to zookeeper and kafka-exporter pods?
