### DISCUSSION TITLE
Zookeeper image change

### DISCUSSION THREAD

**Discussion by miroslavmasaryk3221** [strimzi/strimzi-kafka-operator#6981] [General]
Hello everyone,

Im trying to change image for zookeper inside chart for argoCD:
I have tried everything my strimzi instance always tries to fetch image 3.0.0 unforunately this image is broken, unexepected EOF but I know that 3.1.0 is working, so I need to change it to work with 3.1.0 
Here is my yaml file:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
spec:
  destination:
    namespace: strimzi-system
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: strimzi-kafka-operator
    repoURL: myrepourl
    targetRevision: 0.28.0
    helm:
      values: |
        watchNamespaces: []
        watchAnyNamespace: true
        defaultImageRegistry: artifactory.de/quay.io
        defaultImageRepository: strimzi
        defaultImageTag: 0.28.0
        image:
          registry: "artifactory.de/quay.io"
          repository: "strimzi"
          name: operator
          tag: "0.28.0"
        logVolume: co-config-volume
        logConfigMap: strimzi-cluster-operator
        logLevel: ${env:STRIMZI_LOG_LEVEL:-INFO}
        fullReconciliationIntervalMs: 120000
        operationTimeoutMs: 300000
        kubernetesServiceDnsDomain: cluster.local
        featureGates: ""
        tmpDirSizeLimit: 1Mi
        # Example on how to configure extraEnvs
        # extraEnvs:
        #   - name: JAVA_OPTS
        #     value: "-Xms256m -Xmx256m"
        extraEnvs: []
        tolerations: []
        affinity: {}
        annotations: {}
        labels: {}
        nodeSelector: {}
        priorityClassName: ""
        podSecurityContext: {}
        securityContext: {}
        # Docker images that operator uses to provision various components of Strimzi.  To use your own registry prefix the
        # repository name with your registry URL.
        # Ex) repository: registry.xyzcorp.com/strimzi/zookeeper
        zookeeper:
          image:
            registry: "artifactory.de"
            repository: "strimzi"
            tag: "0.28.0-kafka-3.1.0"
        kafka:
          image:
            registry: ""
            repository: ""
            name: kafka
            tagPrefix: ""
        kafkaConnect:
          image:
            registry: ""
            repository: ""
            name: kafka
            tagPrefix: ""
        topicOperator:
          image:
            registry: ""
            repository: ""
            name: operator
            tag: ""
        userOperator:
          image:
            registry:
            repository:
            name: operator
            tag: ""
        kafkaInit:
          image:
            registry: ""
            repository: ""
            name: operator
            tag: ""
        tlsSidecarEntityOperator:
          image:
            registry: ""
            repository: ""
            name: kafka
            tagPrefix: ""
        kafkaMirrorMaker:
          image:
            registry: ""
            repository: ""
            name: kafka
            tagPrefix: ""
        kafkaBridge:
          image:
            registry: ""
            repository:
            name: kafka-bridge
            tag: 0.21.4
        kafkaExporter:
          image:
            registry: ""
            repository: ""
            name: kafka
            tagPrefix: ""
        jmxTrans:
          image:
            registry: ""
            repository: ""
            name: jmxtrans
            tag: ""
        kafkaMirrorMaker2:
          image:
            registry: ""
            repository: ""
            name: kafka
            tagPrefix: ""
        cruiseControl:
          image:
            registry: ""
            repository: ""
            name: kafka
            tagPrefix: ""
        tlsSidecarCruiseControl:
          image:
            registry: ""
            repository: ""
            name: kafka
            tagPrefix: ""
        kanikoExecutor:
          image:
            registry: ""
            repository: ""
            name: kaniko-executor
            tag: ""
        mavenBuilder:
          image:
            registry: ""
            repository: ""
            name: maven-builder
            tag: ""
        resources:
          limits:
            memory: 384Mi
            cpu: 1000m
          requests:
            memory: 384Mi
            cpu: 200m
        livenessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 30
        createGlobalResources: true
        # Override the exclude pattern for exclude some labels
        labelsExclusionPattern: ""
        # Controls whether Strimzi generates network policy resources (By default true)
        generateNetworkPolicy: true
        # Override the value for Connect build timeout
        connectBuildTimeoutMs: 300000       
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
```
