### DISCUSSION TITLE
entity-operator and kafka-exporter questions - after upgrade to 0.29.0 using Kafka 3.1.0

### DISCUSSION THREAD

**Discussion by BBQigniter** [strimzi/strimzi-kafka-operator#7001] [Q&A] [answered]
Hi,

I recently tried the upgrade on one of our lab-clusters and it worked fine and was straight forward :) - only one thing is a little bit confusing for me. Before and after the upgrade the Kafka and Zookeeper images are still version 3.1.0 as it should be and the `statefulsets` are using the 0.29.0 images. But the `entity-operator` and `kafka-exporter` are suddenly using the 0.29.0's version 3.2.0 images.

* Is this normal behavior?
* Will this create any issues if there is a version mismatch?
  * If so how can I tell the cluster-operator to also use the same version for the `entitiy-operator` and `kafka-exporter` for a cluster?
     In the documentation https://strimzi.io/docs/operators/latest/configuring.html#type-KafkaClusterSpec-schema-reference I can see that `version`  is available (and in our cluster-config yaml I also use it) but in https://strimzi.io/docs/operators/latest/configuring.html#type-EntityOperatorSpec-reference and https://strimzi.io/docs/operators/latest/configuring.html#type-KafkaExporterSpec-reference I couldn't find something similar. 
    Snippet from my cluster-yaml I use
    ```
    apiVersion: kafka.strimzi.io/v1beta2
    kind: Kafka
    metadata:
      name: kafka-lab
      namespace: kafka-lab
    spec:
      kafka:
        version: 3.1.0
    ...
      entityOperator:
        # if {} - default values are used
        # if completely removed - those operator are not used at all
        # see https://strimzi.io/docs/operators/latest/configuring.html#assembly-kafka-entity-operator-str
        topicOperator: {}
        userOperator: {}
      kafkaExporter: {}
    ...
    ```

Thanks for help in advance :)
