### DISCUSSION TITLE
kafka strimzi not able to connect using internal/external load balancer

### DISCUSSION THREAD

**Discussion by monish-devendran** [strimzi/strimzi-kafka-operator#7031] [Q&A] [answered]
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name:my-cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 1
    template:
      externalBootstrapService:
        metadata:
          annotations:
            cloud.google.com/load-balancer-type: "Internal"
      perPodService:
        metadata:
          annotations:
            cloud.google.com/load-balancer-type: "Internal"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        configuration:
          bootstrap:
            annotations:
              cloud.google.com/load-balancer-type: "Internal"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.2"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
  zookeeper:
    replicas: 1
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
```
