### DISCUSSION TITLE
Kafka Connect: is it possible to manage connectors state?

### DISCUSSION THREAD

**Discussion by mirisu2** [strimzi/strimzi-kafka-operator#7042] [Q&A] [answered]
Hi,
Is it possible to manage connectors state? For example, a connector went into FAIL state. And, as I can see, operator doesn't restart a connector. A connector stays in fail state. 
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: "true"
```
What can I do in this case?
