### DISCUSSION TITLE
I am getting error  "The group coordinator is not available"

### DISCUSSION THREAD

**Discussion by 4sif-adnan** [strimzi/strimzi-kafka-operator#7044] [Q&A]
Hi,

I am getting below error..
```
{"level":"ERROR","timestamp":"2022-07-12T11:58:47.199Z","logger":"kafkajs","message":"[Consumer] Crash: KafkaJSProtocolError: The group coordinator is not available","groupId":"noice-live-group","stack":"KafkaJSProtocolError: The group coordinator is not available\n    at createErrorFromCode (/noice-live-service/node_modules/kafkajs/src/protocol/error.js:581:10)\n    at Object.parse (/noice-live-service/node_modules/kafkajs/src/protocol/requests/syncGroup/v0/response.js:24:11)\n    at Connection.send (/noice-live-service/node_modules/kafkajs/src/network/connection.js:333:35)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async Broker.[private:Broker:sendRequest] (/noice-live-service/node_modules/kafkajs/src/broker/index.js:947:14)\n    at async Broker.syncGroup (/noice-live-service/node_modules/kafkajs/src/broker/index.js:476:12)\n    at async ConsumerGroup.[private:ConsumerGroup:sync] (/noice-live-service/node_modules/kafkajs/src/consumer/consumerGroup.js:211:34)\n    at async /noice-live-service/node_modules/kafkajs/src/consumer/consumerGroup.js:314:9\n    at async Runner.join (/noice-live-service/node_modules/kafkajs/src/consumer/runner.js:77:5)\n    at async Runner.start (/noice-live-service/node_modules/kafkajs/src/consumer/runner.js:100:7)\n    at async start (/noice-live-service/node_modules/kafkajs/src/consumer/index.js:251:7)"}
{"level":"INFO","timestamp":"2022-07-12T11:58:47.199Z","logger":"kafkajs","message":"[Consumer] Stopped","groupId":"noice-live-group"}
```
I have below config with 3 replica..i already deleted and re-created the cluster but still same error showing
```
config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
```
