### DISCUSSION TITLE
Zookeeper crashes with 3 replicas but not with 1

### DISCUSSION THREAD

**Discussion by ralphflat** [strimzi/strimzi-kafka-operator#7058] [Q&A]
We configured the Strimzi operator to watch two namespaces - oper and devel. The Strimzi operation is installed into the kafka-operator namespace.

We apply the Kafka kind definition file (below) and see zookeeper start up, but no kafka instance.

```
more kafka-operational.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: operational
spec:
  kafka:
    version:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.2"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

We only see zookeeper pods (no kafka pods) in the watched namespace (the 'oper' namespace)

![image](https://user-images.githubusercontent.com/86305586/179017207-f69ad0df-a3db-4c4e-8d39-c9cd16b6a3ac.png)

When we look at the logs of one of the zookeeper services, we see the following. Specifically, the warning of not being able to open channel followed by exception (identified as operational-zookeeper-1.operational-zookeeper-nodes.oper.svc/10.42.0.34:3888). While we see operational-zookeeper-nodes is attached to port 3888, we do not see anything with the ClusterIP of 10.42.0.34. ClusterIP for the operational-zookeeper-nodes is set to None - is that correct?

![image](https://user-images.githubusercontent.com/86305586/179016122-cb145e7a-cf12-4e45-bdf1-dd07d1b2eab2.png)

When we change replicas on zookeeper (with the Kafka kind configuration) to 1, Kafka start running, as shown below:

![image](https://user-images.githubusercontent.com/86305586/179016675-b0d0d5eb-546d-4ab7-9f29-9a3bb636a3e0.png)

The following is the non-replicated YAML that currently works

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: operational
spec:
  kafka:
    version:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 31234
        type: loadbalancer
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.2"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
What is wrong with our replicated configuration?
