### DISCUSSION TITLE
Strimzi ArgoCD out of sync

### DISCUSSION THREAD

**Discussion by miroslavmasaryk3221** [strimzi/strimzi-kafka-operator#7074] [Q&A]
Hello,

We are using strimzi kafka operator along with argoCD.

ArgoCD  is reporting out of sync ClusterRoleBinding.

![image](https://user-images.githubusercontent.com/83809890/179770614-a1a5083a-eee6-4e2a-bcde-7dae9aadcdb7.png)

The desired manifest is empty 
![image](https://user-images.githubusercontent.com/83809890/179770821-4b4a0102-5e72-405a-baf1-19a3669f63da.png)

We are using onap-community  strimzi application chart.
https://github.com/onap/oom

We have tried to ignore it like this:
|
```
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: onap-strimzi
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-95"
spec:
  project: argo-management
  ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding"
    name: strimzi-onap-onap-strimzi-kafka-init
    jsonPointers:
    - /apiVersion
    - /kind
    - /metadata
    - /managedFields
    - /name
    - /resourceVersion
    - /uid
    - /roleRef
    - /subjects
  syncPolicy:
    syncOptions:
    - RespectIgnoreDifferences=true
    automated:
      prune: false
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: onap
  source:
    repoURL: <companyrepo>
    targetRevision: v10.0.0
    path: strimzi
    helm:
      valueFiles: 
      - ../onap/values-global.yaml
      - ../onap/values-strimzi.yaml
```
Any ideas?

Thanks
