### DISCUSSION TITLE
Very bad performance during consumer perf test

### DISCUSSION THREAD

**Discussion by rgarcia89** [strimzi/strimzi-kafka-operator#7082] [Q&A]
**Describe the bug**
We are currently reviewing the usage of this operator since we are currently running kafka locally installed on virtual machines.
So far the installation of the operator as well as the cluster has been very smooth. As next step we wanted to run some performance tests. When trying to do so we tried to run some consumer performance tests with `kafka-consumer-perf-test.sh`. Unfortunantely they all end up in a timeout. I am wondering what could be the reason for this bad performance and hope to find here some help.

**To Reproduce**
1. Deploy Operator with helm chart.
2. Deploy kafka cluster
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: sisr-cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions:
      "-Xmx": "2g"
      "-Xms": "2g"
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 80Gi
        class: default
        deleteClaim: true
  zookeeper:
    replicas: 3
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
```
3. Create a topic
`kubectl run kafka-producer -ti --image=quay.io/strimzi/kafka:0.29.0-kafka-3.2.0 --rm=true --restart=Never -- bin/kafka-topics.sh --bootstrap-server sisr-cluster-kafka-bootstrap:9092 --create --replication-factor 3 --partitions 100 --topic rgarcia`
4. Run a consumer perf test against the topic
`kubectl run kafka-consumer-perf -ti --image=quay.io/strimzi/kafka:0.29.0-kafka-3.2.0 --rm=true --restart=Never -- bin/kafka-consumer-perf-test.sh --bootstrap-server sisr-cluster-kafka-bootstrap:9092 --topic rgarcia --messages 100`
5. See error
You will see the request running into a timeout because the cluster did not complete it in time
```
kubectl run kafka-consumer-perf -ti --image=quay.io/strimzi/kafka:0.29.0-kafka-3.2.0 --rm=true --restart=Never -- bin/kafka-consumer-perf-test.sh --bootstrap-server sisr-cluster-kafka-bootstrap:9092 --topic rgarcia --messages 100
If you don't see a command prompt, try pressing enter.
start.time, end.time, data.consumed.in.MB, MB.sec, data.consumed.in.nMsg, nMsg.sec, rebalance.time.ms, fetch.time.ms, fetch.MB.sec, fetch.nMsg.sec
WARNING: Exiting before consuming the expected number of messages: timeout (10000 ms) exceeded. You can use the --timeout option to increase the timeout.
2022-07-20 14:37:31:309, 2022-07-20 14:37:41:426, 0.0000, 0.0000, 0, 0.0000, 3448, 6669, 0.0000, 0.0000
pod "kafka-consumer-perf" deleted
```

**Expected behavior**

**Environment (please complete the following information):**
 - Strimzi version: 0.29.0
 - Installation method: Helm chart
 - Kubernetes cluster: 1.23.8
 - Infrastructure: AKS
