### DISCUSSION TITLE
Kubernetes service for Kafka exporter is missing

### DISCUSSION THREAD

**Discussion by scottc-git** [strimzi/strimzi-kafka-operator#7084] [Q&A] [answered]
It seams Strimzi (at least the version that I am using - 0.27.1) does not create a Kubernetes service for the Prometheus exporter. As a result, the Prometheus does not discover the service and of course the Grafana dashboard is empty. 

- The exporter is actually created and it is collecting metrics (I port-forwarded to hit the metrics URL to verify this)
- I am using plain Prometheus helm chart (no Operator and no ServiceMonitor)
- I know Strimzi 0.17.0 created the service in question and my Prometheus scraped them. 
 
What would've changed? I noticed that `metrics:` became `metricsConfig:` and I believe the CRD implementation has changed since then. How can I have the service back and the necessary labels for Prometheus like `prometheus.io/scrape: true` 

#### kafka.yaml
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            host: bootstrap.override.me
            annotations:
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/ssl-passthrough: "true"
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          brokers:
            - broker: 0
              host: broker-0.override.me
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            - broker: 1
              host: broker-1.override.me
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
            - broker: 2
              host: broker-2.override.me
              annotations:
                kubernetes.io/ingress.class: nginx
                nginx.ingress.kubernetes.io/ssl-passthrough: "true"
                nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    authorization:
      type: simple
      superUsers:
        - CN=admin-user
        - CN=mm2-user
        - CN=sr-user
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
      allow.everyone.if.no.acl.found: "true"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - strimzi-kafka
                topologyKey: "kubernetes.io/hostname"
    rack:
      topologyKey: topology.kubernetes.io/zone
  zookeeper: # TODO consider removing this for kafka 2.8 or later
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: strimzi.io/name
                      operator: In
                      values:
                        - strimzi-zookeeper
                topologyKey: "kubernetes.io/hostname"
  entityOperator:
    topicOperator:
      logging:
        type: inline
        loggers:
          # The default INFO logging is very verbose, outputs many GB/day
          rootLogger.level: WARN
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    logging: debug
    # Allow `commonLabels` and `commonAnnotations` to be inserted by Kustomize.
    # Empty maps must be specified here because kafkaExporter is not created by default.
    template:
      deployment: { metadata: { labels: {}, annotations: {} } }
      pod: { metadata: { labels: {}, annotations: {} } }
      service: { metadata: { labels: {}, annotations: {} } }
```
