### DISCUSSION TITLE
Kafka Connect unable to create offset/config/status topics under the kafka cluster

### DISCUSSION THREAD

**Discussion by williamyeungforsure** [strimzi/strimzi-kafka-operator#7099] [Q&A]
Hi there,
I am deploying a Kafka Connector using the following configuration by Helm
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: {{ .Values.kafkaConnectCluster.name }}
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.8.0
  replicas: 1
  image: {{ include "containerImageWithTagOrDigest" (list $ . $imageParams) }}
  authentication:
    type: tls
    certificateAndKey:
      secretName: {{ .Values.kafkaUserProducer.name }}
      certificate: user.crt
      key: user.key
  tls:
    trustedCertificates:
      - secretName: {{ include "common.tplvalues.render" ( dict "value" .Values.kafka.clusterName "context" . ) }}-cluster-ca-cert
        certificate: ca.crt
  bootstrapServers: {{ include "common.tplvalues.render" ( dict "value" .Values.kafka.bootstrapServers "context" . ) | quote }}
  config:
    group.id: {{ .Values.kafkaConnectCluster.groupId }}
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    offset.storage.topic: {{ .Values.kafkaConnectCluster.internalTopics.offset }}
    config.storage.topic: {{ .Values.kafkaConnectCluster.internalTopics.config }}
    status.storage.topic: {{ .Values.kafkaConnectCluster.internalTopics.status }}
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    config.providers: directory
    config.providers.directory.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
  resources:
    requests:
      cpu: "1"
      memory: 2Gi
    limits:
      cpu: "2"
      memory: 2Gi
  jvmOptions:
    "-Xmx": "1g"
    "-Xms": "1g"
  template:
    pod:
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets.name }}
  externalConfiguration:
    volumes:
      - name: connector-config-postgresql-username
        secret:
          secretName: {{ .Values.postgres.usernameSecret }}
      - name: connector-config-postgresql-password
        secret:
          secretName: {{ .Values.postgres.passwordSecret }}
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: jmx-exporter-config-map
        key: kafka-connect
```

Earlier than that, I could those 3 topics, then I delete all kafka topics, clean up all the resources in my kubernetes cluster and redeploy the Kafkaconnect. However, after deploying the KafkaConnect, I could the Kafka Connect is working, but there's no offset/config/status topics under the kafka cluster when I enter `kubectl get kafkatopic`. I am wondering should I create those 3 topics manually? I thought they are created by KC automatically. Appreciate it if anyone could help.
