### DISCUSSION TITLE
Set the log.retention.bytes in broker.yml

### DISCUSSION THREAD

**Discussion by AydinChavez** [strimzi/strimzi-kafka-operator#7146] [Q&A] [answered]
Hi!

Simple question.

I am setting properties like following in the kafka.spec.config part within the strimzi broker.yaml: 

```
    config:
      auto.create.topics.enable: "true"
      log.retention.hours: 168 #1 week
      log.segment.bytes: 524288000 #500 MB
      log.retention.bytes: 1073741824 #1GB
```
and apply it to k8s.

But when I do exec into one of my kafka broker pod I see that the value in the server.properties file is still commented out (/opt/kafka/server.properties):

```
sh-4.4$ grep log.retention.bytes server.properties 
# segments drop below log.retention.bytes. Functions independently of log.retention.hours.
#log.retention.bytes=1073741824

```

Am I missing something here?
