### DISCUSSION TITLE
Enable Client authentication as well as SASL/SCRAM for ACL in standalone KafkaConnect Cluster

### DISCUSSION THREAD

**Discussion by ee07dazn** [strimzi/strimzi-kafka-operator#7173] [Q&A] [answered]
Hello 

My Kafka cluster (external and not setup via Strimzi) has mTLS enabled along with SASL/SCRAM256 to provide ACL. Can I configure Strimzi's KafkaConnect for this ? 
I have been looking at the document `[here](https://strimzi.io/docs/operators/latest/configuring.html#proc-configuring-kafka-connect-user-authorization-str:~:text=2.2.1.%20Configuring%20Kafka%20Connect)` but I can't find a way to specify both in here. 

My Kafka cluster is outside strimzi's setup hence using the KafkaUser is probably not possible?
Could you please help/guide ?

My connect yaml looks like

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 1
  bootstrapServers: "0.xx:30827,1.xx:30827,2.xx:30827"
  authentication:
    type: tls
    certificateAndKey: 
      secretName: my-connect-secret
      certificate: client-debug.crt
      key: client-debug.key
  config:
    group.id: strimzi-connect-cluster
    offset.storage.topic: strimzi-connect-cluster-offsets
    config.storage.topic: strimzi-connect-cluster-configs
    status.storage.topic: strimzi-connect-cluster-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "DEBUG"
```
I am thinking along the above lines, because i am getting authentication error
