### DISCUSSION TITLE
Control assignment with Multiple KafkaConnect objects

### DISCUSSION THREAD

**Discussion by andreas-ibm** [strimzi/strimzi-kafka-operator#7188] [Q&A] [answered]
I have a "stable" KafkaConnect cluster with a single KafkaConnector pointing to a MySQL database.
I wanted to build a second cluster to connect to an Oracle database, which I did in a separate cluster since I didn't want to upset the first (see separate discussion on the journey to getting that working :-) ).
So now I have two clusters, one mysql and one oracle.  I created a second KafkaConnector object and watched my logs to see something happening.
As far as I can tell, the mysql cluster has picked up the second connector and failed since it doesn't have the class for Oracle it fails.  How can I address the connector to the second cluster?

**Comment by scholzj** [comment, marked as answer]
Please make sure you properly configure the topics names of the KafkaConnect clusters: https://strimzi.io/docs/operators/latest/full/deploying.html#con-kafka-connect-multiple-instances-str ... without that, they will act as a single cluster because they will link with each other through the topics.

**Reply by andreas-ibm** [reply]
Thanks, I had indeed made that mistake.
But fixing it doesn't seem to have fixed my problem. I can still see my MySQL cluster erroring whilst my Oracle cluster stays silent.
Ahhhhhh, in copying and pasting my entire config in here I noticed the metadata.labels.strimzi.io/cluster setting was pointing to the mysql cluster!
So I fixed it, deleted the failing KafkaConnector and created the new one, and *nothing* in either logs now!  I can see the the new kafka topics for the cluster in the list, but not the topics for the connector.
Debugging stuff in the cloud is HARD man! (I appreciate the help!)

**Reply by andreas-ibm** [reply]
```
Status:
  Conditions:
    Last Transition Time:  2022-08-15T16:03:50.760744Z
    Message:               PUT /connectors/debezium-oracle-connector/config returned 400 (Bad Request): Connector configuration is invalid and contains the following 1 error(s):
A value is required
You can also find the above list of errors at the endpoint `/connector-plugins/{connectorType}/config/validate`
    Reason:             ConnectRestException
    Status:             True
    Type:               NotReady
  Observed Generation:  1
  Tasks Max:            1
  Topics:
```
So I've written *something* wrong!
The config is as follows:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-oracle-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: debezium-oracle-cluster
spec:
  class: io.debezium.connector.oracle.OracleConnector
  tasksMax: 1
  config:
    database.hostname: sidb.oracle
    database.port: 3306
    database.include.list: XE
    database.server.name: oracle
    database.history.kafka.bootstrap.servers: my-cluster-kafka-bootstrap:9092
    database.history.kafka.topic: schema-changes.xe
```
(super secret password omitted)
