### DISCUSSION TITLE
kafka dashboard empty due to missing a key metrics

### DISCUSSION THREAD

**Discussion by scottc-git** [strimzi/strimzi-kafka-operator#7194] [Q&A]
What could be the reason the `kafka_server_replicamanager_leadercount` metric is missing in Prometheus?  That metric is critical to render the drop down menus in the Strimzi Kafka dashboard.   Since it's missing the dashboard is currently empty.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    jmxOptions:
      authentication:
        type: "password"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics*
          key: kafka-metrics-config.yml

  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    logging: debug

  jmxTrans^:
    outputDefinitions:
      - outputType: "com.googlecode.jmxtrans.model.output.StdOutWriter"
        name: "standardOut"
      - outputType: "com.googlecode.jmxtrans.model.output.GraphiteOutputWriter"
        host: "mylogstash.com"
        port: 31028
        flushDelayInSeconds: 5
        name: "logstash"
    kafkaQueries:
      - targetMBean: "kafka.server:type=BrokerTopicMetrics,name=*"
        attributes:  ["Count"]
        outputs: ["standardOut"]
    
```

*: The kafka-metrics config map is exactly as in https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/kafka-metrics.yaml

^:  I enabled jmxTrans but I believe it is irrelevant to the issue. 

**Strimzi: 0.27.1
Kafka: 2.8**
