### DISCUSSION TITLE
Slow metric endpoint for MirrorMaker2

### DISCUSSION THREAD

**Discussion by kushmangal** [strimzi/strimzi-kafka-operator#7197] [Q&A]
I was facing issues with the slow metrics endpoint via JMX Exporter for MirrorMaker 2. Has anyone else faced the same issue?
I am using following metric-config.yml

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: mirror-maker-2-metrics
  labels:
    app: strimzi
data:
  metrics-config.yml: |
    # See https://github.com/prometheus/jmx_exporter for more info about JMX Prometheus Exporter metrics
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    rules:
    #kafka.connect:type=app-info,client-id="{clientid}"
    #kafka.consumer:type=app-info,client-id="{clientid}"
    #kafka.producer:type=app-info,client-id="{clientid}"
    - pattern: 'kafka.(.+)<type=app-info, client-id=(.+)><>start-time-ms'
      name: kafka_$1_start_time_seconds
      labels:
        clientId: "$2"
      help: "Kafka $1 JMX metric start time seconds"
      type: GAUGE
      valueFactor: 0.001
    - pattern: 'kafka.(.+)<type=app-info, client-id=(.+)><>(commit-id|version): (.+)'
      name: kafka_$1_$3_info
      value: 1
      labels:
        clientId: "$2"
        $3: "$4"
      help: "Kafka $1 JMX metric info version and commit-id"
      type: GAUGE
    #kafka.producer:type=producer-topic-metrics,client-id="{clientid}",topic="{topic}"", partition="{partition}"
    #kafka.consumer:type=consumer-fetch-manager-metrics,client-id="{clientid}",topic="{topic}"", partition="{partition}"
    - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), topic=(.+), partition=(.+)><>(.+-total|compression-rate|.+-avg|.+-replica|.+-lag|.+-lead)
      name: kafka_$2_$6
      labels:
        clientId: "$3"
        topic: "$4"
        partition: "$5"
      help: "Kafka $1 JMX metric type $2"
      type: GAUGE
    #kafka.producer:type=producer-topic-metrics,client-id="{clientid}",topic="{topic}"
    #kafka.consumer:type=consumer-fetch-manager-metrics,client-id="{clientid}",topic="{topic}"", partition="{partition}"
    - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), topic=(.+)><>(.+-total|compression-rate|.+-avg)
      name: kafka_$2_$5
      labels:
        clientId: "$3"
        topic: "$4"
      help: "Kafka $1 JMX metric type $2"
      type: GAUGE
    #kafka.connect:type=connect-node-metrics,client-id="{clientid}",node-id="{nodeid}"
    #kafka.consumer:type=consumer-node-metrics,client-id=consumer-1,node-id="{nodeid}"
    - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.+), node-id=(.+)><>(.+-total|.+-avg)
      name: kafka_$2_$5
      labels:
        clientId: "$3"
        nodeId: "$4"
      help: "Kafka $1 JMX metric type $2"
      type: UNTYPED
    #kafka.connect:type=kafka-metrics-count,client-id="{clientid}"
    #kafka.consumer:type=consumer-fetch-manager-metrics,client-id="{clientid}"
    #kafka.consumer:type=consumer-coordinator-metrics,client-id="{clientid}"
    #kafka.consumer:type=consumer-metrics,client-id="{clientid}"
    - pattern: kafka.(.+)<type=(.+)-metrics, client-id=(.*)><>(.+-total|.+-avg|.+-bytes|.+-count|.+-ratio|.+-age|.+-flight|.+-threads|.+-connectors|.+-tasks|.+-ago)
      name: kafka_$2_$4
      labels:
        clientId: "$3"
      help: "Kafka $1 JMX metric type $2"
      type: GAUGE
    #kafka.connect:type=connector-task-metrics,connector="{connector}",task="{task}<> status"
    - pattern: 'kafka.connect<type=connector-task-metrics, connector=(.+), task=(.+)><>status: ([a-z-]+)'
      name: kafka_connect_connector_status
      value: 1
      labels:
        connector: "$1"
        task: "$2"
        status: "$3"
      help: "Kafka Connect JMX Connector status"
      type: GAUGE
    #kafka.connect:type=task-error-metrics,connector="{connector}",task="{task}"
    #kafka.connect:type=source-task-metrics,connector="{connector}",task="{task}"
    #kafka.connect:type=sink-task-metrics,connector="{connector}",task="{task}"
    #kafka.connect:type=connector-task-metrics,connector="{connector}",task="{task}"
    - pattern: kafka.connect<type=(.+)-metrics, connector=(.+), task=(.+)><>(.+-total|.+-count|.+-ms|.+-ratio|.+-avg|.+-failures|.+-requests|.+-timestamp|.+-logged|.+-errors|.+-retries|.+-skipped)
      name: kafka_connect_$1_$4
      labels:
        connector: "$2"
        task: "$3"
      help: "Kafka Connect JMX metric type $1"
      type: GAUGE
    #kafka.connect:type=connector-metrics,connector="{connector}"
    #kafka.connect:type=connect-worker-metrics,connector="{connector}"
    - pattern: kafka.connect<type=connect-worker-metrics, connector=(.+)><>([a-z-]+)
      name: kafka_connect_worker_$2
      labels:
        connector: "$1"
      help: "Kafka Connect JMX metric $1"
      type: GAUGE
    #kafka.connect:type=connect-worker-metrics
    - pattern: kafka.connect<type=connect-worker-metrics><>([a-z-]+)
      name: kafka_connect_worker_$1
      help: "Kafka Connect JMX metric worker"
      type: GAUGE
    #kafka.connect:type=connect-worker-rebalance-metrics
    - pattern: kafka.connect<type=connect-worker-rebalance-metrics><>([a-z-]+)
      name: kafka_connect_worker_rebalance_$1
      help: "Kafka Connect JMX metric rebalance information"
      type: GAUGE
    #kafka.connect:type=MirrorSourceConnector
    - pattern: kafka.connect.mirror<type=MirrorSourceConnector, target=(.+), topic=(.+), partition=(.+)><>([a-z-_]+)
      name: kafka_connect_mirror_mirrorsourceconnector_$4
      labels:
        target: "$1"
        topic: "$2"
        partition: "$3"
      help: "Kafka Mirror Maker 2 Source Connector metrics"
      type: GAUGE
    #kafka.connect:type=MirrorCheckpointConnector
    - pattern: kafka.connect.mirror<type=MirrorCheckpointConnector, source=(.+), target=(.+), group=(.+), topic=(.+), partition=(\d+)><>([a-z-_]+)
      name: kafka_connect_mirror_checkpoint_connector_$6
      labels:
        source: "$1"
        target: "$2"
        group: "$3"
        topic: "$4"
        partition: "$5"
      help: "Kafka Mirror Maker 2 Checkpoint Connector metrics"
      type: GAUGE
```

I was getting metrics scrape time as around 20-30s. Sometimes even more. Is it common and any idea how it can be optimized?

**Comment by scholzj** [comment]
I haven't seen this, but I think you should share more information ... your Mirror Maker configuration, how much load does it handle etc. Without that, it will be hard for anyone to comment on it.

**Reply by kushmangal** [reply]
Hi,
The configuration used was:
```
# Source: mirror-maker-2/templates/mm2.yml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: source-kafka-target-kafka
  labels:
    mirror-name: source-kafka-target-kafka
    helm.sh/chart: mirror-maker-2-0.1.1
    app.kubernetes.io/name: mirror-maker-2
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "3.2.1"
    app.kubernetes.io/managed-by: Helm
spec:
  version: 3.2.1
  replicas: 5
  connectCluster: target-kafka
  clusters:
  - alias: "source-kafka"
    bootstrapServers: "source-kafka:9092"
  - alias: "target-kafka"
    bootstrapServers: "target-kafka:9092"
    config:
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "source-kafka"
    targetCluster: "target-kafka"
    sourceConnector:
      tasksMax: 100
      config:
        consumer.auto.offset.reset: latest
        offset-syncs.topic.location: target
        refresh.topics.interval.seconds: 600
        replication.factor: 3
        replication.policy.class: org.apache.kafka.connect.mirror.IdentityReplicationPolicy
        sync.topic.acls.enabled: false
        sync.topic.configs.enabled: true
    heartbeatConnector:
      config:
        consumer.auto.offset.reset: latest
        emit.heartbeats.enabled: true
        emit.heartbeats.interval.seconds: 1
        heartbeats.topic.replication.factor: 3
    checkpointConnector:
      tasksMax: 30
      config:
        emit.checkpoints.enabled: true
        emit.checkpoints.interval.seconds: 60
        offset-syncs.topic.location: target
        refresh.groups.enabled: true
        refresh.groups.interval.seconds: 600
        replication.policy.class: org.apache.kafka.connect.mirror.IdentityReplicationPolicy
        sync.group.offsets.enabled: "true"
        sync.group.offsets.interval.seconds: 600
    topicsPattern: ".*"
    topicsExcludePattern: ".*"
    groupsPattern: ""
    groupsExcludePattern: ""
  resources:
    limits:
      cpu: 4000m
      memory: 10Gi
    requests:
      cpu: 4000m
      memory: 8Gi
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: test-mirror-maker-2-metrics-conf
        key: metrics-config.yml
```
Here I am using 0.31.0 version of strimzi operator
Metrics configuration is as defined in the question. 

**With respect to load**
Record Rate: 1000-1500
Byte rate: 2.5-3.5 MB/s
Total Topic count: 1670
Total Partition count: 7065
Total Consumer group count: 160
Total consumer group partition count: 4200
Topics with consumer group: 150
