### DISCUSSION TITLE
mm2 sourceConnector config items not applied to mirrored topics

### DISCUSSION THREAD

**Discussion by scottc-git** [strimzi/strimzi-kafka-operator#7224] [Q&A]
I have a few source topics that I've been trying to mirror to Strimzi kafka.  Since mm2 did not create topics in the target cluster exactly the same as the source, I've added a few Kafka topic config items to the sourceConnector.  And it did create the topics with those configs, however, some time later somebody (the mirrorMaker? Entity|Topic Operator?) sets those back to the Kafka (broker) default!  Saw this multiple times.   

To be specific, I need to ensure at least the following 3 items are applied to the target topics: replication.factor(3), min.insync.replicas(2) and the message.max.bytes (10M), however, they are set to 3, 1(!), and 10M, respectively.   I've also tried defining KafkaTopic yaml resources myself for these topics (I didn't need to) just to ensure I get the correct topic configurations but to no avail.   

Here's my simplified MM2 config. 
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: strimzi
spec:
  version: 2.8.0
  replicas: 1
  image: example.com/dev:strimzi-kafka-connect-extended-strimzi-0-27-1-32838c44-62188
  clusters:
    - alias: example-ref
    - alias: source
    - alias: strimzi
      bootstrapServers: strimzi-kafka-bootstrap:9093
      config:
        group.id: strimzi-mm2
        offset.storage.topic: strimzi-mm2-offset
        config.storage.topic: strimzi-mm2-config
        status.storage.topic: strimzi-mm2-status
        offset.storage.cleanup.policy: compact
        config.storage.cleanup.policy: compact
        status.storage.cleanup.policy: compact
        offset.storage.replication.factor: 1
        config.storage.replication.factor: 1
        status.storage.replication.factor: 1

  connectCluster: strimzi

  mirrors:
    - sourceCluster: source
      targetCluster: strimzi
      topicsPattern: >-
        topic\.foo\.v2,
        topic\.bar\.v2
      topicsExcludePattern: >-
        __consumer_offsets,
        _schemas
      groupsPattern: "do-not-mirror-groups"
      sourceConnector:
        tasksMax: 10
        config:
          replication.factor: 3             #   <==   #1. 
          min.insync.replicas: 2            #   <==  #2. NOT APPLIED
          message.max.bytes: 10485760       #   <== #3. 
          
          # NOTE:  Actually #1 and #3 are applied because I set these values as broker default.
          
          offset-syncs.topic.replication.factor: 1
          
          sync.topic.acls.enabled: "false"
          replication.policy.separator: ""
          replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"

          transforms: FilterOldMessages, AvroSchemaTransfer
          transforms.FilterOldMessages.type: my.kafka.ConnectFilterTimeRange
          transforms.FilterOldMessages.start.time: ${env:INPUT_MIRROR_START_TIME}
          transforms.AvroSchemaTransfer.type: cricket.jmoore.kafka.connect.transforms.SchemaRegistryTransfer
          transforms.AvroSchemaTransfer.transfer.message.keys: "false"
          transforms.AvroSchemaTransfer.src.schema.registry.url: http://override.me:8081
          transforms.AvroSchemaTransfer.dest.schema.registry.url: http://schema-registry-client:8081
          transforms.AvroSchemaTransfer.schema.capacity: 5000
```          

Am I using right config items at right place?  Maybe the SMTs are messing up things? Probably not because I do not see the overridden items in /tmp/strimzi-connect.properties.     

**Question**:  How am I supposed to set `min.insync.replicas: 2` and how can I ensure these are not reset to Kafka default?

Thanks for the help in advance.
