### DISCUSSION TITLE
error upgrading Kafka CRDs t0 0.29 - Invalid value: "v1beta": must appear in spec.versions

### DISCUSSION THREAD

**Discussion by 282ori** [strimzi/strimzi-kafka-operator#7226] [Q&A]
Hi,
I'm trying to upgrade the Kafka CRD's from 0.22.1 to 0.29.
when I run the oc replace command there's an exception:

CustomResourceDefinition.apiextensions.k8s.io "kafkas.kafka.strimzi.io" is invalid: status.storedVersions[0]:
Invalid value: "v1beta1": must appear in spec.versions

I receive this error when I try to replace the CRDs: kafka, kafka connect, kafkaconnector, kafkamirrormaker,kafkarebalance etc.
The only CRDs I succeeded replacing are KafkaTopic and KafkaUser.
for some of the CRDs instead of 'invalid value: v1beta1' I see 'invalid value: v1alpha1'

Does anyone know what could be the problem?
Thanks

**Comment by scholzj** [comment]
Please follow the CRD upgrade procedure. It is linked from the release page and from the docs.

**Reply by 282ori** [reply]
Well I hope I did, I alse tried to run the api-conversion script and got the errors:
Changing stored version in all CRDs to v1beta2:
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing PATCH at:
https://{kube-api}/apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/kafkamirrormakers.kafka.strimzi.io. Message: CustomResourceDefinition.apiextensions.k8s.io "kafkamirrormakers.kafka.strimzi.io" is invalid: spec.versions: Invalid value: 
[]apiextensions.CustomResourceDefinitionVersion{apiextensions.CustomResourceDefinitionVersion{
Name: "v1beta1", Served: true, Storage: false, Deprecated: false...................................

for all kafka CRDs

**Reply by scholzj** [reply]
The error suggests you didn't - or at least not successfully.

**Reply by 282ori** [reply]
What could cause this problem?
I tried running this command in a new kubernetes environment WITHOUT any kafka's CRs and the crd-upgrade command does not work and produces the error I mentioned.
Beyond that I don't know what else I can do, any ideas?

**Reply by scholzj** [reply]
You are probably not following the procedure. You need to follow it step by step including the versions which are used.

**Reply by 282ori** [reply]
Which versions are you reffering to?
I have CRDs in version 0.22.1 and trying to upgrade to 0.29.0.
Should I upgrade first to other CRDs version?
The procedure you mentioned includes only running the 'api-conversion.sh crd-upgrade' command (the cr command is not relevant because I don't have any existing CRs).

**Reply by scholzj** [reply]
But it is procedure which is part of the upgrade from 0.22 to 0.23. So you have to use the corresponding CRDs from these versions. The 0.29 CRDs can be installed only after you successfully converted the CRDs.

**Reply by 282ori** [reply]
In the realse notes in upgrading to 0.23 writing the following:
CRD Upgrades
!!! IMPORTANT !!!

This release supports only the API version v1beta2 and CRD version apiextensions.k8s.io/v1. Migration to v1beta2 needs to be completed for all Strimzi CRDs and CRs **before** the upgrade to 0.23 is done!

From that I understand that the script must be run _before_ upgrading the CRDs to 0.23.
Are you claiming that I need to upgrade the CRDs to 0.23 and only then run the api-conversion script?

**Reply by scholzj** [reply]
No, you need to run it on the old 0.22 CRDs. If it doe snot work, you do not have the 0.22 CRDs.

**Reply by 282ori** [reply]
Is it important if I have 0.22.0 or 0.22.1 CRDs when I try to upgrade?

**Reply by scholzj** [reply]
No, that should not matter. Any 0.22 CRDs should do.

**Reply by 282ori** [reply]
Well I have just taken the CRDs of 0.22.1 located in the 'install' from the github (the 'realse.version' file indicated '0.22.1')
and performed 'kubectl apply' for them.
While they exist, when I run the 'api-conversion.sh crd-upgrade' command I see the error with the stored.versions I mentioned,
so I can surely guarantee you that I do have the CRDs of 0.22.1 and perform the script action on them.
How does it make sense that it does not work?

**Reply by scholzj** [reply]
You should you `kubectl replace` and not `kubectl apply` to avoid any possibility of bad patching and making sure you actually have the right CRDs. You also never shared the full logs, so it is not really clear what error are you talking about.

**Reply by scholzj** [reply]
PS: Use the CRDs from the release ZIPs.

**Reply by 282ori** [reply]
well I meant to the first installation of the CRDs, It is pointless to 'kubectl replace' before the script would run successfully.
I also saw that there are serveral versions of the api-conversion tool, does it matter which version of it I am running?

**Reply by scholzj** [reply]
> It is pointless to 'kubectl replace' before the script would run successfully

`kubectl apply` is known to cause issues during patching of complex resources. The patch is sometimes simply wrong. `kubectl replace` is the command which avoid the risk of bad patch and makes sure the CRD is as it is in the YAML file. So it is not pointless. Given your current state, you should download the release ZIP, use `kubectl replace` to make sure you have the right CRDs from 0.22.0 or 0.22.1.

> I also saw that there are serveral versions of the api-conversion tool, does it matter which version of it I am running?

The last version - from 0.24 - has IIRC some bugfix for converting CR with some special configuration. It was some niche thing IIRC, but you might be best of to use that version.

**Reply by javadnasrolahi** [reply]
Hi
I think we have the same problem. 
we upgraded strimzi from version 0.19.0 to 0.22.1 directly. then we changed all Kafka resources from v1beta1 to v1beta2 as it was said in the [document](https://strimzi.io/docs/operators/0.22.1/full/deploying.html#proc-upgrade-kafka-resources-str) without any problem. (we didn't use API conversion tool)

then we went to upgrade strimzi from version 0.22.1 to version 0.25.0. first, we upgrade the operator with `helm upgrade` without any problem, then we wanted to upgrade CRDs so we run ` kubectl replace -f strimzi-kafka-operator-0.25.0/crds/` but we got this err: 
```
customresourcedefinition.apiextensions.k8s.io/kafkatopics.kafka.strimzi.io replaced
customresourcedefinition.apiextensions.k8s.io/kafkausers.kafka.strimzi.io replaced
Error from server (Invalid): error when replacing "strimzi-kafka-operator-0.25.0/crds/040-Crd-kafka.yaml": CustomResourceDefinition.apiextensions.k8s.io "kafkas.kafka.strimzi.io" is invalid: status.storedVersions[0]: Invalid value: "v1beta1": must appear in spec.versions
Error from server (Invalid): error when replacing "strimzi-kafka-operator-0.25.0/crds/041-Crd-kafkaconnect.yaml": CustomResourceDefinition.apiextensions.k8s.io "kafkaconnects.kafka.strimzi.io" is invalid: status.storedVersions[0]: Invalid value: "v1beta1": must appear in spec.versions
Error from server (Invalid): error when replacing "strimzi-kafka-operator-0.25.0/crds/045-Crd-kafkamirrormaker.yaml": CustomResourceDefinition.apiextensions.k8s.io "kafkamirrormakers.kafka.strimzi.io" is invalid: status.storedVersions[0]: Invalid value: "v1beta1": must appear in spec.versions
Error from server (Invalid): error when replacing "strimzi-kafka-operator-0.25.0/crds/046-Crd-kafkabridge.yaml": CustomResourceDefinition.apiextensions.k8s.io "kafkabridges.kafka.strimzi.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
Error from server (Invalid): error when replacing "strimzi-kafka-operator-0.25.0/crds/047-Crd-kafkaconnector.yaml": CustomResourceDefinition.apiextensions.k8s.io "kafkaconnectors.kafka.strimzi.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
Error from server (Invalid): error when replacing "strimzi-kafka-operator-0.25.0/crds/048-Crd-kafkamirrormaker2.yaml": CustomResourceDefinition.apiextensions.k8s.io "kafkamirrormaker2s.kafka.strimzi.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
Error from server (Invalid): error when replacing "strimzi-kafka-operator-0.25.0/crds/049-Crd-kafkarebalance.yaml": CustomResourceDefinition.apiextensions.k8s.io "kafkarebalances.kafka.strimzi.io" is invalid: status.storedVersions[0]: Invalid value: "v1alpha1": must appear in spec.versions
```

**Reply by scholzj** [reply]
Have you done the conversion using the conversion tool as described in the docs? It does not seem so from the error message.

**Reply by javadnasrolahi** [reply]
I think we did (maybe we didn't do a part correctly)
we changed all v1beta1 resources. here is our manifest: 
```
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  kafka:
    version: 2.7.0
    replicas: 5
    template:
    jvmOptions:
      -Xms: 7000m
      -Xmx: 7000m
      javaSystemProperties:
        - name: log4j2.formatMsgNoLookups
          value: "true"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    config:
      log.message.format.version: "2.7"
    storage:
      type: persistent-claim
      size: 23Gi
      deleteClaim: false
      class: "lvm-ext4"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yaml
  zookeeper:
    replicas: 3
    jvmOptions:
      -Xms: 2024m
      -Xmx: 2024m
      javaSystemProperties:
        - name: log4j2.formatMsgNoLookups
          value: "true"
    template:
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    storage:
      type: persistent-claim
      size: 15Gi
      deleteClaim: false
      class: "lvm-ext4"
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: zookeeper-metrics
          key: zookeeper-metrics-config.yaml

  kafkaExporter:
    #image: "danielqsj/kafka-exporter:v1.3.1"
    topicRegex: ".*."
    groupRegex: ".*."
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
      limits:
        cpu: 500m
        memory: 128Mi
    logging: "warn"
    enableSaramaLogging: true
  entityOperator:
    topicOperator:
      jvmOptions:
        javaSystemProperties:
          - name: log4j2.formatMsgNoLookups
            value: "true"
    userOperator:
      jvmOptions:
        javaSystemProperties:
          - name: log4j2.formatMsgNoLookups
            value: "true"

```
