### DISCUSSION TITLE
Accessing KafkaConnect REST API from outside K8s via Ingress resource

### DISCUSSION THREAD

**Discussion by ee07dazn** [strimzi/strimzi-kafka-operator#7248] [Q&A] [answered]
Hi 
I have a KC cluster setup and i can port forward the *-connect-api service and run/check @ localhost:8083 (so far so good). I have setup an ingress resource (in GKE via HTTPS load balancer), which points to two backends - one being the prometheus UI (works all good) and other being the kafka connect rest api (backend service failing). I just want to expose the rest api for read only purposes...I will still be using the KafkaConnector CRD for setting up any connector configuration. 

I have been looking at this issue and specifically your comments [here](https://github.com/strimzi/strimzi-kafka-operator/issues/3201#issuecomment-644439336) .

Could you please help elaborate? I believe I still need a custom NetworkPolicy to be defined but I am little confused about the `podSelector` bit of it. Currently, I am not trying to run an pod like kafka-connect-ui from landoop etc.. to connect to this service. Its purely exposing the rest api @ https://my-domain.com/connect.

Is there something specific from my ingress resource that i need to tie up to this network policy ?
Apologies, if it seems like a silly question but i am still learning a lot here so hope you don't mind.

**Comment by scholzj** [comment, marked as answer]
I think you will need a custom policy, yes. The Ingress will normally run some kind of proxy (e.g. Nginx) which will be forwarding the requests to the Connect service / pods. So I think you need to enabled in the custom network policy the connections from this proxy. For example if you use the Kubernetes Nginx Ingress, I believe that this would be the `nginx-ingress-controller` pod (the actual name mightdiffer depending on installation I guess). With other Ingress controllers, it will be similar, jst some different pod.

**Reply by ee07dazn** [reply]
Thanks for this. So in my case, its a GKE Ingress controller, and unfortunately, it doesn't create any pods in the cluster...Probably GCP handles this behind the scene. However, it does create HTTP(S) proxy as per doc. 
![Screenshot 2022-08-29 at 17 43 05](https://user-images.githubusercontent.com/46483973/187251699-dba1280a-ded4-48bb-a463-378f66f45420.png)

I just tried allowing all ingress traffic to my connect pods

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafkaconnect-ui
  namespace: strimzi
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      strimzi.io/cluster: kafkaconnect-cluster
      strimzi.io/kind: KafkaConnect
      strimzi.io/name: kafkaconnect-cluster-connect
  policyTypes:
  - Ingress 

```
My backend is up as in not failing but now I get `{"error_code":404,"message":"HTTP 404 Not Found"}` when hitting `https://my-domain.com/connect`

Is there a contradiction with the networkpolicy that gets created OOB in connect cluster, with this one, when i enable all traffic ?
