### DISCUSSION TITLE
Kafka ingress/contour not create service and ingress resources

### DISCUSSION THREAD

**Discussion by sattha-p** [strimzi/strimzi-kafka-operator#7280] [Q&A]
I'm facing an issue service and ingress not create after apply "ingress listeners".
I follow this [document](https://strimzi.io/blog/2019/05/23/accessing-kafka-part-5/).

K8S Tanzu
Ingress controller: Contour/Envoy

I'm not sure is this because I'm not use the Ingress Nginx or not? However, Ingress Contour also support [TLS Pass through](https://projectcontour.io/docs/v1.22.0/config/tls-termination/#tls-session-passthrough). Is there anything I can do with Strimzi and Ingress Contour

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-strimzi
  namespace: kafka-dev
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    resources:
      requests:
        memory: "2Gi"
        cpu: 0.5
      limits:
        memory: "2Gi"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: ingress
        tls: true
        configuration:
          bootstrap:
            host: kafka.dev.store.global.abc.org
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka.dev.store.global.abc.org.
              external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
          - broker: 0
            host: kafka-broker-0.dev.store.global.abc.org
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-0.dev.store.global.abc.org.
              external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 1
            host: kafka-broker-1.dev.store.global.abc.org
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-1.dev.store.global.abc.org.
              external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 2
            host: kafka-broker-2.dev.store.global.abc.org
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-2.dev.store.global.abc.org.
              external-dns.alpha.kubernetes.io/ttl: "60"
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
    storage:
      type: persistent-claim
      class: cpt-vsphere-with-tanzu-storage-policy
      size: 50G
      deleteClaim: false
    template:
      pod:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution: 
            - weight: 1
              preference:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - kafka 

  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: "1Gi"
        cpu: 0.3
      limits:
        memory: "1Gi"
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    storage:
      type: persistent-claim
      size: 50G
      class: cpt-vsphere-with-tanzu-storage-policy
      deleteClaim: false
    template:
      pod:
        affinity:
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution: 
            - weight: 1
              preference:
                matchExpressions:
                - key: service
                  operator: In
                  values:
                  - kafka

  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "0.2"
        limits:
          memory: 256Mi
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "0.2"
        limits:
          memory: 512Mi

  kafkaExporter:
    resources:
      requests:
        memory: 256Mi
        cpu: "0.2"
      limits:
        memory: 256Mi

```
