### DISCUSSION TITLE
SSL authentication failing when trying to run consumer script.

### DISCUSSION THREAD

**Discussion by inthemistr1** [strimzi/strimzi-kafka-operator#7303] [Q&A]
I have been following the documentation at https://strimzi.io/docs/operators/in-development/deploying.html#setup-external-clients-str

I could already produce and consume from a topic using internal listener, I am trying to replicate the same with an external listener. I created a kafka cluster, topic and user all with the Authentication: simple setup and I have this client-ssl.properties file: 

```
bootstrap.servers=<external ip>:9094
security.protocol=SSL
ssl.truststore.location=ca.p12
ssl.truststore.password=<password>
ssl.truststore.type=PKCS12
ssl.keystore.location=user.p12
ssl.keystore.password= <password>
ssl.keystore.type=PKCS12
```

The connection works but when I try to produce on the topic I get the following:

[2022-09-09 19:06:19,543] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 7 : {my-topic=TOPIC_AUTHORIZATION_FAILED} (org.apache.kafka.clients.NetworkClient)
[2022-09-09 19:06:19,544] ERROR [Producer clientId=console-producer] Topic authorization failed for topics [my-topic] (org.apache.kafka.clients.Metadata)
[2022-09-09 19:06:19,544] ERROR Error when sending message to topic my-topic with key: null, value: 0 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [my-topic]

The pod logs for an attempted authorization are the following: 

2022-09-09 19:54:51,696 INFO Principal = User:ANONYMOUS is Denied Operation = Describe from host = 10.244.1.1 on resource = Topic:LITERAL:my-topic for request = Metadata with resourceRefCount = 1 (kafka.authorizer.logger) [data-plane-kafka-request-handler-7]

This is the Kafka CR YAML: 

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: external-listener
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        type: internal
        port: 9093
        tls: false
        authentication:
          type: tls
      - name: external
        type: loadbalancer
        tls: true
        port: 9094
        authentication:
          type: tls
    config:
      preferredNodePortAddressType: InternalDNS
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    authorization:
      type: simple
      superUsers:
        - my-user
    storage:
      type: ephemeral
      volumes:
      - id: 0
        class: managed-premium
        type: persistent-claim
        size: 64Gi
        deleteClaim: false

  zookeeper:
      replicas: 1
      storage:
        type: persistent-claim
        class: managed-premium
        size: 32Gi
        deleteClaim: false
    entityOperator:
      topicOperator: {}
      userOperator: {}
```

**Comment by scholzj** [comment]
These seem like two separate errors -> one is about authorization and one is about authentication. So these might not be the same client - they might not correspond to each other.

**Reply by inthemistr1** [reply]
I'm not following, how would they be different clients? Different versions?

**Reply by scholzj** [reply]
Because it looks like a different errors? One says authorization failed and one is about TLS handshake failing.

**Reply by inthemistr1** [reply]
No, I agree, but the log corresponds to that connection, so could I fix using 2 different clients? Different Kafka versions or something like that?

**Reply by scholzj** [reply]
But why do you think these are related? The times are completely different and they do not correspond to each other.

**Reply by inthemistr1** [reply]
Ah sorry, that was the wrong log, will edit the first post, these are the correct logs: 

Producer error: 

[2022-09-09 19:54:51,716] WARN [Producer clientId=console-producer] Error while fetching metadata with correlation id 4 : {my-topic=TOPIC_AUTHORIZATION_FAILED} (org.apache.kafka.clients.NetworkClient)
[2022-09-09 19:54:51,720] ERROR [Producer clientId=console-producer] Topic authorization failed for topics [my-topic] (org.apache.kafka.clients.Metadata)
[2022-09-09 19:54:51,724] ERROR Error when sending message to topic my-topic with key: null, value: 1 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [my-topic]

Pod log: 

2022-09-09 19:54:51,696 INFO Principal = User:ANONYMOUS is Denied Operation = Describe from host = 10.244.1.1 on resource = Topic:LITERAL:my-topic for request = Metadata with resourceRefCount = 1 (kafka.authorizer.logger) [data-plane-kafka-request-handler-7]

**Reply by scholzj** [reply]
Right ... so this suggests that you did not enabled authentication in the Kafka cluster. Can you share your Kafka CR YAML?

**Reply by inthemistr1** [reply]
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: external-listener
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        type: internal
        port: 9093
        tls: false
        authentication:
          type: tls
      - name: external
        type: loadbalancer
        tls: true
        port: 9094
        authentication:
          type: tls
    config:
      preferredNodePortAddressType: InternalDNS
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    authorization:
      type: simple
      superUsers:
        - my-user
    storage:
      type: ephemeral
      volumes:
      - id: 0
        class: managed-premium
        type: persistent-claim
        size: 64Gi
        deleteClaim: false

  zookeeper:
      replicas: 1
      storage:
        type: persistent-claim
        class: managed-premium
        size: 32Gi
        deleteClaim: false
    entityOperator:
      topicOperator: {}
      userOperator: {}
```

**Reply by scholzj** [reply]
Hmm, you have the authentication there, but clearly not in the broker. Can you check the operator logs and the status of the Kafka CR in your Kubernetes cluster?

**Reply by inthemistr1** [reply]
I see, how can I check the operator logs?

This is the status of the Kafka CR

[Screenshot 2022-09-09 143741](https://user-images.githubusercontent.com/113207505/189439169-5a453923-d3a3-40e5-aae3-1cc66514071b.png)

**Reply by scholzj** [reply]
Yeah, but you need to get a full YAML with `kubectl get kafka -o yaml` => this just shows it is not ready, but not why.

**Reply by inthemistr1** [reply]
Here is the YAML, I see the errors now 

```
  status:
    conditions:
    - lastTransitionTime: "2022-09-09T21:20:38.445554Z"
      message: The desired Kafka storage configuration contains changes which are
        not allowed. As a result, all storage changes will be ignored. Use DEBUG level
        logging for more information about the detected changes.
      reason: KafkaStorage
      status: "True"
      type: Warning
    - lastTransitionTime: "2022-09-09T21:20:38.445851Z"
      message: log.message.format.version does not match the Kafka cluster version,
        which suggests that an upgrade is incomplete.
      reason: KafkaLogMessageFormatVersion
      status: "True"
      type: Warning
    - lastTransitionTime: "2022-09-09T21:23:56.673Z"
      message: Pod kafka-cluster-kafka-0 is currently not rollable
      reason: UnforceableProblem
      status: "True"
      type: NotReady
```

I think I know how I caused the storage one, but not sure on the version one. 

I checked the logs of the strimzi-cluster-operator

And I got an error regarding the following property: 

      transaction.state.log.min.isr

Saying it should be set up to 1 since there's only 1 replication, I went ahead and fixed it and the pod has been stuck in reconciliation:


```
2022-09-09 22:31:20 INFO  KafkaAvailability:127 - Reconciliation #11976(timer) Kafka(external-listener/kafka-cluster): __strimzi_store_topic/0 is already under-replicated (ISR={0}, replicas=[0,2,1], min.insync.replicas=2); broker 0 is in the ISR, so should not be restarted right now (it would impact consumers).
2022-09-09 22:31:20 INFO  KafkaRoller:306 - Reconciliation #11976(timer) Kafka(external-listener/kafka-cluster): Could not roll pod {kafka-cluster-kafka-0} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$UnforceableProblem: Pod kafka-cluster-kafka-0 is currently not rollable, retrying after at least 32000ms
2022-09-09 22:36:59 ERROR AbstractOperator:247 - Reconciliation #11978(timer) Kafka(external-listener/kafka-cluster): createOrUpdate failed
io.strimzi.operator.cluster.operator.resource.KafkaRoller$UnforceableProblem: Pod kafka-cluster-kafka-0 is currently not rollable
        at io.strimzi.operator.cluster.operator.resource.KafkaRoller.restartIfNecessary(KafkaRoller.java:354) ~[io.strimzi.cluster-operator-0.30.0.jar:0.30.0]
        at io.strimzi.operator.cluster.operator.resource.KafkaRoller.lambda$schedule$6(KafkaRoller.java:284) ~[io.strimzi.cluster-operator-0.30.0.jar:0.30.0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
```
