### DISCUSSION TITLE
PV, PVC and failover recommendations

### DISCUSSION THREAD

**Discussion by AydinChavez** [strimzi/strimzi-kafka-operator#7343] [Q&A]
Hi!

I have a Strimzi cluster with 3 replicas for broker and zookeeper, all distributed on 3 nodes. For this I define three PV using claimRef attribute and nodeAffinity.
This works so far.
But I did not get, what the strategy / routine is in order to ensure, that the kafka logs are reused in case of crashes or recreation (delete, deploy) of the cluster. I am also unsure, which PV strategy to use.. Retain or Recycle?
This may be more related to k8s than strimzi, but maybe somebody has experience in this.

**Comment by scholzj** [comment]
I'm not entirely sure what is your use-case. In most cases, the storage is provisioned dynamically through the Storage Class and Persistent Volume Claims. But in general, Strimzi integrates with the PVs through PVCs. So the operator creates the PVCs and Kubernetes has to bind them to some PVs. If you have the PVs and want to build the cluster from them, you can follow this guide form the docs: https://strimzi.io/docs/operators/latest/full/configuring.html#cluster-recovery-str

Keep in mind that if your PVs are from some non-Strimzi Kafka cluster, you might need to adjust the paths of the files to match what Strimzi expects.

Strimzi does not really care about the reclaim policies. So that is up to you. Retain is normally safer option as it helps you to keep the data and make sure they are not _recycled_ after some mistake for example.

**Comment by AydinChavez** [comment]
Thanks Jakub. I was not using any provisioner, but now I configured one.

One question related to this though. When deploying via gitops/argocd, I get following warning:
`
22s         Warning   FailedScheduling   pod/mds-zookeeper-2                 0/6 nodes are available: 6 persistentvolumeclaim "data-abc-zookeeper-2" not found.`

I thought the PVC is created by the strimzi entity operator? Do you have any idea what could be the cause for this error here? I am simply deploying a cluster, PV is already existing.

**Reply by scholzj** [reply]
That message seems a bit weird. Strimzi Cluster operator creates the PVCs. The PVs also need to be _aligned_ to the scheduling of the Pods. The message with `pod/mds-zookeeper-2 0/6 nodes are available` might normally suggest that for example your PVs are in a wrong availability zone and cannot be mounted on the nodes where the Pod would be scheduled. But I'm not entirely sure what does the `6 persistentvolumeclaim "data-abc-zookeeper-2" not found` part mean.

**Reply by scholzj** [reply]
Are you using some kind of local persistent storage? Or what is the storage you are using? Typically, with Local Persistent Storage you might for example use existing PVs. But most other Storage providers would always create a new ones and if you want to bind to existing volumes you would need to create the PVCs manually first.

Also, does the PVC the error message talks about exist? And if yes, in what state it is? Is it `Bound`?

**Reply by AydinChavez** [reply]
Yes local persistent volumes on bare metal. Will provide details soon.

**Reply by scholzj** [reply]
Ok, with that, you should check the state of the PVCs first I guess. 

One thing which might help would be to set the volume binding mode in your storage class to `Immediate` to bound the PVCs immediately: https://kubernetes.io/docs/concepts/storage/storage-classes/#volume-binding-mode. You should also check you didn't add any scheduling constraints to the Kafka cluster which would conflict the PV locations.

**Reply by AydinChavez** [reply]
I am using the https://github.com/rancher/local-path-provisioner from rancher project but learned now, that it won't work with kafka / strimzi in general, because latter expects fixed paths (e.g. /var/lib/kafka/..) where this provisionier generates uuids in the folder names (https://github.com/rancher/local-path-provisioner/issues/132).

Regarding the missing pvc issue from yesterday, honestly I don't know what the exact root cause was.

Now I will try to use the static provisionier (https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner) and create the dirs before. Let's see if this approach'll work.

**Reply by scholzj** [reply]
I do not have any experience with Rancher and their provisioner. But keep in mind, that when Strimzi uses the storage in `/var/lib/kafka/...`, that is the mount path inside the container. It does not mean this also needs to be the path inside the worker node. So quite typically, the various local storage providers like this work the way that the _volume directory_ is created e.g. in `/tmp/<uuid>` and their inside is mounted as a disk into the Kubernetes pod.

I do not know if the Rancher provisioner works in some weird way. But in the past I used the provisioner from Minikube without any problems:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: storage-provisioner
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:persistent-volume-provisioner
subjects:
  - kind: ServiceAccount
    name: storage-provisioner
    namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storage-provisioner
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - deletecollection
  - patch
  - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: storage-provisioner-endpoints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: storage-provisioner
subjects:
  - kind: ServiceAccount
    name: storage-provisioner
    namespace: kube-system

---
apiVersion: v1
kind: Pod
metadata:
  name: storage-provisioner
  namespace: kube-system
spec:
  serviceAccountName: storage-provisioner
  hostNetwork: true
  containers:
  - name: storage-provisioner
    image: gcr.io/k8s-minikube/storage-provisioner:latest
    command: ["/storage-provisioner"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /tmp
      name: tmp
  volumes:
  - name: tmp
    hostPath:
      path: /tmp
      type: Directory

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: kube-system
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/minikube-hostpath
```

**Comment by AydinChavez** [comment]
Thanks Jakub, these are golden hints for me.
I will than again try rancher provisioner, if it fails try the Minikube one you recommended.
Than I misinterpreted the issue I referenced, because I had one situation where the k8s events showed sth like "path /var/lib/kafka/.. does not exist" and I wrongly thought it's missing on the worker node.

Did I understood right that in case of a provisioner I don't need to manually create/apply a PV at all because it is handled by the provisioner?

My current setup is:

- 3 worker nodes
- Strimzi broker 3 replicas + zookeeper 3 replicase

- 6 PV (3xbroker, 3xzookeeper) all having nodeAffinity set so each pod gets deployed on one node
- Those PV also use claimRef in order to reference the PVC created by Strimzi

- In Strimzi config, I use persistent-claim and storageClass accordingly

Thanks for your help. Most of this is more k8s than Strimzi, therefore much appreciated.
If you need details, I can provide those soon. Til than, I will retry rancher and than Minikube provisioner.

**Reply by scholzj** [reply]
Most provisioners should create the PVs, so you should not need to create them. You just need to specify the right storage class. But it might depend on the provisioner of course.

**Comment by AydinChavez** [comment]
Jakub, do you have any experience with strimzi and argocd? In my case, the PVCs are created and deleted again. Am not sure if this is being done by some git magic aka argocd sync process, or by some issues with my strimzi setup.

I changed back to no-provisioner, need to fix this issue first.

**Reply by scholzj** [reply]
I don't use it. There are some other discussions about it here and on Slack, so you should look for them. I think you need to disable soem cleanup or something in Argo.

**Reply by AydinChavez** [reply]
Yes you might be right. Will check the slack channel.

Do you know how to add annotations to the PVC created by strimzi?

I guess using template (?), so something like:

```
  kafka:
      template:
        PersistentVolumeClaim:
          metadata:
            annotations:
              argocd.argoproj.io/sync-options: Prune=false
```
