### DISCUSSION TITLE
Helm template stringifies KubernetesSecretConfigProvider instead of substitution with secret

### DISCUSSION THREAD

**Discussion by cyberjar09** [strimzi/strimzi-kafka-operator#7346] [Q&A] [answered]
- I have a helm template to generate a yaml for my Mongo Connector
- when attempting to deploy, I see an error:
```
 Exception authenticating MongoCredential{mechanism=SCRAM-SHA-1, userName='${secrets:strimzi/strimzi-region-secrets:DB_USERNAME}', source='db_staging', password=<hidden>, mechanismProperties=<hidden>}
```
- this implies that helm template generation is quoting the config of `${secrets:strimzi/strimzi-region-secrets:DB_USERNAME}` instead of substitution
- my helm template:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ .Values.connectors.mongodb.metadata.name }}
  labels:
    strimzi.io/cluster: {{ .Values.kafkaConnect.clusterName }}
spec:
  class: io.debezium.connector.mongodb.MongoDbConnector
  tasksMax: 1
  config:
    tasks.max: 1
    mongodb.name: {{ .Values.connectors.mongodb.config.name }}
    mongodb.hosts: {{ .Values.connectors.mongodb.config.hosts }}
    mongodb.user: ${secrets:strimzi/strimzi-region-secrets:APPSERVER_DB_USERNAME}
    mongodb.password: ${secrets:strimzi/strimzi-region-secrets:APPSERVER_DB_PASSWORD}
    mongodb.authsource: {{ .Values.connectors.mongodb.config.authsource }}
    database.history.kafka.bootstrap.servers: {{ .Values.kafka.bootstrapServers }}
    database.include.list: {{ .Values.connectors.mongodb.config.databaseIncludeList }}
    collection.include.list: {{ .Values.connectors.mongodb.config.collectionIncludeList }}
    snapshot.include.collection.list: {{ .Values.connectors.mongodb.config.snapshotIncludeCollectionList }}

```
