### DISCUSSION TITLE
kafka connect postgresql ssl connection problem

### DISCUSSION THREAD

**Discussion by bahaeddinoz** [strimzi/strimzi-kafka-operator#7354] [Q&A]
Hi,
would like to enable SSL in kafka connect for postgresql connection. According the documentation specified below configs but each time i got an error. 

https://debezium.io/documentation/reference/stable/connectors/postgresql.html
https://strimzi.io/blog/2021/07/22/using-kubernetes-config-provider-to-load-data-from-secrets-and-config-maps/

### Create secret containing certificates
```
kubectl create secret generic postgresql-certificates \
      --type kubernetes.io/tls \
      --from-file=client-crt.pem=client-cert.pem \
      --from-file=client-key.pem=client-key.pem \
      --from-file=server-ca.pem=server-ca.pem \
      --namespace <<namaspace>>
```

### Edit kafka connect to mount secret and provider is directory
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: dev-kafka-connect
  annotations:
  # use-connector-resources configures this KafkaConnect
  # to use KafkaConnector resources to avoid
  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  image: kafka-connector/connector-debezium:v1.9.0
  replicas: 2
  bootstrapServers: bootstrap:9092
  externalConfiguration:
    volumes:
      - name: postgresql-certificates
        secret:
          secretName: postgresql-certificates
  config:
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    config.providers: directory
    config.providers.directory.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
    producer.max.in.flight.requests.per.connection: 5
    producer.retries: 2147483647
    producer.acks: all
    producer.enable.idempotence: true
  resources:
    requests:
      cpu: 300m
      memory: 2Gi
    limits:
      cpu: 300m
      memory: 2Gi
  jvmOptions:
    "-Xmx": "1g"
    "-Xms": "1g"
  template:
    pod:
      metadata:
        annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/port: '9404'
        labels:
          app.kubernetes.io/version: 3.2.0
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "Kafka"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                  - Kafka
  readinessProbe:
    initialDelaySeconds: 50
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 50
    timeoutSeconds: 5
```

### Reference the files with parameters database.sslmode, database.sslcert, database.sslkey, database.sslrootcert
```
apiVersion: "kafka.strimzi.io/v1beta2"
kind: "KafkaConnector"
metadata:
  name: "inventory-connector"
  labels:
    strimzi.io/cluster: kafka-connect
    app.kubernetes.io/version: 3.2.0
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    database.hostname: xxxxxxxx
    database.port: "5432"
    database.user: pg_username
    database.password: pg_password
    database.dbname: pg_db
    database.server.name: pg_server
    database.sslmode: verify-ca
    database.sslcert: ${directory:/opt/kafka/external-configuration/postgresql-certificates:client-crt.pem}
    database.sslkey: ${directory:/opt/kafka/external-configuration/postgresql-certificates:client-key.pem}
    database.sslrootcert: ${directory:/opt/kafka/external-configuration/postgresql-certificates:server-ca.pem}
    plugin.name: pgoutput
    schema.include.list: xxxxxxx
    topic.creation.default.replication.factor: 3
    topic.creation.default.partitions: 1
    topic.creation.default.cleanup.policy: "delete"
    topic.creation.default.compression.type: "lz4"
    topic.creation.default.min.insync.replicas: 2
    topic.creation.default.retention.ms: 31556926000
    tombstones.on.delete: false
```

After deploy the above configs it just failed with upcoming error
```
io.strimzi.operator.cluster.operator.assembly.ConnectRestException: PUT /connectors/dev-inventory-connector/config returned 400 (Bad Request): Connector configuration is invalid and contains the following 1 error(s):
Error while validating connector config: Could not open SSL certificate file -----BEGIN CERTIFICATE-----
<< OUTPUT OF THE CERTIFICATE >>
```

Manually copied certificates into /tmp folder of kafka connect and tried again but the error is same. These certificates are valid and i am using for my other connections. Also changed database.sslmode to other values but didn't help.

 It can be better to run cloud sql proxy sidecar container for this configuration but as i understand it is not supported way by strimzi. So tried to provide certificates but again couldn't do it. 
 Could you please help me on this ?
