### DISCUSSION TITLE
Kafka Connectors Artifact locations

### DISCUSSION THREAD

**Discussion by twosdai** [strimzi/strimzi-kafka-operator#7356] [Q&A]
Hey I'm new to Kafka and Kafka connect. Specifically I'm looking for Influxdb, and AWS kinesis connectors. 
I know that in ConfluentHub they have them available 
https://www.confluent.io/hub/confluentinc/kafka-connect-influxdb
https://www.confluent.io/hub/confluentinc/kafka-connect-kinesis

However I don't see an easy URL link that I can paste into the build properties of my `KafkaConnect` configuration when deploying my cluster
similar to the documentation: 

```yaml
plugins: # (3)
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/1.3.1.Final/debezium-connector-postgres-1.3.1.Final-plugin.tar.gz
            sha512sum: 962a12151bdf9a5a30627eebac739955a4fd95a08d373b86bdcea2b4d0c27dd6e1edd5cb548045e115e33a9e69b1b2a352bee24df035a0447cb820077af00c03
      - name: camel-telegram
        artifacts:
          - type: tgz
            url: https://repo.maven.apache.org/maven2/org/apache/camel/kafkaconnector/camel-telegram-kafka-connector/0.7.0/camel-telegram-kafka-connector-0.7.0-package.tar.gz
            sha512sum: a9b1ac63e3284bea7836d7d24d84208c49cdf5600070e6bd1535de654f6920b74ad950d51733e8020bf4187870699819f54ef5859c7846ee4081507f48873479
```

I was thinking of just creating my own image, where I install the connectors I need and then tell the strimzi operator to just use that, however I just wanted to check if there was something obvious I was missing. 

Any thoughts or help would be greatly appreciated, also let me know if I'm completely off base with my thinking. Very new to this ecosystem.
