### DISCUSSION TITLE
Cluster authorization exception when reassigning partitions

### DISCUSSION THREAD

**Discussion by jacobball11** [strimzi/strimzi-kafka-operator#7401] [Q&A] [answered]
We have been experiencing an issue with the reassign partitions tool and can't diagnose the root cause. Our goal is to scale up from 2 nodes to 3 in our kafka cluster. We have added the 3rd node as well as set the kafka replica count to 3. The final step is to re-balance our topics across 3 brokers rather than 2.
### Short explanation of the problem
When following the documentation, we are able to successfully generate a reassignment json file. We experience issues when calling `bin/cafka-reassign-partitions.sh` in the `--execute` mode. Here is the error:
```
Error: org.apache.kafka.common.errors.ClusterAuthorizationException: Request Request(processor=10, connectionId=10.0.9.143:9095-10.0.63.159:59124-902, session=Session(User:CN=partition-reassignment-tool,/10.0.63.159), listenerName=ListenerName(INTERNTLS-9095), securityProtocol=SSL, buffer=java.nio.HeapByteBuffer[pos=41 lim=41 cap=41], envelope=None) is not authorized.
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.ClusterAuthorizationException: Request Request(processor=10, connectionId=10.0.9.143:9095-10.0.63.159:59124-902, session=Session(User:CN=partition-reassignment-tool,/10.0.63.159), listenerName=ListenerName(INTERNTLS-9095), securityProtocol=SSL, buffer=java.nio.HeapByteBuffer[pos=41 lim=41 cap=41], envelope=None) is not authorized.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
        at kafka.admin.ReassignPartitionsCommand$.executeAssignment(ReassignPartitionsCommand.scala:752)
        at kafka.admin.ReassignPartitionsCommand$.handleAction(ReassignPartitionsCommand.scala:238)
        at kafka.admin.ReassignPartitionsCommand$.main(ReassignPartitionsCommand.scala:206)
        at kafka.admin.ReassignPartitionsCommand.main(ReassignPartitionsCommand.scala)
Caused by: org.apache.kafka.common.errors.ClusterAuthorizationException: Request Request(processor=10, connectionId=10.0.9.143:9095-10.0.63.159:59124-902, session=Session(User:CN=partition-reassignment-tool,/10.0.63.159), listenerName=ListenerName(INTERNTLS-9095), securityProtocol=SSL, buffer=java.nio.HeapByteBuffer[pos=41 lim=41 cap=41], envelope=None) is not authorized.
```
From what I can tell, Kafka is attempting to see if there are any existing reassignments before creating new reassignments and that is not being allowed by the cluster. I know that I'm using a `KafkaUser` that has access to all of my topics and has Write, Describe, Create, and Alter permissions on them all.
I have no way to see which operation is causing the throw because the running code is within Kafka and for good reasons the operation data is not exposed in the error message. I also know that everything fails when I remove the user's credentials from the command so I'm assuming my user is being authenticated properly.

### Long explanation of the problem

1. I begin by gathering the `ca.p12` file and the password (base64 decoded) from the cluster-ca-cert secret.
2. I run the strimzi pod image for my version of strimzi (0.28) and kafka (3.1).
```
kubectl -n develop-namespace run --restart=Never --image=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0 kafka-partition-reassigner -- /bin/sh -c "sleep 3600"
```
3. I copy the `ca.p12` file to the /tmp directory in the pod.
4. I apply my reassignment tool kafka user with the following definition:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  namespace: develop-namespace
  name: partition-reassignment-tool
  labels:
    strimzi.io/cluster: kafka-cluster-name
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # access to topic-1
      - resource:
          type: topic
          name: topic-1
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: topic-1
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: topic-1
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: topic-1
          patternType: literal
        operation: Alter
        host: "*"
      # access to topic-2
      - resource:
          type: topic
          name: topic-2
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: topic-2
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: topic-2
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: topic-2
          patternType: literal
        operation: Alter
        host: "*"
      # access to topic-3
      - resource:
          type: topic
          name: topic-3
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: topic-3
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: topic-3
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: topic-3
          patternType: literal
        operation: Alter
        host: "*"
```
5. After the KafkaUser is finished being created, I gather the `user.p12` file and the password (base64 decoded) from the user secret.
6. I copy the `user.p12` file to the /tmp directory in the pod.
7. I get the bootstrap server from kafka using the following command:
```
kubectl -n develop-namespace get kafka kafka-cluster-name -o jsonpath='{.status.listeners[?(@type=="interntls")].bootstrapServers}'
```
This gives me something like `kafka-cluster-name-kafka-bootstrap.develop-namespace.svc:9095` which matches our kafka config:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  namespace: develop-namespace
  name: kafka-cluster-name
spec:
  kafka:
  ...
  listeners:
    ...
    - name: interntls
      port: 9095
      type: internal
      tls: true
      authentication:
        type: tls
    ...
  ...
```
8. I create the `config.properties` file and copy it into the pod as well. It ends up looking like this:
```
bootstrap.servers=kafka-cluster-name-kafka-bootstrap.develop-namespace.svc:9095
security.protocol=SSL
ssl.truststore.location=/tmp/ca.p12
ssl.truststore.password=<truststore_password>
ssl.keystore.location=/tmp/user.p12
ssl.keystore.password=<keystore_password>
```
9. I copy the `topics.json` file into the /tmp directory in the pod. This file looks like this:
```json
{
    "version": 1,
    "topics": [
        {
            "topic": "topic-1"
        },
        {
            "topic": "topic-2"
        },
        {
            "topic": "topic-3"
        }
    ]
}
```
10. I generate a reassignment json object using the following command:
```
kubectl exec -n develop-namespace kafka-partition-reassigner -- bin/kafka-reassign-partitions.sh \
--bootstrap-server kafka-cluster-name-kafka-bootstrap.develop-namespace.svc:9095 \
--command-config /tmp/config.properties \
--topics-to-move-json-file /tmp/topics.json \
--broker-list 0,1,2 \
--generate \
>> generated-reassignment.txt
```
11. I copy the generated json object from the `generated-reassignment.txt` file and make a new file with it called `reassignment.json`. I won't put the contents of that file here because it is quite long and is a generated file. I will note that the file makes sense to me and the json is valid.
12. I copy the `reassignment.json` file into the /tmp directory in the pod.
13. I attempt to reassign the partitions with the following command:
```
kubectl exec -n develop-namespace kafka-partition-reassigner -- bin/kafka-reassign-partitions.sh \
--bootstrap-server kafka-cluster-name-kafka-bootstrap.develop-namespace.svc:9095 \
--command-config /tmp/config.properties \
--reassignmane-json-file /tmp/reassignment.json \
--execute
```

This results in the following output:
```
Error: org.apache.kafka.common.errors.ClusterAuthorizationException: Request Request(processor=10, connectionId=10.0.9.143:9095-10.0.63.159:59124-902, session=Session(User:CN=partition-reassignment-tool,/10.0.63.159), listenerName=ListenerName(INTERNTLS-9095), securityProtocol=SSL, buffer=java.nio.HeapByteBuffer[pos=41 lim=41 cap=41], envelope=None) is not authorized.
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.ClusterAuthorizationException: Request Request(processor=10, connectionId=10.0.9.143:9095-10.0.63.159:59124-902, session=Session(User:CN=partition-reassignment-tool,/10.0.63.159), listenerName=ListenerName(INTERNTLS-9095), securityProtocol=SSL, buffer=java.nio.HeapByteBuffer[pos=41 lim=41 cap=41], envelope=None) is not authorized.
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
        at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:165)
        at kafka.admin.ReassignPartitionsCommand$.executeAssignment(ReassignPartitionsCommand.scala:752)
        at kafka.admin.ReassignPartitionsCommand$.handleAction(ReassignPartitionsCommand.scala:238)
        at kafka.admin.ReassignPartitionsCommand$.main(ReassignPartitionsCommand.scala:206)
        at kafka.admin.ReassignPartitionsCommand.main(ReassignPartitionsCommand.scala)
Caused by: org.apache.kafka.common.errors.ClusterAuthorizationException: Request Request(processor=10, connectionId=10.0.9.143:9095-10.0.63.159:59124-902, session=Session(User:CN=partition-reassignment-tool,/10.0.63.159), listenerName=ListenerName(INTERNTLS-9095), securityProtocol=SSL, buffer=java.nio.HeapByteBuffer[pos=41 lim=41 cap=41], envelope=None) is not authorized.

command terminated with exit code 1
```

### Other things I've tried
- I thought maybe this was an issue with windows line endings so I attempted this whole workflow with CRLF and LF line endings in all of the files getting copied into the pod. It made no difference.
- I tried re-ordering the arguments in the execute command. It made no difference.
- I removed the `ssl.keystore.location` and `ssl.keystore.password` from the config.properties file and it resulted in an AdminClient error:
```
ERROR [AdminClient clientId=reassign-partitions-tool] Connection to node -1 (kafka-cluster-name-kafka-bootstrap.develop-namespace.svc/xxx.xx.xx.xxx:9095) failed authentication due to: Failed to process post-handshake messages (org.apache.kafka.clients.NetworkClient)
```
This tells me the AdminClient is authenticating successfully with the credentials provided.
- I tried this whole workflow using a bootstrap server name closer to the one mentioned in the documentation (`<kafka_cluster_name>-kafka-bootstrap:9093`) so mine was something like `kafka-cluster-name-kafka-bootstrap:9095`. Interestingly, this made no difference.
- I also tried using a mixture of my two bootstrap server names. One inside the `config.properties` file and one as a command line argument. I tried it both ways and there was no difference. For clarity, the two bootstrap names I tried were `kafka-cluster-name-kafka-bootstrap:9095` and `kafka-cluster-name-kafka-bootstrap.develop-namespace.svc:9095`.
- I tried running the command from within the pod. No difference.

### Final thoughts
I am at a loss as to what I might be doing wrong but I feel like I'm close. I did look into how the script works and what all its doing within the [Kafka 3.1 repo](https://github.com/apache/kafka/tree/3.1). Effectively the problem is coming from [line 752 & 753 in ReassignPartitionsCommand.scala](https://github.com/apache/kafka/blob/55701dc00ab72233e7c238550a423fdce479afc1/core/src/main/scala/kafka/admin/ReassignPartitionsCommand.scala#L753) with the `.get()` command. However, this eventually leads to [line 55 in the AuthHelper.scala file](https://github.com/apache/kafka/blob/99b9b3e84f4e98c3f07714e1de6a139a004cbc5b/core/src/main/scala/kafka/server/AuthHelper.scala#L55) where the exception is thrown. The fact that everything is running inside a `CompletableFuture` means that the stack trace isn't helpful to find exactly what operation was being carried out when the exception was thrown.

Any leads on getting this all to work would be super helpful. I fear I've been looking at this for so long there's something simple broken that I'm not seeing.

**Comment by scholzj** [comment]
For authorization issues, the best thing to do is to check the broker logs => they normally tell you exactly what ACL rights are you missing.  So, can you check the broker log to see what it says there? I do not see it in the different outputs above.

**Reply by jacobball11** [reply]
It appears our logging is not working at all on our brokers which is news to me. I'll look into fixing that and I'll get back to you with some logs.
```
log4j:WARN No appenders could be found for logger (io.strimzi.kafka.agent.KafkaAgent).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

**Reply by scholzj** [reply]
Did you remove some libraries form the containers? Or do you have some special configuration for the broker logging?

**Reply by jacobball11** [reply]
I don't believe any libraries have been removed.
Here is our configuration. Its nothing crazy but it doesn't seem to be picking up on it.
```
  log4j.properties:
    kafka.root.logger.level="WARN"
    zookeeper.root.logger="WARN"
  log4j2.properties:
    rootLogger.level="WARN"
```

**Reply by scholzj** [reply]
If you pass that as the log4j.properties file, it does not define any appenders etc. I'm not sure this is really a valid Log4j configuration - I guess it might result in what you are seeing. For comparison, this is the default Log4j config for Kafka used by Strimzi: https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/src/main/resources/kafkaDefaultLoggingProperties

**Reply by jacobball11** [reply]
I updated the properties and I'm still not getting any logs. I also temporarily removed the `logging` blocks from the kafka, zookeeper, topicOperator, and userOperator sections to try and get it to re-pull the new config but it didn't help.

```
  log4j.properties:
    kafka.root.logger.level = WARN
    log4j.appender.CONSOLE = org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.layout = org.apache.log4j.PatternLayout
    log4j.appender.CONSOLE.layout.ConversionPattern = %d{ISO8601} %p %m (%c) [%t]%n
    log4j.rootLogger = ${kafka.root.logger.level}, CONSOLE
    log4j.logger.org.I0Itec.zkclient.ZkClient = INFO
    log4j.logger.org.apache.zookeeper = INFO
    log4j.logger.kafka = INFO
    log4j.logger.org.apache.kafka = INFO
    log4j.logger.kafka.request.logger = WARN, CONSOLE
    log4j.logger.kafka.network.Processor = OFF
    log4j.logger.kafka.server.KafkaApis = OFF
    log4j.logger.kafka.network.RequestChannel$ = WARN
    log4j.logger.kafka.controller = TRACE
    log4j.logger.kafka.log.LogCleaner = INFO
    log4j.logger.state.change.logger = TRACE
    log4j.logger.kafka.authorizer.logger = INFO

    zookeeper.root.logger = WARN
  log4j2.properties:
    name = TOConfig

    appender.console.type = Console
    appender.console.name = STDOUT
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss,nnnnn} %-5p [%t] %c{1}:%L - %m%n

    rootLogger.level = WARN
    rootLogger.appenderRefs = stdout
    rootLogger.appenderRef.console.ref = STDOUT
    rootLogger.additivity = false

    logger.clients.name = org.apache.kafka.clients
    logger.clients.level = INFO
    logger.clients.additivity = false

    logger.streams.name = org.apache.kafka.streams
    logger.streams.level = INFO
    logger.streams.additivity = false
```

**Reply by scholzj** [reply]
That us weird. It works fine for me with the defaults.

**Reply by jacobball11** [reply]
Alright I got it working. There is a ton of stuff coming out so I'll dig through it for a little bit and get back to you.

**Comment by jacobball11** [comment]
I found a lead in the broker logs for broker 1.
```
2022-09-28 17:23:04,685 INFO Principal = User:CN=partition-reassignment-tool is Denied Operation = Describe from host = 10.0.63.159 on resource = Cluster:LITERAL:kafka-cluster for request = ListPartitionReassignments with resourceRefCount = 1 (kafka.authorizer.logger) [data-plane-kafka-request-handler-5]
```
Just FYI, I have 3 brokers on 3 different pods. Broker 0 and 1 are currently in use and broker 2 is the new one.

**Reply by scholzj** [reply]
Right ... so you need to add this right to your user and you should be hopefully good to go. The ACLs should be the same on all brokers. Where the error shows up depends on with which broker the client is talking.

**Comment by jacobball11** [comment, marked as answer]
I was finally able to complete the reassignment with no errors so I will describe my solution here.
After adding `Alter` permissions as per the documentation I was able to call the script in `--execute` mode and not receive any errors.
I called the script in `--verify` mode and I received an authentication error for a `AlterConfig` operation. To solve this, I changed the permission to `All` on the cluster resource.
I called the script in `--verify` mode again and it threw another authentication error for `AlterConfig` on each of my topics. To solve this I ended up giving every topic and the cluster resource the `All` permissions for the KafkaUser. I am allowing this because this is a temporary user that I am removing after it completes.

For reference, my `KafkaUser.yaml` file looked like this:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  namespace: develop-namespace
  name: partition-reassignment-tool
  labels:
    strimzi.io/cluster: kafka-cluster-name
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # access to topic-1
      - resource:
          type: topic
          name: topic-1
          patternType: literal
        operation: All
        host: "*"
      # access to topic-2
      - resource:
          type: topic
          name: topic-2
          patternType: literal
        operation: All
        host: "*"
      # access to topic-3
      - resource:
          type: topic
          name: topic-3
          patternType: literal
        operation: All
        host: "*"
      # access to the cluster
      - resource:
          type: cluster
          name: kafka-cluster-name
          patternType: literal
        operation: All
        host: "*"
```

I would recommend making the cluster resource permission a little bit more obvious in the documentation as it was very easy to miss. Also, I had to give it permission to `Alter` and to `AlterConfig` (or just `All`) to get it to work entirely so that may need updated in the docs as well if thats not just a "me" issue.

Thanks @scholzj  for all the help and quick responses!!
