### DISCUSSION TITLE
MirrorMaker2 custom probes

### DISCUSSION THREAD

**Discussion by scottc-git** [strimzi/strimzi-kafka-operator#7429] [Q&A]
**Question:**
Is there a way to provide my own Readiness probe to MirrorMaker2?
 
**Background**
I am using a few SMTs for the MirrorMaker2 - one of them is to copy the Avro schemas from the source Kafka to target (Strimzi) Kafka environment upon mirroring.  The problem is the timing issue when SchemaRegistry becomes ready sometime **after** Mirroring started.  The SMT will fail if the target schema registry is not ready yet and the MirrorMaker worker thread will eventually stop.  I will have to restart the MM2 pod manually and then it will resume the mirroring.    The whole Strimzi Kafka (mirror) environment can be built a few times a day and this problem has been making the test environments unreliable to my users.  

**Error Logs**
```
2022-10-03 18:58:51,981 ERROR WorkerSourceTask{id=mirrortxn->strimzi-zxrt.MirrorSourceConnector-6} 
Task threw an uncaught and unrecoverable exception. 
Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) 
[task-thread-mirrortxn->strimzi-zxrt.MirrorSourceConnector-6]
```
**Real Question**
According to the [Kafka documentation](https://kafka.apache.org/28/documentation.html#sourceconnectorconfigs_errors.tolerance), setting `errors.tolerance` to `none (default)` seems to be a solution to this but the tasks do not come back up as the error message says.  In the meantime, Pod status is still `Running` (with the dead threads) and Kubernetes will not bother recreating the pod either.  Is there a way to configure the KMM2 to overcome this situation?  I was going to override the Readiness probe to `httpGet` against http://schema-registry-client:8081 but it seems the `[Probe](https://strimzi.io/docs/operators/0.27.1/using.html#type-Probe-reference)` only checks on its own service (mm2) being running.

**KMM2 spec**
```
    mirrors:
    - checkpointConnector:
        config:
          sync.group.offsets.enabled: false
      groupsPattern: do-not-mirror-groups
      sourceCluster: mirrorref
      sourceConnector:
        config:
          checkpoints.topic.replication.factor: 1
          errors.log.enable: "true"
          errors.log.include.messages: "true"
          errors.tolerance: none           <== Do Not Ignore Errors
          heartbeats.topic.replication.factor: 1
          offset-syncs.topic.replication.factor: 3
          refresh.topics.interval.seconds: 60
          replication.factor: 1
          replication.policy.class: io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy
          replication.policy.separator: ""
          sync.topic.acls.enabled: "false"
          transforms: AvroSchemaTransfer
          transforms.AvroSchemaTransfer.dest.schema.registry.url: http://schema-registry-client:8081
          transforms.AvroSchemaTransfer.schema.capacity: 5000
          transforms.AvroSchemaTransfer.src.schema.registry.url: http://schema-registry-client.tdp-mirror-az-stg:8081
          transforms.AvroSchemaTransfer.transfer.message.keys: "false"
          transforms.AvroSchemaTransfer.type: cricket.jmoore.kafka.connect.transforms.SchemaRegistryTransfer
        tasksMax: 10
      targetCluster: strimzi-zwim
      topicsExcludePattern: __consumer_offsets, _schemas, heartbeats
      topicsPattern: ^master-data.(bar.v1|foo.v1)$
```

**Alternative considered**
I was thinking of using init-container for more extensive health check but previous discussions suggested that it is going to be more rough path and it is not supported.

**Version**
Strimzi 0.27.1

Thanks in advance.
