### DISCUSSION TITLE
SSL handshake failed - Kafka Listener Certificate

### DISCUSSION THREAD

**Discussion by senthil13** [strimzi/strimzi-kafka-operator#7456] [General]
Hi Experts,
I was using the latest strimzi-operator latest version, working fine without any issues. But I have to use the custom certificate since we have our own CA. So First I started following the [link ](https://github.com/scholzj/strimzi-custom-ca-test) and created a cluster with its own CA, which worked fine. As a next step, I did it in two parts.

#### First part: OWN CA change all certs
Create clients csr + strimzi csr
```
openssl req -new -newkey rsa:2048 -nodes -keyout strimzi.key -out strimzi.csr -passout pass:"test1234" -subj "/C=US/ST=XXXX/L=XX/O=XXX/OU=XXX/CN=StrimziCA"
openssl req -new -newkey rsa:2048 -nodes -keyout clients.key -out clients.csr -passout pass:"test1234" -subj "/C=US/ST=XXXX/L=XX/O=XXX/OU=XXX/CN=ClientsCA"

```
Signed both certificates with my own CA, and they provided my certificate + root cert + intermediate cert.

```
cat strimzi.pem > strimzi-bundle.crt;cat inter.crt >> strimzi-bundle.crt;cat root.crt >> strimzi-bundle.crt
cat clients.pem > clients-bundle.crt;cat inter.crt >> clients-bundle.crt;cat root.crt  >> clients-bundle.crt

```

Loaded those to the secrets using [script](https://github.com/scholzj/strimzi-custom-ca-test/blob/master/load.sh)

Started the cluster - 

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app: my-cluster
spec:
  kafka:
    replicas: 1
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: "1"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        type: ingress
        tls: true
          bootstrap:
            host: my-cluster-bootstrap.tcp.devops.XXX.XXXX.com
            annotations:
              external-dns.alpha.kubernetes.io/hostname: my-cluster-bootstrap.tcp.devops.XXX.XXXX.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
          - broker: 0
            host: my-cluster-broker-0.tcp.devops.XXX.XXXX.com
            annotations:
              external-dns.alpha.kubernetes.io/hostname: my-cluster-broker-0.tcp.devops.XXX.XXXX.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: "0.3"
      limits:
        memory: 1Gi
        cpu: "0.5"
    storage:
      type: ephemeral
  clusterCa:
    generateCertificateAuthority: false
  clientsCa:
    generateCertificateAuthority: false
  entityOperator:
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
    topicOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
```

but the operator didn't create the zookeeper node.

```
Control key when opening logs to launch a new window.
Detected Zookeeper ID 1
Preparing truststore
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/zookeeper/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore is complete
Looking for the right CA
No CA found. Thus exiting.
```

#### Second part: Kafka Listener certificate
Since the first part failed I want to try the second part, so that operator can handle the internal certificate and outside consumer/producer. I used the same YAML just commenting below lines. named it as `name: strimzi-cluster`

```
  clusterCa:
    generateCertificateAuthority: false
  clientsCa:
    generateCertificateAuthority: false
```

Created the certificate with SAN.

```
openssl genrsa -out strimzi-cluster-private-cert.key 2048
openssl req -new -key strimzi-cluster-private-cert.key -out strimzi-cluster-private-cert.csr -subj "/C=US/ST=XXXX/L=XX/O=XXX/OU=XXX/CN=StrimziCA" -addext "subjectAltName = DNS.1:*.strimzi-cluster-kafka-brokers,DNS.2:*.strimzi-cluster-kafka-brokers.kafka.svc,DNS.3:strimzi-cluster-kafka-bootstrap,DNS.4:strimzi-cluster-kafka-bootstrap.kafka.svc"
```

Signed from CA. 

```
openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in strimzi-cluster-private-cert.key -out strimzi-cluster-private-pkcs8.key
```

added the root and intermediate certificates. 

```
cat strimzi-cluster-private-cert.csr > strimzi-bundle.crt;cat inter.crt >> strimzi-bundle.crt;cat root.crt >> strimzi-bundle.crt
kubectl create secret generic strimzi-cluster-private-cert --from-file=ca.crt=strimzi-cluster-private-cert.crt --from-file=ca.key=strimzi-cluster-private-pkcs8.key -n kafka
```

added below lines and updated.

```
        configuration:
          brokerCertChainAndKey:
            secretName: strimzi-cluster-private-cert
            certificate: ca.crt
            key: ca.key

kubectl apply -f kafka-ephemeral.yaml -n kafka
```

Added root and intermediate certificates to the trust store. 

```
keytool -import -trustcacerts -alias CARoot -file root.crt -keystore kafka.client.truststore.jks -storepass test1234 -noprompt
keytool -import -trustcacerts -alias CAIntermediate -file inter.crt -keystore kafka.client.truststore.jks -storepass test1234 -noprompt

kafka-console-producer --broker-list strimzi-cluster-bootstrap.tcp.devops.XXX.XXXX.com:443 --producer-property security.protocol=SSL --producer-property ssl.truststore.password=test1234 --producer-property ssl.truststore.location=kafka.client.truststore.jks  --topic test-topic
```

Getting,  SSL handshake 

```
Broker Logs
2022-10-10 19:58:37,772 INFO [SocketServer listenerType=ZK_BROKER, nodeId=0] Failed authentication with /10.42.11.0 (channelId=10.42.7.35:9094-10.42.11.0:51069-3) (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(EXTERNAL-9094)-SSL-11]

Client logs
[2022-10-10 15:58:11,955] DEBUG [Producer clientId=console-producer] Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 102400, SO_TIMEOUT = 0 to node -1 (org.apache.kafka.common.network.Selector)
[2022-10-10 15:58:12,551] DEBUG [Producer clientId=console-producer] Completed connection to node -1. Fetching API versions. (org.apache.kafka.clients.NetworkClient)
[2022-10-10 15:58:12,599] INFO [Producer clientId=console-producer] Failed authentication with strimzi-cluster-bootstrap.tcp.devops.XXXX.XXXX.com/XXXX (SSL handshake failed) (org.apache.kafka.common.network.Selector)
[2022-10-10 15:58:12,600] DEBUG [Producer clientId=console-producer] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient)
[2022-10-10 15:58:12,601] ERROR [Producer clientId=console-producer] Connection to node -1 (strimzi-cluster-bootstrap.tcp.devops.XXXX.XXXX.com/XXXX:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2022-10-10 15:58:12,601] WARN [Producer clientId=console-producer] Bootstrap broker strimzi-cluster-bootstrap.tcp.devops.XXXX.XXXX.com:443 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2022-10-10 15:58:12,701] DEBUG [Producer clientId=console-producer] Initialize connection to node strimzi-cluster-bootstrap.tcp.devops.XXXX.XXXX.com:443 (id: -1 rack: null) for sending metadata request (org.apache.kafka.clients.NetworkClient)
[2022-10-10 15:58:12,702] DEBUG [Producer clientId=console-producer] Initiating connection to node strimzi-cluster-bootstrap.tcp.devops.XXXX.XXXX.com:443 (id: -1 rack: null) using address strimzi-cluster-bootstrap.tcp.devops.XXXX.XXXX.com/XXXX (org.apache.kafka.clients.NetworkClient)
[2022-10-10 15:58:12,725] DEBUG [Producer clientId=console-producer] Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 102400, SO_TIMEOUT = 0 to node -1 (org.apache.kafka.common.network.Selector)
```

### Question

- What is the best way to use our own CA?
- Is it using own CA for all certificates or Kafka listen alone? 
- Documents show how to create the custom CA, but not showing how to connect. 
- Since we do have external clients we cant share the server certificate, but clients can sign their own cert with the same CA.

Thanks
Senthil

**Comment by scholzj** [comment]
First of all, let's clarify what exactly you mean with `latest` version. The container images and installation files with the tag `:latest` are from the `main` branch. These are unstable since these are under development. What you want to be using is the latest release which is currently 0.31.1. It is not really clear what do you mean with _latest_ here, so I wanted to clarify it.

> First part: OWN CA change all certs

Sorry, but from your description it is not really clear what you did. Please follow the steps described here: https://strimzi.io/docs/operators/latest/full/configuring.html#installing-your-own-ca-certificates-str. If you want to move from Strimzi managed CA to your own CA, you should first configure the Kafka CR to tell the operator that you want to now use your own CA (this is the `generateCertificateAuthority: false` part). And then follow the _own CA renewal process_ to roll out your new CA: https://strimzi.io/docs/operators/latest/full/configuring.html#renewing-your-own-ca-certificates-str

Also, keep in mind that the CA needs to be a CA => the certificate you provide needs to be marked as usable for CA purposes (but it can be just an intermediate CA, does not have to be a Root CA).

From the error, it seems clear that you didn't rolled it correctly. If you are starting with a fresh cluster, you do not need to do the renewal, just do your own CA from the start.

> Second part: Kafka Listener certificate

I think that in most cases you will use either your own CA or the listener certificate. The difference is that when using your own CA, you need to provide a CA as mentioned above. And this CA is used to sign all certificates used to secure the Kafka cluster. So it is not just used for the communication between your Kafka clients and brokers. It is also used for communication between the brokers, between ZooKeeper nodes, between Kafka and ZooKeeper. So it is used for more things, but it is also more complicated.

The listener certificate is much easier. You provide a server certificate which will be used for a particular listener in the Kafka broker. It does not need to be CA as it is not used to sign any additional certificates. It will be used only for communication between your clients and your Kafka brokers.

**Reply by senthil13** [reply]
- Yes I am using the 0.31.1 only.
- Let's park the OWN CA on the side for now and check the Second part alone. 
   - Since the process here our cert team follows is, we provide them a CSR they will provide back a signed Cert for that CSR + intermediate + root certs.
- Which instruction to follow?
  - https://strimzi.io/docs/operators/latest/configuring.html#installing-your-own-ca-certificates-str 
  - https://strimzi.io/docs/operators/latest/full/configuring.html#installing-your-own-ca-certificates-str
 
- Kafka Listener certificate, since its easier, I am going to work on this
  - when I used this following the process described in - https://strimzi.io/docs/operators/latest/full/configuring.html#proc-installing-certs-per-listener-str
  - I am getting the SSL handshake error as mentioned above. All details are there in my last post. If you need any additional details please let me know.

**Reply by scholzj** [reply]
> I am getting the SSL handshake error as mentioned above. All details are there in my last post. If you need any additional details please let me know.

There are plenty of other discussions here about TLS handshake errors - especially when using Ingress type listeners. I suggest you go through them and the steps suggested there since from the logs you provided, I definitely cannot give any definitive answer.

**Reply by senthil13** [reply]
Thanks, I searched a couple and didn't find the solution from those threads. So thought of checking with a new discussion. I will check again.

**Reply by scholzj** [reply]
Well, they might not contain a solution for your problem ... but list steps what to try. So you can try them and list them here -> it migth tells what is not the problem if nothing else.

**Reply by senthil13** [reply]
The main problem is for the own CA, there is no end-to-end documentation for CSR creation or client connection. More info got from our cert team they DigiCert/SecureTrust/ along with internal cert. I tried all possible ways but either I am getting an `SSL handshake` issue or `No CA issue`.  I am running out of options now, will try tomorrow. Also, is there any way we can expose the plain port 9092 outside of k8s without SSL

Thanks -

**Reply by scholzj** [reply]
TBH, if you want to use your own CA, then the expectation is that you know how CAs work, how to generate them etc. There are hundreds of ways how to manage CAs with different tools and services etc. There is no chance we can support you or provide detailed docs for all of these.

Also, as I said right on the beginning, you should also pick which one you want to use - own ca or custom listener certificate and not mix them together. When you mix those, it is not possible to understand what you exactly. And you should also reflect the advice from the different posts. There is no update to what you did based on that, no updated steps, no updated errors etc.

**Reply by senthil13** [reply]
I verified one more time, all threads are either closed or the requestor is resolved not shared the resolution steps.  

Threads I checked

```
https://github.com/strimzi/strimzi-kafka-operator/discussions/6867
https://github.com/strimzi/strimzi-kafka-operator/discussions/6809
https://github.com/strimzi/strimzi-kafka-operator/discussions/7323
https://github.com/strimzi/strimzi-kafka-operator/discussions/5552
https://github.com/strimzi/strimzi-kafka-operator/discussions/4664
https://github.com/strimzi/strimzi-kafka-operator/discussions/6537
https://github.com/strimzi/strimzi-kafka-operator/discussions/5360
https://github.com/strimzi/strimzi-kafka-operator/discussions/5552
```

I agree with you that I should have opened two posts, but I thought since both belong to have own CA, I posted here. Let me have this one for **_OWN CA_**

Followed these documents. 
https://strimzi.io/docs/operators/latest/configuring.html#installing-your-own-ca-certificates-str
https://strimzi.io/docs/operators/latest/full/configuring.html#installing-your-own-ca-certificates-str

Zookeeper pods are unable to create, having below errors
```
Detected Zookeeper ID 1
Preparing truststore
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/zookeeper/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore is complete
Looking for the right CA
No CA found. Thus exiting.
```

Steps followed for certificates. (my own CA, with self signed cert)
```
# OWN CA per documents
openssl req -new -x509 -keyout ca-key.pem -out ca.pem -days 365 -passout pass:"test1234" -subj "/C=US/ST=XXXX/L=Oaks/O=XXXX/OU=XXXX/CN=RootCA"

openssl req -new -newkey rsa:2048 -keyout intermediate-key.pem -out intermediate.csr -days 365 -passout pass:"test1234" -subj "/C=US/ST=XXXX/L=XXx/O=XXXX/OU=XXXX/CN=IntermediateCA"
openssl x509 -req -days 365 -in intermediate.csr -CA ca.pem -CAkey ca-key.pem -CAcreateserial -out intermediate.pem -passin pass:"test1234"

openssl req -new -newkey rsa:2048 -keyout strimzi-key.pem -out strimzi.csr -passout pass:"test1234" -subj "/C=US/ST=XXXX/L=XXX/O=XXXX/OU=XXXX/CN=StrimziCA" 
openssl x509 -req -days 365 -in strimzi.csr -CA intermediate.pem -CAkey intermediate-key.pem -CAcreateserial -out strimzi.pem -passin pass:"test1234"

openssl req -new -newkey rsa:2048 -keyout clients-key.pem  -out clients.csr -passout pass:"test1234" -subj "/C=US/ST=XXXX/L=XXX/O=XXXX/OU=XXXX/CN=ClientsCA" 
openssl x509 -req -days 365 -in clients.csr -CA intermediate.pem -CAkey intermediate-key.pem -CAcreateserial -out clients.pem -passin pass:"test1234"

cat strimzi.pem > strimzi-bundle.crt;cat intermediate.pem >> strimzi-bundle.crt;cat ca.pem >> strimzi-bundle.crt
cat clients.pem > clients-bundle.crt;cat intermediate.pem >> clients-bundle.crt;cat ca.pem >> clients-bundle.crt

openssl pkcs8 -topk8 -nocrypt -in ca-key.pem -out ca.key -passin pass:"test1234"
openssl pkcs8 -topk8 -nocrypt -in intermediate-key.pem -out intermediate.key -passin pass:"test1234"
openssl pkcs8 -topk8 -nocrypt -in clients-key.pem -out clients.key -passin pass:"test1234"
openssl pkcs8 -topk8 -nocrypt -in strimzi-key.pem -out strimzi.key -passin pass:"test1234"
```

Steps how I created the secerts.
```

openssl pkcs12 -export -in strimzi-bundle.crt --nokeys -out strimzi-bundle.p12 -password pass:test1234 -caname strimzi-bundle.crt
openssl pkcs12 -export -in clients-bundle.crt --nokeys -out clients-bundle.p12 -password pass:test1234 -caname clients-bundle.crt

kubectl -n kafka delete secret strimzi-cluster-clients-ca-cert
kubectl -n kafka delete secret strimzi-cluster-cluster-ca-cert

kubectl -n kafka create secret generic strimzi-cluster-clients-ca-cert --from-file=ca.crt=clients-bundle.crt
kubectl -n kafka create secret generic strimzi-cluster-cluster-ca-cert --from-file=ca.crt=strimzi-bundle.crt --from-file=ca.p12=strimzi-bundle.p12 --from-literal=ca.password=test1234
  
kubectl -n kafka delete secret strimzi-cluster-clients-ca
kubectl -n kafka delete secret strimzi-cluster-cluster-ca

kubectl -n kafka create secret generic strimzi-cluster-cluster-ca --from-file=ca.key=strimzi.key
kubectl -n kafka create secret generic strimzi-cluster-clients-ca --from-file=ca.key=clients.key


kubectl -n kafka label secret strimzi-cluster-cluster-ca-cert strimzi.io/kind=Kafka strimzi.io/cluster=strimzi-cluster
kubectl -n kafka label secret strimzi-cluster-clients-ca-cert strimzi.io/kind=Kafka strimzi.io/cluster=strimzi-cluster
kubectl -n kafka label secret strimzi-cluster-cluster-ca strimzi.io/kind=Kafka strimzi.io/cluster=strimzi-cluster
kubectl -n kafka label secret strimzi-cluster-clients-ca strimzi.io/kind=Kafka strimzi.io/cluster=strimzi-cluster

kubectl -n kafka annotate secret strimzi-cluster-cluster-ca-cert strimzi.io/ca-cert-generation=0
kubectl -n kafka annotate secret strimzi-cluster-cluster-ca strimzi.io/ca-key-generation=0
kubectl -n kafka annotate secret strimzi-cluster-clients-ca-cert strimzi.io/ca-cert-generation=0
kubectl -n kafka annotate secret strimzi-cluster-clients-ca strimzi.io/ca-key-generation=0
```

The Kafka CR (already its in my initial post)

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi-cluster
  labels:
    app: strimzi-cluster
spec:
  kafka:
    replicas: 1
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "DEBUG"
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: "1"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        type: ingress
        tls: true
        configuration:
          bootstrap:
            host: strimzi-cluster-bootstrap.tcp.devops.xxx.xxx.com
            annotations:
              external-dns.alpha.kubernetes.io/hostname: strimzi-cluster-bootstrap.tcp.devops.xxx.xxx.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
          - broker: 0
            host: strimzi-cluster-broker-0.tcp.devops.xxx.xxxx.com
            annotations:
              external-dns.alpha.kubernetes.io/hostname: strimzi-cluster-broker-0.tcp.devops.xxx.xxx.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: "0.3"
      limits:
        memory: 1Gi
        cpu: "0.5"
    storage:
      type: ephemeral
  clusterCa:
    generateCertificateAuthority: false
  entityOperator:
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
    topicOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi
```
