### DISCUSSION TITLE
Is TLS encryption necessary for route listener?

### DISCUSSION THREAD

**Discussion by koktlzz** [strimzi/strimzi-kafka-operator#7541] [Q&A] [answered]
The document said 'Enables TLS encryption for each listener. Default is false. TLS encryption is not required for route listeners' in [Configuring Kafka](https://strimzi.io/docs/operators/in-development/configuring.html#proc-config-kafka-str).

But if I set this field to false:

```yaml
listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: route
        tls: false
```

The cluster operator can't reconcile:

```shell
2022-10-27 03:09:07 WARN  AbstractOperator:516 - Reconciliation #9976(timer) Kafka(kafka/test-ece): Failed to reconcile
io.strimzi.operator.cluster.model.InvalidResourceException: Listener configuration is not valid: [listener external is Route or Ingress type listener and requires enabled TLS encryption]
```

Did I misunderstood the documentation?
