### DISCUSSION TITLE
User Operator overwrites existing Secret data?

### DISCUSSION THREAD

**Discussion by sbalmos** [strimzi/strimzi-kafka-operator#7546] [Q&A]
It seems as though the User Operator overwrites any other data in a referenced existing Secret when processing the addition of a KafkaUser. This is with Entity Operator 0.31.1-kafka-3.2.3

I will have an existing Secret with basically the following data. Note the addition of username and group_id data keys. 

```
apiVersion: v1
kind: Secret
metadata:
  namespace: kafka
  name: reading-user
type: Opaque
data:
  username: reading_user
  password: supersecret
  group_id: reading_glasses
```
In the KafkaUser definition, I have
```
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          name: reading-user
          key: password
```
However, after the KafkaUser is applied, the Secret data has been overwritten. It has the same password value, so obviously the existing password /value/ was used. But the Secret has lost the username and group_id keys.
```
apiVersion: v1
data:
  password: supersecret
  sasl.jaas.config: blahblahblah
kind: Secret
metadata:
  ...
type: Opaque
```
Is this intentional or am I missing something?
```
