### DISCUSSION TITLE
connect to an external listener without authentication

### DISCUSSION THREAD

**Discussion by eslam-gomaa** [strimzi/strimzi-kafka-operator#7547] [Q&A]
Hi

Just to be sure, what's the correct [backend protocol](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#backend-protocol) to use with the external ingress listener ?

and as a Kafka beginner, Is it possible to connect to that external listener without authentication ? ... if so I'll appreciate you if reference an example

```yaml
kafkaCluster:
  version: 3.2.0
  interBrokerProtocolVersion: "3.2"

  kafka:
    replicas: 3
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: true
            prometheus.io/path: /metrics
            prometheus.io/port: "9404"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: ingress
        tls: true
        configuration:
          bootstrap:
            host: "..."
            annotations:
              nginx.ingress.kubernetes.io/ssl-passthrough: true
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          brokers:
          - broker: 0
            host: "..."
            annotations:
              nginx.ingress.kubernetes.io/ssl-passthrough: true
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          - broker: 1
            host: "..."
            annotations:
              nginx.ingress.kubernetes.io/ssl-passthrough: true
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS
          - broker: 2
            host: "..."
            annotations:
              nginx.ingress.kubernetes.io/ssl-passthrough: true
              kubernetes.io/ingress.class: nginx
              nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    config:
      auto.create.topics.enable: false
      delete.topic.enable: true
      num.io.threads: 8
      num.recovery.threads.per.data.dir: 1
      unclean.leader.election.enable: false
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 300Gi
        class: gp2
        deleteClaim: false
    resources:
      requests:
        cpu: 1
        memory: 4Gi
      limits:
        cpu: 2
        memory: 8Gi
    jvmOptions:
      -Xms: 4G
      -Xmx: 4G
....
```
