### DISCUSSION TITLE
How do I make Strimzi to trust my certificate?

### DISCUSSION THREAD

**Discussion by cedar715** [strimzi/strimzi-kafka-operator#7548] [Q&A]
I just want Strimzi to trust my certificate for mTLS. I don't want to replace any of the Client/Cluster CA's. Here are the steps I tried:

1. Generate StrimziClient Keypair 
   
    `keytool -genkeypair -keystore strimziclient.jks -alias strimziclient -storepass changeit`

2. Export cert

    `keytool -exportcert -keystore strimziclient.jks -alias strimziclient -rfc -file strimziclient.pem -storepass changeit`

3. Import Broker CA's into keystore

    ```
    export CLUSTER_NAME=my-cluster    
    kubectl get secret $CLUSTER_NAME-cluster-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 --decode > cluster-ca.crt    
    kubectl get secret $CLUSTER_NAME-clients-ca-cert -o jsonpath='{.data.ca\.crt}' | base64 --decode > clients-ca.crt        
    keytool -import -alias cluster-ca -file cluster-ca.crt -keystore strimziclient.jks -storepass changeit -noprompt    
    keytool -import -alias clients-ca -file clients-ca.crt -keystore strimziclient.jks -storepass changeit -noprompt
    ```

4. Create Secret with strimziclient cert

    `kubectl create secret generic strimziclient --from-file=ca.crt=strimziclient.pem`

5. Configure the broker to trust the certificate  
     ```
     listeners:
          - name: external
            port: 9094
            type: loadbalancer
            tls: true
            authentication:
               type: tls
               tlsTrustedCertificates:
                - secretName: strimziclient
                  certificate: ca.crt
     ```

6. mtls.properties
   ```
   bootstrap.servers=10.108.187.144:9094
   security.protocol=SSL
   ssl.truststore.location=strimziclient.jks
   ssl.truststore.password=changeit
   ssl.keystore.location=strimziclient.jks
   ssl.keystore.password=changeit
   ```

RESULT

`$KAFKA_HOME/bin/kafka-console-producer.sh --broker-list $LOADBALANCER_PUBLIC_IP:9094 --topic $TOPIC_NAME --producer.config mtls.properties` 
>[2022-10-29 22:55:57,694] ERROR [Producer clientId=console-producer] Connection to node -1 (/10.108.187.144:9094) failed authentication due to: Failed to process post-handshake messages (org.apache.kafka.clients.NetworkClient)

**Comment by scholzj** [comment]
You seem to be making up your own fields and expect it to somehow magically work:
```yaml
       authentication:
          type: tls
          tlsTrustedCertificates:
           - secretName: strimziclient
             certificate: ca.crt
```

That is not how it works. There is no `tlsTrustedCertificates` field in the `authentication` section. You have to follow the Strimzi API and use the fields it supports.

The TLS client authentication is based on some trusted CA which is issuing the user certificates. There is nothing like _trsuting your own certificate_ => you always trust some CA. So if you want to use your own CA, then you have to follow the docs and use your own Clients CA.
