### DISCUSSION TITLE
listener certificate renewal

### DISCUSSION THREAD

**Discussion by senthil13** [strimzi/strimzi-kafka-operator#7578] [General]
Hi Admin,

Our Kafka cluster runs with its own listener certificate, like below. This is working fine. 

```
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        type: ingress
        tls: true
        configuration:
          brokerCertChainAndKey:
            secretName: listener-secret
            certificate: listener.crt
            key: listener.key
          bootstrap:
            host: strimzi-cluster-bootstrap.tcp.devops.com
```

Now we need to renew the certificate, but I am unable to find the procedure in the documents (may be I am looking wrong place). I see the renewal procedure/document for the own CA renewal procedure. Please help

Thanks
Senthil
