### DISCUSSION TITLE
Zookeeper and Kafka loglevels not configurable

### DISCUSSION THREAD

**Discussion by vstoppe** [strimzi/strimzi-kafka-operator#7587] [Q&A]
**Describe the bug**
I am trying to set the loglevel for the zookeeper and broker pods to "WARN", but still get the "INFO" logs. I set this in the Kafka CRD as the excerpts shows from the live CRD below:

```
yq .Spec.Zookeeper.Logging kafka-cluster-yaml  -y
Loggers:
  kafka.root.logger.level: WARN
Type: inline

yq .Spec.Kafka.Logging kafka-cluster-yaml  -y
Loggers:
  kafka.root.logger.level: WARN
Type: inline
```

The log4j.properties is set correctly:

```
kafka]$  cat /opt/kafka/custom-config/log4j.properties | grep logger.level
kafka.root.logger.level=WARN
```

Despite the configuration a lot of info logs are produced

```
kubectl logs mx-strimzi-zookeeper-0 --tail 1000  | grep INFO | wc -l
1000

kubectl logs mx-strimzi-kafka-0 --tail 10000  | grep INFO | wc -l
9702
```

**Expected behavior**

I would expect that no INFO logs get produced.

**Environment (please complete the following information):**
 - Strimzi version: 0.29.0
 - Kafka 3.2.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.21
 - Infrastructure: Rancher. 2.6

I think this is related to: [Dynamic configuration of logging doesn't work](https://github.com/strimzi/strimzi-kafka-operator/issues/6999#top)

**Comment by scholzj** [comment]
Kafka and ZooKeeper have many different loggers. I suspect you might need to change all of them to WARN level to get rid of all INFO level messages? The list should be in the docs:
* https://strimzi.io/docs/operators/latest/full/configuring.html#property-kafka-logging-reference
* https://strimzi.io/docs/operators/latest/full/configuring.html#property-zookeeper-logging-reference

The default Log4j config files can be found here: https://github.com/strimzi/strimzi-kafka-operator/tree/main/cluster-operator/src/main/resources ... if needed, you can also use the external logging to provide your own Log4j configuration.

**Reply by vstoppe** [reply]
Thanks for the hints! I studied the blog post "[Dynamically changeable logging levels](https://strimzi.io/blog/2020/11/10/dynamically-changeable-logging/)" and now I have some suggestions for an Update of this artical:
* For configuring the operator you could mention the the log level can also be changed by the helm values.
* Is the information that broker use "log4j" outdated? We noticed a autoload of new log setting.
* Links to the detailed configuration would be helpful in the blogpost.

The example for configuring Kafka broker etc with type inline is misleeding. With this example nothing changes. For other readers, this can be a valid logging configuration for the brokers:

```
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: WARN
        log4j.logger.kafka: WARN
        log4j.logger.org.apache.kafka: WARN
        log4j.logger.state.change.logger: WARN
        log4j.logger.kafka.controller: INFO
```

Now days the blog post is missing the information that zookeeper can be configured in a similar way:

```
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: WARN
```

Kubernetes software is aging faster than a joghurt in the sun. Thanks for the help!
