### DISCUSSION TITLE
Unable to view health status for overall Kafka Cluster

### DISCUSSION THREAD

**Discussion by AAR256** [strimzi/strimzi-kafka-operator#7632] [Q&A]
We're running a Kafka Cluster on version 3.0.0 on AKS. The configuration for the same is below -

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cdt-north-1-kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 3
    resources:
      requests:
        memory: 500Mi
        cpu: "100m"
      limits:
        memory: 600Mi
        cpu: "1"
    listeners:
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            host: cdt-north-1-kafka-cluster-1-bootstrap.net
          brokers:
          - broker: 0
            host: cdt-north-1-kafka-cluster-1-kafka-0.net
          - broker: 1
            host: cdt-north-1-kafka-cluster-1-kafka-1.net
          - broker: 2
            host: cdt-north-1-kafka-cluster-1-kafka-2.net
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    authorization:
      type: simple
      superUsers:
        - admin
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "3.0"
      inter.broker.protocol.version: "3.0"
      default.replication.factor: 3
      min.insync.replicas: 3
      num.partitions: 1
      log.segment.bytes: 1073741824
      log.retention.check.interval.ms: 300000
      num.network.threads: 3
      num.io.threads: 8
      num.recovery.threads.per.data.dir: 1
      socket.send.buffer.bytes: 102400
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      group.initial.rebalance.delay.ms: 0
      replica.fetch.max.bytes: 1048576
      auto.create.topics.enable: false
      delete.topic.enable: true
      offsets.topic.num.partitions: 50
      offsets.commit.required.acks: -1
      queued.max.requests: 500
      replica.socket.receive.buffer.bytes: 65536
      log.roll.ms: 604800000
      log.retention.bytes: 1073741824
      log.retention.ms: 1680000
      log.segment.delete.delay.ms: 60000
      log.cleanup.policy: compact,delete
      log.cleaner.backoff.ms: 15000
      log.cleaner.delete.retention.ms: 86400000
      log.cleaner.dedupe.buffer.size: 134217728
      log.cleaner.io.buffer.load.factor: 0.9
      log.cleaner.threads: 8
      log.cleaner.io.max.bytes.per.second: 1.7976931348623157E308
      message.max.bytes: 1048576
      compression.type: producer
      log.flush.scheduler.interval.ms: 2000
      log.flush.interval.ms: 50000
      log.flush.interval.messages: 100000
      replica.lag.time.max.ms: 500
      auto.leader.rebalance.enable: true
      leader.imbalance.check.interval.seconds: 300
      leader.imbalance.per.broker.percentage: 10
      unclean.leader.election.enable: false
      group.initial.rebalance.delay.ms: 3000
      zookeeper.connection.timeout.ms: 6000
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
        class: kafka-storage
      - id: 1
        type: persistent-claim
        size: 20Gi
        deleteClaim: false
        class: kafka-storage
    template:
      pod:
        tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              strimzi.io/name: cdt-north-1-kafka-cluster-kafka
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 200Mi
        cpu: "100m"
      limits:
        memory: 400Mi
        cpu: "200m"
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: true
      class: zookeeper-storage
    template:
      pod:
        tolerations:
        - key: "kubernetes.azure.com/scalesetpriority"
          operator: "Equal"
          value: "spot"
          effect: "NoSchedule"
        topologySpreadConstraints:
        - maxSkew: 2
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              strimzi.io/name: cdt-north-1-kafka-cluster-zookeeper
  entityOperator:
    tlsSidecar:
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 128Mi
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "100m"
        limits:
          memory: 512Mi
          cpu: "200m"
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "100m"
        limits:
          memory: 512Mi
          cpu: "200m"
  cruiseControl:
    tlsSidecar:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 2Gi
          cpu: "2"
    resources:
      requests:
        memory: 512Mi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "2"
  kafkaExporter:
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 128Mi
    topicRegex: ".*"
    groupRegex: ".*"
```

Is it possible to get http response via endpoint describing the state of Kafka Cluster. Eg. - If cluster is running fine, the endpoint should return 200.
We have tried using Kafka Bridge but it returns the state of the Kafka bridge resource not the cluster, as we tested that by bringing down the Kafka cluster but kafka-bridge-endpoint/healthy returned code 200.
Any help or input here would be appreciated on how to implement this?
