### DISCUSSION TITLE
ACLs config example is incorrect

### DISCUSSION THREAD

**Discussion by sattha** [strimzi/strimzi-kafka-operator#7737] [Q&A] [answered]
**Suggestion / Problem**
Not sure is it my misunderstanding or something... 
for the ACLs configuration example, the "operations" attribute is not an array but it's string value. 

Also, the CRD mention like below..

```
operation:
  type: string
  enum:
  - Read
  - Write
  - Create
  - Delete
  - Alter
  - Describe
  - ClusterAction
  - AlterConfigs
  - DescribeConfigs
  - IdempotentWrite
  - All
  description: "Operation which will be allowed or denied. Supported operations are: Read, Write, Create, Delete, Alter, Describe, ClusterAction, AlterConfigs, DescribeConfigs, IdempotentWrite and All."
```

**Documentation Link**
https://strimzi.io/docs/operators/latest/configuring.html#proc-configuring-kafka-connect-user-authorization-str

AS-IS
```
  authorization:
    type: simple
    acls:
      # access to offset.storage.topic
      - resource:
          type: topic
          name: connect-cluster-offsets
          patternType: literal
        operations:
          - Create
          - Describe
          - Read
          - Write
```

TO-BE
```
  authorization:
    type: simple
    acls:
      # access to offset.storage.topic
      - resource:
          type: topic
          name: connect-cluster-offsets
          patternType: literal
        operation: Create
      - resource:
          type: topic
          name: connect-cluster-offsets
          patternType: literal
        operation: Describe
      - resource:
          type: topic
          name: connect-cluster-offsets
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: connect-cluster-offsets
          patternType: literal
        operation: Write
```
