### DISCUSSION TITLE
metricsConfig change to Zookeeper was not applied without restarting the operator pod

### DISCUSSION THREAD

**Discussion by tgib23** [strimzi/strimzi-kafka-operator#7820] [Q&A]
**Describe the bug**

I've added the following changes to existing clusters' Kafka CRD manifests and applied to several of our clusters including AKS, GKE, and Openshift.

```
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper_metrics_config
          name: jmx-exporter-config-kafka-cluster
```

Then, I observed two kinds of different failure behaviors as well as successfully applied cases.
In both failure cases, Kafka CRD change was applied when observe Kafka CRD.

```
  Zookeeper:
    Metrics Config:
      Type:  jmxPrometheusExporter
      Value From:
        Config Map Key Ref:
          Key:   zookeeper_metrics_config
          Name:  jmx-exporter-config-kafka-cluster
```

In one failure case, Zookeeper pods restart was triggered, but the env `ZOOKEEPER_METRICS_ENABLED` was not set true, and thus metrics was not enabled.
Zookeeper pods seemed to infinitely rolling-restarted, but `ZOOKEEPER_METRICS_ENABLED` was not set true anyways.

In another failure case, even Zookeeper pods restart was not triggered.
I observed the log `Kafka kafka-cluster in namespace kafka was MODIFIED` in operator log, but nothing happened.

In both failure cases, I killed the operator pod and let it restart, then Zookeeper pods were triggered to get restarted with `ZOOKEEPER_METRICS_ENABLED` set true.

I've asked for an advice on this issue in strimzi slack channel, then was advised to report it here.

**To Reproduce**

1. Zookeeper clusters are running without metrics config set.
2. Add metrics config
```
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper_metrics_config
          name: jmx-exporter-config-kafka-cluster
```
3. apply the manifest

**Expected behavior**

Zookeeper is restarted with env var `ZOOKEEPER_METRICS_ENABLED` set true, so that we can see the metrics

**Environment (please complete the following information):**
 - Strimzi version: [0.31.1]
 - Installation method: [YAML files]
 - Kubernetes cluster: [Kubernetes 1.23.11-gke.300 (GKE), 1.23.8 (AKS)]
 - Infrastructure: [GKE, AKS]

**YAML files and logs**

[logs.zip](https://github.com/strimzi/strimzi-kafka-operator/files/10242985/logs.zip)

I've added strimzi operator logs files from two different clusters.

The first one strimzi-aks.log is from AKS cluster, where no zookeeper restart happened.
The second one strimzi-gke.log is from GKE cluster, where Zookeer restart happened, but env var `ZOOKEEPER_METRICS_ENABLED` was not set true anyways.

For the strimzi-aks.log, I applied the change at around 2022-12-15 02:58:20 and there is no logs regarding zookeeper restarts.
For the strimzi-gke.log, I applied the change at around 2022-12-13 00:57:09 and there is logs regarding zookeeper restarts.

It's not likely the difference of AKS and GKE caused different behaviors because I saw the failure with zookeeper restarts in other AKS cluster.
In addition, I saw some successful cases in GKE and Openshift clusters.
