### DISCUSSION TITLE
When do the bootstrap servers for external listeners change?

### DISCUSSION THREAD

**Discussion by Otto45** [strimzi/strimzi-kafka-operator#7860] [Q&A] [answered]
We are running strimzi kafka in an AWS EKS cluster, so when we have EKS perform a k8s or ami upgrade for our managed node group, it will spin up new EC2 instances and drain the old ones. Obviously when this occurs, our bootstrap server list for our external listener will change, as the new EC2 instances for the node group will have different private IPs. We have noticed that our EC2 instances in our node group actually have 3 different private IPs each (currently we're unsure why this is). Would there be any reason the strimzi operator would re-evaluate the IPs used as the bootstrap servers for a listener and change them during a reconciliation run? We have had this happen to us, but we're unsure if something in AWS was tweaked which would cause this, so I want to rule out the strimzi operator behaving in this manner.

Here is the config for our external listener:

```
- name: externtls
  port: 9096
  type: nodeport
  tls: true
  authentication:
    type: tls
  configuration:
    preferredNodePortAddressType: InternalIP
```
