### DISCUSSION TITLE
Nodeport type listeners do not observe the broker id/Host ordering

### DISCUSSION THREAD

**Discussion by sebady** [strimzi/strimzi-kafka-operator#7866] [Q&A] [answered]
We have recently noticed that the broker IDs that are specified in the listeners of nodeport type do not match.    Not sure if this expected behavior with nodeport type or possibly a bug?  This has been seen with Strimzi version 0.30/Kafka3.1.1 (as well as 0.19.0)

For e.g. if we have 3 listeners configured like so
```
  listeners:
    - name: external
      port: 9094
      type: nodeport
      tls: false
      configuration:
        bootstrap:
          nodePort: 30700
        brokers:
           - advertisedHost: kafka-broker-1.ap-northeast-1
            broker: 0
            nodePort: 31110
          - advertisedHost: kafka-broker-2.ap-northeast-1
            broker: 1
            nodePort: 30111
          - advertisedHost: kafka-broker-3.ap-northeast-1
            broker: 2
            nodePort: 30101
```            
We have noticed `broker 0` was scheduled on host `kafka broker 3`.  

We expected the above brokers list to be observed.  Note that we have many Kafka clusters all on the same k8s cluster and clients appear to be connecting sometimes to "wrong" brokers when using just using nodeport IPs/Ports.
