### DISCUSSION TITLE
ca cert has expired

### DISCUSSION THREAD

**Discussion by clhlc** [strimzi/strimzi-kafka-operator#7876] [Q&A]
cert has expired
```shell
subject= /O=io.strimzi/CN=cluster-ca v0
issuer= /O=io.strimzi/CN=cluster-ca v0
notBefore=Jan  5 08:34:48 2022 GMT
notAfter=Jan  5 08:34:48 2023 GMT
```

My Kafka cluster yaml
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator:
      logging:
        loggers:
          rootLogger.level: WARN
        type: inline
  kafka:
    config:
      default.replication.factor: 1
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - authentication:
          type: tls
        name: tls
        port: 9093
        tls: true
        type: internal
      - name: external
        port: 9094
        tls: false
        type: loadbalancer
    logging:
      loggers:
        kafka.root.logger.level: WARN
      type: inline
    replicas: 3
    storage:
      type: jbod
      volumes:
        - deleteClaim: true
          id: 0
          size: 10Gi
          type: ephemeral
    template:
      externalBootstrapService:
        metadata:
          annotations:
            cloud.google.com/load-balancer-type: Internal
      podDisruptionBudget:
        maxUnavailable: 0
    version: 3.1.0
  zookeeper:
    logging:
      loggers:
        zookeeper.root.logger: WARN
      type: inline
    replicas: 3
    storage:
      deleteClaim: true
      size: 10Gi
      type: ephemeral
```

And how to renew cert if cert is expired. Cert is auto generated by cluster operator
