### DISCUSSION TITLE
Setup custom gssapi listener

### DISCUSSION THREAD

**Discussion by jusch23** [strimzi/strimzi-kafka-operator#7887] [Q&A] [answered]
As described in issue [#3088](https://github.com/strimzi/strimzi-kafka-operator/issues/3088 ) kerberos is currently not supported for strimzi. I saw the authentication type "custom" for a listener in the documentation and could imagine a setup like this:

```
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi-cluster-small
spec:
  kafka:
    version: 3.3.1
    replicas: 3
    listeners:
      - name: external
        port: 9093
        type: ingress
        tls: true
        authentication:
          type: custom
          sasl: true
          listenerConfig:
            sasl.enabled.mechanisms: GSSAPI
            sasl.kerberos.service.name: kafka
            # Problems: Setting different listener config for each broker, keytab needs to be mounted
            #gssapi.sasl.jaas.config: com.sun.security.auth.module.Krb5LoginModule required useKeyTab=true storeKey=true keyTab="/opt/kafka/cluster.keytab" principal="kafka/broker-X.myingress.com@MY.REALM.COM";
        configuration:
          class: nginx
          bootstrap:
            host: bootstrap.myingress.com
          brokers:
            - broker: 0
              host: broker-0.myingress.com
            - broker: 1
              host: broker-1.myingress.com
            - broker: 2
              host: broker-2.myingress.com
    jvmOptions:
      javaSystemProperties:
        - name: java.security.krb5.realm
          value: MY.REALM.COM
        - name: java.security.krb5.kdc
          value: my.kdc.com
...
```
For each broker I would create a service principal (kafka/broker-X.myingress.com) and create a keytab which contains entries for all service principals. This "cluster.keytab" should then be mounted in each kafka pod, e.g. at /opt/kafka/.
The following problems I see, for which I have not found a solution yet:

1. It is not possible to configure broker-specific listener configuration. The gssapi.sasl.jaas.config parameter needs to set a principal which contains the broker external ingress hostname (different for each broker)
2. The keytab needs to be mounted in each kafka pod

As written above, I now kerberos is not supported at the moment. However, is there a way to solve this problems in the current strimzi version?
