### DISCUSSION TITLE
Problems with KafkaMirror

### DISCUSSION THREAD

**Discussion by AEncinas19** [strimzi/strimzi-kafka-operator#7893] [Q&A]
Happy new year for everyone.
I'm trying to deploy a kafka distributed system with 2 kafka clusters in the same k8s cluster in order to have a bidirectional replication (replication active/active). To get this, I've deployed two MirrorMaker2 which I've modificated and deployed  from the examples:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2-active
spec:
  version: 3.3.1
  replicas: 1
  connectCluster: "my-cluster"
  clusters:
  - alias: "my-cluster2"
    bootstrapServers: my-cluster2-kafka-bootstrap:9092
  - alias: "my-cluster"
    bootstrapServers: my-cluster-kafka-bootstrap:9092
    config:
      # -1 means it will use the default replication factor configured in the broker
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "my-cluster2"
    targetCluster: "my-cluster"
    sourceConnector:
      config:
        replication.factor: 3
        offset-syncs.topic.replication.factor: 3
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 3
    topicsPattern: ".*"
    groupsPattern: ".*"
```
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
spec:
  version: 3.3.1
  replicas: 1
  connectCluster: "my-cluster2"
  clusters:
  - alias: "my-cluster"
    bootstrapServers: my-cluster-kafka-bootstrap:9092
  - alias: "my-cluster2"
    bootstrapServers: my-cluster2-kafka-bootstrap:9092
    config:
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "my-cluster"
    targetCluster: "my-cluster2"
    sourceConnector:
      config:
        replication.factor: 3
        offset-syncs.topic.replication.factor: 3
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 3
    topicsPattern: ".*"
    groupsPattern: ".*"
```

So, I've created a topic from one kafka pod of my-cluster and when I try to write in that topic in my-cluster2 I get the following error:

>[kafka@my-cluster2-kafka-2 kafka]$ bin/kafka-console-producer.sh --bootstrap-server 10.152.183.217:9092 --topic my-cluster.pruebas3
>p4
>[2023-01-10 10:51:43,534] WARN [Producer clientId=console-producer] Got error produce response with correlation id 6 on topic-partition my-cluster.pruebas3-0, retrying (2 attempts left). Error: NOT_ENOUGH_REPLICAS (org.apache.kafka.clients.producer.internals.Sender)
[2023-01-10 10:51:43,632] WARN [Producer clientId=console-producer] Got error produce response with correlation id 7 on topic-partition my-cluster.pruebas3-0, retrying (1 attempts left). Error: NOT_ENOUGH_REPLICAS (org.apache.kafka.clients.producer.internals.Sender)
[2023-01-10 10:51:43,733] WARN [Producer clientId=console-producer] Got error produce response with correlation id 8 on topic-partition my-cluster.pruebas3-0, retrying (0 attempts left). Error: NOT_ENOUGH_REPLICAS (org.apache.kafka.clients.producer.internals.Sender)
[2023-01-10 10:51:43,837] ERROR Error when sending message to topic my-cluster.pruebas3 with key: null, value: 2 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.NotEnoughReplicasException: Messages are rejected since there are fewer in-sync replicas than required.

Each kafka cluster has 3 kafka replicas and I created the topic on my-cluster with a replication factor of 3.

Also, when I write in my-cluster, all the messages that I write don't appear when I access from my-cluster2, I only can see the topic but not its body.
