### DISCUSSION TITLE
Can't modify the Policy on the MirrorMaker yaml.

### DISCUSSION THREAD

**Discussion by AEncinas19** [strimzi/strimzi-kafka-operator#7898] [Q&A] [answered]
Hello everyone, I'm trying to modify the Policy in order to replicate topics without name changing in my MirrorMaker yaml.
Here is my configuration file:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
spec:
  version: 3.3.1
  replicas: 1
  connectCluster: "my-cluster2"
  clusters:
  - alias: "my-cluster"
    bootstrapServers: my-cluster-kafka-bootstrap:9092
  - alias: "my-cluster2"
    bootstrapServers: my-cluster2-kafka-bootstrap:9092
    config:
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "my-cluster"
    targetCluster: "my-cluster2"
    sourceConnector:
      config:
        replication.factor: 3
        offset-syncs.topic.replication.factor: 3
        sync.topic.acls.enabled: "false"
        refresh.topics.interval.seconds: 60
        "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 3
    topicsPattern: "flows"
    groupsPattern: ".*"

```
However, when I deploy this file it appears: error: error parsing Descargas/strimzi-0.32.0/KafkaMirror2/kafka-mirror-maker-2.yaml: error converting YAML to JSON: yaml: line 34: could not find expected ':'. 
How can I fix it?
