### DISCUSSION TITLE
Messages replicating constantly

### DISCUSSION THREAD

**Discussion by AEncinas19** [strimzi/strimzi-kafka-operator#7899] [Q&A] [answered]
Hello,
I'm using an active/active replication with MirrorMaker. In order to do this, I've created two MakerMirror2, one that replicates from my-cluster to my-cluster 2 and another for the other direction.

When I write a message from one Kafka pod in a cluster, it replicates into the other cluster. However I don't know why the messages are continuosly generating copied data.

Here are my MirrorMaker yamls:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
spec:
  version: 3.3.1
  replicas: 1
  connectCluster: "my-cluster2"
  clusters:
  - alias: "my-cluster"
    bootstrapServers: my-cluster-kafka-bootstrap:9092
  - alias: "my-cluster2"
    bootstrapServers: my-cluster2-kafka-bootstrap:9092
    config:
      # -1 means it will use the default replication factor configured in the broker
      # Number of replicas configuration for each message at target cluster.
      config.storage.replication.factor: 1
      # Number of replicas configuration for each topic at target cluster.
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "my-cluster"
    targetCluster: "my-cluster2"
    sourceConnector:
      config:
        # Replication factor for new topics (default 2)
        replication.factor: 3
        # Replication factor for the internal offset-syncs topic (default 3). The offset syncs topic maps the source and target offsets for replicated topic partitions.
        offset-syncs.topic.replication.factor: 3
        sync.topic.acls.enabled: "false"
        # Frecuency of topic refresh (default 600)
        refresh.topics.interval.seconds: 60
        replication.policy.separator: ""
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
    checkpointConnector:
      config:
      # Replication factor for the internal checkpoints topic (default 3). The checkpoint topic maps the last commited offset in the source and target cluster for replicated topic partitions in each consumer group.
        checkpoints.topic.replication.factor: 3
        replication.policy.separator: ""
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
    topicsPattern: "flows"
    groupsPattern: ".*"
``` 
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2-active
spec:
  version: 3.3.1
  replicas: 1
  connectCluster: "my-cluster"
  clusters:
  - alias: "my-cluster2"
    bootstrapServers: my-cluster2-kafka-bootstrap:9092
  - alias: "my-cluster"
    bootstrapServers: my-cluster-kafka-bootstrap:9092
    config:
      # -1 means it will use the default replication factor configured in the broker
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  mirrors:
  - sourceCluster: "my-cluster2"
    targetCluster: "my-cluster"
    sourceConnector:
      config:
        # Replication factor for new topics (default 2)
        replication.factor: 3
        # Replication factor for the internal offset-syncs topic (default 3). The offset syncs topic maps the source and target offsets for replicated topic partitions.
        offset-syncs.topic.replication.factor: 3
        sync.topic.acls.enabled: "false"
        # Frecuency of topic refresh (default 600)
        refresh.topics.interval.seconds: 60
        replication.policy.separator: ""
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
    checkpointConnector:
      config:
      # Replication factor for the internal checkpoints topic (default 3). The checkpoint topic maps the last commited offset in the source and target cluster for replicated topic partitions in each consumer group.
        checkpoints.topic.replication.factor: 3
        replication.policy.separator: ""
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
    topicsPattern: "flows"
    groupsPattern: ".*"
```

The output of the consumer is the following:
![ReplicatedData](https://user-images.githubusercontent.com/49205996/212052197-8964e6ed-db11-4fa0-be67-115fa31f46cb.png)
