### DISCUSSION TITLE
Not able to set affinity rules.

### DISCUSSION THREAD

**Discussion by abhixops** [strimzi/strimzi-kafka-operator#7907] [Q&A]
Hi, Tried setting up affinity rules in strimzi version 0.31.1, but its not working and giving following error - 
`❌  k8s schema validation error: For field spec.kafka.template: Additional property affinity is not allowed`

I am posting my manifest here - 
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    template:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: memory
                  operator: In
                  values:
                  - high
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  strimzi.io/cluster: "kafka-cluster"
    config:
      default.replication.factor: 2
      delete.topic.enable: true
      inter.broker.protocol.version: '3.2'
      log.retention.hours: 24
      min.insync.replicas: 2
      num.partitions: 3
      offsets.topic.replication.factor: 2
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 2
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    storage:
      type: jbod
      volumes:
        - deleteClaim: false
          id: 0
          size: 500Gi
          type: persistent-claim
    version: 3.2.3
  kafkaExporter:
    groupRegex: '.*'
    topicRegex: '.*'
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    storage:
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
```

Please suggest something.
