### DISCUSSION TITLE
Pods using service account that has no bindings

### DISCUSSION THREAD

**Discussion by roberto-civitas** [strimzi/strimzi-kafka-operator#7933] [Q&A]
I'm currently getting this error:
`User "system:serviceaccount:kafka:civitas-kafka" cannot get resource "nodes" in API group "" at the cluster scope. `
in the kafka pods. After investigating it seems a service account gets created for the cluster, the name of the cluster is "civitas-kafka", thus it creates a service account called "civitas-kafka" to be used by the pods, but this service account has no bindings, hence the permissions errors. This is my cluster definition:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: civitas
  namespace: kafka
spec:
  kafka:
    version: 3.3.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.3"
    rack: 
      topologyKey: topology.kubernetes.io/zone
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

Any ideas?
