### DISCUSSION TITLE
TopicOperator recreates topics after deletion

### DISCUSSION THREAD

**Discussion by blintgit** [strimzi/strimzi-kafka-operator#8000] [Q&A] [answered]
Hi!

We have some microservices which implements a template to create a KafkaTopic. When we uninstall these charts, the kafkatopic managed by the chart first gets deleted but at the time of the next reconciliation it gets recreated by the topicoperator. 

Our kafka configuration is as follows: (using strimzi 0.30.0)

``` yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ...
spec:
  kafka:
    replicas: {{.Values.kafka.replicas }}
    listeners:
...............................................
    authorization:
      type: simple
    storage:
...............................................
    config:
      auto.create.topics.enable: false
      delete.topic.enable: false
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 1 #(live: 3)
    storage:
      type: persistent-claim
      class: managed-premium
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

I have found several (mostly closed) issues regarding this 'behaviour', but non of them discussed the fact that how the       `auto.create.topics.enable: false` and `delete.topic.enable: false` options work together with deleting the KafkaTopic resource. 

I have a feeling that once the `delete.topic.enable` is set to `false` once we delete the KafkaTopic, the topic in kafka cannot be deleted, therefore it recreates the topic, even though `auto.create.topics.enable` is disabled (which might not even be considered, as the topic in kafka context already exists). 

Is it intended to work this way with the above configuration? Do you experience the same?
