### DISCUSSION TITLE
Integrate mTLS and OPA with Strimzi

### DISCUSSION THREAD

**Discussion by mint-lmc** [strimzi/strimzi-kafka-operator#8034] [Q&A]
Hi everyone,
I want  to produce and consume to kafka from an external python client using mTLS for the authentication and OPA for the authorization.
- I followed this tutorial to use OPA https://strimzi.io/blog/2020/08/05/using-open-policy-agent-with-strimzi-and-apache-kafka/
- and the TLS certificates from the Strimzi documentation:  https://strimzi.io/docs/operators/latest/full/configuring.html#certificates-and-secrets-formats-str

Broker configuration:

```
    authorization:
      type: opa
      url: http://10.42.0.208:8181/v1/data/kafka/authz/example/basic/allow
      expireAfterMs: 60000
    config:
      default.replication.factor: 1
      inter.broker.protocol.version: "3.1"
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - authentication:
        type: tls
      name: tls
      port: 9093
      tls: true
      type: internal
    - authentication:
        type: tls
      name: external
      port: 9094
      tls: true
      type: nodeport
```
kafka user:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: john
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
```
I have extracted the user certificates in PEM (.crt) format to use it with the kafka producer in python

Python code for the producer:
```
from kafka import KafkaProducer
import json
from bson import json_util

bootstrap_server = 'localhost:32672'

print("Producing messages to Kafka topic ...")
producer = KafkaProducer(
		       bootstrap_servers=bootstrap_server,
                       security_protocol="SSL",
                       ssl_cafile="ca.crt",
		       ssl_certfile="user.crt",
		       ssl_keyfile="user.key",
                       ssl_password="SPf6WnxZzdRz",
		       ssl_check_hostname=False,
		       value_serializer=lambda v: json.dumps(v).encode('ascii'),
		       key_serializer=lambda v: json.dumps(v).encode('ascii')
			)

producer.send("my-topic",
	       key={"key": 1},
		value={"message":"hello world"}
)
producer.flush()
```

Kafka user:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: matt
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
```
Python code for the consumer:
```
from kafka import KafkaConsumer
import json
from bson import json_util

bootstrap_server = 'localhost:32672'

print("Consuming messages from Kafka topic ...")

consumer = KafkaConsumer(
		 bootstrap_servers=bootstrap_server,
                 ssl_cafile="ca.crt",
		 client_id ="matt",
		 security_protocol="SSL",
		 ssl_certfile="user.crt",
		 ssl_keyfile="user.key",
                 ssl_password= 'ZU9rZkLBrBYF',
		 ssl_check_hostname=False,
		 value_deserializer = lambda v: json.loads(v.decode('ascii')),
		 auto_offset_reset="earliest"
	)
consumer.subscribe(topics='my-topic')
for message in consumer:
  print ("%d:%d: v=%s" % (message.partition,
                          message.offset,
                          message.value))

```

I have tested the kafka producer and consumer in python with the ssl certificates and it s working fine.

I have deployed OPA server and added the OPA policies with Config map following the tutorial. The OPA server is working fine.
Once I add the authorization section to the broker configruation,
```
authorization:
      type: opa
      url: http://10.42.0.208:8181/v1/data/kafka/authz/example/basic/allow
      expireAfterMs: 60000
```
 the producer is failing with this error :
`kafka.errors.KafkaTimeoutError: KafkaTimeoutError: Failed to update metadata after 60.0 secs.`  

- Can we use the client certificates generated by Strimzi (ca.crt,  user.crt, user.key) with an external client like python?
