### DISCUSSION TITLE
MM2: is connectCluster must be same as targetCluster

### DISCUSSION THREAD

**Discussion by tulequ** [strimzi/strimzi-kafka-operator#8067] [General]
I have some question about mirrormaker2
As the title, is connectCluster must be same as targetCluster?
If so, why don't remove connectCluster?

And how to configure more than one targetCluster as below?

To me, document is not clear enough to figure it out

```
  connectCluster: kk-dev2
  clusters:
    - alias: kk-dev1
    - alias: kk-dev2
    - alias: kk-dev3

  mirrors:
    - sourceCluster: kk-dev1
      targetCluster: kk-dev2
    - sourceCluster: kk-dev2
      targetCluster: kk-dev1
    - sourceCluster: kk-dev2
      targetCluster: kk-dev3
```

Thank for help
