### DISCUSSION TITLE
Help to understand how scram-sha-512 auth works

### DISCUSSION THREAD

**Discussion by ginwakeup** [strimzi/strimzi-kafka-operator#8074] [Q&A] [answered]
Hey,

Following my question the other day, I've now setup scram-sha-512 authentication on the kafka cluster external listeners:

```
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        authentication:
          type: scram-sha-512
```

Then I created an user with same auth type:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: user
  labels:
    strimzi.io/cluster: messaging
spec:
  authentication:
    type: scram-sha-512
```

And I am using it to connect from a python consumer:

```
from kafka import KafkaConsumer


sasl_mechanism = 'SCRAM-SHA-512'

# To consume latest messages and auto-commit offsets
consumer = KafkaConsumer('test',
                         group_id='test',
                         auto_offset_reset='earliest',
                         bootstrap_servers=['******'],
                         sasl_plain_username="user",
                         sasl_mechanism=sasl_mechanism,
                         security_protocol="SASL_SSL",
                         sasl_plain_password="******"
                         )
...

```

Kafka gives me an error on the handshake:

```
2023-02-07 22:32:36,755 INFO [SocketServer listenerType=ZK_BROKER, nodeId=1] Failed authentication with /1****128 (channelId=1****.16:9094-1*****.128:45471-7) (Failing SASL authentication due to invalid receive size) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-1-ListenerName(EXTERNAL-9094)-SASL_PLAINTEXT-16]
```

I am trying to understand few things here to properly configure it:

- Do I have to use SSL even if the auth type is set to scram-sha-512? Do I need to provide certificates from the python client when I connect to the listeners?
- If so, what certificates can I use that are generated from the operator? `<cluster>-clients-ca`?
- I've tried to set `tls: true` on the `kafka-cluster.yaml`, but still I am not sure I understand what certificates then I have to pass from the clients, if any at all.

Thanks
