### DISCUSSION TITLE
Error with Kafka Connect Build | x509: certificate signed by unknown authority

### DISCUSSION THREAD

**Discussion by dttl-oburgess** [strimzi/strimzi-kafka-operator#8134] [General]
Hi,

I am attempting to use the connect build feature (yaml below). I am pushing to a docker hub repository with a docker credentials secret which appears to be working correctly. However I am running into the following error:
```
INFO[0000] Retrieving image manifest quay.io/strimzi/kafka:0.33.1-kafka-3.3.2
INFO[0000] Retrieving image quay.io/strimzi/kafka:0.33.1-kafka-3.3.2 from registry quay.io
error building image: Get "https://quay.io/v2/": x509: certificate signed by unknown authority
```

Is anyone able to assist? Thanks in advance!!
```
build:
    output:
      type: docker
      image: docker.io/xxxx/datalake-poc:latest
      pushSecret: oburgess-registry-secret
    plugins:
      - name: debezium-postgres-connector
        artifacts:
          - type: tgz
            url: https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.1.1.Final/debezium-connector-postgres-2.1.1.Final-plugin.tar.gz
            sha512sum: 962a12151bdf9a5a30627eebac739955a4fd95a08d373b86bdcea2b4d0c27dd6e1edd5cb548045e115e33a9e69b1b2a352bee24df035a0447cb820077af00c03
```
