### DISCUSSION TITLE
Using custom certitifcate as User Certificate

### DISCUSSION THREAD

**Discussion by rajjaiswalsaumya** [strimzi/strimzi-kafka-operator#8163] [General]
Hi, i am trying to make strimzi Kafka use my CSR-created certificate as the client wants their certificate to use used for their use instead of one created by Strimzi. In our case, we have 3 products that want the same behavior for security reasons they do not want to share private key of theirs and want strimzi to use their cert. I initially thought that I will ask the Strimzi operator to create certs, pause reconciliation, sign the CSR with Strimzi-provided CA, and recreate the user secret, using this new Certificate.
The moment, I tried this and enabled reconciliation for the custom resource KafkaUser, we see that the secret was automatically modified by Strimzi and the key was added to the secret. I dont want to stop using KafkaUser CRD, as otherwise, i  will have to manage ACL on my own. 
Is there a better way to use a custom user cert with Strimzi?
PS: I am not trying to change CA, which is mentioned all across in Strimzi docs to use custom CA.

**Comment by scholzj** [comment]
If you want to manage your own TLS certificates for TLS client authentication, you can use the `type: tls-external` authentication. In such case, you have to generate a certificate signed by the Clients CA on your own (typically, this is used with a custom Clients CA since it makes not much sense to use it with the Strimzi Clients CA). The User OPerator will only manage your ACLs and Quotas.

**Reply by rajjaiswalsaumya** [reply]
Do you have any sample for this ?

**Reply by scholzj** [reply]
No, but its quite simple, you just change the `type` field. It is also covered by the docs.

**Reply by rajjaiswalsaumya** [reply]
It would be great if you can link the doc's exact URL here for future reference for others. Btw I searched docs and didn't find resources to change just client cert. May be I am not able to find it.

**Reply by scholzj** [reply]
Sorry, I'm confused ... You didn't find docs for what?

**Reply by rajjaiswalsaumya** [reply]
Was looking to use my cert as a user cert. Found it here. https://strimzi.io/docs/operators/in-development/deploying.html#mtls_authentication_using_a_certificate_issued_outside_the_user_operator

**Reply by scholzj** [reply]
You cannot use your own user certificate just like that. You have to use your own Clients CA and use the CA to issue your certificate.

**Reply by rajjaiswalsaumya** [reply]
I checked code and realized i can let strimzi create a cluster and clients ca and create a cert signed by the ca generated by strimzi when setting authentication type: tls-external

**Reply by rajjaiswalsaumya** [reply]
Can you give me the exact openssl commands that are run during cert generation by strimzi?

**Reply by scholzj** [reply]
No, I cannot. I do not know them out of my head. They will be in the `certificate-manager` module. But I do not understand how they are relevant.

**Reply by rajjaiswalsaumya** [reply]
So, I am currently doing POC to try creating my own cert and sign with Strimzi CA, then try to connect to Kafka and ensure strimzi does not change them back. If this all works, then i am good and can say I am able to use my custom cert as a user cert for strimzi. Hence was looking for exact commands to run that is run my strimzi

**Reply by scholzj** [reply]
Well, you can search for them in the code. But if you google one of the many guides on how to do that, it will be probably easier.

**Reply by rajjaiswalsaumya** [reply]
Thanks, I tried that, why strimzi is deleting my secret although the authentication type is marked as tls-external for my user? Here is my config and i am trying with user `devops-kafka-user`

```
    users:
      - userName: devops-kafka-user # Convention: <product-id>-<deployment-id>-<region>-<env>-sedjetstream-ccdf
        authenticationType: tls-external # ### tls, scram-sha-512
        #   ### List of ACL rules required for various topics for the given user
        #   ### resourceType: topic/group/cluster/transactionalId
        #   ### resourceName(OPTIONAL): name of the resource type. Use an asterisk (*) to allow or deny the operation from all specific to the mentioned resource type.
        #   ### resourcePatternType(OPTIONAL): literal/prefix
        #   ### operation: operations such as Read/Write/Delete/Describe/All etc.,
        #   ### ruleType(OPTIONAL): allow/deny
        #   ### host(OPTIONAL): remote host from which the rule is allowed or denied. Use an asterisk (*) to allow or deny the operation from all hosts.
        acls:
          - resourceType: topic
            resourceName: "devops-kafka-bucket-sink"
            resourcePatternType: "prefix"
            operation: All
            ruleType: allow
          - resourceType: topic
            resourceName: "devops-kafka-input"
            resourcePatternType: "prefix"
            operation: Write
            ruleType: allow
          - resourceType: group
            resourceName: "*"
            resourcePatternType: "literal"
            operation: All
            ruleType: allow
            host: "*"
      - userName: devops-kafka-all-access-user # Convention: <product-id>-<deployment-id>-<region>-<env>-sedjetstream-ccdf
        authenticationType: tls # ### tls, scram-sha-512
        #   ### List of ACL rules required for various topics for the given user
        #   ### resourceType: topic/group/cluster/transactionalId
        #   ### resourceName(OPTIONAL): name of the resource type. Use an asterisk (*) to allow or deny the operation from all specific to the mentioned resource type.
        #   ### resourcePatternType(OPTIONAL): literal/prefix
        #   ### operation: operations such as Read/Write/Delete/Describe/All etc.,
        #   ### ruleType(OPTIONAL): allow/deny
        #   ### host(OPTIONAL): remote host from which the rule is allowed or denied. Use an asterisk (*) to allow or deny the operation from all hosts.
        acls:
          - resourceType: topic
            resourceName: "*"
            resourcePatternType: "literal"
            operation: All
            ruleType: allow
          - resourceType: group
            resourceName: "*"
            resourcePatternType: "literal"
            operation: All
            ruleType: allow
            host: "*"
```
