### DISCUSSION TITLE
Cruise Control, can it be made more aggressive?

### DISCUSSION THREAD

**Discussion by craiglservin** [strimzi/strimzi-kafka-operator#8191] [Q&A]
I've been trying to get Cruise Control to balance the disk use on an 8 broker cluster.   Each broker has 2000G of storage, and  7 of the brokers were relatively close in disk use having 1.5 TB free, one of the brokers only has 320G free.  Looking at the topics/partitions/replicas there does not seem to be any reason why things could not be balanced.

I've tried pealing away most of the goals that might interfere with replica movement:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: full-rebalance
  labels:
    strimzi.io/cluster: app
spec:
  skipHardGoalCheck: true
  goals:
    - RackAwareGoal
    - DiskUsageDistributionGoal
    - DiskCapacityGoal
  replicaMovementStrategies:
    - PrioritizeSmallReplicaMovementStrategy
```

When it comes up with a proposal, it happily improves things a little bit.  But, it makes almost no difference.  I'm just wondering if I missed something obvious that is causing CC to not be as aggressive as I would like.
