### DISCUSSION TITLE
MirrorMaker 2.0 | mirror topic called "A" from source cluster to topic called "B" in destination cluster

### DISCUSSION THREAD

**Discussion by orbar1** [strimzi/strimzi-kafka-operator#8194] [General]
Hey guys how are you?
I did some searching regarding the title, but I couldn't find a complete answer wether I can replicated a topic called say "my-topic" from kafka cluster A to a topic called "my-topic-mirrored" in kafka cluster B.
I did see some info regarding that in MM 2.0 and it makes me believe I can do it, which is a thing wasn't possible using previous MM version.

Could you please provide me with some data and help me figure this out?
I am using strimzi and would love to see how would you configure such a thing if that's actually possible ([say something like that](https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/mirror-maker/kafka-mirror-maker-2.yaml)), thank you! : )

**Comment by scholzj** [comment]
You would probably need to write your own Replication Policy. You can check the existing policies in Kafka source codes as inspiration.

**Reply by orbar1** [reply]
thank you mate! 
woud you find something like this valid base on **[that example](https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/mirror-maker/kafka-mirror-maker-2-custom-replication-policy.yaml)**:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
spec:
  version: 3.4.0
  replicas: 1
  connectCluster: "cluster-b"
  clusters:
  - alias: "cluster-a"
    bootstrapServers: 1.1.1.1:9092
  - alias: "cluster-b"
    bootstrapServers: 2.2.2.2:9092
    config:
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "cluster-a"
    targetCluster: "cluster-b"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
        replication.policy.separator: ""
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
        replication.policy.separator: ""
        replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
    topics:
      - name: "topic-a"
        targetTopic: "topic-b"
    groupsPattern: ".*"
```
