### DISCUSSION TITLE
Creation of KafkaUser is not creating the secret

### DISCUSSION THREAD

**Discussion by adcoder007** [strimzi/strimzi-kafka-operator#8272] [Q&A]
I am creating a kafka user using below yaml which was suppose to create a secret in Kubernetes. But I can see the KafkaUser got created but not the secret

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  namespace: kafka
  name: kafka-user
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operation: All
      - resource:
          type: group
          name: "*"
          patternType: literal
        operation: All
      - resource:
          type: cluster
          name: "*"
          patternType: literal
        operation: All
      - resource:
          type: transactionalId
          name: "*"
          patternType: literal
        operation: All
```
