### DISCUSSION TITLE
Strimzi standalone user operator and Java heap space errors

### DISCUSSION THREAD

**Discussion by jslusher** [strimzi/strimzi-kafka-operator#8286] [Q&A]
I'm trying to deploy a standalone user operator and I'm running into an issue with java heap space.

I currently have the following allocated to my pods:
```
          resources:
            limits:
              memory: 2Gi
              cpu: 500m
            requests:
              memory: 2Gi
              cpu: 500m
```

If I omit `STRIMZI_JAVA_OPTS` from my Deployment, the operator starts up but then fails:
```
Terminating due to java.lang.OutOfMemoryError: Java heap space
```

If I try setting `STRIMZI_JAVA_OPTS` to any variation of the following according to the user operator docs: 
```
          - name: STRIMZI_JAVA_OPTS
            value: "-Xmx=512M -Xms=256M"
```

I get the following error:
```
Invalid maximum heap size: -Xmx=512M
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

It seems to be a problem with whichever I set first, so if I set `Xmx=512M` first I get the error above, but if I set `Xms=256M` first it complains about that setting instead. I wonder if it's an issue of ordering in the java command. This is what it looks like with the settings: 

```
java -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Xmx=512M -Xms=256M -Dvertx.cacheDirBase=/tmp/vertx-cache -Djava.security.egd=file:/dev/./urandom '-Xlog:gc*:stdout:time' -XX:NativeMemoryTracking=summary -XX:+ExitOnOutOfMemoryError -XX:MinRAMPercentage=15 -XX:MaxRAMPercentage=20 -classpath .....
```
