### DISCUSSION TITLE
How to configure loadbalancer type in AWS with lets-encrypt certificate

### DISCUSSION THREAD

**Discussion by jslusher** [strimzi/strimzi-kafka-operator#8336] [Q&A] [answered]
I have the following configuration for my scram listener:

```yaml
    listeners:
    - authentication:
        type: scram-sha-512
      configuration:
        bootstrap:
          alternativeNames:
          - strimzi-kafka-broker-0.staging.company.com
          - strimzi-kafka-broker-1.staging.company.com
          - strimzi-kafka-broker-2.staging.company.com
          annotations:
            external-dns.alpha.kubernetes.io/hostname: strimzi-kafka-bootstrap.staging.company.com
            external-dns.alpha.kubernetes.io/ttl: "60"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
            service.beta.kubernetes.io/aws-load-balancer-type: external
        brokerCertChainAndKey:
          certificate: tls.crt
          key: tls.key
          secretName: strimzi-kafka-tls
        brokers:
        - annotations:
            external-dns.alpha.kubernetes.io/hostname: strimzi-kafka-broker-0.staging.company.com
            external-dns.alpha.kubernetes.io/ttl: "60"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
            service.beta.kubernetes.io/aws-load-balancer-type: external
          broker: 0
        - annotations:
            external-dns.alpha.kubernetes.io/hostname: strimzi-kafka-broker-1.staging.company.com
            external-dns.alpha.kubernetes.io/ttl: "60"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
            service.beta.kubernetes.io/aws-load-balancer-type: external
          broker: 1
        - annotations:
            external-dns.alpha.kubernetes.io/hostname: strimzi-kafka-broker-2.staging.company.com
            external-dns.alpha.kubernetes.io/ttl: "60"
            service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
            service.beta.kubernetes.io/aws-load-balancer-scheme: internal
            service.beta.kubernetes.io/aws-load-balancer-type: external
          broker: 2
      name: scram
      port: 9096
      tls: true
      type: loadbalancer
```

I'm trying to get a avro-schema-registry cluster to connect to it by configuring its bootstrap setting like this:
```yaml
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: SASL_SSL://strimzi-kafka-broker-0.staging.company.com:9096,strimzi-kafka-broker-1.staging.company.com:9096,strimzi-kafka-broker-2.staging.company.com:9096
```

The certificate specified in `brokerCertChainAndKey` looks like this: 
```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: strimzi-kafka-sdlc
spec:
  secretName: strimzi-kafka-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - strimzi-kafka-bootstrap.staging.company.com
  - strimzi-kafka-broker-0.staging.company.com
  - strimzi-kafka-broker-1.staging.company.com
  - strimzi-kafka-broker-2.staging.company.com
```

I get the following error from the avro server:
```
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching k8s-strimzik-myclust-f4784b7673-7xxxxxxxxxxxxxx.elb.us-west-2.amazonaws.com found.
```
Do I need to specify the ELB hostnames in my certificate? I was under the impression that this wouldn't need them since the hostnames in the bootstrap configuration is for the hosts in the domain I have the certificate for.
