### DISCUSSION TITLE
Kafka cluster could not create pvc while different namespace with kafka operator

### DISCUSSION THREAD

**Discussion by chary1112004** [strimzi/strimzi-kafka-operator#8414] [Q&A]
Hi,

We have tried install **kafka operator** in namespace **kafka**. And **kafka cluster** in namespace **kafka-dev**.

1) **Kafka operator**: is installed with helm chart https://artifacthub.io/packages/helm/strimzi/strimzi-kafka-operator

```
helm install my-strimzi-kafka-operator strimzi/strimzi-kafka-operator --version 0.34.0 -n kafka
```

with value file
```
watchNamespaces: [kafka-dev]
```

2) **Kafka cluster**: We could see that kafka zookeeper is provision however there is message that no pvc is created.
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.4.0
    replicas: 3
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      num.io.threads: 8
      num.network.threads: 5
      num.partitions: 1
      num.replica.fetchers: 2
      message.max.bytes: 15728640
      replica.fetch.max.bytes: 15728640
      replica.fetch.response.max.bytes: 15728640
      replica.lag.time.max.ms: 30000
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 102400
      unclean.leader.election.enable: true
      zookeeper.session.timeout.ms: 18000
      inter.broker.protocol.version: "3.4"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 20Gi
          class: kafka-sc-gp2
          deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 30Gi
      class: kafka-sc-gp2
      deleteClaim: false
  entityOperator:
    topicOperator:
      watchedNamespace: tenant1
    userOperator:
      watchedNamespace: tenant1
```

```
$ kubectl get pods -n kafka-dev

NAME                        READY   STATUS    RESTARTS   AGE
kafka-cluster-zookeeper-0   0/1     Pending   0          27m
kafka-cluster-zookeeper-1   0/1     Pending   0          27m
kafka-cluster-zookeeper-2   0/1     Pending   0          27m

$ kubectl get pvc -n kafka-dev
No resources found in kafka-dev namespace.
```

![image](https://user-images.githubusercontent.com/76929085/233032014-d99127b8-6e20-4d62-a901-d161bd26ce4e.png)

Any solution to resolve this issue would be very much appreciated.

Thanks!
