### DISCUSSION TITLE
Application  facing issue while connecting with 9094 port where TLS is enabled with cert-manager integration

### DISCUSSION THREAD

**Discussion by amitdrana** [strimzi/strimzi-kafka-operator#8507] [General]
Hi,
I have integrated the cert-manager with Kafka on the 9094 port; everything is working fine from Kafka's end, but when applications connect to 9094 with Let's Encrypt CA certificates and user keys, they is facing the following issue:
 
` o.a.k.c.networkclient: [AdminClient clientId=kafka-ui-admin-1683812394-302] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 8614 ms.2023-05-11 13:40:19,943 INFO  [kafka-admin-client-thread | kafka-ui-admin-1683812394-302] o.a.k.c.NetworkClient: [AdminClient clientId=kafka-ui-admin-1683812394-302] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 16757 ms.2023-05-11 13:40:24,385 INFO  [kafka-admin-client-thread | kafka-ui-admin-1683812394-302] o.a.k.c.a.i.AdminMetadataManager: [AdminClient clientId=kafka-ui-admin-1683812394-302] Metadata update failedorg.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call. Call: fetchMetadata`

but working fine with the strimzi Kafka CA certificate and user keys on the 9093 port, where TLS is also enabled.

**Comment by scholzj** [comment]
I guess you might need to share the configs of the Kafka cluster and of the client - not sure it is possible to get some useful info just from this error message.

**Comment by amitdrana** [comment]
Here is the Kafka cluster config:

kafka-cluster.yaml

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-dev
  namespace: mfsa-kafka
spec:
  kafka:
    version: 3.3.2
    replicas: 3
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
         type: tls
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
         type: tls
        configuration:
          bootstrap:
           annotations:
             service.beta.kubernetes.io/aws-load-balancer-type: nlb
             service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
             service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0571cbb4ba01f0fff
             service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0edac95e203d28e95
             external-dns.alpha.kubernetes.io/hostname: bootstrap.kafka.dev.apimfsafrica.com
             external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
          - broker: 0
            annotations:
                external-dns.alpha.kubernetes.io/hostname: broker-0.kafka.apimfsafrica.com.
                external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 1
            annotations:
                 external-dns.alpha.kubernetes.io/hostname: broker-1.kafka.dev.apimfsafrica.com.
                 external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 2
            annotations:
               external-dns.alpha.kubernetes.io/hostname: broker-2.kafka.dev.apimfsafrica.com
               external-dns.alpha.kubernetes.io/ttl: "60"
          brokerCertChainAndKey:
            secretName: kafka-development-lets-encrypt
            certificate: tls.crt
            key: tls.key
    template:
      pod:
       tolerations:
       - key: "mfsa-kafka"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"

       affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - KafkaOnDemand
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.3"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 200Gi
        class: kafka-storage
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      class: kafka-storage
      deleteClaim: false
    template:
     pod:
       tolerations:
       - key: "mfsa-kafka"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"

       affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - KafkaOnDemand
  entityOperator:
    topicOperator: {}
    userOperator: {}

```

Kafka-user.yaml

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
 name: kafkaui-user
 namespace: mfsa-kafka
 labels:
   # Cluster name set previously
   strimzi.io/cluster: kafka-dev
spec:
 authentication:
   type: tls
 authorization:
   type: simple
   acls:
   # Kafka Connects internal topics used to store configuration, offsets or status
     # Example consumer Acls for topic my-topic using consumer group my-group
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Describe
          - Read
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Read
        host: "*"
      # Example Producer Acls for topic my-topic
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
```


and I am trying to use provectus Kafka UI with the following config


`docker run -p 8080:8080 \
    -v "$(pwd)"/SSL_STORE_FOLDER/client.keystore.p12:/client.keystore.p12:ro \
    -v "$(pwd)"/SSL_STORE_FOLDER/client.truststore.jks:/server.truststore.jks:ro \
    -e KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=bootstrap.kafka.dev.apimfsafrica.com:443 \
    -e KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SSL \
    -e KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION=/server.truststore.jks \
    -e KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_PASSWORD=asdf1234 \
    -e KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_LOCATION=/client.keystore.p12 \
    -e KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_PASSWORD=asdf1234 \
    -e KAFKA_CLUSTERS_0_PROPERTIES_SSL_KEYSTORE_TYPE=PKCS12 \
    -d provectuslabs/kafka-ui:latest
`

**Reply by scholzj** [reply]
I think you are using the wrong port -> you seem to configure the client with `443` but the `loadbalancer` listener is using `9094`. So I think that needs to be changed.

**Reply by amitdrana** [reply]
I am facing the following error while changing the port to 443.

```

# kafkas.kafka.strimzi.io "kafka-dev" was not valid:
# * spec.kafka.listeners[2].port: Invalid value: 443: spec.kafka.listeners[2].port in body should be greater than or equal to 9092
#
```
I configure Kafka via the following document.
https://strimzi.io/blog/2021/05/07/deploying-kafka-with-lets-encrypt-certificates/

and also using NLB with public IP attached so that I can whitelisted the IP..

**Reply by scholzj** [reply]
You cannot change the port to 443 in the Kafka configuration. You have to configure the client to use 9094.

**Reply by amitdrana** [reply]
Facing certificate error while changing port to 9094

NOTE: I have user kafka-user crt and pem key with tls.crt from let encrypt certificate. is this correct

`2023-05-13 14:52:34,762 INFO  [kafka-admin-client-thread | kafka-ui-admin-1683989553-1] o.a.k.c.m.Metrics: Metrics reporters closed
2023-05-13 14:52:34,763 ERROR [parallel-1] c.p.k.u.s.StatisticsService: Failed to collect cluster Default info
java.lang.IllegalStateException: Error while creating AdminClient for Cluster Default
        at com.provectus.kafka.ui.service.AdminClientServiceImpl.lambda$createAdminClient$5(AdminClientServiceImpl.java:53)
        at reactor.core.publisher.Mono.lambda$onErrorMap$28(Mono.java:3773)
        at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94)
        at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onError(MonoPeekTerminal.java:258)
        at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onError(FluxMap.java:265)
        at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onError(Operators.java:2210)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
        at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:180)
        at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:278)
        at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:187)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: org.apache.kafka.common.errors.SslAuthenticationException: Failed to process post-handshake messages
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: certificate_unknown
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:358)
        at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:204)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736)
        at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506)
        at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482)
        at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679)
        at org.apache.kafka.common.network.SslTransportLayer.read(SslTransportLayer.java:576)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:95)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:452)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:402)
        at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:674)
        at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:576)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:560)
        at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1415)
        at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1346)
        at java.base/java.lang.Thread.run(Thread.java:833)
2023-05-13 14:52:34,766 DEBUG [parallel-1] c.p.k.u.s.ClustersStatisticsScheduler: Metrics updated for cluster: Default
`

**Reply by scholzj** [reply]
I guess you would need to explain how did you created the keystore and truststore.

**Comment by amitdrana** [comment]
openssl pkcs12 -export       \
    -inkey user.key       \
    -in user.cert         \
    -out client.keystore.p12 \
    -name kafka-user

keytool -import  \
    -file ca.crt\
    -alias CA    \
    -keystore client.truststore.jks

User.key and user.crt i get from secret created by kafkauser.

And ca.crt i get from secret created by lets encrypt certificate.(tls.crt)



Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Reply by scholzj** [reply]
If you use Let's Encrypt, the truststore should not be needed really, as the certificate should be trusted anyway. But I guess the problem seems to be more in the user certificate rather than in the trustsstore.

**Reply by amitdrana** [reply]
Yes . I think so.
 As i tried to user.key user.crt and strimzi ca.crt to 9093 port where its works as that port not configured with let’s encrypt.  Its means strimzi local CA authorise it.
 Do you know how i can sign user key with lets encrypt CA.
May be i need to create user.crt with lets encrypt ca.

**Reply by scholzj** [reply]
You cannot sign a user certificate with Let's Encrypt as that is used for server certificates. The truststore / broker certificates and the client certificates are separate. So if the user cert works on the 9093 port, it should be correct and the problem has to be in your truststore. It is hard to say without a complete logs. Maybe you can try to:
a) remove the truststore as it should not be needed with Let's Encrypt normally
b) you can try to use `openssl s_client` to see what certificates does the cluster actually use as there can be also some other issue which connects you elsewhere etc.
c) Assuming the client is in Java, You can use the Java system property `-Djavax.net.debug=ssl` to get more TLS debug information.

**Reply by amitdrana** [reply]
Here are the logs for OpenSSL s_client.
Also, I am setup this up from the following document but find that you have setup it up at 9094 and test the OpenSSL client to the 443 port. is there any specific reason
`https://strimzi.io/blog/2021/05/07/deploying-kafka-with-lets-encrypt-certificates/`

and I try to remove the  truststore cert but find an error certificate error

Also, I am using NLB not ALB ..

```
`mit@BASTION-SERVER:~/mfsa-cicd/mfsa-dev-cluster/kafka/akhq-kafka$ openssl s_client -connect bootstrap.kafka.dev.apimfsafrica.com:9094 -servername bootstrap.kafka.dev.apimfsafrica.com
CONNECTED(00000003)
depth=2 C = US, O = (STAGING) Internet Security Research Group, CN = (STAGING) Pretend Pear X1
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=1 C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
verify return:1
depth=0 CN = bootstrap.kafka.dev.apimfsafrica.com
verify return:1
---
Certificate chain
 0 s:CN = bootstrap.kafka.dev.apimfsafrica.com
   i:C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: May 10 14:57:59 2023 GMT; NotAfter: Aug  8 14:57:58 2023 GMT
 1 s:C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
   i:C = US, O = (STAGING) Internet Security Research Group, CN = (STAGING) Pretend Pear X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
 2 s:C = US, O = (STAGING) Internet Security Research Group, CN = (STAGING) Pretend Pear X1
   i:C = US, O = (STAGING) Internet Security Research Group, CN = (STAGING) Doctored Durian Root CA X3
   a:PKEY: rsaEncryption, 4096 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 20 19:14:03 2021 GMT; NotAfter: Sep 30 18:14:03 2024 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFfjCCBGagAwIBAgITAPoPmaBbxvXMGrk1dgrEWdBzpTANBgkqhkiG9w0BAQsF
ADBZMQswCQYDVQQGEwJVUzEgMB4GA1UEChMXKFNUQUdJTkcpIExldCdzIEVuY3J5
cHQxKDAmBgNVBAMTHyhTVEFHSU5HKSBBcnRpZmljaWFsIEFwcmljb3QgUjMwHhcN
MjMwNTEwMTQ1NzU5WhcNMjMwODA4MTQ1NzU4WjAvMS0wKwYDVQQDEyRib290c3Ry
YXAua2Fma2EuZGV2LmFwaW1mc2FmcmljYS5jb20wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQC10/wkoO0GegY8LhHukT4fsorxfk3DMEFRxhtcF7piaCry
xnt9l/gvsS2uFdewucelN4payg9Brwr7iovTXloSw7N2KIXgbMHgbb1KPsaZGCG8
5YMVUSHe+/gvaMb8SsYlnxCAW+WfesTdUJgzAJW0N0IbSJCHSMSZCnIwVHOuAwTU
9hXtODBIcPTBPr0026gUdS1VYGFdx1gKkqn8akz/QMDeDk5DxTi4Tt5Cnf01cDDi
mLuixlSjhstpNX5N4kHV/VWSs1ZuOr2j8eq4TIJywjvXFQzbOKhbzgO+/gbGLf7N
BInjDEGGfTmBVxFxPcSCJ7Ar0kv7/XOZfjV+OY47AgMBAAGjggJnMIICYzAOBgNV
HQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1Ud
EwEB/wQCMAAwHQYDVR0OBBYEFOlMacbUUcmvHiDeAvV4j5wKbhy9MB8GA1UdIwQY
MBaAFN5yekjfMcOmUN+fhSPfVzdLXS5lMF0GCCsGAQUFBwEBBFEwTzAlBggrBgEF
BQcwAYYZaHR0cDovL3N0Zy1yMy5vLmxlbmNyLm9yZzAmBggrBgEFBQcwAoYaaHR0
cDovL3N0Zy1yMy5pLmxlbmNyLm9yZy8wLwYDVR0RBCgwJoIkYm9vdHN0cmFwLmth
ZmthLmRldi5hcGltZnNhZnJpY2EuY29tMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcG
CysGAQQBgt8TAQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5
cHQub3JnMIIBBAYKKwYBBAHWeQIEAgSB9QSB8gDwAHYAFuhpwdGV6tfD+Jca4/B2
AfeM4badMahSGLaDfzGoFQgAAAGIBmI1bwAABAMARzBFAiAPas7t73/oY2K1hCOB
jLTyNSYXY4k2WrBqKADdWdl3HgIhAOcA+b+wT+wUSWnP7mYUFi53FRc3Og/pjkfP
0PWTVj6wAHYAsMyD5aX5fWuvfAnMKEkEhyrH6IsTLGNQt8b9JuFsbHcAAAGIBmI1
OgAABAMARzBFAiBLhId/04y5CWophShsXEfofxDxdptsG3SLqsuHA4EW0QIhANxq
ZxtIHtGOKlC59BYp8443mQcWHU+FhW/cwcGPgFNeMA0GCSqGSIb3DQEBCwUAA4IB
AQAD+1kVkFv3AF91lQ1QynBru6F5W9ghjxJsyEd6Yff0uXnBu3Hj/WwrbsMc3/Py
4B5u0T6YGOeegPWxx5/7N5FNd8hnBquKcUk0wBCJIOuOHPff/Or/j5GXzuZZYQ8N
cUSFl/cKHswtsJ7cTsN6RZK+9u3BviAuG6NSAWZPM4n9C/PZ0DsXAZ33/zW0nNWw
gTlMwHs69R+m/BNjF2o1KD9SuLPivsHqzkIf74YKPBid1fKHUYFQaP6zDEw9ri4E
2UHG9VEINE2Wkst5+A70p+nN5rOaP04mYS3a61HH3+rJVE2AQjWAB0hyXCkZEw9C
zrdacYjIvkBwZvwMRA+f0m/l
-----END CERTIFICATE-----
subject=CN = bootstrap.kafka.dev.apimfsafrica.com
issuer=C = US, O = (STAGING) Let's Encrypt, CN = (STAGING) Artificial Apricot R3
---
Acceptable client certificate CA names
O = io.strimzi, CN = clients-ca v0
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA1:RSA+SHA1
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 4833 bytes and written 448 bytes
Verification error: unable to get local issuer certificate
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 20 (unable to get local issuer certificate)
---
809B3585F47F0000:error:0A000412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../ssl/record/rec_layer_s3.c:1584:SSL alert number 42


-----BEGIN CERTIFICATE-----`
```

**Reply by scholzj** [reply]
The OpenSSL output looks good. So I think the issue must be with your truststore / keystore.

**Reply by amitdrana** [reply]
I remove the let's encrypt  CA and used to local one to solve the issue for now.
Thanks @scholzj for the help.


I just want one more help from your side.
Currently, I have set up a Kafka cluster with 4 load balancers attached to it.
1 Master 
3 with the Broker.

can we release the Broker load balancer?
Following are the Kafka-cluster yaml

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-dev
  namespace: mfsa-kafka
spec:
  kafka:
    version: 3.3.2
    replicas: 3
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
         type: tls
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
         type: tls
        configuration:
          bootstrap:
           alternativeNames:
           - bootstrap.kafka.dev.apimfsafrica.com
           annotations:
             service.beta.kubernetes.io/aws-load-balancer-type: nlb
             service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
             service.beta.kubernetes.io/aws-load-balancer-eip-allocations: eipalloc-0571cbb4ba01f0fff
             service.beta.kubernetes.io/aws-load-balancer-subnets: subnet-0edac95e203d28e95
             external-dns.alpha.kubernetes.io/hostname: bootstrap.kafka.dev.apimfsafrica.com
             external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
          - broker: 0
            annotations:
                external-dns.alpha.kubernetes.io/hostname: broker-0.kafka.apimfsafrica.com.
                external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 1
            annotations:
                 external-dns.alpha.kubernetes.io/hostname: broker-1.kafka.dev.apimfsafrica.com.
                 external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 2
            annotations:
               external-dns.alpha.kubernetes.io/hostname: broker-2.kafka.dev.apimfsafrica.com
               external-dns.alpha.kubernetes.io/ttl: "60"
    template:
      pod:
       tolerations:
       - key: "mfsa-kafka"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"

       affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - KafkaOnDemand
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.3"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 200Gi
        class: kafka-storage
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      class: kafka-storage
      deleteClaim: false
    template:
     pod:
       tolerations:
       - key: "mfsa-kafka"
         operator: "Equal"
         value: "true"
         effect: "NoSchedule"

       affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
           nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: In
                values:
                - KafkaOnDemand
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
