### DISCUSSION TITLE
ERROR: Sasl Scram-sha-512 configuration

### DISCUSSION THREAD

**Discussion by emimifleur** [strimzi/strimzi-kafka-operator#8510] [General]
I need help getting past this issue please.
I am currently working on setting up SASL configuration for Kafka. I am utilizing the Strimzi Kafka Operator along with a custom Kafka config deployed via a Helm chart. Although the pods appear to be healthy, I am encountering errors in the two broker pods:

Error 1:

```
INFO [Socket Server listenerType=ZK_BROKER, (channelId=xx.xxx.x.xx:9092-xx.xxx.x.x:5xxxxx-9xxxx)
(Unexpected Kafka request of type FIND_COORDINATOR (org.apache.kafka.common.network.Selector)
[data-plane-kafka-network-thread-0-ListenerName (PLAIN-9092)-SASL_PLAINTEXT-5]
This error message indicates a failed authentication during the SASL handshake with the IP address /10.xxx.x.x.
```

Error 2:

```
Failing SASL authentication due to invalid receive size (org.apache.kafka.common.network.Selector)
[data-plane-kafka-network-thread-8-ListenerName (PLAIN-9892)-SASL_PLAINTEXT-5]
This error suggests that the SASL authentication is failing due to an invalid receive size.
```

Additionally, I am receiving a warning from the Kafka-UI, stating:

```
Connection WARN [0:39m [[34mkafka-admin-client-thread | kafka-ui-admin-client-xxx 
[mo.a.k.c.NetworkClient [0:39m: [AdminClient clientId-kafka-ui-admin-client-xxx]
to node cluster-kafka-bootstrap.kafka-operator.svc/10.xx.x.xx:9092) terminated during authentication.
This may happen for the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0,
(2) Firewall blocking TLS traffic (e.g., allowing only HTTPS traffic), (3) Transient...
```

Here is what the kafka configuration look like:

```
spec:
  kafka:
    version: {{ .cluster.version }}
    replicas: {{ len .cluster.brokerIpAddresses }}
    image: {{ .image }}
    rack:
      {{- if .cluster.topologyKey }}
      topologyKey: {{ .cluster.topologyKey }}
      {{- end}}
    authorization:
      type: simple
      superUsers:
        - CN=my-name-user
        - CN=cd-user
        - CN=stry-user
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: external
        port: 9895
        type: loadbalancer
        tls: false
...
    config:
...
      inter.broker.listener.name: SASL_SSL
      security.inter.broker.listener.name: SASL_SSL
      sasl.enabled.mechanisms: SCRAM-SHA-512
      sasl.mechanism.inter.broker.protocol: SCRAM-SHA-512
      authorizer.class.name: kafka.security.auth.AclAuthorizer
```

The kafka-ui config :

```
      containers:
        - name: {{ .Chart.Name }}
          env:
            ...
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL
              value: SASL_SSL
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM
             value: SCRAM-SHA-512
            - name: KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG
             value: org.apache.kafka.common.security.scram.ScramLoginModule required username="my-name-user" password="user-secret";
```
