### DISCUSSION TITLE
Use custom storage class for externalising disks to another resource group? Supported?

### DISCUSSION THREAD

**Discussion by chrismelikian** [strimzi/strimzi-kafka-operator#8550] [General]
Hi,

I'm using Strimzi 0.34/AKS 1.25.5 and am looking to use a resource group in the same Azure subscription for the persistent disk storage. 

I am wondering whether this is a supported configuration combined with ReadWriteMany access in the PVC? 

The documentation isn't clear whether external storage is OK other than saying NFS isn't recommended.

My custom storage class:-

```
apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata:
  name: my-kafka-external-rg-storage 
parameters:
  cachingmode: None
  kind: Managed 
  skuname: Standard_LRS 
  resourcegroup: "kafka-persistent-disks"
  diskencryptionsetid:/subscriptions/mine/resourceGroups/my-group/providers/Microsoft.Compute/diskEncryptionSets/my-encryption 
  subscriptionid: mine
provisioner: disk.csi.azure.com
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

All help appreciated! :-)

Best regards, Chris.
