### DISCUSSION TITLE
message: Configuration model /kafka-3.2.3-config-model.json was not found

### DISCUSSION THREAD

**Discussion by hari819** [strimzi/strimzi-kafka-operator#8575] [Q&A] [answered]
Hello team,

i am trying to deploy cluster using 0.31.1 version of operator , I see this in the status of the kafka cluster , please could you help,
@scholzj 

```
status:
  conditions:
    - lastTransitionTime: '2023-05-27T05:34:37.370Z'
      message: Configuration model /kafka-3.2.3-config-model.json was not found
      reason: RuntimeException
      status: 'True'
      type: NotReady
  observedGeneration: 2
```

this is the snippet from cluster definition,
```apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  clusterCa:
    generateCertificateAuthority: false
  clientsCa:
    generateCertificateAuthority: false
  kafka:
    version: 3.2.3
    replicas: 3
```

Thanks,
Hari
