### DISCUSSION TITLE
[Bug]: Helm Chart couldn't apply watchNamespaces option

### DISCUSSION THREAD

**Discussion by tankim** [strimzi/strimzi-kafka-operator#8594] [General]
### Bug Description

When I tried to install strimzi-kafka-operator via helm chart with custom values file, 
below option is not applied.
```
watchNamespaces: []
watchAnyNamespace: true
```
values file, adding something like this seems to work.
```
strimzi-kafka-operator:
  watchAnyNamespace: true
```

### Steps to reproduce
```
# values.yaml
watchNamespaces: []
watchAnyNamespace: true

helm upgrade --install strimzi-kafka-operator . -f values.yaml -n kafka
```
When run as above, the operator will only monitor the kafka namespace.

```
# values.yaml
#watchNamespaces: []
#watchAnyNamespace: true
strimzi-kafka-operator:
  watchAnyNamespace: true

helm upgrade --install strimzi-kafka-operator . -f values.yaml -n kafka
```
When run as above, the operator will monitor all namespaces.

_No response_

### Strimzi version

0.34.0

### Kubernetes version

1.23

**Comment by scholzj** [comment]
Can you please share the exact steps to reproduce it?

**Comment by tankim** [comment]
@scholzj edited comment I wrote.

**Comment by scholzj** [comment]
I tried the following commands:

```
helm install cluster-operator strimzi/strimzi-kafka-operator -f values.yaml -n kafka
```

and 

```
helm upgrade --install cluster-operator strimzi/strimzi-kafka-operator -f values.yaml -n kafka
```

and both seem to work completely fine. The `values.yaml` file is as you suggested:

```
watchNamespaces: []
watchAnyNamespace: true
```

It deploys the operator watching all namespaces.

**Comment by tankim** [comment]
can you share whole the values.yaml you tested?

**Comment by scholzj** [comment]
That ^^^ is exactly what is in my `values.yaml` file as that is what you suggested as a reproducer.

**Comment by tan-kim** [comment]
This is my whole values.yaml.
```
# Default values for strimzi-kafka-operator.

# If you set `watchNamespaces` to the same value as ``.Release.Namespace` (e.g. `helm ... --namespace $NAMESPACE`),
# the chart will fail because duplicate RoleBindings will be attempted to be created in the same namespace
watchNamespaces: []
watchAnyNamespace: true
#strimzi-kafka-operator:
#  watchAnyNamespace: true

image:
  registry: quay.io
  repository: strimzi
  name: operator
  tag: 0.34.0
logVolume: co-config-volume
logConfigMap: strimzi-cluster-operator
logLevel: ${env:STRIMZI_LOG_LEVEL:-INFO}
fullReconciliationIntervalMs: 120000
operationTimeoutMs: 3000000
kubernetesServiceDnsDomain: cluster.local
featureGates: ""

tolerations: []
affinity: {}
annotations: {}
labels: {}
nodeSelector: {}

podSecurityContext: {}
securityContext: {}

# Docker images that operator uses to provision various components of Strimzi.  To use your own registry prefix the
# repository name with your registry URL.
# Ex) repository: registry.xyzcorp.com/strimzi/zookeeper
zookeeper:
  image:
    registry: quay.io
    repository: strimzi
    name: kafka
    tagPrefix: 0.34.0
kafka:
  image:
    registry: quay.io
    repository: strimzi
    name: kafka
    tagPrefix: 0.34.0
kafkaConnect:
  image:
    registry: quay.io
    repository: strimzi
    name: kafka
    tagPrefix: 0.34.0
topicOperator:
  image:
    registry: quay.io
    repository: strimzi
    name: operator
    tag: 0.34.0
userOperator:
  image:
    registry: quay.io
    repository: strimzi
    name: operator
    tag: 0.34.0
kafkaInit:
  image:
    registry: quay.io
    repository: strimzi
    name: operator
    tag: 0.34.0
tlsSidecarEntityOperator:
  image:
    registry: quay.io
    repository: strimzi
    name: kafka
    tagPrefix: 0.34.0
kafkaMirrorMaker:
  image:
    registry: quay.io
    repository: strimzi
    name: kafka
    tagPrefix: 0.34.0
kafkaBridge:
  image:
    registry: quay.io
    repository: strimzi
    name: kafka-bridge
    tag: 0.20.2
kafkaExporter:
  image:
    registry: quay.io
    repository: strimzi
    name: kafka
    tagPrefix: 0.34.0
jmxTrans:
  image:
    registry: quay.io
    repository: strimzi
    name: jmxtrans
    tag: 0.34.0
kafkaMirrorMaker2:
  image:
    registry: quay.io
    repository: strimzi
    name: kafka
    tagPrefix: 0.34.0
cruiseControl:
  image:
    registry: quay.io
    repository: strimzi
    name: kafka
    tagPrefix: 0.34.0
tlsSidecarCruiseControl:
  image:
    registry: quay.io
    repository: strimzi
    name: kafka
    tagPrefix: 0.34.0
kanikoExecutor:
  image:
    registry: quay.io
    repository: strimzi
    name: kaniko-executor
    tag: 0.34.0
resources:
  limits:
    memory: 384Mi
    cpu: 1000m
  requests:
    memory: 384Mi
    cpu: 200m
livenessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 30

# Override the docker registry used by all Strimzi images
imageRegistryOverride: ""
# Override the docker image repository used by all Strimzi images
imageRepositoryOverride: ""
# Override the docker image tag used by all Strimzi images
imageTagOverride: ""
createGlobalResources: true
# Override the exclude pattern for exclude some labels
labelsExclusionPattern: ""
# Controls whether Strimzi generates network policy resources (By default true)
generateNetworkPolicy: true
# Override the value for Connect build timeout
connectBuildTimeoutMs: 3000000
```

And this is log in strimzi-cluster-operator.
`2023-05-22 23:37:11 INFO  ClusterOperator:136 - Setting up periodic reconciliation for namespace kafka`
