### DISCUSSION TITLE
Strimzi kafka mirrormaker2 custom names for heartbeats , checkpoints and offset-syncs topic

### DISCUSSION THREAD

**Discussion by suchitrakaashyap** [strimzi/strimzi-kafka-operator#8633] [Q&A]
We have a multi-tenanted kafka setup and are using Strimzi Kafka mirrormaker2 to do some mirroring as part of a migration. From looking into the documentation for strimzi-kafka mirrormaker2 I can't see a way of renaming the internal topics such as heartbeats, <source_cluster>.checkpoints.internal topics?
Is there a way to do this if possible?
If not are there any recommendations for a multi-tenanted setup?

**Comment by jakubmalek** [comment]
As far as I remember, the MM2 internal topic names are provided by the `ReplicationPolicy` class
See:
https://github.com/apache/kafka/blob/3.5.0/connect/mirror-client/src/main/java/org/apache/kafka/connect/mirror/ReplicationPolicy.java#L61-L73

But you would need a custom implementation of `ReplicationPolicy` to change it as all standard implementation uses the same naming.

What you can configure is the location of `offset-sync` topic which by default is set to a Kafka source cluster.
The `offset-sync` topic is produced by the source connector, but consumed by the `checkpointConnector` to translate the topic partition offsets for synced consumer groups.

```yaml
spec:
  sourceConnector:
    config:
      offset-syncs.topic.location: target
  checkpointConnector:
    config:
      offset-syncs.topic.location: target
```

But what is the issue with topic names ?
