### DISCUSSION TITLE
Is there any way to expose a debug port in kafka connect pod?

### DISCUSSION THREAD

**Discussion by atrifyllis** [strimzi/strimzi-kafka-operator#8671] [Q&A]
I am probably missing something fundamental, but how else do you remote debug kafka connect connectors? You need an exposed port in the host right?

For example, I can add this env variable in the pod's container but how do I expose port 5005 then?
```
  template:
    connectContainer:
      env:
        - name: JAVA_TOOL_OPTIONS
          value: -agentlib:jdwp=transport=dt_socket,address=*:5005,server=y,suspend=n
```
