### DISCUSSION TITLE
Why are my secrets being deleted?

### DISCUSSION THREAD

**Discussion by rjones-duchancell** [strimzi/strimzi-kafka-operator#8724] [General]
I am attempting to use custom certificates in my deployment and have set generateCertificateAuthority false for clientsCa.  I have followed the documentation and have labeled and annotated the secrets appropriately.  The secrets are created, but after a few minutes they are deleted.  I am deploying to OpenShift.  What behavior is causing this?  Kafka and Zookeeper pods deploy correctly, but the Entity Operator is failing with an error message saying it can't find the wds-cluster-ca-cert.  The Strimzi pod looks good initially, then starts reporting errors not being able to find certs.

Is there some garbage collection going on behind the scenes that I need to configure or turn off?

BTW, I did add the external listener cert configuration after reading (and commenting on) another discussion.  Is there a conflict going on?

Here is my template:

```
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: wds-kafka-aa-template
  annotations:
    description: "Template used to deploy Kafka via AA"
    tags: "wds,kafka"
labels:
  template: wds-kafka-aa-template
objects:

- apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: wds-clients-ca
      annotations:
        strimzi.io/ca-key-generation: "0"
      labels:
        strimzi.io/kind: Kafka
        strimzi.io/cluster: wds
    data:
      ca.key: ${TLS_KEY}
    
  - apiVersion: v1
    kind: Secret
    type: Opaque
    metadata:
      name: wds-clients-ca-cert
      annotations:
        strimzi.io/ca-cert-generation: "0"
      labels:
        strimzi.io/kind: Kafka
        strimzi.io/cluster: wds
    data:
      ca.crt: ${TLS_CERT}
      
  - apiVersion: v1
    kind: Secret
    type: kubernetes.io/tls
    metadata:
      name: wds-cert-chain
    data:
      tls.crt: ${TLS_CERT}
      tls.key: ${TLS_KEY}      

  - apiVersion: kafka.strimzi.io/v1beta2
    kind: Kafka
    metadata:
      name: wds
    spec:
      clientsCa:
        generateCertificateAuthority: false
      kafka:
        replicas: 1
        version: 3.4.0
        image: ${AA_REGISTRY}/wds/kafka:0.34.0-kafka-3.4.0
        resources:
          requests:
            memory: 4Gi
            cpu: "1"
          limits:
            memory: 4Gi
            cpu: "1"
        readinessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
        livenessProbe:
          initialDelaySeconds: 15
          timeoutSeconds: 5
        jvmOptions:
          -Xms: 2048m
          -Xmx: 2048m
        listeners:
          - name: plain
            port: 9092
            type: internal
            tls: false
            configuration:
              useServiceDnsDomain: true
          - name: tls
            port: 9093
            type: internal
            tls: true
            authentication:
              type: tls
          - name: external
            port: 9094
            type: route
            tls: true
            configuration:
              brokerCertChainAndKey:
                secretName: wds-cert-chain
                certificate: tls.crt
                key: tls.key
        config:
          offsets.topic.replication.factor: 1
          transaction.state.log.replication.factor: 1
          transaction.state.log.min.isr: 1
          default.replication.factor: 1
          min.insync.replicas: 1
          inter.broker.protocol.version: "3.4"
          message.max.bytes: 104857600
        storage:
          type: persistent-claim
          size: ${KAFKA_STORAGE_SIZE}
          class: ${STORAGE_CLASS_NAME}
          deleteClaim: false
        logging:
          loggers:
            kafka.root.logger.level: ${KAFKA_ROOT_LOGGER_LEVEL}
          type: inline  
        template:
          pod:
            imagePullSecrets:
              - name: aa-dockerconfig
      zookeeper:
        image: ${AA_REGISTRY}/wds/kafka:0.34.0-kafka-3.4.0
        replicas: 1
        storage:
          type: persistent-claim
          size: ${ZOOKEEPER_STORAGE_SIZE}
          class: ${STORAGE_CLASS_NAME}
          deleteClaim: false
        logging:
          loggers:
            zookeeper.root.logger: ${ZOOKEEPER_ROOT_LOGGER_LEVEL}
          type: inline      
        template:
          pod:
            imagePullSecrets:
              - name: aa-dockerconfig
      entityOperator:
        topicOperator: {}
        userOperator: {}             
​
parameters:
​
  - name: AA_REGISTRY
    description: "App Arsenal Docker registry (environment-specific)"
    value: acs-arsenal.apps.communal3.sd.niwc.navy.mil
    required: true
    
  - name: NAMESPACE
    description: "OpenShift namespace"
    value: wds-kafka
    required: true  
    
  - name: STORAGE_CLASS_NAME
    description: "The storage class to use for persistent volume claims"
    value: gp2
    required: true  
    
  - name: KAFKA_STORAGE_SIZE
    description: "Persistent storage request for Kafka"
    value: 100Gi
    required: true
    
  - name: KAFKA_ROOT_LOGGER_LEVEL
    description: "Root logger level for Kafka"
    value: INFO
    required: true    
    
  - name: ZOOKEEPER_STORAGE_SIZE
    description: "Persistent storage request for Zookeeper"
    value: 25Gi
    required: true
    
  - name: ZOOKEEPER_ROOT_LOGGER_LEVEL
    description: "Root logger level for Zookeeper"
    value: INFO
    required: true
    
  - name: TLS_KEY
    description: "Server Private Key (Change Per Deployment Environment)"
    value: <encoded private key>
    required: true
    
  - name: TLS_CERT
    description: "Server Certificate (Change Per Deployment Environment)"
    value: <encoded certificate with trust chain, 3 certs total>
    required: true
```
