### DISCUSSION TITLE
After removing Strimzi cluster with external loadbalancer, the Kubernetes Frontend IP configuration will not be deleted

### DISCUSSION THREAD

**Discussion by FlowsenAusMonotown** [strimzi/strimzi-kafka-operator#8757] [Q&A] [answered]
I have the following configuration:

```yaml
...
listeners:
        - name: external
          port: 9093
          type: loadbalancer
          tls: true
          authentication:
            type: tls
          configuration:
            bootstrap:
              annotations:
                "service.beta.kubernetes.io/azure-load-balancer-ipv4": ${azurerm_public_ip.instance_kafka_ip.ip_address}
              loadBalancerIP: ${azurerm_public_ip.instance_kafka_ip.ip_address}
            brokerCertChainAndKey:
              secretName: ${local.external-kafka-cert-secret-name}
              certificate: tls.crt
              key: tls.key
...
```

When removing the Kafka cluster the Kubernetes Frontend IP configuration will left over and the deletion of the public IP address will fail. How I can make sure, if the Kafka cluster is removed, that the Kubernetes Frontend IP configuration is also be deleted?
