### DISCUSSION TITLE
Strimzi Cluster Operator down after upgrading to 0.35.1 from 0.27.1

### DISCUSSION THREAD

**Discussion by Sai-Charan-Madhvaraj** [strimzi/strimzi-kafka-operator#8829] [General]
Hi Team, 

We are trying to upgrade strimzi from version 0.27.1 to 0.35.1 directly and Strimzi Cluster operator pod was down with error.

Basically its complaining for access for all api resources of kafka.strimzi.io and core.strimzi.io, Please see below error in logs.
``` 
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.1.0.1:443/apis/kafka.strimzi.io/v1beta2/kafkamirrormaker2s?resourceVersion=0. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. kafkamirrormaker2s.kafka.strimzi.io is forbidden: User "system:serviceaccount:emp-kafka:strimzi-cluster-operator" cannot list resource "kafkamirrormaker2s" in API group "kafka.strimzi.io" at the cluster scope.
```

```
2023-07-12 13:14:04 ERROR InformerUtils:29 - Caught exception in the StrimziPodSet informer which is not started
java.util.concurrent.CompletionException: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://10.1.0.1:443/apis/core.strimzi.io/v1beta2/strimzipodsets?resourceVersion=0. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. strimzipodsets.core.strimzi.io is forbidden: User "system:serviceaccount:emp-kafka:strimzi-cluster-operator" cannot list resource "strimzipodsets" in API group "core.strimzi.io" at the cluster scope.
``` 

Upon investigating, we found that there is a new Cluster role strimzi-cluster-operator-watched where all  API permissions  has moved to this cluster role instead of strimzi-cluster-operator-namespaced which was case in 0.27.1.

Below are the changes in strimzi cluster operator deployment file 
```  
           - name: STRIMZI_NAMESPACE
              value: "*"
            - name: STRIMZI_LEADER_ELECTION_ENABLED
              value: "true"
            - name: STRIMZI_LEADER_ELECTION_LEASE_NAME
              value: "strimzi-cluster-operator"
            - name: STRIMZI_LEADER_ELECTION_LEASE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_LEADER_ELECTION_IDENTITY
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
```

**Comment by scholzj** [comment]
0.27->0.35 is a big jump. So yes, it is likely that there were some RBAC resource changes. You need to make sure the RBAC resources are installed properly according to the version you are upgrading to.

**Reply by Sai-Charan-Madhvaraj** [reply]
will test the pod status by adding RBAC to existing cluster roles

If Cluster operator pod is up by adding RBAC manually, will there by any effect on managing Strimzi Kafka components later ? Is the way of manually adding RBAC suggested ?

**Reply by scholzj** [reply]
I'm not really sure I understand what exactly you mean by _adding it manually_. Normally, the installation / upgrade procedure should install the RBACs. So I think you need to check how you install the operator and find out what the issue is. In general, with every upgrade, all resources might contain changes so you should apply all of them, including the CRDs. Not for example just the Deployment only.

**Reply by AAR256** [reply]
@scholzj We followed the upgrade guide step-by-step and updated not only the deployment but the other RBACs as well. That is why we're a bit puzzled that this error is coming up. But from the error it seems to be an access issue from service account. Any idea on why this could be happening here or if we're missing anything there?

**Reply by scholzj** [reply]
Well, if you followed the guide, then you should have [this cluster role](https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/023-ClusterRole-strimzi-cluster-operator-role.yaml) and [this (cluster) role binding](https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/023-RoleBinding-strimzi-cluster-operator.yaml). Is that the case? Does the binding point to the right service account?

**Reply by Sai-Charan-Madhvaraj** [reply]
@scholzj , yes above Cluster role and cluster role bindings are present and pointing to right service account . 

Strimzi Cluster operator came up running once i changed the environment variable "STRIMZI_NAMESPACE" to metadata.namespace instead of *.

If we configure strimzi cluster deployment with below config, operator fails with error mentioned above. 
```
           - name: STRIMZI_NAMESPACE
              value: "*"
```

when i changed this to below, operator pod came up successfully.

```
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```
