### DISCUSSION TITLE
Overly permissive service account

### DISCUSSION THREAD

**Discussion by wei669** [strimzi/strimzi-kafka-operator#8974] [Q&A]
Hello. We recently sent our charts and images for vulnerability scan, and this is the feedback we received.

> The service account "strimzi-cluster-operator" has been granted to a role with high permission, which all actions (* - list/create/delete/patch etc.) secretes, configmaps and other resources. This is an example of an overly permissive service account, because it has more privileges than are necessary to run the application it is associated with. 

Here is the permissions associated to the SA:
```
- apiGroups:
  - ""
  resources:
  - pods
  - serviceaccounts
  - configmaps
  - services
  - endpoints
  - secrets
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - patch
  - update
``` 
An attacker can access all secrets, update secrets, delete secrets, delete pods etc. This will lead to a malicious user to access other resources or perform denial of services by deleting resources. Is there a way we can reduce the permissions while allowing operator to administrate the cluster? If all these verbs and resources are required, can we remove them using kubectl after spinning up the cluster and etc?

Can we limit the RBAC permissions to namespace level i.e., switch clusterrole to role / rolebinding? Currently the strimzi operator sits in the same namespace as all other services and we have no plan to let strimzi operator to administrate resources outside of its cluster.
