### DISCUSSION TITLE
Topic Operator fails to start with VertxException: Thread blocked

### DISCUSSION THREAD

**Discussion by sksahu-244** [strimzi/strimzi-kafka-operator#8992] [Q&A] [answered]
Hello, 

When kafka replica is set to 1 or 2, Topic Operator fails to start with below VertxException: Thread blocked. The issue is not reproducible with 3 replicas of kafka.

Below is the exception stacktrace:

Thread Thread[blocking-startup-ops-0,5,main] has been blocked for 412528 ms, time limit is 60000 ms io.vertx.core.VertxException: Thread blocked|\tat java.base@11.0.19/jdk.internal.misc.Unsafe.park(Native Method)|\tat java.base@11.0.19/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)|\tat java.base@11.0.19/java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1796)|\tat java.base@11.0.19/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3128)|\tat java.base@11.0.19/java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1823)|\tat java.base@11.0.19/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1998)|\tat app//io.strimzi.operator.topic.Session.createTopicStore(Session.java:324)|\tat app//io.strimzi.operator.topic.Session$$Lambda$234/0x000000010038e840.apply(Unknown Source)|\tat app//io.strimzi.operator.topic.Session.lambda$createTopicStoreAsync$15(Session.java:254)|\tat app//io.strimzi.operator.topic.Session$$Lambda$448/0x000000010051f440.handle(Unknown Source)|\tat app//io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)|\tat app//io.vertx.core.impl.ContextImpl$$Lambda$314/0x0000000100469040.handle(Unknown Source)|\tat app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)|\tat app//io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)|\tat app//io.vertx.core.impl.ContextImpl$$Lambda$307/0x000000010044a840.run(Unknown Source)|\tat app//io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)|\tat app//io.vertx.core.impl.TaskQueue$$Lambda$238/0x000000010038d840.run(Unknown Source)|\tat java.base@11.0.19/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)|\tat java.base@11.0.19/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)|\tat app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)|\tat java.base@11.0.19/java.lang.Thread.run(Thread.java:829)

I checked an older discussion https://github.com/strimzi/strimzi-kafka-operator/issues/6046 with same issue.
The workaround suggested in this discussion to use the environment variable USE_ZOOKEEPER_TOPIC_STORE and set it to true works for me fine. I also checked the PR https://github.com/strimzi/strimzi-kafka-operator/pull/6645, it seems the fix was delivered in 0.29.0. I am currently using 0.31.0. I am still facing this issue. Could you please take a look and let me know if I am missing something here or is it a Bug?

Thanks,
Santosh

**Comment by scholzj** [comment]
You would probably need to share all the logs and not just one exception which tells nothing about the actual issue. You should not use `USE_ZOOKEEPER_TOPIC_STORE`. It is not really covered by any real tests.

**Reply by sksahu-244** [reply]
Hi, Thanks a lot for your response. 
Please find attached the topic-operator log which contains the VertxException: Thread blocked exception. This issue is reproducible with kafka replica set to 1 or 2, but not seen with kafka replica set to 3.

[topic-operator-log.txt](https://github.com/strimzi/strimzi-kafka-operator/files/12366175/topic-operator-log.txt)


Thanks,
Santosh

**Reply by scholzj** [reply]
> This issue is reproducible with kafka replica set to 1 or 2, but not seen with kafka replica set to 3.

So, did you reconfigure the topics properly when you scale down the Kafka cluster?

**Reply by sksahu-244** [reply]
Hi, This issue happens at startup / installation / initial deployment of the Kafka cluster. This is not a scale down of Kafka cluster use case.

Steps to reproduce the issue:

1. Install Strimzi Operator 0.31.1 using helm chart on Kubernetes cluster.

2. Create a Kafka cluster manifest using below kafka.yaml file content:

apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: backup-restore-with-stanza
spec:
  kafka:
    replicas: 1
    storage:
      type: ephemeral
  zookeeper:   
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    enabled: true

3. Apply the above manifest file (kafka.yaml) with below command:
kubectl apply -f kafka.yaml -n namespace

4. Watch the topic operator logs with below command:
kubectl log backup-restore-with-stanza-entity-operator-748f987df8-9t2rm -c topic-operator -n namespace

Thanks,
Santosh

**Reply by scholzj** [reply]
Can you format the YAML as a code? I do not think it is correct. There is nothing like `enabled: true` in `entityOperator` section.

**Reply by sksahu-244** [reply]
Hi, Please find below the yaml as a code. I have corrected `enabled: true` in `entityOperator` section.

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: backup-restore-with-stanza
spec:
  kafka:
    replicas: 1
    storage:
      type: ephemeral
  zookeeper:   
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

**Reply by scholzj** [reply]
I'm sorry, but I don't think this is the resource you use. First the `entityOperator` was wrong. Also, the API version is wrong (`kafka.strimzi.io/v1beta1` is not supported in 0.31.1). It is also missing the `listeners` field which is mandatory.

**Reply by sksahu-244** [reply]
Hi, Would the below POD manifest work for you and would help you in reproducing this issue?

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: backup-restore-with-stanza
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:   
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

Thanks,
Santosh

**Reply by scholzj** [reply]
It's not about what works for me. I know how to get it working. The problem is that you say that you have some problem - but the resource you are supposed to have it with is clearly invalid and does not work. So clearly, trying to reproduce it with it would not really be possible. You should not share what would work for me but what exactly are you doing and how exactly does your resource look like.

**Reply by sksahu-244** [reply]
Hi, Sorry for the late response. I can confirm I am testing with below Kafka manifest and now I am testing with latest strimzi version 0.36.1 helm chart and I could reproduce the issue in latest strimzi version 0.36.1. Please find attached the topic-operator log with latest strimzi version 0.36.1. 
[latest_strimzi_topic_operator_log.txt](https://github.com/strimzi/strimzi-kafka-operator/files/12415728/latest_strimzi_topic_operator_log.txt)

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: backup-restore-with-stanza
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

When I changed the kafka replicas to 3 in the above Kafka manifest, the vertx exception is no more seen in the topic-operator log and topic-operator container becomes up and running.

Thanks,
Santosh
