### DISCUSSION TITLE
How to use selector in PersistentClaimStorage ?

### DISCUSSION THREAD

**Discussion by jackchuong** [strimzi/strimzi-kafka-operator#9120] [Q&A] [answered]
Hi all,
I created 2 pv and 2 pvc for kafka and zookeeper. How do I specify these volumes for kafka and zookeeper ?
As I read documentation
<html><body>

selector | Specifies a specific persistent volume to use. It contains key:value pairs representing labels for selecting such a volume.
-- | --

</body>
</html>
I have yaml like this

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mykafka
  namespace: kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4.0"
      log.cleanup.policy: compact,delete
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: nfs-idcnas002
        size: 10Gi
        deleteClaim: false
        #selector: ???
    resources:
      limits:
        memory: 4Gi
        cpu: "2"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      class: nfs-idcnas002
      size: 10Gi
      deleteClaim: false
      #selector: ???
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
Please give me some advice, thank you very much,

**Comment by scholzj** [comment]
First of all, NFS does not work well with Kafka. You should use block storage instead.

I'm not aware of anyone using the selector, but I guess you just list the labels there that match the PVs you want to use. Maybe if you share what exactly you are trying to do, there would be some other way to do it as well.

**Reply by jackchuong** [reply]
Hi @scholzj 
Assume that I have 2 pvc & 2pv like
```
kubectl -n kafka get pvc
NAME                              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS
data-0-ebms-kafka-new-kafka-0     Bound    pvc-3c54f96b-7372-40e6-ae36-d329a00ad58a   10Gi       RWO            nfs-idcnas002
data-ebms-kafka-new-zookeeper-0   Bound    pvc-d6bde085-dc0e-4c28-8455-ddd61d8a2615   10Gi       RWO            nfs-idcnas002

kubectl -n kafka get pv | grep kafka
pvc-3c54f96b-7372-40e6-ae36-d329a00ad58a                       10Gi       RWO            Delete           Bound    kafka/data-0-ebms-kafka-new-kafka-0                                             nfs-idcnas002            
pvc-d6bde085-dc0e-4c28-8455-ddd61d8a2615                       10Gi       RWO            Delete           Bound    kafka/data-ebms-kafka-new-zookeeper-0                                           nfs-idcnas002
```            

How should I list lables in selector to make kafka and zookeeper use these volumes ?

**Reply by scholzj** [reply]
So, actually, if you already have the PVC, the selector would not help you. You can simply create the PVC with the right name and settings manually, bind it to the PVs you want to use, and then just deploy the Kafka cluster without anything special. The operator should just pickup the PVCs and use them.

**Reply by jackchuong** [reply]
Yes it works as you said, but I still want to know how to use selector.
If I just create PV without PVC , leave PV status as "available" , how should I list lables in selector to make operator create PVC point to selected PV ?

**Reply by scholzj** [reply]
I guess is just key-value field ...
```
selector:
  label1: value1
  label2: value2
```

**Reply by jackchuong** [reply]
so if I have 2 PV like
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs-provisioner-idcnas002
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-3c54f96b-7372-40e6-ae36-d329a00ad58a
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-0-ebms-kafka-new-kafka-0
    namespace: kafka
  mountOptions:
  - nfsvers=3
  nfs:
    path: /k8s-nfs-idcnas002/kafka-data-0-ebms-kafka-new-kafka-0-pvc-3c54f96b-7372-40e6-ae36-d329a00ad58a
    server: 192.168.0.108
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-idcnas002
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: nfs-provisioner-idcnas002
  finalizers:
  - kubernetes.io/pv-protection
  name: pvc-d6bde085-dc0e-4c28-8455-ddd61d8a2615
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-ebms-kafka-new-zookeeper-0
    namespace: kafka
  mountOptions:
  - nfsvers=3
  nfs:
    path: /k8s-nfs-idcnas002/kafka-data-ebms-kafka-new-zookeeper-0-pvc-d6bde085-dc0e-4c28-8455-ddd61d8a2615
    server: 192.168.0.108
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-idcnas002
  volumeMode: Filesystem
```
Then kafka cluster yaml would be
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: mykafka
  namespace: kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4.0"
      log.cleanup.policy: compact,delete
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: nfs-idcnas002
        size: 10Gi
        deleteClaim: false
        selector:
          name: pvc-3c54f96b-7372-40e6-ae36-d329a00ad58a
    resources:
      limits:
        memory: 4Gi
        cpu: "2"
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      class: nfs-idcnas002
      size: 10Gi
      deleteClaim: false
      selector:
        name: pvc-d6bde085-dc0e-4c28-8455-ddd61d8a2615
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
Is it right ?
