### DISCUSSION TITLE
Cannot enabe autoRestart property on KafkaConnector

### DISCUSSION THREAD

**Discussion by raduone** [strimzi/strimzi-kafka-operator#9248] [Q&A]
The connector helm config is based on the following template I created:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: {{ required "value 'global.sinkConnectorName' is required" .Values.global.sinkConnectorName }}
  labels:
    strimzi.io/cluster: {{ required "value 'connectClusterName' is required" .Values.global.connectClusterName }}
spec:
  autoRestart:
    enabled: {{ .Values.autoRestart | default true }}
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: {{ .Values.tasksMax | default 1 }}
  config:
.....
```

The strimzi operator:
```
apiVersion: v2
name: strimzi
version: 0.36.1
dependencies:
  - name: strimzi-kafka-operator
    version: 0.36.1
    repository: https://strimzi.io/charts
```

All worked until I added the `autoRestart` property.
With the autoRestart I keep getting, whenever I try to upgrade:

```
Error: UPGRADE FAILED: error validating "": error validating 
data: ValidationError(KafkaConnector.spec): unknown field "autoRestart" in io.strimzi.kafka.v1beta2.KafkaConnector.spec  
```

From all the documentation I could find, it looks like I added the configuration correctly, 
though I am not sure why it's not working.
