### DISCUSSION TITLE
trying to change the log level of kafka broker

### DISCUSSION THREAD

**Discussion by themkarimi** [strimzi/strimzi-kafka-operator#9286] [Q&A]
I am trying to change the log level of my kafka cluster brokers and zookeeper nodes using this configuration:
```
  kafka:
    authorization:
      superUsers:
      - app-superuser
      type: simple
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: WARN
        kafka.request.logger.level: WARN
        kafka.state.change.logger.level: WARN
        kafka.controller.logger.level: WARN
        kafka.unclean.leader.election.logger.level: WARN
        kafka.authorization.logger.level: WARN
        kafka.failed.authentication.logger.level: WARN
        kafka.ssl.logger.level: WARN
        kafka.scheduler.logger.level: WARN

```

the one with     _`kafka.root.logger.level: WARN`_ seems to be working but the other components log level is not changed. how can i change them?
