### DISCUSSION TITLE
Nodeselector not working for Kafka and Zookeeper

### DISCUSSION THREAD

**Discussion by fayazahamedj** [strimzi/strimzi-kafka-operator#9294] [Q&A]
Hello folks, I tried to implement NodeSelector for both Kafka & zookeeper as saw in one of the discussions, but it's not taking effect. Have shared the YAML snippet only for zookeeper as the complete YAML is lengthy. I tried nodeAffinity on the Kafka Strimzi Pod set & it is working fine, however when creating under Kafka cluster not working. 

Have shared the complete Kafka YAML as attachment. Could you help on this??

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
 name: my-cluster
 namespace: streaming-telemetry
spec:
  zookeeper:
     replicas: 3
     storage:
       size: 2Gi
       type: persistent-claim
     template:
        pod:
           affinity:
              nodeAffinity:
                 requiredDuringSchedulingIgnoredDuringExecution:
                    nodeSelectorTerms:
                       - matchExpressions:
                              - key: nodetype
                                 operator: In
                                 values:
                                 - kafka
```

**Comment by fayazahamedj** [comment]
[kafka.txt](https://github.com/strimzi/strimzi-kafka-operator/files/13180478/kafka.txt)

**Comment by scholzj** [comment]
I'm not sure I follow what you mean with `I tried nodeAffinity on the Kafka Strimzi Pod set & it is working fine, however when creating under Kafka cluster not working.` -> can you elaborate on this, please?

**Reply by scholzj** [reply]
BTW: It looks like your cluster is using an old Kafka version:

```yaml
  conditions:
    - lastTransitionTime: '2023-10-26T16:08:12.190040865Z'
      message: >-
        Unsupported Kafka.spec.kafka.version: 3.4.0. Supported versions are:
        [3.5.0, 3.5.1, 3.6.0]
      reason: UnsupportedKafkaVersionException
      status: 'True'
      type: NotReady
```

So if you change the affinity, it will not be applied because of this. You have to upgrade Kafka to fix this first. So maybe that is the problem?
