### DISCUSSION TITLE
Quickstart Kafka setup fails

### DISCUSSION THREAD

**Discussion by LDTips** [strimzi/strimzi-kafka-operator#9351] [Q&A]
Hello.

I am running a local microk8s instance. I was looking to use the quickstart example posted here https://strimzi.io/quickstarts/

I install the strimzi operator and the pod gets created - everything ok in logs.
But after I try to apply the configuration from https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml with the only difference in reducing the sizes from 100Gi to 2Gi, I am unable to get a Kafka pod running. The zookeeper pod gets created, but no Kafka pod.

Interestingly, the default ephemeral configuration works.
To be sure I did not change something by accident, here is the applied yaml file:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 2Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 2Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

And attached are the logs from the zookeeper and the strimzi operator pods.

[strimzi-cluster-op_new.log](https://github.com/strimzi/strimzi-kafka-operator/files/13364032/strimzi-cluster-op_new.log)
[zookeeper_new.log](https://github.com/strimzi/strimzi-kafka-operator/files/13364034/zookeeper_new.log)
