### DISCUSSION TITLE
How to access strimzi kafka cluster running on minikube publically?

### DISCUSSION THREAD

**Discussion by sleepy0owl** [strimzi/strimzi-kafka-operator#9352] [Q&A]
I have set up a Kafka cluster using strimzi on Minikube. The Minikube running on an EC2 machine. I have created a node port-type service to expose the Kafka cluster. However, I can not access the Kafka cluster outside of the ec2. The following is my deployment yaml file.

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: nodeport
        tls: false
    storage:
      type: ephemeral
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

I used `kubectl get node minikube -o=jsonpath='{range .status.addresses[*]}{.type}{"\t"}{.address}{"\n"}'` to get node address. And node address is `192.168.49.2`
And used `kubectl exec kafka-cluster-kafka-0 -c kafka -n kafka -it -- cat /tmp/strimzi.properties | grep advertised\n` and got the same IP address.
I even setup the security group to allow every port.
Now I want to access the Kafka cluster by using the ec2 IP address and nodeport, but I wasn't able to access the Kafka publicly.
Is there a way to expose strimzi Kafka cluster running on minukube to the internet?
