### DISCUSSION TITLE
Kafkaconnector returned 500 (Internal Server Error)

### DISCUSSION THREAD

**Discussion by sai9920** [strimzi/strimzi-kafka-operator#9358] [General]
My Kafka connect pods are up and running 

```
NAME                                            READY   STATUS    RESTARTS   AGE
pod/my-connect-cluster-connect-0                1/1     Running   0          66m
pod/my-connect-cluster-connect-1                1/1     Running   0          66m
pod/my-connect-cluster-connect-2                1/1     Running   0          66m
pod/strimzi-cluster-operator-658944789b-474f2   1/1     Running   0          5d5h

NAME                                     TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
service/my-connect-cluster-connect       ClusterIP   None            <none>        8083/TCP   66m
service/my-connect-cluster-connect-api   ClusterIP   172.20.149.23   <none>        8083/TCP   66m

NAME                                       READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/strimzi-cluster-operator   1/1     1            1           30d

NAME                                                  DESIRED   CURRENT   READY   AGE
replicaset.apps/strimzi-cluster-operator-658944789b   1         1         1       30d
```

Using this "    strimzi.io/use-connector-resources: "true"" in my kafkaconnect manifeast file. But when i am trying to apply kafkaconnector facing below issue:

```
Error:
    Last Transition Time:  2023-11-17T10:17:00.132377666Z
    Message:               PUT /connectors/poctest/config returned 500 (Internal Server Error): IO Error trying to forward REST request: java.net.SocketTimeoutException: Connect Timeout
    Reason:                ConnectRestException
    Status:                True
    Type:                  NotReady

```

Below is my connector config:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: poctest
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 2
  config:
    database.hostname: rds.amazonaws.com
    database.port: 5432
    database.user: postgres
    database.password: 
    database.server.name:
    database.whitelist: debezium
    # database.history.kafka.bootstrap.servers: 
    table.include.list: debezium.order
    transforms: Reroute,extractKeyFromStruct
    transforms.extractKeyFromStruct.type: org.apache.kafka.connect.transforms.ExtractField$Key
    transforms.extractKeyFromStruct.field: id
    transforms.Reroute.type: io.debezium.transforms.ByLogicalTableRouter
    transforms.Reroute.topic.regex: (.*)debezium.order
    topic.prefix: POCPostgres-
    database.dbname:
    transforms.Reroute.topic.replacement:
    key.enforce.uniqueness: false
```

Note: i removed server/user details from above while posting here.

I created networkpolicy as well:

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-connect-ui
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          strimzi.io/cluster: my-connect-cluster
          strimzi.io/kind: KafkaConnect
          strimzi.io/name: my-connect-cluster-connect
    - namespaceSelector: {}

    ports:
    - port: 8083
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/cluster: my-connect-cluster
      strimzi.io/kind: KafkaConnect
      strimzi.io/name: my-connect-cluster-connect
  policyTypes:
  - Ingress
```

    Please help if i am missing something
