### DISCUSSION TITLE
Customize kafka config

### DISCUSSION THREAD

**Discussion by jackchuong** [strimzi/strimzi-kafka-operator#9409] [Q&A] [answered]
Hi all,
I'm using Strimzi Kafka operator for creating and managing Kafka on K8S, here my yaml
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster1
  namespace: kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      num.partitions: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.4.0"
      log.cleanup.policy: compact,delete
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: nfs-idcnas002
        size: 10Gi
        deleteClaim: true
    resources:
      requests:
        memory: 1Gi
        cpu: "0.5"
      limits:
        memory: 4Gi
        cpu: "2"
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: nfs-idcnas002
      size: 10Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
How can I customize kafka configuration as below ?
```
echo producer.override.linger.ms=50 >> /opt/kafka/config/kraft/server.properties
echo producer.override.batch.size=40000 >> /opt/kafka/config/kraft/server.properties
```
