### DISCUSSION TITLE
Why the memory consumption of my brokers are constantly going up? Feels like everything is getting stored in memory

### DISCUSSION THREAD

**Discussion by npandeya** [strimzi/strimzi-kafka-operator#9445] [Q&A]
This is my cluster specification. I am writing test data constantly into a kafkatopic on this cluster with 120 partitions. When I check my messages, the memory consumption of each of the broker actually goes above the limit or slowly goes up and constantly. This is the grafana dashboard screenshot as well. Any guidance will be highly appreciated 
![kafka](https://github.com/strimzi/strimzi-kafka-operator/assets/52768607/0b278462-adf3-460b-bdb1-45a8454c8018)

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: test-cluster
  namespace: kafka
spec:
  kafka:
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-purpose
                  operator: In
                  values:
                  - kafka
    resources:
      requests:
        memory: 24Gi # changed from 8 on 20 sep
        cpu: "1"
      limits:
        memory: 48Gi
        cpu: "2"
    version: 3.4.0
    replicas: 30
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: true
        authentication:
          type: tls

      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        type: cluster-ip
        tls: true
        port: 9096
        authentication:
          type: tls
    authorization: 
      type: simple
        
    config:
      offsets.topic.replication.factor: 3 
      num.partitions: 30000
      transaction.state.log.replication.factor: 3 
      transaction.state.log.min.isr: 2
      default.replication.factor: 2 
      min.insync.replicas: 1
      log.retention.hours: 24 
      # log.segment.bytes: 2147483648 # 2gb
      log.retention.check.interval.ms: 300000
      num.network.threads: 24 # initially it was 3 changed on 29 jun #12
      num.io.threads: 64 # Initially it was 8 changed on 29 Jun   #16
      num.recovery.threads.per.data.dir: 8 # Initially it was 1 # 4
      inter.broker.protocol.version: "3.4"
      # More config
      auto.create.topics.enable: false 
      auto.leader.rebalance.enable: true 
      compression.type: snappy 
      controlled.shutdown.enable: true 
      controlled.shutdown.max.retries: 3
      controlled.shutdown.retry.backoff.ms: 5000
      delete.topic.enable: true 
      producer.purgatory.purge.interval.requests: 10000
      queued.max.requests: 500
      ssl.enabled.protocols: TLSv1.2

    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: kafka
        size: 500Gi
        deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    # jvmOptions:
    #   javaSystemProperties:
    #     - name: zookeeper.ssl.hostnameVerification
    #       value: "false"
    #     - name: zookeeper.ssl.quorum.hostnameVerification
    #       value: "false"
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-purpose
                  operator: In
                  values:
                  - kafka
    storage:
      type: persistent-claim
      size: 125Gi # st1 volume must be at least 125 
      deleteClaim: false
      class: kafka
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-purpose
                  operator: In
                  values:
                  - kafka
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
  kafkaExporter:
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-purpose
                  operator: In
                  values:
                  - kafka
    topicRegex: ".*"
    groupRegex: ".*"
```

**Comment by scholzj** [comment]
The configuration is badly formatted and not readable. It might depend on many things, but in general yes. Part of the memory will be taken by Java and the rest will be likely filled with the disk page cache keeping the data written to the disk to be able to quickly access them. So with enough time, it will likely eventually consume all the memory you give it. Whether it really needs the memory, that is a different question and will at the end depend a lot on the use-cases, performance you expect etc.

**Reply by npandeya** [reply]
Hi , 
let me add my config here. What would you recommend to fix this issue? I feel like strimzi is not even writing to the disk and just keeping everything on the memory. What would be the best practice for the prod situation?
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: testcluster
  namespace: kafka
spec:
  kafka:
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-purpose
                  operator: In
                  values:
                  - kafka
    resources:
      requests:
        memory: 24Gi # changed from 8 on 20 sep
        cpu: "1"
      limits:
        memory: 48Gi
        cpu: "2"
    version: 3.4.0
    replicas: 30
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: true
        authentication:
          type: tls

      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        type: cluster-ip
        tls: true
        port: 9096
        authentication:
          type: tls
    authorization: 
      type: simple
        
    config:
      offsets.topic.replication.factor: 3 
      num.partitions: 30000
      transaction.state.log.replication.factor: 3 
      transaction.state.log.min.isr: 2
      default.replication.factor: 2 
      min.insync.replicas: 1
      log.retention.hours: 24 
      # log.segment.bytes: 2147483648 # 2gb
      log.retention.check.interval.ms: 300000
      num.network.threads: 24 # initially it was 3 changed on 29 jun #12
      num.io.threads: 64 # Initially it was 8 changed on 29 Jun   #16
      num.recovery.threads.per.data.dir: 8 # Initially it was 1 # 4
      inter.broker.protocol.version: "3.4"
      # More config
      auto.create.topics.enable: false 
      auto.leader.rebalance.enable: true 
      compression.type: snappy 
      controlled.shutdown.enable: true 
      controlled.shutdown.max.retries: 3
      controlled.shutdown.retry.backoff.ms: 5000
      delete.topic.enable: true 
      producer.purgatory.purge.interval.requests: 10000
      queued.max.requests: 500
      ssl.enabled.protocols: TLSv1.2

    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: kafka
        size: 500Gi
        deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 3
    # jvmOptions:
    #   javaSystemProperties:
    #     - name: zookeeper.ssl.hostnameVerification
    #       value: "false"
    #     - name: zookeeper.ssl.quorum.hostnameVerification
    #       value: "false"
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-purpose
                  operator: In
                  values:
                  - kafka
    storage:
      type: persistent-claim
      size: 125Gi # st1 volume must be at least 125 
      deleteClaim: false
      class: kafka
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-purpose
                  operator: In
                  values:
                  - kafka
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
  kafkaExporter:
    template:
      pod:
        tolerations:
          - key: "dedicated"
            operator: "Equal"
            value: "kafka"
            effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-purpose
                  operator: In
                  values:
                  - kafka
    topicRegex: ".*"
    groupRegex: ".*"
```
