### DISCUSSION TITLE
How to pass JVM options to KafkaConnect with the exact order?

### DISCUSSION THREAD

**Discussion by mikekamornikov** [strimzi/strimzi-kafka-operator#9475] [General]
The following config after being applied
```yaml
jvmOptions:
  -XX:
    ExitOnOutOfMemoryError: true
    InitialRAMPercentage: 30
    MaxHeapFreeRatio: 30
    MaxRAMPercentage: 80
    MinHeapFreeRatio: 10
    UnlockExperimentalVMOptions: true
    UseShenandoahGC: true
    ShenandoahUncommit: true
    ShenandoahGCHeuristics: compact
```
results into
```yaml
jvmOptions:
  -XX:
    ExitOnOutOfMemoryError: true
    InitialRAMPercentage: 30
    MaxHeapFreeRatio: 30
    MaxRAMPercentage: 80
    MinHeapFreeRatio: 10
    ShenandoahGCHeuristics: compact
    ShenandoahUncommit: true
    UnlockExperimentalVMOptions: true
    UseShenandoahGC: true
```

The pod crashes with
```
Error: VM option 'ShenandoahUncommit' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.
Error: The unlock option must precede 'ShenandoahUncommit'.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Is there any ENV I can use to pass OPTS string as a whole?

**Comment by mikekamornikov** [comment]
It's the same one - https://github.com/strimzi/strimzi-kafka-operator/issues/3418

**Comment by mikekamornikov** [comment]
BTW, I've found the following:
```
private static final Set<String> JVM_PERFORMANCE_PRIORITY_OPTIONS = Set.of("UnlockDiagnosticVMOptions");
```
Probably this property could contain more `Unlock` flags.

**Reply by scholzj** [reply]
Feel free to open a PR for it if you want.

**Comment by mikekamornikov** [comment]
So far it looks like the following works fine:
```yaml
jvmOptions:
  -Xmx: 1000M
resources:
  limits:
    memory: 1600Mi
  requests:
    cpu: 100m
    memory: 1200Mi
template:
  connectContainer:
    env:
    - name: KAFKA_JVM_PERFORMANCE_OPTS
      value: "-XX:+ExitOnOutOfMemoryError -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=30 -XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:+ShenandoahUncommit -XX:ShenandoahGCHeuristics=compact"
```
- `.spec.template. connectContainer. env` sets the ENV which is usually calculated from `.spec.jvmOptions.-XX`
- `.spec.jvmOptions.-Xmx` causes generation of `KAFKA_HEAP_OPTS` env, so heap settings are not calculated automatically. Probably setting empty `KAFKA_HEAP_OPTS` has the same effect.
