### DISCUSSION TITLE
Offset translation isn't working for Multi-Region Strimzi cluster.

### DISCUSSION THREAD

**Discussion by AAR256** [strimzi/strimzi-kafka-operator#9487] [Q&A]
Hi,

We have Multi-Region Strimzi cluster deployed in Production environment running with Kafka version - 3.4.0. The MM2 config used for the setup in down below - 

```
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: pp-kafka-west-2
  namespace: kafka
spec:
  version: 3.4.0
  replicas: 3
  template:
    pod:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9404"
      tolerations:
      - key: "kubernetes.azure.com/scalesetpriority"
        operator: "Equal"
        value: "spot"
        effect: "NoSchedule"
  connectCluster: pp-north-1 #"my-cluster-target"
  clusters:
  - alias: pp-west-2 #"my-cluster-source"
    authentication:
      type: scram-sha-512
      username: pp-shared-admin
      passwordSecret:
        secretName: pp-shared-admin
        password: password
    bootstrapServers: pp-west-2-bootstrap.net:443
    tls:
      trustedCertificates:
        - secretName: pp-west-2-cert
          certificate: ca.crt

  - alias: pp-north-1 #"my-cluster-target"
    authentication:
      type: scram-sha-512
      username: pp-shared-admin
      passwordSecret:
        secretName: pp-shared-admin
        password: password
    bootstrapServers: pp-north-1-bootstrap.net:443
    tls:
      trustedCertificates:
        - secretName: pp-north-1-cert
          certificate: tls.crt
    config:
      # -1 means it will use the default replication factor configured in the broker
      config.storage.replication.factor: 3
      offset.storage.replication.factor: 3
      status.storage.replication.factor: 3
  mirrors:
  - sourceCluster: pp-west-2 #"my-cluster-source"
    targetCluster: pp-north-1 #"my-cluster-target"
    sourceConnector:
      config:
        replication.factor: 3
        offset-syncs.topic.replication.factor: 3
        tasks.max: 6
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 3
        sync.group.offsets.enabled: true
    topicsPattern: ".*"
    groupsPattern: ".*"
  resources:
    requests:
      memory: 4Gi
      cpu: "1"
    limits:
      memory: 8Gi
      cpu: "2"
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: mirror-maker-2-metrics
        key: metrics-config.yml
---
```

The scenario I'm trying to figure out is that I have 2 regions - West and North. If a topic is created in West region with few messages consumed in the same region. Through MM2 I should be able to consume the subsequent offsets in North region which has the replicated events using the same consumer group. But that doesn't seem to be the case. During consumption with the same consumer group, it's starting over from the initial offset. Please let me know if I'm missing something here.
