### DISCUSSION TITLE
Request for Support of Custom Readiness Probe

### DISCUSSION THREAD

**Discussion by m2khosravi** [strimzi/strimzi-kafka-operator#9509] [Q&A]
Hi Team, 

I've observed that the current readinessProbe functionality in Streamzi Operator only permits basic TCP socket checks for broker liveness by confirming the existence of a file managed by kafka-agent. 
```
readinessProbe:
  exec:
    command:
    - test
    - -f
    - /var/opt/kafka/kafka-ready

```

However, there's a possibility that the broker process is running without the ability to handle requests effectively. I'm considering solutions, such as enabling an HTTP custom endpoint for readiness checks to determine whether Kafka brokers are genuinely ready to process requests, This would give a better understanding of whether Kafka brokers are really prepared to handle requests.

appreciated your feedback on this matter.

Best,
Mahdi
