### DISCUSSION TITLE
Mirror Maker 2 | offset sync topics creating without '.' dot

### DISCUSSION THREAD

**Discussion by senthil13** [strimzi/strimzi-kafka-operator#9541] [General]
Hi Experts,
I was using the strimzi connector version `31.1`  and testing the mirror maker functionality.  Everything worked fine, but the internal topics were created without `.` on the source cluster. Am I missing something? Please find my mirrormaker.yaml file below. ( I was following this git repo --> https://github.com/rmarting/strimzi-migration-demo)

At the target cluster
```
kafkatopic.kafka.strimzi.io/heartbeats
kafkatopic.kafka.strimzi.io/mirrormaker2-cluster-configs
kafkatopic.kafka.strimzi.io/mirrormaker2-cluster-offsets
kafkatopic.kafka.strimzi.io/mirrormaker2-cluster-status
kafkatopic.kafka.strimzi.io/mm-topic
kafkatopic.kafka.strimzi.io/source-cluster.checkpoints.internal
```

At the source cluster ( note that I created manually the topic with the .)
```
kafkatopic.kafka.strimzi.io/mm-topic
kafkatopic.kafka.strimzi.io/mm2-offset-syncs.target-cluster.internal
kafkatopic.kafka.strimzi.io/mm2-offset-syncstarget-clusterinternal
```

Mirror maker, Yaml file
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker-2
  namespace: target-kafka-cluster
spec:
  version: 3.2.3
  replicas: 1
  connectCluster: "target-cluster" # Must be the target cluster
  clusters:
  - alias: "source-cluster"
    bootstrapServers: "source-cluster-kafka-brokers.source-kafka-cluster:9092"
    config:
      # -1 means it will use the default replication factor configured in the broker
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  - alias: "target-cluster" # Target cluster
    bootstrapServers: "target-cluster-kafka-brokers.target-kafka-cluster:9092"
    config:
      # -1 means it will use the default replication factor configured in the broker
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "source-cluster"
    targetCluster: "target-cluster"
    sourceConnector:
      tasksMax: 1
      config:
        # -1 means it will use the default replication factor configured in the broker
        replication.factor: -1
        offset-syncs.topic.replication.factor: -1
        sync.topic.acls.enabled: "false"
        replication.policy.separator: ""
        # Instead of prepending the name with the name of the source cluster, the topic retains its original name
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
        refresh.topics.interval.seconds: 60
    heartbeatConnector:
      config:
        # Internal topic 'heartbeats' created at the target cluster
        heartbeats.topic.replication.factor: 3        
    checkpointConnector:
      tasksMax: 1
      config:
        # -1 means it will use the default replication factor configured in the broker
        checkpoints.topic.replication.factor: -1
        # Offset synchronization periodically transfers the consumer offsets for the consumer groups
        # of a source cluster into the consumer offsets topic of a target cluster.        
        sync.group.offsets.enabled: "true"
        refresh.groups.interval.seconds: 60
        # Instead of prepending the name with the name of the source cluster, the topic retains its original name
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
    topicsPattern: ".*"
    groupsPattern: ".*"
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  readinessProbe:
    initialDelaySeconds: 45
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 45
    timeoutSeconds: 5
```

Both source and target Kafka clusters are running on the same k8s in separate namespaces. Can someone suggest what I am doing wrong here?
