### DISCUSSION TITLE
[Bug]: Doesn't reconcile kafka connector

### DISCUSSION THREAD

**Discussion by hoptical** [strimzi/strimzi-kafka-operator#9542] [General]
### Bug Description

We have installed the Strimzi operator on our cluster and created some objects including the `Kafka` cluster, `Kafkaconnect`, and some `KafkaConnectors`. However, after a couple of months, Kafka Connectors weren't reconciled anymore. We noticed that by checking the status of the newly created connectors in which there wasn't any status field meaning that the reconciliation didn't happen for them. Objects like Kafka and kafkaconnects were reconciled properly but not the same for Kafkaconnectors.
Additionally, there wasn't any record regarding the connectors in the operator log.

Finally, the issue was resolved after restarting the operator but we're worried about this problem in the future since it needs our manual action for restarting the operator pod.

It seems that it could be related to `futures` mentioned in [here](https://github.com/strimzi/strimzi-kafka-operator/issues/6944#issuecomment-1156605392) and #5691.

### Steps to reproduce

1. Create some resources including `Kafka`, `KafkaConnect`, `KafkaConnector`.
2. After a while (maybe a long time), the operator won't reconcile `KafkaConnector` objects anymore.

### Expected behavior

The operator must always reconcile all objects, no matter how many objects are already existed there.

### Strimzi version

0.35.1

### Kubernetes version

Openshift 4.10

### Installation method

OperatorHub.io

**Comment by scholzj** [comment]
For a start, you have to provide more details about the supposed bug:
* Share the full custom resources including the status where available
* Share the full logs form the Cluster Operator
* etc.

**Comment by hoptical** [comment]
Sure. 

Here is the `KafkaConnector` object before having problem with the operator (I know it's a failed connector):
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: debezium-connect-cluster
  name: debezium-connector-mysql
  namespace: connector-testing
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  config:
    database.history.kafka.bootstrap.servers: debezium-cluster-kafka-bootstrap:9092
    database.history.kafka.topic: schema-changes
    database.server.name: mysql
  tasksMax: 1
status:
  conditions:
  - lastTransitionTime: "2024-01-02T20:08:23.962570749Z"
    message: KafkaConnect resource 'debezium-connect-cluster' identified by label
      'strimzi.io/cluster' does not exist in namespace connector-testing.
    reason: NoSuchResourceException
    status: "True"
    type: NotReady
  observedGeneration: 1
  tasksMax: 0

```

After detecting problem with the operator, we recreated the object that didn't have the `status` field anymore:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: debezium-connect-cluster
  name: debezium-connector-mysql
  namespace: connector-testing
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  config:
    database.history.kafka.bootstrap.servers: debezium-cluster-kafka-bootstrap:9092
    database.history.kafka.topic: schema-changes
    database.server.name: mysql
  tasksMax: 1

```
The operator log is attached. It has logs only for two days.
[strimzi-operator.log.tar.gz](https://github.com/strimzi/strimzi-kafka-operator/files/13842220/strimzi-operator.log.tar.gz)
