### DISCUSSION TITLE
[Bug]: Cruise control is not honoring hard goals

### DISCUSSION THREAD

**Discussion by sreelu27** [strimzi/strimzi-kafka-operator#9546] [General]
### Bug Description

Cruise control is not honoring hard goals. RackAwareGoal only provided as hard goal for cruise Control, but KafkaRebalance is failing due to NetworkInboundCapacityGoal not statisfied, even though NetworkInboundCapacityGoal is not part of hard goals.

kafka cluster spec :

```
cruiseControl:
    config:
      hard.goals:
        com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal
```

KafkaRebalance failing with error "com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException: [NetworkInboundCapacityGoal] Insufficient capacity for networkInbound"

### Steps to reproduce

 1. Add com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal only as hard.goals for cruise Control Configuration.
 2. Deployed the system.
 3. Produce events with more than inbound Network capacity configured per node in cruise Control Configuration (Default is 10000 Kib/s), so if you have 3 node and planning to scale out for 6 nodes, then events to be produce more than inboutNetworkCapatiy*no.of node, in this case it should more than 70000 kib/s.
 4. Keep produce events and scale out Kafka pods from 3 to 6, and wait till all pods to come running state.
 5. Apply KafkaRebalance (below is for reference)
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: rebalance
  labels:
    strimzi.io/cluster: bug
# no goals specified, using the default goals from the Cruise Control configuration
spec:
  mode: add-brokers 
  brokers: [3, 4, 5]
```
  6. KafkaRebalance failing with error "com.linkedin.kafka.cruisecontrol.exception.OptimizationFailureException: 
  [NetworkInboundCapacityGoal] Insufficient capacity for networkInbound".

### Expected behavior

If hard goals are statisfied, then other goals can ignore even if it not satisfies and KafkaRebalance should come to PROPOSALREADY as true.

### Strimzi version

0.36.1

### Kubernetes version

1.27.6

### Installation method

Helm chart

**Comment by scholzj** [comment]
You should probably start by sharing the full Kafka custom resource and make sure it is correctly formatted. You should also compare it with the API reference and make sure what you have there corresponds to it. I don't think there are any `enableAutomation`, `enable` or `autoApprovalInterval` fields.

**Comment by sreelu27** [comment]


**Reply by scholzj** [reply]
While there are some similarities, that does not look like Strimzi. Strimzi custom resource would look for example like this: https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/kafka/kafka-persistent.yaml

**Reply by ppatierno** [reply]
It's a `MessageBus` custom resource ... for sure not part of Strimzi :-)

**Comment by sreelu27** [comment]
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: bug
  namespace: tr
spec:
  cruiseControl:
    brokerCapacity:
      inboundNetwork: 10KB/s
      outboundNetwork: 10KB/s
    config:
      hard.goals: com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal
    resources:
      limits:
        cpu: "3"
        memory: 2Gi
      requests:
        cpu: "2"
        memory: 1Gi
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: "3"
          memory: 2Gi
        requests:
          cpu: "2"
          memory: 1Gi
    userOperator:
      resources:
        limits:
          cpu: "3"
          memory: 2Gi
        requests:
          cpu: "2"
          memory: 1Gi
  kafka:
    config:
      default.replication.factor: 3
      min.insync.replicas: 2
    rack:
      topologyKey: kubernetes.io/hostname
    replicas: 6
    resources:
      limits:
        cpu: "3"
        memory: 2Gi
      requests:
        cpu: "2"
        memory: 1Gi
    storage:
      class: network-block
      size: 25Gi
      type: persistent-claim
    version: 3.5.1
  zookeeper:
    replicas: 1
    resources:
      limits:
        cpu: "3"
        memory: 2Gi
      requests:
        cpu: "2"
        memory: 1Gi
    storage:
      class: network-block
      size: 15Gi
      type: persistent-claim``
```
