### DISCUSSION TITLE
*Some* Kafka Connectors started to fail resolving secrets via KubernetesSecretConfigProvider

### DISCUSSION THREAD

**Discussion by schunggit** [strimzi/strimzi-kafka-operator#9575] [General]
**Problem:** 
The `secrets` provider in **some** KafkaConnectors started to fail to access/resolve the secret values.

**Worth Noting**
1. The `secrets` provider had been functioning properly until recently.
2. The problem occurs with **some** connectors.  If I delete the existing one and create a new one, I can reproduce the issue.

**Detailed Steps:**
1. Configure a `KafkaConnect` with the `secrets` provider
```
k describe kafkaconnect source-connectors-cluster
Name:         source-connectors-cluster
Namespace:    staging-fsm
Labels:       app.kubernetes.io/managed-by=Helm
Annotations:  meta.helm.sh/release-name: source-connectors-cluster
              meta.helm.sh/release-namespace: staging-fsm
              strimzi.io/use-connector-resources: true
API Version:  kafka.strimzi.io/v1beta2
Kind:         KafkaConnect
Metadata:
  Creation Timestamp:  2022-04-28T21:06:08Z
  Generation:          25
  Resource Version:    1303885128
  UID:                 908b63ac-fd26-4d13-8415-197265a288ba
Spec:
  Bootstrap Servers:  staging-fsm-kafka-bootstrap.staging-fsm:9092
  Config:
    config.providers:                         secrets
    config.providers.secrets.class:           io.strimzi.kafka.KubernetesSecretConfigProvider
    config.storage.replication.factor:        3
    config.storage.topic:                     source-connectors-cluster-configs
    connector.client.config.override.policy:  All
    group.id:                                 source-connectors-cluster
   . . .
```
2. Create a `KafkaConnector` with the `secrets` provider to configure the database password from a k8s secret
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: my-gb-adapter-connector
  namespace: staging-fsm
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  config:
    connector.class: io.debezium.connector.postgresql.PostgresConnector
    database.dbname: my_gb_adapter
    database.history.kafka.bootstrap.servers: staging-fsm-kafka-bootstrap.staging-fsm:9092
    database.history.kafka.topic: my_gb_history
    database.hostname: my-gb-adapter-core_staging.engdev03.flexport.internal
    database.password: ${secrets:staging-fsm/my-gb-adapter-postgres-secrets:my-gb-adapter-connector-secret}
    . . .
```
3. The `KafkaConnector` is created but the secret value is not resolved.  
```
org.apache.kafka.connect.runtime.rest.errors.ConnectRestException: Invalid value io.fabric8.kubernetes.client.KubernetesClientException: Operation: [get]  for kind: [Secret]  with name: [my-gb-adapter-postgres-secrets]  in namespace: [staging-fsm]  failed. 
for configuration Failed to retrieve Secret my-gb-adapter-postgres-secrets from Kubernetes namespace staging-fsm
```
However, the secret does exist in the namespace.

4. Verified that the KafkaConnect pod itself can retrieve the secret value using the ServiceAccount.  The role has `get` access to all secrets in the namespace and there's a role biding for that SA. 
```
k exec -it source-connectors-cluster-connect-579bdfdb85-76qgt -- bash
[kafka@source-connectors-cluster-connect-579bdfdb85-76qgt kafka]$ TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
[kafka@source-connectors-cluster-connect-579bdfdb85-76qgt kafka]$ curl -H "Authorization: Bearer $TOKEN" -k https://kubernetes.default.svc/api/v1/namespaces/staging-fsm/secrets/my-gb-adapter-postgres-secrets
{
  "kind": "Secret",
  "apiVersion": "v1",
  "metadata": {
    "name": "my-gb-adapter-postgres-secrets",
    "namespace": "staging-fsm",
   ...
  "data": {
    "my-gb-adapter-connector-secret": "<<redacted>>"
  },
  "type": "Opaque"
}
```

**Question:** 
 Can someone think of reason why this started to happen suddenly and why this can happen to some connectors only?
 
<img width="1356" alt="image" src="https://github.com/strimzi/strimzi-kafka-operator/assets/156138125/722623f4-d5c6-4b0d-859b-e72e66673804">

**Environment:**
  Kafka: quay.io/strimzi/kafka:0.36.0-kafka-3.5.0
