### DISCUSSION TITLE
How can I see the connector log?

### DISCUSSION THREAD

**Discussion by smeeklai** [strimzi/strimzi-kafka-operator#9583] [Q&A] [answered]
I'm trying to run `s3-sink` using the `KafkaConnect`. I'm seeing the connector status is ready and it seems to run fine but I expect to see some error logs because the connector doesn't have permission to interact with the bucket yet. However, I can't find it in the connect pod. Please guide me.

Kafka cluster: MSK

KafkaConnect
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-connect-s3
  namespace: strimzi-kafka-operator
  annotations:
   strimzi.io/use-connector-resources: "true"
spec:
  version: 3.4.0
  replicas: 1
  bootstrapServers: xxx:9096,xxx:9096
  image: xxxx:tmp
  tls:
    trustedCertificates: []
  authentication:
    passwordSecret:
      password: password
      secretName: creds
    type: scram-sha-512
    username: app
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
```

KafkaConnector
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: kafka-connect-s3-connector
  namespace: strimzi-kafka-operator
  labels:
    strimzi.io/cluster: kafka-connect-s3
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  config:
    s3.region: ap-southeast-1
    s3.part.retries: 1
    format.class: io.confluent.connect.s3.format.json.JsonFormat
    flush.size: 1
    schema.compatibility: NONE
    topics.regex: ^(?!__)\\S+$
    tasks.max: 2
    partitioner.class: io.confluent.connect.storage.partitioner.DefaultPartitioner
    storage.class: io.confluent.connect.s3.storage.S3Storage
    s3.bucket.name: xxxxx
    errors.log.enable: true
```
Logs:
[kafka-connect-s3-connect.log](https://github.com/strimzi/strimzi-kafka-operator/files/14024718/kafka-connect-s3-connect.log)

Thanks
