### DISCUSSION TITLE
AKS internal loadbalancer - broker is listing with IP address not the dns name

### DISCUSSION THREAD

**Discussion by Veljen** [strimzi/strimzi-kafka-operator#9587] [Q&A] [answered]
Hi,

we used external listener 9094 for the internal loadbalancer.  we have no external dns installed on AKS, we manage the dns records through terraform / manual.  I would like to get the dns name instead of IP address for the broker..

```
 3 brokers:
  broker 0 at 10.88.4.36:9094 (controller)
  broker 2 at 10.88.4.35:9094
  broker 1 at 10.88.4.37:9094
```

```
- authentication:
          type: tls
        configuration:
          bootstrap:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          brokers:
          - annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            broker: 0
          - annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            broker: 1
          - annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
            broker: 2
        name: external
        port: 9094
        tls: true
        type: loadbalancer
```

without external dns , how can we override the external dns name for the broker and bootstrap for the loadbalancer type ?
