### DISCUSSION TITLE
Can I bind DNS using Loadbalancer? In a private cloud environment

### DISCUSSION THREAD

**Discussion by peter-hst** [strimzi/strimzi-kafka-operator#9594] [Q&A] [answered]
we using `strimzi-v0.32.0` , After trying various configurations, it seems that it cannot bind DNS, right? It is possible to produce/consume messages using LB-IP directly. Could you help support ? Thanks a lot!

```yaml
    listeners:
      - name: plain
        type: internal
        port: 9092
        tls: false
      - name: external
        port: 9094
        # https://strimzi.io/docs/operators/0.32.0/configuring#property-listener-config-annotations-reference
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          # useServiceDnsDomain: true
          bootstrap:
            # host: kafka-bootstrap-demo.test.com
            loadBalancerIP: 10.237.203.34
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap-demo.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
          - broker: 0
            # host: kafka-broker-demo-0.test.com
            loadBalancerIP: 10.237.201.45
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-demo-0.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 1
            # host: kafka-broker-demo-1.test.com
            loadBalancerIP: 10.237.203.118
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-demo-1.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 2
            # host: kafka-broker-demo-2.test.com
            loadBalancerIP: 10.237.202.160
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-demo-2.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
```

when I enabled/disabled that `host: kafka-bootstrap-demo.test.com`, `host: kafka-broker-demo-0.test.com`, `host: kafka-broker-demo-1.test.com`, `host: kafka-broker-demo-2.test.com` options(only for nodeport?), it doesn't work. I don't knows the reason.

<img width="1584" alt="Screenshot 2024-01-25 at 16 52 32" src="https://github.com/strimzi/strimzi-kafka-operator/assets/4138222/7ee81239-03f2-4298-8a1b-5bbaacde20cf">

**Comment by peter-hst** [comment]
If I use the following options, does it support Loadbalancer?

```yaml
listeners:
  #...
  - name: external
    port: 9094
    type: loadbalancer
    tls: true
    authentication:
      type: tls
    configuration:
      brokers:
      - broker: 0
        advertisedHost: kafka-broker-demo-0.test.com
        advertisedPort: 9094
      - broker: 1
        advertisedHost: kafka-broker-demo-1.test.com
        advertisedPort: 9094
      - broker: 2
        advertisedHost: kafka-broker-demo-2.test.com
        advertisedPort: 9094
```

**Comment by scholzj** [comment, marked as answer]
Strimzi integrates with Kubernetes and not with your DNS. If you want to use custom DNS names, you have to set them up yourself or using other tools. The documentation (and multiple previous discussions) covers how to add additional names to the certificates (`alternativeNames` property) or how to override advertised hostnames (`advertisedHost` property). Please check there for examples.

**Reply by peter-hst** [reply]
Hello Scholzj @scholzj  Thank you ! do you have the link?

[this one](https://strimzi.io/docs/operators/0.32.0/configuring#property-listener-config-altnames-reference)?

**Reply by scholzj** [reply]
I do not have a link at hand. You can search for the fields I mentioned.

**Reply by peter-hst** [reply]
It works! Thanks a lot!
```yaml
            alternativeNames:
              - kafka-bootstrap-demo.test.com ### It works! only added this line
              - kafka-broker-demo-0.test.com ### borkers list, is it right?
              - kafka-broker-demo-1.test.com ### borkers list, is it right?
              - kafka-broker-demo-2.test.com ### borkers list, is it right?
```
you solved a big deal. 😀


can I settings blow options?

```yaml
    listeners:
      - name: plain
        type: internal
        port: 9092
        tls: false
      - name: external
        port: 9094
        # https://strimzi.io/docs/operators/0.32.0/configuring#property-listener-config-annotations-reference
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          # useServiceDnsDomain: true
          bootstrap:
            # host: kafka-bootstrap-demo.test.com
            alternativeNames:
              - kafka-bootstrap-demo.test.com
            loadBalancerIP: 10.237.203.34
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap-demo.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
          brokers:
          - broker: 0
            # host: kafka-broker-demo-0.test.com
            advertisedHost: kafka-broker-demo-0.test.com
            advertisedPort: 9094
            loadBalancerIP: 10.237.201.45
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-demo-0.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 1
            # host: kafka-broker-demo-1.test.com
            advertisedHost: kafka-broker-demo-1.test.com
            advertisedPort: 9094
            loadBalancerIP: 10.237.203.118
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-demo-1.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
          - broker: 2
            # host: kafka-broker-demo-2.test.com
            advertisedHost: kafka-broker-demo-2.test.com
            advertisedPort: 9094
            loadBalancerIP: 10.237.202.160
            annotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-demo-2.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
```
