### DISCUSSION TITLE
Deploy Kafka , where dynamic volume provision is not avilable

### DISCUSSION THREAD

**Discussion by ranjith-ka** [strimzi/strimzi-kafka-operator#9675] [General]
Hi Team,

Can you advise, how to deploy kafka on environment dont have dynamic PVC.

PVC is created already, i have added the lables, 

kubectl label pvc pvc-crn-27087-784 "blu-kafka=0"

kubectl patch pvc pvc-crn-27087-784  -p '{"metadata":{"labels":{"blu-kafka":"0"}}}'

Looks the configs not supported !!! any help in this ? 

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: blu-kafka
  namespace: default
spec:
  kafka:
    version: 3.6.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
        selector:
          blu-kafka: 0
      - id: 1
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
        selector:
          blu-kafka: 1
      - id: 2
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
        selector:
          blu-kafka: 2
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      selector:
        blu-zookeper: 0
  entityOperator:
    topicOperator: {}
    userOperator: {}
    
   ```
