### DISCUSSION TITLE
Static Loadbalancer IPs for broker services with KafkaNodePools

### DISCUSSION THREAD

**Discussion by mitchell5297** [strimzi/strimzi-kafka-operator#9680] [Q&A] [answered]
I am using the KafkaNodePools feature in an AKS cluster and I am trying to set static IPs for the loadbalancer services for each broker. I have it so that it will set the IP for the first broker service in each pool but I am having trouble getting it to do it for multiple brokers. Here is my yaml file for the CRD:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafkanodepool1
  labels:
    strimzi.io/cluster: kafkacl2
  annotations:
    strimzi.io/next-node-ids: "[100-199]"
spec:
  replicas: 2
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 256Gi
        deleteClaim: true
        class: default
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - eastus-1
    perPodService:
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-ipv4: x.x.x.x
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafkanodepool2
  labels:
    strimzi.io/cluster: kafkacl2
  annotations:
    strimzi.io/next-node-ids: "[200-299]"
spec:
  replicas: 2
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 256Gi
        deleteClaim: true
        class: default
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - eastus-2
    perPodService:
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-ipv4: x.x.x.x
---

apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafkanodepool3
  labels:
    strimzi.io/cluster: kafkacl2
  annotations:
    strimzi.io/next-node-ids: "[300-399]"
spec:
  replicas: 2
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 256Gi
        deleteClaim: true
        class: default
  template:
    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - eastus-3
    perPodService:
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-ipv4: x.x.x.x
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafkacl2
  annotations:
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.6.1
    # The replicas field is required by the Kafka CRD schema while the KafkaNodePools feature gate is in alpha phase.
    # But it will be ignored when Kafka Node Pools are used
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: externaltls
        port: 19092
        type: loadbalancer
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              service.beta.kubernetes.io/azure-load-balancer-ipv4: x.x.x.x
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.6"
    # The storage field is required by the Kafka CRD schema while the KafkaNodePools feature gate is in alpha phase.
    # But it will be ignored when Kafka Node Pools are used
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 64Gi
        deleteClaim: false
    rack:
      topologyKey: topology.kubernetes.io/zone
    config:
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 64Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

**Comment by scholzj** [comment]
Can you please format the code to make it readable?

**Reply by mitchell5297** [reply]
Sorry, it is readable now.

**Reply by scholzj** [reply]
Well, this part:
```yaml
    perPodService:
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-ipv4: x.x.x.x
```

would set the same IP address to each load balancer service. I guess that would not work? But you should be able to set different annotations for each broker using this in the listener configuration in `Kafka` custom resource: https://strimzi.io/docs/operators/latest/full/configuring.html#property-listener-config-annotations-reference

**Reply by mitchell5297** [reply]
When I set the listener to have the following config:
```yaml
      - name: externaltls
        port: 19092
        type: loadbalancer
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              service.beta.kubernetes.io/azure-load-balancer-ipv4: "x.x.x.x"
          brokers:
          - broker: 0
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              service.beta.kubernetes.io/azure-load-balancer-ipv4: "x.x.x.x"
          - broker: 1
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              service.beta.kubernetes.io/azure-load-balancer-ipv4: "x.x.x.x"
          - broker: 2
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              service.beta.kubernetes.io/azure-load-balancer-ipv4: "x.x.x.x"
          - broker: 3
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              service.beta.kubernetes.io/azure-load-balancer-ipv4: "x.x.x.x"
          - broker: 4
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              service.beta.kubernetes.io/azure-load-balancer-ipv4: "x.x.x.x"
          - broker: 5
            annotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
              service.beta.kubernetes.io/azure-load-balancer-ipv4: "x.x.x.x" 
```
The zookeepers freak out and give an unresolved address error.
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/159936075/4d272050-225f-429b-8d66-9334cab08127)

**Reply by scholzj** [reply]
I don't think that is related. ZooKeeper does not connect to Kafka, so it has nothing to do with the loadbalancers. Errors like this in ZooKeeper are usually caused by slow DNS / bug in ZooKEeper that des not let it recover from it.

**Reply by mitchell5297** [reply]
Do you know how to fix the ZooKeepers? I have tried this config multiple times and each time I get the same issue

**Reply by mitchell5297** [reply]
I also see these errors in the Strimzi operator
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/159936075/00393e10-56f7-49bc-ba33-e6e0d58282a2)

**Reply by scholzj** [reply]
I don't know your configuration, so not easy to say how to fix it. As I said, it is often caused by slow DNS, so sometimes restarting the DNS helps. Restarting the ZooKeeper pods manually with `kubectl delete pod`. It also helps to make sure to run ZooKeeper with 3 nodes and not just one. But no idea how many ZooKeeper nodes you have now.

**Reply by mitchell5297** [reply]
Okay, I restarted the ZooKeeper Pods and they stopped erroring. However, the services for the load balancers do not have any annotations in them now: 
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/159936075/9d6dc7af-f30c-411c-b2b6-088f872d5932)

**Reply by scholzj** [reply]
That seems strange. I think you would need to share the full custom resource including the status. Maybe that tells something.

**Reply by mitchell5297** [reply]
Here is the CR for the kafka cluster:
```yaml
Name:         kafkacl2
Namespace:    kafkacl2
Labels:       <none>
Annotations:  strimzi.io/node-pools: enabled
API Version:  kafka.strimzi.io/v1beta2
Kind:         Kafka
Metadata:
  Creation Timestamp:  2024-02-14T13:49:01Z
  Generation:          1
  Resource Version:    11855
  UID:                 146fef69-1e48-49bb-b0ef-da4fbfc8a430
Spec:
  Entity Operator:
    Topic Operator:
    User Operator:
  Kafka:
    Config:
      replica.selector.class:  org.apache.kafka.common.replica.RackAwareReplicaSelector
    Listeners:
      Name:  plain
      Port:  9092
      Tls:   false
      Type:  internal
      Name:  tls
      Port:  9093
      Tls:   true
      Type:  internal
      Authentication:
        Type:  tls
      Configuration:
        Bootstrap:
          Annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal:  true
            service.beta.kubernetes.io/azure-load-balancer-ipv4:      x.x.x.x
        Brokers:
          Annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal:  true
            service.beta.kubernetes.io/azure-load-balancer-ipv4:      x.x.x.x
          Broker:                                                     0
          Annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal:  true
            service.beta.kubernetes.io/azure-load-balancer-ipv4:      x.x.x.x
          Broker:                                                     1
          Annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal:  true
            service.beta.kubernetes.io/azure-load-balancer-ipv4:      x.x.x.x
          Broker:                                                     2
          Annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal:  true
            service.beta.kubernetes.io/azure-load-balancer-ipv4:      x.x.x.x
          Broker:                                                     3
          Annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal:  true
            service.beta.kubernetes.io/azure-load-balancer-ipv4:      x.x.x.x
          Broker:                                                     4
          Annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal:  true
            service.beta.kubernetes.io/azure-load-balancer-ipv4:      x.x.x.x
          Broker:                                                     5
      Name:                                                           externaltls
      Port:                                                           19092
      Tls:                                                            true
      Type:                                                           loadbalancer
    Rack:
      Topology Key:  topology.kubernetes.io/zone
    Replicas:        3
    Storage:
      Type:  jbod
      Volumes:
        Delete Claim:  false
        Id:            0
        Size:          64Gi
        Type:          persistent-claim
    Version:           3.6.1
  Zookeeper:
    Replicas:  3
    Storage:
      Delete Claim:  true
      Size:          64Gi
      Type:          persistent-claim
Status:
  Cluster Id:  UuGvswJpSPqzlqBnojRlDg
  Conditions:
    Last Transition Time:  2024-02-14T13:51:34.892158073Z
    Message:               default.replication.factor option is not configured. It defaults to 1 which does not guarantee reliability and availability. You should configure this option in .spec.kafka.config.
    Reason:                KafkaDefaultReplicationFactor
    Status:                True
    Type:                  Warning
    Last Transition Time:  2024-02-14T13:51:34.892284476Z
    Message:               min.insync.replicas option is not configured. It defaults to 1 which does not guarantee reliability and availability. You should configure this option in .spec.kafka.config.
    Reason:                KafkaMinInsyncReplicas
    Status:                True
    Type:                  Warning
    Last Transition Time:  2024-02-14T13:55:37.338693963Z
    Status:                True
    Type:                  Ready
  Kafka Node Pools:
    Name:         kafkanodepool1
    Name:         kafkanodepool2
    Name:         kafkanodepool3
  Kafka Version:  3.6.1
  Listeners:
    Addresses:
      Host:             kafkacl2-kafka-bootstrap.kafkacl2.svc
      Port:             9092
    Bootstrap Servers:  kafkacl2-kafka-bootstrap.kafkacl2.svc:9092
    Name:               plain
    Addresses:
      Host:             kafkacl2-kafka-bootstrap.kafkacl2.svc
      Port:             9093
    Bootstrap Servers:  kafkacl2-kafka-bootstrap.kafkacl2.svc:9093
    Certificates:
      -----BEGIN CERTIFICATE-----
<CERT STRING>
-----END CERTIFICATE-----

    Name:  tls
    Addresses:
      Host:             x.x.x.x
      Port:             19092
    Bootstrap Servers:  x.x.x.x:19092
    Certificates:
      -----BEGIN CERTIFICATE-----
<CERT STRING>
-----END CERTIFICATE-----

    Name:                            externaltls
  Observed Generation:               1
  Operator Last Successful Version:  0.39.0
Events:                              <none>
```
