### DISCUSSION TITLE
Receive failed: Invalid response size

### DISCUSSION THREAD

**Discussion by haroon9** [strimzi/strimzi-kafka-operator#9706] [Q&A] [answered]
We are using .net confluent Kafka client to connect to the Kafka broker but are getting the below errors. The Strimzi Kafka broker uses the default configuration, and we are not producing or consuming any messages, but as soon as the client pod starts, we start to get these logs.

```
%3|1708349623.158|ERROR|rdkafka#consumer-1| [thrd:app]: rdkafka#consumer-1: bootstrap-server-staging.mydomain.com:443/bootstrap: Receive failed: Invalid response size 1213486160 (0..100000000): increase receive.message.max.bytes (after 18ms in state APIVERSION_QUERY, 3 identical error(s) suppressed)
%3|1708349623.181|FAIL|rdkafka#producer-2| [thrd:bootstrap-server-staging.mydomain.com:443/bootstrap]: bootstrap-server-staging.mydomain.com:443/bootstrap: Receive failed: Invalid response size 1213486160 (0..100000000): increase receive.message.max.bytes (after 23ms in state APIVERSION_QUERY, 3 identical error(s) suppressed)
%3|1708349623.181|ERROR|rdkafka#producer-2| [thrd:app]: rdkafka#producer-2: bootstrap-server-staging.mydomain.com:443/bootstrap: Receive failed: Invalid response size 1213486160 (0..100000000): increase receive.message.max.bytes (after 23ms in state APIVERSION_QUERY, 3 identical error(s) suppressed)
```

Strimzi Kafka broker configuration:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  kafka:
    version: {{ .Values.kafka.version }}
    replicas: {{ .Values.kafka.replicas }}
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: INFO
    resources:
      {{ toYaml .Values.kafka.resources | nindent 6 }}
    readinessProbe:
      {{ toYaml .Values.kafka.readinessProbe | nindent 6 }}
    livenessProbe:
      {{ toYaml .Values.kafka.livenessProbe | nindent 6 }}
    listeners:
      - name: tls
        port: 9092
        type: internal
        tls: true
        authentication:
          type: tls
      - name: ingress
        port: 9093
        type: ingress
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            host: {{ .Values.kafka.bootstrap.host }}
          brokers:
            {{ toYaml .Values.kafka.brokers | nindent 10 }}
          class: nginx
    authorization:
        type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
```
