### DISCUSSION TITLE
strimzi-cluster-operator is up and running but other related pods are not comming up.

### DISCUSSION THREAD

**Discussion by mr-vardhan24** [strimzi/strimzi-kafka-operator#9736] [Q&A]
Hi,

We are using the Strimzi Kafka(without helm) operator version 0.26.0 in EKS v1.25.
we mistakenly run this command 
k delete strimzi-kafka-operator -n kafka

due to which our whole Kafka went down 
to resolve that we run the command 
kubectl apply -f install/cluster-operator -n Kafka

in this case, our strimzi-cluster-operator came up, but other pods, zookeepers, and brokers in not come up.
what we can do in this phase.

<img width="1046" alt="Screenshot 2024-02-23 at 3 39 58 PM" src="https://github.com/strimzi/strimzi-kafka-operator/assets/66646221/02e13f83-1c58-49ae-8880-af5481d6e5dc">

 @strimzi-ci 
 @ajborley
@antonio-pedro99
@scholzj

**Comment by scholzj** [comment]
I do not think it is really clear what exactly have you deleted or recreated. You would have to check the logs for the exact details of what is going on. But Strimzi 0.26 does not support Kubernetes 1.25 or higher. It is also years old and will be full of bugs and CVEs.

**Reply by mr-vardhan24** [reply]
Thanks! @schmichri
Please Support the below comments
as we were using the 0.26 version of strimzi Kafka, so now which version I can choose for the Kubernetes version v1.25

**Reply by damodarreddy08** [reply]
Hi @mr-vardhan24 , This is Damodar I also try to install the strimzi operator Kafka in Kubernetes this is my number 91-9620140623. could you please share your connect details for general discussion.. right now i am facing the one of issue during the implementation please help me it..

**Comment by mr-vardhan24** [comment]
Thanks! @schmichri 
Please Support the below comments
as we were using the 0.26 version of strimzi Kafka, so now which version I can choose for the Kubernetes version v1.25

**Reply by mr-vardhan24** [reply]
Recently we upgraded our EKS cluster, At that time our Kafka cluster was running(I think due to a stateful set)
but today I mistakenly run the command 
"k delete strimzi-kafka-operator -n kafka"
due to which my whole Kafka cluster went down 
instantly I run the command to up the cluster operator "kubectl apply -f install/cluster-operator -n Kafka"
after this command cluster came up but other pods like entity operator, zookeeper and broker not.

how can I resolve this 
as we have deployed this strimzi-kafka in EKS directly through yaml, we are not using helm for it 

this is our directory(file ) structure for reference 
<img width="1231" alt="Screenshot 2024-02-23 at 6 48 48 PM" src="https://github.com/strimzi/strimzi-kafka-operator/assets/66646221/8b914bf1-7497-483c-859a-4239df52b034">



and Please tell us how can i upgrade to a proper version according to our EKS v1.25

**Reply by mr-vardhan24** [reply]
Hi, 
we have upgraded our strimzi-kafka version to the kafka:0.39.0-kafka-3.5.0
now it gets deployed but again we are getting the cluster operator and Zookeeper not another pod-like entity operator and broker
here is the 
<img width="1070" alt="Screenshot 2024-02-23 at 7 45 26 PM" src="https://github.com/strimzi/strimzi-kafka-operator/assets/66646221/560b908a-f560-4a7a-8d27-23da879d817a">

**Reply by scholzj** [reply]
As I said, you will have to check the logs. There isn't anything one can say based on these screenshots.

**Reply by mr-vardhan24** [reply]
thanks for the reply 
here are my zookeeper logs and cluster-operator logs
[zookeeper.txt](https://github.com/strimzi/strimzi-kafka-operator/files/14386338/zookeeper.txt)
[cluster-operator.txt](https://github.com/strimzi/strimzi-kafka-operator/files/14386366/cluster-operator.txt)


and also please could help with the version, which version is best compatible with v1.25 EKS

**Reply by scholzj** [reply]
None of the logs is complete. So that is of little help. Also, do you intentionally have only 2 ZooKeeper replicas? You should have an odd number of them - e.g. 3.

**Reply by mr-vardhan24** [reply]
Hello again, @scholzj
thank you for the help, I think it was the issue of the zookeeper number, i changed it to 3, and now everything is up and running.
but in my logs, I am getting this error due to which Kafka is not respond

Please help with this also.

"Authentication failed during authentication due to invalid credentials with SASL mechanism SCRAM-SHA-512"
where am I misconfiguration?



this is my kafka.yaml

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: dev-kafka
spec:
  kafka:
    version: 3.5.0
    replicas: 3
    listeners:
      - name: external
        port: 9094
        type: ingress
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            host: kafka.dev.orahi.com
            annotations:
              kubernetes.io/ingress.class: kafka-nginx
          brokers:
            - broker: 0
              host: ********
              annotations:
                kubernetes.io/ingress.class: kafka-nginx      
            - broker: 1
              host: ********
              annotations:
                kubernetes.io/ingress.class: kafka-nginx
            - broker: 2
              host: ********
              annotations:
                kubernetes.io/ingress.class: kafka-nginx
          brokerCertChainAndKey:
            secretName: dev-kafka-cluster-lets-encrypt
            certificate: tls.crt
            key: tls.key      
#    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"
    authorization:
      type: simple
      superUsers:
        - super-admin
    jvmOptions:
      "-Xms": "4096m"
      "-Xmx": "4096m"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 51Gi
        deleteClaim: false
    template:
      pod:
        tolerations:
        - effect: NoSchedule
          key: only-dev-app
          operator: Equal
          value: allowed
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: allowed
                    operator: In
                    values:
                    - dev-app
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: strimzi.io/cluster
                  operator: In
                  values:
                  - dev-kafka
                - key: strimzi.io/name
                  operator: In
                  values:
                  - dev-kafka-kafka
              topologyKey: "kubernetes.io/hostname"
  kafkaExporter:
    topicRegex: "important-topic-.*"
    groupRegex: "important-group-.*"
    template:
      pod:
        tolerations:
        - effect: NoSchedule
          key: only-dev-app
          operator: Equal
          value: allowed
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: allowed
                    operator: In
                    values:
                    - dev-app
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
    jvmOptions:
      "-Xms": "512m"
      "-Xmx": "512m"
      javaSystemProperties:
        - name: zookeeper.ssl.hostnameVerification
          value: "false"
        - name: zookeeper.ssl.quorum.hostnameVerification
          value: "false"
    template:
      pod:
        tolerations:
        - effect: NoSchedule
          key: only-dev-app
          operator: Equal
          value: allowed
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: allowed
                    operator: In
                    values:
                    - dev-app
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                - key: strimzi.io/cluster
                  operator: In
                  values:
                  - dev-kafka
                - key: strimzi.io/name
                  operator: In
                  values:
                  - dev-kafka-zookeeper
              topologyKey: "kubernetes.io/hostname"
  entityOperator:
    template:
      pod:
        tolerations:
        - effect: NoSchedule
          key: only-dev-app
          operator: Equal
          value: allowed
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: allowed
                    operator: In
                    values:
                    - dev-app
    topicOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: INFO
    userOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:`
          rootLogger.level: INFO`
```
