### DISCUSSION TITLE
How to expose the external access with multiple kafka pods

### DISCUSSION THREAD

**Discussion by dumplingdumpling** [strimzi/strimzi-kafka-operator#9739] [Q&A]
Hi, I'm a strimzi noob here. I'm trying to establish a cluster with 3 kafka replicas with external accessible service. I used the config from https://youtu.be/1qO2qGuJNQI and tweaked it a little bit according to the blog https://strimzi.io/blog/2019/04/23/accessing-kafka-part-2/.

However, when I tried to apply the configuration, only 3 zookeeper pods were initialized. The kafka pod doesn't show up by typing "kubectl get pods -n kafka".  I don't know if I tweaked the config in the right way. I really appreciate If someone could provide some guidance about this.

Here is the context:

The environment is on a ubuntu PC with a docker desktop and k8s. I used `kubectl create -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka` to deploy the strimzi operator. The config is:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.6.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          # bootstrap:
          #   nodePort: 32100
          brokers:
          - broker: 0
            advertisedHost: localhost
            advertisedPort: 32000
          - broker: 1
            advertisedHost: localhost
            advertisedPort: 32001
          - broker: 2
            advertisedHost: localhost
            advertisedPort: 32002
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.6"
      message.max.bytes: 100000000
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 50Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

```

**Comment by scholzj** [comment]
For a start, you have to format the YAML to make it readable. You should also check the logs to see what they say, explain what exactly does not work etc.

**Reply by dumplingdumpling** [reply]
Thank you for your prompt reply. I've updated the YAML format and I've checked the logs using `kubectl logs deployment/strimzi-cluster-operator -n kafka -f`, the error is as follows:

```
2024-02-23 16:09:51 ERROR StaticHostProvider:148 - Unable to resolve address: my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.kafka.svc/<unresolved>:2181
java.net.UnknownHostException: my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.kafka.svc
        at java.net.InetAddress$CachedAddresses.get(InetAddress.java:801) ~[?:?]
        at java.net.InetAddress.getAllByName0(InetAddress.java:1533) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1385) ~[?:?]
        at java.net.InetAddress.getAllByName(InetAddress.java:1306) ~[?:?]
        at org.apache.zookeeper.client.StaticHostProvider$1.getAllByName(StaticHostProvider.java:88) ~[org.apache.zookeeper.zookeeper-3.8.3.jar:3.8.3]
        at org.apache.zookeeper.client.StaticHostProvider.resolve(StaticHostProvider.java:141) ~[org.apache.zookeeper.zookeeper-3.8.3.jar:3.8.3]
        at org.apache.zookeeper.client.StaticHostProvider.next(StaticHostProvider.java:368) ~[org.apache.zookeeper.zookeeper-3.8.3.jar:3.8.3]
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1204) ~[org.apache.zookeeper.zookeeper-3.8.3.jar:3.8.3]
2024-02-23 16:09:52 ERROR VertxUtil:125 - Reconciliation #1(watch) Kafka(kafka/my-cluster): Exceeded timeout of 300000ms while waiting for ZooKeeperAdmin connection to my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.kafka.svc:2181,my-cluster-zookeeper-1.my-cluster-zookeeper-nodes.kafka.svc:2181,my-cluster-zookeeper-2.my-cluster-zookeeper-nodes.kafka.svc:2181 to be connected
```

**Reply by scholzj** [reply]
That suggests the DNS of your Kubernetes cluster does not resolve the hostname. So likely some DNS issue or worker node issue, or networking or something like that.

**Reply by dumplingdumpling** [reply]
Thank you for your reply again. I solved this by reducing the zookeeper replicas to 1 and adding `my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.kafka.svc:2181` under the `config` area.

But I don't know why this works. I checked an online [blog](https://qdnqn.com/kafka-strimzi-behind-nginx-ingress-controller/) saying that kRaft mode is for zookeeper-less deployment, in which the configuration still uses the zookeeper. That's also quite confusing.

**Reply by scholzj** [reply]
You are not using KRaft mode if you have ZooKeeper. I'm not sure what you mean with `adding my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.kafka.svc:2181 under the config area`.

**Reply by dumplingdumpling** [reply]
just like this:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.6.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: false
        configuration:
          # bootstrap:
          #   nodePort: 32100
          brokers:
          - broker: 0
            advertisedHost: localhost
            advertisedPort: 31770
          - broker: 1
            advertisedHost: localhost
            advertisedPort: 31499
          - broker: 2
            advertisedHost: localhost
            advertisedPort: 30815
    config:
      zookeeper.connect: my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.kafka.svc:2181
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.6"
      message.max.bytes: 100000000
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 50Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

```
