### DISCUSSION TITLE
How to configure granular logging for KafkaConnect cluster?

### DISCUSSION THREAD

**Discussion by jslusher** [strimzi/strimzi-kafka-operator#9741] [Q&A] [answered]
I have the following logger configuration for my `KafkaConnect`:
```
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "INFO"
      log4j.logger.io.debezium: "DEBUG"
      log4j.logger.io.debezium.connector.base.ChangeEventQueue: "INFO"
      log4j.logger.org.apache.kafka.clients.NetworkClient: "WARN"
      log4j.logger.org.apache.kafka.connect.runtime.rest.RestServer: "WARN"
```

My goal is to try and set `DEBUG` on all `io.debezium` loggers except for `log4j.logger.io.debezium.connector.base.ChangeEventQueue` because it emits several logs for polling. For some reason, when I added the line for `log4j.logger.io.debezium.connector.base.ChangeEventQueue: "INFO"` I see my other loggers are now set to `INFO` instead of `WARN`: 

```
curl http://localhost:8083/admin/loggers | jq '."org.apache.kafka.connect.runtime.rest.RestServer"'
{
  "level": "INFO"
}
```

And I still see that `io.debezium.connector.base.ChangeEventQueue` is set to `DEBUG` 
```
curl http://localhost:8083/admin/loggers | jq '."io.debezium.connector.base.ChangeEventQueue"'
{
  "level": "DEBUG"
}
``` 

Is this something I'm doing wrong in the KafkaConnect or is there something I need to know about log4j that's preventing me from getting more granular log settings?
