### DISCUSSION TITLE
unable to connect kafka broker from nginx controller ingress

### DISCUSSION THREAD

**Discussion by sagarshrestha24** [strimzi/strimzi-kafka-operator#9777] [Q&A]
Please help me to configure kafka cluster where i have to use scram-sha-512 authentication and kafka endpoint using ingress

i have tested from this cluster.yaml
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi-kafka-cluster
  namespace: kafka
spec:
  kafka:
    jvmOptions:
      -Xms: 2G
      -Xmx: 5G
    replicas: 1
    authorization:
     type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
      - configuration:
          brokers:
          - broker: 0
            advertisedHost: kafka-broker-0.xxxx.com.np
            advertisedPort: 9097
        name: external
        port: 9094
        authentication:
          type: scram-sha-512
        tls: true
        type: cluster-ip
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    config:
      sasl.enabled.mechanisms: scram-sha-512
      sasl.mechanism.inter.broker.protocol: scram-sha-512
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.5.1"
      replica.fetch.max.bytes: 1048576
  zookeeper:
    jvmOptions:
      -Xms: 1G
      -Xmx: 2G
    replicas: 1
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
  ```  
    
    but there is issue tls handshake while connecting from client

**Comment by scholzj** [comment]
You do not use `type: ingress` listener. So it is not clear what kind of issues you have with Ingress. You should either get more into details of what are you doing or check the docs and use the `type: ingress` listener.

**Reply by sagarshrestha24** [reply]
@scholzj  Here is the configuration of kafka with ingress listener
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi-kafka-cluster
  namespace: kafka
spec:
  kafka:
    jvmOptions:
      -Xms: 2G
      -Xmx: 5G
    replicas: 1
    authorization:
     type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
      - configuration:
          brokers:
          - broker: 0
            advertisedHost: kafka-broker-0.rohanshahi.com.np
            advertisedPort: 9097
        name: external
        port: 9094
        authentication:
          type: scram-sha-512
          sasl: true
        tls: true
        type: ingress
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    config:
      sasl.enabled.mechanisms: scram-sha-512
      sasl.mechanism.inter.broker.protocol: scram-sha-512
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.5.1"
      replica.fetch.max.bytes: 1048576
  zookeeper:
    jvmOptions:
      -Xms: 1G
      -Xmx: 2G
    replicas: 1
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
  i have used scram-sha-512 to authenticate the kafka with broker with domain.
  when i used to produce the message from this command
  `./kafka_2.13-3.7.0/bin/kafka-console-producer.sh --topic test-topic --bootstrap-server kafka-broker-0.xxx.com.np:9097  --producer.config client.properties`
  
  i got this error
  ```
  [2024-03-05 12:00:01,115] WARN [Producer clientId=console-producer] Bootstrap broker kafka-broker-0.rohanshahi.com.np:9097 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2024-03-05 12:00:02,180] WARN [Producer clientId=console-producer] Connection to node -1 (kafka-broker-0.rohanshahi.com.np/172.18.254.200:9097) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue. (org.apache.kafka.clients.NetworkClient)
```

**Reply by sagarshrestha24** [reply]
i have enable ssl passthrough also it is no working as expected.
here is the ingress file 
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: kafka-cluster-1-kafka-brokers
spec:
  ingressClassName: nginx
  rules:
  - host: kafka-broker-0.xxx.com.np
    http:
      paths:
      - backend:
          service:
            name: strimzi-kafka-cluster-kafka-0
            port:
              number: 9094
        path: /
        pathType: Prefix
    ```
