### DISCUSSION TITLE
[Enhancement]: ability to use node fqdn for preferredNodePortAddressType

### DISCUSSION THREAD

**Discussion by olivierbouffet** [strimzi/strimzi-kafka-operator#9792] [General]
### Related problem

Hello,

I am running a bare metal k8s cluster, my nodes are configured with the short name in kubernetes and I want to use : nodeport, externalTrafficPolicy local and a valid SSL certificate for external listener.

I only have InternalIP and Hostname available in node status: 
```
 k get node k8s-node -ojsonpath='{.status.addresses}' 
[{"address":"10.x.x.x","type":"InternalIP"},{"address":"k8s-node","type":"Hostname"}]%
```

So if I try to set `preferredNodePortAddressType: Hostname` only the shortname will be advertised, and I will not be able to have a valid certificate because my certificate issuer does not accept short hostname.

### Suggested solution

Would it be possible to add an option to support full hostname (fqdn) for the prefered node port address type.

### Alternatives

I can workaround that with externalTrafficPolicy Cluster and forcing the advertised address with the fqdn of the nodes. 
But for performance point of view I would like to use externalTrafficPolicy Local.

Thanks in advance

**Comment by scholzj** [comment]
Strimzi cannot make-up the FGDN for you. If you configure your Kubernetes cluster to have it properly listed in the node status, it will be used. Alternatively, you can override the advertised hostnames using the `advertisedHost` option for each node if you want to.

**Reply by olivierbouffet** [reply]
Hello,

The following config with `externalTrafficPolicy : Cluster` is working  

```
      - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          externalTrafficPolicy: Cluster
          brokerCertChainAndKey:
            secretName: bootstrap-external-cert
            certificate: tls.crt
            key: tls.key
          bootstrap:
            nodePort: 32100
          brokers:
          - broker: 0
            advertisedHost: node1.domain.com
            nodePort: 32000
          - broker: 1
            advertisedHost: node2.domain.com
            nodePort: 32001
          - broker: 2
            advertisedHost: node3.domain.com
            nodePort: 32002
```

But if I change it to `externalTrafficPolicy : Local` it doesn't , because the broker could be located on other node, or even move in case of cluster scaling.

I understand that if I reinstall the cluster with fqdn for nodename it will work.

But maybe it could be usefull (at least for me) to be able to append the domain of the fqdn or even better we could specify the advertisedhost directly in the node label like it is already done for the rack.
