### DISCUSSION TITLE
Duplicate CRs for same  kafka topic

### DISCUSSION THREAD

**Discussion by Sharad-SKJ052** [strimzi/strimzi-kafka-operator#9796] [Q&A]
Hi Team ,
We are running on Kubernetes version 1.28 and kafka version 3.4.0 .
We are using boiler plate kafka cluster code which is available on strimzi GitHub with slight modification.
We are trying to create below topic 
``` 
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata: 
  labels: 
    strimzi.io/cluster: test-kafka
  name: abc.test.group.topic.internal.any.v2
  namespace: kafka
spec:
  topicName: ABC.test.group.topic.internal.any.v2
  partitions: 3
  replicas: 3
  config: 
    retention.ms: 259200000
    segment.bytes: 1073741824
    cleanup.policy: delete
    delete.retention.ms: 86400000
    max.message.bytes: 2097164
    min.compaction.lag.ms: 0
    retention.bytes: -1
    segment.ms: 604800000
```

In the cluster when I am applying the above configuration it is creating two topic , one with the provided CR and another having the CR name appended with some hash value .

My assumption here is 2nd topic is being created by strimzi directly.

```
abc.test.group.topic.internal.any.v2                                                                                               test-kafka   3            3                    True
abc.test.group.topic.internal.any.v2---3b2f256bea4edecca0d007a1def60143be9fbf50                                                    test-kafka   3            3                    
```

Is there any specific property which we have to define on the cluster to stop this behaviour. 
Any insights here would be valuable 

FYI - @scholzj
