### DISCUSSION TITLE
IAM Creds for KafkaConnect

### DISCUSSION THREAD

**Discussion by sai9920** [strimzi/strimzi-kafka-operator#9814] [General]
I want to deploy s3 sink connector from kafkaconnect Cluster, But i dont want to pass the access key and private key instead trying to use IAM role part of service account. But i am unable to achieve it.

Any help on how to pass this IAM Role ?

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    eks.amazonaws.com/role-arn: >-
      arn:aws:iam::awsaccount:role/iamname
    strimzi.io/use-connector-resources: 'true'
  labels:
    argocd.argoproj.io/instance: kafkaconnect
  name: qa-kafkaconnect
  namespace: kafka-connect

spec:
  authentication:
  config:
    config.providers: env
    config.providers.env.class: org.apache.kafka.common.config.provider.EnvVarConfigProvider
    config.storage.replication.factor: 1
    config.storage.topic: kafkaconnect-configs
    group.id: cluster
    offset.storage.replication.factor: 1
    offset.storage.topic: kafkaconnect-offsets
    status.storage.replication.factor: 1
    status.storage.topic: kafkaconnect-status
  image: >-
    kafkaconnect-image:baZrIvzrVzgq_SAsHcVG1FJZ6jECFnvP
  replicas: 3
  template:
    pod:
      metadata:
        annotations:
          iam.amazonaws.com/role: >-
            arn:aws:iam::awsaccount:role/iamname
  tls:
    trustedCertificates: []
  version: 3.6.0
  replicas: 3

```
