### DISCUSSION TITLE
superuser cannot login suddenly

### DISCUSSION THREAD

**Discussion by runkecheng** [strimzi/strimzi-kafka-operator#9841] [Q&A] [answered]
```
    kafka:
      authorization:
        superUsers:
        - kafka-xxx-admin
        type: simple
```

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-xxx-admin
spec:
  authentication:
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: kafka-xxx-admin
    type: scram-sha-512
  authorization:
    acls: []
    type: simple
```

I have a superuser that was available when I created the cluster, and after running it for a while, it suddenly became unavailable and scram reported the following error:
```
kafka: client has run out of available brokers to talk to: EOF
```
Is there a way to get the real passwords stored in the cluster? I haven't changed the password and the status of kafkauser is ready.
