### DISCUSSION TITLE
Kafka connect POD takes a lot of time to get into Ready state.

### DISCUSSION THREAD

**Discussion by piyushbhojgude** [strimzi/strimzi-kafka-operator#9871] [Q&A] [answered]
Hi I have deployed a Kafka connect cluster based on Strimzi kafka connect CR. I'm noticing that it takes more than 20 mins and sometimes close to an hour for the pod to be in ready state. Is there a way to figure out why the pod takes so much time?
For example here is the pod status:
```
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-03-25T07:20:44Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-03-25T08:10:56Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-03-25T08:10:56Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-03-25T07:20:44Z"
    status: "True"
    type: PodScheduled
```

As we can see above the pod get initialized at 7.20 but got into ready state at 8.10. 
Any suggestions on how to debug and find the root cause for this would be highly appreciated
