### DISCUSSION TITLE
[strimzi-kafka-operator] STRIMZI_MAX_QUEUE_SIZE environmental variable not being passed to topic-operator

### DISCUSSION THREAD

**Discussion by BlackCorsair** [strimzi/strimzi-kafka-operator#9886] [Q&A] [answered]
Hi!
We set the `extraEnvs` in the `strimzi-kafka-operator` chart values.yaml and we can see in the `strimzi-cluster-operator` the variable is set:
```
$ kubectl exec -ti strimzi-cluster-operator-587fc6c4b4-7476c -- env | grep STRIMZI_MAX_QUEUE_SIZE
STRIMZI_MAX_QUEUE_SIZE=2048

$ kubectl describe pod strimzi-cluster-operator-587fc6c4b4-7476c | grep STRIMZI_MAX_QUEUE_SIZE
      STRIMZI_MAX_QUEUE_SIZE:                             2048
```

But in the topic-operator pod the variable isn't:
```
$ kubectl describe pod kafka-entity-operator-86896b4895-q4g9c | grep STRIMZI_MAX_QUEUE_SIZE
```

We're trying to raise the queue size because we're getting the following error:
```
ERROR [-1574509514-pool-3-thread-3] BatchingLoop:108 - Queue length 1024 exceeded, stopping operator. Please increase STRIMZI_MAX_QUEUE_SIZE environment variable.
```

Is there anything else I'm missing?

Thanks!

**Comment by scholzj** [comment]
I guess you are mixing up the Cluster and Topic operators? If you want to set it in the Topic Operator, you have to configure it in the `Kafka` custom resource in the template section.

**Reply by BlackCorsair** [reply]
Hi @scholzj ,
Thanks! We'll try that.

BR

**Reply by ignaciogonzalezsomoza** [reply]
Hi, I face the same problem. Please, could you tell us how the environment variable can be transferred to the topicOperator of the entityOperator? EntityTopicOperatorSpec schema properties in https://strimzi.io/docs/operators/latest/configuring.html#type-EntityTopicOperatorSpec-reference does not seem to include the ability to add environment variables. We have tested via template with:
```
    topicOperator:
      template:
        pod:
          env:
            - name: STRIMZI_MAX_QUEUE_SIZE
              value: "16384"
```

But it doesn't generate this in the kafka object.
Could you help us?, thanks in advance.

**Reply by scholzj** [reply, marked as answer]
The `template` section is under `.spec.entityOperator`. So from the YAML snippet you share I guess you have it badly places? Also, the environment variables are configured per container and not per pod: https://strimzi.io/docs/operators/latest/configuring.html#type-EntityOperatorTemplate-reference

**Reply by ignaciogonzalezsomoza** [reply]
Ok, thanks.

**Reply by lean-illia-shpak** [reply]
Hey. @ignaciogonzalezsomoza , how do you resolve this in the end?  Should it here? 
```
spec:
  entityOperator:
      kafkaContainer:
        env:
        - name: STRIMZI_MAX_QUEUE_SIZE
          value: "10000"
```

**Reply by see-quick** [reply]
For instance:
```yaml
...
spec:
  entityOperator:
    template:
      topicOperatorContainer:
        env:
        - name: STRIMZI_MAX_QUEUE_SIZE
          value: "2147483647"
```
