### DISCUSSION TITLE
Help on Disk Usage - Few PVCs are getting full and getting "No Space Left on Device"

### DISCUSSION THREAD

**Discussion by npandeya** [strimzi/strimzi-kafka-operator#9904] [Q&A]
Hello,
I am running the cluster with 30 brokers. Each broker has this storage spec:
```yaml 
storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: kafka
        size: 750Gi
        deleteClaim: false
```

log retention hours is 12 hours. with this config log.retention.hours 

What I am seeing is only few of the pods is filling up fast. Is there a way I can balance the disk storage across all the PVCs? I was reading up on kafkarebalance but only saw the specs etc. Will using cruisecontrol with the kafkarebalance will help? I was thinking of using the default configuration for both.

Thank you for your help.
