### DISCUSSION TITLE
Get source bootstrap servers from k8s configmap in MM2?

### DISCUSSION THREAD

**Discussion by iftachbyaf** [strimzi/strimzi-kafka-operator#9934] [Q&A]
Hello,

I'm working on setting up our MM2 strimzi deployment as dynamically as possible. I want the source bootstrap servers to read from a k8s configmap that we have which contains the bootstrap servers.

Right now we have the bootstrap servers as a string passed to the chart;

```
spec:
  clusters:
    - alias: {{ get .Values.clusters.source "alias" }}
      tls:
        trustedCertificates: []
      bootstrapServers: {{ get .Values.clusters.source "bootstrapServers" }}
    - alias: {{ get .Values.clusters.target "alias" }}
      tls:
        trustedCertificates: []
      bootstrapServers: {{ get .Values.clusters.target "bootstrapServers" }}
```

I saw that it is possible to setup externalConfiguration at the spec schema level, which will load a configmap, but I'm not sure how to set this up and then reference this as the value passed to bootstrapServers exactly? Is there an example somewhere on how to do this?

For reference for normal kafka connect I used

```
spec:
  config:
    config.providers: secrets,configmaps
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider 
```
and then loaded it from configmap like this
`  bootstrapServers: "${configmaps:strimzi/{{ .Values.cluster }}:brokers_tls}"
`

This syntax doesnt seem to match how I'm supposed to do it on mm2?

Thanks!

**Comment by scholzj** [comment]
I would not expect it to work to specify a config provider-based value directly in the custom resource. But if it works for you in Connect, it should work the same way for you in MM2.

**Reply by iftachbyaf** [reply]
Hey, thanks for the quick reply again. 
It doesnt work the same as in Connect as MM2 doesnt have `spec.config` 


It seems like it should be setup using `spec.externalConfiguration`, but I don't really understand from the docs how exactly to set this up or reference it later as the value. (if that's even possible)

**Reply by iftachbyaf** [reply]
For reference I tried to setup according to the docs 

```
spec:
  externalConfiguration:
    env:
      name: msk-data
      valueFrom:
        configMapKeyRef:
          name: msk-data
          key: brokers_tls 
```

on helm install I see the following errors;

```
W0409 15:39:19.417150   19260 warnings.go:70] unknown field "spec.externalConfiguration.env.name"
W0409 15:39:19.417220   19260 warnings.go:70] unknown field "spec.externalConfiguration.env.valueFrom"
Error: UPGRADE FAILED: cannot patch "mirrormaker-2" with kind KafkaMirrorMaker2: KafkaMirrorMaker2.kafka.strimzi.io "mirrormaker-2" is invalid: [spec.clusters[0].bootstrapServers: Required value, spec.externalConfiguration.env: Invalid value: "object": spec.externalConfiguration.env in body must be of type array: "object"]
```

**Reply by scholzj** [reply]
I guess the `.spec.config` is basically the config of the target cluster.

**Reply by scholzj** [reply]
I think the YAML is invalid. You have to check it against the specification.

**Reply by iftachbyaf** [reply]
Hi, my YAML was indeed invalid,

correct syntax is 

```
spec:
  externalConfiguration:
    env:
    - name: msk-data
      valueFrom:
        configMapKeyRef:
          name: msk-data
          key: brokers_tls
```
(was missing `-` before `name`)

Now I see the configmap value loaded as env var on the mm2 pods. now I just need to understand how to reference this as the value for the bootstrap servers. :)

**Reply by iftachbyaf** [reply]
This seems to work for me for referencing the configmap once its loaded to the env var;
`bootstrapServers: ${env:msk-data}  `

So seems like this is solved. Thanks!

**Reply by iftachbyaf** [reply]
Actually that was my mistake on referencing the env var. it doesnt seem to work. it just refrences the env var name. I do see the env var on the MM2 pods with the correct value;

```
spec:
  externalConfiguration:
    env:
    {{- range $source_cluster := .Values.source_clusters }}
    - name: {{ $source_cluster.name | upper }}
      valueFrom:
        configMapKeyRef:
          name: {{ $source_cluster.name }}
          key: {{ $source_cluster.key_name }}
    {{- end }}
```
    

added this to the clusters config;
```
  clusters:
  {{- range $cluster := .Values.target_clusters }}
    - alias: {{ $cluster.alias }}
      bootstrapServers: {{ $cluster.bootstrapServers }}
      tls:
        trustedCertificates: []
  {{- end }}
    - alias: source
      bootstrapServers: ${env:MSK}
      tls:
        trustedCertificates: []
      config:
        config.providers: env
        config.providers.env.class: org.apache.kafka.common.config.provider.EnvVarConfigProvider
```

in the mm2 CRD I see it loading `bootstrapServers: '${env:MSK}'`
on the mm2 pods i do see the env var `MSK: b-1...9094`. so this part does seem working. my issue is with actually referencing the env var value

This is what I pass in the values file for the confimap
```
source_clusters:
  - name: msk
    key_name: brokers_tls 
```

I've been following this example from the docs 
https://strimzi.io/docs/operators/latest/deploying#assembly-loading-config-with-providers-str:~:text=kind%3A%20KafkaConnector%0Ametadata%3A%0A%20%20name%3A%20my%2Dconnector%0A%20%20labels%3A%0A%20%20%20%20strimzi.io/cluster%3A%20my%2Dconnect%0Aspec%3A%0A%20%20%23%20...%0A%20%20config%3A%0A%20%20%20%20option%3A%20%24%7Benv%3AAWS_ACCESS_KEY_ID%7D%0A%20%20%20%20option%3A%20%24%7Benv%3AAWS_SECRET_ACCESS_KEY%7D%0A%20%20%20%20%23%20...

Which specifies how to do it with connect/connector but I believe it should be possible to do the same for mm2?

Any idea what im doing wrong?

**Reply by scholzj** [reply]
Well, I'm not sure you are initializing the config provider in the right place. Have you tried it in the target cluster as I suggested? But as I said, it might also not work at all.

**Reply by scholzj** [reply]
You should be also super careful how you create the resource. From my experience in many cases the `${...}` gets interpreted already before it reaches Kafka and that as a result doesn't work.

**Reply by iftachbyaf** [reply]
```
I tried setting it up on the target;

    - alias: target
      bootstrapServers: b-2...9094
      config:
      config.providers: env,secrets,configmaps
      config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider
      config.providers.env.class: org.apache.kafka.common.config.provider.EnvVarConfigProvider
      config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
```

i am just able to reference the configmap/env var name and the key name. but not the value itself... so im wondering if its even possible

**Reply by scholzj** [reply]
I don't understand what you mean by this `i am just able to reference the configmap/env var name and the key name. but not the value itself`.

**Reply by iftachbyaf** [reply]
So lets say i load this configmap;
```
  externalConfiguration:
    env:
    - name: msk
      valueFrom:
        configMapKeyRef:
          name: msk
          key: brokers_tls
```
This creates the env var on the mm2 pods. so far so good.
Now I want to reference the value in brokers_tls (its the bootstrap-servers list), from the env var in some other property in the chart. I tried several methods

```
  clusters:
    - alias: source
      bootstrapServers: ${env:msk}
```

This returns value `bootstrapServers: ${env:msk}`, so it basically passes it as is as a string.
I also tried `bootstrapServers: {{ index .Values.source_clusters 0 "key_name" }}` or bootstrapServers: `{{ index .Values.source_clusters 0 "key_name" }}`

these return `msk` / `brokers_tls` respectively, as strings. So it does access the env config but I'm unable to retrieve the actual value of the env var... Tried `bootstrapServers: {{ index .Values.source_clusters 0 "key" }}` / `bootstrapServers: {{ index .Values.source_clusters 0 "value" }}` but these both return empty strings...

Hope that makes sense.

I also tried setting up retrieval directly from configmap using  `config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider` and then accessing the configmap using `"${configmaps:namespace/msk:brokers_tls}"`, but that again just loads it as string `bootstrapServers: "${configmaps:namespace/msk:brokers_tls}"`
