### DISCUSSION TITLE
Accessing global variable in subchart within if block sometimes injects `true`

### DISCUSSION THREAD

**Discussion by mathe-matician** [strimzi/strimzi-kafka-operator#9956] [Q&A]
I have a subchart that has a `deployment.tpl` file that has this if block in it:

```yaml
{{- if .Values.global.image.pullSecrets.enabled }}
   imagePullSecrets:
      - name: {{ .Values.global.image.pullSecrets.name }}
{{- end }}
```

Where the top level values file looks like this:

```yaml
global:
  image:
    pullSecrets:
      enabled: true
      name: regcred
```

Most of the time this renders correctly:

```yaml
imagePullSecrets:
   - name: regcred
```

But sometimes it injects the value `true` into the array:

```yaml
imagePullSecrets:
   - name: true
   - name: regcred
```

Is this a bug or am I misunderstanding global values (I thought they could be accessed reliably within subcharts).
