### ISSUE TITLE
Adding Kafka Connect metrics

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#101]
Other than getting metrics from Kafka brokers and Zookeeper, we should add metrics support for Kafka Connect as well. Maybe it's something already provided by the Debezium project ? We should check on the project itself and with @gunnarmorling ?

**Comment by gunnarmorling** [comment]
As a starting point, Kafka Connect provides rather [basic status info](https://docs.confluent.io/current/connect/managing.html#connector-and-task-status) through its REST API. It doesn't tell you very much though beyond a status (RUNNING/PAUSED/FAILED etc.) and in case of failures the last exception. 

More interesting is [KIP-196](https://cwiki.apache.org/confluence/display/KAFKA/KIP-196%3A+Add+metrics+to+Kafka+Connect+framework) which seems to provide extensive metrics via JMX as of Kafka 1.0. Definitely worth checking out.

As far as Debezium is concerned, we also provide a [few metrics via JMX](http://debezium.io/docs/monitoring/).

Happy to help with the details as needed. What exactly does "metrics support" entail from Barnabas' POV? Would be super-cool to see those metrics in some form in the OpenShift dashboard/console, is this what it is about?

**Comment by renatomefi** [comment]
For the future google surfers, that's an example of a JMX configuration file for Kafka Connect, this one focused on Source connectors:

```yml
    jmxUrl: service:jmx:rmi:///jndi/rmi://{{ .Values.jmx.host }}:{{ .Values.jmx.port }}/jmxrmi
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true
    ssl: false
    rules:
    - pattern : "kafka.connect<type=connect-worker-metrics>([^:]+):"
      name: "connect_worker_$1"
    - pattern : "kafka.connect<type=connect-metrics, client-id=([^:]+)><>([^:]+)"
      name: "connect_connect_$2"
      labels:
        client_id: "$1"
    - pattern : "kafka.connect<type=source-task-metrics, connector=([-.\\w]+), task=([-.\\w]+)>([^:]+):"
      name: "connect_source_task_$3"
      labels:
        connector: "$1"
        task: "$2"
```

For sink you can add:

```yml
    - pattern : "kafka.connect<type=sink-task-metrics, connector=([-.\\w]+), task=([-.\\w]+)>([^:]+):"
      name: "connect_sink_task_$3"
      labels:
        connector: "$1"
        task: "$2"
```

The common examples tend to concatenate the connector/client/task ids into the metric itself, making it hard to grow dynamically, this one turns them into labels with makes them self-maintainable
