### ISSUE TITLE
[Bug]: Adding a serviceAccount annotation in KafkaConnect spec makes Cluster Operator Stuck on Reconciliation of Strimzipodset 

### ISSUE THREAD

**Issue by yordanovsstoyan** [strimzi/strimzi-kafka-operator#10118]
### Bug Description

Adding an annotation to the service account of Kafka Connect creates only the new annotated service account (kafka-connect pod does not get created), while cluster operator times out trying to reconcile kafka-connect StrimziPodSet.

### Steps to reproduce

KafkaConnect config to reproduce

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
spec:
  template:
    serviceAccount:
      metadata:
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/my-role
  version: 3.7.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  config:
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
```

### Expected behavior

Cluster Operator creates both the pod and the annotated service account

### Strimzi version

0.41.0

### Kubernetes version

1.26
