### ISSUE TITLE
[Bug]: KafkaRebalance not respecting replicationThrottle

### ISSUE THREAD

**Issue by AlbertoEAF** [strimzi/strimzi-kafka-operator#10122]
### Bug Description

Hello,

I was triggering a KafkaRebalance in the mode `add-brokers` after adding one broker to have a cluster with 6 brokers.

I set a really low threshold of replicationThrottle=10 (which is apparently in bytes/s according to the source code), as reported by the description of the `KafkaRebalance` with k9s:
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/3976753/3e1c56cf-fca1-44bf-92a7-7651a98642f0)

however, I am observing writes to the new broker at a rate of ~140MiB/s:
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/3976753/9c684b11-4b3a-4487-a264-f61c896e775f)

### Steps to reproduce

This is the KafkaRebalance CRD I wrote and approved at first:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  name: rebalance-proposal
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  # We expect to have to transfer ~800GB. At a max rate of 10MB/s (the cluster is currently operating at ~20-30MB/s), this amounts to ~22h:
  replicationThrottle: 10 # max bytes/s. By default there is no limit.  
  mode: add-brokers
  brokers: [5]  # Add 6th broker (index 5) to the cluster.
```

I first started with `replicationThrottle=10000` (supposedly ~10MB/s), but no throttling happened, so I tried 10 and the same write throughput to the new broker of 140MiB/s happened -- that's when I understood the parameter wasn't taking effect at all.

### Expected behavior

The `replicationThrottle` parameter should be respected, meaning my new broker would write at most `<replicationThrottle value> [bytes/s]`.

### Strimzi version

0.40.0

### Kubernetes version

kuberenetes v1.26.15-eks-adc7111

### Installation method

unknown but I can ask if needed

### Infrastructure

Amazon EKS
