### ISSUE TITLE
[Bug]: ListenerStatus (Kafka) contains NodePort info about controller nodes (kraft mode)

### ISSUE THREAD

**Issue by Frawless** [strimzi/strimzi-kafka-operator#10169]
### Bug Description

When I have KRaft cluster with separated broker and controller nodes and NodePort listener, the status of Kafka CR also contains nodeport info about nodes that hosts only controller pods

### Steps to reproduce

1. Deploy CO
2. Deploy Kafka with separated broker and controller nodes and make sure that controller is on separated kubernetes node
3. Wait for Kafka ready and check Kafka status. It will contain Kube nodes that hosts only controllers 
```
    - addresses:
      - host: 172.18.0.7 (node with broker)
        port: 31544
      - host: 172.18.0.4 (node with just controller)
        port: 31544
      bootstrapServers: 172.18.0.4:31544,172.18.0.7:31544
      name: external
```

### Expected behavior

Kafka status will contains only info about bootstrap addresses of broker nodes

### Strimzi version

main

### Kubernetes version

Kubernetes 1.23

### Installation method

YAML files

### Infrastructure

Kind
