### ISSUE TITLE
Improve the Offset Syncronization Latency metrics / table

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#10183]
The MM2 metrics include metrics for Offset Synchronization Latency. But their labeling seems currently a bit weird as the `target` label includes not only the target cluster but also the group, topic and partition:

```prometheus
# HELP kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms Kafka Mirror Maker 2 Checkpoint Connector metrics
# TYPE kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms gauge
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=0"} 6.0
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=1"} 6.0
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=2"} 6.0
# HELP kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_avg Kafka Mirror Maker 2 Checkpoint Connector metrics
# TYPE kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_avg gauge
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_avg{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=0"} 6.0
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_avg{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=1"} 6.0
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_avg{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=2"} 6.0
# HELP kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_max Kafka Mirror Maker 2 Checkpoint Connector metrics
# TYPE kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_max gauge
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_max{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=0"} 6.0
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_max{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=1"} 6.0
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_max{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=2"} 6.0
# HELP kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_min Kafka Mirror Maker 2 Checkpoint Connector metrics
# TYPE kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_min gauge
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_min{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=0"} 6.0
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_min{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=1"} 6.0
kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_ms_min{source="cluster-a",target="cluster-b, group=my-kafka-consumer-source, topic=kafka-test-apps, partition=2"} 6.0
```

This is also translated into the MM2 Grafana Dashabord that has a table for Offset Syncronization Latency:
![Screenshot 2024-05-31 at 22 53 56](https://github.com/strimzi/strimzi-kafka-operator/assets/5658439/0dca9b67-8b21-4e52-badd-cedd4e49e5ea)

It is readable but a bit strange with all the information in single column.

We should probably try to improve it:
* Properly label the metrics
* Use the columns in the table properly

**Comment by maciej-tatarski** [comment]
This can be solved by regex values overrides in grafana or by creating proper labels for consumergroup and topic. Which approach would you prefer here?

**Comment by ppatierno** [comment]
I guess we are referring to this line in the JMX exporter filtering 

https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/metrics/kafka-mirror-maker-2-metrics.yaml#L175

more specifically `target=(.+)` which is then the `$2` variable but I am not aware of any JMX Exporter way to process a variable (by using a regex for example) and splitting in multiple sub-values for labels. So not sure it's feasible at JMX Exporter level, but should be done at Grafana level only.

**Comment by maciej-tatarski** [comment]
I'll give it a try

**Comment by scholzj** [comment]
I think you can just add more fields to the rule definition:

```
pattern: kafka.connect.mirror<type=MirrorCheckpointConnector, source=(.+), target=(.+), group=(.+), topic=(.+), partition=(.+)><>([a-z-_]+)
```

**Comment by ppatierno** [comment]
@scholzj I don't have the JMX representation for that metric but I am not sure you can do what you are suggesting. It looks to me that the JMX bean exposes just a field named `target` and its content is a string which is a comma separated key-value pairs. So from a JMX Exporter perspective you can select just the `target` field exposed by the bean and not regex on the content (which is just a string). This is my understanding.

**Comment by scholzj** [comment]
@ppatierno I don't know, I guess someone would need to try it. But the value looks exactly like what we are matching against in the rules, just everything captured by the single `(.+)` 🤷

**Comment by maciej-tatarski** [comment]
I cannot get it to work even on the main branch. `kafka_connect_mirror_mirrorcheckpointconnector_checkpoint_latency_*` is not coming for me.
![image](https://github.com/strimzi/strimzi-kafka-operator/assets/135701313/e807147c-a541-404e-ad2b-fcd61401a17b)


My mm2 setting:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mm2-cluster
  labels:
    app: my-mm2-cluster
spec:
  version: 3.7.0
  replicas: 1
  connectCluster: "my-cluster-target"
  clusters:
    - alias: "my-cluster-source"
      bootstrapServers: my-cluster-1-kafka-bootstrap:9092
    - alias: "my-cluster-target"
      bootstrapServers: my-cluster-2-kafka-bootstrap:9092
      config:
        config.storage.replication.factor: 1
        offset.storage.replication.factor: 1
        status.storage.replication.factor: 1
  mirrors:
    - sourceCluster: "my-cluster-source"
      targetCluster: "my-cluster-target"
      sourceConnector:
        config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: "false"
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
          refresh.groups.interval.seconds: 600
          sync.group.offsets.enabled: true
          sync.group.offsets.interval.seconds: 60
          emit.checkpoints.interval.seconds: 60
      topicsPattern: ".*"
      groupsPattern: ".*"
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: mirror-maker-2-metrics
        key: metrics-config.yml
```

Am i missing smth here?
