### ISSUE TITLE
[Bug]: TopicOperator's use of SSL and auth for Cruise Control cannot be disabled anymore

### ISSUE THREAD

**Issue by Pinimo** [strimzi/strimzi-kafka-operator#10289]
### Bug Description

Starting with #9483 (which holds awesome work otherwise :sweat_smile:), we found the TopicOperator will necessarily speak SSL with Cruise Control. This seems to be a regression, because in some setups, it is not easy to use SSL on Cruise Control backends, especially when using a CC front-end UI (as mentioned in this [blog post's](https://strimzi.io/blog/2023/01/11/hacking-for-cruise-control-ui/) prerequisites).

When changing a topic replication factor, the TopicOperator will throw the following error:
```
ReplicasChangeHandler:299 - Replicas change failed, javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
```

Indeed, there is no SSL on Cruise Control side, so the Topic Operator's attempt to negociate SSL is in vain.

We tried to change the TopicOperator's SSL behaviour with the following configuration, but it turned out to be impossible, because the `STRIMZI_CRUISE_CONTROL_SSL_ENABLED` environment variable is hard-coded to true [here](https://github.com/strimzi/strimzi-kafka-operator/blob/12cff8da6eb52031120ae78911ee968bd116c8ef/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/EntityTopicOperator.java#L190). In the case of the following scenario, [this error](https://github.com/strimzi/strimzi-kafka-operator/blob/12cff8da6eb52031120ae78911ee968bd116c8ef/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/ContainerUtils.java#L226-L226) is thrown: `User defined container template environment variable STRIMZI_CRUISE_CONTROL_SSL_ENABLED is already in use and will be ignored`.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: test-kafka
  namespace: strimzi-test
spec:
  cruiseControl:
    config:
      webserver.security.enable: false  <-- ask Cruise Control backend to use no auth
      webserver.ssl.enable: false       <-- nor any SSL
  entityOperator:
    template:
      topicOperatorContainer:
        env:
        - name: STRIMZI_CRUISE_CONTROL_SSL_ENABLED
          value: "false"    <-- ask topicOperator not to speak SSL to Cruise Control
```

Thank you for your help :heart:

I guess it will be necessary to modify or enrich the way the `addContainerEnvsToExistingEnvs` function works (for instance by making it possible to add the "true" value as a default value) or is called (for instance by calling the method only after the template vars are already loaded in the configuration).

PS. Beyond auth and SSL, other [parameters](https://github.com/strimzi/strimzi-kafka-operator/blob/12cff8da6eb52031120ae78911ee968bd116c8ef/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/EntityTopicOperator.java#L186-L191) are also affected by this issue.

### Steps to reproduce

Deploy the following resource:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: test-kafka
  namespace: strimzi-bug-cruise-control-no-ssl
spec:
  cruiseControl:
    config:
      webserver.security.enable: false
      webserver.ssl.enable: false
  entityOperator:
    template:
      topicOperatorContainer:
        env:
        - name: STRIMZI_CRUISE_CONTROL_SSL_ENABLED
          value: "false"
  kafka:
    replicas: 3
    resources:
      limits:
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 2Gi
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    app: test-kafka
    strimzi.io/cluster: test-kafka
  name: test-topic
  namespace: strimzi-bug-cruise-control-no-ssl
spec:
  partitions: 12
  replicas: 1
```

Once the cluster is created, `kubectl edit kt/test-topic` to change the replication factor to 2.

Monitor the logs of the TopicOperator, especially to see the configuration printed at startup.

### Expected behavior

As the default value of `STRIMZI_CRUISE_CONTROL_SSL_ENABLED` is [false](https://github.com/strimzi/strimzi-kafka-operator/blob/12cff8da6eb52031120ae78911ee968bd116c8ef/topic-operator/src/main/java/io/strimzi/operator/topic/TopicOperatorConfig.java#L141), one expects this variable not to be true. But when [printed](https://github.com/strimzi/strimzi-kafka-operator/blob/12cff8da6eb52031120ae78911ee968bd116c8ef/topic-operator/src/main/java/io/strimzi/operator/topic/TopicOperatorConfig.java#L367-L367) at startup, it appears to be true. Digging through, I saw the cluster operator actually adds the environment variable as a result from a hard-coded setting.

If the environment variable is manually added in the Kafka spec (see first code sample above), the cluster operator ignores it.

### Strimzi version

0.41

### Kubernetes version

v1.28.9-gke.1289000

### Installation method

Helm Chart

### Infrastructure

GKE

### Additional context

The security issue with Cruise Control is addressed using native Kubernetes filtering.
