### ISSUE TITLE
[Bug]: Cannot use Cruise Control to rebalance disks on KafkaNodePools with JBOD volumes

### ISSUE THREAD

**Issue by Kyle-Cooley** [strimzi/strimzi-kafka-operator#10280]
### Bug Description

When creating a KafkaRebalance resource for a cluster containing a node pool with multiple volumes (JBOD), it fails with an error stating that the cluster does not have JBOD volumes.

### Steps to reproduce

1. Create a cluster with multiple volumes using storage type jbod:

    ```yaml
   apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaNodePool
    metadata:
      name: dual-role
      labels:
        strimzi.io/cluster: my-cluster
    spec:
      replicas: 3
      roles:
        - controller
        - broker
      storage:
        type: jbod
        volumes:
          - id: 0
            type: persistent-claim
            size: 10Gi
            deleteClaim: false
            kraftMetadata: shared
          - id: 1
            type: persistent-claim
            size: 10Gi
            deleteClaim: false
            kraftMetadata: shared
    ---
    
    apiVersion: kafka.strimzi.io/v1beta2
    kind: Kafka
    metadata:
      name: my-cluster
      annotations:
        strimzi.io/node-pools: enabled
        strimzi.io/kraft: enabled
    spec:
      cruiseControl: {}
      kafka:
        version: 3.7.0
        metadataVersion: 3.7-IV4
        listeners:
          - name: plain
            port: 9092
            type: internal
            tls: false
          - name: tls
            port: 9093
            type: internal
            tls: true
        config:
          offsets.topic.replication.factor: 1
          transaction.state.log.replication.factor: 1
          transaction.state.log.min.isr: 1
          default.replication.factor: 1
          min.insync.replicas: 1
      entityOperator:
        topicOperator: {}
        userOperator: {}
   ```

2. Create a KafkaRebalance resource

   ```yaml
   apiVersion: kafka.strimzi.io/v1beta2
   kind: KafkaRebalance
   metadata:
     name: proposal
     labels:
       strimzi.io/cluster: my-cluster
   spec: 
     skipHardGoalCheck: true
     rebalanceDisk: true
     goals:
     - CpuCapacityGoal
     - DiskCapacityGoal
     - RackAwareGoal
     - MinTopicLeadersPerBrokerGoal
     - ReplicaCapacityGoal
   ```

3. Describe the resource and observe the following status condition:

   ```
   Conditions:
     Last Transition Time:  2024-06-29T21:03:53.198686083Z
     Message:               Cannot set rebalanceDisk=true for Kafka clusters with a non-JBOD storage config. Intra-broker balancing only applies to Kafka deployments that use JBOD storage with multiple disks.
     Reason:                InvalidResourceException
     Status:                True
     Type:                  NotReady

   ```

### Expected behavior

Cruise Control should rebalance the data across JBOD volumes.

### Strimzi version

0.41.0

### Kubernetes version

v1.28.3

### Installation method

YAML files

### Infrastructure

Minikube
