### ISSUE TITLE
[Enhancement]: Allow to mount trustedCertificates as configmap in KafkaConnect

### ISSUE THREAD

**Issue by RafaelOm** [strimzi/strimzi-kafka-operator#10308]
### Related problem

Currently, the KafkaConnect CRD allows us to mount the tls trusted certificates using a secret.
Under my point of view, it should be able to mount the trusted CAs using also configmaps.
This should not be a security issue because the certificates mounted here are public keys of the Certificate Authority.

### Suggested solution

Be able to mount the trusted CAs using also configmaps.
```
tls:
  trustedCertificates:
    - secretName: my-cluster-cluster-cert
      certificate: ca.crt
    - configmap: my-ca-configmap
      certificate: ca2.crt
```

### Additional context

https://strimzi.io/docs/operators/latest/full/configuring.html#con-common-configuration-trusted-certificates-reference
