### ISSUE TITLE
Make it easier to handle TLS trust in service account based authentication

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#10354]
In #10317 we add support for service account based authentication. But the way to configure TLS trust seems very hacky and strange. We should figure out how to improve this:
* Either by support for loading certs from ConfigMaps (see #10308)
* Or by allowing to use the certificate mounted in the pod itself

**Comment by scholzj** [comment]
Triaged on the Community call on 8.8.2024: Should be postponed for the next call with more maintainers.

**Comment by scholzj** [comment]
Discussed on a community call on 22.8.2024: This makes sense and should be kept. But it should have a proposal since there are at least two ways how to handle this:
* Use the certificate from the path already mounted int he Kafka pods
* Use the Kube Config Map directly

The proposal should clarify the exact approach.

**Comment by L040639** [comment]
``Hey @scholzj  , trying to connect the tls enabled boostrap server from my app code, i am unable to connect, which certs i have to use in the pod to connect the cluster, if tls is false i can able to connect .
`yaml
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka-system-dev
  # annotations:
  #   sidecar.istio.io/inject: "true"         ##currently disabled .
spec:                                                                                 ##yet to add promethous metric server .`
  kafka:
    version: 3.7.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: true
        authentication:
          type: tls
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: clusterip
        port: 9096
        type: cluster-ip
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.7"
      auto.create.topics.enable: "false"                    #                                check this to enable topic creation automatically .
    # authorization:
    #   type: simple
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi                                                                            ## Currently 10gi, will be increase .
        deleteClaim: false
        class: efs-sc
      - id: 1
        type: persistent-claim
        size: 10Gi                                                                            ## Currently 10gi, will be increase .
        deleteClaim: false
        class: efs-sc
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi                                                                               ## Currently 10gi, will be increase .
      deleteClaim: false
      class: efs-sc
  entityOperator:
    topicOperator:
      watchedNamespace: kafka-system-dev
    userOperator:
      watchedNamespace: kafka-system-dev`

**Comment by scholzj** [comment]
Sorry, but what does it have to do with this issue?

**Comment by L040639** [comment]
@scholzj updated the case above .

**Comment by scholzj** [comment]
Assuming the proposal https://github.com/strimzi/proposals/pull/175 goes through, I think this issue will not be needed anymore. With `type: custom` authentication, you can easily use certificates from Config Maps either by using the one mounted with the Service Account or mount a separate one through additional volumes. E.g.:

```
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: custom
          sasl: true
          listenerConfig:
            sasl.enabled.mechanisms: OAUTHBEARER
            oauthbearer.sasl.server.callback.handler.class: io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
            oauthbearer.sasl.jaas.config: |
                org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required unsecuredLoginStringClaim_sub="thePrincipalName" oauth.valid.issuer.uri="https://kubernetes.default.svc.cluster.local" oauth.jwks.endpoint.uri="https://kubernetes.default.svc.cluster.local/openid/v1/jwks" oauth.server.bearer.token.location="/var/run/secrets/kubernetes.io/serviceaccount/token" oauth.check.access.token.type="false" oauth.include.accept.header="false" oauth.custom.claim.check="@.['kubernetes.io'] && @.['kubernetes.io'].['namespace'] in ['myproject']" oauth.ssl.truststore.location="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt" oauth.ssl.truststore.type="PEM";
            principal.builder.class: io.strimzi.kafka.oauth.server.OAuthKafkaPrincipalBuilder
            connections.max.reauth.ms: 3600000
```
