### ISSUE TITLE
[Bug]: Infinite topic sync in topic operator

### ISSUE THREAD

**Issue by padilo** [strimzi/strimzi-kafka-operator#10380]
### Bug Description

When the specs on an unmanaged KafkaTopic resource (annotated with `strimzi.io/managed="false"`) is different from the topic on the cluster, the topic operator enters a loop and continuously tries updates the resourceVersion.

Seems like it's trying to consolidate the state, but as is unmanaged it can't and continues in the loop forever.

### Steps to reproduce

You can do the following script:

```
helm install strimzi-cluster-operator --set replicas=1 --version 0.42.0 oci://quay.io/strimzi-helm/strimzi-kafka-operator

# Create Kafka cluster:
kubectl apply -f - <<EOF 
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-kafka
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    storage:
      type: persistent-claim
      size: 1Gi
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi

  entityOperator:
    topicOperator: {}
EOF
kubectl wait --for=condition=ready --timeout=10m kafka/my-kafka

# Create a topic
kubectl apply -f - <<EOF
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sync-test
  labels:
    strimzi.io/cluster: my-kafka
spec:
  replicas: 1
  partitions: 1
  config:
    retention.ms: 432000000
EOF

sleep 5

# Annotate topic as unmanaged
kubectl annotate kafkatopic sync-test strimzi.io/managed="false"

# Path the topic with updated retention
kubectl patch kafkatopic sync-test --type='merge' -p '{"spec": {"config": {"retention.ms": "432000001"}} }'
```

### Expected behavior

Topic operator should entirely ignore the KafkaTopic resources if it is set to unmanaged

### Strimzi version

0.42.0

### Kubernetes version

Kubernetes 1.30.0

### Installation method

helm chart

### Infrastructure

Kind, also confirmed with EKS

### Configuration files and logs

all relevant stuff is already in the steps to reproduce

### Additional context

I would like to work on this issue :)
