### ISSUE TITLE
Key `password` in MirrorMaker `spec` is ambiguous named 

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-operator#1042]
If look at the example in Strimzi documentation we can find the following example:
```
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
spec:
  # ...
  consumer:
    authentication:
      type: scram-sha-512
      username: my-source-user
      passwordSecret:
        secretName: my-source-user
        password: password
```
where we need to specify an authentication setting for Mirror Maker. And after reading the text above in the documentation `Specify the password as a link to a Secret containing the password in the passwordSecret property.` I still can't understand what value I need to set for key `password`. If look at the `PasswordSecretSource schema reference` we can find a strong description for this key, like `The name of the key in the Secret under which the password is stored.` but the key name still looks confusing. 
My point of view here that we need to rename this key from `password` to `passwordKey`. (@ppatierno idea generator)
