### ISSUE TITLE
[Bug]: KafkaConnectors cannot be scaled with HPA via KEDA

### ISSUE THREAD

**Issue by philipp94831** [strimzi/strimzi-kafka-operator#10450]
### Bug Description

KEDA allows auto-scaling of custom Kubernetes resources using the scale subresource. KafkaConnector does have this resource but auto-scaling is failing with the following error: `InvalidSelector: the HPA target's scale is missing a selector`. According to this [answer](https://github.com/kedacore/keda/issues/5898#issuecomment-2188661681), the custom resource requires a `status.selector` field in the scale subresource, which is not present in the current [CRDs](https://github.com/strimzi/strimzi-kafka-operator/blob/73f5d0365c1f6a7a699d6bb9f92c7f1ea5af75e1/helm-charts/helm3/strimzi-kafka-operator/crds/047-Crd-kafkaconnector.yaml#L29). See also the [linked blog post](https://medium.com/@thescott111/autoscaling-kubernetes-custom-resource-using-the-hpa-957d00bb7993) in the answer.

### Steps to reproduce

1. Create a KafkaConnector resource
  ```yaml
  apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaConnector
  metadata:
    labels:
      strimzi.io/cluster: strimzi
    name: my-connector
  spec:
    class: com.example.Connector
    config:
      topics: my-topic
      # configure the connector
    state: running
    tasksMax: 1
  ```
2. Create a ScaledObject resource
  ```yaml
  apiVersion: keda.sh/v1alpha1
  kind: ScaledObject
  metadata:
    name: my-connector-so
  spec:
    cooldownPeriod: 300
    maxReplicaCount: 2
    minReplicaCount: 1
    pollingInterval: 30
    scaleTargetRef:
      apiVersion: kafka.strimzi.io/v1beta2
      kind: KafkaConnector
      name: my-connector
    triggers:
    - metadata:
        bootstrapServers: strimzi-kafka-bootstrap:9092
        consumerGroup: connect-my-connector
        lagThreshold: "1000"
        offsetResetPolicy: earliest
        topic: my-topic
      type: kafka
  ```

### Expected behavior

KEDA/HPA can auto-scale KafkaConnector, i.e., no errors are generated by HPA

### Strimzi version

0.41.0

### Kubernetes version

Kubernetes 1.28

### Additional context

KEDA version 2.15.1
