### ISSUE TITLE
topic-operator fails liveness 7x per hour

### ISSUE THREAD

**Issue by BradyWiseman** [strimzi/strimzi-kafka-operator#1050]
Running strimzi/topic-operator:0.8.2 standalone on Oracle Cloud Infrastructure/Oracle Kubernetes Engine.
Using manifests as shipped in examples/install/topic-operator.
Once started, topic-operator fails liveness probe 5-7 times per hour and is restarted by k8s.  Pod logs show normal operation (using DEBUG flag), no exceptions or errors.

We have increased both cpu & memory requests, which seemed to help, then back to the previous pattern.

**Comment by scholzj** [comment]
Hmm, interesting. Can you supply the full log from the Topic Operator? If you are using the `examples/install/topic-operator` installation, you are using it with your own Kafka cluster which is not deployed by the Strimzi Cluster Operator, right? Is this cluster stable? Are other applications connected to the Kafka and Zookeeper nodes running stable?

**Comment by BradyWiseman** [comment]
Correct - kafka cluster is dead simple, not deployed by strimzi.  Yes, it is stable.  Nothing else is connected to it.
I will send logs after next lengthy run.

**Comment by wmorgan6796** [comment]
I am having this issue on a much larger scale as well. I use the vanilla option as well
[logs-from-topic-operator-in-will-cluster-entity-operator-67ccb64c86-hrkv9.txt](https://github.com/strimzi/strimzi-kafka-operator/files/2555860/logs-from-topic-operator-in-will-cluster-entity-operator-67ccb64c86-hrkv9.txt)

**Comment by scholzj** [comment]
@wmorgan6796 For how long can you see this repeat in the log file? On the startup, this can sometimes happen before all the components get in sync and up and running.

**Comment by wmorgan6796** [comment]
I’m seeing this for hours straight. Today over a four hour period it had
over 20 restarts.

**Comment by scholzj** [comment]
Hmm, that is strange. Could you please also share the log from the tls-sidecar / stunnel container in the same pod? Do you use persistent or ephemeral Zookeeper?

**Comment by sjbodzo** [comment]
I am also seeing the same issue. We had a 5-node cluster deployed for ~6 hours that restarted 20+ times while sitting idle.

**Comment by wmorgan6796** [comment]
Here are logs from the tls sidecar and the topic operator at the same time
[tls-sidecar-topic-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/2557816/tls-sidecar-topic-operator.log)
[topic-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/2557817/topic-operator.log)

**Comment by BradyWiseman** [comment]
This problem went away with a change in config.

**Comment by totemcaf** [comment]
@BradyWiseman can you describe the change in config that solve the problem?, thanks

**Comment by shalin-hudda** [comment]
I had the same issue but when I added the following "resources" config the issue got resolved:
```yml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: projec
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    resources:
      limits:
        cpu: 1000m
        memory: 1536Mi
      requests:
        cpu: 500m
        memory: 768Mi
    listeners:
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.6"
      inter.broker.protocol.version: "2.6"
      auto.create.topics.enable: "false"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator:
      resources:
        limits:
          cpu: 1000m
          memory: 1536Mi
        requests:
          cpu: 500m
          memory: 768Mi
    userOperator:
      resources:
        limits:
          cpu: 1000m
          memory: 1536Mi
        requests:
          cpu: 500m
          memory: 768Mi
```

Hope this helps.
