### ISSUE TITLE
[Bug]: The namespace.mapper configuration option of Mongodb Sink connector is reported as forbidden

### ISSUE THREAD

**Issue by aka-peter** [strimzi/strimzi-kafka-operator#10500]
### Bug Description

The namespace.mapper configuration of the Mongodb connector is reported as forbidden.

```
2024-08-27 07:16:39 WARN  AbstractConfiguration:147 - Reconciliation #14080(timer) KafkaConnect(my-proj/strimzi): Configuration option "namespace.mapper" is forbidden and will be ignored
```
https://www.mongodb.com/docs/kafka-connector/current/sink-connector/configuration-properties/mongodb-namespace/#std-label-sink-configuration-namespace-mapping

### Steps to reproduce

Create a Mongodb Sink connector and check the logs.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
  labels:
    strimzi.io/cluster: strimzi
  name: my-mongodb-sink
  namespace: my-ns
spec:
  class: com.mongodb.kafka.connect.MongoSinkConnector
  config:
    namespace.mapper: com.mongodb.kafka.connect.sink.namespace.mapping.FieldPathNamespaceMapper
```

### Expected behavior

The namespace.mapper configuration options should be accepted.

### Strimzi version

0.43.0

### Kubernetes version

Kubernetes 1.27

### Installation method

Kustomize

### Additional context

Could possibly been introduced here

https://github.com/strimzi/strimzi-kafka-operator/pull/10229

https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/AbstractConfiguration.java#L141
