### ISSUE TITLE
[Bug]: Cannot install Strimzi on KinD

### ISSUE THREAD

**Issue by QuinnBast** [strimzi/strimzi-kafka-operator#10585]
### Bug Description

Attempting to install the Strimzi kafka operator to a KinD cluster results in the operator going into a crash-loop backoff.
My KinD cluster is running on Almalinux 9 (though this shouldn't matter?)

> exec /opt/strimzi/bin/cluster_operator_run.sh: exec format error
> Stream closed EOF for kafka/strimzi-cluster-operator-77cc6fbbdb-hc4rq (strimzi-cluster-operator)

### Steps to reproduce

1. Perform a helm install from https://strimzi.io/charts using version: 0.41.0 of strimzi-kafka-operator
2. Use the values file below.
3. Once the minfests get applied, the operator goes into a crashloop backoff.

### Expected behavior

Would expect the operator to work. It works on other baremetal clusters so this might be something to do with KinD or running inside of a virtualized environment.

### Strimzi version

0.41.0

### Kubernetes version

v1.29.2

### Installation method

Helm Chart

### Infrastructure

Bare-Metal

### Configuration files and logs

Chart values.yaml
```
defaultImageRegistry: quay.io
defaultImageRepository: strimzi
defaultImageTag: 0.41.0

priorityClassName: ""

dashboards:
  enabled: false
```

CRD:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka-pool
  labels:
    # Must match the name of your cluster below
    strimzi.io/cluster: kafka-cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  # Configure storage here.
  storage:
    type: persistent-claim
    size: 10Gi
    class: standard
    deleteClaim: false
    kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    replicas: 1
    resources:
      requests:
          memory: 1Gi
          cpu: 500m
      limits:
          memory: 4Gi
          cpu: 1
    version: 3.7.0
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: INFO
    jvmOptions:
      "-XX":
        UseG1GC: "true"
        MaxGCPauseMillis: "20"
    # You might need more than this if you plan on exposing kafka outside of the cluster
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.7"
      delete.topic.enable: "true"
      auto.create.topics.enable: "true"
      log.retention.ms: 600000 # 10 minutes
      # The cleaner settings determine how long out-of-date records can exist on a compacted log before they
      # can be deleted. These settings should be high enough so that if a consumer starts at the beginning of
      # a compacted log topic, it should be able to read to the end before the retention time expires.
      log.cleaner.max.compaction.lag.ms: 3600000 # 1 hour
      log.cleaner.min.compaction.lag.ms: 600000 # 10 minutes
      log.cleaner.delete.retention.ms: 600000 # 10 minutes
      # Compaction is only run on older segments (not the active one), so also set a relatively small segment
      # size to trigger rollover more often.
      log.segment.bytes: 52428800 # 50 MiB
  entityOperator:
    topicOperator:
      # You need to change this to your kafka namespace if different
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 30
    userOperator:
      watchedNamespace: kafka
      reconciliationIntervalSeconds: 30
```

### Additional context

My KinD cluster is running through Podman if that means anything.
