### ISSUE TITLE
[Bug]: WARN The client is using resource type 'kafkanodepools' with unstable version 'v1beta2'

### ISSUE THREAD

**Issue by hlisdero** [strimzi/strimzi-kafka-operator#10584]
### Bug Description

Hi everybody,

I followed the procedure described in the documentation to migrate to `KafkaNodePools`.
https://strimzi.io/docs/operators/latest/deploying#proc-migrating-clusters-node-pools-str

I get two warnings after migrating to a `KafkaNodePool`.

> 2024-09-13 17:01:04 WARN  KafkaAssemblyOperator:923 - KafkaNodePool kafka in namespace kafka was ADDED, but the Kafka cluster migration-tutorial to which it belongs does not have KafkaNodePool support enabled
> (...)
> 2024-09-13 17:01:55 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkanodepools' with unstable version 'v1beta2'

This warning could be in part misleading, since the version 'v1beta2' is the only one available right now for a 'KafkaNodePool'.

The command `kubectl get kafka` shows the column `WARNINGS` with `True`. This could shadow other warnings that may come later. The warning flag does not seem to go away.

```text
NAME                 DESIRED KAFKA REPLICAS   DESIRED ZK REPLICAS   READY   METADATA STATE   WARNINGS
migration-tutorial   3                        1                     True    ZooKeeper        True
```

Intestingly enough, if I remove the annotations from the Kafka resource, the second warning is not printed anymore but the `WARNINGS` column is set. Does this mean that I should not set the annotation at all in the beginning?

### Steps to reproduce

1. Set up Strimzi in the `kafka` namespace as described in the quickstart
2. Apply the following configuration for a simple cluster similar to the one found in the [examples](https://github.com/strimzi/strimzi-kafka-operator/blob/0.43.0/examples/kafka/kafka-persistent.yaml) but with annotations set

  ```yaml
  apiVersion: kafka.strimzi.io/v1beta2
  kind: Kafka
  metadata:
    name: migration-tutorial
    annotations:
      strimzi.io/kraft: disabled # states that the cluster is ZooKeeper-based
      strimzi.io/node-pools: disabled
  spec:
    kafka:
      version: 3.8.0
      replicas: 3
      listeners:
        - name: plain
          port: 9092
          type: internal
          tls: false
        - name: tls
          port: 9093
          type: internal
          tls: true
      config:
        offsets.topic.replication.factor: 3
        transaction.state.log.replication.factor: 3
        transaction.state.log.min.isr: 2
        default.replication.factor: 3
        min.insync.replicas: 2
        inter.broker.protocol.version: "3.8"
      storage:
        type: jbod
        volumes:
          - id: 0
            type: persistent-claim
            size: 2Gi
            deleteClaim: true
    zookeeper:
      replicas: 1
      storage:
        type: persistent-claim
        size: 2Gi
        deleteClaim: true
    entityOperator:
      topicOperator: {}
      userOperator: {}
  ```

3. Apply the configuration for the Kafka node pool

  ```yaml
  apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaNodePool
  metadata:
    name: kafka
    labels:
      strimzi.io/cluster: migration-tutorial
  spec:
    roles:
      - broker
    replicas: 3
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 2Gi
          deleteClaim: true
  ``` 
  
3. Modify the annotation with the following command:

  ```bash
  kubectl annotate kafka migration-tutorial strimzi.io/node-pools="enabled" --overwrite
  ```

4. ` kubectl get kafka -w` shows "WARNINGS=True" and the logs of the operator show the warning message.

### Expected behavior

The warning is not printed in the logs and `WARNINGS` is not set to `True`.

### Strimzi version

0.43.0

### Kubernetes version

v1.31.0

### Installation method

YAML files

### Infrastructure

Minikube v1.34.0

### Configuration files and logs

**2024-09-13 17:01:04 WARN  KafkaAssemblyOperator:923 - KafkaNodePool kafka in namespace kafka was ADDED, but the Kafka cluster migration-tutorial to which it belongs does not have KafkaNodePool support enabled**
2024-09-13 17:01:54 INFO  AbstractOperator:510 - Reconciliation #32(watch) Kafka(kafka/migration-tutorial): Kafka migration-tutorial in namespace kafka was MODIFIED
2024-09-13 17:01:54 INFO  AbstractOperator:264 - Reconciliation #32(watch) Kafka(kafka/migration-tutorial): Kafka migration-tutorial will be checked for creation or modification
**2024-09-13 17:01:55 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkanodepools' with unstable version 'v1beta2'**
2024-09-13 17:01:55 INFO  CrdOperator:123 - Reconciliation #32(watch) Kafka(kafka/migration-tutorial): Status of KafkaNodePool kafka in namespace kafka has been updated
2024-09-13 17:01:55 INFO  KafkaAssemblyOperator:920 - Reconciliation #33(watch) Kafka(kafka/migration-tutorial): KafkaNodePool kafka in namespace kafka was MODIFIED
2024-09-13 17:01:56 INFO  StrimziPodSetController:378 - Reconciliation #34(watch) StrimziPodSet(kafka/migration-tutorial-kafka): StrimziPodSet will be reconciled
2024-09-13 17:01:56 INFO  StrimziPodSetController:414 - Reconciliation #34(watch) StrimziPodSet(kafka/migration-tutorial-kafka): reconciled
2024-09-13 17:01:57 INFO  AbstractOperator:510 - Reconciliation #35(watch) Kafka(kafka/migration-tutorial): Kafka migration-tutorial in namespace kafka was MODIFIED
2024-09-13 17:01:57 INFO  CrdOperator:123 - Reconciliation #32(watch) Kafka(kafka/migration-tutorial): Status of Kafka migration-tutorial in namespace kafka has been updated
2024-09-13 17:01:57 INFO  AbstractOperator:536 - Reconciliation #32(watch) Kafka(kafka/migration-tutorial): reconciled
