### ISSUE TITLE
[Bug]: Do reconciliation and rolling update on pod (Cruise Control) even if only secretKeyRef changed

### ISSUE THREAD

**Issue by egyedt** [strimzi/strimzi-kafka-operator#10649]
### Bug Description

We can deploy Kafka with Cruise Control e.g. from the following example:
https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/cruise-control/kafka-cruise-control-with-goals.yaml

If we would like to enable the Basic auth for Cruise Control, then the following section should be added to the yaml descriptor:
```yaml
#...
kind: Kafka
spec:
  # ...
  cruiseControl:
    # ...
    config:
      webserver.security.enable: true
    # ...
    apiUsers:
      type: hashLoginService
      valueFrom:
        secretKeyRef:
          name: cruise-control-api-users-secret
          key: cruise-control-auth.txt
  # ...
```
    
When I modified the name or the key of the **secret** in the `secretKeyRef`, e.g.:
```yaml
#...
        secretKeyRef:
          name: cruise-control-api-users-secret-2
          key: cruise-control-auth-2.txt
  # ...
```
then reconciliation loop was not able to recognize the change/modification and Cruise Control pod was NOT rolling updated, so it was still running with the old secret.

When I modified one of the **'spec.cruiseControl.config'** goal section, then reconciliation happened, and Cruise Control was rolling updated, which is the expected behaviour

### Steps to reproduce

1. Create a **cluster-operator**
2. Create **secret** for Cruise Control auth (e.g.: `userOne: passwordOne, USER`)
3. Deploy **Kafka with CC**: https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/cruise-control/kafka-cruise-control-with-goals.yaml, but with `apiUsers` section and with **'hashLoginService'**
4. Wait for the cluster to be ready
5. Create a new **secret** (name or key or both of them should be different from the secret of the 2nd step)
6. Edit **kafka-cruise-control-with-goals.yaml** to use the new secret, but nothing else
7. Wait for **reconciliation** and CC rolling update (**This will not happen!**)

### Expected behavior

Cruise Control pod should be reconciled even when only a secret ref is changed.
Furthermore we should check this behaviour for other type of resources as well (instead of Cruise Control)

### Strimzi version

main, 0.43.0

### Kubernetes version

1.30.1

### Installation method

yaml files + helm chart
