### ISSUE TITLE
[Enhancement]: Support Authentication for plugin downloads in KafkaConnect

### ISSUE THREAD

**Issue by aboucham** [strimzi/strimzi-kafka-operator#10691]
### Bug Description

the KafkaConnect build process does not support a basic authentication for a case that it requires credentials to connect to Respository like Artifactory for downloading artifacts:

The only way to do it right now is to expose the username and password are exposed in the URL:

```
    plugins:
      - name: kafka-connect-jdbc
        artifacts:
          - type: jar
            url: "https://myuser:mypassword@my.company.net/artifactory/io/confluent/kafka-connect-jdbc/10.6.1/kafka-connect-jdbc-10.6.1.jar"
```

### Strimzi version

main

### Kubernetes version

OpenShift 4.16
