### ISSUE TITLE
[Bug]: 0.43 in local kind cluster, fails with DNS problems

### ISSUE THREAD

**Issue by XBeg9** [strimzi/strimzi-kafka-operator#10765]
### Bug Description

My connector cluster just randomly fails to connect with this warning:

```
WARN [Worker clientId=connect-connector-connect-0.connector-connect.default.svc:8083, groupId=connector-cluster] Error connecting to node cluster-kafka-0.cluster-kafka-brokers.default.svc:9093 (id: 2147483647 rack: null) (org.apache.kafka.clients.NetworkClient) [DistributedHerder-connect-connector-connect-0.connector-connect.default.svc:8083-1]
java.net.UnknownHostException: cluster-kafka-0.cluster-kafka-brokers.default.svc
```

I have equal config on my production (non-local environment, and have zero issues). Something with `kind` cluster, and DNS resolution. 

What I have tried so far:
1. go zookeeper less (better, kafka starts, but connect still doesn't work)
2.  useServiceDnsDomain: true
3. KUBERNETES_SERVICE_DNS_DOMAIN = cluster.local

### Steps to reproduce

1. create local kind cluster with `ctlptl create cluster kind --registry=ctlptl-registry --min-cpus=8 --kubernetes-version 1.29` (I have used >1.29, same issue)
2. helm install (default values), also used `latest` link. 
3. apply this yaml
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: kafka
  labels:
    strimzi.io/cluster: cluster
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
        kraftMetadata: shared
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.8.0
    metadataVersion: 3.8-IV0
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: "1"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        # configuration:
        #   useServiceDnsDomain: true
      - name: tls
        port: 9093
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        tls: false
        type: internal
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
      superUsers:
        - kafkauser
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: connector
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: kafkaconnect
  replicas: 1
  bootstrapServers: cluster-kafka-bootstrap:9093
  authentication:
    type: scram-sha-512
    username: kafkauser
    passwordSecret:
      secretName: kafkauser-secret
      password: password
  config:
    group.id: connector-cluster
    offset.storage.topic: connector-offsets
    config.storage.topic: connector-configs
    status.storage.topic: connector-status
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
```

### Expected behavior

connector should connect to cluster 

### Strimzi version

0.43, 0.42

### Kubernetes version

1.29, 1.31

### Installation method

yaml, helm

### Infrastructure

kind
