### ISSUE TITLE
[Bug]: strimzi upgrade from `0.39.0` to `0.42.0` changed prometheus metrics URL

### ISSUE THREAD

**Issue by lgo** [strimzi/strimzi-kafka-operator#10811]
### Bug Description

I have had a deployment of strimzi `0.39.0` using Kafka MirroMaker2 (`3.6.1`). It is setup with some set it up with prometheus scraping operator and upon upgrading to strimzi `0.42.0` I found the metrics stopped working.

After some debugging, I realized in the pod after the upgrade `curl localhost:9404/` was giving a landing page pointing to query `/metrics` which is when it clicked - the metric URL must have changed requiring something like my `prometheus.io/path` to change from `/` to `/metrics`.

This was a little more subtle than that: on `0.39.0`, `localhost:9404/` and `localhost:9404/metrics` would return metrics whereas `0.42.0` only `localhost:9404/metrics` would return metrics. That did allow a two-step process to update the CRD, retain metrics, and upgrade strimzi which was nice.

It didn't appear to be documented anywhere so it took a bit of time to debug. I imagine this slipped in through a dependency bump, such as #10184. At worse, this issue should hopefully help anyone else running into prometheus scraping issues when upgrading strimzi, and at best we can pinpoint the culprit and make an update to the changelogs about this :)

### Strimzi version

0.42.0

### Kubernetes version

Kubernetes 1.29.7

### Configuration files and logs

The setup looks something like this:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-mirror-maker-config
data:
  metrics-config.yml: |
    lowercaseOutputName: true
    lowercaseOutputLabelNames: true

    rules: [ ... ]
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker
spec:
  version: 3.6.1
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        key: metrics-config.yml
        name: my-mirror-maker-config
  template:
    pod:
      metadata:
        annotations:
          prometheus.io/path: /
          prometheus.io/port: "9404"
          prometheus.io/scrape: "true"
```
