### ISSUE TITLE
[Bug]: Tiered storage remote retention.ms isn't applied to topic if local.retention.ms is less then 10800000(3h)

### ISSUE THREAD

**Issue by hennadii2012** [strimzi/strimzi-kafka-operator#10892]
### Bug Description

When we are wanting to store only 1 hour locally and 200 hours on tiered storage, we can see, that we have only 3h on tiered storage. In the logs of node poll object we can found, that segments are deleted from tiered storage after `retention.ms=10800000`. In the same time we can see in description of the topic via kafka-topics.sh script in container, that this option for this topic is `retention.ms=720000000` (like in the config). If increase `local.retention.ms` to more then 3h, then `retention.ms` become the same as in config and kafka works as it should

### Steps to reproduce

1. Create kafka using kind `Kafka`, that strimzi (version 0.44.0 in our case) crd provides version 3.8.0 with support of tiered storage and entiry-operator on board (we are using GCS and this driver: https://github.com/Aiven-Open/tiered-storage-for-apache-kafka/releases/tag/2024-10-23-1729694047)
2. Create the topic, using kind `KafkaTopic`, that strimzi crd provides with `local.retention.ms=3600000`, `remote.storage.enable=true`,`segment.ms=3600000`
3. Wait for 4 hours and see that data on remote storage are deleted for the first hour
4. Increase `local.retention.ms=14400000` and wait 24h. See that data are not deleted
5. Decrease `local.retention.ms=3600000` and see that all data except last 3h are deleted

### Expected behavior

We are expecting respect of `retention.ms` option in case of `local.retention.ms` one is less then 3h

### Strimzi version

0.44.0

### Kubernetes version

Kubernetes-1.30.5-gke.1014003

### Installation method

Helm chart

### Infrastructure

Google GKE

### Configuration files and logs

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  labels:
    strimzi.io/cluster: test
  name: test
  namespace: test
spec:
  cruiseControl:
    autoRebalance:
      - mode: add-brokers
        template:
          name: test-rb-tpl
      - mode: remove-brokers
        template:
          name: test-rb-tpl
    brokerCapacity:
      inboundNetwork: 2GiB/s
      outboundNetwork: 2GiB/s
      overrides:
        - brokers:
            - 0
          inboundNetwork: 2GiB/s
          outboundNetwork: 2GiB/s
        - brokers:
            - 1
            - 2
          inboundNetwork: 2GiB/s
          outboundNetwork: 2GiB/s
    config:
      broker.failure.alert.threshold.ms: '30000'
      broker.failure.self.healing.threshold.ms: '40000'
      cpu.balance.threshold: '1.1'
      default.goals: >
        com.linkedin.kafka.cruisecontrol.analyzer.goals.RackAwareGoal,
        com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaCapacityGoal,
        com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal,
        com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkInboundCapacityGoal,
        com.linkedin.kafka.cruisecontrol.analyzer.goals.NetworkOutboundCapacityGoal,
        com.linkedin.kafka.cruisecontrol.analyzer.goals.CpuCapacityGoal,
        com.linkedin.kafka.cruisecontrol.analyzer.goals.ReplicaDistributionGoal,
        com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderBytesInDistributionGoal,
        com.linkedin.kafka.cruisecontrol.analyzer.goals.TopicReplicaDistributionGoal,
        com.linkedin.kafka.cruisecontrol.analyzer.goals.LeaderReplicaDistributionGoal
      disk.balance.threshold: '1.1'
      hard.goals: |
        com.linkedin.kafka.cruisecontrol.analyzer.goals.DiskCapacityGoal
      metadata.max.age.ms: '30000'
      send.buffer.bytes: '131072'
      webserver.http.cors.enabled: 'true'
      webserver.http.cors.exposeheaders: User-Task-ID,Content-Type
      webserver.http.cors.origin: '*'
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    logging:
      loggers:
        rootLogger.level: INFO
      type: inline
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: metrics-config.yml
          name: cruise-control-metrics
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 1
        memory: 512Mi
    template:
      pod:
        securityContext:
          fsGroup: 0
          runAsUser: 1000001
        terminationGracePeriodSeconds: 120
  entityOperator:
    topicOperator:
      logging:
        loggers:
          rootLogger.level: INFO
        type: inline
      reconciliationIntervalMs: 60000
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 1
          memory: 512Mi
      watchedNamespace: test
    userOperator:
      logging:
        loggers:
          rootLogger.level: INFO
        type: inline
      reconciliationIntervalMs: 60000
      resources:
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 1
          memory: 512Mi
      watchedNamespace: test
  kafka:
    config:
      auto.create.topics.enable: 'false'
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      remote.log.storage.system.enable: 'true'
      rlmm.config.remote.log.metadata.topic.replication.factor: 1
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    jvmOptions:
      '-Xms': 2048m
      '-Xmx': 2048m
    listeners:
      - configuration:
          useServiceDnsDomain: false
        name: plain
        port: 9092
        tls: false
        type: internal
      - name: external
        port: 9099
        tls: false
        type: nodeport
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    logging:
      loggers:
        kafka.root.logger.level: INFO
      type: inline
    metadataVersion: '3.8'
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    resources:
      limits:
        cpu: 700m
        memory: 7Gi
      requests:
        cpu: 700m
        memory: 7Gi
    template:
      serviceAccount:
        metadata:
          annotations:
            iam.gke.io/gcp-service-account: test@test.iam.gserviceaccount.com
    tieredStorage:
      remoteStorageManager:
        className: io.aiven.kafka.tieredstorage.RemoteStorageManager
        classPath: /opt/kafka/plugins/tiered-storage-gcs/*
        config:
          chunk.size: '4194304'
          storage.backend.class: io.aiven.kafka.tieredstorage.storage.gcs.GcsStorage
          storage.gcs.bucket.name: test
          storage.gcs.credentials.default: 'true'
      type: custom
    version: 3.8.0
  kafkaExporter:
    groupRegex: .*
    topicRegex: .*

```
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster:  test
  name:  test
  namespace:  test
spec:
  config:
    local.retention.ms: '2600000'
    min.insync.replicas: '1'
    remote.storage.enable: 'true'
    retention.ms: '720000000'
    segment.bytes: '1073741824'
    segment.ms: '3600000'
  partitions: 375
  replicas: 2
 ```
 
 ```yaml 
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  labels:
    strimzi.io/cluster: test
  name: test-b-0
  namespace: test
spec:
  replicas: 3
  roles:
    - broker
  storage:
    class: pd-balanced
    deleteClaim: true
    kraftMetadata: shared
    size: 40Gi
    type: persistent-claim
 ```
