### ISSUE TITLE
[Bug]: strimzi operator doesn't expose content-type in /metrics endpoint

### ISSUE THREAD

**Issue by KyriosGN0** [strimzi/strimzi-kafka-operator#10902]
### Bug Description

after upgrading to Prometheus v3, we noticed it started to alert us on TargetDown for strimzi operator pods 
the error from the logs are `non-compliant scrape target sending blank Content-Type and no fallback_scrape_protocol specified for target`

### Steps to reproduce

1. deploy strimzi operator 
2. deploy prometheus v3
3. create pod/service monitor and try to scrape the /metrics endpoint 

### Expected behavior

prometheus v3 should scrape without any issues 

### Strimzi version

0.44.0

### Kubernetes version

1.30.5

### Installation method

helm chart 

### Infrastructure

GKE

### Configuration files and logs

```
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cluster-operator-metrics
  labels:
    app: strimzi
spec:
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  podMetricsEndpoints:
  - path: /metrics
    port: http
  selector:
    matchLabels:
      name: strimzi-cluster-operator
````

podmonitor config we used
