### ISSUE TITLE
[Bug]: Mirror Maker OAuth Authentication with Client Assertion expiration

### ISSUE THREAD

**Issue by MarekLani** [strimzi/strimzi-kafka-operator#11002]
### Bug Description

I am using OAuth authentication with Client Assertion from within Mirror Maker. I have configured Mirror Maker to pickup the client assertion from Kubernetes secret. Since the client assertion JWT has its expiration, I do have an mechanism which generates new client assertions and updates Kubernetes Secret. Mirror Maker however seems not to have a mechanism to pickup the updated version of the secret and it locks to the value of secret set during the pod/container start and naturaly fails to authenticate to target Kafka cluster after some time (in my case it is Azure Event Hubs Kafka interface)

Given the limited time validity of client assertions I would need the Mirror Maker to be able to force refresh the client assertion value. Please what is the suggeste approach here?

### Steps to reproduce

See above and provided configuration.

### Expected behavior

I would expect Mirror Maker to pickup the new value of the client assertion secret

### Strimzi version

0.44

### Kubernetes version

1.30.6

### Installation method

Helm Chart

### Infrastructure

Azure Kubernetes Service

### Configuration files and logs

Mirror Maker configuration: 

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mymirrormaker
  namespace: kafka
spec:
  version: 3.8.0
  replicas: 1
  connectCluster: "eventhub"
  clusters:
  - alias: "my-cluster"
    bootstrapServers: x.x.x.x:9092
  - alias: "eventhub"
    bootstrapServers: myeh.servicebus.windows.net:9093
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
      producer.connections.max.idle.ms: 180000
      producer.metadata.max.age.ms: 180000
    authentication:
      type: oauth
      tokenEndpointUri: https://login.microsoftonline.com/<tenantid>/oauth2/v2.0/token
      clientId: <clientid>
      scope: https://myeh.servicebus.windows.net/.default
      clientAssertion:
        secretName: client-assertion-secret
        key: client-assertion
    tls:
      trustedCertificates: []
  mirrors:
  - sourceCluster: "my-cluster"
    targetCluster: "eventhub"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: ".*"
    groupsPattern: ".*"
```

**Comment by scholzj** [comment]
I don't think this is a bug. The client connector is instantiated once and is not reconfigured by Kafka MirrorMaker2/Connect.

**Comment by MarekLani** [comment]
Agree this is more of a generic question about design, nevertheless when the access token expires, reauthentication is needed and for that the fresh client assertion is needed. I was thinking about using the clientAssertionPath instead where I would use volume shared with additional custom pod, which would take care of updating the secret (client assertion). Would this work?

If there is no way to periodically update the client assertion it essentialy makes it unusable, but there might be some gap in my udnerstanding of the process.

**Comment by scholzj** [comment]
Maybe you need to use it in the way that allows the library to refresh the token - as far as I know if you configure it with client id and secret it will auto-refresh the tokens.

**Comment by MarekLani** [comment]
I am looking for as secure approach as possible and use of certificates/client assertion is preffered for that reason. I understand strimzi CRD supports feeding the client assertion to underlying Kafka libraries via yaml file and I would expect kafka libraries to be able to request new token. Please can you help me understand where exactly the gap which prevents reauthentication is? Is it udenrlying Kafka or strimzi?

**Comment by scholzj** [comment]
As I said, the assertion is loaded when the container starts and not updated later.

**Comment by MarekLani** [comment]
Sorry for delay, I needed some time for testing. I have explored approach with  clientAssertionPath. I was able to validate that if I change the client assertion value on the provided path, the reauthentication of MirrorMaker against event hubs works. However there is additional problem to this approach. I was not able to figure out how to create a volume mapping for the Mirror Maker container spinned up thru Strimzi CRD. Is this possible? I would like to have a standalone container or a pod, making care of the refresh of client assertion and propagating the update to mirror maker pod via volume

**Comment by scholzj** [comment]
The assertion is mounted from a file from a mounted Secret, or? That normally auto-updates when you update the Secret.

**Comment by scholzj** [comment]
The assertion is mounted from a file from a mounted Secret, or? That normally auto-updates when you update the Secret. But the assertion is loaded at the startup. So I do not think you can reload it regardless of how you update the file.

**Comment by scholzj** [comment]
Actually, I guess it depends whether you use it in the source or target cluster. For source cluster, it is loaded through the FileConfigProvider when the connector (task?) is started. But that will definitely not do any periodic reloading of the file either.

**Comment by MarekLani** [comment]
So this is my auth specification for target cluster Event Hub

```
    authentication:
      type: oauth
      tokenEndpointUri: https://login.microsoftonline.com/tenantid/oauth2/v2.0/token
      clientId: <clientId>
      scope: https://<sbname>.servicebus.windows.net/.default
      clientAssertionLocation: /output/jwt.txt
```

I produce the assertion jwt.txt file using cron job baked into custom Mirror Maker 2 Image which I reference in Strimzi Operator config:

```
FROM quay.io/strimzi/kafka:0.45.0-kafka-3.8.0

USER root

# Install necessary tools if not already available
RUN microdnf install -y openssl util-linux cronie && microdnf clean all

# Ensure directories exist and have appropriate permissions
RUN mkdir -p /var/run /var/log /etc/cron.d /output && chmod -R 777 /var/run /var/log /etc/cron.d /output

# Copy the script and necessary files into the container
COPY jwtgen.sh /usr/local/bin/jwtgen.sh
# Script generating Client Assertion JWT
COPY service-principal.pem /usr/local/bin/service-principal.pem
COPY private.key /usr/local/bin/private.key

# Make the script executable
RUN chmod +x /usr/local/bin/jwtgen.sh

# Add a cron job to execute the script every minute
RUN echo "* * * * * root PATH="/usr/bin:/bin" /usr/bin/sh /usr/local/bin/jwtgen.sh" > /etc/cron.d/jwtgen-cron
RUN chmod 0644 /etc/cron.d/jwtgen-cron
RUN crontab /etc/cron.d/jwtgen-cron

# Custom entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the custom entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
```

And this works I am not seeing authentication errors as I have seen when referencing client assertion from secret.

Nevertheless I'd like to prevent creation of custom docker image and running the cron job and as I mentioned rather have additional custom pod generating the assertion and writting it into a volume or a secret.

I was trying to achieve this but I am unable to add a volume into Mirror Maker pod. In the Mirror Maker 2 CRD spec I found the option to add a volume and volume mounts like so:

```
  template:
    pod:
	  volumes:
        - name: secret-volume
          secret:
            secretName: my-secret
	connectContainer:
	  volumeMounts:
        - name: secret-volume
          mountPath: "/mnt/my-secret"
          readOnly: true
```

but no mattter what mount path I use I do get following error from operator when trying to spin up the Mirror Maker:

Message: Pod "mymirrormaker-mirrormaker2-0" is invalid: spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/mnt/my-secret": must be unique. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.containers[0].volumeMounts[3].mountPath, message=Invalid value: "/mnt/my-secret": must be unique, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Pod, name=mymirrormaker-mirrormaker2-0, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Pod "mymirrormaker-mirrormaker2-0" is invalid: spec.containers[0].volumeMounts[3].mountPath: Invalid value: "/mnt/my-secret": must be unique, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).

**Comment by scholzj** [comment]
I guess you would need to share the full custom resource to understand why you get the error.

**Comment by MarekLani** [comment]
of course, here is the Mirror Maker 2 yaml definition I use:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mymirrormaker
  namespace: kafka
spec:
  version: 3.8.0
  replicas: 1
  connectCluster: "eventhub"
  clusters:
  - alias: "my-cluster"
    bootstrapServers: 57.154.208.44:9092
  - alias: "eventhub"
    bootstrapServers: ehmljnt.servicebus.windows.net:9093
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
      producer.connections.max.idle.ms: 180000
      producer.metadata.max.age.ms: 180000
    authentication:
      type: oauth
      tokenEndpointUri: https://login.microsoftonline.com/fe63bf93-7bc5-4b22-a352-ca31381cd813/oauth2/v2.0/token
      clientId: f36d8e12-ca94-4acc-9d86-5bf8ff3f204b
      scope: https://ehmljnt.servicebus.windows.net/.default
      clientAssertionLocation: /output/jwt.txt
    tls:
      trustedCertificates: []
  mirrors:
  - sourceCluster: "my-cluster"
    targetCluster: "eventhub"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: ".*"
    groupsPattern: ".*"
  template:
    pod:
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret
    connectContainer:
      volumeMounts:
      - name: secret-volume
        mountPath: "/mnt/my-secret"
        readOnly: true
```

**Comment by MarekLani** [comment]
Of course here is the Mirror Maker definition I use:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mymirrormaker
  namespace: kafka
spec:
  version: 3.8.0
  replicas: 1
  connectCluster: "eventhub"
  clusters:
  - alias: "my-cluster"
    bootstrapServers: <kafkaip>:9092
  - alias: "eventhub"
    bootstrapServers: <ehanme>.servicebus.windows.net:9093
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
      producer.connections.max.idle.ms: 180000
      producer.metadata.max.age.ms: 180000
    authentication:
      type: oauth
      tokenEndpointUri: https://login.microsoftonline.com/<tenantId>/oauth2/v2.0/token
      clientId: <clientId>
      scope: https://<ehname>.servicebus.windows.net/.default
      clientAssertionLocation: /output/jwt.txt
    tls:
      trustedCertificates: []
  mirrors:
  - sourceCluster: "my-cluster"
    targetCluster: "eventhub"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: ".*"
    groupsPattern: ".*"
  template:
    pod:
	  volumes:
        - name: secret-volume
          secret:
            secretName: my-secret
	connectContainer:
	  volumeMounts:
        - name: secret-volume
          mountPath: "/mnt/my-secret"
          readOnly: true
```
