### ISSUE TITLE
[Bug]: unable to upgrade to 3.9.0: Could not upgrade metadata.version to 21

### ISSUE THREAD

**Issue by osklil** [strimzi/strimzi-kafka-operator#11039]
### Bug Description

I have upgraded operator from 0.44.0 to 0.45.0 and then edited the Kafka CRD to change spec.kafka.version from 3.8.0 to 3.9.0. The pods recreated with new image but the upgrade did not complete. Now the cluster got this status:
```
  status:
    conditions:
    - lastTransitionTime: "2025-01-15T05:37:35.221452943Z"
      message: Failed to update metadata version to 3.9
      reason: MetadataUpdateFailed
      status: "True"
      type: Warning
```

I tried manual upgrade:

```
$ kubectl exec -n … --context=… kafka-cluster-kafka-0 -- /opt/kafka/bin/kafka-features.sh --bootstrap-server localhost:9092 upgrade --metadata 3.9
Could not upgrade metadata.version to 21. Invalid update version 21 for feature metadata.version. Controller 5 only supports versions 1-20
1 out of 1 operation(s) failed.
command terminated with exit code 1
$
```

### Strimzi version

0.45.0

### Kubernetes version

1.27.11

### Installation method

Helm

### Infrastructure

Bare-metal
