### ISSUE TITLE
[Bug]: strimziPodSet pod template subdomain is the same for all kafka type brokers

### ISSUE THREAD

**Issue by vagharsh** [strimzi/strimzi-kafka-operator#11067]
### Bug Description

i deployed kafka with the cluster name : `kafka-cluster`
i have enabled jmx metrics, so the port 9404 is open on the kafka brokers aka node pool components
i have created a service to point to that port , i am using datadog to collect metrics from kafka jmx port  but i can't use the following fqdn
`kafka-cluster-broker-0.kafka-cluster-metrics.kafka.svc.cluster.local:9404/metrics` but i am able to use `10-30-21-10..kafka-cluster-metrics.kafka.svc.cluster.local:9404/metrics`.
after checking the pod subdomain i see that `strimziPodSet` sets `subdomain` for all kafka broker pod specs the same value which is `kafka-cluster-kafka-brokers` which i would assume CLUSTER_NAME-kafka-brokers is the template. 

i am not a java developer so basically i did not understand much from the code but i did find this https://github.com/search?q=repo%3Astrimzi%2Fstrimzi-kafka-operator%20subdomain&type=code 
- https://github.com/strimzi/strimzi-kafka-operator/blob/bade7644c4b9563866c8a792cc73d71129883bcf/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/WorkloadUtils.java#L268
- https://github.com/strimzi/strimzi-kafka-operator/blob/bade7644c4b9563866c8a792cc73d71129883bcf/cluster-operator/src/test/java/io/strimzi/operator/cluster/model/KafkaClusterTest.java#L3341

is there a way to use the pod name as subdomain instead of one name for all ? 

### Strimzi version

0.43.0

### Kubernetes version

1.30

### Installation method

Helm chart

### Infrastructure

Amazon EKS

**Comment by scholzj** [comment]
This is intentional, it defines the domain used by all the brokers and is based on the headless service used for all the nodes. Setting it to the pod name does not make any sense IMHO and we definitely do not plan to support that as it would break all other things.

**Comment by vagharsh** [comment]
and if that is not possible .. how can i expose the metrics port to the brokers services along with the 9094 port ? 

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: ${kafka_cluster_name}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: ${kafka_version}
    metadataVersion: ${kafka_metadata_version}
    # The replicas field is required by the Kafka CRD schema while the KafkaNodePools feature gate is in alpha phase.
    # But it will be ignored when Kafka Node Pools are used
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: cluster-ip
        tls: false
        configuration:
          brokers:
            - broker: 0
              advertisedHost: ${kafka_broker0_hostname}
              advertisedPort: 9095
            - broker: 1
              advertisedHost: ${kafka_broker1_hostname}
              advertisedPort: 9096
            - broker: 2
              advertisedHost: ${kafka_broker2_hostname}
              advertisedPort: 9097
```
