### ISSUE TITLE
Add user configuration for suggested maintenance times

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1109]
The user should be able to configure specific times/windows for maintenance operations.
One the these operations is the certificates renewal process.

**Comment by ppatierno** [comment]
The already merged #997 PR defines the following way for maintenance: 

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
  # ...
  zookeeper:
  # ...
  entityOperator:
  # ...
  maintenance:
    windows:
      - <cron expression>
      - <cron expression>
```

If we want to specify different maintenance windows for different operations, this doesn't allow to do that. Today we have just certificates renewal to address but we could have more in the future.
One possible solution is moving these `maintenance` under a specific field related to specific operations. For example, talking about certificates renewal, we have `clusterCa` and `clientsCa` property under which we could move the `maintenance` property in order to describe when operations related to cluster/clients renewal should happen.

```yaml
clusterCa:
  maintenance:
    windows:
      - <cron expression>
      - <cron expression>
```

or just

```yaml
maintenanceWindows:
      - <cron expression>
      - <cron expression>
```

if we don't see use cases where we could need more fields under `maintenance`.
Another solution could be having more fields under the current `maintenance` property, for example:

```yaml
maintenance:
    certificatesRenewal:
      windows:
        - <cron expression>
        - <cron expression>
    anotherOperation:
    # windows
    justAnotherOperation:
    # windows
```

Leaving the current CRD (in the master) we have no way for specifying windows on different operations.

@tombentley @scholzj @stanlyDoge @kyguy any thoughts on that?
