### ISSUE TITLE
[Bug]: Topics with a name containing "_" can't be deleted properly

### ISSUE THREAD

**Issue by zehweh** [strimzi/strimzi-kafka-operator#11113]
### Bug Description

Hello,

when I create a topic with a `topicName` containing a "_", I can't delete it properly.
The `KafkaTopic` is gone after I delete it but the actual topic in the cluster is still there.
When I delete it manually, it reappears.

### Steps to reproduce

1. Create a topic like:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: domain.test-topic
  labels:
    strimzi.io/cluster: astro
spec:
  partitions: 12
  replicas: 3
  topicName: domain.test_topic
  config:
    retention.ms: 7200000
    segment.bytes: 1000000
```

2. Delete topic
`kubectl delete kafkatopics.kafka.strimzi.io domain.test-topic`

3. Check your kafka topics using CLI or UI

### Expected behavior

I expect the topic to be deleted in the cluster after I delete the `KafkaTopic`

### Strimzi version

0.45.0

### Kubernetes version

Kubernetes 1.30

### Installation method

Helm chart

### Infrastructure

Bare-metal
