### ISSUE TITLE
[Enhancement]: Support configuring .spec.subdomain for OpenShift routes

### ISSUE THREAD

**Issue by tim-van-dijkhuizen** [strimzi/strimzi-kafka-operator#11126]
### Related problem

I recently started using Strimzi on OpenShift and configured it to create routes for external access. This worked perfectly fine before but now failed due to the generated routes exceeding the maximum DNS host (part) length of 63 characters.

I've searched the Strimzi docs and code trying to find a work-around (see alternatives) but none really fit my setup.

### Suggested solution

OpenShift Route resources support setting the .spec.subdomain to define the first part of the host.

Example: If you set subdomain for your route to "test123" and the apps domain for your OpenShift cluster is set to "apps.example.com" the generated host would be test123.apps.example.com.

OpenShift Route specs:
https://docs.okd.io/latest/rest_api/network_apis/route-route-openshift-io-v1.html#spec

It would be great if, just like the "host" property, we could configure the "subdomain" property through the listener configuration block inside my Kafka resource spec.

Example spec:
```yaml
# ...
listeners:
  # ...
  - name: external
    port: 9094
    type: route
    tls: true
    authentication:
      type: tls
    configuration:
      bootstrap:
        subdomain: my-kafka
      brokers:
      - broker: 0
        subdomain: my-kafka-0
# ...
```

### Alternatives

1. It's possible to define the host to be used for a listener. This is not an option because I'm not using a custom domain but instead the *.apps.example.com managed by OpenShift. This domain is different for each environment, and I would really like to avoid having to define this domain in my Helm Charts values as it changes every now and then.
2. It's possible to create your own route when using listener type cluster-ip. However, once again, I do not know the full host in advance which makes it impossible to add it as alternative subject and therefor the generated certificate won't work for my custom Route.
3. The spec.kafka.template.externalBootstrapRoute propery could have been the solution, but unfortunately it only allows overriding the labels and annotations of the Route.
4. Obviously, I could reduce the length of my namespace or Kafka resource name. This is not my preferred approach as it requires some big changes, and it doesn't feel like a future-proof solution. My namespace and resources names are not extremely long so future resources might face this issue as well. Ideally, I would like more flexible control over the route configuration.
