### ISSUE TITLE
[Enhancement]: support for k8s Gateway TLSRoute on Kafka listeners

### ISSUE THREAD

**Issue by lgo** [strimzi/strimzi-kafka-operator#11123]
### Related problem

It would be very helpful to have a new `tls-route` listener type which handles all of the templating for the newer Gateway TLSRoutes: https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1alpha2.TLSRoute

I've recently begun to leverage strimzi with a k8s Gateway setup, which vastly simplified a previous setup with nginx (and some hacks to do port-to-broker mappings, in lieu of a TLS passthrough with SNI parsing).

Today, we have this setup with a `cluster-ip` listener with the CRD explicitly listing the `brokers` with the respective `advertisedHost`/`advertisedPort` for each broker.

```yaml
    listeners:
    - configuration:
        bootstrap:
          alternativeNames:
          - bootstrap.kafka.example.com
        brokerCertChainAndKey: ...
        brokers:
        - advertisedHost: b1.kafka.example.com
          advertisedPort: 443
          broker: 1
        ...
      name: externaltls
      port: 9095
      tls: true
      type: cluster-ip
```

In addition, we manually create the `TLSRoute` entries which look like the following:

```yaml
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: kafka-broker-1
  namespace: kafka
spec:
  hostnames:
  - b1.kafka.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: my-gateway
    namespace: ingress
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: cluster-broker-externaltls-1
      namespace: kafka
      port: 9095
```

This is mostly just the broker-specific resources that need creation. There are additional configurations that are general to Gateways and TLSRoutes that are necessary for things to fully work (e.g. which domains they are permitted to attach to, whether to use passthrough or TLS termination on the Gateway, etc.).

Doing the manual management comes with its pitfalls: our tooling needs to effectively track the strimzi results (which nodeIds are assigned) and go and create those resources. We've stumbled around race conditions where adding new brokers (alongside rebalances / topic-partition creation) which have resulted in producer/consumers failing due to those resources (and the `listeners` list of brokers) being correctly managed.

### Suggested solution

Adding a `tls-route` listener type similar to `ingress`, where:
- You can get a free `TLSRoute` for a bootstrap server and each broker
- Allow for parameterization of broker lists or a template (like `ingress`)

I also believe there's benefit in providing some more generic resources with some minimal-level of templating on a Kafka CRD's resource templates. It would have allowed for us to largely create the `TLSRoute` without any specific implementation on strimzi's end (ignoring the listener broker ID listing). I do recognize that's a bit of an ask to do!

I see at least two benefits to more generic resource templates:
1. There doesn't need to be a strimzi implementation for TLSRoute, which is currently marked as an alpha resource and I suspect could vary between k8s deployments in-use
2. Flexibility to support other resources that may be necessary

In fact, we need (2) to effectively deploy our use-case. My current deployment uses Envoy as our k8s Gateway implementation and we require an Envoy-specific CRD to configure each `TLSRoute` appropriately, like so
```
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: kafka-broker-1  # <-- arbitrary name for resource
  namespace: kafka
spec:
  # ... misc Envoy configurations such as for connection limits
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: TLSRoute
    name: kafka-broker-1  # <-- name of the TLSRoute from above
```
