### ISSUE TITLE
[Bug]: Kafka operator does not correctly restart the Kafka pods to apply configuration changes to seven config parameters

### ISSUE THREAD

**Issue by kos-team** [strimzi/strimzi-kafka-operator#11151]
### Bug Description

We found that the Strimzi Kafka operator does not correctly restart the Kafka pods to pick up the configuration change for certain configuration parameters. For example, after changing the `socket.send.buffer.bytes` parameter to `204800`, the operator only updates the ConfigMap, and prints log saying 
```
2025-02-10 22:57:03 INFO  KafkaRoller:744 - Reconciliation #126(watch) Kafka(acto-namespace/test-cluster): Dynamic update of pod test-cluster-dual-role-0/0 was successful.
2025-02-10 22:57:03 INFO  KafkaRoller:744 - Reconciliation #126(watch) Kafka(acto-namespace/test-cluster): Dynamic update of pod test-cluster-dual-role-1/1 was successful.
2025-02-10 22:57:03 INFO  KafkaRoller:744 - Reconciliation #126(watch) Kafka(acto-namespace/test-cluster): Dynamic update of pod test-cluster-dual-role-2/2 was successful.
```

When dumping the config from the Kafka cluster, the config values used by the Kafka do not reflect the changes:
```
$ ./bin/kafka-configs.sh --bootstrap-server 127.0.0.1:9092 --entity-type brokers --entity-name 1 --all --describe

> 
...
socket.send.buffer.bytes=102400 sensitive=false synonyms={DEFAULT_CONFIG:socket.send.buffer.bytes=102400}
...
```

The full list of configuration parameters is:
* controller.quorum.election.backoff.max.ms
* ssl.protocol
* log.flush.interval.ms
* ssl.cipher.suites
* controller.quorum.fetch.timeout.ms
* socket.send.buffer.bytes
* ssl.enabled.protocols

### Steps to reproduce

1. Deploy the Kafka operator, node pool, and the Kafka CR
2. Change the`spec.kafka.config` with `socket.send.buffer.bytes` set as `204800`

### Expected behavior

The Kafka operator should correctly apply the configuration change to the Kafka cluster

### Strimzi version

quay.io/strimzi/operator:0.45.0

### Kubernetes version

v1.28.0

### Installation method

YAML

### Infrastructure

Kind

### Configuration files and logs

1. Initial Kafka CR file
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  name: test-cluster
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    metadataVersion: 3.9-IV0
    version: 3.9.0
```
2. ~~Kafka CR file to change the securityContext~~ Change the`spec.kafka.config` with `socket.send.buffer.bytes` set as `204800`
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  name: test-cluster
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      socket.send.buffer.bytes: 204800
      default.replication.factor: 3
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
    metadataVersion: 3.9-IV0
    version: 3.9.0
```
3. Run `./bin/kafka-configs.sh --bootstrap-server 127.0.0.1:9092 --entity-type brokers --entity-name 1 --all --describe` to get the currently used config
