### ISSUE TITLE
[Bug]: brokersService includes controller pods

### ISSUE THREAD

**Issue by Compunctus** [strimzi/strimzi-kafka-operator#11183]
### Bug Description

In a cluster with two node pools (first one - broker-only, second one - controller-only) - generated brokersService includes controller-only pods for port 9092. Controller-only pods do not listen on 9092, so connections made to brokersService on port 9092 fail sporadically.

### Steps to reproduce

1. Deploy all 3 provided resources
2. Run `kubectl describe svc internal-bus-kafka-brokers`
3. Observe controller pods being included in service's endpointSlice.

### Expected behavior

I expected brokersService to use `strimzi.io/broker-role: true` in it's selector, and not include controller-only pods in service's endpoint.

### Strimzi version

0.45.0

### Kubernetes version

1.29.10

### Installation method

Helm chart

### Infrastructure

Bare-metal

### Configuration files and logs

Kafkas CRD:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    strimzi.io/kraft: enabled
    strimzi.io/node-pools: enabled
  name: internal-bus
spec:
  kafka:
    listeners:
    - configuration:
        useServiceDnsDomain: true
      name: plain
      port: 9092
      tls: false
      type: internal
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 2Gi
    version: 3.9.0
```

KafkaNodePool - brokers CRD:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  labels:
    strimzi.io/cluster: internal-bus
  name: brokers
spec:
  replicas: 3
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  roles:
  - broker
  storage:
    class: ceph-csi-rbd
    deleteClaim: false
    size: 5Gi
    type: persistent-claim
```

KafkaNodePool - controllers CRD:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  labels:
    strimzi.io/cluster: internal-bus
  name: controllers
spec:
  replicas: 3
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 100m
      memory: 2Gi
  roles:
  - controller
  storage:
    class: ceph-csi-rbd
    deleteClaim: false
    size: 5Gi
    type: persistent-claim
```
