### ISSUE TITLE
Can we change the time zone of kafka cluster?

### ISSUE THREAD

**Issue by Mikedu1988** [strimzi/strimzi-kafka-operator#1122]
Can we change the log time zone to GMT+08？
We are tring to build a centralizing log center, the difference in tome zone is painful.

![image](https://user-images.githubusercontent.com/24424690/49195722-3cdba500-f3c3-11e8-8d54-d846a1228847.png)

**Comment by scholzj** [comment]
Just FYI: Since 0.14.0 you should be able to use the environment variables to do that:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    listeners:
      tls: {}
      plain: {}
    replicas: 3
    storage:
      type: ephemeral
    template:
      kafkaContainer:
        env:
        - name: TZ
          value: Europe/Prague
      tlsSidecarContainer:
        env:
        - name: TZ
          value: Europe/Prague
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
    template:
      tlsSidecarContainer:
        env:
        - name: TZ
          value: Europe/Prague
      zookeeperContainer:
        env:
        - name: TZ
          value: Europe/Prague
  entityOperator:
    template:
      tlsSidecarContainer:
        env:
        - name: TZ
          value: Europe/Prague
      topicOperatorContainer:
        env:
        - name: TZ
          value: Europe/Prague
      userOperatorEnvironment:
        env:
        - name: TZ
          value: Europe/Prague
    topicOperator: {}
    userOperator: {}
```
