### ISSUE TITLE
[Bug]: Cannot start on IPv6 only k8s cluster

### ISSUE THREAD

**Issue by darwin67** [strimzi/strimzi-kafka-operator#11246]
### Bug Description

When attempt to deploy Kafka (kraft based) via Strimzi on an IPv6 only k8s cluster, neither the controller or broker can start due to controller not binding itself to ipv6.

This is the output when running `netstat` within the controller pods.
```
sh-5.1$ netstat -lnt
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp        0      0 0.0.0.0:8443            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:9999            0.0.0.0:*               LISTEN
tcp        0      0 0.0.0.0:34531           0.0.0.0:*               LISTEN
```

Which seems to be hardcoded here.
https://github.com/strimzi/strimzi-kafka-operator/blob/a5a774763434ef4d0a1f608e895d9612c66712ce/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaBrokerConfigurationBuilder.java#L233

Setting the following on `brokersService` and `bootStrapService` also seem to have no effect, which is kinda understandable since it's hard to tell the correlation between those and the kraft controller.
```
ipFamilyPolicy: SingleStack
ipFamilies: [IPv6]
```

And here's the output of the resources.
```
NAME                                        DESIRED REPLICAS   ROLES            NODEIDS
kafkanodepool.kafka.strimzi.io/broker       3                  ["broker"]       [0,1,2]
kafkanodepool.kafka.strimzi.io/controller   3                  ["controller"]   [3,4,5]

NAME                           TYPE        CLUSTER-IP                  EXTERNAL-IP   PORT(S)                                        AGE
service/kafka-console          ClusterIP   2607:e3c0:a040:f100::90bf   <none>        8080/TCP                                       2d17h
service/main-kafka-bootstrap   ClusterIP   2607:e3c0:a040:f100::1558   <none>        9091/TCP,9092/TCP                              41m
service/main-kafka-brokers     ClusterIP   None                        <none>        9090/TCP,9091/TCP,8443/TCP,9092/TCP,9999/TCP   41m

NAME                    READY   STATUS             RESTARTS        AGE
pod/main-broker-0       0/1     CrashLoopBackOff   12 (109s ago)   41m
pod/main-broker-1       0/1     CrashLoopBackOff   12 (95s ago)    41m
pod/main-broker-2       0/1     CrashLoopBackOff   12 (107s ago)   41m
pod/main-controller-3   1/1     Running            0               41m
pod/main-controller-4   1/1     Running            0               41m
pod/main-controller-5   1/1     Running            0               41m

NAME                          DESIRED KAFKA REPLICAS   DESIRED ZK REPLICAS   READY   METADATA STATE   WARNINGS
kafka.kafka.strimzi.io/main                                                                           True
```

### NOTE

The error will actually surface as
```
2025-03-10 17:13:53,505 WARN [RaftManager id=3] Error connecting to node main-controller-5.main-kafka-brokers.kafka-main.svc.cluster.local:9090 (id: 5 rack: null) (org.apache.kafka.clients.NetworkClient) [kafka-3-raft-outbound-request-thread]
java.net.UnknownHostException: main-controller-5.main-kafka-brokers.kafka-main.svc.cluster.local
```
Which looks like a DNS resolution error, but DNS can be resolved to an IPv6 address, and pods are also reachable via the network.

### Steps to reproduce

1. Setup IPv6 only k8s
2. Deploy Strimzi
3. Deploy Kafka with controller and broker nodepools
4. Cluster won't come up

### Expected behavior

Cluster to come up and is healthy

### Strimzi version

0.45.0

### Kubernetes version

Kubernetes 1.31

### Installation method

Helm

### Infrastructure

Bare-Metal

### Configuration files and logs

Helm

```yaml
watchAnyNamespace: true

defaultImageTag: 0.45.0

rbac:
  create: yes

leaderElection:
  enable: true

podDisruptionBudge:
  enabled: false

createGlobalResources: true
createAggregateRoles: false
generateNetworkPolicy: true
connectBuildTimeoutMs: 300000
generatePodDisruptionBudget: true

dashboards:
  enabled: true
```

Custom resources

```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# prefix: kafka
# cluster name: main
namespace: kafka-main

commonLabels:
  strimzi.io/cluster: main

resources:
  - controller-nodepool.yaml
  - broker-nodepool.yaml
  - kafka.yaml
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: controller
spec:
  replicas: 3
  roles:
    - controller
  resources:
    limits:
      memory: 8Gi
    requests:
      cpu: 5
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 182Gi
        kraftMetadata: shared
        class: disks
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
spec:
  replicas: 3
  roles:
    - broker
  template:
    pod:
      metadata:
        labels:
          sys: kafka
          cluster: main
  resources:
    limits:
      memory: 35Gi
    requests:
      cpu: 10
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1758Gi # 1.7TB
        kraftMetadata: shared
        class: disks
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: main
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.9.0
    metadataVersion: 3.9-IV0
    rack:
      topologyKey: kubernetes.io/hostname
    jmxOptions: {}
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
      superUsers:
        - admin
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 1
      # inter.broker.protocol.version: "3.9"
    template:
      bootstrapService:
        ipFamilyPolicy: SingleStack
        ipFamilies: [IPv6]
      brokersService:
        ipFamilyPolicy: SingleStack
        ipFamilies: [IPv6]
  entityOperator:
    # TODO: setup logging to external system, GCP
    topicOperator: {}
    userOperator: {}
  # use default settings for cruise control
  cruiseControl: {}
```

### Additional context

We have a test account for AWS where we tested Strimzi initially and didn't encountered any issues, likely due to AWS VPCs always have IPv4 addresses.

But in our on-prem system, we don't assign any IPv4 addresses internally, and only uses IPv6, so this issue surfaced when we're trying to deploy Kafka in our on-prem cluster.
