### ISSUE TITLE
[Bug]: Mirrormaker2 <source-cluster-name>.checkpoints.internal topic empty

### ISSUE THREAD

**Issue by GBHU753** [strimzi/strimzi-kafka-operator#11241]
### Bug Description

The `<source-cluster-name>.checkpoints.internal` in the target cluster is empty, however `mm2-offset-sync.<target-cluster-name>.internal` in the source cluster has messages in it. I'm little confused why this is happening as I thought the checkpoint connector reads from `mm2-offset-syncs.<target-cluster>.internal` topic, performs consumer groups offsets translation, and writes translation information to the `<source-cluster>.checkpoints.internal topic`.

I don't see any errors in the pod's log for the checkpoint connector, any help would be appreciated.

### Strimzi version

0.45.0

### Kubernetes version

Openshift 4.15

### Installation method

OperatorHub

### Configuration files and logs

```
kind: KafkaMirrorMaker2
apiVersion: kafka.strimzi.io/v1beta2
metadata: 
  name: svl-prod
  labels:
    helm.sh/chart: svl-event-streams-1.1.0
    app.kubernetes.io/name: svl-event-streams
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.5.1"
    app.kubernetes.io/managed-by: Helm
    strimzi.io/cluster: svl
spec:
  replicas: 1
  clusters:
    - alias: svl
      bootstrapServers: svl-kafka-bootstrap.svl-prod.svc:9092
    - alias: confluent
      bootstrapServers: Redacted
      authentication:
        type: plain
        username: Redacted
        passwordSecret:
          secretName: confluent-prod
          password: password
      tls:
        trustedCertificates:
          []
      config:
        config.storage.replication.factor: -1
        offset.storage.replication.factor: -1
        status.storage.replication.factor: -1
        config.storage.topic: svl-mirrormaker2-cluster-configs
        offset.storage.topic: svl-mirrormaker2-cluster-offsets
        status.storage.topic: svl-mirrormaker2-cluster-status
        replication.policy.internal.topic.separator.enabled: true
        replication.policy.separator: "-"
        sync.topic.acls.enabled: false
        errors.log.enable: true
        errors.log.include.messages: true
  mirrors:
    - sourceCluster: svl
      targetCluster: confluent
      sourceConnector:
        tasksMax: 12 
        config:
          replication.policy.internal.topic.separator.enabled: true
          replication.policy.separator: "-"
          replication.factor: -1
          offset-syncs.topic.replication.factor: -1
          offsets.storage.topic: svl-mirrormaker2-cluster-offsets
          sync.topic.acls.enabled: false
          refresh.topics.enabled: true
          sync.topic.configs.enabled: true
          errors.log.enable: true
          errors.log.include.messages: true
      checkpointConnector:
        tasksMax: 3
        config:
          replication.policy.internal.topic.separator.enabled: true
          replication.policy.separator: "-"
          checkpoint.topic.replication.factor: -1
          offsets.storage.topic: svl-mirrormaker2-cluster-offsets
          sync.topic.acls.enabled: false
          errors.log.enable: true
          errors.log.include.messages: true
      topicsPattern: observations.v1
      groupsPattern: .*
  connectCluster: confluent
  version: 3.9.0
```
