### ISSUE TITLE
[Bug]: KafkaConnect strimzi resource doesn't work in 0.46.0

### ISSUE THREAD

**Issue by dancb10** [strimzi/strimzi-kafka-operator#11488]
### Bug Description

I have configured the strimzi operator and the crds for version 0.46, deployed Kafka and now trying to deploy KafkaConnect as follows 
```
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: scylla-to-elasticsearch
  namespace: kafka
  annotations:
  # use-connector-resources configures this KafkaConnect
  # to use KafkaConnector resources to avoid
  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.0.0
  replicas: 1
  image: localhost:32000/kafka-connect:1.0.3
  bootstrapServers: scylla-kafka-elasticsearch-kafka-bootstrap:9093
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 4Gi
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "INFO"
      log4j.logger.io.debezium: "DEBUG"
      log4j.logger.io.debezium.connector.base.ChangeEventQueue: "INFO"
      log4j.logger.org.apache.kafka.clients.NetworkClient: "WARN"
      log4j.logger.org.apache.kafka.connect.runtime.rest.RestServer: "WARN"
  template:
    connectContainer:
      env:
        - name: JAVA_TOOL_OPTIONS
          value: "-Dlog4j.configuration=file:/opt/kafka/custom-config/log4j.properties"

```

But no matter what I've tried, the bootstrap servers is not populated and the container crashes because of missing log4j configuration:
Starting Kafka Connect with configuration:
# Bootstrap servers
bootstrap.servers=
# REST Listeners
rest.port=8083
rest.advertised.host.name=scylla-to-elasticsearch-connect-0.scylla-to-elasticsearch-connect.kafka.svc
rest.advertised.port=8083
# Plugins
plugin.path=/opt/kafka/plugins
# Provided configuration

security.protocol=PLAINTEXT
producer.security.protocol=PLAINTEXT
consumer.security.protocol=PLAINTEXT
admin.security.protocol=PLAINTEXT

# Additional configuration
consumer.client.rack=

Configuring Java heap: -Xms3221225472 -Xmx3221225472
+ exec /usr/bin/tini -w -e 143 -- /opt/kafka/bin/connect-distributed.sh /tmp/strimzi-connect.properties
Picked up JAVA_TOOL_OPTIONS: -Dlog4j.configuration=file:/opt/kafka/custom-config/log4j.properties
log4j:ERROR Could not read configuration file from URL [file:/opt/kafka/custom-config/log4j.properties].
java.io.FileNotFoundException: /opt/kafka/custom-config/log4j.properties (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:111)
	at java.base/sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:86)
	at java.base/sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:189)
	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:532)
	at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:485)
	at org.apache.log4j.LogManager.<clinit>(LogManager.java:115)
	at org.slf4j.impl.Reload4jLoggerFactory.<init>(Reload4jLoggerFactory.java:67)
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:72)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:45)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
	at org.apache.kafka.connect.cli.AbstractConnectCli.<clinit>(AbstractConnectCli.java:46)
log4j:ERROR Ignoring configuration file [file:/opt/kafka/custom-config/log4j.properties].
log4j:WARN No appenders could be found for logger (org.apache.kafka.connect.cli.AbstractConnectCli).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

### Strimzi version

0.46.0

### Kubernetes version

v1.33.1

### Installation method

Helm

### Infrastructure

Bare-metal
