### ISSUE TITLE
Operator does not restart kafka controllers after tiered storage is enabled, preventing data offload into S3 bucket

### ISSUE THREAD

**Issue by totochichi** [strimzi/strimzi-kafka-operator#11584]
Hello all, we are using custom image with tiered storage plugin with the below config (Operator version 0.45 and Kafka 3.8.0)
We also have MirrorMaker2 installed in this namespace.
After helmchart deployment, kafka brokers restart and we are able to create topic with remote storage enabled, but the topics data are not being sent to S3 bucket.

```yaml
 kafka:
      authorization:
        superUsers:
        ...
        type: simple
      config:
        auto.create.topics.enable: false
        default.replication.factor: 3
        log.retention.hours: 24
        min.insync.replicas: 2
        num.io.threads: 8
        num.network.threads: 3
        num.recovery.threads.per.data.dir: 1
        num.replica.fetchers: 1
        offsets.topic.replication.factor: 3
        principal.builder.class: cz.scholz.customprincipalbuilder.CustomPrincipalBuilder
        remote.log.manager.task.interval.ms: 30000
        remote.log.manager.thread.pool.size: 4
        remote.log.reader.threads: 5
        remote.log.storage.system.enable: true
        rsm.config.chunk.size: 4194304
        rsm.config.compression.enabled: true
        rsm.config.compression.heuristic.enabled: true
        rsm.config.storage.backend.class: io.aiven.kafka.tieredstorage.storage.s3.S3Storage
        rsm.config.storage.s3.bucket.name: bucket-kafka-example
        rsm.config.storage.s3.region: us-east-1
        rsm.config.upload.rate.limit.bytes.per.second: 104857600
        transaction.state.log.min.isr: 2
        transaction.state.log.replication.factor: 3
      image: strimzi-image/kafka:0.45.0-kafka-3.8.0-77
     tieredStorage:
        remoteStorageManager:
          className: io.aiven.kafka.tieredstorage.RemoteStorageManager
          classPath: /opt/kafka/plugins/tiered-storage-for-apache-kafka/core/*:/opt/kafka/plugins/tiered-storage-for-apache-kafka/s3/*
          config:
            aws.credentials.provider.class: software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider
            remote.log.metadata.manager.impl.prefix: rlmm.config.
            remote.log.storage.manager.impl.prefix: rsm.config.
        type: custom
      version: 3.8.0
```

Upon checking controller logs, we see the error below. If we delete the controllers and let them restart, then the errors disappear and data sent to S3 successfully. Do we know why this happens? Should the Operator restart Controllers as well if the cert or ACLs needs to be refreshed?

``` log
ERROR [ControllerApis nodeId=3] Unexpected error handling request
Forwarded request:
  RequestContext(
    header=RequestHeader(
      apiKey=ENVELOPE,
      apiVersion=0,
      clientId=2,
      correlationId=15,
      headerVersion=2
    ),
    connectionId='IP_A:PORT-TO-IP_B:PORT',
    clientAddress=/IP_B,
    principal=User:CN=kafka-kafka,O=ORG_PLACEHOLDER,
    listenerName=ListenerName(CONTROLPLANE-9090),
    securityProtocol=SSL,
    clientInformation=ClientInformation(
      softwareName=apache-kafka-java,
      softwareVersion=3.8.0
    ),
    fromPrivilegedListener=false,
    principalSerde=Optional[cz.scholz.customprincipalbuilder.CustomPrincipalBuilder@MASKED]
  )
  RequestHeader(
    apiKey=CREATE_ACLS,
    apiVersion=3,
    clientId=sourceCluster->targetCluster|sourceCluster->targetCluster.MirrorSourceConnector|replication-target-admin,
    correlationId=104,
    headerVersion=2
  )
  – CreateAclsRequestData(
      creations=[
        AclCreation(resourceType=2, resourceName='sourceCluster.heartbeats', resourcePatternType=3, principal='User:MASKED', host='*', operation=5, permissionType=3),
        ...
      ]
    )
  with context RequestContext(
    header=RequestHeader(
      apiKey=CREATE_ACLS,
      apiVersion=3,
      clientId=sourceCluster->targetCluster|sourceCluster->targetCluster.MirrorSourceConnector|replication-target-admin,
      correlationId=104,
      headerVersion=2
    ),
    connectionId='IP_A:PORT-TO-IP_C:PORT',
    clientAddress=/IP_C,
    principal=User:MASKED,
    listenerName=ListenerName(CONTROLPLANE-9090),
    securityProtocol=SSL,
    clientInformation=ClientInformation(
      softwareName=unknown,
      softwareVersion=unknown
    ),
    fromPrivilegedListener=false,
    principalSerde=Optional.empty
  )
  (kafka.server.ControllerApis) [data-plane-kafka-request-handler-4]

org.apache.kafka.common.errors.ClusterAuthorizationException:
  Request Request(
    processor=0,
    connectionId=IP_A:PORT-TO-IP_B:PORT,
    session=org.apache.kafka.network.Session@MASKED,
    listenerName=ListenerName(CONTROLPLANE-9090),
    securityProtocol=SSL,
    buffer=java.nio.HeapByteBuffer[pos=MASKED lim=MASKED cap=MASKED],
    envelope=Some(
      Request(
        processor=0,
        connectionId=IP_A:PORT-TO-IP_B:PORT,
        session=org.apache.kafka.network.Session@MASKED,
        listenerName=ListenerName(CONTROLPLANE-9090),
        securityProtocol=SSL,
        buffer=java.nio.HeapByteBuffer[pos=MASKED lim=MASKED cap=MASKED],
        envelope=None
      )
    )
```
