### ISSUE TITLE
Environment var for init container image?

### ISSUE THREAD

**Issue by tomcooperca** [strimzi/strimzi-kafka-operator#1165]
We use a couple different k8s clusters internally. We also use an internal mirror for Docker Hub images via JFrog Artifactory. This works fine for strimzi images because of the environment variables exposed via the cluster operator. However, the `busybox` initContainer is using a local image ref. It would be helpful to have that field exposed via cluster operator so that it can be fully used in an air-gapped environment (behind corporate proxies) where a user can specific something like this via the cluster operator:

```
    spec:
      serviceAccountName: strimzi-cluster-operator
      containers:
      - name: strimzi-cluster-operator
        image: docker.artifactory.example.com/strimzi/cluster-operator:0.9.0-rc1
        imagePullPolicy: IfNotPresent
        env:
        - name: STRIMZI_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
...
        - name: STRIMZI_DEFAULT_BUSYBOX_IMAGE
          value: docker.artifactory.example.com/busybox
```

I'm very new to using this project so my apologies if this isn't the correct place to file a feature request!
