### ISSUE TITLE
Broker services are not creating internal load balancers (missing annotations)

### ISSUE THREAD

**Issue by lostick** [strimzi/strimzi-kafka-operator#1364]
Kafka broker services are creating external load balancers while the `kafka-external-bootstrap` service is creating an internal one (as expected).

How can we inject annotations in each `kafka-kafka-*` broker service to force load balancers to be internals?

```
$ kubectl -n kafka get svc
NAME                             TYPE           CLUSTER-IP       EXTERNAL-IP
kafka-kafka-0                    LoadBalancer   10.100.76.65     xxxxxx.xxxx.eu-west-2.elb.amazonaws.com
kafka-kafka-1                    LoadBalancer   10.100.48.69     xxxxxx.xxxx.eu-west-2.elb.amazonaws.com
kafka-kafka-2                    LoadBalancer   10.100.176.191   xxxxxx.xxxx.eu-west-2.elb.amazonaws.com
kafka-kafka-bootstrap            ClusterIP      10.100.113.186   <none>
kafka-kafka-brokers              ClusterIP      None             <none>
kafka-kafka-external-bootstrap   LoadBalancer   10.100.21.38     internal-xxxxxx.xxxx.eu-west-2.elb.amazonaws.com
```

```
$ kubectl -n kafka get kafka kafka -o yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
spec:
  kafka:
    version: 2.1.0
    listeners:
      external:
        type: loadbalancer
    ...
    template:
      externalBootstrapService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      brokersService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```

```
$ kubectl -n kafka get svc kafka-kafka-external-bootstrap -o=json | jq -r '[.metadata.annotations]'
[
  {
    "service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled": "true",
    "service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout": "60",
    "service.beta.kubernetes.io/aws-load-balancer-internal": "0.0.0.0/0"
  }
]

$ kubectl -n kafka get svc kafka-kafka-0 -o=json | jq -r '[.metadata.annotations]'
[
  null
]
```

**Comment by scholzj** [comment]
The `brokersService` which you use in your configuration is for configuring the headless service names `<cluster-name>-kafka-brokers`. To configure the per pod services which create the other loadbalancers you should use the key `perPodService`. I.e.:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
spec:
  kafka:
    version: 2.1.0
    listeners:
      external:
        type: loadbalancer
    #...
    template:
      #...
      perPodService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
            service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
            service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
```
