### ISSUE TITLE
Add Kafka, zookeeper logs in JSON format

### ISSUE THREAD

**Issue by val1715** [strimzi/strimzi-kafka-operator#1378]
**Is there possible way to configure logs output as true json format for kafka and zookeeper ?**
May be i just have not found it but now i don't see that it is possible for strimzi operator. 

Now it looks like:
```
2019-02-26 13:03:52,302 [custom field] INFO Initiating client connection, connectString=localhost:2181 sessionTimeout=6000 watcher=kafka.zookeeper.ZooKeeperClient$ZooKeeperClientWatcher$@397fbdb (org.apache.zookeeper.ZooKeeper) [main]
```
But it is kubernetes, digital world. I will store logs at elasticsearch and want to configure further processing. At least i got it like:
```
{"level":"INFO","logger":"kafka.coordinator.group.GroupMetadataManager","message":"[GroupMetadataManager brokerId=2] Removed 0 expired offsets in 4 milliseconds.","host":"kafka-cluster-kafka-2.kafka-cluster-kafka-brokers.my_namespace.svc.cluster.local","@timestamp":"2019-02-26T13:42:47.541Z","thread":"group-metadata-manager-0","@version":"1"}
```
or
```
{"level":"INFO","logger":"org.apache.zookeeper.server.NIOServerCnxn","message":"Closed socket connection for client \/127.0.0.1:51756 (no session established for client)","mdc":{"myid":"3"},"host":"kafka-cluster-zookeeper-2.kafka-cluster-zookeeper-nodes.my_namespace.svc.cluster.local","@timestamp":"2019-02-26T09:55:10.134Z","thread":"Thread-13260","@version":"1"}
```
  - pay attention to extra backslash for escaping to keep JSON format. It is not possible by PatternLayout.

---

**Is it possible to add JSON log output for kafka/zookeeper natively by operator config?**

---

Actually, 
For my purpose i create custom docker image over existing with Dockerfile:
```
FROM strimzi/kafka:0.10.0-kafka-2.0.1
COPY files/ /opt/kafka/libs
CMD ["/opt/kafka/kafka_run.sh"]
```
At `files` folder i placed builded `log4j-json-layout-szhem-1.0.0.jar` from this repository > https://github.com/szhem/log4j-json-layout
I met problems and errors using official logstash repo - https://github.com/logstash/log4j-jsonevent-layout

And i added custom config to my pods:
kafka:
```
spec:
  kafka:
    template:
    image: 
    ...
    logging:
      type: external
      name: kafka-config-properties
```
configmap:
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: mynamespace
  name: kafka-config-properties
data:
  log4j.properties: |
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
    log4j.appender.CONSOLE.layout=com.github.szhem.logstash.log4j.LogStashJsonLayout

```
