### ISSUE TITLE
An error during deploying Kafka cluster in another namespace than CO

### ISSUE THREAD

**Issue by serrss** [strimzi/strimzi-kafka-operator#1442]
An error occurs when deploying Kafka cluster in another namespace than CO. Error message in CO log `io.vertx.core.impl.NoStackTraceThrowable: Given namespace second-namespace incompatible with desired namespace third-namespace`

Pre-conditions
1. Namespaces were created: `first-namespace`, `second-namespace`, `third-namespace` 
2. ClusterRoleBindings were created that grant cluster-wide access to all OpenShift projects 
3. CO was deployed in namespace `first-namespace` to watch all namespaces
```
         - name: STRIMZI_NAMESPACE
          value: "*"
```
Steps to reproduce: 
1. Deploy Kafka cluster in namespace `third-namespace` with custom configuration for TO and UO
```
  entityOperator:
    topicOperator:
      watchedNamespace: second-namespace
    userOperator:
      watchedNamespace: second-namespace
```
Actual result: Kafka cluster was deployed without EO and CO has an error in logs `io.vertx.core.impl.NoStackTraceThrowable: Given namespace second-namespace incompatible with desired namespace third-namespace`
Expected results:
EO should be deployed in `third-namespace` and Co should not contain error in log
