### ISSUE TITLE
Access kafka from outside of k8s cluster on docker-for-desktop on windows

### ISSUE THREAD

**Issue by Ulf-H** [strimzi/strimzi-kafka-operator#1463]
I have issues with connecting to Kafka from a client outside k8s. I realize it is the same problem as discussed in issue #1156, but since thats closed I opened a new one.
I'm running Docker-Kubernetes-Kafka on windows locally on my laptop. I want to connect to Kafka from Intellij while debugging my application. I have configured an external listener and have the services
```
$ kubectl get svc -n kafka
NAME                                TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
nn-kafka-kafka-0                    NodePort    10.101.178.74    <none>        9094:32668/TCP               2h
nn-kafka-kafka-1                    NodePort    10.110.90.229    <none>        9094:32436/TCP               2h
nn-kafka-kafka-bootstrap            ClusterIP   10.111.242.124   <none>        9091/TCP,9093/TCP            2h
nn-kafka-kafka-brokers              ClusterIP   None             <none>        9091/TCP,9093/TCP            2h
nn-kafka-kafka-external-bootstrap   NodePort    10.108.88.10     <none>        9094:32059/TCP               2h
nn-kafka-zookeeper-client           ClusterIP   10.109.82.42     <none>        2181/TCP                     2h
nn-kafka-zookeeper-nodes            ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   2h
```
I get the IP through
```
$ kubectl get node docker-for-desktop -o=jsonpath='{range .status.addresses[*]}{.type}{"\t"}{.address}{"\n"}'
InternalIP      192.168.65.3
Hostname        docker-for-desktop
```
However, the node is not available on the InternalIP or Hostname outside kubernetes. Outside kubernetes the node is available on localhost or my DockerNAT interface IP 10.0.75.1. So when I connect to Kafka I use 10.0.75.1 and the nodeport of the external bootstrap service, e.g. 10.0.75.1:32059 and voila it works!

But after approx 30 sec I start getting
```
2019-03-20 15:49:02.417  WARN 12056 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node 0 (/192.168.65.3:32668) could not be established. Broker may not be available.
2019-03-20 15:49:23.422  WARN 12056 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node 1 (/192.168.65.3:32436) could not be established. Broker may not be available.
2019-03-20 15:49:23.468  WARN 12056 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node 0 (/192.168.65.3:32668) could not be established. Broker may not be available.
2019-03-20 15:49:44.530  WARN 12056 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node 1 (/192.168.65.3:32436) could not be established. Broker may not be available.
```
The Kafka Controller process periodically fetches a list of all alive brokers in the Kafka cluster and sends that information back to the client. My conclusion is that the list of alive brokers is showing the IP of the kafka brokers inside k8s while my kafka client running outsde k8s. The outside IP should be 10.0.75.1 and not 192.168.65.3 which is the inside IP. 

Is there a way to make kafka returning the outside IP to my Kafka client?

**Comment by scholzj** [comment]
You will have to manually override the listener configuration and set the IP address as the advertised host manually. Unfortunately there is a bug in 0.11.1, so you will also need to specify a node ports :-(. So you have to do something like this:

```yaml
# ...
listeners:
  external:
    type: nodeport
    # ...
    overrides:
      brokers:
      - broker: 0
        nodePort: 32000
        advertisedHost: 10.0.75.1
      - broker: 1
        nodePort: 32001
        advertisedHost: 10.0.75.1
      - broker: 2
        nodePort: 32002
        advertisedHost: 10.0.75.1
# ...
```

Hope this helps.

**Comment by Ulf-H** [comment]
Great, works like a charm. I ended up configuring
```yaml
    listeners:
      tls:
        authentication:
          type: tls
      external:
        type: nodeport
        tls: false
        overrides:
          bootstrap:
            nodePort: 32100
          brokers:
          - broker: 0
            nodePort: 32000
            advertisedHost: localhost
          - broker: 1
            nodePort: 32001
            advertisedHost: localhost
```
And then connecting to localhost:32100 in my Kafka Client outside k8s.

**Comment by haf** [comment]
What's the current solution? Is the bug that requires specifying node ports fixed?

**Comment by scholzj** [comment]
The bug from Strimzi 0.11.1 is for sure fixed.

**Comment by haf** [comment]
So using a nodeport and manually indexing the brokers is the way to go?

**Comment by scholzj** [comment]
To be honest I don't know how much Docker Kubernetes evolved during the year and a half since I'm not using it and never was. The only reason why the whole `override` section was needed was because (at least in this case) the Docker Kubernetes were reporting another node address then under which it was available. That might not be the case anymore or maybe it was the case of the user who raised this issue only.

The actual Strimzi bug which is long since fixed was that when you specified the `advertisedHost` you had to also specify the `nodePort` otherwise you got `NullPointerException`. That was fixed in 0.11.2.

**Comment by haf** [comment]
It just needs to match the hostname that the client uses to connect. Then the question is; do we load-balance through a `kind: Service` using `NodePort`, or should I configure the L7 HTTPS ingress to route to the main boostrap server's service name?

**Comment by scholzj** [comment]
When you deploy a cluster with N Kafka nodes, you will get N+1 services: there will be one service for each broker which let the Kafka clients access each of the broker individually (so this would e N services in total). And then there will be one more service called _...-bootstrap_ which will load balance between all brokers for the initial connection. This is what should be configured in the clients.

Using Ingress is a bit more complicated - Kafka is a TCP protocol - so using HTTPS L7 ingress does not help sicne it would not understand the Kafka protocol.

All the supported mechanisms for accessing KAfka are described here in more details: https://strimzi.io/blog/2019/04/17/accessing-kafka-part-1/

**Comment by haf** [comment]
Ok, here's what happens:

It would seem the overrides section doesn't bite:

```
$ kubectl get svc
ingress-broker-kafka-0                    NodePort    10.109.243.85    <none>        9094:30310/TCP                        13s
ingress-broker-kafka-bootstrap            ClusterIP   10.101.76.226    <none>        9091/TCP,9092/TCP,9093/TCP,9404/TCP   13s
ingress-broker-kafka-brokers              ClusterIP   None             <none>        9091/TCP,9092/TCP,9093/TCP            13s
ingress-broker-kafka-external-bootstrap   NodePort    10.96.96.79      <none>        9094:30122/TCP                        13
```

with this config:

```
spec:
  kafka:
    replicas: 1

    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false

      overrides:
        bootstrap:
          nodePort: 30094
        brokers:
        - broker: 0
          advertisedHost: kafka.test
          advertisedPort: 32094
          nodePort: 32094
```

**Comment by scholzj** [comment]
You have the YAML aligned incorrectly. The should be like this:

```yaml
spec:
  kafka:
    replicas: 1

    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false
        overrides:
          bootstrap:
            nodePort: 30094
          brokers:
          - broker: 0
            advertisedHost: kafka.test
            advertisedPort: 32094
            nodePort: 32094
```
