### ISSUE TITLE
Adding additional pod annotations doesn't restart pods

### ISSUE THREAD

**Issue by joekohlsdorf** [strimzi/strimzi-kafka-operator#1472]
I have added some additional annotations to my already deployed Kafka and Zookeeper pods like documented:
```
template:
    pod:
        metadata:
            annotations:
                annotation1: value1
```

I would expect that the operator does a rolling update to ensure that these annotations are set, instead I had to manually restart the pods to rollout the annotations to the pods.

Maybe the problem is that these annotations should really be in the pod template of the statefulset so that a change to this would trigger all pods to restart but there seems to be no way to configure this.

**Comment by scholzj** [comment]
I agree that this should work and trigger rolling update. What version of Strimzi are you using? Could you change the logging level in the cluster operator to DEBUG (there is an environment variable for that in the CO deployment) and share the log?

**Comment by joekohlsdorf** [comment]
I'm running version 0.11.1 of the operator.
Attached is debug log off adding the following annotation:

```
template:
    pod:
        metadata:
            annotations:
                test: "value"
```
[strimzi.log](https://github.com/strimzi/strimzi-kafka-operator/files/3005779/strimzi.log)
