### ISSUE TITLE
allow configuration of health check for livenessProbe 

### ISSUE THREAD

**Issue by jslusher** [strimzi/strimzi-kafka-operator#1479]
Reading through the documentation and I'm either misunderstanding it or I'm not configuring the parameters properly. 

I have a debezium-mysql plugin I'm using on my kafkaconnect deployment. If the mysql server gets restarted or otherwise becomes unavailable, the connect pod throws an exception and stops, waiting to be restarted manually. I need to be able to configure a livenessProbe for the connect deployment I made that will kill the pod if this happens. 

I have this in the CRD but it doesn't seem to be reaching the Deployment: https://gist.github.com/jslusher/0f8a8979a844875830d2a0e1cf250595#file-kafka-connect-yaml-L16-L24

I was under the impression based on the wording and the link (the example doesn't show an alternate probe configuration) that configuring a custom check was possible. https://strimzi.io/docs/latest/#proc-configuring-healthchecks-deployment-configuration-kafka

Is it just the parameters listed there that are configurable then?

If so, does that mean I'm out of luck if I want a custom health check?

**Comment by tombentley** [comment]
We don't support custom health checks for connectors in a kafka connect deployment. The health check for the deployment are based on the connect REST endpoint, rather than individual connectors deployed within it. 

However what you're trying to does makes sense, so we should try to support this use case somehow.

> Is it just the parameters listed there that are configurable then?

Right

**Comment by scholzj** [comment]
> However what you're trying to does makes sense, so we should try to support this use case somehow.

TBH, I don't think it does. You cannot bind the pod health to any particular connector. There might be many tasks of manny connectors running on the same pod and you cannot restart it just because of a single connector / task failing. So I think the health-checks are correct in not including the connectors.

There is for sure space for additional tooling to monitor / restart the connectors (such as #1468 ). But it is not the health-check where this should be addressed.

**Comment by tombentley** [comment]
Yes, I agree the #1468, as a completely different way of using connectors within Kubernetes, would be able to handle this better. But TBH a lot depends on how people chose to use the existing Kafka Connect support. If they're deploying a single connector then restarting the connect deployment is a perfectly valid thing to do. Of course it doesn't work if you're using the connect deployment to host a bunch of unrelated connectors. But users might well decide to have multiple separate Kafka connect deployments when they have unrelated connectors.

**Comment by scholzj** [comment]
Yeah, users might decide to run only a single connector and it might be a wise decision. But they might also not do it. The current implementation takes Kafka Connect as it was designed - as a framework for running many connectors.

**Comment by jslusher** [comment]
Thanks for the information and feedback. I could be wrong, but it does seem like an easy thing to implement a means to customize connector health checks, especially since a default is available if you do want to use the same connector deployment for multiple connections. I would have to guess that in many if not most situations, even if the connector is using multiple connections the default health check would still need to be made more specific to the deployment. Simply checking that the root path of the API endpoint is available only accounts that it's responding, but does not account for the many variations of what would be its functionality. In our situation, since the health check is not sufficient to detect a failed connection from the plugin to mysql, it means I'll need to separate the connecter deployment from the operator entirely, which I think is worse than customizing a health check.

**Comment by tomasz-zylka-fluke** [comment]
We also find this health-check issue very serious in our deployments and we're looking for by-passing it.
Reading this conversation, we're going to try the solution of one KafkaConnect cluster per one KafkaConnector.
We have three debezium postgresql connectors, therefore my understanding is that we will have three `KafkaConnect` resources and three `KafkaConnector` resources, right?.
@scholzj can you help me understand `where` should I put liveness probe in, to make sure we will restart the pod when connector is not running?
In here?
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: kafka-connect-cluster
  annotations:
  # use-connector-resources configures this KafkaConnect
  # to use KafkaConnector resources to avoid
  # needing to call the Connect REST API directly
    strimzi.io/use-connector-resources: "true"
spec:
  image: {{ .Values.connector.image.repository }}/{{ .Values.connector.image.name }}:{{ .Values.connector.image.tag }}
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9092
  config:
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
  **livenessProbe:
      exec:
        command:
        - sh
        - ...**
```
