### ISSUE TITLE
Kafka Connect Configurations are not transferred to the rebuild image with S2I in Openshift

### ISSUE THREAD

**Issue by dozturk** [strimzi/strimzi-kafka-operator#1498]
I am trying to run single instance kafka-connector service together with plugins in the openshift , using Openshift Build and S2I image. Everything works fine but the container gets into CrashLoopBackOff stage due to missing required configuration of key.converter (can be seen below).
![Capture-1](https://user-images.githubusercontent.com/41675129/55467595-e9dc5d80-5601-11e9-9260-4f82fd081915.PNG)

So somehow provided configuration from the yaml file is not transferred to rebuild image with the plugins. here is a screenshot from the log and it does not show provided configurations from the yaml file:

![Capture-2](https://user-images.githubusercontent.com/41675129/55468163-12b12280-5603-11e9-8d35-9260a03e96bd.PNG)

I am using the openshift-template.yaml file provided for this purpose:
kafka-connect/s2i/resources/openshift-template.yaml:

```yaml
apiVersion: v1
kind: Template
metadata:
  name: strimzi-connect-s2i
  annotations:
    openshift.io/display-name: "Apache Kafka Connect (with S2I build pipeline)"
    description: >-
      This template installes Apache Kafka Connect in distributed mode together with build pipeline
      for new Kafka Connect images with additional plugins. For more information about using this 
      template see https://github.com/strimzi/strimzi
    tags: "messaging"
    iconClass: "fa pficon-topology"
    template.openshift.io/documentation-url: "https://github.com/strimzi/strimzi"
message: "Use 'kafka-connect:8083' to access Kafka Connect REST API."
parameters:
- description: Specifies the number of Kafka Connect instances to be started by default.
  displayName: Number of Kafka connect instances
  name: INSTANCES
  required: true
  value: "1"
- description: A list of host:port pairs to use for establishing the initial connection to the Kafka cluster.
  displayName: Kafka bootstrap servers
  name: KAFKA_CONNECT_BOOTSTRAP_SERVERS
  required: true
  value: kafka:9092
- description: |
        A unique string that identifies the Connect cluster group this worker belongs to. 
        This must not conflict with any consumer group IDs.
  displayName: Group ID
  name: KAFKA_CONNECT_GROUP_ID
  required: true
  value: connect-cluster
- description: Converter class used to convert between Kafka Connect format and the serialized form that is written to Kafka.
  displayName: Key Converter
  name: KAFKA_CONNECT_KEY_CONVERTER
  required: true
  value: org.apache.kafka.connect.json.JsonConverter
- description: Set to false to use schemaless format
  displayName: Enable schemas for key converters
  name: KAFKA_CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
  value: "true"
- description: Converter class used to convert between Kafka Connect format and the serialized form that is written to Kafka.
  displayName: Value Converter
  name: KAFKA_CONNECT_VALUE_CONVERTER
  required: true
  value: org.apache.kafka.connect.json.JsonConverter
- description: Set to false to use schemaless format
  displayName: Enable schemas for value converters
  name: KAFKA_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
  value: "true"
- description: Replication factor for config storage topic
  displayName: Config replication factor
  name: KAFKA_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
  value: "3"
- description: Replication factor for offset storage topic
  displayName: Offset replication factor
  name: KAFKA_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
  value: "3"
- description: Replication factor for status storage topic
  displayName: Status replication factor
  name: KAFKA_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
  value: "3"
- description: Name of the Build which will be created by this template
  displayName: Build name
  name: BUILD_NAME
  required: true
  value: "kafka-connect"
- description: Name of the new Kafka Connect Docker image which will be generated
  displayName: Target image name
  name: TARGET_IMAGE_NAME
  required: true
  value: "kafka-connect"
- description: Tag of the new Kafka Connect Docker image which will be generated
  displayName: Target image tag
  name: TARGET_IMAGE_TAG
  value: 0.1.0
- description: Image repository name of the S2I Docker image
  displayName: S2I image repository
  name: S2I_IMAGE_REPO_NAME
  value: strimzi 
- description: Name of the S2I Docker image
  displayName: S2I image name
  name: S2I_IMAGE_NAME
  value: kafka-connect-s2i
- description: Tag of the S2I Docker image
  displayName: S2I image tag
  name: S2I_IMAGE_TAG
  value: 0.1.0
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: ${BUILD_NAME}
    name: ${TARGET_IMAGE_NAME}
  spec:
    lookupPolicy:
      local: true
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: ${BUILD_NAME}
    name: ${S2I_IMAGE_NAME}
  spec:
    lookupPolicy:
      local: false
    tags:
    - name: ${S2I_IMAGE_TAG}
      from:
        kind: DockerImage
        name: ${S2I_IMAGE_REPO_NAME}/${S2I_IMAGE_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${BUILD_NAME}
    name: ${BUILD_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${TARGET_IMAGE_NAME}:${TARGET_IMAGE_TAG}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      binary: {}
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: ${S2I_IMAGE_NAME}:${S2I_IMAGE_TAG}
      type: Source
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: kafka-connect
  spec:
    ports:
      - name: rest-api
        port: 8083
        targetPort: 8083
        protocol: TCP
    selector:
      name: kafka-connect
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: kafka-connect
  spec:
    replicas: ${INSTANCES}
    template:
      metadata:
        labels:
          name: kafka-connect
      spec:
        containers:
          - name: kafka-connect
            image: ${TARGET_IMAGE_NAME}:${TARGET_IMAGE_TAG}
            ports:
              - name: rest-api
                containerPort: 8083
                protocol: TCP
            env:
              - name: KAFKA_CONNECT_BOOTSTRAP_SERVERS
                value: "${KAFKA_CONNECT_BOOTSTRAP_SERVERS}"
              - name: KAFKA_CONNECT_GROUP_ID
                value: "${KAFKA_CONNECT_GROUP_ID}"
              - name: KAFKA_CONNECT_KEY_CONVERTER
                value: "${KAFKA_CONNECT_KEY_CONVERTER}"
              - name: KAFKA_CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
                value: "${KAFKA_CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE}"
              - name: KAFKA_CONNECT_VALUE_CONVERTER
                value: "${KAFKA_CONNECT_VALUE_CONVERTER}"
              - name: KAFKA_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
                value: "${KAFKA_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE}"
              - name: KAFKA_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
                value: "${KAFKA_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR}"
              - name: KAFKA_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
                value: "${KAFKA_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR}"
              - name: KAFKA_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
                value: "${KAFKA_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR}"
            livenessProbe:
              httpGet:
                path: /
                port: rest-api
              initialDelaySeconds: 60
    triggers:
      - type: ConfigChange
      - type: ImageChange"
        imageChangeParams:
          automatic: true
          containerNames:
            - kafka-connect
          from:
            kind: ImageStreamTag
            name: ${TARGET_IMAGE_NAME}:${TARGET_IMAGE_TAG}
```

When I check the script kafka_connect_config_generator.sh I see there the env variable as KAFKA_CONNECT_CONFIGURATION, but it is not set or used anywhere the same way??

```
#!/usr/bin/env bash

SECURITY_PROTOCOL=PLAINTEXT

if [ -n "$KAFKA_CONNECT_TRUSTED_CERTS" ]; then
    SECURITY_PROTOCOL="SSL"
    TLS_CONFIGURATION=$(cat <<EOF
# TLS / SSL
ssl.truststore.location=/tmp/kafka/cluster.truststore.p12
ssl.truststore.password=${CERTS_STORE_PASSWORD}
ssl.truststore.type=PKCS12

producer.ssl.truststore.location=/tmp/kafka/cluster.truststore.p12
producer.ssl.truststore.password=${CERTS_STORE_PASSWORD}

consumer.ssl.truststore.location=/tmp/kafka/cluster.truststore.p12
consumer.ssl.truststore.password=${CERTS_STORE_PASSWORD}
EOF
)

    if [ -n "$KAFKA_CONNECT_TLS_AUTH_CERT" ] && [ -n "$KAFKA_CONNECT_TLS_AUTH_KEY" ]; then
        TLS_AUTH_CONFIGURATION=$(cat <<EOF
ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
ssl.keystore.password=${CERTS_STORE_PASSWORD}
ssl.keystore.type=PKCS12

producer.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
producer.ssl.keystore.password=${CERTS_STORE_PASSWORD}
producer.ssl.keystore.type=PKCS12

consumer.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
consumer.ssl.keystore.password=${CERTS_STORE_PASSWORD}
consumer.ssl.keystore.type=PKCS12
EOF
)
    fi
fi

if [ -n "$KAFKA_CONNECT_SASL_USERNAME" ] && [ -n "$KAFKA_CONNECT_SASL_PASSWORD_FILE" ]; then
    if [ "$SECURITY_PROTOCOL" = "SSL" ]; then
        SECURITY_PROTOCOL="SASL_SSL"
    else
        SECURITY_PROTOCOL="SASL_PLAINTEXT"
    fi

    PASSWORD=$(cat /opt/kafka/connect-password/$KAFKA_CONNECT_SASL_PASSWORD_FILE)
    SASL_MECHANISM="SCRAM-SHA-512"

    SASL_AUTH_CONFIGURATION=$(cat <<EOF
sasl.mechanism=${SASL_MECHANISM}
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_CONNECT_SASL_USERNAME}" password="${PASSWORD}";

producer.sasl.mechanism=${SASL_MECHANISM}
producer.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_CONNECT_SASL_USERNAME}" password="${PASSWORD}";

consumer.sasl.mechanism=${SASL_MECHANISM}
consumer.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_CONNECT_SASL_USERNAME}" password="${PASSWORD}";

EOF
)
fi

# Write the config file
cat <<EOF
# Bootstrap servers
bootstrap.servers=${KAFKA_CONNECT_BOOTSTRAP_SERVERS}
# REST Listeners
rest.port=8083
rest.advertised.host.name=$(hostname -I)
rest.advertised.port=8083
# Plugins
plugin.path=${KAFKA_CONNECT_PLUGIN_PATH}
# Provided configuration
${KAFKA_CONNECT_CONFIGURATION}

security.protocol=${SECURITY_PROTOCOL}
producer.security.protocol=${SECURITY_PROTOCOL}
consumer.security.protocol=${SECURITY_PROTOCOL}
${TLS_CONFIGURATION}
${TLS_AUTH_CONFIGURATION}
${SASL_AUTH_CONFIGURATION}
EOF
```

Can someone help or direct me for this issue??

Thank you very much in advance
