### ISSUE TITLE
Support for other resource configuration in PVCs than just size

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#1504]
Currently, Strimzi allows to configure only the size for the persistent volumes claims. But it seems that in some cases, there can be more options - for example IOPS count etc. We should consider changing the PVC definition in our CRs to use the Kubernetes native resource definition and not our custom fields to allow users to configure different aspects of the disks and not just the size.

**Comment by MihaiAnei** [comment]
It would also be useful for example to be able to add custom annotations for the PVCs created by the operator. A use case for this is:

https://argoproj.github.io/argo-cd/user-guide/compare-options/

Which tells ArgoCD to ignore those resources as they are created by a 3rd party, is not a direct result of the resources it keeps in sync and it should ignore those.

**Comment by scholzj** [comment]
This issue is mainly meant to cover configurations covering the disks the PVCs result in, such as IOPS etc.

You can already set the annotations to PVCs using the template property (https://strimzi.io/docs/latest/full.html#con-customizing-template-properties-str):

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app: my-cluster
spec:
  kafka:
    # ...
    template:
      persistentVolumeClaim:
        metadata:
          annotations:
            myanno: myvalue
    # ...
```
