### ISSUE TITLE
Question: Are ports going to be configurable in the near future?

### ISSUE THREAD

**Issue by royantman** [strimzi/strimzi-kafka-operator#1506]
Just as the title says. We wonder if ports are going to be configured. Cheers.

**Comment by scholzj** [comment]
I'm not aware of any such plans right now.

**Comment by tombentley** [comment]
What's your use case for wanting to configure the ports?

**Comment by adamglt** [comment]
> What's your use case for wanting to configure the ports?

Strimzi has a hard incompatibility with Istio at the moment.  

When dealing with headless services, Istio injects wildcard listeners to the workload's Envoy proxies.  
There's no issues with HTTP/GRPC or TLS with SNI, since there's a hostname to split traffic by.  
With opaque TCP (plaintext or non-SNI TLS), there's no way to classify traffic, so for Kafka's headless service, you'd get a `0.0.0.0:9092` listener in Istio.

Once you have more than one of those headless services sharing a port, Istio accepts only the first listener.  
There's a few ways to get around that with all sorts of networking magic, but it's all bad and prone to crazy mistakes (for example, leaking traffic across namespaces).

The core reason behind this behavior is that headless service backed pods are normally accessed by their direct pod address (e.g. `kafka-0.kafka.svc.cluster.local`), and pushing a listener for every pod will not scale to thousands of instances or thousands of clusters (not really relevant for Kafka, but other gossip-based systems that use the same constructs).  
This is more of a "fault" with Istio than with Strimzi, they're aware of it and working on several approaches (for example, exposing `ServiceEntry` to a limited scope and avoiding the collisions that way).

Instead (for us at least), this could be solved in a couple of minutes by assigning every Kafka cluster with a unique port.

**Comment by scholzj** [comment]
Not knowing much about Istio, this got me a bit confused ... do you need _every Kafka cluster with a unique port_? Or every Kafka broker with unique port? Because the headless service covers the individual brokers which need to be addressed separately by the clients.

**Comment by adamglt** [comment]
Every cluster - brokers can (and should) share the port.  
Basically, Istio does not currently support two TCP headless services using the same port.

More details can be found here: https://github.com/istio/istio/issues/9784

**Comment by samuel-hawker** [comment]
Has this issue been closed out by #2238 ?
Are there any remaining ports that need changes for Istio?

**Comment by scholzj** [comment]
FYI: The https://github.com/strimzi/proposals/blob/master/005-improving-configurability-of-kafka-listeners.md proposal is relevant for this. But if the initial issue is satisfied for @royantman we can close it.

**Comment by AceHack** [comment]
I believe istio has fixed this issue in 1.5/1.6.  We are using the banzai operator with istio without any issues.  I believe this should work now, have there been any recent tests?

**Comment by satishmane** [comment]
@AceHack 

I have been struggling to get zookeeper and kafka work together in mtls mode. everything is in Strict mtls mode
I have below

Banzai istio operator : 1.6.8
Banzai zookeeper charts

**zookeeper**

I installed using : https://github.com/banzaicloud/banzai-charts/tree/master/zookeeper-operator and quorumListenOnAllIPs=true
zookeeper nodes comes up without crashing, 

$ netstat -pan | grep 3888 
tcp        0      0 0.0.0.0:3888            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:54716         127.0.0.1:3888          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:53266         127.0.0.1:3888          TIME_WAIT   -                   
$ netstat -pan | grep 3888
tcp        0      0 0.0.0.0:3888            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:54716         127.0.0.1:3888          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:55108         127.0.0.1:3888          TIME_WAIT   -                   
$ netstat -pan | grep 2888
tcp        0      0 0.0.0.0:2888            0.0.0.0:*               LISTEN      -                   
$ netstat -pan | grep 2181
tcp        0      0 0.0.0.0:2181            0.0.0.0:*               LISTEN      -                   
tcp        0      0 127.0.0.1:45376         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44892         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44310         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:2181          127.0.0.1:50392         ESTABLISHED -                   
tcp        0      0 127.0.0.1:45068         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:45556         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:45210         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44774         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:50428         127.0.0.1:2181          ESTABLISHED 17/envoy            
tcp        0      0 127.0.0.1:50392         127.0.0.1:2181          ESTABLISHED 17/envoy            
tcp        0      0 127.0.0.1:44942         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:50100         127.0.0.1:2181          ESTABLISHED 17/envoy            
tcp        0      0 127.0.0.1:44262         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44702         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44580         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:45404         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:2181          127.0.0.1:50100         ESTABLISHED -                   
tcp        0      0 127.0.0.1:45196         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:45518         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:45666         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:2181          127.0.0.1:50428         ESTABLISHED -                   
tcp        0      0 127.0.0.1:45828         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44894         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44244         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44612         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:45050         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:45922         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:45774         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:45918         127.0.0.1:2181          TIME_WAIT   -                   
tcp        0      0 127.0.0.1:44448         127.0.0.1:2181          TIME_WAIT   -  

But I see continously below exceptions. 

2020-08-24 09:47:38,717 [myid:1] - WARN  [0.0.0.0/0.0.0.0:3888:QuorumCnxManager@540] - Exception reading or writing challenge: {}
java.io.EOFException
	at java.io.DataInputStream.readFully(DataInputStream.java:197)
	at java.io.DataInputStream.readLong(DataInputStream.java:416)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.handleConnection(QuorumCnxManager.java:516)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager.receiveConnection(QuorumCnxManager.java:470)
	at org.apache.zookeeper.server.quorum.QuorumCnxManager$Listener.run(QuorumCnxManager.java:898)
2020-08-24 09:47:38,870 [myid:1] - INFO  [SessionTracker:ZooKeeperServer@398] - Expiring session 0x1000394e4960b93, timeout of 4000ms exceeded

**Kafka**

Simply injected side car and pointed to zookeerp service. Kafka logs shows kafka started

When I connect my micro service to kafka, it fails with leader not available error. And keeps crashing.

Any idea whats happening here.

**Comment by AceHack** [comment]
We have not attempted it in mTLS strict mode.  But I would look to see if all ports that are needed are listed in the deployment, statefulset, and service and named correctly according to istio rules.
https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by satishmane** [comment]
@AceHack 
yes all ports - zookeeper, kafka are prefixed with "tcp-<port name>"

**Comment by satishmane** [comment]
@AceHack 
So if we leave kafka in permissive mode, does istio autMtls take care of encrypting anyway. Have you verified

**Comment by snuggie12** [comment]
I have both kafka/zookeeper working with `STRICT` and the zookeeper part in particular has seemingly been a pain so figured I'd share my setup:

- Versions: istio 1.7.4, strimzi 0.20.0, kafka 2.6.0, zookeeper 3.5.8? (I think this is correct,) k8s 1.16. Note this also worked for istio 1.5.4, strimzi 0.18.0 and whatever the default versions of kafka/zk are for that version of the operator.
- Kafka resource (some unrelated settings like storage omitted):
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: jaeger
  namespace: monitoring
spec:
  kafka:
    config:
      log.message.format.version: "2.3"
      offsets.topic.replication.factor: 3
      quorumListenOnAllIPs: true
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    replicas: 3
  zookeeper:
    config:
      quorumListenOnAllIPs: true
    template:
      pod:
        metadata:
          annotations:
            traffic.sidecar.istio.io/excludeInboundPorts: 2888,3888
            traffic.sidecar.istio.io/excludeOutboundPorts: 2888,3888
            traffic.sidecar.istio.io/includeInboundPorts: '*'
```
- Istio Resources. NOTE that I needed service entries and destination rules for both namespaces and this was only necessary for zookeeper:
```
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: jaeger-zookeeper
  namespace: kafka-operator # duplicate resource in the monitoring namespace
spec:
  host: jaeger-zookeeper-nodes.monitoring.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
---
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: jaeger-zookeeper
  namespace: kafka-operator # duplicate resource in the monitoring namespace
spec:
  hosts:
  - jaeger-zookeeper-0.jaeger-zookeeper-nodes.monitoring.svc.cluster.local
  - jaeger-zookeeper-1.jaeger-zookeeper-nodes.monitoring.svc.cluster.local
  - jaeger-zookeeper-2.jaeger-zookeeper-nodes.monitoring.svc.cluster.local
  ports:
  - name: tcp-clients
    number: 2181
    protocol: TCP
  - name: tcp-clustering
    number: 2888
    protocol: TCP
  - name: tcp-election
    number: 3888
    protocol: TCP
```

**Comment by satishmane** [comment]
You can change as below. So you do not need to add or remove when new nodes are added
hosts:
  - *.jaeger-zookeeper-nodes.monitoring.svc.cluster.local

**Comment by DekelMalul** [comment]
@snuggie12  can you sure your setup for kafka cluster also?

**Comment by snuggie12** [comment]
Funny enough I don't own the kafka cluster anymore and it doesn't run istio but the pieces are still checked in. :)

Nothing special added to the `Kafka` CR, just istio resources:

```
apiVersion: networking.istio.io/v1beta1
kind: ServiceEntry
metadata:
  name: jaeger-kafka
  # duplicate resource in the monitoring namespace though I do not think that is necessary
  # as long as you manage your Sidecar CR correctly
  namespace: kafka-operator
spec:
  hosts:
  # untested with the wildcard but that sounds correct to me
  - jaeger-kafka-0.jaeger-kafka-brokers.monitoring.svc.cluster.local
  - jaeger-kafka-1.jaeger-kafka-brokers.monitoring.svc.cluster.local
  - jaeger-kafka-2.jaeger-kafka-brokers.monitoring.svc.cluster.local
  ports:
  - name: tcp-replication
    number: 9091
    protocol: TCP
  - name: tcp-clients
    number: 9092
    protocol: TCP
  - name: tcp-clientstls
    number: 9093
    protocol: TCP

# Destination Rule
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: jaeger-kafka
  # ditto from above. inheritance suggests to go look at the destination namespace so only monitoring should be necessary
  namespace: kafka-operator
spec:
  host: jaeger-kafka-brokers.monitoring.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
```
