### ISSUE TITLE
Unable to get SASL_SSL to work

### ISSUE THREAD

**Issue by aceeric** [strimzi/strimzi-kafka-operator#1525]
I'm running Strimzi 0.11.1 under Openshift. I've deployed a basic cluster using a descriptor cloned from examples/ephemeral. Everything matches the ephemeral example, except my changes are:
...
metadata:
  name: strimzi-cluster
spec:
  kafka:
    version: 2.1.0
    replicas: 3
    listeners:
      plain: {}
      tls:
        authentication:
          type: scram-sha-512
...
For basic testing, I am trying to validate a console producer/consumer. I manually add a user into Zookeeper:

oc rsh pod/strimz-cluster-zookeeper-0
cd bin
./kafka-configs.sh --zookeeper localhost:21810 --alter --add-config 'SCRAM-SHA-512=[password=qqqqqqq]' --entity-type users --entity-name qqqqqqq

Then from my console (outside the pod)
oc extract secret/strimzi-cluster-cluster-ca-cert --keys ca.crt
keytool -keystore truststore.jks -alias CARoot -import -file ca.crt

Then:
oc run test -ti --image=strimzi/kafka:0.11.1-kafka-2.1.0 --rm=true --restart=Never -- /bin/bash

(and from inside the test pod)
cd /tmp
mkdir test
cd test
tee ./jaas.conf <<EOF
KafkaClient {
  org.apache.common.security.scram.ScramLoginModule required
  username="qqqqqqq"
  password="qqqqqqq";
};
EOF

tee ./test.properties <<EOF
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
ssl.truststore.location=/tmp/test/truststore.jks
EOF

(meanwhile from another console window outside of the pod)
oc cp truststore.jks mynamespace/test:/tmp/test/truststore.jks
# to get the truststore into the pod

... then back in the test pod:
export KAFKA_OPTS="-Djava.security.auth.login.config=/tmp/test/jaas.conf"

and then finally (still in the test pod):
$KAFKA_HOME/bin/kafka-console-consumer.sh --broker-list strimzi-cluster-kafka-bootstrap:9093 --topic test-topic --producer.config /tmp/test/test.properties

I get the prompt:
>
so I enter one message into the topic:
> test <press ENTER>

I get "failed authentication doe to: Authentication failed due to invalid credentials with SASL mechanism SCRAM-SHA-512 (org.apache.clients.NetworkClient)"

This STRIMZI configuration replicates a configuration I was successful with against a plain Kafka/Zookeeper installation that I configured (server and client). So - I'm unclear why this test client wouldnt be able to connect.

So I would have expected SASL/SSL auth to be fine, and the producer to be able to start creating messages.

Any help is appreciated. Apologies for any typos - I've had to hand-type this...

**Comment by scholzj** [comment]
The examples have the User Operator enabled. Have you disabled it in the YAML file before applying it? With the User Operator (running as container in the deployment called `<cluster-name>-entity-operator`), you have to manage the users using the `KafkaUser` resource - you create the custom resource and the User Operator will generate a password inside a secret and in Zookeeper. But if you create the user manually in Zookeeper then it will delete it because there is no corresponding KafkaUser resource. So you have to either use the UserOperator or disable it and manage the users directly in Zookeeper.

**Comment by aceeric** [comment]
Thanks. I am relying on the Entity Operator in the ephemeral example, rather than the separate User Operator. And - I see you're correct that the user is removed from Zookeeper if it is manually inserted.

Let me back up.

I *originally* created a user with a custom resource thus:

```
apiVersionL kafka.strimzi.io/v1alpha1
  kind: KafkaUser
metadata:
  name: strimziuser
  labels:
    strimzi.io/cluster: strimzi-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource
        type: cluster
        patternType: literal
      - resource:
        type: topic
        name: "*"
        patternType: literal
      operation: All
      host: "*"
      - resource:
        type: group
        name: "*"
        patternType: literal
      operation: All
      host: "*"
```
followed by oc apply -f etc..

I was able to see the user in Zookeeper thus:

$ ./kafka-configs.sh --zookeeper localhost:21810 --describe --entity-type users

gives response:

Configs for user-principal 'strimziuser' are SCRAM-SHA-512=salt=zzzzzzzz,stored_key=zzzzz,server_key=zzzzzz,iterations=4096

So I confirmed that my cloned ephemeral deployment with the included Entity Operator does in fact create the user - and the user looks configured for SCRAM-SHA-512. Yet I'm getting invalid credentials from the client pod using - in this case - the password from the secret created by the Entity Operator.

Wondering if there are any available examples that demonstrate successful SASL SCRAM-SHA-512 over SSL. Note - previously, I had success with SASL SCRAM-SHA-512 PLAINTEXT (no SSL.) So it is the addition of SSL that appears to not work.
