### ISSUE TITLE
[Enhancement] Add support for Status Subresource in Custom Resources

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#1573]
This feature is related to issues like #1500, #191, and others that would benefit from having the current state of custom resources be easily accessible.

As discussed in #191, the Fabric8 API doesn't currently support manipulating CR subresources. However, we can get around this by using the OkHttp client in a similar way to how it was used to support RBAC resources in the past. [1] [2] 

Since each CRD will have unique status fields, I think it would be best to split the basic design of these into separate PRs with the exception of the Kafka resource. We can define the Kafka CRD status here as a guideline for the other custom resources.

For starters, for our initial Kafka status, we could include condition[3] fields to monitor Kafka and EO restarts, tracking progress and delays. We could also include a listeners field for broker access convenience. e.g.
`
status:
    conditions:
        - lastTransitionTime: 2019-04-08T09:13:27Z
          reason: ""
          status: "False"
          type: ZookeeperRollingRestart
        - lastTransitionTime: 2019-04-08T09:13:27Z
          reason: "KafkaUpgradePhase1"
          status: "True"
          type: KafkaRollingRestart
       - lastTransitionTime: 2019-04-08T09:13:27Z
         reason: ""
         status: "False"
         type: EntityOperatorRestart
    listeners:
        plain:
            host: foobar
            port: 123
`

Any other ideas or thing people would like to see?

[1] https://github.com/strimzi/strimzi-kafka-operator/blob/3578f5986ea4c2ba6e58b72477313351bbfcbcb4/operator-common/src/main/java/io/strimzi/operator/common/operator/resource/WorkaroundRbacOperator.java
[2] https://github.com/strimzi/strimzi-kafka-operator/blob/3578f5986ea4c2ba6e58b72477313351bbfcbcb4/operator-common/src/main/java/io/strimzi/operator/common/operator/resource/RoleBindingOperator.java
[3] https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#spec-and-status

**Comment by scholzj** [comment]
@kyguy Sounds good. 
* IMHO we should think through the `status.listeners` field. 
* Should we have `status.condition.message`?

**Comment by kyguy** [comment]
>     * IMHO we should think through the `status.listeners` field.
I was thinking we could fill these host/port fields with the addresses of the respective bootstrap services. As I understand, the client, using one of these bootstrap services, would be forwarded to one of the bootstrap servers from which it could discover the other brokers. What do you think?
```
status:
  listeners:
    plain:
      host: foobar
      port: 123
    tls:
      host:  foobar
      port: 124
    external
      host:  foobaz
      port:  125
```
>     * Should we have `status.condition.message`?
Its an optional field to further describe the transition condition in more detail. I figured the "reason" field would be enough to describe the transition so I left it out.

**Comment by kyguy** [comment]
Adding a "KafkaClusterNotReady" condition and a "kafkaVersion" field to the original proposal. The "KafkaClusterNotReady" condition allows clients to easily discern when the cluster is ready for use. The condition also provides useful debugging information like the time of when and reason of why a cluster has become unready. The "kafkaVersion" field would be useful for verifying the cluster version after an upgrade. Here is the revised proposal below:
```yaml
kind: Kafka
spec:
  # ...
status:
  conditions:
    - lastTransitionTime: 2019-04-08T09:13:27Z
      reason: ""
      status: "False"
      type: ZookeeperRollingRestart
    - lastTransitionTime: 2019-04-08T09:13:27Z
      reason: "KafkaUpgradePhase1"
      status: "True"
      type: KafkaRollingRestart
    - lastTransitionTime: 2019-04-08T09:13:27Z
      reason: ""
      status: "False"
      type: EntityOperatorRestart
    - lastTransitionTime: 2019-04-08T09:13:27Z
      reason: ""
      status: "False"
      type: KafkaClusterNotReady
  kafkaVersion: 2.1.1
  listeners:
    plain:
      host: foobar
      port: 123
    tls:
      host:  foobar
      port: 124
    external:
      host:  foobaz
      port:  125
```
