### ISSUE TITLE
Add Kafka bridge deployment handled via the CO

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1625]
In order to deploy the Kafka bridge alongside a Kafka cluster deployed by the Strimzi Cluster Operator, following a potential CR for describing the bridge itself.

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaBridge
metadata:
  name: my-kafka-bridge
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  consumer:
    tls:
      trustedCertificates:
        - secretName: my-secret
          certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: my-secret
        certificate: public.crt
        key: private.key
  producer:
    tls:
      trustedCertificates:
        - secretName: my-secret
          certificate: ca.crt
    authentication:
      type: scram-sha-512 # plain supported as well
      username: my-user
      passwordSecret:
        secretName: my-user
        password: my-password-key
  http:
    port: 8080
```

Currently, the bridge doesn't have support for accepting TLS encrypted connection (so HTTPS) but it works with HTTP only. This could be addressed using a 3scale gateway in front of it or adding the feature in the future in the bridge itself. The same for users management.

At the same time, there is no support for accessing the Kafka cluster via TLS but the feature has to be implemented, so it's better having this configuration parameter in the CR already. The same is for authentication against the Kafka cluster.
Each of them can be set for the producer and consumer (as it happens with the Kafka Mirror Maker). Of course, we are talking about authenticating each producer and consumer which are created on the bridge against the Kafka cluster (for each connected HTTP client). Such authentication could be different from the one against the connected HTTP clients from outside which is not implemented in the bridge right now (by 3scale gateway?).

The current Kafka bridge implementation supports the AMQP protocol as well but I would not include it for now. In the future, it should just be a matter of adding a `spec.amqp` property with all the related fields for the configuration.

**[UPDATE]**

Moving TLS and authentication on the root node without any differences between consumer and producer.

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaBridge
metadata:
  name: my-kafka-bridge
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  tls:
    trustedCertificates:
      - secretName: my-secret
        certificate: ca.crt
  authentication:
    type: tls
    certificateAndKey:
      secretName: my-secret
      certificate: public.crt
      key: private.key
  http:
    port: 8080
```

The `authentication` section could support plain and scram-sha-512 as well in the following way.

```yaml
...
authentication:
      type: scram-sha-512 # plain supported as well
      username: my-user
      passwordSecret:
        secretName: my-user
        password: my-password-key
...
```

**Comment by ppatierno** [comment]
@scholzj @tombentley @stanlyDoge @kyguy any feedback is much appreciated.

**Comment by scholzj** [comment]
Some comments:
* Since this is not a Kafka component ... should it be just `Bridge`?
* At the code level ... are there really any benefits of having the AMQP and HTTP bridge in one project? E.g. shared code etc. (doesn't matter about now, but more whether you expect them in the future)
* Do we really want the port as configurable?
* I think we need to add also healthchecks, templates, resources etc. (not needed to add them to the example, but we should keep it in mind)
* I do not understand the idea behind the separate consumer and producer configuration. I think it should be just a single connection here.

**Comment by ppatierno** [comment]
> Since this is not a Kafka component ... should it be just Bridge?

but it's a bridge for Kafka. When you are on Kube/OpenShift asking for the custom resources, it's more understandable doing `oc get kafkabridge` than `oc get bridge` that could be related to something different (maybe another custom resource not in Strimzi).

> The bridge was born for AMQP. Then I abstracted a layer for using it with HTTP as well. Of course, if we think that the AMQP support will not be needed anymore (think about the AMQP Kafka Connect connector instead), the underlying common layer could be simplified for supporting HTTP only.

> Do we really want the port as configurable?

Why not?

> I think we need to add also healthchecks, templates, resources etc. (not needed to add them to the example, but we should keep it in mind)

Yes agree. Let's keep them in mind.

> I do not understand the idea behind the separate consumer and producer configuration. I think it should be just a single connection here.

Of course each HTTP client has its own producer and consumer. Instead of saying "single connection" I would say that "single common configuration" could make sense for producing and consuming at least from TLS and auth point of view. We could then move `tls` and `authentication` section just under `spec` removing the difference between consumer and producer.

**Comment by scholzj** [comment]
> but it's a bridge for Kafka. When you are on Kube/OpenShift asking for the custom resources, it's more understandable doing oc get kafkabridge than oc get bridge that could be related to something different (maybe another custom resource not in Strimzi).

Well, it could be also `StrimziBridge` :-). Anyway, if I'm the only one who sees the association to Kafka there as problematic then we should keep your suggestion.

> > Do we really want the port as configurable?
> 
> Why not?

It is something we will need to maintain and support. So why yes?

> Of course each HTTP client has its own producer and consumer. Instead of saying "single connection" I would say that "single common configuration" could make sense for producing and consuming at least from TLS and auth point of view. We could then move tls and authentication section just under spec removing the difference between consumer and producer.

Right, I do not really care about the actual TCP connections (although it is not clear to me why not pool them and share one connection for multiple consumers / producers - but I let you deal witht he implementation there ;-)). I meant the configuration - I do not see any reason for separate consumer and producer configuration. As you suggest we should just move it level higher and remove the `consumer` and `producer` stuff.

**Comment by tombentley** [comment]
Just a wild crazy Wednesday morning idea... for the `boostrapServers`, I wonder whether as well as supporting a literal address we should also support specifying by reference a bootstrap `Service` and/or a `Kafka.spec.kafka.listeners.*` listener.

I agree about pulling tls and authentication up into the `spec`. Also about resources, templates etc. Rather than just keeping them in mind, @ppatierno can you post a revised example, so we can all be on the same page about what _exactly_ is being proposed. We also need to consider logging and jvm options; I don't know whether you had those in mind already.

Can you elaborate a little about user management? I think you are saying the bridge will act as a single Kafka user, and 3scale would authenticate (and authorize?) bridge users separately, but what if we wanted some kind of authentication passthrough mode? (I'm not say we should support this, but I am interested in how the CR for that might look).

**Comment by ppatierno** [comment]
> Can you elaborate a little about user management? I think you are saying the bridge will act as a single Kafka user, and 3scale would authenticate (and authorize?) bridge users separately, but what if we wanted some kind of authentication passthrough mode? (I'm not say we should support this, but I am interested in how the CR for that might look).

As far as I understood that was the initial idea by @scholzj when he proposed this "integration" with 3scale so offloading the users management to 3scale while the bridge acts as just one user against the Kafka cluster (as "others" do ... ;)).

**Comment by tombentley** [comment]
> Isn't it too much tied to the bridge running on Kubernetes/OpenShift while it could be used on bare metal as well?

Well you're describing a CR, so the whole discussion assumes Kubernetes/OpenShift. The _operator_ would need to resolve the reference and pass an plain address to the bridge.

**Comment by ppatierno** [comment]
> Well you're describing a CR, so the whole discussion assumes Kubernetes/OpenShift. 

Right :-) My mind is already at Disneyland.

**Comment by scholzj** [comment]
> Just a wild crazy Wednesday morning idea... for the boostrapServers, I wonder whether as well as supporting a literal address we should also support specifying by reference a bootstrap Service and/or a Kafka.spec.kafka.listeners.* listener.

I would be quite interested with what you have in mind here. Could you post some ideas?

**Comment by tombentley** [comment]
Very roughly the idea was that the CR could support these alternative ways of specifying the boostrap servers:

1. A literal address (basically the same as Paolo's suggestion, but different syntax)
```
bootstrapServers:
  value: my-cluster-kafka-bootstrap:9092
```
Presumably this sets the value of some env var in the Deployment container.
 
2. A reference to a Service
```
bootstrapServers:
  valueFrom: 
    serviceRef:
      name: my-cluster-kafka-bootstrap
```
This is analogous to/inspired by the API for supplying an env var value from a secret.
The operator would resolve the address from the `Service`, setting the value of the same env var in the Deployment container.

3. A reference to a listener in a `Kafka` cluster:
```
bootstrapServers:
  valueFrom: 
    kafkaClusterRef:
      name: my-cluster
      listener: plain
```
The operator would resolve the address from the `Kafka.status.listeners`, setting the value of the same env var in the Deployment container.

That's as much as I've thought about it. If the idea holds water (any maybe it doesn't), we could use a similar pattern for `KafkaMirrorMaker`.
