### ISSUE TITLE
[Enhancement] Support multiple operations per ACLRule

### ISSUE THREAD

**Issue by itadventurer** [strimzi/strimzi-kafka-operator#1671]
**Is your feature request related to a problem? Please describe.**
Currently I need to add a new ACLRule for every operation I want to permit. The KafkaUser CRD is getting very long this way when the user needs read and write access to a lot of topics.

**Describe the solution you'd like**
Replace `operation` by `operations` (or add this field) and allow to pass an array to it.

**Describe alternatives you've considered**
Comma separated lists… no!

**Additional context**
Example:

```yaml

    acls:
    # topic1
      - resource:
          type: topic
          name: topic1
          patternType: literal
        operation: Read

      - resource:
          type: topic
          name: topic1
          patternType: literal
        operation: Write

    # topic2 
      - resource:
          type: topic
          name: topic2
          patternType: literal
        operation: Read

      - resource:
          type: topic
          name: topic2
          patternType: literal
        operation: Read
```

New way:

```yaml

    acls:
      - resource:
          type: topic
          name: topic1
          patternType: literal
        operations: ["Read","Write"]

      - resource:
          type: topic
          name: topic2
          patternType: literal
        operation: ["Read","Write"]
```
