### ISSUE TITLE
[Bug] OpenShift template  provisioning for Kafkaconnect, Kafkamirrormaker  is not working when you have "template" property defined  for the CR as Kafkaconnect.spec.template or Kafkamirrormaker.spec.template 

### ISSUE THREAD

**Issue by sharafcmr** [strimzi/strimzi-kafka-operator#1831]
**Describe the bug**
Provisioning a cluster from OpenShift console is not proceeding after you click "create" button when you have "template" property(eg: Kafkaconnects2i.spec.template.pod.labels) defined in Kafkamirrormaker, Kafkaconnect or Kafkaconnects2i OpenShift templates. Provisioning works fine via `oc process ` command.

**To Reproduce**
1. Create a Kafkaconnect/kafkamirrormaker/kafkaconnects2i template with custom pod/deployment/statefulset option which has template parameter configured in the CR object to add a label
Eg:
```
apiVersion: v1
kind: Template
metadata:
  name: amq-streams-connect-s2i
  annotations:
    iconClass: "fa fa-exchange"
    openshift.io/display-name: "Apache Kafka Connect S2I"
message: "Kafka Connect S2I cluster ${CLUSTER_NAME} is being deployed. Use '${CLUSTER_NAME}-connect-api:8083' to access Kafka Connect REST API."
parameters:
- description: All Kubernetes resources will be named after the cluster name
  displayName: Name of the cluster
  name: CLUSTER_NAME
  value: my-connect-cluster
- description: Specifies the number of Kafka Connect instances to be started by default.
  displayName: Number of Kafka Connect instances
  name: INSTANCES
  required: true
  value: "1"
- description: The Kafka version to use for this Kafka connect cluster.
  displayName: The Kafka version to use
  name: KAFKA_VERSION
  required: true
  value: "2.1.1"
- description: A list of host:port pairs to use for establishing the initial connection to the Kafka cluster.
  displayName: Kafka bootstrap servers
  name: KAFKA_CONNECT_BOOTSTRAP_SERVERS
  required: true
  value: my-target-cluster-kafka-bootstrap:9093
- description: A unique string that identifies the Connect cluster group this worker belongs to. Note this must not conflict with any consumer group IDs.
  displayName: Group ID
  name: KAFKA_CONNECT_GROUP_ID
  required: true
  value: "connect-cluster"
- description: Converter class used to convert between Kafka Connect format and the serialized form that is written to Kafka.
  displayName: Key Converter
  name: KAFKA_CONNECT_KEY_CONVERTER
  required: true
  value: org.apache.kafka.connect.json.JsonConverter
- description: Set to false to use schemaless format
  displayName: Enable schemas for key converters
  name: KAFKA_CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE
  value: "true"
- description: Converter class used to convert between Kafka Connect format and the serialized form that is written to Kafka.
  displayName: Value Converter
  name: KAFKA_CONNECT_VALUE_CONVERTER
  required: true
  value: org.apache.kafka.connect.json.JsonConverter
- description: Set to false to use schemaless format
  displayName: Enable schemas for value converters
  name: KAFKA_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE
  value: "true"
- description: Replication factor for config storage topic
  displayName: Config replication factor
  name: KAFKA_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR
  value: "3"
- description: Replication factor for offset storage topic
  displayName: Offset replication factor
  name: KAFKA_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR
  value: "3"
- description: Replication factor for status storage topic
  displayName: Status replication factor
  name: KAFKA_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR
  value: "3"
- description: Number of seconds after the container has started before healthcheck probes are initiated.
  displayName: Kafka Connect healthcheck initial delay
  name: HEALTHCHECK_DELAY
  value: "60"
- description: Number of seconds after which the probe times out.
  displayName: Kafka Connect health check timeout
  name: HEALTHCHECK_TIMEOUT
  value: "5"
- description: "Should have the kafka broker ca certificate secret as the value. example: If the certificate secret name is `my-kafka-cluster-ca-cert` then the value should be same `my-kafka-cluster-ca-cert`"
  displayName: "Kafka cluster ca-certificate secret name"
  name: KAFKA_CLUSTER_CA_CERT_SECRET_NAME
  required: true
  value: "my-kafka-cluster-ca-cert"
- description: "Should have the Kafka certificate keyname(that holds certificate data) in the secret as the value. example: If the certificate secret name is my-kafka-cluster-ca-cert` and the secret has the certificate stored under the key `ca.crt` then the value should be `ca.crt`"
  displayName: "Kafka cluster ca certificate key/file name in the secret"
  name: KAFKA_CLUSTER_CA_CERT_NAME
  required: true
  value: "ca.crt"
- description: "This will pass the above option level events and above to stdout. Defaults to INFO"
  displayName: "KafkaConnect Log4j root log level"
  name: KAFKA_CONNECT_LOG_LEVEL
  value: "INFO"
- description: "Maximum amount of CPU the container can use.Default value is '1 core'"
  displayName: "CPU Limit"
  name: KAFKA_CONNECT_CPU_LIMIT
  value: "1"
- description: "Maximum amount of memory the container can use.Default value is '4Gi', User must change the values based on the requirement"
  displayName: "Memory Limit"
  name: KAFKA_CONNECT_MEMORY_LIMIT
  value: "4Gi"
- description: "Required cpu for the container. Default value is 1 core, User must change the values based on the requirement"
  displayName: "CPU Request"
  name: KAFKA_CONNECT_CPU_REQUEST
  value: "1"
- description: "Memory required for container. Default value is 4Gi. User must change the values based on the requirement"
  displayName: "Memory Request"
  name: KAFKA_CONNECT_MEMORY_REQUEST
  value: "4Gi"
- description: >-
    Kafka connect JVM Options as a JSON map, for example: { "-Xms": "1g","-Xmx": "1g","-server": "true" }.
  displayName: Kafka Connect JVM Options
  name: KAFKA_CONNECT_JVM_OPTIONS
  required: true
  value: "{}"
objects:
- apiVersion: kafka.strimzi.io/v1alpha1
  kind: KafkaConnectS2I
  metadata:
    name: ${CLUSTER_NAME}
  spec:
    version: ${{KAFKA_VERSION}}
    replicas: ${{INSTANCES}}
    livenessProbe:
      initialDelaySeconds: ${{HEALTHCHECK_DELAY}}
      timeoutSeconds: ${{HEALTHCHECK_TIMEOUT}}
    readinessProbe:
      initialDelaySeconds: ${{HEALTHCHECK_DELAY}}
      timeoutSeconds: ${{HEALTHCHECK_TIMEOUT}}
    bootstrapServers: "${KAFKA_CONNECT_BOOTSTRAP_SERVERS}"
    config:
      config.providers: file
      config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
      group.id: "${KAFKA_CONNECT_GROUP_ID}"
      offset.storage.topic: "${KAFKA_CONNECT_GROUP_ID}-offsets"
      config.storage.topic: "${KAFKA_CONNECT_GROUP_ID}-configs"
      status.storage.topic: "${KAFKA_CONNECT_GROUP_ID}-status"
      key.converter: "${KAFKA_CONNECT_KEY_CONVERTER}"
      value.converter: "${KAFKA_CONNECT_VALUE_CONVERTER}"
      key.converter.schemas.enable: ${{KAFKA_CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE}}
      value.converter.schemas.enable: ${{KAFKA_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE}}
      config.storage.replication.factor: ${{KAFKA_CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR}}
      offset.storage.replication.factor: ${{KAFKA_CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR}}
      status.storage.replication.factor: ${{KAFKA_CONNECT_STATUS_STORAGE_REPLICATION_FACTOR}}
    tls:
      trustedCertificates:
      - certificate: ${KAFKA_CLUSTER_CA_CERT_NAME}
        secretName: ${KAFKA_CLUSTER_CA_CERT_SECRET_NAME}
    insecureSourceRepository: true
    metrics:
      lowercaseOutputName: true
    logging:
      type: inline
      loggers:
        connect.root.logger.level: "${{KAFKA_CONNECT_LOG_LEVEL}}"
    resources:
      limits:
        cpu: "${KAFKA_CONNECT_CPU_LIMIT}"
        memory: "${{KAFKA_CONNECT_MEMORY_LIMIT}}"
      requests:
        cpu: "${KAFKA_CONNECT_CPU_REQUEST}"
        memory: "${{KAFKA_CONNECT_MEMORY_REQUEST}}"
    template:
      pod:
        metadata:
          labels:
            owner: productowner
            product: amq-streams-kafka-connects2i
    jvmOptions:
      "${{KAFKA_CONNECT_JVM_OPTIONS}}"
```

2.  Provision a kafkaconnects2i instance using above created template from UI. After clicking create button in the template provisioning window, it wont proceed to the creation of custom resource. Even after clicking "create" button multiple times, the provisioning window will still remain in the same stage.

**Expected behavior**
It was expected to create a kafkaconnects2i custom resource and start an connect pod

**Environment (please complete the following information):**
 - Strimzi version:  0.11.1-AMQ Streams 1.1.1
 - Installation method:  YAML files
 - Kubernetes cluster: OpenShift 3.11
 - Infrastructure: GCP

**Additional context**

Provisioning succeeds when i use oc process command using the same template
