### ISSUE TITLE
[Question] Running Mirror Maker with Kubernetes Service name?

### ISSUE THREAD

**Issue by cnadolny** [strimzi/strimzi-kafka-operator#1856]
I'm trying to follow the TLS Mirror Maker example and run Mirror Maker using Kubernetes service names for the bootstrap servers. Here's my YAML file:
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
  namespace: kafka
spec:
  version: 2.2.1
  replicas: 1
  consumer:
    bootstrapServers: cluster1-kafka-bootstrap:9093
    groupId: my-source-group-id
    tls:
      trustedCertificates:
        - secretName: cluster1-cluster-ca-cert
          certificate: ca.crt
  producer:
    bootstrapServers: cluster2-kafka-bootstrap:9093
    tls:
      trustedCertificates:
        - secretName: cluster2-cluster-ca-cert
          certificate: ca.crt
  whitelist: ".*"
```

Where both Kafka clusters are on the same Kubernetes cluster, and both are exposed externally, secured by TLS. Running MM using the external IP on port 9094 works fine, but I'm trying to see if I can use the Kubernetes service name for one of the clusters, and I'm running into issues. 

If I put in the internal service IP, or the bootstrap Kubernetes service, Mirror Maker runs into a crash back off loop. I also tried putting the full service DNS name since my clusters are in the kafka namespace, cluster1-kafka-bootstrap.kafka.svc.cluster.local:9093, but still not working. Is it possible to run mirror maker with the Kubernetes service name?

Here are some error messages, it looks like mirror maker is failing with SSL handshake failure:
```
2019-07-30 22:52:45,505 INFO [Consumer clientId=my-source-group-id-0, groupId=my-source-group-id] Failed authentication with cluster1-kafka-bootstrap/10.0.1.83 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [mirrormaker-thread-0]
2019-07-30 22:52:45,512 ERROR [Consumer clientId=my-source-group-id-0, groupId=my-source-group-id] Connection to node -1 (cluster1-kafka-bootstrap/10.0.1.83:9093) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient) [mirrormaker-thread-0]
2019-07-30 22:52:45,531 INFO Cluster ID: jDK8JAzCT9qWc9HIqhqYkw (org.apache.kafka.clients.Metadata) [kafka-producer-network-thread | producer-1]
2019-07-30 22:52:45,535 ERROR [mirrormaker-thread-0] Mirror maker thread failure due to  (kafka.tools.MirrorMaker$MirrorMakerThread) [mirrormaker-thread-0]
org.apache.kafka.common.errors.SslAuthenticationException: SSL handshake failed
```

**Comment by scholzj** [comment]
You should be able to run them through the service names. Your Mirror Maker configuration looks good to me assuming your Kafka clusters have the right configuration. For this to work, they would need to be:
* In the same namespace as your Mirror Maker
* Have the TLS listener enabled without authentication (i.e. just `tls: {}`) 

Can you share the YAMLs for your Kafka clusters?

**Comment by cnadolny** [comment]
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster1
spec:
  kafka:
    version: 2.2.1
    replicas: 3
    listeners:
      external:
        type: loadbalancer
        tls: true
      tls:
        authentication:
          type: tls
    config:
      log.message.format.version: "2.2"
      ssl.client.auth: "required"
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
    storage:
      type: jbod
      volumes:
      - id: 0
        class: managed-premium
        type: persistent-claim
        size: 64Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: managed-premium
      size: 32Gi
      deleteClaim: false
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

It looks like I have the TLS enabled with authentication for my scenario. Why is it not possible to do without the TLS listener enabled without authentication?

**Comment by scholzj** [comment]
You have two options:
* you can either disable the authentication on the TLS interface.
* or you have to configure the authentication in the Mirror Maker

## The first one will be something like this ... change this:

```yaml
      tls:
        authentication:
          type: tls
```

to:

```yaml
      tls: {}
```

The authentication is different for each interface. The external address works for you because there you have currently no authentication. To enable it you have to change it to something like this:

```yaml
      external:
        type: loadbalancer
        tls: true
        authentication:
          type: tls
```

## The other option would be to keep your Kafka cluster as it is and create a new users and enable authentication in Mirror Maker.

To create new users just apply a YAML like this:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: cluster1-mirror-maker
  labels:
    strimzi.io/cluster: cluster1
spec:
  authentication:
    type: tls
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: cluster2-mirror-maker
  labels:
    strimzi.io/cluster: cluster2
spec:
  authentication:
    type: tls
```

And change your Mirror Maker configuration to this:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
  namespace: kafka
spec:
  version: 2.2.1
  replicas: 1
  consumer:
    bootstrapServers: cluster1-kafka-bootstrap:9093
    groupId: my-source-group-id
    tls:
      trustedCertificates:
        - secretName: cluster1-cluster-ca-cert
          certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: cluster1-mirror-maker
        certificate: user.crt
        key: user.key
  producer:
    bootstrapServers: cluster2-kafka-bootstrap:9093
    tls:
      trustedCertificates:
        - secretName: cluster2-cluster-ca-cert
          certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: cluster2-mirror-maker
        certificate: user.crt
        key: user.key
  whitelist: ".*"
```
