### ISSUE TITLE
[Doc] Adding minimum user rights for Kafka Connect user when authorization is enabled

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#1882]
The documentation section about having Kafka Connect connecting to the Kafka brokers with authentication (https://strimzi.io/docs/master/#assembly-kafka-connect-authentication-deployment-configuration-kafka-connect) explains how to specify the TLS certificate or the user for SASL SCRAM-SHA-512 and PLAIN.
What doesn't it explain is that the Kafka Connect user has to have the rights for accessing (read/write) topics used for handing connectors configuration, offsets and status so the one specified by the following configuration parameter:

* `offset.storage.topic` with default value `connect-cluster-offsets`
* `config.storage.topic` with default value `connect-cluster-configs`
* `status.storage.topic` with default value `connect-cluster-status`

At the same time, it has to have the right to join the consumer group specified by:

`group.id` with default value `connect-cluster`

All this parameter are configurable in `KafkaConnect.spec.config` field.
So using the default values, a Kafka Connect user should have at least this configuration in the corresponding `KafkaUser` resource for working properly.

```yaml
# rights on the "offset.storage.topic" by default "connect-cluster-offsets"
      - resource:
          type: topic
          name: connect-cluster-offsets
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: connect-cluster-offsets
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: connect-cluster-offsets
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: connect-cluster-offsets
          patternType: literal
        operation: Read
        host: "*"
      # rights on the "status.storage.topic" by default "connect-cluster-status"
      - resource:
          type: topic
          name: connect-cluster-status
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: connect-cluster-status
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: connect-cluster-status
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: connect-cluster-status
          patternType: literal
        operation: Read
        host: "*"
      # rights on the "config.storage.topic " by default "connect-cluster-configs"
      - resource:
          type: topic
          name: connect-cluster-configs
          patternType: literal
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: connect-cluster-configs
          patternType: literal
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: connect-cluster-configs
          patternType: literal
        operation: Describe
        host: "*"
      - resource:
          type: topic
          name: connect-cluster-configs
          patternType: literal
        operation: Read
        host: "*"
      # joining "group.id" by default "connect-cluster" for the above topics
      - resource:
          type: group
          name: connect-cluster
          patternType: literal
        operation: Read
        host: "*"
```
otherwise Kafka Connect doesn't work when authentication is enable.
We should explain that in the documentation.
