### ISSUE TITLE
[Enhancement] Provide a way to specify the loadBalancerIP for the externalBootstrapService

### ISSUE THREAD

**Issue by johren** [strimzi/strimzi-kafka-operator#1887]
**Is your feature request related to a problem? Please describe.**
We need to pass the IP address of our external bootstrap service to a client outside the cluster and we don't currently have external DNS available.   To do this, we would like to provide a pinned IP to the LoadBalancer service that is created by the operator.

**Describe the solution you'd like**
Something like the ability to specify
```
    template:
       externalBootstrapService:
        metadata:
          annotations:
            metallb.universe.tf/address-pool: my-pool
        spec:
          loadBalancerIP:  10.10.10.100
```

**Describe alternatives you've considered**

- Create a way to learn the IP allocated by MetalLB to pass to the client.  This doesn't really work for us right now. 
- Create another LoadBalancer service alongside the one that is created by the operator.   Not a great solution.

**Additional context**
We are running on bare metal with the MetalLB load balancer.
