### ISSUE TITLE
[Bug] SSL handshake failed when using openshift routes

### ISSUE THREAD

**Issue by uocxp** [strimzi/strimzi-kafka-operator#1902]
The cluster is working without any problem on openshift when using only internal Listeners, but I need to connect to the brokers from outside so I followed the documentation [here](https://strimzi.io/2019/04/30/accessing-kafka-part-3.html) and extracted the my-cluster-cluster-ca-cert and imported to a keystore. When I run the producer example

```
 /opt/kafka/bin/kafka-console-producer.sh --broker-list bootstrap-kafka.mydomain:443 --producer-property security.protocol=SSL --producer-property ssl.truststore.password=password --producur-property ssl.truststore.location=./truststore.jks --topic test
```

 I get :

```
 ERROR [Producer clientId=console-producer] Connection to node -1 (bootstrap-kafka.mydomain/<<myip>:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
```

**Expected behavior**
The producer connects without any problem to the external listener using ssl

**Environment (please complete the following information):**
 - Strimzi strimzi/kafka:0.13.0-kafka-2.3.0
 - Installation method: [OKD]
 - Kubernetes cluster: [OpenShift 3.9]

**YAML files and logs**
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 2
    listeners:
     external:
       type: route
       authentication:
         type: tls
       overrides:
           bootstrap:
                host: bootstrap-kafka.mydomain
           brokers:
           - broker: 0
             host: broker-0.mydomain
           - broker: 1
             host: broker-1.mydomain
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.3"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 30Gi
        deleteClaim: false
  zookeeper:
    replicas: 2
    storage:
      type: persistent-claim
      size: 30Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

```

**Comment by scholzj** [comment]
If you run the client with the Java property `-Djavax.net.debug=ssl` it should tell use more about what is exactly failing. But my guess from the provided files is that you are using TLS client authentication. But you seem to be configuring the client only for TLS Server authentication because your `kafka-console-producer.sh` seems to configure only the truststore options.

You have most probably two options:

1) Disable the TLS Client authentication by deleting the following section form your CRD:

```yaml
       authentication:
         type: tls
```

and trying to use the command as you have it.

2) Create a TLS user and specifying the `ssl.keystore` related options in your producer as well. Let me know if you want to try this and I can put together some more details about how to do it.

**Comment by uocxp** [comment]
I will try the first option at fist and see if it works and after that I will try the second option. I will be very happy if you post more details about the second option. I didn't understand what do you mean with `create the TLS user`, do you mean to create a keystore for the client ?

**Comment by uocxp** [comment]
The first option worked!

**Comment by scholzj** [comment]
Right. So for the option 2 with mutual TLS you will need to do following in addition:

1) Create the KafkaUser resource:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
```

2) Export the user TLS certificate from the TLS secret generated by the User Operator:

```
oc extract secret/$USERNAME --keys=user.crt --to=- > user.crt
oc extract secret/$USERNAME --keys=user.key --to=- > user.key
```

3) Use them to create a keystore:

```
openssl pkcs12 -export -in user.crt -inkey user.key -name my-user -password pass:123456 -out user.p12
```

4) Use it in your application:

```
/opt/kafka/bin/kafka-console-producer.sh --broker-list bootstrap-kafka.mydomain:443 --producer-property security.protocol=SSL --producer-property ssl.truststore.password=password --producur-property ssl.truststore.location=./truststore.jks  --producer-property ssl.truststore.password=password --producur-property ssl.truststore.location=./user.p12 --topic test
```

**Comment by uocxp** [comment]
thanks a lot i will try it soon. Is it possible to configure my CRD so that the internal listener uses plaintext and the external ssl ? I tried this configuration but it didn't work :
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 2
    listeners:
        plain: {}
        external:
          type: route
          overrides:
              bootstrap:
                   host: bootstrap-kafka.mydomain
              brokers:
              - broker: 0
                host: broker-0.mydomain
              - broker: 1
                host: broker-1.mydomain
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 2
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.3"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 30Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 30Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}


```
