### ISSUE TITLE
[Bug] Kafka keeps rolling after some changes

### ISSUE THREAD

**Issue by stanlyDoge** [strimzi/strimzi-kafka-operator#1958]
**Describe the bug**
The kafka pods keep restarting after some CR updates. 

**To Reproduce**
1. Start CO
2. Apply 
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 1
    listeners:
      external:
        type: route
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
3. Wait for creation
4. Update CR to 
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 1
    listeners:
      external:
        type: route
      plain: {}
      tls:
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
5. After the reconciliation time the Kafka pods are restarted

**Expected behavior**
Kafka pods should roll once.

**Environment (please complete the following information):**
 - Strimzi version: master
 - Installation method: YAML files
 - Kubernetes cluster: OpenShift 3.11
 - Infrastructure: Minikube

**YAML files and logs**
```
2019-09-03 13:33:48 DEBUG StatefulSetDiff:101 - Current StatefulSet path /spec/template/spec/containers/0/env/5 has value {"name":"KAFKA_CLIENTTLS_AUTHENTICATION","value":"tls"}
2019-09-03 13:33:48 DEBUG StatefulSetDiff:102 - Desired StatefulSet path /spec/template/spec/containers/0/env/5 has value {"name":"KAFKA_CLIENTTLS_ENABLED","value":"TRUE"}
```

`io.strimzi.operator.cluster.model.KafkaCluster#getEnvVars` contains this code 
```
. . .
if (listeners.getTls() != null) {
                varList.add(buildEnvVar(ENV_VAR_KAFKA_CLIENTTLS_ENABLED, "TRUE"));

                if (listeners.getTls().getAuth() != null) {
                    varList.add(buildEnvVar(ENV_VAR_KAFKA_CLIENTTLS_AUTHENTICATION, listeners.getTls().getAuth().getType()));
                }
            }
. . .
```
but result statefulset contains envVars in this order 
```
            - name: KAFKA_CLIENTTLS_AUTHENTICATION
              value: tls
            - name: KAFKA_CLIENTTLS_ENABLED
              value: 'TRUE'
```
which leads to StatefulSetDiff false positive and kafka pods are rolled over and over again.
I have tried to use order preserving collections with no success. It seems k8s is changing the order on its behalf. 

I also tried to switch the order of there two envars in the code, but they are in the wrong order again in the created SS.

When the modified SS is created manually, everything is ok.

**Possible solution**
```
--- a/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/StatefulSetDiff.java
+++ b/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/resource/StatefulSetDiff.java
@@ -83,6 +83,11 @@ public class StatefulSetDiff extends AbstractResourceDiff {
                 log.debug("StatefulSet {}/{} ignoring diff {}", md.getNamespace(), md.getName(), d);
                 continue;
             }
+            if ("move".equals(d.path("op").asText())) {
+                ObjectMeta md = current.getMetadata();
+                log.debug("StatefulSet {}/{} ignoring diff {}", md.getNamespace(), md.getName(), d);
+                continue;
+            }
``` 
but I am not sure whether it breaks anything else. I tried it and the bug is eliminated by this.
http://jsonpatch.com/#move

**Additional context**
