### ISSUE TITLE
KafkaUser CR prefixing

### ISSUE THREAD

**Issue by aceeric** [strimzi/strimzi-kafka-operator#1986]
Currently, the KafkaUser CR is named identically to the user. For example, user "mrducks" has a KafkaUser CR named "mrducks". Consider this scenario: Application X uses both Kafka, and another backing service (backing service Q.) App X wants to have a system user named "xsysuser" in both Kafka, and Backing Service Q. What if both the Kafka operator _and_ the Q operator want to name its ...User CR by the actual user name: "xsysuser"? Instead, the name of the KafkaUser CR should be able to be prefixed, like "kafka-xsysuser" and and the Q system should support "q-xsysuser". In this scenario, the user name would become an attribute of the KafkaUser CR:
```
...
kind: KafkaUser
metadata:
  name: kafka-xsysuser
spec:
  userName: xsysuser
...
```

**Comment by scholzj** [comment]
This is fairly complicated to implement. Mainly because you can then have user:

```yaml
kind: KafkaUser
metadata:
  name: kafka-xsysuser
spec:
  userName: xsysuser
```

and 

```yaml
kind: KafkaUser
metadata:
  name: somethingelse-xsysuser
spec:
  userName: xsysuser
```

And we would need to decide which of these is valid and which should be ignored etc. So I do not think we plan anything like this.

Also, I'm not completely sure I understand the problem. If the other user with the same name is in a different service, you will not use the `KafkaUser` resource to create such user but for example `ServiceQUser` resource. And you can have resoruces of these two types with the same name.
