### ISSUE TITLE
Problem with client communication https

### ISSUE THREAD

**Issue by valentinPierdet** [strimzi/strimzi-kafka-operator#2000]
I'm trying to communicate with my kafka through Ingress NGINX Controller but all my request end up in an 502 error bad gateway.

I don't really know if the problem come from the controller or kafka. 

Here is my yaml file for installation : 
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: bdi
spec:
  kafka:
    version: 2.3.0
    replicas: 3
    listeners:
      external:
        type: ingress
        authentication:
          type: tls
        configuration:
          bootstrap:
            host: bootstrap.bdi
          brokers:
          - broker: 0
            host: broker-0.bdi
          - broker: 1
            host: broker-1.bdi
          - broker: 2
            host: broker-2.bdi
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: persistent-claim
      class: fast-rbd
      size: 5Gi
      delete-claim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: fast-rbd
      size: 5Gi
      delete-claim: false
  entityOperator:
    topicOperator:
      spec:
        watchedNamespace: default
        image: docker.io/strimzi/operator:latest
    userOperator:
        watchedNamespace: default
        image: docker.io/strimzi/operator:latest
```

Here is a description of one of the Ingress automatically generated by the controller and the kafka service linked to it
Service :

```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-09-19T14:39:05Z"
  labels:
    strimzi.io/cluster: bdi
    strimzi.io/kind: Kafka
    strimzi.io/name: bdi-kafka-0
  name: bdi-kafka-0
  namespace: default
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta1
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: bdi
    uid: 254f62b2-daeb-11e9-8d22-525400f0e95b
  resourceVersion: "32287610"
  selfLink: /api/v1/namespaces/default/services/bdi-kafka-0
  uid: 3b3d42a7-daeb-11e9-90ce-525400f0e95b
spec:
  clusterIP: 10.233.20.126
  ports:
  - name: external
    port: 9094
    protocol: TCP
    targetPort: 9094
  selector:
    statefulset.kubernetes.io/pod-name: bdi-kafka-0
    strimzi.io/cluster: bdi
    strimzi.io/kind: Kafka
    strimzi.io/name: bdi-kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```
Ingress :

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  creationTimestamp: "2019-09-19T14:39:05Z"
  generation: 1
  labels:
    strimzi.io/cluster: bdi
    strimzi.io/kind: Kafka
    strimzi.io/name: bdi-kafka-0
  name: bdi-kafka-0
  namespace: default
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta1
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: bdi
    uid: 254f62b2-daeb-11e9-8d22-525400f0e95b
  resourceVersion: "32287914"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/bdi-kafka-0
  uid: 3b457426-daeb-11e9-90ce-525400f0e95b
spec:
  rules:
  - host: broker-0.bdi
    http:
      paths:
      - backend:
          serviceName: bdi-kafka-0
          servicePort: 9094
        path: /
  tls:
  - hosts:
    - broker-0.bdi
status:
  loadBalancer:
    ingress:
    - {}
```

This is my service for the NGINX controller :
```yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-09-19T13:55:29Z"
  labels:
    app: nginx-ingress
    chart: nginx-ingress-1.20.0
    component: controller
    heritage: Tiller
    release: nginx
  name: nginx-nginx-ingress-controller
  namespace: default
  resourceVersion: "32267334"
  selfLink: /api/v1/namespaces/default/services/nginx-nginx-ingress-controller
  uid: 23c12794-dae5-11e9-a733-525400f0e95b
spec:
  clusterIP: 10.233.4.130
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31456
    port: 80
    protocol: TCP
    targetPort: http
  - name: https
    nodePort: 30431
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app: nginx-ingress
    component: controller
    release: nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
```

So I am trying to curl the bdi-kafka-0 with the command :   
>  curl -k -s https://10.10.3.20:30431 -H "Host: broker-0.bdi" -v  

Here is my answer :   

![2019-09-19 17_56_25-vagrant@p3kubemaster1_~_kafka](https://user-images.githubusercontent.com/54103242/65260569-dc128a00-db06-11e9-8ab8-3ab56b1a7000.png)  

Here is my Ingress Controller logs : 

![2019-09-19 18_19_46-vagrant@p3kubemaster1__etc](https://user-images.githubusercontent.com/54103242/65262215-221d1d00-db0a-11e9-81d9-055cd44b1095.png)

Here is my broker log : 

![2019-09-19 18_21_58-vagrant@p3kubemaster1__etc](https://user-images.githubusercontent.com/54103242/65262351-732d1100-db0a-11e9-838e-554f9fdf81f0.png)

Thanks for the help !!

**Comment by scholzj** [comment]
From the screenshot you seem to be getting back a certificate which looks like the Ingress default certificate. So my guess would be that the Ingress terminates the TLS instead of passing it through. Have you enabled TLS passthrough in your Ingress configuration? (The ingress deployment configuration it self)

**Comment by valentinPierdet** [comment]
Yes i'm deploying the Ingress Controller that way :
```shell
 helm install stable/nginx-ingress --name nginx --set rbac.create=true --set controller.service.type=NodePort, controller.extraArgs.enable-ssl-passthrough=""
``` 
And the corresponding annotations is present in the Ingress ressources.

I checked int the ingress controller pod and ssl passthrough is enabled :  
![2019-09-20 10_31_23-Inbox - valentin pierdet@capgemini com - Outlook](https://user-images.githubusercontent.com/54103242/65312043-fd6c8800-db91-11e9-9b86-27755aa90249.png)

**Comment by scholzj** [comment]
That seems to be the same as in my Ingress:

```
www-data@nginx-ingress-controller-777f5d8df8-tt4qk:/etc/nginx$ /dbg conf | grep ssl
                        is_ssl_passthrough_enabled = true,
                listen_ports = { ssl_proxy = "442", https = "443" },
        ssl_protocols TLSv1.2;
        ssl_session_cache builtin:1000 shared:SSL:10m;
        ssl_session_timeout 10m;
        # allow configuring ssl session tickets
        ssl_session_tickets on;
        ssl_buffer_size 4k;
        # allow configuring custom ssl ciphers
        ssl_ciphers 'ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256';
        ssl_prefer_server_ciphers on;
        ssl_ecdh_curve auto;
        proxy_ssl_session_reuse on;
                listen 442 proxy_protocol proxy_protocol default_server reuseport backlog=511 ssl http2 ;
                listen [::]:442 proxy_protocol proxy_protocol default_server reuseport backlog=511 ssl http2 ;
                ssl_certificate                         /etc/ingress-controller/ssl/default-fake-certificate.pem;
                ssl_certificate_key                     /etc/ingress-controller/ssl/default-fake-certificate.pem;
                ssl_certificate_by_lua_block {
                                        force_ssl_redirect = false,
                listen 442 proxy_protocol proxy_protocol ssl http2 ;
                listen [::]:442 proxy_protocol proxy_protocol ssl http2 ;
                ssl_certificate                         /etc/ingress-controller/ssl/default-fake-certificate.pem;
                ssl_certificate_key                     /etc/ingress-controller/ssl/default-fake-certificate.pem;
                ssl_certificate_by_lua_block {
                                        force_ssl_redirect = true,
                listen 442 proxy_protocol proxy_protocol ssl http2 ;
                listen [::]:442 proxy_protocol proxy_protocol ssl http2 ;
                ssl_certificate                         /etc/ingress-controller/ssl/default-fake-certificate.pem;
                ssl_certificate_key                     /etc/ingress-controller/ssl/default-fake-certificate.pem;
                ssl_certificate_by_lua_block {
                                        force_ssl_redirect = true,
                listen 442 proxy_protocol proxy_protocol ssl http2 ;
                listen [::]:442 proxy_protocol proxy_protocol ssl http2 ;
                ssl_certificate                         /etc/ingress-controller/ssl/default-fake-certificate.pem;
                ssl_certificate_key                     /etc/ingress-controller/ssl/default-fake-certificate.pem;
                ssl_certificate_by_lua_block {
                                        force_ssl_redirect = true,
                listen 442 proxy_protocol proxy_protocol ssl http2 ;
                listen [::]:442 proxy_protocol proxy_protocol ssl http2 ;
                ssl_certificate                         /etc/ingress-controller/ssl/default-fake-certificate.pem;
                ssl_certificate_key                     /etc/ingress-controller/ssl/default-fake-certificate.pem;
                ssl_certificate_by_lua_block {
                                        force_ssl_redirect = true,
```

Also the curl command seems to get to the Kafka broker:

```
curl -k -s https://kafka-bootstrap.mydomain.cz -H "Host: kafka-bootstrap.mydomain.cz" -v
* Rebuilt URL to: https://kafka-bootstrap.mydomain.cz/
*   Trying 52.0.45.107...
* TCP_NODELAY set
* Connected to kafka-bootstrap.j9z.cz (52.0.45.107) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Request CERT (13):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (OUT), TLS alert, Server hello (2):
* error:1401E0F4:SSL routines:CONNECT_CR_FINISHED:unexpected message
* stopped the pause stream!
* Closing connection 0
```

What looks a bit different is my Ingress resource:

```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: my-cluster-kafka-bootstrap
  namespace: myproject
  selfLink: >-
    /apis/extensions/v1beta1/namespaces/myproject/ingresses/my-cluster-kafka-bootstrap
  uid: 2174949a-937f-449c-9897-ba14876a60c4
  resourceVersion: '11568'
  generation: 1
  creationTimestamp: '2019-09-21T20:48:49Z'
  labels:
    app: my-cluster
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kafka-bootstrap
  annotations:
    ingress.kubernetes.io/ssl-passthrough: 'true'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
  ownerReferences:
    - apiVersion: kafka.strimzi.io/v1beta1
      kind: Kafka
      name: my-cluster
      uid: 31b96c1a-bd50-4ca9-abc5-cffdeb90f121
      controller: false
      blockOwnerDeletion: false
spec:
  tls:
    - hosts:
        - kafka-bootstrap.mydomain.cz
  rules:
    - host: kafka-bootstrap.mydomain.cz
      http:
        paths:
          - path: /
            backend:
              serviceName: my-cluster-kafka-external-bootstrap
              servicePort: 9094
status:
  loadBalancer:
    ingress:
      - hostname: >-
          xxxxxxxxxxxxxxxxxx.us-east-1.elb.amazonaws.com
```

I have the status with the LoadBalancer address where as your status is empty. TBH I'm not sure whether this mean that your Ingress controller for whatever reason ignores the resources created for the brokers or whether it is just some difference between the infrastructure. But IIRC I saw the status also for exmaple on Minishift.

If the Ingress controller doesn't know about the Ingress resources for some reason it would explain why does it give you the defaul backend website.

**Comment by scholzj** [comment]
Just FYI: I'm using Nginx 0.25.1 as Ingress Controller.

**Comment by valentinPierdet** [comment]
Kafka : v2.3
Kafka operator: v0.13.0
Ingress-NGINX: v0.25.1
Nginx: v1.15.8.1

I have not find the issue on Minishift neither on openshift.
I'm using the same version of nginx. Can i see your the deployment file of your kafka cluster ?

Here is the log of my Ingress-controller : 
![git](https://user-images.githubusercontent.com/54103242/65531774-f5e31100-defa-11e9-8da1-237e2780e4ea.png)
I don't know what is the problem with the endpoint, my services do exist and have endpoints.

Just FYI:
![getall](https://user-images.githubusercontent.com/54103242/65532165-a3eebb00-defb-11e9-94d8-d066c372a35e.png)

**Comment by scholzj** [comment]
This is the Kafka resource I'm using. I only changed the `mydomain.cz`. I tried it also without the authentication and both worked for me.

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app: my-cluster
spec:
  kafka:
    replicas: 3
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: "1"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
      gcLoggingEnabled: false
    listeners:
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: tls
      external:
        type: ingress
        authentication:
          type: tls
        configuration:
          bootstrap:
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: bootstrap.mydomain.cz.
              external-dns.alpha.kubernetes.io/ttl: "60"
            host: bootstrap.mydomain.cz
          brokers:
          - broker: 0
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: broker-0.mydomain.cz.
              external-dns.alpha.kubernetes.io/ttl: "60"
            host: broker-0.mydomain.cz
          - broker: 1
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: broker-1.mydomain.cz.
              external-dns.alpha.kubernetes.io/ttl: "60"
            host: broker-1.mydomain.cz
          - broker: 2
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: broker-2.mydomain.cz.
              external-dns.alpha.kubernetes.io/ttl: "60"
            host: broker-2.mydomain.cz
    authorization:
      type: simple
      superUsers:
        - CN=my-connect
        - my-connect
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: "0.3"
      limits:
        memory: 1Gi
        cpu: "0.5"
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
      gcLoggingEnabled: false
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: true
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 256Mi
          cpu: "0.2"
        limits:
          memory: 256Mi
          cpu: "0.5"
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "0.2"
        limits:
          memory: 512Mi
          cpu: "0.5"
  clusterCa:
    validityDays: 1000
  clientsCa:
    validityDays: 1000
```

**Comment by Amojow** [comment]
Hello , 
I have the same configurations as @valentinPierdet for my kafka cluster and my nginx ingress controller.
I first tried to reach my bootstrap server service with a curl command, and i also had the 502 bad gateway error. 
Then, i tried with a "hello-world producer" with this configuration :
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-producer
  name: hello-world-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-producer
  template:
    metadata:
      labels:
        app: hello-world-producer
    spec:
      hostAliases:
      - ip: "10.10.1.8"
        hostnames:
        - "ca-cluster"
      containers:
      - name: hello-world-producer
        image: strimzi/hello-world-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: ca-cluster:31011
          - name: TOPIC
            value: logs
          - name: DELAY_MS
            value: "1000"
          - name: LOG_LEVEL
            value: "INFO"
          - name: CA_CRT
            valueFrom:
              secretKeyRef:
                name: my-cluster-ca-cert
                key: ca.crt
          - name: USER_CRT
            valueFrom:
              secretKeyRef:
                name: producer-user
                key: user.crt
          - name: USER_KEY
            valueFrom:
              secretKeyRef:
                name: producer-user
                key: user.key
```

And i had the following error : 
```
2019-11-26 13:37:43 INFO  KafkaProducerExample:33 - Sending 10 messages ...
2019-11-26 13:37:43 INFO  KafkaProducerExample:35 - Sending messages "Hello world - 0"
537 [kafka-producer-network-thread | producer-1] INFO org.apache.kafka.common.network.Selector - [Producer clientId=producer-1] Failed authentication with ca-cluster/10.10.1.8 (SSL handshake failed)
539 [kafka-producer-network-thread | producer-1] ERROR org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Connection to node -1 (ca-cluster/10.10.1.8:31011) failed authentication due to: SSL handshake failed
```
It seems like the **ssl passthrough** is not working at all, because the client here needs the nginx-controller CA certificate. 

Any ideas ?

**Comment by scholzj** [comment]
@Amojow How does your Kafka CR look like? You can probably edit the examples and add TLS debug to the Java client. But also `ca-cluster:31011` is a bit weird address for Ingress access. Are you shure this is where you Ingress exposes HTTPS and that this is the right URL?

**Comment by Amojow** [comment]
This is my Kafka CR : 
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my
spec:
  kafka:
    version: 2.3.0
    replicas: 3
    listeners:
      tls:
        authentication:
          type: tls
      external:
        type: ingress
        configuration:
          bootstrap:
            host: ca-cluster
          brokers:
          - broker: 0
            host: broker-0.bdi
          - broker: 1
            host: broker-1.bdi
          - broker: 2
            host: broker-2.bdi
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      spec:
        watchedNamespace: kafka
        image: docker.io/strimzi/operator:latest
    userOperator:
        watchedNamespace: kafka
        image: docker.io/strimzi/operator:latest
```

I know it's a weird address for Ingress access, it was just for a test but i named it bootstrap.bdi before and i had the same result. 
Yes i checked it's the HTTPS port, and i tried reaching the nginx-ingress-controller service with the cluster-ip address on port 443, and with one of my cluster node address (10.10.1.8) on port https (31011).
