### ISSUE TITLE
[Enhancement] Allow injection of arbitrary JAR files in classpath

### ISSUE THREAD

**Issue by forsberg** [strimzi/strimzi-kafka-operator#2124]
**Is your feature request related to a problem? Please describe.**
In my Kubernetes cluster, I log everything to a central Graylog instance. To get the best experience, these logs should be sent using the GELF protocol. Unfortunately, it's not possible to inject the JAR files required to get support for sending GELF messages in log4j.

**Describe the solution you'd like**
Possible solutions:

1. Allow mounting configmaps in arbitrary locations of the Kafka pod. This will work for adding small JAR files, and in my particular case the JAR file is 179KiB, so no problem.
2. Allow defining additional initContainer that could mount a configmap, download from maven, whatever, and move the JAR to the right location.

**Describe alternatives you've considered**
Rebuilding the Docker container of Strimzi Kafka is too much work for such a small modification.

**Comment by redsk** [comment]
@scholzj does it work along with KafkaConnect image build? For instance, can I specify the `from` image for KafkaConnect build?

**Comment by scholzj** [comment]
Well, Kafka Connect build works only for Kafka Connect. Plus it does some sandboxing I think. So it might not work with Log4j. The easiest way is probably to write your Dockerfile which starts with something like `FROM quay.io/strimzi/kafka:0.28.0-kafka-3.1.0` (depending on the Kafka and Strimzi versions you use) and then you just add your JAR to Kafka`s  `libs` directory. You build it, push it into some container repository and then you can edit the Cluster Operator deployment to tell it to use this image -> the images are configured in environment variables like this: https://github.com/strimzi/strimzi-kafka-operator/blob/04bf7af222fd9043b0cd83692638eaa501955c3e/install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml#L58.

**Comment by redsk** [comment]
@scholzj thanks for your answer. Adding the jars in the docker image makes sense.

Are `STRIMZI_KAFKA_CONNECT_IMAGES` the base images used for the Kafka Connect build? 
```yaml
            - name: STRIMZI_KAFKA_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka:0.28.0-kafka-3.0.0
                3.1.0=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |
                3.0.0=quay.io/strimzi/kafka:0.28.0-kafka-3.0.0
                3.1.0=quay.io/strimzi/kafka:0.28.0-kafka-3.1.0
```

If not, I've seen it's still possible to put files in arbitrary positions during the build, like so
```yaml
    plugins:
      - name: sentry
        artifacts:
        - type: other
          url: https://repo1.maven.org/maven2/io/sentry/sentry/1.7.30/sentry-1.7.30.jar
          fileName: ../../../libs/sentry-1.7.30.jar
        - type: other
          url: https://repo1.maven.org/maven2/io/sentry/sentry-log4j/1.7.30/sentry-log4j-1.7.30.jar
          fileName: ../../../libs/sentry-log4j-1.7.30.jar
```

Then set 
```yaml
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "INFO, CONSOLE, Sentry"
      log4j.appender.Sentry: io.sentry.log4j.SentryAppender
      log4j.appender.Sentry.threshold: WARN
```
and 
```yaml
  template:
    connectContainer:
      env:
        - name: SENTRY_DSN
           value: <your sentry dsn>
```

I'll admit it's a bit hackish, but yeah, it works.
