### ISSUE TITLE
[Question] How do I specify a KafkaUser that has access to all topics and is authorized to create new topics?

### ISSUE THREAD

**Issue by LeonardAukea** [strimzi/strimzi-kafka-operator#2141]
Does anyone know how I could create a 'super' KafkaUser that is allowed to create topics and can operate on all topics? 

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: super-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  type: allow
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: *
          patternType: literal
        operation: All
```

I've been trying to get a faust worker (https://faust.readthedocs.io/en/latest/) up and running but it fails:
```
kafka.errors.TopicAuthorizationFailedError: [Error 29] TopicAuthorizationFailedError: Cannot create topic: faust-app-__assignor-__leader (29): Authorization failed.
``` 
According to the strimzi config the creation of topics should be allowed. But i think the name of the topic that faust want to create is not  very valid due to the underscores. Either way,I'm not really sure how to go about this but I would like to able to specify a user that has access to all topics. Any help is much appreciated.

**Comment by scholzj** [comment]
I will need to look at what exacty is the problem here. In the meantime, you can configure the user as an super user: https://strimzi.io/docs/latest/full.html#super_users

**Comment by scholzj** [comment]
Ok, I had a look at this ... The YAML as you have it above doesn't work for me. It complains about the `*`. It looks like I need to do this to have it accepted:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: super-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  type: allow
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: All
```

But once I change that, it seems to work and I can create the topic:

```
$ bin/kafka-topics.sh --bootstrap-server my-cluster-kafka-bootstrap-myproject.192.168.64.126.nip.io:443 --command-config ./topics-config.properties --create --topic faust-app-__assignor-__leader --partitions 3 --replication-factor 3
WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both.
$ bin/kafka-topics.sh --bootstrap-server my-cluster-kafka-bootstrap-myproject.192.168.64.126.nip.io:443 --command-config ./topics-config.properties --describe
Topic:faust-app-__assignor-__leader	PartitionCount:3	ReplicationFactor:3	Configs:
	Topic: faust-app-__assignor-__leader	Partition: 0	Leader: 0	Replicas: 0,1,2	Isr: 0,1,2
	Topic: faust-app-__assignor-__leader	Partition: 1	Leader: 1	Replicas: 1,2,0	Isr: 1,2,0
	Topic: faust-app-__assignor-__leader	Partition: 2	Leader: 2	Replicas: 2,0,1	Isr: 2,0,1
```

I do not really use Faust for anything so I cannot try it with that. Maybe it triggers some other rights than the `kafka-topics` tool. But maybe the `*` is the issue?

**Comment by LeonardAukea** [comment]
@scholzj  Thanks for looking into this. Sorry for not being clear enough. I never used the '*' syntax. I just thought that it might be the way it should be used (Following kubernetes syntax). Thanks for pointing me to the right location in the docs.  Could you please share your super user config.  In the meantime, I will try following the description in the docs.

**Comment by scholzj** [comment]
Well, funny enough at least for creating the topic, it actually works as you described it there with the only exception off wrapping the `*`. But it is not a real super user - this gives the user only all rights to topics. But not to consumer groups, cluster resources etc. So for an actual super user, you should foolow the docs I pointed out.

**Comment by LeonardAukea** [comment]
hehe. Yeah I will probably create a superuser for all the faust applications just in case. Just to clarify, since I'm not sure that I follow the docs completely. 

1. Create a KafkaUser 

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: super-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  type: allow
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: All
```

2. Add the user to the spec 

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
spec:
  kafka:
    # ...
    authorization:
      type: tls
      superUsers:
        - CN=super-user
    # ...
  zookeeper:
    # ...
```

**Comment by scholzj** [comment]
You do not have to specify the ACLs for the user when setting it as super user. I would do it like this:

1. Set the user as super user:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
spec:
  kafka:
    # ...
    authorization:
      type: tls
      superUsers:
        - CN=super-user
    # ...
  zookeeper:
    # ...
```

2. Create the user with `authentication` only:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: super-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
```

**Comment by LeonardAukea** [comment]
Thanks. It worked either way :)

**Comment by scholzj** [comment]
Yeah, the order doesn't matter so much. But the user needs to wait for the brokers to be updated, that is all. Can we close this issue? Or do you have something more?

**Comment by LeonardAukea** [comment]
No we can close it Thank you for your help! much appreciated

**Comment by alokhom** [comment]
Am facing this problem from an external Camel Kafka app onto Strimzi over Openshift.
TopicAuthorizationException - Not authorized to access topics: [my-topic]

background :- 
I used the KafkaUser user.p12 keystore and ca.crt TrustStore in the App 


here is my Kafka config - 
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  creationTimestamp: '2020-08-25T14:38:29Z'
  generation: 6
  name: my-cluster
  namespace: kafka
  resourceVersion: '2105105'
  selfLink: /apis/kafka.strimzi.io/v1beta1/namespaces/kafka/kafkas/my-cluster
  uid: 984954e3-0c68-4ea0-a9e0-0d9e8f55f4a6
spec:
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
  kafka:
    authorization:
      superUsers:
        - CN=my-user
      type: simple
    config:
      log.message.format.version: '2.5'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      external:
        overrides:
          bootstrap:
            host: bootstrap.apps.kafka.cluster42.openshift-enfo.se
          brokers:
            - broker: 0
              host: broker-0.apps.kafka.cluster42.openshift-enfo.se
            - broker: 1
              host: broker-1.apps.kafka.cluster42.openshift-enfo.se
            - broker: 2
              host: broker-2.apps.kafka.cluster42.openshift-enfo.se
        type: route
      plain:
        authentiation:
          type: scram-sha-512
      tls:
        authentiation:
          type: tls
    replicas: 3
    storage:
      class: rook-ceph-block
      size: 20Gi
      type: persistent-claim
    version: 2.5.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
--
Kafka Topic
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  creationTimestamp: '2020-08-25T14:41:13Z'
  generation: 1
  labels:
    strimzi.io/cluster: my-cluster
  name: my-topic
  namespace: kafka
  resourceVersion: '1468960'
  selfLink: /apis/kafka.strimzi.io/v1beta1/namespaces/kafka/kafkatopics/my-topic
  uid: 52d65111-ba4f-49ad-bb56-1db93b35d60b
spec:
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
  partitions: 10
  replicas: 3
--

here is my KafkaUser - 
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  creationTimestamp: '2020-08-26T11:06:58Z'
  generation: 5
  labels:
    strimzi.io/cluster: my-cluster
  name: my-user
  namespace: kafka
  resourceVersion: '2104858'
  selfLink: /apis/kafka.strimzi.io/v1beta1/namespaces/kafka/kafkausers/my-user
  uid: 75bca2ad-690e-4e7c-94ef-57840c35ceea
spec:
  authentication:
    type: tls

**Comment by scholzj** [comment]
So when you say that you have an _external Apache Camel application_ ... that means it is running outside of OCP and connects using the routes? If that is the case the problem is that you have no authentication enabled for the external interface. So you configured `CN=my-user` as super user. But without enabling authentication on the listener the user will be authenticated as ANONYMOUS. You will need to add the authentication section also to the external listener:

```yaml
    listeners:
      external:
        overrides:
          bootstrap:
            host: bootstrap.apps.kafka.cluster42.openshift-abcd.com
          brokers:
            - broker: 0
              host: broker-0.apps.kafka.cluster42.openshift-abcd.com
            - broker: 1
              host: broker-1.apps.kafka.cluster42.openshift-abcd.com
            - broker: 2
              host: broker-2.apps.kafka.cluster42.openshift-abcd.com
        type: route
        authentiation:
          type: tls
      plain:
        authentiation:
          type: scram-sha-512
      tls:
        authentiation:
          type: tls
```
