### ISSUE TITLE
[Question] Can't connect via LoadBalancer

### ISSUE THREAD

**Issue by dcrdev** [strimzi/strimzi-kafka-operator#2145]
I'm having some difficulty connecting to the cluster when exposed via a load balancer, I've read the documentation top to bottom and can't spot anything obviously wrong with my deployments.

I'm getting the following error from clients:
```
% ERROR: Failed to query metadata for topic [TOPIC]: Local: Broker transport failure
```

Now I have increased verbosity and enabled debug client side, but I'm not getting anything more than that; which to me would indicate that it's not able to connect at all.

I can telnet to the bootstrap address fine, my current working theory is that maybe the clients send a keep alive ping to the brokers, in which case Azure Load Balancers do not support icmp packets. I could be completely off base with that one, so would value anyone's input.

Aside from that here are my manifests:
```yaml
MANIFEST:

---
# Source: sdi-data-pipelines/templates/cluster-deployment.yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  labels:
    app: sdi-data-pipelines
    component: cluster
    chart: sdi-data-pipelines-0.1.8
    release: billowing-beetle
    heritage: Tiller
  name: "billowing-beetle-cluster"
  namespace: "pipelines"
spec:
  kafka:
    version: 2.3.0
    replicas: 3
    authorization:
      type: simple
      superUsers:
        - CN=sdadmin
    listeners:
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: tls
      external:
        type: loadbalancer
        tls: true
        authentication:
          type: tls
        overrides:
          bootstrap:
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: billowing-beetle-bootstrap.[REDACTED].io
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
              address: billowing-beetle-bootstrap.[REDACTED].io
          brokers:
          
          - broker: 0
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: billowing-beetle-broker-0.[REDACTED].io
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            advertisedHost: billowing-beetle-broker-0.[REDACTED].io
          
          - broker: 1
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: billowing-beetle-broker-1.[REDACTED].io
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            advertisedHost: billowing-beetle-broker-1.[REDACTED].io
          
          - broker: 2
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: billowing-beetle-broker-2.[REDACTED].io
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            advertisedHost: billowing-beetle-broker-2.[REDACTED].io
          
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: 2.3
    storage:
      type: jbod
      volumes:
      
      - id: 0
        type: persistent-claim
        size: 100Gi
        class: managed-premium
        deleteClaim: true
      
      - id: 1
        type: persistent-claim
        size: 100Gi
        class: managed-premium
        deleteClaim: true
      
      - id: 2
        type: persistent-claim
        size: 100Gi
        class: managed-premium
        deleteClaim: true
      
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      class: managed-premium
      deleteClaim: true
  entityOperator:
    topicOperator:
      watchedNamespace: "pipelines"
      reconciliationIntervalSeconds: 60
    userOperator:
      watchedNamespace: "pipelines"
      reconciliationIntervalSeconds: 60
---
# Source: sdi-data-pipelines/templates/kafka-topics.yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: unstructured.nsbsales
  labels:
    app: sdi-data-pipelines
    component: pipelines
    chart: sdi-data-pipelines-0.1.8
    release: billowing-beetle
    heritage: Tiller
    strimzi.io/cluster: "billowing-beetle-cluster"
  namespace: "pipelines"
spec:
  topicName: [TOPIC]
  config:
    cleanup.policy: delete
    compression.type: snappy
    min.insync.replicas: 2
  partitions: 3
  replicas: 3
---
# Source: sdi-data-pipelines/templates/cluster-superuser.yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: sdadmin
  labels:
    app: sdi-data-pipelines
    component: cluster
    chart: sdi-data-pipelines-0.1.8
    release: billowing-beetle
    heritage: Tiller
    strimzi.io/cluster: "billowing-beetle-cluster"
  namespace: "pipelines"
spec:
  type: allow
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operation: All
```

^ Again would highly value anyone's input as to things I may have missed.

Many Thanks!
