### ISSUE TITLE
Our own metrics examples do not scrape the Kafka Exporter

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2193]
We added Kafka Exporter to provide addiitonal metrics. But it seems that our own example files for configuring the Prometheus operator and our docs do configure it to scrape these metrics. Based on a Slack discussion (https://cloud-native.slack.com/archives/CMH3Q3SNP/p1573775472031900), following option can help to scrape it:

```yaml
  additionalServiceMonitors:
    - name: "kafka-exporter"
      selector:
        matchLabels:
          strimzi.io/name: my-cluster-kafka-exporter
      namespaceSelector:
        any: true
      endpoints:
        - port: metrics
          interval: 10s
          path: /metrics
```

We should incorporate this into our examples and docs.
