### ISSUE TITLE
[Bug] KafkaCrdITs do not check if exception is thrown by invalid CR

### ISSUE THREAD

**Issue by tomncooper** [strimzi/strimzi-kafka-operator#2229]
The current `io.strimzi.api.kafka.model.Kafka*CrdIT` tests are not actually checking if an invalid CR actually throws an exception, they only performed the assertion check if one is thrown and will pass if no exception is thrown. 

I have added those checks and a couple of invalid Kafka CR do not throw exceptions.

For example `KafkaCrdIT#testKafkaWithInvalidResourceMemory` tries to deploy a cluster with:
```
spec:
  kafka:
    replicas: 3
    image: "strimzi/kafka:latest"
    resources:
      limits:
        memory: "5GiFooBar"
```

Which does not throw an error when deployed because the `install/cluster/040-Crd-kafka.yaml` expects a generic object so the invalid memory string is fine:

```
resources:
    type: object
    properties:
        limits:
            type: object
        requests:
            type: object
```

This is due to the `io.fabric8.kubernetes.api.model.ResourceRequirements` in the `KafkaClusterSpec` class having no `Pattern` annotations. By contrast our `io.strimzi.api.kafka.model.JvmOptions` defines `@Pattern` for any memory field.

**My question is**: Do the limits need to be validated? If so what kind of fields should we expect? If we do need to validate we will need to extend the Fabric8 class. 

If we are not wanting to validate the resource limits then this test will need to be removed.

More confusingly is the `KafkaUserCrdIT#testKafkaUserWithMissingRequired` which tries to deploy:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: missing-required
spec:
  {}
```
Which throws no error when deployed? Looking at `install/cluster-operator/044-Crd-kafkauser.yaml` I can't see what the issue is?
