### ISSUE TITLE
[Question] How do I specify public certs for external connection ?

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#2233]
If I'm configuring strimzi with external endpoints: 
```
      external:
        type: loadbalancer
        tls: true
        authentication:
          type: oauth
          clientId: broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          disableTlsHostnameVerification: false
          jwksEndpointUri: https://REDACTED/auth/realms/demo/protocol/openid-connect/certs
          validIssuerUri: https://REDACTED/auth/realms/demo
          userNameClaim: preferred_username
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: ca.crt
```
Is there a way to specifying a public cert for the listener?  I'd like to terminate TLS with the internal cert and use a public cert for TLS customer connection?
