### ISSUE TITLE
[Bug] Ingress Class Ignored

### ISSUE THREAD

**Issue by rewt** [strimzi/strimzi-kafka-operator#2235]
**Describe the bug**
external:
  class: nginx-internal

Above config not being recognized in kafka definition

**To Reproduce**
add `class: nginx-ingress` to kafka definition

**Expected behavior**
ingresses created on specified nginx controller (internal)

**Environment (please complete the following information):**
 - Strimzi version: 2.3.0
 - Installation method: operator installed with helm, kafka with yaml
 - Kubernetes cluster: 1.14

**YAML files and logs**
Defined class here 
```
      external:
        type: ingress
        class: nginx-internal
        configuration:
          bootstrap:
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: bootstrap.example.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
            host: bootstrap.exmple.com
```
nginx controller logs
```
I1122 14:40:25.536144       6 store.go:347] ignoring add for ingress hk-kafka-kafka-bootstrap based on annotation kubernetes.io/ingress.class with value
I1122 14:40:25.553961       6 store.go:347] ignoring add for ingress hk-kafka-kafka-0 based on annotation kubernetes.io/ingress.class with value
I1122 14:40:25.557664       6 store.go:347] ignoring add for ingress hk-kafka-kafka-1 based on annotation kubernetes.io/ingress.class with value
I1122 14:40:25.557688       6 store.go:347] ignoring add for ingress hk-kafka-kafka-2 based on annotation kubernetes.io/ingress.class with value
```
ingress definition created from yaml
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: broker-0.example.com.
    external-dns.alpha.kubernetes.io/ttl: "60"
    ingress.kubernetes.io/ssl-passthrough: "true"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
```

**Comment by scholzj** [comment]
I tried this with master as well as with Strimzi 0.14.0. But it seems to work fine for me in both cases:

```yaml
      listeners:
        external:
          class: nginx-internal
          configuration:
            # ...
          type: ingress
```

Gives me Ingress resources witht he right annotation.

```yaml
  apiVersion: extensions/v1beta1
  kind: Ingress
  metadata:
    annotations:
      # ...
      kubernetes.io/ingress.class: nginx-internal
    # ...
```

Strange is that oyur YAML looks the same, so I do not know why it didn't worked for you.
