### ISSUE TITLE
[Bug] Strimzi and AMQ Streams operators define the same kind, name and version

### ISSUE THREAD

**Issue by radtriste** [strimzi/strimzi-kafka-operator#2265]
Hello!

We're using Strimzi Operator as a dependency for our own operator and sometimes OLM installs AMQ Streams instead of Strimzi. This is happening because both define the same kind, name and version:

```
  required:
    - description: Represents a Kafka cluster
      displayName: Kafka
      kind: Kafka
      name: kafkas.kafka.strimzi.io
      version: v1beta1
    - description: Represents a topic inside a Kafka cluster
      displayName: Kafka Topic
      kind: KafkaTopic
      name: kafkatopics.kafka.strimzi.io
      version: v1beta1
```

Is it possible to have different kind for AMQ Streams ? That way we can differentiate from the upstream/downstream projects.

We add it as a dependency in the [operator](https://github.com/kiegroup/kogito-cloud-operator/blob/master/deploy/olm-catalog/kogito-cloud-operator/0.6.0/kogito-cloud-operator.v0.6.0.clusterserviceversion.yaml#L214-L220) manifest and there is no way to set the exact operator we want.
Here's more info about OLM dependency management: https://github.com/operator-framework/operator-lifecycle-manager#dependency-resolution

This goes in the same way as https://github.com/strimzi/strimzi-kafka-operator/issues/1247

**Expected behavior**
I would like to have Strimzi installed and not AMQ Streams.

**Environment:**
 - Strimzi version: 0.14.0 (AMQ Streams 1.3.0)
 - Installation method: OperatorHub.io
 - Kubernetes cluster: OpenShift 4.2
 - Infrastructure: CRC
