### ISSUE TITLE
[Enhancement] Allow inter-broker TLS to be disabled

### ISSUE THREAD

**Issue by dalelane** [strimzi/strimzi-kafka-operator#2266]
**Is your feature request related to a problem? Please describe.**
Disabling TLS for Kafka's inter-broker connections would improve the performance. For installs where security isn't a concern, such as those running on private isolated secure clusters, inter-broker TLS may not be needed.

We'd like a way to disable TLS for these cases, so users can decide whether they want to prioritise performance or security.

**Describe the solution you'd like**
A new boolean attribute in KafkaClusterSpec that enables/disables inter-broker TLS. 

e.g. 

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.3.1
    replicas: 3
    interBrokerTls: false
```

The new attribute would default to `true` to maintain current behaviour. Existing CR definitions need not be affected, but there would be an option here to edit an existing cluster by setting this to `false`. (Rolling updates that modify this would require persistence, as new brokers wouldn't be able to talk to the previous generation brokers so replication wouldn't be possible during the rolling upgrade.)

**Describe alternatives you've considered**
Alternatively, we could treat this as a new type of listener, that can be configured - calling it something like `interbroker` or `replication`:

e.g.
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.3.1
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      interbroker:
        tls: false
```

If we think we'll ever want to make other configuration changes to the inter-broker listeners, this might be a preferable approach. Plus, semantically it feels like a good fit to configure it here rather than as an attribute of the Kafka cluster overall. 

**Additional context**
None.

**Comment by scholzj** [comment]
I think the `spec.kafka.listeners.interbroker` looks good in the current API state - it fits well and allows to add more options in the future. However, we had some thoughts (and user requests) about giving users more freedom to define the listeners. E.g. to change to something more "free":

```yaml
listeners:
 - name: plain
    type: internal
    port: 9092
    tls: false
    authentication:
      type: scram-sha522
 - name: tls
    type: internal
    tls: true
    port: 9093
    authentication:
      type: tls
 - name: external1
    type: external
    tls: true
    port: 9094
    authentication:
      type: tls
 - name: external2
    type: external
    tls: true
    port: 9095
    authentication:
      type: tls
```

And I'm not sure how well it would fit in here. Maybe having it as `spec.kafka.interbroker` would be better to cover this?

I personally would wonder if we should call it `replication` rather than `interbroker`, but no storng feelings about. Also, would this cover everything - including Zookeeper encryption?

CC @tombentley
