### ISSUE TITLE
[Bug] ... create kafkatopic failed in openshift3.11

### ISSUE THREAD

**Issue by MQluna** [strimzi/strimzi-kafka-operator#2272]
**Describe the bug**
1、oc apply 
010-ServiceAccount-strimzi-cluster-operator.yaml
020-ClusterRole-strimzi-cluster-operator-role.yaml
020-RoleBinding-strimzi-cluster-operator.yaml
021-ClusterRoleBinding-strimzi-cluster-operator.yaml
021-ClusterRole-strimzi-cluster-operator-role.yaml
030-ClusterRoleBinding-strimzi-cluster-operator-kafka-broker-delegation.yaml
030-ClusterRole-strimzi-kafka-broker.yaml
031-ClusterRole-strimzi-entity-operator.yaml
031-RoleBinding-strimzi-cluster-operator-entity-operator-delegation.yaml
032-ClusterRole-strimzi-topic-operator.yaml
032-RoleBinding-strimzi-cluster-operator-topic-operator-delegation.yaml
040-Crd-kafka.yaml
041-Crd-kafkaconnect.yaml
042-Crd-kafkaconnects2i.yaml
043-Crd-kafkatopic.yaml
044-Crd-kafkauser.yaml
045-Crd-kafkamirrormaker.yaml
046-Crd-kafkabridge.yaml
047-Crd-kafkaconnector.yaml
050-Deployment-strimzi-cluster-operator.yaml

2、create kafka
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}

pod status normal
my-cluster-entity-operator-8cc945844-ldqhp   3/3       Running   0          14m
my-cluster-kafka-0                           2/2       Running   0          14m
my-cluster-kafka-1                           2/2       Running   0          14m
my-cluster-kafka-2                           2/2       Running   0          14m
my-cluster-zookeeper-0                       2/2       Running   0          15m
my-cluster-zookeeper-1                       2/2       Running   0          15m
my-cluster-zookeeper-2                       2/2       Running   0          15m
strimzi-cluster-operator-ddbbc8f8c-4tp8t     1/1       Running   0          2h

3、oc logs -f  my-cluster-entity-operator-8cc945844-ldqhp -c topic-operator shows warn:

INFO  <adataManager:238> [dminclient-1] [AdminClient clientId=adminclient-1] Metadata update failed
org.apache.kafka.common.errors.TimeoutException: Timed out waiting to send the call

WARN  <etworkClient:748> [dminclient-1] [AdminClient clientId=adminclient-1] Connection to node -1 (my-cluster-kafka-bootstrap/172.30.161.146:9091) could not be established. Broker may not be available.

4、create kafkatopic 
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: lines
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 2
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824

then run ' bash kafka-topics.sh --list --zookeeper localhost:2181' in the kafka pod
show nothing ,the topic created failed.
but  i can create topic manually.

5、oc logs -f  my-cluster-entity-operator-8cc945844-ldqhp -c topic-operator shows warn:

[2019-12-03 13:13:08,237] INFO  <TopicWatcher:43> [2.30.0.1/...] 1|kube =lines|29726560: event MODIFIED on resource lines generation=1, labels={strimzi.io/cluster=my-cluster}
[2019-12-03 13:13:08,248] WARN  <onUsageUtils:60> [s-ops-tool-0] The client is using resource type 'kafkatopics' with unstable version 'v1beta1'
[2019-12-03 13:15:08,416] ERROR <TopicWatcher:56> [oop-thread-1] 1|kube =lines|29726560: Failure processing KafkaTopic watch event MODIFIED on resource lines with labels {strimzi.io/cluster=my-cluster}: Timed out waiting for a node assignment.
org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
[2019-12-03 13:15:08,427] WARN  <opicOperator:105> [oop-thread-1] Failure processing KafkaTopic watch event MODIFIED on resource lines with labels {strimzi.io/cluster=my-cluster}: Timed out waiting for a node assignment.

**T'o Reproduce**
2. Create Custom Resource '....'
3. Run command '....'

**Expected behavior**

**Environment (please complete the following information):**
 - Strimzi version: [e.g. master, 0.11.1]
 - Installation method: [e.g. YAML files, Helm chart, OperatorHub.io]
 - Kubernetes cluster: [e.g. Kubernetes 1.14, OpenShift 3.9]
 - Infrastructure: [e.g. Amazon EKS, Minikube]

**YAML files and logs**

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/master/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh [--namespace <string>] [--cluster <string>]`*

**Additional context**

**Comment by scholzj** [comment]
This is weird. Looks like the Topic Operator cannot connect to KAfka. 

@tombentley @stanlyDoge Any ideas?

**Comment by tombentley** [comment]
I agree that it looks like a connection problem between TO and bootstrap server/a broker, but no idea what might be the cause without more info. @MQluna can you reliably (and repeatably) connect to the brokers from other clients?

**Comment by MQluna** [comment]
@scholzj @tombentley 
i think its network problem
after i create a networkpolicy, everything is ok.

allow-all.yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"NetworkPolicy","metadata":{"annotations":{},"name":"allow-all","namespace":"kafkaoperator"},"spec":{"ingress":[{}],"podSelector":{},"policyTypes":["Ingress"]}}
  creationTimestamp: 2019-12-04T03:42:34Z
  generation: 1
  name: allow-all
  namespace: kafkaoperator
  resourceVersion: "121008557"
  selfLink: /apis/extensions/v1beta1/namespaces/kafkaoperator/networkpolicies/allow-all
  uid: 1b5c4565-1648-11ea-8c5d-005056b688c3
spec:
  ingress:
  - {}
  podSelector: {}
  policyTypes:
  - Ingress

**Comment by tombentley** [comment]
It shouldn't be necessary to create a NetworkPolicy for the TO (when deployed by the CO) to work.

**Comment by scholzj** [comment]
I never heard about network policy issue whicih would involve the TO. At least assuming the TO was deployed as part of the Kafka CR and not separately.

**Comment by tombentley** [comment]
@MQluna is it possible to check the CO logs to see whether there was some issue with the CO creating the NetworkPolicies?

**Comment by nylend95** [comment]
Hi, I have the same issue. I can see that the network policy for the kafka pods created by the CO does not contain the port 9091. The port 9091 is what is configured in the TO for communication with the Kafka pods. 
Wondering if the port 9091 should be included in the network policy (`my-cluster-network-policy-kafka`). I added a netpol only for allowing port 9091 on for the kafka pods, and the TO started working immediately. 

The netpol I added:
```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: extra-kafka-netpol
  namespace: kafka-operator
  generation: 1
spec:
  podSelector:
    matchLabels:
      strimzi.io/name: my-cluster-kafka
  ingress:
    - ports:
        - protocol: TCP
          port: 9091
  policyTypes:
    - Ingress
```
The TO in my case was deployed as a part of the Kafka cluster

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: first-cluster 
spec:
  kafka:
    version: 2.4.0
    replicas: 3
    listeners:
      plain: {}
      tls: 
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.4"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

 Versions used:
OpenShift v3.11.82
Kubernetes v1.11.0+d4cacc0
Strimzi commit used: 0768cd5af779c1f00b5a7188412cfe7113a13934
