### ISSUE TITLE
Adding per pod anti-affinity to cluster with rack previously defined fails

### ISSUE THREAD

**Issue by gamer22026** [strimzi/strimzi-kafka-operator#2280]
**Describe the bug**
Adding a per pod anti-affinity stanza to a Kafka cluster spec that already has a rack property defined results in a bad affinity stanza, leading to the kafka brokers not restarting during a rolling restart

**To Reproduce**
1. Create kafka cluster with a rack property defined. This will create an preferredDuringSchedulingIgnoredDuringExecution anti-affinity section in the statefulset.
2. Once cluster if fully up, modify it by adding a per pod anti-affinity rule as outlined here: https://strimzi.io/docs/latest/#configuring-pod-anti-affinity-in-kafka-components-deployment-configuration-kafka-scheduling-based-on-pods
3. Look at the resultant kafka stateful set and see that the affinity section is incorrect:
```   
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  strimzi.io/cluster: kafka-cluster
                  strimzi.io/name: kafka-name
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: ""
```
4. Now comment out the rack section and re-apply. Notice the affinity section in the statefulset is now correct for per pod anti-affinity.
```
     affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: strimzi.io/name
                operator: In
                values:
                - kafka-name
            topologyKey: kubernetes.io/hostname
```
5. Once cluster is fully up, re-enable the rack settings and re-apply. Notice the affinity section in the stateful set is now correct for both rack and per pod anti-affinity:
```
     affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  strimzi.io/cluster: kafka-cluster
                  strimzi.io/name: kafka-name
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: strimzi.io/name
                operator: In
                values:
                - kafka-name
            topologyKey: kubernetes.io/hostname
```
**Expected behavior**
Adding a per pod anti-affinity to an existing kafka cluster where a rack was already defined should correctly add the additional settings.

**Environment (please complete the following information):**
 - Strimzi version: 0.15.0
 - Installation method: Helm chart for operator, yaml for kafka cluster
 - Kubernetes cluster: Kubernetes 1.11
 - Infrastructure: AWS
