### ISSUE TITLE
Define selector in persistent storage override field

### ISSUE THREAD

**Issue by dobl1** [strimzi/strimzi-kafka-operator#2316]
**Is your feature request related to a problem? Please describe.**
As described here [PersistentClaimStorageOverride](https://strimzi.io/docs/latest/#type-PersistentClaimStorageOverride-reference)
Only the storage class can be overridden, would be nide to have also the selector
In my case to override the PVC name for each kafka/zoo instance

**Describe the solution you'd like**
```yaml
    storage:
      type: persistent-claim
      size: 50Gi
      class: nas
      overrides:
        - broker: 0
          selector:
            alicloud-pvname: kafka-pv-0
        - broker: 1
            selector:
              alicloud-pvname: kafka-pv-1
```
