### ISSUE TITLE
[Question] Just use ACL operations in User Operation by not providing the authentication property in user cr

### ISSUE THREAD

**Issue by Frankiechan** [strimzi/strimzi-kafka-operator#2358]
Hello folks, as hosting CA outside of k8s, I would like to use user-operator just as an ACL manager; However, there are no docs to mention this kind of use-case; 
After reading the code, I found that it might be able to bypass the creds generation step by not providing the authentication field in my user custom resource instance; I tested it out and it works.

Not sure if it is an intended behavior but just not documented properly; if it is, I would like to raise a pr to improve the docs, otherwise, I would like to provide a feature toggle to support the ACL operations only without considering the CA part;

Please feel free to advise and thanks in advance!

Here is an Example:
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: "my-user"
spec:
  #authentication:
    #type: tls
  authorization:
    type: simple
    acls:
      - type: allow
        resource:
          type: topic
          name: my-topic
          patternType: prefix
        operation: Read
```
