### ISSUE TITLE
[Question] ...I am trying to implement TLS client authentication using Nodeport : SSL handshake error.

### ISSUE THREAD

**Issue by ami11singh** [strimzi/strimzi-kafka-operator#2398]
I would like to confirm the steps to perform this.

1. I have configured Kafka resource as below:
Snippet:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  namespace: my-kafka
  name: my-cluster
spec:
  kafka:
    version: 2.3.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: true
        authentication:
           type: tls 
        overrides:
          bootstrap:
            nodePort: 32100
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
    storage:
      type: persistent-claim
      class: applications
      size: 10Gi
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      class: applications
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

2. I created a Topic and a TLS authenticated user.
3. Created keystore truststore.jks using my-cluster-ca-cert.
4. Created keystore user.p12 using user.key and user.crt of the kafka user.
5. Used the below command from another kafka server to produce messages on the Topic:

bin/kafka-console-producer.sh --broker-list XX.XXX.X.XX:32100 --producer-property security.protocol=SSL --producer-property ssl.truststore.password=password --producer-property ssl.truststore.location=./truststore.jks  --producer-property ssl.keystore.password=password --producer-property ssl.keystore.location=./user.p12 --topic test

The address -XX.XXX.X.XX I am using here is the node of one of the broker pods. Is it the right address to use? Also please let me know if I am doing this right or missing something?
