### ISSUE TITLE
[Question] operator refuses to upgrade cluster due to it not reading log.message.format.version

### ISSUE THREAD

**Issue by jantebeest** [strimzi/strimzi-kafka-operator#2426]
Hi,

I've just upgraded the operator from 0.15.0 to 0.16.0 which caused a rolling update of the zookeeper pods, so far as expected. However, I get the message `You must explicitly set log.message.format.version: "2.3" in Kafka.spec.kafka.config to perform the upgrade`, even though it is set.

This is an excerpt of `kubectl -n kafka get kafka {cluster-name} -o yaml`:
```
spec:
  kafka:
    config:
      default.replication.factor: 3
      log.message.format.version: "2.3"
```

I also tried setting the version to "2.4.0" explicitly, but that does not help.

Am I missing something?
