### ISSUE TITLE
Integrate OAuth Authorization into Strimzi

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#2428]
This issue is about integrating into Strimzi the OAuth Authorization provided by Keycloak.
It's related to this https://github.com/strimzi/strimzi-kafka-oauth/pull/24 and providing the right CRD additions into the `Kafka` resource for enabling this type of authorization (other than the `simple` one already in place).
Authorization should have a new `keycloak` type and the related configuration parameters in the CRD.
Following a proposal for that.

```yaml
# ...
authorization:
  type: keycloak
  tokenEndpointUri: <URL of the Keycloak's token endpoint>
  clientId: <A client id of the OAuth client definition in Keycloak>
  delegateToKafkaAcls: false #if fallback to Simple authz if no access provided by Keycloak
  tlsTrustedCertificates:
     - secretName: oauth-server-cert
       certificate: ca.crt
  disableTlsHostnameVerification: false
  superUsers:
    - Alice
    - CN=Bob
```
