### ISSUE TITLE
[Bug] kafka cluster pods don't start

### ISSUE THREAD

**Issue by juangon** [strimzi/strimzi-kafka-operator#2449]
**Describe the bug**
When using strimzi operator to try to start a Kafka infrastructure, kafka cluster pods don't start.

**To Reproduce**
1. Create a separate namespace:
```shell
kubectl create namespace kafka    
```
2. Download strimzi YAML and create resources:
```shell
curl -L https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.16.0/strimzi-cluster-operator-0.16.0.yaml \
 | sed 's/namespace: .*/namespace: kafka/' \
 | kubectl apply -f - -n kafka
```
3.`kubectl apply`this file:
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.4.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.3'
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
3. `my-cluster-kafka-*` Pods doesn't start and keep restarting

**Expected behavior**
Kafka cluster pods starts properly.

**Environment:**
 - Strimzi version: 0.16.0
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes 1.17.0
 - Infrastructure: Minikube

**YAML files and logs**
Attached logs for my-cluster-kafka-0,my-cluster-kafka-1, zookeper and tls-sidecar from one zookeper Pod. (there are 3 pods)
[logs-from-kafka-in-my-cluster-kafka-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4107959/logs-from-kafka-in-my-cluster-kafka-0.txt)
[logs-from-kafka-in-my-cluster-kafka-1.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4107960/logs-from-kafka-in-my-cluster-kafka-1.txt) 

[logs-from-zookeeper-in-my-cluster-zookeeper-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4110760/logs-from-zookeeper-in-my-cluster-zookeeper-0.txt)
[logs-from-strimzi-cluster-operator-in-strimzi-cluster-operator-6f47f586f7-rlv96.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4110761/logs-from-strimzi-cluster-operator-in-strimzi-cluster-operator-6f47f586f7-rlv96.txt)
[logs-from-tls-sidecar-in-my-cluster-zookeeper-1.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4115857/logs-from-tls-sidecar-in-my-cluster-zookeeper-1.txt)
