### ISSUE TITLE
[Bug] Fail pod when change numbers of podes

### ISSUE THREAD

**Issue by tsyrfa** [strimzi/strimzi-kafka-operator#2494]
**Describe the bug**
When I change numbers of replica of kafka infrastructure one of pods can't to start after recreating (it always kafka-cluster-kafka-1)

**To Reproduce**

1. Create a separate namespace:
`kubectl create namespace kafka-test`

2. Install the cluster-operator (I pull the "cluster-operator" folder from your repo)
`kubectl apply -f .\cluster-operator`

3. Apply configure for kafka-cluster

```
apiVersion: kafka.strimzi.io/v1beta1
 kind: Kafka
 metadata:
  name: kafka-cluster
 spec:
   kafka:
     replicas: 3
     listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false

          
    storage:
      type: ephemeral
      
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1 
    
  zookeeper:
    replicas: 3
        
    storage:
      type: ephemeral
      
    entityOperator:
      topicOperator: {}
      userOperator: {}

```
4. Wait while it finished

5. Change numbers of replica for kafka and zookeeper:

```...
spec:
  kafka:
    replicas: 4
...
  zookeeper:
    replicas: 4
```

full configure is here:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    replicas: 4
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false

          
    storage:
      type: ephemeral
      
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1 
    
  zookeeper:
    replicas: 4
        
    storage:
      type: ephemeral
      
    entityOperator:
      topicOperator: {}
      userOperator: {}
```

6. `kafka-cluster-kafka-1` return error (it always number pod 1)

**Expected behavior**
All pods correct started, when I changed numbers of replica

**Environment (please complete the following information):**
 - Strimzi version: 0.16.0 and 0.16.2 
 - Installation method: YAML files
 - Kubernetes cluster:  Kubernetes 1.15
 - Infrastructure: "yandex cloud"

**YAML files and logs**

This is output after change numbers of replic
[get pod.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4143116/get.pod.txt)

Logs from crashed Kafka:
[kafka-cluster-kafka-1.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4143118/kafka-cluster-kafka-1.txt)

Logs from corrected started Kafka:
[kafka-cluster-kafka-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4143119/kafka-cluster-kafka-0.txt)

Logs from crashed Kafka tls-sidecar:
[kafka-cluster-kafka-1_tls-sidecar.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4143124/kafka-cluster-kafka-1_tls-sidecar.txt)

Logs from correct started Kafka tls-sidecar:
[kafka-cluster-kafka-0_tls-sidecar.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4143123/kafka-cluster-kafka-0_tls-sidecar.txt)

Logs from Zookeeper :
[kafka-cluster-zookeeper-0.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4143127/kafka-cluster-zookeeper-0.txt)

Logs from Zookeeper tls-sidecar :
[kafka-cluster-zookeeper-0-tls-sidecar.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4143128/kafka-cluster-zookeeper-0-tls-sidecar.txt)

**Additional context**
At first glance it looks like same bug:
https://github.com/strimzi/strimzi-kafka-operator/issues/2449
