### ISSUE TITLE
[Question] Setting java.library.path for kafka connect

### ISSUE THREAD

**Issue by mariusstaicu** [strimzi/strimzi-kafka-operator#2507]
Some connectors like debezium oracle need some native library for oci driver libocijdbc19.so. This needs to be specified via -Djava.library.path flag for jvm. How can one set that flag from KafkaConnect spec?

**Comment by scholzj** [comment]
TBH, I'm not aware of such requirement since I'm not Debezium expert. You should be able to use the environment variables in template (https://strimzi.io/docs/latest/full.html#con-customizing-containers-str) to set someething like `KAFKA_OPTS` or `KAFKA_JMX` and sneak it in.

If this is really needed, we should probably add this in some better way.

@gunnarmorling Is this really needed? Thanks

**Comment by mariusstaicu** [comment]
Their docs specify the need to actually add instantclient/ dir to LD_LIBRARY_PATH. However, I'm not sure if that doesn't break something else.

> Extract the archive into a directory, e.g. /path/to/instant_client/. Copy the files _ojdbc8.jar and xstreams.jar from the Instant Client into Kafka’s libs directory. Create the environment variable LD_LIBRARY_PATH, pointing to the Instant Client directory:
> 
> LD_LIBRARY_PATH=/path/to/instant_client/

**Comment by gunnarmorling** [comment]
Yes, this indeed is needed when using the Debezuim connector for Oracle, based on XStream.

**Comment by scholzj** [comment]
Sorry, I was traveling and busy with some other work, so I didn't got to this. I think there are two options how you can configure it today. If the Java property is what you need, you should be able to do something like this:

```yaml
kind: KafkaConnect
spec:
  # ...
  template:
    connectContainer:
      env:
        - name: KAFKA_OPTS
          value: "-Djava.library.path=/path/to/instant_client/"
  # ...
``` 

To specify the `LD_LIBRARY_PATH`, you should be able to do something liek this:

```yaml
kind: KafkaConnect
spec:
  # ...
  template:
    connectContainer:
      env:
        - name: LD_LIBRARY_PATH
          value: /path/to/instant_client/
  # ...
``` 

Please give this a try and let me know if it works or not.

I'm not sure this is worth adding some dedicated support. TBH I'm not sure how many connectors do need it. But also, we will not know the path to the binaries anyway, so you would still need to configure it your self, just in a different place in the KafkaConnect CR.
