### ISSUE TITLE
[Question] spec.replicas in body is required

### ISSUE THREAD

**Issue by dorsany** [strimzi/strimzi-kafka-operator#2529]
I'm getting the following error
```
spec.replicas in body is required
```

This is part of my `kafka.yaml` for the default kafka config:
```
...
  kafka:
    config:
      auto.create.topics.enable: "false"
      default.replication.factor: 1
      log.retention.bytes: 2147483648
      log.retention.hours: 48
      log.roll.hours: 24
      message.max.bytes: 2097152
      min.insync.replicas: 1
      num.io.threads: 8
      num.network.threads: 6
      num.partitions: 6
      offsets.topic.replication.factor: 1
      offsets.topic.segment.bytes: 26214400
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
...
```

Here is my `KafkaTopic.yaml` :
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my.topic
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 18
```
If I will remove the *specs* (in my case spec line and partions line) it will work 
or 
if I will add the *replicas* it will work too

my questions is why I can't configure only the `partitions` and the `KafkaTopic` will use the default value of the replicas (in my case is `default.replication.factor: 1`) from the `kafka.yaml` ?

Version: `0.16.2`

**Comment by scholzj** [comment]
TBH, This looks like a validation issue to me. I think if you don't specify the `spec` section it should error as well. Cc @tombentley @stanlyDoge

**Comment by dorsany** [comment]
Hi @scholzj ,
I understand that it is a validation issue @JsonProperty(required = true) in 
strimzi-kafka-operator/api/src/main/java/io/strimzi/api/kafka/model/KafkaTopicSpec.java

I am asking if can we make both partitions & replicas optional, as the Kafka cluster have these defaults...
example: I want to create a specific topic without specifying the replica count (it depends on the broker replicas) and i want that the topic will be created with the cluster default.

I see that in: strimzi-kafka-operator/topic-operator/src/main/java/io/strimzi/operator/topic/Topic.java there is an option to create without replicas or partitions specifications...

Can we consider it as a feature request?

10x!

**Comment by ppatierno** [comment]
@dorsany I think that in your case you can just set `auto.create.topics.enable` in the `Kafka.spec.kafka.config` so that when your consumer/producer connects for the first time and the topic doesn't exist, it's created with default value. The TO will sync with it and create a `KafkaTopic` resource with the right partitions and replicas values.

**Comment by tombentley** [comment]
I guess this would make sense as a feature request. Then, if it's possible to create a `KafkaTopic` with an empty `spec` is it really necessary to require the `spec`? I suppose not.

**Comment by dorsany** [comment]
Hi @ppatierno  , yes I know of the `auto.create.topics.enable` , but that will make any bad behaving producer/developer creating multiple and misleading topics, and we want to have control over the topics (names/partitions/replicas) .
I believe that a Kafka operator should enable the control over topics names/partitions/replicas in a simple k8s deployments.

So in my case if I have `KafkaTopic` crd manifest like this:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my.topic
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 18
```
It will be amazing if the operator will add  the "missing" `replication` number from the default settings `default.replication.factor: 1`
