### ISSUE TITLE
[Question] How do I utilize strimzi-kafka-operator custom resources within my helm charts?

### ISSUE THREAD

**Issue by paul-nelson-baker** [strimzi/strimzi-kafka-operator#2552]
Hello!

So I have declared strimzi as a dependency of my chart:
```yaml
dependencies:
- name: strimzi-kafka-operator
  version: 0.16.2
  repository: https://strimzi.io/charts/
```
and pulled down the chart via `helm dep up ./my-chart`

When I attempt to `helm install ./my-chart` I get an error:
```
Error: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "KafkaTopic" in version "kafka.strimzi.io/v1beta1"
```
Which is somewhat confusing, because essentially my yaml file has a single definition for a kafka topic that [almost exactly matches the documentation](https://strimzi.io/docs/0.16.2/#creating-a-topic-str)

My Values.yaml:
```yaml
topics:
  - name: NameOne
    partitions: 3
    replicas: 3
  - name: NameTwo
    partitions: 3
    replicas: 3
  - name: NameThree
    partitions: 3
    replicas: 3
```

and my accompanying template:
```yaml
{{ range .Values.topics }}
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: {{ .name }}
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
{{ end }}
```

Would someone be so kind as to inform me of what I'm missing from the equation? Thank you for your time, I appreciate it!
