### ISSUE TITLE
[Bug] Operator Rolling Update is triggered when resource is not modified

### ISSUE THREAD

**Issue by mhaddon** [strimzi/strimzi-kafka-operator#2558]
**Describe the bug**
It seems that if the operator thinks that the Kafka resource has been changed it triggers a rolling update of the resource. 
As hinted in the documentation: "In most cases, the Cluster Operator only updates your Kafka or ZooKeeper clusters in response to changes to the corresponding Kafka resource. This enables you to plan when to apply changes to a Kafka resource to minimize the impact on Kafka client applications.".

The problem I am having is that even if the resource does not change, the rolling update is triggered. 

If I am using kustomize and have my "kind: Kafka" in the same kustomize "build" as another resource. If the other resource is updated, then the Strimizi Operator thinks it needs to perform a rolling update of Kafka, even if Kafka is not modified. Looking at the yaml output of kustomize, I cannot even see a difference in the yaml.

This is a big problem because I am using GitOps to provision my environment and therefore I am getting a rolling update about every 5-10 minutes...

**To Reproduce**
1. Put Kafka in the same Kustomize build as another resource
2. Edit the other resource
2. kustomize build . | kubectl apply -f -
3. Kafka is forced to rolling update 

**Expected behavior**
Rolling update only happens if I specifically edit Kafka... or at least give me the ability to turn-off the rolling update functionality.

**Environment (please complete the following information):**
 - Strimzi version: 0.16.2
 - Installation method: yaml
 - Kubernetes cluster: 1.14
 - Infrastructure: EKS

**YAML files and logs**
The logs just keep saying: 
```
2020-02-16 22:06:02 INFO  PodOperator:65 - Rolling update of test/kafka-zookeeper: Rolling pod kafka-zookeeper-0
2020-02-16 22:06:48 INFO  PodOperator:65 - Rolling update of test/kafka-kafka: Rolling pod kafka-kafka-0
```

My Kafka deployment:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 2.4.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
      delete.topic.enable: "true"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 10Gi
          deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

**Comment by scholzj** [comment]
Can you please share the whole log from the Cluster Operator? Ideally with DEBUG log level switched on? (by setting the environment variable `STRIMZI_LOG_LEVEL` to `DEBUG` in the Operator deployment)

**Comment by mhaddon** [comment]
Here is 6 minutes worth of logs, it already rolling updated a lot, so hopefully there is enough info

[operatorlogs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4211182/operatorlogs.txt)

**Comment by mhaddon** [comment]
It also seems that if I want a while, and just from the terminal just try re-applying the Kafka yaml file:

```
kustomize build . | kubectl apply -f -
kafka.kafka.strimzi.io/kafka configured
kafkatopic.kafka.strimzi.io/ingress-ship-event configured
kafkatopic.kafka.strimzi.io/test configured
```

It gets listed as being configured, which is probably what triggers the operator, even though nothing has actually changed

**Comment by scholzj** [comment]
I'm not sure it is kustomize what is changing the resource. You seem to be adding some labels to it:

```
2020-02-16 23:01:32 DEBUG StatefulSetDiff:97 - StatefulSet team-test/kafka-zookeeper differs: {"op":"remove","path":"/metadata/labels/fluxcd.io~1sync-gc-mark"}
2020-02-16 23:01:32 DEBUG StatefulSetDiff:98 - Current StatefulSet path /metadata/labels/fluxcd.io~1sync-gc-mark has value 
2020-02-16 23:01:32 DEBUG StatefulSetDiff:99 - Desired StatefulSet path /metadata/labels/fluxcd.io~1sync-gc-mark has value 
2020-02-16 23:01:32 DEBUG StatefulSetDiff:81 - StatefulSet team-test/kafka-zookeeper ignoring diff {"op":"remove","path":"/spec/revisionHistoryLimit"}
2020-02-16 23:01:32 DEBUG StatefulSetDiff:81 - StatefulSet team-test/kafka-zookeeper ignoring diff {"op":"remove","path":"/spec/template/metadata/annotations/strimzi.io~1generation"}
2020-02-16 23:01:32 DEBUG StatefulSetDiff:97 - StatefulSet team-test/kafka-zookeeper differs: {"op":"remove","path":"/spec/template/metadata/labels/fluxcd.io~1sync-gc-mark"}
2020-02-16 23:01:32 DEBUG StatefulSetDiff:98 - Current StatefulSet path /spec/template/metadata/labels/fluxcd.io~1sync-gc-mark has value 
2020-02-16 23:01:32 DEBUG StatefulSetDiff:99 - Desired StatefulSet path /spec/template/metadata/labels/fluxcd.io~1sync-gc-mark has value 
```

That is one of the things which is triggering the restart. Additionally it seems to list `ancillary CM change` as changed. Not sure what exactly does that mean in your case, because I'm not sure what code you actually use since you say you are using master branch, but this message is not in the latest master branch.

**Comment by scholzj** [comment]
As for the `configured`, I have no idea what your kustomize build is changing. You will need to compare the resource before and after to see what exactly changed.

**Comment by mhaddon** [comment]
I am using 0.16.2 of the operator.

I think I know what the problem is, now I need to figure out what to do about it.

I did this: 
```
kubectl get kafka -o yaml -n team-test > a && kustomize build env/prod/ > b && kustomize build env/prod/ | kubectl apply -f -
```
Then I compared the output of the a and b file, and I see something very obvious.

If you use FluxCD, the GitOps CD tool by Weaveworks, then it add its own annotations and labels to the deployment.

```
annotations:
  fluxcd.io/sync-checksum: cee6605a3f351637b5a60ba4e28c87cb9e5e78d9
labels:
  fluxcd.io/sync-gc-mark: sha256.lFncy9Bn7eb87iLUySM2398Zx2GPXE0752HbwgTMRxE
```
