### ISSUE TITLE
How to set max.request.size on KafkaConnect CRDs?

### ISSUE THREAD

**Issue by jslusher** [strimzi/strimzi-kafka-operator#2592]
I referenced these document items:
https://strimzi.io/docs/latest/#type-KafkaConnectSpec-reference

I set my values accordingly:

```
...
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
...
spec:
  bootstrapServers: platform-kafka-bootstrap:9092
  config:
    max.request.size: 2097152
```

I still see in the log output that the default is set:
A connect pod:
```
max.request.size = 1048576
```

And I'm still getting this exception from one of my connectors:

```
org.apache.kafka.common.errors.RecordTooLargeException: The message is 1904641 bytes when serialized which is larger than the maximum request size you have configured with the max.request.size configuration.
```

**Comment by scholzj** [comment]
Have you tried to configure it with the `consumer.` and/or `producer.` prefix?

**Comment by jslusher** [comment]
I tried setting the config like this:

```
spec:
  bootstrapServers: platform-kafka-bootstrap:9092
  config:
    producer.max.request.size: 2097152
    consumer.max.request.size: 2097152
```
I see this in the logs:

```
2020-02-24 22:18:36,328 WARN The configuration 'producer.max.request.size' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig) [DistributedHerder-connect-1]
2020-02-24 22:18:36,329 WARN The configuration 'consumer.max.request.size' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig) [DistributedHerder-connect-1]
	max.request.size = 1048576
```

**Comment by scholzj** [comment]
Yeah, it is because the configuration and logging in Kafka is a bit mess. But if you look at the message, it is `AdminClientConfig` complaining. You do not care about `AdminClientConfig` with these options. The more important is to find in the logs whether the consumer / producer saw this config and accepted it.

**Comment by jslusher** [comment]
I gripped for the word `max` in the output of the connect pod and the only thing I see is the `max-request.size = 1048576` which is I believe separate from the warnings about the configuration. Which I think means that even though the logs that are complaining about the configuration aren't related, the connect pods still don't seem to be taking the setting. Is there someplace besides the logs that I can look for the setting?

**Comment by scholzj** [comment]
Can you share the log file? Normally when connect is starting, it prints several times the configuration of the different clients. So even if it ignores your confguration, you should see the default value in the log file many times.

**Comment by jslusher** [comment]
I created two gists, [ConsumerConfig values](https://gist.github.com/jslusher/245de6b2eae2eda1a0d23c0f430309fe) and [ProducerConfig values](https://gist.github.com/jslusher/378ded2e676505a11c7de0ba38435be5), containing their respective log output for config. I don't see any `max.request.size` in the ConsumerConfig and the setting in the ProducerConfig looks to be the default of 1048576.

**Comment by scholzj** [comment]
I gave it a try (with latest master - not sure what exact version are you using). I created the KafkaConnect resource with this YAML:
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
spec:
  version: 2.4.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: my-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    max.request.size: 2097152
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
```

In the startup log I can see following:
* The option is printed in the config on the beginning - these are just the startup scripts of our container image.
* Next is the message you mentioned. This is correct - this option is only for Producers. So the Admin APi does not understand it but w eshould not care.
```
2020-02-25 18:29:55,069 WARN The configuration 'max.request.size' was supplied but isn't a known config. (org.apache.kafka.clients.admin.AdminClientConfig) [main]
```
* Afterwards it is printed in the Producer config. This is where we want to have it and it seems to be ok - it has the new value. 
```
2020-02-25 18:29:57,333 INFO ProducerConfig values:
        acks = all
        batch.size = 16384
        bootstrap.servers = [my-cluster-kafka-bootstrap:9093]
        buffer.memory = 33554432
        client.dns.lookup = default
        client.id =
        compression.type = none
        connections.max.idle.ms = 540000
        delivery.timeout.ms = 2147483647
        enable.idempotence = false
        interceptor.classes = []
        key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
        linger.ms = 0
        max.block.ms = 60000
        max.in.flight.requests.per.connection = 1
        max.request.size = 2097152
        metadata.max.age.ms = 300000
        metric.reporters = []
        metrics.num.samples = 2
        metrics.recording.level = INFO
        metrics.sample.window.ms = 30000
        partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
        receive.buffer.bytes = 32768
        reconnect.backoff.max.ms = 1000
        reconnect.backoff.ms = 50
        request.timeout.ms = 30000
        retries = 2147483647
        retry.backoff.ms = 100
        sasl.client.callback.handler.class = null
        sasl.jaas.config = null
        sasl.kerberos.kinit.cmd = /usr/bin/kinit
        sasl.kerberos.min.time.before.relogin = 60000
        sasl.kerberos.service.name = null
        sasl.kerberos.ticket.renew.jitter = 0.05
        sasl.kerberos.ticket.renew.window.factor = 0.8
        sasl.login.callback.handler.class = null
        sasl.login.class = null
        sasl.login.refresh.buffer.seconds = 300
        sasl.login.refresh.min.period.seconds = 60
        sasl.login.refresh.window.factor = 0.8
        sasl.login.refresh.window.jitter = 0.05
        sasl.mechanism = GSSAPI
        security.protocol = SSL
        security.providers = null
        send.buffer.bytes = 131072
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
        ssl.endpoint.identification.algorithm = https
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLS
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.location = /tmp/kafka/cluster.truststore.p12
        ssl.truststore.password = [hidden]
        ssl.truststore.type = PKCS12
        transaction.timeout.ms = 60000
        transactional.id = null
        value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
 (org.apache.kafka.clients.producer.ProducerConfig) [DistributedHerder-connect-1]
```
* Then there is another message from Consumer config abotu not understanding the option. Thsi is again valid because this is producer option only.
```
2020-02-25 18:29:57,700 WARN The configuration 'max.request.size' was supplied but isn't a known config. (org.apache.kafka.clients.consumer.ConsumerConfig) [DistributedHerder-connect-1]
```

So the way you described it originally seems to work fine for me. If it doesn't work for you, what version do you use? Also, can you share the log from the Cluster Operator plus the whole KafkaConnect CR including the metadata and status?

PS: The `producer.` prefix does not seem to work here - so for confusing you and leading you the wrong way.
