### ISSUE TITLE
[Question] Is there a way to enable both oauth and sasl sha external endpoints? 

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#2616]
Can we enable both oauth and sasl sha bootstrap server endpoints? i.e. have oauth and scram-sha-512      configured under external?

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafkaExporter: {}
  kafka:
    version: 2.3.0
    replicas: 13
    listeners:
      plain:
        authentication:
          type: scram-sha-512     
      external:
        type: loadbalancer
        tls: true
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
```
