### ISSUE TITLE
[Enhancement] Support configurable cipher suites

### ISSUE THREAD

**Issue by beavenj** [strimzi/strimzi-kafka-operator#2643]
**Is your feature request related to a problem? Please describe.**
We need to be able to select which cipher suites Kafka supports in order to align with other components in our infrastructure and ensure consistency.

**Describe the solution you'd like**
The underlying Kafka implementation provides control over cipher suites using a configuration property **ssl.cipher.suites**. In Strimzi, these configuration settings are exposed in the CRD for Kafka under Kafka.spec.kafka.config. Currently settings prefixed with **ssl** are prohibited and so if **ssl.cipher.suites** is added to the config, it is ignored when the Kafka instance is created. The proposal here is to add this specific setting to the forbidden prefix exceptions list which is a white list of allowed properties that overriders the blanket ssl.* ban. So, for example would have definitions like this:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.4.0
    .
    .
    .
    config:
      ssl.cipher.suites: TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
.
.
.
```

If not specified, no restrictions would be imposed on the supported cipher suites. This approach keeps things simple without the need to further extend the CRD and retains consistency with the approach adopted by Kafka.

**Describe alternatives you've considered**
There are two alternative approaches that have been discussed. The first is to capture this under the configuration settings for a listener in a new section called **cipherSuites** (for example Kafka.spec.listeners.external.configuration.cipherSuites). This would be as follows:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.4.0
    .
    .
    .
    listeners:
      tls:
        authentication:
          type: tls
      external:
        type: route
        authentication:
          type: tls
        configuration:
            cipherSuites:
              - "TLS_RSA_WITH_AES_128_GCM_SHA256"
              - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"
.
.
.
```

The second alternative is to capture this in a new section such as Kafka.spec.kafka.ssl.cipherSuties along these lines. 

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.4.0
    .
    .
    .
    ssl:
       cipherSuites:
         - "TLS_RSA_WITH_AES_128_GCM_SHA256"
         - "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"     
.
.
.
```
