### ISSUE TITLE
[Question] How to set FQDN into listener field?

### ISSUE THREAD

**Issue by SpecialForce3331** [strimzi/strimzi-kafka-operator#2650]
Good day!
At now i have a this:
`kubectl -n kafka-test  get kafka -o yaml`
```    
   ....
    listeners:
    - addresses:
      - host: kafka-test-kafka-bootstrap.kafka-test.svc
```
And i want to get `kafka-test-kafka-bootstrap.kafka-test.svc`.**cluster.local**
How i can get full name with cluster name?
