### ISSUE TITLE
OAUTH kafka error 

### ISSUE THREAD

**Issue by saneera** [strimzi/strimzi-kafka-operator#2662]
Hi 

I configured kafka cluster with OAUTH configuration as follows

```
listeners:
      plain:
        authentication:
          type: oauth
          validIssuerUri: https://sso-my-project2.apps.90d5.example.opentlc.com/auth/realms/internal
          jwksEndpointUri: https://sso-my-project2.apps.90d5.example.opentlc.com/auth/realms/internal/protocol/openid-connect/certs
          userNameClaim: preferred_username
          tlsTrustedCertificates:
            - secretName: sso-x509-https-secret
              certificate: tls.crt
      tls:
        authentication:
          type: oauth
          validIssuerUri: https://sso-my-project2.apps.90d5.example.opentlc.com//auth/realms/internal
          jwksEndpointUri: https://sso-my-project2.apps.90d5.example.opentlc.com/auth/realms/internal/protocol/openid-connect/certs
          userNameClaim: preferred_username
          tlsTrustedCertificates:
            - secretName: sso-x509-https-secret
              certificate: tls.crt
    authorization:
      type: simple
```
my keycloak server succesfully running on openshift with URL provided above 

when I configured kafka cluster with above configuration my cluster not starting (check the error)
anyway I configured kafka cluster on same project and replace the keycloak url with local url with port 8443 its working fine 

error lookes like secrets keys , wich secret keys need to configure within the project to get it working 

```
org.apache.kafka.common.KafkaException: java.lang.RuntimeException: Failed to fetch public keys needed to validate JWT signatures: https://sso-my-project2.apps.90d5.example.opentlc.com/auth/realms/internal/protocol/openid-connect/certs
--
  | at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:158)
  | at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
  | at org.apache.kafka.common.network.ChannelBuilders.serverChannelBuilder(ChannelBuilders.java:85)
  | at kafka.network.Processor.<init>(SocketServer.scala:753)
  | at kafka.network.SocketServer.newProcessor(SocketServer.scala:394)
  | at kafka.network.SocketServer.$anonfun$addDataPlaneProcessors$1(SocketServer.scala:279)
  | at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
  | at kafka.network.SocketServer.addDataPlaneProcessors(SocketServer.scala:278)
  | at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1(SocketServer.scala:241)
  | at kafka.network.SocketServer.$anonfun$createDataPlaneAcceptorsAndProcessors$1$adapted(SocketServer.scala:238)
  | at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
  | at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
  | at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
  | at kafka.network.SocketServer.createDataPlaneAcceptorsAndProcessors(SocketServer.scala:238)
  | at kafka.network.SocketServer.startup(SocketServer.scala:121)
  | at kafka.server.KafkaServer.startup(KafkaServer.scala:263)
  | at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
  | at kafka.Kafka$.main(Kafka.scala:84)
  | at kafka.Kafka.main(Kafka.scala)
  | Caused by: java.lang.RuntimeException: Failed to fetch public keys needed to validate JWT signatures: https://sso-my-project2.apps.90d5.example.opentlc.com/auth/realms/internal/protocol/openid-connect/certs
  | at io.strimzi.kafka.oauth.validator.JWTSignatureValidator.fetchKeys(JWTSignatureValidator.java:141)
  | at io.strimzi.kafka.oauth.validator.JWTSignatureValidator.<init>(JWTSignatureValidator.java:100)
  | at io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler.configure(JaasServerOauthValidatorCallbackHandler.java:91)
  | at org.apache.kafka.common.network.SaslChannelBuilder.configure(SaslChannelBuilder.java:128)
  | ... 18 more
  | Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  | at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
  | at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
  | at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
  | at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
  | at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
  | at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
  | at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
  | at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
  | at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
  | at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
  | at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
  | at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
  | at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
  | at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
  | at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:167)
  | at io.strimzi.kafka.oauth.common.HttpUtil.postOrGet(HttpUtil.java:105)
  | at io.strimzi.kafka.oauth.common.HttpUtil.get(HttpUtil.java:49)
  | at io.strimzi.kafka.oauth.validator.JWTSignatureValidator.fetchKeys(JWTSignatureValidator.java:137)
  | ... 21 more
  | Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  | at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:450)
  | at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:317)
  | at sun.security.validator.Validator.validate(Validator.java:262)
  | at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:330)
  | at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:237)
  | at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
  | at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1621)
  | ... 34 more
  | Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  | at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)
  | at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)
  | at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
  | at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:445)
  | ... 40 more


```

**Comment by scholzj** [comment]
The problem is with the TLS certificates you are using the Kafka broker to use. They do not seem to match what Keycloak is using. IIRC the secret `sso-x509-https-secret` has the TLS certificate used by Keycloak internally. But the Route you are using to access it is using re-encrypt strategy or something like that and therefore it is not using the Keycloak certificate but the Openshift router certificate instead. So you need to use that.

I'm not sure there is any secret with that you can use out of the box. I usually get the publi key using `openssl s_client` and create a secret with it manually.

**Comment by samyan123** [comment]
Can you able to provide me steps of doing that

**Comment by saneera** [comment]
Thanks can you provide me to steps to do that

**Comment by scholzj** [comment]
Sorry, I do not have it running right now. So I cannot give you the exact step by step guide. But basically:

* Run `openssl s_client -connect sso-my-project2.apps.90d5.example.opentlc.com/auth/realms/internal:443 -showcerts -servername sso-my-project2.apps.90d5.example.opentlc.com`
* That should give you some output which contains several certificates starting with `-----BEGIN CERTIFICATE-----` and ending with `-----END CERTIFICATE-----`
* Copy the first one (including the begin and end above) into a file an create a secret
* Use the secret in the configuration

**Comment by saneera** [comment]
@scholzj Thanks I will do

**Comment by saneera** [comment]
@scholzj I managed to run Kafka cluster with OAuth configuration however I tried to run clients producer with the following configuration

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
      strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  partitions: 12
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic-reversed
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 3
  partitions: 12
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: service-account-hello-world-producer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
        operation: Write
      - resource:
          type: topic
          name: my-topic
        operation: Create
      - resource:
          type: topic
          name: my-topic
        operation: Describe
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-producer-oauth
type: Opaque
data:
  clientSecret: aGVsbG8td29ybGQtcHJvZHVjZXItc2VjcmV0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-producer
  name: hello-world-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-producer
  template:
    metadata:
      labels:
        app: hello-world-producer
    spec:
      containers:
      - name: hello-world-producer
        image: strimzi/hello-world-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: my-topic
          - name: DELAY_MS
            value: "1000"
          - name: LOG_LEVEL
            value: "INFO"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: OAUTH_CLIENT_ID
            value: hello-world-producer
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: hello-world-producer-oauth
                key: clientSecret
          - name: OAUTH_TOKEN_ENDPOINT_URI
            value: https://sso-keycloak.apps.90d5.example.opentlc.com:443/auth/realms/internal/protocol/openid-connect/token
          - name: OAUTH_CRT
            valueFrom:
              secretKeyRef:
                name: sso-x509-https-secret
                key: tls.crt
```
                                                 

the producer is up and running but it does not send messages                               

```
2020-03-10 12:09:59 INFO  KafkaProducerExample:35 - Sending messages "Hello world - 9"
12575 [kafka-producer-network-thread | producer-1] INFO org.apache.kafka.common.network.Selector - [Producer clientId=producer-1] Failed authentication with my-cluster-kafka-bootstrap/172.30.49.233 ({"status":"invalid_token"})
12575 [kafka-producer-network-thread | producer-1] ERROR org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Connection to node -1 (my-cluster-kafka-bootstrap/172.30.49.233:9092) failed authentication due to: {"status":"invalid_token"}
2020-03-10 12:10:00 INFO  KafkaProducerExample:35 - Sending messages "Hello world - 10"
13786 [kafka-producer-network-thread | producer-1] INFO org.apache.kafka.common.network.Selector - [Producer clientId=producer-1] Failed authentication with my-cluster-kafka-bootstrap/172.30.49.233 ({"status":"invalid_token"})
13786 [kafka-producer-network-thread | producer-1] ERROR org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Connection to node -1 (my-cluster-kafka-bootstrap/172.30.49.233:9092) failed authentication due to: {"status":"invalid_token"}
2020-03-10 12:10:02 INFO  KafkaProducerExample:35 - Sending messages "Hello world - 11"
15248 [kafka-producer-network-thread | producer-1] INFO org.apache.kafka.common.network.Selector - [Producer clientId=producer-1] Failed authentication with my-cluster-kafka-bootstrap/172.30.49.233 ({"status":"invalid_token"})
15248 [kafka-producer-network-thread | producer-1] ERROR org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Connection to node -1 (my-cluster-kafka-bootstrap/172.30.49.233:9092) failed authentication due to: {"status":"invalid_token"}
2020-03-10 12:10:03 INFO  KafkaProducerExample:35 - Sending messages "Hello world - 12"
16559 [kafka-producer-network-thread | producer-1] INFO org.apache.kafka.common.network.Selector - [Producer clientId=producer-1] Failed authentication with my-cluster-kafka-bootstrap/172.30.49.233 ({"status":"invalid_token"})
16560 [kafka-producer-network-thread | producer-1] ERROR org.apache.kafka.clients.NetworkClient - [Producer clientId=producer-1] Connection to node -1 (my-cluster-kafka-bootstrap/172.30.49.233:9092) failed authentication due to: {"status":"invalid_token"}
2020-03-10 12:10:04 INFO  KafkaProducerExample:35 - Sending messages "Hello world - 13"
```

it looks like token is not generating properly with URL provides in producer deployment

any idea ??

Thanks

**Comment by scholzj** [comment]
TBH, I'm not sure how to change the log levels here to get more infor from the OAuth library. I would need to look into image. But looking at the YAMLs - yould it be the same problem as with the broker? You seem to be using again `sso-x509-https-secret` for the TLS certificate which was not the right certificate in the broker, right? Can you try to use the same secret / certificate as with the broker if you got it running?

**Comment by saneera** [comment]
Thanks @scholzj  Yes I m using same  secret/certificate used for broker still is the same

**Comment by scholzj** [comment]
@mstruk Any idea what could cause `{"status":"invalid_token"}` with Keycloak?

**Comment by saneera** [comment]
This is the error inside kafka broker 


```
2020-03-10 22:23:29,068 INFO [SocketServer brokerId=0] Failed authentication with /10.1.8.1 ({"status":"invalid_token"}) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(PLAIN-9092)-SASL_PLAINTEXT-4]
--
  | 2020-03-10 22:23:30,335 INFO [SocketServer brokerId=0] Failed authentication with /10.1.8.1 ({"status":"invalid_token"}) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(PLAIN-9092)-SASL_PLAINTEXT-5]
  | 2020-03-10 22:23:31,610 INFO [SocketServer brokerId=0] Failed authentication with /10.1.8.1 ({"status":"invalid_token"}) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(PLAIN-9092)-SASL_PLAINTEXT-3]
  | 2020-03-10 22:23:33,070 INFO [SocketServer brokerId=0] Failed authentication with /10.1.8.1 ({"status":"invalid_token"}) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(PLAIN-9092)-SASL_PLAINTEXT-4]
  | 2020-03-10 22:23:34,337 INFO [SocketServer brokerId=0] Failed authentication with /10.1.8.1 ({"status":"invalid_token"}) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(PLAIN-9092)-SASL_PLAINTEXT-5]
```

**Comment by mstruk** [comment]
One common reason for invalid token is if host, port and realm in the URL used by the client to authenticate (the OAUTH_TOKEN_ENDPOINT_URI) are not the same as those in the URL used by the broker to validate the token (validIssuerUri).

In previous comments above I can see:
OAUTH_TOKEN_ENDPOINT_URI set to https://sso-keycloak.apps.90d5.example.opentlc.com:443/auth/realms/internal/protocol/openid-connect/token

And validIssuerUri for 'plain' set to: https://sso-my-project2.apps.90d5.example.opentlc.com/auth/realms/internal.

These are completely different URIs while they should both start the same. In this case either https://sso-my-project2.apps.90d5.example.opentlc.com/auth/realms/internal or https://sso-keycloak.apps.90d5.example.opentlc.com:443/auth/realms/internal.

Kafka client and Kafka broker both have to access the Keycloak server using the url with the same hostname, port, and realm.

**Comment by saneera** [comment]
@mstruk 
Sorry my bad my final configuration as follows

both kafka cluster and producer running on same project but keycloak running on different project on openshift 

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app: my-cluster
spec:
  kafka:
    replicas: 1
    jvmOptions:
      gcLoggingEnabled: false
    listeners:
      plain:
        authentication:
          type: oauth
          validIssuerUri: https://sso-keycloak.apps.90d5.example.opentlc.com:443/auth/realms/internal
          jwksEndpointUri: https://sso-keycloak.apps.90d5.example.opentlc.com:443/auth/realms/internal/protocol/openid-connect/certs
          userNameClaim: preferred_username
          tlsTrustedCertificates:
            - secretName: ca-truststore
              certificate: oauth.crt
      tls:
        authentication:
          type: oauth
          validIssuerUri: https://sso-keycloak.apps.90d5.example.opentlc.com:443/auth/realms/internal
          jwksEndpointUri: https://sso-keycloak.apps.90d5.example.opentlc.com:443/auth/realms/internal/protocol/openid-connect/certs
          userNameClaim: preferred_username
          tlsTrustedCertificates:
            - secretName: ca-truststore
              certificate: oauth.crt
    authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    jvmOptions:
      gcLoggingEnabled: false
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      jvmOptions:
        gcLoggingEnabled: false
    userOperator:
      jvmOptions:
        gcLoggingEnabled: false)

apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
      strimzi.io/cluster: my-cluster
spec:
  replicas: 1
  partitions: 12
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: my-topic-reversed
  labels:
    strimzi.io/cluster: my-cluster
spec:
  replicas: 1
  partitions: 12
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: service-account-hello-world-producer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
        operation: Write
      - resource:
          type: topic
          name: my-topic
        operation: Create
      - resource:
          type: topic
          name: my-topic
        operation: Describe
---
apiVersion: v1
kind: Secret
metadata:
  name: hello-world-producer-oauth
type: Opaque
data:
  clientSecret: aGVsbG8td29ybGQtcHJvZHVjZXItc2VjcmV0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world-producer
  name: hello-world-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-producer
  template:
    metadata:
	  labels:
    app: hello-world-producer
  name: hello-world-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-producer
  template:
    metadata:
      labels:
        app: hello-world-producer
    spec:
      containers:
      - name: hello-world-producer
        image: strimzi/hello-world-producer:latest
        env:
          - name: BOOTSTRAP_SERVERS
            value: my-cluster-kafka-bootstrap:9092
          - name: TOPIC
            value: my-topic
          - name: DELAY_MS
            value: "1000"
          - name: LOG_LEVEL
            value: "DEBUG"
          - name: MESSAGE_COUNT
            value: "1000000"
          - name: OAUTH_CLIENT_ID
            value: hello-world-producer
          - name: OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: hello-world-producer-oauth
                key: clientSecret
          - name: OAUTH_TOKEN_ENDPOINT_URI
            value: https://sso-keycloak.apps.90d5.example.opentlc.com:443/auth/realms/internal/protocol/openid-connect/token
          - name: OAUTH_CRT
            valueFrom:
              secretKeyRef:
                name: ca-truststore
                key: oauth.crt

```
