### ISSUE TITLE
[Bug] TO JVM options

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#2684]
EntityOperator sets the `STRIMZI_JAVA_SYSTEM_PROPERTIES` env var with the various JVM configs in `JvmOptions`. 

`topic_operator_run.sh` then does `export JAVA_OPTS="${JAVA_OPTS} ${STRIMZI_JAVA_SYSTEM_PROPERTIES}"` before `exec`ing `launch_java.sh` which does this:

```bash
MAX_HEAP=`get_heap_size`
if [ -n "$MAX_HEAP" ]; then
  JAVA_OPTS="-Xms${MAX_HEAP}m -Xmx${MAX_HEAP}m $JAVA_OPTS"
fi
```

The result is we end up with two `-Xmx` options on the `java` cmdline. `java` does not reject a cmdline with multiple `-Xmx`. I assume (but don't know) that the last one wins. If that's right then there's no actual bug, it's merely confusing. If I'm wrong then it means the TO is not being started with the correct `-Xmx`. 

In either case this is something we should fix. I suppose we should only do the MAX_HEAP thing in `launch_java.sh` if `-Xmx` is not already in the `JAVA_OPTS`.

**Comment by carlosjgp** [comment]
Good news, setting the environment variable allowed the Topic Operator to use more than 50% of the memory limit

```
        env:
        # A little bit less than the container limit to avoid being OOMKilled by K8s
        - name: JAVA_OPTS
          value: "-Xmx480m"
```

and bad news is that it seems to have a memory leak (should I report this on a separate issue?)

![topic-operator-metrics-2020 03 16-09_09_17](https://user-images.githubusercontent.com/1277613/76740619-18e1d580-6766-11ea-9bea-851ea64bc82d.png)

Full container `spec`
```
      containers:
      - name: msk-topic-operator
        image: strimzi/operator:0.16.2
        args:
        - /opt/strimzi/bin/topic_operator_run.sh
        imagePullPolicy: IfNotPresent
        env:
        - name: STRIMZI_RESOURCE_LABELS
          value: strimzi.io/cluster=msk
        - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
          value: "xxx:9092"
        - name: STRIMZI_ZOOKEEPER_CONNECT
          value: "yyy:2181"
        - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
          value: "20000"
        - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
          value: "90000"
        - name: STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS
          value: "6"
        - name: STRIMZI_LOG_LEVEL
          value: INFO
        - name: STRIMZI_GC_LOG_ENABLED
          value: "true"
        - name: STRIMZI_TLS_ENABLED
          value: "false"
        - name: STRIMZI_NAMESPACE
          value: strimzi
        # A little bit less than the container limit to avoid being OOMKilled by K8s
        - name: JAVA_OPTS
          value: "-Xmx480m"
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
        resources:
          limits:
            memory: 512Mi
            cpu: 500m
          requests:
            memory: 512Mi
            cpu: 100m
```

**Comment by tombentley** [comment]
@carlosjgp I think you're probably setting the Xmx too close to the container memory limit and therefore you can't really conclude that there's a memory leak necessarily. The heap is just one aspect of JVM memory. There are a bunch of other memory pools too, which likely accounts for the fact that the JVM  uses more than the container limit and gets killed by the kernel. This is backed up by the graph you posted, which doesn't really show evidence of any garbage collection by the JVM.

Try setting the heap at a smaller proportion of of the container memory and turn on JVM GC logging  and you should start to get a better idea about what settings work for you.

**Comment by carlosjgp** [comment]
> @carlosjgp I think you're probably setting the Xmx too close to the container memory limit and therefore you can't really conclude that there's a memory leak necessarily. The heap is just one aspect of JVM memory. There are a bunch of other memory pools too, which likely accounts for the fact that the JVM uses more than the container limit and gets killed by the kernel. This is backed up by the graph you posted, which doesn't really show evidence of any garbage collection by the JVM.
> 
> Try setting the heap at a smaller proportion of the container memory and turn on JVM GC logging and you should start to get a better idea about what settings work for you.

Thanks for your response @tombentley ,

I have limited knowledge about the JVM. This is why I thought it was a memory leak

The previous configuration of Topic Operator was using the default configuration (no `Xmx` option) meaning that it was using 50% of the available memory as heap (yellow lines on CPU and Memory usage)
on the 11th the heap hit its max cap and the CPU started to be used more intensively (CPU garbage collection was my guess) until it crashed, not killed by the Kernel but by the JVM,

Because we running the Topic Operator with 
```
        - name: STRIMZI_GC_LOG_ENABLED
          value: "true"
```

I could get this last log entry referring to `Full GC (Allocation Failure)` before the TO restarted
```
2020-03-12 09:02:05 INFO  TopicOperator:1302 - Success reconciling KafkaTopic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
2020-03-12T09:02:05.238+0000: 248370.778: [Full GC (Allocation Failure) 2020-03-12T09:02:05.238+0000: 248370.778: [Tenured: 87423K->87423K(87424K), 1.1583092 secs] 126719K->124201K(126720K), [Metaspace: 37088K->37088K(1083392K)], 1.1583811 secs] [Times: user=0.61 sys=0.00, real=1.16 secs] 
2020-03-12T09:02:20.574+0000: 248386.114: [Full GC (Allocation Failure) 2020-03-12T09:02:20.574+0000: 248386.114: [Tenured: 87423K->87423K(87424K), 1.2798194 secs] 126715K->123494K(126720K), [Metaspace: 37105K->37105K(1083392K)], 1.2798820 secs] [Times: user=0.64 sys=0.00, real=1.28 secs] 
Heap
 def new generation   total 39296K, used 36346K [0x00000000f8000000, 0x00000000faaa0000, 0x00000000faaa0000)
  eden space 34944K, 100% used [0x00000000f8000000, 0x00000000fa220000, 0x00000000fa220000)
  from space 4352K,  32% used [0x00000000fa220000, 0x00000000fa37eba8, 0x00000000fa660000)
  to   space 4352K,   0% used [0x00000000fa660000, 0x00000000fa660000, 0x00000000faaa0000)
 tenured generation   total 87424K, used 87423K [0x00000000faaa0000, 0x0000000100000000, 0x0000000100000000)
   the space 87424K,  99% used [0x00000000faaa0000, 0x00000000fffffff0, 0x0000000100000000, 0x0000000100000000)
 Metaspace       used 37136K, capacity 38080K, committed 38272K, reserved 1083392K
  class space    used 3946K, capacity 4181K, committed 4224K, reserved 1048576K
```

And this is our log aggregation service with a diagram with the number of occurrences (about 6.6k in 24h) to `Full GC (Allocation Failure)` which matches exactly with the CPU activity increasing
![topic-operator-logs-occurrences](https://user-images.githubusercontent.com/1277613/76754528-3456db80-677a-11ea-863c-dce60d1e9705.png)


Should I be looking into something more particular on these logs? Or is there any other way of getting more insights about this?

(we are not creating or deleting topics often so the activity on the Topic operator should be just reconciliations most of the time)

**Comment by carlosjgp** [comment]
More news on this

As @tombentley predicted assigning 93% of the Container memory to the Heap was not a good idea
This time was K8s who killed the process
```
    lastState:
      terminated:
        containerID: docker://7cf9c811bfc606e156700fdeb7183fa3bc4c74b70ed03226f6c9a39dea6b8176
        exitCode: 137
        finishedAt: "2020-03-17T21:21:45Z"
        reason: OOMKilled
        startedAt: "2020-03-12T09:32:31Z"
```

![pod-resources](https://user-images.githubusercontent.com/1277613/77095259-8cedd900-6a05-11ea-940b-c47250f6c6dd.png)


And there are no logs about the `Full GC (Allocation Failure)` (expected after seeing the CPU graph)

We will adjust the memory again to allow an extra 20% memory free for non-heap and give an update next week
