### ISSUE TITLE
Manually Set SCRAM Password

### ISSUE THREAD

**Issue by MrFishFinger** [strimzi/strimzi-kafka-operator#2698]
According to the docs [0], the SCRAM user credential is automatically generated by the User Operator as a "random 12 character password".

Is it possible to manually set this password? eg by pre-creating a secret and disabling generation ?

(apologies if this question has already been covered elsewhere)

[0] https://strimzi.io/docs/master/#supported_scram_credentials

**Comment by scholzj** [comment]
If you create the secret with the matching name and matching structure containing the password, IIR the User Operator should be able to take it and just use it.

**Comment by MrFishFinger** [comment]
hi @scholzj, thanks for that tip. You are absolutely correct, pre-creating the secret with the same name as the new user works.

for those interested, this is the yaml required to pre-create the secret for a user with the name "strimziUser1":
```yaml
kind: Secret
apiVersion: v1
metadata:
  name: strimziUser1
type: Opaque
stringData:
  password: 'a_very_secure_password'
```
