### ISSUE TITLE
[Question] Strimzi 0.16.2. "The OpenShift route API is not available in this Kubernetes cluster"

### ISSUE THREAD

**Issue by jxadro** [strimzi/strimzi-kafka-operator#2700]
Hi.

I'm creating a Kafka cluster with this CR:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: nsX
spec:
  kafka:
    version: 2.4.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
      external:
        type: route
        tls: false
    storage:
      type: ephemeral
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
But I'm getting this status:
```
Status:
  Conditions:
    Last Transition Time:  2020-03-13T19:26:13+0000
    Message:               The OpenShift route API is not available in this Kubernetes cluster. Exposing Kafka cluster my-cluster using routes is not possible.
    Reason:                NoStackTraceThrowable
    Status:                True
    Type:                  NotReady
```

In this cluster I created a Kafka server like these two days ago and it worked, since then I had a problem with the hypervisor and the virtual machines were rebooted so may be something didn't start correctly.

What is behind this message so I could debug or report it accurately?

Thank you.
