### ISSUE TITLE
[Bug] mm2 recreate doesn't seem to work

### ISSUE THREAD

**Issue by carlobongiovanni** [strimzi/strimzi-kafka-operator#2715]
**Describe the bug**
Hi, I'm playing with mm2 and on the first install of it, it worked correctly, the resources are created and all looks fine. 
after that I deleted the mm2 and reinstalled it and according to the operator there is nothing to be done, but the mm2 deployment is not created anymore. 

I'm using the release 0.17.0-rc2

```
2020-03-18 15:47:37 INFO  ClusterOperator:125 - Triggering periodic reconciliation for namespace *...
2020-03-18 15:47:37 INFO  AbstractOperator:122 - Reconciliation #367(timer) Kafka(nonprod-seller-kfk/seller): Kafka seller should be created or updated
2020-03-18 15:47:37 INFO  AbstractOperator:122 - Reconciliation #368(timer) KafkaMirrorMaker2(nonprod-seller-kfk/seller-mm2-cluster): KafkaMirrorMaker2 seller-mm2-cluster should be created or updated
2020-03-18 15:47:37 INFO  AbstractOperator:262 - Reconciliation #368(timer) KafkaMirrorMaker2(nonprod-seller-kfk/seller-mm2-cluster): reconciled
2020-03-18 15:47:38 INFO  AbstractOperator:262 - Reconciliation #367(timer) Kafka(nonprod-seller-kfk/seller): reconciled
```

the mm2 cluster is setup to use as source a non-strimzi kafka cluster on version 2.0, and as target cluster a strimzi kafka 2.4.0

I have tried to delete the topics left after the installation of mm2 on the destination cluster, and I have also tried to delete completely the destination cluster, but it seems it makes no difference. 

I have also tried installing in a separate namespace, same results.

I haven't tried to delete the topics created in the source cluster.

Please note that on my setup I have also done the upgrade of the strimzi operator, the first installed version was 0.14.0 and I have upgraded it up to the latest one. 

**To Reproduce**
1. install a cluster 2.4.0
2. install mm2 
3. delete mm2
4. try to install mm2 again

**Expected behavior**
The mm2 should be recreated.

**Environment (please complete the following information):**
 - Strimzi version: [0.17.0-rc2]
 - Installation method: [YAML files, Helm chart]
 - Kubernetes cluster: [GKE]
 - Infrastructure: [Google Cloud]

**YAML files and logs**

```
 apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: seller-mm2-cluster
spec:
  version: 2.4.0
  replicas: 2
  # target
  connectCluster: {{ .Values.clusterName }}
  clusters:
  - alias: "ecg-nonprod"
    bootstrapServers: source-lb:9092
  - alias: "euwe-seller-nonprod"
    bootstrapServers: target-lb:9094
    authentication:
      type: scram-sha-512
      username: mm2-connect
      passwordSecret:
        secretName: mm2-connect
        password: password
    config:
      config.storage.replication.factor: 2
      offset.storage.replication.factor: 2
      status.storage.replication.factor: 2
    tls:
      trustedCertificates:
      - certificate: ca.crt
        secretName: {{ .Values.clusterName }}-cluster-ca-cert
  mirrors:
  - sourceCluster: "ecg-nonprod"
    targetCluster: "euwe-seller-nonprod"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: "^seller.*|^move-seller.*"
    groupsPattern: ".*"
```
