### ISSUE TITLE
Setting max.request.size for Producer

### ISSUE THREAD

**Issue by rsolano** [strimzi/strimzi-kafka-operator#2716]
Similarly to #2592, I'm setting the value for `max.request.size` in the `KafkaConnect` CRD:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: connect-cluster
spec:
  version: 2.4.0
  replicas: 1
  bootstrapServers: kafka-cluster-kafka-bootstrap:9093
  ...
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
    offset.flush.timeout.ms: 50000
    max.request.size: 8388608
```
The log shows the correct value at first:
```
# Provided configuration
..
max.request.size=8388608
..
```
Until I start my [postgres connector](https://debezium.io/documentation/reference/1.1/connectors/postgresql.html) via the `REST` interface:
```
2020-03-18 20:40:20,082 INFO Instantiated connector postgres-connector with version 1.0.2.Final of type class io.debezium.connector.postgresql.PostgresConnector (org.apache.kafka.connect.runtime.Worker) [pool-6-thread-1]
2020-03-18 20:40:20,086 INFO ProducerConfig values:
...
	max.request.size = 1048576
...
```

Is there any way to prevent `max.request.size` from being reset to the default value?

I'm using:
- Strimzi 0.16.2
- A custom Kafka Connect image based on `strimzi/kafka:0.16.2-kafka-2.4.0`

**Comment by scholzj** [comment]
To be honest, when looking into that case it always worked for me. So I'm not sure what could be the problem. What Strimzi does is it really just takes these values, generates a config file with them and starts Kafka Connect. The rest is up to Connect and the connectors.

**Comment by scholzj** [comment]
@tombentley You heard about any bugs like this in the Kafka Community?

**Comment by rsolano** [comment]
Thanks for the quick response @scholzj. 

It turns out I just needed to set `producer.max.request.size` to ensure the producer worker picked it up.

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: connect-cluster
spec:
  ...
  config:
    ..
    max.request.size: 8388608
    producer.max.request.size: 8388608
```

Not sure why my consumer doesn't require a `consumer.max.request.size` counterpart, but it works.
