### ISSUE TITLE
[Bug] custom nodeAffinity ineffective due to rack-aware nodeAffinity

### ISSUE THREAD

**Issue by joekohlsdorf** [strimzi/strimzi-kafka-operator#2720]
**Describe the bug**

In 0.16.0 a change was introduced which sets nodeAffinity when rack awareness is enabled: https://github.com/strimzi/strimzi-kafka-operator/pull/2347

When an operator sets their own node affinity to select specific nodes they end up with both rules. So far so good.
BUT, the K8s docs state the following: `If you specify multiple matchExpressions associated with nodeSelectorTerms, then the pod can be scheduled onto a node if one of the matchExpressions is satisfied.`

The pods can be scheduled on nodes which meet only one of the two conditions.
We are seeing this unwanted behavior in multiple clusters.

**To Reproduce**

Bring up a cluster with a containing custom node affinity, for example:
```
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: dedicated
                  operator: In
                  values:
                  - kafka
```

You'll end up with a statefulset with the following spec:
```
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - kafka
            - matchExpressions:
              - key: failure-domain.beta.kubernetes.io/zone
                operator: Exists
```

**Expected behavior**

If custom node affinity is set, it MUST be respected under all circumstances.

**Environment (please complete the following information):**
 - Strimzi version: 0.16.2
 - Installation method: YAML
 - Kubernetes cluster: 1.16
 - Infrastructure: AWS kops

**Comment by scholzj** [comment]
Yeah, I think this is a bug. I guess when we added (it was probably me) we didn't realised that it is executed as _OR_. I guess we should instead inject it into the `matchExpressions` which is _AND_. I will have a look at it tomorrow or over the weekend and see if I can get it fixed still in 0.17.0.

**Comment by scholzj** [comment]
I opened a PR for this which should make sure the affinity looks like this:

```yaml
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: dedicated
                operator: In
                values:
                - kafka
              - key: failure-domain.beta.kubernetes.io/zone
                operator: Exists
```

That should resolve this.
