### ISSUE TITLE
[Bug] Not all labels are propagated from template

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#2743]
When user specifies labels in the template section, they should be propagated even when they are app.kubernetes.io labels (or at least some of them). For example in this case:

```yaml
    template:
      statefulset:
        metadata:
          labels:
            app: spring-music-cdc
            app.kubernetes.io/part-of: spring-music-cdc
            template: spring-music-cdc
```

Here the {{app.kubernetes.io/part-of}} label should be propagated to indicate what application is this part of. This should not apply to any strimzi.io labels which are our own.
