### ISSUE TITLE
[Enhancement] Add support for ExternalKafka kind

### ISSUE THREAD

**Issue by avif** [strimzi/strimzi-kafka-operator#2821]
**Is your feature request related to a problem? Please describe.**
Strimzi kafka operator is great!
I would like to use it in some cases to operate on a managed kafka service (mainly: topic & user management via k8s resources), but that's a bit complicated right now...
You need to install the operator, deploy entity operator parts manually and manage certificates manually as well.

**Describe the solution you'd like**
I suggest adding a new resource type: ExternalKafka
this resource will be similar to the Kafka resource in that it will contain all the details of the external kafka connection and the entity operator configuration.
Example:
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: ExternalKafka
metadata:
  name: external-cluster
spec:
  externalKafka:
    externalBootstrapService: external-kafka-bootstrap:9092
    externalZookeeperService: external-zookeeper-client:2181
#    TLS certificates
    clusterCa: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    clientsCa: |-
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
#    clients-ca-cert for user operator
    clientsCaCert: -----BEGIN PRIVATE KEY-----
      ...
      -----END PRIVATE KEY-----
  entityOperator:
    topicOperator: {}
    userOperator: {}
``` 

Note that I ignored some auth methods and certificate renewals, but these seem to be solved already today and may be implemented here too.

Note also that the user operator can't currently automate certificate generation with an external CA (no CSR process) and can't configure ACL's for externally generated users it seems (see https://github.com/strimzi/strimzi-kafka-operator/issues/2358).

**Describe alternatives you've considered**
This can all be achieved with deploying entity operator parts manually (overriding bootstrap servers and zookeeper env variables) and manage certificates manually as well.

**Additional context**
None that I can think of.
