### ISSUE TITLE
Can I create user without creating/updating Secret?

### ISSUE THREAD

**Issue by dilox** [strimzi/strimzi-kafka-operator#2828]
Hi Strimzi!
I am using this file to create KafkaUser, I would like to know if there is a way to say to the user-operator to not create/update the secret, since I manage it by the application.

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: username
  namespace: namespace
  labels:
    strimzi.io/cluster: kafka-external
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: topic-name
          patternType: literal
        operation: All
```

**Comment by scholzj** [comment]
What do you mean with _I manage it by the application_? You can use something like this:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: username
  namespace: namespace
  labels:
    strimzi.io/cluster: kafka-external
spec:
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: topic-name
          patternType: literal
        operation: All
```

Which will not create the password and only set the ACLs. But you cannot create the SCRAM-HA user manually with that, because the operator would delete it. If you want to manage your users manually, you can just disable the User Operator and not use it.
