### ISSUE TITLE
[Enhancement] Allow external config for KafkaConnector

### ISSUE THREAD

**Issue by mikekamornikov** [strimzi/strimzi-kafka-operator#2866]
**Is your feature request related to a problem? Please describe.**
We plan to implement a custom operator for entities which besides other things cause creation of `KafkaConnector` resources. These connectors have 40+ config settings each and 3/4 of that is usually a copy paste and can be considered a reasonable default. Supporting all possible values is hard to both implement and maintain. Additionally it causes a basic copy/paste issue - you change the value in place A and forget to do the same in place B.

**Describe the solution you'd like**
It'll be great to move common configuration to some ConfigMap and leave inline config for overrides.

**Describe alternatives you've considered**
- moving common configuration to `KafkaConnect`
Only a small subset of configuration can be moved. And it tunes worker for a specific connector type.
- moving common configuration to some connector default settings
It's not supporter by my connector.

**Additional context**
<details>
    <summary>Only 7-8 values are important for me. But I have to specify them all:</summary>

```yaml
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.hostname: cxp-perf-02-ac-1.cluster-c1jkvsjbpkil.us-west-2.rds.amazonaws.com
    database.port: "3306"
    database.user: "${file:/opt/kafka/external-configuration/cxp-perf-02/dbcreds.properties:MYSQL_USER}"
    database.password: "${file:/opt/kafka/external-configuration/cxp-perf-02/dbcreds.properties:MYSQL_PASSWORD}"
    database.server.id: "6402"
    database.server.name: cxp-perf
    database.ssl.mode: preferred
    database.whitelist: "db_cxp_perf_\\w+"
    table.blacklist: "^\\w+\\.audit_events$,^\\w+\\.\\w+_audit$,^\\w+\\.activities\\w*$,^\\w+\\.\\w+_backup$,^\\w+\\.\\w+_bak$,^\\w+\\.\\w*config\\w*$,^\\w+\\.\\w*cache\\w*$,^\\w+\\.oauth_\\w+$,^\\w+\\.\\w+_queue$,^\\w+\\.session_\\w+$,^\\w+\\.team_sets_modules$,^\\w+\\.team_sets_users_\\w+$,^\\w+\\.tracker\\w*$"
    database.history.kafka.bootstrap.servers: b-1.cxp-k8s-usw2-dev.wfq4wf.c3.kafka.us-west-2.amazonaws.com:9094,b-2.cxp-k8s-usw2-dev.wfq4wf.c3.kafka.us-west-2.amazonaws.com:9094,b-3.cxp-k8s-usw2-dev.wfq4wf.c3.kafka.us-west-2.amazonaws.com:9094
    database.history.kafka.topic: cxp-perf-02.stack.dbhistory
    database.history.producer.security.protocol: SSL
    database.history.consumer.security.protocol: SSL
    key.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: "false"
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: "true"
    tombstones.on.delete: "false"
    decimal.handling.mode: double
    time.precision.mode: connect
    include.schema.changes: "false"
    snapshot.mode: initial
    snapshot.locking.mode: minimal
    snapshot.lock.timeout.ms: 28800000
    snapshot.delay.ms: 5000
    transforms: RerouteToDbTopic,AddDBNameToKey,ExtractDbName,RerouteToStackTopic
    transforms.RerouteToDbTopic.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.RerouteToDbTopic.regex: "([a-zA-Z0-9_\\-]+)\\.([a-zA-Z0-9_\\-]+)\\.([a-zA-Z0-9_\\-]+)"
    transforms.RerouteToDbTopic.replacement: $2
    transforms.AddDBNameToKey.type: "org.apache.kafka.connect.transforms.InsertField$Key"
    transforms.AddDBNameToKey.topic.field: db
    transforms.ExtractDbName.type: "org.apache.kafka.connect.transforms.ExtractField$Key"
    transforms.ExtractDbName.field: db
    transforms.RerouteToStackTopic.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.RerouteToStackTopic.regex: (.*)
    transforms.RerouteToStackTopic.replacement: cxp-perf-02.stack.data
    max.queue.size: "16384"
    max.batch.size: "4096"
    producer.override.acks: "1"
    producer.override.compression.type: zstd
    producer.override.linger.ms: "10"
    producer.override.batch.size: "163840"
    producer.override.buffer.memory: "335544320"
```
</details>

**Comment by avif** [comment]
Have you tried FileConfigProvider with a ConfigMap mounted as a volume?
https://strimzi.io/docs/master/#external_configuration_as_volumes

Also, you could probably implement some mechanism to read a ConfigMap from the k8s api, override some of it's values and apply that to whatever connector template you are applying with your operator.

**Comment by scholzj** [comment]
My understanding of the proposal correctly, I think it is basically asking for something liek this:

```
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    fromConfigMap: my-configuration
```

I think that is not a bad idea.

**Comment by mikekamornikov** [comment]
@scholzj I see it more like this:
```yaml
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1

  externalConfiguration:
  - name: defaults
    valueFrom:
      configMapRef: debezium-default-config
  - name: perf-tweaks
    valueFrom:
      configMapRef: debezium-optimized-config
  - name: common-db-creds
    valueFrom:
      secretRef: debezium-db-creds

  config:
    # overrides on top of defaults and other merged external configs
    transforms: RerouteToStackTopic
    transforms.RerouteToStackTopic.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.RerouteToStackTopic.regex: (.*)
    transforms.RerouteToStackTopic.replacement: cxp-dev.stack.data
```
