### ISSUE TITLE
[Bug] False diff when reconciling PVC size

### ISSUE THREAD

**Issue by glindstedt** [strimzi/strimzi-kafka-operator#2877]
**Describe the bug**

Strimzi does not seem to convert between `Ti` and `Gi` when reconciling a StatefulSet's persistentVolumeClaimTemplate. We encountered this issue when deploying a Kafka cluster with the storage claim set to `3072Gi` which happens to be exactly equal to `3Ti`. It appears that kubernetes will realize this and convert it to the more terse `3Ti` when you query the manifest, however Strimzi does not and thinks that the storage claim size has changed.

NOTE: This can be mitigated by simply specifying `3Ti` in the Kafka resource manifest.

**To Reproduce**
1. Deploy a Kafka resource with persistent storage claim size set to `3072Gi`

**Expected behavior**
Strimzi realizes that the values are equivalent and no change has occurred.

**Environment (please complete the following information):**
 - Strimzi version: 0.17.0
 - Installation method: YAML Files
 - Kubernetes cluster: 1.14.10
 - Infrastructure: GKE

**YAML files and logs**

Kafka yaml definition
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
...
spec:
  kafka:
    storage:
      class: kafka-data
      type: persistent-claim
      size: 3072Gi
      deleteClaim: false
      selector:
        kafka-cluster: adevents
...
```

Resulting statefulsets storage request:
```
$ kubectl get statefulsets adevents-kafka -o jsonpath='{.spec.volumeClaimTemplates[0].spec.resources.requests.storage}'
3Ti
```

Relevant logline from reconciliation:
```
2020-04-23 09:30:08 DEBUG StatefulSetDiff:100 - StatefulSet dataflow-ad-kafka/adevents-kafka differs: {"op":"replace","path":"/spec/volumeClaimTemplates/0/spec/resources/requests/storage","value":"3072Gi"}
```
