### ISSUE TITLE
Updating kafka broker properties after deployment

### ISSUE THREAD

**Issue by ananthk01** [strimzi/strimzi-kafka-operator#2961]
Hi,

I currently have kafka running with a set of config properties which I would like to expand on. 
```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: kafka-test
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.3"
```
I tried to add the properties to the kafka.yaml and apply that. 

```yaml
      auto.create.topics.enable: true
      num.partitions: 5
      default.replication.factor: 3
```
Describing the pods still shows the old set of properties. 

```
      KAFKA_CONFIGURATION:           log.message.format.version=2.3
                                     offsets.topic.replication.factor=3
                                     transaction.state.log.min.isr=2
                                     transaction.state.log.replication.factor=3

```

I attempted to restart the kafka and zookeeper pods but it still doesn't take effect. Is it possible to have the new set of broker configuration properties to be applied without having to start from scratch?
