### ISSUE TITLE
[Question] why does my k8s not pull the image?

### ISSUE THREAD

**Issue by tirelibirefe** [strimzi/strimzi-kafka-operator#3003]
Hello; 
I'm not sure it's operator issue or not need to ask.
I would like to deploy a KafkaConnect cluster by using Strimzi on Kubernetes. I customized and uploaded my Docker images.

First I've created crendtial secret:

```kubectl create secret -n kafka docker-registry harborcred --docker-server=harbor.dev-kik.io --docker-username=someone --docker-password=HiddenPassword12345```

I'm using following yaml:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: beytepe-connect-cluster
  namespace: kafka
annotations:
  strimzi.io/use-connector-resources: "true"
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
spec:
  version: 2.4.0
  replicas: 2
  containers:
  - name: kc-with-debezium-mssql
    image: harbor.dev-kik.io/kafka/kc-with-debezium-mssql:v0.1
    imagePullPolicy: Always
  imagePullSecrets:
  - name: harborcred
  bootstrapServers: kafka-beytepe-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: kafka-beytepe-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: dbz-mssql-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status

```
When I apply the yaml, Kubernetes pretends there is no container definition and pull kafka 2.4.0 image all the time even I delete the version line. My image is proper, it can be pulled by docker pull.

What am I missing? Could you please advise?

**Comment by scholzj** [comment]
You cannot just take whatever configuration Kubernetes has an expect the operator to use it. That is not how it works. You have to follow the structure as supported by Strimzi. So in this case, I think you should use something like this:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: beytepe-connect-cluster
  namespace: kafka
annotations:
  strimzi.io/use-connector-resources: "true"
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
spec:
  version: 2.4.0
  image: harbor.dev-kik.io/kafka/kc-with-debezium-mssql:v0.1
  replicas: 2
  bootstrapServers: kafka-beytepe-kafka-bootstrap:9093
  tls:
    trustedCertificates:
      - secretName: kafka-beytepe-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: dbz-mssql-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
  template:
    pod:
      imagePullSecrets:
        - name: harborcred
```
