### ISSUE TITLE
[Question] Kafka broker failed to read meta.properties

### ISSUE THREAD

**Issue by klalafaryan** [strimzi/strimzi-kafka-operator#3012]
Hey all,

we have noticed couple of times that one of our brokers fails to start with following exception:
```
java.nio.file.FileSystemException: /var/lib/kafka/data/kafka-log0/meta.properties.tmp: Input/output error
```

We have tried to delete the pod, and we got the same exception. After deleting the pod 3rd time it worked.

We are using the latest version of strimzi. (0.17.0)

Do you have some ideas ?

Thanks.

**Comment by scholzj** [comment]
No idea to be honest. What kind of storage are you using? Could it be some kind of storage issue?

**Comment by klalafaryan** [comment]
@scholzj  thanks for your quick reply.

We are using AWS EBS volumes, with following storage class:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: $STORAGE_CLASS_NAME
  namespace: $NAMESPACE
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
parameters:
  fsType: ext4
  type: gp2
  encrypted: "true"
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
```

So for we can't see any problems.
