### ISSUE TITLE
s3 connector - where should I put minio accesskey and secretkey?

### ISSUE THREAD

**Issue by tirelibirefe** [strimzi/strimzi-kafka-operator#3027]
Hello;
I would like to use s3sink connector to write data to a minio bucket.
Minio recommends authentication but all kafka connect documentation is prepared for AWS, not for Mino.

I put following lines into my connector config file:

```
  config:
    s3.proxy.user: AKIAIOSFODNN7EXAMPLE
    s3.proxy.password: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    s3.proxy.url: http://minio.dev-kik.io/
    store.url: http://minio.dev-kik.io/minio/dosyalar/
```
...but Kafka didn't accept.

```
2020-05-15 03:25:15,898 ERROR WorkerSinkTask{id=minio-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-minio-connector-0]
org.apache.kafka.connect.errors.ConnectException: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@6b197352: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@7fd78297: Failed to connect to service endpoint: ]
```

How can I make s3connector authenticated to write data to Minio? Where should I put credentials?
