### ISSUE TITLE
[Bug] CruiseControl doesn't handle empty goals

### ISSUE THREAD

**Issue by im-konge** [strimzi/strimzi-kafka-operator#3090]
**Describe the bug**
When we want to deploy CruiseControl with empty `goals` or `default.goals`, Kafka will have error in it's status:

```
- lastTransitionTime: 2020-05-25T19:52:28+0000
      message: goals - Unsupported type class java.util.LinkedHashMap in configuration
        for this key
      reason: InvalidConfigParameterException
      status: "True"
      type: NotReady
```

**To Reproduce**
1. Add `goals: {}` or `default.goals: {}` to CC config

**YAML files and logs**

```
spec:
    cruiseControl:
      capacity:
        networkIn: 10000KB/s
        networkOut: 10000KB/s
      config:
        goals: {}

    ...

  status:
    conditions:
    - lastTransitionTime: 2020-05-25T19:52:28+0000
      message: goals - Unsupported type class java.util.LinkedHashMap in configuration
        for this key
      reason: InvalidConfigParameterException
      status: "True"
      type: NotReady
```
https://gist.github.com/im-konge/98b1a2649b4d48ac088763c6399ae3ae
