### ISSUE TITLE
[Bug] FileNotFoundException when creating new Kafka instance

### ISSUE THREAD

**Issue by sutaakar** [strimzi/strimzi-kafka-operator#3092]
**Describe the bug**
When I create a new Kafka instance using Strimzi operator, the zookeeper pod doesn't start correctly. I can see repeated `java.io.FileNotFoundException: /tmp/zookeeper/cluster.keystore.p12 (No such file or directory)` error in zookeeper pod log.
Strimzi operator also doesn't create kafka pods.

This problem occurs in case I specify number of zookeeper replicas to 1.
The issue seems intermittent, I wasn't able to reproduce it reliably.

If I terminate the zookeeper pod and let operator spin up new zookeeper then the issue disappears.

**To Reproduce**
1. Create new project on OpenShift
2. Install Strimzi operator from OperatorHub directly into created project (no cluster wide installation)
3. Create Custom Resource
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.5'
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
4. Wait until zookeeper pod is instantiated and started
5. Open zookeeper pod log (in OpenShift console or using OC client)
6. See error in log

**Expected behavior**
Zookeeper pod is correctly started, kafka pods are created and working. Zookeeper and Strimzi operator log don't contain any error.

**Environment (please complete the following information):**
 - Strimzi version: 0.18.0
 - Installation method: OperatorHub.io
 - Kubernetes cluster: OpenShift 4.4.3 (OCP)
 - Infrastructure: OpenStack

**YAML files and logs**
[report-26-05-2020_11-01-55.zip](https://github.com/strimzi/strimzi-kafka-operator/files/4681034/report-26-05-2020_11-01-55.zip)

**Additional context**
