### ISSUE TITLE
[Kafka Mirror Maker- Unable to delete the deployment as it is recreating every time since the operator is watching] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3095]
Hi Team,

We have deployed MirrorMaker more than once with changes every time, however, the previous pods are not getting deleted even after deleting the deployment or making the replica set to 0. 

```
apiVersion: kafka.strimzi.io/v1beta1
  kind: KafkaMirrorMaker
  metadata:
    name: mmtest
  spec:
    version: 2.4.0
    replicas: 1
    consumer:
      bootstrapServers: cluster2-kafka-external-bootstrap:9094
      groupId: hello-world-consumer-grp
    producer:
      bootstrapServers: cluster-backup-kafka-external-bootstrap:9094
    whitelist: happy-topic
```

Need help to know how can we clean the existing POD's/Deployments. 

**PODS Information:**

pod/kafka-mm-v1-mirror-maker-5fb655bdd6-2xl4v        0/1     Running            0          47s
pod/mirrormaker-v1-mirror-maker-789f96f5c-wvvfn      0/1     Running            4          107s
pod/mmtest-mirror-maker-6dcf74b447-n4zsm             0/1     Running            0          14m
pod/my-mirror-maker-mirror-maker-7884ffbc8b-4rgt5    0/1     Running            0          107s

**Deployment Information:**

deployment.apps/kafka-mm-v1-mirror-maker           0/1     1            0           115m
deployment.apps/mirrormaker-v1-mirror-maker        0/1     1            0           25m
deployment.apps/mmtest-mirror-maker                0/1     1            0           14m
deployment.apps/my-mirror-maker-mirror-maker       0/1     1            0           24m
deployment.apps/my-mirror-maker-new-mirror-maker   0/0     0            0           26m

**Replicaset Information:**

replicaset.apps/kafka-mm-v1-mirror-maker-5fb655bdd6           1         1         0       115m
replicaset.apps/mirrormaker-v1-mirror-maker-789f96f5c         1         1         0       25m
replicaset.apps/mmtest-mirror-maker-6dcf74b447                1         1         0       14m
replicaset.apps/my-mirror-maker-mirror-maker-7884ffbc8b       1         1         0       24m
replicaset.apps/my-mirror-maker-new-mirror-maker-5568485f7f   0         0         0       26m

**Strimzi Operator:**

deployment.apps/strimzi-operator                   1/1     1            1           5d4h
replicaset.apps/strimzi-operator-7dbd899d8b                   1         1         1       5d4h
