### ISSUE TITLE
[Kafka MirrorMaker CR - Which one to be considered?????] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3097]
Hi Team,

We have a few questions about which KafkaMirrorMaker CR has to be used for strimzi operator. 

1) **https://github.com/strimzi/strimzi-kafka-operator/blob/release-0.17.x/examples/kafka-mirror-maker/kafka-mirror-maker-tls.yaml**

Can we use this CR if our kafka is 2.4.0 and strimzi is 0.17.0?

2) We have also noticed another detailed configuration based CR in the 0.17.0 documentation, referring to the following link.

https://strimzi.io/docs/0.17.0/#assembly-deployment-configuration-kafka-mirror-maker-str

Q1) How different these 2 CR's in terms of functionalities and which one to consider when?
Q2) I have noticed consumer and producer bootstraps has been shown with 9092 port with tls enabled, Why do we need tls for 9092, is it for an example only?, As per my understanding 9093/9094 can also be used as they are bootstrap services running on TLS encrypted ports, am i correct?
Q3) In point (2) under 3.4.1. Configuring the Kafka MirrorMaker section we have  2 CR's with kind as KafkaMirrorMaker and KafkaMirrorMaker2, however, 1st one has image and 2nd one doesn't...

What does the image represents here?? 

I have clubbed all my questions in a single post based on my understanding of the documentation. Please help and address accordingly.

**Comment by scholzj** [comment]
Since Kafka 2.4, Kafka has two versions of Mirror Maker : the old version _1_ and the new version _2_. Right now we support both and each works a bit differently. But ultimately the version 2 is the future. 

Some of the differences are described in our docs and in this blog post: https://strimzi.io/blog/2020/03/30/introducing-mirrormaker2/ ... plus I'm sure the Kafka docs have something as well. But right now you can choose any of them depending on your preferences.

**Comment by vperi1730** [comment]
Sure, thanks for the info, We are trying to set up the mirror maker with source cluster in 1 namespace and target in the other, something like below.

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: mmtest
spec:
  version: 2.4.0
  replicas: 1
  consumer:
    bootstrapServers: cluster2-kafka-bootstrap:9093
    groupId: hello-world-consumer-grp
    tls:
      trustedCertificates:
        - secretName: cluster2-cluster-ca-cert
          certificate: ca.crt 
  producer:
    bootstrapServers: mm-backup-cluster-kafka-bootstrap:9093
    abortOnSendFailure: false
    tls:
      trustedCertificates:
      - secretName: mm-backup-cluster-cluster-ca-cert
        certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: backup-user
        certificate: ca.crt
        key: ca.key
    config:
      compression.type: gzip
      batch.size: 8192
  whitelist: ".*"
```

However, while deploying the CR from source namespace there is an issue noticed which says 

 **Warning  FailedMount  19s (x8 over 83s)  kubelet, gke-gtso-enter-gke-g-gtso-enter-gke-g-ace0200e-0r0b  MountVolume.SetUp failed for volume "backup-user" : secret "backup-user" not found
  Warning  FailedMount  19s (x8 over 83s)  kubelet, gke-gtso-enter-gke-g-gtso-enter-gke-g-ace0200e-0r0b  MountVolume.SetUp failed for volume "mm-backup-cluster-cluster-ca-cert" : secret "mm-backup-cluster-cluster-ca-cert" not found**

Need help on how do we achieve this...

**Comment by scholzj** [comment]
It looks like the secrets you are refering to do not exist. Kubernetes in general allow mounting only secrets in the sme namespace - so if these secrets are in a different namespace, you will need to copy them manually.

**Comment by vperi1730** [comment]
OK, I have noticed it is not able to resolve the bootstrap server mm-backup-cluster-Kafka-bootstrap:9093...

**2020-05-27 08:37:52,092 WARN Couldn't resolve server mm-backup-cluster-kafka-bootstrap:9093 from bootstrap.servers as DNS resolution failed for mm-backup-cluster-kafka-bootstrap (org.apache.kafka.clients.ClientUtils) [main]
2020-05-27 08:37:52,093 INFO [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 0 ms. (org.apache.kafka.clients.producer.KafkaProducer) [main]
2020-05-27 08:37:52,100 ERROR Exception when starting mirror maker. (kafka.tools.MirrorMaker$) [main]**

Considering this situation if I want to use 2 individual clusters for testing the mirror maker, is there a way to achieve?

**Comment by scholzj** [comment]
Where is that cluster running? Again, if it is in a different namespace, you will need to use more qualified address - <service><namespace>.svc for example.

**Comment by vperi1730** [comment]
OK, we made all the changes recommended, and here is how our CR looks now...

```
#Kafka Mirror Maker
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: mmtest
spec:
  version: 2.4.0
  replicas: 1
  consumer:
    bootstrapServers: cluster2-kafka-bootstrap.kafka-1.svc.cluster.local:9093
    groupId: hello-world-consumer-grp
    tls:
      trustedCertificates:
        - secretName: cluster2-cluster-ca-cert
          certificate: ca.crt 
  producer:
    bootstrapServers: mm-backup-cluster-kafka-bootstrap.kafka-mirror.svc.cluster.local:9093
    abortOnSendFailure: false
    tls:
      trustedCertificates:
      - secretName: mm-backup-cluster-cluster-ca-cert
        certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: backup-user
        certificate: ca.crt
        key: ca.key
    config:
      compression.type: gzip
      batch.size: 8192
  whitelist: ".*"
```

1) Secrets are copied manually into the source cluster.
2) bootstrap servers has been added with the qualified address.

After all the changes when we are launching the mirror maker, the following is the error observed.

**(org.apache.kafka.clients.producer.ProducerConfig) [main]
2020-05-27 09:49:54,044 INFO [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 0 ms. (org.apache.kafka.clients.producer.KafkaProducer) [main]
2020-05-27 09:49:54,050 ERROR Exception when starting mirror maker. (kafka.tools.MirrorMaker$) [main]
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:432)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:298)
        at kafka.tools.MirrorMaker$MirrorMakerProducer.<init>(MirrorMaker.scala:372)
        at kafka.tools.MirrorMaker$MirrorMakerOptions.checkArgs(MirrorMaker.scala:540)
        at kafka.tools.MirrorMaker$.main(MirrorMaker.scala:90)
        at kafka.tools.MirrorMaker.main(MirrorMaker.scala)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /tmp/kafka/producer.keystore.p12 of type PKCS12
        at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:71)
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
        at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:450)
        at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:421)
        ... 5 more
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /tmp/kafka/producer.keystore.p12 of type PKCS12
        at org.apache.kafka.common.security.ssl.SslEngineBuilder.createSSLContext(SslEngineBuilder.java:163)
        at org.apache.kafka.common.security.ssl.SslEngineBuilder.<init>(SslEngineBuilder.java:104)
        at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:95)
        at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:69)
        ... 10 more
Caused by: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /tmp/kafka/producer.keystore.p12 of type PKCS12**

**Comment by scholzj** [comment]
Can you please share the full log from the Mirror Maker pods from the real beginning where it prints the config etc.? Also, can you share the Kafka CRs for the two clusters?

**Comment by vperi1730** [comment]
1) Kafka CR used for both the clusters----
```
#Kafka/Zookeeper CR 
kafkaYaml: |-
  apiVersion: kafka.strimzi.io/v1beta1
  kind: Kafka
  metadata:
    name: mm-backup-cluster
  spec:
    clusterCa:
      generateCertificateAuthority: true
    clientsCa:
      generateCertificateAuthority: true
    kafka:
      version: 2.4.0
      replicas: 3
      listeners:
         plain: {}
         tls:
           authentication:
             type: tls
         external:
           type: loadbalancer
           tls:  true
           authentication: 
             type: tls
           overrides:
             bootstrap:
               address: kafka.dns.acl.com
      authorization:
        type: simple        
      logging:
       type: inline
       loggers:
         kafka.root.logger.level: "DEBUG"      
      metrics:
        lowercaseOutputName: true
        rules: 
        #Special cases and very specific rules
        - pattern : kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
          name: kafka_server_$1_$2
          type: GAUGE
          labels:
            clientId: "$3"
            topic: "$4"
            partition: "$5"
              
      storage:
        type: persistent-claim
        size: 10Gi
        deleteClaim: false        
      config:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
        log.message.format.version: "2.4"
        
    zookeeper:
      replicas: 3
      logging:
        type: inline
        loggers:
          zookeeper.root.logger: "DEBUG"   
      storage:
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
    entityOperator:
      topicOperator: {}
      userOperator: {}
```

2) Logs of the mirror maker POD-----

Preparing truststore
Certificate was added to keystore
Preparing truststore is complete
Preparing truststore
Certificate was added to keystore
Preparing truststore is complete
Preparing keystore
No certificate matches private key
Preparing keystore is complete
Kafka Mirror Maker consumer configuration:
# Bootstrap servers
bootstrap.servers=cluster2-kafka-bootstrap.kafka-1.svc.cluster.local:9093
# Consumer group
group.id=hello-world-consumer-grp
# Provided configuration


security.protocol=SSL
# TLS / SSL
ssl.truststore.location=/tmp/kafka/consumer.truststore.p12
ssl.truststore.password=[hidden]
ssl.truststore.type=PKCS12



Kafka Mirror Maker producer configuration:
# Bootstrap servers
bootstrap.servers=mm-backup-cluster-kafka-bootstrap.kafka-mirror.svc.cluster.local:9093
# Provided configuration
batch.size=8192
compression.type=gzip


security.protocol=SSL
# TLS / SSL
ssl.truststore.location=/tmp/kafka/producer.truststore.p12
ssl.truststore.password=[hidden]
ssl.truststore.type=PKCS12
ssl.keystore.location=/tmp/kafka/producer.keystore.p12
ssl.keystore.password=[hidden]
ssl.keystore.type=PKCS12


OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
2020-05-27 10:21:07,877 INFO Starting readiness poller (io.strimzi.mirrormaker.agent.MirrorMakerAgent) [main]
2020-05-27 10:21:07,959 INFO Starting liveness poller (io.strimzi.mirrormaker.agent.MirrorMakerAgent) [main]
2020-05-27 10:21:08,178 INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$) [main]
2020-05-27 10:21:08,576 INFO Starting mirror maker (kafka.tools.MirrorMaker$) [main]
WARNING: The default partition assignment strategy of the mirror maker will change from 'range' to 'roundrobin' in an upcoming release (so that better load balancing can be achieved). If you prefer to make this switch in advance of that release add the following to the corresponding config: 'partition.assignment.strategy=org.apache.kafka.clients.consumer.RoundRobinAssignor'
2020-05-27 10:21:08,638 INFO ProducerConfig values: 
	acks = all
	batch.size = 8192
	bootstrap.servers = [mm-backup-cluster-kafka-bootstrap.kafka-mirror.svc.cluster.local:9093]
	buffer.memory = 33554432
	client.dns.lookup = default
	client.id = 
	compression.type = gzip
	connections.max.idle.ms = 540000
	delivery.timeout.ms = 2147483647
	enable.idempotence = false
	interceptor.classes = []
	key.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
	linger.ms = 0
	max.block.ms = 9223372036854775807
	max.in.flight.requests.per.connection = 1
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = SSL
	security.providers = null
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = /tmp/kafka/producer.keystore.p12
	ssl.keystore.password = [hidden]
	ssl.keystore.type = PKCS12
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = /tmp/kafka/producer.truststore.p12
	ssl.truststore.password = [hidden]
	ssl.truststore.type = PKCS12
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
 (org.apache.kafka.clients.producer.ProducerConfig) [main]
2020-05-27 10:21:08,749 INFO [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 0 ms. (org.apache.kafka.clients.producer.KafkaProducer) [main]
2020-05-27 10:21:08,754 ERROR Exception when starting mirror maker. (kafka.tools.MirrorMaker$) [main]
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:432)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:298)
	at kafka.tools.MirrorMaker$MirrorMakerProducer.<init>(MirrorMaker.scala:372)
	at kafka.tools.MirrorMaker$MirrorMakerOptions.checkArgs(MirrorMaker.scala:540)
	at kafka.tools.MirrorMaker$.main(MirrorMaker.scala:90)
	at kafka.tools.MirrorMaker.main(MirrorMaker.scala)
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /tmp/kafka/producer.keystore.p12 of type PKCS12
	at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:71)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:146)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:67)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:99)
	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:450)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:421)
	... 5 more
Caused by: org.apache.kafka.common.KafkaException: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /tmp/kafka/producer.keystore.p12 of type PKCS12
	at org.apache.kafka.common.security.ssl.SslEngineBuilder.createSSLContext(SslEngineBuilder.java:163)
	at org.apache.kafka.common.security.ssl.SslEngineBuilder.<init>(SslEngineBuilder.java:104)
	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:95)
	at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:69)
	... 10 more
Caused by: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /tmp/kafka/producer.keystore.p12 of type PKCS12
	at org.apache.kafka.common.security.ssl.SslEngineBuilder$SecurityStore.load(SslEngineBuilder.java:292)
	at org.apache.kafka.common.security.ssl.SslEngineBuilder.createSSLContext(SslEngineBuilder.java:144)
	... 13 more
Caused by: java.io.IOException: Short read of DER length
	at sun.security.util.DerInputStream.getLength(DerInputStream.java:582)
	at sun.security.util.DerValue.init(DerValue.java:391)
	at sun.security.util.DerValue.<init>(DerValue.java:332)
	at sun.security.util.DerValue.<init>(DerValue.java:345)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:1938)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at org.apache.kafka.common.security.ssl.SslEngineBuilder$SecurityStore.load(SslEngineBuilder.java:289)
	... 14 more
Exception in thread "main" java.lang.NullPointerException
	at kafka.tools.MirrorMaker$.main(MirrorMaker.scala:97)
	at kafka.tools.MirrorMaker.main(MirrorMaker.scala)
2020-05-27 10:21:08,760 INFO Start clean shutdown. (kafka.tools.MirrorMaker$) [MirrorMakerShutdownHook]
2020-05-27 10:21:08,760 INFO Shutting down consumer threads. (kafka.tools.MirrorMaker$) [MirrorMakerShutdownHook]
2020-05-27 10:21:08,761 INFO Closing producer. (kafka.tools.MirrorMaker$) [MirrorMakerShutdownHook]
Exception in thread "MirrorMakerShutdownHook" java.lang.NullPointerException
	at kafka.tools.MirrorMaker$.cleanShutdown(MirrorMaker.scala:175)
	at kafka.tools.MirrorMaker$MirrorMakerOptions$$anon$2.run(MirrorMaker.scala:524)

**Comment by scholzj** [comment]
So, I think there are several problems:
* The consumer has no authentication configured although you seem to have it in your Kafka cluster
* The authentication configuration for the producer seems to be wrong - it say the certificate and key do not match. You should for this basically copy the secret created for given cluster with `KafkaUser`.

**Comment by vperi1730** [comment]
Ok, Also do Kafka topic replicate from the source cluster to target just with whitelist: ".*"  in the CR or any other configuration is needed for this?

**Comment by scholzj** [comment]
I'm really not an expert on the Mirror Maker, so I might not remember it correctly. But AFAIK:
* It does not mirror the topics automatically. You either need to manually create them on the other side or you need to have the auto creation of the topics enabled in which case they will be auto created by the broker but with the defalt settings. The MM2 does thi sbetter and can actually mirror the topic settings etc.
* The Mirror Maker is client as any other. So when you have authorization enabled, you have to give the mirror maker the same users as to any other user - so to produce / consumer / create the topics. The broker logs normally tell you which rights you might be missing.

**Comment by vperi1730** [comment]
We have enabled the MM2 by adding the source and target cluster information and their certificates. Following is the CR.

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: brcm-mirror-maker2
spec:
  version: 2.4.0 
  replicas: 1
  connectCluster: "mm-backup-cluster"
  clusters:
  - alias: "mm-src-cluster"
    authentication:
      certificateAndKey:
        certificate: user.crt
        key: user.key
        secretName: mm-consumer-user
      type: tls
    bootstrapServers: mm-src-cluster-kafka-bootstrap.kafka-mirror-src.svc:9093
    tls:
      trustedCertificates:
      - certificate: ca.crt
        secretName: mm-src-cluster-clients-ca-cert
  - alias: "mm-backup-cluster"
    authentication:
      certificateAndKey:
        certificate: user.crt
        key: user.key
        secretName: mm-producer-user
      type: tls
    bootstrapServers: mm-backup-cluster-kafka-bootstrap.kafka-mirror.svc.cluster.local:9093
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
    tls:
      trustedCertificates:
      - certificate: ca.crt
        secretName: mm-backup-cluster-clients-ca-cert
  mirrors:
  - sourceCluster: "mm-src-cluster"
    targetCluster: "mm-backup-cluster"
    sourceConnector:
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector: 
      config:
        heartbeats.topic.replication.factor: 1 
    checkpointConnector: 
      config:
        checkpoints.topic.replication.factor: 1 
    topicsPattern: ".*"
    groupsPattern: ".*" 
```

After enabling all the certificates, secrets, Kafka users, and Kafka topics we have triggered producer and consumer script for message producing and consumption.

However, we are able to produce it successfully, on the consumer end we are receiving the SSL handshake primarily on the VM nodes which we are not sure why is it happening. Need real help in this, available to provide any info. 

Attaching the file which has the error.
[nodelog.log](https://github.com/strimzi/strimzi-kafka-operator/files/4696466/nodelog.log)

**Comment by scholzj** [comment]
Sorry, I'm not sure I understand where do these logs come from. The MM2 config looks good to me. In the log, I can see that the `mm-producer-user` connected but does not have sufficient rights as it contains authroization errors. I'm not sure what or who is 10.90.0.156 which has the TLS errors. So no idea why is that happening.

**Comment by vperi1730** [comment]
These are the VM nodes...

k8soptr@jumpbox:~$ kubectl get nodes -n kafka-mirror -o wide
NAME                                                  STATUS   ROLES    AGE     VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                             KERNEL-VERSION   CONTAINER-RUNTIME
gke-gtso-enter-gke-g-gtso-enter-gke-g-ac145f10-clzv   Ready    <none>   7d      v1.16.8-gke.15   10.90.0.166                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-ac145f10-gxqw   Ready    <none>   7d      v1.16.8-gke.15   10.90.0.169                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-ac145f10-p04p   Ready    <none>   8d      v1.16.8-gke.15   10.90.0.151                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-ac145f10-qqfx   Ready    <none>   8d      v1.16.8-gke.15   10.90.0.150                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-ace0200e-0r0b   Ready    <none>   8d      v1.16.8-gke.15   10.90.0.156                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-ace0200e-3q52   Ready    <none>   7d      v1.16.8-gke.15   10.90.0.168                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-ace0200e-6q84   Ready    <none>   2d1h    v1.16.8-gke.15   10.90.0.182                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-ace0200e-d57k   Ready    <none>   8d      v1.16.8-gke.15   10.90.0.158                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-f4873fba-5whj   Ready    <none>   8d      v1.16.8-gke.15   10.90.0.148                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-f4873fba-kf31   Ready    <none>   6d21h   v1.16.8-gke.15   10.90.0.172                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-f4873fba-q6tt   Ready    <none>   7d      v1.16.8-gke.15   10.90.0.167                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1
gke-gtso-enter-gke-g-gtso-enter-gke-g-f4873fba-zjs7   Ready    <none>   8d      v1.16.8-gke.15   10.90.0.145                 Container-Optimized OS from Google   4.19.109+        docker://19.3.1

**Comment by scholzj** [comment]
> Any specific permissions needed for this topic as we didn't create this...

MM2 is using these topics for storing the internal data. But TBH I do not have a list anywhere and it might depend on your configuration. So I guess you should just reverse engineer it from the denied operations and check the Kafka docs if the have some list. I do not have it running anywhere right now to check what topics did it created.

> These are the VM nodes...

I'm not sure I understand. Why do they try to connect to Kafka (with misconfigured TLS)?

**Comment by vperi1730** [comment]
Ok, Can you please check this if you get any pointers about the Kafka connect stopping and topic auth failing.

2020-05-28 15:59:29,612 INFO Kafka version: 2.4.0 (org.apache.kafka.common.utils.AppInfoParser) [DistributedHerder-connect-1]
2020-05-28 15:59:29,612 INFO Kafka commitId: 77a89fcf8d7fa018 (org.apache.kafka.common.utils.AppInfoParser) [DistributedHerder-connect-1]
2020-05-28 15:59:29,612 INFO Kafka startTimeMs: 1590681569612 (org.apache.kafka.common.utils.AppInfoParser) [DistributedHerder-connect-1]
2020-05-28 15:59:29,644 INFO [Consumer clientId=consumer-mirrormaker2-cluster-1, groupId=mirrormaker2-cluster] Cluster ID: UYTj0E0PQOmG9PAb6axowg (org.apache.kafka.clients.Metadata) [DistributedHerder-connect-1]
2020-05-28 15:59:29,647 ERROR [Worker clientId=connect-1, groupId=mirrormaker2-cluster] Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [DistributedHerder-connect-1]
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [mirrormaker2-cluster-offsets]
2020-05-28 15:59:29,662 INFO Stopped http_8083@2f3c6ac4{HTTP/1.1,[http/1.1]}{0.0.0.0:8083} (org.eclipse.jetty.server.AbstractConnector) [Thread-1]
2020-05-28 15:59:29,663 INFO node0 Stopped scavenging (org.eclipse.jetty.server.session) [Thread-1]
2020-05-28 15:59:29,860 INFO Started o.e.j.s.ServletContextHandler@1280851e{/,null,AVAILABLE} (org.eclipse.jetty.server.handler.ContextHandler) [main]
2020-05-28 15:59:29,860 INFO REST resources initialized; server is started and ready to handle requests (org.apache.kafka.connect.runtime.rest.RestServer) [main]
2020-05-28 15:59:29,861 INFO Kafka Connect started (org.apache.kafka.connect.runtime.Connect) [main]
2020-05-28 15:59:29,861 INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect) [Thread-10]
2020-05-28 15:59:29,861 INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer) [Thread-10]
2020-05-28 15:59:29,861 INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer) [Thread-10]
2020-05-28 15:59:29,861 INFO [Worker clientId=connect-1, groupId=mirrormaker2-cluster] Herder stopping (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [Thread-10]
2020-05-28 15:59:34,863 INFO [Worker clientId=connect-1, groupId=mirrormaker2-cluster] Herder stopped (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [Thread-10]
2020-05-28 15:59:34,863 INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect) [Thread-10]

**Comment by scholzj** [comment]
No idea ... I guess because of this?

```
2020-05-28 15:59:29,647 ERROR [Worker clientId=connect-1, groupId=mirrormaker2-cluster] Uncaught exception in herder work thread, exiting: (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [DistributedHerder-connect-1]
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [mirrormaker2-cluster-offsets]
```

**Comment by vperi1730** [comment]
We tried creating the mirrormaker2-cluster-offsets topic manually and gave access to the kafkauser, even then while MM2 is getting launched due to auth failure Kafka connect is stopping which in turn is making MM crash. 

We are presently not sure how to resolve this issue as we attempted all the possible ways, it would be good if you can help us here if possible else if you can connect us to someone in this forum who worked on MM2 and connect really well who can target this.

Logs are the same as the above. 

Thanks for all the support, it was a great help till date :)

**Comment by scholzj** [comment]
The Connect logs do not really say the details about the rights. But the broker logs will give ou more fetails abotu the authorization errors.

**Comment by vperi1730** [comment]
OK sure.

Also, when I am referring to the Kafka connect CR, 1 question I have is, for the bootstrap will the trusted cert be always been the cluster CA crt or can it be the client CA crt as well??

https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/kafka-connect/kafka-connect.yaml

In my case with the below CR, there is an SSL handshake observed. 

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: mm-backup-connect
#  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
#    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.4.0
  replicas: 1
  bootstrapServers: mm-backup-cluster-kafka-bootstrap.kafka-mirror.svc.cluster.local:9093
  tls:
    trustedCertificates:
      - secretName: mm-backup-cluster-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
```

**Comment by scholzj** [comment]
You cannot create the consumer group. But you need to give it the rights to use the consumer group in the KafkaUser ACLs.

**Comment by vperi1730** [comment]
Here is my user CR and MM CR.
```
#kafkauser.yaml
kafkauserYaml: |-
  apiVersion: kafka.strimzi.io/v1beta1
  kind: KafkaUser
  metadata:
    name: mm-user-9092
    labels:
      strimzi.io/cluster: mm-src-cluster
  spec:
    authentication:
      type: tls
    authorization:
      type: simple
      acls:
        - resource:
            type: topic
            name: mm-topic-9092
          operation: Read
          type: allow
        - resource:
            type: topic
            name: mm-topic-9092
          operation: Describe
          type: allow
        - resource:
            type: group
            name: mm-group-9092
            patternType: literal
          operation: Read
          host: "*"
```

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: brcm-mirror-maker-9092
spec:
  version: 2.4.0
  replicas: 1
  consumer:
    bootstrapServers: mm-src-cluster-kafka-bootstrap.kafka-mirror-src.svc:9092
    groupId: mm-group-9092
  producer:
    bootstrapServers: mm-backup-cluster-kafka-bootstrap.kafka-mirror.svc:9092
  whitelist: ".*"
```

I still see the error, please correct me.
