### ISSUE TITLE
[Bug] Helm install strimzi/strimzi-kafka-operator pod fails with error ErrImagePull in minikube

### ISSUE THREAD

**Issue by saranyaeu2987** [strimzi/strimzi-kafka-operator#3098]
**Describe the bug**
I tried to install helm chart strimzi/strimzi-kafka-operator in minikube but pod failed with error **ErrImagePull**  (reference document https://strimzi.io/blog/2018/11/01/using-helm/)

**To Reproduce**

```
//Install minikube 
minikube --memory 20g --cpus 3 start

//add repo
helm repo add strimzi https://strimzi.io/charts/

//install chart
helm install strimzi-kafka strimzi/strimzi-kafka-operator

```
**Output of above command**
NAME: strimzi-kafka-operator-1590524093
LAST DEPLOYED: Tue May 26 15:14:55 2020
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Thank you for installing strimzi-kafka-operator-0.18.0
```

Now, if I do  
kubectl get pods
NAME                                        READY   STATUS         RESTARTS   AGE
strimzi-cluster-operator-54565f8c56-5rjp4   0/1     ErrImagePull   0          19s
```

**Expected behavior**
Pod strimzi-cluster-operator should be in running status. Why the Imagepull failed.?

**Comment by scholzj** [comment]
Can you do `kubectl get pod strimzi-cluster-operator-54565f8c56-5rjp4 -o yaml` and share the output? It should point to the image `strimzi/operator:0.18.0` which for me pulls fine.

**Comment by saranyaeu2987** [comment]
output of ```kubectl get pod strimzi-cluster-operator-54565f8c56-5rjp4 -o yaml```

....
```
spec:
  containers:
  - args:
    - /opt/strimzi/bin/cluster_operator_run.sh
    env:
    - name: STRIMZI_NAMESPACE
......
    image: strimzi/operator:0.18.0
    imagePullPolicy: IfNotPresent
........  
containerStatuses:
  - image: strimzi/operator:0.18.0
    imageID: ""
    lastState: {}
    name: strimzi-cluster-operator
    ready: false
    restartCount: 0
    started: false
    state:
      waiting:
        message: Back-off pulling image "strimzi/operator:0.18.0"
        reason: ImagePullBackOff
```
....

**Comment by scholzj** [comment]
Does it help if you edit the deployment and change the image name from `strimzi/operator:0.18.0` to `docker.io/strimzi/operator:0.18.0`?

**Comment by saranyaeu2987** [comment]
Trivial qq: I Dont have deployment yaml file as I was using charts repo.
I see this configuration in  https://github.com/strimzi/strimzi-kafka-operator/blob/master/helm-charts/strimzi-kafka-operator/values.yaml 

```
image:
  repository: strimzi
  name: operator
  tag: latest
```
Can I edit this file ? if so where can I include **docker.io** in that yaml file
