### ISSUE TITLE
[Question] Kafka connect pod keeps crashing in minikube

### ISSUE THREAD

**Issue by saranyaeu2987** [strimzi/strimzi-kafka-operator#3109]
Here is my deployment.yaml file 

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
spec:
  image: strimzi/kafka:0.16.1-kafka-2.4.0
  replicas: 1
  bootstrapServers: 54.189.50.146:9092 
  externalConfiguration:
    volumes:
      - name: aws-credentials
        secret:
          secretName: aws-credentials
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false

```

When deployed , the pod crashes for below reason

2020-05-27 23:14:38,880 ERROR [Worker clientId=connect-1, groupId=connect-cluster] Uncaught exception in herder work thread, exiting:  (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [DistributedHerder-connect-1]
**org.apache.kafka.common.errors.TimeoutException: Failed to get offsets by times** in 30002ms
2020-05-27 23:14:38,882 INFO Kafka Connect stopping (org.apache.kafka.connect.runtime.Connect) [Thread-10]
2020-05-27 23:14:38,883 INFO Stopping REST server (org.apache.kafka.connect.runtime.rest.RestServer) [Thread-10]
2020-05-27 23:14:38,886 INFO Stopped http_8083@76318a7d{HTTP/1.1,[http/1.1]}{0.0.0.0:8083} (org.eclipse.jetty.server.AbstractConnector) [Thread-1]
2020-05-27 23:14:38,887 INFO node0 Stopped scavenging (org.eclipse.jetty.server.session) [Thread-1]
2020-05-27 23:14:38,889 INFO REST server stopped (org.apache.kafka.connect.runtime.rest.RestServer) [Thread-10]
2020-05-27 23:14:38,889 INFO [Worker clientId=connect-1, groupId=connect-cluster] Herder stopping (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [Thread-10]
2020-05-27 23:14:43,894 INFO [Worker clientId=connect-1, groupId=connect-cluster] Herder stopped (org.apache.kafka.connect.runtime.distributed.DistributedHerder) [Thread-10]
2020-05-27 23:14:43,894 INFO Kafka Connect stopped (org.apache.kafka.connect.runtime.Connect) [Thread-10]

Googling says the topic **__consumer_offsetss** might be out of sync and asked to restart the kafka server but it didnt help.

I dont see any errors reported in my kafka logs. 

Any suggestion on how to investigate or resolve this pod issue ??
