### ISSUE TITLE
[Kafka User- How do we support any topic access in the user while creating??] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3127]
Hi Team,

We have created a Kafkauser and we would like to give access to any topic which the user attempts to access. Added a wildcard ".*" under name to support this,  However, it didn't work, need help.

```
  apiVersion: kafka.strimzi.io/v1beta1
  kind: KafkaUser
  metadata:
    name: consumer-sha-user
    labels:
      strimzi.io/cluster: mm-src-cluster
  spec:
    authentication:
      type: scram-sha-512
    authorization:
      type: simple
      acls:
        - resource:
            type: topic
            name: ".*"
          operation: Read
          type: allow
        - resource:
            type: topic
            name: ".*"
          operation: Describe
          type: allow
        - resource:
            type: group
            name: sha-consumer-grp
            patternType: literal
          operation: Read
          host: "*"
```
