### ISSUE TITLE
Method to create multiple topics/users in a single trigger

### ISSUE THREAD

**Issue by pashafirdous** [strimzi/strimzi-kafka-operator#3129]
Hello, 
is there a way or do you suggest a Method to create multiple topics/users in a single trigger?

for example, if i want to create hundreds of topics or users. what is the best way i can achieve using the operator?

regards,

**Comment by scholzj** [comment]
I think it depends and what exactly do you want to do. You can create a folder with 100 topics / users and do single `kubectl apply -f` on it. You can also have a script which genertes these in some loop. All you need to be aware that there is nothing transaction like abotu this - the resources will be processes individually as the operator gets them.

**Comment by pashafirdous** [comment]
is there a single line command like below?
```
kubectl create kafkatopic <NAME> <PARAMETER>
```

**Comment by scholzj** [comment]
Not so easy. But you should be able to do something like this:

```
cat <<EOF | kubectl apply -f -
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
EOF
```
