### ISSUE TITLE
[Question] How to add SSL Encryption Configuration to Kafka connectors

### ISSUE THREAD

**Issue by saranyaeu2987** [strimzi/strimzi-kafka-operator#3133]
Our On Prem kafka clusters are **SASL_SSL** security enabled and we need to authenticate and provide truststore location to connect to kafka cluster.

Configuration looks something like this.

```
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<username>" password="<password>";

ssl.truststore.location=
ssl.truststore.password=
```

- How to add this configuration to strimzi kafka connect running on kubernetes deployed using **helm chart strimzi/strimzi-kafka-operator** (minikube) which consumes topics from SASL secured Kafka cluster??
- Any examples , blog post or reference documentation will be helpful!

**Comment by scholzj** [comment]
This is described in the documentation:
* https://strimzi.io/docs/operators/latest/full/using.html#sasl_based_plain_authentication
* https://strimzi.io/docs/operators/latest/full/using.html#assembly-kafka-connect-tls-deployment-configuration-kafka-connect

If you haven't seen that yet, please start there and let us know if you have any questions.

**Comment by scholzj** [comment]
There are also examples here: https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/security/scram-sha-512-auth/connect.yaml ... all you need to change is use PLAIN instead of SCRAM-SHA-512.

**Comment by saranyaeu2987** [comment]
@scholzj 

I used the documentation and created a deployment file as follows

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: selumalai/selumalai-s3-kafkaconnectcamel
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  replicas: 1
  bootstrapServers: *******.com:9092
  authentication:
    type: plain
    username: emdconsumer
    passwordSecret:
      secretName: sasl-user-pass
      password: password
  tls:
    trustedCertificates:
      - secretName: my-secret
        certificate: kafkaclient.certification.truststore.jks
        passwordSecret:
          secretName: truststore-password
          password: password
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
```

secrets are created as 
```
kubectl create secret generic my-secret --from-file=kafkaclient.certification.truststore.jks
kubectl create secret generic sasl-user-pass --from-file=password=sasl-password.txt 
kubectl create secret generic truststore-password --from-file=password=truststore-password.txt
```

But I ended up in error 

```
Caused by: org.apache.kafka.common.KafkaException: Failed to load SSL keystore /tmp/kafka/cluster.truststore.p12 of type PKCS12
	at 
	... 11 more
Caused by: java.nio.file.NoSuchFileException: /tmp/kafka/cluster.truststore.p12
```

Any suggestions on why the keystore file not located!!? 

Attached full log

[logs-from-my-connect-cluster-connect-in-my-connect-cluster-connect-6844f89665-5mcfl.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4719425/logs-from-my-connect-cluster-connect-in-my-connect-cluster-connect-6844f89665-5mcfl.txt)

**Comment by scholzj** [comment]
For the TLS, you have to provide the certificate as PEM encoded public key. You should be able to get it from the truststore with something like this if needed: `keytool -exportcert -keystore truststore.jks  -rfc`. Use that to create the secret and than pass it in the CR as described in the docs or shown in the examples:
```
  tls:
    trustedCertificates:
      - secretName: my-secret
        certificate: my-file.crt
```

**Comment by saranyaeu2987** [comment]
@scholzj 
I now use PEM .cert file. but getting Timeout exception.

is my deployment file right ?
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: selumalai/selumalai-s3-kafkaconnectcamel
  logging:
    type: inline
    loggers:
      connect.root.logger.level: "INFO"
  replicas: 1
  bootstrapServers: w2capl0084101.heb.com:9092
  authentication:
    type: plain
    username: emdconsumer
    passwordSecret:
      secretName: sasl-user-pass
      password: password
  tls:
    trustedCertificates:
      - secretName: my-secret
        certificate: HEBcert.crt
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false

```

Full logs
[logs-from-my-connect-cluster-connect-in-my-connect-cluster-connect-55d9c9f845-x4dr4.txt](https://github.com/strimzi/strimzi-kafka-operator/files/4719750/logs-from-my-connect-cluster-connect-in-my-connect-cluster-connect-55d9c9f845-x4dr4.txt)
