### ISSUE TITLE
[Bug] Adding volumes to JBOD storage does nor work out of the box

### ISSUE THREAD

**Issue by fboismenu** [strimzi/strimzi-kafka-operator#3136]
Hello there!

Thanks for the great product! 

Here is my question / issue:

Context: 

1. Tested with GKE / Kubernetes 1.15.x 1.16.x
2. Create a namespace `kafka`
3. Deployed Strimzi (tested with 0.17.0 and 0.18.0) via helm chart - default values
4. Applied a cluster + topic like the following:
 ```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      log.message.format.version: "2.4"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      plain: {}
      tls: {}
    replicas: 3
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 100Gi
        type: persistent-claim
    version: 2.4.0
  zookeeper:
    replicas: 1
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: "my-cluster"
spec:
  partitions: 3
  replicas: 3
```
5. Create a producer in a separate console:
```
kubectl -n kafka run kafka-producer -ti --image=strimzi/kafka:0.18.0-kafka-2.5.0 --rm=true --restart=Never bash
```
from inside:
```
{ while true; do sleep 1; date; done } | bin/kafka-console-producer.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --topic my-topic
```

6. Create a consume in a separate console:
```
kubectl -n kafka run kafka-consumer -ti --image=strimzi/kafka:0.18.0-kafka-2.5.0 --rm=true --restart=Never bash
```

from inside:
```
bin/kafka-console-consumer.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --topic my-topic
```

7. Add JBOD, by editing kafka/my-cluster CRD
`kubectl edit kafka my-cluster`

Now it looks like:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      log.message.format.version: "2.4"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      plain: {}
      tls: {}
    replicas: 3
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 100Gi
        type: persistent-claim
# Adding this block:
      - deleteClaim: false
        id: 1
        size: 100Gi
        type: persistent-claim
    version: 2.4.0
  zookeeper:
    replicas: 1
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
```

8. Then the operator replaces the STS, we see following warning in:

```
  Warning  FailedUpdate  60s (x2 over 118s)  statefulset-controller  update Pod my-cluster-kafka-1 in StatefulSet my-cluster-kafka failed error: Pod "my-cluster-kafka-1" is invalid:
spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)
  core.PodSpec{
    Volumes: []core.Volume{
-     {
-       Name: "data-1",
-       VolumeSource: core.VolumeSource{
-         PersistentVolumeClaim: &core.PersistentVolumeClaimVolumeSource{ClaimName: "data-1-my-cluster-kafka-1"},                                                                    
-       },
-     },
      {Name: "data-0", VolumeSource: core.VolumeSource{PersistentVolumeClaim: &core.PersistentVolumeClaimVolumeSource{ClaimName: "data-0-my-cluster-kafka-1"}}},                     
```

9. The operator would then delete pod, e.g. `my-cluster-kafka-1`
10. The statefulset is stuck not recreating pod #1, looking at logs of the statefulset controller it seems  that it goes over pods sequentially from 0 to N (3 here).
11. Bouncing pod 0 manually unblocks the rolling upgrade

Please note, that if there's no producer/consumer running the above process works, because the KafkaRoller decides to roll pods in sequence from 0 to 3, like the STS seems to like it.

Other way to demonstrate the issue *without Strimzi* being involved:

1. Create a test STS like following:
```
---
apiVersion: v1
kind: Service
metadata:
  name: "test-sts-headless"
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: test-sts
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: test-sts
spec:
  podManagementPolicy: Parallel
  updateStrategy:
    type: OnDelete
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: test-sts
      app.kubernetes.io/instance: test-sts
  serviceName: "test-sts-headless"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: test-sts
        app.kubernetes.io/instance: test-sts
      annotations:
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: test-sts
          image: alpine
          volumeMounts:
            - name: vol-0
              mountPath: "/volumes/0"
            # - name: vol-1
            #   mountPath: "/volumes/1"
          command: [ "/bin/sh" ]
          args: [ "-c", "trap : TERM INT; sleep infinity & wait" ]
  volumeClaimTemplates:
    - metadata:
        name: vol-0
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "1Gi"
    # - metadata:
    #     name: vol-1
    #   spec:
    #     accessModes: [ "ReadWriteOnce" ]
    #     resources:
    #         requests:
    #             storage: "1Gi"
```

2. Wait for everything to up & running
3. delete sts with `--cascade=false`
4. uncomment new volume, and apply again
5. bounce pod `test-sts--1`
6. STS is "stuck" test-sts-1 is never recreated by StafefulSet controller
7. Bouncing pod #0 would "stuck" the controller

What do you think?
