### ISSUE TITLE
Allow connector API rest access when strimzi.io/use-connector-resources:"true"

### ISSUE THREAD

**Issue by cameronbraid** [strimzi/strimzi-kafka-operator#3143]
Currently when I configure the KafkaConnect resource with the annotation strimzi.io/use-connector-resources: "true", the connector rest API on port 8083 returns http 503

Id like to use the rest api to monitor the status of connectors, so can the rest api be re-enabled ?

**Comment by scholzj** [comment]
Right now, we do not do anything about the REST API (at least until we have some option to restart the connectrs without it). There could be network policies blocking it - but then I would not expect it to return HTTP 503 - you would be not able to connect to it at all.

**Comment by cameronbraid** [comment]
Adding a network policy is the solution

I just based the network policy on the existing kafaka-connect network policy that strimzi creates and target my pods with 
```
      podSelector:
        matchLabels:
          app: kafka-connect-ui
```

full policy below

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-connect-ui
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          strimzi.io/cluster: kafka
          strimzi.io/kind: KafkaConnect
          strimzi.io/name: kafka-connect
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: kafka-connect-ui
    ports:
    - port: 8083
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/cluster: kafka
      strimzi.io/kind: KafkaConnect
      strimzi.io/name: kafka-connect
  policyTypes:
  - Ingress
```
