### ISSUE TITLE
[Question] Adding SSL connection for external listeners 

### ISSUE THREAD

**Issue by nikhileshva** [strimzi/strimzi-kafka-operator#3171]
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: pilcrow
spec:
  kafka:
    version: 2.5.0
    replicas: 1
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: true
        configuration:
          brokerCertChainAndKey:
            secretName: kafka-letsencrypt-cert
            certificate: 4e85e4ac.crt
            key: 4e85e4ac.key
        authentication:
            type: scram-sha-512
        overrides:
          bootstrap:
            nodePort: 31094
          brokers:
            - broker: 0
              nodePort: 31095
              advertisedHost: kafka-bootstrap.domain.com
              advertisedPort: 9094              
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

```

So, I'm trying to add ssl connection from an external client to my Kafka broker. Above is my configuration, but it doesn't work. The client receives `SSL handshake failed`. 
I have a `KafkaUser` type for scram-sha authentication. 

Everything worked when `tls:false` and no config for certs and chain. However, when I add this and the client tries to connect through ssl, it doesn't work. 

Am I missing some config required for ssl to work?
