### ISSUE TITLE
[Kafka-Ingress feature with TLS Passthrough is failing with SSL handshake] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3172]
Hi Team,

We have enabled the external type as ingress for the Kafka CR and also we have installed the Nginx controller which supports TLS pass through, below are the commands and CR used. 

1) 
```
#Kafka/Zookeeper CR 
kafkaYaml: |-
  apiVersion: kafka.strimzi.io/v1beta1
  kind: Kafka
  metadata:
    name: cluster2
  spec:
    clusterCa:
      generateCertificateAuthority: true
    clientsCa:
      generateCertificateAuthority: true
    kafka:
      version: 2.4.0
      replicas: 3
      listeners:
         plain: 
           authentication:
             type: scram-sha-512
         tls:
           authentication:
             type: tls
         external:
          type: ingress
          authentication:
            type: tls
          configuration:
            bootstrap:
              host: cluster2-kafka-external-bootstrap
            brokers:
            - broker: 0
              host: cluster2-kafka-0
            - broker: 1
              host: cluster2-kafka-1
            - broker: 2
              host: cluster2-kafka-2
      authorization:
        type: simple   
```

2) helm install nginx stable/nginx-ingress  --set "rbac.create=true" --set "controller.service.type=LoadBalancer" --set "controller.extraArgs.annotations-prefix=nginx.ingress.kubernetes.io" --set "controller.extraArgs.enable-ssl-passthrough="

We have created the following and kept in place.
1) Cluster and user certificates
2) DNS with name as cluster2-Kafka-external-bootstrap within the Kubernetes cluster under Cloud DNS.
3) Kafka users and topics are also in place. 
4) Strimzi version is 0.17.0
5) Kafka is 2.4.0

With all the above configuration call to the producer script is throwing us SSL handshake which we expect it shouldn't as it supports the passthrough. 

Need your help to let us know if we are really missing something in the configuration and why is it trying to do SSL handshake?

**Command Call**:
**[kafka@cluster1-kafka-0 kafka]$ ./bin/kafka-console-producer.sh --broker-list cluster2-kafka-external-bootstrap:443 --topic ingress-topic \
> --producer-property security.protocol=SSL \
> --producer-property ssl.truststore.type=PKCS12 \
> --producer-property ssl.keystore.type=PKCS12 \
> --producer-property ssl.truststore.password=123456 \
> --producer-property ssl.keystore.password=123456 \
> --producer-property ssl.truststore.location=/tmp/prod/cluster.truststore.p12 \
> --producer-property ssl.keystore.location=/tmp/prod/producer.keystore.p12
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
>[2020-06-08 15:32:57,907] ERROR [Producer clientId=console-producer] Connection to node -1 (cluster2-kafka-external-bootstrap/35.245.76.206:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2020-06-08 15:32:58,066] ERROR [Producer clientId=console-producer] Connection to node -1 (cluster2-kafka-external-bootstrap/35.245.76.206:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2020-06-08 15:32:58,427] ERROR [Producer clientId=console-producer] Connection to node -1 (cluster2-kafka-external-bootstrap/35.245.76.206:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2020-06-08 15:32:59,554] ERROR [Producer clientId=console-producer] Connection to node -1 (cluster2-kafka-external-bootstrap/35.245.76.206:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)**

Attaching the error logs for reference.

[kafka-ingress.log](https://github.com/strimzi/strimzi-kafka-operator/files/4747128/kafka-ingress.log)
