### ISSUE TITLE
[Question] oc start-build on a KafkaConnect pod can't seem to find my IBM COS Sink Connector

### ISSUE THREAD

**Issue by jackyng88** [strimzi/strimzi-kafka-operator#3185]
Hey so this might be a really silly question but on an OpenShift cluster with the Strimzi Operator installed I have a KafkaConnect S2I pod up.

I might be going about this the wrong way but I built the JAR from this repo https://github.com/ibm-messaging/kafka-connect-ibmcos-sink

Anyways I used an `oc start-build connect-cluster-pod --from-dir ./connectors/` where the connectors folder has the built connector binary/JAR. Next I'm trying to create a CRD for a KafkaConnector by applying the below yaml

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: cos-sink-connector
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: com.ibm.eventstreams.connect.cossink.COSSinkConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    topics: <topic-name>
    cos.api.key: <api-key>
    cos.bucket.location: <region>
    cos.bucket.name: <bucket-name>
    cos.bucket.resiliency: regional
```

Next when I run `oc get kafkaconnector cos-sink-connector -o yaml` I receive this following error

```
message: 'PUT /connectors/cos-sink-connector/config returned 500 (Internal Server
        Error): Failed to find any class that implements Connector and which name
        matches com.ibm.eventstreams.connect.cossink.COSSinkConnector
```

Apologies if I'm going about this in completely the wrong way.

**Comment by jackyng88** [comment]
> So, did the S2I build succeeded? Did the DeploymentConfig rolled to use the new image? What exactly does the status of the different resources show and how do they look like?

Hey, sorry for the delay.

This section is in the deploymentconfig 

```
Deployment #2 (latest):
	Name:		jng-connect-cluster-101-connect-2
	Created:	17 hours ago
	Status:		Complete
	Replicas:	1 current / 1 desired
	Selector:	deployment=jng-connect-cluster-101-connect-2,deploymentconfig=jng-connect-cluster-101-connect,strimzi.io/cluster=jng-connect-cluster-101,strimzi.io/kind=KafkaConnectS2I,strimzi.io/name=jng-connect-cluster-101-connect
	Labels:		app.kubernetes.io/instance=jng-connect-cluster-101,app.kubernetes.io/managed-by=strimzi-cluster-operator,app.kubernetes.io/name=kafka-connect,app.kubernetes.io/part-of=strimzi-jng-connect-cluster-101,openshift.io/deployment-config.name=jng-connect-cluster-101-connect,strimzi.io/cluster=jng-connect-cluster-101,strimzi.io/kind=KafkaConnectS2I,strimzi.io/name=jng-connect-cluster-101-connect
	Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
Deployment #1:
	Created:	17 hours ago
	Status:		Complete
	Replicas:	0 current / 0 desired
```

Deployment #1 was the original successful build of the S2I. I used these steps originally for the Apache Camel Kafka Connectors and this worked fine, I'm guessing it might be a problem with the way the IBM COS Sink Connector is built maybe?

For instance this is the the KafkaConnectS2I (that can't find the.connector) - 

```
status:
    buildConfigName: jng-connect-cluster-101-connect
    conditions:
    - lastTransitionTime: "2020-06-10T20:32:57.476Z"
      status: "True"
      type: Ready
    connectorPlugins:
    - class: org.apache.kafka.connect.file.FileStreamSinkConnector
      type: sink
      version: 2.5.0
    - class: org.apache.kafka.connect.file.FileStreamSourceConnector
      type: source
      version: 2.5.0
    - class: org.apache.kafka.connect.mirror.MirrorCheckpointConnector
      type: source
      version: "1"
    - class: org.apache.kafka.connect.mirror.MirrorHeartbeatConnector
      type: source
      version: "1"
    - class: org.apache.kafka.connect.mirror.MirrorSourceConnector
      type: source
      version: "1"
    observedGeneration: 1
    url: http://jng-connect-cluster-101-connect-api.jng-es-cos.svc:8083
```
