### ISSUE TITLE
[Question] Is Kafka Connect cluster accessible via REST API outside K8S cluster?

### ISSUE THREAD

**Issue by saranyaeu2987** [strimzi/strimzi-kafka-operator#3201]
As per this document https://strimzi.io/docs/operators/latest/using.html#availability_of_the_kafka_connect_rest_api
looks like kafka connect cluster is accessible via <connect-cluster-name>-connect-api:8083.
 here is my kafka connect definition
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: emd-kafka-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
image: selumalai/selumalai-s3-kafkaconnecttestd:1.0.0
  logging:
.....
```

But if I curl, I get "Host not resolved issue". Is the REST API exposed outside K8S cluster ?

```
$ curl http://emd-kafka-cluster-connect-api:8083
curl: (6) Could not resolve host: emd-kafka-cluster-connect-api
```

I am interested in to know about the topics status. is there a way to find from kafka connect cluster via API?

EDIT:
@scholzj 
looks like https://github.com/strimzi/strimzi-kafka-operator/issues/130 is still open. Can you please confirm if kafka connect is accessible outside cluster or not ?

**Comment by scholzj** [comment]
#130 is not implemented and TBH I'm not sure anymore we still plan it since there are lot of issues with things around security and the Connector operator makes it less important. And you cannot access Kubernetes services from the outside. But you can easily create some Ingress or some additional loadbalancer or node port service to expose it. 

Also, keep in mind that when you enable the connector operator, we have to create a network policy which will guarantee that our operators will have access to the Connect REST API in environments with default-to-deny network policies. But the default-to-deny and default-to-allow are hard to detect - so in case you have defaut-to-allow network policies, it will block the access to the REST API for other apps. So what you have to do is to create an additional network policy (with your own name) which would allow the application from which you are trying to connect the access. You shouldkeep it in mind if for example using Ingress to expose the REST API.

> I am interested in to know about the topics status. is there a way to find from kafka connect cluster via API?

I not sure what exactly do you have in mind. But I do nto think the Connect API offers you any infromation about topics. It will let you manage and monitor the connectors and that is it.

**Comment by saranyaeu2987** [comment]
@scholzj 
I was exploring UI for kafka connect clusters for better visualization of topics consumed, cluster details etc.
Lensesio https://github.com/lensesio/kafka-connect-ui offers UI for kafka connect which requires connect cluster url. 

Please do let me know if there are any other better alternatives within Strimzi or other open source.

**Comment by cameronbraid** [comment]
fyi I use kafka-connect-ui and to make it work with strimzi managed kafak connect I add the following network policy

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-connect-ui
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          strimzi.io/cluster: kafka
          strimzi.io/kind: KafkaConnect
          strimzi.io/name: kafka-connect
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: kafka-connect-ui
    ports:
    - port: 8083
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/cluster: kafka
      strimzi.io/kind: KafkaConnect
      strimzi.io/name: kafka-connect
  policyTypes:
  - Ingress
```

This was based on the existing network policy 'kafka-connect' and changing the podSelector/matchLabels to target my kafaka-connect-ui pods
```
      podSelector:
        matchLabels:
          app: kafka-connect-ui
```

**Comment by saranyaeu2987** [comment]
@cameronbraid 
I would like to clarify the below.
1. Did you add new NetworkPolicy or have you edited the networkpolicy provided by Strimzi to add the following? 

```
podSelector:
        matchLabels:
          app: kafka-connect-ui
```

**Comment by scholzj** [comment]
You have to add new policy ... if you edit the Strimzi one it will revert the changes.

**Comment by saranyaeu2987** [comment]
@scholzj 
I have added new network policy 

```
$ kubectl get networkpolicies
NAME                        POD-SELECTOR                                                                                                  AGE
emd-kafka-cluster-connect   strimzi.io/cluster=emd-kafka-cluster,strimzi.io/kind=KafkaConnect,strimzi.io/name=emd-kafka-cluster-connect   4d17h

kafka-connect-ui            strimzi.io/cluster=emd-kafka-cluster,strimzi.io/kind=KafkaConnect,strimzi.io/name=emd-kafka-cluster-connect   2m2s
```

Here is the definition of kafka-connect-ui  

```
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: kafka-connect-ui
spec:
  ingress:
  - from:
    - podSelector:
        matchLabels:
          strimzi.io/cluster: emd-kafka-cluster
          strimzi.io/kind: KafkaConnect
          strimzi.io/name: emd-kafka-cluster-connect
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          app: kafka-connect-ui
    ports:
    - port: 8083
      protocol: TCP
  podSelector:
    matchLabels:
      strimzi.io/cluster: emd-kafka-cluster
      strimzi.io/kind: KafkaConnect
      strimzi.io/name: emd-kafka-cluster-connect
  policyTypes:
  - Ingress
```

I still get host not resolved error. 

```
$ curl http://emd-kafka-cluster-connect-api:8083
curl: (6) Could not resolve host: emd-kafka-cluster-connect-api
```

I am highly doubtful if I am doing it right. Any suggestions ?
