### ISSUE TITLE
DNS remains unassigned on GCP

### ISSUE THREAD

**Issue by pascals-ager** [strimzi/strimzi-kafka-operator#3213]
Hello,

I am trying to bring u Strimzi using this manifest:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 2.4.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: loadbalancer
        overrides:
          bootstrap:
            address: kafka-bootstrap-stg.test.com
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap-stg.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
              address: kafka-bootstrap-stg.test.com
          brokers:
          - broker: 0
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-0-stg.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
              advertisedHost: kafka-broker-0-stg.test.com            
          - broker: 1
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-1-stg.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
              advertisedHost: kafka-broker-1-stg.test.com
          - broker: 2
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-broker-2-stg.test.com.
              external-dns.alpha.kubernetes.io/ttl: "60"
              advertisedHost: kafka-broker-2-stg.test.com
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5      
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.4"
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 4000m
        memory: 4Gi      
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false     
  zookeeper:
    replicas: 3
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5    
    resources:
      requests:
        cpu: 1000m
        memory: 1Gi
      limits:
        cpu: 4000m
        memory: 4Gi            
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false      
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"    
```

I see that an `EXTERNAL_IP` is assigned correctly:
```
kubectl get svc kafka-cluster-kafka-external-bootstrap -o=jsonpath='{.status.loadBalancer.ingress[0].ip}{"\n"}' -n kafka
34.**.**.**
```
However, this remains empty:
```
kubectl get svc kafka-cluster-kafka-external-bootstrap -o=jsonpath='{.status.loadBalancer.ingress[0].hostname}{"\n"}' -n kafka
```

Is there something specific to Google Cloud that I am missing or is there something wrong with my manifest? Appreciate all inputs..
