### ISSUE TITLE
[Question] Is Strimzi compatible with k8s v1.16?

### ISSUE THREAD

**Issue by cannontrodder** [strimzi/strimzi-kafka-operator#3235]
I have Strimzi v0.17.0 currently installed and am investigating upgrading our EKS dev cluster to kubernetes v1.16 (in EKS)

The [Upgrde pre-requisites](https://docs.aws.amazon.com/eks/latest/userguide/update-cluster.html#1-16-prequisites) suggest that we update certain resource API versions, in particular, NetworkPolicies:

> NetworkPolicy resources will no longer be served from extensions/v1beta1 in v1.16. Migrate use to the networking.k8s.io/v1 API, available since v1.8. Existing persisted data can be retrieved through the networking.k8s.io/v1 API.

A query of NetworkPolicy resources in our cluster shows:

```
bash-5.0# kubectl get NetworkPolicy/tombola-kafka-cluster-network-policy-kafka  -n kafka -o yaml
apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  creationTimestamp: "2020-06-16T14:55:20Z"
  generation: 1
  labels:
    app: tombola-kafka-cluster
    app.kubernetes.io/instance: tombola-kafka-cluster
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: strimzi
    application: tombola-kafka-cluster
    chart: tombola-kafka-cluster-0.0.16
...
```

If I upgrade our cluster, I'm expecting this to break. Does strimzi support the `networking.k8s.io/v1` api? Can you give me any advice on how to proceed here? (I'm tempted to try the upgrade but I have no roll-back option)
