### ISSUE TITLE
[Question] what is the correct way to install Prometheus? Documentation is not clear.

### ISSUE THREAD

**Issue by tirelibirefe** [strimzi/strimzi-kafka-operator#3236]
Hello;
I've read the documentation but haven't understood the order.

In order to install Prometheus on Kubernetes;

1)should I install kube-prometheus independently and then apply modified sample configurations? (didn't work)
└── prometheus-install
    ├── alert-manager.yaml (8)
    ├── prometheus-rules.yaml (9)
    ├── prometheus.yaml (10)
    ├── strimzi-pod-monitor.yaml (11)
    └── strimzi-service-monitor.yaml (12)

2)or instead of deploying kube-prometheus via bundle.yaml, should I only apply Strimzi example configurations after modfiying them? IThis way doesn't install operator. (didn't work)

3)Documentation says apply "prometheus-operator-deployment.yaml". This is completely confusing, because applying only prometheus-operator-deployment.yaml doesn't install prometheus operator alone.

Could you please advise?

Thanks & Reagrds

**Comment by tirelibirefe** [comment]
Also, does prometheus operator and Kafka have to be in the same namespace?

**Comment by scholzj** [comment]
@stanlyDoge @ppatierno Can you help? You are the Prometheus experts ;-)

**Comment by tirelibirefe** [comment]
I installed Prometheus operator under namespace=kafka.
I changed namespaces and applied examples/metrics/prometheus-install/prometheus.yaml. 

Prometheus operator gives the following error:
`E0624 18:44:19.170004       1 operator.go:1022] Sync "monitoring/monitoring-prometheus-oper-prometheus" failed: failed to create new ConfigMap 'prometheus-monitoring-prometheus-oper-prometheus-rulefiles-0': configmaps "prometheus-monitoring-prometheus-oper-prometheus-rulefiles-0" already exists
`

This is my custom (didn't change many things) prometheus.yaml file.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-server
  labels:
    app: strimzi
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-server
  labels:
    app: strimzi

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-server
  labels:
    app: strimzi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-server
subjects:
  - kind: ServiceAccount
    name: prometheus-server
    namespace: kafka

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: strimzi
spec:
  replicas: 1
  serviceAccountName: prometheus-server
  serviceMonitorSelector:
    matchLabels:
      app: strimzi
  podMonitorSelector:
    matchLabels:
      app: strimzi
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false
  ruleSelector:
    matchLabels:
      role: alert-rules
      app: strimzi
  alerting:
    alertmanagers:
    - namespace: kafka
      name: alertmanager
      port: alertmanager
  additionalScrapeConfigs:
    name: additional-scrape-configs
    key: prometheus-additional.yaml
```

prometheus pod cannot be created:

```
prometheus-prometheus-0                          0/3     ContainerCreating   0          0s  
prometheus-prometheus-0                          0/3     Terminating         0          3s  
prometheus-prometheus-0                          0/3     Terminating         0          5s  
prometheus-prometheus-0                          0/3     Terminating         0          5s  
prometheus-prometheus-0                          0/3     Pending             0          0s  
prometheus-prometheus-0                          0/3     Pending             0          0s  
prometheus-prometheus-0                          0/3     ContainerCreating   0          0s  
prometheus-prometheus-0                          0/3     Terminating         0          4s  
prometheus-prometheus-0                          2/3     Terminating         0          5s  
prometheus-prometheus-0                          2/3     Terminating         1          6s  
prometheus-prometheus-0                          0/3     Terminating         1          9s  
prometheus-prometheus-0                          0/3     Terminating         1          17s 
prometheus-prometheus-0                          0/3     Terminating         1          17s 
prometheus-prometheus-0                          0/3     Pending             0          0s  
prometheus-prometheus-0                          0/3     Pending             0          0s  
prometheus-prometheus-0                          0/3     ContainerCreating   0          0s  
prometheus-prometheus-0                          0/3     Terminating         0          1s  
prometheus-prometheus-0                          0/3     Terminating         0          10s 
prometheus-prometheus-0                          0/3     Terminating         0          10s 
prometheus-prometheus-0                          0/3     Pending             0          0s  
prometheus-prometheus-0                          0/3     Pending             0          0s  
prometheus-prometheus-0                          0/3     ContainerCreating   0          0s  
prometheus-prometheus-0                          2/3     Error               0          5s  
prometheus-prometheus-0                          2/3     Running             1          6s  
prometheus-prometheus-0                          2/3     Terminating         1          7s  
prometheus-prometheus-0                          0/3     Terminating         1          10s 
prometheus-prometheus-0                          0/3     Terminating         1          20s 
prometheus-prometheus-0                          0/3     Terminating         1          20s 
prometheus-prometheus-0                          0/3     Pending             0          0s  
prometheus-prometheus-0                          0/3     Pending             0          0s  
prometheus-prometheus-0                          0/3     ContainerCreating   0          0s  
```
