### ISSUE TITLE
[Question] Mirror Maker 2 circular mirror replication

### ISSUE THREAD

**Issue by john-mcpeek** [strimzi/strimzi-kafka-operator#3249]
I have 2 OCP clusters (let's call them A and B). 
I installed AMQ Streams on both. 
Kafka on both. 
MM2 on B. 
Add topic `test-topic-1` on A.
Everything is working.
When I install MM2 on A, it starts mirroring the backup topics. (yaml below)
Then `remote-cluster.test-topic-1` shows up on B. (good)
Then `remote-cluster.remote-cluster.test-topic-1` shows up on A. (BAD)
Then this continues. `remote-cluster.remote-cluster.remote-cluster.remote-cluster`....

I tried using `topicsBlacklistPattern` to prevent this. That didn't make a different.

**Any thoughts?**

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: kafka-mm2-cluster
  namespace: common
spec:
  version: 2.5.0
  replicas: 1
  connectCluster: local-cluster
  clusters:
    - alias: remote-cluster
      bootstrapServers: 'kafka-cluster-kafka-bootstrap-common.apps.blahblah.oscplatform.site:443'
      tls:
        trustedCertificates:
          - certificate: ca.crt
            secretName: remote-kafka-ca-crt
    - alias: local-cluster
      bootstrapServers: 'kafka-cluster-kafka-bootstrap.common.svc:9093'
      tls:
        trustedCertificates:
          - certificate: ca.crt
            secretName: kafka-cluster-cluster-ca-cert
  mirrors:
    - sourceCluster: remote-cluster
      targetCluster: local-cluster
      sourceConnector:
        config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: 'false'
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
      topicsPattern: .*
      topicsBlacklistPattern: remote-cluster.*
      groupsPattern: .*
```

**Comment by scholzj** [comment]
If I understand you right, you use the same MirrorMaker resource in both OCP cluster, just with different `bootstrspServer` for the `remote-cluster`?

If that is so, I think the main issue is in the naming the clusters which does not match the MM2 ideas. You should ideally try to name them after you cluster - e.g. `cluster-a` and `cluster-b` And make sure the same alias is always pointing to the same cluster. So esentially, you should just switch the `sourceCluster` and `targetCluster` and `connectCluster`. 

E.g. on OCP cluster A:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: kafka-mm2-cluster
  namespace: common
spec:
  version: 2.5.0
  replicas: 1
  connectCluster: cluster-a
  clusters:
    - alias: cluster-b
      bootstrapServers: 'kafka-cluster-kafka-bootstrap-common.apps.blahblah.oscplatform.site:443'
      tls:
        trustedCertificates:
          - certificate: ca.crt
            secretName: remote-kafka-ca-crt
    - alias: cluster-a
      bootstrapServers: 'kafka-cluster-kafka-bootstrap.common.svc:9093'
      tls:
        trustedCertificates:
          - certificate: ca.crt
            secretName: kafka-cluster-cluster-ca-cert
  mirrors:
    - sourceCluster: cluster-b
      targetCluster: cluster-a
      sourceConnector:
        config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: 'false'
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
      topicsPattern: .*
      groupsPattern: .*
```

and on OCCP cluster B:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: kafka-mm2-cluster
  namespace: common
spec:
  version: 2.5.0
  replicas: 1
  connectCluster: cluster-b
  clusters:
    - alias: cluster-b
      bootstrapServers: 'kafka-cluster-kafka-bootstrap.common.svc:9093'
      tls:
        trustedCertificates:
          - certificate: ca.crt
            secretName: remote-kafka-ca-crt
    - alias: cluster-a
      bootstrapServers: 'kafka-cluster-kafka-bootstrap-common.apps.abcdabcd.oscplatform.site:443'
      tls:
        trustedCertificates:
          - certificate: ca.crt
            secretName: kafka-cluster-cluster-ca-cert
  mirrors:
    - sourceCluster: cluster-a
      targetCluster: cluster-b
      sourceConnector:
        config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: 'false'
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 1
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 1
      topicsPattern: .*
      groupsPattern: .*
```
