### ISSUE TITLE
javaSystemProperties not correctly set [Bug] ...

### ISSUE THREAD

**Issue by barrydobson** [strimzi/strimzi-kafka-operator#3301]
I'm having an issue setting jvmOptions.javaSystemProperties in both KafaCluster and KafkaConnect resources. When I add values I see the following in the operator logs:

`KafkaConnect resource my-connect in namespace kafka: Contains object at path spec.jvmOptions.javaSystemProperties with an unknown property: https.protocols`

The value of the environment variable STRIMZI_JAVA_SYSTEM_PROPERTIES gets set to `-Dnull=null -Dnull=null`
It doesn’t matter what I set the values to. 

I’m using v0.18.0

My definition looks like:
```yaml
jvmOptions:
    -Xms: 2G
    -Xmx: 2G
    -XX:
      UseContainerSupport: true
      UseCompressedOops: true
      MetaspaceSize: 96m
      UseG1GC: true
      MaxGCPauseMillis: 20
      InitiatingHeapOccupancyPercent: 35
      G1HeapRegionSize: 16M
      MinMetaspaceFreeRatio: 50
      MaxMetaspaceFreeRatio: 80
      ExplicitGCInvokesConcurrent: true
      ParallelGCThreads: 1
      ConcGCThreads: 1
    javaSystemProperties:
    - "java.awt.headless": true
    - "https.protocols": TLSv1.1,TLSv1.2
```

I'm not sure if I'm misconfiguring or this is an issue.
Thanks

**Comment by scholzj** [comment]
As mentioned on Slack ... I think this should look something like this:

```yaml
    javaSystemProperties:
    - name: java.awt.headless
      value: "true"
    - name: https.protocols
      value: TLSv1.1,TLSv1.2
```
