### ISSUE TITLE
[Question] SCRAM, SASL_PLAINTEXT with external listeners config does not work aymore, leads to Local: Broker transport failure

### ISSUE THREAD

**Issue by oana-s** [strimzi/strimzi-kafka-operator#3313]
I am using an AKS cluster and the following config:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 1
    listeners:
      external:
        type: loadbalancer
        authentication:
          type: scram-sha-512
        tls: false
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Write
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Create
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: my-group
          patternType: prefix
        operation: Read
```

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```

For the client.properties
```
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="my-user" password="OSo00092yx73";
```

Weird enough that the same config used to work ~1 month ago.

Now, the only that still works is 
`kubectl exec -it my-cluster-kafka-0 -- bin/kafka-console-producer.sh --broker-list 20.54.147.5:9094 --producer.config /tmp/client.properties --topic my-topic`

But my unit test and my kafkacat are not working anymore:
```
kafkacat -C -b 20.54.147.5:9094 -t my-topic -L -X security.protocol=SASL_PLAINTEXT -X sasl.mechanisms=SCRAM-SHA-512 -X sasl.username="my-user" -X sasl.password="OSo00092yx73" -v -X debug=generic,broker,security

%7|1594649473.645|SASL|rdkafka#producer-1| [thrd:app]: Selected provider SCRAM (builtin) for SASL mechanism SCRAM-SHA-512
%7|1594649473.646|WAKEUPFD|rdkafka#producer-1| [thrd:app]: sasl_plaintext://20.54.147.5:9094/bootstrap: Enabled low-latency partition queue wake-ups
%7|1594649473.647|WAKEUPFD|rdkafka#producer-1| [thrd:app]: sasl_plaintext://20.54.147.5:9094/bootstrap: Enabled low-latency ops queue wake-ups
%7|1594649473.646|BRKMAIN|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Enter main broker thread
%7|1594649473.649|STATE|rdkafka#producer-1| [thrd::0/internal]: :0/internal: Broker changed state INIT -> UP
%7|1594649473.653|BROADCAST|rdkafka#producer-1| [thrd::0/internal]: Broadcasting state change
%7|1594649473.648|BROKER|rdkafka#producer-1| [thrd:app]: sasl_plaintext://20.54.147.5:9094/bootstrap: Added new broker with NodeId -1
%7|1594649473.664|BRKMAIN|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: Enter main broker thread
%7|1594649473.666|CONNECT|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: broker in state INIT connecting
%7|1594649473.664|TOPIC|rdkafka#producer-1| [thrd:app]: New local topic: my-topic
%7|1594649473.684|CONNECT|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: Connecting to ipv4#20.54.147.5:9094 (sasl_plaintext) with socket 7
%7|1594649473.705|TOPPARNEW|rdkafka#producer-1| [thrd:app]: NEW my-topic [-1] 0x7fffd66aba40 (at rd_kafka_topic_new0:282)
%7|1594649473.725|STATE|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: Broker changed state INIT -> CONNECT
%7|1594649473.728|BROADCAST|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: Broadcasting state change
%7|1594649473.729|METADATA|rdkafka#producer-1| [thrd:app]: Skipping metadata refresh of 1 topic(s): no usable brokers
%7|1594649474.646|NOINFO|rdkafka#producer-1| [thrd:main]: Topic my-topic partition count is zero: should refresh metadata
%7|1594649474.647|METADATA|rdkafka#producer-1| [thrd:main]: Skipping metadata refresh of 1 topic(s): no usable brokers
%7|1594649475.648|NOINFO|rdkafka#producer-1| [thrd:main]: Topic my-topic partition count is zero: should refresh metadata
%7|1594649475.652|METADATA|rdkafka#producer-1| [thrd:main]: Skipping metadata refresh of 1 topic(s): no usable brokers
%7|1594649475.733|BROKERFAIL|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: failed: err: Local: Broker transport failure: (errno: Connection refused)
%7|1594649475.736|STATE|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: Broker changed state CONNECT -> DOWN
%7|1594649475.741|BROADCAST|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: Broadcasting state change
%7|1594649475.743|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: Purging bufq with 0 buffers
%7|1594649475.744|BUFQ|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: Updating 0 buffers on connection reset
%7|1594649476.664|NOINFO|rdkafka#producer-1| [thrd:main]: Topic my-topic partition count is zero: should refresh metadata
%7|1594649476.665|METADATA|rdkafka#producer-1| [thrd:main]: Skipping metadata refresh of 1 topic(s): no usable brokers
%7|1594649476.750|CONNECT|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: broker in state DOWN connecting
%7|1594649476.751|CONNECT|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: Connecting to ipv4#20.54.147.5:9094 (sasl_plaintext) with socket 7
%7|1594649476.752|STATE|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: sasl_plaintext://20.54.147.5:9094/bootstrap: Broker changed state DOWN -> CONNECT
%7|1594649476.753|BROADCAST|rdkafka#producer-1| [thrd:sasl_plaintext://20.54.147.5:9094/bootstrap]: Broadcasting state change
%7|1594649477.667|NOINFO|rdkafka#producer-1| [thrd:main]: Topic my-topic partition count is zero: should refresh metadata
%7|1594649477.668|METADATA|rdkafka#producer-1| [thrd:main]: Skipping metadata refresh of 1 topic(s): no usable brokers
%7|1594649478.674|NOINFO|rdkafka#producer-1| [thrd:main]: Topic my-topic partition count is zero: should refresh metadata
%7|1594649478.676|METADATA|rdkafka#producer-1| [thrd:main]: Skipping metadata refresh of 1 topic(s): no usable brokers
```

Could you please help me out here?

Thank you!
