### ISSUE TITLE
[Bug] Kafka Exporter do not accept SASL configuration

### ISSUE THREAD

**Issue by MacPower** [strimzi/strimzi-kafka-operator#3323]
**Describe the bug**

When authentication is enable for kafka broker, kafka exporter is not able to connect. The provided `/opt/kafka-exporter/kafka_exporter_run.sh` script does not take argument for SASL auth. 

**Error Message**

`
level=error msg="Cannot get describe groups: kafka: broker not connected" source="kafka_exporter.go:373"
`

**To Reproduce**

Configuration : 

```yaml
 listeners:
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: scram-sha-512
```

```yaml
kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
```

**Expected behavior**

I which to have the ability to pass as environment variable SASL configuration, like for broker configuration to this init script and/or mounted secret.

Thanks.

**Comment by scholzj** [comment]
I'm not sure I follow the issue. When you deploy Kafka Exporter using Strimzi, it is always using TLS client authentication and it does not use any of the listeners in the `.spec.kafka.listeners` section of the Kafka custom resource. So you cannot really configure it to use SASL.

**Comment by MacPower** [comment]
> 
> 
> I'm not sure I follow the issue. When you deploy Kafka Exporter using Strimzi, it is always using TLS client authentication and it does not use any of the listeners in the `.spec.kafka.listeners` section of the Kafka custom resource. So you cannot really configure it to use SASL.

Ok so Kafka exporter use TLS client authentication. 
I assumed that Kafka exporter used the listeners because it uses the bootstrap service, but actually on port 9091. 

One (big) thing that I omitted I that I use `authorization:
      type: simple` in my configuration (misspelled authorization/authentication when I opened this issue). 

I assume that the Kafka exporter client is not authorized to do any actions onto the cluster because it does not have any permission defined in a ACL right ? So I thought that I needed to use a user/password generated through UserOperator with the according permission. 

So, how could I configure Kafka exporter with authorization enable ? 

Thanks

**Comment by scholzj** [comment]
You do not have to configure any authorization. Unless you are using custom build of Strimzi with some new authorizer plugin, it is all handled by Strimzi.

**Comment by MacPower** [comment]
> 
> 
> You do not have to configure any authorization. Unless you are using custom build of Strimzi with some new authorizer plugin, it is all handled by Strimzi.

Ok that is perfect !

In that case I am missing something. I can see that the exporter describe some of the content in the kafka brokers since it is aware of some topics : 

```json 
time="2020-07-17T08:22:00Z" level=error msg="Cannot get describe groups: kafka: broker not connected" source="kafka_exporter.go:373"
time="2020-07-17T08:22:20Z" level=error msg="Cannot get consumer group: kafka: broker not connected" source="kafka_exporter.go:361"
time="2020-07-17T08:22:30Z" level=error msg="Cannot get oldest offset of topic prisme-sesame partition 0: kafka: broker not connected" source="kafka_exporter.go:296"
time="2020-07-17T08:22:30Z" level=error msg="Cannot get oldest offset of topic prisme--infra_mediation partition 0: kafka: broker not connected" source="kafka_exporter.go:296"
time="2020-07-17T08:22:50Z" level=error msg="Cannot get describe groups: kafka: broker not connected" source="kafka_exporter.go:373"
```

my complete Kafka configuration : 

```yml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: REDACTED
spec:
  kafka:
    image: registry.glouton.int.nbyt.fr/strimzi/kafka:0.18.0-kafka-2.5.0
    version: 2.5.0
    replicas: 3
    rack:
      topologyKey: alpha.eksctl.io/instance-id
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      limits:
        memory: 6Gi
        cpu: "1.5"
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    authorization:
      type: simple
    listeners:
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: scram-sha-512
      external:
        type: loadbalancer
        tls: false
        authentication:
          type: scram-sha-512
        overrides:
          bootstrap:
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: bootstrap.REDACTED
              external-dns.alpha.kubernetes.io/ttl: "60"
            address: bootstrap.REDACTED
          brokers:
          - broker: 0
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: broker-0.REDACTED
              external-dns.alpha.kubernetes.io/ttl: "60"
            advertisedHost: broker-0.REDACTED
          - broker: 1
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: broker-1.REDACTED
              external-dns.alpha.kubernetes.io/ttl: "60"
            advertisedHost: broker-1.REDACTED
          - broker: 2
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: broker-2.REDACTED
              external-dns.alpha.kubernetes.io/ttl: "60"
            advertisedHost: broker-2.REDACTED
    config:
      auto.create.topics.enable: "true"
      num.partitions: 3
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
      log.cleanup.policy: delete
      log.retention.ms: 14400000
    template:
      externalBootstrapService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: REDACTED
            service.beta.kubernetes.io/aws-load-balancer-security-groups: REDACTED
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-additional-resource-tag: REDACTED
      perPodService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-internal: "true"
            service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "9094"
            service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
            service.beta.kubernetes.io/aws-load-balancer-ssl-cert: REDACTED
            service.beta.kubernetes.io/aws-load-balancer-security-groups: REDACTED
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-additional-resource-tag: REDACTED
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "role"
                      operator: In
                      values:
                        - "kafka"

    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: true
      class: gp2-encrypted-expandable-eu-west-3b
    metrics:
      # Inspired by config from Kafka 2.0.0 example rules:
      # https://github.com/prometheus/jmx_exporter/blob/master/example_configs/kafka-2_0_0.yml
      lowercaseOutputName: true
      rules:
      # Special cases and very specific rules
      - pattern : kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          topic: "$4"
          partition: "$5"
      - pattern : kafka.server<type=(.+), name=(.+), clientId=(.+), brokerHost=(.+), brokerPort=(.+)><>Value
        name: kafka_server_$1_$2
        type: GAUGE
        labels:
          clientId: "$3"
          broker: "$4:$5"
      # Some percent metrics use MeanRate attribute
      # Ex) kafka.server<type=(KafkaRequestHandlerPool), name=(RequestHandlerAvgIdlePercent)><>MeanRate
      - pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>MeanRate
        name: kafka_$1_$2_$3_percent
        type: GAUGE
      # Generic gauges for percents
      - pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*><>Value
        name: kafka_$1_$2_$3_percent
        type: GAUGE
      - pattern: kafka.(\w+)<type=(.+), name=(.+)Percent\w*, (.+)=(.+)><>Value
        name: kafka_$1_$2_$3_percent
        type: GAUGE
        labels:
          "$4": "$5"
      # Generic per-second counters with 0-2 key/value pairs
      - pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+), (.+)=(.+)><>Count
        name: kafka_$1_$2_$3_total
        type: COUNTER
        labels:
          "$4": "$5"
          "$6": "$7"
      - pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*, (.+)=(.+)><>Count
        name: kafka_$1_$2_$3_total
        type: COUNTER
        labels:
          "$4": "$5"
      - pattern: kafka.(\w+)<type=(.+), name=(.+)PerSec\w*><>Count
        name: kafka_$1_$2_$3_total
        type: COUNTER
      # Generic gauges with 0-2 key/value pairs
      - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Value
        name: kafka_$1_$2_$3
        type: GAUGE
        labels:
          "$4": "$5"
          "$6": "$7"
      - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Value
        name: kafka_$1_$2_$3
        type: GAUGE
        labels:
          "$4": "$5"
      - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Value
        name: kafka_$1_$2_$3
        type: GAUGE
      # Emulate Prometheus 'Summary' metrics for the exported 'Histogram's.
      # Note that these are missing the '_sum' metric!
      - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+), (.+)=(.+)><>Count
        name: kafka_$1_$2_$3_count
        type: COUNTER
        labels:
          "$4": "$5"
          "$6": "$7"
      - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*), (.+)=(.+)><>(\d+)thPercentile
        name: kafka_$1_$2_$3
        type: GAUGE
        labels:
          "$4": "$5"
          "$6": "$7"
          quantile: "0.$8"
      - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.+)><>Count
        name: kafka_$1_$2_$3_count
        type: COUNTER
        labels:
          "$4": "$5"
      - pattern: kafka.(\w+)<type=(.+), name=(.+), (.+)=(.*)><>(\d+)thPercentile
        name: kafka_$1_$2_$3
        type: GAUGE
        labels:
          "$4": "$5"
          quantile: "0.$6"
      - pattern: kafka.(\w+)<type=(.+), name=(.+)><>Count
        name: kafka_$1_$2_$3_count
        type: COUNTER
      - pattern: kafka.(\w+)<type=(.+), name=(.+)><>(\d+)thPercentile
        name: kafka_$1_$2_$3
        type: GAUGE
        labels:
          quantile: "0.$4"
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      limits:
        memory: 6Gi
        cpu: "1.5"
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: true
      class: gp2-encrypted-expandable
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "role"
                      operator: In
                      values:
                        - "zookeeper"
    metrics:
      # Inspired by Zookeeper rules
      # https://github.com/prometheus/jmx_exporter/blob/master/example_configs/zookeeper.yaml
      lowercaseOutputName: true
      rules:
      # replicated Zookeeper
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+)><>(\\w+)"
        name: "zookeeper_$2"
        type: GAUGE
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+)><>(\\w+)"
        name: "zookeeper_$3"
        type: GAUGE
        labels:
          replicaId: "$2"
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(Packets.*)"
        name: "zookeeper_$4"
        type: COUNTER
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+)><>(\\w+)"
        name: "zookeeper_$4"
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: "org.apache.ZooKeeperService<name0=ReplicatedServer_id(\\d+), name1=replica.(\\d+), name2=(\\w+), name3=(\\w+)><>(\\w+)"
        name: "zookeeper_$4_$5"
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"
      # standalone Zookeeper
      - pattern: "org.apache.ZooKeeperService<name0=StandaloneServer_port(\\d+)><>(\\w+)"
        type: GAUGE
        name: "zookeeper_$2"
      - pattern: "org.apache.ZooKeeperService<name0=StandaloneServer_port(\\d+), name1=InMemoryDataTree><>(\\w+)"
        type: GAUGE
        name: "zookeeper_$2"
  entityOperator:
    topicOperator:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "role"
                    operator: In
                    values:
                      - "system"
    userOperator:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "role"
                    operator: In
                    values:
                      - "system"
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: "role"
                      operator: In
                      values:
                        - "kafka"
```

For information, my cluster is running on AWS EKS.

Do you have any ideas why the exporter is not working properly ? 

Thanks.
