### ISSUE TITLE
[Question] ACL not working for Node Port with tlsh auth

### ISSUE THREAD

**Issue by gricuk** [strimzi/strimzi-kafka-operator#3337]
Hi, I don't understand how ACL working.
Here my configuration:
**kafka-cluster:**
```apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: test-kafka
spec:
  kafka:
    version: 2.5.0
    jvmOptions:
      -Xms: 3G
      -Xmx: 3G
    replicas: 3
    listeners:
      plain: {}
      tls:
        authentication:
          type: tls
      external:
        type: nodeport
        tls: true
        authentication:
          type: tls
        overrides:
          bootstrap:
            nodePort: 32100
          brokers:
            - broker: 0
              nodePort: 32000
              advertisedHost: my-host1.example.com
            - broker: 1
              nodePort: 32001
              advertisedHost: my-host2.example.com
            - broker: 2
              nodePort: 32002
              advertisedHost: my-host3.example.com
      authorization:
        type: simple
    config:
      num.partitions: 8
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
      inter.broker.protocol.version: "2.5"
      group.initial.rebalance.delay.ms: 3000
      default.replication.factor: 3
      log.cleanup.policy: "compact"
      log.segment.bytes: 104857600
      offset.retention.minutes: 10080
      auto.create.topics.enable: "false"
      ssl.cipher.suites: "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384"
      ssl.enabled.protocols: "TLSv1.2"
      ssl.protocol: "TLSv1.2"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 20Gi
          deleteClaim: false
  kafkaExporter: {}
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
**kafkatopic:**
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: test-kafka
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```

**kafkauser:**
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: test-kafka
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Read
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Describe
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read
```

I've exported CA and user certificates from secrets:
```
kubectl get secret my-cluster-cluster-ca-cert -o jsonpath=’{.data.ca\.crt}’ | base64 -d > ca.crt
kubectl get secret my-user -o jsonpath=’{.data.user\.password}’ | base64 -d > user.password
kubectl get secret my-user -o jsonpath=’{.data.user\.p12}’ | base64 -d > user.p12
```

And convert them to  jks:
```
keytool -keystore user-truststore.jks -alias CARoot -import -file ca.crt
keytool -importkeystore -srckeystore user.p12 -srcstoretype pkcs12 -destkeystore user-keystore.jks -deststoretype jks
```

It's working fine, but when I've created the second topic I see its topic in my Kafkatool and I can delete this topic, although User my-user hasn't permission to second topic.
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: test-kafka
  labels:
    strimzi.io/cluster: test-kafka
spec:
  partitions: 1
  replicas: 3
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```

Could you please explain how it work?

Additional info:
k8s version:  v1.17.5
operator version: 0.18.0
