### ISSUE TITLE
[Bug] Error "Required value" for field "spec.kafka.listeners" with default Kafka CR

### ISSUE THREAD

**Issue by bandrade** [strimzi/strimzi-kafka-operator#3344]
**Describe the bug**
When it's used UI to create a Kafka instance, the default CR suggestion does not work. It returns an error: "Required value" for field "spec.kafka.listeners". Here is the current CR:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  labels: {}
  namespace: amq-streams
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.5'
    version: 2.5.0
    storage:
      type: ephemeral
    replicas: 3
  zookeeper:
    storage:
      type: ephemeral
    replicas: 3
```

The workaround is to add the required value as shown below:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  labels: {}
  namespace: amq-streams
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.5'
    listeners:
      plain: {}
    version: 2.5.0
    storage:
      type: ephemeral
    replicas: 3
  zookeeper:
    storage:
      type: ephemeral
    replicas: 3

    listeners:
      plain: {}
```

**To Reproduce**
1. Install AMQ Streams Operator
2. Create Kafka instance with default values

**Expected behavior**
When it's used UI to create a Kafka instance, the default CR suggestion does not work. It returns an error: "Required value" for field "spec.kafka.listeners". Here is the current CR:

**Environment (please complete the following information):**
OCP 4.6.0-0.nightly-2020-07-04-234602
AMQ Streams 1.5.0
