### ISSUE TITLE
[Bug] Unable to define resource requests on kafka objects

### ISSUE THREAD

**Issue by bcouetil** [strimzi/strimzi-kafka-operator#3355]
**Describe the bug**

On Kafka objects, I am able de define the zookeeper resources requests, but not the kafka's. This is not taken into account.

Did I miss something ?

**To Reproduce**

Only the second set of requests are effectively used :

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 2.4.0
    replicas: 1
    listeners:
      plain: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.4"
    resources:
      requests:
        cpu: "50m"
        memory: "512Mi"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    resources:
      requests:
        cpu: "10m"
        memory: "256Mi"
    storage:
      type: ephemeral
```
