### ISSUE TITLE
[Enhancement] Ability to change external listener port

### ISSUE THREAD

**Issue by MacPower** [strimzi/strimzi-kafka-operator#3377]
Hi, 

I would like to know if it is possible to change the exposed port of the kafka brokers when using the external listener. 

Indeed, my company infrastructure is restricted on certain port range and I would like to expose my Kafka broker via AWS NLB with a different port than 9094.

I tried to use this option used for nodeport type : 
```yaml
external:
  type: loadbalancer
  tls: true
  authentication:
    type: scram-sha-512
  overrides:
    bootstrap:
      dnsAnnotations:
        external-dns.alpha.kubernetes.io/hostname: REDACTED
        external-dns.alpha.kubernetes.io/ttl: "60"
      address: REDACTED
      nodePort: 8094
    brokers:
    - broker: 0
      dnsAnnotations:
        external-dns.alpha.kubernetes.io/hostname: REDACTED
        external-dns.alpha.kubernetes.io/ttl: "60"
      advertisedHost: REDACTED
      nodePort: 8094
    - broker: 1
      dnsAnnotations:
        external-dns.alpha.kubernetes.io/hostname: REDACTED
        external-dns.alpha.kubernetes.io/ttl: "60"
      advertisedHost: REDACTED
      nodePort: 8094
    - broker: 2
      dnsAnnotations:
        external-dns.alpha.kubernetes.io/hostname: REDACTED
        external-dns.alpha.kubernetes.io/ttl: "60"
      advertisedHost: REDACTED
      nodePort: 8094
```

But the operator does not recognize the input : `Contains object at path spec.kafka.listeners.external.overrides.bootstrap with an unknown property: nodePort`.

I do not want to changes the current port used inside the cluster, I know that It is possible with to do that with AWS ELB but this require (for the eks implementation) to change the port of the k8s service which I did not find a way to configure it .

Thanks
