### ISSUE TITLE
What is the recommended strategy for reducing (replacing with smaller) persistent volume claims for brokers[Question] ...

### ISSUE THREAD

**Issue by bradkyle** [strimzi/strimzi-kafka-operator#3387]
Hi, I'm trying to decrease the size of a given persistent volume claim (of a given storage class) for a set of kafka brokers defined by strimzi i.e. from 150Gi to 75Gi, obviously kubernetes only allows for one to increase the disk size and as such one would have to change the current persistent volume claim to a different one (of the same storage class). Would you be able to give me some guidance on how one might best go about doing this? Thanks. Best Regards.

**Comment by scholzj** [comment]
I don't think we have anything. As you said, Kubernetes does not support it, so you will need to do it manually. But how to do it might depend on your infrastructure. 

If you platform supports increasing storage size, I guess that you would probably need to start by changing the storage capacity in the Kafka CR and in `strimzi.io/storage` annotations on the StatefulSet. Otherwise the operator might expend the storage right after you make it smaller.

**Comment by maowerner** [comment]
Trying this in 2023 with the StrimziPodSet instead of StatefulSet and this was exactly our problem. The following worked:

1. Stop the strimzi operator
2. Remove the annotation
    ``` 
    kubectl get -o yaml sps strimzi-zookeeper | grep -C 10 storage
    apiVersion: core.strimzi.io/v1beta2
    kind: StrimziPodSet
    metadata:
      annotations:
        strimzi.io/storage: '{"type":"persistent-claim","size":"10Gi"}'
    ...
    ```
3. Delete the pod
4. Save the pvc template with `kubectl get pvc -o yaml data-strimzi-zookeeper-0 > pvc.yaml`
5. Edit the `pvc.yaml` - reduce capacity, change storageClass etc.
6. Delete the pvc
7. Recreate the (edited) pvc with `kubectl apply -f pvc.yaml`
8. Deploy the same change in the strimzi resources and restart the strimzi operator
9. Repeat for all replica

Maybe it is possible to keep the operator running during some of the steps but we did not want a reconciliation to trigger in the wrong moment.  Deleting the pod is necessary because a pvc cannot be edited while still controlled by a pod and stoping the strimzi operator was necessary to stop reconciliations of course but also to prevent the StrimziPodSet from restarting the pod before editing the pvc was done.
