### ISSUE TITLE
SASL scram-sha-512 connection to Strimzi 0.18.0 in CodeReadyContainers 1.13.0

### ISSUE THREAD

**Issue by aceeric** [strimzi/strimzi-kafka-operator#3388]
Hello - I'm trying to connect an application to Strimzi 0.18.0 in CodeReadyContainers
```
$ ./crc version
CodeReady Containers version: 1.13.0+8070bae
OpenShift version: 4.5.1 (embedded in binary)
```
I've had success with the app and Strimzi in OpenShift 3.11 and I'm trying to duplicate that in CRC. No matter what I try, the Kafka logs look like this when the client initiates a connection:
```
2020-07-27 00:58:24,900 INFO [SocketServer brokerId=0] Failed authentication with /10.116.0.68 (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(PLAIN-9092)-SASL_PLAINTEXT-3]
2020-07-27 00:58:25,332 INFO [SocketServer brokerId=0] Failed authentication with /10.116.0.68 (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(PLAIN-9092)-SASL_PLAINTEXT-4]
2020-07-27 00:58:25,736 INFO [SocketServer brokerId=0] Failed authentication with /10.116.0.68 (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(PLAIN-9092)-SASL_PLAINTEXT-5]
2020-07-27 00:58:26,141 INFO [SocketServer brokerId=0] Failed authentication with /10.116.0.68 (Unexpected Kafka request of type METADATA during SASL handshake.) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(PLAIN-9092)-SASL_PLAINTEXT-3]
...
```
I've been able to successfully configure anonymous plain text access in CRC from the app. So I believe that it is not a service-related issue. Even when I change the password to be invalid the exact same error occurs which is odd. I tried to configure DEBUG logging per: https://strimzi.io/docs/operators/latest/full/using.html#con-kafka-logging-deployment-configuration-kafka but I'm not seeing any additional info in the logs during the connection time period that is pointing me to the issue.

This is my Kafka CR:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: zzzzz
  namespace: backing
spec:
  logging:
    type: inline
    loggers:
      kafka.root.logger.level: "DEBUG"
  kafka:
    replicas: 1
    listeners:
      plain:
        authentication:
          type: scram-sha-512
    authorization:
      type: simple
    storage:
      type: ephemeral
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
And my KafkaUser CR:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: zzzzz
  name: zzzzzuser
  namespace: backing
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
    - resource:
        type: cluster
        name: "*"
        patternType: literal
      host: "*"
      operation: All
    - resource:
        type: topic
        name: "*"
        patternType: literal
      host: "*"
      operation: All
    - resource:
        type: group
        name: "*"
        patternType: literal
      host: "*"
      operation: All
```
The app has been configured this way:
```
bootstrap.servers=zzzzz-kafka-bootstrap.backing.svc.cluster.local:9092
#also tried bootstrap.servers=zzzzz-kafka-bootstrap:9092
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="zzzzzuser" password="S2WeOwff2JvP";
```
Any insight into the issue, and whether it's possible to get more detail on the SASL negotiation would be appreciated. Thank you.

**Comment by scholzj** [comment]
I don't know what the problem could be and I do not have CodeReady Containers to try it my self. I used SASL over the weekend with 0.19.0-rc1 and did not have any problems.

How did you get the password? Did you decode the base64? That is the only thing which comes to my mind. I also always pass the JAAS config without the `"`, but not sure that is a problem.

**Comment by aceeric** [comment]
Initially I was mounting the password as an environment variable from the KafkaUser secret but that failed so: `oc extract secret/zzzzzuser --keys=password --to=-` then copy/paste that into the client config file. I'm reasonably confident the issue is on the client side but it's a packaged open source app and I was hoping for some insight from the Kafka logs regarding what Kafka is receiving from the client in terms of credentials before I build and debug the their app. Does it look like I have the logging configured correctly in the Kafka CR? Maybe Kafka just doesn't provide more information about the connection negotiation? Thanks.

**Comment by scholzj** [comment]
The logging is not correct - it has to be under `.spec.kafka`. But I do not think it would help much - it would not expect any details on this issue. Also - since your cluster seems to be having ephemeral storage, it will trigger the restart of the broker and loose the data (just saying - I guess it is some test env where it doesn't matter).

The way to get the password looks good. So there should not be a problem. And the config looks mostly good as well - the `"` are the only thing I have differently in my configs for SCRAM-SHA-512.

**Comment by aceeric** [comment]
Ok thanks. The instance truly is ephemeral just for testing connections under various Kafka profiles (anonymous, sasl, tls). By the way - looking at the documentation on: https://strimzi.io/docs/operators/latest/full/using.html#con-kafka-logging-deployment-configuration-kafka

The YAML for the inline logging section (this is a copy) looks like:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
spec:
  # ...
  logging:
    type: inline
    loggers:
      kafka.root.logger.level: "INFO"
  # ...
  zookeeper:
    # ...
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
```
The kafka root logging stanza looks indented only two, rather than under the kafka resource. Whereas the ZK logging is under the ZK resource. Maybe that's incorrect and should look like this?:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
spec:
  # ...
  kafka
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
  # ...
  zookeeper:
    # ...
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
```
