### ISSUE TITLE
PVC annotation will be overwritten / removed

### ISSUE THREAD

**Issue by dweber019** [strimzi/strimzi-kafka-operator#3398]
**Describe the bug**
The cluster operator removes annotations on the persistentvolumeclaim (PVC). The following annotation will be set automatically by the storage class provisioner`volume.beta.kubernetes.io/storage-provisioner: netapp.io/trident` and will be removed by the cluster operator on each reconcil.

In addition accoring to the CRD there isn't any option to provide custom defined annotation.

**The cluster CR**
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version:  2.4.0
    template:
      pod:
        affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: kafkaAffinity
                        operator: In
                        values:
                          - brokerAffinity
                  topologyKey: kubernetes.io/hostname
      statefulset:
        metadata:
          labels:
            kafkaAffinity: brokerAffinity
    replicas: 3
    listeners:
      external:
        type: route
        authentication:
          type: tls
        overrides:
          bootstrap:
            host: kafka-kafka-bootstrap.kafka-test.app-test.example.com
          brokers:
            - broker: 0
              host: kafka-0-kafka-test.app-test.example.com
            - broker: 1
              host: kafka-1-kafka-test.app-test.example.com
            - broker: 2
              host: kafka-2-kafka-test.app-test.example.com
      tls:
        authentication:
          type: tls
    authorization:
      type: simple
    resources:
      requests:
        cpu: 25m
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi
    tlsSidecar:
      resources:
        requests:
          cpu: 75m
          memory: 64Mi
        limits:
          cpu: 75m
          memory: 64Mi
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      min.insync.replicas: 2
      default.replication.factor: 3
      log.message.format.version: "2.4"
      auto.create.topics.enable: true
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 5Gi
          deleteClaim: false
          class: trident-prod-backup
    jvmOptions:
      gcLoggingEnabled: false
      -Xms: 500m
      -Xmx: 500m
  zookeeper:
    template:
      pod:
        affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: kafkaAffinity
                          operator: In
                          values:
                            - zookeeperAffinity
                    topologyKey: kubernetes.io/hostname
      statefulset:
        metadata:
          labels:
            kafkaAffinity: zookeeperAffinity
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
      class: trident-prod-backup
    resources:
      requests:
        cpu: 25m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    tlsSidecar:
      resources:
        requests:
          cpu: 75m
          memory: 64Mi
        limits:
          cpu: 75m
          memory: 64Mi
    jvmOptions:
      gcLoggingEnabled: false
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 750m
          memory: 512Mi
    userOperator:
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 750m
          memory: 512Mi
    tlsSidecar:
      resources:
        requests:
          cpu: 75m
          memory: 64Mi
        limits:
          cpu: 75m
          memory: 64Mi
```

**Expected behavior**
Annotations aren't removed or can be provided over the CR.

**Environment (please complete the following information):**
- Strimzi version: AMQ steams 1.4.1 = Strimzi 0.17.x
- Installation method: YAML files
- Kubernetes cluster: OpenShift 3.9

**Additional context**
This annotation is required in order to resize the storage.
