### ISSUE TITLE
[Kafka: Something strange behaviour we have noticed for the user secret] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3409]
Hi Team,

We have created a Kafka user(with name as my-producer) which in-turn created a secret in K8 with the same name. As part of this, the key user.password is defined with an encoded value along with the metadata timestamp.

One strange thing we noticed is the user. password inside the secret has been changed and the metadata timestamp is also updated today, however, we didn't perform any operations for the user once after it was created.

Q1) We never saw this behavior anytime, But what are all possible reasons for this behavior?, Impact is as the password is changed the original Keystore we have generated is no more working which is failing while producing/consuming.

Q2) Is there a way to audit the user to know if any change has happened which caused this?
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: my-producer
  labels:
    strimzi.io/cluster: my-cluster
spec:
  # ...
  authorization:
    type: simple
    acls:
      # access to offset.storage.topic
      - resource:
```

Need help.
