### ISSUE TITLE
Kafka Cluster TLS secrets across namespaces

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3410]
We have Kafka cluster in the namespace `kafka`
We have created Debezium Connect and Connectors in the namespace `stream-producer`

Providing the namespace does not make connect refer to the secret in kafka namespace. Kafka connect pod is not booting  due to this.

```
  Warning  FailedMount  119s                 kubelet, ip-172-31-102-84.ap-south-1.compute.internal  Unable to attach or mount volumes: unmounted volumes=[k8s-cluster-ca-cert], unattached volumes=[kafka-metrics-and-logging k8s-cluster-ca-cert ext-conf-stream-voice-829ad mysql-connect-cluster-1afe09f-20200729-131452-connect-toketq9zl]: timed out waiting for the condition
```

`k get kc -n stream-producer -o yaml`
```
replicas: 1
spec:
    tls:
      trustedCertificates:
      - certificate: ca.crt
        secretName: k8s-cluster-ca-cert
        namespace: kafka
```
