### ISSUE TITLE
[Bug] JvmOptions not ordered correctly

### ISSUE THREAD

**Issue by canberkkoc** [strimzi/strimzi-kafka-operator#3418]
**Describe the bug**

Hello, i am using cluster operator and give jvmoptions like this:

```yaml
    jvmOptions:
      "-Xmx": "6g"
      "-Xms": "6g"
      "-XX":
        "UnlockExperimentalVMOptions": true
        "MaxGCPauseMillis": 200
        "UseG1GC": true
        "InitiatingHeapOccupancyPercent": 35
        "UseParNewGC": false
        "ConcGCThreads": 6
        "G1MaxNewSizePercent": 75
        "G1MixedGCLiveThresholdPercent": 90
        "G1OldCSetRegionThresholdPercent": 60
        "PrintGCDetails": true
        "PrintGCApplicationStoppedTime": true
        "PrintGCDateStamps": true
        "PrintGCTimeStamps": true
```

When i get kafka CR from kubectl i saw options ordered alphabetical and not the way i want them to be. 

```yaml
    jvmOptions:
      -XX:
        ConcGCThreads: 6
        G1MaxNewSizePercent: 75
        G1MixedGCLiveThresholdPercent: 90
        G1OldCSetRegionThresholdPercent: 60
        InitiatingHeapOccupancyPercent: 35
        MaxGCPauseMillis: 200
        PrintGCApplicationStoppedTime: true
        PrintGCDateStamps: true
        PrintGCDetails: true
        PrintGCTimeStamps: true
        UnlockExperimentalVMOptions: true
        UseG1GC: true
        UseParNewGC: false
      -Xms: 6g
      -Xmx: 6g
```

So this leads getting this error from Kafka broker pods.(IMHO)
```
Error: VM option 'G1MixedGCLiveThresholdPercent' is experimental and must be enabled via -XX:+UnlockExperimentalVMOptions.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**To Reproduce**

Create a cluster with given jvmoptions.

**Expected behavior**

Get Kafkas up and running

**Environment (please complete the following information):**
 - Strimzi version: 0.17.0
 - Installation method: Cluster Operator
 - Kubernetes cluster: Kubernetes 1.15.3
 - Infrastructure:  Baremetal

**Comment by scholzj** [comment]
Why do they need to be ordered? I'm not sure we can really order them as this is passed though several different components before it reaches Strimzi.

**Comment by rzasgal** [comment]
I think "UnlockExperimentalVMOptions" variable should come before any experimental options in argument jvm argument list https://www.oracle.com/technical-resources/articles/java/g1gc.html#Unlock

**Comment by tombentley** [comment]
I don't think we can maintain the order while sticking to using an object. We'd need to use a list in the YAML/JSON. 

I guess if it's _only_ for `UnlockExperimentalVMOptions` we could do something in the script to move it to the head of the list. That's definitely a hack but it would save having to deal with the compatibility concerns about making `jvmOptions` a list.

**Comment by canberkkoc** [comment]
Well i see i'll try Kafka container template. 

> I guess if it's only for UnlockExperimentalVMOptions we could do something in the script to move it to the head of the list. That's definitely a hack but it would save having to deal with the compatibility concerns about making jvmOptions a list.

This could be work too. I'll let you know the result of template workaround, thanks for quick reply.

**Comment by canberkkoc** [comment]
Hello again,

Workaround works like this, i'm leaving the yaml part to be an example:
```
    template:
      kafkaContainer:
        env:
        - name: KAFKA_JVM_PERFORMANCE_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1OldCSetRegionThresholdPercent=60 -XX:G1MaxNewSizePercent=75 -XX:ConcGCThreads=6 -XX:InitiatingHeapOccupancyPercent=35 -XX:MaxGCPauseMillis=200 -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseG1GC -XX:-UseParNewGC"
        - name: KAFKA_HEAP_OPTS
          value: "-Xms8g -Xmx8g"

```

Thank you for your interest.
