### ISSUE TITLE
[Question] Prometheus Rule about TLS sidecar in zookeeper

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#3424]
Hi, 

I noticed you removed the TLS sidecar for zookeeper with the strimzi 0.18 release. That would mean the example rule in the prometheus metric example section is now invalid. Correct? 
```
    - alert: ZookeeperTlsSidecarContainersDown
      expr: absent(container_last_seen{container_name="tls-sidecar",kubernetes_pod_name=~".+-zookeeper-[0-9]+"})
      for: 3m
      labels:
        severity: major
      annotations:
        summary: 'All `tls-sidecar` containers in the Zookeeper pods down or in CrashLookBackOff status'
        description: 'All `tls-sidecar` containers in the Zookeeper pods have been down or in CrashLookBackOff status for 3 minutes'
```
