### ISSUE TITLE
The scale subresources in CRD points to .status.selector but the actual name is .status.podSelector

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#3432]
The Scale subresource in our CRD points to `.status.selector` for `labelSelectorPath`:

```yaml
  subresources:
    status: {}
    scale:
      specReplicasPath: .spec.replicas
      statusReplicasPath: .status.replicas
      labelSelectorPath: .status.selector
```

But the actual selector seems to be always on `.status.podSelector` path:

```yaml
  status:
    conditions:
    - lastTransitionTime: "2020-08-02T10:00:33.839679Z"
      status: "True"
      type: Ready
    observedGeneration: 1
    podSelector:
      matchLabels:
        strimzi.io/cluster: my-connect-cluster
        strimzi.io/kind: KafkaConnect
        strimzi.io/name: my-connect-cluster-connect
    replicas: 1
    url: http://my-connect-cluster-connect-api.myproject.svc:8083
```

Thsi should be fixed.
