### ISSUE TITLE
Strimzi kafka CR not coming up

### ISSUE THREAD

**Issue by Avni-Sharma** [strimzi/strimzi-kafka-operator#3449]
I have installed the strimzi-kafka-operator from operatorHub and I apply the following resource
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: my-cluster
  labels:
    app: my-cluster
spec:
  kafka:
    replicas: 3
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: "1"
    jvmOptions:
      -Xms: 1024m
      -Xmx: 1024m
    listeners:
      plain: {}
      tls:
        authentication:
          type: tls
    authorization:
      type: simple
      superUsers:
        - CN=my-connect
        - my-connect
        - ANONYMOUS
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: "0.3"
      limits:
        memory: 1Gi
        cpu: "0.5"
    storage:
      type: ephemeral
```

I receive the status as 
```
status:
  conditions:
  - lastTransitionTime: 2020-08-04T13:24:43+0000
    message: Exceeded timeout of 300000ms while waiting for StatefulSet resource my-cluster-zookeeper
      in namespace default to be ready
    reason: TimeoutException
    status: "True"
    type: NotReady
  observedGeneration: 1
```
Any clue as to why would I get 
`Exceeded timeout of 300000ms while waiting for StatefulSet resource my-cluster-zookeeper
      in namespace default to be ready` ?

I am using OpenShift cluster 4.6
