### ISSUE TITLE
Plain listeners config when external listeners (loadbalancer, encryption: tls, authentication: scram-sha-512) and simple authorization is already configured

### ISSUE THREAD

**Issue by oana-s** [strimzi/strimzi-kafka-operator#3474]
I have already configured the external listeners and ACL as it follows (those are functional)

```yaml
listeners:
     plain: {}
     external:
       type: loadbalancer
       tls: true
       authentication:
         type: scram-sha-512
authorization:
  type: simple
```

This is hosted on a AKS cluster. Consuming from on prem it does work already and also producing from inside the cluster but with publicIP:9094 as bootstrapServers.

I would like to add a producer inside the cluster and use 9092 port (like this  BootstrapServers = "my-cluster-kafka-bootstrap:9092", I suppose) with minumun necessary effort (even without ACL if possible, without any authentication, without any encryption).

What would recommend?

Thank you in advance!

**Comment by scholzj** [comment]
Kafka has only one authorizer configuration for the whole cluster. So it is either on or off for all listeners. The `plain` listener is without encryption, but if you need authorization for the external listener, you will need enable authentication there (since without authentication the authorization would deny everything). So you will need something like this?

```
listeners:
  plain:
    authentication:
      type: scram-sha-512
  external:
    type: loadbalancer
    tls: true
    authentication:
      type: scram-sha-512
authorization:
  type: simple
```
