### ISSUE TITLE
[Enhancement] Add  Connectors info to the status  of KafkaConnector custom resources

### ISSUE THREAD

**Issue by samuel-hawker** [strimzi/strimzi-kafka-operator#3476]
**Is your feature request related to a problem? Please describe.**

Kafka 2.5 introduced the `GET /connectors/{name}/topics` Connect REST API endpoint to list the topics that a source connector has written to or a sink connector has read from. It would be good to add this info to the `KafkaMirrorMaker2` and `KafkaConnector` custom resource status fields, alongside the other connector info. 

Related is the `PUT /connectors/{name}/topics/reset` endpoint that resets the above list. This could be done via a custom resource annotation that gets removed after the operation completes.

**Describe the solution you'd like**
Work in progress

**Describe alternatives you've considered**

**Additional context**

**Comment by scholzj** [comment]
I think this should go to KafkaConnector and not into KafkaConnect.

**Comment by samuel-hawker** [comment]
Thanks Jakub, you're absolutely right, and I have updated the issue to reflect this.

As part of this work the `Map<String, Object> connectorStatus` field in `KafkaConnectorStatus` should be converted into a typed Object instead of a map to allow for concrete key value pairs being handled rather than generic keys.

**Comment by rudeigerc** [comment]
Hi, I would like to work on it and need some guidance. 😃
As mentioned in https://github.com/strimzi/strimzi-kafka-operator/issues/3476#issuecomment-670494001, what I should do first is to rebase the `Map<String, Object> connectorStatus` to `Object connectorStatus` and replace the following parts
https://github.com/strimzi/strimzi-kafka-operator/blob/136ceaf5782d544267c8707a300229a7ecbfd64a/cluster-operator/src/main/java/io/strimzi/operator/cluster/operator/assembly/AbstractConnectOperator.java#L668-L688
with the Object structure, then implement the `getTopics` in `KafkaConnectApiImpl.java`. Are there any supplements?

**Comment by scholzj** [comment]
I'm not sure it should go into the map. Maybe it should be just another field on the same level? Something like `List<String> topics`?

WDYT @tombentley @samuel-hawker?

**Comment by scholzj** [comment]
Maybe something like this?

```yaml
  apiVersion: kafka.strimzi.io/v1alpha1
  kind: KafkaConnector
  metadata:
    labels:
      strimzi.io/cluster: my-connect
    name: echo-sink-connector
    namespace: myproject
  spec:
    class: EchoSink
    config:
      level: INFO
      topics: kafka-test-apps
    tasksMax: 3
  status:
    conditions:
    - lastTransitionTime: "2021-02-08T21:03:17.921391Z"
      status: "True"
      type: Ready
    connectorStatus:
      connector:
        state: RUNNING
        worker_id: 172.16.180.222:8083
      name: echo-sink-connector
      tasks:
      - id: 0
        state: RUNNING
        worker_id: 172.16.180.222:8083
      - id: 1
        state: RUNNING
        worker_id: 172.16.180.222:8083
      - id: 2
        state: RUNNING
        worker_id: 172.16.180.222:8083
      type: sink
    topics:
    - kafka-test-apps
    observedGeneration: 1
    tasksMax: 3
```
