### ISSUE TITLE
[Question] Can not publish to Kafka with any client

### ISSUE THREAD

**Issue by emaincourt** [strimzi/strimzi-kafka-operator#3510]
Hi folks 👋 

First of all thanks a lot for the great work you're doing with Strimzi.

I'm currently trying to migrate some of our messaging systems to Kafka inside of Kubernetes and would need a bit of advise here.

Please find below the manifest of my cluster:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: scheduler
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.5"
      auto.create.topics.enable: true
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
        class: expandable-gp2
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
      class: expandable-gp2
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

When applying the manifests, everything gets properly created and the Kafka cluster seems to be running well. However, I've never been able to publish anything to any topic from a Docker container. Let's take the following code:

```
sarama.Logger = log.New(os.Stdout, "[sarama] ", log.LstdFlags)

config := sarama.NewConfig()
config.Producer.RequiredAcks = sarama.WaitForAll
config.Producer.Return.Successes = true
config.Producer.Retry.Max = 0

p, err := sarama.NewSyncProducer([]string{"scheduler-kafka-bootstrap.kafka:9092"}, config)
if err != nil {
	panic(err)
}

if _, _, err := p.SendMessage(&sarama.ProducerMessage{
	Topic:    "topic",
	Value:     sarama.StringEncoder("Hello"),
	Partition: -1,
}); err != nil {
	panic(err)
}
```

When I run it locally with port forward it works well. However, as soon as I run it inside the Kubernetes cluster, I get the following error on Kafka side:

```
scheduler-kafka-2 kafka 2020-08-14 14:33:17,692 WARN [SocketServer brokerId=2] Unexpected error from /100.96.25.8; closing connection (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-2-ListenerName(PLAIN-9092)-PLAINTEXT-3]
scheduler-kafka-2 kafka org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 369295616 larger than 104857600)
scheduler-kafka-2 kafka         at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
scheduler-kafka-2 kafka         at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:448)
scheduler-kafka-2 kafka         at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:398)
scheduler-kafka-2 kafka         at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:678)
scheduler-kafka-2 kafka         at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:580)
scheduler-kafka-2 kafka         at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
scheduler-kafka-2 kafka         at kafka.network.Processor.poll(SocketServer.scala:861)
scheduler-kafka-2 kafka         at kafka.network.Processor.run(SocketServer.scala:760)
scheduler-kafka-2 kafka         at java.base/java.lang.Thread.run(Thread.java:834)
```

And the following one on my backend side:

```
broker-68978b745c-77pmz broker [sarama] 2020/08/14 14:33:17 ClientID is the default of 'sarama', you should consider setting it to something application-specific.
broker-68978b745c-77pmz broker [sarama] 2020/08/14 14:33:17 producer/broker/2 starting up
broker-68978b745c-77pmz broker [sarama] 2020/08/14 14:33:17 producer/broker/2 state change to [open] on schedule-job-events/2
broker-68978b745c-77pmz broker [sarama] 2020/08/14 14:33:17 Connected to broker at scheduler-kafka-2.scheduler-kafka-brokers.kafka.svc:9092 (registered as #2)
broker-68978b745c-77pmz broker [sarama] 2020/08/14 14:33:17 producer/broker/2 state change to [closing] because read tcp 100.96.25.8:49026->100.96.13.61:9092: read: connection reset by peer
broker-68978b745c-77pmz broker [sarama] 2020/08/14 14:33:17 Closed connection to broker scheduler-kafka-2.scheduler-kafka-brokers.kafka.svc:9092
broker-68978b745c-77pmz broker [sarama] 2020/08/14 14:42:48 client/metadata fetching metadata for all topics from broker scheduler-kafka-bootstrap.kafka:9092
broker-68978b745c-77pmz broker [sarama] 2020/08/14 14:52:48 client/metadata fetching metadata for all topics from broker scheduler-kafka-bootstrap.kafka:9092
```

According to what I found on the web, it seems somehow to be related to TLS which is, as far as I know, disabled on port `9092` according to my manifest.

I've been trying to make it work with both:
- [Samara](https://github.com/Shopify/sarama)
- [Confluent Kafka Go](https://github.com/confluentinc/confluent-kafka-go)
- [Kafka Go](https://github.com/segmentio/kafka-go)

Do you have any hints ?

Thanks in advance for help of any kind
