### ISSUE TITLE
[Question] Problem using OAUTH with external listeners (0.19 operator / 2.5.0 kafka)

### ISSUE THREAD

**Issue by somejfn** [strimzi/strimzi-kafka-operator#3513]
Hi !

Im trying to enable OAUTH2 authentication but when I do the kafka pods complains continuously of:

```
2020-08-14 21:05:30,103 INFO [SocketServer brokerId=0] Failed authentication with /10.35.1.41 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(REPLICATION-9091)-SSL-0]
2020-08-14 21:05:30,130 INFO [SocketServer brokerId=0] Failed authentication with /10.35.1.41 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(REPLICATION-9091)-SSL-1]
2020-08-14 21:05:30,154 INFO [SocketServer brokerId=0] Failed authentication with /10.35.1.41 (SSL handshake failed) (org.apache.kafka.common.network.Selector) [data-plane-kafka-network-thread-0-ListenerName(REPLICATION-9091)-SSL-2]
```

Interestingly that IP (10.35.1.41) is the strimzi cluster operator pod.

That cluster is working fine with just TLS enabled.   My Kafka resource when OAUTH enabled:

```
    listeners:
      external:
        type: ingress
        class: my-nginx-ingress
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          validIssuerUri: https://keycloak.somename.io/auth/realms/kafka
          jwksEndpointUri: https://keycloak.somename.io/auth/realms/kafka/protocol/openid-connect/certs
          userNameClaim: preferred_username
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: oidc.crt
        configuration:
          bootstrap:
            host: bootstrap.somename.io
          brokers:
          - broker: 0
            host: broker-0.somename.io
          - broker: 1
            host: broker-1.somename.io
          - broker: 2
            host: broker-2.somename.io
      plain: {}
      tls:
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          validIssuerUri: https://keycloak.somename.io/auth/realms/kafka
          jwksEndpointUri: https://keycloak.somename.io/auth/realms/kafka/protocol/openid-connect/certs
          userNameClaim: preferred_username
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: oidc.

```

This same pod logs during startup looked fine to me:

```
+ ./kafka_pre_start.sh
Waiting for the TLS sidecar to get ready
TLS sidecar is not ready yet, waiting for another 1 second
TLS sidecar should be ready
++ hostname
++ awk -F- '{print $NF}'
+ STRIMZI_BROKER_ID=0
+ export STRIMZI_BROKER_ID
+ echo STRIMZI_BROKER_ID=0
+ export GC_LOG_ENABLED=false
+ GC_LOG_ENABLED=false
+ '[' -z '' ']'
+ export KAFKA_LOG4J_OPTS=-Dlog4j.configuration=file:/opt/kafka/custom-config/log4j.properties
+ KAFKA_LOG4J_OPTS=-Dlog4j.configuration=file:/opt/kafka/custom-config/log4j.properties
+ rm -f /var/opt/kafka/kafka-ready /var/opt/kafka/zk-connected
STRIMZI_BROKER_ID=0
++ ls /opt/kafka/libs/kafka-agent.jar
+ KAFKA_OPTS=' -javaagent:/opt/kafka/libs/kafka-agent.jar=/var/opt/kafka/kafka-ready:/var/opt/kafka/zk-connected'
+ export KAFKA_OPTS
+ '[' '' = true ']'
+ '[' -n '' ']'
+ KAFKA_OPTS=' -javaagent:/opt/kafka/libs/kafka-agent.jar=/var/opt/kafka/kafka-ready:/var/opt/kafka/zk-connected '
+ '[' false = true ']'
+ export LOG_DIR=/opt/kafka
+ LOG_DIR=/opt/kafka
++ tr -dc _A-Z-a-z-0-9
++ head -c32
+ CERTS_STORE_PASSWORD=0e3lC3OlDX5_GZGu0fF_kcfImsAIZ9hm
+ export CERTS_STORE_PASSWORD
+ mkdir -p /tmp/kafka
+ ./kafka_tls_prepare_certificates.sh
Preparing truststore for replication listener
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/kafka/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore for replication listener is complete
Looking for the right CA
Found the right CA: /opt/kafka/cluster-ca-certs/ca.crt
Preparing keystore for replication and clienttls listener
Preparing keystore for replication and clienttls listener is complete
Preparing truststore for clienttls listener
Adding /opt/kafka/client-ca-certs/ca.crt to truststore /tmp/kafka/clients.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore for clienttls listener is complete
Preparing truststore for OAuth on TLS listener
Adding /opt/kafka/certificates/oauth-tls-9093-certs/ca-truststore-0/tls.crt to truststore /tmp/kafka/oauth-tls-9093.truststore.p12 with alias oauth-0
Certificate was added to keystore
Preparing truststore for OAuth on TLS listener is complete
Preparing truststore for OAuth on external listener
Adding /opt/kafka/certificates/oauth-external-9094-certs/ca-truststore-0/tls.crt to truststore /tmp/kafka/oauth-external-9094.truststore.p12 with alias oau
th-0
Certificate was added to keystore
Preparing truststore for OAuth on external listener is complete
Starting Kafka with configuration:
+ echo 'Starting Kafka with configuration:'
+ tee /tmp/strimzi.properties
+ ./kafka_config_generator.sh
+ sed -e 's/sasl.jaas.config=.*/sasl.jaas.config=[hidden]/g' -e 's/password=.*/password=[hidden]/g'
##############################
##############################
# This file is automatically generated by the Strimzi Cluster Operator
# Any changes to this file will be ignored and overwritten!
##############################
##############################

##########
# Broker ID
##########
broker.id=0

##########
# Zookeeper
##########
zookeeper.connect=localhost:2181

##########
# Kafka message logs configuration
##########
log.dirs=/var/lib/kafka/data-0/kafka-log0

##########
# Replication listener
##########
listener.name.replication-9091.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
listener.name.replication-9091.ssl.keystore.password=[hidden]
listener.name.replication-9091.ssl.keystore.type=PKCS12
listener.name.replication-9091.ssl.truststore.location=/tmp/kafka/cluster.truststore.p12
listener.name.replication-9091.ssl.truststore.password=[hidden]
listener.name.replication-9091.ssl.truststore.type=PKCS12
listener.name.replication-9091.ssl.client.auth=required

##########
# Plain listener
##########

##########
# TLS listener
##########
listener.name.tls-9093.oauthbearer.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
listener.name.tls-9093.oauthbearer.sasl.jaas.config=[hidden]
listener.name.tls-9093.sasl.enabled.mechanisms=OAUTHBEARER

listener.name.tls-9093.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
listener.name.tls-9093.ssl.keystore.password=[hidden]
listener.name.tls-9093.ssl.keystore.type=PKCS12

##########
# External listener
##########
listener.name.external-9094.oauthbearer.sasl.server.callback.handler.class=io.strimzi.kafka.oauth.server.JaasServerOauthValidatorCallbackHandler
listener.name.external-9094.oauthbearer.sasl.jaas.config=[hidden]
listener.name.external-9094.sasl.enabled.mechanisms=OAUTHBEARER

listener.name.external-9094.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12
listener.name.external-9094.ssl.keystore.password=[hidden]
listener.name.external-9094.ssl.keystore.type=PKCS12

##########
# Common listener configuration
##########
listeners=REPLICATION-9091://0.0.0.0:9091,PLAIN-9092://0.0.0.0:9092,TLS-9093://0.0.0.0:9093,EXTERNAL-9094://0.0.0.0:9094
advertised.listeners=REPLICATION-9091://saas-kafka-0.saas-kafka-brokers.saas-apps.svc:9091,PLAIN-9092://saas-kafka-0.saas-kafka-brokers.saas-apps.svc:9092,
TLS-9093://saas-kafka-0.saas-kafka-brokers.saas-apps.svc:9093,EXTERNAL-9094://broker-0.somename.io:443
listener.security.protocol.map=REPLICATION-9091:SSL,PLAIN-9092:PLAINTEXT,TLS-9093:SASL_SSL,EXTERNAL-9094:SASL_SSL
inter.broker.listener.name=REPLICATION-9091
sasl.enabled.mechanisms=
ssl.secure.random.implementation=SHA1PRNG
ssl.endpoint.identification.algorithm=HTTPS

##########
# User provided configuration
##########
auto.create.topics.enable=false
offsets.topic.replication.factor=3
ssl.enabled.protocols=TLSv1.2
ssl.protocol=TLSv1.2
transaction.state.log.min.isr=2
+ echo ''
+ '[' -z -Xms128M ']'
+ . ./set_kafka_gc_options.sh
++ set -e
transaction.state.log.replication.factor=3
++ '[' false == true ']'
++ export 'KAFKA_GC_LOG_OPTS= '
++ KAFKA_GC_LOG_OPTS=' '
++ export GC_LOG_ENABLED=false
++ GC_LOG_ENABLED=false
+ exec /usr/bin/tini -w -e 143 -- /opt/kafka/bin/kafka-server-start.sh /tmp/strimzi.properties
2020-08-14 21:00:12,315 INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$) [main]
2020-08-14 21:00:13,802 INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper
.common.X509Util) [main]
2020-08-14 21:00:13,925 INFO Registered signal handlers for TERM, INT, HUP (org.apache.kafka.common.utils.LoggingSignalHandler) [main]
2020-08-14 21:00:13,929 INFO starting (kafka.server.KafkaServer) [main]
2020-08-14 21:00:13,930 INFO Connecting to zookeeper on localhost:2181 (kafka.server.KafkaServer) [main]
2020-08-14 21:00:13,958 INFO [ZooKeeperClient Kafka server] Initializing a new session to localhost:2181. (kafka.zookeeper.ZooKeeperClient) [main]
2020-08-14 21:00:13,965 INFO Client environment:zookeeper.version=3.5.7-f0fdd52973d373ffd9c86b81d99842dc2c7f660e, built on 02/10/2020 11:30 GMT (org.apache
.zookeeper.ZooKeeper) [main]

```

Any help appreciated !
