### ISSUE TITLE
Timeout with external bootstrap and NodePort

### ISSUE THREAD

**Issue by dbalzan** [strimzi/strimzi-kafka-operator#3605]
I have a development Strimzi cluster which has been working for over a month.  Earlier today there were some problems with the worker nodes that needed a power cycle.   Once the worker nodes were available again, the pods came back up into Running state and the topics are accessible with the following command:

`kubectl -n kafka run kafka-producer -it --image=strimzi/kafka:0.18.0-kafka-2.5.0 --rm=true -- bin/kafka-console-producer.sh --broker-list mykafka-kafka-bootstrap:9092 --topic my-topic`

But any request from outside the cluster results in a timeout.  For example the following commands results in the error messages below
`./kafka-broker-api-versions.sh --bootstrap-server <external ip address>:32447`

> Exception in thread "main" java.lang.RuntimeException: Request METADATA failed on brokers List(*****:32447 (id: -1 rack: null))
>         at kafka.admin.BrokerApiVersionsCommand$AdminClient.sendAnyNode(BrokerApiVersionsCommand.scala:158)
>         at kafka.admin.BrokerApiVersionsCommand$AdminClient.findAllBrokers(BrokerApiVersionsCommand.scala:181)
>         at kafka.admin.BrokerApiVersionsCommand$AdminClient.awaitBrokers(BrokerApiVersionsCommand.scala:173)
>         at kafka.admin.BrokerApiVersionsCommand$.execute(BrokerApiVersionsCommand.scala:60)
>         at kafka.admin.BrokerApiVersionsCommand$.main(BrokerApiVersionsCommand.scala:54)
>         at kafka.admin.BrokerApiVersionsCommand.main(BrokerApiVersionsCommand.scala)

`./kafka-topics.sh --bootstrap-server <external ip address>:32447 --list`

> Error while executing topic command : org.apache.kafka.common.errors.TimeoutException: Call(callName=listTopics, deadlineMs=1599227068720, tries=1, nextAllowedTryMs=1599227068821) timed out at 1599227068721 after 1 attempt(s)
> [2020-09-04 15:44:28,725] ERROR java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=listTopics, deadlineMs=1599227068720, tries=1, nextAllowedTryMs=1599227068821) timed out at 1599227068721 after 1 attempt(s)
>         at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
>         at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
>         at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
>         at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
>         at kafka.admin.TopicCommand$AdminClientTopicService.getTopics(TopicCommand.scala:352)
>         at kafka.admin.TopicCommand$AdminClientTopicService.listTopics(TopicCommand.scala:260)
>         at kafka.admin.TopicCommand$.main(TopicCommand.scala:66)
>         at kafka.admin.TopicCommand.main(TopicCommand.scala)
> Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=listTopics, deadlineMs=1599227068720, tries=1, nextAllowedTryMs=1599227068821) timed out at 1599227068721 after 1 attempt(s)
> Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.
>  (kafka.admin.TopicCommand$)

NodePort service is available and running on 32447 as it was before (when it worked)

```
NAME                                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
mykafka-kafka-0                    NodePort    10.97.92.197     <none>        9094:31448/TCP               124m
mykafka-kafka-1                    NodePort    10.97.179.155    <none>        9094:30822/TCP               124m
mykafka-kafka-2                    NodePort    10.102.8.22      <none>        9094:32284/TCP               124m
mykafka-kafka-bootstrap            ClusterIP   10.98.173.176    <none>        9091/TCP,9092/TCP,9093/TCP   124m
mykafka-kafka-brokers              ClusterIP   None             <none>        9091/TCP,9092/TCP,9093/TCP   124m
mykafka-kafka-external-bootstrap   NodePort    10.110.94.23     <none>        9094:32447/TCP               124m
mykafka-zookeeper-client           ClusterIP   10.108.168.190   <none>        2181/TCP                     125m
mykafka-zookeeper-nodes            ClusterIP   None             <none>        2181/TCP,2888/TCP,3888/TCP   125m
```

**Environment:**
 - Strimzi version:. 0.18.0
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes v1.18.5
 - Infrastructure: RHEL on VM hypervisor

**YAML files**

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: mykafka
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false
        overrides:
          bootstrap:
            nodePort: 32447
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: persistent-claim
      size: 10Gi
      class: fast
      deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      class: fast
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
