### ISSUE TITLE
[Question] what is the best way to test avoiding data loss while restarting kafka?

### ISSUE THREAD

**Issue by mykidong** [strimzi/strimzi-kafka-operator#3622]
I have installed kafka cluster with operator with the following manifest `kafka-persistent.yaml`:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - id: 0
        class: direct.csi.min.io
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      class: direct.csi.min.io
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

I have checked if kafka works with the following producer and consumer:
```
# consume messages.
kubectl -n kafka run kafka-consumer -ti --image=strimzi/kafka:0.19.0-kafka-2.5.0 --rm=true --restart=Never -- \
bin/kafka-console-consumer.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --topic my-topic --from-beginning

# produce messages.
kubectl -n kafka run kafka-producer -ti --image=strimzi/kafka:0.19.0-kafka-2.5.0 --rm=true --restart=Never -- \
bin/kafka-console-producer.sh --broker-list my-cluster-kafka-bootstrap:9092 --topic my-topic
.. type something...
```
It worked fine.

Now, I want to check the data availability with restarting kafka.
I have deleted and applied the above manifest `kafka-persistent.yaml`  to do that.
After reinstalling kafka, I have run consumer, but it does not consume anything from the topic.

I have no idea how to check if the data is available even if kafka is restarted.
