### ISSUE TITLE
Unable to produce topic on kafka producer with internal load balancer enabled with 9094

### ISSUE THREAD

**Issue by saloni-2404** [strimzi/strimzi-kafka-operator#3625]
Here is my configuration:

```yaml
listeners:
   external:
    type: loadbalancer
    tls: false
    authentication:
      type: tls
template:
  externalBootstrapService:
    metadata:
      annotations:
        cloud.google.com/load-balancer-type: "Internal"
  perPodService:
    metadata:
      annotations:
        cloud.google.com/load-balancer-type: "Internal"
```

Here is the error:
When I run the command ./bin/kafka-console-producer.sh --broker-list my-src-cluster-kafka-external-bootstrap.kafka-src-ir174.svc.cluster.local:9094 --topic sep09-topic

[2020-09-10 07:51:15,839] ERROR Error when sending message to topic sep09-topic with key: null, value: 0 bytes with error: (org.apache.kafka.clients.producer.internals.ErrorLoggingCallback)
org.apache.kafka.common.errors.TimeoutException: Topic sep09-topic not present in metadata after 60000 ms.

Even though when I list topics using the command ./bin/kafka-topics.sh --zookeeper localhost:2181 --list I can see the topic.

Am I missing something?
