### ISSUE TITLE
[Bug] Kafka Operator fails to bringup zookeeper with error - java.io.IOException: keystore password was incorrect

### ISSUE THREAD

**Issue by sreenureddyy** [strimzi/strimzi-kafka-operator#3657]
**Describe the bug**
Trying to bring up the kafka operator and I am running into zookeeper CrashLoopBackOff

**To Reproduce**

Followed the quickstarts guide of Kubernetes Kind from - https://strimzi.io/quickstarts/

1. Created Custom Resource  
   `kubectl apply -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka`
2. Apply Kafka operator
     `kubectl apply -f kafka-operator.yaml -n kafka`
3. Get status of Kafka operator
     ```
     # kubectl get all -n kafka
     NAME                                            READY   STATUS             RESTARTS   AGE
     pod/my-cluster-zookeeper-0                      0/1     CrashLoopBackOff   4          6m1s
     pod/my-cluster-zookeeper-1                      0/1     CrashLoopBackOff   4          6m1s
     pod/my-cluster-zookeeper-2                      0/1     CrashLoopBackOff   4          6m1s
    pod/strimzi-cluster-operator-7d6cd6bdf7-zkh6z   1/1     Running            0          21m
    ```
4. zookeeper logs showing below error
     ```
     # kubectl logs -f pod/my-cluster-zookeeper-0 -n kafka
     Detected Zookeeper ID 1
     Preparing truststore
     Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/zookeeper/cluster.truststore.p12 with alias ca
     keytool error: java.io.IOException: keystore password was incorrect
     ```

**Environment:**
 - Strimzi version: Latest
 - Installation method: YAML files
 - Kubernetes cluster: 
    
    ```
    # kubectl version

    Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.2-6+38ac483e736488", 
    GitCommit:"38ac483e736488517dd754156441b89e0b2060e2", GitTreeState:"clean", BuildDate:"2020-07- 
     07T13:54:17Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

    Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.2-6+38ac483e736488", 
    GitCommit:"38ac483e736488517dd754156441b89e0b2060e2", GitTreeState:"clean", BuildDate:"2020-07- 
    07T13:51:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
    ```
 - Infrastructure: VMware supervisor cluster 

**YAML files**

   Custom resources yaml file- https://strimzi.io/install/latest?namespace=kafka
   Yaml file to deploy Kafka 

 **kafka-operator.yaml**
   ```
   apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  cruiseControl: {}
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: loadbalancer
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
   ```
