### ISSUE TITLE
[Question]  Can affinity scheduled broker pods end up on other nodes? 

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#3664]
I noticed that we had kafka brokers on nodes of other node groups even after setting the below affinity setting. I don't believe they were scheduled there originally, but might have ended up there as a result of a kafka broker eviction. We don't have any taints/dedicated tolerations set. 

Is this possible? 

```
     template:
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                    - key: app
                      operator: In
                      values:
                      - high-mem
```
