### ISSUE TITLE
[Question] Is there anything more needed to set up after installation by Strimzi operator (from OperatorHub) in comparison to installation according to quickstart?

### ISSUE THREAD

**Issue by mkralik3** [strimzi/strimzi-kafka-operator#3666]
Is there anything more needed to set up after installation by Strimzi operator (from OperatorHub) in comparison to installation according to quickstart?

When I install Kafka on OCP 4.5 using commands from quickstarts https://strimzi.io/quickstarts/
```
oc apply -f 'https://strimzi.io/install/latest?namespace=mkralik1' -n mkralik1
oc apply -f https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml -n mkralik1
```
The pods are successfully created
```
my-cluster-entity-operator-b9d8b67bd-jr9ct   3/3     Running   0          2m32s
my-cluster-kafka-0                           2/2     Running   0          3m4s
my-cluster-zookeeper-0                       1/1     Running   0          3m46s
strimzi-cluster-operator-7d6cd6bdf7-7k5nx    1/1     Running   0          5m
```
and I am able to perform producer-consumer example from the quickstarts:
```
oc -n mkralik1 run kafka-producer -ti --image=strimzi/kafka:0.19.0-kafka-2.5.0 --rm=true --restart=Never -- bin/kafka-console-producer.sh --broker-list my-cluster-kafka-bootstrap:9092 --topic my-topic

oc -n mkralik1 run kafka-consumer -ti --image=strimzi/kafka:0.19.0-kafka-2.5.0 --rm=true --restart=Never -- bin/kafka-console-consumer.sh --bootstrap-server my-cluster-kafka-bootstrap:9092 --topic my-topic --from-beginning
```

However, when I install Kafka by Strimzi operator from OperatorHub (v. 0.19.0) (update channel: stable, Installation Mode: All namespaces on the cluster (default) ) 
with default settings
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: mkralik1
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.5'
    version: 2.5.0
    storage:
      type: ephemeral
    replicas: 3
    listeners:
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: tls
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
  zookeeper:
    storage:
      type: ephemeral
    replicas: 3
```

the pods are successfully created too but I am not able to perform producer-consumer example from the quickstarts as previous. The producer / consumer are not able to connect to broker:
```
[2020-09-17 11:32:45,644] WARN [Consumer clientId=consumer-console-consumer-53917-1, groupId=console-consumer-53917] Bootstrap broker my-cluster-kafka-bootstrap:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2020-09-17 11:32:46,049] WARN [Consumer clientId=consumer-console-consumer-53917-1, groupId=console-consumer-53917] Bootstrap broker my-cluster-kafka-bootstrap:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2020-09-17 11:32:46,452] WARN [Consumer clientId=consumer-console-consumer-53917-1, groupId=console-consumer-53917] Bootstrap broker my-cluster-kafka-bootstrap:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
```
I don't see any error in my-cluster-kafka pod log.

Is there anything more which I need to set?

edit: Maybe this is a bug because when I am using AMQ Streams operator from OperatorHub (v 1.5.3) which uses the same settings for Kafka as I specified above, the producer-consumer example works.

**Comment by scholzj** [comment]
This should work fine in my opinion. The difference in this case is that when using https://strimzi.io/examples/latest/kafka/kafka-persistent-single.yaml, there is no authentication configured on the listeners. Whereas the Kafka CR you listed as used with Operator Hub has authentication enabled. So you would need to authenticate to send or receive messages which the quick start commends don't do. I originally expected that it would give some more intelligent error message, but I tried it locally and get the same message as you. So I think this is the issue.

Just edit the Kafka CR and change it from:

```yaml
    listeners:
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: tls
```

to:

```yaml
    listeners:
      plain: {}
      tls: {}
```

Wehad to add the authentication to the examples there because the openShift UI was unable to handle the `{}`. Hopefully it should be fixed in OCP 4.6.
