### ISSUE TITLE
How can I replicate connect-config, connect-offsets, connect-status topics using Mirror Maker 2 from prod kafka to backup?

### ISSUE THREAD

**Issue by IlyaNakhaichuk** [strimzi/strimzi-kafka-operator#3682]
I have 2 clusters of kafka, one prod, the second cluster is exactly empty. I need to organize this cluster. I am using Mirror Maker 2, which I run through the strimzi operator. My config looks like this. With this configuration, I get to back up the topics jdbc_source_ums_user, _schemas. Could you help me?

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker2
spec:
  version: 2.5.0
  connectCluster: "backup-kafka-target"
  replicas: 1
  clusters:
  - alias: "prod-kafka-source"
    bootstrapServers: prod1:9092,prod2:9092,prod3:9092
  - alias: "backup-kafka-target"
    bootstrapServers: backup:9092
  mirrors:
  - sourceCluster: "prod-kafka-source"
    targetCluster: "backup-kafka-target"
    sourceConnector:
      tasksMax: 5
      config:
        replication.factor: 3
        offset-syncs.topic.replication.factor: 3
        sync.topic.acls.enabled: "false"
        sync.topic.configs.enabled: "true"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 3
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 3
    topics: "__test1-connect-config,__test1-connect-offsets,__test1-connect-status,__test2-connect-config,__test2-connect-offsets,__test2-connect-status,jdbc_source_ums_user,_schemas"
    topicsBlacklistPattern: .*[\-\.]internal, .*\.replica
    groupsBlacklistPattern: console-consumer-.*, connect-.*
    groups: ".*" 

```

**Comment by scholzj** [comment]
Have you check the docs (https://strimzi.io/docs/operators/latest/full/using.html#type-KafkaMirrorMaker2MirrorSpec-reference) or the examples (https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/mirror-maker/kafka-mirror-maker-2.yaml)? According to them you should use the `topicsPattern` to specify a regex with the topics whcih should be mirrored. So if you haven't tried that, that would be the thing I would try.

**Comment by IlyaNakhaichuk** [comment]
After all, I set specifically the topics that need to be backed up in the line:
```topics: "__test1-connect-config,__test1-connect-offsets,__test1-connect-status,__test2-connect-config,__test2-connect-offsets,__test2-connect-status,jdbc_source_ums_user,_schemas```

As I understand it, this should be enough. And can I use topics in conjunction with topicsPattern?

**Comment by scholzj** [comment]
But why do you think there is any `topics` field there? There is nothing about it in the spec: https://strimzi.io/docs/operators/latest/full/using.html#type-KafkaMirrorMaker2MirrorSpec-reference

**Comment by IlyaNakhaichuk** [comment]
@scholzj I tried to replace topics with topicsPattern, everything is the same, topics that start with __test1-connect-offsets are still not replicated, can there be another solution?

**Comment by scholzj** [comment]
Have you also changed the value to make it a valid regular expression? Because I do not think coma separated list of topic names would be valid from this perspective.

**Comment by IlyaNakhaichuk** [comment]
@scholzj Yes I tried setting topicsPattern: ". *". Removed the list of topics.
I got a replication of all my topics besides:
```__test1-connect-config,__test1-connect-offsets,__test1-connect-status,__test2-connect-config,__test2-connect-offsets,__test2-connect-status```

**Comment by scholzj** [comment]
So can you share the actual configuration you use now? Mayve it doesn't like the `__` prefixes?

**Comment by IlyaNakhaichuk** [comment]
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: my-mirror-maker2
spec:
  version: 2.5.0
  connectCluster: "backup-kafka-target"
  replicas: 1
  clusters:
  - alias: "prod-kafka-source"
    bootstrapServers: prod1:9092,prod2:9092,prod3:9092
  - alias: "backup-kafka-target"
    bootstrapServers: backup:9092
    #config:
    #  config.storage.replication.factor: 1
    #  offset.storage.replication.factor: 1
    #  status.storage.replication.factor: 1
  mirrors:
  - sourceCluster: "prod-kafka-source"
    targetCluster: "backup-kafka-target"
    sourceConnector:
      tasksMax: 5
      config:
        replication.factor: 3
        offset-syncs.topic.replication.factor: 3
        sync.topic.acls.enabled: "false"
        sync.topic.configs.enabled: "true"
    #heartbeatConnector:
    #  config:
    #    heartbeats.topic.replication.factor: 3
    #checkpointConnector:
    #  config:
    #    checkpoints.topic.replication.factor: 3
    topicsPattern: "__test1-connect-config,__test1-connect-offsets,__test1-connect-status,__test2-connect-config,__test2-connect-offsets,__test2-connect-status,jdbc_source_ums_user,_schemas"
    #topicsPattern: ".*"
    #topicsBlacklistPattern: .*[\-\.]internal, .*\.replica
    topicsBlacklistPattern: replic
    #groupsBlacklistPattern: console-consumer-.*, connect-.*
    groupsBlacklistPattern: replic
    #groups: ".*"
```
I don’t think that matters are in the consoles, because the topic called _schema, it replicates. Perhaps because two "__" are used?
