### ISSUE TITLE
Availability of bootstrap servers on all network interfaces

### ISSUE THREAD

**Issue by samuel-sujith** [strimzi/strimzi-kafka-operator#3705]
Hello Team,

I have installed the strimzi operator from the quickstart option using the below command

kubectl apply -f 'https://strimzi.io/install/latest?namespace=kafka' -n kafka

After that I am trying to create the cluster using the below yaml

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      external:
        type: nodeport
        tls: false
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.5"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
The host on which this is exposed as a nodeport has 2 addresses one is the address within the firewall,addr1 and one for computers trying to reach from external,addr2. 

When i am trying to enter the bootstrap server address as <addr2>:<nodeport> in the kafka UI tool, I am unable to connect.

I would just like to confirm that if strimzi has exposed the bootstrap server externally as NodePort then doesnt that mean it would be available over all the network interface addresses?

My service addresses are as in the below
NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                      AGE
my-cluster-kafka-0                    NodePort    10.233.29.58    <none>        9094:31079/TCP               111m
my-cluster-kafka-1                    NodePort    10.233.44.61    <none>        9094:31366/TCP               111m
my-cluster-kafka-2                    NodePort    10.233.6.9      <none>        9094:31418/TCP               111m
my-cluster-kafka-bootstrap            ClusterIP   10.233.18.203   <none>        9091/TCP,9092/TCP,9093/TCP   111m
my-cluster-kafka-brokers              ClusterIP   None            <none>        9091/TCP,9092/TCP,9093/TCP   111m
my-cluster-kafka-external-bootstrap   NodePort    10.233.1.171    <none>        9094:30252/TCP               111m
my-cluster-zookeeper-client           ClusterIP   10.233.58.31    <none>        2181/TCP                     111m
my-cluster-zookeeper-nodes            ClusterIP   None            <none>        2181/TCP,2888/TCP,3888/TCP   111m
zoo-entrance                          NodePort    10.233.46.129   <none>        2181:31655/TCP               88m

When i provide  addr2:30252, it just hangs for a long time and then says not reachable.

Kindly assist.

Thanks,
Sujith.

**Comment by samuel-sujith** [comment]
Changed the yaml overrides to below and started working

```yaml
    listeners:
      external:
        type: nodeport
        tls: false
        overrides:
          bootstrap:
            nodePort: 32510
          brokers:
          - broker: 0
            nodePort: 32511
            advertisedHost: 150.236.157.60
          - broker: 1
            nodePort: 32512
            advertisedHost: 150.236.157.60
          - broker: 2
            nodePort: 32513
```
