### ISSUE TITLE
[Bug] advertised.listeners environment variable in kafka_config_generator.sh concatenated with "export STRIMZI_NODEPORT_DEFAULT_ADDRESS=..."

### ISSUE THREAD

**Issue by domanq** [strimzi/strimzi-kafka-operator#3727]
**Describe the bug**

One of the three brokers does not start due to advertised.listeners environment variable in kafka_config_generator.sh concatenated with the next: "export STRIMZI_NODEPORT_DEFAULT_ADDRESS=...".

```sh
$ kubectl get pods -n kafka
NAME                                        READY   STATUS    RESTARTS   AGE
elkafka-kafka-0                             2/2     Running   0          82m
elkafka-kafka-1                             2/2     Running   0          82m
elkafka-kafka-2                             1/2     Error     4          2m4s
elkafka-zookeeper-0                         1/1     Running   0          82m
elkafka-zookeeper-1                         1/1     Running   0          82m
elkafka-zookeeper-2                         1/1     Running   0          82m
strimzi-cluster-operator-6cf9c8df67-9xffq   1/1     Running   0          3h7m
```

**To Reproduce**

1. Pull/tag/push latest images (Sep 30, 2020):
    - docker.io/strimzi/kafka:latest-kafka-2.5.0
    - docker.io/strimzi/operator:latest
    - docker.io/strimzi/kafka-bridge:0.18.0
    - docker.io/strimzi/jmxtrans:latest

2. Preparation and successful launch of a single namespace operator using yaml script, according to the instructions: https://strimzi.io/docs/operators/master/deploying.html
    kubectl apply -f install/cluster-operator -n kafka
    
3. Preparation of a "pesrsistent" Kafka yaml script and its application:
    kubectl apply -f kafka_start.yaml -n kafka

4. See error:
    - 3 Zookeeper nodes successfully started (0 restarts)
    - 2 Kafka brokers running (0 restarts, no errors in logs)
    - 1 Kafka broker failed with the following message:
```log
      2020-09-30 11:29:52,601 INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util) [main] 
      2020-09-30 11:29:52,613 ERROR Exiting Kafka due to fatal exception (kafka.Kafka$) [main] 
      java.lang.IllegalArgumentException: Error creating broker listeners from 'REPLICATION-9091://elkafka-kafka-2.elkafka-kafka-brokers.kafka.svc:9091,PLAIN-9092://elkafka-kafka-2.elkafka-kafka-brokers.kafka.svc:9092,TLS-9093://elkafka-kafka-2.elkafka-kafka-brokers.kafka.svc:9093,EXTERNAL-9094://export STRIMZI_NODEPORT_DEFAULT_ADDRESS=10.252.144.195': Unable to parse EXTERNAL-9094://export STRIMZI_NODEPORT_DEFAULT_ADDRESS=10.252.144.195 to a broker endpoint 
        at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:266) 
        at kafka.server.KafkaConfig.advertisedListeners(KafkaConfig.scala:1621) 
        at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1696) 
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1674) 
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1238) 
        at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1218) 
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:34) 
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:29) 
        at kafka.Kafka$.main(Kafka.scala:68) 
        at kafka.Kafka.main(Kafka.scala) 
      Caused by: org.apache.kafka.common.KafkaException: Unable to parse EXTERNAL-9094://export STRIMZI_NODEPORT_DEFAULT_ADDRESS=10.252.144.195 to a broker endpoint 
        at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:57) 
        at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$6(CoreUtils.scala:263) 
        at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238) 
        at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36) 
        at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33) 
        at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38) 
        at scala.collection.TraversableLike.map(TraversableLike.scala:238) 
        at scala.collection.TraversableLike.map$(TraversableLike.scala:231) 
        at scala.collection.AbstractTraversable.map(Traversable.scala:108) 
        at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:263) 
        ... 9 more 
```

**Environment:**
 - Strimzi version: [0.19.0]
 - Installation method: [YAML]
 - Kubernetes cluster: [Kubernetes 1.16.9]
 - Infrastructure: [Rancher v 2.3.7]

**YAML files and logs**

_**kafka_start.yaml:**_

```yml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: elkafka
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: true
        authentication:
          type: tls
        overrides:
          bootstrap:
            nodePort: 30144
          brokers:
            - broker: 0
              nodePort: 30145
            - broker: 1
              nodePort: 30146
            - broker: 2
              nodePort: 30147
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.5"
    storage:
      type: persistent-claim
      size: 200Gi
      deleteClaim: false
      class: local-storage-logs
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
      class: local-storage-logs
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

_**elkafka-kafka-2 log:**_

```sh
+ ./kafka_pre_start.sh 
Waiting for the TLS sidecar to get ready 
TLS sidecar should be ready 
++ hostname 
++ awk -F- '{print $NF}' 
+ STRIMZI_BROKER_ID=2 
+ export STRIMZI_BROKER_ID 
+ echo STRIMZI_BROKER_ID=2 
STRIMZI_BROKER_ID=2 
+ export GC_LOG_ENABLED=false 
+ GC_LOG_ENABLED=false 
+ '[' -z '' ']' 
+ export KAFKA_LOG4J_OPTS=-Dlog4j.configuration=file:/opt/kafka/custom-config/log4j.properties 
+ KAFKA_LOG4J_OPTS=-Dlog4j.configuration=file:/opt/kafka/custom-config/log4j.properties 
+ rm -f /var/opt/kafka/kafka-ready /var/opt/kafka/zk-connected 
++ ls /opt/kafka/libs/kafka-agent.jar 
+ KAFKA_OPTS=' -javaagent:/opt/kafka/libs/kafka-agent.jar=/var/opt/kafka/kafka-ready:/var/opt/kafka/zk-connected' 
+ export KAFKA_OPTS 
+ '[' '' = true ']' 
+ '[' -n '' ']' 
+ KAFKA_OPTS=' -javaagent:/opt/kafka/libs/kafka-agent.jar=/var/opt/kafka/kafka-ready:/var/opt/kafka/zk-connected ' 
+ '[' false = true ']' 
+ export LOG_DIR=/opt/kafka 
+ LOG_DIR=/opt/kafka 
++ tr -dc _A-Z-a-z-0-9 
++ head -c32 
+ CERTS_STORE_PASSWORD=[-hidden-] 
+ export CERTS_STORE_PASSWORD 
+ mkdir -p /tmp/kafka 
+ ./kafka_tls_prepare_certificates.sh 
Preparing truststore for replication listener 
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/kafka/cluster.truststore.p12 with alias ca 
Certificate was added to keystore 
Preparing truststore for replication listener is complete 
Looking for the right CA 
Found the right CA: /opt/kafka/cluster-ca-certs/ca.crt 
Preparing keystore for replication and clienttls listener 
Preparing keystore for replication and clienttls listener is complete 
Preparing truststore for clienttls listener 
Adding /opt/kafka/client-ca-certs/ca.crt to truststore /tmp/kafka/clients.truststore.p12 with alias ca 
Certificate was added to keystore 
Preparing truststore for clienttls listener is complete 
+ echo 'Starting Kafka with configuration:' 
Starting Kafka with configuration: 
+ ./kafka_config_generator.sh 
+ tee /tmp/strimzi.properties 
+ sed -e 's/sasl.jaas.config=.*/sasl.jaas.config=[hidden]/g' -e 's/password=.*/password=[hidden]/g' 
############################## 
############################## 
# This file is automatically generated by the Strimzi Cluster Operator 
# Any changes to this file will be ignored and overwritten! 
############################## 
############################## 
 
########## 
# Broker ID 
########## 
broker.id=2 
 
########## 
# Zookeeper 
########## 
zookeeper.connect=localhost:2181 
 
########## 
# Kafka message logs configuration 
########## 
log.dirs=/var/lib/kafka/data/kafka-log2 
 
########## 
# Replication listener 
########## 
listener.name.replication-9091.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12 
listener.name.replication-9091.ssl.keystore.password=[hidden] 
listener.name.replication-9091.ssl.keystore.type=PKCS12 
listener.name.replication-9091.ssl.truststore.location=/tmp/kafka/cluster.truststore.p12 
listener.name.replication-9091.ssl.truststore.password=[hidden] 
listener.name.replication-9091.ssl.truststore.type=PKCS12 
listener.name.replication-9091.ssl.client.auth=required 
 
+ echo '' 
########## 
+ '[' -z -Xms128M ']' 
# Plain listener 
########## 
 
########## 
# TLS listener 
########## 
listener.name.tls-9093.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12 
listener.name.tls-9093.ssl.keystore.password=[hidden] 
listener.name.tls-9093.ssl.keystore.type=PKCS12 
 
########## 
# External listener 
########## 
listener.name.external-9094.ssl.client.auth=required 
+ . ./set_kafka_gc_options.sh 
listener.name.external-9094.ssl.truststore.location=/tmp/kafka/clients.truststore.p12 
listener.name.external-9094.ssl.truststore.password=[hidden] 
listener.name.external-9094.ssl.truststore.type=PKCS12 
 
listener.name.external-9094.ssl.keystore.location=/tmp/kafka/cluster.keystore.p12 
listener.name.external-9094.ssl.keystore.password=[hidden] 
listener.name.external-9094.ssl.keystore.type=PKCS12 
 
########## 
# Common listener configuration 
########## 
listeners=REPLICATION-9091://0.0.0.0:9091,PLAIN-9092://0.0.0.0:9092,TLS-9093://0.0.0.0:9093,EXTERNAL-9094://0.0.0.0:9094 
advertised.listeners=REPLICATION-9091://elkafka-kafka-2.elkafka-kafka-brokers.kafka.svc:9091,PLAIN-9092://elkafka-kafka-2.elkafka-kafka-brokers.kafka.svc:9092,TLS-9093://elkafka-kafka-2.elkafka-kafka-brokers.kafka.svc:9093,EXTERNAL-9094://export STRIMZI_NODEPORT_DEFAULT_ADDRESS=10.252.144.195 
export STRIMZI_NODEPORT_EXTERNALIP_ADDRESS=10.252.144.195 
export STRIMZI_NODEPORT_EXTERNALDNS_ADDRESS=10.252.144.195 
export STRIMZI_NODEPORT_INTERNALIP_ADDRESS=10.252.144.195 
export STRIMZI_NODEPORT_INTERNALDNS_ADDRESS=10.252.144.195 
export STRIMZI_NODEPORT_HOSTNAME_ADDRESS=srv24246zd-kvm:30147 
listener.security.protocol.map=REPLICATION-9091:SSL,PLAIN-9092:PLAINTEXT,TLS-9093:SSL,EXTERNAL-9094:SSL 
inter.broker.listener.name=REPLICATION-9091 
sasl.enabled.mechanisms= 
ssl.secure.random.implementation=SHA1PRNG 
ssl.endpoint.identification.algorithm=HTTPS 
 
########## 
# User provided configuration 
########## 
log.message.format.version=2.5 
offsets.topic.replication.factor=3 
transaction.state.log.min.isr=2 
transaction.state.log.replication.factor=3 
++ set -e 
++ '[' false == true ']' 
++ export 'KAFKA_GC_LOG_OPTS= ' 
++ KAFKA_GC_LOG_OPTS=' ' 
++ export GC_LOG_ENABLED=false 
++ GC_LOG_ENABLED=false 
+ exec /usr/bin/tini -w -e 143 -- /opt/kafka/bin/kafka-server-start.sh /tmp/strimzi.properties 
2020-09-30 13:28:34,310 INFO Registered kafka:type=kafka.Log4jController MBean (kafka.utils.Log4jControllerRegistration$) [main] 
2020-09-30 13:28:34,743 INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util) [main] 
2020-09-30 13:28:34,755 ERROR Exiting Kafka due to fatal exception (kafka.Kafka$) [main] 
java.lang.IllegalArgumentException: Error creating broker listeners from 'REPLICATION-9091://elkafka-kafka-2.elkafka-kafka-brokers.kafka.svc:9091,PLAIN-9092://elkafka-kafka-2.elkafka-kafka-brokers.kafka.svc:9092,TLS-9093://elkafka-kafka-2.elkafka-kafka-brokers.kafka.svc:9093,EXTERNAL-9094://export STRIMZI_NODEPORT_DEFAULT_ADDRESS=10.252.144.195': Unable to parse EXTERNAL-9094://export STRIMZI_NODEPORT_DEFAULT_ADDRESS=10.252.144.195 to a broker endpoint 
	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:266) 
	at kafka.server.KafkaConfig.advertisedListeners(KafkaConfig.scala:1621) 
	at kafka.server.KafkaConfig.validateValues(KafkaConfig.scala:1696) 
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1674) 
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1238) 
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1218) 
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:34) 
	at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.scala:29) 
	at kafka.Kafka$.main(Kafka.scala:68) 
	at kafka.Kafka.main(Kafka.scala) 
Caused by: org.apache.kafka.common.KafkaException: Unable to parse EXTERNAL-9094://export STRIMZI_NODEPORT_DEFAULT_ADDRESS=10.252.144.195 to a broker endpoint 
	at kafka.cluster.EndPoint$.createEndPoint(EndPoint.scala:57) 
	at kafka.utils.CoreUtils$.$anonfun$listenerListToEndPoints$6(CoreUtils.scala:263) 
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238) 
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36) 
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33) 
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38) 
	at scala.collection.TraversableLike.map(TraversableLike.scala:238) 
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231) 
	at scala.collection.AbstractTraversable.map(Traversable.scala:108) 
	at kafka.utils.CoreUtils$.listenerListToEndPoints(CoreUtils.scala:263) 
	... 9 more 
```

**Comment by scholzj** [comment]
It doesn't reproduce in my environment when I use the same CR as you use. Can you make sure that you have all the same images on all nodes? With the master images which are changing very often it is easy to have somewhere some stale image. If you think you are using the latest images everywhere, can you share the content of the `elkafka-kafka-config` config map which contains the configuration and the YAML of the Kafka pods / StatefulSets?

**Comment by domanq** [comment]
Thanks a lot. Surely this was the problem you write about. For some reason, Harbour was sharing images that were previously completely removed.
I downloaded, tagged and pushed the current versions of the images. I used Kafka 2.6.0. The init phase completed successfully, but now I have the following error on every Kafka node, even though I have allocated quite a lot of resources:

```log
2020-10-05 11:47:36,197 INFO Starting the log cleaner (kafka.log.LogCleaner) [main]
2020-10-05 11:47:36,257 ERROR [KafkaServer id=0] Fatal error during KafkaServer startup. Prepare to shutdown (kafka.server.KafkaServer) [main]
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:61)
	at java.base/java.nio.ByteBuffer.allocate(ByteBuffer.java:348)
	at kafka.log.SkimpyOffsetMap.<init>(OffsetMap.scala:45)
	at kafka.log.LogCleaner$CleanerThread.<init>(LogCleaner.scala:292)
	at kafka.log.LogCleaner.$anonfun$startup$2(LogCleaner.scala:155)
	at kafka.log.LogCleaner.startup(LogCleaner.scala:154)
	at kafka.log.LogManager.startup(LogManager.scala:436)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:274)
	at kafka.server.KafkaServerStartable.startup(KafkaServerStartable.scala:44)
	at kafka.Kafka$.main(Kafka.scala:82)
	at kafka.Kafka.main(Kafka.scala)
2020-10-05 11:47:36,260 INFO [KafkaServer id=0] shutting down (kafka.server.KafkaServer) [main]
```

**Comment by scholzj** [comment]
Is that still the the same Kafka CR as you shared on the beginning?

**Comment by domanq** [comment]
I work in the same Rancher environment, but with the freshest images from today.

**Comment by domanq** [comment]
I pushed these images into Harbour:
```log
REPOSITORY             TAG                    IMAGE ID            CREATED             SIZE
strimzi/kafka          latest-kafka-2.6.0     d1234eec294e        6 hours ago         604MB
strimzi/jmxtrans       latest                 2bd67f69582c        6 hours ago         539MB
strimzi/operator       latest                 61cd84f5bf54        6 hours ago         480MB
strimzi/kafka-bridge   0.18.0                 2b4864132cf4        2 months ago        508MB
```

***kafka_start.yaml:***

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: elkafka
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: true
        authentication:
          type: tls
        overrides:
          bootstrap:
            nodePort: 30144
          brokers:
            - broker: 0
              nodePort: 30145
            - broker: 1
              nodePort: 30146
            - broker: 2
              nodePort: 30147
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.6"
    storage:
      type: persistent-claim
      size: 200Gi
      deleteClaim: false
      class: local-storage-logs
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
      class: local-storage-logs
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

**Comment by scholzj** [comment]
Well, the Kafka CR does not seem to configure any resources. So I think that is where you should start: https://strimzi.io/docs/operators/latest/full/using.html#assembly-resource-limits-and-requests-deployment-configuration-kafka ... configure the memory requests.

**Comment by domanq** [comment]
Thanks, I've just started on Kafka and Kubernetes, so there is still a lot to learn :)

In the previous approach, when I tried to update the parameters according to the documentation, I was getting errors (...in body must be of type object: "array") even though the yaml was syntactically correct. So now I have decided to remove the containers and start from scratch. Unfortunately or fortunately, all containers unexpectedly restarted after removing. Without any changes to the configuration finally they started up correctly:
```log
$ kubectl get pods -n kafka
NAME                                        READY   STATUS    RESTARTS   AGE
elkafka-entity-operator-799484fc9d-mw886    3/3     Running   0          41m
elkafka-kafka-0                             1/1     Running   0          43m
elkafka-kafka-1                             1/1     Running   0          43m
elkafka-kafka-2                             1/1     Running   1          43m
elkafka-zookeeper-0                         1/1     Running   1          43m
elkafka-zookeeper-1                         1/1     Running   0          43m
elkafka-zookeeper-2                         1/1     Running   0          43m
strimzi-cluster-operator-59f5f84596-krl2z   1/1     Running   0          44m
```

Our Kubernetes currently has tons of free resources, but I'll ultimately apply these parameters of course.

**Comment by scholzj** [comment]
Java doesn't run well without some boundaries. So setting the memory requests is important for the stability and you should definitely do it. You should also keep in mind that in case you do not set the resources, things such as LimitRange might set them to some defaults which can cause problems.

**Comment by domanq** [comment]
Referring to the configuration update issue, please give me a hint what I am doing wrong:
```shell
$ kubectl apply -f kafka.update.yaml -n kafka --dry-run
kafka.kafka.strimzi.io/elkafka configured (dry run)

$ kubectl apply -f kafka.update.yaml -n kafka
The Kafka "elkafka" is invalid: spec.kafka.listeners: Invalid value: "array": spec.kafka.listeners in body must be of type object: "array"
```

***kafka.update.yaml***

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: elkafka
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    resources:
      requests:
        memory: 64Gi
        cpu: "8"
      limits:
        memory: 64Gi
        cpu: "12"
    jvmOptions:
      -Xms: 8192m
      -Xmx: 8192m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap:
            nodePort: 30144
          brokers:
            - broker: 0
              nodePort: 30145
            - broker: 1
              nodePort: 30146
            - broker: 2
              nodePort: 30147
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.6"
    storage:
      type: persistent-claim
      size: 200Gi
      deleteClaim: false
      class: local-storage-logs
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 8Gi
        cpu: "2"
      limits:
        memory: 8Gi
        cpu: "2"
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
      class: local-storage-logs
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"

```

**Comment by domanq** [comment]
One more thing by the way. I noticed that the advertised.listeners contains an internal IP instead of an external one.

```shell
advertised.listeners = REPLICATION-9091://elkafka-kafka-0.elkafka-kafka-brokers.kafka.svc:9091,PLAIN-9092://elkafka-kafka-0.elkafka-kafka-brokers.kafka.svc:9092,TLS-9093://elkafka-kafka-0.elkafka-kafka-brokers.kafka.svc:9093,EXTERNAL-9094://10.252.144.194:30145
```

node information:

```yaml
...
customConfig": {
"address": "10.252.144.66",
"internalAddress": "10.252.144.194",
...
"externalIpAddress": "10.252.144.66",
...
```

**Comment by scholzj** [comment]
> Referring to the configuration update issue, please give me a hint what I am doing wrong:

I'm not sure why the `--dry-run` doesn't catch it. But you seem to have still some mixups in the versions of the different components. The `Kafka.spec.kafka.listeners` field is supported only in current master (will be released in 0.20.0). But the error seems to suggests some parts of your installation are still 0.19.0. In this case at least the CRD definitions. So maybe you should try to update the CRD definitions and see if it helps.

> One more thing by the way. I noticed that the advertised.listeners contains an internal IP instead of an external one.

I'm not sure where does the JSON snippet come from. The address in the advertised listeners is taken from the Kubernetes worker node status. Normally the following order of preference is used:
1) ExternalDNS
2) ExternalIP
3) Hostname
4) InternalDNS
5) InternalIP

Can you do `kubectl get nodes -o yaml` and share the output? That would tell me if the IP address corresponds to your node settings or if it is some bug. Thanks.

**Comment by domanq** [comment]
Thanks! You're right again :) 
Not all components were up to date. Now the cluster is booting up correctly. Updating also works fine.

Regardind the external address, I tried various options of preferredNodePortAddressType but none worked.
Here is the configuration of one of the nodes. Some data has been hidden for obvious reasions and replaced with "[...]".

```yaml
- apiVersion: v1
  kind: Node
  metadata:
    annotations:
      flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"[...]"}'
      flannel.alpha.coreos.com/backend-type: vxlan
      flannel.alpha.coreos.com/kube-subnet-manager: "true"
      flannel.alpha.coreos.com/public-ip: 10.252.144.67
      node.alpha.kubernetes.io/ttl: "0"
      projectcalico.org/IPv4IPIPTunnelAddr: 10.42.3.1
      rke.cattle.io/external-ip: 10.252.144.67
      rke.cattle.io/internal-ip: 10.252.144.195
      volumes.kubernetes.io/controller-managed-attach-detach: "true"
    creationTimestamp: "2020-07-19T19:03:36Z"
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      kubernetes.io/arch: amd64
      kubernetes.io/hostname: [...]d-kvm
      kubernetes.io/os: linux
      node-role.kubernetes.io/worker: "true"
    name: [...]d-kvm
    resourceVersion: "12769533"
    selfLink: /api/v1/nodes/[...]d-kvm
    uid: [...]
  spec:
    podCIDR: 10.42.3.0/24
    podCIDRs:
    - 10.42.3.0/24
  status:
    addresses:
    - address: 10.252.144.195
      type: InternalIP
    - address: [...]d-kvm
      type: Hostname
    allocatable:
      cpu: "80"
      ephemeral-storage: "309086649857"
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 790865244Ki
      pods: "110"
    capacity:
      cpu: "80"
      ephemeral-storage: 327520Mi
      hugepages-1Gi: "0"
      hugepages-2Mi: "0"
      memory: 790967644Ki
      pods: "110"
    conditions:
    - lastHeartbeatTime: "2020-10-09T11:09:10Z"
      lastTransitionTime: "2020-08-06T13:14:00Z"
      message: kubelet has sufficient memory available
      reason: KubeletHasSufficientMemory
      status: "False"
      type: MemoryPressure
    - lastHeartbeatTime: "2020-10-09T11:09:10Z"
      lastTransitionTime: "2020-08-06T13:14:00Z"
      message: kubelet has no disk pressure
      reason: KubeletHasNoDiskPressure
      status: "False"
      type: DiskPressure
    - lastHeartbeatTime: "2020-10-09T11:09:10Z"
      lastTransitionTime: "2020-08-06T13:14:00Z"
      message: kubelet has sufficient PID available
      reason: KubeletHasSufficientPID
      status: "False"
      type: PIDPressure
    - lastHeartbeatTime: "2020-10-09T11:09:10Z"
      lastTransitionTime: "2020-08-11T21:24:19Z"
      message: kubelet is posting ready status
      reason: KubeletReady
      status: "True"
      type: Ready
    daemonEndpoints:
      kubeletEndpoint:
        Port: 10250
    images:
    [...]
    nodeInfo:
      architecture: amd64
      bootID: [...]
      containerRuntimeVersion: docker://19.3.12
      kernelVersion: 3.10.0-1127.13.1.el7.x86_64
      kubeProxyVersion: v1.16.9
      kubeletVersion: v1.16.9
      machineID: [...]
      operatingSystem: linux
      osImage: CentOS Linux 7 (Core)
      systemUUID: [...]
```

**Comment by domanq** [comment]
Currently is:
```shell
$ kubectl get kafka elkafka -o=jsonpath='{.status.listeners[?(@.type=="external")].bootstrapServers}{"\n"}' -n kafka
10.252.144.195:30144
```
The expected IP value should be:
```shell
10.252.144.67
```

**Comment by scholzj** [comment]
Well, this is what the node reports as its address:

```
    addresses:
    - address: 10.252.144.195
      type: InternalIP
    - address: [...]d-kvm
      type: Hostname
```

So based on the priorities, the Hostname should be used by default and you can change to the InternalIP. You do not have the ExternalIP there so the operator has no place to read it from and will fallback to the other addresses. You could also try to configure the addresses manually by configuring the `advertisedHostname` (https://strimzi.io/docs/operators/master/full/using.html#type-GenericKafkaListenerConfigurationBroker-reference) which is a bit complicated since the pods might not be bound to a single worker node in most cases.

**Comment by domanq** [comment]
I will try this in the next step if I fail to get ExternalIP explicitly. 

But when a node does not report ExternalIP in the address list, with NodePort it would be nice to be able to indicate exactly which path the value should be retrieved from first. As in this case from one of:

```yaml
  metadata:
    annotations:
      [...]
      flannel.alpha.coreos.com/public-ip: 10.252.144.67
      [...]
      rke.cattle.io/external-ip: 10.252.144.67
```

e.g.:

```yaml
      - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: tls
        configuration:
          preferredNodePortAddressType: Custom
          bootstrap:
            nodePort: 30144
          brokers:
            - broker: 0
              nodePort: 30145
              nodePortAddressPath: "flannel.alpha.coreos.com/public-ip"
            [...]
```
