### ISSUE TITLE
[Question] How to get SASL_SSL with SCRAM on Kafka Connect

### ISSUE THREAD

**Issue by pcasaes** [strimzi/strimzi-kafka-operator#3730]
I've followed the documentation on how to setup from SCRAM but the security protocol get's set to SASL_PLAINTEXT

security.protocol = SASL_PLAINTEXT

Is there anyway to get it to be SASL_SSL?

For some context I'm trying to integrate with MSK using SASL SCRAM.
https://docs.aws.amazon.com/msk/latest/developerguide/msk-password.html

```
security.protocol=SASL_SSL
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="username" password="password";

```

**Comment by scholzj** [comment]
Yeah. You just configure TLS in .spec.tls and SASL auth in .spec.auth ...
and when they are both set, it enables SASL_SSL. Not at my desk right now,
but I can provide docs links and examples tomorrow.

**Comment by scholzj** [comment]
To add from tomorrow ... this example is using `SASL_SSL`: https://github.com/strimzi/strimzi-kafka-operator/blob/02edfdd9b0b78c1e5ffbc4c052da24c8c1bbf3f4/examples/security/scram-sha-512-auth/connect.yaml#L102

But MSK normally uses signed certificates so you do not need to provide the trusted certificate and can do just something like this:

```yaml
  tls:
    trustedCertificates: []
  authentication:
    type: scram-sha-512
    username: my-connect
    passwordSecret:
      secretName: my-connect
      password: password
```

**Comment by pcasaes** [comment]
Thank you! that did it.

Follow up question. Hot about for confluent cloud that uses PLAIN SASL with a signed certificate.

Would it be this?
```
  tls:
    trustedCertificates: []
  authentication:
    type: plain
    username: my-connect
    passwordSecret:
      secretName: my-connect
      password: password
```
