### ISSUE TITLE
Strimzi 0.19.0 Kafka Cluster on Openshift 4.4 error: java.io.IOException: Cannot run program “openssl”: error=11, Resource temporarily unavailable

### ISSUE THREAD

**Issue by kaganmersin** [strimzi/strimzi-kafka-operator#3766]
In the openshift 4.4 cluster Installed Operators page when I click Create Kafka button which is under the Kafka section I face error like below;

![resim](https://user-images.githubusercontent.com/46555755/95463377-58ca0d80-0981-11eb-9222-8962a30ab9f8.png)

I am trying to create kafka cluster with default yaml without edited as shown below;

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: dxl
spec:
  kafka:
    version: 2.5.0
    replicas: 3
    listeners:
      plain:
        authentiation:
          type: scram-sha-512
      tls:
        authentiation:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '2.5'
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator:
      reconciliationIntervalSeconds: 90
    userOperator:
      reconciliationIntervalSeconds: 120
```

There is no error in Event stream of Openshift. And no more info beyond of the condition section which I have attached above in Openshift. No resource creation also no entry in Event stream about kafka. I have check default yaml on other environment Openshift clusters with same version (4.4) and observed that they are working succesfully. But unsuccesful in one of the specific Openshif Cluster(4.4)

Is there anyone who can help about on it ? Thanks from now !
