### ISSUE TITLE
[Doc] storage class override for zookeeper nodes

### ISSUE THREAD

**Issue by szymek116** [strimzi/strimzi-kafka-operator#3782]
**Suggestion / Problem**
The docs doesn't mention whether it is possible to override storage class for zookeeper while it is in non intuitive way by adding override broker directive under zookeeper section of yaml (I think we don't use broker term for zookeeper). I imagine PR for this is rather low prio, but having a note in the documentation it can be achieved for zookeeper make sense.

here is the config I've tested:

```  
kafka:
...
    storage:
...
      overrides:
        - broker: 0
          class: dev-kafka-pv-node1-class
        - broker: 1
          class: dev-kafka-pv-node2-class
        - broker: 2
          class: dev-kafka-pv-node3-class
  zookeeper:
    replicas: 3
    storage:
...
      class: dev-zookeeper-pv-node1-class
      overrides:
        - broker: 0
          class: dev-zookeeper-pv-node1-class
        - broker: 1
          class: dev-zookeeper-pv-node2-class
        - broker: 2
          class: dev-zookeeper-pv-node3-class
```

**Documentation Link**
https://strimzi.io/docs/operators/latest/using.html#storage_class_overrides
https://strimzi.io/docs/operators/latest/using.html#assembly-zookeeper-node-configuration-deployment-configuration-kafka
