### ISSUE TITLE
[Question] I want to set infinite log retention hours

### ISSUE THREAD

**Issue by alok87** [strimzi/strimzi-kafka-operator#3800]
Do not have much data and want to retain whatever gets written in Kafka.

Changing the retention from `kubectl edit kafka` does not work.

Change made:
```
spec:
  kafka:
      config:
        log.message.format.version: "2.5"
        log.retention.hours: -1
```

Result after new pod came:
```
$ k exec -it k8s-kafka-0 /bin/sh
Defaulting container name to kafka.
Use 'kubectl describe pod/k8s-kafka-0 -n kafka' to see all of the containers in this pod.
sh-4.2$ grep retention /opt/kafka/config/*
/opt/kafka/config/server.properties:log.retention.hours=168
```

I also tried different values like 10, 167 etc.. did not work.

Please suggest.
