### ISSUE TITLE
[Bug] Custom, oauth and authz-keycloak related P12 truststore are not built correctly

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#3823]
While testing the latest RC1 I noticed that, if you specify a custom certificate for an external listener like the following example:

```yaml
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: openshift
        port: 9094
        type: route
        tls: true
        configuration:
          brokerCertChainAndKey:
            secretName: strimzi-letsencrypt-cert
            certificate: tls.crt
            key: tls.key  
```

The Kafka pod is crash-looping with following error:

```shell
2020-10-15 13:21:24,641 ERROR Modification time of key store could not be obtained: /tmp/kafka/custom-openshift-9094.keystore.p12 (org.apache.kafka.common.security.ssl.DefaultSslEngineFactory) [main]
java.nio.file.NoSuchFileException: /tmp/kafka/custom-openshift-9094.keystore.p12
```

The volume `/opt/kafka/certificates/custom-openshift-9094-certs` is mounted correctly and the certificate and the key should be there but the problem seems to be in the script in the Kafka image (kafka_tls_prepare_certificates.sh) generating the P12 truststores where hardcoded paths are used as for the previous format of listeners that were fixed (plain, tls, external) while now they can have different name and port.
Probably the same bug affects oauth and authz-keycloak related certificates generation.
