### ISSUE TITLE
[Doc] Prometheus alert example does not work

### ISSUE THREAD

**Issue by pantaoran** [strimzi/strimzi-kafka-operator#3824]
**Suggestion / Problem**
In the examples section you have suggested a few Prometheus Alerts, but I don't see how the alert named `ZookeeperContainerRestartedInTheLast5Minutes` could ever fulfill its condition expression.

The expression is as follows:
`count(count_over_time(container_last_seen{container="zookeeper"}[5m])) > 2 * count(container_last_seen{container="zookeeper",pod=~".+-zookeeper-[0-9]+"})`

I have observed these 2 queries and they seem to always move in lock-step (except one has double the value of the other of course). I don't see how there could ever be a situation where the left side could be bigger than the right side.

I don't have a suggestion for a fix since I don't really understand the idea of this alert in the first place.

**Documentation Link**
https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/metrics/prometheus-install/prometheus-rules.yaml

**Comment by stanlyDoge** [comment]
I do not remember exactly, but I think `container_last_seen` is just number of the zk containers currently running and `count_over_time` part counts every new occurence of the container. It is doubled by 2. So if we have 3 zk pods, obviously first part is 3, and if the cluster is healthy, the second part should be also 3. If the zk pods are rolled, left expression stays 3, but the right one is increased to 6 (after all pods are rolled).

**Comment by pantaoran** [comment]
That is not what I observe experimentally, can you verify that?

**Comment by stanlyDoge** [comment]
Oh. So you always see the same numbers on both sides?

**Comment by pantaoran** [comment]
Exactly (if you ignore the doubling in the formula).

**Comment by pantaoran** [comment]
And the same problem applies to the alert named `KafkaContainerRestartedInTheLast5Minutes`

**Comment by stanlyDoge** [comment]
So I tested this and I cannot se an issue :(
ZK after one rolling update:
![Snímek z 2020-10-19 15-36-13](https://user-images.githubusercontent.com/19408098/96458486-44a7cb00-1221-11eb-9399-3843e621b943.png)

ZK after two rolling updates:
![Snímek z 2020-10-19 15-38-26](https://user-images.githubusercontent.com/19408098/96458532-538e7d80-1221-11eb-8c7f-788b6ca5a66f.png)

**Comment by pantaoran** [comment]
Interesting. Thanks a lot for checking it!
I observe that I can also produce this outcome, but only when I extend the `5m` interval in the first query to `10m`. Not sure why that is though.
Anyway, in that case the issue can be closed I guess...

**Comment by pantaoran** [comment]
I imagine it must depend on how long the metric `container_last_seen` sticks around after the value stops changing.
![image](https://user-images.githubusercontent.com/7800702/96556056-d1ea2e80-12b8-11eb-99a6-ce2880084b9b.png)
In my case that seems to be about 5min, which would explain why the graphs move in lock-step when only looking back over the last 5min with the `count_over_time`.

**Comment by stanlyDoge** [comment]
I also tried to deploy metrics cluster on OCP 4.x and I hit the same issue as you had. Some fiddling with time intervals fixed it for me as well.

**Comment by pantaoran** [comment]
Yes I am also on OCP 4.5, and I also needed to slightly adjust the labels to even see results at all.
Now I'm going to increase the alert interval to 10min for us and that should be good enough.

**Comment by pantaoran** [comment]
One more thought: While I was able to see the condition fulfilled in Prometheus, I still couldn't get the alert to trigger.
I noticed that here:
https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/metrics/prometheus-install/prometheus-rules.yaml#L120
the condition must be fulfilled for at least 5min to trigger the alert. Can that actually happen when you're only looking back in time 5min? My guess would be no, and then the alert would still never fire.

**Comment by blezoray** [comment]
Hi, FYI, I use these rules expressions:
```
  - alert: Services_Strimzi_KafkaContainerRestartedInTheLast5Minutes_Critical
    expr: (increase(kube_pod_container_status_restarts_total{container="kafka"}[5m])) > 0
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: 'One or more Kafka containers restarted too often'
      description: 'One or more Kafka containers were restarted too often within the last 5 minutes'
  - alert: Services_Strimzi_TopicOperatorContainerRestartedInTheLast5Minutes_Critical
    expr: (increase(kube_pod_container_status_restarts_total{container="topic-operator"}[5m])) > 0
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: 'Container topic-operator in Entity Operator pod down or in CrashLookBackOff status'
      description: 'Container topic-operator in Entity Operator pod has been or in CrashLookBackOff status for 5 minutes'
  - alert: Services_Strimzi_UserOperatorContainerRestartedInTheLast5Minutes_Critical
    expr: (increase(kube_pod_container_status_restarts_total{container="user-operator"}[5m])) > 0
    for: 3m
    labels:
      severity: critical
    annotations:
      summary: 'Container user-operator in Entity Operator pod down or in CrashLookBackOff status'
      description: 'Container user-operator in Entity Operator pod have been down or in CrashLookBackOff status for 5 minutes'
```
