### ISSUE TITLE
[Bug] Cannot use Strimzi on cloud because cannot specify custom annotations and labels on PersistentVolumeClaim of kafka/zookeeper 

### ISSUE THREAD

**Issue by fzyzcjy** [strimzi/strimzi-kafka-operator#3870]
**Describe the bug**
The cloud I use *forces* me to follow the following pattern in order to create a PVC:
```
...
kind: PersistentVolumeClaim
metadata:
  annotations:
    everest.io/disk-volume-type: SAS # MUST!!
  labels:
    failure-domain.beta.kubernetes.io/region: some-name-here #MUST!
    failure-domain.beta.kubernetes.io/zone: some-name-here #MUST!
spec:
  storageClassName: csi-disk
...
```

However, I cannot find a way to specify this metadata (annotations and labels). Thus, I cannot use it in the cloud provider :( IMHO many cloud providers require such things as annotations and labels, so I wonder how to do it?

Thanks very much!

**To Reproduce**
N/A

**Expected behavior**
N/A

**Environment (please complete the following information):**
 - Strimzi version: latest
 - Installation method: helm
 - Kubernetes cluster: n/a
 - Infrastructure: cloud

**YAML files and logs**
N/A

**Additional context**
N/A
