### ISSUE TITLE
Use of useServiceDnsDomain ?

### ISSUE THREAD

**Issue by savind** [strimzi/strimzi-kafka-operator#3898]
For some reason, my windows node  in the cluster can only resolve fully qualified dns names.
I used useServiceDnsDomain: true, in my internal listener
expecting that the bootstrap service will now provide fqdn names to the client.
But I'm still getting this error on the client.

> Error: GroupCoordinator: Failed to resolve 'tt-kafka-kafka-2.tt-kafka-kafka-brokers.shared.svc:9092': No such host is known.

Client BootstrapServers used: tt-kafka-kafka-bootstrap.shared.svc.cluster.local

Is my expectation correct? If no, what does useServiceDnsDomain do?

**Comment by scholzj** [comment]
You can use the `useServiceDnsDomain` option in listener configuration: https://strimzi.io/docs/operators/latest/full/using.html#type-GenericKafkaListenerConfiguration-reference

I.e. something like this:
```yaml
listeners:
  #...
  - name: plain
    port: 9092
    type: internal
    tls: false
    configuration:
      useServiceDnsDomain: true
      # ...
```

**Comment by savind** [comment]
@scholzj Two points: 
a. the document has a sample yaml, where useServiceDnsDomain is directly below listeners, like this
```
listeners: 
      - name: plain 
        port: 9092 
        type: internal 
        tls: false 
        useServiceDnsDomain: true 
```
I used the property like this. I will try your suggestion and post the result.
b. Am I right to understand that when this flag is true, the client will be provided with fully qualified dns name?

I have explained what I did in this question
https://stackoverflow.com/q/64599270/4618170?sem=2
