### ISSUE TITLE
[Doc] Update resource values in Cruise Control docs example with more realistic values

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#3904]
**Suggestion / Problem**
As a Java application, Cruise Control can consume a good amount of resources, however the resource `request` and `limits` values listed in the yaml example in the `Deploying Cruise Control` docs [1] are quite low. We should update these values with more realistic resource values so users don't starve their Cruise Control instances!
```
spec:
  cruiseControl:
    resources: (3)
      requests:
        cpu: <UPDATE HERE>
        memory: <UPDATE HERE>
      limits:
        cpu: <UPDATE HERE>
        memory: <UPDATE HERE>
```

**Documentation Link**
[1] https://github.com/strimzi/strimzi-kafka-operator/blob/c836a4ed8cc3e44a544a288fa172a3d255a85006/documentation/modules/cruise-control/proc-deploying-cruise-control.adoc
