### ISSUE TITLE
[Question] Kafka Bridge Support for kubernetes v1.7

### ISSUE THREAD

**Issue by shalin-hudda** [strimzi/strimzi-kafka-operator#3915]
I am currently trying to deploy strimzi cluster operator v0.20.0 on openshift platform v3.7 and kubernetes v1.7. I am doing this so that I can use the kafka-bridge to provide REST support for HTTP clients.

However, strimzi v0.20.0 requires kubernetes v1.11 and above. I am looking for a strimzi version which has kafka-bridge and also works with kubernetes v1.7.

**Comment by scholzj** [comment]
I'm afraid there might not be such version. The Bridge is actually a relatively simple deployment - so maybe you can deploy it there manually.

**Comment by shalin-hudda** [comment]
Thank you. 

I am still new to kubernetes so could you please specify what you mean by deploy it manually? Do you mean create a CRD for Kafka Bridge?

**Comment by scholzj** [comment]
Basically, writing a deployment YAML which will use the bridge image. 

Possibly, you could for example run Minikube where you deploy it with operator and copy the Deployment YAML.

**Comment by shalin-hudda** [comment]
Something like this?
```yml
apiVersion: apps/v1alpha1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: test
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: strimzi/operator:latest
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: strimzi/kafka-bridge:0.19.0
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
```

**Comment by scholzj** [comment]
Exactly. Just for the bridge and not for the operator.

**Comment by shalin-hudda** [comment]
Thank you Jakub. I was able to deploy the bridge. Just for reference below is the deployment I used.
```yml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: strimzi-kafka-bridge
  namespace: test
  labels:
    app: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strimzi
  template:
    metadata:
      labels:
        app: strimzi
    spec:
      volumes:
        - name: kafka-bridge-config-volume
          configMap:
            name: strimzi-kafka-bridge
      containers:
        - name: strimzi-kafka-bridge
          image: 'strimzi/kafka-bridge:0.19.0'
          volumeMounts:
          - name: kafka-bridge-config-volume
            mountPath: /opt/strimzi/config/
          args:
            - bin/kafka_bridge_run.sh
            - '--config-file'
            - config/application.properties
          ports:
            - containerPort: 8080
              name: http
  strategy:
    type: Recreate
```
