### ISSUE TITLE
Allow use of a CRD to express the desired configuration of Kafka and Kafka Connect clusters

### ISSUE THREAD

**Issue by tombentley** [strimzi/strimzi-kafka-operator#392]
## Benefits of using CRDs

Using a CRD would have a number of benefits:

* A hierarchical representation would allow a more natural way to group related configurations together.
* Since Kubernetes v1.9 there is support for some [server-side validation](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#validation). No validation is possible with ConfigMaps.
* Having a JSON schema for the CRD also provides documentation value.
* A separate resource kind allows RBAC to be configured to allow creation of CMs that do not represent clusters, while not allowing creation of clusters. This is not possible using ConfigMaps alone.

## Straw man

Here's a possible example of how a resource representing a Kafka cluster might look:

```yaml
apiVersion: cluster-controller.strimzi.io/v1alpha1
kind: Kafka
metadata:
  name: strimzi-ephemeral
kafka:
  replicas: 3
  image: "strimzi/kafka:latest"
  resources:
    limits:
      memory: "5Gi"
  livenessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 1
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 4
  javaOptions:
    -Xmx: "4G"
  storage:
    type: persistent-claim
    size: 500Gi
  config:
    min.insync.replicas: 3
  metrics: {
      "lowercaseOutputName": true,
      "rules": [
          {
            "pattern": "kafka.server<type=(.+), name=(.+)PerSec\\w*><>Count",
            "name": "kafka_server_$1_$2_total"
          },
          {
            "pattern": "kafka.server<type=(.+), name=(.+)PerSec\\w*, topic=(.+)><>Count",
            "name": "kafka_server_$1_$2_total",
            "labels":
            {
              "topic": "$3"
            }
          }
      ]
    }
zookeeper:
  replicas: 3
  image: "strimzi/zookeeper:latest"
  resources:
    limits:
      memory: "512Mi"
  livenessProbe:
    initialDelaySeconds: 5
    timeoutSeconds: 1
  readinessProbe:
    initialDelaySeconds: 10
    timeoutSeconds: 4
  javaOptions:
    -Xmx: "512Mi"
    -Xms: "512Mi"
  storage:
    type: ephemeral
  metrics: {}
topicController:
  watchedNamespace: my-ns
```

Here's the corresponding CRD:

```yaml

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kafkas.cluster-controller.strimzi.io
spec:
  group: cluster-controller.strimzi.io
  version: v1alpha1
  names:
    kind: Kafka
    plural: kafkas
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        topicController:
          properties:
            image:
              description: "The docker image for the topic controller pod"
              example: "strimzi/topic-controller:latest"
              type: string
            watchedNamespace:
              description: "The namespace the TC should watch"
              type: string
            reconciliationIntervalMs:
              type: integer
              minimum: 1
            zookeeperSessionTimeoutMs:
              type: integer
              minimum: 1
            topicMetadataMaxAttempts:
              type: integer
              minimum: 1
        zookeeper:
          required:
            - replicas
          properties:
              replicas:
                description: "The number of Zookeeper brokers in the ensemble."
                type: integer
                minimum: 1
              image:
                description: "The docker image for Zookeeper pods."
                example: "strimzi/zookeeper:latest"
                type: string
              resources:
                description: "Constraints of container resource usage."
                properties:
                  limits:
                    properties:
                      memory:
                        type: string
                        pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                      cpu:
                        type: string
                        pattern: "[0-9]+m?"
                  requests:
                    properties:
                      memory:
                        type: string
                        pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                      cpu:
                        type: string
                        pattern: "[0-9]+m?"
              livenessProbe:
                properties:
                  initialDelaySeconds:
                    type: integer
                    minimum: 0
                  timeoutSeconds:
                    type: integer
                    minimum: 0
              readinessProbe:
                properties:
                  initialDelaySeconds:
                    type: integer
                    minimum: 0
                  timeoutSeconds:
                    type: integer
                    minimum: 0
              javaOptions:
                description: "Options to be passed to the JVM running Zookeeper."
                properties:
                  -Xmx:
                    type: string
                    pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                  -Xms:
                    type: string
                    pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
        kafka:
          required:
          - replicas
          properties:
            replicas:
              description: "The number of Kafka brokers in the cluster."
              type: integer
              minimum: 1
            image:
              description: "The docker image for Kafka pods."
              example: "strimzi/kafka:latest"
              type: string
            resources:
              description: "Constraints of container resource usage."
              properties:
                limits:
                  properties:
                    memory:
                      type: string
                      pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                    cpu:
                      type: string
                      pattern: "[0-9]+m?"
                requests:
                  properties:
                    memory:
                      type: string
                      pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                    cpu:
                      type: string
                      pattern: "[0-9]+m?"
            livenessProbe:
              properties:
                initialDelaySeconds:
                  type: integer
                  minimum: 0
                timeoutSeconds:
                  type: integer
                  minimum: 0
            readinessProbe:
              properties:
                initialDelaySeconds:
                  type: integer
                  minimum: 0
                timeoutSeconds:
                  type: integer
                  minimum: 0
            javaOptions:
              description: "Options to be passed to the JVM running Kafka."
              properties:
                -Xmx:
                  type: string
                  pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                -Xms:
                  type: string
                  pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
            kafkaConfig:
              description: "The Kafka configuration."
              type: object
            storage:
              description: "Configuration of how the Kafka logs are stored."
              properties:
                type:
                  type: string
                  enum: ["ephemeral", "persistent-claim"]
                size:
                  description: "When type=persistent-claim, the size of the claim"
                  type: string
                  pattern: "[0-9]+([kKmMgGtTpPeE]i?)?$"
                class:
                  description: "When type=persistent-claim, the storage class"
                  type: string
                selector:
                  description: "When type=persistent-claim, the selector for the specific volume."
                  properties:
                    matchLabels:
                      type: object
                      #additionalProperties:
                      #  type: string
                deleteClaim:
                  description: "When type=persistent-claim, whether the claim should be deleted when the pod is deleted."
                  type: boolean
            metrics:
              description: "The metrics config map"
              type: object
```

## Retain support for ConfigMaps

For use cases where people want to use strimzi, but lack the necessary cluster permissions to create CRDs we would need to continue supporting configuration via config maps. 

This creates a few extra problems:

* We will need to keep the CM and CRD representations in sync. This is mainly an issue wrt maintenance burden in code and documentation. Having a systematic way of mapping between the two representations at the syntactic level would help alleviate this. Acheiving this will require changes from how the cluster CMs look today, in order to fully realise the benefits of using CRDs. 
* Being a K8s API, CRDs will have an explicit version, which will allow us to evolve the representation over time. ConfigMaps API version does the same thing, but that's not our version to change. So are a follow-on from the first point, we will also need a way of versioning the representation of cluster configmaps. We could use a label for this.
* What should the CC do when a ConfigMap and a Kafka resource with the same name coexist? The easiest thing would be for the CC to have a configurable mode, so as far as it was concerned there was no coexistence. This would make migrating from CM to Kafka resources a big-bang change. A more complex alternative would be a config option for which kind of resource should take priority.
