### ISSUE TITLE
[Bug] Failed to connect to Zookeeper - Connection was not ready in 300000 ms using a different DNS domain

### ISSUE THREAD

**Issue by pierDipi** [strimzi/strimzi-kafka-operator#3945]
**Describe the bug**

Zookeeper pods can't talk to each other when a different domain is used.

**To Reproduce**
1. `kind create cluster --config kind.yaml` where `kind.yaml` is the following:

```yaml
          apiVersion: kind.x-k8s.io/v1alpha4
          kind: Cluster
          # This is needed in order to support projected volumes with service account tokens.
          # See: https://kubernetes.slack.com/archives/CEKK1KTN2/p1600268272383600
          kubeadmConfigPatches:
            - |
              apiVersion: kubeadm.k8s.io/v1beta2
              kind: ClusterConfiguration
              metadata:
                name: config
              apiServer:
                extraArgs:
                  "service-account-issuer": "kubernetes.default.svc"
                  "service-account-signing-key-file": "/etc/kubernetes/pki/sa.key"
              networking:
                dnsDomain: c359206310.local 
          nodes:
          - role: control-plane
          - role: worker
```
Note: `dnsDomain` is changed, it works fine without that configuration.

2. Create namespace `kubectl create namespace kafka --dry-run -o yaml | kubectl apply -f -`

3. Deploy Operator

```bash
curl -L "https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.20.0/strimzi-cluster-operator-${strimzi_version}.yaml" |
  sed 's/namespace: .*/namespace: kafka/' |
  kubectl -n kafka apply -f 
```

4. `kubectl -n kafka apply -f kafka-ephemeral.yaml` where `kafka-ephemeral.yaml` is:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.6"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

**Expected behavior**

**Environment (please complete the following information):**
 - Strimzi version: [e.g. 0.20, 0.19]
 - Installation method: YAMLs
 - Kubernetes cluster: Kubernetes 1.19, Kubernetes 1.18
 - Infrastructure: KinD

**YAML files and logs**

- [report-12-11-2020_10-01-08.zip](https://github.com/strimzi/strimzi-kafka-operator/files/5529382/report-12-11-2020_10-01-08.zip)

- Output of `kubectl describe kafka -n kafka my-cluster`:
```
$ kubectl describe kafka -n kafka my-cluster 
Name:         my-cluster
Namespace:    kafka
Labels:       <none>
Annotations:  <none>
API Version:  kafka.strimzi.io/v1beta1
Kind:         Kafka
Metadata:
  Creation Timestamp:  2020-11-12T08:40:05Z
  Generation:          1
  Managed Fields:
    API Version:  kafka.strimzi.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        f:entityOperator:
          f:topicOperator:
            f:reconciliationIntervalSeconds:
            f:topicMetadataMaxAttempts:
            f:zookeeperSessionTimeoutSeconds:
          f:userOperator:
            f:reconciliationIntervalSeconds:
            f:zookeeperSessionTimeoutSeconds:
      f:status:
        .:
        f:conditions:
        f:observedGeneration:
    Manager:         okhttp
    Operation:       Update
    Time:            2020-11-12T08:48:17Z
  Resource Version:  2221
  Self Link:         /apis/kafka.strimzi.io/v1beta1/namespaces/kafka/kafkas/my-cluster
  UID:               34ba6d75-e73c-47da-8fda-8df987806d68
Spec:
  Entity Operator:
    Topic Operator:
    User Operator:
  Kafka:
    Config:
      log.message.format.version:                2.6
      offsets.topic.replication.factor:          3
      transaction.state.log.min.isr:             2
      transaction.state.log.replication.factor:  3
    Listeners:
      Plain:
      Tls:
    Replicas:  3
    Storage:
      Type:   ephemeral
    Version:  2.6.0
  Zookeeper:
    Replicas:  3
    Storage:
      Type:  ephemeral
Status:
  Conditions:
    Last Transition Time:  2020-11-12T08:48:17+0000
    Message:               Failed to connect to Zookeeper my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.kafka.svc:2181,my-cluster-zookeeper-1.my-cluster-zookeeper-nodes.kafka.svc:2181,my-cluster-zookeeper-2.my-cluster-zookeeper-nodes.kafka.svc:2181. Connection was not ready in 300000 ms.
    Reason:                ZookeeperScalingException
    Status:                True
    Type:                  NotReady
    Last Transition Time:  2020-11-12T08:41:34.844760Z
    Message:               In API version kafka.strimzi.io/v1beta1 the object kafkaListeners at path spec.kafka.listeners.kafkaListeners has been deprecated. This object has been replaced with GenericKafkaListener.
    Reason:                DeprecatedObjects
    Status:                True
    Type:                  Warning
  Observed Generation:     1
Events:                    <none>
```

**Additional context**

- https://github.com/knative-sandbox/eventing-kafka-broker/pull/364/checks?check_run_id=1389155583

- Deploy `dnsutils.yaml` where `dnsutils.yaml` is:

```
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
  namespace: default
spec:
  containers:
  - name: dnsutils
    image: gcr.io/kubernetes-e2e-test-images/dnsutils:1.3
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
```

Output:
```
$ kubectl exec dnsutils -- cat /etc/resolv.conf
search default.svc.c359206310.local svc.c359206310.local c359206310.local
nameserver 10.96.0.10
options ndots:5
```
