### ISSUE TITLE
using helm hook to create topics causing issues during helm upgrade

### ISSUE THREAD

**Issue by dineshudayakumar** [strimzi/strimzi-kafka-operator#3946]
Hi,

We are using topic operator alone in our environment and we are using helm pre-install & pre-upgrade hook to create the topics. When we do helm upgrade or re-install of the chart intermittently some topics getting deleted from Kafka

This is the pre-hook we are using
```
{{- $root := . -}}
{{- range .Values.kafka.topics }}
---
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: {{ .name  }}
  labels:
    operator.io/kind: topic
  namespace: "{{ tpl $root.Values.kafka.namespace $root }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  topicName: {{ .name }}
  partitions: {{ .partitions }}
  replicas: {{ .replicas }}
{{- with .config }}
  config:
{{ toYaml . | indent 4 }}
{{- end }}
{{- end }}
```
And we have the topic config in values.yaml as below
```
kafka:
  namespace: avaya-kafka
  topics:
    flow1:
      name: flow1
      replicas: 1
      partitions: 1
      config:
        retention.ms: 300000
    flow2:
      name: flow2
      replicas: 1
      partitions: 1
      config:
        retention.ms: 300000
```
 
When we upgrade the chart the pre-hook is getting deleted and created immediately and that is causing topic-operator to delete the topics and create them back immediately. And in this case intermittently some topics are getting deleted

Attached the logs for the below scenario

1. Installed a chart which creates flow1 to flow16 topics using helm pre-hook
2. All the topic created
3. Delete the chart
4. Install the chart again
5 I see these topics got deleted flow7 and flow8
[sample-chart-and-log.zip](https://github.com/strimzi/strimzi-kafka-operator/files/5530626/sample-chart-and-log.zip)
