### ISSUE TITLE
[Bug] MirrorMaker does not use the consumer bootstrapServer value specified in config.yaml

### ISSUE THREAD

**Issue by uliludmann** [strimzi/strimzi-kafka-operator#3949]
**Describe the bug**
Mirror Maker does not use the consumer bootstrapServer value specified in its config.yaml

**To Reproduce**
1. use this config.yaml
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaMirrorMaker
metadata:
  name: my-mirror-maker
  namespace: kafka
spec:
  version: 2.6.0
  replicas: 1
  consumer:
    bootstrapServers: my-bootstrap-server:31090
    groupId: my-grpupID
    tls:
      trustedCertificates:
      - secretName: mirrormakersecret
        certificate: tls.crt
    authentication:
      type: plain
      username: myuser
      passwordSecret: 
        secretName: myuserpassword
        password: data
    config:
      # max.partition.fetch.bytes: Dont set this 
      # max.request.size: 4194304
      # fetch.max.bytes: 209715200
      # max.poll.records: 2000

      ## trackunit config
      security.protocol: "SASL_SSL"
      exclude.internal.topics: "true"
      allow.auto.create.topics: "true"
      client.id: "mirror_maker_consumer"
      mirror.topics.whitelist: "mytopic"
      auto.offset.reset: "earliest"

      
  producer:
    bootstrapServers: producer-cluster:9092
    config:
      acks: 1
      # batch.size: 16384
      buffer.memory: 67108864 #2147483648
      compression.type: gzip
      #linger.ms: 15000
      #max.request.size: 4194304
  whitelist: ".*"
```

kubectl apply -f config.yaml

see the logs of the pod where consumer bootstrap server list is empty:
```
INFO ConsumerConfig values: 
	allow.auto.create.topics = true
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [] <--- this is empty and should not be
	check.crcs = true
	client.dns.lookup = use_all_dns_ips
....
```

Note that producer bootstrap server is filled correctly 

**Expected behavior**
bootstrap server list should be filled with the corresponding server from the config.yaml

**Environment (please complete the following information):**
 - Strimzi version: 0.20
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.18.6
 - Infrastructure: Azure Kubernetes Service
