### ISSUE TITLE
[Question] How do I use kafka-log-dirs with strimzi?

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#3950]
We are embarking on a benchmarking activity and I'd like to record the locations of the topic log folders. I'm trying to figure out how to use the below utility in strimzi with no luck so far. I pasted a section of our kafka deployment related to the listeners. We use oauth for authentication. 

 Is there anyway to go through zookeeper for this? `--zookeeper localhost:2181`
```
[kafka@kafka-cluster-kafka-0 kafka]$ ./bin/kafka-log-dirs.sh --describe --bootstrap-server 127.0.0.1:9092 --broker-list 0 --topic-list TOPIC-1.stream
```

Querying brokers for log directories information
Exception in thread "main" java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.TimeoutException: Call(callName=describeLogDirs, deadlineMs=1605211591449) timed out at 1605211591450 after 1 attempt(s)
	at org.apache.kafka.common.internals.KafkaFutureImpl.wrapAndThrow(KafkaFutureImpl.java:45)
	at org.apache.kafka.common.internals.KafkaFutureImpl.access$000(KafkaFutureImpl.java:32)
	at org.apache.kafka.common.internals.KafkaFutureImpl$SingleWaiter.await(KafkaFutureImpl.java:89)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:260)
	at kafka.admin.LogDirsCommand$.describe(LogDirsCommand.scala:51)
	at kafka.admin.LogDirsCommand$.main(LogDirsCommand.scala:37)
	at kafka.admin.LogDirsCommand.main(LogDirsCommand.scala)
Caused by: org.apache.kafka.common.errors.TimeoutException: Call(callName=describeLogDirs, deadlineMs=1605211591449) timed out at 1605211591450 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: Timed out waiting for a node assignment.

```
    listeners:
      plain:
        authentication:
          type: scram-sha-512
      tls:
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          disableTlsHostnameVerification: false
          jwksEndpointUri: REDACT
          validIssuerUri: REDACT
          userNameClaim: preferred_username
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: ca.crt
          jwksExpirySeconds: 960
          jwksRefreshSeconds: 300
      external:
        type: loadbalancer
        tls: true
        configuration:
          brokerCertChainAndKey:
            certificate: ca.crt
            key: ca.key
            secretName: external-cert-secret
        authentication:
          type: oauth
          clientId: kafka-broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          disableTlsHostnameVerification: false
          jwksEndpointUri: REDACT
          validIssuerUri: REDACT
          userNameClaim: preferred_username
          tlsTrustedCertificates:
          - secretName: ca-truststore
            certificate: ca.crt
          jwksExpirySeconds: 960
          jwksRefreshSeconds: 300

```

**Comment by scholzj** [comment]
Your plain listener has authentication enabled:

```yaml
      plain:
        authentication:
          type: scram-sha-512
```

So if nothing else you would need to configure the authentication to make it work.
