### ISSUE TITLE
How to mirror data without decompressing in Mirrormaker 2

### ISSUE THREAD

**Issue by eazhilan-nagarajan** [strimzi/strimzi-kafka-operator#3963]
Hi,

Hope you're having a good day!
Let me come straight to the question in hand. We have two Kafka clusters, active and a passive. Using MirrorMaker 2 we copy topic data from the active cluster to the passive one. This is all working fine.

FYI, the data in the topics are compressed while producing so we want the MirrorMaker 2 just to copy the compressed data across clusters without decompressing and compressing again.

```
- alias: my-passive-cluster
    authentication:
      passwordSecret:
        password: password
        secretName: passive-cluster-secret
      type: scram-sha-512
      username: user-1
    bootstrapServers: my-passive-cluster.com:443
    config:
      config.storage.replication.factor: 3
      offset.storage.replication.factor: 3
      status.storage.replication.factor: 3
      producer.compression.type: gzip
```
I used the above config which compressed the data produced at the target (passive) cluster but it was decompressed initially while mirroring. 

Just wanted to know if there is something like a shallow compressing which will tell MirrorMaker 2 to just copy the data as such from source cluster topics without decompressing.

Thanks,
Eazhilan
