### ISSUE TITLE
kafka-connect cluster not deploying

### ISSUE THREAD

**Issue by coloal** [strimzi/strimzi-kafka-operator#3964]
Hi all,
I am working with kafka on AKS(Azure Cloud) using strimzi, I have created two additional namespaces to the default ones in kubernetes: kafka-cluster and kafka-connect; kafka-cluster is being used to deploy a Kafka cluster and kafka-connect to deploy a Kafka Connect cluster, both in the same AKS cluster. The strimzi cluster operator is deployed in the default namespace. 

The .yaml file defining the Kafka resource is:

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-kafka-cluster
spec:
  kafka:
    version: 2.6.0
    replicas: 1
    listeners:
      plain: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.6"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
```

The .yaml defining the KafkaConnect resource is(is like the one in https://github.com/strimzi/strimzi-kafka-operator/blob/master/examples/connect/kafka-connect-single-node-kafka.yaml but commenting the TLS configuration):

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  name: my-connect-cluster
#  annotations:
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
#    strimzi.io/use-connector-resources: "true"
spec:
  version: 2.6.0
  bootstrapServers: my-kafka-cluster-kafka-bootstrap.kafka-cluster.svc.cluster.local:9092
  #tls:
  #  trustedCertificates:
  #    - secretName: my-kafka-cluster-ca-cert
  #      certificate: ca.crt
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
```

The problem is that when I do: "kubectl apply -f kafka-connect.yaml --namespace=kafka-connect"
It returns: "kafkaconnect.kafka.strimzi.io/my-connect-cluster created"
But, neither deployment nor pods have been created. If I do: "kubectl get deployments -n kafka-connect" or "kubectl get pods -n kafka-connect"  it says: "No resources found in kafka-connect namespace.". And if I run: " kubectl get kafkaconnect.kafka.strimzi.io my-connect-cluster -n kafka-connect" it returns:

```
NAME                       DESIRED REPLICAS
my-connect-cluster

```

If I check replica sets it also says that no resources are found, even if I run "kubectl get all -n kafka-connect" it says "No resources found in kafka-connect namespace."
Since no deployment is created I can't run "kubectl describe deployment -n kafka-connect" to check the events runned while deploying and trace what is happening. If I do "kubectl describe kafkaconnect my-connect-cluster -n kafka-connect" it shows:

```
Name:         my-connect-cluster
Namespace:    kafka-connect
Labels:       <none>
Annotations:  <none>
API Version:  kafka.strimzi.io/v1beta1
Kind:         KafkaConnect
Metadata:
  Creation Timestamp:  2020-11-16T16:54:05Z
  Generation:          3
  Resource Version:    959523
  Self Link:           /apis/kafka.strimzi.io/v1beta1/namespaces/kafka-connect/kafkaconnects/my-connect-cluster
  UID:                 179ad6a6-91dd-4d63-a53d-1a81fd32c644
Spec:
  Bootstrap Servers:  my-kafka-cluster-kafka-bootstrap.kafka-cluster.svc.cluster.local:9092
  Config:
    config.storage.replication.factor:  1
    config.storage.topic:               connect-cluster-configs
    group.id:                           connect-cluster
    offset.storage.replication.factor:  1
    offset.storage.topic:               connect-cluster-offsets
    status.storage.replication.factor:  1
    status.storage.topic:               connect-cluster-status
  Version:                              2.6.0
Events:                                 <none>
```

I don't know if there is something I am doing wrong with the bootstrapServer definition in the .yaml of kafka connect, but I have checked it and the DNS name specified should be correct, or if the 'tls' configuration is mandatory, which I don't think so since you should comunicate with the kafka cluster with encryption or plain text, so I don't know. I have checked if the offsets, configs and status topics exists in the kafka cluster and they do exist. I appreciate any help or way to trace what is happenning so I could solve it, thank a lot.
