### ISSUE TITLE
External Dns is not working with private Load-balancer with AWS [question]

### ISSUE THREAD

**Issue by naggappan** [strimzi/strimzi-kafka-operator#3966]
**Describe the bug**
I have used my helm chart to deploy strimzi kafka with external load balancer and also using DNS anotations to get a route53 domain name. My chart extternal dns part is as below,

Now it is creating automatically a domain name with specified internal domain value in "hostname" ttl value is also taken propeller. But though I have provided "access" as private it is still creating a LB with type external in AWS , Hence this LB is directly accessible from internet rather than only within my vpc. 

```yaml
 external:
           type: loadbalancer
           tls: true
           authentication:
             type: tls
           overrides:
             bootstrap:
               dnsAnnotations:
                 external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap-internal.com
                 external-dns.alpha.kubernetes.io/ttl: "60"
                 external-dns.alpha.kubernetes.io/access: private
```

**Expected behavior**
It should create LB only within type as internal and have access only within the vpc (i.e LB of type "internal" and not "internet-facing")

**Comment by scholzj** [comment]
I think that to get internal loadbalancer in AWS, you need to use this annotation: `service.beta.kubernetes.io/aws-load-balancer-internal: "true"` which is missing in your YAML. Also, you would need to also set it to the per-broker loadbalancers and not just for the bootstrap load-balancer.

**Comment by naggappan** [comment]
> I think that to get internal loadbalancer in AWS, you need to use this annotation: `service.beta.kubernetes.io/aws-load-balancer-internal: "true"` which is missing in your YAML. Also, you would need to also set it to the per-broker loadbalancers and not just for the bootstrap load-balancer.

I tried the below and still the external lb type is public and did not change to private / internal . May be it is already created as public and hence not getting changed?

> spec:
>   kafka:
>     version: 2.6
>     replicas: 3
>     listeners:
>       plain: {}
>       tls: {}
>       external:
>         type: loadbalancer
>         tls: true
>         authentication:
>           type: tls
>         overrides:
>           bootstrap:
>               dnsAnnotations:
>                 external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap.internal.com
>                 external-dns.alpha.kubernetes.io/ttl: "60"
>                 external-dns.alpha.kubernetes.io/access: "private"
>                 service.beta.kubernetes.io/aws-load-balancer-internal: "true"
>             brokers:
>               - broker: 0
>                 dnsAnnotations:
>                   external-dns.alpha.kubernetes.io/hostname: kafka-broker-0.internal.com
>                   external-dns.alpha.kubernetes.io/ttl: "60"
>                   external-dns.alpha.kubernetes.io/access: "private"
>                   service.beta.kubernetes.io/aws-load-balancer-internal: "true"
>               - broker: 1
>                 dnsAnnotations:
>                   external-dns.alpha.kubernetes.io/hostname: kafka-broker-1.internal.com
>                   external-dns.alpha.kubernetes.io/ttl: "60"
>                   external-dns.alpha.kubernetes.io/access: "private"
>                   service.beta.kubernetes.io/aws-load-balancer-internal: "true"
>               - broker: 2
>                 dnsAnnotations:
>                   external-dns.alpha.kubernetes.io/hostname: kafka-broker-2.internal.com
>                   external-dns.alpha.kubernetes.io/ttl: "60"
>                   external-dns.alpha.kubernetes.io/access: "private"
>                   service.beta.kubernetes.io/aws-load-balancer-internal: "true"

Only doubt I Have is may be "service.beta.kubernetes.io/aws-load-balancer-internal: "true"" outside of the dnsAnnotation block? so that it should be aligned to  broker:1 , broker1 etc..?
Also is it mandatory that we need dns annotation for all brokers? can't we just use one for external-bootstrap?

**Comment by naggappan** [comment]
It works with type:nlb , by default it is creating a clasic loadbalancer in aws and for some reason it is not creating a classic loadbalancer with private . Hence with type nlb it works fine , finally below chart works fine for me


```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version:2.6.0
    replicas: 3
    listeners:
      plain: {}
      tls: {}
      external:
        type: loadbalancer
        tls: true
        authentication:
          type: tls
        overrides:
          bootstrap:
            dnsAnnotations:
              external-dns.alpha.kubernetes.io/hostname: kafka-bootstrap.internal.com
              external-dns.alpha.kubernetes.io/ttl: "60"
              external-dns.alpha.kubernetes.io/access: "private"
          brokers:
            - broker: 0
              dnsAnnotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-0.internal.com
                external-dns.alpha.kubernetes.io/ttl: "60"
                external-dns.alpha.kubernetes.io/access: "private"
            - broker: 1
              dnsAnnotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-1.internal.com
                external-dns.alpha.kubernetes.io/ttl: "60"
                external-dns.alpha.kubernetes.io/access: "private"
            - broker: 2
              dnsAnnotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-2.internal.com
                external-dns.alpha.kubernetes.io/ttl: "60"
                external-dns.alpha.kubernetes.io/access: "private"
    template:
      externalBootstrapService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-internal: true
      perPodService:
        metadata:
          annotations:
            service.beta.kubernetes.io/aws-load-balancer-type: nlb
            service.beta.kubernetes.io/aws-load-balancer-internal: true
```

**Comment by naggappan** [comment]
The only doubt which I have now is do we need external LB for all kafka pods as well? because using bootstrap url itself i am able to do all operations.

**Comment by scholzj** [comment]
That is weird, this should work with classic ELBs as well. I do not have an environment to try it in right now, but I definitely worked fine in the past.

The external listener is needed if you have applications connecting to Kafka running outside of the same Kubernetes cluster. If all your applications using Kafka run inside the same Kubernetes cluster, you do not need it. (and you can remove the whole `external` section)

**Comment by naggappan** [comment]
I was not saying on the external listener, I was saying about like "do we need the load balancers / dns for brokers as well or not". Eg: the below section. So i mean i can use the loadbalancer of bootstrp itself and no need to use brokers

```
brokers:
            - broker: 0
              dnsAnnotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-0.internal.com
                external-dns.alpha.kubernetes.io/ttl: "60"
                external-dns.alpha.kubernetes.io/access: "private"
            - broker: 1
              dnsAnnotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-1.internal.com
                external-dns.alpha.kubernetes.io/ttl: "60"
                external-dns.alpha.kubernetes.io/access: "private"
            - broker: 2
              dnsAnnotations:
                external-dns.alpha.kubernetes.io/hostname: kafka-broker-2.internal.com
                external-dns.alpha.kubernetes.io/ttl: "60"
                external-dns.alpha.kubernetes.io/access: "private"
```

**Comment by scholzj** [comment]
Ahh, sorry, I misunderstood that. I think that in general you should not need the DNS names per-broker as they are not configured anywhere. The clients will be configured with the bootstrap server -> the client connects there and gets the metadata from the broker. So it you normally don't care if these are some random AWS names or your own domain name.

**Comment by scholzj** [comment]
Just to clarify ... technically, you do not need it even for the bootstrap. But you would have to use some generated AWS name instead ... so normally using something like `kafka-bootstrap.internal.com` is easier to remember and more stable.

**Comment by naggappan** [comment]
Got it thanks, but using dns name is easier to be used everywhere. But now i am facing another problem i am using it with MTLS and when i use the AWS random dns name for the LB service it works fine with certs. But when i use the same with the domain name it fails with the certificate issue as below,

`Caused by: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
        at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1709)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:318)
        at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:970)
        at sun.security.ssl.Handshaker$1.run(Handshaker.java:967)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.security.ssl.Handshaker$DelegatedTask.run(Handshaker.java:1459)
        at org.apache.kafka.common.network.SslTransportLayer.runDelegatedTasks(SslTransportLayer.java:430)
        at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:514)
        at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:368)
        ... 8 more
Caused by: java.security.cert.CertificateException: No subject alternative DNS name matching kafka-bootstrap.internal.com found.
        at sun.security.util.HostnameChecker.matchDNS(HostnameChecker.java:214)
        at sun.security.util.HostnameChecker.match(HostnameChecker.java:96)
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:462)
        at sun.security.ssl.X509TrustManagerImpl.checkIdentity(X509TrustManagerImpl.java:428)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:261)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:144)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1626)
        ... 17 more` 

I guess my issue is same as mentioned in this bug: https://github.com/strimzi/strimzi-kafka-operator/issues/2629 but there it is using route and this doesn't work with AWS i think . I need to make it work with dns but using MTLS certs as well

**Comment by scholzj** [comment]
What Strimzi version do you use? You will need to configure the bootstrap DNS in `alternativesNames`: https://strimzi.io/docs/operators/latest/full/using.html#property-listener-config-altnames-reference ... Strimzi does not understand the External DNS annotations, you you have to tell it the domain to add it to the TLS cert.

**Comment by abhi1git** [comment]
My configuration
```
      - name: intlb
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          bootstrap:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
This config created 1 internal loadbalancer for bootstrap and 1 public loadbalancer for my single broker cluster.

Can the creation of separate loadbalancers for brokers be disabled because I am able to access my cluster using the bootstrap loadbalancer itself?

**Comment by scholzj** [comment]
@abhi1git No, that is not how Kafka works. It has its own discovery mechanism which needs the per-broker load balancers.

**Comment by abhi1git** [comment]
Hey @scholzj ...thanks for the quick reply.
Understood your point now clearly. Won't be able to bear that additional cost hence dropping this loadbalancer option.

Actually I was trying with ingress type before but that failed with **SSL handshake failed error** hence went on to try loadbalancer approach
```
      - name: ingress
        port: 9094
        type: ingress
        tls: true
        configuration:
          bootstrap:
            host: kafka-bootstrap-pre.kinfra-internal.example.com
            annotations:
               kubernetes.io/ingress.class: kong
               cert-manager.io/cluster-issuer: letsencrypt-pre-production
          brokers:
          - broker: 0
            host: kafka-broker-0-pre.kinfra-internal.example.com
            annotations:
               kubernetes.io/ingress.class: kong
               cert-manager.io/cluster-issuer: letsencrypt-pre-production
```
Ingress object gets created successfully and a valid letsencrypt certificate also got created but when tried to connect to kafka-bootstrap-pre.kinfra-internal.example.com with **SSL handshake failed error**
In my kubernetes cluster I manage all ingress via kong ingress controller, certmanager (letsencrypt) for SSL certificates.
Strimzi : 0.22.1
Kafka : 2.7
Can you let me know if any configuration I am missing here like ?

**Comment by scholzj** [comment]
> Understood your point now clearly. Won't be able to bear that additional cost hence dropping this loadbalancer option.

Well, not much we can do about it. The Kafka logic is explained for example in this blog post series: https://strimzi.io/blog/2019/04/17/accessing-kafka-part-1/ ... that said, with something like Kafka, the data transfer costs are quite often much higher than the fixed load balancer fee.

> Can you let me know if any configuration I am missing here like ?

I don't know since you provided a very little information. But in general, you need to:
* Make sure your Ingress has TLS passthrough supported and enabled
* Keep in mind that because of TLS passthrough, it will use the certificates from the Kafka brokers and not from the Ingress => so it does not matter what your `cert-manager.io/cluster-issuer` annotation says, if you wanna use Let's Encrypt certificates, you have to configure them in the Kafka resource directly (see the blog post on Strimzi.io - a recent one was about this)

In general, as covered by our docs, the Ingress listener is tested and developed with Kubernetes Nginx Ingress. I did not heard about anyone using it with Kong -> it might be without issues, it might be not, no idea, it depends on how compatible it is with the Kubernetes Nginx Ingress.

**Comment by abhi1git** [comment]
Hi @scholzj ....Followed the [blog](https://strimzi.io/blog/2021/05/07/deploying-kafka-with-lets-encrypt-certificates/) and tried to implement ingress for kafka with lets-encrypt certificate. (I did not use external DNS as I created a DNS record for ***.kinfra-internal.example.com** --> Classic loadbalancer of Nginx Ingress)
* Kafka Ingress Configuration
```
      - name: ingress
        port: 9094
        type: ingress
        tls: true
        configuration:
          bootstrap:
            host: bootstrap-pre.kinfra-internal.example.com
          brokers:
          - broker: 0
            host: broker-0-pre.kinfra-internal.example.com                     
          brokerCertChainAndKey:
            secretName: kafka-pre-certificate-secret
            certificate: tls.crt
            key: tls.key
```
* Certificate status is **True**
* Kafka cluster got deployed, Ingress for bootstrap and broker got created
* But when I ran the openssl command `openssl s_client -connect bootstrap-pre.kinfra-internal.example.com:443 -servername bootstrap-pre.kinfra-internal.example.com` it did not display as certificate issued by Letsencrypt instead it showed & resorted to the default nginx ingress controller certificate
```
Certificate chain
 0 s:O = Acme Co, CN = Kubernetes Ingress Controller Fake Certificate
   i:O = Acme Co, CN = Kubernetes Ingress Controller Fake Certificate
```
* Described the ingress configuration and could see that TLS is referring to SNI instead of the secret(kafka-pre-certificate-secret) which was mentioned in the ingress configuration
```
kubectl describe ing -n kafka kafka-cluster-pre-kafka-ingress-bootstrap

Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
Name:             kafka-cluster-pre-kafka-ingress-bootstrap
Namespace:        kafka
Address:          10.0.4.158
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  SNI routes bootstrap-pre.kinfra-internal.example.com
Rules:
  Host                                     Path  Backends
  ----                                     ----  --------
  bootstrap-pre.kinfra-internal.example.com  
                                           /   kafka-cluster-pre-kafka-ingress-bootstrap:9094   100.96.0.26:9094)
Annotations:                               ingress.kubernetes.io/ssl-passthrough: true
                                           nginx.ingress.kubernetes.io/backend-protocol: HTTPS
                                           nginx.ingress.kubernetes.io/ssl-passthrough: true
Events:                                    <none>
```
* So I edited ingress config manually and added secretName and then on hitting openssl command I could see the correct lets encrypt certificate
```
  tls:
  - hosts:
      - bootstrap-pre.kinfra-internal.example.com
    secretName: kafka-pre-certificate-secret

# After adding above syntax the describe ingress command showed as follows & openssl command showed correct certificate
TLS:
  kafka-pre-certificate-secret terminates bootstrap-pre.kinfra-internal.example.com
```
* Still I was unable to connect to Kafka from kafka producer and got the following logs:
```
[2021-05-29 12:46:50,111] ERROR [Producer clientId=console-producer] Connection to node -1 (bootstrap-pre.kinfra-internal.example.com/52.66.122.197:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2021-05-29 12:46:50,111] WARN [Producer clientId=console-producer] Bootstrap broker bootstrap-pre.kinfra-internal.example.com:443 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2021-05-29 12:46:50,222] ERROR [Producer clientId=console-producer] Connection to node -1 (bootstrap-pre.kinfra-internal.example.com/52.66.122.197:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2021-05-29 12:46:50,222] WARN [Producer clientId=console-producer] Bootstrap broker bootstrap-pre.kinfra-internal.example.com:443 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2021-05-29 12:46:50,333] ERROR [Producer clientId=console-producer] Connection to node -1 (bootstrap-pre.kinfra-internal.example.com/52.66.122.197:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2021-05-29 12:46:50,333] WARN [Producer clientId=console-producer] Bootstrap broker bootstrap-pre.kinfra-internal.example.com:443 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2021-05-29 12:46:50,447] ERROR [Producer clientId=console-producer] Connection to node -1 (bootstrap-pre.kinfra-internal.example.com/52.66.122.197:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2021-05-29 12:46:50,448] WARN [Producer clientId=console-producer] Bootstrap broker bootstrap-pre.kinfra-internal.example.com:443 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
[2021-05-29 12:46:50,559] ERROR [Producer clientId=console-producer] Connection to node -1 (bootstrap-pre.kinfra-internal.example.com/52.66.122.197:443) failed authentication due to: SSL handshake failed (org.apache.kafka.clients.NetworkClient)
[2021-05-29 12:46:50,559] WARN [Producer clientId=console-producer] Bootstrap broker bootstrap-pre.kinfra-internal.example.com:443 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
```
* And also after some time Strimzi operator again reverts the secretName changes added by me in ingress object

Can you let me know if I missed any configuration/steps during this implementation?
