### ISSUE TITLE
[Kafka Connect Connectors - Strimzi 20] ...

### ISSUE THREAD

**Issue by vperi1730** [strimzi/strimzi-kafka-operator#3976]
Hi Team,

I have deployed the Strimzi 20 with Kafka 2.6.0 version, Now I wanted to configure the Kafka connect to test a small POC.

1) Do we have any blogs/examples which have been tried with some of the available connectors?
2) What all list of connectors does Kafka connect supports as part of the latest Strimzi 20?

I found one blog which is leveraging the Apache camel, not sure about this.

https://strimzi.io/blog/2020/05/07/camel-kafka-connectors/

**Comment by scholzj** [comment]
I think there will be somewhere also a blog post about Debezium CDC connector on the Strimzi.io blog. In general, you can use it with any Kafka compatible connector. There are no limitations. But I do not have a catalog of all of them. But the Camel connectors alone give you quite a lot of options: https://camel.apache.org/camel-kafka-connector/latest/index.html

**Comment by vperi1730** [comment]
Ok great. Another question is as Camel supports a broad range of connectors, Do we have docker images available for all of them?

For example, I am working on a small POC for "Reading a simple text file and load the data into Kafka" for which I would be using the camel-file-kafka-connector. The blog explains the standalone way of writing a compose file+tar the camel file connector and then extracting and then building the docker image. 

Thoughts?

**Comment by scholzj** [comment]
You have to follow this to build your own image with the connectors you want: https://strimzi.io/docs/operators/latest/full/deploying.html#using-kafka-connect-with-plug-ins-str ... We cannot pre-build this since the images would then have several GBs in size.

**Comment by vperi1730** [comment]
Sure Scholzj, Let me check this.

I have tried the use case of FileStreamSourceConnector and FileStreamSinkConnector, came across 2 questions.

1) As part of my SourceConnector CR, I have configured the spec in the following way and it wrote the content from the LICENSE file to the Kafka topic. Let's say if I want to write it from my custom file(test.txt which is in my file system), how do I achieve this?

```
spec:
  class: org.apache.kafka.connect.file.FileStreamSourceConnector
  tasksMax: 2
  config:
    file: "/opt/kafka/LICENSE"
    topic: my-topic
```
2) When i am trying to read the topic and writing to a sample file in my SinkConnector, it is throwing me an error.

```
Spec:
  Class:  org.apache.kafka.connect.file.FileStreamSinkConnector
  Config:
    File:     /tmp/sink_test_data.txt
    Topic:    eagletopic
  Tasks Max:  3
Status:
  Conditions:
    Last Transition Time:  2020-11-23T06:32:09.817849Z
    Message:               PUT /connectors/cluster20-sink-connector/config returned 500 (Internal Server Error): Must configure one of topics or topics.regex
    Reason:                ConnectRestException
    Status:                True
    Type:                  NotReady
  Observed Generation:     1
  Tasks Max:               3
```

Need help here.

**Comment by scholzj** [comment]
Re 1) This is really just an example of how to use the KafkaConnector resource. You cannot mount your own files into it.
Re 2) Well, the error says you do not have valid connector CR. You probably have to share the whole CR for us to understand where the problem is.

**Comment by vperi1730** [comment]
Here is my CR.

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnector
metadata:
  name: cluster20-sink-connector
  labels:
    strimzi.io/cluster: cluster20-kafka-connect
spec:
  class: org.apache.kafka.connect.file.FileStreamSinkConnector
  tasksMax: 3
  config:
    file: "/tmp/sink_test_data.txt"
    topics: eagletopic
```

My understanding is whatever content is available in the eagletopic would be written inside the txt file under the tmp folder.
