### ISSUE TITLE
[Question] KafkaMirrorMaker2 keeps creating topics an cannot consume messages from destination

### ISSUE THREAD

**Issue by psamagal** [strimzi/strimzi-kafka-operator#3977]
After some time running we will have a large number of topics as the one above, the <cluster name>-src ('kafka-mycluster'), is being added to prefix over and over creating new topics.

```
kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.heartbeats
```

Current Kafka Setup is the following

**Source**: Kafka Cluster (v2.5.1), deployed as a single server, using standard Kafka deployment modes
**Destination**: Kafka Cluster (v2.5.1) deployed with stimzi kafka operator with 3 replicas. As part of the operator deployment there's also a KafkaMirrorMaker2 deployment.

This is my Kafka Cluster Config
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-mycluster
  labels:
    maintainer: devops
  namespace: mynamespace
spec:
  kafka:
    version: 2.5.1
    replicas: 3
    listeners:
      plain:
        port: 9092
        type: internal
        tls: false
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "2"
    jvmOptions:
      -Xms: 512m
      -Xmx: 512m
    config:
      offsets.topic.replication.factor: 2
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      inter.broker.protocol.version: "2.5"
      log.message.format.version: "2.5"
      auto.create.topics.enable: "true"
      delete.topic.enable: "true"
    storage:
      type: persistent-claim
      class: efs-prov
      size: 50Gi
    tlsSidecar:
      resources:
        requests:
          memory: 256Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 300m
    metrics:
# (...) metrics alert rules redacted
  zookeeper:
    replicas: 3
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 320Mi
    storage:
      type: persistent-claim
      class: efs-prov
      size: 10Gi
      deleteClaim: false
    metrics:
# (...) metrics alert rules redacted
  entityOperator:
    topicOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
    userOperator:
      resources:
        requests:
          memory: 512Mi
          cpu: "1"
        limits:
          memory: 512Mi
          cpu: "1"
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
  cruiseControl:
    logging:
        type: inline
        loggers:
          cruisecontrol.root.logger: "INFO"
    resources:
      requests:
        cpu: 300m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    tlsSidecar:
      resources:
        requests:
          cpu: 200m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 128Mi
```
Until here all good, i can create topics on the new cluster and produce and consume to then as expected.
My problems start when I try to introduce the mirror maker 2 that things start to fail. 
It's the fist time i use the mirror maker and is very likely that i'm doing something wrong.  :(

My intention  is to replicate a group of topics that follow a pattern  _topicsPattern: "dropzone.*"_ from my src cluster to the new strimzi kafka cluster. This new cluster will be on a different location and consumers will consume from here instead of original source. The sync should only flow in one direction.

This is my current KafkaMirrorMaker2 Config
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: kafka-mycluster-mirror
  namespace: mynamespace
  labels:
    maintainer: devops
spec:
  version: 2.5.1
  replicas: 1
  connectCluster: "kafka-mycluster-src"
  clusters:
  - alias: "kafka-mycluster-src"
    bootstrapServers: kafkamycluster01.servername:9092
    config:
      config.storage.replication.factor: 1
      offset.storage.replication.factor: 1
      status.storage.replication.factor: 1
  - alias: "kafka-mycluster-dst"
    bootstrapServers: kafka-mycluster-kafka-bootstrap.mynamespace:9092
    # config:
    #   config.storage.replication.factor: 1
    #   offset.storage.replication.factor: 1
    #   status.storage.replication.factor: 1
  mirrors:
  - sourceCluster: "kafka-mycluster-src"
    targetCluster: "kafka-mycluster-dst"
    sourceConnector: 
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 1
        sync.topic.acls.enabled: "false"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 1
    topicsPattern: "dropzone.*"
    groupsPattern: ".*"
  resources:
    requests:
      memory: 1Gi
      cpu: "1"
    limits:
      memory: 2Gi
      cpu: "2"
```

After it start working i can see some topics being created on the new cluster.
being the **dropzone.testtopic1** the original topic, 
I can see the **kafka-mycluster-src.dropzone.testtopic1** on destination cluster, but i cannot consume anything from it. Should this be the topic I should use for consume messages? or should we have the same  **dropzone.testtopic1** created here?

I know Mirror maker can work bidirectional and outside strimzi we defined the flow using
_ClusterA->ClusterB=true_, is there something similar here on strimzi? (the topic growth gave me some idea it may had gotten in some loop, cause of it).

```
$ kubectl --kubeconfig=config.aldn-uat-frontend -n pushgateway run kafka-list -ti --image=strimzi/kafka:0.20.0-kafka-2.5.1 --limits="cpu=2,memory=2Gi" --requests="cpu=1,memory=1Gi" --rm=true --restart=Never -- bin/kafka-topics.sh --list --bootstrap-server kafka-mycluster-kafka-bootstrap.pushgateway:9092
If you don't see a command prompt, try pressing enter.
__consumer_offsets
heartbeats
kafka-mycluster-src.checkpoints.internal
kafka-mycluster-src.dropzone.testtopic1
kafka-mycluster-src.dropzone.testtopic2
kafka-mycluster-src.dropzone.testtopic3
kafka-mycluster-src.dropzone.testtopic4
kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.kafka-mycluster-src.heartbeats
kafka-mycluster-src.topicmirrortest
strimzi.cruisecontrol.metrics
strimzi.cruisecontrol.modeltrainingsamples
strimzi.cruisecontrol.partitionmetricsamples
topicmirrortest
pod "kafka-list" deleted
```

Any help to setup the scenario above, will be appreciated?
Please let me know if you need more details or logs, i can provide then if necessary.
