### ISSUE TITLE
Changing fsGroup id

### ISSUE THREAD

**Issue by ghahramani** [strimzi/strimzi-kafka-operator#3993]
Hi,

I just tried to change the `fsGroup` id as it is set to `0` for zookeeper and the cluster I am working it just accepts from `1` not `0`.

So I just added it like this (I am not sure I did it right or not) but it does not start any `Statefulset` or anything at all but when I remove the template, it starts but gives me the error of `fsGroup` cannot be in that range.

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: messaging
spec:
  kafka:
    version: 2.6.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.6"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 8Gi
          deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 8Gi
      deleteClaim: false
    template:
      pod:
        securityContext:
          fsGroup: 1
  entityOperator:
    topicOperator: { }
    userOperator: { }
```
