### ISSUE TITLE
[Question] Connection done with two broker but not with the third broker

### ISSUE THREAD

**Issue by Gonath** [strimzi/strimzi-kafka-operator#4001]
Dear all, 

I deployed a classical solution based on a replication of 3 broker and 3 zookeepers. I'm using only the external listeners with the port 9094, a scram authentication and a self-signed CA for the TSL. 

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: cluster
  namespace: kafka-cluster
spec:
  kafka:
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
          username: test
          passwordSecret:
            secretName: test
            password: test
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}

```

My library KafkaJS with Nodejs is able to connect to the broker cluster-kafka-1 and cluster-kafka-2 (successful authentication) but not with the broker cluster-kafka-0.

Here is my log: 

```
{"level":"DEBUG","timestamp":"2020-11-24T22:43:30.928Z","logger":"kafkajs","message":"[Connection] Connecting","broker":"51.210.253.39:9094","clientId":"39336f75-1934-411d-a86b-04de21bf62fe","ssl":true,"sasl":true}

{"level":"ERROR","timestamp":"2020-11-24T22:43:33.928Z","logger":"kafkajs","message":"[Connection] Connection timeout","broker":"51.210.253.39:9094","clientId":"39336f75-1934-411d-a86b-04de21bf62fe"}

{"level":"ERROR","timestamp":"2020-11-24T22:43:33.928Z","logger":"kafkajs","message":"[BrokerPool] Failed to connect to broker, reconnecting","retryCount":0,"retryTime":266}
```

Where may I found log information to try to find the error with kafka? There is nothing interesting with the log of the POD. 
Or if someone already met a similar problem, that could be nice to share ;)
