### ISSUE TITLE
[Question] How to use Azure Internal Loadbalancer as Loadbalancer?

### ISSUE THREAD

**Issue by patrickheinzelmann** [strimzi/strimzi-kafka-operator#4013]
Hi,

I followed the [blog post](https://strimzi.io/blog/2019/05/13/accessing-kafka-part-4/) and tried to for configuration of the Azure Internal Loadbalancer.

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
        overrides:
          bootstrap:
            dnsAnnotations:
              service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  entityOperator:
    topicOperator: {}
    userOperator: {}
  template:
    externalBootstrapService:
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    perPodService:
      metadata:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```

However the operator is always creating an external loadbalancer for broker and bootstrap. Is there any example how to use an Azure Internal Loadbalancer?
