### ISSUE TITLE
[Enhancement] How to reference Kafka POD nodeName as container env variable using the Downward API

### ISSUE THREAD

**Issue by milon619** [strimzi/strimzi-kafka-operator#4023]
I am trying to inject some POD information about the Kafka POD as env variable to the container using template.kafkaContainer schema,

```
      kafkaContainer:
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
```

However, I can see it's not working as expected. Could someone explain if this is a supported feature or are there any workarounds for accomplishing it?
https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/#use-pod-fields-as-values-for-environment-variables

**Comment by scholzj** [comment]
`template.kafkaContainer.env` does not support environment variables from ConfigMaps, Secrets or from Downward API. You can only specify a value.

**Comment by milon619** [comment]
Ok. Is there a way I can reference the POD nodeName as an env variable in the container? Basically I am trying to ship Kafka logs to FluentD POD running as a daemonset in the k8s cluster. The idea is to use logstash-gelf facility to append the logs to GELF listener which in this case is my FluentD POD.

**Comment by scholzj** [comment]
I do not think that is possible in any way. (And to be honest I'm not sure how would the node name help here since in general node name is not a node address. But that might not be surprising as I do not understand FluentD / Logstash etc. too much. So I might be just missing some point.)

**Comment by milon619** [comment]
In our setup, nodeName is the same as the node host address/hostname and FluentD is acting as GELF listener on a UDP port which is exposed to outside via a NodePort service, so that FluentD can be reached at <nodeName>:<Port> and this configuration is added in the log4j.properties file

```
log4j.appender.gelf.Host=udp:<nodeName>
 log4j.appender.gelf.Port=<port>
```

It would be good if there is support for `template.kafkaContainer.env` to specify env variables from ConfigMaps, Secrets, or from Downward API in the future.

Thanks

**Comment by scholzj** [comment]
I can understand what are you trying to do, but I do not think it is generally applicable outside of your environment. I can change this to enhancement if you want. But I'm not sure if/when this might get implemented. 

Out of curiosity ... why can't you just have some service and use the service name / DNS which will be stable and not depend on the node?

**Comment by milon619** [comment]
Thanks for changing this topic into an enhancement request. Using a service name also works. Thanks for your suggestion

**Comment by scholzj** [comment]
> Using a service name also works. Thanks for your suggestion

So is it still needed? Or is the node name still a better solution for some reason and we should keep the enhancement?

**Comment by milon619** [comment]
For my use-case, I can live with using the service, but I still think it would be good to get the same supported features as native Kubernetes like injecting the env var values from ConfigMaps, Secrets, or from Downward API.

**Comment by scholzj** [comment]
You are not supposed to inject random information. This is expected to be used for example for doing some Kafka tuning. So I think there needs to be a clear usecase for this to support it.

**Comment by milon619** [comment]
Okay, then I think we can close this issue.

**Comment by rsvalerio** [comment]
Hi @scholzj @milon619 

Our use-case is to register some environment variables, for a couple of "legacy" k8s services (Our k8s deployment is a bit peculiar).
These environment variables are related to consul service registration and/or other consul related stuff.

If you can just expose some basic pod information as env vars:

```yaml
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

We could then use

```yaml
        - name: CONSUL_CLIENT_HTTP_ADDR
          value: "http://$(NODE_IP):8500"
```

Thanks in advance

**Comment by scholzj** [comment]
Strimzi does not have any Consul integration, so I guess you are using some custom builds? In any case, there is currently no way to get this information injected into the pod.

**Comment by rsvalerio** [comment]
The consul stuff was an answer to your request:
"...So I think there needs to be a clear use-case for this to support it...."

We can think of it as just an extension point, Strimzi just needs to expose some kafka POD information.

Strimzi would just add these 4 environment variables in the kafka pod:

```yaml
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

I can try to contribute a PR if this is an acceptable change.

Thank you for your answer @scholzj 

Cheers
