### ISSUE TITLE
[Bug] Operator continuously update resources in AKS

### ISSUE THREAD

**Issue by vutkin** [strimzi/strimzi-kafka-operator#4035]
**Describe the bug**
In our case we noticed that when we trying to create internal LB in AKS managed by Rancher (this is important) using annotation:
```
externalBootstrapService:
  metadata:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
perPodService:
  metadata:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"
```
we see that time needed for creating LB is ~15 min.
The root cause is that Strimzi operator and Rancher (which adds custom annotations like `/metadata/annotations/field.cattle.io~1publicEndpoints`) simultaneously try to change the same services of LoadBalancer type. Rancher adds some labels and annotations to services and Strimzi operator removes that data. That process caused continuously updating Azure load balancer configuration. As a result, Azure load balancer stays in an "updating" state with a long processing queue.

**To Reproduce**
1. Create internal LB for external listener
2. Create AKS cluster managed by Rancher (https://rancher.com/docs/rancher/v2.x/en/cluster-provisioning/hosted-kubernetes-clusters/aks/)
3. Create Internal LB by adding annotations: creating takes more than 15 min

**Expected behavior**
LB creation takes less than 2 min.

**Environment (please complete the following information):**
 - Strimzi version: 0.18
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.18
 - Infrastructure: Azure AKS/Rancher

**YAML files and logs**

![image](https://user-images.githubusercontent.com/25753488/100874260-5aadda00-34b5-11eb-8bbf-173f42d07128.png)

**Additional context**
Suggestion: add ability ignore changes for annotations/labels for resources watched by operator:
```
example:
ignore_changes = [
      metadata[0].annotations["cattle.io/*"],
      metadata[0].annotations["field.cattle.io~1publicEndpoints"]
    ]
```
