### ISSUE TITLE
[Enhancement] Use shared IP for brokers loadBalancer

### ISSUE THREAD

**Issue by liamnv** [strimzi/strimzi-kafka-operator#4081]
**Is your feature request related to a problem? Please describe.**
We use strimzi and expose external via loadBalancer, but strimzi has no option for use same IP and difference port

**Describe the solution you'd like**
Loadbalancer listeners has option to expose in same IP, difference port (ex metallb)

**Describe alternatives you've considered**

**Additional context**

**Comment by scholzj** [comment]
@liamnv Can you elaborate on how should this work? Kafka needs to have different services for each broker because each service has different selector. So we cannot just create one LoadBalancer service with multiple ports each pointing to a different broker.

**Comment by scholzj** [comment]
Triaged on 31.3.2022: Not clear how it should be implemented. Should be closed. If anyone has idea how to do it, we can get back to it.

**Comment by QuinnBast** [comment]
Would love to see this added - I thought the description was pretty straight forward. I'm surprised this hasn't been required more.

My cluster's LoadBalancer only has access to a single IP address in it's pool, but I can use any number of ports.

How this should be implemented is to allow loadbalancer listener to also be able to specify a "broadcastPort" or alternate ports that the kubernetes Service uses to listen on (but under the hood, the service still routes to the broker).

For example, there would still be 4 services deployed, but we should be able to set their port:

bootstrap: myIpaddress:9094
Broker0: myIpaddress:9095 --> Forwards to broker0
Broker1: myIpaddress:9096 --> forwards to broker1
Broker2: myIpaddress:9097 --> forwards to broker3

In this case, the boostrap would broadcast the other brokers as: `myIpaddress:9095,myIpaddress:9096,myIpaddress:9097`

I tried getting around this by specifying multiple `listeners`, one for each individual broker that I wanted to configure, but this still doesn't work, and I get met with this exception:

For example here was the config I tried:
```yaml
# Strimzi can only expose one listener to one port so we need to specify
# A listener for each port and explicitly define each broker.
- name: extbstrp
  port: 9094
  type: loadbalancer
  tls: false
  configuration:
    createBootstrapService: true
    bootstrap:
      loadBalancerIP: myIpAddress
    brokers: []
- name: extbroker0
  port: 9095
  type: loadbalancer
  tls: false
  configuration:
    createBootstrapService: false
    brokers:
    - broker: 0
      loadBalancerIP: myIpAddress
- name: extbroker1
  port: 9096
  type: loadbalancer
  tls: false
  configuration:
    createBootstrapService: false
    brokers:
    - broker: 1
      loadBalancerIP: myIpAddress
- name: extbroker2
  port: 9097
  type: loadbalancer
  tls: false
  configuration:
    createBootstrapService: false
    brokers:
    - broker: 2
      loadBalancerIP: myIpAddress
```

But using this configuration, my brokers will not startup and end up throwing an error because each `listener` still attempts to make all brokers listen on the same IP/port combination...

```
java.lang.IllegalArgumentException: requirement failed: Configured end points myIpAddress:9094 in advertised listeners are already registered by broker 1
	at scala.Predef$.require(Predef.scala:337)
	at kafka.server.KafkaServer.$anonfun$createBrokerInfo$3(KafkaServer.scala:512)
	at kafka.server.KafkaServer.$anonfun$createBrokerInfo$3$adapted(KafkaServer.scala:510)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:926)
	at kafka.server.KafkaServer.createBrokerInfo(KafkaServer.scala:510)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:331)
	at kafka.Kafka$.main(Kafka.scala:109)
	at kafka.Kafka.main(Kafka.scala)
```

![2023_12_20_0pw_Kleki](https://github.com/strimzi/strimzi-kafka-operator/assets/22599103/be5757ab-966d-47c1-8852-ae090b814fd8)
