### ISSUE TITLE
[Enhancement] Add template for kafkaconnect

### ISSUE THREAD

**Issue by liamnv** [strimzi/strimzi-kafka-operator#4089]
**Is your feature request related to a problem? Please describe.**
We use debezium connector for kafkaconnect, debezium use much RAM although it completed snapshot database, we want to add resource limit, request for kafkaconnect pod

**Describe the solution you'd like**
Implement template in KafkaConnectSpect, we found it existed on JsonProperties but hasn't been implemented (https://github.com/strimzi/strimzi-kafka-operator/blob/b0c04b4ff41d688d716ec5454082a95e873d551b/api/src/main/java/io/strimzi/api/kafka/model/KafkaConnectSpec.java)

**Additional context**
We can create PR and implement it?

**Comment by scholzj** [comment]
Resources for Kafka Connect should be supported. You can do something like this:

```yaml
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaConnect
metadata:
  name: my-connect
spec:
  replicas: 1
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 2Gi
      cpu: 1000m
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  config:
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    key.converter.schemas.enable: false
    value.converter.schemas.enable: false
```

The values from `.spec.resources` is applied to the pods created by the Connect cluster. Is this what you meant?
