### ISSUE TITLE
Issue connecting to listener using SCRAM-SHA-512

### ISSUE THREAD

**Issue by alex-ionescu-qualitance** [strimzi/strimzi-kafka-operator#4103]
Hello everyone,

We have a Kafka cluster which needs to be secured and we have configured 2 listeners using the Strimzi Operator 0.20.0. The one with OAUTHBEARER works correctly but we are unable to connect to the one using SCRAM-SHA-512.

Our Kafka configuration for the listeners looks like this:
```yaml
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    authorization:
      clientId: kafka-sso
      delegateToKafkaAcls: false
      disableTlsHostnameVerification: false
      grantsRefreshPeriodSeconds: 60
      grantsRefreshPoolSize: 5
      tlsTrustedCertificates:
        - certificate: ca.crt
          secretName: oauth-server-cert
      tokenEndpointUri: >-
        https://.....
      type: keycloak
    config:
      log.message.format.version: '2.6'
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - authentication:
          type: scram-sha-512
        name: scram
        port: 9092
        tls: false
        type: internal
      - authentication:
          disableTlsHostnameVerification: true
          userNameClaim: preferred_username
          clientId: kafka-sso
          validIssuerUri: 'https://.....'
          maxSecondsWithoutReauthentication: 3600
          tlsTrustedCertificates:
            - certificate: ca.crt
              secretName: oauth-server-cert
          type: oauth
          clientSecret:
            key: secret
            secretName: bridge-oauth-secret
          introspectionEndpointUri: >-
            https://.....
        name: tls
        port: 9093
        tls: false
        type: internal
    logging:
      loggers:
        kafka.root.logger.level: TRACE
      type: inline
    replicas: 3
    storage:
      type: ephemeral
    version: 2.6.0
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
```

We are testing using a console consumer:
```
cat > /tmp/client.properties <<EOF
security.protocol=SASL_PLAINTEXT
sasl.mechanism=SCRAM-SHA-512
sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="my-user" password="tR6uauWQw74u";
ssl.endpoint.identification.algorithm=
EOF

bin/kafka-console-consumer.sh --bootstrap-server copo-test-kafka-bootstrap:9092 --topic ro.btrl.out.copo.service.nomenclator.findLabels.v1 --from-beginning --consumer.config=/tmp/client.properties
```

The error message that we get it:
[2020-12-14 12:06:10,762] WARN [Consumer clientId=consumer-console-consumer-63952-1, groupId=console-consumer-63952] Bootstrap broker localhost:9092 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)

If we try to connect with a different mechanism we get the correct error:
org.apache.kafka.common.errors.UnsupportedSaslMechanismException: Client SASL mechanism 'OAUTHBEARER' not enabled in the server, enabled mechanisms are [SCRAM-SHA-512]

Any ideea how to troubleshoot this or something that we can change? We need this authentication type for AKHQ (which does not support OAUTHBEARER or has OIDC flows correctly implemented).
