### ISSUE TITLE
Use configMapKeyRef for the external logging configuration

### ISSUE THREAD

**Issue by sknot-rh** [strimzi/strimzi-kafka-operator#4247]
Currently, we specify just the name of ConfigMap containing external logging. The name of the data property is hardcoded. It would be better to use `configMapKeyRef` as we do in `metricsConfig`. Backward compatibility needs to be persisted.

The CR after change could be like 
```
     logging:
        type: external
        valueFrom:
          configMapKeyRef:
            name: my-config-map
            key: my-key
```
