### ISSUE TITLE
Setup a strimzi kafka cluster with ingress &  Use custom certificates.

### ISSUE THREAD

**Issue by kpravin001** [strimzi/strimzi-kafka-operator#4406]
Hi Team,
There are facing issue with custom certificate and ssl.  I have created configMap  but i am not able to get it.
kindly look on my setup and configuration. Please advice.  

**strimzi setup steps** 
kubectl create ns kafka
helm repo add strimzi https://strimzi.io/charts/ -n kafka
helm install strimzi-cluster strimzi/strimzi-kafka-operator -n kafka
helm ls -n kafka

----------
**my-nginx stable/nginx-ingress  setup steps** 

$ helm repo add nginx-stable https://helm.nginx.com/stable -n kafka
$ helm repo update -n kafka
$ helm install my-nginx nginx-stable/nginx-ingress --namespace default --set service.type=LoadBalancer -n kafka

$ 
`cat client-properties

ssl.keystore.location: /tmp/server.keystore.jks
ssl.keystore.password: password
ssl.key.password: password
ssl.truststore.location: /tmp/server.truststore.jks
ssl.truststore.password: password
ssl.enabled.protocols: TLSv1.2,TLSv1.1,TLSv1
ssl.client.auth: required`

kafka.yaml:

```yaml
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: my-cluster
spec:
  volumes:
    - name: server-properties
      configMap:
        name: server.properties
  kafka:
    version: 2.7.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
volumeMounts:
        - name: server-properties
          mountPath: /home/kafka/
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.7"
      inter.broker.protocol.version: "2.7"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
volumes:
      - name: my-cm-vol
        configMap:
           name: client.properties
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

kubectl create cm client.roperties --from-file=client-properties
kubectl apply -f kafka.yaml
kubectl exec -it pod /bin/bash 
cd /home/kafka/
ls -- empty not able to see client.properties file
