### ISSUE TITLE
Removing exernal listener type: loadbalancer do not removes AWS LB

### ISSUE THREAD

**Issue by aholbreich** [strimzi/strimzi-kafka-operator#4410]
**Describe the bug**

the following part of Kafka resource beeing deployed in EKS will create AWS classic LB for every broker and for bootstrap address

```
 listeners:     
      - name: external
        port: 9094
        type: loadbalancer
        tls: false
```
but when these lines are removed again and configuration is applied, then tge loadbalancers are not cleaned up.

**Expected behavior**
I expect every system that creates resources in the the cloud (here AWS) also be responsible for removal. 
It must be not the default behavior, but at leas there should be a `force-lb-removal` flag or simmilar.

**Environment (please complete the following information):**
 - Strimzi version:  0.21.1
 - Installation method:  Helm chart
 - Kubernetes cluster: Kubernetes 1.18
 - Infrastructure: Amazon EKS

**YAML files and logs**

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
#Docu: https://strimzi.io/docs/operators/latest/using.html#ref-sample-kafka-resource-config-deployment-configuration-kafka
metadata:
  name: main-cluster
  namespace: kafka
spec:
  kafka:
    version: 2.7.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
# This starts 4 classic Loadbalancers 
#  when removed, loadbalancer are nor removed.
#      - name: external
#        port: 9094
#        type: loadbalancer
#        tls: false

```

**Comment by scholzj** [comment]
Strimzi creates only the services. And when you delete the listener, we delete the service. We do not manage the load balancers => that is something Kubernetes does.

**Comment by aholbreich** [comment]
@scholzj yes, probably kubernetes know how to crete Loadbalancer in surrounding IaaS environment. But is there no way to tell kubernetes to destroy these LB again? 
In the scenarios where Ingress ressources are used, controllers also take responsibillity of resource distruction. Ok. Ingress controllers are not part of kubernetes API, but does it really make a difference?

**Comment by scholzj** [comment]
Normally, the LBs are deleted when the service is deleted ... in the same way as they are created when the service is created.

**Comment by aholbreich** [comment]
@scholzj but didn't worked here.

**Comment by scholzj** [comment]
Yeah, I get that. But I do not think there is much we can about it in Strimzi.

**Comment by scholzj** [comment]
In 0.23, we are adding support for configuring finalizers: https://strimzi.io/docs/operators/master/full/using.html#type-GenericKafkaListenerConfiguration-schema-reference ... that should help.

**Comment by aholbreich** [comment]
@scholzj  thank you for doing something about it. Can you give me some more hints on how it can work now?

**Comment by scholzj** [comment]
Well, it is not released yet => it will be released in 0.23 probably in few weeks. Once it is, you should be able to do something like this:

```yaml
listeners:
  #...
  - name: external
    port: 9094
    type: nodeport
    tls: false
    configuration:
      finalizers:
        - service.kubernetes.io/load-balancer-cleanup
  #...
```

That will configure the finalizer on the loadbalancer services and Kubernetes should make sure the loadbalancer is deleted (https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#garbage-collecting-load-balancers).

It cannot be set by default since it is not supported everywhere and the services would never get deleted when it is not supported. So that is why you need to configure it.
