### ISSUE TITLE
KafkaConnect dies with - Preparing truststore / keystore password was incorrect

### ISSUE THREAD

**Issue by iceman91176** [strimzi/strimzi-kafka-operator#4434]
**Describe the bug**
We are unable to deploy (more than one) KafkaConnect-Instances. The Pods go to a CrashLoopBackOff.  Logfile output of the failing container is

```
Preparing truststore
keytool error: java.io.IOException: keystore password was incorrect
```
It happens with any number of replicas. 
If i change the deployment manually, so that the container starts in "debug-mode" with an infinite sleep i am able to exec into the container and start ./kafka_connect_run.sh manually. And it works

```
[kafka@connect-cluster01-connect-77b8c6bb4c-bl6sj kafka]$ ./kafka_connect_run.sh
Preparing truststore
Certificate was added to keystore
Preparing truststore is complete
Starting Kafka Connect with configuration:
......
```

Since we have one instance running (in another namespace and another cluster) it might be that it it only happens with additional instances. But i can't delete the other instance to prove that.

It fails when adding the Certificate to a new truststore. This is a new container, there should be no existing truststore in /tmp/kafka.

**To Reproduce**
1. Create Custom Resource (see below)
2. Pod(s) crashes

**Expected behavior**
Kafka-Connect Pods should start without problems - truststores can be created

**Environment (please complete the following information):**
 - Strimzi version: [0.21.1]
 - Installation method: [Helm chart]
 - Kubernetes cluster: [Kubernetes 1.17.14]
 - Infrastructure: [Baremetal]

**YAML files and logs**

```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: "true"
  name: connect-cluster01
spec:
  authentication:
    clientId: connect-cluster01
    clientSecret:
      key: client-secret
      secretName: connect-cluster01-oauth-secret
    tokenEndpointUri: https://xxxx
    type: oauth
  bootstrapServers: streaming-xxx-01-cluster-kafka-bootstrap:9093
  config:
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    config.storage.replication.factor: 2
    config.storage.topic: wit.sys.connect-cluster01.config.0
    group.id: connect-cluster01
    key.converter: org.apache.kafka.connect.storage.StringConverter
    offset.storage.replication.factor: 2
    offset.storage.topic: wit.sys.connect-cluster01.offsets.0
    status.storage.replication.factor: 2
    status.storage.topic: wit.sys.connect-cluster01.status.0
    value.converter: io.apicurio.registry.utils.converter.AvroConverter
    value.converter.apicurio.registry.as-confluent: true
    value.converter.apicurio.registry.converter.deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
    value.converter.apicurio.registry.converter.serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
    value.converter.apicurio.registry.global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
    value.converter.apicurio.registry.url: http://${file:/opt/kafka/external-configuration/registry-config/connect-registry-credentials.properties:registry_username}:${file:/opt/kafka/external-configuration/registry-config/connect-registry-credentials.properties:registry_password}@registry01-apicurio-registry-streams-secure-gateway:8081/api
  logging:
    type: external
    name: logging-connect-configmap
  template:
    pod:
      imagePullSecrets:
      - name: xxxx
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/cluster-service
                operator: Exists
      tolerations:
      -
        effect: NoSchedule
        key: node-role.kubernetes.io/cluster-service
      -
        effect: PreferNoSchedule
        key: node-role.kubernetes.io/cluster-service
  externalConfiguration:
    volumes:
    - name: connector-config
      secret:
        secretName: connect-cluster01-sql-credentials
    - name: registry-config
      secret:
        secretName: connect-cluster01-registry-credentials
  image: xxx/strimzi/strimzi-kafka-connect-jdbc:latest
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: streaming-xxx-01-metrics
        key: connect-metrics-config.yml
  replicas: 1
  tls:
    trustedCertificates:
    - certificate: ca.crt
      secretName: streaming-xxx-01-cluster-ca-cert
```
