### ISSUE TITLE
Unable to deploy into hybrid cluster

### ISSUE THREAD

**Issue by mkoziel2000** [strimzi/strimzi-kafka-operator#4436]
When deploying a Kafka cluster into a K8S cluster that is setup as a hybrid (both Linux and windows worker nodes), it is very hard to get things deployed.  Affinity rules need to be added to both kafka and zookeeper spec area of a Kafka CRD.  But, even with that, there is an Entity-Operator deployment definition that gets generated whereby I could not find a way to apply the node selector such that this pod does not try to run on windows nodes.

**Steps to reproduce the behavior:**
1. Install strimzi helm chart into a K8S cluster containing both windows and linux worker nodes (make sure nodeSelector is defined in the values.yaml so that the strimzi operator doesn't land on a windows worker node)
2. Create a kafka cluster resource using the definition below:
3. Examine where the "my-cluster-entity-operator" pod ends up

**Expected behavior**
Provide an ability to apply affinity or nodeSelector rules to the entity-operator deployment

**Environment (please complete the following information):**
 - Strimzi version: 0.21.1
 - Installation method: Helm chart + YAML definition
 - Kubernetes cluster: K8S 1.19
 - Infrastructure: BareMetal

Kafka cluster YAML

```yaml
kind: Kafka
apiVersion: kafka.strimzi.io/v1beta1
metadata:
  name: my-cluster
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      inter.broker.protocol.version: '2.7'
      log.message.format.version: '2.7'
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 1
    listeners:
      external:
        overrides:
          bootstrap:
            nodePort: 32100
        port: 9094
        tls: false
        type: nodeport
      plain:
        port: 9092
        tls: false
        type: internal
      tls:
        port: 9093
        tls: true
        type: internal
    template:
	  pod:
	    affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux		
    replicas: 1
    storage:
      type: jbod
      volumes:
        - deleteClaim: false
          id: 0
          size: 100Gi
          type: persistent-claim
    version: 2.7.0
  zookeeper:
    template:
	  pod:
	    affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux		
    replicas: 1
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
```

**Comment by scholzj** [comment]
Maybe opening a discussion instead of a bug would have been better. You can add the affinity for the entity operator as well. Something like this should do:

```yaml
  # ...
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                    - linux	
  # ...
```
