### ISSUE TITLE
Deleting broker pod causes "Permission denied" errors

### ISSUE THREAD

**Issue by fsouza-bux** [strimzi/strimzi-kafka-operator#4467]
When deleting one broker pod, for example for a disruption test, the statefulset or kafka_operator restarts the pod, but then pod initialization has issues with permissions like one below in the kafka-init initContainer:

```
+ JMX_ACCESS_FILE=/tmp/access.file
+ JMX_PASSWORD_FILE=/tmp/password.file
+ cat
+ cat
/opt/kafka/kafka_run.sh: line 32: /tmp/password.file: Permission denied
```

First attempt to fix was to remove the jmx collector authentication, but anyway the pod had the same permission problems in another point:

```
+ exec /usr/bin/tini -w -e 143 -- /opt/kafka/bin/kafka-server-start.sh /tmp/strimzi.properties
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /opt/kafka/kafka-request.log (Permission denied)
```

For passing through the whole problem, had to add the **securityContext** to run the pods as **root**, and then the operator / statefulset was able to start it again.

**Until before the tests, no securityContext configuration was added, so the cluster was running using the user kafka.**

**This bug has originated from a discussion here: https://github.com/strimzi/strimzi-kafka-operator/discussions/4460**

1. Create a kafka cluster
2. Delete one broker pod with `kubectl delete pod <pod-name>`
3. Check the pod being initialised, and some permission error might appear

**Expected behavior**
The new pod should restart with any permission errors.

**Environment (please complete the following information):**
 - Strimzi version: strimzi-kafka-operator: 0.21.1
 - Installation method: Helm
 - Kubernetes cluster: 1.18.12-gke.1206
 - Infrastructure: GCP / GKE

**YAML files and logs**

This is the last Kafka CRD, differences to the previous one is the inclusion now of the `securityContext`, and the removal of the authentication for the jmx collector.

```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  annotations:
    meta.helm.sh/release-name: kafka
    meta.helm.sh/release-namespace: kafka
  labels:
    app.kubernetes.io/instance: kafka
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kafka
    app.kubernetes.io/version: 1.16.0
    helm.sh/chart: kafka-0.1.0
  name: kafka
  namespace: kafka
spec:
  entityOperator:
    tlsSidecar:
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
    topicOperator:
      logging:
        loggers:
          rootLogger.level: INFO
        type: inline
      reconciliationIntervalSeconds: 120
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
      watchedNamespace: kafka
    userOperator:
      logging:
        loggers:
          rootLogger.level: INFO
        type: inline
      reconciliationIntervalSeconds: 120
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 200m
          memory: 256Mi
      watchedNamespace: kafka
  kafka:
    authorization:
      type: simple
    config:
      auto.create.topics.enable: "false"
      background.threads: 10
      default.replication.factor: 3
      delete.topic.enable: "false"
      group.initial.rebalance.delay.ms: 3000
      log.cleaner.threads: 1
      log.retention.check.interval.ms: 300000
      log.retention.hours: -1
      log.segment.bytes: 1073741824
      min.insync.replicas: 2
      num.io.threads: 8
      num.network.threads: 3
      num.partitions: 1
      num.recovery.threads.per.data.dir: 1
      num.replica.fetchers: 2
      offsets.retention.minutes: 525600
      offsets.topic.replication.factor: 3
      socket.receive.buffer.bytes: 102400
      socket.request.max.bytes: 104857600
      socket.send.buffer.bytes: 102400
      ssl.cipher.suites: TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384,TLS_DHE_RSA_WITH_AES_256_GCM_SHA384
      ssl.enabled.protocols: TLSv1.2
      ssl.protocol: TLSv1.2
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
      transactional.id.expiration.ms: 2147483647
      zookeeper.connection.timeout.ms: 6000
    jvmOptions:
      -XX:
        MaxDirectMemorySize: 512m
      -Xms: 3G
      -Xmx: 6G
    listeners:
    - authentication:
        type: scram-sha-512
      configuration:
        useServiceDnsDomain: true
      name: plain
      port: 9092
      tls: true
      type: internal
    - authentication:
        type: scram-sha-512
      name: tls
      port: 9093
      tls: true
      type: internal
    - authentication:
        type: scram-sha-512
      configuration:
        bootstrap:
          annotations:
            cloud.google.com/load-balancer-type: Internal
            external-dns.alpha.kubernetes.io/hostname: #removed
            external-dns.alpha.kubernetes.io/ttl: "300"
        brokerCertChainAndKey:
          certificate: ca.crt
          key: ca.key
          secretName: external-listener-ca
        brokers:
        - advertisedHost: #removed
          annotations:
            cloud.google.com/load-balancer-type: Internal
            external-dns.alpha.kubernetes.io/hostname: #removed
            external-dns.alpha.kubernetes.io/ttl: "300"
          broker: 0
        - advertisedHost: #removed
          annotations:
            cloud.google.com/load-balancer-type: Internal
            external-dns.alpha.kubernetes.io/hostname: #removed
            external-dns.alpha.kubernetes.io/ttl: "300"
          broker: 1
        - advertisedHost: #removed
          annotations:
            cloud.google.com/load-balancer-type: Internal
            external-dns.alpha.kubernetes.io/hostname: #removed
            external-dns.alpha.kubernetes.io/ttl: "300"
          broker: 2
        loadBalancerSourceRanges:
        - #removed
      name: external
      port: 9094
      tls: true
      type: loadbalancer
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    logging:
      name: kafka-broker-log4j-config
      type: external
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: jmx-broker-prometheus
          name: jmx-broker-config
    rack:
      topologyKey: topology.kubernetes.io/zone
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 3
    resources:
      limits:
        cpu: 2
        memory: 12Gi
      requests:
        cpu: 1500m
        memory: 8Gi
    storage:
      class: kafka-data
      deleteClaim: false
      size: 500Gi
      type: persistent-claim
    template:
      externalBootstrapService:
        metadata:
          annotations:
            cloud.google.com/load-balancer-type: Internal
      perPodService:
        metadata:
          annotations:
            cloud.google.com/load-balancer-type: Internal
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodetype
                  operator: In
                  values:
                  - kafka
        securityContext:
          fsGroup: 0
          runAsUser: 0
        terminationGracePeriodSeconds: 30
        tolerations:
        - effect: NoSchedule
          key: nodetype
          operator: Equal
          value: kafka
    version: 2.7.0
  zookeeper:
    config:
      initLimit: 20
      syncLimit: 10
      tickTime: 5000
    jvmOptions:
      -XX:
        MaxDirectMemorySize: 128m
      -Xms: 2G
      -Xmx: 4G
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    logging:
      name: kafka-zookeeper-log4j-config
      type: external
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: jmx-zookeeper-prometheus
          name: jmx-zookeeper-config
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    replicas: 3
    resources:
      limits:
        cpu: 2
        memory: 5Gi
      requests:
        cpu: 500m
        memory: 3Gi
    storage:
      class: zookeeper-data
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: nodetype
                  operator: In
                  values:
                  - zookeeper
        securityContext:
          fsGroup: 0
          runAsUser: 0
        terminationGracePeriodSeconds: 10
        tolerations:
        - effect: NoSchedule
          key: nodetype
          operator: Equal
          value: zookeeper
```

**Additional context**
This bug has originated from a discussion here: https://github.com/strimzi/strimzi-kafka-operator/discussions/4460
