### ISSUE TITLE
Internal Listeners Should Implement GenericKafkaListenerConfiguration possibly GenericKafkaListenerConfigurationBootstrap

### ISSUE THREAD

**Issue by towens** [strimzi/strimzi-kafka-operator#4542]
Hello. This is an amazing project and we also use Istio. ListenerConfiguration on an internal listener would allow us map the host of an advertised broker to an Istio gateway and then to a virtual service pointing to the internal kafka svc's.

**Describe the solution you'd like**
Context: We terminate ssl at the network load balancer level with Istio and cert-manager.
```
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          brokers:
            - broker: 0
              host: broker-0.your-domain.com
```
A call to the bootstrap svc would include `broker-0.your-domain.com`

**Describe alternatives you've considered**
External listeners via load balancers with NLB annotations: https://strimzi.io/blog/2020/01/02/using-strimzi-with-amazon-nlb-loadbalancers/

The hope is one Network Load Balancer, not two 😉  

**Additional context**
I mention possibly for `GenericKafkaListenerConfigurationBootstrap` as one can already create a gateway and virtual service with istio to hit the bootstrap svc. Of course when you do so it fails to resolve the internal k8s dns entry for the broker(s)

```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: a-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: tcp
      protocol: TCP
    hosts:
    - kafka-bootstrap.your-domain.com
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: a-vs
spec:
  gateways:
  - a-gateway
  hosts:
  - kafka-bootstrap.your-domain.com
  tcp:
  - match:
    - port: 80
    route:
    - destination:
        host: clustername-kafka-bootstrap.ns.svc.cluster.local
        port:
          number: 9092
```

On a host outside of K8s:
```
kafkacat -L -b kafka-bootstrap.your-domain.com:80

Metadata for all topics (from broker -1: kafka-bootstrap.your-domain.com:80/bootstrap):
 1 brokers:
   broker 0 at clustername-kafka-0.clustername-kafka-brokers.ns.svc:9092
 0 topics:
 |FAIL|rdkafka#producer-0| clustername-kafka-0.clustername-kafka-brokers.ns.svc:9092/0: Failed to resolve 'clustername-kafka-0.clustername-kafka-brokers.ns.svc:9092': Name or service not known
 |ERROR|rdkafka#producer-0| clustername-kafka-0.clustername-kafka-brokers.ns.svc:9092/0: Failed to resolve 'clustername-kafka-0.clustername-kafka-brokers.ns.svc:9092': Name or service not known
```

**Comment by scholzj** [comment]
The `internal` type listener is creating just Kubernetes Services. It does not create any other resources. And on the service, there is nowhere to place the `broker-0.your-domain.com` from your suggested example. So, what would the operator do with it?

**Comment by scholzj** [comment]
If the only purpose of the `host` field should be to set the advertised host in Kafka to correspond to the manually created Istio resources, you can do it already today by using the `advertisedHost` field: https://strimzi.io/docs/operators/latest/full/using.html#type-GenericKafkaListenerConfigurationBroker-reference

**Comment by towens** [comment]
Thanks @scholzj, for the comments and link. I had previously read through all the external listener types to find a fit for our implementation.

I can see your point. It may not be an issue with the internal listeners, possibly the types of external listeners offered.

With how Istio works with k8s DNS, this listener would only need to set the advertised host, nothing else. This would alleviate the need to provision a load balancer, a nodeport svc, create resources for Nginx, or create OpenShift routes (also Istio.) If I misunderstand something with the Strimzi listeners, I am happy to change the viewpoint. 

As mentioned above, using an external listener of type `loadbalancer` could work.

Our team and partner teams all ingress through a Network Load Balancer, that traffic is routed via Istio. Why add another load balancer if you don't need it? Especially when Strimzi svc's are of the `clusterip` and `clusterip` svc's are inconsequential for Istio.

**Comment by scholzj** [comment]
> With how Istio works with k8s DNS, this listener would only need to set the advertised host, nothing else. This would alleviate the need to provision a load balancer, a nodeport svc, create resources for Nginx, or create OpenShift routes (also Istio.) If I misunderstand something with the Strimzi listeners, I am happy to change the viewpoint.

Well, as I said above ... you can use the internal listener and configure the advertised hosts manually to whatever you need. The services will be created but if you don't use them and route the traffic directly to the pods that should not matter.

> Especially when Strimzi svc's are of the clusterip and clusterip svc's are inconsequential for Istio.

Not sure what this means to be honest.

**Comment by towens** [comment]
Thank you, the docs you shipped and the ones I was reading state. "Configures broker service overrides for external listeners."

Indeed, if you click through to [B.15.7. Schema reference](https://strimzi.io/docs/operators/latest/full/using.html#type-GenericKafkaListenerConfiguration-schema-reference) it does list an array of GenericKafkaListenerConfigurationBroker

In the future I'll make sure to trust your word over the docs 😉
The advertised hosts on the internal listener are working.

>>Especially when Strimzi svc's are of the clusterip and clusterip svc's are inconsequential for Istio.

>Not sure what this means to be honest.

No hidden meaning, just stating the obvious that strimzi svc's and Istio are compatible.

Thanks again, be well.

**Comment by scholzj** [comment]
> Thank you, the docs you shipped and the ones I was reading state. "Configures broker service overrides for external listeners."

Damn ... that used to be the case few releases back. I will remove it.

**Comment by towens** [comment]
Hello @scholzj,  as you previously relayed `advertisedHost` and `advertisedPort` work with `configuration.brokers` on an internal listener.

From the docs and testing this does not extend to `configuration.bootstrap` that I can see.

This would hone in on the enhancement of the internal listeners to implement `GenericKafkaListenerConfigurationBootstrap` or a partial implementation for additional fields.

Trying to advertise the bootstrap service with `host` on an internal listener returns
```
Status:
  Conditions:
    Message:               Listener configuration is not valid: [listener plain cannot configure bootstrap.host because it is not Route ot Ingress based listener]
    Reason:                InvalidResourceException
    Status:                True
    Type:                  NotReady
```

With
```
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          bootstrap:
            host: cluster-bootstrap.namespace.team.company.com
          brokers:
            - broker: 0
              advertisedHost: broker-0.namespace.team.company.com
              advertisedPort: 80
```

Also when trying to advertise the bootstrap service with `advertisedHost` and `advertisedPort` on an internal listener returns
```
  Conditions:
    Status:                True
    Type:                  Ready
    Message:               Contains object at path spec.kafka.listeners.genericKafkaListeners.configuration.bootstrap with unknown properties: advertisedHost, advertisedPort
    Reason:                UnknownFields
    Status:                True
    Type:                  Warning
```

With
```
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          bootstrap:
            advertisedHost: cluster-bootstrap.namespace.team.company.com
            advertisedPort: 80
          brokers:
            - broker: 0
              advertisedHost: broker-0.namespace.team.company.com
              advertisedPort: 80
```

context:
  - both the advertised bootstrap host and advertised broker host are entries for Istio that resolve to Strimzi's internal svc's.
  - these routes will be secured with https.
  - OIDC will be added.
  - do the same with another cluster
  - link with mirror maker 2
  - migrate
  - we use network load balancer(s) as ingress with Istio as our traffic levels knock over classic and application load balancers.

Enhancement?
