### ISSUE TITLE
Kafka Connect build pod uses default service account

### ISSUE THREAD

**Issue by adriank-convoy** [strimzi/strimzi-kafka-operator#4592]
**Describe the bug**
The pod started for the Kafka Connect build runs as the `default` service account, not the service account created by Strimzi for Kafka Connect. In AWS EKS we rely on service account annotations to specify the IAM role for the containers in the pod. Because the pod is running as default service account the build container is using the default role for our cluster, and is not able to push the built image to our ECR repository:
```
error checking push permissions -- make sure you entered the correct tag name, and that you are authenticated correctly, and try again: checking push permission for "*********.dkr.ecr.****.amazonaws.com/***************": POST https://*******.dkr.ecr.****.amazonaws.com/v2/********/blobs/uploads/: DENIED: User: arn:aws:sts::************:assumed-role/<INCORRECT_DEFAULT_ROLE> is not authorized to perform: ecr:InitiateLayerUpload on resource: arn:aws:ecr:****:********:repository/*******
```
As far as I can tell there's no way to change this behavior

**To Reproduce**
1. Create `KafkaConnect` custom resource w/ build specified
```
  build:
    output:
      type: docker
      image: <image>
    plugins:
      - name: camel-salesforce
        artifacts:
          - type: jar
            url: https://repo.maven.apache.org/maven2/org/apache/camel/kafkaconnector/camel-salesforce-kafka-connector/0.8.0/camel-salesforce-kafka-connector-0.8.0.jar
```
2. Get yaml for kafka connect build pod with `kubectl get pod -o yaml <pod_name>`
3. Check serviceAccount and serviceAccountName values:
```
apiVersion: v1
kind: Pod
metadata:
  ...
spec:
  ...
  serviceAccount: default
  serviceAccountName: default
```

**Expected behavior**
Pod uses the same service account created by the Strimzi operator for the Kafka Connect cluster

**Environment (please complete the following information):**
 - Strimzi version: 0.21.1
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.18
 - Infrastructure: Amazon EKS

**Additional context**

I went poking around the code, and I believe this is caused by the [KafkaConnectBuild](https://github.com/strimzi/strimzi-kafka-operator/blob/master/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectBuild.java) class not overriding `getServiceAccountName()`, and the base class implementation just returns null. I'm not very familiar with the code base, but if it makes sense for the KafkaConnectBuild class to use the same implementation as the [KafkaConnectCluster](https://github.com/strimzi/strimzi-kafka-operator/blob/master/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/KafkaConnectCluster.java) class I'd be happy to send a PR.

**Workaround**
For now I'm just going to try adding the annotation needed for the role to the default service account in the namespace, which should unblock us for now.
