### ISSUE TITLE
Remove support for legacy metrics configuration from the CO code

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#4628]
In `v1beta2`, the only way for configuring the metrics should be using the `metricsConfig` field. I.e. this is not supported anymore:

```yaml
metrics:
  # ... 
```

and only this can be used instead:

```yaml
metricsConfig:
  type: jmxPrometheusExporter
  valueFrom:
    configMapKeyRef:
      name: kafka-mm-metrics
      key: mm-metrics-config.yml
```

We should remove the support for the old legacy way from the CO. This should cover all affected resources and classes.

_(The fields should still remain present in the `api` module for the time being)_
