### ISSUE TITLE
Remove support for legacy logging configuration from the CO code

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#4629]
In `v1beta2`, the only way for configuring the external logging should  be using the `configMapKeyRef` field. I.e. this is not supported anymore:

```yaml
logging:
  type: external
  name: my-config-map
```

and only this can be used instead:

```yaml
logging:
  type: external
  valueFrom:
    configMapKeyRef:
      name: my-config-map
      key: log4j.properties
```

We should remove the support for the old legacy way from the CO. This should cover all affected resources and classes.

_(The fields should still remain present in the `api` module for the time being)_
