### ISSUE TITLE
topic-store-changelog created with min.isr of 2 but replication factor 1

### ISSUE THREAD

**Issue by cablespaghetti** [strimzi/strimzi-kafka-operator#4694]
**Describe the bug**
The `__strimzi-topic-operator-kstreams-topic-store-changelog` topic was created when installing 0.22.1 (on top of old volumes from 0.19 which might make a difference...) the topic was created with min.isr of 2 but replication factor 1.  

```
[kafka@kafka-kafka-0 bin]$ ./kafka-topics.sh --bootstrap-server localhost:9092 --describe --topic __strimzi-topic-operator-kstreams-topic-store-changelog
Topic: __strimzi-topic-operator-kstreams-topic-store-changelog	PartitionCount: 1	ReplicationFactor: 1	Configs: min.insync.replicas=2,cleanup.policy=compact,segment.bytes=67108864,message.format.version=2.7-IV2,min.compaction.lag.ms=0,message.timestamp.type=CreateTime
	Topic: __strimzi-topic-operator-kstreams-topic-store-changelog	Partition: 0	Leader: 1	Replicas: 1	Isr: 1
```
We're running 3 Kafka nodes with this config:
```
    config:
      auto.create.topics.enable: "false"
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      replica.fetch.max.bytes: 10485760
      min.insync.replicas: 2
```

**Expected behavior**
The topic to be created with the default isr and replication factor of the cluster.

**Environment (please complete the following information):**
 - Strimzi version: 0.22.1
 - Installation method: Helm Chart
 - Kubernetes cluster: Kubernetes 1.19
 - Infrastructure: Amazon EKS

I'm happy to supply more information and try further deployments if this isn't easy to reproduce. Thanks
