### ISSUE TITLE
In K8s >= 1.17 Kafka cannot be deployed - Ingress uses both annotation and IngressClass

### ISSUE THREAD

**Issue by failytaler** [strimzi/strimzi-kafka-operator#4754]
**Describe the bug**
In K8s >= 1.17 Kafka cannot be deployed as ingress uses both annotation and IngressClass

**To Reproduce**
1. Create kafka with custom ingress class in k8s >=1.17
2. See error
```
2021-04-14 11:54:26 ERROR AbstractOperator:275 - Reconciliation #4(timer) Kafka(strimzi-test/core): createOrUpdate failed
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://172.20.0.1/apis/networking.k8s.io/v1/namespaces/strimzi-test/ingresses. Message: Ingress.extensions "core-kafka-bootstrap" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx-tls": can not be set when the class field is also set. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=annotations.kubernetes.io/ingress.class, message=Invalid value: "nginx-tls": can not be set when the class field is also set, reason=FieldValueInvalid, additionalProperties={})], group=extensions, kind=Ingress, name=core-kafka-bootstrap, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Ingress.extensions "core-kafka-bootstrap" is invalid: annotations.kubernetes.io/ingress.class: Invalid value: "nginx-tls": can not be set when the class field is also set, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
```
**Expected behavior**
Either annotation or ingressclass is added, not both.

**Environment (please complete the following information):**
 - Strimzi version: 0.22.1
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.19.6
 - Infrastructure: Amazon EKS

**YAML files and logs**
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: core
  namespace: test
spec:
  kafka:
    replicas: 2
    version: 2.7.0
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      limits:
        memory: 5Gi
        cpu: "4"
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    listeners:
      plain: {}
      tls: {}
      external:
        type: ingress
        class: nginx-tls
        authentication:
          type: tls
        configuration:
          bootstrap:
            host: bootstrap.kafka
          brokers:
          - broker: 0
            host: broker-0.kafka
          - broker: 1
            host: broker-1.kafka
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 500Gi
        deleteClaim: true
    rack:
      topologyKey: topology.kubernetes.io/zone
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
