### ISSUE TITLE
Standalone Topic Operator can't connect via TLS without authentication

### ISSUE THREAD

**Issue by jozenstar** [strimzi/strimzi-kafka-operator#4766]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
I'm using Strimzi to operate on AWS MSK cluster which requires TLS connection but doesn't have any authentication enabled at the moment. I've set the KafkaConnect successfully with this codeblock
```
tls:
    trustedCertificates: []

```
However, I can't set the Standalone Topic Operator to behave the same. If you set `STRIMZI_TLS_ENABLED` to `true` then the topic operator requires trust- and keystore locations and passwords to be set.  If you set `STRIMZI_TLS_ENABLED` to `false` then you get the Java OOM (because of nonTLS connection). 
I've tried to set `STRIMZI_TLS_ENABLED` to `false`  and set the `security.protocol` to `SSL` via `STRIMZI_JAVA_SYSTEM_PROPERTIES`, however this value is being overwritten by AdminConfig.
 

**To Reproduce**
1. Create an MSK cluster with strict TLS connection but without authentication
2. Create a TopicOperator to connect to it
3. Check logs 

**Expected behavior**
I'd like the standalone topic operator to be able to communicate via TLS without an authentication

**Environment (please complete the following information):**
 - Strimzi version: 0.22.1
 - Installation method: YAML files
 - Kubernetes cluster: Kubernetes v1.18.9-eks-d1db3c
 - Infrastructure: Amazon EKS

**YAML files and logs**
I've tried different configurations. I believe that this one should work, but it doesn't.
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-topic-operator
  labels:
    app: strimzi
  namespace: strimzi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-topic-operator
  template:
    metadata:
      labels:
        name: strimzi-topic-operator
    spec:
      serviceAccountName: strimzi-topic-operator
      containers:
        - name: strimzi-topic-operator
          image: quay.io/strimzi/operator:0.22.1
          args:
          - /opt/strimzi/bin/topic_operator_run.sh
          env:
            - name: STRIMZI_RESOURCE_LABELS
              value: "strimzi.io/cluster=my-cluster"
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: "Placeholder"
            - name: STRIMZI_ZOOKEEPER_CONNECT
              value: "Placeholder"
            - name: STRIMZI_ZOOKEEPER_SESSION_TIMEOUT_MS
              value: "20000"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "900000"
            - name: STRIMZI_TOPIC_METADATA_MAX_ATTEMPTS
              value: "6"
            - name: STRIMZI_LOG_LEVEL
              value: DEBUG
            - name: STRIMZI_TLS_ENABLED
              value: "false"
            - name: STRIMZI_JAVA_SYSTEM_PROPERTIES
              value: "-Dsecurity.protocol=SSL"
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          livenessProbe:
            httpGet:
              path: /healthy
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              memory: 96Mi
              cpu: 100m
            requests:
              memory: 96Mi
              cpu: 100m
  strategy:
    type: Recreate
```
