### ISSUE TITLE
Documentation to enable value-less -XX JVM options inconsistent with POJOs/implementation

### ISSUE THREAD

**Issue by k-wall** [strimzi/strimzi-kafka-operator#4782]
**Describe the bug**

The documentation](https://strimzi.io/docs/operators/in-development/using.html#con-common-configuration-jvm-reference)
illustrates value-less JVM options being signaled in the CRD with a boolean true value.

```
jvmOptions:
  "-XX":
    "ExplicitGCInvokesConcurrent": true
```

This is inconsistent with the Java pojos/builders of `io.strimzi.api.kafka.model` and the io.strimzi.operator.cluster.model.EntityOperator#javaOptions implement that processes the same.  The POJO defines the field as Map<String,String>, and the implementation expects a stringified boolean value "true" or "false". Passing a boolean value is impossible with the current Java API.

I suspect that the documentation is at fault.

**Environment (please complete the following information):**
 - Strimzi version: [main]

**Comment by scholzj** [comment]
I guess this was fixed somewhere because now both this from the docs:

```yaml
jvmOptions:
  "-XX":
    "UseG1GC": false
    "MaxGCPauseMillis": 20
    "InitiatingHeapOccupancyPercent": 35
    "ExplicitGCInvokesConcurrent": true
```

As well as this:

```yaml
jvmOptions:
  "-XX":
    "UseG1GC": "false"
    "MaxGCPauseMillis": 20
    "InitiatingHeapOccupancyPercent": 35
    "ExplicitGCInvokesConcurrent": "true"
```

seem to produce the same results: `-XX:+ExplicitGCInvokesConcurrent -XX:InitiatingHeapOccupancyPercent=35 -XX:MaxGCPauseMillis=20 -XX:-UseG1GC`

So I guess this can be closed?
