### ISSUE TITLE
Document increasing maxTasks to improve MirrorMaker2 performance

### ISSUE THREAD

**Issue by jordan-thoms** [strimzi/strimzi-kafka-operator#4833]
**Suggestion / Problem**
After setting up MirrorMaker2, the mirroring speed was slow and adding more replica nodes did not help. Eventually I found that increasing the maxTasks setting on the sourceConnector helped, but that setting is only mentioned in the spec and not in the main documentation. 
**Documentation Link**
https://strimzi.io/docs/operators/latest/using.html#proc-mirrormaker-replication-str should include maxTasks like this:
```
  mirrors:
  - sourceCluster: "source-cluster"
    targetCluster: "strimzi-cluster"
    sourceConnector:
      tasksMax: 100
      config:
        replication.factor: 1
        offset-syncs.topic.replication.factor: 3
```

and suggest increasing it if the replication is not fast enough.
