### ISSUE TITLE
Cruise Control UnknownHostException

### ISSUE THREAD

**Issue by imalik8088** [strimzi/strimzi-kafka-operator#4886]
**Describe the bug**
Adding the KafkaRebalance (cruise control) Resource I do get an UnknownHostException in the State. Although Topics could be created and also metrics were build If I run `kubectl describe kafkarebalance my-cluster` I get an UnknownHostException in the state.

**To Reproduce**
1. Add `cruiseControl: {}` to an existing cluster
2. Run command 'kubectl describe kafkarebalance xxxx'
3. See error

**Expected behavior**
Show me the proposal by cruise control. for e.g.

```yaml
Status:
  Conditions:
    Last Transition Time:  2021-04-30T11:44:49.074773Z
    Status:                True
    Type:                  ProposalReady
  Observed Generation:     1
  Optimization Result:
    Data To Move MB:  108
    Excluded Brokers For Leadership:
```

**Environment:**
 - Strimzi version: 0.22.1
 - Installation method: YAML
 - Kubernetes cluster: K8s v1.19.7
 - Infrastructure: Azure AKS

**YAML files and logs**

**Additional context**
Solved by deleting the `kubectl delete kafkarebalance xxx` and reapplying the yaml file

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaRebalance
metadata:
  labels:
    argocd.argoproj.io/instance: xxxxx
    strimzi.io/cluster: xxxxxxxx
  name: xxxxx
  namespace: xxxxxx
spec: {}
```

Thats what I'm getting from describe kafkarebalance before reapplying.
```yaml
status:
  conditions:
  - lastTransitionTime: "2021-05-03T09:51:00.590323Z"
    message: 'failed to resolve ''xxxxxxx.svc''
      after 2 queries '
    reason: UnknownHostException
    status: "True"
    type: NotReady
  observedGeneration: 1
```
