### ISSUE TITLE
`kind` property duplicated in some tests after upgrade to kubernetes-client 5.4.0

### ISSUE THREAD

**Issue by sknot-rh** [strimzi/strimzi-kafka-operator#5053]
**Describe the bug**
After upgrading fabric8 kubernetes-client dependency to version 5.4.0 (https://github.com/strimzi/strimzi-kafka-operator/pull/5000) some tests are failing, at the `kind` property is duplicated in the resource, for example 
```
---
apiVersion: "kafka.strimzi.io/v1alpha1"
kind: "KafkaRebalance"
metadata:
  labels:
    strimzi.io/cluster: "kafka-cruise-control-test-cluster"
  name: "my-rebalance"
  namespace: "cruise-control-namespace"
spec:
  goals:
  - "CpuCapacityGoal"
  - "NetworkInboundCapacityGoal"
  - "DiskCapacityGoal"
  - "RackAwareGoal"
  - "NetworkOutboundCapacityGoal"
  - "ReplicaCapacityGoal"
  skipHardGoalCheck: false
  concurrentPartitionMovementsPerBroker: 0
  concurrentIntraBrokerPartitionMovements: 0
  concurrentLeaderMovements: 0
  replicationThrottle: 0
  unknown: "property"
kind: "KafkaRebalance"
```
Because of this, the tests are failing.

**To Reproduce**
Run `MockKubeTest` class or `io.strimzi.operator.cluster.operator.assembly.KafkaRebalanceAssemblyOperatorTest#testUnknownPropertyInSpec`

**Expected behavior**
Test passed

**Environment (please complete the following information):**
 - Strimzi version: this PR rebased to main (https://github.com/strimzi/strimzi-kafka-operator/pull/5000)
