### ISSUE TITLE
Strimzi operator removes annotations from secrets with custom credentials

### ISSUE THREAD

**Issue by jharting** [strimzi/strimzi-kafka-operator#5129]
**Describe the bug**
A way to define custom credentials for a KafkaUser is to define define the credentials in a secret with a matching name and labeled with `strimzi.io/cluster` and `strimzi.io/kind` labels, for example:

```
apiVersion: v1
kind: Secret
metadata:
  name: cyndi
  labels:
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: KafkaUser
  annotations:
    foo: bar
data:
  password: aGF2ZWZ1bg==
  sasl.jaas.config: b3JnLmFwYWNoZS5rYWZrYS5jb21tb24uc2VjdXJpdHkuc2NyYW0uU2NyYW1Mb2dpbk1vZHVsZSByZXF1aXJlZCB1c2VybmFtZT0iY3luZGkiIHBhc3N3b3JkPSJoYXZlZnVuIjs=
type: Opaque
```

The strimzi operator then uses these credentials for the user instead of generating new ones, which is great.

However, during the reconciliation, the operator also modifies the secret and removes all the annotations. This is not such a problem in the `foo: bar` scenario but it becomes a problem when a gitops tools is used to provision (and rotate) the credentials in the secret. **These tools typically make use of annotations and get confused or work unexpectedly if the strimzi operator interferes with the annotations they use.**

**To Reproduce**
1. Deploy Strimzi/AMQ Streams (I am using amqstreams.v1.7.2)
2. Create a custom secret with kafka user credentials (see above)
3. Create a KafkaUser with the matching name
4. Observe the strimzi-operator take ownership of the secret and remove all annotations

**Expected behavior**
The operator should read the provided credentials (and add custom labels/annotations if needed) but should otherwise respect the state of the resource and should not touch labels/annotations it had not set.

**Environment (please complete the following information):**
 - Strimzi version: amqstreams.v1.7.2
 - Installation method: OLM
 - Kubernetes cluster: CodeReady Containers version: 1.26.0+31f06c09
 - Infrastructure: Run locally on my Fedora laptop
