### ISSUE TITLE
Add suffix patterntype for aclrules

### ISSUE THREAD

**Issue by joedugdale** [strimzi/strimzi-kafka-operator#5131]
Requesting ability to specify suffix in kafkauser acl instead of only literal and prefix

eg
```
      - host: '*'
        operation: Read
        resource:
          name: '*.foo'
          patternType: suffix
          type: topic

whereas at the moment we have to specify
      - host: '*'
        operation: Read
        resource:
          name: 'deva.foo'
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: 'testa.foo'
          patternType: literal
          type: topic
etc

```

https://github.com/strimzi/strimzi-kafka-operator/blob/main/documentation/modules/appendix_crds.adoc#aclruletopicresource-schema-reference

**Describe alternatives you've considered**
we have to specify exact topic names if the only thing changing is suffix. Would be easier if there was the flexibility of suffix and prefix instead of just prefix and literal
