### ISSUE TITLE
Support providing custom KafkaUser credentials

### ISSUE THREAD

**Issue by jharting** [strimzi/strimzi-kafka-operator#5141]
**Is your feature request related to a problem? Please describe.**

By default, Strimzi operator auto-generates authentication credentials for each KafkaUser and puts them in a Kubernetes secret. This secret can only be used from within the same Kubernetes namespace. This is a limitation in situations where e.g. a KafkaConnect cluster resides in a different namespace than the Kafka cluster. The credentials need to be copied and kept in sync with other namespaces where they are needed.

A way around this limitation is to provide custom authentication credentials to Strimzi. There are many tools available that
* let one define their credentials in a central source-of-truth place (e.g. Vault), and
* will keep Kubernetes secrets in given namespaces in sync with the given source of truth

The piece that is currently missing is convincing the Strimzi operator to use the custom credentials instead of the auto-generated ones.

**Describe the solution you'd like**
I'd like to be able to specify the credentials to be used as part of the KafkaUser definition, e.g:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
spec:
  authentication:
    type: scram-sha-512
    secret: kafka-user-secret
```
or
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
spec:
  authentication:
    type: scram-sha-512
    password:
      secretKeyRef:
        name: kafka-user-secret
        key: password
```

**Describe alternatives you've considered**
I've tried tricking the operator into using my credentials by defining a Kubernetes secret with the same name and structure as it normally uses. This gets the job done but is not ideal as the fact that the Strimzi operator takes ownership and control over the provided secret causes conflicts with the cluster management tools used to provision the Secret in the first place. See https://github.com/strimzi/strimzi-kafka-operator/issues/5129#issuecomment-862613056 for more details.

I've also considered taking the auto-generate credentials, storing them in Vault and getting them to the other namespaces that way. The problem with that is that the Vault is no longer the single source of truth which comes with its own set of problems.

**Additional context**
See https://github.com/strimzi/strimzi-kafka-operator/issues/5129 for more context.
