### ISSUE TITLE
Provide ability to set sizeLimit on strimzi-tmp emptyDir volume

### ISSUE THREAD

**Issue by tmojlupo** [strimzi/strimzi-kafka-operator#5340]
**Is your feature request related to a problem? Please describe.**
Our K8s cluster has a policy that blocks objects if sizeLimit is not set for emptyDir volumes.  This is to prevent a single pod from accidentally consuming all of a node's resources and causing impact to other pods running on the same node.  In order to use the Strimzi operator we had to disable that policy on the cluster running the Strimzi operator since there is no way to set that parameter for the kafka and zookeeper statefulsets that are created.

**Describe the solution you'd like**
It would be good to have a parameter within the kafka object that allowed defining a sizeLimit for the emptyDir volume.

**Describe alternatives you've considered**
Possibly in the kafka CRD under spec.kafka.statefulset.emptyDir you can have an object sizeLimit that will set the appropriate size limit for emptyDir with an appropriate default size if it isn't set.  The same could be done for zookeeper.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-prod
spec:
  kafka:
    statefulset:
      emptyDir:
        sizeLimit: 1Gi
  zookeeper:
    statefulset:
      emptyDir:
        sizeLimit: 1Gi
```
