### ISSUE TITLE
MirrorMaker2 resync all messages on topic when restarting

### ISSUE THREAD

**Issue by gricuk** [strimzi/strimzi-kafka-operator#5366]
Hi,
We use strimzi MM2 for syncing our Kafka topics between strimzi Kafka cluster and non-strimzi Kafka cluster.
My config:
```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaMirrorMaker2
metadata:
  name: mirror-maker2-kafka1-to-kafka2
  namespace: test-kafka
spec:
  connectCluster: "target-kafka-cluster"
  version: 2.6.0
  replicas: 1
  clusters:
    - alias: "target-kafka-cluster"
      bootstrapServers: test-kafka1.example.com:9092,test-kafka2.example.com,test-kafka3.example.com
      config:
        group.id: "mirrormaker2-cluster-test-kafka"
        client.id: "mirrormaker2-cluster-test-kafka-consumer"
        config.storage.topic: "mirrormaker2-cluster-test-configs"
        status.storage.topic: "mirrormaker2-cluster-test-status"
        offset.storage.topic: "mirrormaker2-cluster-test-offsets"
    - alias: "test-kafka"
      authentication:
        certificateAndKey:
          certificate: user.crt
          key: user.key
          secretName: kafka-mm2-user
        type: tls
      bootstrapServers: test-kafka-kafka-bootstrap:9093
      config:
        config.storage.replication.factor: 3
        offset.storage.replication.factor: 3
        status.storage.replication.factor: 3
      tls:
        trustedCertificates:
          - secretName: test-kafka-cluster-ca-cert
            certificate: ca.crt
  mirrors:
    - sourceCluster: "test-kafka"
      targetCluster: "target-kafka-cluster"
      sourceConnector:
        config:
          replication.factor: 3
          offset-syncs.topic.replication.factor: 3
          replication.policy.separator: ""
          replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
      heartbeatConnector:
        config:
          heartbeats.topic.replication.factor: 3
      checkpointConnector:
        config:
          checkpoints.topic.replication.factor: 3
      topicsPattern: "topic1,topic2,topic3"
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: mirror-maker-2-metrics
        key: metrics-config.yml

```
but we faced with the following problem:
when I try to add the new topic to MM it restarts and becomes to sync **all messages on all topics from the outset**. It happens each time when I add a new topic. It is affected all topics.
