### ISSUE TITLE
Make resources section in kafka initContainer configurable as this is hardcoded currently

### ISSUE THREAD

**Issue by hari819** [strimzi/strimzi-kafka-operator#5372]
### Discussed in https://github.com/strimzi/strimzi-kafka-operator/discussions/5369

<div type='discussions-op-text'>

<sup>Originally posted by **hari819** July 29, 2021</sup>
Hello Team,

i would like to remove the resources section by adding empty {} in the kafka STS section for the initContainer , because sometimes PODs are unable to start with insufficient cpu error ,  I was able to do this for the main Kafka container using 

  ```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 2.7.0
    replicas: 3
    template:
      pod:
        resources: {} #disable requests
```

but i am unable to set the same for the initContainer , 

  ```
initContainers:
    - name: kafka-init
      image: 'quay.io/strimzi/operator:0.22.1'
      args:
        - /opt/strimzi/bin/kafka_init_run.sh
      resources:
        limits:
          cpu: '1'
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
```

could you please help me on this ,</div>
