### ISSUE TITLE
advertisedHost on a tls listener is not included in Subject Alternate Names in generated certificate

### ISSUE THREAD

**Issue by mark-rushakoff** [strimzi/strimzi-kafka-operator#5447]
**Describe the bug**

When a `kafka` resource includes an internal TLS listener, and the broker configuration specifies an `advertisedHost`, the generated certificate for that broker does not include the specified `advertisedHost` as a Subject Alternate Name.

In my case, I am setting up an internal listener, which has an associated Kubernetes Service, which has an associated Istio VirtualService, which is associated with an Istio Gateway. The routing appears to all be set up correctly, but when I attempt to connect, the client fails to verify the TLS connection, because the certificate does not match the advertisedHost I am connecting to.

**To Reproduce**

Create a minimal Kafka resource, like this:

```yaml
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: k
  namespace: myns
spec:
  kafka:
    version: 2.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        configuration:
          bootstrap:
            alternativeNames:
              - kafka-bootstrap.example.com
          brokers:
            - advertisedHost: kafka-0.example.com # <--- Note the advertisedHost here, on a tls internal listener
              broker: 0
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

Then inspect the certificate for broker-0, dump it through `openssl x509`, and do some formatting to print the SANs in a human friendly way:

```console
$ kubectl --context kind-pipescope -n myns get secret k-kafka-brokers -o jsonpath='{.data.k-kafka-0\.crt}' | base64 --decode | openssl x509 -noout -text | grep DNS | tr , '\n' | cut -d: -f2
k-kafka-brokers.myns.svc
k-kafka-brokers.myns.svc.cluster.local
k-kafka-brokers
k-kafka-brokers.myns
k-kafka-0.k-kafka-brokers.myns.svc.cluster.local
k-kafka-bootstrap.myns.svc
k-kafka-bootstrap.myns.svc.cluster.local
k-kafka-bootstrap
kafka-bootstrap.example.com  <--- bootstrap host is present on the certificate, but no advertisedHost
k-kafka-bootstrap.myns
k-kafka-0.k-kafka-brokers.myns.svc
```

**Expected behavior**

I inferred that the advertisedHost would be part of the SANs for the generated certificate. The docs at https://strimzi.io/docs/operators/latest/using.html#type-GenericKafkaListenerConfigurationBroker-reference appear to state that the advertisedHost will be part of the broker certificates, too.

> You can specify a broker ID and customize the advertised hostname and port in the configuration property of the listener. Strimzi will then automatically configure the advertised address in the Kafka brokers and add it to the broker certificates so it can be used for TLS hostname verification.

**Environment (please complete the following information):**
 - Strimzi version: reproduced locally with 0.23.0, seen in our staging environment with 0.24.0
 - Installation method: YAML files
 - Kubernetes cluster: 1.17.17
 - Infrastructure: AWS, on EC2 nodes, not EKS
