### ISSUE TITLE
Strimzi fails to create a cluster inside a service mesh (Istio)

### ISSUE THREAD

**Issue by ReggieCarey** [strimzi/strimzi-kafka-operator#5519]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**

Attempts to create a Kafka cluster using any from examples/kafka/kafka-*.yaml fails if the target namespace has automatic sidecar injection as per ISTIO service mesh.

The cause of the failure is non-obvious as the Zookeeper infrastructure comes up just fine.

**To Reproduce**
1. Install ISTIO in a K8s cluster
2. Enable side car injection in a target namespace (e.g. target)
3. attempt to create a cluster. (e.g., kubectl apply -n target -f example/kafka/kafka-ephemeral.yaml)

Only the zookeeper pods are created and the cluster never becomes available.

4. edit the namespace to disable sidecar injection
5. the rest of the components start to deploy after the zookeeper instances are restarted without sidecar injection.

**Expected behavior**

It is expected that a company that implements a service mesh can operate kafka clusters within namespaces that are service mesh enabled.

**Environment (please complete the following information):**
 - Strimzi version: [e.g. main, 0.25.0]
 - Installation method: OperatorHub.io
 - Kubernetes cluster: [Kubernetes 1.21]
 - Infrastructure: [onprem baremetal]

**YAML files and logs**

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

To get a full set of logs, I installed without a sidecar, then enabled sidecar in the namespace and then manually terminated all of the pods in the namespace so they could restart within the service mesh.  This allows logs to be collected from the cluster instances as well as the entity operator - these would otherwise never start.

Your "report.sh" script failed on macOS:
```
$ ./report.sh --namespace kafka --cluster my-cluster
./report.sh: line 7: syntax error near unexpected token `newline'
./report.sh: line 7: `<!DOCTYPE html>'
```

[my-cluster-kafka-2.log](https://github.com/strimzi/strimzi-kafka-operator/files/7101365/my-cluster-kafka-2.log)
[my-cluster-entity-operator-655dd879c-vqctd.log](https://github.com/strimzi/strimzi-kafka-operator/files/7101373/my-cluster-entity-operator-655dd879c-vqctd.log)

**Additional context**

**Comment by scholzj** [comment]
This is not a bug. We do not support any integration with Istio.

> Your "report.sh" script failed on macOS:

It seems to work fine for me on my MacOS. Did you donwloaded the actual report script? The error suggests it contains some HTML code instead of bash.

**Comment by manishpython** [comment]
I can also able to reproduce it, is there any workaround to solve this issue? Also there is no such strimzi documentation talk about this issue.

**Comment by sreejesh123** [comment]
The way we integrated STRIMZI with ISTIO, to make it work - on operators and Kafka manifest  you need to exclude  ports by  annotating those which is used by strimzi for inter pod communications. Afaik   effectively saying no sidecar for these ports. Some Example ports   9091,2181,2888,3888

**Comment by hsiaand** [comment]
@sreejesh123 Can you share more detail on your workaround?  Are you using kubectl edit to insert the annotations or update some configmap?

**Comment by hsiaand** [comment]
For anyone interested to use Istio mTLS, my workaround is to enable namespace sidecar injection but exclude zookeeper in sidecar injection.  Since all communication between zookeeper component and brokers are already encrypted by operator setup.

The zookeeper liveness probe failed to execute when iptable rule routes traffic to sidecar.
```
OK=$(echo ruok | nc 127.0.0.1 12181)
```

The following is a snippet of Kafka CRD that needs to be modified
```
...
  zookeeper:
    replicas: 3
    template:
      pod:
        metadata:
          labels:
            sidecar.istio.io/inject: "false"
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
...
```

The output shows all pods in the namespace has sidecar injected (2 containers), except zookeeper
```
% kubectl get po -n strimzi
NAME                                           READY   STATUS    RESTARTS   AGE
kafka-consumer1                                2/2     Running   0          6h43m
kafka-consumer2                                2/2     Running   0          6h42m
sdn-cluster-entity-operator-7cb89d7758-jxr9v   4/4     Running   0          7h11m
sdn-cluster-kafka-0                            2/2     Running   0          7h11m
sdn-cluster-kafka-1                            2/2     Running   0          7h11m
sdn-cluster-kafka-2                            2/2     Running   0          7h11m
sdn-cluster-zookeeper-0                        1/1     Running   0          7h12m
sdn-cluster-zookeeper-1                        1/1     Running   0          7h12m
sdn-cluster-zookeeper-2                        1/1     Running   0          7h12m
strimzi-cluster-operator-587cb79468-dhqfq      2/2     Running   0          14h
```

**Comment by kehao95** [comment]
This issue has been discussed in the istio https://github.com/istio/istio/issues/19280
> The root cause is that zookeeper listens on pod ip only

The solution includes:

**Option 1:** disable sidecar injection for zookeepers
```yaml
...
  zookeeper:
    replicas: 3
    template:
      pod:
        metadata:
          labels:
            sidecar.istio.io/inject: "false"
...
```

**Option 2:** excluded 3888/2888 ports, e.g.

```yaml
      annotations:
        traffic.sidecar.istio.io/excludeInboundPorts: "2888,3888"
        traffic.sidecar.istio.io/excludeOutboundPorts: "2888,3888"
```

Both Option 1/2 will exclude mTLS from zookeepers communications.

**Option 3:** Change zookeepers' config set  `quorumListenOnAllIPs=true`

```
spec.zookeeper.config.quorumListenOnAllIPs: true
```

I haven't tried option 2, will try option 3 which looks most reasonable to me.

**Comment by rasheedamir** [comment]
@scholzj when you say this

> We do not support any integration with Istio.

What do you mean? As mentioned by @hsiaand and @kehao95 we can exclude zookeepers from service mesh

But can we do mTLS between clients and kafka via service mesh or not?

**Comment by scholzj** [comment]
> What do you mean? As mentioned by @hsiaand and @kehao95 we can exclude zookeepers from service mesh
> 
> But can we do mTLS between clients and kafka via service mesh or not?

@rasheedamir I'm not an expert on service mesh - Istio or any other. TBH, I do not really know whether you might be able to make it work or not. When I say that it is supported, I mean with it in this context:
* There was no intentional work done to integrate with it
* There is no testing for such integration

I think there are at least some unsolved issues. For example around how it deals with Strimzi's own mTLS, etc. But if someone made it work and is happy with it, that is fine. It is a community software and anyone can do with it whatever they want. But I have no idea how to do it or whether it will still work in the next release. So I personally do not want to tell anyone that it _works great_ just to tell them after the next release _bad luck, it does not work anymore_.

Our focus right is mainly around the ZooKeeper removal - which is an unrelated effort, but in a way should make some things easier once ZooKeeper is gone.

> Option 3: Change zookeepers' config set quorumListenOnAllIPs=true
But telling from thread, it doesn't seem to be working.

I never used this option. But I'm not aware of any reasons why would it not work. You should be able to set it in the config. So if it does not work for someone in a reasonably recent Strimzi version, please provide your CR and logs and I can have a look at it.

**Comment by rasheedamir** [comment]
thanks @scholzj for quick response

> I think there are at least some unsolved issues. For example around how it deals with Strimzi's own mTLS, etc.

I see this use case has been discussed multiple times on different issues; then I wonder why isn't explicitly mentioned in docs that don't use Strimzi with Istio for mtls between the kafka broker and the applications?

I understand it's opensource and one can contribute and make forks etc.; but for long term it's best that the key contributors  guide the community

**Comment by scholzj** [comment]
I think there are several reasons why it is not listed. First of all, I think projects usually tend to list things they support. Not things they don't support. There are many different projects we never intentionally supported and don't test with. I mean just listing all the different service mesh implementations we _do not support_ would be a long list. Second, there are apparently people using it so then we get people complaining that we say it doesn't work while they use it. 🤷

**Comment by rasheedamir** [comment]
> Second, there are apparently people using it so then we get people complaining that we say it doesn't work while they use it

So, it's kind of a grey area :) try at your own risk! And Strimzi team doesn't provide any guarantee that it will continue to work without any issues in future

To make it bit more interesting; we want to run it on RedHat OpenShift with their supported versions; so, maybe we should open support case to RH and ask their opinion on this topic?

**Comment by sreejesh123** [comment]
Regarding this 

Option 2: excluded 3888/2888 ports, e.g.

 We made our SETUP  work with above  setting in our Kafka yaml  , but only difference is  the excluding up should be provided one line and not comma separated 8inside same string 

I will try to post the actual yaml soon,

**Comment by rasheedamir** [comment]
@sreejesh123 on which k8s distribution are you running it?

**Comment by sreejesh123** [comment]
Google GKE AND ASM mesh (which is ISTIO inside)

**Comment by rasheedamir** [comment]
@scholzj regarding

>  I mean just listing all the different service mesh implementations we do not support would be a long list.

I think the key thing are the principals and the not actual service mesh implementation; given everyone wants to have zero trust based architecture so, using mtls based authentication with kafka seems to be the right way to go; with letting service mesh to handle the certificates and everything

As end user of kafka one won't care how internally kafka handles authn/authz with it's components; but one will dcare about the authn/authz for the client applications which want to communicate with kafka

**Comment by scholzj** [comment]
But we do support mTLS as well as other authentication types as well as authorization. There is no problem with that.

**Comment by sreejesh123** [comment]
Mtls of Kafka works and to expose bootstrap and Kafka broker I felt going with Kafka external ip or ilb works well

**Comment by rasheedamir** [comment]
> we do support mTLS

between client application and kafka? how does it handle the certs rotation etc.? does it use some proxy?

can you plz point me to some documentation?

**Comment by scholzj** [comment]
No, it does not use proxy. It rolls the brokers to rotate certificates. It should be all documented in https://strimzi.io/documentation/

**Comment by njlaw** [comment]
Just as a follow-up in case anyone else runs into this: the original cause of this error has to do with the resolution of hosts in an Istio injected pod.

Without Istio, `getent hosts kubernetes.default` outputs:

```
10.96.0.1       kubernetes.default.svc.cluster.local
```

However, in a pod with an Istio sidecar injection enabled, `getent hosts kubernetes.default` outputs:

```
10.96.0.1       kubernetes.default kubernetes.default.ns.svc.cluster.local
```

This causes the script that determines the cluster domain name to fail:

https://github.com/strimzi/strimzi-kafka-operator/blob/c13930de6ae5ae1cb08526aa2e9a5e2606b61e1a/cluster-operator/scripts/cluster_operator_run.sh#L6

and resolve to `1096.0.1       kubernetes.default kubernetes.default.ns.svc.cluster.local` instead of `cluster.local` which results in the invalid DNS error.

If you set the KUBERNETES_SERVICE_DNS_DOMAIN environment variable, the cluster operator starts and Istio and mTLS work without any issues that we've seen.

I do not understand exactly why `default` is repeated in the getent ouput when Istio is injected.  For some reason with Istio injected a DNS query for `kubernetes.default` with the default search domain of `ns.svc.cluster.local` succeeds and resolves to the correct address.  But regardless, if you set KUBERNETES_SERVICE_DNS_DOMAIN it seems to work.

**Comment by sreejesh123** [comment]
Thank you , this is great,  but how did you set this variable and where ? Can you share manifest or more details,

To confirm strmzi by default communicate with its pods in mtls with in namespace,   Please can you elaborate whe you said you can see mtls works,

**Comment by Hronom** [comment]
I was able to partially launch this, using this configs:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: default-cluster
  annotations:
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 3.6.1
    template:
      pod:
        metadata:
          annotations:
            proxy.istio.io/config: |
              holdApplicationUntilProxyStarts: true
              proxyMetadata:
                ISTIO_META_DNS_CAPTURE: "true"
                ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        configuration:
          useServiceDnsDomain: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.6"
    jvmOptions:
      javaSystemProperties:
        - name: zookeeper.ssl.hostnameVerification
          value: "false"
        - name: zookeeper.ssl.quorum.hostnameVerification
          value: "false"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
  zookeeper:
    template:
      pod:
        metadata:
          annotations:
            proxy.istio.io/config: |
              holdApplicationUntilProxyStarts: true
              proxyMetadata:
                ISTIO_META_DNS_CAPTURE: "true"
                ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    replicas: 3
    config:
      quorumListenOnAllIPs: true
    jvmOptions:
      javaSystemProperties:
        - name: zookeeper.ssl.hostnameVerification
          value: "false"
        - name: zookeeper.ssl.quorum.hostnameVerification
          value: "false"
    storage:
      type: persistent-claim
      size: 100Gi
      deleteClaim: false
  entityOperator:
    template:
      pod:
        metadata:
          annotations:
            proxy.istio.io/config: |
              holdApplicationUntilProxyStarts: true
              proxyMetadata:
                ISTIO_META_DNS_CAPTURE: "true"
                ISTIO_META_DNS_AUTO_ALLOCATE: "true"
    topicOperator: {}
    userOperator: {}
```
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-a
  labels:
    strimzi.io/cluster: default-cluster
spec:
  template:
    pod:
      metadata:
        annotations:
  {{/*            sidecar.istio.io/inject: "false"*/}}
          proxy.istio.io/config: |
            holdApplicationUntilProxyStarts: true
            proxyMetadata:
              ISTIO_META_DNS_CAPTURE: "true"
              ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  replicas: 3
  roles:
    - broker
  jvmOptions:
    javaSystemProperties:
      - name: zookeeper.ssl.hostnameVerification
        value: "false"
      - name: zookeeper.ssl.quorum.hostnameVerification
        value: "false"
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: pool-b
  labels:
    strimzi.io/cluster: default-cluster
spec:
  template:
    pod:
      metadata:
        annotations:
          proxy.istio.io/config: |
            holdApplicationUntilProxyStarts: true
            proxyMetadata:
              ISTIO_META_DNS_CAPTURE: "true"
              ISTIO_META_DNS_AUTO_ALLOCATE: "true"
  replicas: 3
  roles:
    - broker
  jvmOptions:
    javaSystemProperties:
      - name: zookeeper.ssl.hostnameVerification
        value: "false"
      - name: zookeeper.ssl.quorum.hostnameVerification
        value: "false"
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 200Gi
        deleteClaim: false
```


However there appear hard blocker related to this issue https://github.com/strimzi/strimzi-kafka-operator/issues/2266

There no possibility to disable SSL for embedded listeners generated by strimzi. 
Specifically need to set: CONTROLPLANE-9090:PLAINTEXT and REPLICATION-9091:PLAINTEXT for `listener.security.protocol.map`

cc @scholzj

**Comment by cooervo** [comment]
this worked for me:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: default
spec:
  kafka:
  ...
  zookeeper:
    replicas: 3
    template:
      pod:
        metadata:
          labels:
            sidecar.istio.io/inject: "false" # this tells istio to not autoinject for zookeeper pods

    ```
