### ISSUE TITLE
Instana agent attach problem

### ISSUE THREAD

**Issue by canberkkoc** [strimzi/strimzi-kafka-operator#5559]
Hello,

I try to use instana-agent on my k8s cluster but networkpolicies are blocking the communication between instana and kafka pods. I tried to turn around the problem with listener config as this:

```
listeners:
      plain:
        networkPolicyPeers:
          - namespaceSelector:
              matchLabels:
                name: instana
            podSelector:
              matchLabels:
                app.kubernetes.io/name: instana-agent
```

But i couldn't get a solution. Is there a way to give permission to all calls on all ports from a namespace to kafkas.

Strimzi Operator Version : 0.19.0
Kafka Version: 2.5.0
