### ISSUE TITLE
Improve the certificate handling

### ISSUE THREAD

**Issue by sknot-rh** [strimzi/strimzi-kafka-operator#5630]
Currently we've failed to really encapsulate and abstract our certificate handling. What I mean by that is everywhere we pass around a `Secret` which we _happen to know_ contains a key store (broker certificate and key), or truststore (ca certificate). But that requires that the consumer of that `Secret` knows what _type_ of secret is it, and how to decode the values within it into something it can use. 

I think there is value is trying to better encapsulate these concepts, so rather than passing around Secrets we pass around something higher level. For example a `AdminClientSupplier` might accept some Strimzi `Truststore` class and a Strimzi `Keystore` class. Providing Resource Operators for those things (`Truststore` and `Keystore`) would be a logical thing to do. This would provide a path towards being able to abstract where certain credentials are stored (e.g. option to store keys in Vault), and should make the KAO slightly simpler to understand, because there are fewer generic Secrets floating around.

At least that was my motivation for suggesting this, and I'd be interested to know whether people think that's a desirable goal or not (and if they have specific reasons to think it wouldn't work out).

_Originally posted by @tombentley in https://github.com/strimzi/strimzi-kafka-operator/pull/5549#discussion_r714675992_

**Comment by SDBrett** [comment]
Am I correct that you're proposing a singular CR which contains relevant credentials for a Kafka cluster?

I mocked up two manifests to help illustrate my understanding, though I may be way off.


```
apiVersion: v1
kind: KafkaCredential
metadata:
  name: cluster-01-creds
spec:
  truststore:
    dataSource: literal
    truststore: encoded cert
  clientCredentials:
    type: certificate
    certificate:
      dataSource: vault
      secretName: secret/clientCert

---
apiVersion: v1
kind: KafkaCredential
metadata:
  name: cluster-02-creds
spec:
  truststore:
    dataSource: literal
    truststore: encoded cert
  clientCredentials:
    type: plain
    plain:
      dataSource: literal
      userName: user
      password: test123
```
