### ISSUE TITLE
Add per-listener connections.max.reauth.ms support

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#5639]
Apache Kafka provides the `connections.max.reauth.ms` [1] configuration parameter which can be set at broker level so applied on all listeners or even on a specific listener only.
Currently, Strimzi doesn't have support for specifying such a parameter at listener level because the `listener.` prefix is part of the list of the forbidden ones for the `spec.kafka.config` section.
The `connections.max.reauth.ms` would make sense for OAuth and SCRAM authentications enabled on a specific listener so we should add support in the authentication section of listeners via the `KafkaListenerAuthenticationOAuth` and `KafkaListenerAuthenticationScramSha512` classes adding a new field for it.

[1] https://kafka.apache.org/documentation/#brokerconfigs_connections.max.reauth.ms

**Comment by fjbecerra** [comment]
hey, I'd like to work on this, may I be assigned, please?

**Comment by scholzj** [comment]
@ppatierno What is the plan for this? Do you have any idea how should the API look like?

**Comment by OneCricketeer** [comment]
What if there was a config section like

```yml
listenerOverrides:
  name: SASL_SSL  # optional: validate this exists as a configured listener 
  sasl_mechanism: OAUTHBEARER
  spec: 
    connections.max.reauth.ms: 3600000
```

When templated will add
```
listener.name.sasl_ssl.oauthbearer.connections.max.reauth.ms=3600000
```

**Comment by scholzj** [comment]
@ppatierno ^^^ ???

I think it applies in general to all SASL listeners. So, I wonder if it should be just a property of the authentication? E.g.

```yaml
listeners:
  #...
  - name: external
    port: 9094
    type: nodeport
    tls: false
    authentication:
      type: scram-sha-512
      maxReauthMs: 3600000
```
