### ISSUE TITLE
Listener in status reporting name as type of listener

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#5757]
It seems that the listeners information in the `status.listeners` of the `Kafka` CR show the name of the listener but in the `type` field.
For example, the `spec` has:

```yaml
listeners:
    - name: plain
      port: 9092
      tls: false
      type: internal
    - name: tls
      port: 9093
      tls: true
      type: internal
```

the `status` has:

```yaml
listeners:
  - addresses:
    - host: my-cluster-kafka-bootstrap.kafka.svc
      port: 9092
    bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc:9092
    type: plain
  - addresses:
    - host: my-cluster-kafka-bootstrap.kafka.svc
      port: 9093
    bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc:9093
    certificates:
    - |
      -----BEGIN CERTIFICATE-----
      ...
      -----END CERTIFICATE-----
    type: tls
```

so from listener `name: plain` in spec we have `type: plain` in status instead of reflecting `type: internal`.
We should have a new `name` field in the listener status API definition in order to bring the right field from listener declaration and setting the `type` to the actual internal, route, loadbalancer and so on.
At some point we could decide to deprecate and remove the `type` field (it's enough from the name in the listener status check the corresponding type from the listener spec declaration) or just leave it.
