### ISSUE TITLE
Kafka upgrade, with inter broker protocol and log message format as M.m.p, fails with misleading error

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#5767]
Starting from a `Kafka` CR having `spec.kafka.version: 2.8.0` and the corresponding inter broker protocol and log message format as following:

```yaml
config:
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
```

doing an upgrade to `3.0.0`, everything works fine.
If "by mistake", we use something like this as starting point instead:

```yaml
config:
      log.message.format.version: "2.8.0"
      inter.broker.protocol.version: "2.8.0"
```

So not just M.m but M.m.p for above versions, the Kafka upgrade to 3.0.0 fails with following condition:

```yaml
conditions:
    - lastTransitionTime: '2021-10-25T09:25:28.802Z'
      message: >-
        log.message.format.version (2.8.0) and inter.broker.protocol.version
        (2.8.0) used by the brokers have to be lower or equal to the Kafka
        broker version we upgrade from (2.8.0)
      reason: KafkaUpgradeException
      status: 'True'
      type: NotReady
```

which of course doesn't make sense because 2.8.0 is actually lower or equal to 2.8.0.

NOTE:
At same time using M.m.p versions, it seems that during Kafka cluster creation they are considered valid values and Kafka brokers work without any issues.
