### ISSUE TITLE
Metrics Configmap doesn't reload in the kafka broker upon change

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#5778]
**Describe the bug**
A metric, requesttime,  was added to the following configmap. 
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka-metrics
  labels:
    app: strimzi
data:
  kafka-metrics-config.yml: |
    # See https://github.com/prometheus/jmx_exporter for more info about JMX Prometheus Exporter metrics
    lowercaseOutputName: true
    rules:
    # Special cases and very specific rules
    - pattern: kafka.server<type=(.+), name=(.+), clientId=(.+), topic=(.+), partition=(.*)><>Value
      name: kafka_server_$1_$2
      type: GAUGE
      labels:
       clientId: "$3"
       topic: "$4"
       partition: "$5"
    - pattern: kafka.server<type=(.+), user=(.+)><>request-time
      name: kafka_server_$1_requesttime
      type: GAUGE
      labels:
       user: "$2"
```
The added requesttime metric does not show up in prometheus or inside the kafka broker ( seen by the following ) . I can see the metric in the ConfigMap `k -n strimzi-pro get ConfigMap`. 
```
 kubectl -n strimzi-pro exec -ti kafka-cluster-kafka-0 bash
cat /opt/kafka/custom-config/metrics-config.json
```

I have had success in getting this metric working on a development cluster. I used JMXTrans to write the metric to standard out. Then when I had the query correct, I designed the requesttime metric above and demonstrated that it works.  

What is the proper procedure to update kafka metrics via the configmap? 
 
**To Reproduce**
```
kubectl -n strimzi-pro replace -f kafka-metrics-upgrade.yaml
# check to see if the metric showed up. 
 kubectl -n strimzi-pro exec -ti kafka-cluster-kafka-0 bash
cat /opt/kafka/custom-config/metrics-config.json
```

**Expected behavior**
The new metric should have showed up here - `/opt/kafka/custom-config/metrics-config.json`

**Environment (please complete the following information):**
 - Strimzi version: 0.25.0
 - Installation method:  YAML files
 - Kubernetes cluster: k8s 1.18
 - Infrastructure: [Amazon EKS]
