### ISSUE TITLE
PodTemplate tmpDirSizeLimit doesn't affect EntityOperator emptyDir volumes

### ISSUE THREAD

**Issue by herzogf** [strimzi/strimzi-kafka-operator#5789]
**Describe the bug**
Strimzi v0.26.0 introduced tmpDirSizeLimit in PodTemplate to make the emptyDir volume sizes configurable (default = 1Mi, see https://github.com/strimzi/strimzi-kafka-operator/pull/5609. This works like a charm for the zookeeper and kafka parts within the kafka custom resource, BUT:
This PodTemplate is also used in the EntityOperator part of the Kafka resource but the 3 emptyDir volumes in the entity-operator Deployment are not affected by this property, i.e. they stay at sizeLimit = 1Mi.

**To Reproduce**
1. Set up strimzi operator v0.26.0 in OpenShift (e.g. OCP 4.7)
2. Create Custom Resource 'Kafka' (kafka.strimzi.io/v1beta2)
3. Set spec->entityOperator->template->pod->tmpDirSizeLimit = 100Mi
4. Check the created deployment '*-entity-operator' emptyDir volumes strimzi-to-tmp, strimzi-uo-tmp and strimzi-tls-sidecar-tmp -> they're still at 1Mi

**Expected behavior**
The three emptyDir volumes' sizeLimits in deployment '*-entity-operator' should all be set to the tmpDirSizeLimit value.

IF the current behavior was works as designed (i.e. tmpDirSizeLimit in entityOperator just should do nothing) this should definitely be in the docs  - but then we need another feature request to make those 3 emptyDirs for the entityOperator configurable.

**Environment (please complete the following information):**
 - Strimzi version: 0.26.0
 - Installation method: OperatorHub.io
 - Kubernetes cluster: OpenShift 4.7
 - Infrastructure: on-prem

**YAML files and logs**

Relevant kafka custom resource yaml and yaml for the entity-operator deployment generated by the strimzi operator are attached, see [strimzi-entityoperator-yamls.zip](https://github.com/strimzi/strimzi-kafka-operator/files/7426636/strimzi-entityoperator-yamls.zip)

Kafka custom resource yaml snippet:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: local-dev-kafka-cluster
spec:
  entityOperator:
    template:
      pod:
        tmpDirSizeLimit: 100Mi
...
```

entity-operator deployment snippet which defines the volumes (expected: 100Mi, is: 1Mi):
```
      volumes:
        - name: strimzi-to-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: strimzi-uo-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: strimzi-tls-sidecar-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
```

**Additional context**
1Mi tmp emptyDir Volumes break strimzi in our environment as our monitoring tool Instana automatically puts its sensor jar files in each container's /tmp directory. This worked like a charm up to strimzi 0.24.0 but broke when the 1Mi sizeLimit was introduced.
