### ISSUE TITLE
Entity Operator seems to consume a substantial amount of broker resource

### ISSUE THREAD

**Issue by jrivers96** [strimzi/strimzi-kafka-operator#5790]
**Describe the bug**
Entity Operator seems to consume a substantial amount of broker resource
I added the following metric to kafka to understand resource usage related to an individual broker. ( We have a lot of single partition topics ) . 

``` 
   - pattern: kafka.server<type=(.+), user=(.+)><>request-time
      name: kafka_server_$1_requesttime
      type: GAUGE
      labels:
       user: "$2"
```

```
kafka_server_request_requesttime{user=~".*cluster-entity.*."}
```

![RequestPerformance](https://user-images.githubusercontent.com/11034356/139090594-db1bf815-fd98-462f-ae85-e88dc4dfbd56.png)

**To Reproduce**
Look at the following metric. We have rarely have user/topic additions. The plot should be representative of entity operator without any additions to the cluster
```
kafka_server_request_requesttime{user=~".*cluster-entity.*."}
```

**Expected behavior**
I'd expect the entity operator to consume very little broker time. This is critical for us for cluster management purposes and our data is low latency as kafka can go. We also have a stringent SLA for data delivery.  

**Environment (please complete the following information):**
 - Strimzi version: 0.25
 - Installation method: YAML
 - Kubernetes cluster: k8s 1.18
 - Infrastructure: Amazon EKS

**YAML files and logs**

Let me know if you'd like to see anything.
