### ISSUE TITLE
Kafka User Operator keep restarting when the number of KafkaUser is more than 9,000

### ISSUE THREAD

**Issue by pjamenaja** [strimzi/strimzi-kafka-operator#5887]
**Describe the bug**
I created the Kafka cluster using the attached YAML and created the 9,300 KafkaUser. I can see that the User Operator keep restarting and always see the exception below. 

> WARN  BlockedThreadChecker: - Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 28592 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked

**To Reproduce**
1. Create Kafka cluster
2. Create 9,000+ KafkaUser

**Expected behavior**
User Operator should not restart

**Environment (please complete the following information):**
 - Strimzi version: 0.26.0
 - Installation method: Helm Chart
 - Kubernetes cluster: 1.21
 - Infrastructure: Rancher

**YAML files and logs**
This is the error log from User Operator container.
[error5.log.gz](https://github.com/strimzi/strimzi-kafka-operator/files/7533802/error5.log.gz)

This is the YAML of the KafkaUser I created.
[kafka-users.yaml.gz](https://github.com/strimzi/strimzi-kafka-operator/files/7533805/kafka-users.yaml.gz)

This is the YAML of my Kafka cluster.
[kafka-his-gw-cluster.yaml.gz](https://github.com/strimzi/strimzi-kafka-operator/files/7533809/kafka-his-gw-cluster.yaml.gz)

**Comment by pjamenaja** [comment]
I'm not sure if this is something about the `export MALLOC_ARENA_MAX=2` in the `launch_java.sh` or not.

Thanks,
James

**Comment by scholzj** [comment]
9000 is a lot. Not sure it was really designed for this amount. I don't think anyone has tested it for that amount of users. 

I assume you tried to give it more resources or finetune the Java options?

**Comment by pjamenaja** [comment]
> 9000 is a lot. Not sure it was really designed for this amount. I don't think anyone has tested it for that amount of users.
> 
> I assume you tried to give it more resources or finetune the Java options?

Yes, I did try adding block below in the KafkaUser but does not help.
```YAML
  entityOperator:
    topicOperator: {}
    userOperator:
      jvmOptions:
        -Xmx: "4g"
        -Xms: "3g"
        javaSystemProperties:
          - name: vertx.options.blockedThreadCheckInterval
            value: "3000000000"
```
