### ISSUE TITLE
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [my-topic]

### ISSUE THREAD

**Issue by Utkarsh-0211** [strimzi/strimzi-kafka-operator#5921]
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 3
    listeners:
       tls:
          authentication:
               type:tls
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: nodeport
        tls: true
        configuration:
          brokers:
          -  broker: 0
             advertisedHost: 192.168.49.2
          -  broker: 1
             advertisedHost: 192.168.49.2
          -  broker: 2
             advertisedHost: 192.168.49.2
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.8"
      inter.broker.protocol.version: "2.8"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
```
