### ISSUE TITLE
api converter exception on valid user config

### ISSUE THREAD

**Issue by vutkin** [strimzi/strimzi-kafka-operator#5964]
**Describe the bug**
Api converter exception on valid user config when trying convert resources before upgrade till 0.23.0 strimzi operator.

**To Reproduce**
1. Create Custom Resource
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: test
  name: test-user
spec:
  authentication:
    type: scram-sha-512
  authorization:
    acls:
    - operation: Describe
      resource:
        name: test.streams.
        patternType: prefix
        type: transactionalId
    - operation: Write
      resource:
        name: test.streams.
        patternType: prefix
        type: transactionalId
    - operation: Describe
      resource:
        name: test2.streams.
        patternType: prefix
        type: transactionalId
    - operation: Write
      resource:
        name: test2.streams.
        patternType: prefix
        type: transactionalId
    type: simple
```
2. Run command './api-conversion.sh cr --name test-user --kind KafkaUser'
3. See error

Converting KafkaUser resource named test-user from namespace test
KafkaUser resource named test-user in namespace test has been converted
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: PUT at: [...]. Message: KafkaUser.kafka.strimzi.io "test-user" is invalid: spec.authorization.acls.resource.type: Required value. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.authorization.acls.resource.type, message=Required value, reason=FieldValueRequired, additionalProperties={})], group=kafka.strimzi.io, kind=KafkaUser, name=test-user, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=KafkaUser.kafka.strimzi.io "test-user" is invalid: spec.authorization.acls.resource.type: Required value, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:583)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:522)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:487)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:448)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:299)
        at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleReplace(OperationSupport.java:280)
        at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleReplace(BaseOperation.java:875)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.lambda$replace$0(HasMetadataOperation.java:74)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:79)
        at io.fabric8.kubernetes.client.dsl.base.HasMetadataOperation.replace(HasMetadataOperation.java:28)
        at io.strimzi.kafka.api.conversion.cli.ConvertResourceCommand.replace(ConvertResourceCommand.java:82)
        at io.strimzi.kafka.api.conversion.cli.ConvertResourceCommand.convertInKube(ConvertResourceCommand.java:167)
        at io.strimzi.kafka.api.conversion.cli.ConvertResourceCommand.run(ConvertResourceCommand.java:221)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at io.strimzi.kafka.api.conversion.cli.EntryCommand.main(EntryCommand.java:31)

**Expected behavior**
Successfully converted resource

**Environment (please complete the following information):**
 - Strimzi version: [0.22.1]
 - Installation method: [Helm chart]
 - Kubernetes cluster: [e.g. Kubernetes 1.20.9]
 - Infrastructure: [Azure AKS]
