### ISSUE TITLE
Topic operator auto regenerate topic after deleting

### ISSUE THREAD

**Issue by nautiam** [strimzi/strimzi-kafka-operator#5990]
**Describe the bug**
I create a Kafka cluster with Topic Operator. Then I create "my-topic" by using Kafka Topic crd. But when I use CLI to delete topic, it will be regenerate.

**To Reproduce**
1. Create Custom Resource 'Kafka'
2. Create Custom Resource 'KafkaTopic'
3. Go to Zookeeper pod
3. Run command '$ bin/kafka-topics.sh --zookeeper localhost:2181 --delete --topic my-topic'
4. Kafka Topic 'my-topic' is auto regenerated

**Expected behavior**
Topic is deleted and will not be re generated.

**Environment (please complete the following information):**
 - Strimzi version: 0.25.0
 - Installation method: [e.g. YAML files, Helm chart, OperatorHub.io]
 - Kubernetes cluster: OpenShift 4.9
 - Infrastructure: Baremetal

**YAML files and logs**
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    authorization:
      type: simple
    config:
      inter.broker.protocol.version: '2.8'
      log.message.format.version: '2.8'
      transaction.state.log.min.isr: 2
      replica.fetch.max.bytes: 41943040
      max.message.bytes: 10485760
      offsets.topic.replication.factor: 3
    listeners:
      - authentication:
          type: scram-sha-512
        name: plain
        port: 9092
        tls: false
        type: internal
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        tls: true
        type: internal
      - authentication:
          type: scram-sha-512
        name: external
        port: 9094
        tls: true
        type: route
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    storage:
      class: nfs
      deleteClaim: false
      size: 5Gi
      type: persistent-claim
    version: 2.8.0
  kafkaExporter:
    groupRegex: .*
    topicRegex: .*
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    storage:
      class: nfs
      deleteClaim: false
      size: 5Gi
      type: persistent-claim
```

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
  labels:
    strimzi.io/cluster: my-cluster
spec:
  config: {}
  partitions: 10
  replicas: 3
  topicName: my-topic
```

**Additional context**
After regeneration, both partitions and replicas of topic are 1.

**Comment by scholzj** [comment]
It looks like your cluster does not have disabled topic auto-creation. So you have to make sure there are no clients using the topic when you delete it, otherwise they would just recreated it with the default settings (1 partition and 1 replica) when they consume / produce. There are several older issues and discussions about this –> please have a look at them.

PS: NFS storage does not work with Kafka, you should use block storage.

**Comment by nautiam** [comment]
> It looks like your cluster does not have disabled topic auto-creation. So you have to make sure there are no clients using the topic when you delete it, otherwise they would just recreated it with the default settings (1 partition and 1 replica) when they consume / produce. 

I'm pretty sure that there are no clients using the topic. I even tried to create some totally new topics by using KafkaTopic and repeat all the steps, and I get the same issue. The topic is auto regenerated if I deleted it by using CLI or java code.

**Comment by scholzj** [comment]
Well, if the operator recreates it, it would do it with the original settings. There is an easy test for it: disable the topic auto-creation, wait until the brokers roll and try it again. But if it does not help and you think the operator does it, then it would be great if you can provide a DEBUG log from the topic operator to show what it is doing and why.

**Comment by nautiam** [comment]
I tried to remove the Topic Operator when creating Kafka cluster, and now I can delete topic without regeneration.

**Comment by fvaleri** [comment]
Hi @nautiam , I tried your use case and it works as expected:

When I use the following command:

```shell
$ kubectl exec my-cluster-kafka-0 -- bin/kafka-topics.sh --bootstrap-server :9092 --topic my-topic --delete
```

The ZK watcher is notified as soon as the delete operation returns and triggers a new reconciliation: 

```log
2021-12-06 08:32:17,69936 INFO  [ZkClient-EventThread-20-localhost:2181] ZkTopicsWatcher:126 - Topics deleted from ZK for watch 1: [my-topic]
2021-12-06 08:32:17,70834 INFO  [ZkClient-EventThread-20-localhost:2181] ZkTopicsWatcher:142 - Topics created in ZK for watch 1: []
2021-12-06 08:32:18,72096 INFO  [vert.x-eventloop-thread-1] TopicOperator:576 - Reconciliation #506(/brokers/topics 1:-my-topic) KafkaTopic(test/my-topic): Reconciling topic my-topic, k8sTopic:nonnull, kafkaTopic:null, privateTopic:nonnull
2021-12-06 08:32:18,73110 INFO  [OkHttp https://10.96.0.1/...] K8sTopicWatcher:56 - Reconciliation #510(kube =my-topic) KafkaTopic(test/my-topic): event MODIFIED on resource my-topic generation=4, labels={strimzi.io/cluster=my-cluster}
2021-12-06 08:32:19,36817 INFO  [OkHttp https://10.96.0.1/...] K8sTopicWatcher:56 - Reconciliation #513(kube -my-topic) KafkaTopic(test/my-topic): event DELETED on resource my-topic generation=4, labels={strimzi.io/cluster=my-cluster}
2021-12-06 08:32:19,76860 INFO  [vert.x-eventloop-thread-1] K8sTopicWatcher:60 - Reconciliation #530(kube =my-topic) KafkaTopic(test/my-topic): Success processing event MODIFIED on resource my-topic with labels {strimzi.io/cluster=my-cluster}
2021-12-06 08:32:19,77826 INFO  [vert.x-eventloop-thread-1] TopicOperator:576 - Reconciliation #536(kube -my-topic) KafkaTopic(test/my-topic): Reconciling topic null, k8sTopic:null, kafkaTopic:null, privateTopic:null
2021-12-06 08:32:19,77907 INFO  [vert.x-eventloop-thread-1] K8sTopicWatcher:60 - Reconciliation #540(kube -my-topic) KafkaTopic(test/my-topic): Success processing event DELETED on resource my-topic with labels {strimzi.io/cluster=my-cluster}
```

And this is the end result:

```
$ kubectl get kt
NAME                                                                                               CLUSTER      PARTITIONS   REPLICATION FACTOR   READY
consumer-offsets---84e7a678d08f4bd226872e5cdd4eb527fadc1c6a                                        my-cluster   50           3                    True
strimzi-store-topic---effb8e3e057afce1ecf67c3f5d8e4e3ff177fc55                                     my-cluster   1            1                    True
strimzi-topic-operator-kstreams-topic-store-changelog---b75e702040b99be8a9263134de3507fc0cc4017b   my-cluster   1            1                    True
```

You can check what happens in your topic-operator logs when you delete that topic and compare with mine.

**Comment by AvihuHenya** [comment]
> I tried to remove the Topic Operator when creating Kafka cluster, and now I can delete topic without regeneration.

I'm facing with the same problem of recreating topics after deleting them (both KafkaTopic and topic) in one of my Kafka clusters. auto topics creation is unable but the topics still get created (with the unique specs configured in spec.kafka.config of that Kafka cluster). 
can you explain what exactly you did in order to make it work fine?

**Comment by nautiam** [comment]
> I'm facing with the same problem of recreating topics after deleting them (both KafkaTopic and topic) in one of my Kafka clusters. auto topics creation is unable but the topics still get created (with the unique specs configured in spec.kafka.config of that Kafka cluster).
> can you explain what exactly you did in order to make it work fine?

At first, do not use topicOperator
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  entityOperator:
    userOperator: {}
```

Then, write code connect to Kafka Cluster and delete the topic.
