### ISSUE TITLE
Setting up Mutual TLS in Kafka

### ISSUE THREAD

**Issue by mohitruhaan** [strimzi/strimzi-kafka-operator#6041]
Hi all,

I have local Minikube Setup in which i have deployed strimzi following: https://strimzi.io/quickstarts and kafka 2.8.0 (yaml below).

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 2.8.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
        configuration:
          brokerCertChainAndKey:
            secretName: my-cluster-cluster-ca-cert
            certificate: ca.crt
            key: ca.key
      - name: external
        port: 9094
        type: nodeport
        tls: true
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.0"
      inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

I am able to setup one way TLS and stuck while configuring Mutual TLS (Referring to Article: https://dev.to/azure/kafka-on-kubernetes-the-strimzi-way-part-3-od).

I have created a Kakfa User with below yaml:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata: 
  labels: 
    strimzi.io/cluster: my-cluster
  name: my-user
spec: 
  authentication: 
    type: tls
```

After that i transferred this user's secrets: user.p12 and user.password to producer/consumer.

In Producer, i created a keystore using keytool:
`keytool -keystore kafka-auth-keystore.jks -alias kafka-producer -genkey`

And then imported user.p12 into the above keystore. Post that i verified that i can see this user details in my keystore:

[kafka@kafka-producer ~]$ keytool -list -keystore kafka-auth-keystore.jks -storetype JKS -storepass changeit
```
Keystore type: JKS
Keystore provider: SUN

Your keystore contains 3 entries

kafka-producer, Dec 10, 2021, PrivateKeyEntry, 
Certificate fingerprint (SHA-256): 18:C6:0A:0D:FA:2C:74:E7:6C:5E:0B:F9:D4:5B:14:2E:D2:8C:AF:50:DE:17:F1:AD:AF:AF:D8:75:EB:35:96:25
my-user, Dec 10, 2021, PrivateKeyEntry, 
Certificate fingerprint (SHA-256): 79:AE:A1:82:AF:FD:C0:52:1C:87:44:7E:8D:9A:77:D5:04:3D:98:3D:34:97:C8:98:0F:F0:C5:F9:DE:AB:D6:36
my-user-new, Dec 10, 2021, PrivateKeyEntry, 
Certificate fingerprint (SHA-256): 7E:48:73:62:80:2E:CD:8B:AB:1F:65:67:31:51:96:8C:77:81:B4:56:F8:DB:25:D1:CA:5E:F5:31:8C:DE:52:3E
```
[kafka@kafka-producer ~]$ pwd
/home/kafka

[kafka@kafka-producer tmp]$ keytool -list -keystore user.p12 -storetype PKCS12 -storepass Y9o4KEDrwhuM
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

my-user, Dec 15, 2021, PrivateKeyEntry, 
Certificate fingerprint (SHA-256): 79:AE:A1:82:AF:FD:C0:52:1C:87:44:7E:8D:9A:77:D5:04:3D:98:3D:34:97:C8:98:0F:F0:C5:F9:DE:AB:D6:36
[kafka@kafka-producer tmp]$ 

Then i created a client properties file as below:

[kafka@kafka-producer ~]$ cat client-ssl-auth.properties
```
bootstrap.servers=my-cluster-kafka-bootstrap:9093
security.protocol=SSL
ssl.truststore.location=/home/kafka/cacerts-new
ssl.truststore.password=changeit
ssl.keystore.location=/home/kafka/kafka-auth-keystore.jks
ssl.keystore.password=changeit
ssl.key.password=Y9o4KEDrwhuM
```
[kafka@kafka-producer ~]$

Now, when i try to run Producer, i see below error. Can anyone please suggest? Thanks.

kubectl -n kafka exec -ti  kafka-producer -- bin/kafka-console-producer.sh --broker-list my-cluster-kafka-bootstrap:9093 --topic my-topic --producer.config /home/kafka/client-ssl-auth.properties

org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:439)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:290)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:317)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:302)
	at kafka.tools.ConsoleProducer$.main(ConsoleProducer.scala:45)
	at kafka.tools.ConsoleProducer.main(ConsoleProducer.scala)
**Caused by: org.apache.kafka.common.KafkaException: java.security.UnrecoverableKeyException: Get Key failed: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.**
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createSSLContext(DefaultSslEngineFactory.java:268)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.configure(DefaultSslEngineFactory.java:173)
	at org.apache.kafka.common.security.ssl.SslFactory.instantiateSslEngineFactory(SslFactory.java:140)
	at org.apache.kafka.common.security.ssl.SslFactory.configure(SslFactory.java:97)
	at org.apache.kafka.common.network.SslChannelBuilder.configure(SslChannelBuilder.java:73)
	at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:192)
	at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81)
	at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:104)
	at org.apache.kafka.clients.producer.KafkaProducer.newSender(KafkaProducer.java:447)
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:428)
	... 5 more
**Caused by: java.security.UnrecoverableKeyException: Get Key failed: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.**
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:446)
	at java.base/sun.security.util.KeyStoreDelegator.engineGetKey(KeyStoreDelegator.java:90)
	at java.base/java.security.KeyStore.getKey(KeyStore.java:1057)
	at java.base/sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:145)
	at java.base/sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
	at java.base/javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:271)
	at org.apache.kafka.common.security.ssl.DefaultSslEngineFactory.createSSLContext(DefaultSslEngineFactory.java:251)
	... 14 more
Caused by: javax.crypto.BadPaddingException: Given final block not properly padded. Such issues can arise if a bad key is used during decryption.
	at java.base/com.sun.crypto.provider.CipherCore.unpad(CipherCore.java:975)
	at java.base/com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1056)
	at java.base/com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:853)
	at java.base/com.sun.crypto.provider.PBES2Core.engineDoFinal(PBES2Core.java:323)
	at java.base/javax.crypto.Cipher.doFinal(Cipher.java:2202)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.lambda$engineGetKey$0(PKCS12KeyStore.java:387)
	at java.base/sun.security.pkcs12.PKCS12KeyStore$RetryWithZero.run(PKCS12KeyStore.java:276)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineGetKey(PKCS12KeyStore.java:381)
	... 20 more
command terminated with exit code 1
