### ISSUE TITLE
Allow annotation of the <cluster>-zookeeper-nodes secret

### ISSUE THREAD

**Issue by nethershaw** [strimzi/strimzi-kafka-operator#6047]
**Is your feature request related to a problem? Please describe.**
Problem: I have a requirement to instrument my Kafka and ZooKeeper deployments with Datadog's monitoring agent for observability. There is no trouble instrumenting Kafka itself via JMX; [the agent's ZooKeeper integration](https://docs.datadoghq.com/integrations/zk/?tab=containerized), however, is somewhat problematic because of Strimzi's requirement for mutual TLS authentication between ZK nodes. While [it is easy to share the `*-zookeeper-nodes` secret](https://strimzi.io/docs/operators/latest/using.html#configuring-internal-clients-to-trust-cluster-ca-str) with the monitoring agent for authentication if the agent is running in the same namespace that contains the secrets, operational constraints can (and in my case do) require that the agent is running in a namespace separate from Strimzi, so *the problem becomes how to replicate the necessary secret from one namespace to another.*

**Describe the solution you'd like**
Permit annotation of the `*-zookeeper-nodes` secret via resource templates in precisely the same way that annotations of the `clusterCaCert` secret resource are permitted, e.g.:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  # ...
  kafka:
    template:
      # already supported, useful, and working
      clusterCaCert:
        metadata:
          annotations:
            my.secret.replicator/replicate-to: my-other-namespace
  # ...
  zookeeper:
    template:
      # requested enhancement à la spec.kafka.template.clusterCaCert
      zkNodeCerts:
        metadata:
          annotations:
            my.secret.replicator/replicate-to: my-other-namespace
```

This would allow a simple operator to identify the secrets for cross-namespace replication, for which there exist multiple solutions in the wild. Such a solution is already working for me with respect to the `clusterCaCert` secret, and the solution would be complete if only I could apply it to both secrets.

**Describe alternatives you've considered**
I have attempted to authenticate the monitoring agent by enabling the User Operator and having it issue the client its own certificate in its own annotated secret, but this requires enabling ACL management, and the client applications I am supporting must be able to use the Kafka brokers anonymously. Even if that were not the case, the attempt seems unlikely to work, since I would assume user certificates are not valid for authentication to the ZooKeeper nodes anyway.

I have contemplated establishing my own private CA and distributing custom certificates and keys to Strimzi for the cluster's use, but that is vastly more work and infrastructure than seems necessary if Strimzi is already capable of handling the PKI.

I have looked into disabling TLS between the ZooKeepers entirely, but that seems to be an architecturally Bad Idea.

If exporting the ZooKeeper node TLS secrets to other applications should run counter to Strimzi's design, I would ask instead by what means I should approach authorizing such a monitoring client.
