### ISSUE TITLE
KubernetesConfigMapConfigProvider in KafkaConnect not working when no externalConfiguration is provided

### ISSUE THREAD

**Issue by iceman91176** [strimzi/strimzi-kafka-operator#6134]
**Describe the bug**
We are using the KubernetesConfigMapConfigProvider for configuring kafka-connect and its connectors. As long as there is any **externalConfiguration** present in the KafkaConnect specs everything is fine. This externalConfiguration doesn't have to be used by either KafkaConnect or any KafkaConnector, it just need to be defined.
As soon as the externalConfiguration is removed from the KafkaConnect specs the connectors start to fail, because they try to read the properties from a (non-existing) file instead of the configmap (see logfiles). 

**To Reproduce**
1. Create configmaps, roles, rolebindings, KafkaConnect as described here https://strimzi.io/blog/2021/07/22/using-kubernetes-config-provider-to-load-data-from-secrets-and-config-maps/
2. Remove **externalConfiguration** from KafkaConnect Specs (if present)
3. wait until reconciled

**Expected behavior**
The configmap-provider should be used in any case.

**Environment (please complete the following information):**
 - Strimzi version: [0.27.0]
 - Installation method: [Helm chart]
 - Kubernetes cluster: [Kubernetes 1.18]
 - Infrastructure: [Bare Metal]

**YAML files and logs**

Connect-Cluster specs

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  annotations:
    strimzi.io/use-connector-resources: "true"
  name: demo-connect-cluster
  namespace: strimzi-operator
spec:
  authentication:
    accessTokenIsJwt: true
    clientId: demo-connect-cluster
    clientSecret:
      key: client-secret
      secretName: demo-connect-cluster-secret
    tokenEndpointUri: https://xxx/auth/realms/kafka-01/protocol/openid-connect/token
    type: oauth
  bootstrapServers: test-cluster-kafka-bootstrap:9093
  build:
    output:
      image: x.x.x/strimzi/demo-connect-cluster:latest
      pushSecret: k8s01-registry-push
      type: docker
    plugins:
    - artifacts:
      - type: tgz
        url: https://x.x.x/repository/maven-releases/com/github/jcustenborder/kafka-connect-transform-common/0.1.0.36/kafka-connect-transform-common-0.1.0.36.tar.gz
      name: kafka-connect-transform-common
    - artifacts:
      - type: jar
        url: https://packages.confluent.io/maven/io/confluent/kafka-connect-jdbc/5.5.7/kafka-connect-jdbc-5.5.7.jar
      - type: jar
        url: https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/12.2.0.1/ojdbc8-12.2.0.1.jar
      - type: jar
        url: https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/7.2.1.jre11/mssql-jdbc-7.2.1.jre11.jar
      - type: jar
        url: https://repo1.maven.org/maven2/org/mariadb/jdbc/mariadb-java-client/2.1.0/mariadb-java-client-2.1.0.jar
      name: jdbc-connector
    - artifacts:
      - type: tgz
        url: https://repo1.maven.org/maven2/io/apicurio/apicurio-registry-distro-connect-converter/1.3.2.Final/apicurio-registry-distro-connect-converter-1.3.2.Final-converter.tar.gz
      name: apicurio-connect-converter
  config:
    config.providers: file,configmaps
    config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    config.storage.replication.factor: 1
    config.storage.topic: demo-connect-cluster-configs
    group.id: demo-connect-cluster
    key.converter: org.apache.kafka.connect.storage.StringConverter
    offset.storage.replication.factor: 1
    offset.storage.topic: demo-connect-cluster-offsets
    status.storage.replication.factor: 1
    status.storage.topic: demo-connect-cluster-status
    value.converter: io.apicurio.registry.utils.converter.AvroConverter
    value.converter.apicurio.registry.as-confluent: true
    value.converter.apicurio.registry.converter.deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
    value.converter.apicurio.registry.converter.serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
    value.converter.apicurio.registry.global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
    value.converter.apicurio.registry.url: http://${configmaps:strimzi-operator/connect-registry-credentials:registry_username}:${configmaps:strimzi-operator/connect-registry-credentials:registry_password}@test-registry01-apicurio-registry-sql-secure-gateway:8081/api
#  externalConfiguration:
#    volumes:
#    - name: dummy-config
#      secret:
#        secretName: dummy-config
  logging:
    type: external
    valueFrom:
      configMapKeyRef:
        key: log4j.properties
        name: logging-connect-configmap
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        key: connect-metrics-config.yml
        name: kafka-metrics
  replicas: 2
  tls:
    trustedCertificates:
    - certificate: ca.crt
      secretName: test-cluster-cluster-ca-cert
  version: 3.0.0
```

Connector-Spec (just an example, happens with all connectors that are referencing properties from the configmap)

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: demo-connect-cluster
  name: source-ts-itsm-crm-0
  namespace: strimzi-operator
spec:
  class: io.confluent.connect.jdbc.JdbcSourceConnector
  config:
    connection.password: ${configmaps:strimzi-operator/connect-sql-credentials:oracle01_password}
    connection.url: jdbc:oracle:thin:@orcl01svvc1.x.x.x:1521:DB
    connection.user: ${configmaps:strimzi-operator/connect-sql-credentials:oracle01_username}
    mode: timestamp
    .....
  tasksMax: 1
```

Logs (in case of error)

`[demo-connect-cluster-connect-68dcf78785-rh9bm] {"exception":{"stacktrace":"org.apache.kafka.common.config.ConfigException: Could not read properties from file \/opt\/kafka\/external-configuration\/connector-config\/connect-sql-credentials.properties\n\tat org.apache.kafka.common.config.provider.FileConfigProvider.get(FileConfigProvider.java:92)\n\tat org.apache.kafka.common.config.ConfigTransformer.transform(ConfigTransformer.java:103)\n\tat org.apache.kafka.connect.runtime.WorkerConfigTransformer.transform(WorkerConfigTransformer.java:58)\n\tat org.apache.kafka.connect.runtime.distributed.ClusterConfigState.taskConfig(ClusterConfigState.java:164)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnector(DistributedHerder.java:1575)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.reconfigureConnectorTasksWithRetry(DistributedHerder.java:1513)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.lambda$null$29(DistributedHerder.java:1526)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:408)\n\tat org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:326)\n\tat java.base\/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)\n\tat java.base\/java.util.concurrent.FutureTask.run(FutureTask.java:264)\n\tat java.base\/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)\n\tat java.base\/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)\n\tat java.base\/java.lang.Thread.run(Thread.java:829)","exception_class":"org.apache.kafka.common.config.ConfigException","exception_message":"Could not read properties from file \/opt\/kafka\/external-configuration\/connector-config\/connect-sql-credentials.properties"},"source_host":"demo-connect-cluster-connect-68dcf78785-rh9bm","method":"lambda$reconfigureConnectorTasksWithRetry$31","level":"ERROR","message":"[Worker clientId=connect-1, groupId=demo-connect-cluster] Failed to reconfigure connector's tasks (source-ts-itsm-crm-0), retrying after backoff:","mdc":{},"@timestamp":"2022-01-03T15:31:11.804Z","file":"DistributedHerder.java","line_number":"1522","thread_name":"DistributedHerder-connect-1-1","@version":1,"logger_name":"org.apache.kafka.connect.runtime.distributed.DistributedHerder","class":"org.apache.kafka.connect.runtime.distributed.DistributedHerder"}`

Kafka tries to open a properties file with the base-name of the ConfigMap, in that case **connect-sql-credentials**, but this is not present.

Logs (when we add any externalConfiguration to the KafkaConnect specs) - no error here

`[demo-connect-cluster-connect-6897f46998-thxbd] {"@timestamp":"2022-01-03T15:36:20.789Z","source_host":"demo-connect-cluster-connect-6897f46998-thxbd","file":"AbstractKubernetesConfigProvider.java","method":"getResource","level":"INFO","line_number":"113","thread_name":"DistributedHerder-connect-1-1","@version":1,"logger_name":"io.strimzi.kafka.AbstractKubernetesConfigProvider","message":"Retrieving configuration from ConfigMap connect-sql-credentials in namespace strimzi-operator","class":"io.strimzi.kafka.AbstractKubernetesConfigProvider","mdc":{}}`

**Additional context**
As a work around we just add some secret as a volume to the externalConfiguration. This can be empty and/or ave an arbitrary name. It just has to be there.

**Comment by scholzj** [comment]
> Connector-Spec (just an example, happens with all connectors that are referencing properties from the configmap)

Can you share the actual configs to reproduce this? Also, what are the exact steps to reproduce this? Do you get the error with a clean deployment when you just create the two resources you shared above? 

The exception in case of the error suggests that you are not using the Kubernetes Config Map provider at all => It clearly references `FileConfigProvider`. So the error in general seems to be expected, but for some reason from how you describe it Kafka seems to use a wrong configuration provider.

You share the resources without the `.status` sections and didn't share any operator logs. So it is quite hard to understand what is happening there, whether these resources are actually applied by the operator or waiting to be processed and different configurations are applied at that point etc.

**Comment by scholzj** [comment]
I tried similar setup ... not exactly the same, but it follows the points you mentioned:

1) I created my Kafka Connect cluster with this YAML
    ```yaml
    apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaConnect
    metadata:
      annotations:
        strimzi.io/use-connector-resources: "true"
      labels:
        app: my-connect
      name: my-connect
    spec:
      authentication:
        certificateAndKey:
          certificate: user.crt
          key: user.key
          secretName: my-connect
        type: tls
      bootstrapServers: my-cluster-kafka-bootstrap:9093
      config:
        config.providers: file,configmaps
        config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider
        config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
        key.converter: org.apache.kafka.connect.storage.StringConverter
        key.converter.schemas.enable: false
        value.converter: org.apache.kafka.connect.storage.StringConverter
        value.converter.schemas.enable: false
      image: quay.io/scholzj/kafka-connect-build:latest
      metricsConfig:
        type: jmxPrometheusExporter
        valueFrom:
          configMapKeyRef:
            key: connect-metrics.yaml
            name: connect-metrics
      replicas: 1
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      tls:
        trustedCertificates:
        - certificate: ca.crt
          secretName: my-cluster-cluster-ca-cert
    ```
   It has no `externalConfiguration` and uses the same configuration of config providers as you used in your YAML.
2) Next, I create a Config Map with the value I will load:
    ```yaml
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: connector-configuration
    data:
      log.level: WARN
    ```
    It has a field with log level configuration which I will use in my connector.
3) I create the corresponding RBAC resources:
    ```yaml
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: connector-configuration-role
    rules:
    - apiGroups: [""]
      resources: ["configmaps"]
      resourceNames: ["connector-configuration"]
      verbs: ["get"]
    ---
    
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: connector-configuration-role-binding
    subjects:
    - kind: ServiceAccount
      name: my-connect-connect
      namespace: myproject
    roleRef:
      kind: Role
      name: connector-configuration-role
      apiGroup: rbac.authorization.k8s.io
    ```
4) Last, I create the connector:
    ```yaml
    apiVersion: kafka.strimzi.io/v1beta2
    kind: KafkaConnector
    metadata:
      name: echo-sink-connector
      labels:
        strimzi.io/cluster: my-connect
    spec:
      class: EchoSink
      tasksMax: 3
      config:
        level: ${configmaps:myproject/connector-configuration:log.level}
        topics: "kafka-test-apps"
    ```
   I'm using my own connector which just reads messages from topic and logs them at configured log level -> in this case loaded from the Config Map. You can find it [here](https://github.com/scholzj/echo-sink) in case you want to try this step by step. But there is nothing special about it -> it just makes things easy to test.

----

This all seems to work completely fine for me.

**Comment by iceman91176** [comment]
Thanks for looking at it. Your setup looks very similar indeed. The connectors and the Connect-Cluster are "old" deployments which used the FileProvider before. We added the ConfigMapProvider and the configs only recently. So i will try

* clean deployment
* deleting/recreating existing connector

and provide feedback

**Comment by scholzj** [comment]
Did you managed to try it again? Did you still experienced the issue?

**Comment by andreyolv** [comment]
Does the my-connect-connect serviceaccount already exist or has it been created? It is not clear from this example and documentation where this serviceaccount comes from.

How do I define which serviceaccount will be used to get the configmap?

Because I did exactly as this example and in the documentation and I got the following error:
```
'PUT /connectors/inventory-connector/config returned 500 (Internal Server
       Error): Invalid value io.fabric8.kubernetes.client.KubernetesClientException:
       Failure executing: GET at: https://10.96.0.1/api/v1/namespaces/kafka-strimzi/configmaps/jks-files.
       Message: Forbidden!Configured service account doesn''t have access. Service
       account may have been revoked. configmaps "jks-files" is forbidden: User "system:serviceaccount:kafka-strimzi:connect-cluster-connect"
       cannot get resource "configmaps" in API group "" in the namespace "kafka-strimzi".
       for configuration Failed to retrieve ConfigMap jks-files from Kubernetes namespace
       kafka-strimzi'
```

It seems that strimzi uses the connect-cluster-connecto serviceaccount to get the configmap, so what is this example above and the documentation for? Am I missing something?

Thanks

**Comment by andreyolv** [comment]
Example of code in KafkaConnector

```
key.converter.schema.registry.ssl.keystore.location: "${configmaps:kafka-strimzi/jks-files:keystore.jks}"
```

KafkaConnect:
```
config.providers: directory, configmaps
config.providers.directory.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider
```

Roles:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-connect-connect
  namespace: kafka-strimzi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: connector-configuration-role
  namespace: kafka-strimzi
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["jks-files"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: connector-configuration-role-binding
  namespace: kafka-strimzi
subjects:
- kind: ServiceAccount
  name: my-connect-connect
  namespace: kafka-strimzi
roleRef:
  kind: Role
  name: connector-configuration-role
  apiGroup: rbac.authorization.k8s.io
```
