### ISSUE TITLE
Kafka Exporter has **CrashLoopBackOff** and can't recover.

### ISSUE THREAD

**Issue by nautiam** [strimzi/strimzi-kafka-operator#6137]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
Kafka Exporter has **CrashLoopBackOff** and can't recover.

**To Reproduce**
Sometimes, when I create Kafka Cluster and it works. But after a while, the Kafka Exporter has **CrashLoopBackOff** and is always in this status.

`Readiness probe failed: Get "http://10.130.0.49:9404/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)`

**Expected behavior**

**Environment (please complete the following information):**
 - Strimzi version: main
 - Installation method: OperatorHub
 - Kubernetes cluster: Openshift 4.9
 - Infrastructure: BareMetal

**YAML files and logs**

```
[kafka_exporter] [INFO] 2022/01/04 07:38:01 Starting kafka_exporter (version=1.3.1.redhat-00001, branch=master, revision=eb1f5c4229ce4ca51d64d2034926ce64c60e05e9)
[kafka_exporter] [INFO] 2022/01/04 07:38:01 Build context (go=go1.13, user=worker@pnc-ba-pod-4c2d6e, date=20210708-16:03:34)
[kafka_exporter] [INFO] 2022/01/04 07:38:01 Done Init Clients
[kafka_exporter] [INFO] 2022/01/04 07:38:01 Listening on :9404
[kafka_exporter] [INFO] 2022/01/04 07:38:02 Refreshing client metadata
[kafka_exporter] [INFO] 2022/01/04 07:38:05 concurrent calls detected, waiting for first to finish
[kafka_exporter] [INFO] 2022/01/04 07:38:17 concurrent calls detected, waiting for first to finish
[kafka_exporter] [INFO] 2022/01/04 07:38:32 concurrent calls detected, waiting for first to finish
[kafka_exporter] [INFO] 2022/01/04 07:38:35 concurrent calls detected, waiting for first to finish
[kafka_exporter] [INFO] 2022/01/04 07:38:45 concurrent calls detected, waiting for first to finish
[kafka_exporter] [INFO] 2022/01/04 07:38:47 concurrent calls detected, waiting for first to finish
[kafka_exporter] [INFO] 2022/01/04 07:39:05 concurrent calls detected, waiting for first to finish
[kafka_exporter] [INFO] 2022/01/04 07:39:15 concurrent calls detected, waiting for first to finish
[kafka_exporter] [INFO] 2022/01/04 07:39:15 concurrent calls detected, waiting for first to finish
```

**Comment by ppatierno** [comment]
@alesj you did some work on this, any idea? I see it's not upstream Strimzi as well, but an older Red Hat AMQ Streams version (1.3.1). Not sure if your improvements are included in that version and they fixed this problem.

**Comment by nautiam** [comment]
> @alesj you did some work on this, any idea? I see it's not upstream Strimzi as well, but an older Red Hat AMQ Streams version (1.3.1). Not sure if your improvements are included in that version and they fixed this problem.

I'm using Red Hat AMQ Streams version 1.8.4. 
Btw, I see that this bug usually happens when I create cluster with 1 broker and 1 zookeeper.

**Comment by ppatierno** [comment]
> I'm using Red Hat AMQ Streams version 1.8.4.

Yeah sorry, 1.3.1 is clearly the kafka-exporter version not the AMQ Streams one.
I think that version should have some improvements from @alesj 

Is everything up and running and working correctly from Kafka clients point of view when you see this message in the Kafka exporter? 
I mean, is ZK and Kafka pods up and running? Are you able to use Kafka clients to exchange messages without problems.
The Kafka exporter should run some admin calls against the Kafka cluster, not sure if some problems on the cluster side are raising the issue in the exporter.

**Comment by nautiam** [comment]
> Is everything up and running and working correctly from Kafka clients point of view when you see this message in the Kafka exporter?

Yes, the Kafka Broker and Zk pods are still running. I can use Kafka clients to produce and consume messages without any problems. There is only Kafka exporter had crash.

**Comment by scholzj** [comment]
If you are not using Strimzi, you should probably not raise it here but raise this with Red Hat support instead.

**Comment by nautiam** [comment]
I tried to send message to Kafka Cluster and after a while, the Kafka Exporter works again.

**Comment by nautiam** [comment]
I found a reply from author and he said that this is not bug.
[https://issueexplorer.com/issue/danielqsj/kafka_exporter/259](https://issueexplorer.com/issue/danielqsj/kafka_exporter/259)

I want to enable _concurrent.enable_ flag for Kafka exporter. Is there anyway to do it?

**Comment by nautiam** [comment]
> If you are not using Strimzi, you should probably not raise it here but raise this with Red Hat support instead.

I change to use Strimzi 0.27.0 and I still meet this issue.
This is my cluster template.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  entityOperator:
    userOperator: {}
  kafka:
    authorization:
      type: simple
    config:
      inter.broker.protocol.version: '2.8'
      delete.topic.enable: true
      socket.request.max.bytes: 10485760
      client.quota.callback.class: io.strimzi.kafka.quotas.StaticQuotaCallback
      transaction.state.log.replication.factor: 2
      queued.max.requests: 100
      client.quota.callback.static.fetch: 104857600
      client.quota.callback.static.produce: 104857600
      log.message.format.version: '2.8'
      transaction.state.log.min.isr: 1
      replica.fetch.max.bytes: 10485760
      max.message.bytes: 5242880
      offsets.topic.replication.factor: 2
    listeners:
      - authentication:
          type: scram-sha-512
        name: plain
        port: 9092
        tls: false
        type: internal
      - authentication:
          type: scram-sha-512
        name: tls
        port: 9093
        tls: true
        type: internal
      - authentication:
          type: scram-sha-512
        name: external
        port: 9094
        tls: true
        type: route
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    replicas: 2
    storage:
      type: ephemeral
    version: 2.8.0
  kafkaExporter:
    groupRegex: .*
    topicRegex: .*
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 2
    storage:
      type: ephemeral
```

**Comment by scholzj** [comment]
So, can you please share the log from Strimzi 0.27.0?

**Comment by nautiam** [comment]
> So, can you please share the log from Strimzi 0.27.0?

This is the log from kafka-exporter
```
+ exec /usr/bin/tini -w -e 143 -- /tmp/run.sh
I0110 10:09:55.957724      12 kafka_exporter.go:769] Starting kafka_exporter (version=1.4.2, branch=HEAD, revision=0d5d4ac4ba63948748cc2c53b35ed95c310cd6f2)
I0110 10:09:56.070116      12 kafka_exporter.go:929] Listening on HTTP :9404
```

It always get this error
```
Readiness probe failed: Get "http://10.131.1.52:9404/metrics": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

Idk where to get the log of Strimzi? Can you tell me how?

**Comment by scholzj** [comment]
Did you give it enough resources (CPU and memory)?

**Comment by nautiam** [comment]
> Did you give it enough resources (CPU and memory)?

I don't set the limit resources for Kafka-exporter so that it can allocate unlimited resources.

**Comment by scholzj** [comment]
Well, there can be some resources set automatically through LimitRange etc.. It is also unlimited if not set, but that doesn't answer what is available. That is why it is always a good idea to set the resources. I normally give it this in my cluster:
```yaml
    resources:
      requests:
        memory: 256Mi
        cpu: "0.5"
      limits:
        memory: 256Mi
        cpu: "0.5"
```

But it has just a few topics. It might depend on you cluster size what is appropriatte.
