### ISSUE TITLE
extraEnvs doesn't work for cluster operator helm charts

### ISSUE THREAD

**Issue by spenczar** [strimzi/strimzi-kafka-operator#6145]
**Describe the bug**

`extraEnvs` is intended to set extra environment variables used by the cluster operator when deploying with Helm charts. The implementation in #5859 is incorrect - it uses `toYaml` which raises a confusing error, possibly due to typing issues with the Helm YAML.

**To Reproduce**

0. (if this is the first time using Strimzi with Helm) set up your helm system to use strimzi charts:

    ```
    helm repo add strimzi https://strimzi.io/charts/
   ```

1. Update Strimzi repo

    ```
    helm repo update
    ```

2. Use this `values.yaml`:

    ```yaml
    extraEnvs:
      - name: JAVA_OPTS
        value: "-Xms=256m -Xmx=256m"
    ```

3. Run this command:

    ```
    helm template strimzi strimzi/strimzi-kafka-operator --dry-run --version 0.27.0 --debug --values valules.yaml
    ```

**Expected behavior**

Rendered resource definitions in YAML, and a zero exit code, including the following deployment:

```yaml
# Source: strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  labels:
    app: strimzi
    chart: strimzi-kafka-operator-0.27.0
    component: deployment
    release: strimzi-release
    heritage: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      name: strimzi-cluster-operator
      strimzi.io/kind: cluster-operator
  template:
    metadata:
      labels:
        name: strimzi-cluster-operator
        strimzi.io/kind: cluster-operator
    spec:
      serviceAccountName: strimzi-cluster-operator
      volumes:
        - name: strimzi-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
        - name: co-config-volume
          configMap:
            name: strimzi-cluster-operator
      containers:
        - name: strimzi-cluster-operator
          image: quay.io/strimzi/operator:0.27.0
          ports:
            - containerPort: 8080
              name: http
          args:
            - /opt/strimzi/bin/cluster_operator_run.sh
          volumeMounts:
            - name: strimzi-tmp
              mountPath: /tmp
            - name: co-config-volume
              mountPath: /opt/strimzi/custom-config/
          env:
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_OPERATION_TIMEOUT_MS
              value: "300000"
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_ENTITY_OPERATOR_IMAGE
              value: quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
            - name: STRIMZI_DEFAULT_KAFKA_EXPORTER_IMAGE
              value: quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
            - name: STRIMZI_DEFAULT_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
            - name: STRIMZI_DEFAULT_TLS_SIDECAR_CRUISE_CONTROL_IMAGE
              value: quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
            - name: STRIMZI_KAFKA_IMAGES
              value: |                 
                2.8.0=quay.io/strimzi/kafka:0.27.0-kafka-2.8.0
                2.8.1=quay.io/strimzi/kafka:0.27.0-kafka-2.8.1
                3.0.0=quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
            - name: STRIMZI_KAFKA_CONNECT_IMAGES
              value: |                 
                2.8.0=quay.io/strimzi/kafka:0.27.0-kafka-2.8.0
                2.8.1=quay.io/strimzi/kafka:0.27.0-kafka-2.8.1
                3.0.0=quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
            - name: STRIMZI_KAFKA_MIRROR_MAKER_IMAGES
              value: |                 
                2.8.0=quay.io/strimzi/kafka:0.27.0-kafka-2.8.0
                2.8.1=quay.io/strimzi/kafka:0.27.0-kafka-2.8.1
                3.0.0=quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
            - name: STRIMZI_KAFKA_MIRROR_MAKER_2_IMAGES
              value: |                 
                2.8.0=quay.io/strimzi/kafka:0.27.0-kafka-2.8.0
                2.8.1=quay.io/strimzi/kafka:0.27.0-kafka-2.8.1
                3.0.0=quay.io/strimzi/kafka:0.27.0-kafka-3.0.0
            - name: STRIMZI_DEFAULT_TOPIC_OPERATOR_IMAGE
              value: quay.io/strimzi/operator:0.27.0
            - name: STRIMZI_DEFAULT_USER_OPERATOR_IMAGE
              value: quay.io/strimzi/operator:0.27.0
            - name: STRIMZI_DEFAULT_KAFKA_INIT_IMAGE
              value: quay.io/strimzi/operator:0.27.0
            - name: STRIMZI_DEFAULT_KAFKA_BRIDGE_IMAGE
              value: quay.io/strimzi/kafka-bridge:0.21.2
            - name: STRIMZI_DEFAULT_JMXTRANS_IMAGE
              value: quay.io/strimzi/jmxtrans:0.27.0
            - name: STRIMZI_DEFAULT_KANIKO_EXECUTOR_IMAGE
              value: quay.io/strimzi/kaniko-executor:0.27.0
            - name: STRIMZI_DEFAULT_MAVEN_BUILDER
              value: quay.io/strimzi/maven-builder:0.27.0
            - name: STRIMZI_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            
            - name: STRIMZI_FEATURE_GATES
              value: ""
            - name: JAVA_OPTS
              value: "Xms=256m -Xmx=256m"
          livenessProbe:
            httpGet:
              path: /healthy
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /ready
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
            limits:
              cpu: 1000m
              memory: 384Mi
            requests:
              cpu: 200m
              memory: 384Mi
  strategy:
    type: Recreate
```

(note in particular the "JAVA_OPTS" value inside `spec.template.spec.containers[0].env`)

**Environment (please complete the following information):**
 - Strimzi version: 0.27.0
 - Installation method: Helm
 - Kubernetes cluster: N/A
 - Infrastructure: N/A
 - Helm version: `version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}`

**YAML files and logs**

Actual error:

```
Error: YAML parse error on strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml: error converting YAML to JSON: yaml: line 102: did not find expected key
helm.go:81: [debug] error converting YAML to JSON: yaml: line 102: did not find expected key
YAML parse error on strimzi-kafka-operator/templates/060-Deployment-strimzi-cluster-operator.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
	/home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
	/home/circleci/helm.sh/helm/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:240
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newTemplateCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/template.go:73
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
	/usr/local/go/src/runtime/proc.go:204
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1374
```
