### ISSUE TITLE
Logging issues in Kafka

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#622]
When following logging configuration is used in Kafka CR:
```yaml
    logging:
      type: inline
      loggers:
        log4j.rootLogger: INFO
        log4j.logger.kafka.authorizer.logger: INFO
```

The following happens:
* The log4j.properties file seems to have the right content
```
#Do not change this generated file. Logging can be configured in the corresponding kubernetes/openshift resource.

log4j.rootLogger=INFO
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.logger.kafka.authorizer.logger=INFO
log4j.logger.kafka.network.Processor=OFF
log4j.logger.kafka.request.logger=WARN, CONSOLE
log4j.logger.kafka.controller=TRACE
log4j.logger.kafka.network.RequestChannel$=WARN
log4j.logger.org.apache.zookeeper=INFO
log4j.logger.state.change.logger=TRACE
log4j.logger.org.I0Itec.zkclient.ZkClient=INFO
log4j.logger.kafka.server.KafkaApis=OFF
log4j.logger.org.apache.kafka=INFO
log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} %p %m (%c) [%t]%n
kafka.root.logger.level=INFO
log4j.logger.kafka=INFO
log4j.logger.kafka.log.LogCleaner=INFO
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
```
* But the log output contains only following warnings:
```
log4j:WARN No appenders could be found for logger (kafka.utils.Log4jControllerRegistration$).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig  for more info.
```
* Apart from these warnings, only GC logs are printed and nothing else.

Is this caused by the order of the records? Please investigate also the same for other components.

**Comment by scholzj** [comment]
@stanlyDoge Can you have a look at this please on Monday?

**Comment by stanlyDoge** [comment]
Sure

**Comment by stanlyDoge** [comment]
I think `log4j.rootLogger` needs also appender to be set. This configuration should be ok:
```
    logging:
      type: inline
      loggers:
        log4j.rootLogger: DEBUG, CONSOLE
        log4j.logger.kafka.authorizer.logger: INFO
```
