### ISSUE TITLE
Bidirectional data replication not happening in strimzi mirrormaker2

### ISSUE THREAD

**Issue by Raju-kf** [strimzi/strimzi-kafka-operator#6278]
Hello, I am using Strimzi MirrorMaker2 for replicating data between two kafka clusters. Bidirectional data replication is not happening in my case. I'm using strimzi operator 0.26 and kafka 2.8.0. Please let me know any special configuration required to enable bidirectional data replication in following mirrormaker2 configurations.

->From source to target cluster able to replicated topics and data but from target to source data replication is not happening.
->Topics are getting duplicated in both kafka clusters.
-> How can we configure data flow policies from A -> B and B-> A clusters, any example configuration file is there.

Providing my mirrormaker.yaml file
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
 name: my-mirror-maker-2
spec:
 version: 2.8.0
 replicas: 1
 connectCluster: "my-target-cluster"
 clusters:
 - alias: "my-source-cluster"
   bootstrapServers: xxxx:30056
   tls:
     trustedCertificates:
       - secretName: my-cluster-cluster-ca-cert
         certificate: ca.crt
 - alias: "my-target-cluster"
   bootstrapServers: xxxx:30054
   tls:
     trustedCertificates:
       - secretName: my-target-cluster-cluster-ca-cert
         certificate: ca.crt
   config:
     config.storage.replication.factor: -1
     offset.storage.replication.factor: -1
     status.storage.replication.factor: -1
 mirrors:
 - sourceCluster: "my-source-cluster"
   targetCluster: "my-target-cluster"
   sourceConnector:
     config:
       replication.factor: 1
       offset-syncs.topic.replication.factor: 1
       sync.topic.acls.enabled: "false"
       refresh.topics.interval.seconds: 5
   heartbeatConnector:
     config:
       heartbeats.topic.replication.factor: 1
   checkpointConnector:
     config:
       checkpoints.topic.replication.factor: 1
   topicsPattern: ".*"
   groupsPattern: ".*"
 resources:
   requests:
     cpu: 200m
     memory: 2Gi
   limits:
     cpu: 250m
     memory: 2Gi
```

Topics list from source kafka c;usters:

[kafka@my-cluster-kafka-0 kafka]$ ./bin/kafka-topics.sh --bootstrap-server localhost:9092 --list
__consumer_offsets
__strimzi-topic-operator-kstreams-topic-store-changelog
__strimzi_store_topic
cluster-c1
cluster-c1-1
heartbeats
mirrormaker2-cluster-configs
mirrormaker2-cluster-offsets
mirrormaker2-cluster-status
mm2-offset-syncs.my-target-cluster.internal
my-cluster-connect-cluster-configs
my-cluster-connect-cluster-offsets
my-cluster-connect-cluster-status
my-source-cluster.checkpoints.internal
my-source-cluster.cluster-c2
my-source-cluster.heartbeats
my-source-cluster.mirrormaker2-cluster-configs
my-source-cluster.mirrormaker2-cluster-offsets
my-source-cluster.mirrormaker2-cluster-status
my-source-cluster.my-source-cluster.cluster-c1
my-source-cluster.my-source-cluster.cluster-c1-1
my-source-cluster.my-source-cluster.heartbeats
my-source-cluster.my-source-cluster.mirrormaker2-cluster-configs
my-source-cluster.my-source-cluster.mirrormaker2-cluster-offsets
my-source-cluster.my-source-cluster.mirrormaker2-cluster-status
my-source-cluster.my-source-cluster.my-cluster-connect-cluster-configs
my-source-cluster.my-source-cluster.my-cluster-connect-cluster-offsets
my-source-cluster.my-source-cluster.my-cluster-connect-cluster-status
my-source-cluster.my-source-cluster.my-source-cluster.cluster-c2
my-source-cluster.my-source-cluster.my-source-cluster.heartbeats
my-source-cluster.my-source-cluster.my-source-cluster.mirrormaker2-cluster-configs
my-source-cluster.my-source-cluster.my-source-cluster.mirrormaker2-cluster-offsets
my-source-cluster.my-source-cluster.my-source-cluster.mirrormaker2-cluster-status
my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.cluster-c1
my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.cluster-c1-1

Mirrormaker pod logs:

2021-11-08 15:39:24,512 INFO Found 0 new topic-partitions on my-source-cluster. Found 0 deleted topic-partitions on my-source-cluster. Found 41 topic-partitions missing on my-target-cluster. (org.apache.kafka.connect.mirror.MirrorSourceConnector) [Scheduler for MirrorSourceConnector-refreshing topics]
2021-11-08 15:39:24,517 INFO refreshing topics took 21 ms (org.apache.kafka.connect.mirror.Scheduler) [Scheduler for MirrorSourceConnector-refreshing topics]
2021-11-08 15:39:24,518 INFO SourceConnectorConfig values:
        config.action.reload = restart
        connector.class = org.apache.kafka.connect.mirror.MirrorSourceConnector
        errors.log.enable = false
        errors.log.include.messages = false
        errors.retry.delay.max.ms = 60000
        errors.retry.timeout = 0
        errors.tolerance = none
        header.converter = null
        key.converter = null
        name = my-source-cluster->my-target-cluster.MirrorSourceConnector
        predicates = []
        tasks.max = 1
        topic.creation.groups = []
        transforms = []
        value.converter = null
 (org.apache.kafka.connect.runtime.SourceConnectorConfig) [DistributedHerder-connect-1-1]
2021-11-08 15:39:24,518 INFO EnrichedConnectorConfig values:
        config.action.reload = restart
        connector.class = org.apache.kafka.connect.mirror.MirrorSourceConnector
        errors.log.enable = false
        errors.log.include.messages = false
        errors.retry.delay.max.ms = 60000
        errors.retry.timeout = 0
        errors.tolerance = none
        header.converter = null
        key.converter = null
        name = my-source-cluster->my-target-cluster.MirrorSourceConnector
        predicates = []
        tasks.max = 1
        topic.creation.groups = []
        transforms = []
        value.converter = null
 (org.apache.kafka.connect.runtime.ConnectorConfig$EnrichedConnectorConfig) [DistributedHerder-connect-1-1]
2021-11-08 15:39:24,519 WARN Could not create topic my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.target-topic. (org.apache.kafka.connect.mirror.MirrorSourceConnector) [kafka-admin-client-thread | adminclient-13]
org.apache.kafka.common.errors.InvalidTopicException: Topic name is illegal, it can't be longer than 249 characters, topic name: my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.target-topic
2021-11-08 15:39:24,519 WARN Could not create topic my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.mirrormaker2-cluster-offsets. (org.apache.kafka.connect.mirror.MirrorSourceConnector) [kafka-admin-client-thread | adminclient-13]
org.apache.kafka.common.errors.InvalidTopicException: Topic name is illegal, it can't be longer than 249 characters, topic name: my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.mirrormaker2-cluster-offsets
2021-11-08 15:39:24,519 WARN Could not create topic my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.source-topic-nov-1. (org.apache.kafka.connect.mirror.MirrorSourceConnector) [kafka-admin-client-thread | adminclient-13]
org.apache.kafka.common.errors.InvalidTopicException: Topic name is illegal, it can't be longer than 249 characters, topic name: my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.source-topic-nov-1
2021-11-08 15:39:24,519 WARN Could not create topic my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.heartbeats. (org.apache.kafka.connect.mirror.MirrorSourceConnector) [kafka-admin-client-thread | adminclient-13]
org.apache.kafka.common.errors.InvalidTopicException: Topic name is illegal, it can't be longer than 249 characters, topic name: my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.my-source-cluster.heartbeats

**Comment by bertbaron** [comment]
Not sure if I'm hitting the same issue, but with my local test configuration mirror maker always seem to sync to the connectCluster regardless of the value of targetCluster. In other words, it only seems to work correctly if the connectCluster equals the targetCluster in all mirrors.

My configuration:


```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mirrormaker
spec:
  version: 3.0.0
  replicas: 1
  connectCluster: "local"
  clusters:
    - alias: "local"
      bootstrapServers: <my-host-ip>:9092
      config:
        config.storage.replication.factor: 1
        offset.storage.replication.factor: 1
        status.storage.replication.factor: 1
    - alias: "remote"
      bootstrapServers: <my-host-ip>:19092
      config:
        config.storage.replication.factor: 1
        offset.storage.replication.factor: 1
        status.storage.replication.factor: 1
  mirrors:
    - sourceCluster: "local"
      targetCluster: "remote"
      topicsPattern: "topic1"
      sourceConnector:
        tasksMax: 1
        config:
          replication.factor: 1
          offset-syncs.topic.replication.factor: 1
          sync.topic.acls.enabled: "false"
          emit.heartbeats.enabled: "false"
#          replication.policy.class: "org.apache.kafka.connect.mirror.IdentityReplicationPolicy"
```

The clusters are setup with the following docker-compose file:

```yaml
version: '3'
services:
  zookeeper-local:
    image: wurstmeister/zookeeper:3.4.6
    restart: unless-stopped

  kafka-local:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP_ADDRESS:?err}:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-local:2181
      KAFKA_CREATE_TOPICS: "topic1:1:1"
    restart: unless-stopped

  zookeeper-remote:
    image: wurstmeister/zookeeper:3.4.6
    restart: unless-stopped

  kafka-remote:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "19092:9092"
    environment:
      DOCKER_API_VERSION: 1.22
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${HOST_IP_ADDRESS:?err}:19092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-remote:2181
    restart: unless-stopped
```
where HOST_IP_ADDRESS is the ip address of my host

If I use 'remote' as connectCluster the synchronization works fine, if I use local it synchronizes to the local cluster, creating the topic 'local.topic1' on the local cluster.

With the IdentityReplicationPolicy it gets even more ugly because it ends up in a loop sending all messages back to 'topic1' on the local cluster.

I wonder if there is something missing in the configuration resulting in this behavior.
