### ISSUE TITLE
Ability to create custom initContainers in kafka-broker

### ISSUE THREAD

**Issue by KrisMacBP** [strimzi/strimzi-kafka-operator#6339]
### Discussed in https://github.com/strimzi/strimzi-kafka-operator/discussions/6335

Based on the discussion linked, the ability to add our own initContainers would be beneficial. 

I require this to be able to add in other routing mechanism to work with our larger cluster, and im sure that some people may also require this. I thought this is a basic K8s feature to be able to add your own initContainers (And this may be wrong and maybe this is possible with the Kafka CRDs?) but is this something that can be implemented if not?

Referance to K8s docs for initContainers: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

If this is possible and I have totally missed this, please let me know 😄

**Comment by scholzj** [comment]
Did you checked if there are any existing enhancements for this?

**Comment by scholzj** [comment]
Ok, than lets keep this one for triage.

In general, this is IMHO much more complicated than you make it sound:
* It is much more rare than you make it sound. 
* When people need it, they often need to configure way more than just the container => volumes, RBAC rights, security, etc. So it would be very complex to configure it.
* It makes it easy to screw-up many things up and makes it impossible to provide help to users of such clusters because we do not know what might have been broken by such init container.

**Comment by KrisMacBP** [comment]
Im only going off past experience in companies that like to put a few init containers for their own purposes, and when searching it seemed a lot more used 😄  

As above, in most cases it was always running some basic checks and commands, so no need for RBAC rights etc, just volumes normally.

As for the support and help side of things, that i understand, but again if its custom container is company/user specific, then yeah support should not be given in circumstances if the base deploy without the custom initContainers work fine and thus can be easily mentioned that any custom changes as such are not supported and no help can be given 😄 

Could you suggest of potentially another way of doing the above? I guess it would most likely be using a customer docker image based off the current one being used, and injecting the changes there?

**Comment by scholzj** [comment]
> I guess a workaround would most likely be using a customer docker image based off the current one being used, and injecting the changes there?

Well, without knowing what you need the init container to do, it is hard to say what would be a workaround. A custom main container image could help. Maybe you can for example also use Admission Webhooks to inject your init container.

**Comment by KrisMacBP** [comment]
So just as an example, i would require that an init container to attached a configmap as a volume, then to run a script to add routes for the kafka-broker containers to access company specific cluster resources via a secondary nic (added as a part of an annotation).

Fairly similar to the discussion thread actually! 

An example where we have this currently in use is for the Elasticsearch operator:

```yaml
podTemplate:
      spec:
        initContainers:
        - name: int-routes
          image: busybox:1.28
          command: ['sh', '-c', "/mnt/routes_script/run.sh"] 
          volumeMounts:
          - name: routes_script
            mountPath: /mnt/route_script
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: "-Xms15g -Xmx15g"
          resources:
            requests:
              memory: 30Gi
              cpu: 8
            limits:
              memory: 30Gi
        tolerations:
        - key: estype
          operator: Exists
        nodeSelector:
          estype: warm
        volumes:
        - name: routes_script
          configMap:
            name: routes_script
            defaultMode: 0777
      metadata:
        annotations:
          danm.k8s.io/interfaces: '[ {"clusterNetwork":"flannel-local", "ip": "dynamic"}, {"tenantNetwork":"tenant-vxlan", "ip": "dynamic"}]'
```

Elastic CRD ref: https://github.com/elastic/cloud-on-k8s/blob/main/config/crds/v1/bases/elasticsearch.k8s.elastic.co_elasticsearches.yaml - Line 4526 - Or `spec.versions[0].schema.openAPIV3Schema.properties.spec.nodeSets.items.properties.podTemplate.properties.spec.properties.initContainers`

Hopefully that helps :)
