### ISSUE TITLE
Rack Awareness doesn't work with Strimzi Connect

### ISSUE THREAD

**Issue by tsaiboon** [strimzi/strimzi-kafka-operator#6492]
**Describe the bug**
By following Strimzi Documentation, I enabled rack awareness in Connect but I notice my Sink Connector still consuming from leader according the consumer logs in Connect. 

Example by refer cluster and connect logs below, consumer in Connect "odf-connect-cluster-connect-5db9446969-29mxp" which deployed on node label "ip-10-65-202-151", consumed topic "streams-output-sbsb" partition 2 from Kafka 0 which deployed on node label "ip-10-65-201-163" where the partition 2 leader located. 

What I refer:
https://strimzi.io/docs/operators/0.25.0/using.html#proc-kafka-connect-config-str
https://strimzi.io/docs/operators/0.25.0/using.html#type-Rack-reference (The example for KafkaConnect looks wrong, we don't have 'kafka' configuration for KafkaConnect kind.) 

**To Reproduce**
1. Start Kafka with 3 replica & rack awareness enable. I was testing in multi node cluster, so I use node label "kubernetes.io/hostname"
2. Create Kafka Topic with replica 3 and partition 6.
3. Start KafkaConnect with 3 replica & rack awareness enable with logger level DEUBG for class "org.apache.kafka.clients.consumer.internals.Fetcher"
4. Start My Custom Sink Connector to consume from the topic created earlier. 

**Expected behavior**
Connector task consumers should consume the topic partition from Kafka where the same node KafkaConnect deployed. 

Example by refer cluster below, consumer in Connect "odf-connect-cluster-connect-5db9446969-29mxp" which deployed on node label "ip-10-65-202-151", consumed topic "streams-output-sbsb" partition 2 from Kafka 0 which deployed on same node label "ip-10-65-202-151". 

**Environment:**
 - Strimzi version: 0.25.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes v1.21.5

**YAML files and logs**
Kafka Deployment
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
...
spec:
  entityOperator:
    ...
  kafka:
    config:
      inter.broker.protocol.version: "2.8"
      log.message.format.version: "2.8"
      offsets.topic.replication.factor: 3
      replica.selector.class: org.apache.kafka.common.replica.RackAwareReplicaSelector
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      ...
    rack:
      topologyKey: kubernetes.io/hostname
    replicas: 3
    storage:
      ...
    template:
      ...
    version: 2.8.0
  kafkaExporter:
    ...
  zookeeper:
    ...
```

Connect Deployment
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
...
spec:
  bootstrapServers: odf-cluster-kafka-bootstrap:9092
  config:
    config.storage.replication.factor: 1
    config.storage.topic: connect-cluster-configs
    group.id: connect-cluster
    offset.storage.replication.factor: 1
    offset.storage.topic: connect-cluster-offsets
    status.storage.replication.factor: 1
    status.storage.topic: connect-cluster-status
    value.converter.schema.registry.url: http://odf-cluster-schema-registry:8081
  ...
  logging:
    loggers:
      log4j.logger.org.apache.kafka.clients.consumer.internals.Fetcher: DEBUG
    type: inline
  rack:
    topologyKey: kubernetes.io/hostname
  replicas: 3
  template:
    ...
  version: 2.8.0
```

Cluster Allocation
```
$ kubectl get pods -o wide
NAME                                           READY   STATUS    RESTARTS   AGE     IP            NODE               NOMINATED NODE   READINESS GATES
odf-cluster-entity-operator-d9bdd7648-z4qj6    3/3     Running   0          3h5m    10.42.2.88    ip-10-65-201-163   <none>           <none>
odf-cluster-kafka-0                            1/1     Running   0          3h7m    10.42.2.87    ip-10-65-201-163   <none>           <none>
odf-cluster-kafka-1                            1/1     Running   0          3h7m    10.42.1.216   ip-10-65-205-21    <none>           <none>
odf-cluster-kafka-2                            1/1     Running   0          3h7m    10.42.0.103   ip-10-65-202-151   <none>           <none>
odf-cluster-schema-registry-6d7db7646d-szgsr   2/2     Running   5          3h8m    10.42.1.214   ip-10-65-205-21    <none>           <none>
odf-cluster-zookeeper-0                        1/1     Running   0          3h8m    10.42.2.85    ip-10-65-201-163   <none>           <none>
odf-cluster-zookeeper-1                        1/1     Running   0          3h8m    10.42.2.84    ip-10-65-201-163   <none>           <none>
odf-cluster-zookeeper-2                        1/1     Running   0          3h8m    10.42.2.83    ip-10-65-201-163   <none>           <none>
odf-connect-cluster-connect-5db9446969-29mxp   1/1     Running   0          3m26s   10.42.0.109   ip-10-65-202-151   <none>           <none>
odf-connect-cluster-connect-5db9446969-l9c6h   1/1     Running   0          3m26s   10.42.2.92    ip-10-65-201-163   <none>           <none>
odf-connect-cluster-connect-5db9446969-pl465   1/1     Running   0          3m26s   10.42.1.220   ip-10-65-205-21    <none>           <none>
strimzi-cluster-operator-6d4f759d57-vkqjc      1/1     Running   0          3h10m   10.42.1.213   ip-10-65-205-21    <none>           <none>
```

Connect "odf-connect-cluster-connect-5db9446969-29mxp" logs
```
2022-03-09 07:52:45,219 DEBUG [Consumer clientId=connector-consumer-sftpfilestreamsink-1, groupId=connect-sftpfilestreamsink] Added READ_UNCOMMITTED fetch request for partition streams-output-sbsb-2 at position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[odf-cluster-kafka-0.odf-cluster-kafka-brokers.cgf.svc:9093 (id: 0 rack: ip-10-65-201-163)], epoch=0}} to node odf-cluster-kafka-0.odf-cluster-kafka-brokers.cgf.svc:9093 (id: 0 rack: ip-10-65-201-163) (org.apache.kafka.clients.consumer.internals.Fetcher) [task-thread-sftpfilestreamsink-1]
2022-03-09 07:53:04,237 DEBUG [Consumer clientId=connector-consumer-sftpfilestreamsink-1, groupId=connect-sftpfilestreamsink] Added READ_UNCOMMITTED fetch request for partition streams-output-sbsb-3 at position FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[odf-cluster-kafka-2.odf-cluster-kafka-brokers.cgf.svc:9093 (id: 2 rack: ip-10-65-202-151)], epoch=0}} to node odf-cluster-kafka-2.odf-cluster-kafka-brokers.cgf.svc:9093 (id: 2 rack: ip-10-65-202-151) (org.apache.kafka.clients.consumer.internals.Fetcher) [task-thread-sftpfilestreamsink-1]
```

**Additional context**
I did try add "consumer.override.client.rack" with hardcoded value in my Sink Connector and it work as expected. No sure why rack.topologyKey in KafkaConnect not able to control connector task consumer to consume from the Kafka on same rack label.
