### ISSUE TITLE
Kafka Connector partially not working with config.providers.file.class and/or config.providers.directory.class

### ISSUE THREAD

**Issue by BBQigniter** [strimzi/strimzi-kafka-operator#6533]
I have here some Kafka-cluster which is working and a Kafka-Connect-cluster which should use TLS auth also internally the working config now looks like this:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: kafka-test-connect
  namespace: kafka-test
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  replicas: 3
  # if TLS would not work for some reason
  #authentication:
  #  type: SCRAM-SHA-512
  #  username: app-kafka-test-dev-plain
  #  passwordSecret:
  #    secretName: app-kafka-test-dev-plain
  #    password: password
  # mutual TLS auth
  authentication:
    type: tls
    certificateAndKey:
      secretName: app-kafka-test-dev-tls
      certificate: user.crt
      key: user.key
  # plain bootstrap-connection
  #bootstrapServers: kafka-test-kafka-bootstrap:9092
  # mutual TLS bootstrap-connection
  bootstrapServers: kafka-test-kafka-bootstrap:9093
  # needed for TLS auth - comment if SCRAM-SHA-512 without TLS is used!
  tls:
    trustedCertificates:
    - secretName: kafka-test-cluster-ca-cert
      certificate: ca.crt
  config:
    # user needs appropriate ACLs set to be able to create and manage those
    group.id: kafka-test-connect
    offset.storage.topic: kafka-test-connect-offsets
    config.storage.topic: kafka-test-connect-configs
    status.storage.topic: kafka-test-connect-status
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    # additional config parameters (credentials) via file --- see https://strimzi.io/blog/2020/01/27/deploying-debezium-with-kafkaconnector-resource/
    # the rest of the configs can be found at the bottom definitions!
    config.providers: file,directory
    config.providers.file.class: org.apache.kafka.common.config.provider.FileConfigProvider
    config.providers.directory.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
  externalConfiguration:
    volumes:
      # for mysql-connection
      - name: kafka-test-at-main-connector-connector-config
        secret:
          secretName: kafka-test-at-main-connector-mysql-credentials
      # for internal mutual TLS connection to Kafka
      - name: app-kafka-test-dev-tls-config
        secret:
          secretName: app-kafka-test-dev-tls
      - name: kafka-test-cluster-ca-cert-config
        secret:
          secretName: kafka-test-cluster-ca-cert
  # strimzi will download the given connectors
  # it builds a new image
  # pushes it and uses this said image
  build:
    output:
      type: docker
      image: docker.registry.private/sys/strimzi/kafka-connect/kafka-test-connect:latest
      pushSecret: app-kafka-connect-push
      additionalKanikoOptions:
        - "--insecure"
        - "--skip-tls-verify"
    plugins:
      - name: debezium-mysql-connector
        artifacts:
          - type: tgz
            url: http://private.artifactory.com/artifactory/tools/debezium-connectors/debezium-connector-mysql-1.8.1.Final-plugin.tar.gz
            # optional but needs to be checked on your own
            sha512sum: dff3e1f973ab203490d19337fac65e7545fbd70e3f22555e6ca74b3c734160140cbef5905b9f138f8b56616e0af5a41a8b2b7f09497d9cc62f64863017bdc088
  resources:
    requests:
      cpu: 0.5
      memory: 2Gi
    limits:
      cpu: 1.0
      memory: 2Gi
  jvmOptions:
    "-Xmx": "1g"
    "-Xms": "1g"
  logging:
    type: inline
    loggers:
      log4j.rootLogger: "DEBUG"
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: at-main-connector
  namespace: kafka-test
  labels:
    # The strimzi.io/cluster label identifies the KafkaConnect instance
    # in which to create this connector. That KafkaConnect instance
    # must have the strimzi.io/use-connector-resources annotation
    # set to true.
    strimzi.io/cluster: kafka-test-connect
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    database.hostname: "main.db.mysql"
    database.port: "3306"
    include.schema.changes: "false"
    decimal.handling.mode: "string"
    compression.type: "lz4"
    # to create the credentials as secret you have to do the following
    # cat <<EOF > kafka-test-at-main-connector-connector-config-mysql-credentials.properties
    # mysql_username: app_debezium
    # mysql_password: the_password
    # EOF
    #
    # kubectl -n kafka-test create secret generic kafka-test-at-main-connector-mysql-credentials --from-file=kafka-test-at-main-connector-connector-config-mysql-credentials.properties
    database.user: "${file:/opt/kafka/external-configuration/kafka-test-at-main-connector-connector-config/kafka-test-at-main-connector-connector-config-mysql-credentials.properties:mysql_username}"
    database.password: "${file:/opt/kafka/external-configuration/kafka-test-at-main-connector-connector-config/kafka-test-at-main-connector-connector-config-mysql-credentials.properties:mysql_password}"
    database.server.id: "25501010"
    database.server.name: "at"
    database.whitelist: "main"
    database.history.kafka.bootstrap.servers: "kafka-test-kafka-bootstrap:9093"
    database.history.kafka.topic: "at.main.schema"
    # PKCS12 trial general definition
    security.protocol: SSL
    ssl.truststore.type: PKCS12
    # seems not to be working for some reason
    #ssl.truststore.location: "${directory:/opt/kafka/external-configuration/kafka-test-cluster-ca-cert-config/ca.p12}"
    #ssl.truststore.password: "${directory:/opt/kafka/external-configuration/kafka-test-cluster-ca-cert-config/ca.password}"
    ssl.truststore.location: /opt/kafka/external-configuration/kafka-test-cluster-ca-cert-config/ca.p12
    ssl.truststore.password: [hidden]
    ssl.keystore.type: PKCS12
    # seems not to be working for some reason
    #ssl.keystore.location: "${directory:/opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.p12}"
    #ssl.keystore.password: "${directory:/opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.password}"
    ssl.keystore.location: /opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.p12
    ssl.keystore.password: [hidden]
    # PKCS12 config for producer and consumer
    # producer
    database.history.producer.security.protocol: SSL
    database.history.producer.ssl.truststore.type: PKCS12
    # seems not to be working for some reason
    #database.history.producer.ssl.truststore.location: "${directory:/opt/kafka/external-configuration/kafka-test-cluster-ca-cert-config/ca.p12}"
    #database.history.producer.ssl.truststore.password: "${directory:/opt/kafka/external-configuration/kafka-test-cluster-ca-cert-config/ca.password}"
    database.history.producer.ssl.truststore.location: /opt/kafka/external-configuration/kafka-test-cluster-ca-cert-config/ca.p12
    database.history.producer.ssl.truststore.password: [hidden]
    database.history.producer.ssl.keystore.type: PKCS12
    # seems not to be working for some reason
    #database.history.producer.ssl.keystore.location: "${directory:/opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.p12}"
    #database.history.producer.ssl.keystore.password: "${directory:/opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.password}"
    database.history.producer.ssl.keystore.location: /opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.p12
    database.history.producer.ssl.keystore.password: [hidden]
    # consumer
    database.history.consumer.security.protocol: SSL
    database.history.consumer.ssl.truststore.type: PKCS12
    # seems not to be working for some reason
    #database.history.consumer.ssl.truststore.location: "${directory:/opt/kafka/external-configuration/kafka-test-cluster-ca-cert-config/ca.p12}"
    #database.history.consumer.ssl.truststore.password: "${directory:/opt/kafka/external-configuration/kafka-test-cluster-ca-cert-config/ca.password}"
    database.history.consumer.ssl.truststore.location: /opt/kafka/external-configuration/kafka-test-cluster-ca-cert-config/ca.p12
    database.history.consumer.ssl.truststore.password: [hidden]
    database.history.consumer.ssl.keystore.type: PKCS12
    # seems not to be working for some reason
    #database.history.consumer.ssl.keystore.location: "${directory:/opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.p12}"
    #database.history.consumer.ssl.keystore.password: "${directory:/opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.password}"
    database.history.consumer.ssl.keystore.location: /opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.p12
    database.history.consumer.ssl.keystore.password: [hidden]
    database.serverTimezone: "Europe/Vienna"
    database.history.skip.unparseable.ddl: "true"
    table.whitelist: "main.quoten,main.ticketm"
    snapshot.mode: "when_needed"
    snapshot.locking.mode: "none"
    poll.interval.ms: "20"
    value.converter: "org.apache.kafka.connect.json.JsonConverter"
    value.converter.schemas.enable: "false"
    value.converter.include.schema.changes: "false"
    value.converter.include.schema.events: "false"
    value.converter.schemas.infer.enable: "true"
    key.converter: "org.apache.kafka.connect.json.JsonConverter"
    key.converter.include.schema.changes: "false"
    key.converter.include.schema.events: "false"
    key.converter.schemas.enable: "false"
    key.converter.schemas.infer.enable: "true"
    decimal.handling.mode: "string"
    compression.type: "lz4"
    message.key.columns: "main.quoten:i_basegame"
```

I first tried to only define the `ssl.keystore` and `ssl.trusture` parameters with `"${directory:...}"` [as seen in the corresponding documentation in chapter - scroll down to - "Example connector configuration showing placeholders for external values"](https://strimzi.io/docs/operators/latest/configuring.html#property-kafka-connect-external-volumes-reference). But that did not work - I found then following in the logs:

```
2022-03-17 08:41:02,734 INFO [at-main-connector|task-0] ProducerConfig values: 
... removed a few lines to keep it simple
        security.protocol = PLAINTEXT
        security.providers = null
        send.buffer.bytes = 131072
        socket.connection.setup.timeout.max.ms = 30000
        socket.connection.setup.timeout.ms = 10000
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
        ssl.endpoint.identification.algorithm = https
        ssl.engine.factory.class = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.certificate.chain = null
        ssl.keystore.key = null
        ssl.keystore.location = null
        ssl.keystore.password = null
        ssl.keystore.type = JKS
        ssl.protocol = TLSv1.3
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.certificates = null
        ssl.truststore.location = null
        ssl.truststore.password = null
        ssl.truststore.type = JKS
        transaction.timeout.ms = 60000
        transactional.id = null
        value.serializer = class org.apache.kafka.common.serialization.StringSerializer
 (org.apache.kafka.clients.producer.ProducerConfig) [task-thread-at-main-connector-0]
```

So I added `database.history.producer` and `database.history.consumer` configs. After that it looked better in the logs seeing:

```
2022-03-17 10:00:05,538 INFO ProducerConfig values: 
... removed a few lines to keep it simple
        security.protocol = SSL
        security.providers = null
        send.buffer.bytes = 131072
        socket.connection.setup.timeout.max.ms = 30000
        socket.connection.setup.timeout.ms = 10000
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
        ssl.endpoint.identification.algorithm = https
        ssl.engine.factory.class = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.certificate.chain = null
        ssl.keystore.key = null
        ssl.keystore.location = /tmp/kafka/cluster.keystore.p12
        ssl.keystore.password = [hidden]
        ssl.keystore.type = PKCS12
        ssl.protocol = TLSv1.3
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.certificates = null
        ssl.truststore.location = /tmp/kafka/cluster.truststore.p12
        ssl.truststore.password = [hidden]
        ssl.truststore.type = PKCS12
        transaction.timeout.ms = 60000
        transactional.id = null
        value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer
```

But a lot of log-lines later I spotted:

```
2022-03-17 10:00:12,031 INFO [at-main-connector|task-0] ProducerConfig values: 
... removed a few lines to keep it simple
        security.protocol = SSL
        security.providers = null
        send.buffer.bytes = 131072
        socket.connection.setup.timeout.max.ms = 30000
        socket.connection.setup.timeout.ms = 10000
        ssl.cipher.suites = null
        ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
        ssl.endpoint.identification.algorithm = https
        ssl.engine.factory.class = null
        ssl.key.password = null
        ssl.keymanager.algorithm = SunX509
        ssl.keystore.certificate.chain = null
        ssl.keystore.key = null
        ssl.keystore.location = ${directory:/opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.p12}
        ssl.keystore.password = [hidden]
        ssl.keystore.type = PKCS12
        ssl.protocol = TLSv1.3
        ssl.provider = null
        ssl.secure.random.implementation = null
        ssl.trustmanager.algorithm = PKIX
        ssl.truststore.certificates = null
        ssl.truststore.location = ${directory:/opt/kafka/external-configuration/kafka-test-cluster-ca-cert-config/ca.p12}
        ssl.truststore.password = [hidden]
        ssl.truststore.type = PKCS12
        transaction.timeout.ms = 60000
        transactional.id = null
        value.serializer = class org.apache.kafka.common.serialization.StringSerializer
 (org.apache.kafka.clients.producer.ProducerConfig) [task-thread-at-main-connector-0]
2022-03-17 10:00:12,033 ERROR [at-main-connector|task-0] Modification time of key store could not be obtained: ${directory:/opt/kafka/external-configuration/app-kafka-test-dev-tls-config/user.p12} (org.apache.kafka.common.security.ssl.DefaultSslEngineFactory) [task-thread-at-main-connector-0]
```

If I use the config-parameters with `${directory:...` it seems that the producer and consumer configs are not correctly populated later. After I changed the `ssl.keystore...`, `ssl.truststore...`, `database.history.producer.ssl...` and `database.history.consumer...` to "fixed" values it worked and the connector task was finally able to do it's job.

Is that supposed to be like that or did I miss something?
