### ISSUE TITLE
Strimzi Kafka User simple authorization with Oauth2 Authentication

### ISSUE THREAD

**Issue by adbhutrai** [strimzi/strimzi-kafka-operator#6565]
Hi,
I have set up the kafka cluser  with keycloak oauth2 authentication, and it is working as expected. However, I want to use simple authorization and when creating the kafka user, I cannot successfully access the topic from a java client. 
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  entityOperator:
    tlsSidecar: 
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 20m
          memory: 128Mi
    topicOperator: 
      watchedNamespace: test-kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO"
      resources:
        requests:
          memory: 512Mi
          cpu: 50m
        limits:
          memory: 512Mi
          cpu: 100m
    userOperator: 
      watchedNamespace: test-kafka
      reconciliationIntervalSeconds: 60
      logging:
        type: inline
        loggers:
          rootLogger.level: "INFO"
      resources:
        requests:
          memory: 512Mi
          cpu: 100m
        limits:
          memory: 512Mi
          cpu: 200m
  kafka:
    config:
      auto.create.topics.enable: 'false'
      default.replication.factor: 3
      inter.broker.protocol.version: '3.0'
      log.message.format.version: '3.0'
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    authorization:
       type: simple
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - name: tls
        port: 9093
        tls: true
        type: internal
      - authentication:
          clientId: broker
          clientSecret:
            key: secret
            secretName: broker-oauth-secret
          enableOauthBearer: true
          jwksEndpointUri: "https://<keycloak-server>/auth/realms/realm/protocol/openid-connect/certs"
          maxSecondsWithoutReauthentication: 3600
          type: oauth
          userNameClaim: preferred_username
          validIssuerUri: 'https://<keycloak-server>/auth/realms/realm'
        name: external
        port: 9094
        tls: true
        type: route
    logging:
      loggers:
        kafka.root.logger.level: INFO
      type: inline
    replicas: 3
    resources: 
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 1024Gi
        cpu: 200m
    readinessProbe: 
      initialDelaySeconds: 30
      timeoutSeconds: 10
    livenessProbe:
      initialDelaySeconds: 30
      timeoutSeconds: 10
    storage:
      deleteClaim: true
      size: 3Gi
      type: persistent-claim
      class: thin
    version: 3.0.0
  zookeeper:
    logging:
      loggers:
        zookeeper.root.logger: "INFO"
      type: inline
    replicas: 3
    resources:
      requests:
        memory: 512Mi
        cpu: 100m
      limits:
        memory: 1024Mi
        cpu: 200m
    storage:
      deleteClaim: true
      size: 3Gi
      type: persistent-claim
      class: thin
```

My kafka user configuration:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-user
  labels:
    strimzi.io/cluster: my-cluster
  namespace: davy-mq
spec:
  authentication:
    type: tls
  authorization:
    acls:
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Describe
        host: '*'
      - resource:
          type: group
          name: my-group
          patternType: literal
        operation: Read
        host: '*'
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Write
        host: '*'
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Create
        host: '*'
      - resource:
          type: topic
          name: my-topic
          patternType: literal
        operation: Describe
        host: '*'
    type: simple
```
My topic configuration:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
spec:
  config:
    retention.ms: '604800000'
    segment.bytes: '1073741824'
  partitions: 3
  replicas: 3
  topicName: my-topic
```
My java client configuration is:
```
 public static Properties createProperties(KafkaProducerConfig config) {
        Properties props = new Properties();
        props.put(ProducerConfig.BOOTSTRAP_SERVERS_CONFIG, config.getBootstrapServers());
        props.put(ProducerConfig.ACKS_CONFIG, config.getAcks());
        props.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, "org.apache.kafka.common.serialization.StringSerializer");
        props.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG,
                "org.apache.kafka.common.serialization.StringSerializer");

        try {
            File keystore = new ClassPathResource("keystore.jks").getFile();
            out.println("keystore:" + keystore.getAbsolutePath());
            props.put("ssl.truststore.location", keystore.getAbsolutePath());
            props.put("ssl.truststore.password", "password");

        } catch (IOException e) {
            e.printStackTrace();
        }
        System.setProperty(ClientConfig.OAUTH_TOKEN_ENDPOINT_URI,
                "https://<keycloak-server>/auth/realms/realm/protocol/openid-connect/token");
        System.setProperty(ClientConfig.OAUTH_CLIENT_ID, "kafka-producer");
        System.setProperty(ClientConfig.OAUTH_CLIENT_SECRET, "kafka-secret");
        props.put(SaslConfigs.SASL_JAAS_CONFIG,
             "org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required;");
       props.put(CommonClientConfigs.SECURITY_PROTOCOL_CONFIG, SASL_SSL_PROTOCOL);
        props.put(SaslConfigs.SASL_MECHANISM, OAUTH_BEARER);
        props.put(SaslConfigs.SASL_LOGIN_CALLBACK_HANDLER_CLASS, config.SASL_LOGIN_CALLBACK_CLASS);
        return props;
    }
```
I tried to follow the client example from following client example:
https://github.com/strimzi/client-examples/tree/main/java

I am trying to access this I am getting following error:
```
14:32:24.202 [main] DEBUG org.apache.kafka.clients.producer.KafkaProducer - [Producer clientId=producer-1] Exception occurred during message send:
org.apache.kafka.common.errors.TopicAuthorizationException: Not authorized to access topics: [my-topic]
```

Would it be possible for someone to look into this or confirm if this is possible or not?

**Comment by scholzj** [comment]
In your KafkaUser, you have this:

```
  authentication:
    type: tls
```

That will set the ACL rights for user `CN=my-user`. You should leave out the `authentication section if you use the OAuth authentication. That will cause the ACL rights to be set to just `my-user`. And then you need to make sure that your OAuth prefferred username mapes to `my-user`.

In general, for ACL errors its best to check the broker. It normally prints the full error including the username there.

**Comment by adbhutrai** [comment]
Hi @scholzj thank you so much for your quick help. This has helped me in getting the fix for my code. I forgot to remove the authentication section on the user:
```
  authentication:
    type: tls
```
Just for others help generally the preferred_username is in the form of "service-account-<oauth-client-id>". For my case it was "service-account-kafka-producer" so my  kafka user name will be **service-account-kafka-producer** 

A sample kafka user for my case will be:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: my-cluster
  name: service-account-kafka-producer
spec:
  authorization:
    acls:
      - host: '*'
        operation: Read
        resource:
          name: my-topic
          patternType: literal
          type: topic
      - host: '*'
        operation: Describe
        resource:
          name: my-topic
          patternType: literal
          type: topic
      - host: '*'
        operation: Read
        resource:
          name: my-customer-group
          patternType: literal
          type: group
      - host: '*'
        operation: Write
        resource:
          name: my-topic
          patternType: literal
          type: topic
      - host: '*'
        operation: Create
        resource:
          name: my-topic
          patternType: literal
          type: topic
      - host: '*'
        operation: Describe
        resource:
          name: my-topic
          patternType: literal
          type: topic
    type: simple
```
