### ISSUE TITLE
Strimzi duplicate topics

### ISSUE THREAD

**Issue by arekborucki** [strimzi/strimzi-kafka-operator#6578]
**Describe the bug**
Strimzi keeps creating k8s kafkatopic manifests for topics that already exist in the cluster.  It keeps forgetting it has the kafka topics defined in k8s, sees it in kafka so creates another k8s manifest entry which then conflicts with the original. We had this issue already second time on two different clusters 

for example:
`attachments.error-preview                                                                                                 kafka-strimzi   1            3                    True`
`attachments-error-preview---5bece5fa6f351e7abb00c5146bfacc68bc57068d        kafka-strimzi   1            3`

`contacts.exporter.error-preview                                                                    kafka-strimzi   50           3                    True`
`contacts.exporter-error-preview---3221b206c938a823c81ecffcd718be211b2ba50f                         kafka-strimzi   50           3`

**Expected behavior**
Strimzi is not creating duplicate topics

**Environment (please complete the following information):**
 - Strimzi version: 0.27.1
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.21.6
 - Infrastructure: GKE

**YAML files and logs**
report.sh generated file attached  - report-28-03-2022_10-44-47.zip
[report-28-03-2022_10-44-47.zip](https://github.com/strimzi/strimzi-kafka-operator/files/8361309/report-28-03-2022_10-44-47.zip)

**Comment by scholzj** [comment]
Can you maybe explain what the timing is with which the topics are created in Kafka and in Kubernetes? Is it around the same time? Or are the topics created only some time after it existed in Kafka and after you created the initial KafkaTopic CRs?

**Comment by fbuetler** [comment]
Observed the same yesterday with KafkaTopics.
Both are created shortly after each other (order of seconds) in Kubernetes and one is intended but the other one isnt.
Interestingly, that doesnt happend for all created KafkaTopics . 
But the behaviour is the same that one of both is ready and the other one isnt.

**Comment by fbuetler** [comment]
Interestingly, I disabled the auto-creation functionality of topics with `auto.create.topics.enable: "false"` and no user on the cluster has the right to create a topic (`type: topic/cluster`)

**Comment by arekborucki** [comment]
we also have

**Comment by LiamClarkeNZ** [comment]
Hi @arekborucki,

Yep, if an application uses the admin client API to create a topic, then auto.create.topics.enable doesn't apply. That's only used for the "producing/consuming to/from a non-existent topic creates it" functionality.

**Comment by LiamClarkeNZ** [comment]
Hi @arekborucki, 

Glad I could help. :) Does this resolve your issue? If so, okay if we close this issue?

Cheers :)

**Comment by trathborne** [comment]
Strimzi 0.31.0 is still doing this ... on only one of my clusters. A log is attached of the topic-operator container when I create a KafkaTopic 'dev-test' with TopicName 'test'. Almost immediately a KafkaTopic 'test' is created. Then I try to delete it, and then the dev-test topic, and then re-add it. The extra topic is created again. It looks like the operator is trying and failing to log some Events about these failures.

[duplicate-topic-log.txt](https://github.com/strimzi/strimzi-kafka-operator/files/9557359/duplicate-topic-log.txt)

**Comment by trathborne** [comment]
I gave up and turned off delete.topic.enable, then made my k8s resource names match the topic names.

**Comment by runkecheng** [comment]
> Strimzi 0.31.0 is still doing this ... on only one of my clusters. A log is attached of the topic-operator container when I create a KafkaTopic 'dev-test' with TopicName 'test'. Almost immediately a KafkaTopic 'test' is created. Then I try to delete it, and then the dev-test topic, and then re-add it. The extra topic is created again. It looks like the operator is trying and failing to log some Events about these failures.
> 
> [duplicate-topic-log.txt](https://github.com/strimzi/strimzi-kafka-operator/files/9557359/duplicate-topic-log.txt)
> 
> P.S. auto.create.topics.enable = false

Same issue, If the name of KafkaUser must be the same as the Topic name, there is no way to create topic of the same name in different clusters in the same namespace. I guess the reason for this phenomenon is that the config of Kafktopic I created is inconsistent with the Config detected by the topic Operator (It may be caused by inconsistent data types)

**Comment by scholzj** [comment]
> Same issue, If the name of KafkaUser must be the same as the Topic name, there is no way to create topic of the same name in different clusters in the same namespace. I guess the reason for this phenomenon is that the config of Kafktopic I created is inconsistent with the Config detected by the topic Operator (It may be caused by inconsistent data types)

Not sure how KafkaUser fits into this - it has nothing to do with topics. But our recommendations are to have only one Topic Operator per namespace (ideally one Kafka cluster per namespace). Multiple of them watching the same namespace does not work well.

**Comment by Antiarchitect** [comment]
It seems like we faced somewhat similar to this. Has anyone got the solution?

**Comment by mlo82** [comment]
Facing this issue after upgrading from kafka-version 3.3.1 to 3.4.1 in stimzi-operator version 0.36.1.

auto.create.topics.enable was false all the time.

After upgrade was finished i have tow `KafkaTopic`resources. The second one created at time of update with NOT_READY and `InvalidStateStoreException`.

I would expect strimzi to not create a second KafkaTopic-CR when there is one for the topic already.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"kafka.strimzi.io/v1beta2","kind":"KafkaTopic","metadata":{"annotations":{},"labels":{"strimzi.io/cluster":"raikafka-strimzi"},"name":"my-topic","namespace":"kafka-strimzi"},"spec":{"config":{"cleanup.policy":"compact","min.insync.replicas":"2"},"partitions":48,"replicas":3,"topicName":"my_topic"}}
  name: my-topic
  creationTimestamp: '2023-06-14T14:20:56Z'
  generation: 1
  labels:
    strimzi.io/cluster: kafka-strimzi
spec:
  config:
    cleanup.policy: compact
    min.insync.replicas: '2'
  partitions: 48
  replicas: 3
  topicName: my_topic
status:
  conditions:
    - lastTransitionTime: '2023-06-14T14:20:58.643552590Z'
      status: 'True'
      type: Ready
  observedGeneration: 1
  topicName: my_topic

```

 
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  creationTimestamp: '2023-09-27T06:23:27Z'
  generation: 1
  labels:
    strimzi.io/cluster: kafka-strimzi
  name: my-topic---5b115b4fabcc06d17d7e1e738869243ab9287cc5
spec:
  config:
    cleanup.policy: compact
    min.insync.replicas: '2'
  partitions: 48
  replicas: 3
  topicName: my_topic
status:
  conditions:
    - lastTransitionTime: '2023-09-27T06:23:33.150347052Z'
      message: 'The state store, topic-store, may have migrated to another instance.'
      reason: InvalidStateStoreException
      status: 'True'
      type: NotReady
  observedGeneration: 1
  topicName: my_topic
```
