### ISSUE TITLE
Kafka listener certificate

### ISSUE THREAD

**Issue by MathieuTheerensKlarrio** [strimzi/strimzi-kafka-operator#6818]
### Discussed in https://github.com/strimzi/strimzi-kafka-operator/discussions/6809

<div type='discussions-op-text'>

<sup>Originally posted by **MathieuTheerensKlarrio** May 13, 2022</sup>
I've been trying to setup Strimzi using a listener certificate but so far I've always run into troubles. I am using the latest version of the operator and my setup is:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi-cluster
  namespace: kafka
spec:
  kafka:
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "3.1"
      inter.broker.protocol.version: "3.1"
      auto.create.topics.enable: true
      default.replication.factor: 1
      num.partitions: 6
      ssl.enabled.protocols: "TLSv1,TLSv1.2,TLSv1.1"
    version: 3.1.0
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: true
        configuration:
          brokerCertChainAndKey:
            secretName: private-cert
            certificate: ca.crt
            key: ca.key
```

Where `private-cert` is a certificate I create via the following commands:

```
### Create CA
openssl genrsa -out rootCA.key 2048
openssl req -x509 -sha256 -new -nodes -key rootCA.key -days 3650 -out rootCA.crt
openssl pkcs12 -export -in rootCA.crt --nokeys -out rootCA.p12 -password pass:my-password -caname ca.crt

### Create certificate signed by CA
cat > client.ext << EOF
authorityKeyIdentifier=keyid,issuer
basicConstraints=CA:FALSE
subjectAltName = @alt_names

[alt_names]
DNS.1 = *.strimzi-cluster-kafka-brokers
DNS.2 = *.strimzi-cluster-kafka-brokers.kafka.svc
DNS.3 = strimzi-cluster-kafka-bootstrap
DNS.4 = strimzi-cluster-kafka-bootstrap.kafka.svc
EOF


openssl genrsa -out private-cert.key 2048
openssl req -new -key private-cert.key -out private-cert.csr
openssl x509 -req -in private-cert.csr -CA rootCA.crt -CAkey rootCA.key -CAcreateserial -out private-cert.crt -days 825 -sha256 -extfile client.ext
openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in private-cert.key -out private-cert-pkcs8.key
```

I create the secret via 
```
kubectl create secret generic private-cert --from-file=ca.crt=private-cert.crt --from-file=ca.key=private-cert-pkcs8.key -n kafka
```

Every time I try to setup a kafka producer or consumer by deploying the kafka-cli pod to K8s and afterwards connecting to shell and executing:
```
cat > /tmp/props << EOF
security.protocol=SSL
ssl.protocol=SSL
ssl.truststore.type=PEM
ssl.truststore.location=/tmp/private-cert/ca.crt
EOF


kafka-console-producer.sh --producer.config /tmp/props --bootstrap-server strimzi-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092 --topic test-topic-1
```

it gives me the error:
```
javax.net.ssl.SSLProtocolException: Unexpected handshake message: client_hello
```

Can anyone help me with this?</div>
