### ISSUE TITLE
Wrong Zookeeper DNS when deploying Strimzi cluster

### ISSUE THREAD

**Issue by ethanttbui** [strimzi/strimzi-kafka-operator#6821]
**Describe the bug**
When deploying the strimzi cluster, I got this error:
```bash
│ 2022-05-16 11:07:27 WARN  AbstractOperator:532 - Reconciliation #3(watch) Kafka(default/flow-strimzi): Failed to reconcile          │
│ java.lang.IllegalArgumentException: Invalid DNS name: my-app-zookeeper-client.default.svc.::1             kubernetesdefault   │
│     at io.strimzi.certs.Subject$Builder.addDnsName(Subject.java:47) ~[io.strimzi.certificate-manager-0.27.1.jar:0.27.1]             │
│     at io.strimzi.operator.cluster.model.ClusterCa.lambda$generateZkCerts$2(ClusterCa.java:161) ~[io.strimzi.cluster-operator-0.27. │
│     at io.strimzi.operator.cluster.model.Ca.maybeCopyOrGenerateCerts(Ca.java:423) ~[io.strimzi.operator-common-0.27.1.jar:0.27.1]   │
│     at io.strimzi.operator.cluster.model.ClusterCa.generateZkCerts(ClusterCa.java:172) ~[io.strimzi.cluster-operator-0.27.1.jar:0.2 │
│     at io.strimzi.operator.cluster.model.ZookeeperCluster.generateCertificates(ZookeeperCluster.java:569) ~[io.strimzi.cluster-oper │
│     at io.strimzi.operator.cluster.operator.assembly.KafkaAssemblyOperator$ReconciliationState.lambda$zkGenerateCertificates$61(Kaf │
│     at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159) ~[io.vertx.vertx-core-4.2.1.jar:4.2.1]                    │
│     at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100) ~[io.vertx.vertx-core-4.2.1.jar:4.2.1]                 │
│     at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157) ~[io.vertx.vertx-core-4.2.1.jar:4.2.1]         │
│     at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76) ~[io.vertx.vertx-core-4.2.1.jar:4.2.1]                                   │
│     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]                                       │
│     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]                                       │
│     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [io.netty.netty-common-4.1.71.Final.ja │
│     at java.lang.Thread.run(Thread.java:829) [?:?]
```
Obviously, the DNS is incorrect `my-app-zookeeper-client.default.svc.::1             kubernetesdefault`

**To Reproduce**
1. Use default namespace or create a namesspace
2. Install strimzi. I use this [strimzi-cluster-operator-0.27.1.yaml](https://github.com/strimzi/strimzi-kafka-operator/releases/download/0.27.1/strimzi-cluster-operator-0.27.1.yaml) file, after replacing all `my-cluster` namespace with my own namespace (`default` in this example)
```bash
kubectl apply -f k8s/flow-dev/strimzi-cluster-operator.yml -n default
```
4. Create the cluster config:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-app
  namespace: default 
spec:
  kafka:
    version: 2.8.1 
    replicas: 1
    listeners:
      - name: internal
        port: 9092
        type: internal
        tls: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 50Gi
        deleteClaim: false
    config:
      offsets.topic.replication.factor: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 50Gi
      deleteClaim: false
  entityOperator: {}
```
And apply the config:
```bash
kubectl apply -f k8s/flow-dev/strimzi-cluster.yml -n default
```
6. The cluster cannot be created with the error mentioned above

**Expected behavior**
The cluster can be created

**Environment (please complete the following information):**
 - Strimzi version: 0.27.1
 - Installation method: YAML file
 - Kubernetes cluster: Docker Desktop Kubernetes v1.24.0
 - Infrastructure: Mac M1

**Additional context**
I was able to create the cluster before, but somehow it just stopped working all of the sudden. I've tried:
- Using a different namespace
- Restart Docker Desktop
- Restart my PC
- Debug the cluster DNS resolution following [this guide](https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/)

**Comment by scholzj** [comment]
This might be related to the detection of the cluster service domain (https://github.com/strimzi/strimzi-kafka-operator/blob/main/cluster-operator/scripts/cluster_operator_run.sh#L5-L15). It looks like you cluster DNS is somewhat special and the detection does not work? You can probably check the logs from the operator startup as to what it actually provides and if needed override it by setting the `KUBERNETES_SERVICE_DNS_DOMAIN` in the operator deployment.

**Comment by ethanttbui** [comment]
@scholzj Thank you for the prompt reply and the pointer. In fact, I got this within my cluster:
```
[strimzi@strimzi-cluster-operator-7cc4b5759c-kt7br strimzi]$ getent hosts kubernetes.default | head -1 | sed "s/.*\skubernetes.default.svc//" | sed "s/\.//"
::1             kubernetesdefault
```
Do you have any idea how this might happen? I'm sorry, I'm still quite new to Kubernetes. T_T

**Comment by scholzj** [comment]
I guess it would be more interesting to see what just `getent hosts kubernetes.default` does. In my case, I get the following:

```
$ getent hosts kubernetes.default | head -1 | sed "s/.*\skubernetes.default.svc//" | sed "s/\.//"
cluster.local
$ getent hosts kubernetes.default
10.96.0.1       kubernetes.default.svc.cluster.local
```

TBH, I do not sure what is this based on. Might be the worker host etc.

**Comment by ethanttbui** [comment]
Also, using `nslookup`, the result is correct, so I think getent has some bug here?
```bash
root@dnsutils:/# nslookup kubernetes.default
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.96.0.1

root@dnsutils:/# nslookup kubernetes.default.svc
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	kubernetes.default.svc.cluster.local
Address: 10.96.0.1
```

**Comment by scholzj** [comment]
That looks as if your DNS does not automatically expand the `svc` suffix to services. What is in your `/etc/resolv.conf ` file in the pod?

**Comment by ethanttbui** [comment]
For some reason, the cluster works again today... I totally have no idea.
But please feel free to close this thread, I will reopen it if I find anything new.
Thank you for your support @scholzj

**Comment by scholzj** [comment]
Ok, I guess it was just some temporary glitch maybe. DNS is always full of mysteries for me :-o.

**Comment by levi218** [comment]
I got the same issue on:

Strimzi version: 0.29.0
Installation method: Helm 
`helm install strimzi-operator strimzi/strimzi-kafka-operator --namespace kafka  --create-namespace`
Kubernetes cluster: kind 0.13.0
Infrastructure: Windows 10

First line in the operator pod's logs is 
`Auto-detected KUBERNETES_SERVICE_DNS_DOMAIN: ::1 kubernetesdefault`
so I guess it's the same issue. Will try again tomorrow.

**Comment by derketo** [comment]
For anyone else running into this, I had a similar error and was able to resolve it by setting KUBERNETES_SERVICE_DNS_DOMAIN in the 060-Deployment-strimzi-cluster-operator.yaml to force it to use cluster.local when the automatic assignment visible at top of log was setting it to "[IPv6Address] kubernetes.default" as reported here.

I am using kind with a multi-node configuration.

e.g. (in 060-Deployment-strimzi-cluster-operator.yaml)
          env:
            - name: STRIMZI_NAMESPACE
              value: kafka
            - name: KUBERNETES_SERVICE_DNS_DOMAIN
              value: "cluster.local"

All then works as advertised.

I tried setting:

**Comment by tanlda** [comment]
For who install the operator by using helm chart at https://artifacthub.io/packages/helm/strimzi/strimzi-kafka-operator, you can set as below and it will work:

```yaml
extraEnvs:
  - name: KUBERNETES_SERVICE_DNS_DOMAIN
    value: "cluster.local"
```
