### ISSUE TITLE
KafkaUsers do not show any ready state when there is no authorization type on the cluster CR

### ISSUE THREAD

**Issue by matzew** [strimzi/strimzi-kafka-operator#6842]
With Strimzi 0.26+

Creating a `Kafkas` cluster, pretty much like:
https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/kafka/kafka-ephemeral.yaml

And than adding a user, pretty much like:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: my-tls-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: "*"
        operation: Describe
        host: "*"
      - resource:
          type: group
          name: "*"
        operation: Read
        host: "*"
      - resource:
          type: topic
          name: "*"
        operation: Write
        host: "*"
      - resource:
          type: topic
          name: "*"
        operation: Create
        host: "*"
      - resource:
          type: topic
          name: "*"
        operation: Describe
        host: "*"
```

The user does not render any `READY` state - they stay idle (I know the cluster is not setup for this):

```bash
k get kafkausers.kafka.strimzi.io -A 
NAMESPACE   NAME          CLUSTER      AUTHENTICATION   AUTHORIZATION   READY
default     my-tls-user   my-cluster   tls              simple          
➜  ~ 
```

Given that the cluster is not correct configured, and lacks the authorization type, I was expecting those users turn into READY:FALSE, also with a reason on the _why_ it is not ready.

E.g. like:

```yaml
    - name: Reason
      type: string
      jsonPath: ".status.conditions[?(@.type==\"Ready\")].reason"
```

on the `additionalPrinterColumns` section
