### ISSUE TITLE
Fails to reconcile users

### ISSUE THREAD

**Issue by ctron** [strimzi/strimzi-kafka-operator#6944]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**

Starting with one of the recent versions, and a bigger number of `KafkaUser` resources (~100), the user reconciliation fails.

**To Reproduce**
1. Deploy
2. Create kafka cluster
3. Create topics and users

**Expected behavior**

This should not fail

**Environment (please complete the following information):**
 - Strimzi version: 0.28
 - Installation method: Openshift Marketplace
 - Kubernetes cluster: OpenShift 4.10.16
 - Infrastructure: libvirt

**YAML files and logs**

zookeeper:

```
2022-06-15 14:00:56,593 INFO Authenticated Id 'CN=cluster-operator,O=io.strimzi' for Scheme 'x509' (org.apache.zookeeper.server.auth.X509AuthenticationProvider) [nioEventLoopGroup-7-2]
2022-06-15 14:00:56,602 INFO Committing global session 0x100000634a50373 (org.apache.zookeeper.server.quorum.LeaderSessionTracker) [CommitProcessor:1]
2022-06-15 14:00:57,444 INFO Submitting global closeSession request for session 0x100000634a50373 (org.apache.zookeeper.server.ZooKeeperServer) [RequestThrottler]
```

user-operator:

```
2022-06-15 14:00:59 INFO NetworkClient:797 - [AdminClient clientId=adminclient-1] Disconnecting from node 0 due to request timeout.
2022-06-15 14:00:59 INFO NetworkClient:341 - [AdminClient clientId=adminclient-1] Cancelled in-flight DESCRIBE_CLIENT_QUOTAS request with correlation id 427 due to node 0 being disconnected (elapsed time since creation: 35ms, elapsed time since send: 35ms, request timeout: 34ms)
```

Example user status section:

```yaml
status:
  conditions:
    - lastTransitionTime: '2022-06-15T15:13:57.672092Z'
      message: 'Timed out waiting for a node assignment. Call: describeClientQuotas'
      reason: TimeoutException
      status: 'True'
      type: NotReady
  observedGeneration: 1
  secret: user-asdf
  username: user-asdf
```

**Additional context**
