### ISSUE TITLE
OAuth 2.0 (keycloak) with self-signed certs causes kafka-kafka-{0,1,2} pods to crashloop backoff

### ISSUE THREAD

**Issue by anthony-zawacki** [strimzi/strimzi-kafka-operator#6967]
When configuring the operator with a Kafka object, the kafka pods crash during start up with

```
$ kubectl logs --previous -n strimzi-kafka kafka-kafka-0 | grep Caused 
Caused by: java.lang.RuntimeException: Failed to fetch public keys needed to validate JWT signatures: https://keycloak-[fqdn]/auth/realms/OIDC/protocol/openid-connect/certs
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

While some information has been redacted, all hostnames that include [fqdn] are resolvable in DNS using that hostname.  In places labeled [sensitive], an internal project name has been redacted, but all related names are valid for where they are used.

**Expected behavior**
Kafka to be able to fetch the public keys required for JWT validation.

**Environment (please complete the following information):**
 - Strimzi version: 0.28.0 (kafka 3.1.0)
 - Installation method: Operator installed via helm
 - Kubernetes cluster: v1.21.5-eks-9017834
 - Infrastructure: Amazon EKS
 - keycloak 15.0.2
 - istio 1.10.1

A bit more background:

Our environment has a root self-signed cert managed by an external entity.  They have provided our kubernetes cluster with an intermediate cert, which we've loaded into cert-manager.  Using cert-manager, we've created certificates for Keycloak and Kafka.
Keycloak and istio are already deployed into the cluster.  Keycloak is protected by istio requiring mutual TLS to access the pod using the internal service name.  We're using terraform to create the strimzi-kafka namespace, copy the keycloak certificates from the istio-system namespace into the strimzi-kafka namespace and, deploy strimzi-kafka.  (We recognize that this doesn't handle certificate renewals and recognize that we will have to examine some mechanism for secret replication between namespaces.)  While it shouldn't impact this scenario, istio is configured with a gateway for all of the kafka hostnames (kafka, kafka-0, kafka-1, and kafka-2) with tls.mode = PASSTHROUGH, so kafka is terminating inbound connections.  The keycloak URL provided to kafka is the virtualservice name provided to keycloak, meaning it's accessible via the intranet in use for this cluster.  We've confirmed within another pod within the cluster that the pods can access the external url for keycloak without issue.

**YAML files and logs**

Our kafka configuration:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: strimzi-kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    authorization:
      clientId: oidc-client
      delegateToKafkaAcls: true
      superUsers:
      - User:service-account-oidc-client
      tokenEndpointUri: https://keycloak-[fqdn]/auth/realms/OIDC/protocol/openid-connect/token
      type: keycloak
    config:
      log.message.format.version: "2.8"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - authentication:
        jwksEndpointUri: https://keycloak-[fqdn]/auth/realms/OIDC/protocol/openid-connect/certs
        maxSecondsWithoutReauthentication: 3600
        tlsTrustedCertificates:
        - certificate: ca.crt
          secretName: keycloak-[sensitive]-cert
        type: oauth
        userNameClaim: preferred_username
        validIssuerUri: https://keycloak-[fqdn]/auth/realms/OIDC
      configuration:
        brokerCertChainAndKey:
          certificate: tls.crt
          key: tls.key
          secretName: kafka-external-cert
        brokers:
        - advertisedHost: kafka-0.[fqdn]
          broker: 0
        - advertisedHost: kafka-1.[fqdn]
          broker: 1
        - advertisedHost: kafka-2.[fqdn]
          broker: 2
      name: external
      port: 9094
      tls: true
      type: internal
    - authentication:
        jwksEndpointUri: https://keycloak-[fqdn]/auth/realms/OIDC/protocol/openid-connect/certs
        maxSecondsWithoutReauthentication: 3600
        type: oauth
        userNameClaim: preferred_username
        validIssuerUri: https://keycloak-[fqdn]/auth/realms/OIDC
      configuration:
        brokerCertChainAndKey:
          certificate: tls.crt
          key: tls.key
          secretName: kafka-internal-cert
      name: internal
      port: 9093
      tls: true
      type: internal
    - authentication:
        jwksEndpointUri: https://keycloak-[fqdn]/auth/realms/OIDC/protocol/openid-connect/certs
        maxSecondsWithoutReauthentication: 3600
        type: oauth
        userNameClaim: preferred_username
        validIssuerUri: https://keycloak-[fqdn]/auth/realms/OIDC
      name: plain
      port: 9092
      tls: false
      type: internal
    logging:
      loggers:
        log4j.logger.io.strimzi: DEBUG
        log4j.logger.kafka: DEBUG
        log4j.logger.org.apache.kafka: DEBUG
      type: inline
    replicas: 3
    storage:
      class: gp2-encrypted
      deleteClaim: true
      size: 15Gi
      type: persistent-claim
  zookeeper:
    replicas: 3
    storage:
      class: gp2-encrypted
      deleteClaim: true
      size: 100Gi
      type: persistent-claim
```

Inside another pod running in the cluster, which happens to have curl installed, using the value of the "ca.crt" secret that is stored in the keycloak-[sensitive]-cert tls secret, it is possible to obtain a jwt successfully using curl, like this:
```
curl -s -X POST https://keycloak-[fqdn]/auth/realms/OIDC/protocol/openid-connect/token --cacert /tmp/tmp.zyYoYth7Ks -H 'Content-Type: application/x-www-form-urlencoded' -d client_secret=9478[sensitive]2a22 -d grant_type=client_credentials -d client_id=oidc-client
{"access_token":"eyJhbGciOiJSUzI1...R7h4Yw","expires_in":7200,"refresh_expires_in":0,"token_type":"Bearer","not-before-policy":0,"scope":"profile email"}
```

Kafka start up fails, logs attached.

**Comment by anthony-zawacki** [comment]
[logs.txt](https://github.com/strimzi/strimzi-kafka-operator/files/8954032/logs.txt)

**Comment by scholzj** [comment]
I guess you provided a wrong CA for the self-signed certificate?

**Comment by anthony-zawacki** [comment]
The CA cert used in the curl command is the same CA cert used by Kafka.  We ended up going down that route to confirm that we were using the right cert because we were thinking the same thing.  However, with the cert, curl is happy, and if we don't provide that cert, we get the expected curl could not verify the site because of the self signed cert error message.

**Comment by scholzj** [comment]
Wait, but you have configured it only for one listener ... so how should the other listeners work?

**Comment by anthony-zawacki** [comment]
I spoke too soon. That changed allowed the brokers to all start successfully, but they are still not functioning properly.  Now that the pods are starting successfully, I was able to `kubectl exec` into the kafka-0 pod where running this curl successfully fetches a token:
```
curl -s -X POST "https://keycloak-[fqdn]/auth/realms/kafka-authz/protocol/openid-connect/token" --cacert /opt/kafka/certificates/oauth-external-9094-certs/keycloak-cumulus-cert-0/tls.crt -H "Content-Type: application/x-www-form-urlencoded" -d "client_secret=[sensitive]" -d "grant_type=client_credentials" -d client_id=kafka

{"access_token":"eyJhbGciOiJSUzI...jgBeZBqew","expires_in":7200,"refresh_expires_in":0,"token_type":"Bearer","not-before-policy":0,"scope":"email profile"}
```
We can see in the logs that /opt/kafka/certificates/oauth-external-9094-certs/keycloak-cumulus-cert-0/tls.crt is the cert being added to the oauth-*.truststore.p12 files with alias oauth-0.  Now when we attempt to produce a message, we're seeing error messages similar to what we saw when starting up:

```
$ grep Exception kafka-0.logs
...
2022-06-23 14:42:27,906 WARN [IGNORED] Failed to fetch grants for token: java.lang.RuntimeException: Failed to fetch authorization data from authorization server:  (io.strimzi.kafka.oauth.server.authorizer.KeycloakRBACAuthorizer) [pool-11-thread-1]
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Failed to fetch authorization data from authorization server: 
Caused by: java.lang.RuntimeException: Failed to fetch authorization data from authorization server: 
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by scholzj** [comment]
Yeah, I guess you need to pass the secret once again in the `authorization` block? (It seems complicated, but there are uses cases where the certificates will be different).

**Comment by anthony-zawacki** [comment]
@KandpalS I don't exactly recall.  I think it had something to do with the `listener:` section of the Kafka configuration.  We:
- have cert-manager installed and configured properly
- install the strimzi-kafka-operator
- create a cert for our ingress (external) into the cluster (kafka.fqdn, kafka-0.fqdn, ...) with a keystore configuration.
- create a self-signed cert for our pod-to-pod (internal) communication with the kubernetes service names.
- create a kafka object to deploy the kafka/zookepper pods.

We're currently using strimzi 0.35.1, keycloak 21.1.1, cert-manager 1.12.1, and istio 1.18.0

An example of a kafka object we create:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
    meta.helm.sh/release-name: kafka
    meta.helm.sh/release-namespace: kafka
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kafka
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    authorization:
      clientId: kafka
      delegateToKafkaAcls: true
      superUsers:
      - User:service-account-kafka
      tokenEndpointUri: https://keycloak.[FQDN]/realms/kafka-authz/protocol/openid-connect/token
      type: keycloak
    config:
      log.message.format.version: "2.8"
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
    - authentication:
        jwksEndpointUri: https://keycloak.[FQDN]/realms/kafka-authz/protocol/openid-connect/certs
        maxSecondsWithoutReauthentication: 3600
        type: oauth
        userNameClaim: preferred_username
        validIssuerUri: https://keycloak.[FQDN]/realms/kafka-authz
      configuration:
        brokerCertChainAndKey:
          certificate: tls.crt
          key: tls.key
          secretName: kafka-external-cert
        brokers:
        - advertisedHost: kafka-0.[FQDN]
          broker: 0
        - advertisedHost: kafka-1.[FQDN]
          broker: 1
        - advertisedHost: kafka-2.[FQDN]
          broker: 2
      name: external
      port: 9094
      tls: true
      type: internal
    - authentication:
        jwksEndpointUri: https://keycloak.[FQDN]/realms/kafka-authz/protocol/openid-connect/certs
        maxSecondsWithoutReauthentication: 3600
        type: oauth
        userNameClaim: preferred_username
        validIssuerUri: https://keycloak.[FQDN]/realms/kafka-authz
      configuration:
        brokerCertChainAndKey:
          certificate: tls.crt
          key: tls.key
          secretName: kafka-internal-cert
      name: internal
      port: 9093
      tls: true
      type: internal
    - authentication:
        jwksEndpointUri: https://keycloak.[FQDN]/realms/kafka-authz/protocol/openid-connect/certs
        maxSecondsWithoutReauthentication: 3600
        type: oauth
        userNameClaim: preferred_username
        validIssuerUri: https://keycloak.[FQDN]/realms/kafka-authz
      name: plain
      port: 9092
      tls: false
      type: internal
    logging:
      loggers:
        log4j.logger.io.strimzi: WARN
        log4j.logger.kafka: WARN
        log4j.logger.org.apache.kafka: WARN
      type: inline
    replicas: 3
    storage:
      class: gp3
      deleteClaim: true
      size: 15Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: eks.amazonaws.com/capacityType
                  operator: In
                  values:
                  - ON_DEMAND
  zookeeper:
    replicas: 3
    storage:
      class: gp3
      deleteClaim: true
      size: 100Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: eks.amazonaws.com/capacityType
                  operator: In
                  values:
                  - ON_DEMAND
```

The external cert configuration:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    meta.helm.sh/release-name: kafka-certs
    meta.helm.sh/release-namespace: kafka
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kafka-external-cert
  namespace: kafka
spec:
  commonName: kafka.[FQDN]
  dnsNames:
  - kafka.[FQDN]
  - kafka-0.[FQDN]
  - kafka-1.[FQDN]
  - kafka-2.[FQDN]
  issuerRef:
    kind: ClusterIssuer
    name: cluster-issuer
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password
        name: jks-password
  secretName: kafka-external-cert
```

The internal cert configuration:
```
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  annotations:
    meta.helm.sh/release-name: kafka-certs
    meta.helm.sh/release-namespace: kafka
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: kafka-internal-cert
  namespace: kafka
spec:
  commonName: kafka.kafka.svc.cluster.local
  dnsNames:
  - kafka-kafka-bootstrap.kafka.svc.cluster.local
  - kafka-kafka-bootstrap.kafka.svc
  - kafka-kafka-0.kafka-kafka-brokers.kafka.svc.cluster.local
  - kafka-kafka-0.kafka-kafka-brokers.kafka.svc
  - kafka-kafka-1.kafka-kafka-brokers.kafka.svc.cluster.local
  - kafka-kafka-1.kafka-kafka-brokers.kafka.svc
  - kafka-kafka-2.kafka-kafka-brokers.kafka.svc.cluster.local
  - kafka-kafka-2.kafka-kafka-brokers.kafka.svc
  issuerRef:
    kind: ClusterIssuer
    name: selfsigned-ca-issuer
  keystores:
    jks:
      create: true
      passwordSecretRef:
        key: password
        name: jks-password
  secretName: kafka-internal-cert

```
Here, everything is listed twice in dnsNames because some applications use the short version and other applications use the long version.

There is probably extra stuff in there, I copy/pasted these from a running test cluster in our lab.  The pod affinity is optional, we sometimes build our clusters with both on-demand and spot instances, but want kafka to only run on the on-demand nodes.
