### ISSUE TITLE
Kafka Connect is not reachable 

### ISSUE THREAD

**Issue by flobuc** [strimzi/strimzi-kafka-operator#6985]
**Describe the bug**
KafkaConnect installed with StrimziOperator is not reachable.

I installed KafkaConnect on Azure and everything is working fine. So the configuration looks fine.
But when installing KafkaConnect on Scaleway, DigitalOcean and OVH it's not reachable. It seems there is some kind of Network Issue.
Pods and Services are up and running fine, but when i try to access the ClusterIP service, i always get a timeout.

When i start a port-forward to the Kafka-Connect Pod it is also working. 
But accessing the pod over the service the connection is blocked.

I work around the problem by installing Pod and Service manually with DeploymentDescriptors in the same way the operator is doing it and it works.

**Expected behavior**
KafkaConnect is accessible on all Plattforms.

**Environment (please complete the following information):**
 - Strimzi version: 0.28.0 - 0.29.0
 - Installation method: Operator
 - Kubernetes cluster: Kubernetes Version 1.23.6, Container Network cilium
 - Infrastructure: Scaleway

**YAML files and logs**
_Create ConnectImage with DebeziumConnector:_
```
FROM quay.io/strimzi/kafka:0.29.0-kafka-3.1.0

LABEL org.opencontainers.image.description="strimzi/kafka:0.29.0-kafka-3.1.0 debezium-connector-sqlserver/1.9.2.Final debezium-connector-oracle/1.9.2.Final"

USER root:root
RUN mkdir -p /opt/kafka/plugins/debezium && \
  cd /opt/kafka/plugins/debezium &&  \
  curl -k "https://repo1.maven.org/maven2/io/debezium/debezium-connector-sqlserver/1.9.2.Final/debezium-connector-sqlserver-1.9.2.Final-plugin.tar.gz" -o debezium-connector-sqlserver-1.9.2.Final-plugin.tar.gz && \
  tar -xvzf debezium-connector-sqlserver-1.9.2.Final-plugin.tar.gz && \
  curl -k "https://repo1.maven.org/maven2/io/debezium/debezium-connector-oracle/1.9.2.Final/debezium-connector-oracle-1.9.2.Final-plugin.tar.gz" -o debezium-connector-oracle-1.9.2.Final-plugin.tar.gz && \
  tar -xvzf debezium-connector-oracle-1.9.2.Final-plugin.tar.gz
```
  
USER 1001

_Install ConnectImage:_
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  namespace: kafka
  name: dashboard-cluster-kafka-connect
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  image: ghcr.io/<your-organisation>/kafka-connect-image:1.0.1
  version: 3.1.0
  replicas: 1
  bootstrapServers: dashboard-cluster-kafka-bootstrap:9092
  config:
    group.id: kafka-connect
    offset.storage.topic: kafka-connect-offsets
    config.storage.topic: kafka-connect-configs
    status.storage.topic: kafka-connect-status
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    config.storage.replication.factor: 1
    offset.storage.replication.factor: 1
    status.storage.replication.factor: 1
  template:
    pod:
      imagePullSecrets:
        - name: github-packages 
```
