### ISSUE TITLE
zookeeper crashing shortly after operator starts Kafka Cluster in watched namespace

### ISSUE THREAD

**Issue by ralphflat** [strimzi/strimzi-kafka-operator#7057]
We configured the Strimzi operator to watch two namespaces - oper and devel.  The Strimzi operation is installed into the kafka-operator namespace.

We apply the Kafka kind definition file (below) and see zookeeper start up, but no kafka instance.

```
more kafka-operational.yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: operational
spec:
  kafka:
    version:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.2"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

We only see zookeeper pods (no kafka pods) in the watched namespace (the 'oper' namespace)

![image](https://user-images.githubusercontent.com/86305586/179004051-3b8c266b-ef90-47e0-97a8-969c50ca6297.png)

When we look at the logs of one of the zookeeper services, we see the following.  Specifically, the warning of not being able to open channel followed by exception (identified as operational-zookeeper-1.operational-zookeeper-nodes.oper.svc/10.42.0.34:3888).  While we see operational-zookeeper-nodes is attached to port 3888, we do not see anything with the ClusterIP of 10.42.0.34.  ClusterIP for the operational-zookeeper-nodes is set to None - is that correct?

![image](https://user-images.githubusercontent.com/86305586/179004325-fcf66b4d-8734-438a-86c5-d9ab0e8b084c.png)
