### ISSUE TITLE
Disks disappear when updating to strimzi 0.30.0

### ISSUE THREAD

**Issue by roelvdberg** [strimzi/strimzi-kafka-operator#7093]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
Disks disappear when updating to strimzi 0.30.0

**To Reproduce**
Deploy 0.30.0 with the same values as 0.29.0

**Expected behavior**
I expected the disks to keep existing, even when kafka transitions to strimzipodsets.

**Environment (please complete the following information):**
 - Strimzi version: 0.29.0 to 0.30.0
 - Installation method: Helm chart (deployed with ArgoCD)
 - Kubernetes cluster: 1.23
 - Infrastructure: Azure AKS

**YAML files and logs**

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  labels:
    argocd.argoproj.io/instance: exampledev-dev3-kafka
    chartVersion: 1.3.3-strimzikafkaoperator-minor-update-to-version-0-30-11317
  name: exampledev-dev3
  namespace: kafka
spec:
  cruiseControl:
    jvmOptions:
      -Xms: 450m
      -Xmx: 450m
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: cruisecontrol-metrics-config.yml
          name: kafka-metrics
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
    template:
      cruiseControlContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      pod:
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
      tlsSidecarContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
  entityOperator:
    template:
      pod:
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
      tlsSidecarContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      topicOperatorContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      userOperatorContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    topicOperator:
      jvmOptions:
        -Xms: 450m
        -Xmx: 450m
      resources:
        requests:
          cpu: 10m
          memory: 512Mi
    userOperator:
      jvmOptions:
        -Xms: 450m
        -Xmx: 450m
      resources:
        requests:
          cpu: 10m
          memory: 512Mi
  kafka:
    authorization:
      superUsers:
      - akhq
      type: simple
    config:
      log.retention.hours: 168
      offsets.topic.replication.factor: 2
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 2
    jvmOptions:
      -Xms: 700m
      -Xmx: 700m
    listeners:
    - authentication:
        type: scram-sha-512
      name: plain
      port: 9092
      tls: false
      type: internal
    - authentication:
        type: scram-sha-512
      name: tlsinternal
      port: 9094
      tls: true
      type: internal
    - authentication:
        type: scram-sha-512
      configuration:
        bootstrap:
          annotations:
            mcp.infosupport.com/private.dns: enabled
          host: kafka-bootstrap.internal.dev3.example.com
        brokerCertChainAndKey:
          certificate: tls.crt
          key: tls.key
          secretName: custom-external-broker-cert
        brokers:
        - annotations:
            mcp.infosupport.com/private.dns: enabled
          broker: 0
          host: kafka-broker-0.internal.dev3.example.com
        - annotations:
            mcp.infosupport.com/private.dns: enabled
          broker: 1
          host: kafka-broker-1.internal.dev3.example.com
        class: private-nginx
      name: external
      port: 9096
      tls: true
      type: ingress
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    replicas: 2
    resources:
      requests:
        cpu: 350m
        memory: 1Gi
    storage:
      type: jbod
      volumes:
      - deleteClaim: false
        id: 0
        size: 20Gi
        type: persistent-claim
    template:
      kafkaContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      pod:
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              chartVersion: 1.3.3-strimzikafkaoperator-minor-update-to-version-0-30-11317
              strimzi.io/name: exampledev-dev3-kafka
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              chartVersion: 1.3.3-strimzikafkaoperator-minor-update-to-version-0-30-11317
              strimzi.io/name: exampledev-dev3-kafka
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
    version: 3.2.0
  kafkaExporter:
    groupRegex: .*
    template:
      container:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
      pod:
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
    topicRegex: .*
  zookeeper:
    jvmOptions:
      -Xms: 450m
      -Xmx: 450m
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 1
    resources:
      requests:
        cpu: 10m
        memory: 512Mi
    storage:
      class: default
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
    template:
      pod:
        securityContext:
          fsGroup: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          runAsUser: 1001
        topologySpreadConstraints:
        - labelSelector:
            matchLabels:
              chartVersion: 1.3.3-strimzikafkaoperator-minor-update-to-version-0-30-11317
              strimzi.io/name: exampledev-dev3-zookeeper
          maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
        - labelSelector:
            matchLabels:
              chartVersion: 1.3.3-strimzikafkaoperator-minor-update-to-version-0-30-11317
              strimzi.io/name: exampledev-dev3-zookeeper
          maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
      zookeeperContainer:
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
```

**Additional context**

**Comment by scholzj** [comment]
Could it be related to some cluster tooling deleting the disks because the StatefulSet is not there anymore?

**Comment by scholzj** [comment]
I tried it in my environment (which is on Google and not Azure) to doublecheck, but nothing seems to happen there with the PVCs / PVs.

**Comment by roelvdberg** [comment]
ArgoCD is missing the PVC in the desired state so it will delete that PVC. 
We can work around this if the PVC is created and managed by another process.

Once the disks are deleted no new disks are created. 
I would expect that the strimziPodSet recreates the deleted PVC's. But that doesn't happen.

**Comment by scholzj** [comment]
Without some logs it is hard to say why. Strimzi normally creates the PVCs when they don't exist. On a DEBUG log level in the Cluster Operator, you should be able to see it. Can it be that Argo simply deletes them again?

**Comment by roelvdberg** [comment]
You are correct, the pvc are created and directly deleted.

I am missing the owner reference in the disks. I would expect the Kafka resource to be the owner of the disks.
``` 
  ownerReferences:
    - apiVersion: kafka.strimzi.io/v1beta2
      kind: Kafka
      name: exampledev-dev3
```

Argo thinks he has to remove the disks because it is not in the desired state and there is no owner.
Is it possible to add Kafka or the strimziPodSet as ownerReference to the disks?
