### ISSUE TITLE
setting offsets.retention.minutes in spec.kafka.config doesn't seem to have any effect

### ISSUE THREAD

**Issue by rubensayshi** [strimzi/strimzi-kafka-operator#7135]
**Describe the bug**
setting `offsets.retention.minutes` in `spec.kafka.config` doesn't seem to have any effect on the `__consumer_offsets` topic.

**To Reproduce**
1. Create a `kafka` resource with `offsets.retention.minutes` set in `spec.kafka.config`
2. Check the `kube describe kafkatopic consumer-offsets`
3. See there spec is set to `compact` without any retention params.

**Expected behavior**
I would expect the retention to be applied to the `__consumer-offsets` topic, to avoid my offsets being lost when a consumer hasn't been alive for a while longer than the default 7 days (which also happens if there just weren't any new messages on the topic).

**YAML files and logs**

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: main
  namespace: kafka
spec:
  kafka:
    version: 3.0.0
    replicas: 2
    authorization:
      type: simple
    listeners:
      - name: tls
        port: 9093
        type: internal
    config:
      offsets.retention.minutes: 525600
```
