### ISSUE TITLE
Required fields not generated for KafkaConnectTls

### ISSUE THREAD

**Issue by ppatierno** [strimzi/strimzi-kafka-operator#720]
The `KafkaConnectTls` class has the `private List<CertSecretSource> trustedCertificates` field.
The used `CertSecretSource` class has two "required" fields (`secretName` and `certficate`).
This api design isn't reflected in the generated CRD YAML which is the following:

```yaml
          tls:
             type: object
              properties:
                trustedCertificates:
                  type: array
                  items:
                    type: object
                    properties:
                      certificate:
                        type: string
                      secretName:
                        type: string
              required:
              - trustedCertificates
```

It's worth noticing that the `KafkaConnectAuthenticationTls` class has the `private CertAndKeySecretSource certificateAndKey` field where the `CertAndKeySecretSource` is derived by the above `CertSecretSource` adding a new `key` field which is "required" as well.
In this case the generated CRD YAML is fine with all required fields in place:

```yaml
           authentication:
              type: object
              properties:
                certificateAndKey:
                  type: object
                  properties:
                    certificate:
                      type: string
                    key:
                      type: string
                    secretName:
                      type: string
                  required:
                  - certificate
                  - key
                  - secretName
                type:
                  type: string
              required:
              - certificateAndKey
```
