### ISSUE TITLE
Kafka cluster cannot be deployed with IPv6 advertised names

### ISSUE THREAD

**Issue by rvolchanskii** [strimzi/strimzi-kafka-operator#7217]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

Assigning IPv6 to advertised names for kafka nodes or using IPv6 load balancers causes strimzi operator fails with error.

**To Reproduce**
1. Create kafka cluster which assigns IPv6 addresses to listeners's LB
2. Configure ipFamilies as IPv6 only
3. Try to deploy cluster

**Expected behavior**
Cluster is starting normally

**Environment (please complete the following information):**
 - Strimzi version: 0.30.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.21
 - Infrastructure: Yandex Cloud

**YAML files and logs**
`2022-08-20 07:27:50 INFO  ClusterOperator:128 - Triggering periodic reconciliation for namespace *
2022-08-20 07:27:51 INFO  AbstractOperator:226 - Reconciliation #3604(timer) Kafka(kafka/kafka): Kafka kafka will be checked for creation or modification
2022-08-20 07:27:55 ERROR AbstractOperator:247 - Reconciliation #3604(timer) Kafka(kafka/kafka): createOrUpdate failed
java.lang.IllegalArgumentException: Invalid DNS name: MY_IPV6_ADDRESS
        at io.strimzi.certs.Subject$Builder.addDnsName(Subject.java:47) ~[io.strimzi.certificate-manager-0.30.0.jar:0.30.0]
        at io.strimzi.operator.cluster.model.ClusterCa.lambda$generateBrokerCerts$4(ClusterCa.java:204) ~[io.strimzi.cluster-operator-0.30.0.jar:0.30.0]
        at io.strimzi.operator.cluster.model.Ca.maybeCopyOrGenerateCerts(Ca.java:430) ~[io.strimzi.operator-common-0.30.0.jar:0.30.0]
        at io.strimzi.operator.cluster.model.ClusterCa.generateBrokerCerts(ClusterCa.java:224) ~[io.strimzi.cluster-operator-0.30.0.jar:0.30.0]
        at io.strimzi.operator.cluster.model.KafkaCluster.generateCertificatesSecret(KafkaCluster.java:1259) ~[io.strimzi.cluster-operator-0.30.0.jar:0.30.0]
        at io.strimzi.operator.cluster.operator.assembly.KafkaReconciler.lambda$certificateSecret$46(KafkaReconciler.java:729) ~[io.strimzi.cluster-operator-0.30.0.jar:0.30.0]
        at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
        at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
        at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
        at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
        at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
        at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]`

Attach or copy paste the custom resources you used to deploy the Kafka cluster and the relevant YAMLs created by the Cluster Operator.
Attach or copy and paste also the relevant logs.

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  kafka:
    version: 3.2.0
    image: quay.io/strimzi/kafka:0.30.0-kafka-3.2.0
    replicas: 5
    rack:
      topologyKey: kubernetes.io/hostname
    jvmOptions:
      -Xms: 8192m
      -Xmx: 8192m
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
        configuration:
          useServiceDnsDomain: true
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          useServiceDnsDomain: true
      - name: external
        port: 9095
        type: loadbalancer
        tls: true
        authentication:
          type: scram-sha-512
        configuration:
          ipFamilies:
          - IPv6
          bootstrap:
            loadBalancerIP: fc01::8d1c
          brokers:
            - broker: 0
            - broker: 1
            - broker: 2
            - broker: 3
            - broker: 4
    authorization:
      type: simple
      superUsers:
        - root
        - apicurio
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      log.message.format.version: "3.2"
      inter.broker.protocol.version: "3.2"

      auto.create.topics.enable: false
      topic.creation.enable: true
      log.cleanup.policy: compact
      log.retention.ms: -1
      message.max.bytes: 1073741824
      log.cleaner.max.compaction.lag.ms: 84600000 # 1 day`

```
*To easily collect all YAMLs and logs, you can use our [report script](https://github.com/strimzi/strimzi-kafka-operator/blob/main/tools/report.sh) which will automatically collect all files and prepare a ZIP archive which can be easily attached to this issue.
The usage of this script is:
`./report.sh --namespace <string> --cluster <string> [--bridge <string>] [--connect <string>] [--mm2 <string>]`*
