### ISSUE TITLE
Cruise Control Can Block Multiple Clusters

### ISSUE THREAD

**Issue by treyhendon** [strimzi/strimzi-kafka-operator#7249]
**Describe the bug**
Trying to bring up a second Kafka in single broker mode is blocked by Cruise Control Topic Creation.

**To Reproduce**
1. Create `strimzi` and `strimzi-2` namepaces
2. Install Operator in `strimzi` namespace
3. Install Kafka CR (with 3 brokers/zookeeprs and Cruise Control enabled) in `strimzi` namespace
4. Install Kafka CR (with 1 broker/zookeeper and Cruise Control disabled) in `strimzi-2` namespace
5. See URP error in the Operator reconcile logs for Cruise Control topic in `strimzi-2` asset

**Expected behavior**
The single broker cluster should not try to create the Cruise Control topics and/or the Operator should not allow "phantom" Cruise Control topics to prevent the broker from rolling.  

Searching through the code, it's possible that there might need to be an additional condition added in this method:  
https://github.com/strimzi/strimzi-kafka-operator/blob/0.30.0/cluster-operator/src/main/java/io/strimzi/operator/cluster/model/CruiseControl.java#L180

**Environment (please complete the following information):**
 - Strimzi version: 0.30.0
 - Installation method: Helm
 - Kubernetes cluster: Kubernetes 1.22
 - Infrastructure: AKS

**YAML files and logs**

First Cluster (3 Brokers w/ Cruise Control)
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  labels:
    strimzipod: strimzi
  name: corp
  namespace: strimzi
spec:
  cruiseControl:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: cruise-control-metrics-config.yml
          name: kafka-metrics
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      auto.create.topics.enable: true
      default.replication.factor: 3
      group.initial.rebalance.delay.ms: 3000
      inter.broker.protocol.version: '3.2'
      log.message.format.version: '3.2'
      log.retention.check.interval.ms: 300000
      log.retention.hours: 168
      min.insync.replicas: 2
      num.io.threads: 8
      num.network.threads: 3
      num.partitions: 10
      num.recovery.threads.per.data.dir: 1
      offsets.retention.minutes: 10080
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
      zookeeper.connection.timeout.ms: 6000
    jvmOptions:
      '-Xms': 12288m
      '-Xmx': 12288m
    listeners:
      - authentication:
          type: scram-sha-512
        name: plain
        port: 9092
        tls: false
        type: internal
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    resources:
      limits:
        cpu: '4'
        memory: 16Gi
      requests:
        cpu: '4'
        memory: 16Gi
    storage:
      type: jbod
      volumes:
        - deleteClaim: false
          id: 0
          size: 600Gi
          type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: agentpool
                      operator: In
                      values:
                        - strimzi
        tolerations:
          - key: strimzi-node
            operator: Exists
        topologySpreadConstraints:
          - labelSelector:
              matchExpressions:
                - key: strimzi.io/name
                  operator: In
                  values:
                    - corp-kafka
            maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
    version: 3.2.0
  kafkaExporter:
    groupRegex: .*
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    topicRegex: .*
  zookeeper:
    jvmOptions:
      '-Xms': 1024m
      '-Xmx': 1024m
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    resources:
      limits:
        cpu: 500m
        memory: 1.5Gi
      requests:
        cpu: 500m
        memory: 1.5Gi
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: agentpool
                      operator: In
                      values:
                        - strimzi
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: strimzi.io/name
                        operator: In
                        values:
                          - corp-zookeeper
                  topologyKey: topology.kubernetes.io/zone
                weight: 100
        tolerations:
          - key: strimzi-node
            operator: Exists
        topologySpreadConstraints:
          - labelSelector:
              matchExpressions:
                - key: strimzi.io/name
                  operator: In
                  values:
                    - corp-zookeeper
            maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
```

2nd Cluster (1 Broker / no Cruise Control)
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  labels:
    strimzipod: strimzi
  name: corp2
  namespace: strimzi-2
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      auto.create.topics.enable: true
      default.replication.factor: 1
      group.initial.rebalance.delay.ms: 3000
      inter.broker.protocol.version: '3.2'
      log.message.format.version: '3.2'
      log.retention.check.interval.ms: 300000
      log.retention.hours: 168
      min.insync.replicas: 1
      offsets.retention.minutes: 10080
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
      zookeeper.connection.timeout.ms: 6000
    jvmOptions:
      '-Xms': 12288m
      '-Xmx': 12288m
    listeners:
      - authentication:
          type: scram-sha-512
        name: plain
        port: 9092
        tls: false
        type: internal
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    replicas: 1
    resources:
      limits:
        cpu: '4'
        memory: 16Gi
      requests:
        cpu: '4'
        memory: 16Gi
    storage:
      type: jbod
      volumes:
        - deleteClaim: false
          id: 0
          size: 500Gi
          type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: agentpool
                      operator: In
                      values:
                        - strimzi2
        tolerations:
          - key: strimzi-corp2-node
            operator: Exists
        topologySpreadConstraints:
          - labelSelector:
              matchExpressions:
                - key: strimzi.io/name
                  operator: In
                  values:
                    - corp2-kafka
            maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
    version: 3.2.0
  kafkaExporter:
    groupRegex: .*
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
    topicRegex: .*
  zookeeper:
    jvmOptions:
      '-Xms': 1024m
      '-Xmx': 1024m
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1.5Gi
      requests:
        cpu: 500m
        memory: 1.5Gi
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
                - matchExpressions:
                    - key: agentpool
                      operator: In
                      values:
                        - strimzi2
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: strimzi.io/name
                        operator: In
                        values:
                          - corp2-zookeeper
                  topologyKey: topology.kubernetes.io/zone
                weight: 100
        tolerations:
          - key: strimzi-corp2-node
            operator: Exists
        topologySpreadConstraints:
          - labelSelector:
              matchExpressions:
                - key: strimzi.io/name
                  operator: In
                  values:
                    - corp2-zookeeper
            maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: ScheduleAnyway
```

Error from Operator:
```
2022-08-29 17:09:29 INFO  KafkaAvailability:135 - Reconciliation #51(watch) Kafka(strimzi-2/corp2): strimzi.cruisecontrol.partitionmetricsamples/0 will be under-replicated (ISR={0}, replicas=[0,1], min.insync.replicas=1) if broker 0 is restarted.
2022-08-29 17:09:29 INFO  KafkaRoller:306 - Reconciliation #51(watch) Kafka(strimzi-2/corp2): Could not roll pod {corp2-kafka-0} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$UnforceableProblem: Pod corp2-kafka-0 is currently not rollable, retrying after at least 32000ms
2022-08-29 17:10:02 INFO  KafkaAvailability:135 - Reconciliation #51(watch) Kafka(strimzi-2/corp2): strimzi.cruisecontrol.partitionmetricsamples/0 will be under-replicated (ISR={0}, replicas=[0,1], min.insync.replicas=1) if broker 0 is restarted.
2022-08-29 17:10:02 INFO  KafkaRoller:306 - Reconciliation #51(watch) Kafka(strimzi-2/corp2): Could not roll pod {corp2-kafka-0} due to io.strimzi.operator.cluster.operator.resource.KafkaRoller$UnforceableProblem: Pod corp2-kafka-0 is currently not rollable, retrying after at least 64000ms
2022-08-29 17:10:19 INFO  AbstractOperator:373 - Reconciliation #67(timer) Kafka(strimzi-cpe/cpe): Reconciliation is in progress
```

**Additional context**
I did modify names/urls in these files to protect live use.
