### ISSUE TITLE
Support hostPort for kind: Kafka

### ISSUE THREAD

**Issue by magguns** [strimzi/strimzi-kafka-operator#7397]
**Is your feature request related to a problem? Please describe.**
We are running a production kubernetes cluster on bare metal (on Talos Linux), and need to expose each broker individually on each node for external access, accessing fqdn:post on the individual nodes directly:
- examplenode01.exampledomain.local:9093
- examplenode01.exampledomain.local:9093
- ...

**Describe the solution you'd like**
Have you considered supporting for `hostPort` in `spec.kafka.template.pod.containers.ports`?
```yaml
    template:
      pod:
        container:
        - name: kafka
          ports:
          - containerPort: 9092
            hostPort: 9092
            protocol: TCP
          - containerPort: 9093
            hostPort: 9093
            protocol: TCP
          - ...
```
We are currently using fast local storage on our Strimzi nodes using _openebs-device_, pod scheduling is already static and predictable (1 broker per physical node).

**Describe alternatives you've considered**
We have already excluded the `loadbalancer` listener type for our use for performance reasons (we are using MetalLB in L2 mode, resulting in single-node bottlenecking).
We also found the `nodeport` listener type suboptimal in this case.
