### ISSUE TITLE
superUsers requires full certificate Subject

### ISSUE THREAD

**Issue by Manicben** [strimzi/strimzi-kafka-operator#7427]
**Suggestion / Problem**
In the Strimzi docs, this is what is mentioned regarding specifying mTLS super user principals:
> If a user uses TLS client authentication, their username is the common name from their certificate subject prefixed with CN=

However, from testing, this is not the case.
When using the following in the Kafka CR:
```
    authorization:
      type: simple
      superUsers:
        - CN=strimzi-kafka
```
And using a AdminClient to perform operations on the cluster with a certificate with the following Subject:
`CN=strimzi-kafka,OU=foo,O=bar,L=baz,ST=qux,C=XX`
The AdminClient is denied operations.

When the CR is updated to the following:
```
    authorization:
      type: simple
      superUsers:
        - CN=strimzi-kafka,OU=foo,O=bar,L=baz,ST=qux,C=XX
```
Then the AdminClient is authorized as expected. This indicates that the documentation may be making assumptions about the Subject contained in users' certificates only containing a CN and I have checked that `ssl.principal.mapping.rules` is not used anywhere to do this either.

Thus I suggest that the documentation be updated for all versions that supported the `superUsers` field to mention that the entire Subject (Distinguished Name) of the certificate is treated as the username, as per https://docs.confluent.io/platform/current/kafka/authorization.html#tls-ssl-principal-user-names
I.e.
> By default, the name of the principal identified by a TLS/SSL certificate is the DN (X.500 Distinguished Name) of that certificate (also known as the Subject), which uses the form CN=writeuser,OU=Unknown,O=Unknown,L=Unknown,ST=Unknown,C=Unknown.

**Documentation Link**
https://strimzi.io/docs/operators/latest/configuring.html#super_users
