### ISSUE TITLE
Zookeeper and Kafka loglevels not configurable

### ISSUE THREAD

**Issue by vstoppe** [strimzi/strimzi-kafka-operator#7586]
**Describe the bug**
I am trying to set the loglevel for the zookeeper and broker pods to "WARN", but still get the "INFO" logs. I set this in the Kafka CRD as the excerpts shows from the live CRD below:

```
yq .Spec.Zookeeper.Logging kafka-cluster-yaml  -y
Loggers:
  kafka.root.logger.level: WARN
Type: inline

yq .Spec.Kafka.Logging kafka-cluster-yaml  -y
Loggers:
  kafka.root.logger.level: WARN
Type: inline
```

The log4j.properties is set correctly:

```
kafka]$  cat /opt/kafka/custom-config/log4j.properties | grep logger.level
kafka.root.logger.level=WARN
```

Despite the configuration a lot of info logs are produced

```
kubectl logs mx-strimzi-zookeeper-0 --tail 1000  | grep INFO | wc -l
1000

kubectl logs mx-strimzi-kafka-0 --tail 10000  | grep INFO | wc -l
9702
```

**Expected behavior**

I would expect that no INFO logs get produced.

**Environment (please complete the following information):**
 - Strimzi version: 0.29.0
 - Kafka 3.2.0
 - Installation method: Helm chart
 - Kubernetes cluster: Kubernetes 1.21
 - Infrastructure: Rancher. 2.6

I think this is related to: [Dynamic configuration of logging doesn't work](https://github.com/strimzi/strimzi-kafka-operator/issues/6999#top)
