### ISSUE TITLE
Support deletion of Statefulset's PVC

### ISSUE THREAD

**Issue by holysheep** [strimzi/strimzi-kafka-operator#7765]
As it is known, k8s control plane never cleans up the PVCs created for StatefulSets. In v1.23 version they've added a new retention policy for this, which can be enabled with [StatefulSetAutoDeletePVC](https://kubernetes.io/blog/2021/12/16/kubernetes-1-23-statefulset-pvc-auto-deletion/) feature gate inside container like this:
```
    spec:
      containers:
        ...
          command:
            - kube-apiserver
            - --feature-gates=StatefulSetAutoDeletePVC=true 
```   
            
As we delegate Kafka-related PVC provisioning to Strimzi cluster operator, we can't enable this feature inside the resources.

Seems like STRIMZI_FEATURE_GATES env doesn't support this gate either:

<img width="1146" alt="Screenshot 2022-12-08 at 18 48 35" src="https://user-images.githubusercontent.com/9785806/206526247-3ac05281-48ef-47db-b204-7ca392e18edd.png">

Is there any alternative solution?
