### ISSUE TITLE
MirrorMaker2 not replicating consumer groups

### ISSUE THREAD

**Issue by RomanTheLegend** [strimzi/strimzi-kafka-operator#7904]
When setting up a migration from Kafka2 to Kafka3 using operator, MirrorMaker2 correctly replicates all topics, but none of consumer groups are created

operator:0.32.0

MirrorMaker2 is installed from manifest:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: mm2-kafka3
  namespace: kafka3
spec:
  version: 3.3.1
  replicas: 1
  connectCluster: "target"
  template:
    pod:
      tolerations:
        - key: "workloadsType"
          operator: "Exists"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: workloadsType
                  operator: In
                  values:
                    - mm2
      metadata:
        annotations:
          sidecar.istio.io/inject: "false"
  jvmOptions:
    -Xms: 7G
    -Xmx: 7G
  resources:
      limits:
        cpu: 6
        memory: 9G
      requests:
        cpu: 1
        memory: 7G
  clusters:
  - alias: "source"
    bootstrapServers: kafka2-cluster-kafka-bootstrap.kafka2:9092
  - alias: "target"
    bootstrapServers: kafka3-cluster-kafka-bootstrap:9092
    config:
      producer.max.request.size: 52428800
      producer.compression.type: gzip
      config.storage.replication.factor: 2
      offset.storage.replication.factor: 2
      status.storage.replication.factor: 2
  mirrors:
  - sourceCluster: "source"
    targetCluster: "target"
    topicsPattern: "topic1|mastertopic1.*|mastertopic2.*|sometopic.*"
    groupsPattern: ".*"
    sourceConnector:
      tasksMax: 40
      config:
        producer.enable.idempotence: true
        producer.max.in.flight.requests.per.connection: 1
        producer.acks: all
        producer.retries: 2147483647
        offset-syncs.topic.replication.factor: 2
        offset-syncs.topic.location: "target"
        sync.topic.acls.enabled: "false"
        replication.policy.separator: ""
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
    heartbeatConnector:
      config:
        heartbeats.topic.replication.factor: 1
    checkpointConnector:
      config:
        checkpoints.topic.replication.factor: 2
        replication.policy.separator: ""
        replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
        sync.group.offsets.enabled: "true"

```

**To Reproduce**
1) Install Kafka3 from operator:0.32.0
2) Install MM2 from aforementioned manifest

In logs it says it tries to sync idle consumer group offset from source to target but in reality none of the groups gets created

**Environment:**
 - Strimzi version: [e.g. main, 0.32.0]
 - Installation method: Helm chart via terraform
 - Kubernetes cluster:  Kubernetes 1.24
 - Infrastructure: GKE
