### ISSUE TITLE
Cruise control API - Cannot enable CORS

### ISSUE THREAD

**Issue by aventi-lasith** [strimzi/strimzi-kafka-operator#8128]
I'm trying to enable CORS for the cruise control API. 

I have created a separate LoadBalancer resource to access the API
```
apiVersion: v1
kind: Service
metadata:
  labels:
    strimzi.io/cluster: kafka-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-cluster-cruise-control
  name: cruise-control-api
  namespace: kafka
spec:
  ports:
    - port: 9090
      targetPort: 9090
  type: LoadBalancer
  selector:
    strimzi.io/cluster: kafka-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: kafka-cluster-cruise-control
```

Then, I updated my `Kafka `resource to enable `CORS`.
```
-----
  cruiseControl:
    metricsConfig:
      --------
    config:
      webserver.security.enable: false
      webserver.ssl.enable: false
      webserver.http.cors.enabled: true
      webserver.http.cors.origin: "*"
      webserver.http.cors.exposeheaders: "User-Task-ID,Content-Type"
      webserver.http.cors.allowmethods: "OPTIONS,GET,POST"
```

Not sure what I'm missing here but, cruise control API cannot be accessed. 

This is the log file of the cruise control pod.
[cclogs.log](https://github.com/strimzi/strimzi-kafka-operator/files/10782988/cclogs.log)

I appreciate any help.
Thanks!
