### ISSUE TITLE
Add envFrom to externalConfiguration of KafkaConnect

### ISSUE THREAD

**Issue by Voldemat** [strimzi/strimzi-kafka-operator#8162]
**Describe the solution you'd like**
Main idea is to add new property to KafkaConnect externalConfiguration, in order to set all properties at once.
Schema should be the same as for pod container (https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#Container). 

Example configuration:
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-kafka-connect
  annotations:
     strimzi.io/use-connector-resources: "true"
spec:
  externalConfiguration:
      envFrom:
        - secretRef:
            name: service-postgresql-secret
          prefix: SERVICE_
```
