### ISSUE TITLE
Expired non-CA certificates causing Entity Operator and Exporter to CrashLoopBackOff

### ISSUE THREAD

**Issue by eosantigen** [strimzi/strimzi-kafka-operator#8188]
_Please use this to only for bug reports. For questions or when you need help, you can use the [GitHub Discussions](https://github.com/strimzi/strimzi-kafka-operator/discussions), our [#strimzi Slack channel](https://slack.cncf.io/) or out [user mailing list](https://lists.cncf.io/g/cncf-strimzi-users/topics)._

**Describe the bug**
It seems that auto-renewal of any certificate might be broken. Might be due large gap in versions of Kubernetes and 0.14.0 due to some API deprecations, maybe?

**To Reproduce**
Steps to reproduce the behavior, but it cannot be easily reproduced due to different timings in renewing dates:
1. Have deployed Strimzi Kafka Operator 0.14.0 on Kubernetes 1.23.12.
2. Create Custom Resource as following Yaml or simpler
3. Run command `kubectl logs <entity-operator-pod-name> -n kafka-operator -c tls-sidecar`
4. See the following error:

```
Service [zookeeper-2181] connected remote server from 10.244.15.222:60860
2023.03.03 11:14:03 LOG5[1:140217960855296]: Certificate accepted: depth=1, /O=io.strimzi/CN=cluster-ca v0
2023.03.03 11:14:03 LOG5[1:140217960855296]: Certificate accepted: depth=0, /O=io.strimzi/CN=kafka-operator-zookeeper
2023.03.03 11:14:03 LOG3[1:140217960855296]: SSL_connect: 14094415: error:14094415:SSL routines:ssl3_read_bytes:sslv3 alert certificate expired
```

**Expected behavior**
No such errors exists and pods of the Entity Operator / Exporter (of metrics) are in Running state.

**Environment (please complete the following information):**
 - Strimzi version: 0.14.0
 - Installation method: plain Yaml manifests
 - Kubernetes cluster: 1.23.12
 - Infrastructure: AKS

**YAML files and logs**
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: kafka-operator
  namespace: kafka-operator
  labels:
    app: kafka-operator
spec:
  zookeeper:
    template:
      pod:
        priorityClassName: critical 
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: strimzi.io/name
                    operator: In
                    values:
                    - kafka-operator-zookeeper
                topologyKey: kubernetes.io/hostname      
    replicas: 3
    storage:
      type: persistent-claim
      class: fast
      size: 20Gi
    resources:
      limits:
        memory: 3Gi
      requests:
        memory: 1Gi
        cpu: "300m"
  kafka:
    template:
      pod:
        priorityClassName: critical      
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: strimzi.io/name
                    operator: In
                    values:
                    - kafka-operator-kafka
                topologyKey: kubernetes.io/hostname
    replicas: 3
    version: 2.3.0
    storage:
      type: persistent-claim
      class: fast
      size: 999Gi
    resources:
      limits:
        memory: 10Gi
      requests:
        memory: 6Gi
        cpu: "1"
    listeners:
      plain: {}
      tls: {}
      external:
        type: nodeport
        tls: false
    config:
      auto.create.topics.enable: false
      replica.fetch.max.bytes: 10485760
      message.max.bytes: 10485760
      max.message.bytes: 10485760
      log.retention.hours: 168
    metrics:
      # Inspired by config from Kafka 2.0.0 example rules:
      # https://github.com/prometheus/jmx_exporter/blob/master/example_configs/kafka-2_0_0.yml
      lowercaseOutputName: true
      rules:
      # Special cases and very specific rules
      # some rules....
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
```

**Additional context**
1. We had renewed the CA Certs manually last year, since we had a similar issue, but at that time the services went up - followed this https://strimzi.io/docs/0.14.0/#proc-renewing-ca-certs-manually-str
2. Now the issue doesn't seem to be with the CA certs however, but the following certs have been expired, that are not CA, as the doc refers to, so they don't seem to accept the `force-renew` annotation:
```
kubectl -n kafka-operator get secret kafka-operator-entity-operator-certs -o 'jsonpath={.data.entity-operator\.crt}' | base64 -d | openssl x509 -subject -issuer -startdate -enddate -noout
```
And seemingly, this is one of the secrets that cannot be renewed (entity-operator.crt) .

What are we missing ? Thanks...
