### ISSUE TITLE
Better logging documentation

### ISSUE THREAD

**Issue by xhl1988** [strimzi/strimzi-kafka-operator#8209]
**Suggestion / Problem**
Describe your problem or suggestion
Currently the logging [examples](https://strimzi.io/docs/operators/latest/full/configuring.html#property-kafka-logging-reference) doesn't include how to set log levels for specific class, it's better to include the specific class or Kafka logger example in the yaml. e.g.,
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
spec:
  # ...
  kafka:
    # ...
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
        org.openpolicyagent.kafka.OpaAuthorizer: "TRACE"
```

**Documentation Link**
Provide a link to the documentation where the bug / suggestion should be applied
https://strimzi.io/docs/operators/latest/full/configuring.html#property-kafka-logging-reference
