### ISSUE TITLE
[Bug]: standalone User Operator with SASL: STRIMZI_CA_CERT_NAME cannot be null

### ISSUE THREAD

**Issue by jslusher** [strimzi/strimzi-kafka-operator#8284]
### Bug Description

I'm trying to deploy a standalone user operator to authenticate with an MSK cluster using the `STRIMZI_KAFKA_ADMIN_CLIENT_CONFIGURATION` env to set up `SASL/SCRAM` authentication instead of using mTLS. If I don't set `STRIMZI_CA_CERT_NAME` and `STRIMZI_CA_KEY_NAME` I can't get the operator to start up because it throws an exception:

```
Exception in thread "main" io.strimzi.operator.common.InvalidConfigurationException: STRIMZI_CA_CERT_NAME cannot be null
	at io.strimzi.operator.user.UserOperatorConfig.fromMap(UserOperatorConfig.java:225)
	at io.strimzi.operator.user.Main.main(Main.java:73)
```

I would like to avoid setting up mTLS since it won't be used. Is that possible?

### Steps to reproduce

Set up standalone user operator Deployment and omit `STRIMZI_CA_CERT_NAME` and `STRIMZI_CA_KEY_NAME` and it should throw the exception.

### Expected behavior

If `STRIMZI_KAFKA_ADMIN_CLIENT_CONFIGURATION` has an alternate authentication method specified, the operator should try it before throwing an exception.

### Strimzi version

0.34.0

### Kubernetes version

1.24

### Installation method

yaml file (Deployment)

### Infrastructure

Amazon EKS

### Configuration files and logs

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-user-operator
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      name: strimzi-user-operator
  template:
    metadata:
      labels:
        name: strimzi-user-operator
    spec:
...
      containers:
        - name: strimzi-user-operator
          image: quay.io/strimzi/operator:0.34.0
          args:
            - /opt/strimzi/bin/user_operator_run.sh
...
          env:
          - name: STRIMZI_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
            value: b-3.example.example.cxx.kafka.us-west-2.amazonaws.com:9096,b-2.example.example.cxx.kafka.us-west-2.amazonaws.com:9096,b-1.example.example.cxx.kafka.us-west-2.amazonaws.com:9096
          - name: STRIMZI_LABELS
            value: "strimzi.io/cluster=msk-sdlc"
          - name: STRIMZI_LOG_LEVEL
            value: INFO
          - name: STRIMZI_GC_LOG_ENABLED
            value: "true"
          - name: STRIMZI_SECRET_PREFIX
            value: "msk-sdlc-"
          - name: STRIMZI_ACLS_ADMIN_API_SUPPORTED
            value: "false"
          - name: STRIMZI_MAINTENANCE_TIME_WINDOWS
            value: '* * 8-10 * * ?;* * 14-15 * * ?'
          - name: STRIMZI_KAFKA_ADMIN_CLIENT_CONFIGURATION
            valueFrom:
              secretKeyRef:
                name: strimzi-user-operator-configuration-secrets
                key: admin-client-config
...
```
```yaml
apiVersion: v1
data:
  admin-client-config: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
kind: Secret
metadata:
  name: strimzi-user-operator-configuration-secrets
  namespace: strimzi-operator
type: Opaque
```

### Additional context

Mostly I'm uncertain whether mTLS is necessary at all if using a different authentication for the Kafka cluster. The MSK cluster to which this will connect does not use it.
