### ISSUE TITLE
Please add support for annotating the kafka/zookeper sets from configuration 

### ISSUE THREAD

**Issue by cameronbraid** [strimzi/strimzi-kafka-operator#847]
My use case is that I configure prometheus to scrape all pods using a path name based on an annotation like the following : 

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/path: /metrics
```

Therefore it would be nice it the kafka/zookeeper resource definitions provided an annotations configuration option
