### ISSUE TITLE
[Bug]: Invalid order of -XX properties in KAFKA_JVM_PERFORMANCE_OPTS variable

### ISSUE THREAD

**Issue by jakubmalek** [strimzi/strimzi-kafka-operator#8579]
### Bug Description

The ordering of JVM performance options is not guaranteed, due use of unordered `Map<String, String>` in [JvmOptions ](https://github.com/strimzi/strimzi-kafka-operator/blob/0.31.1/api/src/main/java/io/strimzi/api/kafka/model/JvmOptions.java) class.
As a consequence following configuration:
```yaml
jmxOptions:
  -XX:
    UnlockDiagnosticVMOptions: true
    PrintNMTStatistics: true
```
can result in JVM startup failure when JVM flags are misordered:
`java -XX:+PrintNMTStatistics -XX:+UnlockDiagnosticVMOptions`

> Error: VM option 'PrintNMTStatistics' is diagnostic and must be enabled via -XX:+UnlockDiagnosticVMOptions.
> Error: The unlock option must precede 'PrintNMTStatistics'.
> Error: Could not create the Java Virtual Machine.
> Error: A fatal exception has occurred. Program will exit.

### Steps to reproduce

Configure `jvmOptions` with to enable `UnlockDiagnosticVMOptions` and `PrintNMTStatistics` flags.

### Expected behavior

The ordering of performance options should guaranteed.

### Strimzi version

0.31.1

### Kubernetes version

1.24.9

### Installation method

Helm chart

### Infrastructure

Azure

**Comment by scholzj** [comment]
IIRC, ordered maps are not supported by YAML / CRDs. So I think this might not be possible. Have you tried directly defining the environment variable using the `.spec.kafka.template` section as a String?

**Comment by jakubmalek** [comment]
That is indeed a good point, I forgot about possible issues with the ordering inside the resulting k8s manifest itself.
I'm not sure how many VM of those -XX options requires specific order, but I think the easiest way out (without breaking changes to CRD) would be to include such options in separated configuration section.

But anyway, was able to get it running with proposed use `.spec.kafka.template` thanks for the hint @scholzj !
```yaml
spec:
  template:
    connectContainer:
      env:
        - name: JAVA_TOOL_OPTIONS
          value: -XX:+UnlockDiagnosticVMOptions
```
