### ISSUE TITLE
[Bug]: No error logged when `KafkaTopic` is created without `strimzi.io/cluster` label

### ISSUE THREAD

**Issue by kyguy** [strimzi/strimzi-kafka-operator#8676]
### Bug Description

When a `KafkaTopic` resource is created without a `strimzi.io/cluster` label, no topic will be created in any Kafka cluster because no Topic Operator knows which cluster that `KafkaTopic` resource belongs to. This makes sense. However, the Topic Operator doesn't log any errors about a  `KafkaTopic` missing a `strimzi.io/cluster` label. This could be confusing for a user that forgets to provide a  `strimzi.io/cluster`  label in their `KafkaTopic` resource and they don't know why the Kafka topic corresponding to their `KafkaTopic` resource is not being created.

### Steps to reproduce

1. Deploy `Kafka` cluster with TopicOperator enabled
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.4.0
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.4"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}

```
2. Create `KafkaTopic` resource without any labels
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: my-topic
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```

### Expected behavior

Expected behavior would that the Topic Operator logs an error when there is a `KafkaTopic` resource that is missing a `strimzi.io/cluster` label

### Strimzi version

0.35.1

### Kubernetes version

Kubernetes 1.25

### Installation method

YAML files

### Infrastructure

Minikube

### Configuration files and logs

[topic-operator.txt](https://github.com/strimzi/strimzi-kafka-operator/files/11760917/topic-operator.txt)
