### ISSUE TITLE
[Bug]: Topic Operator fails ready check, blocked on createTopicStore

### ISSUE THREAD

**Issue by cyvcloud** [strimzi/strimzi-kafka-operator#8737]
### Bug Description

Creating a Kafka cluster with the below configuration results in a entity operator pod whose topic operator container never becomes ready.

### Strimzi version

0.35.1

### Kubernetes version

Kubernetes 1.26.6

### Installation method

Helm chart

### Configuration files and logs

[topic-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/11881342/topic-operator.log)

Kafka CR
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
  namespace: kafka
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 9
      inter.broker.protocol.version: '3.4'
      min.insync.replicas: 5
      offsets.topic.replication.factor: 3
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
      - name: plain
        port: 9092
        tls: false
        type: internal
      - authentication:
          type: tls
        configuration:
          bootstrap:
            alternativeNames:
              - >-
                bootstrap.[...]
            annotations:
              external-dns.alpha.kubernetes.io/hostname: >-
                bootstrap.[...]
              load-balancer.hetzner.cloud/type: lb31
          brokers:
            - advertisedHost: >-
                broker-0.[...]
              annotations:
                external-dns.alpha.kubernetes.io/hostname: >-
                  broker-0.[...]
                load-balancer.hetzner.cloud/type: lb31
              broker: 0
            - advertisedHost: >-
                broker-1.[...]
              annotations:
                external-dns.alpha.kubernetes.io/hostname: >-
                  broker-1.[...]
                load-balancer.hetzner.cloud/type: lb31
              broker: 1
            - advertisedHost: >-
                broker-2.[...]
              annotations:
                external-dns.alpha.kubernetes.io/hostname: >-
                  broker-2.[...]
                load-balancer.hetzner.cloud/type: lb31
              broker: 2
            - advertisedHost: >-
                broker-3.[...]
              annotations:
                external-dns.alpha.kubernetes.io/hostname: >-
                  broker-3.[...]
                load-balancer.hetzner.cloud/type: lb31
              broker: 3
            - advertisedHost: >-
                broker-4.[...]
              annotations:
                external-dns.alpha.kubernetes.io/hostname: >-
                  broker-4.[...]
                load-balancer.hetzner.cloud/type: lb31
              broker: 4
            - advertisedHost: >-
                broker-5.[...]
              annotations:
                external-dns.alpha.kubernetes.io/hostname: >-
                  broker-5.[...]
                load-balancer.hetzner.cloud/type: lb31
              broker: 5
            - advertisedHost: >-
                broker-6.[...]
              annotations:
                external-dns.alpha.kubernetes.io/hostname: >-
                  broker-6.[...]
                load-balancer.hetzner.cloud/type: lb31
              broker: 6
            - advertisedHost: >-
                broker-7.[...]
              annotations:
                external-dns.alpha.kubernetes.io/hostname: >-
                  broker-7.[...]
                load-balancer.hetzner.cloud/type: lb31
              broker: 7
            - advertisedHost: >-
                broker-8.[...]
              annotations:
                external-dns.alpha.kubernetes.io/hostname: >-
                  broker-8.[...]
              broker: 8
          externalTrafficPolicy: Local
          finalizers:
            - service.kubernetes.io/load-balancer-cleanup
        name: external
        port: 9093
        tls: true
        type: loadbalancer
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    replicas: 9
    resources:
      limits:
        memory: 24Gi
    storage:
      deleteClaim: false
      id: 0
      size: 1024Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - kafka
                    - key: strimzi.io/cluster
                      operator: In
                      values:
                        - kafka
                topologyKey: kubernetes.io/hostname
    version: 3.4.0
  zookeeper:
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 5
    resources:
      limits:
        memory: 2Gi
    storage:
      deleteClaim: false
      size: 10Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - zookeeper
                    - key: strimzi.io/cluster
                      operator: In
                      values:
                        - kafka
                topologyKey: kubernetes.io/hostname
```

### Additional context

As far as I can tell the topic operator topics exist:

```shell
[kafka@kafka-kafka-0 kafka]$ ./bin/kafka-topics.sh --list --bootstrap-server localhost:9092
__consumer_offsets
__strimzi-topic-operator-kstreams-topic-store-changelog
__strimzi_store_topic
[kafka@kafka-kafka-0 kafka]$ ./bin/kafka-topics.sh --describe --topic __strimzi_store_topic --bootstrap-server localhost:9092
Topic: __strimzi_store_topic    TopicId: MIyXo7I1SO6Rmobcox1Hxw PartitionCount: 1       ReplicationFactor: 3    Configs: min.insync.replicas=2,message.format.version=3.0-IV1
        Topic: __strimzi_store_topic    Partition: 0    Leader: 1       Replicas: 1,6,7 Isr: 1,6,7
[kafka@kafka-kafka-0 kafka]$ ./bin/kafka-topics.sh --list --bootstrap-server localhost:9092
__consumer_offsets
__strimzi-topic-operator-kstreams-topic-store-changelog
__strimzi_store_topic
[kafka@kafka-kafka-0 kafka]$ ./bin/kafka-topics.sh --describe --topic __strimzi-topic-operator-kstreams-topic-store-changelog --bootstrap-server localhost:9092
Topic: __strimzi-topic-operator-kstreams-topic-store-changelog  TopicId: ryL0uDkrRWuLqmXaJsWozw PartitionCount: 1       ReplicationFactor: 9    Configs: min.insync.replicas=5,cleanup.policy=compact,segment.bytes=67108864,message.format.version=3.0-IV1,min.compaction.lag.ms=0,message.timestamp.type=CreateTime
        Topic: __strimzi-topic-operator-kstreams-topic-store-changelog  Partition: 0    Leader: 3       Replicas: 3,7,0,5,2,8,4,1,6     Isr: 3,7,0,5,2,8,4,1,6
```

**Comment by scholzj** [comment]
I guess the first thing you should do is configure the resource requests for it to make sure it has enough resources to start. I use something like this for development and it starts fine:

```yaml
        limits:
          cpu: 500m
          memory: 256Mi
        requests:
          cpu: 200m
          memory: 256Mi
```

You do not have any resources set, so there is absolutely no way to know what it really gets.
