### ISSUE TITLE
[Enhancement]: support allocateLoadBalancerNodePorts parameter to enable/disable dynamic nodeport creation for type LoadBalancer in Strimzi Kafka 

### ISSUE THREAD

**Issue by Janardhan78** [strimzi/strimzi-kafka-operator#8782]
### Related problem

When we create kafka cluster using strimzi operator we provide external exposure of the kafka cluster with LoadBalancer. and when the kafka cluster is created the load balancer service allocates dynamic nodePorts. 

### Suggested solution

we would require parameter support  similar to one supported by kubernetes service "allocateLoadBalancerNodePorts",  so that the dynamic node port creation can be controlled while creating kafka cluster from strimzi operator 

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#service-v1-core 

allocateLoadBalancerNodePorts

**Comment by scholzj** [comment]
Thanks for raising this. We will triage it next week on the community call. But I think this makes sense.

**Comment by scholzj** [comment]
Triaged on 13.7.2023: Makes sense as an enhancement. Should be probably added to the Listener Configuration section which already configures IP Families etc.

**Comment by prashant235913** [comment]
Hey @scholzj and @see-quick  .This enhancement is marked as good-start.I wanna contribute.Tell me something if I can do something in this.I am starting out with open source.

**Comment by scholzj** [comment]
I think @see-quick planned to work on it - not sure it is still the case, so I leave it up to him.

**Comment by see-quick** [comment]
I did not start yet. So you can assign it to yourself if you want :) @prashant235913.

**Comment by prashant235913** [comment]
Thanks @see-quick , I am not sure where to start.This is marked as 'good-start' ,Is it really is?
Or I am too dumb to understand it.
I'll love to work on this issue.Can You give some insights about how to proceed.Keeping in mind,That I am just starting with strimzi.
But yes,I really wanna contribute.
Thanks.

**Comment by scholzj** [comment]
I guess the first step is to get your self familiar with the code and with how to build Strimzi etc.

For the code, you would need to add a new field to the `GeneralKafkaListenerConfiguration` in the `api` module, update the `ListenerValidation`classes and `KafkaCluster` class to use the new API field. This PR -https://github.com/strimzi/strimzi-kafka-operator/pull/7752 - was changing an existing field and not adding a new one. So it is not exactly the same. But I would expect this to change more or less the same files.

**Comment by prashant235913** [comment]
Okay...Let me Give it a try because I successfully build strimzi and giving time to understand it.Please assign me.

**Comment by pillai-ashwin** [comment]
Hi, checking in to see if this issue is still being worked on @prashant235913? I'd love to give it a shot otherwise.

**Comment by see-quick** [comment]
Due to the inactivity from @prashant235913, I can re-assign this task to you, @pillai-ashwin, if it aligns with your schedule.

**Comment by pillai-ashwin** [comment]
I've added `allocateLoadBalancerNodePorts`, its getter & setter to the `GenericKafkaListenerConfiguration` & also added a validator for it in `ListenersValidator`  here https://github.com/pillai-ashwin/strimzi-kafka-operator/commit/3abbd31b89c180f68b8cc7c836717e78d43e30ce

If it looks good to you as a start - Any recommendations on how I can manually test these changes out?

**Comment by pillai-ashwin** [comment]
I deployed a kafka cluster locally using this config
``` yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.6.0
    replicas: 1
    listeners:
      - name: plain1
        port: 9092
        type: loadbalancer
        tls: false
        configuration:
          allocateLoadBalancerNodePorts: false
      - name: plain2
        port: 9093
        type: loadbalancer
        tls: false
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 3
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

I'm able to see these services -
``` bash
NAME                                        TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)                      AGE
service/my-cluster-kafka-plain1-0           LoadBalancer   10.100.78.211    localhost     9092:31022/TCP               64s
service/my-cluster-kafka-plain1-bootstrap   LoadBalancer   10.103.243.229   <pending>     9092:31146/TCP               64s
service/my-cluster-kafka-plain2-0           LoadBalancer   10.105.198.117   <pending>     9093:31370/TCP               64s
service/my-cluster-kafka-plain2-bootstrap   LoadBalancer   10.96.109.14     localhost     9093:31052/TCP               64s

```
I see that a `NodePort` still exists for the `plain1` `LoadBalancer` service -
``` bash
 kubectl describe service/my-cluster-kafka-plain1-bootstrap 
Name:                     my-cluster-kafka-plain1-bootstrap
Namespace:                myproject
Labels:                   app.kubernetes.io/instance=my-cluster
                          app.kubernetes.io/managed-by=strimzi-cluster-operator
                          app.kubernetes.io/name=kafka
                          app.kubernetes.io/part-of=strimzi-my-cluster
                          strimzi.io/cluster=my-cluster
                          strimzi.io/component-type=kafka
                          strimzi.io/kind=Kafka
                          strimzi.io/name=my-cluster-kafka
Annotations:              <none>
Selector:                 strimzi.io/cluster=my-cluster,strimzi.io/kind=Kafka,strimzi.io/name=my-cluster-kafka
Type:                     LoadBalancer
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.103.243.229
IPs:                      10.103.243.229
Port:                     tcp-plain1  9092/TCP
TargetPort:               9092/TCP
NodePort:                 tcp-plain1  31146/TCP
Endpoints:                <none>
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
```
