### ISSUE TITLE
[Bug]: Getting error with loadBalancerClass

### ISSUE THREAD

**Issue by girishms-sentient** [strimzi/strimzi-kafka-operator#8823]
### Bug Description

The loadBalancerClass error occurs when I try to create a Kafka cluster with ArgoCD.

Is there support for loadBalancerClass in strimzi?

### Strimzi version

0.35.0

### Kubernetes version

K8s 1.25

### Installation method

Helm chart with ArgoCD

### Infrastructure

Amazon EKS

### Configuration files and logs

`Failure executing: PATCH at: [https://172.20.0.1:443/api/v1/namespaces/central-logging/services/kafka-kafka-external-bootstrap](https://172.20.0.1/api/v1/namespaces/central-logging/services/kafka-kafka-external-bootstrap). Message: Service "kafka-kafka-external-bootstrap" is invalid: spec.loadBalancerClass: Invalid value: "null": may not change once set. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.loadBalancerClass, message=Invalid value: "null": may not change once set, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Service, name=kafka-kafka-external-bootstrap, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Service "kafka-kafka-external-bootstrap" is invalid: spec.loadBalancerClass: Invalid value: "null": may not change once set, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).`

**Comment by scholzj** [comment]
You should probably set your Load Balancer Class in the `Kafka` custom resource: https://strimzi.io/docs/operators/latest/full/configuring.html#type-GenericKafkaListenerConfiguration-schema-reference (look for the `class` field).

**Comment by girishms-sentient** [comment]
Are you referring to this?

For example: 
```
    listeners:
      - name: external
        port: 9092
        type: loadbalancer
        loadBalancerClass: service.k8s.aws/nlb
```

**Comment by scholzj** [comment]
Almost I guess. If you check the schema reference the filed name is `class`.

**Comment by scholzj** [comment]
One curious question -> did you configure the Load Balancer class on the service yourself (e.g. manually using `kubectl edit`)? Or did AWS inject it automatically?

**Comment by girishms-sentient** [comment]
@scholzj  AWS injected it automatically. 

Even if I added it in this approach, the Argo deployment continues to give me issues.

        type: loadbalancer
        loadBalancerClass: service.k8s.aws/nlb

`Failure executing: PATCH at: [https://172.20.0.1:443/api/v1/namespaces/central-logging/services/kafka-kafka-external-bootstrap](https://172.20.0.1/api/v1/namespaces/central-logging/services/kafka-kafka-external-bootstrap). Message: Service "kafka-kafka-external-bootstrap" is invalid: spec.loadBalancerClass: Invalid value: "null": may not change once set. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.loadBalancerClass, message=Invalid value: "null": may not change once set, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=Service, name=kafka-kafka-external-bootstrap, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Service "kafka-kafka-external-bootstrap" is invalid: spec.loadBalancerClass: Invalid value: "null": may not change once set, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).`

Kafka cluster config:
```
    listeners:
      - name: external
        port: 9092
        type: loadbalancer
        loadBalancerClass: service.k8s.aws/nlb
        tls: true
        authentication:
          type: tls
        configuration:
          brokers:
          - broker: 0
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: external
              service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
              service.beta.kubernetes.io/aws-load-balancer-subnets:  "subnet-xxxxxxxxxxxxxxx,subnet-xxxxxxxxxxxxxxx"
          - broker: 1
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: external
              service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
              service.beta.kubernetes.io/aws-load-balancer-subnets:  "subnet-xxxxxxxxxxxxxxx,subnet-xxxxxxxxxxxxxxx"
          - broker: 2
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: external
              service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
              service.beta.kubernetes.io/aws-load-balancer-subnets:  "subnet-xxxxxxxxxxxxxxx,subnet-xxxxxxxxxxxxxxx"
          bootstrap:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-type: external
              service.beta.kubernetes.io/aws-load-balancer-ip-address-type: ipv4
              service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: instance
              service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-xxxxxxxxxxxxxxx,subnet-xxxxxxxxxxxxxxx"
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
```
