### ISSUE TITLE
[Bug]: io.aiven.kafka.connect.opensearch.OpensearchSinkConnector broken Ready check

### ISSUE THREAD

**Issue by taylorsmithgg** [strimzi/strimzi-kafka-operator#8849]
### Bug Description

When using io.aiven.kafka.connect.opensearch.OpensearchSinkConnector, if a connector is manually deleted from kafka connect, it will not update the Ready status or attempt to reconcile.

### Steps to reproduce

1. Install io.aiven.kafka.connect.opensearch.OpensearchSinkConnector
2. Create `KafkaConnector`
  ```
  apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaConnector
  metadata:
    namespace: kafka
    name: opensearch-sink-connector
    labels:
      # The strimzi.io/cluster label identifies the KafkaConnect instance
      # in which to create this connector. That KafkaConnect instance
      # must have the strimzi.io/use-connector-resources annotation
      # set to true.
      strimzi.io/cluster: connect-managed-cluster
  spec:
    pause: false
    class: io.aiven.kafka.connect.opensearch.OpensearchSinkConnector
    autoRestart:
      enabled: true
    tasksMax: 1
    config:
      write.method: upsert
      flush_synchronously: true
      name: opensearch-sink-connector
      topics: input.topic
      connection.url: https://my-es-or-opensearch.com
      connection.username: <user>
      connection.password: <password>
      value.converter: io.confluent.connect.avro.AvroConverter
      value.converter.schema.registry.url: http://kafka-registry-cp-schema-registry:8081
      key.converter: io.confluent.connect.avro.AvroConverter
      key.converter.schema.registry.url: http://kafka-registry-cp-schema-registry:8081
      type.name: '_doc'
      tasks.max: 1
      schema.ignore: true
      key.ignore: false
      errors.tolerance: all
      transforms: dropPrefix
      transforms.dropPrefix.type: org.apache.kafka.connect.transforms.RegexRouter
      transforms.dropPrefix.regex: 'topic-prefix.(.*)'
      transforms.dropPrefix.replacement: '$1'
      behavior.on.version.conflict: warn
      delete.enabled: false
      auto.create: true
      auto.evolve: true
   ```
3. Delete the connector from connect API
  ```
   curl -X DELETE http://<kafka-connect-host>:<port>/connectors/opensearch-sink-connector
  ```
4. Observe that Strimzi does not reconcile or detect the deleted connector

### Expected behavior

When a connector is manually deleted but a `KafkaConnector` object still exists, strimzi should detect the drift and reconcile accordingly.

### Strimzi version

0.33.2

### Kubernetes version

1.23

### Installation method

Helm chart

### Infrastructure

Amazon EKS

### Configuration files and logs

No customizations

**Comment by scholzj** [comment]
Please share the full logs from the cluster operator - a DEBUG log level would be best, but even INFO would be a start.

**Comment by scholzj** [comment]
Also, the KafkaConnector resource above is invalid -> not sure if that is a copy-paste error or if it is related.

**Comment by taylorsmithgg** [comment]
> Also, the KafkaConnector resource above is invalid -> not sure if that is a copy-paste error or if it is related.

fixed the formatting

**Comment by taylorsmithgg** [comment]
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: connect-managed-cluster
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
  labels:
    strimzi.io/cluster: connect-managed-cluster
#  # use-connector-resources configures this KafkaConnect
#  # to use KafkaConnector resources to avoid
#  # needing to call the Connect REST API directly
spec:
  template:
    pod:
  logging:
    loggers:
      connect.root.logger.level: WARN
    type: inline
  jmxOptions: {}
  replicas: 1
  image: quay.io/strimzi/kafka:0.29.0-kafka-3.2.0
  bootstrapServers: kafka-kafka-bootstrap:9092
  config:
    config.providers: secrets,configmaps
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    config.providers.configmaps.class: io.strimzi.kafka.KubernetesConfigMapConfigProvider
    group.id: connect-managed-cluster
    offset.storage.topic: connect-managed-cluster-offsets
    config.storage.topic: connect-managed-cluster-configs
    status.storage.topic: connect-managed-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: 2
    offset.storage.replication.factor: 2
    status.storage.replication.factor: 2
    offset.storage.partitions: 1
    status.storage.partitions: 1
    errors.log.enable: "true"
    offset.flush.timeout.ms: 10000
    # connector.client.config.override.policy: all
    # producer.override.batch.size: 327680
    # topic.creation.default.partitions: 10
    # topic.creation.default.delete.retention.ms: 100
    # topic.creation.default.segment.ms: 100
    # topic.creation.default.min.cleanable.dirty.ratio: 0.01
  rack:
    topologyKey: topology.kubernetes.io/zone
  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: kafka-metrics
        key: connect-metrics-config.yml
  externalConfiguration:
    env:
      - name: SCHEMA
        valueFrom:
          secretKeyRef:
            name: connect-credentials
            key: schema
```
