### ISSUE TITLE
[Bug]: Default CA certs are not renewing after one year and my zookeeper pods are failing to start

### ISSUE THREAD

**Issue by JaviOverflow** [strimzi/strimzi-kafka-operator#8861]
### Bug Description

My cluster CA certificates expired and the strimzi operator is not renewing them. One of my zookeeper pods is failing to start now.

Something I noticed as well is that my zookeeper pods have the annotation `strimzi.io/cluster-ca-cert-generation=0` and `strimzi.io/generation=0`, I don't know if that's relevant.

I'm not using custom CA certs and I've never provided one. I created this cluster about 1 year and 1 month ago.

### Steps to reproduce

1. Create a strimzi cluster with the yaml provided
2. Wait 1 year plus
3. CA certs are expired and not renewed

### Expected behavior

CA certs to be renewed and zookeeper able to restart without problems

### Strimzi version

0.29.0

### Kubernetes version

1.24

### Installation method

Helm Chart

### Infrastructure

Amazon EKS

### Configuration files and logs

Zookeeper pod error:

```
Detected Zookeeper ID 3
Preparing truststore
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/zookeeper/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore is complete
Looking for the right CA
No CA found. Thus exiting.
```

When I inspect the ca.pk12 in the other running zookeeper pods I can see it expired on Mon Jun 19 11:34:21 GMT 2023

```
[kafka@kafka-cluster-zookeeper-1 cluster-ca-certs]$ keytool -list -v -keystore ca.p12 -storepass $(cat ca.password) -storetype PKCS12
Keystore type: PKCS12
Keystore provider: SUN

Your keystore contains 1 entry

Alias name: ca.crt
Creation date: Jul 19, 2023
Entry type: trustedCertEntry

Owner: CN=cluster-ca v0, O=io.strimzi
Issuer: CN=cluster-ca v0, O=io.strimzi
Serial number: 36fc0aa2fb1a9b6b9e5eaa8b3bc279b7daaed06d
Valid from: Sun Jun 19 11:34:21 GMT 2022 until: Mon Jun 19 11:34:21 GMT 2023
Certificate fingerprints: ....
Signature algorithm name: SHA512withRSA
Subject Public Key Algorithm: 4096-bit RSA key
Version: 3
```

This is the YAML I used to create the cluster

```yaml
# https://strimzi.io/docs/operators/0.22.1/full/using.html#type-Kafka-reference
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.2.0
    replicas: 3
    storage:
      size: 15Gi
      type: persistent-claim
      deleteClaim: false
      class: gp3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.2"
  zookeeper:
    replicas: 3
    storage:
      deleteClaim: false
      type: persistent-claim
      size: 3Gi
      class: gp3
  entityOperator:
    topicOperator: {}
    userOperator: {}
```
