### ISSUE TITLE
[Bug]: Cluster operator allows multiple jbod disks for Kraft with Nodepools

### ISSUE THREAD

**Issue by Frawless** [strimzi/strimzi-kafka-operator#8955]
### Bug Description

When user tries to deploy Kraft Kafka with nodepool that contains JBOD storage config with 2 or more disks, the cluster starts rolling updated but the pod end-up in the crashloopbackoff. This is currently known limitation and the yaml should be validated on Operator side. JBOD with 1 disk works fine.

### Steps to reproduce

1. Deploy CO
2. Deploy Kafka with jbod configuration with 2 disks

### Expected behavior

Kafka will be in `NotReady` state as this configuration is not supported.

### Strimzi version

main

### Kubernetes version

OpenShift 4.13.6

### Installation method

YAML files

### Infrastructure

Openstack

### Configuration files and logs

```
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: broker
  labels:
    strimzi.io/cluster: horus
spec:
  replicas: 5
  roles:
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
      - id: 1
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
```
