### ISSUE TITLE
Kafaka Debizium connector doesnt not send new record after taken snapshot

### ISSUE THREAD

**Issue by amitdrana** [strimzi/strimzi-kafka-operator#9030]
### Discussed in https://github.com/orgs/strimzi/discussions/9028

<div type='discussions-op-text'>

<sup>Originally posted by **amitdrana** August 25, 2023</sup>
Hi,
 I have setup strimzi source kafka connector with debizium.Everything is working fine no error in the broker and connector. but we are facing 2 issue
 
 1. The connector connected to the bin log after exporting the existing records but did not send the new record after being connected to the bin log.
 2. While the initial snapshot is going on and the connector restarts it again sends the record from the start.
 
 Following are the connector configuration:
 
```
 spec:
 class: io.debezium.connector.mysql.MySqlConnector
 config:
   group.id: transaction-4-source-connect
   tasks.max: 1
   topic.creation.enable: true
   topic.creation.default.replication.factor: 3
   topic.creation.default.partitions: 240
   database.hostname: 185.103.98.2
   database.port: 3306
   database.user: **
   database.password: **
   database.server.id: 19046
   database.server.name: **
   snapshot.mode: "initial"
   database.whitelist: "**"
   include.schema.changes: "true"
   database.include.list: "**"
   retention.ms: 2592000000
   retention.bytes: 42949672960
   database.allowPublicKeyRetrieval: true
   exactly.once.support: requested
   table.include.list: "***"
    database.history.kafka.bootstrap.servers: mfsa-kafka-prod-kafka-bootstrap:9093
   database.history.kafka.topic: schema-changes.transaction-4
   database.history.producer.security.protocol: SSL
   database.history.producer.ssl.keystore.type: PKCS12
   database.history.producer.ssl.keystore.location: /opt/kafka/external-configuration/my-user/user.p12
   database.history.producer.ssl.keystore.password: ${secrets:mfsa-kafka/curbi-user:user.password}
   database.history.producer.ssl.truststore.type: PKCS12
   database.history.producer.ssl.truststore.location: /opt/kafka/external-configuration/cluster-ca/ca.p12
   database.history.producer.ssl.truststore.password: ${secrets:mfsa-kafka/mfsa-kafka-prod-cluster-ca-cert:ca.password}

   database.history.consumer.security.protocol: SSL
   database.history.consumer.ssl.keystore.type: PKCS12
   database.history.consumer.ssl.keystore.location: /opt/kafka/external-configuration/my-user/user.p12
   database.history.consumer.ssl.keystore.password: ${secrets:mfsa-kafka/curbi-user:user.password}
   database.history.consumer.ssl.truststore.type: PKCS12
   database.history.consumer.ssl.truststore.location: /opt/kafka/external-configuration/cluster-ca/ca.p12
   database.history.consumer.ssl.truststore.password: ${secrets:mfsa-kafka/mfsa-kafka-prod-cluster-ca-cert:ca.password}
   key.converter: org.apache.kafka.connect.json.JsonConverter
   key.converter.schemas.enable: true
   value.converter: org.apache.kafka.connect.json.JsonConverter
   value.converter.schemas.enable: true
```
  </div>
