### ISSUE TITLE
[ST]: `testKafkaRollsWhenTopicIsUnderReplicated` and `testKafkaNodePoolBrokerIdsManagementUsingAnnotations` fails since broker contains partition replicas while scale down happens

### ISSUE THREAD

**Issue by ShubhamRwt** [strimzi/strimzi-kafka-operator#9134]
### Bug Description

While running ST's on #9042, the test `testKafkaRollsWhenTopicIsUnderReplicated` in KafkaRollerST  and the test `testKafkaNodePoolBrokerIdsManagementUsingAnnotations` in KafkaNodePoolsST fails since the brokers are not scaled down nicely and they contain paritition replicas.

```
  status:
    clusterId: YqrVF1YgQHGOf1gvqMOsVw
    conditions:
    - lastTransitionTime: "2023-09-18T23:34:20.596201107Z"
      message: Cannot scale down brokers [6] because brokers [6] are not empty
      reason: InvalidResourceException
      status: "True"
      type: NotReady
    kafkaVersion: 3.5.1
    observedGeneration: 1
    operatorLastSuccessfulVersion: 0.38.0-SNAPSHOT
```

### Steps to reproduce

1. Go to KafkaRollerST class
2. Enable the broker scale down check
3. Run the `testKafkaRollsWhenTopicIsUnderReplicated` method
4. The reconciliation should fail with `InvalidResourceException: Cannot scale down brokers [6] because brokers [6] are not empty`

### Strimzi version

0.37.0

### Kubernetes version

1.25.3
