### ISSUE TITLE
[Bug]: ssl.endpoint.identification.algorithm is forbidden

### ISSUE THREAD

**Issue by davidfaulkner12** [strimzi/strimzi-kafka-operator#9181]
### Bug Description

In the [documentation](https://strimzi.io/docs/operators/latest/configuring.html#con-common-configuration-ssl-reference), `ssl.endpoint.identification.algorithm` is explicitly stated as a configuration parameter that can be set.

> Use the `ssl.endpoint.identification.algorithm` property to enable or disable hostname verification.

However, in the logs for the `strimzi-operator`, I see the following message:

```
2023-09-29 18:48:56 WARN  AbstractConfiguration:147 - Reconciliation #217(timer) Kafka(strimzi/strimzi-cluster): Configuration option "ssl.endpoint.identification.algorithm" is forbidden and will be ignored
2023-09-29 18:48:58 WARN  AbstractConfiguration:147 - Reconciliation #217(timer) Kafka(strimzi/strimzi-cluster): Configuration option "ssl.endpoint.identification.algorithm" is forbidden and will be ignored
```

### Steps to reproduce

```
kubectl -n strimzi get kafka/strimzi-cluster -o yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  annotations:
  creationTimestamp: "2023-09-29T17:35:16Z"
  generation: 7
  labels:
    app.kubernetes.io/managed-by: pulumi
  name: strimzi-cluster
  namespace: strimzi
spec:
  entityOperator:
    userOperator: {}
  kafka:
    config:
      default.replication.factor: 3
      inter.broker.protocol.version: "3.5"
      min.insync.replicas: 2
      offsets.topic.replication.factor: 3
      ssl.endpoint.identification.algorithm: ""
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 3
    listeners:
    - authentication:
        type: scram-sha-512
      name: tls
      port: 9093
      tls: true
      type: cluster-ip
    rack:
      topologyKey: topology.kubernetes.io/zone
    replicas: 3
    resources:
      requests:
        cpu: "7"
        memory: 60Gi
    storage:
      class: nvme-ssd
      deleteClaim: false
      size: 5500Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-group
                  operator: In
                  values:
                  - strimzi-ng-arm64
        tolerations:
        - effect: NoSchedule
          key: workload
          operator: Equal
          value: strimzi
        - effect: NoExecute
          key: workload
          operator: Equal
          value: strimzi
      podDisruptionBudget:
        maxUnavailable: 0
    version: 3.5.1
  zookeeper:
    config:
      ssl.endpoint.identification.algorithm: ""
    replicas: 3
    storage:
      class: nvme-ssd
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-group
                  operator: In
                  values:
                  - strimzi-control-ng-arm64
        tolerations:
        - effect: NoSchedule
          key: workload
          operator: Equal
          value: strimzi-control
        - effect: NoExecute
          key: workload
          operator: Equal
          value: strimzi-control
      podDisruptionBudget:
        maxUnavailable: 0
```

### Strimzi version

0.37.0

### Kubernetes version

25

### Installation method

Helm Chart

### Infrastructure

EKS
