### ISSUE TITLE
[Bug]: KafkaMirrorMaker2 TopicsPattern not working

### ISSUE THREAD

**Issue by viscory** [strimzi/strimzi-kafka-operator#9243]
### Bug Description

Hi

I have a few topics I am trying to replicate, named X_Y_A, X_Y_B, X_Y_C.

When I set TopicsPattern to X_Y_A, it replicated on topic, but X_Y_.* replicates nothing, X_Y_A|X_Y_B works, .* works as well.

It doesnt seem like this field follows normal regex. Please advise us on how to proceed.

### Steps to reproduce

When I set TopicsPattern to X_Y_A, it replicated on topic, but X_Y_.* replicates nothing, X_Y_A|X_Y_B works, .* works as well.

### Expected behavior

I expect X_Y_.* to replicate all three topics

### Strimzi version

0.37.0

### Kubernetes version

1.24

### Installation method

Helm

### Infrastructure

Aliyun ACK

**Comment by scholzj** [comment]
Please share your configuration (the custom resource) and full logs.

**Comment by viscory** [comment]
```
        helm:
          releaseName: strimzi-mirrormaker2
          valueFiles:
            - REDACTED
          parameters:
            - name: mirrorMaker2.sourceCluster.bootstrapServers
              value: REDACTED
            - name: mirrorMaker2.topicsPattern
              value: "X_Y_.*"
      destination:
        name: '{{ REDACTED
        namespace: 'REDACTED'
      syncPolicy: {}

```

```
    - sourceCluster: {{ .Values.mirrorMaker2.sourceCluster.alias }}
      targetCluster: {{ .Values.mirrorMaker2.targetCluster.alias }}
      {{- with .Values.mirrorMaker2.sourceConnector }}
      sourceConnector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mirrorMaker2.heartbeatConnector }}
      heartbeatConnector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mirrorMaker2.checkpointConnector }}
      checkpointConnector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      topicsPattern: {{ .Values.mirrorMaker2.topicsPattern }}

  {{- with .Values.mirrorMaker2.metricsConfig }}
  metricsConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}

```
