### ISSUE TITLE
[Bug]: Authorization for Produscers fail after upgrading to Kafka 3.2.x / Strimzi-Operator 0.29.0

### ISSUE THREAD

**Issue by iceman91176** [strimzi/strimzi-kafka-operator#9261]
### Bug Description

We just started upgading an older strimzi-operated cluster (strimzi 0.27.x, with kafka 3.0.0). As first step we upgraded strimzi-operator to 0.29.0 as it is the latest versino to support kafka 3.0.x. We followed the instructions and now are running a kafka 3.2.x cluster. 
Next step was upgrading our clients and we have a major problem with Kafka-Authorization. We are using keycloak-based authorization which was working without any problems so far.

But as soon as we update our client applications to kafka-client version 3.2.3 none of out producer-clients are able to access the cluster any more.

Writing to topics fails with

`Caused by: org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.`

More logs below

As soon as we switch back to kafka-clients 3.0.x all is fine again. Consumers don't have an issue at all. Also kafka-connect (strimzi-based) has no problems.

### Expected behavior

Writing to the topics should not fail due to authorization errors

### Strimzi version

0.29.0

### Kubernetes version

Kubernetes 1.27.6

### Installation method

Helm chart

### Infrastructure

Bare-Metal

### Configuration files and logs

Cluster-Specs (upgrading is not done yet, so inter.broker.protocol.version is still 3.0)

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: test-cluster
  namespace: strimzi-operator
spec:
  entityOperator:
    template:
      pod:
        metadata:
          labels:
            kafka-role: entity-operator
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/cluster-service
        - effect: PreferNoSchedule
          key: node-role.kubernetes.io/cluster-service
    topicOperator:
      logging:
        type: external
        valueFrom:
          configMapKeyRef:
            key: log4j2.properties
            name: logging-entity-operator-configmap
      resources:
        requests:
          cpu: "1"
          memory: 1Gi
    userOperator:
      logging:
        type: external
        valueFrom:
          configMapKeyRef:
            key: log4j2.properties
            name: logging-entity-operator-configmap
      resources:
        requests:
          cpu: "1"
          memory: 1Gi
  kafka:
    authorization:
      clientId: test-cluster
      superUsers:
      - demoadmin
      - kafkaadmin
      tokenEndpointUri: ***
      type: keycloak
    config:
      auto.create.topics.enable: "false"
      inter.broker.protocol.version: "3.0"
      offsets.topic.replication.factor: 2
      transaction.state.log.min.isr: 2
      transaction.state.log.replication.factor: 2
    listeners:
    - authentication:
        accessTokenIsJwt: true
        checkAccessTokenType: true
        checkIssuer: true
        clientId: test-cluster
        clientSecret:
          key: secret
          secretName: test-cluster-oauth-secret
        enableOauthBearer: true
        introspectionEndpointUri: ***
        maxSecondsWithoutReauthentication: 3600
        type: oauth
        userNameClaim: preferred_username
        validIssuerUri: ***
      name: internal
      port: 9093
      tls: true
      type: internal
    - authentication:
        accessTokenIsJwt: true
        checkAccessTokenType: true
        checkIssuer: true
        clientId: test-cluster
        clientSecret:
          key: secret
          secretName: test-cluster-oauth-secret
        enableOauthBearer: true
        introspectionEndpointUri: ***
        maxSecondsWithoutReauthentication: 3600
        type: oauth
        userNameClaim: preferred_username
        validIssuerUri: ***
      configuration:
        bootstrap:
          alternativeNames:
          - ***
          annotations:
            external-dns.alpha.kubernetes.io/hostname: ***
            kubernetes.io/external-dns.type: private
        brokerCertChainAndKey:
          certificate: tls.crt
          key: tls.key
          secretName: kafka-test-cluster-lets-encrypt
        brokers:
        - advertisedHost: ***
          annotations:
            external-dns.alpha.kubernetes.io/hostname: ***
            kubernetes.io/external-dns.type: private
          broker: 0
        - advertisedHost: ***
          annotations:
            external-dns.alpha.kubernetes.io/hostname: ***
            kubernetes.io/external-dns.type: private
          broker: 1
        externalTrafficPolicy: Local
      name: external
      port: 9094
      tls: true
      type: loadbalancer
    logging:
      type: external
      valueFrom:
        configMapKeyRef:
          key: log4j.properties
          name: logging-configmap
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    replicas: 2
    resources:
      requests:
        cpu: "4"
        memory: 32Gi
    storage:
      type: jbod
      volumes:
      - deleteClaim: true
        id: 0
        size: 100Gi
        type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/cluster-service
                  operator: Exists
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/cluster-service
        - effect: PreferNoSchedule
          key: node-role.kubernetes.io/cluster-service
    version: 3.2.0
  kafkaExporter:
    resources:
      requests:
        cpu: 200m
        memory: 64Mi
  zookeeper:
    logging:
      type: external
      valueFrom:
        configMapKeyRef:
          key: log4j.properties
          name: logging-zookeeper-configmap
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 2
    storage:
      deleteClaim: true
      size: 100Gi
      type: persistent-claim
    template:
      pod:
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/cluster-service
                  operator: Exists
        tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/cluster-service
        - effect: PreferNoSchedule
          key: node-role.kubernetes.io/cluster-service
```

Client-Logs 

```[nocsource01-noc-source-connector-7d58ff974-6v2t7] 2023-10-18 16:52:10.942 ERROR 1 --- [ad | producer-1] o.s.k.support.LoggingProducerListener    : Exception thrown when sending a message with key='TICKET-2216' and payload='eventId: "TICKET-2216"
[nocsource01-noc-source-connector-7d58ff974-6v2t7] entityType: NOC_ENTITY_TYPE_TICKET
[nocsource01-noc-source-connector-7d58ff974-6v2t7] entityId: 2216
[nocsource01-noc-source-connector-7d58ff974-6v2t7] requestType: NOC_ENTITY_REQ...' to topic wit.sys.noc-source-connector-01.entity-request.1:
[nocsource01-noc-source-connector-7d58ff974-6v2t7]
[nocsource01-noc-source-connector-7d58ff974-6v2t7] org.apache.kafka.common.errors.ClusterAuthorizationException: Cluster authorization failed.

```

As soon as the client-errors happens we get the following on the brokers

```
[test-cluster-kafka-1] {"@timestamp":"2023-10-18T16:52:07.921Z","source_host":"test-cluster-kafka-1","file":"AclAuthorizer.scala","method":"logAuditMessage","level":"INFO","line_number":"614","thread_name":"data-plane-kafka-request-handler-7","@version":1,"logger_name":"kafka.authorizer.logger","message":"Principal = OAuthKafkaPrincipal(User:service-account-noc-source-connector-01-client, groups: null, session: 382392697, token: eyJh**4AKw) is Denied Operation = Write from host = 10.113.156.49 on resource = Topic:UNKNOWN:NONE for request = InitProducerId with resourceRefCount = 0","class":"kafka.security.authorizer.AclAuthorizer","mdc":{}}
```

The write operation is denied - but why does the  broker think the client is trying to access resource Topic:UNKNOWN:NONE ?
The topic the client tries to write to is named wit.sys.noc-source-connector-01.entity-request.1
