### ISSUE TITLE
[Bug]: TopicOperator doesn't work with KRaft flags

### ISSUE THREAD

**Issue by ventsislav-georgiev** [strimzi/strimzi-kafka-operator#9262]
### Bug Description

I have a cluster with a Zookeeper that works properly. The moment I enable the featureGates required for using KRaft (+UseKRaft,+KafkaNodePools,+UnidirectionalTopicOperator) the topic operator stops working. I've not added any annotations to the Kafka resource nor added any Kafka node pools. Just enabled the feature flags.

The topic operator is in Running state and does not fail its liveness or readiness probe. However, it does not work and logs constantly the same Unexpected Exception error:
```
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "requested" is null   
```

The only config added for the topicOperator in the Kafka resource is the following:
```
    topicOperator:
      jvmOptions:
        -Xms: 128m
        -Xmx: 128m
      resources:
        limits:
          memory: 600Mi
        requests:
          cpu: 100m
          memory: 600Mi
```

### Expected behavior

Is there any required modification to the Kafka resource in order to be able to enable the feature gates? The intention here is to utilize the new feature of having multiple clusters one with Zookeeper and one with KRaft. Currently just enabling the feature gate, stops the TopicOperator of the Zookeeper cluster of working properly.

### Strimzi version

0.38.0

### Kubernetes version

1.27.4

### Installation method

Helm

### Infrastructure

GKE

### Configuration files and logs

<img width="1727" alt="image" src="https://github.com/strimzi/strimzi-kafka-operator/assets/5616486/794e64d1-5733-4155-b8a1-790d89e191ca">

**Comment by scholzj** [comment]
Can you please provide more step by step guide what exactly you do and share your Cluster Operator configuration and the Kafka custom resource?

There is no support for KRaft migration or upgrades. So the `UseKRaft` feature gate should not be enabled with any existing Kafka resources. You should enable it without any Kafka clusters and only once enabled create the Kafka resource. But it is not really clear to me if this is related to your problem or not because I do not really understand your configuration and what you do.

I used the `+UseKRaft,+KafkaNodePools,+UnidirectionalTopicOperator` combination several times while testing the 0.38 release without any problems. So I do not think this is a general issue and I cannot reproduce it by just enabling them.

**Comment by ventsislav-georgiev** [comment]
The cluster operator is installed via helm with terraform provider:
```
resource "helm_release" "strimzi" {
  name       = "strimzi"
  namespace  = local.strimzi_namespace
  chart      = "strimzi-kafka-operator"
  repository = "oci://quay.io/strimzi-helm"
  version    = "0.38.0"
  atomic     = false
  values     = [file("strimzi.yml")]

  depends_on = [kubectl_manifest.strimzi_namespace]
}
```

and has the following values (the strimzi.yml from above):
```
priorityClassName: critical
generateNetworkPolicy: false
tmpDirSizeLimit: 10Mi
watchAnyNamespace: true
featureGates: +UseKRaft,+KafkaNodePools,+UnidirectionalTopicOperator
```

The kafka resource has the following:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  labels:
    app: strimzi
  name: strimzi
  namespace: strimzi
spec:
  entityOperator:
    template:
      pod:
        priorityClassName: high
    topicOperator:
      jvmOptions:
        -Xms: 128m
        -Xmx: 128m
      resources:
        limits:
          memory: 600Mi
        requests:
          cpu: 100m
          memory: 600Mi
    userOperator:
      resources:
        limits:
          memory: 600Mi
        requests:
          cpu: 200m
          memory: 600Mi
      watchedNamespace: staging
  kafka:
    authorization:
      superUsers:
      - offsets-manager-user
      type: simple
    config:
      auto.create.topics.enable: "true"
      default.replication.factor: 3
      delete.topic.enable: false
      log.retention.hours: 168
      min.insync.replicas: 2
      num.partitions: 12
      offsets.retention.minutes: 129600
    jmxOptions: {}
    jvmOptions:
      -Xms: 555m
      -Xmx: 555m
    listeners:
    - authentication:
        type: scram-sha-512
      name: plainsasl
      port: 9094
      tls: false
      type: internal
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: kafka-metrics-config.yml
          name: kafka-metrics
    readinessProbe:
      failureThreshold: 3
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    replicas: 3
    resources:
      limits:
        memory: 2500Mi
      requests:
        cpu: 1
        memory: 2500Mi
    storage:
      deleteClaim: false
      size: 100Gi
      type: persistent-claim
    template:
      pod:
        priorityClassName: critical
    version: 3.5.1
  kafkaExporter:
    groupRegex: .*
    topicRegex: .*
  zookeeper:
    jmxOptions: {}
    jvmOptions:
      -Xms: 170m
      -Xmx: 170m
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          key: zookeeper-metrics-config.yml
          name: kafka-metrics
    replicas: 3
    resources:
      limits:
        memory: 768Mi
      requests:
        cpu: 10m
        memory: 768Mi
    storage:
      deleteClaim: false
      size: 2Gi
      type: persistent-claim
    template:
      pod:
        priorityClassName: critical
```

**Comment by ventsislav-georgiev** [comment]
There are also many (~500) topic resources that look like this:
```
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: 'ping'
  labels:
    strimzi.io/cluster: 'strimzi'
    created_by: system
spec:
  topicName: 'ping'

```
