### ISSUE TITLE
[Enhancement]: Configurable user credentials format

### ISSUE THREAD

**Issue by borisssmidtCET** [strimzi/strimzi-kafka-operator#9267]
### Related problem

The current generated secret contains the files:
```
user.password                                                                                                                                                                                                                  
ca.crt
user.crt
user.key
user.p12
```
To connect using golang we need pem files.
While if you connect using the jvm you need a jks or pem file.

### Suggested solution

Since a user is often used by 1 language only it would be possible add a new field to decide which secret format you get.
```
authentication:
	type: tls
	format: jsk | p12 | pem
```
Another possible solution is to just generate the 3 different formats then the user doesn't need to convert anything but this makes the secrets bigger.

### Alternatives

Another solution i have is that i write a custom operator which converts the secrets to the right format. But then i have to manage more operators. 

### Additional context

Another usefull feature would be that you can merge secrets. Like the `external-secrets` operator can do. 
Then this operator only regenerates the secrest when its managed fields are updated. This would allow you to combine the kafka secret with the application secret to generate a single secret per application.

https://external-secrets.io/latest/api/externalsecret/
```
  # the target describes the secret that shall be created
  # there can only be one target per ExternalSecret
  target:

    # The secret name of the resource
    # Defaults to .metadata.name of the ExternalSecret
    # It is immutable
    name: application-config

    # Enum with values: 'Owner', 'Merge', or 'None'
    # Default value of 'Owner'
    # Owner creates the secret and sets .metadata.ownerReferences of the resource
    # Merge does not create the secret, but merges in the data fields to the secret
    # None does not create a secret (future use with injector)
    creationPolicy: 'Merge'
```
