### ISSUE TITLE
[Bug]: Images for kafkaExporter & tlsSidecar are out of sync

### ISSUE THREAD

**Issue by xor22h** [strimzi/strimzi-kafka-operator#9277]
### Bug Description

If you don't set image inside Kafka resource spec, and only set version, images used by TLS Sidecar & kafkaExporter is not accounting that version, and uses older image.

For example, using Strimzi 0.37.0 default kafka version is 3.5.1. If you set kafka.spec.version to 3.4.0, the kafka & zookeeper pods are using expected proper image, but tlsSidecar & kafkaExporter is using the 3.5.1 (default). Which might cause imagePullBackoff on airgapped deployments.

### Steps to reproduce

1. Apply kafka CRD:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: release-name-kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 3
    resources: 
      {}
    listeners:
      - name: tls
        port: 9092
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        type: nodeport
        tls: true
        configuration:
          bootstrap:
            nodePort: 30107
          brokers:
          - broker: 0
            nodePort: 30109
          - broker: 1
            nodePort: 30111
          - broker: 2
            nodePort: 30113
        authentication:
          type: scram-sha-512
      - name: extplain
        port: 9095
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 30108
          brokers:
          - broker: 0
            nodePort: 30110
          - broker: 1
            nodePort: 30112
          - broker: 2
            nodePort: 30114
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: 
        size: 10Gi
        deleteClaim: false
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: '9404'
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: release-name-kafka-metrics-config
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      class: 
      size: 10Gi
      deleteClaim: false
    template:
      pod:
        securityContext: 
          fsGroup: 1000
          fsGroupChangePolicy: OnRootMismatch
          runAsGroup: 1000
          runAsUser: 1000
          seLinuxOptions:
            level: s0:c1,c2
        affinity: 
          {}
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: '9404'
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: release-name-kafka-metrics-config
          key: zookeeper-metrics-config.yml
  entityOperator:
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
  kafkaExporter:
    topicRegex: ".*"
    groupRegex: ".*"
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: '9404'
```

### Expected behavior

Images are in sync, and kafka.spec.version is accounted properly for every related image.

### Strimzi version

0.37.0

### Kubernetes version

Kubernetes 1.25

### Installation method

Helm Chart

### Infrastructure

Openstack

**Comment by scholzj** [comment]
That is not a bug, that is as designed and intended. These images have their own configuration https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/060-Deployment-strimzi-cluster-operator.yaml#L50-L55 that is driving it and the software is the same for every Kafka version. So there i no need to adjust it based on the version.

The general expectation is that if you want to use it in disconnected environment, you should have all the images available there. But if you want, you should be also able to just change the operator configuration linked above to use the images from other Kafka version, it should normally make no difference.

**Comment by xor22h** [comment]
Althought I'm aware of these default images env variables set on Strimzi Cluster Operator itself - it doesn't make too much sense.

I've also found another way, to explicitly set images inside kafka CR.

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: release-name-kafka
spec:
  kafka:
    version: 3.4.0
    image: quay.io/strimzi/kafka:0.37.0-kafka-3.4.0  # technically not needed here, as being picked properly from version field above
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        class: 
        size: 10Gi
        deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: release-name-kafka-metrics-config
          key: kafka-metrics-config.yml
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      class: 
      size: 10Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: release-name-kafka-metrics-config
          key: zookeeper-metrics-config.yml
  entityOperator:
    tlsSidecar:
      image: quay.io/strimzi/kafka:0.37.0-kafka-3.4.0  # workaround the issue
    topicOperator: {}
    userOperator: {}
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
  kafkaExporter:
    image: quay.io/strimzi/kafka:0.37.0-kafka-3.4.0 # workaround the issue
    topicRegex: ".*"
    groupRegex: ".*"
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/scrape: "true"
            prometheus.io/path: "/metrics"
            prometheus.io/port: '9404'
```

It's just a bit weird that kafka.spec.image is taking kafka.spec.version into account, but jmxExporter and tlsSidecar doesn't.

If we talk about disconnected enviroment, i understand that we can take all supported images for packaging, but that's also taking images into docker daemon which we are not even going to use, but some customers still scan every image delivered, causing "high" vulnerability counts for something we not even using. 

Expectation would be maybe just to update the docs, to clearly state that these two containers don't take into account kafka's version, and always picks the DEFAULT version.
