### ISSUE TITLE
[Bug]: Operator does not create zookeeper strimzipodset

### ISSUE THREAD

**Issue by Elyytscha** [strimzi/strimzi-kafka-operator#9320]
### Bug Description

its not possible to install a kafka instance via operator on GKE
debug logs:
[strimzi-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/13249708/strimzi-operator.log)

### Steps to reproduce

1. Create the following resources on GKE cluster 1.25.x
```
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: strimzi-kafka-operator
  namespace: operators
spec:
  channel: stable
  name: strimzi-kafka-operator
  source: operatorhubio-catalog
  sourceNamespace: olm
  installPlanApproval: Automatic
  config:
    env:
      - name: STRIMZI_LOG_LEVEL
        value: DEBUG
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: graphql-hive-kafka
spec:
  kafka:
    version: 3.6.0
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: ${kafka_size}
        deleteClaim: true
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

### Strimzi version

0.38.0

### Kubernetes version

1.25 GKE

### Installation method

Operatorhub.io

### Infrastructure

GKE

### Additional context

it has worked (maybe) a few versions before, because we installed and used kafka cluster via strimzi operator already successful, the only thing which changed, was the operator version, due to auto olm upgrade
