### ISSUE TITLE
[Bug]: Improve performance of cluster

### ISSUE THREAD

**Issue by ducle-ttlab** [strimzi/strimzi-kafka-operator#9321]
### Bug Description

I have create cluster kafka with strimzi with change many way from increase `resources` or `replicas` but when i'm testing performance with `kafka-producer-perf-test.sh` number it's doesn't change alway around `359324.469996 records/sec` how can i improve this to procedure 1 million records ?

My command testing
```
/opt/kafka/bin/kafka-producer-perf-test.sh \
    --topic my-topic \
    --num-records 1000000 \
    --record-size 300 \
    --throughput -1 \
    --producer.config /tmp/perf.properties \
    --producer-props \
        batch.size=200000 \
        linger.ms=100 \
        compression.type=lz4 \
        acks=1
```

My config 
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.6.0
    replicas: 3
    resources:
      requests:
        memory: 16Gi
        cpu: "8"
    listeners:
      - name: plain
        port: 9093
        type: internal
        tls: false
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.6"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        deleteClaim: false 
  zookeeper:
    replicas: 5
    resources:
      requests:
        memory: 16Gi
        cpu: "8"
    jvmOptions:
      -Xms: 4096m
      -Xmx: 4096m
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
```

### Expected behavior

Improve procedure 1 million records/second

### Strimzi version

latest

### Kubernetes version

1.28.1
