### ISSUE TITLE
[Bug]: NPE when trying KRaft setup

### ISSUE THREAD

**Issue by FlowsenAusMonotown** [strimzi/strimzi-kafka-operator#9336]
### Bug Description

When try to run KRaft mode, there is a NPE in the reconciliation process: 

```
│ 2023-11-08 07:20:54 INFO  ClusterOperator:142 - Triggering periodic reconciliation for namespace *                                                                                                                                  │
│ 2023-11-08 07:20:54 INFO  AbstractOperator:265 - Reconciliation #34(timer) Kafka(osp-sbx-fb-customer-1/customer-1): Kafka customer-1 will be checked for creation or modification                                                   │
│ 2023-11-08 07:20:54 ERROR AbstractOperator:284 - Reconciliation #34(timer) Kafka(osp-sbx-fb-customer-1/customer-1): createOrUpdate failed                                                                                           │
│ java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because the return value of "java.util.Map.get(Object)" is null                                                                                            │
│     at io.strimzi.operator.cluster.operator.assembly.KafkaReconciler.lambda$perBrokerKafkaConfiguration$42(KafkaReconciler.java:657) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]                                               │
│     at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                                  │
│     at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                                  │
│     at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                                 │
│     at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                                │
│     at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                                  │
│     at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                         │
│     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                              │
│     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                          │
│     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                  │
│     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[io.netty.netty-transport-4.1.100.Final.jar:4.1.100.Final]                                                                                                     │
│     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                        │
│     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                                           │
│     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                               │
│     at java.lang.Thread.run(Thread.java:833) ~[?:?]                                                                                                                                                                                 │
│ 2023-11-08 07:20:54 WARN  AbstractOperator:557 - Reconciliation #34(timer) Kafka(osp-sbx-fb-customer-1/customer-1): Failed to reconcile                                                                                             │
│ java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because the return value of "java.util.Map.get(Object)" is null                                                                                            │
│     at io.strimzi.operator.cluster.operator.assembly.KafkaReconciler.lambda$perBrokerKafkaConfiguration$42(KafkaReconciler.java:657) ~[io.strimzi.cluster-operator-0.38.0.jar:0.38.0]                                               │
│     at io.vertx.core.impl.future.Composition.onSuccess(Composition.java:38) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                                  │
│     at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:60) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                                  │
│     at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:211) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                                 │
│     at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                                │
│     at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                                  │
│     at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54) ~[io.vertx.vertx-core-4.4.6.jar:4.4.6]                                                                                                         │
│     at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                              │
│     at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                          │
│     at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                  │
│     at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[io.netty.netty-transport-4.1.100.Final.jar:4.1.100.Final]                                                                                                     │
│     at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                        │
│     at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                                           │
│     at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.100.Final.jar:4.1.100.Final]                                                                               │
│     at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Here is the used configuration:

```yaml
resource "kubectl_manifest" "kafka_controller" {
  depends_on = [var.instance_ip]
  yaml_body = <<-EOF
  apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaNodePool
  metadata:
    name: controller
    namespace: ${kubernetes_namespace_v1.instance_namespace.metadata.0.name}
    labels:
      strimzi.io/cluster: ${var.instance_name}
  spec:
    replicas: 1
    roles:
      - controller
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 20Gi
          deleteClaim: false
EOF
}

resource "kubectl_manifest" "kafka_broker" {
  depends_on = [var.instance_ip]
  yaml_body = <<-EOF
  apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaNodePool
  metadata:
    name: broker
    namespace: ${kubernetes_namespace_v1.instance_namespace.metadata.0.name}
    labels:
      strimzi.io/cluster: ${var.instance_name}
  spec:
    replicas: 1
    roles:
      - broker
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
EOF
}

resource "kubectl_manifest" "kafka_instance" {
  depends_on = [var.instance_ip]
  yaml_body = <<-EOF
  apiVersion: kafka.strimzi.io/v1beta2
  kind: Kafka
  metadata:
    name: ${var.instance_name}
    namespace: ${kubernetes_namespace_v1.instance_namespace.metadata.0.name}
    annotations:
      strimzi.io/node-pools: enabled
      strimzi.io/kraft: enabled
  spec:
    clientsCa:
      generateCertificateAuthority: false
    kafka:
      image: ${var.container_image_registry_url}/strimzi:latest
      version: 3.6.0
      replicas: 1
      listeners:
        - name: external
          port: 9093
          type: loadbalancer
          tls: true
          authentication:
            type: tls
          configuration:
            bootstrap:
              annotations:
                "service.beta.kubernetes.io/azure-load-balancer-ipv4": ${var.instance_ip}
              loadBalancerIP: ${var.instance_ip}
            brokerCertChainAndKey:
              secretName: ${local.external_kafka_cert_secret_name}
              certificate: tls.crt
              key: tls.key
            finalizers: ["service.kubernetes.io/load-balancer-cleanup"]
        - name: internal
          port: 29093
          type: cluster-ip
          tls: true
          authentication:
            type: tls
          configuration:
            brokerCertChainAndKey:
              secretName: ${local.internal_kafka_cert_secret_name}
              certificate: tls.crt
              key: tls.key
      config:
        offsets.topic.replication.factor: 1
        transaction.state.log.replication.factor: 1
        transaction.state.log.min.isr: 1
        default.replication.factor: 1
        min.insync.replicas: 1
        inter.broker.protocol.version: "3.4"
        offsets.retention.minutes: 525600
        allow.everyone.if.no.acl.found: false
        auto.create.topics.enable: false
        principal.builder.class: com.custom.CustomKafkaPrincipalBuilder
      storage:
        type: jbod
        volumes:
        - id: 0
          type: persistent-claim
          size: 100Gi
          deleteClaim: false
      authorization:
        type: simple
        superUsers:
          - Applications:${local.app-id}
    zookeeper:
      replicas: 1
      storage:
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
EOF
}
```

### Steps to reproduce

- Install Strimzi via Helm chart
- Add yaml configuration to Kubernetes
- See Strimzi operator logs

### Expected behavior

Controller and broker will be cretaed and Kafka is available

### Strimzi version

0.38.0

### Kubernetes version

v1.26.6

### Installation method

Helm + yaml

### Infrastructure

Azure Kubernetes Service

### Configuration files and logs

Helm:

```yaml
resource "helm_release" "strimzi_kafka_operator" {
  depends_on = [kubernetes_namespace_v1.strimzi]
  name       = "${var.env_id}-strimzi"

  repository = "oci://quay.io/strimzi-helm"
  chart      = "strimzi-kafka-operator"
  version    = "0.38.0"

  namespace = kubernetes_namespace_v1.strimzi.metadata.0.name
  create_namespace = false

  set {
    name  = "watchAnyNamespace"
    value = "true"
  }

  set {
    name  = "featureGates"
    value = "+UseKRaft\\,+KafkaNodePools"
    type  = "string"
  }
}
```
