### ISSUE TITLE
Kafkaconnector authentication details to broker(Dont want to use kafkaconnect authentication details)

### ISSUE THREAD

**Issue by sai9920** [strimzi/strimzi-kafka-operator#9367]
### Discussed in https://github.com/orgs/strimzi/discussions/9366

<div type='discussions-op-text'>

<sup>Originally posted by **sai9920** November 20, 2023</sup>

**Issue Description:**
I am currently working with Kafka connectors and attempting to set individual authentication details at the Kafka connector level. I have noticed that even when incorrect credentials are provided in the Kafka connector manifest, the connector is still able to start successfully, indicating that the provided credentials are not being validated.

**Steps to Reproduce:**

*Provide a step-by-step guide on how to reproduce the issue.*

1. Define the connector configuration with specific authentication details.
2. Start the Kafka connector.
3. Observe that the connector starts successfully even with incorrect credentials.

*Describe what you expected to happen.*

I expected the Kafka connector to validate the provided authentication details and fail to start if incorrect credentials are provided.

*Explain what actually happened.*

The Kafka connector starts successfully even when incorrect credentials are provided.

**Configuration Used:**

```yaml
database.history.kafka.bootstrap.servers: .us-east-1.aws.confluent.cloud:9092
database.history.kafka.security.protocol: SASL_SSL
database.history.kafka.sasl.mechanism: PLAIN
database.history.kafka.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username=eds password=abc;
```

Please help if someone has tried it</div>
