### ISSUE TITLE
[KRaft] Mixed nodes cluster is not able to recover from misconfiguration affecting the whole cluster

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#9426]
Strimzi currently does not seem to be able to recover mixed-nodes KRaft cluster when it runs into some initial misconfiguration. This can be easily reproduced with the following steps:

1. Deploy new KRaft mixed-nodes cluster with misconfigured node affinity.
   For example, set the affinity to a non-existent zone:
   ```yaml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: topology.kubernetes.io/zone
                  operator: In
                  values:
                  - zone-1
   ```
2. The Pods should be all in the Pending state and the deployment should be failing. The reconciliation should fail after 5 minutes timeout as the pods never get ready.
3. Fix the affinity by using the correct zone or by removing it

**Expected result:**
* Operator rolls the nodes and fixes the cluster

**Actual result:**
* The operator tries to roll the first pod, but it never becomes ready and starts crash looping. Because of that it never moves on to the other nodes.

----

Some notable points:
* This might seem unimportant for a fresh deployment of misconfigured clusters as it can be just deleted and redeployed with a correct configuration. And the operator should not allow you to bring all pods to Pending by misconfiguring the Kafka cluster as it should not roll the next pod before the previous one got ready. However, there might be some situations this happens for existing clusters:
  * While the operator might not roll the next pod when the first one is pending, the pods might be deleted by some unrelated disaster and the new node affinity will be applied to them
  * You might have correctly configured the cluster, but lose the whole AZ to some disaster and you might need to reschedule the pods.
* This seems to have a workaround in manually deleting the pods
* This affects only mixed nodes. Dedicated controller nodes do not seem to be affected.
  * Does this indicate an issue in our readiness probes? Where the mixed nodes are stopped by us?
  * Or is this a Kafka issue where it exists the mixed node without waiting for the quorum to form?
  * It seems the second -> Kafka shutdowns. So to fix this in Strimzi only, we would need to detect situations like this and roll all controllers. Fix in Kafka would be certainly nicer.
* Most production clusters are expected to have a dedicated controller quorum, so they should not be affected. There is also a reasonably simple workaround. So this might not be a blocker to GA KRaft support?
