### ISSUE TITLE
[Bug]: entity-operator deployment can't set resources

### ISSUE THREAD

**Issue by tanberBro** [strimzi/strimzi-kafka-operator#9455]
### Bug Description

When I deploy a kafka instance, I find that the operator started entity-operator has no cpu, memory limit and requests,
And I didn't find how to set cpu, memory limit and requests in CRD.

### Steps to reproduce

kafka-instance.yaml
```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
spec:
  kafka:
    version: 3.4.0
    image: test/kafka:0.37.0-kafka-3.4.0
    authorization:
      type: simple
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
    resources:
      limits:
        cpu: 4
        memory: 4Gi
      requests:
        cpu: 2
        memory: 2Gi
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        deleteClaim: false
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 5Gi
      deleteClaim: false
    resources:
      limits:
        cpu: 2
        memory: 2Gi
      requests:
        cpu: 1
        memory: 1Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: kafka-topic
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-user
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      # Example consumer Acls for topic my-topic using consumer group my-group
      #      - resource:
      #          type: topic
      #          name: my-topic
      #          patternType: literal
      #        operations:
      #          - Describe
      #          - Read
      #        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - Read
        host: "*"
      # Example Producer Acls for topic my-topic
      - resource:
          type: topic
          name: kafka-topic
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
          - Read
        host: "*"
```

apply yaml

```shell
kubectl apply -f kafka-instance.yaml
```

### Expected behavior

Expect to be able to configure the entity-operator resources in the kafka-instance.yaml

### Strimzi version

0.37.0

### Kubernetes version

kubernetes 1.24.10

### Installation method

Helm Chart
