### ISSUE TITLE
[Bug]:  Topic operator pod cannot start due to Thread blocked 

### ISSUE THREAD

**Issue by sanit4u** [strimzi/strimzi-kafka-operator#9503]
### Bug Description

I am trying to deploy the strimzi kafka. 0.36.1 . The Kafka and Pods are running fine. However, the Entity operator is not in ready state. I have already tried to use the Zookeeper topic store, but it did not work out.

It would be great, if you could point me to some fix

### Expected Behaviour

Kafka Entity Operator should start successfully

### Steps to reproduce

Strimzi version used : 0.36.1

### Strimzi version

0.36.1

### Kubernetes version

k8s : v1.28.3

### Infrastructure

Azure AKS

Spec used:

````yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: *****-kafka-cluster
spec:
  kafka:
    template:
      pod:
        metadata:
          annotations:
            prometheus.io/port: "9404"
            prometheus.io/scrape: "true"
            sidecar.istio.io/inject: "false"
    version: 3.5.1
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: "INFO"
    resources:
      requests:
        memory: 6Gi
        cpu: "1"
      limits:
        memory: 6Gi
        cpu: "1.5"
    replicas: 1
    readinessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    livenessProbe:
      initialDelaySeconds: 15
      timeoutSeconds: 5
    jvmOptions:
      -Xms: 6g
      -Xmx: 6g
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
    config:
      auto.create.topics.enable: false
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: 3.5
      inter.broker.protocol.version: 3.5
    storage:
      type: jbod
      volumes:
        - id: 0
          class: managed-premium
          type: persistent-claim
          size: 64Gi
          deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: kafka-metrics-config.yml
  zookeeper:
    template:
      pod:
        metadata:
          annotations:
             prometheus.io/port: "9404"
             prometheus.io/scrape: "true"
             sidecar.istio.io/inject: "false"
    replicas: 1
    logging:
      type: inline
      loggers:
        zookeeper.root.logger: "INFO"
    resources:
      requests:
        memory: 4Gi
        cpu: "1"
      limits:
        memory: 4Gi
        cpu: "1.5"
    jvmOptions:
      -Xms: 4g
      -Xmx: 4g
    storage:
      type: persistent-claim
      class: managed-premium
      size: 32Gi
      deleteClaim: false
    metricsConfig:
      type: jmxPrometheusExporter
      valueFrom:
        configMapKeyRef:
          name: kafka-metrics
          key: zookeeper-metrics-config.yml
  entityOperator:
    template:
     # topicOperatorContainer:
     #   env:
     #   - name: STRIMZI_USE_ZOOKEEPER_TOPIC_STORE
     #     value: "true"
      pod:
        metadata:
          annotations:
              sidecar.istio.io/inject: "false"
    topicOperator: 
       resources:
         requests:
           memory: 1024Mi
           cpu: "2"
         limits:
           memory: 1024Mi
           cpu: "2"
      livenessProbe:
        periodSeconds: 60
        timeoutSeconds: 30
      readinessProbe:
        periodSeconds: 60
        timeoutSeconds: 30
    userOperator: 
       resources:
         requests:
           memory: 1024Mi
           cpu: "1"
         limits:
           memory: 1024Mi
           cpu: "1"
      livenessProbe:
        periodSeconds: 60
        timeoutSeconds: 30
      readinessProbe:
        periodSeconds: 60
        timeoutSeconds: 30
  kafkaExporter:
    template:
      pod:
        metadata:
          labels:
            app: ****-kafka-cluster-kafka-exporter
          annotations:
            prometheus.io/port: "9404"
            prometheus.io/scrape: "true"
            sidecar.istio.io/inject: "false"
    topicRegex: ".*"
    groupRegex: ".*"
    logging: debug
    resources:
      requests:
        memory: "128Mi"
        cpu: "300m"
      limits:
        memory: "256Mi"
        cpu: "600m"
    livenessProbe:
      periodSeconds: 15
      timeoutSeconds: 5
    readinessProbe:
      periodSeconds: 15
      timeoutSeconds: 5
```



[topic-operator.log](https://github.com/strimzi/strimzi-kafka-operator/files/13829775/topic-operator.log)
