### ISSUE TITLE
[Bug]: Unable to get MirrorMaker2 to create replicated topic in target cluster

### ISSUE THREAD

**Issue by ETisREAL** [strimzi/strimzi-kafka-operator#9576]
### Bug Description

First and foremost, thank you guys for this amazing project!

I've really been trying my head off to get MirrorMaker2 to work. I've gone through the documentation multiple times and looked at all the examples provided, but I just can't get it to work! :(

### Steps to reproduce

I am creating a source cluster in GKE with internal load balancers for each broker to be reachable by mirrormaker2:

``` yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka
spec:
  kafka:
    version: 3.6.1
    replicas: 3
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: secure
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
      - name: external
        port: 9094
        configuration:
          brokers:
            - broker: 0
              annotations:
                networking.gke.io/load-balancer-type: "Internal"
                networking.gke.io/internal-load-balancer-allow-global-access: "true" # to allow traffic across regions
            - broker: 1
              annotations:
                networking.gke.io/load-balancer-type: "Internal"
                networking.gke.io/internal-load-balancer-allow-global-access: "true" # to allow traffic across regions  
            - broker: 2
              annotations:
                networking.gke.io/load-balancer-type: "Internal"
                networking.gke.io/internal-load-balancer-allow-global-access: "true" # to allow traffic across regions  
          bootstrap:
            annotations:
              networking.gke.io/load-balancer-type: "Internal"
              networking.gke.io/internal-load-balancer-allow-global-access: "true" # to allow traffic across regions
        type: loadbalancer
        tls: false
        authentication:
          type: scram-sha-512
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.6"
      auto.create.topics.enable: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 4Gi
        deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 4Gi
      deleteClaim: true
  entityOperator:
    tlsSidecar: {}
    topicOperator: {}
    userOperator: {}
```

This is the target cluster:

``` yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-mirror
spec:
  kafka:
    version: 3.6.1
    replicas: 3
    authorization:
      type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: secure
        port: 9093
        type: internal
        tls: true
        authentication:
          type: scram-sha-512
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
      inter.broker.protocol.version: "3.6"
      auto.create.topics.enable: false
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 4Gi
        deleteClaim: true
  zookeeper:
    replicas: 3
    storage:
      type: persistent-claim
      size: 4Gi
      deleteClaim: true
  entityOperator:
    tlsSidecar: {}
    topicOperator: {}
    userOperator: {}
```

I am creating a user in the source cluster fot mirrormaker2:

``` yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kmm2-source-user
  labels:
    strimzi.io/cluster: kafka
    kafka-mirror-make: source
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations:
          - All
        host: "*"
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations:
          - All
        host: "*"
      - resource:
          type: cluster
        operations:
          - All
      - resource:
          type: transactionalId
          name: "*"
          patternType: literal
        operations:
          - All
```

I then retrieve the password and copied over to a secret in the target cluster:

``` bash
kubectl get secret kmm2-source-user -o jsonpath='{.data.password}'

# copied passsword in the source-cluster-user-secret.yaml under the password key

kubectl config use gke_k8s-409709_europe-west2-a_cluster-2

kubectl apply -f source-cluster-user-secret.yaml
```

I create a topic in the source cluster:

``` yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: mirrored-topic-two
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 4
  replicas: 2
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824
```

and finally I create mirrormaker2 in the target cluster

``` yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: kafka-mirror-maker2
spec:
  version: 3.6.1
  replicas: 1
  connectCluster: "cluster-target"
  resources:
    requests:
      cpu: 10m
      memory: 50Mi
    limits:
      cpu: 750m
      memory: 512Mi
  clusters:
  - alias: "cluster-source"
    bootstrapServers: 10.2.0.4:9094,10.2.0.5:9094,10.2.0.6:9094
    authentication:
      type: scram-sha-512
      username: kmm2-source-user
      passwordSecret:
        password: password
        secretName: source-cluster-user-secret
  - alias: "cluster-target"
    bootstrapServers: kafka-mirror-kafka-bootstrap.default.svc:9092
    authentication:
      type: scram-sha-512
      username: kmm2-target-user
      passwordSecret:
        password: password
        secretName: kmm2-target-user
  mirrors:
  - sourceCluster: "cluster-source"
    targetCluster: "cluster-target"
    topicsPattern: "mirrored-topic,"
```

As far as I can tell, I am doing everything correctly... MirrorMaker2 can actually connect successfully to both clusters (as the logs on the brokers on each cluster show the metadata topic for mirrormaker are getting created). Everything looks normal on MirrorMaker's logs as well:

```
 2024-01-20 17:07:59,802 INFO 192.168.124.16 - - [20/Jan/2024:17:07:59 +0000] "GET /connectors HTTP/1.1" 200 2 "-" "- │
│ " 3 (org.apache.kafka.connect.runtime.rest.RestServer) [qtp1761853129-20]                                            │
│ 2024-01-20 17:07:59,822 INFO 192.168.124.16 - - [20/Jan/2024:17:07:59 +0000] "GET /admin/loggers/ HTTP/1.1" 200 142  │
│ "-" "-" 2 (org.apache.kafka.connect.runtime.rest.RestServer) [qtp1761853129-19]                                      │
│ 2024-01-20 17:08:01,384 INFO 192.168.126.1 - - [20/Jan/2024:17:08:01 +0000] "GET / HTTP/1.1" 200 91 "-" "kube-probe/ │
│ 1.27" 3 (org.apache.kafka.connect.runtime.rest.RestServer) [qtp1761853129-22]
```

For reference, I tried using both the brokers endpoint and the bootsrapServer endpoint for the 'bootstrapServers' propery of the source cluster, but it didn't change anything.

Also, I produced records on the topic, and still the topic didn't even get created in the target cluster

As I said, everything starts without errors or anything, so I really don't know what else to try. Any help is very, very much appreciated.

Thank you in advance

### Strimzi version

0.39.0

### Kubernetes version

1.27.3-gke.100

### Installation method

Helm chart, yaml manifests

### Infrastructure

GKE
