### ISSUE TITLE
Not possibly to specify integer as annotation value anymore

### ISSUE THREAD

**Issue by scholzj** [strimzi/strimzi-kafka-operator#9625]
It seems that after #9508, where we modified our CRDs to use `additionalProperties` instead of `x-kubernetes-preserve-unknown-fields`, we have some backward compatibility issues. With the old CRDs, the following example:

```yaml
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: my-bridge
spec:
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap:9093
  http:
    port: 8080
  template:
    apiService:
      metadata:
        annotations:
          discovery.myapigateway.io/port: 8080
```

Worked fine and resulted in a Service with annotation having the value `8080`. While annotations allow only String values, the old CRD passed the Integer to Strimzi where (likely Jackson FasterXML on its own) converted it to String. So everything works fine even with an Integer value.

But now it fails with the following error:

```
# kafkabridges.kafka.strimzi.io "my-bridge" was not valid:
# * spec.template.apiService.metadata.annotations.discovery.myapigateway.io/port: Invalid value: "integer": spec.template.apiService.metadata.annotations.discovery.myapigateway.io/port in body must be of type string: "integer"
```

To make this configuration work with the new CRD, one has to change the value to be string:

```yaml
  template:
    apiService:
      metadata:
        annotations:
          discovery.myapigateway.io/port: "8080"
```

We have to decide how do we want to proceed with this. On one hand:
* We did this change because it improves the experience for some users
* Annotations have only String as a valid value. So if you specify annotation in the actual resource metadata, an integer value would fail as well.

On the other hand, this is a backward compatibility issue and could cause problems to users who have previously working integer values.
