### ISSUE TITLE
[Enhancement]: Downwards API for dynamic env variables in Kafka connect

### ISSUE THREAD

**Issue by xontab** [strimzi/strimzi-kafka-operator#9684]
### Related problem

I would like to set up environment variables for OTEL in Kafka Connect.  However since the OTEL agent is configured in daemonset mode, usually the environment variable for the OTLP endpoint is configured using the [Downwards API](https://kubernetes.io/docs/concepts/workloads/pods/downward-api/) such as the following example:

```
      env:
         - name: NODE_IP
           valueFrom:
             fieldRef:
               fieldPath: status.hostIP
         - name: OTEL_EXPORTER_OTLP_ENDPOINT
           value: "http://$(NODE_IP):4317"
         - name: OTEL_SERVICE_NAME
           value: kafka-connect
```
After investigating the KafkaConnect CRD, it looks like only static environment variables are supported.  Reference https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/cluster-operator/041-Crd-kafkaconnect.yaml#L948-L961

### Suggested solution

Is it possible to achieve something similar with the existing KafkaConnect CRD and setup?  If not, the suggestion is to add Downwards API support in the `connectContainer` environment variables by propagating the `fieldRef`s when creating the Kafka connect pod.
