### ISSUE TITLE
Creating Kafka topic with standalone Topic Operator

### ISSUE THREAD

**Issue by Ihjaz** [strimzi/strimzi-kafka-operator#971]
Hi,

What should be the label used when creating a kafka topic with standalone Topic Operator?

If I use the name of my kubernetes cluster which is not created using Cluster Operator then topic operator is not picking it up.

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: mytopic
  labels:
    strimzi.io/cluster: kubernetes
```
I saw that the label used for topics created outside the operator is "strimzi.io/kind: topic".
If I use the label as "strimzi.io/kind: topic" then topic operator is getting notified and creating the topic but I see the topic operator pod restarting when I delete the topic.

```
apiVersion: kafka.strimzi.io/v1alpha1
kind: KafkaTopic
metadata:
  name: mytopic
  labels:
    strimzi.io/kind: topic
```

Is the Topic operator restarting because I'm using this label ? What is the right label to use if the cluster is not created using a Cluster Operator?
