### ISSUE TITLE
[Bug]: Overriding pod label `app.kubernetes.io/instance` no longer works with 0.37.0

### ISSUE THREAD

**Issue by erikdahmen** [strimzi/strimzi-kafka-operator#9735]
### Bug Description

We override pod labels using

```
spec:
  entityOperator:
    template:
      pod:
        metadata:
          labels:
            app.kubernetes.io/instance: custom
  kafka:
    template:
      pod:
        metadata:
          labels:
            app.kubernetes.io/instance: custom
  zookeeper:
    template:
      pod:
        metadata:
          labels:
            app.kubernetes.io/instance: custom
```

in `Kafka` custom resource. This worked without issues with Strimzi operator up to 0.33.2.

After updating to 0.37.0 these overrides are ignored. The `app.kubernetes.io/instance` label for all pods is now set to the cluster name:

```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: cluster-name
```

### Steps to reproduce

1. Use Strimzi operator 0.33.2
2. Apply above values to the kafka custom ressource
3. Check pods labels and find `app.kubernetes.io/instance: custom`
4. Update Strimzi operator to 0.37.0
5. Wait until reconciliation finishes
6. Check pods labels and find `app.kubernetes.io/instance: cluster-name`

### Expected behavior

Either overriding this label should work or documentation should be improved to state which labels cannot be overridden.

### Strimzi version

0.37.0

### Kubernetes version

Kubernetes 1.25

### Installation method

Helm chart

### Infrastructure

Amazon EKS

### Additional context

Strimzi operator is deployed with default values except `watchAnyNamespace: true`
