### ISSUE TITLE
[Bug]: standalone user-operator not working

### ISSUE THREAD

**Issue by sebastiangaiser** [strimzi/strimzi-kafka-operator#9740]
### Bug Description

Hey, 

I tried to connect with mTLS enabled to a Kraft Kafka cluster from a standalone user-operator deployed in a different Kubernetes cluster. 
For this I used the same cluster and clients CAs for the cluster and the standalone user-operator.
For the deployment of the standalone user-operator I used the guide from https://strimzi.io/docs/operators/latest/deploying.html#deploying-the-user-operator-standalone-str and found the deployment itself here https://github.com/strimzi/strimzi-kafka-operator/blob/main/install/user-operator/05-Deployment-strimzi-user-operator.yaml , too.
Apparently when I start the standalone user-operator I get the following error message:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "src" is null
	at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
	at io.strimzi.operator.common.Util.decodeFromSecret(Util.java:166)
	at io.strimzi.operator.common.DefaultAdminClientProvider.createAdminClient(DefaultAdminClientProvider.java:58)
	at io.strimzi.operator.user.Main.createAdminClient(Main.java:148)
	at io.strimzi.operator.user.Main.main(Main.java:80)
```

The following environment variables are added in the standalone user-operator deployment:
```
        - name: STRIMZI_NAMESPACE
        - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
        - name: STRIMZI_LABELS
        - name: STRIMZI_CA_CERT_NAME
        - name: STRIMZI_CA_KEY_NAME
        - name: STRIMZI_ACLS_ADMIN_API_SUPPORTED
        - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
        - name: STRIMZI_LOG_LEVEL
        - name: STRIMZI_GC_LOG_ENABLED
        - name: STRIMZI_CA_VALIDITY
        - name: STRIMZI_CA_RENEWAL
        - name: STRIMZI_SECRET_PREFIX
        - name: STRIMZI_CLUSTER_CA_CERT_SECRET_NAME
        - name: STRIMZI_EO_KEY_SECRET_NAME
```

### Steps to reproduce

1. deploy mTLS cluster
2. deploy standalone user-operator and try to connect

### Expected behavior

standalone user-operator can start

### Strimzi version

0.39.0

### Kubernetes version

Kubernetes 1.28

### Installation method

Helm chart + YAMLs

**Comment by scholzj** [comment]
I guess you misconfigured something? Maybe sharing the actual deployment might be a good start. You should also explain what secrets you have, in which namespaces and what structure they have.

**Comment by sebastiangaiser** [comment]
I played a bit around but still get the same error for the user-operator.

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cluster-user-operator
  namespace: kafka
  labels:
    app.kubernetes.io/app: my-cluster
    app.kubernetes.io/name: user-operator
    strimzi.io/cluster: my-cluster
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-user-operator
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: my-cluster
      strimzi.io/kind: Kafka
      strimzi.io/name: my-cluster-user-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/app: my-cluster
        app.kubernetes.io/name: user-operator
        strimzi.io/cluster: my-cluster
        strimzi.io/kind: Kafka
        strimzi.io/name: my-cluster-user-operator
    spec:
      serviceAccountName: my-cluster-user-operator
      volumes:
        - name: strimzi-to-tmp
          emptyDir:
            medium: Memory
            sizeLimit: 5Mi
        - configMap:
            defaultMode: 420
            name: my-cluster-user-operator-config
          name: user-operator-metrics-and-logging
      containers:
        - name: user-operator
          image: quay.io/strimzi/operator:0.39.0
          args:
            - /opt/strimzi/bin/user_operator_run.sh
          volumeMounts:
            - mountPath: /tmp
              name: strimzi-to-tmp
            - mountPath: /opt/user-operator/custom-config/
              name: user-operator-metrics-and-logging
          env:
            - name: STRIMZI_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STRIMZI_KAFKA_BOOTSTRAP_SERVERS
              value: private-bootstrap-my-cluster.example.com:30106
            - name: STRIMZI_LABELS
              value: "strimzi.io/cluster=my-cluster"
            - name: STRIMZI_CA_CERT_NAME
              value: my-cluster-clients-ca-cert
            - name: STRIMZI_CA_KEY_NAME
              value: my-cluster-clients-ca
            - name: STRIMZI_ACLS_ADMIN_API_SUPPORTED
              value: "true"
            - name: STRIMZI_FULL_RECONCILIATION_INTERVAL_MS
              value: "120000"
            - name: STRIMZI_LOG_LEVEL
              value: INFO
            - name: STRIMZI_GC_LOG_ENABLED
              value: "true"
            - name: STRIMZI_CA_VALIDITY
              value: "365"
            - name: STRIMZI_CA_RENEWAL
              value: "30"
            - name: STRIMZI_SECRET_PREFIX
              value: "my-cluster-"
            - name: STRIMZI_CLUSTER_CA_CERT_SECRET_NAME
              value: my-cluster-cluster-ca-cert
            - name: STRIMZI_EO_KEY_SECRET_NAME
              value: my-cluster-cluster-ca
            - name: STRIMZI_KAFKA_ADMIN_CLIENT_CONFIGURATION
              value: |
                default.api.timeout.ms=120000
                request.timeout.ms=60000
          ports:
            - containerPort: 8081
              name: healthcheck
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthy
              port: healthcheck
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /ready
              port: healthcheck
              scheme: HTTP
```

For the cluster itself, the two CAs for cluster and clients were originally created via cert-manager using a self-signed CA. Afterwards I extracted the `tls.key` part in the `my-cluster-clients-ca-tls`, `tls.crt` + `ca.crt` into `my-cluster-clients-ca-cert`. Did same for the cluster CA and used the same Kubernetes secrets for the cluster (which is running fine) itself and the user-operator. 
Probably I'm doing something wrong with the CAs...
