### ISSUE TITLE
[Docs]: example for dual role kraft nodes does not work

### ISSUE THREAD

**Issue by mateuszkwiatkowski** [strimzi/strimzi-kafka-operator#9750]
### Suggestion / Problem

I tried to deploy cluster that is described in dual role kraft nodes documentation but it failed with error:
```
2024-02-28 13:40:16 INFO  AbstractOperator:265 - Reconciliation #1459(timer) Kafka(kafka-cluster-etl-rvapp-test/kafka-cluster): Kafka kafka-cluster will be checked for creation or modification
2024-02-28 13:40:17 ERROR AbstractOperator:284 - Reconciliation #1459(timer) Kafka(kafka-cluster-etl-rvapp-test/kafka-cluster): createOrUpdate failed
io.strimzi.operator.common.model.InvalidResourceException: The Kafka cluster kafka-cluster is invalid: [KafkaNodePool kafka-cluster contains invalid roles configuration. In a ZooKeeper-based Kafka cluster, the KafkaNodePool role has to be always set only to the 'broker' role.]
```
Here's template that I used to deploy the cluster:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.k8s.namespace }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: {{ template "kafka-cluster.name" . }}
  labels:
    strimzi.io/cluster: {{ template "kafka-cluster.name" . }}
spec:
  replicas: {{ .Values.kafka.replicas }}
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        class: {{ .Values.kafka.storage.className }}
        type: persistent-claim
        size: 20Gi
        deleteClaim: {{ .Values.kafka.storage.deleteClaim }}
---
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{ template "kafka-cluster.name" . }}
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: {{ .Values.kafka.version}}
    metadataVersion: 3.6-IV2
    # The replicas field is required by the Kafka CRD schema while the KafkaNodePools feature gate is in alpha phase.
    # But it will be ignored when Kafka Node Pools are used
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
        authentication:
          type: tls
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      default.replication.factor: 3
      min.insync.replicas: 2
    template:
      pod:
        metadata:
          annotations:
            ad.datadoghq.com/kafka.check_names: '["kafka"]'
            ad.datadoghq.com/kafka.init_configs: '[{is_jmx: true, collect_default_metrics: true}]'
            ad.datadoghq.com/kafka.instances: '[{"host": "%%host%%", "port": "%%port%%"}]'
            ad.datadoghq.com/kafka.logs: '[{"source": "kafka", "service": "kafka"}]'
    authorization:
      type: simple
      superUsers: ["CN=kafkaui"]
    # The storage field is required by the Kafka CRD schema while the KafkaNodePools feature gate is in alpha phase.
    # But it will be ignored when Kafka Node Pools are used
    storage:
      type: jbod
      volumes:
      - id: 0
        class: {{ .Values.kafka.storage.className }}
        type: persistent-claim
        size: {{ .Values.kafka.storage.size }}
        deleteClaim: {{ .Values.kafka.storage.deleteClaim }}
  entityOperator:
    userOperator: {}
```

### Documentation Link

https://github.com/strimzi/strimzi-kafka-operator/blob/main/examples/kafka/nodepools/kafka-with-dual-role-kraft-nodes.yaml
