### ISSUE TITLE
unable to connect kafka broker from nginx controller ingress

### ISSUE THREAD

**Issue by sagarshrestha24** [strimzi/strimzi-kafka-operator#9778]
### Discussed in https://github.com/orgs/strimzi/discussions/9777

<div type='discussions-op-text'>

<sup>Originally posted by **sagarshrestha24** March  5, 2024</sup>
Please help me to configure kafka cluster where i have to use scram-sha-512 authentication and kafka endpoint using ingress

i have tested from this cluster.yaml
```
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: strimzi-kafka-cluster
  namespace: kafka
spec:
  kafka:
    jvmOptions:
      -Xms: 2G
      -Xmx: 5G
    replicas: 1
    authorization:
     type: simple
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
        authentication:
          type: scram-sha-512
      - name: tls
        port: 9093
        type: internal
        tls: true
      - configuration:
          brokers:
          - broker: 0
            advertisedHost: kafka-broker-0.xxxx.com.np
            advertisedPort: 9097
        name: external
        port: 9094
        authentication:
          type: scram-sha-512
        tls: true
        type: cluster-ip
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        deleteClaim: false
    config:
      sasl.enabled.mechanisms: scram-sha-512
      sasl.mechanism.inter.broker.protocol: scram-sha-512
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.5.1"
      replica.fetch.max.bytes: 1048576
  zookeeper:
    jvmOptions:
      -Xms: 1G
      -Xmx: 2G
    replicas: 1
    storage:
      type: persistent-claim
      size: 20Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
  ```  
    
    but there is issue tls handshake while connecting from client</div>
