### ISSUE TITLE
[Bug]: kubeconform validation fails for kafka crd

### ISSUE THREAD

**Issue by abrarshivani** [strimzi/strimzi-kafka-operator#9823]
### Bug Description

When configuring a Kafka listener with the type set to cluster-ip, overrides for the bootstrap service may not be necessary, but they may still be required for brokers. This results in the following listener configuration:
```
      - name: external
        port: 9095
        type: cluster-ip
        tls: true
        authentication:
          type: tls
        configuration:
          bootstrap: {}
          brokers:
          - broker: 0
            host: broker-0.domain.com
          - broker: 1
            host: broker-1.domain.com
          - broker: 2
            host: broker-2.domain.com
```
When validating this CRD with kubeconform, an error is encountered: kubeconform expected object, but got null. Additionally, the CRD needs to be adjusted since the bootstrap value can indeed be null. This issue can be resolved by adding the following property for the bootstrap configuration in the Kafka CRD:
```
nullable: true
```

### Steps to reproduce

1. Use script https://github.com/yannh/kubeconform/blob/master/scripts/openapi2jsonschema.py to generate schema:
`python3 openapi2jsonschema.py <path_to_openapi_crd>.yaml`
2. Use kubeconform to validate crd against the schema generated:
`kubeconform -kubernetes-version 1.22.0 -strict -schema-location <dir_to_openapi_crd>/{{.ResourceKind}}{{.KindSuffix}}.json '<path-to-crd>`

### Expected behavior

Kubeconform should not return error: `expected object, but got null`

### Strimzi version

0.34.0

### Kubernetes version

v1.24.17

### Installation method

Helm Chart

### Infrastructure

EKS
