### ISSUE TITLE
[Bug]: MM2: Incorrect setting of connectCluster might cause infinite echo when IdentityReplicationPolicy is used

### ISSUE THREAD

**Issue by maakuth** [strimzi/strimzi-kafka-operator#9905]
### Bug Description

In MirrorMaker2, you [must](https://strimzi.io/docs/operators/latest/configuring#type-KafkaMirrorMaker2Spec-reference) have the connectCluster setting to point to the same cluster alias as targetCluster in the defined mirrors. When connectCluster is pointing to sourceCluster instead, I would expect MM2 to not start.

With default replication policy, a growing number of topics is created in the cluster set as connectCluster and mirror sourceCluster, with the cluster alias prefixed again and again:
```
kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.kafka1.heartbeats
```

When replication policy is set to IdentityReplicationPolicy, this causes local echoing, with the source cluster (also configured as connectCluster) getting overrun by recurring mirrored copies of the messages from itself. 

This is incorrect configuration, so it is not a critical bug. However, it is a mistake I myself did with my local lab configuration and it has a potential of corrupting data in the source cluster in a way that's not trivial to recover from.

### Steps to reproduce

Deploy a Strimzi KafkaMirrorMaker2 with connectCluster set to the same value as mirror sourceCluster.

### Expected behavior

If connectCluster is not the same as mirror targetCluster, the correct thing to do would be to not start the MM2 at all.

### Strimzi version

0.40.0

### Kubernetes version

v1.28.3 (minikube v1.32.0)

### Installation method

Helm via ArgoCD

### Configuration files and logs

```
  apiVersion: kafka.strimzi.io/v1beta2
  kind: KafkaMirrorMaker2
  metadata:
    name: mm2-kafka2kafka
  spec:
    connectCluster: "kafka1"
    replicas: 1
    clusters:
    - alias: "kafka1"
      bootstrapServers: my-cluster-kafka-bootstrap.strimzi:9092
    - alias: "kafka2"
      bootstrapServers: my-cluster2-kafka-bootstrap.strimzi:9092
      config:
        offset.storage.topic: mirrormaker2-cluster-offsets
        status.storage.topic: mirrormaker2-cluster-status
        config.storage.topic: mirrormaker2-cluster-configs
        group.id: mirrormaker2-cluster
        replication.factor: 1
        status.storage.replication.factor: 1
        config.storage.replication.factor: 1
        offset.storage.replication.factor: 1
    mirrors:
    - sourceCluster: "kafka1"
      targetCluster: "kafka2"
      heartbeatConnector:
        config:
          # Internal topic 'heartbeats' created at the target cluster
          heartbeats.topic.replication.factor: 3
      sourceConnector:
        tasksMax: 1
        config:
          # -1 means it will use the default replication factor configured in the broker
          replication.factor: -1
          offset-syncs.topic.replication.factor: -1
          sync.topic.acls.enabled: "false"
          replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
          refresh.topics.interval.seconds: 600
      checkpointConnector:
        tasksMax: 1
        config:
          # -1 means it will use the default replication factor configured in the broker
          checkpoints.topic.replication.factor: -1
          replication.policy.class: "io.strimzi.kafka.connect.mirror.IdentityReplicationPolicy"
          sync.group.offsets.enabled: "false"
          refresh.groups.interval.seconds: 600
      topicsPattern: ".*"
      groupsPattern: ".*"
```
