### ISSUE TITLE
[Enhancement]: Extend Kafka CRD to configure the jmxOptions for the remaining workloads

### ISSUE THREAD

**Issue by jakubmalek** [strimzi/strimzi-kafka-operator#9949]
### Related problem

Right now Kafka CRD provides a way to configure the `jmxOptons` to enable JMX endpoint with or without authentication on port 9999.
This option is missing however for the remaining workloads like user-operator, topic-operator and cruise-control.
This is not that big of a problem, as its still possible to enable the JMX with the environment variable e.g.:

```yaml
env:
  - name: KAFKA_JMX_OPTS
    value: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.port=9999 -Dcom.sun.management.jmxremote.rmi.port=9999 -Djava.rmi.server.hostname=127.0.0.1
```

Nevertheless, if you want enable the authentication, and generate username/password, similarly to what Strimzi does for Kafka and Zookeeper, it requires additional effort.

### Suggested solution

Extend the OpenAPI for Kafka CRD to add reference to the `jmxOptions` configuration with its support in the operator.

### Alternatives

The other alternative is to enable it in the environment variables manually, but as described, it requires some effort to configure authentication with generated secrets.
